### ISSUE TITLE
Easy font size change

### ISSUE THREAD

**Issue by dzialeczko** [filebrowser/filebrowser#1004]
Easy font size change.
Example:
<img width="487" alt="filebrowser_font1" src="https://user-images.githubusercontent.com/53253501/85543210-238bf080-b61a-11ea-9c61-dd5f7f3b27ea.png">

**Comment by o1egl** [comment]
Can you please give more context what problem and how do you propose to solve.

**Comment by dzialeczko** [comment]
I do not know. The easiest way is to change the browser zoom or change the browser font size.

**Comment by o1egl** [comment]
Sorry, but I don’t quite understand what font size are you talking about? The whole page? If yes, then I don't think that it would be a good idea from UI/UX perspective.

**Comment by princemaple** [comment]
Browser zoom in/out is probably the best solution :)
