### ISSUE TITLE
stuck in login page keep loading while using nginx 

### ISSUE THREAD

**Issue by mphz** [filebrowser/filebrowser#1006]
I am using centos 7 on my VPS, use the curl get.sh to install filebrowser, and the filebrowser service running everything looks good. And I have an nginx which location /filebrowser to the filebrowser port, the port also got firewalld opened which I can confirm. The only issue is while using the internet to visit my domain/filebrowser, I can only see three dots loading, and always...

**Comment by o1egl** [comment]
Try to run it with `--baseurl /filebrowser` param

**Comment by yurividal** [comment]
Works for me like this, on my nginx config file:

> `

	    location /files/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://127.0.0.1:8086/;
       }
 `
Obviously, adapt the location and the port for your environment.
Also had to set the base url to /files in the config.

**Comment by rudxde** [comment]
For me the problem was, that i had set an Content-Security-Policy header, which blocked the javascript eval.  After adding the following header everythig worked fine:

```
Content-Security-Policy "script-src 'self' 'unsafe-eval' 'unsafe-inline'"
```
