### ISSUE TITLE
PDF preview

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#1008]
**Is your feature request related to a problem? Please describe.**
No just a nice to have. Would be great to be able to preview pdfs just like images.

**Describe the solution you'd like**
Not sure about the solution. I'm not a go programmer. Is there any library that could do it?

**Describe alternatives you've considered**
N/A

**Additional context**
Just want to thank the maintainers & contributors for the recent 2.2 and 2.3 release, they are great.
This issue itself is less important 😉

**Comment by o1egl** [comment]
Just tested in Chrome and Firefox that pdf preview works as expected.

**Comment by princemaple** [comment]
Meant as a logo, though.
