### ISSUE TITLE
can't create a new file

### ISSUE THREAD

**Issue by fghhfg** [filebrowser/filebrowser#101]
win7 64bit

**In content folder, the circle on the right-bottom won't stop. This green circle just rotate, rotate... and never stop!**

![2017-01-13 12_01_42-content](https://cloud.githubusercontent.com/assets/1284845/21918186/aeca5d10-d989-11e6-946a-a4f5ce5583a4.png)

![2017-01-13 12_03_26-cmder](https://cloud.githubusercontent.com/assets/1284845/21918188/b410cade-d989-11e6-9c40-17b47960e272.png)

my caddyfile:
```
localhost:8080
root      public           # the folder where Hugo generates the website
basicauth /admin user pass # protect the admin area using HTTP basic auth
hugo                       # enable the admin panel
```

---

restart and run again, it still doesn't work:

![2017-01-13 12_18_59- _ windows powershell](https://cloud.githubusercontent.com/assets/1284845/21918258/7cec1080-d98a-11e6-9a7a-7bd4b851431e.png)

---

It can create files on anywhere except content directory...

![2017-01-13 13_34_40-content](https://cloud.githubusercontent.com/assets/1284845/21919397/fa552b1a-d994-11e6-82ac-f33d39dd1070.png)

What should I type in this text box?

---

**and How do I enter here?**

![](https://caddyserver.com/resources/images/middleware/hugo.png)

All I saw is this:

![2017-01-13 14_08_06-dd md](https://cloud.githubusercontent.com/assets/1284845/21920053/a736ffd0-d999-11e6-91d0-8b5faa7fd405.png)

**Comment by fghhfg** [comment]
https://gohugo.io/overview/quickstart/

**Comment by hacdias** [comment]
Hello @fghhfg! Do you still need help?

**Comment by fghhfg** [comment]
No, thx. If someone has same problem, check link    https://gohugo.io/overview/quickstart/

Anyone who wants to use this program needs to know some Hugo knowledge.

**Comment by hacdias** [comment]
Yup :) hope you enjoy it!
