### ISSUE TITLE
404 when downloading for windows

### ISSUE THREAD

**Issue by ReactiveSlime** [filebrowser/filebrowser#1010]
**Description**
download for windows not working

**Expected behavior**
for it to download

**What is happening instead?**
iwr : The remote server returned an error: (404) Not Found.

**How to reproduce?**
download for windows

**Comment by ramiresviana** [comment]
Can you give more details about your problem? What you are trying to download and from what server?

**Comment by ReactiveSlime** [comment]
i was following this guide for windows
https://filebrowser.org/installation

**Comment by ramiresviana** [comment]
Thanks for you report, this need to be fixed. To proceed with the installation you can replace the link of the script with https://raw.githubusercontent.com/filebrowser/get/master/get.ps1

@o1egl Installation script for windows is unavailable at https://filebrowser.org/get.ps1.

**Comment by o1egl** [comment]
Fixed. Thanks for the report!
