### ISSUE TITLE
Minimum TLS Version

### ISSUE THREAD

**Issue by bischsn** [filebrowser/filebrowser#1013]
Bonjour, 

Tout d'abord, merci de votre travail. 
L'outil Filebrowser est vraiment simple d'utilisation et d'installation ce qui nous convient parfaitement. 

Nous avons une fonctionnalité à proposer au niveau de la sécurité SSL HTTP. 
Est-ce possible d'implémenter une configuration permettant de forcer l'utilisation minimum d'une version de TLS (1.2, 1.3 etc ...) ? 

A disposition si besoin.

**Comment by o1egl** [comment]
Hi @bischsn , you can use `--cert` and `--key` flags to use ssl certificate
