### ISSUE TITLE
Allow username/password configuration in docker based setup

### ISSUE THREAD

**Issue by everflux** [filebrowser/filebrowser#1016]
**Is your feature request related to a problem? Please describe.**
I would like to deploy filebrowser as docker container in a safe way by preconfiguring a user.

**Describe the solution you'd like**
I would like a way through docker environment or command line parameter to provide username/password for a static user instead of the default admin/admin.

**Describe alternatives you've considered**
Add a reverse proxy with basic auth leading to a more complex solution.

**Comment by everflux** [comment]
Actually this is in place, but easy to miss when skimming through the documentation.
Perhaps a second docker-run example for quick setup with specified password (to be generated with `filebrowser hash`) would help others as well.

**Comment by zhogov** [comment]
For anyone else looking for a solution:

Generate hash from your password
```
docker run --rm filebrowser/filebrowser hash mypassword
$2a$10$JpE8CfN8p5zOxTa6GdL71.RuQL2efPu3l6P6jWWCB7NgMq1DAfYgS
```
Run your filebrowser with default password:
```
docker run --rm filebrowser/filebrowser --password '$2a$10$JpE8CfN8p5zOxTa6GdL71.RuQL2efPu3l6P6jWWCB7NgMq1DAfYgS'
```
