### ISSUE TITLE
File Browser 2.4.0 CentOS 8 filebrowser.service Can't start automatically at boot

### ISSUE THREAD

**Issue by LsnmxNB** [filebrowser/filebrowser#1019]
filebrowser.service

[Unit]
Description=File Browser
After=network.target

[Service]
ExecStart=/usr/local/bin/filebrowser -d /etc/filebrowser.db

[Install]
WantedBy=multi-user.target

[root@server ~]# systemctl is-enabled filebrowser.service
enabled

**Comment by o1egl** [comment]
Which error you get in logs? Can you try to run another binary with the same config on the same port? You can try to run nginx for example.

**Comment by LsnmxNB** [comment]
> Which error you get in logs? Can you try to run another binary with the same config on the same port? You can try to run nginx for example.

Hello, manual execution of systemctl start filebrowser.service can be started normally, that is, set to automatically start the life and death can not automatically run filebrowser

**Comment by o1egl** [comment]
- Which error you get in logs?
- Can you try to run another binary with the same service config on the same port? nginx for example.

I do not think this problem is related to filebrowser.
