### ISSUE TITLE
flag parsing is not working properly

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#102]
Hi

When reading this config:
```
http://domain.com {
  tls email@example.com
  root /www/site/public
  gzip
  log /var/log/www/site.log
  errors /var/log/www/site.err.log
  basicauth /admin email@example.com password
  hugo /www/site/hugo /admin {
    flag destination /www/site/public
    allow_new true
    allow_edit true
  }
}
```
the value of **flag destination** is *always* set to "true" and the site is published to /www/site/hugo/true on startup.

Caddy 0.9.4

**Comment by hacdias** [comment]
Hello @AstonDavies,

Can you try replacing ```/www/site/public``` for ```"/www/site/public"```. Anyway, I'll try to reproduce this as soon as I can.

**Comment by AstonDavies** [comment]
Hi @hacdias 

I have tried with quotes and also with extra parameters after the path. All results are the same.

I have had a look in the source and it's may be because line 130 should check >= rather than just >
```
			case "flag":
				if !c.NextArg() {
					return cfg, &filemanager.FileManager{}, c.ArgErr()
				}

				values := strings.Split(c.Val(), " ")

				if len(values) == 0 {
					return cfg, fm, errors.New("Not enough arguments for 'flag' option.")
				}

				value := "true"

				if len(values) > 1 {
					value = values[1]
				}

				cfg.Args = append(cfg.Args, "--"+values[0]+"="+value)
```
I'm not sure as I don't have it setup to compile from source, but I could get organised and try it if that would help.

Thanks

**Comment by hacdias** [comment]
Hey @AstonDavies!

Thanks for your insight! 😄 It's fixed.
