### ISSUE TITLE
Shared Folders Should Show Folder Contents

### ISSUE THREAD

**Issue by naclander** [filebrowser/filebrowser#1023]
**Is your feature request related to a problem? Please describe.**
Shared folders currently only show download link and QR code

**Describe the solution you'd like**
Like Dropbox, Nextcloud, and many other sharing folder services, the main view should be a file list,
with the option of downloading the entire folder as a zip archive as secondary.

**Describe alternatives you've considered**
Being sad.

**Additional context**
Sharing folders ( and nested folders ) has the added benefit of treating the shared folder as a public ftp/mirror.

**Comment by tionis** [comment]
I second this issue, this would make folder sharing way more dynamic and useful

**Comment by dantebarba** [comment]
+1

**Comment by h3r** [comment]
+1

**Comment by naclander** [comment]
Haven't done any vue before, but when trying to tackle this I figured I would:

import `listing` into the `Share.vue` file. 
Include the `<listing></listing> tag into the `Share.vue` template.

And something should happen. However, I'm getting some errors and the listing tag doesn't seem to get populated with anything. I'm guessing this is happening because the url path in the `Files.vue` page is an actual path, while in the `Share.vue` page it is a hash. And so maybe the file listing then can't figure out the list of files to display. Not really sure, any help would be appreciated.
