### ISSUE TITLE
Docker image for arm devices

### ISSUE THREAD

**Issue by hibare** [filebrowser/filebrowser#1024]
**Is your feature request related to a problem? Please describe.**
Current docker image available on docker hub won;t work on arm devices such as raspberry pi

**Describe the solution you'd like**
Docker hub image should run on arm devices

**Comment by o1egl** [comment]
You can use filebrowser/filebrowser:pi image to run it on raspberry pi.

**Comment by hibare** [comment]
Tried but it did not run

**Comment by o1egl** [comment]
This image is currently running on my raspberry pi 4.

**Comment by o1egl** [comment]
Which version of raspberry do you have?
