### ISSUE TITLE
I Created a Dark Theme

### ISSUE THREAD

**Issue by yurividal** [filebrowser/filebrowser#1025]
Hi. Just wanted to share this theme for filebrowser with you, maybe you want to check it out.
Its a better dark theme.
https://github.com/yurividal/filebrowserdarktheme

**Comment by mishailovic** [comment]
Beautiful! Already got my star. Much better than stock dark theme

**Comment by ramiresviana** [comment]
Thank you for the contribution, looks like i made a mistake on the current dark theme colors. I will revisit the material design guidelines to make it better.

**Comment by dantebarba** [comment]
+1 if it could be merged.
