### ISSUE TITLE
Error while copying files

### ISSUE THREAD

**Issue by jamolina5** [filebrowser/filebrowser#1027]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?
When I copy a file I get an error object object. See screenshot: https://lnkk.me/5zuXkZZ8
**Expected behaviour**
What did you expect to happen?
Copy the file and report no error

**What is happening instead?**
Please, give full error messages and/or log.
Error https://lnkk.me/5zuXkZZ8. Although the file seemed to be there in the copied directory
**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Im running a linux dedicated server using file browser
**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.
File is 14GB. But happens to every large file.

**Comment by o1egl** [comment]
Can you please share an error from server logs and actual http response? You can track http requests/responses by opening network tab in the browser development tool.
