### ISSUE TITLE
Account space limit

### ISSUE THREAD

**Issue by mishailovic** [filebrowser/filebrowser#1032]
Make a space limit for uploaded files of each user. And also make diagrams for each account, as in ordinary cloud storage such as google drive. For example, I give 50 gigabytes to my mom, 20 gigabytes to my brother and 30 father. And more they can not upload. 
Google drive: 
![drive-storage~2](https://user-images.githubusercontent.com/41520056/87534541-d5a95c00-c69e-11ea-9eef-1bee65b88479.jpg)

**Comment by dantebarba** [comment]
As a sidenote, you can already do this by using docker volumes: https://docs.docker.com/storage/volumes/

More info here: https://stackoverflow.com/questions/40494536/how-specify-the-size-of-a-shared-docker-volume

Filebrowser is a filesystem browser, not a solution like nextcloud or Google Drive. 

You won't get a GUI specifying the remaining space, but for your use-case should work. Keep in mind that it's not easy to track disk usage on a per-user basis without messing with user permissions in the filesystem. To do that, the application should keep track of every file with the attached metadata, so it can calculate the remaining space for each user. Besides, two users could share the same directories so how do you measure the space left in that case?. 

But if you use images to restrain user space, Filebrowser could just show the total available space. Then as root directory for each user you'll have to select the mount point of each image.

Also this approach opens the possibility to mount remote volumes as local and using them for user-specific storage. You could browse them using filebrowser.

**Comment by mishailovic** [comment]
Okay. Thanks a lot, i will try
