### ISSUE TITLE
Error when executing any config command

### ISSUE THREAD

**Issue by dantebarba** [filebrowser/filebrowser#1036]
**Description**

I'm trying to execute config commands to allow proxy auth. I'm running filebrowser inside Docker and I can't get the commands to work. 

**Expected behaviour**

Run any command, such as filebrowser config cat, and display any kind of valid output

**What is happening instead?**

Filebrowser is returning "timeout".

```bash
# /filebrowser cmds ls
2020/07/16 21:56:53 timeout
```

**How to reproduce?**

1. Run filebrowser using Docker. Either image will do the trick, I'm using v2-debian
2. Get inside the container:

```bash
docker exec -it filebrowser /bin/sh
```
3. Run any filebrowser command, like.

```bash
# /filebrowser cmds ls
```

**Comment by DVDAndroid** [comment]
dup of #627 (wrongly closed imo). tldr: config commands edits db, but it's locked by filebrowser. the solution is to stop it, run the command and start filebrowser again.

my solution: override the entrypoint of the image: `docker run -it ... --entrypoint /bin/sh filebrowser/filebrowser:alpine`, then `docker exec -it <id> /bin/sh`, do your stuff and then run `filebrowser` to start the server.

other solutions in posted issue.


i hope this will be fixed w/o workarounds

**Comment by dantebarba** [comment]
Yes I did it that way. But theres clearly an issue here, it makes no sense that you wouldn't be allowed to change configurations on runtime

**Comment by thomaschampagne** [comment]
Same issue for me. +1 for a fix

**Comment by o1egl** [comment]
It's not possible to have multi access to the db file. That is the limitation of boltdb. We have a plan to use API calls in CLI. But that will be implemented in the next major release.
