### ISSUE TITLE
Where is WebDav?

### ISSUE THREAD

**Issue by ClarkQAQ** [filebrowser/filebrowser#1038]
Where is WebDav?

I searched all the codes and found nothing

but WebDav is written in the label

**Comment by o1egl** [comment]
We don't have WebDAV support

**Comment by ClarkQAQ** [comment]
![图片](https://user-images.githubusercontent.com/40785118/87914075-b6496f00-caa2-11ea-8d8d-6aff021b6c41.png)
But..........
