### ISSUE TITLE
How to turn off the image thumbnail function?

### ISSUE THREAD

**Issue by skyrim663** [filebrowser/filebrowser#1039]
I am running filebrowser 2.3.0 on my server. But whenever I open a folder with a lot of pictures, the server's computing resources will be full immediately. I had to restart the server. So besides installing filebrowser version 2.2.0, is there any other solution? how to turn off the image thumbnail function?

**Comment by nambrosch** [comment]
An option to disable the thumbnail feature might not be a bad idea, but I'm wondering what type of processor and disk (ssd, 5400rpm, sd card, etc) are in your device?  What "computing resources" are being exhausted?

**Comment by skyrim663** [comment]
> 禁用缩略图功能的选项可能不是一个坏主意，但我想知道设备中装有哪种类型的处理器和磁盘（ssd，5400rpm，sd卡等）？哪些“计算资源”正在用尽？

The disk type is SSD. When opening a folder with too many pictures, the CPU is used the most. Probably because it does not have very high performance.
So how should I turn off the thumbnail function?
Can it be achieved by modifying a configuration file?

**Comment by skyrim663** [comment]
> An option to disable the thumbnail feature might not be a bad idea, but I'm wondering what type of processor and disk (ssd, 5400rpm, sd card, etc) are in your device? What "computing resources" are being exhausted?

The disk type is SSD. When opening a folder with too many pictures, the CPU is used the most. Probably because it does not have very high performance.
So how should I turn off the thumbnail function?
Can it be achieved by modifying a configuration file?

**Comment by o1egl** [comment]
At the moment there is no such functionality. I think adding caching and limiting the number of workers will solve your issue.

**Comment by skyrim663** [comment]
> At the moment there is no such functionality. I think adding caching and limiting the number of workers will solve your issue.

Looking forward to the next version update can optimize this problem.

**Comment by niubility000** [comment]
Me too,  but finally I found it's not cpu's limit, it's "out of memory". My memory is only 500MB.  So add some virtual memory. Everything is fine now.
