### ISSUE TITLE
A couple of JS issues

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#104]
Hi @hacdias 

I have now got my go environment setup so I can build from source. A couple of new issues now arise:

1. When trying to save the config.toml JS throws:
```
PUT http://domain.com/admin/webdav/config.toml 500 (Internal Server Error)
Promise @ common.js:173
webdav.put @ common.js:157
saveContent @ editor.js:224
document.querySelector.addEventListener.event @ editor.js:238
editor.js:231 Internal Server Error
```
2. When using the **delete** key to edit a field, the next character is deleted and then a dialog is shown asking if I really want to "delete 1 file(s)"

Thanks

**Comment by hacdias** [comment]
Sorry but I don't receive any error here @AstonDavies :/ Can you show me your ```config.toml``` so I can try to reproduce the error?

**Comment by AstonDavies** [comment]
Here it is:

```
SectionPagesMenu = "main"
baseurl = "http://dev.astondavies.co.uk/simonchurch/"
content = ""
languageCode = "en-gb"
publishDir = "/www/mmfc/public"
title = "Simon Church Electrical Contractors, Wiltshire and the South West"

[menu]

  [[menu.main]]
    identifier = "partp"
    name = "Part P"
    url = "/partp/"
    weight = 80.0

  [[menu.main]]
    identifier = "buildingprojects"
    name = "Building Projects"
    url = "/buildingprojects/"
    weight = 70.0

```

**Comment by AstonDavies** [comment]
I ran it locally and got this from Caddy:

`14/Jan/2017:14:25:51 +0000 [PANIC /admin/webdav/config.toml] /home/jeremy/Source/gocode/src/github.com/pelletier/go-toml/tomltree_conversions.go:90 - unsupported value type map[string]interface {}: map[weight:80 identifier:partp name:Part P url:/partp/]`

This is when trying to save the config.toml file

**Comment by hacdias** [comment]
Hey @AstonDavies, I'll solve it as soon as I can. In the meanwhile, can you transfer this issue to https://github.com/hacdias/caddy-filemanager/issues? This issue is related with File Manager code. 👍

**Comment by AstonDavies** [comment]
Ok @hacdias I will close this here and create a new issue in filemanager.
