### ISSUE TITLE
How can I hide the cmd while running？

### ISSUE THREAD

**Issue by DragonRollGH** [filebrowser/filebrowser#1040]
I am running filebrowser on windows 10, I want to hide the black cmd window. 
But once I hide the cmd, the server is stopped.

**Comment by o1egl** [comment]
I'm not an expert in windows but you can try one of those
https://www.google.com/search?q=windows+run+cli+tool+as+a+service

**Comment by DragonRollGH** [comment]
WOW, it works! Thank you very much!
And I have added a fork to record it: https://github.com/DragonRollGH/filebrowser/tree/master/service
