### ISSUE TITLE
Overwriting files in 2.5.0 not working

### ISSUE THREAD

**Issue by nambrosch** [filebrowser/filebrowser#1043]
When uploading a file in filebrowser 2.5.0 who's filename already exists a dialogue box properly appears but when "replace" is selected, the file is not uploaded and screen is not refreshed.

Removing the file and uploading again (no replace dialogue) works fine.

Rolling back to a previous version resolves the issue.

**Comment by ramiresviana** [comment]
What type of file you're trying to overwrite? Please provide the server console output.

**Comment by nambrosch** [comment]
Tried pdf and txt files, here's console output from firefox.  It fails in Chrome as well.

![Screen Shot 2020-07-21 at 11 32 04 AM](https://user-images.githubusercontent.com/3680974/88074937-1cd39900-cb46-11ea-8440-08c4886f32d2.png)

**Comment by ramiresviana** [comment]
Thank you for the report, this is related to the conflict handling when using upload button and needs to be fixed.

**Comment by nambrosch** [comment]
Great thanks, I'll use an older version for now.
