### ISSUE TITLE
Command Runner Variables not working

### ISSUE THREAD

**Issue by johnnyq** [filebrowser/filebrowser#1048]
**Description**
I added a command after upload to set the correct unix permission for the user so I added the following line

chown USERNAME FILE

I get error 500 every time I Upload

I also tried this as well

chown $USERNAME $FILE

but still same error

I then tried this 

reboot

and it worked so it looks like the VARIABLES are the issue im not sure if im entering them in correctly or not

**Expected behaviour**
Variabled for command runner should be reconized

**What is happening instead?**
Get error 500 in the bottom left toast alert

**How to reproduce?**
Go to global settings and add the following after_upload chown $USERNAME $FILE

**Comment by ramiresviana** [comment]
Can you provide the console output of the Filebrowser server when the error occurs?
