### ISSUE TITLE
Saving a content file changes format

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#105]
Hi @hacdias 

### 1. What are you trying to do?
Save a content file, specifically `content/buildingprojects/_index.md`

### 2. What is your entire Caddyfile?
```text
http://localhost:4000 {
  tls jeremy@astondavies.co.uk
  root public
  gzip
  basicauth /admin admin@mmfc.co.uk davav
  hugo /home/jeremy/Source/sites/simonchurchelectrical /admin {
    flag destination public
    allow_new true
    allow_edit true
  }
}

```

### 3. What did you expect to see?
A TOML content file like this:
```
+++
date = "2017-01-18T16:29:00"
title = "Building Projects"
+++

```

### 4. What did you see instead (give full error messages and/or log)?
A file formatted differently:
```
date: 2017-01-18T16:29:00
title: Building Projects
...


```

**Comment by hacdias** [comment]
Thanks for reporting this. I'll have a look! 😄 Though, this is related with FileManager code eheh. Don't need to move though.

**Comment by hacdias** [comment]
Done @AstonDavies!
