### ISSUE TITLE
refresh error

### ISSUE THREAD

**Issue by luoluoluoluojunxi** [filebrowser/filebrowser#1052]
when i refresh  ,the page keep loading alway.  and the cosole  show this error as follows:
chunk-vendors.7fda624e.js:1       Uncaught SyntaxError: Unexpected token '<'
app.fd0a4fec.js:1      Uncaught SyntaxError: Unexpected token '<'

**Comment by o1egl** [comment]
Do you see any errors on the backend? Can you please share server response?
