### ISSUE TITLE
Portainer template: unknown flag: --scope

### ISSUE THREAD

**Issue by micheljung** [filebrowser/filebrowser#1055]
**Description**
In a fresh Portainer installation, I'm trying to create a filebrowser container using the filebrowser app template within Portainer. AFAIK, the app template was added by you.

**Expected behaviour**
Filebrowser works.

**What is happening instead?**
Filebrowser fails to start:

```
Error: unknown flag: --scope,
Usage:,
  filebrowser [flags],
  filebrowser [command],
Available Commands:,
  cmds        Command runner management utility,
  config      Configuration management utility,
  hash        Hashes a password,
  help        Help about any command,
  rules       Rules management utility,
  upgrade     Upgrades an old configuration,
  users       Users management utility,
  version     Print the version number,
Flags:,
  -a, --address string           address to listen on (default "127.0.0.1"),
  -b, --baseurl string           base url,
      --cache-dir string         file cache directory (disabled if empty),
  -t, --cert string              tls certificate,
  -c, --config string            config file path,
  -d, --database string          database path (default "./filebrowser.db"),
      --disable-preview-resize   disable resize of image previews,
      --disable-thumbnails       disable image thumbnails,
  -h, --help                     help for filebrowser,
      --img-processors int       image processors count (default 4),
  -k, --key string               tls key,
  -l, --log string               log output (default "stdout"),
      --noauth                   use the noauth auther when using quick setup,
      --password string          hashed password for the first user when using quick config (default "admin"),
  -p, --port string              port to listen on (default "8080"),
  -r, --root string              root to prepend to relative paths (default "."),
      --socket string            socket to listen to (cannot be used with address, port, cert nor key flags),
      --username string          username for the first user when using quick config (default "admin"),
Use "filebrowser [command] --help" for more information about a command.,
2020/08/02 11:59:39 unknown flag: --scope,
```

**Comment by ramiresviana** [comment]
What do you mean by "filebrowser app template"? Filebrowser has a Docker image that you can use to create containers using Portainer.

> Error: unknown flag: --scope,

Giving a invalid flag to Filebrowser will cause it to not start. What do you probably want is to parse this flag to Portainer or Docker instead of Filebrowser.

**Comment by o1egl** [comment]
I've never used portainer but I think he is talking about this template https://github.com/portainer/templates/blame/master/templates-2.0.json#L806-L827

**Comment by ramiresviana** [comment]
Since 5a83d67 the --scope flag was renamed to --root, but the Portainer template remained with the old flag, causing containers created with the Filebrowser template to not work.

I created a pull request https://github.com/portainer/templates/pull/123 but i dont know how much time the maintainers will take to merge it.

@micheljung you can fix this on your Portainer installation by renaming the --scope flag to --root on the Filebrowser template. You can do it by clicking on the "Update" button on the Portainer templates page.

**Comment by micheljung** [comment]
Sorry for filing in the wrong repo, I somehow thought the template was added by you :-)
Thank you for submitting the PR!
