### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by qianmianyao** [filebrowser/filebrowser#1057]
root@VM-0-17-debian:~# docker run \
>     -v /root:/srv \
>     -v /root/filebrowset/filebrowser.db:/database.db \
>     -v /root/filebrowser/.filebrowser.json:/.filebrowser.json \
>     -p 80:80 \
>     filebrowser/filebrowser
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/root/filebrowser/.filebrowser.json\\\" to rootfs \\\"/var/lib/docker/overlay2/4b99c4ee6e8419f2f7a8ab743c5bde7a4aa3a2836af6224a5b4b506bc56a52df/merged\\\" at \\\"/var/lib/docker/overlay2/4b99c4ee6e8419f2f7a8ab743c5bde7a4aa3a2836af6224a5b4b506bc56a52df/merged/.filebrowser.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by o1egl** [comment]
are you sure that /root/filebrowset/filebrowser.db and /root/filebrowser/.filebrowser.json files exist?

**Comment by qianmianyao** [comment]
I need to create these two files on the host first?

**Comment by o1egl** [comment]
It's written in your error message :wink:
> Check if the specified host path exists and is the expected type.

**Comment by qianmianyao** [comment]
Ok, do I need to create these two files by myself?

**Comment by o1egl** [comment]
Yes. `touch /root/filebrowser/filebrowser.db /root/filebrowser/.filebrowser.json`

**Comment by qianmianyao** [comment]
thank you
