### ISSUE TITLE
Content type is incorrectly stated

### ISSUE THREAD

**Issue by yashcho** [filebrowser/filebrowser#1058]
Hello Team,

Summary:

When we done some security pen-testing of open-source filebrowser 1.11 installed on our project application, we got a Content type is incorrectly stated on specific URL endpoint (/filebrowser/static/js/app.dfee4ad48f81619d57c4.js.map), which might expose the details of our end users uploaded document.

As you can see in this screenshot:
![image](https://user-images.githubusercontent.com/69308923/89648273-999f9a80-d8dc-11ea-988c-67d0e56d17cd.png)

I believe this is a low level severity bug but if you can provide us some fix on it would appreciate it?

**Comment by o1egl** [comment]
@yashcho what is wrong with this content type? looks valid

**Comment by yashcho** [comment]
As per our security team the content type should be specified in request, so that one can injected/manipulated different content type in response using request

**Comment by o1egl** [comment]
I still don't understand what kind of behaviour you expect from the response?

**Comment by yashcho** [comment]
For every response containing a message body, the application should include a single Content-type header that correctly and unambiguously states the MIME type of the content in the response body. Additionally, the response header "X-content-type-options: nosniff" should be returned in all responses to reduce the likelihood that browsers will interpret content in a way that
disregards the Content-type header.

**Comment by o1egl** [comment]
So as I see on the provided picture currently returned content type is `text/plain; charset=utf8` which if a correct content type. If you want to play around it you can use a proxy like nginx or traefic and configure it as you need.

**Comment by yashcho** [comment]
so it means this issue more related towards infrastructure of our project rather then some code flaw in filebrowser, if yes then we will discuss with our infrastructure team and then we can close the ticket.. :)

**Comment by o1egl** [comment]
You are right
