### ISSUE TITLE
Cross-Domain Referrer leakage

### ISSUE THREAD

**Issue by yashcho** [filebrowser/filebrowser#1059]
Hello Team,

Summary:

When we done some security pen-testing of open-source filebrowser 1.11 installed on our project application, we got a Cross-Domain Referrer leakage on specific URL(/filebrowser/static/share), which might expose the redirection to malicious website for our end users.

As you can see in this screenshot:
![image](https://user-images.githubusercontent.com/69308923/89648972-aa044500-d8dd-11ea-8724-b8d10d06a190.png)

I believe this is a low level severity bug but if you can provide us some fix on it would appreciate it?

**Comment by nambrosch** [comment]
@o1egl Could probably just download the minified version and include in /static/css, it hasn't been updated in 2ish years.

https://cdnjs.com/libraries/normalize

**Comment by ramiresviana** [comment]
There is no external library usage in the current version of the frontend. The last release of normalize.css is already being used as a dependency.

**Comment by nambrosch** [comment]
I was wondering about that since I couldn't reproduce it in my local copy of 2.6.2 then noticed @yashcho was testing against release 1.11 which is the oldest release in this github repository.

**Comment by o1egl** [comment]
@yashcho Thanks for the report. I think the best solution would be to upgrade to the latest version of file browser.

**Comment by yashcho** [comment]
@o1egl Thanks for the suggestion.. we would implement it.. but can there be some workaround from release 1.11.. :)

**Comment by ramiresviana** [comment]
@yashcho just for fun, i got the filebrowser v1.1.1 source code and installed the npm dependencies, that give me the following message:

> added 1339 packages from 1570 contributors and audited 1346 packages

Are you going to check security flaws on every package and search a workaround for it?

Stay safe, use updated software.
