### ISSUE TITLE
Can you make the deletion of public folder upon hugo run optional ?

### ISSUE THREAD

**Issue by sugacube** [filebrowser/filebrowser#106]
In the current version, when "hugo" is run with caddy-hugo, the ""public" folder is being deleted before hugo is run to generate the web site.

Could this behaviour be made optional ? For example using a flag "erase=false" ? In certain circumstances it is usefull to keep the old files/directories. (This is also default hugo behaviour iirc)

**Comment by hacdias** [comment]
Hello! Yes, I made it to make sure that if some page is deleted that it wouldn't be available. What are the downsides of this? 😄 But I can do that soon 😃.

P.S.: Sorry for the delay answering.

**Comment by hacdias** [comment]
Just added an option `clean_public` which defaults to `true` but you will be able to use it to prevent the removal of `public` folder before each generation 😄
