### ISSUE TITLE
Add proxy protocol support

### ISSUE THREAD

**Issue by HiFiPhile** [filebrowser/filebrowser#1061]
**Is your feature request related to a problem? Please describe.**
When using HAproxy or Nginx as reverse proxy, it would be great to have the source IP logged instead of IP of the proxy.
Then we can use `fail2ban` to enhance the server security.

**Describe the solution you'd like**
Add an option to active proxy protocol support, in order to get the real IP.

**Describe alternatives you've considered**
- Implement fail2ban mechanism inside `filebrowser` 
- Support `X-Forwarded-For` header

**Additional context**
[go-proxyproto](https://github.com/armon/go-proxyproto) seems a good start.

**Comment by o1egl** [comment]
Implementing any kind of firewall is out of the scope of this project. You can do it with the proper tools
