### ISSUE TITLE
How can I edit and run the frontend alone?

### ISSUE THREAD

**Issue by simzhangbest** [filebrowser/filebrowser#1062]
the frontend code by VUE, I want to debug and edit it, but can't work, how can I run frontend alone or debug it alone?
I found that in the http/static.go file, the backend include the dist folder whit index.html, css and js and so on.  but if I want edit the frontend code index.html or *.vue or sth else, I don't want to run "npm build " and get new dist files.

**Comment by o1egl** [comment]
You can run `npm run watch` to automatically build js files on any change.

**Comment by simzhangbest** [comment]
thanks

**Comment by TCB13** [comment]
Can you guys clarify the process?

I can do `npm run watch` and my files will be always up to date, however I've to recompile the main go binary with `go run main.go` or `go build` because it packs the vue output inside it. Is there any way around this?

**Comment by TCB13** [comment]
Answer here: https://github.com/filebrowser/filebrowser/issues/1394#issuecomment-835451233
