### ISSUE TITLE
active shell in filebrowser web, then   I want active python shell. It didn't work

### ISSUE THREAD

**Issue by simzhangbest** [filebrowser/filebrowser#1064]
![python-issue](https://user-images.githubusercontent.com/24918900/90303085-8cd30600-dedd-11ea-9956-6b8ba8577ca7.png)
sth like this, gdb , I'm using you system's shell to do some python work remotly. would you like help me or tell me how to do this, that I will be very grateful , thank you

**Comment by o1egl** [comment]
At the moment shell is not interactive.

**Comment by o1egl** [comment]
Duplicate of the #984

**Comment by simzhangbest** [comment]
thank you very much
