### ISSUE TITLE
Put config files in subdirectory for docker container

### ISSUE THREAD

**Issue by simon446** [filebrowser/filebrowser#1067]
**Is your feature request related to a problem? Please describe.**
I want to mount filebrowser storage to docker data volumes and it is not possible to do that currently, see problematic example below:

```bash
docker run \
    -v /path/to/root:/srv \
    -v filebrowser_db:/database.db \ # Not possible to mount files to data volumes
    -v filebrowse_config:/.filebrowser.json \ # Same problem here
    -p 80:80 \
    filebrowser/filebrowser
```

This is problematic since database.db (and also .filebrowser.json) resides in the root directory (the root directory cannot be mounted outside of the container), and it is only possible to mount directories to data volumes, not individual files like database.db.

**Describe the solution you'd like**
If both `database.db` and `.filebrowser.json` were moved to a subdirectory `data`, for example, it would allow users to mount configuration files to data volumes while still preserving old behaviour. So to mount using docker we would use this command (from docs):

```bash
docker run \
    -v /path/to/root:/srv \
    -v /path/filebrowser.db:/data/database.db \
    -v /path/.filebrowser.json:/data/.filebrowser.json \
    -p 80:80 \
    filebrowser/filebrowser
```

And this new behaviour would be possible if one wants to use data volumes

```bash
docker run \
    -v /path/to/root:/srv \
    -v filebrowser_data:/data \ # Possible to mount directories to data volumes
    -p 80:80 \
    filebrowser/filebrowser
```

**Comment by o1egl** [comment]
You can use `--config` and  `--database` flags to override default paths

**Comment by gp-slick-coder** [comment]
This version is optimized for docker:
https://github.com/hurlenko/filebrowser-docker

**Comment by i-zhaopin** [comment]
> This version is optimized for docker:
> https://github.com/hurlenko/filebrowser-docker

thanks , It's much better
