### ISSUE TITLE
How to add a new button?

### ISSUE THREAD

**Issue by ninn55** [filebrowser/filebrowser#1068]
My application integrates this project with a cloud ide. I would love to add this feature. When a folder is chosen, add a new button (alongside copy download upload, etc.) which would open a tab with a specific URL (depending on the path of the folder).

How would I possibly implement this?
Couldn't find the "build from source" document for this project.

Edit: I don't know anything about vue though.

Awesome project BTW. Clean interface. Impressive code base.

**Keep up the great work.**

Thanks.

**Comment by o1egl** [comment]
To do that you need to modify frontend part and run `./wizard.sh -a` to build a new binary.

**Comment by ramiresviana** [comment]
Since that request is out of the current scope of the Filebrowser, you will need to create your own version of Filebrowser.

This is a small guide about building Filebrowser: https://filebrowser.org/contributing
You will need some time to learn VueJS and how things work in Filebrowser.

**Comment by ninn55** [comment]
Thanks for the reply.
I will dig around the project and come back with more specific questions.
