### ISSUE TITLE
Can't upload file with name from another language

### ISSUE THREAD

**Issue by idan92** [filebrowser/filebrowser#1069]
**Description**
When I upload a file or folder that name isn't English, I receive a pop message "500 Internal Server Error".

Thanks :)
Idan

**Comment by o1egl** [comment]
Can you please share server logs?

**Comment by idan92** [comment]
> Can you please share server logs?

Thanks for your comment :)

I fixed that.

The Rasspberry Pi Lite OS does this problem so I changed to ubuntu server and it's work now!
