### ISSUE TITLE
Screenshots and/or Demo

### ISSUE THREAD

**Issue by nevf** [filebrowser/filebrowser#107]
It would be great to see some screen shots, better still to have a live demo of caddy-hugo.

**Comment by hacdias** [comment]
Thanks for the suggestion @nevf! I'll check this as soon as I can 😄

**Comment by hacdias** [comment]
Hey @nevf, I've just added a Screenshots section in the README. Do you think it's good? 😄

**Comment by nevf** [comment]
@hacdias Thanks, they look good and certainly help to get a better idea of caddy-hugo's capabilities. You should think about writing a article all about it and publish that on Medium. Good exposure.

**Comment by hacdias** [comment]
Screenshots are available on the [README](https://github.com/hacdias/filemanager/blob/master/README.md) and I'm planning on writing a Medium article soon :)
