### ISSUE TITLE
can't open file browser

### ISSUE THREAD

**Issue by TheHamkerCat** [filebrowser/filebrowser#1070]
i just installed filebrowser and after executing `$ filebrowse`r it says listening on port 8080 but i can't open file browser from external network

**Comment by o1egl** [comment]
Because you started in on your localhost. You can use `--address 0.0.0.0` flag to listen on all available interfaces

**Comment by ivanelson** [comment]
> Because you started in on your localhost. You can use `--address 0.0.0.0` flag to listen on all available interfaces

Great! Thanks. I didn't find this guidance in the documentation.
