### ISSUE TITLE
error : No config file used

### ISSUE THREAD

**Issue by wangzezheng8** [filebrowser/filebrowser#1072]
I execute under Windows.\ filebrowser.exe-d.\ filebrowser.db prompt No config file used
![dfsd](https://user-images.githubusercontent.com/44769177/92134733-78c75800-ee3c-11ea-9fd9-c6b20eb4b479.PNG)

**Comment by o1egl** [comment]
`-d` sets path to the db file. To set the config you have to use `-c` param

**Comment by wangzezheng8** [comment]
Thank you very much, this solved the problem for me

**Comment by wangzezheng8** [comment]
Just now the first time can run successfully, but the second time cannot run successfully, I found that there is no configuration file in the project directory

![20200904114223](https://user-images.githubusercontent.com/44769177/92197229-c0cd9580-eea3-11ea-8f58-a0c6c442dcd0.png)
![image](https://user-images.githubusercontent.com/44769177/92197254-d3e06580-eea3-11ea-93a9-50aafd128bcc.png)

**Comment by o1egl** [comment]
You have to create it manually
