### ISSUE TITLE
Unable to enable noauth

### ISSUE THREAD

**Issue by agneevX** [filebrowser/filebrowser#1073]
I can't seem to figure out how to remove auth.

This is the systemd unit file I'm using:

```ini
[Unit]
Description=filebrowser daemon
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/filebrowser \
        --noauth -r /home/agneev -p 9800 \
        --config /home/agneev/.filebrowser.json \
        --database /home/agneev/filebrowser.db
User=agneev
Group=agneev

[Install]
WantedBy=multi-user.target
```

**Comment by ramiresviana** [comment]
The noauth option is used for the initial setup and does not have effect after the database has initialized.

You can recreate the database or use cli config set to change the auth.method param on the current database.

**Comment by agneevX** [comment]
@ramiresviana what would a command to disable auth, and create a new DB look like?

**Comment by ramiresviana** [comment]
@agneevX you can recreate the database by deleting the current database file, running Filebrowser with --noauth parameter next time will cause it to create a new database with noauth configuration.

Setting auth.method to noauth on an existing database can be done with this command: `filebrowser config set --auth.method noauth`
