### ISSUE TITLE
Unzip button

### ISSUE THREAD

**Issue by sfoxdev** [filebrowser/filebrowser#1076]
Add unzip button on top, so you can simply upload commonly used .zip archive and unzip it in current folder or subfolder.

**Comment by sfoxdev** [comment]
I never used Vue, so it's a new experience for me. Here is what I tried, hope community can help me with the code.

I added to `./files/file.go` row 174
```
case strings.HasSuffix(mimetype, "zip"):
  i.Type = "zip"
  return nil
```

in `./frontend/src/components/files/ListingItem.vue` row 58
```
    icon () {
      if (this.isDir) return 'folder'
      if (this.type === 'zip') return 'archive'
```

So after that icon of zip file changed in files listing, I'm happy with that.

After that I created file `./frontend/src/components/buttons/Unzip.vue`
```
<template>
  <button @click="show" :aria-label="$t('buttons.unzip')" :title="$t('buttons.unzip')" class="action" id="unzip-button">
    <i class="material-icons">unarchive</i>
    <span>{{ $t('buttons.unzip') }}</span>
  </button>
</template>

<script>
export default {
  name: 'unzip-button',
  methods: {
    show: function () {
      console.log(this.$store.getters.isZip)
      console.log(this.$store.state.req)
      this.$store.commit('showHover', 'unzip')
    }
  }
}
</script>
```

Changed the file `./frontend/src/components/Header.vue` row 76
```
import UnzipButton from './buttons/Unzip'
export default {
  name: 'header-layout',
  components: {
    Search,
    InfoButton,
    DeleteButton,
    ShareButton,
    RenameButton,
    DownloadButton,
    CopyButton,
    UploadButton,
    SwitchButton,
    MoveButton,
    ShellButton,
    UnzipButton
  },
```
in the same file on row 141 added 
```
    showUnzipButton () {
      return this.isFiles && (this.isListing
        ? (this.selectedCount === 1 && this.user.perm.create)
        : this.user.perm.create)
    },
```

Now button appears on top and I happy again.

Next what I want is to show button only when the .zip file is selected. How can I implement that?

**Comment by SamDecrock** [comment]
Did you make the button work?

**Comment by sfoxdev** [comment]
Yes, I did.

**Comment by SamDecrock** [comment]
How did you make it work?

**Comment by gingerbeardman** [comment]
Please submit these changes as a PR, it useful for everybody.

It would need to check if zip command was available to the current user.
