### ISSUE TITLE
Unable to build Dockerimage

### ISSUE THREAD

**Issue by tusharsonawanes** [filebrowser/filebrowser#1078]
I cloned the official repo but when I try to build the Dockerfile, I get this error

```
Step 10/11 : COPY filebrowser /filebrowser
COPY failed: stat /var/lib/docker/tmp/docker-builder257534842/filebrowser: no such file or directory

```

**Comment by o1egl** [comment]
We use goreleaser as a builder for file browser. So to build docker image manually you need to build [filebrowser](https://filebrowser.org/contributing#build) first.

**Comment by tusharsonawanes** [comment]
> We use goreleaser as a builder for file browser. So to build docker image manually you need to build [filebrowser](https://filebrowser.org/contributing#build) first.


@o1egl 
Hi, I followed the steps you mentioned. 

I get the following message after `npm run build`

```
 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```

but when I go back to the previous directory and = and I try to build the docker image, still I am getting the same error. Am I in the wrong directory ?

**Comment by o1egl** [comment]
@tusharsonawanes follow the next step https://filebrowser.org/contributing#backend

**Comment by tusharsonawanes** [comment]
@o1egl  


the command `go mod download` runs, I have an issue with rice.

**`bash: rice: command not found...`**

I tried installing it with pip but no luck

**Comment by tusharsonawanes** [comment]
I tried installing it with these commands but still the same error

```
go get github.com/GeertJohan/go.rice
go get github.com/GeertJohan/go.rice/rice
```

**Comment by o1egl** [comment]
@tusharsonawanes you need to add $GOPATH/bin into your PATH

**Comment by tusharsonawanes** [comment]
> @tusharsonawanes you need to add $GOPATH/bin into your PATH

@o1egl  Sorry for the silly question, how do I add it exactly ? I am using bash

**Comment by o1egl** [comment]
Add 
```
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
```
to your .bashrc file

**Comment by tusharsonawanes** [comment]
@o1egl 

Done. The command is not working and also my `go build ` worked. But still, when I try to build the docker image, I get this error

`COPY failed: stat /var/lib/docker/tmp/docker-builder147016300/filebrowser: no such file or directory`

I am in the main filebrowser directory now

**Comment by o1egl** [comment]
Which command is not working?

**Comment by tusharsonawanes** [comment]
So the `go build` command executed successfully and I am now back in this directory

![image](https://user-images.githubusercontent.com/12230324/94020790-f265bc80-fdd0-11ea-8ce9-90bb1163f384.png)

Now when I run  `docker build -t <name> . `

It gives the output that I mentioned above.

**Comment by o1egl** [comment]
`go build` should create `filebrowser` binary. I don't see it in the above screenshot.

**Comment by o1egl** [comment]
You can also run `./wizard.sh -b` to build the binary

**Comment by tusharsonawanes** [comment]
@o1egl I tried running the wizard but still I dont see the filebrowser binary..

**Comment by tusharsonawanes** [comment]
@o1egl completed all the steps. I guess I missed `-b` in the previous step. 

I have the filebrowser binary now and I built my docker image. Now when I try to run the docker image, I get this error using this command, `docker run -v /root:/srv -p 86:80 <image-name>` I get this error

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

**Comment by tusharsonawanes** [comment]
Sorted out the issue. This helped

https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

**Comment by o1egl** [comment]
I think we can close this issue

**Comment by tusharsonawanes** [comment]
Yes absolutely. Thank you soo much @o1egl  for your help 👍
