### ISSUE TITLE
REST api

### ISSUE THREAD

**Issue by dashingstag** [filebrowser/filebrowser#1079]
Is there a rest api we can use for uploading and downloading?

I am using locust but i am getting a 402 unauthorized error when I am tryting to access my folders

**Comment by o1egl** [comment]
To be able to access an API you need to pass authentication first and obtain access token. This token should be injected into `X-Auth` header of your api calls. You can check frontend app as a reference https://github.com/filebrowser/filebrowser/blob/master/frontend/src/api/utils.js#L5-L24

**Comment by dashingstag** [comment]
I am deploying the 2.0.16 version as a web app inside my jupyterhub image so I can't see how the token is being created. Is there a way to request or generate the token? I don't see the token if I just use the jupyter hub login and enter the web app. if i use the network history the x-auth is just there if i enter the app

**Comment by dashingstag** [comment]
solved the issue by tracing the network
This is what i did for anyone that is interested
```
        #generate session tokens
        response = self.client.request("GET","/user/"+self.user+"/test/") 
        #generate workspace token
        response = self.client.request("GET","/user/"+self.user+"/test/shared/filebrowser/files/workspace/?token=admin")
        #login into filebrowser
        response = self.client.request("POST","/user/"+self.user+"/test/shared/filebrowser/api/login",data=json.dumps({
                                    "username": "", 
                                    "password": "", 
                                    "recaptcha": ""}))
        self.x_auth = response.content.decode("utf-8")

        response = self.client.request("POST","/user/"+self.user+"/test/shared/filebrowser/api/resources/workspace/"+self.upload_file+"? 
                                    override=true",
                                    headers={
                                    'x-auth':self.x_auth
                                    },
                                    files={'file': open(self.upload_file, 'rb')})
```

**Comment by icheered** [comment]
I added an example on how to upload and download files using nodejs over in #2551, it took me a while to figure out the `X-Auth` thing because the _normal_ thing to do is use the `Authorization` header instead...
