### ISSUE TITLE
Jekyll instead of Hugo

### ISSUE THREAD

**Issue by Fastidious** [filebrowser/filebrowser#108]
Can this be used with [Jekyll](https://jekyllrb.com) instead of Hugo? If so, where can I find the instructions? Thanks!

**Comment by hacdias** [comment]
Right now, it can't. But it would be an interesting feature to support other Static Website Generators.

**Comment by hacdias** [comment]
I'll close this now @Fastidious! It will be available soon to download on Caddyserver.com if you're still interested!

**Comment by Fastidious** [comment]
@hacdias available as in, possible with Jekyll?!

**Comment by hacdias** [comment]
Yes, there will be a plugin called 'jekyll' as soon as the next caddy release is out 😄

**Comment by hacdias** [comment]
I'll ping you when it's out 😄

**Comment by hacdias** [comment]
Publish @Fastidious! :smile:

**Comment by Fastidious** [comment]
@hacdias could you expand on the basic usage? If I have:

```
quark.business {
        root /var/www/html

        log /var/log/caddy/quark.business.log {
                rotate_size 1
                rotate_age  7
                rotate_keep 1
        }
        header / {
                Strict-Transport-Security "max-age=31536000"
                X-XSS-Protection "1; mode=block"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "DENY"
                -Server
        }
        tls {
                key_type rsa4096
                protocols tls1.2
                must_staple
        }
}
```

And my `jekyll` site is at `/var/local/jekyll/quark.business/`, how would I go to incorporate it?

**Comment by hacdias** [comment]
You can see more here: https://henriquedias.com/filemanager/caddy/

I'd do this:

```
quark.business {
        root /var/www/html
         jekyll /var/local/jekyll/quark.business/

        log /var/log/caddy/quark.business.log {
                rotate_size 1
                rotate_age  7
                rotate_keep 1
        }
        header / {
                Strict-Transport-Security "max-age=31536000"
                X-XSS-Protection "1; mode=block"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "DENY"
                -Server
        }
        tls {
                key_type rsa4096
                protocols tls1.2
                must_staple
        }
}
```

**Comment by Fastidious** [comment]
@hacdias did that. I can go to `https://quark.business/admin` and see a login screen. Now what? Sorry, totally lost. :-)

**Comment by hacdias** [comment]
The default credentials are:

Username: admin
Password: admin

You can change them on Settings.

**Comment by Fastidious** [comment]
I am going to be posting on the Caddy plugin community (https://caddy.community/) about getting this to run. I can login, but I can’t see a way to publish the site, etc. More on https://caddy.community/c/plugins later today. :-)

**Comment by hacdias** [comment]
Sure!

If you open a file you'll see some buttons on the top bar to publish and everything.
