### ISSUE TITLE
Some folders do not appear until I toggle the "switch view" button.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1080]
**Description**
Title + the folders are still accessible in search when they are invisible otherwise. Permissions set to the dangerous 777 still don't fix the issue. I did not notice the issue before adding terabytes of content to my file server.

**Expected behaviour**
I expect the folders in the directory to be visible at all times.

**What is happening instead?**
Several folders (seemingly random ones) are invisible until I toggle "switch view", and after doing that they are visible in either of the provided view options.

**How to reproduce?**
Unsure. Didn't happen until my file server got a lot of files added to it, but just for testing sake, I gave all folders 777 permissions and made sure they were all part of the same owner and group, yet some are still invisible without toggling "switch view".

**Comment by o1egl** [comment]
Do you have any error messages in the server log or in the browser console?

**Comment by ghost** [comment]
Sorry, somewhat new to this. How do I access the server log?

**Comment by o1egl** [comment]
How do you run the app? Logs are printed to stdout.

**Comment by o1egl** [comment]
No response
