### ISSUE TITLE
Video preview not showing up for many videos

### ISSUE THREAD

**Issue by DanielZhang17** [filebrowser/filebrowser#1083]
**Description**
I have been using filebrowser for a while now. I noticed a problem with video preview recently when I uploaded some video footages to my filebrowser. I tried to preview them in browser but the only thing shows up is a download button. I am using the latest version of chrome and the codecs of those videos should be supported. 
**Expected behaviour**
What did you expect to happen?
The video files can be played in the browser before i download them.
**What is happening instead?**
Nothing other than the download button shows up under the menu bar.
**Additional context**
I tied multiple files with various codecs and some of them worked but most of them are not recognized as video files.
I would suggest to treat files ending in all common video extensions (e.g. mp4,mkv,ts,mov,avi,webm,etc.) as videos. Try to show the preview window for all those files and leave the exact handling to the browser. I also tried to update to the latest verison (2.7.0). But the problem persists.
**How to reproduce?**
Put the files into filebrowser and double click on it. See the attachment for sample video.
**Files**
I tried to upload this sample file here but github doesn't support it. So I put a shared link from within filebrowser here instead. This link will expire in 30 days.
[https://file.anranz.xyz/share/R8xc24XE](url)

**Comment by o1egl** [comment]
@DanielZhang17 I just tried to upload and play this file on chrome and firefox and see no playback issues. Do you have any browser extension that can block video playback?

**Comment by DanielZhang17** [comment]
@o1egl I do have ad blocker on my PC though, but it does not apear to block anything in this case. I have my sites whitelisted in the adblocker. 
The video preview for this particular video is not showing up in chrome on my mobile devices as well.  See my screenshot for more details.
![s1](https://user-images.githubusercontent.com/26383041/93025348-a4cca100-f5d3-11ea-9b7d-4de0c959b374.png)

**Comment by o1egl** [comment]
@DanielZhang17 can you please share response tab of that request?

**Comment by DanielZhang17** [comment]
@o1egl 
The response I got is the following
`{"path":"/wot.mp4","name":"wot.mp4","size":67690985,"extension":".mp4","modified":"2020-09-13T18:07:13.055577611Z","mode":493,"isDir":false,"type":"blob"}`

**Comment by DanielZhang17** [comment]
For some other files that it recognize as video, it will show a inline preview with some encryption key string in the fetch request url. Even though chrome does not support HEVC on PC.
![s2](https://user-images.githubusercontent.com/26383041/93026582-5b814f00-f5dd-11ea-801b-1372c8dae5d9.png)

**Comment by DanielZhang17** [comment]
I just did another test on my other install of filebrowser and I can't reproduce the problem over on that server. Can this be downto the problem of my docker image even if I mounted the precompiled binary from github ? 
The docker image that I currently use is [https://github.com/wahyd4/aria2-ariang-docker](url) running on my synology nas. I mounted the filebrowser binary to /app/filebrowser

**Comment by o1egl** [comment]
Looks like /etc/mime.types file is missing in your docker image. You can add it by installing `apk add mailcap` package.

**Comment by DanielZhang17** [comment]
I submitted a pull request to the docker image that I use. The new image now works perfectly. Thanks for the help.
