### ISSUE TITLE
Button to show/hide dotfiles

### ISSUE THREAD

**Issue by kwsp** [filebrowser/filebrowser#1084]
It would be neat if we can add a simple **checkbox in the UI that shows/hides dotfiles**. This feature is available in most file managers (e.g. Nautilus, Dolphin).

I've looked at https://github.com/filebrowser/filebrowser/issues/322, https://github.com/filebrowser/filebrowser/issues/349, https://github.com/filebrowser/filebrowser/issues/489, but all of them are approaching this problem using the disallow/allow rules. 

A minimal version of this feature can be implemented completely in the frontend without touching the backend, although it would be nice if the user's preference is saved to the db or config file. 

I'm happy to work on this feature, but I want to hear what the maintainers think first :) 

Thanks for a great piece of software!

**Comment by o1egl** [comment]
Sounds like a nice feature to add 👍 Feel free to make a PR
