### ISSUE TITLE
Docker image for arm64 devices

### ISSUE THREAD

**Issue by Razerban** [filebrowser/filebrowser#1086]
**Describe the solution you'd like**
A Docker image made for arm64 devices.

It would be awesome if we could have an arm64 image for filebrowser.

Also which base image is the `filebrowser/filebrowser:pi` image using ? `alpine` ?
Unfortunately, I get an error when I try to connect directly to the Kubernetes Pod running these commands:
```
$ kubectl exec -ti -n filebrowser filebrowser-XXXXXXXXXX-XXXXX -- /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
command terminated with exit code 126
```
```
$ kubectl exec -ti -n filebrowser filebrowser-XXXXXXXXXX-XXXXX -- /bin/ash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/ash\": stat /bin/ash: no such file or directory": unknown
command terminated with exit code 126
```
```
$ kubectl exec -ti -n filebrowser filebrowser-XXXXXXXXXX-XXXXX -- /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
command terminated with exit code 126
```
It seems that none of `/bin/sh`, `/bin/ash` and `/bin/bash` exist in the image :disappointed:.

**Comment by o1egl** [comment]
pi image is built from scratch. It contains only filebrowser binary. You can check all existing image configurations [here](https://github.com/filebrowser/filebrowser/blob/master/.goreleaser.yml#L55-L107). On which device are you trying to run it?

**Comment by Razerban** [comment]
Thank you for your reply.
Actually, I'm running it on my Raspberry Pi 4 running arm64 DietPi OS.
It's working fine, but if I want to connect to the container for troubleshooting purposes, I can't.
It would be good to have an `alpine` and/or `debian` based filebrowser container image for `armhf` & `arm64` in addition to the ones already available.

**Comment by pippo73** [comment]
Hi all, 
sorry but I cannot understand if the docker image works or not on a raspberry pi4 system.
If I try I get the following error:
 ```
$ docker run --name "filebrowser" -v /home/pi/Filebrowser:/srv -p 1382:80 filebrowser/filebrowser
standard_init_linux.go:211: exec user process caused "exec format error"
```
Could someone help me pls

**Comment by Razerban** [comment]
> Hi all,
> sorry but I cannot understand if the docker image works or not on a raspberry pi4 system.
> If I try I get the following error:
> 
> ```
> $ docker run --name "filebrowser" -v /home/pi/Filebrowser:/srv -p 1382:80 filebrowser/filebrowser
> standard_init_linux.go:211: exec user process caused "exec format error"
> ```
> 
> Could someone help me pls

Hello 👋 !
You need to use the `pi` image tag when creating the container: `filebrowser/filebrowser:pi`.
This should work:
```bash
$ docker run --name "filebrowser" -v /home/pi/Filebrowser:/srv -p 1382:80 filebrowser/filebrowser:pi
```

**Comment by ionutvilie** [comment]
Hi, Since the name contains what I need to ask I will hijack this an not create another issue to ask some questions.

So basically my issues are like this:

- If you use from scratch it is hard to debug issues or find out how the app works. Is there a reason for not using alpine/busybox and add an extra 6MB to the image?

- for the volumes, I would have expected a configuration volume and a expose data volume. take for example the way linuxserver builds their docker images (data path and everything else needed) https://github.com/linuxserver/docker-calibre#docker.
when you build it and run it this way the state of the container persists and survives restarts. I have tried to configure the docker image but it is not very friendly. 

Issues that I got: When following the documentation:
```bash
# process launches on interface 127.0.0.0 which makes it useless because port forwarding isn't working 
docker run --rm -v /mnt/sgt2t/media/:/srv -v /mnt/sgt2t/config/filebrowser/filebrowser.db:/database.db -v /mnt/sgt2t/config/filebrowser/.filebrowser.json:/.filebrowser.json -p 8082:8080 filebrowser/filebrowser:pi
2020/10/02 06:14:46 Using config file: /.filebrowser.json
2020/10/02 06:14:46 Listening on 127.0.0.1:8080
# works by setting extra arguments but makes it visually wrong :)
docker run --rm -v /mnt/sgt2t/media/:/srv -v /mnt/sgt2t/config/filebrowser/filebrowser.db:/database.db -v /mnt/sgt2t/config/filebrowser/.filebrowser.json:/.filebrowser.json -p 8082:8080 filebrowser/filebrowser:pi -a 0.0.0.0
2020/10/02 06:16:42 Using config file: /.filebrowser.json
2020/10/02 06:16:43 Listening on [::]:8080
```

So the main question will be if it is a reason it is built this way?  :)

**Comment by o1egl** [comment]
@ionutvilie what stops you from mounting a volume to container?
