### ISSUE TITLE
Unexpected file or folder name with "override=false"

### ISSUE THREAD

**Issue by Alsan** [filebrowser/filebrowser#1087]
![ArcoLinux_2020-09-17_13-11-41](https://user-images.githubusercontent.com/217947/93427571-9b537980-f8f0-11ea-9982-e97695e6de6e.png)

As the picture shown, an unexpected file named '?override=false' will be added automatically right after I create a folder, and an unexpected "?override=false" is appended to the filename of my uploaded file.

I've test all the versions down to 2.3, and had the same issue.

**Comment by o1egl** [comment]
On which environment you run the app? Do you use any proxy?

**Comment by Alsan** [comment]
Centos 7. Yes, I'm using Nginx as reverse proxy.

**Comment by o1egl** [comment]
Can you try to access filebrowser directly and check if you have the same issue.

**Comment by Alsan** [comment]
I'm afraid this couldn't be done, and that's why we need a proxy between the client and server.

Below is the conf for proxying the fb:

```text
location ~ /fb/ {
    client_max_body_size 10240M;
    rewrite /fb/(.*)$ /sit/fb/$1$is_args$args break;

    error_log logs/fb_errors debug;

    proxy_http_version 1.1;
    proxy_set_header Upgrade         $http_upgrade;
    proxy_set_header Connection      "Upgrade";
    proxy_set_header Host            $http_host;
    proxy_set_header X-Real-IP       $remote_addr;
    proxy_set_header X-Forward-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto $scheme;
    proxy_redirect off;
    proxy_pass http://fbserver:8080;
}
```

and here is the config file for fb:

```json
{
  "port": 8080,
  "noAuth": false,
  "baseURL": "/sit/fb",
  "address": "0.0.0.0",
  "alternativeRecaptcha": false,
  "reCaptchaKey": "",
  "reCaptchaSecret": "",
  "log": "stdout",
  "plugin": "",
  "root": "/absolute/path/to/data/folder",
  "scope": ".",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": ["git"],
  "database": "filebrowser.db"
}
```

**Comment by o1egl** [comment]
It looks like your proxy is escaping the request query part and filebrowser recognizes it as part of the request path.

**Comment by Alsan** [comment]
Ok, I'll try your suggestion tomorrow morning, cause the network has been shutdown by the admin, and let's see does it work. Thanks.

**Comment by Alsan** [comment]
I't works, thanks a lot.
