### ISSUE TITLE
before_publish and after_publish not working when starting caddy

### ISSUE THREAD

**Issue by seisman** [filebrowser/filebrowser#109]
```
$ caddy -version                                                                         
Caddy 0.10.2
$ hugo version
Hugo Static Site Generator v0.20.6 linux/amd64 BuildDate: 2017-04-27T16:19:04+08:00
```

### 1. What are you trying to do?

I'm trying to run specific commands before/after hugo generate my website.

### 2. What is your entire Caddyfile?

Below is a simple caddyfile to reproduce this "bug":
```text
:2017
root public
basicauth /admin user pass
hugo {
    before_publish echo "before publishing"
    after_publish echo "after publish"
}
```

### 3. What did you expect to see?

`caddy-hugo` should run `echo "before publish"` and `echo "after publish"` before/after running `hugo`. 
And I expect to see `before publish` and `after publish` on screen output.

### 4. What did you see instead (give full error messages and/or log)?

I didn't see `before publish` or `after publish` on screen when I start `caddy`:
```
$ caddy 
Activating privacy features... done.
http://:2017
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
6 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 2 ms
```
Then I edited some text using the web interface provided by `caddy-hugo`, and clicked the `publish` button, below is the output:
```
before publish
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
6 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 1 ms
after publish
```
Now I got `before publish` and `after publish` on screen output. 

It seems that options `before_publish` and `after_publish` doesn't work for the first run and only works when rebuilding website.

### 5. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

1. generate a minimal hugo site 
    ```
    hugo new site hugo-example
   cd hugo-example/
   ```

2. create `Caddyfile` 

3. run `caddy` and you won't see `before publish` and `after_publish` on screen output.
4. goto `localhost:2017/admin`, edit `config.toml` and click the `publish` button. Now you will see `before publish` and `after_publish` on screen output.

**Comment by hacdias** [comment]
before_publish and after_publish are only run when you publish a _new_ post from the interface and not when the website is generated during the startup of Caddy.
