### ISSUE TITLE
"Command not allowed" when trying to run any command in shell

### ISSUE THREAD

**Issue by studioph** [filebrowser/filebrowser#1092]
**Description**
When opening the shell in the Filebrowser UI, typing any command simply gives error: _"Command not allowed"_
Example: `ls`

**Expected behaviour**
Return the output of the command (i.e. list directory contents in the above example)

**What is happening instead?**
_"Command not allowed"_ gets printed to the terminal

**Additional context**
Docker version 19.03.12, build 48a66213fe
Ubuntu 20.04 LTS
**EDIT**: I should also add that this is with the default admin user and not a user created by filebrowser.
Tried with both `latest` and `debian` images. Did not bother to try with `alpine` since `latest` is already built on `alpine`. Here is a screenshot:
![image](https://user-images.githubusercontent.com/36493057/94055688-52e20300-fdab-11ea-981d-4cd7e28afce1.png)

**How to reproduce?**
Login to the UI in the browser, open the shell, and run any Unix/Linux command.

**Comment by dr-bonez** [comment]
seems to be an issue with websockets.
network tab shows all of these requests returning a 101

**Comment by o1egl** [comment]
Go to `Settings -> Global` and add `ls` into the `Commands` section.

**Comment by studioph** [comment]
Unfortunately, that did not solve the issue. I added `ls` to the `Commands` section. Logged out, then logged back in again. I should also add that this is with the default admin user and not a user created by filebrowser.

**Comment by ramiresviana** [comment]
Global settings only sets default values for new users, not affecting existing ones.

Filebrowser will not allow commands by default, since the command list comes empty. To make commands work, you need to change the settings by user basis, adding allowed commands, or you can set global settings and create a new user.

**Comment by studioph** [comment]
Is there a way to set the default allowed commands in ENV when creating the container or do I need to modify the base image?

**Comment by ramiresviana** [comment]
Filebrowser use config files, similar to ENV files, there is some limitations and it does not have support for the commands parameter. Changing the commands can be done with `filebrowser cli`, using `filebrowser config set` or `filebrowser users update`, more info at https://filebrowser.org/cli. You probably will need to make your own image, using the cli or a pre-configured database file, to have the commands configured.

**Comment by studioph** [comment]
Great, thanks for clarifying and explaining the process. I will go ahead and close the issue.

**Comment by Drun1baby** [comment]
How can I open the shell, I can't find the entry
