### ISSUE TITLE
Hash Routing

### ISSUE THREAD

**Issue by dr-bonez** [filebrowser/filebrowser#1093]
**Is your feature request related to a problem? Please describe.**
The app is very clunky when on a slow connection. 

**Describe the solution you'd like**
With js based frameworks this can be massively improved by switching to hash routing so that each route doesn't have to be fetched from the server.

**Additional context**
I use filebrowser on a Tor hidden service, where this problem is very exaggerated

**Comment by o1egl** [comment]
I'm not sure what are you talking about but the frontend is a SPA app. It doesn't load full html page on each request.

**Comment by dr-bonez** [comment]
correct, however the way it does urls causes the browser to hit the server and fetch an _identical_ index.html for every route. 

basically need to just change https://github.com/filebrowser/filebrowser/blob/1529e796df86e6245e107dabe512fa1841f9d4da/frontend/src/router/index.js#L22 from `history` to `hash`.
but we would also need to change any hardcoded urls in the app to include the hash.

https://router.vuejs.org/api/#mode

**Comment by o1egl** [comment]
Something wrong is happening with your browser. It should't behave like that. Which browser are you using?

**Comment by dr-bonez** [comment]
Tor browser. However it looks like you are right. Firefox doesn't have this issue.
