### ISSUE TITLE
Clicking on a search result doesn't show the file.

### ISSUE THREAD

**Issue by vmxr** [filebrowser/filebrowser#1094]
**Description**
When searching for a file and then clicking on it, the actual file is not shown.

**Expected behaviour**
The file should be displayed. (Black overlay with the "Download" button in the middle.)

**What is happening instead?**
The folder overview is shown. The path indicated is actually the path of the file I was looking for.
When using the browser's arrows to navigate one page back and then one page forward, the expected download view is shown.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
1) Click on "My files"
![image](https://user-images.githubusercontent.com/71821508/94237203-c81a1900-ff0e-11ea-8a2c-264499dac540.png)

2) Search for a document (type name + press enter)
![image](https://user-images.githubusercontent.com/71821508/94237260-dbc57f80-ff0e-11ea-8a93-9a05c8230fc9.png)

3) The search result is shown.
![image](https://user-images.githubusercontent.com/71821508/94237270-e3852400-ff0e-11ea-8408-bfc1b3d9b610.png)

4) Click on the search result.

5) Instead of showing the black page with "Download", the folder structure is shown.
At this point the url is "myservername.com/files/AZ/355607_A05.zip"
![image](https://user-images.githubusercontent.com/71821508/94237286-ed0e8c00-ff0e-11ea-9e73-a5e5e13c4dfc.png)

6) Move one page back using the browser's back arrow.
At this point the url is "myservername.com/files/"
![image](https://user-images.githubusercontent.com/71821508/94237418-234c0b80-ff0f-11ea-8c8d-39f225075624.png)

7) Move one page forward using the browser's forward arrow.
At this point the url is "myservername.com/files/AZ/355607_A05.zip"
![image](https://user-images.githubusercontent.com/71821508/94237492-3eb71680-ff0f-11ea-8b1e-09d312c8fb74.png)

**Configuration**
Firefox 80.0.1 (x86) on Windows 10.
Using Filebrowser latest Docker image with ID:  7683094632db

**Other**
Thank you for this awesome piece of software! :)

**Comment by o1egl** [comment]
Which browser are you using? Can't reproduce it in chrome.

**Comment by vmxr** [comment]
At first: Firefox 80.0.1 (x86) on Windows 10.
Today came the update to Firefox 81.0. The bug is still there tho.

Here is the version information from Firefox:

Name: Firefox
Version: 81.0
Build ID: 20200917005511
Distribution ID:
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
OS: Windows_NT 10.0 18363

**Comment by o1egl** [comment]
Can you reproduce it in chrome?

**Comment by ramiresviana** [comment]
When trying to reproduce this issue i've found that a missing '/' on the end of the url causes issues on search results.

https://github.com/filebrowser/filebrowser/blob/1529e796df86e6245e107dabe512fa1841f9d4da/frontend/src/components/Search.vue#L52

This issue can be related to that, using absolute url should fix it.

**Comment by vmxr** [comment]
I am able to reproduce it with Chrome.
But I noticed I can't reproduce it when connecting directly to FileBrowser. (It's running on port 3100.)
It looks like this behavior is caused by the nginx reverse proxy configuration.

**Comment by vmxr** [comment]
Using Firefox developer tools I see that the requested URL is wrong when it fails.
Fail: "http://myservername.com/files/api/resources//AZ/355607_A05.zip" (Note the double forward slash.)
Success: "http://myservername.com/files/api/resources/AZ/355607_A05.zip"
I didn't notice until now because the URL displayed in the navigation bar is different (no mention of 'api') and always contains a single forward slash.
Still not clear what causes this and why it sometimes works ok, sometimes fails. It doesn't matter whether I'm using Chrome or Firefox.
