### ISSUE TITLE
split permission: Create File and Create Directory

### ISSUE THREAD

**Issue by fdefilippo** [filebrowser/filebrowser#1095]
Split create file and directory so a user can only create file but not directory.

**Comment by o1egl** [comment]
What is the reason for that split?

**Comment by fdefilippo** [comment]
Hi, forbid users to create new directories, I use filebrowser as a transit of inbound and outbound files and users must not be able to create new ones.

thnx.

**Comment by o1egl** [comment]
I don't think that this is a commonly needed feature
