### ISSUE TITLE
Deleting admin user

### ISSUE THREAD

**Issue by carl-sauter** [filebrowser/filebrowser#1097]
**Description**
I tried to remove the admin user in order to keep the login saver

**Expected behaviour**
Admin user removes if there are other admins or cant be removed if there arent other admins

**What is happening instead?**
Error 500 everything got crashed cant see users anymore cant add user

**Additional context**
Maybe the opportunity to disable and not remove the admin user

**How to reproduce?**
delete the admin user

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by o1egl** [comment]
I think there should be at least 1 admin user to manage. As a workaround you can can set a strong password for that user.

**Comment by danielo515** [comment]
I agree that should be at least 1 admin use, but as soon as you create a new user which has admin capabilities I don't see why not allowing to delete the default admin user. This is, IMO, a neat security measure
