### ISSUE TITLE
Allow specifying password with docker-compose or in json config

### ISSUE THREAD

**Issue by nullcount** [filebrowser/filebrowser#1103]
**Describe the solution you'd like**
Some way to update the password hash programmatically. I know how to make a password hash:
```
docker run --rm filebrowser/filebrowser hash mypassword
$2a$10$JpE8CfN8p5zOxTa6GdL71.RuQL2efPu3l6P6jWWCB7NgMq1DAfYgS
```
But how to pass this hash with docker-compose?

**Describe alternatives you've considered**
Similar to #1016 but with a docker-compose setup. I tried the `--password` flag but it does not work for me. How to translate this to docker-compose.

**Additional context**
It feels like something that could go in the `.filebrowser.json` file. e.x. 
```
{
        "port": 80,
        "address": "",
        "password", <HASH_CREATED_BY_FILEBROWSER>
        "root": "/srv",
        "database": "/database.db",
        "allowCommands": false,
        "allowEdit": true,
        "allowNew": true,
        "commands": []
}
```

**Comment by o1egl** [comment]
- `docker run --rm -v /path/to/database.db:/database.db filebrowser/filebrowser hash password`
- `docker run --rm filebrowser/filebrowser --password '$2a$10$cv0rRpdT1az1UMEKVp4zQeyYv9MZQQjh7iKzvhd1UQF1.5Wu.7L1q'`
