### ISSUE TITLE
How to secure filebrowser over HTTPS ?

### ISSUE THREAD

**Issue by tusharsonawanes** [filebrowser/filebrowser#1107]
Hello, I am able to access my filebrowser listening on 3300 on a Public IP over **http**. I want to resolve it over HTTPS. I read about caddy but somehow I am unable to configure it on my dockerized filebrowser. Any help here ? @o1egl

**Comment by o1egl** [comment]
You can use `--cert` and `--key` cli flags to locate your certificate files. Another option would be to use any existing http proxy to handle https

**Comment by arvidortwig** [comment]
Hi, i have successfully installed filebrowser (directly, no container), caddy and set the reverse-proxy setting

Filebrowser is only running if i set the config to "filebrowser config set -a myurl.tld" and start it with "filebrowser -r /srv -p 8080". If i set the address to localhost or 127.0.0.1 it just shows 3 dots in the browser window on http://myurl.tld:8080 as if it tries to load the startpage but without success. 

If I then set the caddy reverse_proxy setting to localhost:8080 it shows nothing on https://myurl.tld. If I set the reverse_proxy setting to myurl.tld:8080 it shows the 3 dots from login again. The http://myurl.tld:8080 is still working during that time.
Any Idea how to make it work through https ?

Thanks,
Arvid

**Comment by o1egl** [comment]
Hi @arvidortwig, `-a` sets the address to listen. It should be IP address, not your domain. If filebrowser and proxy are on the same host I highly recommend you to bind filebrowser to 127.0.0.1 and use public IP only for your proxy server.

**Comment by tusharsonawanes** [comment]
> You can use `--cert` and `--key` cli flags to locate your certificate files. Another option would be to use any existing http proxy to handle https

You mean when I start my docker container, I should start it like this,

```docker run -it -d --name <name> -p 3300:80 -v /root:/srv --cert cert.crt --key cert.key <imagename>```

Right @o1egl ?

**Comment by arvidortwig** [comment]
Hi 

> Hi @arvidortwig, `-a` sets the address to listen. It should be IP address, not your domain. If filebrowser and proxy are on the same host I highly recommend you to bind filebrowser to 127.0.0.1 and use public IP only for your proxy server.

thank you for your answer... i bound filebrowser to 127.0.0.1 and set the caddy proxy address also to 127.0.0.1. Now its showing the 3 dots... it just CSS... nothing else... does filebrowser need any more permissions ?

**Comment by o1egl** [comment]
Do you use custom url mounting point in caddy? If yes then you need to add `--baseurl /some/path` flag

**Comment by tusharsonawanes** [comment]
> Do you use custom url mounting point in caddy? If yes then you need to add `--baseurl /some/path` flag

@o1egl any guide on it ? I am unable to figure out caddy installation for filebrowser

**Comment by o1egl** [comment]
Just mount filebrowser to the root `/` in caddy config and it should work.
