### ISSUE TITLE
Folder permissions

### ISSUE THREAD

**Issue by Spasman** [filebrowser/filebrowser#1109]
It would be nice to be able to set permissions for specific files or folders, but that sounds like a lot of work. At the very least, I think it would do a lot if there was a simple checkbox permission for allowing or disallowing users from downloading entire folders, and only being able to download individual files.

**Comment by o1egl** [comment]
Thanks for the idea but the main goal is to keep the app as simple as possible. Adding folder/file level permissions will make it overcomplicated.
