### ISSUE TITLE
Windows service capability

### ISSUE THREAD

**Issue by Spasman** [filebrowser/filebrowser#1110]
Right now, FileBrowser is unable to work as a Windows service, because it needs to be run from command prompt. Trying to add it as a service through a tertiary shortcut or a batch file makes Windows angry, and it feels like this could be resolved if there was some sort of parameter or trick you could use to override the command prompt only error.

Sorry for blowing up the issues tab, but this is a neat app 💯

**Comment by ramiresviana** [comment]
Cobra library has a hook that dont allow running the program if it was started by the Windows Explorer. @o1egl i think we should disabled it, since Filebrowser does not require any CLI parameter to be initialized.
