### ISSUE TITLE
Only connecting if external ip entered

### ISSUE THREAD

**Issue by MishaOpstal** [filebrowser/filebrowser#1111]
My filebrowser webserver runs on port 8181 and has https enabled.
the bind ip is: 0.0.0.0

It connects using the external ip but keeps being stuck on connecting (in browser) if i enter my hostname and port (https://onthelink.nl:8181). After a while it says that it took too long for a response.

What should i do to fix this?

OS: Windows
My website uses CloudFare with proxied DNS to my external ip
Using cmd with the executing command "filebrowser.exe" to run the webserver

**Comment by ramiresviana** [comment]
The hostname that you are trying to access may be pointing to another server. Check if the hostname resolved IP address is the one you are want to access, you can do that by executing a ping command from a terminal and comparing the IP address provided with that of the machine that is hosting Filebrowser.

**Comment by o1egl** [comment]
I would also check firewall rules on your host machine and router.
