### ISSUE TITLE
Disable file header detection

### ISSUE THREAD

**Issue by agneevX** [filebrowser/filebrowser#1112]
~**Description**~
~I have a mounted cloud drive whose file/folder structure are cached in-memory.
However, FB will take very long to load them, especially if the folder contains many **files**...
For a folder which contains over a thousand sub-folders, it will load them instantly. This is weird.~

~**Expected behaviour**~
~Folders with many files and many sub-directories should load instantly and at the same speed.~

~**What is happening instead?**~
~Loading is slow and NGINX throws HTTP 504.~

---

**Is your feature request related to a problem? Please describe.**
I have cloud drives mounted as FUSE filesystems by rclone.

The entire file structure is entirely cached in-memory, so it would behave like any other filesystem... except File Browser tries to detect the file header of all files in a folder, and as a result, the screen is stuck on `Loading...`. 

As a side effect, a lot of simultaneous API calls are made to the cloud storage provider, causing HTTP 429s.

**Describe the solution you'd like**
Disable file header detection and load files, just like `ls`.

**Describe alternatives you've considered**
None. I can't browse any folder with multiple video files because they're taking too long to load.

**Additional context**
Thumbnails are disabled.

**Comment by o1egl** [comment]
I'm not sure that this issue is related to the filebrowser. It uses standard system syscalls to access filesystem. Supporting cloud storages is out of the scope of this project.

**Comment by agneevX** [comment]
> Supporting cloud storages is out of the scope of this project.

That is not related as it behaves like a normal FS. Is there a way to disable what it tries to access in video files?

**Comment by o1egl** [comment]
No, it's not possible to filter out some files from listing. Can you compare the speed with [nginx file listing](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html) for instance?

**Comment by agneevX** [comment]
Not that. What I'm able to gather is that FB queries video files for certain info. 
I don't see any thumbnails generated but unsure whether its enabled. 

Its because of this querying that the process becomes slow.

**Comment by o1egl** [comment]
It reads file header to [detect](https://github.com/filebrowser/filebrowser/blob/master/files/file.go#L137) it's type. That might be the bottleneck in your case.

**Comment by agneevX** [comment]
Hmm. Maybe the detection could be done after the listing is complete?

**Comment by agneevX** [comment]
I've updated the title and description @o1egl. Please take a look, thanks.

**Comment by sergwx** [comment]
Can be nice to add a flag to ignore mime detection/thumbnails/search.. on custom paths... to work nice with remote mounted fs like s3 or other remote endpoints which requires a lot of api calls for every action..
