### ISSUE TITLE
Unable to access terminal

### ISSUE THREAD

**Issue by agneevX** [filebrowser/filebrowser#1118]
**Description**
I'm unable to access the terminal.

**What is happening instead?**
Browser console

`
WebSocket connection to 'ws://files.home/api/command/?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJsb2NhbGUiOiJlbiIsInZpZXdNb2RlIjoibGlzdCIsInBlcm0iOnsiYWRtaW4iOnRydWUsImV4ZWN1dGUiOnRydWUsImNyZWF0ZSI6dHJ1ZSwicmVuYW1lIjp0cnVlLCJtb2RpZnkiOnRydWUsImRlbGV0ZSI6dHJ1ZSwic2hhcmUiOnRydWUsImRvd25sb2FkIjp0cnVlfSwiY29tbWFuZHMiOltdLCJsb2NrUGFzc3dvcmQiOmZhbHNlfSwiZXhwIjoxNjAyNTE1MDQyLCJpYXQiOjE2MDI1MDc4NDIsImlzcyI6IkZpbGUgQnJvd3NlciJ9.tA5Y0-PqeAO5JOSBTh3i6KAz2V5v_XTzQ37RZcpoX68' failed: Unexpected response code: 400
`

**Additional context**
Using nginx:

```nginx
server {
  server_name files.home;
  location / {
    proxy_pass http://127.0.0.1:9800;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_pass_request_headers on;
    proxy_set_header Connection "keep-alive";
    proxy_store off;
    proxy_read_timeout 600s;
  }
}
```

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by o1egl** [comment]
@agneevX you have to enable websocket proxying for /api/command in your nginx config

**Comment by agneevX** [comment]
For each command?

**Comment by o1egl** [comment]
I'm not familiar with nginx config but I think it should look like:
```
location /api/command {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```
Better would be to check nginx log file.
