### ISSUE TITLE
Chain multiple commands on before_publish and after_publish

### ISSUE THREAD

**Issue by chouzar** [filebrowser/filebrowser#112]
Hi, I'm currently using the http.hugo as a small local cms to edit a webpage. I'm trying to figure out if the before_publish and after_publish parameters accept multiple commands. This is what I'm trying to do:

```text
127.0.0.1:1313
root hugo/public
hugo hugo/ /admin {
  clean_public true
  after_publish git add . && git commit -m "modified content"
}
```

When using the caddy file above my terminal builds the site as normally but after publishing it outputs:

```
error: unknown switch `m'
usage: git add [options] [--] <pathspec>...
```
As if I was trying to pass extra parameters to add. So far it seems these parameters are only intended for a single command, is it possible to chain multiple commands?

**Comment by hacdias** [comment]
I'm making some improvements and this will probably be available in the next release. Thanks for suggesting 😄

**Comment by chouzar** [comment]
Got it, will find a workaround probably with an extra tool :)

But just being curious, Is there a specific intended purpose for the before/after publish commands? It seems that just one command might be limiting. Probably a build script would be more suitable for these parameters?

**Comment by hacdias** [comment]
Hey @chouzar,

Sorry for not answering. I think that you can do an workaround like this:

```
after_publish bash -c 'git add . && git commit -m "modified content"'
```

Could you try, please?

**Comment by chouzar** [comment]
Thanks @hacdias for the tip!

Using on my caddy file:
`after_publish bash -c 'git add . && git commit -m "generic comment"'`

When building my terminal spits:
`error: pathspec 'content' did not match any file(s) known to git.`

But with no spaces in in comments the git command works just fine:
`after_publish bash -c 'git add . && git commit -m "generic-comment"'`

For what I wanted to do this will do just fine :)
For a more involved workflow I will try to find a more generic solution, as necessity arrives.

**Note** that other functions have no issues with white space, for example:
`after_publish bash -c 'echo "spit out some text"'` No error here

**Comment by hacdias** [comment]
I don't know what may be causing that error, but maybe something to do with the single quotes and double quotes, not sure. I think I'll have this improved in the next version, so it will be easier for you to set multiple commands 😄

**Comment by hacdias** [comment]
@chouzar, the new version allows you to set multiple commands (on the global settings page) and they will be executed by order 😄
