### ISSUE TITLE
How to change branding in docker?

### ISSUE THREAD

**Issue by LegendaryB** [filebrowser/filebrowser#1122]
First thank you for this great project. It's really ideal for simple scenarios with a few users.
How can I change the branding when running through docker? For example the logo.svg?

**Comment by tronyx** [comment]
Just create a branding folder inside of the config folder (or wherever you want) and then update the setting for the branding directory within the Global settings. It couldn't be easier.

```
root@suladan:~# ls -la /home/filebrowser/config/branding/
total 88
drwxr-xr-x 3 root root  4096 Oct 15  2019 .
drwxr-xr-x 3 root root  4096 Mar 30  2019 ..
-rw-r--r-- 1 root root  6070 Oct 15  2019 custom.css
-rw-r--r-- 1 root root 60943 Mar 30  2019 logo.svg
```

**Comment by o1egl** [comment]
https://filebrowser.org/configuration/custom-branding

**Comment by LegendaryB** [comment]
Yeah but how can I mount the config folder locally on the host? I don't see any hints about that in the documentation?

**Comment by o1egl** [comment]
Just use `-v` param of docker engine to mount a folder.

**Comment by LegendaryB** [comment]
Yeah but what is the exact mount point? myHostPath/sample:/container-path=?

**Comment by o1egl** [comment]
You can use any mounting point you want and then follow [this manual](https://filebrowser.org/configuration/custom-branding)
