### ISSUE TITLE
Ignoring files and directories as in .gitignore

### ISSUE THREAD

**Issue by NorthHub** [filebrowser/filebrowser#1123]
**Is your feature request related to a problem? Please describe.**
I would not want to display some files/directories in filebrowser such as .env, since I have the http Protocol

**Describe the solution you'd like**
Ability to specify in config.json in the "ignore" parameter a list of patterns with similar logic as in .gitignore

**Comment by o1egl** [comment]
You can use `User Management -> {user} -> Rules` for that.
