### ISSUE TITLE
Frontend-plugin: allow loading customized .js file besides the .css file

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1125]
**Is your feature request related to a problem? Please describe.**
filebrowser is a great project, but currently it is a bit hard to implement frontend plugins, since the front end files are hard-coded in the executable file. 

**Describe the solution you'd like**
Providing an option to load a Javascript file for customization besides the css file.  That would allow frontend plugins to implement their features.

**Describe alternatives you've considered**
Would be better to allow loading all the front-end related assets (htmls, js, css) completely from disk instead of the executable file.

**Additional context**
Frontend plugin could enrich the display or editing of a certain type of file.

**Comment by ghost** [comment]
https://github.com/filebrowser/filebrowser/blob/97693cc6117ce1c956baede91de5dd48b904e175/frontend/public/index.html#L140

https://github.com/filebrowser/filebrowser/blob/ad99bf180197e0e6d82231a86457585de16366a8/http/static.go#L48

**Comment by ghost** [comment]
This could also be helpful to provide thumbnail or preview for other types of files, like pdf(#1008), docx, pptx, and videos.
Indexing and generating thumbnail for such file can be done via an external solution like https://github.com/simon987/sist2, and put into a elasticearch instance, which the user's browser can talk to.

**Comment by ghost** [comment]
This can also be helpful for providing full-text search or fuzzy search, mentioned in #252 #415

**Comment by ramiresviana** [comment]
You will have a bad time trying to extend an shipped Vue.js application by just incorporating a javascript file into the page, just a bit of the original project code will be available and lots of unreadable code. The project is not so complex that requires an extension system, you can add features just by creating a fork of it.

**Comment by ghost** [comment]
I am using a fork with some dirty hacks to get sist2 integrated into the search box of filebrowser. I just thought someone would also be interested in doing similar stuff in filebrowser. Yes you're right, it's easier to make a fork.

**Comment by o1egl** [comment]
I think we can close this issue
