### ISSUE TITLE
Upload larger files than 1MB

### ISSUE THREAD

**Issue by eVo93** [filebrowser/filebrowser#1130]
How is it possible to upload larger files than 1MB. I allways get 413 Request Entity Too Large error.
Im using docker filebrowser/filebrowser:alpine image

**Comment by swrap** [comment]
If you are using nginx or apache as a reverse proxy, you might have to change their [settings](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/)
