### ISSUE TITLE
Unable to view large log files

### ISSUE THREAD

**Issue by joeynaor** [filebrowser/filebrowser#1132]
**Description**
Viewing large sized .log files (25MB) is not possible

**Expected behaviour**
Allow users to choose wether or not large files can be viewed

**What is happening instead?**
The UI offers to download the file instead of viewing it

**How to reproduce?**
1. Open filebrowser in a dir with 2 log files, one is small (few lines) and one is large (25MB)
2. In UI, double click each of the files
3. Small files can be viewed, large one can only be downloaded

If there's a possibility to enable this feature, kindly let me know

Using version 2.9.0

**Comment by o1egl** [comment]
I think from the UX perspective it's not wise to open all text files in the browser. What if the size is 200mb, 200gb... There are proper tools for reading large files on client side. So we've chosen 10MB as an optimal limit.

**Comment by nambrosch** [comment]
@o1egl I think what @joeynaor means is checking the size of the log file and if it's larger than that defined size filebrowser will tell the user "file to large to view in browser, would you like to download instead?"

**Comment by joeynaor** [comment]
@o1egl I was referring to what @nambrosch described (individual file viewing)

**Comment by o1egl** [comment]
I got it. At the moment we allow to open/edit text files up to 10mb and it is not configurable.

**Comment by joeynaor** [comment]
Thank you for the explanation @o1egl. I will attempt to increase the 10MB threshold and rebuild the project.
