### ISSUE TITLE
504 Gateway Time-out when copying some files

### ISSUE THREAD

**Issue by Eddie563** [filebrowser/filebrowser#1135]
![gatewaytimeout](https://user-images.githubusercontent.com/71386686/98206373-b24a3b80-1f31-11eb-8485-b1752f6e1b92.png)
**Description**
Trying to copy from local drive to a mounted GDrive via rclone but receive 504 Gateway Time-out

**Expected behaviour**
Copy with success as most of my files do but occasionally it throws the error

**What is happening instead?**
partial copy and 504 Gateway Time-out error

**Comment by o1egl** [comment]
I'm not sure what you are trying to do and how gdrive and rclone are related to filebrowser.

**Comment by Eddie563** [comment]
thanks for taking the time to respond.

I am simply selecting a file, using the copy feature and moving it to another drive. if i use the cli and either copy or rsync there are no issues. if i use another copy method in rutorrent lets say,  it copies fine. if i copy using filebrowser it gives me that error. it is intermittent.

gdrive and rclone are not related to filebrowser but i mentioned them for clarity of my setup, nothing more.

**Comment by o1egl** [comment]
Can you share the logs?

**Comment by Eddie563** [comment]
seems it was an issue when connected with VPN. not a filebrowser issue.

**Comment by PrzemekSkw** [comment]
I have the same issue when copy only when access Filebrowser with my https domain setup trough Nginx Proxy Manager.
