### ISSUE TITLE
It is better to use multipart/form-data to upload files

### ISSUE THREAD

**Issue by YoungerLee** [filebrowser/filebrowser#1137]
The encoding type **application/x-www-form-urlencoded** is inefficient for sending large quantities of binary data or text containing non-ASCII characters.  Thus, a new media type, **multipart/form-data**, is proposed as a way of efficiently sending the
values associated with a filled-out form from client to server.

**Comment by ramiresviana** [comment]
The file upload process in Filebrowser do not make use of forms. Can you provide more information about how those encoding types are being used in Filebrowser?
