### ISSUE TITLE
Wrong Credentials (but they are correct)

### ISSUE THREAD

**Issue by Eddie563** [filebrowser/filebrowser#1142]
**Description**
Issue logging in behind reverse proxy (NGINX)

**Expected behaviour**
Login correctly

**What is happening instead?**
Wrong Credentials - log only shows

2020/11/10 08:54:09 /api/login: 403 [Redacted IP] <nil>

nothing else is contained in the log, i have looked at the bug listed here about basic auth and no auth but i could not fathom it.

**Additional context**
Have 3 Ubuntu servers in the same configuration, filebrowser is installed by using a script which insalls Swizzin seedbox. 2 are clean installs of Ubuntu 20.04 LTS and work perfectly. the one that does not work was an upgrade from 18.04 to 20.04.

**How to reproduce?**
install ubuntu 18.04, upgrade to 20.04, install swizzin seedbox and select filebrowser

i am comfortable navigating the file system via CLI, but i am not experienced in terms of authentication methods etc.

![wrong credentials](https://user-images.githubusercontent.com/71386686/98647045-2b7bd100-232c-11eb-8fa1-ed8cb9d50340.png)

**Comment by o1egl** [comment]
You can reset the password with `filebrowser users update <username> -p <new password>`. 
I checked that swizzin puts config to `/home/${username}/.config/Filebrowser/filebrowser.db`. So the end command should look like `filebrowser -d /home/${username}/.config/Filebrowser/filebrowser.db users update <username> -p <new password>`

**Comment by Eddie563** [comment]
but the username and password are correct, the swizzin user has access to all applications installed with nginx, and its 1 server not working. so im not sure filebrowser password reset would work.

**Comment by o1egl** [comment]
Filebrowser is not using your system user/password. So, this error says that the password in the db does not match. I would suggest you to check the exact db path with which your filebrowser is running and set the password you want.

**Comment by Eddie563** [comment]
Hi, i have tried to run the following command

filebrowser -d /home/shaggy/.config/Filebrowser/filebrowser.db users update shaggy -p [Redacted Password]

but it just times out. 

I have run filebrowser -d /home/shaggy/.config/Filebrowser/filebrowser.db users update ls to see what users exist

but again, that just returns timed out

**Comment by o1egl** [comment]
The db file is locked by running filebrowser. You have to stop the service before running this command.

**Comment by Eddie563** [comment]
Thanks, ok, so i had zero users, not even an admin which was strange, i have created the first user but seems it is not an admin by default, i will go look at the documentation now to find out how i achieve this, thanks for getting me this far. very strange my other two servers had no issues.

**Comment by Eddie563** [comment]
just to follow up, i have done some testing today and it seems its the password that causes this. its no longer being used but this was the password. seems when ever it was used, filebrowser barks about the bracket on the end, once that is removed it then barks about the hyphen at the start.

-7HCBH?XP^rK<>^)

did not like it, so i will avoid that complexity in the future.

**Comment by ghost** [comment]
***Solution***

At First StartUp Program Starts Without A User Fummy Ryt But It The Reality Now Do this 2 step before u start it

Ofc cd into personally preferred dir

`filebrowser config init`
`filebrowser users add` (user_name) (pass_wd)

Note The user u will crete isn't goin to be a admin add extra corresponding flags as per ur needs

I'll be glad for Normy's if thay understand this

**Comment by edukaluz** [comment]
Still no solution? I can't find how to change the admin password....
