### ISSUE TITLE
Database path in config? Config being ignored?

### ISSUE THREAD

**Issue by Darthagnon** [filebrowser/filebrowser#1144]
**Description**
I'm trying to run Filebrowser with static database and branding paths, but variable root folder. Use case: From the context menu in any folder on my Windows PC, I can ```Right-click``` >> ```Send to``` >> [Batch file to launch filebrowser]. Alternatively, I might run it from the CLI via ```filebrowser``` (I have added it to PATH. I want persistent users, branding, and 1 database file. I've figured out how to put most of the paths in the config, but on launch I still have to specify the long paths to the config file and database, as Filebrowser doesn't seem to read config files placed next to the EXE.

**Expected behaviour**
1. Filebrowser should read "filebrowser.json" placed next to filebrowser.exe
2. There should be somewhere to specify the database path in the config; I can't find it 😭

**What is happening instead?**
1. Filebrowser, when launched without arguments from the CLI  always says "No config file used". This occurs whether launching from another folder (via PATH) or from filebrowser.exe's root folder.
2. I can't find any way to specify the database path in the config.

**Comment by Darthagnon** [comment]
I can currently work around launching Filebrowser from the context menu by putting the following in a batch file and placing that in ```shell:SendTo```:
```filebrowser.exe --config "E:\Program Files\Portables\filebrowser\filebrowser.json" --database "E:\Program Files\Portables\filebrowser\filebrowser.db"```

This cannot be done very easily on the CLI...

**Comment by ramiresviana** [comment]
Filebrowser reads database and configuration files from the current working directory.

**Comment by Darthagnon** [comment]
Guess that makes sense; I'd misunderstood that it would check the folder around the binary first. I've found I can also set environment variables to set the paths, to simplify the the scripts, if necessary.
