### ISSUE TITLE
Store thumbnails in database

### ISSUE THREAD

**Issue by acc557** [filebrowser/filebrowser#1145]
**Is your feature request related to a problem? Please describe.**
filebrowser writes thumbnail images as .jpg files on disk. It may become slow to load and hard to move when the folder gets very large.

**Describe the solution you'd like**
Store thumbnails in a database, like lmdb. Purging the cache will be instantaneous.

**Comment by o1egl** [comment]
I think with that solution images fetching speed will drop significantly
