### ISSUE TITLE
Set Permissions on uploaded/created files/directories

### ISSUE THREAD

**Issue by johnnyq** [filebrowser/filebrowser#1146]
Is there a way to set the owner and group permission upon upload and file/directory creation

for example I have Unix users and I also have the same users on filebrowser

So when user jimmy uploads a file or creates a file or directory it will set the permission to  Owner: jimmy rwx --- ---

I use this is conjunction with Samba

and it always sets the user to root

Is this even possible, if so what the best way of going about this.

Thanks Awesome Simple Clean Project and great community!!

**Comment by o1egl** [comment]
You can change the user under which filebrowser app is running but you can't map system users to filebrowser users.

**Comment by fdefilippo** [comment]
Hi, if you run filebrowser as root user you can handle this with "command runner" just write a simple script that change the owner of the file.

**Comment by alexandresoro** [comment]
Hi,

Sorry to jump on this one.
Indeed, the command runner event seems the way to go, and "chowning" seems to work fine on files. 
However, it seems that when creating a folder directly via the UI, no event seems to be triggered and the folder gets owned by "root".
Is this expected, and if so, any clue on how to change the owner for folders like it is done for files?

Thanks for your awesome app!

**Comment by alexandresoro** [comment]
If I get it correctly from the code here : https://github.com/filebrowser/filebrowser/blob/e8c9d1c53989b4b52f6fba2a8ac41ae612c03a7c/http/resource.go#L112

The RunHook that takes care of the commands is not run when creating a directory, so it makes sense that no event is triggered in that case today.

Would it make sense to add a new event on "folder creation"?
