### ISSUE TITLE
Setting up proxy-auth using the official docker image

### ISSUE THREAD

**Issue by 9SMTM6** [filebrowser/filebrowser#1147]
When using the official image I've not found any nice way of setting up proxy-auth. Setting other things  may also be problematic.

The issue is that a few things come together:
* Some settings seem not to be available in the GUI settings
* there is no official documentation on the settings.json format, keys etc.
* you have no obvious access to the filebrowser command in docker
  * the command line in the docker container apaprently has no access to the filebrowser command, even after allowing it in the settings
  * the container seems to be distroless, so if you execute things using i.e. docker execute, you have a difficulty finding around because you dont have any of your known commands available

The only way I can think of as a result is downloading the executable itself somewhere, starting the server, creating a config with the required settings in there and then use that config in the docker image.

While I can do this on an individual level I think this is not the desired usability of this project. As fr as ways out of this situation go, I can think of a few ways you could solve them:
* Document the settings.json format
* create a GUI for the authorization part (could be problematic if you want to add further kinds with other settings)
* somehow allow access to the config creation without having to download and execute a local version of filebrowser
  * i.e. by creating a config cli tool
  * or by creating an documented way to acess the filebrowser CLI in docker
  * or maybe some website that has filebrowser running, i.d.k., there's a lot of things to think of, many of them dont seem desirable.

**Comment by o1egl** [comment]
The workaround is to mount database.db file from your host machine. Then you can use that file to set all required settings using docker image.

- `docker run --rm -it -v /path/to/database.db:/database.db filebrowser/filebrowser <your commands>`
- `docker run --rm -it -v /path/to/database.db:/database.db -p 8080:8080 filebrowser/filebrowser`

**Comment by 9SMTM6** [comment]
Ah, okay, so you dont issue the `filebrowser` command explicitly, thats why that didnt work when i tried it.

Yeah that seems like a good way. Now if only the documentation would show that, I wouldnt have had an issue. I'd issue an MR myself, but frankly I just dont have the time for that right now.

**Comment by o1egl** [comment]
I think we can close the issue
