### ISSUE TITLE
Can it still be used as a middleware?

### ISSUE THREAD

**Issue by phanirithvij** [filebrowser/filebrowser#1153]
I've noticed the docs for [filebrowser.v2](https://pkg.go.dev/github.com/filebrowser/filebrowser/v2) say nothing regarding middleware. I've tried looking at existing issues but couldn't find any. (I might've missed it)

Can filebrowser still be used as a middleware?

----

**Comment by o1egl** [comment]
No, it only can be used as a standalone app.

**Comment by FabioLolix** [comment]
Need to update repo description then :)
![filebrowser](https://user-images.githubusercontent.com/19638095/103097252-03f47580-4607-11eb-98f2-a485bd68d5f6.png)
