### ISSUE TITLE
Allow show loginpage to be configurable when using proxy auth

### ISSUE THREAD

**Issue by phanirithvij** [filebrowser/filebrowser#1154]
**Is your feature request related to a problem? Please describe.**
Allow configuring the availability of the login page when using proxy auth.
That way we need not build a new UI for authentication and can use the same UI but with an external auth (handled by reverseproxy)

**Describe the solution you'd like**
Now it's always false but add a `config set --auth.proxy.showLogin` so it can be enabled
https://github.com/filebrowser/filebrowser/blob/dcbc3286e20aca45a605a3cc8ba741f1fa251424/auth/proxy.go#L33

**Describe alternatives you've considered**
Need to build a login UI, which is not hard but might not be needed when auth is simple user pass, so reusing the UI works :)

**Additional context**

**Comment by o1egl** [comment]
I don't understand how do you want to use filebrowser login as a proxy auth login page? With proxy auth unauthorized user shouldn't get access to the filebrowser.

**Comment by o1egl** [comment]
Your proxy must control user authentication

**Comment by phanirithvij** [comment]
Sorry I couldn't find any examples on how to implement it or how a proxy should behave exactly in this case.
 I was doing something like

```go
// create new server running on `:80`
go func() {
    // map all /admin/* to a handler
    // that handler forwards any request to filebrowser exactly, then forwards the response from filebrowser back to the client
    // Kind of acting like a proxy (not a system-wide one)
    // So essentially maps :80 -> :8080 (filebrowser default port) to show the filebrowser to the users on the same port
    reg.HandleFunc("/admin/*", fileBrowser)

    // serve other handlers like /about, /service1 /api/v1/... etc..
    // reg.HandleFunc("/api/v2", apiV2)
    ...
    err := http.ListenAndServe(":80", reg)
}()

// start the filebrowser instance via exec.Command with flags
// set config
cmd := exec.Command("filebrowser", "config", "set", "--auth.method=proxy", "--auth.header="+"X-App-Username")
...
// filebrowser -r storageDir -b /admin
cmd = exec.Command("filebrowser", "-r", dirname, "-b", "/admin/")
...
```

I had auth in the `fileBrowser` handler with conditions like `if req.Method == "POST" && strings.Contains(req.URL.Path, "/login")` and add the `X-App-Username` header if user exists in the custom external user database.

So allowing a flag with `--auth.proxy.showLogin` works perfectly.

I now see that a proxy is not that simple as I thought it to be.

**Comment by phanirithvij** [comment]
I did implement the flag in my fork 
https://github.com/phanirithvij/filebrowser/commit/a76e5fa6d85c9850e4ed098a77b305fadf036986 https://github.com/phanirithvij/filebrowser/commit/3ffb392dc0d7633475ea2ac305b3eff75dd66d09
But now I'm not sure if it's stupid :(

**Comment by o1egl** [comment]
I still don't understand how filebrowser's login page can be connected to proxy auth. In proxy auth mode your user is already authorized in your proxy server. So no need to display any login page.

**Comment by phanirithvij** [comment]
Sorry for not clearly clarifying 😥.

I intend to use the login page of filebrowser itself to get the username and password, intercept the request, authenticate and forward the username header to filebrowser.

Filebrowser is not behind a proxy but I'm intending to use it as a middleware (As it's not possible normally in v2)
Given my use case, the only authentication method that works is proxy so I use the flags to set it but not use any proxies per se.

Filebrowser is exposed to public users via the server and it's not my intention to block unauthenticated users who are not in the server database, from using it.

This way I can have two types of users:
- Those who register separately via the filebrowser so they can store their files and use it as normal cloud storage and 
- Those who have already signed up and are on the server can use it to manage their data which will only allow deleting, renaming no creating (custom rules).

I don't have a proxy or authentication implemented. The proxy I've implemented as I mentioned above is a simple port forwarding in go itself, I'm not using any Nginx, apache, goproxy, etc. tools for setting up proxies.
 
I just realized I mentioned `reverseproxy` in the issue 😓, but I don't clearly know what it means and I'm not using it.

**Comment by o1egl** [comment]
Under proxy I mean any service which proxies user request to filebrowser. It's not possible to have multiple accounts authorized at the same time. The idea of proxy auth is to have some kind of service which accepts all user queries, does all the checks and forwards user to the filebrowser only if the user is authorized. So displaying login page in that case doesn't make any sense

**Comment by phanirithvij** [comment]
@o1egl Thanks for the explanation.
I need your help understanding this, could you please spare a few minutes for clarifying it?

I have an implementation that uses the flag `--auth.proxy.showLogin`

[phanirithvij/fate](https://github.com/phanirithvij/fate)

Could you please try running it once?

Tested on Windows and Linux. (me no macOS)
Might need Tdm-gcc or msys2 with gcc on windows for go SQLite drivers.

I understand that the purpose of the proxy is different than that of middleware but as I said there's no middleware functionality so I'm creating bindings.

**Comment by phanirithvij** [comment]
My own fork works for me now.
