### ISSUE TITLE
Enhanced log

### ISSUE THREAD

**Issue by alex2ndg** [filebrowser/filebrowser#1156]
**Is your feature request related to a problem? Please describe.**
Nope, no problem. just a feature request.

**Describe the solution you'd like**
I'd like to see on the log when an user logs in, logs out, open, edit, delete, upload and uploads or downloads a file or folder

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by o1egl** [comment]
Will be added in next major release
