### ISSUE TITLE
Option to disable right-click per user profile

### ISSUE THREAD

**Issue by alex2ndg** [filebrowser/filebrowser#1157]
**Is your feature request related to a problem? Please describe.**
An user with specific permissions shouldn't be able to copy/paste specific file contents.

**Describe the solution you'd like**
As we cannot block the control-c/control-v on the browser per-se, i'd like that there is a new permission that locks the right click of the user on the session for not being able to copy the information of the file.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by ramiresviana** [comment]
That request is out of the context of this project. Blocking the default context menu from browsers can be frustrating to users and a weak way of protecting information, being easy to bypass.

**Comment by alex2ndg** [comment]
Agreed that it's easy to bypass or frustrating, but still something nice to have as a quick stopper. I would add it directly to the code if I knew where the code resides but I don't know where it's deployed when running.

Would you care to tell me this and then I'd close the ticket?
Thanks.
