### ISSUE TITLE
Autostart on boot

### ISSUE THREAD

**Issue by mishailovic** [filebrowser/filebrowser#1158]
Hey! How can I make the filebrowser start automatically when my device starts?

**Comment by stvrly** [comment]
I followed the steps in issue #453 to create a systemd service. Works fine.

**Comment by mishailovic** [comment]
Thank you! I think this is need to be placed in the docs, any chance @o1egl ?

**Comment by o1egl** [comment]
I think it is a general stuff which applies to all the services that you have on your host machine. You can make a PR with linux/windows/docker solutions there https://github.com/filebrowser/docs
