### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by pizixi** [filebrowser/filebrowser#1162]
1、The shared folder cannot preview the file list. It can only be downloaded

2、Non administrator users cannot have multiple folder permissions

**Comment by o1egl** [comment]
1. Is in the master branch. You can build it yourself or wait for the next release.
2. What do you mean? We don't have folder permissions concept.

**Comment by pizixi** [comment]
![image](https://user-images.githubusercontent.com/56673215/100422799-eeeafc00-30c5-11eb-8cab-acbf1b3ce9b3.png)

Is it possible to add more Scopes to a new user ？

**Comment by pizixi** [comment]
Thanks for the shared folder file preview. Can I download a file in the folder instead of all the folders, like this ：
![image](https://user-images.githubusercontent.com/56673215/100427107-e813b780-30cc-11eb-91f7-becef1d9983b.png)

**Comment by o1egl** [comment]
@pizixi it's not possible to add multiple scopes to the user.

**Comment by o1egl** [comment]
Follow #1184 for shared subfolder downloads
