### ISSUE TITLE
Add external folder to the root folder to share

### ISSUE THREAD

**Issue by vbaros** [filebrowser/filebrowser#1163]
**Describe the solution you'd like**
Add additional folders to be visible in the web interface which are not created under /srv

It would be nice if a user could add additional folders to be see by the users.

**Comment by o1egl** [comment]
You can change the root folder with `--root` param

**Comment by vbaros** [comment]
I wanted to avoid giving filebrowser app default access to the whole drive. I want to control exactly which folders are added.

**Comment by o1egl** [comment]
Multiple mounted user folders is a feature for the next major release. I have it in my backlog. But we don't plan to add multiple global app roots

**Comment by vbaros** [comment]
What actually works right now, at least on Synology is symlinking another folder (using terminal). After restarting the filebrowser container it actually appears in the web interface. This is ok but I would like to have an option to control it from the UI somehow.

**Comment by o1egl** [comment]
I think that feature is out of the scope of this project.
