### ISSUE TITLE
RPi4 + AP + FileBrowser?

### ISSUE THREAD

**Issue by Villmer** [filebrowser/filebrowser#1165]
**Details:**
We are using a Raspberry Pi Compute Module 4 with a custom carrier board.
We are running a headless (Lite) version of Raspberry Pi OS (no desktop environment).
We have RaspAP installed, which creates a local WiFi Access Point (Hotspot) that users connect to (From tablet, etc)
We also have FileBrowser installed.

When a user connects to the hotspot (raspberrypi.local), it will launch index.html from the var/www/html directory.

**Question**:
How do we access the FileBrowser page from this index.html file? What url / src?

On a normal Raspberry Pi 3, with desktop, we could:
1. install Filebrowser
2. run filebrowser -r /var/www/html
3. Open chromium (on RPi3) and enter http://127.0.0.1:8080
4. This would successfully open FileBrowser.

**Current Setup**
Using a tablet, phone etc..
1. User connects to local hotspot running on Raspberry Pi
2. User opens browser (chrome, safari) on device (tablet, phone, PC)
3. They enter  **raspberrypi.local**  to load the index.html page
4. This html page **will load** in their browser
5. However, FileBrowser **will not** load in the html’s iframe (127.0.0.1:8080)
6. We’ve tried various src urls for the iframe (without success)

**(See below)**

```
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Load FileBrowser</title>
<style>
     body{ height:100%; width:100%; outline: none; margin: 0px;}
</style>
</head>
<body>
<iframe id="iframe" style="border:none;;width:100%;height:100%;background:#323232;"></iframe>  
<script>
    window.onload=init;
    function init(){
        /* 
         tried src = 
        "127.0.0.1:8080"
        Raspberrypi.local:8080
        document.location.host+':8080'
        "10.3.141.1:8080" (address = raspberrypi.local)
       */
        document.getElementById('iframe').src="127.0.0.1:8080" }
</script>
</body>
</html>
```

**Thoughts:**
Could be a conflict with the server running the hotspot... (8080?)
Tried running FileBrowser on port 8090
CLI:
```
filebrowser -p 8090 -r /var/www/html
2020/11/23 15:08:44 No config file used
2020/11/23 15:08:44 Listening on 127.0.0.1:8090
```

Still not working in iframe regardless of source:

```
// "127.0.0.1:8090"
// document.location.host+':8090'
document.getElementById('iframe').src="127.0.0.1:8090"
```

Didn’t work.

**Comment by Villmer** [comment]
We also tried accessing FileBrowser via src=“raspberrypi.local:8080”

**Comment by Villmer** [comment]
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Load FileBrowser</title>
<style>
body{
    height:100%;
    width:100%
    outline: none;
    margin: 0px;}
</style>
</head>
<body>
<iframe id="iframe"  class="" style="border:none;;width:100%;height:100%;background:#323232;"></iframe>  
<script>
    window.onload=init;
    function init(){
        // "127.0.0.1:8080"
        // document.location.host+':8080'
        // "10.3.141.1:8080"
        document.getElementById('iframe').src="127.0.0.1:8080" }
</script>
</body>
</html>

**Comment by Villmer** [comment]
We have a new x.html file running on the CM4 accessed via raspberrypi.local/x.html
Nothing has worked


<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Load FileBrowser</title>
<style>
body{
    height:100%;
    width:100%
    outline: none;
    margin: 0px;}
</style>
</head>
<body>
<iframe id="iframe"  class="" style="border:none;;width:100%;height:100%;background:#323232;"></iframe>  
<script>
    window.onload=init;
    function init(){
        // "127.0.0.1:8080"
        // document.location.host+':8080'
        // "10.3.141.1:8080"
        document.getElementById('iframe').src="127.0.0.1:8080" }
</script>
</body>
</html>

**Comment by Villmer** [comment]
Also tried :
“127.0.0.1:8080"
document.location.host+':8080'
"10.3.141.1:8080"

**Comment by Villmer** [comment]
Here is what we’ve tried:

```


<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Load FileBrowser</title>
<style>
body{
    height:100%;
    width:100%
    outline: none;
    margin: 0px;}
</style>
</head>
<body>
<iframe id="iframe"  class="" style="border:none;;width:100%;height:100%;background:#323232;"></iframe>  
<script>
    window.onload=init;
    function init(){
        // "127.0.0.1:8080"
        // document.location.host+':8080'
        // "10.3.141.1:8080"
        document.getElementById('iframe').src="127.0.0.1:8080" }
</script>
</body>
</html>
```

**Comment by Villmer** [comment]
Ok. Tried running FileBrowser on port 8090
CLI:
```
filebrowser -p 8090 -r /var/www/html
2020/11/23 15:08:44 No config file used
2020/11/23 15:08:44 Listening on 127.0.0.1:8090
```

Still not working in iframe regardless of source:

```
// "127.0.0.1:8090"
// document.location.host+':8090'
document.getElementById('iframe').src="127.0.0.1:8090"
```


Didn’t work.

**Comment by Easy1999** [comment]
127.0.0.1 is localhost, you need to replace with RPi4's IP, using command “ifconfig”, you can see the IP of eth0, make sure that your phone/tablet and RPI4 in the same LAN. This issue is not related to filebrowser, you need to learn more about the Internet.

**Comment by w2035** [comment]
> **Details:**
> We are using a Raspberry Pi Compute Module 4 with a custom carrier board.
> We are running a headless (Lite) version of Raspberry Pi OS (no desktop environment).
> We have RaspAP installed, which creates a local WiFi Access Point (Hotspot) that users connect to (From tablet, etc)
> We also have FileBrowser installed.
> 
> When a user connects to the hotspot (raspberrypi.local), it will launch index.html from the var/www/html directory.
> 
> **Question**:
> How do we access the FileBrowser page from this index.html file? What url / src?
> 
> On a normal Raspberry Pi 3, with desktop, we could:
> 
> 1. install Filebrowser
> 2. run filebrowser -r /var/www/html
> 3. Open chromium (on RPi3) and enter http://127.0.0.1:8080
> 4. This would successfully open FileBrowser.
> 
> **Current Setup**
> Using a tablet, phone etc..
> 
> 1. User connects to local hotspot running on Raspberry Pi
> 2. User opens browser (chrome, safari) on device (tablet, phone, PC)
> 3. They enter  **raspberrypi.local**  to load the index.html page
> 4. This html page **will load** in their browser
> 5. However, FileBrowser **will not** load in the html’s iframe (127.0.0.1:8080)
> 6. We’ve tried various src urls for the iframe (without success)
> 
> **(See below)**
> 
> ```
> <!DOCTYPE HTML>
> <html>
> <head>
> <meta charset="utf-8">
> <title>Load FileBrowser</title>
> <style>
>      body{ height:100%; width:100%; outline: none; margin: 0px;}
> </style>
> </head>
> <body>
> <iframe id="iframe" style="border:none;;width:100%;height:100%;background:#323232;"></iframe>  
> <script>
>     window.onload=init;
>     function init(){
>         /* 
>          tried src = 
>         "127.0.0.1:8080"
>         Raspberrypi.local:8080
>         document.location.host+':8080'
>         "10.3.141.1:8080" (address = raspberrypi.local)
>        */
>         document.getElementById('iframe').src="127.0.0.1:8080" }
> </script>
> </body>
> </html>
> ```
> 
> **Thoughts:**
> Could be a conflict with the server running the hotspot... (8080?)
> Tried running FileBrowser on port 8090
> CLI:
> 
> ```
> filebrowser -p 8090 -r /var/www/html
> 2020/11/23 15:08:44 No config file used
> 2020/11/23 15:08:44 Listening on 127.0.0.1:8090
> ```
> 
> Still not working in iframe regardless of source:
> 
> ```
> // "127.0.0.1:8090"
> // document.location.host+':8090'
> document.getElementById('iframe').src="127.0.0.1:8090"
> ```
> 
> Didn’t work.

127.0.0.1 is localhost, you need to replace with RPi4's IP, using command “ifconfig”, you can see the IP of eth0, make sure that your phone/tablet and RPI4 in the same LAN. This issue is not related to filebrowser, you need to learn more about the Internet.

**Comment by Villmer** [comment]
```
ifconfig
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:7b:a3:d5  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 1160 (1.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 1160 (1.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.3.141.1  netmask 255.255.255.0  broadcast 10.3.141.255
        inet6 fe80::6b03:b773:d193:89a1  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:74:f2:6c  txqueuelen 1000  (Ethernet)
        RX packets 1570  bytes 216496 (211.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1502  bytes 185925 (181.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

We’ve tried:
document.getElementById('iframe').src="10.3.141.1:8090" = NO

**Comment by w2035** [comment]
> ```
> ifconfig
> eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         ether b8:27:eb:7b:a3:d5  txqueuelen 1000  (Ethernet)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 0  bytes 0 (0.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 4  bytes 1160 (1.1 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 4  bytes 1160 (1.1 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.3.141.1  netmask 255.255.255.0  broadcast 10.3.141.255
>         inet6 fe80::6b03:b773:d193:89a1  prefixlen 64  scopeid 0x20<link>
>         ether b8:27:eb:74:f2:6c  txqueuelen 1000  (Ethernet)
>         RX packets 1570  bytes 216496 (211.4 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1502  bytes 185925 (181.5 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> ```
> 
> We’ve tried:
> document.getElementById('iframe').src="10.3.141.1:8090" = NO

document.getElementById('iframe').src = "http://10.3.141.1:8090"

**Comment by Villmer** [comment]
document.getElementById('iframe').src="http://10.3.141.1:8090" = NO

**Comment by Villmer** [comment]
We got it.
The answer was actually related to the initial implementation of FileBrowser. 
You need to explicitly tell FileBrowser to use the CM4 IP address with 8060 when launching it, like so:

`filebrowser -a 10.3.141.1 -p 8060 r /var/www/html`
