### ISSUE TITLE
Can not move files between 2 volumes

### ISSUE THREAD

**Issue by lilhater** [filebrowser/filebrowser#1177]
I have 2 hard drive volumes that are both mounted to /srv/. 
One is /srv/Main/ and the other is /srv/ExternalUSB/.

When using the "Move" functionality, a red box with the error "500 Internal Server Error" appears in the bottom corner.

The logs also show this error:
/ExternalUSB/file.txt: 500 192.168.0.10 rename /srv/ExternalUSB/file.txt /srv/Main/file.txt: invalid cross-device link

I notice that "rename" is used and not "mv". Is this by design?
Is this feature unsupported at this stage?

**Comment by o1egl** [comment]
rename is just an api call name. I think you have some issues with device mounting. Can you run try to run mv command from cli within container?

**Comment by thomasesr** [comment]
I have the same issue when moving files between two different ZFS datasets mounted as folders inside a jail on FreeBSD. Since ZFS datasets are effectively different filesystems it throws the same error. I tried using the mv command from the console and it works normally.

**Comment by lilhater** [comment]
Hi and thanks for your quick response.

My volumes are XFS and I am using an Unraid NAS which I believe is based on Slackware Linux.
I have just confirmed that I can mv files between the volumes using the Unraid OS.

I want to try moving the files using the cli within the container but could not reach the cli using the following method.

I tried my usual way of running a bash shell using:
_# docker exec -it filebrowser2 bash_

This gave me the following error:
_OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown_

I tried changing the command to just be a basic ls but this didn't work either:
_# docker exec -it filebrowser2 ls
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"ls\": executable file not found in $PATH": unknown_

This was the same for all the commands I used including mv.

@o1egl, Is there another way to try the mv command from the cli within the container?

**Comment by o1egl** [comment]
FileBrowser uses rename syscall to quickly move files and it doesn't work across devices. The workaround is to create a complete copy of the file and remove the original one.

**Comment by o1egl** [comment]
@lilhater `filebrowser/filebrowser` is build from scratch. To be able to use the console you need to run `filebrowser/filebrowser:alpine` or `filebrowser/filebrowser:debian` image

**Comment by lilhater** [comment]
Ah, thank you for looking into this further @o1egl. And thanks for letting me know about how to get the consoles working.

I believe mv would perform a rename where the volume is the same. 
It would also have the added benefit of moving across volumes.
However, there must be a good reason filebrowser is using rename instead...

I understand the work around and I've thought of it too, but it seems like an extra step.

**Comment by o1egl** [comment]
I think we can try to make a copy if rename returns an error.

**Comment by lilhater** [comment]
Yes, the copy function is working fine for me across these volumes using the feature from the FileBrowser webui.

**Comment by Joyace** [comment]
I also encountered the same problem

**Comment by mebtte** [comment]
Does this problem still? I also get this error on `File Browser v2.23.0/02db83c7`.

**Comment by bastus1986** [comment]
Apparently, filebrowser can move files across datasets at all. You just have to copy and then delete I guess.
