### ISSUE TITLE
rename or delete make system slow and nothing done

### ISSUE THREAD

**Issue by yeganehaym** [filebrowser/filebrowser#1179]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

edit or delete a directory

**Expected behaviour**
What did you expect to happen?
change name of directory or can delete it

**What is happening instead?**
Please, give full error messages and/or log.
a suspension , make system slow

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by o1egl** [comment]
Please attach server logs and describe how you run the app.

**Comment by yeganehaym** [comment]
I got this service on a cloud provider
I think they fixed it
I sent this report because the app suggested me to do it
