### ISSUE TITLE
Errors with move/rename operations on files inside /files directory.

### ISSUE THREAD

**Issue by antetna** [filebrowser/filebrowser#1185]
**Description**
Trying to rename/move files that reside inside **/files** directory. Filebrowser url for this /files directory is http://_<server>_:_<port>_/files/files/

**Expected behaviour**
I would expect for file to be renamed or moved to another location.

**What is happening instead?**
- move files error
`2020/12/14 15:25:52 /random-1GB.dat: 404 ip.x.x.x rename /_<myhomedir>_/files/random-1GB.dat /_<myhomedir>_/files/tmp/random-1GB.dat: no such file or directory`

- rename file error
`2020/12/14 15:31:40 /random-1GB.dat: 404 ip.x.x.x rename /_<myhomedir>_/files/random-1GB.dat /_<myhomedir>_/files/files/random-1GB-new.dat: no such file or directory`

**Additional context**
Only errors for files inside **/files**  directory, every other directory works just fine.

**How to reproduce?**
Try some rename/move on files that reside inside top directory named **_files_**

**Files**
-

**Comment by o1egl** [comment]
resolved
