### ISSUE TITLE
PDF preview doesn't work on android

### ISSUE THREAD

**Issue by studioai** [filebrowser/filebrowser#1201]
PDF preview works fine on my PC browser (chrome). however, it doesn't on my android.
I tried four browsers (chrome, edge, puffin, Samsung) and the results are the same.
![Screenshot_20201225-043316_Chrome](https://user-images.githubusercontent.com/11453050/103104489-fffa3f00-466a-11eb-8741-8591f93322bd.jpg)

**Comment by o1egl** [comment]
Looks like your browser doesn't support pdf files rendering.

**Comment by studioai** [comment]
I forgot that I reported the same issue before this repository got achieved once.

#964 

I suggested a solution, please refer the issue linked.

**Comment by WeidiDeng** [comment]
Google docs is not working in China and it relies on third party website.

I think [this](https://www.npmjs.com/package/pdf-viewer) is better.

**Comment by xc1984759471** [comment]
The Android version of Chrome does not support PDF browsing. It is recommended to change to a browser that supports PDF, such as Kiwi browser. You can install the corresponding plug-in through the Chrome web store to view the PDF.
![Screenshot_2021-04-12-21-11-03-675_com kiwibrowser browser](https://user-images.githubusercontent.com/53083866/114399936-0e497800-9bd4-11eb-8d1d-b52e001b5494.jpg)
![Screenshot_2021-04-12-21-11-07-627_com kiwibrowser browser](https://user-images.githubusercontent.com/53083866/114399994-19040d00-9bd4-11eb-8877-2f973820e5be.jpg)

**Comment by mckaygerhard** [comment]
this problem is related to https://github.com/filebrowser/filebrowser/issues/1442 we need a way to disable previews so this kind of problems can be bypassed

**Comment by mckaygerhard** [comment]
almost many month was passed at least any way to disable preview for all files? puff please any response!

**Comment by niubility000** [comment]
> almost many month was passed at least any way to disable preview for all files? puff please any response!

I think I have fixed it in my modified version. try this: https://gitee.com/niubilitypdj/filebrowser/releases
If it works, I can make a PR later.

**Comment by mckaygerhard** [comment]
hi @niubility000  i discovered gitee .. ok likely in fact but it seems the code in your fork is pretty same as github..i mean : event i track your commits and there's none related https://gitee.com/niubilitypdj/filebrowser/commits/master?user=76441520%2Bniubility000%40users.noreply.github.com **are you trying to present to us your chinesse preferences? cos the code does not present many differences..** :smile:  please ca you show you the PR of the changes?

**Comment by rwlin** [comment]
Is there any config option that user can download and view the pdf file with external viewer?

**Comment by mckaygerhard** [comment]
@rwlin  this **was solved with commit https://github.com/filebrowser/filebrowser/commit/949f0f277f6004904b3edfa716a8365ec93fa0fa** the download link is showed at corner.. and it depends on the embebed support .. i liked an offline method but the filebrowser itselft is online in the phone so too much work for ..

this issue must marked as solved @o1egl cos androit previews in china uses different provider i guess the only options are to change the browser or when requested if pdf preview is not show, due the recent commit 949f0f277f6004904b3edfa716a8365ec93fa0fa now pdf file can be downloaded @rwlin

**Comment by vvmzgi** [comment]
@niubility000 https://gitee.com/niubilitypdj/filebrowser/releases 已经无法访问了

**Comment by mckaygerhard** [comment]
> 已经无法访问了

1. @vvmzgi post in english or at least use translator
2. of course is not accedible.. it said you MUST REGISTER a forced way of dictatorship get members inside the chinesse git projet management "gitee"

that's why we cannot use nothing that is promoted by a gov (yes .. in some way is managet by entyerpricesa and the chinesse gov)

**Comment by mckaygerhard** [comment]
ping

**Comment by Mubelotix** [comment]
Still an issue

**Comment by vincentaxhe** [comment]
iphone safari chrome edge can not page pdf files, miniserver do better, it's not phone's fault

**Comment by Mubelotix** [comment]
I mean, I understand that devs might not want to pack a pdf viewer in the web app, but what should be done at least is detect browsers not supporting the preview to just not show them the preview and make the file download directly

**Comment by vincentaxhe** [comment]
@Mubelotix I compare miniserver html source file, just use href link to pdf files, safari will open as continuous pics, filebrower do much more work, But safari can not digest it. there a necessity to detect browser.

**Comment by denisidoro** [comment]
> I mean, I understand that devs might not want to pack a pdf viewer in the web app, but what should be done at least is detect browsers not supporting the preview to just not show them the preview and make the file download directly

+1. Is this an option which could be implemented in the future?
