### ISSUE TITLE
When the user with ID 1 does not exist, No Authentication does not work properly.

### ISSUE THREAD

**Issue by xxxxuanran** [filebrowser/filebrowser#1204]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

I have used these commands before:
```
filebrowser -d /etc/filebrowser/filebrowser.db users add root passwd --perm.admin
filebrowser config set --auth.method=noauth
```
Now I have a user with ID 1, and the no authentication function is running normally
But when I delete this user, it was no longer could create a user with ID 1.
The login API also reported a 500 error.

**Expected behaviour**
What did you expect to happen?

When I delete all users, the newly created user ID should be 1.

**What is happening instead?**
Please, give full error messages and/or log.
Log:
```
2020/12/27 00:40:26 Listening on 127.0.0.1:9090
2020/12/27 00:40:35 /api/login: 500 127.0.0.1 the resource does not exist
2020/12/27 00:45:53 Caught signal interrupt: shutting down.
```
what I did:
```
root@ubuntu:/etc/filebrowser# filebrowser users ls
ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
root@ubuntu:/etc/filebrowser# filebrowser -d /path/filebrowser.db users add root passwd --perm.admin
ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
8   root      .      zh-cn   list     false    true   false    true    true    true    true    true   true      false
root@ubuntu:/etc/filebrowser# filebrowser users import user.json --overwrite
2020/12/27 01:02:11 the resource already exists
root@ubuntu:/etc/filebrowser# filebrowser users ls
ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
8   root      .      zh-cn   list     false    true   false    true    true    true    true    true   true      false
root@ubuntu:/etc/filebrowser# filebrowser users import user.json --replace
root@ubuntu:/etc/filebrowser# filebrowser users ls
ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
9   root      .      zh-cn   list     false    true   true     true    true    true    true    true   true      false
root@ubuntu:/etc/filebrowser# filebrowser users rm 9
user deleted successfully
root@ubuntu:/etc/filebrowser# filebrowser users import user.json --overwrite
root@ubuntu:/etc/filebrowser# filebrowser users ls
ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
10  root      .      zh-cn   list     false    true   true     true    true    true    true    true   true      false
root@ubuntu:/etc/filebrowser#
```

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Create two or more users and delete them, and the problem recurs.

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

[user.json.txt](https://github.com/filebrowser/filebrowser/files/5743424/user.json.txt)
[filebrowser.log](https://github.com/filebrowser/filebrowser/files/5743432/filebrowser.log)

**Comment by DanielYWoo** [comment]
same problem reproduced here.

**Comment by o1egl** [comment]
fixed in https://github.com/filebrowser/filebrowser/commit/019ce80fc529a0437984fdc3d1ab6916f34dd594
