### ISSUE TITLE
Client sent an HTTP request to an HTTPS server on Caddy.

### ISSUE THREAD

**Issue by RustyWraith** [filebrowser/filebrowser#1205]
I am receiving  "Client sent an HTTP request to an HTTPS server" in my browser window when I try to access my home server under a router.
filebrowser.service

> [Service] 
> ExecStart=/usr/local/bin/filebrowser -r /home/ubuntu/Sync -a 127.0.0.1 -p 8181

Caddyfile

> { acme_ca https://acme-staging-v02.api.letsencrypt.org/directory } 
> mydomain.com
> reverse_proxy 127.0.0.1:8181

**Comment by RustyWraith** [comment]
Any comments, please?

**Comment by WeidiDeng** [comment]
Try to access https://mydomain.com.

**Comment by RustyWraith** [comment]
I've tried:
> access https://mydomain.com
> access http://mydomain.com
> reverse_proxy https://127.0.0.1:8181

Filebrowser generates error:
>ubuntu filebrowser[3174]: 2021/01/04 02:58:51 http: TLS handshake error from 127.0.0.1:60034: remote error: tls: bad certificate

**Comment by WeidiDeng** [comment]
Do you set filebrowser's tls certificate using filebrowser config set?

**Comment by RustyWraith** [comment]
Sorry, that error comes from one of my experiments.
With starting filebrowser as stated in the first post:
>     CGroup: /system.slice/filebrowser.service
>            └─7160 /usr/local/bin/filebrowser -r /home/ubuntu/Sync -a 127.0.0.1 -p 8181
>
>Jan 04 13:34:17 ubuntu systemd[1]: Started filebrowser.
>Jan 04 13:34:17 ubuntu filebrowser[7160]: 2021/01/04 13:34:17 No config file used
>Jan 04 13:34:17 ubuntu filebrowser[7160]: 2021/01/04 13:34:17 Listening on 127.0.0.1:8181

**Comment by WeidiDeng** [comment]
Can you paste the output when you curl http://127.0.0.1:8181 from your router?

**Comment by RustyWraith** [comment]
>ubuntu@ubuntu:~$ curl http://127.0.0.1:8181
>Client sent an HTTP request to an HTTPS server.

And as for caddy side:
>     CGroup: /system.slice/caddy.service
>             └─6748 /usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
>
>Jan 04 11:47:19 ubuntu caddy[6748]: {"level":"error","ts":1609760839.8413527,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.1.1:53961","proto":"HTTP/2.0","method":"GET","host":"file.rustywraith.ru","uri":"/","heade>
>Jan 04 11:47:20 ubuntu caddy[6748]: {"level":"error","ts":1609760840.0295427,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 127.0.0.1:33082->127.0.0.1:8181: read: connection reset by peer"}
>Jan 04 11:47:20 ubuntu caddy[6748]: {"level":"error","ts":1609760840.0297346,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"read tcp 127.0.0.1:33082->127.0.0.1:8181: read: connection reset by peer"}
>Jan 04 11:47:20 ubuntu caddy[6748]: {"level":"error","ts":1609760840.0301182,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.1.1:53961","proto":"HTTP/2.0","method":"GET","host":"file.rustywraith.ru","uri":"/favicon.>
>Jan 04 13:34:46 ubuntu caddy[6748]: {"level":"error","ts":1609767286.189218,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 127.0.0.1:33352->127.0.0.1:8181: read: connection reset by peer"}
>Jan 04 13:34:46 ubuntu caddy[6748]: {"level":"error","ts":1609767286.189358,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"read tcp 127.0.0.1:33352->127.0.0.1:8181: read: connection reset by peer"}
>Jan 04 13:34:46 ubuntu caddy[6748]: {"level":"error","ts":1609767286.1895125,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.1.1:53961","proto":"HTTP/2.0","method":"GET","host":"file.rustywraith.ru","uri":"/","heade>
>Jan 04 13:34:46 ubuntu caddy[6748]: {"level":"error","ts":1609767286.7771933,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 127.0.0.1:33354->127.0.0.1:8181: read: connection reset by peer"}
>Jan 04 13:34:46 ubuntu caddy[6748]: {"level":"error","ts":1609767286.7774487,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"read tcp 127.0.0.1:33354->127.0.0.1:8181: read: connection reset by peer"}
>Jan 04 13:34:46 ubuntu caddy[6748]: {"level":"error","ts":1609767286.7777388,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.1.1:53961","proto":"HTTP/2.0","method":"GET","host":"file.rustywraith.ru","uri":"/favicon.>

**Comment by WeidiDeng** [comment]
Is there a filebrowser.db in / directory? Stop filebrowser and in / directory run

`
filebrowser config cat
`

**Comment by RustyWraith** [comment]
>ubuntu@ubuntu:/$ filebrowser config cat
>2021/01/04 14:08:04 open ./filebrowser.db: permission denied
>ubuntu@ubuntu:/$ sudo filebrowser config cat
>Sign up:          true
>Create User Dir:  true
>Auth method:      json
>Shell:
>
>Branding:
>  Name:
>  Files override:
>  Disable external links:  false
>
>Server:
>  Log:           stdout
>  Port:          8181
>  Base URL:
>  Root:          /home/ubuntu/Sync
>  Socket:
>  Address:       0.0.0.0
>  TLS Cert:      /home/ubuntu/mycert.pem
>  TLS Key:       /home/ubuntu/mykey.key
>  Exec Enabled:  false
>
>Defaults:
>  Scope:         ./SHARE
>  Locale:        en
>  View mode:     mosaic
>  Single Click:  false
>  Commands:
>  Sorting:
>    By:
>    Asc:  false
>  Permissions:
>    Admin:     false
>    Execute:   false
>    Create:    true
>    Rename:    true
>    Modify:    true
>    Delete:    true
>    Share:     true
>    Download:  true
>
>Auther configuration (raw):
>
>{
>  "recaptcha": null
>}

**Comment by WeidiDeng** [comment]
run 

`
filebrowser config set --key ""
filebrowser config set --cert ""
`

in / directory with filebrowser shutdown, then restart.

**Comment by RustyWraith** [comment]
Works!
So settings are cached in .db file despite of using no config?

**Comment by WeidiDeng** [comment]
> Works!
> So settings are cached in .db file despite of using no config?

Filebrowser has a db that store almost all the commandline arguments. If you don't specify one, it will find (initialize) it in current working directory. Your systemd service doesn't specify a working directory, so it's in the / directory.
