### ISSUE TITLE
Some MP4 files cannot be played

### ISSUE THREAD

**Issue by Hermit-Nameless** [filebrowser/filebrowser#1209]
Some MP4 files cannot be played.
It may be that H264 decoding is not supported.
![image](https://user-images.githubusercontent.com/30073216/103252824-6bb91080-49b9-11eb-80bb-069c1fb625ca.png)
![image](https://user-images.githubusercontent.com/30073216/103256399-26e8a600-49c8-11eb-9e4a-dc1e3e2f4940.png)

**Comment by WeidiDeng** [comment]
The video player is using browser built-in, there are many limitations.

I plan to use [this player](https://github.com/DIYgod/DPlayer) when I have time.

**Comment by aohanhongzhi** [comment]
+1

**Comment by aohanhongzhi** [comment]
Has anyone solved this problem?

**Comment by aohanhongzhi** [comment]
> The video player is using browser built-in, there are many limitations.
> 
> I plan to use [this player](https://github.com/DIYgod/DPlayer) when I have time.

+ 1 , pls add the feature
