### ISSUE TITLE
Confirmation before deleting share link

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#1210]
**Is your feature request related to a problem? Please describe.**
The new share management in 2.11 is a great new feature. However, when there are a lot of links, it's possible to click on the delete button on the wrong line. This was not a problem when using the single file share management dialog, because you'd be viewing a single file, there is no chance you delete the wrong file.

**Describe the solution you'd like**
Add a dialog to confirm the deletion.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1329716/103257163-3aa20580-49e4-11eb-99d4-8fe93d4b4605.png)

Although not as necessary as on share management page, it'd be great to use the same confirmation dialog on this deletion as well

![image](https://user-images.githubusercontent.com/1329716/103257250-8785dc00-49e4-11eb-8b2e-c230181309e9.png)

**Comment by WeidiDeng** [comment]
> **Is your feature request related to a problem? Please describe.**
> The new share management in 2.11 is a great new feature. However, when there are a lot of links, it's possible to click on the delete button on the wrong line. This was not a problem when using the single file share management dialog, because you'd be viewing a single file, there is no chance you delete the wrong file.
> 
> **Describe the solution you'd like**
> Add a dialog to confirm the deletion.
> 
> **Describe alternatives you've considered**
> N/A
> 
> **Additional context**
> ![image](https://user-images.githubusercontent.com/1329716/103257163-3aa20580-49e4-11eb-99d4-8fe93d4b4605.png)

Fixed in [1212](https://github.com/filebrowser/filebrowser/pull/1212).

> Although not as necessary as on share management page, it'd be great to use the same confirmation dialog on this deletion as well
> 
> ![image](https://user-images.githubusercontent.com/1329716/103257250-8785dc00-49e4-11eb-8b2e-c230181309e9.png)

Not possible at this moment.

**Comment by princemaple** [comment]
@WeidiDeng thank you!
