### ISSUE TITLE
Commands Runner variables

### ISSUE THREAD

**Issue by Lucy-2077** [filebrowser/filebrowser#1211]
Hi everyone
I want to make a discord webhook with a python script , but on the command runner 
python3 /home/defidegue/delete.py --user $USERNAME --name $FILE
Only the message has been sent , the variables "$USERNAME" or "$FILE" is not changed
I have also an 500 internal error when i delete a file
![image](https://user-images.githubusercontent.com/20909184/103257664-6d231280-4992-11eb-9962-4446e99eb777.png)
I'm on the 2.11.0 version
The command say blocked but is working
![image](https://user-images.githubusercontent.com/20909184/103257748-d86ce480-4992-11eb-971e-3449cba05f84.png)

2020/12/29 04:55:41 [INFO] Blocking Command: "python3 /home/defidegue/delete.py --user $USERNAME --name $FILE"
@@ Notification sended
Thanks you !

**Comment by o1egl** [comment]
Can you try to run `echo $USERNAME` and `echo $FILE` and check the output?

**Comment by johnnyq** [comment]
im having the same issue when i do a echo $USERNAME

it returns $USERNAME and not the username im logged in as

**Comment by WeidiDeng** [comment]
I believe it's because command runner is not actually a shell, see [this](https://stackoverflow.com/questions/51015569/exec-command-in-go-with-environment-variable).

I tried the trigger for all the events, if environmental variable is read within the command, bash, python scripts whatever, it's correct. When used as commandline arguments, it's not expanded.

**Comment by Lucy-2077** [comment]
```
2021/01/12 18:48:45 [INFO] Blocking Command: "echo $USERNAME"
$USERNAME
2021/01/12 19:17:24 [INFO] Blocking Command: "echo $FILE"
$FILE
```
Hello ,
Thanks for the answer but Same issue
The command is allowed too !

**Comment by WeidiDeng** [comment]
What I mean is, create /tmp/test.sh like this

```
#!/bin/bash
echo $USERNAME $FILE
```

Then chmod+x it and add

```
/tmp/test.sh
```

to the event hook. When this script is run, the environmental variable is expanded.

I made a pr so that command line is expanded.

**Comment by Lucy-2077** [comment]
Hello , the problem i need to imput there variables in my python script.
A fix is possible ?

**Comment by WeidiDeng** [comment]
> Hello , the problem i need to imput there variables in my python script.
> A fix is possible ?

```
import os
print(os.environ['USERNAME'])
```

Or create a bash script

```
#!/bin/bash
python3 /home/defidegue/delete.py --user $USERNAME --name $FILE
```

add run this script instead. Remember to chmod +x.

Or merge my pr yourself and built it.
