### ISSUE TITLE
Share address, including the complete file path, but I don't want others to see it

### ISSUE THREAD

**Issue by mini1025** [filebrowser/filebrowser#1213]
![1](https://user-images.githubusercontent.com/68982525/103341765-bbcfca00-4ac2-11eb-99f7-f040b8c88a51.jpg)
![2](https://user-images.githubusercontent.com/68982525/103341770-bd998d80-4ac2-11eb-8b89-0d23dd6fb1c0.jpg)

**Comment by WeidiDeng** [comment]
The path is for ease of navigation, and a path can be favored and shared.

I see no reason to hide the path, the path only shows complete path from the root of the shared directory, not complete path from user scope root. And if a directory is shared, people can navigate it.

Use timed share if you want to limit resource access.

**Comment by o1egl** [comment]
No response

**Comment by Asion001** [comment]
@o1egl  Hey, the problem still exists. If I press the copy button with the download link, I get a link with the path `/media/Readme.md`. However, if I open the share page and copy the link from the download button there, I get a link without the path.


Share modal:
![image](https://github.com/filebrowser/filebrowser/assets/46422813/1e331a76-9683-4793-aa54-c437309a130c)
First button link: https://**/share/pZm7v_b0
Second button link: https://**/api/public/dl/pZm7v_b0/media/Readme.md

Share page:
![image](https://github.com/filebrowser/filebrowser/assets/46422813/8c3257a5-9205-461c-9eb1-407bb9cdd39a)
Download button link: https://**/api/public/dl/pZm7v_b0
