### ISSUE TITLE
Upload folder not working on mobile

### ISSUE THREAD

**Issue by sumitmamoria** [filebrowser/filebrowser#1215]
**Description**
The upload folder works from the desktop browsers, but not from mobile (android in this case) browsers.

**Expected behaviour**
To be able to upload a folder from a mobile device

**What is happening instead?**
The upload folder option takes the user to the file-system where folders are stored, but the user is unable to choose folder. The user cannot even choose multiple files. Finally, if the user chooses a single file (although, it is not the intended purpose), even then the upload process does not start and the user is returned to the previous screen. 

**How to reproduce?**
From a mobile browser, click upload. Then choose upload folder and select a desired folder from the mobile file-system.

**Comment by o1egl** [comment]
Try to use the latest chrome browser.

**Comment by sumitmamoria** [comment]
> Try to use the latest chrome browser.

I have tested with latest Chrome for android. Does not work.

**Comment by o1egl** [comment]
I think this api is not supported on mobile devices.

**Comment by sumitmamoria** [comment]
> I think this api is not supported on mobile devices.

Is there anything one can try to fix it?

**Comment by o1egl** [comment]
I couldn't find a solution on the net. But perhaps the front-end developers can clarify this.

**Comment by ramiresviana** [comment]
This feature is non-standard and can change on future, should work on chrome based browsers. Unfortunately its not supported on mobile.
