### ISSUE TITLE
Upload feature for shared folder links

### ISSUE THREAD

**Issue by chonjay21** [filebrowser/filebrowser#1218]
**Is your feature request related to a problem? Please describe.**
No, It`s not related to a problem

**Describe the solution you'd like**
Upload feature to shared folder links will be very useful.

**Comment by o1egl** [comment]
Shared folder is a public resource. It doesn't make sense to give anonymous user permission to upload a file.

**Comment by chonjay21** [comment]
If there is the option of protecting a shared folder with a password (#1223 ), the shared folder will be a private folder for the group (friends, coworkers, etc.).
When protected with a password, I think the uploader is no longer an anonymous user.

**Comment by o1egl** [comment]
Adding a password doesn't mean that the write access should be granted to anyone who knows it. User is still anonymous and we only reduce the scope of those users

**Comment by thielepaul** [comment]
Collecting files/photos from other people that do not have an account on my server is a regular usecase for me and thus I wondered if you have a good solution for this @o1egl ?

Creating an account for everyone is not an option for me, as there are a lot of people that do not want to have/remember yet another account/password.

I would also appreciate suggestions regarding other self-hosted solutions for this particular usecase, as long as it isn't nextcloud ;)

**Comment by electrofloat** [comment]
So why was this closed?

Filebrowser does not/will not support uploading of files with guest/anonymous accounts?
