### ISSUE TITLE
Cant update startup.sh

### ISSUE THREAD

**Issue by Technooz** [filebrowser/filebrowser#1220]
**Description**
Sent my ASP.Net project to asp.net cloud clusters and i'm trying to edit startup.sh, when I try to save the changes it gives me an error [object Object]

**Expected behaviour**
Save changes to startup.sh

**What is happening instead?**
[object Object] (this is the error), not saving the file.

**Additional context**

**How to reproduce?**
File manager > config > aspnet > startup.sh

**Files**

**Comment by o1egl** [comment]
Can you provide an error from filebrowser logs?
