### ISSUE TITLE
Is there a way to prevent direct downloads ?

### ISSUE THREAD

**Issue by ericxuo** [filebrowser/filebrowser#1221]
Hi,

I have configured filebrowser on my Apache server.
The problem I have is that I can "direct download" the files under the filebrowser directory.
Ex  : 
wget https://mydomain.fr/fileBrowser/Films/Series/The_Vampire_Diaries/The_Vampire_Diaries_S03/The_Vampire_Diaries_S03_E05.nfo

Is there a way to prevent the direct downloads (while keeping the read access through filebrowser ?).

Regards.

Xuo.

**Comment by WeidiDeng** [comment]
How do you configure apache? You should reverse proxy all traffic to filebrowser.

If you have a base url, set it and reverse proxy all traffic through that path.

**Comment by ericxuo** [comment]
Hi,

Here is my filebrowser.conf for Apache.

<IfModule mod_proxy_http.c>

    <Location /fileBrowser/>
        Order allow,deny
        Allow from all
        ProxyPass http://192.168.0.14:8082/fileBrowser/
        ProxyPassReverse http://192.168.0.14:8082/fileBrowser/
    </Location>

    <Location /fileBrowser/websocket-tunnel>
      Order allow,deny
      Allow from all
      ProxyPass ws://192.168.0.14:8082/fileBrowser/websocket-tunnel
      ProxyPassReverse ws://192.168.0.14:8082/fileBrowser/websocket-tunnel
    </Location>

</IfModule>

As you can see, there is a "/fileBrowser" directory under my root-dir. I think this is the reason why it is possible to do direct downloads when you know the full path of the file you want to download.

Regards.

Xuo.

**Comment by WeidiDeng** [comment]
try this

```
<Location /fileBrowser/>
    Order allow,deny
    Allow from all
    ProxyPass http://192.168.0.14:8082/
    ProxyPassReverse http://192.168.0.14:8082/
</Location>
```

The filebrowser at the end of the proxy is not neccessary, you should set it using

```
filebrowser config set --baseurl /fileBrowser/
```

I don't have much experience with apache, I think it's a path matching problem. Apache default to listing files (direct download) and there is a problem of request matching existing file. You may need to disable directory listing.

**Comment by ericxuo** [comment]
Hi,

Here is what I do : 

1) file /etc/httpd/conf/sites.d/filebrowser.conf : 
<IfModule mod_proxy_http.c>

    <Location /fileBrowser/>
	Order allow,deny
	Allow from all
	ProxyPass http://192.168.0.14:8082/
	ProxyPassReverse http://192.168.0.14:8082/
    </Location>

    <Location /fileBrowser/websocket-tunnel>
      Order allow,deny
      Allow from all
      ProxyPass ws://192.168.0.14:8082/websocket-tunnel
      ProxyPassReverse ws://192.168.0.14:8082/websocket-tunnel
    </Location>
    
</IfModule>

2) Remove the symlink from /usr/share/fileBrowser to /var/www/html/fileBrowser
3) The filebrowser daemon is running the following way : 
/bin/filebrowser -b /fileBrowser/ -a 192.168.0.14 -d /etc/filebrowser/filebrowser.db -p 8082

Whit this config, I can login to filebrowser using  https://my_domain.fr/fileBrowser + username + password
But I still can direct download any file under /usr/share/fileBrowser with : 
wget https://my_domain.fr/fileBrowser/anyFile

I have added the following file /usr/share/fileBrowser/.htaccess : 
<Directory />
    Options -Indexes
</Directory> 
<FilesMatch "*">
    Order Allow,Deny
    Deny from All
</FilesMatch>

but it does not change anything.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

I said something wrong. I can download but something different from the "real" file.
For ex, if I run : 
wget 'https://my_domain.fr/fileBrowser/Films/.htaccess.txt'
I get a file that contains : 
`<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,user-scalable=no"><title>File Browser</title><link rel=icon type=image/png sizes=32x32 href="/fileBrowser/static/img/icons/favicon-32x32.png"><link rel=icon type=image/png sizes=16x16 href="/fileBrowser/static/img/icons/favicon-16x16.png"><link rel=manifest id=manifestPlaceholder crossorigin=use-credentials><meta name=theme-color content=#2979ff><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black><meta name=apple-mobile-web-app-title content=assets><link rel=apple-touch-icon href="/fileBrowser/static/img/icons/apple-touch-icon.png"><meta name=msapplication-TileImage content="/fileBrowser/static/img/icons/mstile-144x144.png"><meta name=msapplication-TileColor content=#2979ff><script>window.FileBrowser = JSON.parse(`{
  "AuthMethod": "json",
  "BaseURL": "/fileBrowser",
  "CSS": false,
  "DisableExternal": false,
  "EnableExec": true,
  "EnableThumbs": true,
  "LoginPage": true,
  "Name": "File Browser",
  "NoAuth": false,
  "ReCaptcha": false,
  "ResizePreview": true,
  "Signup": false,
  "StaticURL": "/fileBrowser/static",
  "Theme": "dark",
  "Version": "2.11.0"
}`);

    var fullStaticURL = window.location.origin + window.FileBrowser.StaticURL;
    var dynamicManifest = {
      "name": window.FileBrowser.Name || 'File Browser',
      "short_name": window.FileBrowser.Name || 'File Browser',
      "icons": [
        {
          "src": fullStaticURL + "/img/icons/android-chrome-192x192.png",
          "sizes": "192x192",
          "type": "image/png"
        },
        {
          "src": fullStaticURL + "/img/icons/android-chrome-512x512.png",
          "sizes": "512x512",
          "type": "image/png"
        }
      ],
      "start_url": window.location.origin + window.FileBrowser.BaseURL,
      "display": "standalone",
      "background_color": "#ffffff",
      "theme_color": "#455a64"
    }

    const stringManifest = JSON.stringify(dynamicManifest);
    const blob = new Blob([stringManifest], {type: 'application/json'});
    const manifestURL = URL.createObjectURL(blob);
    document.querySelector('#manifestPlaceholder').setAttribute('href', manifestURL);</script><style>#loading {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #fff;
    z-index: 9999;
    transition: .1s ease opacity;
    -webkit-transition: .1s ease opacity;
  }

  #loading.done {
    opacity: 0;
  }

  .spinner {
    width: 70px;
    text-align: center;
    position: fixed;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
  }

  .spinner > div {
    width: 18px;
    height: 18px;
    background-color: #333;
    border-radius: 100%;
    display: inline-block;
    -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
    animation: sk-bouncedelay 1.4s infinite ease-in-out both;
  }

  .spinner .bounce1 {
    -webkit-animation-delay: -0.32s;
    animation-delay: -0.32s;
  }

  .spinner .bounce2 {
    -webkit-animation-delay: -0.16s;
    animation-delay: -0.16s;
  }

  @-webkit-keyframes sk-bouncedelay {
    0%, 80%, 100% { -webkit-transform: scale(0) }
    40% { -webkit-transform: scale(1.0) }
  }

  @keyframes sk-bouncedelay {
    0%, 80%, 100% {
      -webkit-transform: scale(0);
      transform: scale(0);
    } 40% {
      -webkit-transform: scale(1.0);
      transform: scale(1.0);
    }
  }</style><link href="/fileBrowser/static/js/chunk-394af474.fdfad866.js" rel=prefetch><link href="/fileBrowser/static/css/app.bfe3744b.css" rel=preload as=style><link href="/fileBrowser/static/css/chunk-vendors.c7045283.css" rel=preload as=style><link href="/fileBrowser/static/js/app.116cf73e.js" rel=preload as=script><link href="/fileBrowser/static/js/chunk-vendors.804f7f8b.js" rel=preload as=script><link href="/fileBrowser/static/css/chunk-vendors.c7045283.css" rel=stylesheet><link href="/fileBrowser/static/css/app.bfe3744b.css" rel=stylesheet></head><body><div id=app></div><div id=loading><div class=spinner><div class=bounce1></div><div class=bounce2></div><div class=bounce3></div></div></div><link rel=stylesheet href="/fileBrowser/static/themes/dark.css"> <script src="/fileBrowser/static/js/chunk-vendors.804f7f8b.js"></script><script src="/fileBrowser/static/js/app.116cf73e.js"></script></body></html>
`
And all the downloaded files have exactly this content.

Regards.

Xuo.

**Comment by WeidiDeng** [comment]
This is the index.html of filebrowser. Are you using wget to download it? It appears it's filebrowser redirecting the request to login page. And you can't prevent anyone to download login page.

**Comment by ericxuo** [comment]
Hi,

Yes, it looks like you say. I try to download file xxx but it is always the filebrowser login page which is downloaded. In this case, this is not an issue.

Thank you for your help.

Regards.

Xuo.
