### ISSUE TITLE
Web interface not working 

### ISSUE THREAD

**Issue by zhanko** [filebrowser/filebrowser#1226]
**Description**
Install File Explorer. All of the install is ok and filebrowser is saying it is running on address 127.0.0.1:8080

**Expected behaviour**
When opening the ip-address-of-the-server:8080 - debian10 file explorer to show on the web browser

**What is happening instead?**
Nothing 

**Additional context**
![image](https://user-images.githubusercontent.com/1668858/103626746-50b04880-4f45-11eb-91c5-4940ee3d1e40.png)
![image](https://user-images.githubusercontent.com/1668858/103627012-b0a6ef00-4f45-11eb-8834-f97289899b37.png)

**How to reproduce?**
Clean install as described in the website 

**Files**
N/A

**Comment by WeidiDeng** [comment]
Because filebrowser listens on localhost, you need to pass param -a your-server-ip

**Comment by zhanko** [comment]
Hello,

Thank you for your prompt response. Still having issues. Please see below

sudo filebrowser -a 192.168.1.169                                                                                                      
2021/01/05 10:12:50 timeout

**Comment by WeidiDeng** [comment]
kill first filebrowser instance, then rerun.

**Comment by zhanko** [comment]
Thank you. All sorted. 

Do you envision to have a text editor ?

**Comment by zhanko** [comment]
WeidiDeng - Thank you for the support

**Comment by WeidiDeng** [comment]
> Thank you. All sorted.
> 
> Do you envision to have a text editor ?

What kind of text editor? Currently there is one with syntax highlight, and I think that's enough.

**Comment by zhanko** [comment]
Correct. Very nice one editor indeed

While we're at it I see there is not systemd support and running filebrowser with & throws an error.how do you guys start the program at boot successfully?

Is there a way to allow an allow administrative user to use all programs at the integrated shell

**Comment by WeidiDeng** [comment]
Systemd can be written very easily, here is a example.

```
[Unit]
Description=Filebrowser Service
After=network.target

[Service]
WorkingDirectory=/etc/filebrowser
PIDFile=/var/run/filebrowser.pid
ExecStart=/usr/local/bin/filebrowser --cache-dir cache
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

Just modify and put it to /etc/systemd/system/filebrowser.service, run

```
systemctl enable filebrowser.service
systemctl start filebrowser.service
```

The integrated shell can only run command set in user configuration.

**Comment by zhanko** [comment]
Hello,

I'm sorry to be a pain.  please see below the issue 

sudo journalctl -u filebrowser
-- Logs begin at Tue 2021-01-05 11:41:22 GMT, end at Wed 2021-01-06 07:17:28 GMT. --
Jan 06 07:15:47 Darkstar systemd[1]: /etc/systemd/system/filebrowser.service:6: PIDFile= references path bJan 06 07:16:06 Darkstar systemd[1]: Started Filebrowser Service.
Jan 06 07:16:06 Darkstar filebrowser[12523]: 2021/01/06 07:16:06 No config file used
Jan 06 07:16:06 Darkstar filebrowser[12523]: 2021/01/06 07:16:06 Listening on 127.0.0.1:8080

again it's listening to localhost when I have done the config in the DB

**Comment by WeidiDeng** [comment]
Do you copy my systemd example? You need to copy the filebrowser.db to /etc/filebrowser

**Comment by zhanko** [comment]
WeidiDeng

I copied the DB into the /etc/filebrowser and it worked like a charm. Thank you immensely for the prompt response and ample help

Would I get the below each time 
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to restart 'filebrowser.service'.
Authenticating as: root
Password: 
==== AUTHENTICATION COMPLETE ===

Final question I promise :)

In relation to the embedded Command Prompt I would very much like to select that I can use all commands but it is evident I can't list them all in the settings . Is there a workaround for this something like *?

**Comment by WeidiDeng** [comment]
To remove authentication prompt, use

```
sudo service filebrowser restart
```

like this.

There is no wildcard in the command prompt, if you need it badly, use [ttyd](https://github.com/tsl0922/ttyd). The command prompt is not a substitute for a real prompt. It's not interactive, and unlikely to be.

**Comment by zhanko** [comment]
Thank you !!! and Happy New Year !!!

I've run out of questions !!

THANK YOU!
