### ISSUE TITLE
运行时内存不足崩溃--fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by zhenfeii** [filebrowser/filebrowser#1227]
服务器内存 512m，崩溃后查看可用内存尚有124m.
![image](https://user-images.githubusercontent.com/30223168/103630481-ae13bc00-4f7c-11eb-9a4e-f9e6d7d71c93.png)
附上完整日志。

**Comment by zhenfeii** [comment]
[nohup.log](https://github.com/filebrowser/filebrowser/files/5769310/nohup.log)

**Comment by WeidiDeng** [comment]
运行时加上--disable-preview-resize --disable-thumbnails参数

**Comment by niubility000** [comment]
Just add virtual memory using your hard disk, just like what I do. It will be perfect.

**Comment by niubility000** [comment]
If you don't want add the virtual memory, just use the following command.It is also OK.
#nohup /tmp/mnt/sda1/filebrowser/filebrowser -d /tmp/mnt/sda1/filebrowser/filebrowser.db --disable-preview-resize --img-processors 1 --cache-dir /tmp/mnt/sda1/filebrowser/cache >/dev/null 2>&1 &

**Comment by niubility000** [comment]
> Just add virtual memory using your hard disk, just like what I do. It will be perfect.

Here is my services-start file:
#!/bin/sh
cd /tmp/mnt/sda1/filebrowser
sleep 15
#加sleep是因为可能移动硬盘唤醒需要时间。
chmod 755 /tmp/mnt/sda1/filebrowser/filebrowser
sleep 2
str=$"/n"
sstr=$(echo -e $str)
#下面是无缩略图，不显示调整尺寸的图片。这个k3服务不会倒！
#nohup /tmp/mnt/sda1/filebrowser/filebrowser -d /tmp/mnt/sda1/filebrowser/filebrowser.db --disable-preview-resize --disable-thumbnails >/dev/null 2>&1 &
#下面是开启缩略图，限制处理器个数为1，并生成缓存。关闭浏览图片下的hd模式。这个好，k3也不会倒。（是不会out of memory）
#nohup /tmp/mnt/sda1/filebrowser/filebrowser -d /tmp/mnt/sda1/filebrowser/filebrowser.db --disable-preview-resize --img-processors 1 --cache-dir /tmp/mnt/sda1/filebrowser/cache >/dev/null 2>&1 &
#加了虚拟内存1个g，硬盘仍然能休眠，不错。可以全速运行了，不开浏览图片时的hd模式，开启了apache证书，只能用https访问。
nohup /tmp/mnt/sda1/filebrowser/filebrowser -d /tmp/mnt/sda1/filebrowser/filebrowser.db --disable-preview-resize --cache-dir /tmp/mnt/sda1/filebrowser/cache --cert /tmp/mnt/sda1/filebrowser/1.crt --key /tmp/mnt/sda1/filebrowser/1.key >/dev/null 2>&1 &
echo "$sstr"

**Comment by zhenfeii** [comment]
thanks.
