### ISSUE TITLE
Install script will not run without curl installed

### ISSUE THREAD

**Issue by ChenTondovski** [filebrowser/filebrowser#1229]
**Description**
I am trying to run the installation script on a linux x64 machine that has no curl installed, curl cannot be installed on this machine, but wget is available.

according to the comments in the script header, it is required to have either curl or wget, and in some places there is code for both alternatives, however when setting the filemanager_tag variable curl is hardcoded. 

**Expected behaviour**
I expected the install to use wget exclusively. and work.

**What is happening instead?**
running the script get.sh with bash 
```
Downloading File Browser for linux/amd64...
get.sh: line 101: curl: command not found
https://github.com/filebrowser/filebrowser/releases/download//linux-amd64-filebrowser.tar.gz
Aborted, error 8 in command: wget --quiet "$filemanager_url" -O "$PREFIX/tmp/$filemanager_file"
```

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Run the install script on a machine without curl installed

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by niubility000** [comment]
Just download the linux-amd64... .tar.gz file manually from the release, and unzip, put  that four files anywhere you like. 
 login to SSH,  run the following commands:

(go to the directory where you put the four files.)
cd /tmp/mnt/h1backup/filebrowser

chmod 755 filebrowser

./filebrowser -d filebrowser.db config init

./filebrowser -d filebrowser.db config set --address 0.0.0.0

./filebrowser -d filebrowser.db config set --port 18

./filebrowser -d filebrowser.db users add aaa 12345 --perm.admin

./filebrowser -d filebrowser.db config set --root /tmp/mnt/h1backup

nohup /tmp/mnt/h1backup/filebrowser/filebrowser -d /tmp/mnt/h1backup/filebrowser/filebrowser.db --disable-preview-resize --cache-dir /tmp/mnt/h1backup/filebrowser/cache  >/dev/null 2>&1 &

Then, just visit ip:18 using your browser.

**Comment by ChenTondovski** [comment]
I wasn't asking for an alternative, I've already implemented one for myself. I'm just pointing out that the install script doesn't work like it says it does, that's all.
That said, I would prefer to use the official script if possible.

**Comment by o1egl** [comment]
@ChenTondovski you can make a PR to https://github.com/filebrowser/get repo

**Comment by ChenTondovski** [comment]
> @ChenTondovski you can make a PR to https://github.com/filebrowser/get repo

I'd love to.
~~Do I need to fork it first or just create a branch on the project? I've never done this before.~~ working on it
