### ISSUE TITLE
Uploading files doesn't work while behind nginx reverse proxy

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1230]
**Description**
Upload doesn't work while behind nginx reverse proxy. It works on localhost:8082 but not on https:/mydomain.com/filebrowser/files/.

Downloading works. Uploading folders works.

**Expected behaviour**
Expect the file to be uploaded.

**What is happening instead?**
The refresh symbol flashed, and then the check mark flashed. But no file can be found. 

I cannot see updates in cmd so I can't pinpoint what's wrong.

**Additional context**
I'm on Windows 10. Running the latest windows-amd64-filebrowser.zip. I ran with the command -p 8082 -b "/filebrowser" --root "path to my folder". No config was used.

I'm using the subfolder approach to nginx.

**How to reproduce?**
I guess test on another windows with nginx set up.

**Files**
My nginx conf below:

location /filebrowser {
	auth_request /auth-0;
        auth_request_set $auth_user $upstream_http_x_organizr_user;
        proxy_set_header X-WEBAUTH-USER $auth_user;
        client_max_body_size 0;
        proxy_read_timeout                      86400s;
        proxy_send_timeout                      86400s;
        proxy_set_header                        X-Forwarded-Host $host;
        proxy_set_header                        X-Forwarded-Server $host;
        proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version                      1.1;
        proxy_redirect                          off;
        proxy_set_header                        Upgrade $http_upgrade;
        proxy_set_header                        Connection "upgrade";
        proxy_pass                              http://127.0.0.1:8082;
    }

**Comment by tyzbit** [comment]
I can't reproduce.  I tried with and without websockets enabled and I'm able to upload files.

Here's one conf without websockets that worked:
```
server {
        listen 8080;
        server_name example.com;
        access_log /var/log/nginx/access.log extended;
        if ($http_x_forwarded_proto = "http") {
                rewrite        ^ https://$server_name$request_uri? permanent;
        }
        location / {
                proxy_pass http://localhost:8085/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```

And here's one with them that worked:
```
server {
        listen 8080;
        server_name example.com;
        access_log /var/log/nginx/access.log extended;
        if ($http_x_forwarded_proto = "http") {
                rewrite        ^ https://$server_name$request_uri? permanent;
        }
        location / {
                proxy_pass http://localhost:8085/;
                proxy_http_version 1.1;
                proxy_redirect off;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
        }
}
```
I tried adding `client_max_body_size 0;` as well and that still worked for me.  That makes me suspect your `auth_request` lines.

**Comment by o1egl** [comment]
No response
