### ISSUE TITLE
下载文件异常后， 服务不可用了

### ISSUE THREAD

**Issue by zhenfeii** [filebrowser/filebrowser#1232]
场景：利用filebrowser提供的下载直链，使用aria2c多线程下载，文件是使用rclone挂载出来的，可能是网络原因导致不稳定，导致下载异常。

但是，打开filebrowser已经无法使用文件管理功能了。
![image](https://user-images.githubusercontent.com/30223168/103734876-cdb3ee80-5027-11eb-9cb4-42204b7faee6.png)

完整日志如下：

**Comment by zhenfeii** [comment]
[nohup.log](https://github.com/filebrowser/filebrowser/files/5774124/nohup.log)

**Comment by zhenfeii** [comment]
发现问题所在， 只要有一个目录加载失败就会全部不可用了。而且得重启服务才可以正常使用。
如果可以，希望优化下。

**Comment by o1egl** [comment]
@zhenfeii Please translate to English

**Comment by WeidiDeng** [comment]
这个是rclone挂载的问题，向rclone反馈。

This is a problem of rclone mounting, give feedback to rclone.

**Comment by niubility000** [comment]
最大可能是内存不足，加点虚拟内存就好了。你的内存多大？或者，加个守护进程，2分钟查一次filebrowser还在不在。
The most posibility is out of memory. add  some virtual memory. What's your memory size? Or , just add a watchdog for filebrowser.

**Comment by if1y** [comment]
should better avoid of using rclone mount
