### ISSUE TITLE
Could you add feature that support multi-scopes need?

### ISSUE THREAD

**Issue by leon-dadi01** [filebrowser/filebrowser#1235]
![image](https://user-images.githubusercontent.com/56914900/103979603-151db480-51b9-11eb-9bd1-91bddd3c7351.png)
I can see in user management panel, only one scope line is allowed. What if we want to add multi-scopes to allow user to access different resources in same folder-level?

Can you guys help to add multi scope lines or support separating paths in single scope line?

**Comment by o1egl** [comment]
At the moment we don't support multiple root scopes. As a workaround you can use `Rules` in user management settings https://github.com/filebrowser/filebrowser/issues/1034

**Comment by o1egl** [comment]
This feature will be a part of the next major release.

**Comment by be-engineer** [comment]
> ![image](https://user-images.githubusercontent.com/56914900/103979603-151db480-51b9-11eb-9bd1-91bddd3c7351.png) I can see in user management panel, only one scope line is allowed. What if we want to add multi-scopes to allow user to access different resources in same folder-level?
> 
> Can you guys help to add multi scope lines or support separating paths in single scope line?

Really need this feature。It is best to set permissions for each scope individually
