### ISSUE TITLE
Opening filebrowser only get a screen loading

### ISSUE THREAD

**Issue by ffuentese** [filebrowser/filebrowser#1237]
**Description**
I just tried to install this. It seems simple but I ran it and configured it so that it shows what's on a small VPS I have. I installed it using the instructions with caddy

**Expected behaviour**
To see my files

**What is happening instead?**
Please, give full error messages and/or log.

I just see dots showing that something has to load. It seems that some files aren't loading from the UI of filebrowser itself.

Failed to load resource: the server responded with a status of 404 ()
chunk-vendors.c7045283.css:1 Failed to load resource: the server responded with a status of 404 ()
app.116cf73e.js:1 Failed to load resource: the server responded with a status of 404 ()
chunk-vendors.804f7f8b.js:1 Failed to load resource: the server responded with a status of 404 ()
chunk-394af474.fdfad866.js:1 Failed to load resource: the server responded with a status of 404 ()
app.116cf73e.js:1 Failed to load resource: the server responded with a status of 404 ()
(index):1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
/static/img/icons/android-chrome-192x192.png:1 Failed to load resource: the server responded with a status of 404 ()
(index):1 Error while trying to use the following icon from the Manifest: https://[my url]/static/img/icons/android-chrome-192x192.png (Download error or resource isn't a valid image)

**Additional context**
I'm using Debian Buster (10). 

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Install according the instructions and implement the reverse proxy in Caddyfile (apparently the syntax has changed from proxy to reverse_proxy)

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by DanielYWoo** [comment]
what kind of auth are you using?

**Comment by ffuentese** [comment]
I just followed the instructions. I assumed that I was going to be asked for a user and a password right after as the tutorial says.

According to this file the authentication is "json" 

https://ttm.sh/daH.txt

**Comment by ffuentese** [comment]
I think this is more of an instructions issue so I fixed it finding the right way to write the Caddyfile configuration:

```
# The Caddyfile is an easy way to configure your Caddy web server.
#
# Unless the file starts with a global options block, the first
# uncommented line is always the address of your site.
#
# To use your own domain name (with automatic HTTPS), first make
# sure your domain's A/AAAA DNS records are properly pointed to
# this machine's public IP, then replace the line below with your
# domain name.
example.com

# Set this path to your site's directory.

root * /var/www/html

# Enable the static file server.
#file_server

# Another common task is to set up a reverse proxy:
reverse_proxy localhost:8080

# Or serve a PHP site through php-fpm:
# php_fastcgi localhost:9000

# Refer to the Caddy docs for more information:
# https://caddyserver.com/docs/caddyfile
```

**Comment by paboum** [comment]
Same for me with:
```
example.com:443 {
    reverse_proxy filebrowser/* http://localhost:8080 # <-- redirect to filebrowser here
    root * /var/www/html/
    tls /etc/letsencrypt/live/example.com/fullchain.pem /etc/letsencrypt/live/example.com/privkey.pem
    file_server browse
    encode gzip
    log {
        output file /var/log/caddy/example.com-access.log
    }
}
```
Apparently, filebrowser doesn't know how to work in a path like `filebrowser/`. Using `-b filebrowser/` causes main page to request multiple css and js files from `example.com/filebrowser/filebrowser`, similar with `-b https://example.com/filebrowser`.

**Comment by matifali** [comment]
> Same for me with:
> 
> ```
> example.com:443 {
>     reverse_proxy filebrowser/* http://localhost:8080 # <-- redirect to filebrowser here
>     tls /etc/letsencrypt/live/example.com/fullchain.pem /etc/letsencrypt/live/example.com/privkey.pem
>     log {
>         output file /var/log/caddy/example.com-access.log
>     }
> }
> ```
> 
> Apparently, filebrowser doesn't know how to work in a path like `filebrowser/`. Using `-b filebrowser/` causes main page to request multiple css and js files from `example.com/filebrowser/filebrowser`, similar with `-b https://example.com/filebrowser`.

I had to use a subdomain.
