### ISSUE TITLE
Render readme.md in directories

### ISSUE THREAD

**Issue by DarkPark** [filebrowser/filebrowser#1244]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be nice to detect readme.md in each directory and render it.

**Comment by o1egl** [comment]
Can you describe this feature better? What is the use case? In general I don't think that it's a good idea to display something else but the list of files. We can add markdown files preview https://github.com/filebrowser/filebrowser/discussions/1240

**Comment by DarkPark** [comment]
The idea is to have a short description for each directory and see it immediately when you open this directory. It's not the same as to open the file to edit or preview.
You can see this feature in action in NextCloud. They have a demo - https://try.nextcloud.com/

**Comment by ghost** [comment]
Same feature exists here on GitHub for every repo.

**Comment by DarkPark** [comment]
@ndalliard thank you
it's one of the best examples
very convenient

**Comment by pklausner** [comment]
Even antique Apache does that. Or e.g. https://github.com/lrsjng/h5ai . This seems a rather standard / expected way to add directory specific information to a plain listing.

**Comment by JaneJeon** [comment]
+1 for this feature. Obviously not a super _urgent_ feature request per se, but it would still be very nice to have it.
