### ISSUE TITLE
Example systemd unit file and Tor setup

### ISSUE THREAD

**Issue by psqnt** [filebrowser/filebrowser#1246]
**Is your feature request related to a problem? Please describe.**
I am able to start FileBrowser on my raspberry pi and access files when on the same network. I would like to be able to run this as a tor hidden service, so I can access my files from anywhere, as long as I have the onion address.

**Describe the solution you'd like**
Can a clear example setup be added to the repository or instructions to do this. editing the torrc file and systemd startup instructions

**Describe alternatives you've considered**
I've tried adding this to the torrc file:
```
# Hidden Services for FileBrowser 
HiddenServiceDir /var/lib/tor/filebrowser/
HiddenServiceVersion 3
HiddenServicePort 8060 127.0.0.1:8060
```
it does not seem to get it working properly

**Comment by niubility000** [comment]
try to change 127.0.0.1 to 0.0.0.0

**Comment by WeidiDeng** [comment]
Tor configuration is beyond the scope of the project. And filebrowser doesn't check for hosts by default. As long as Tor forward traffic to filebrowser's port, it should work.
