### ISSUE TITLE
Upload file appears error : 413 Request Entity Too Large version-2.11.0

### ISSUE THREAD

**Issue by spysir** [filebrowser/filebrowser#1247]
<img width="419" alt="413" src="https://user-images.githubusercontent.com/59646715/104892200-db189380-59ac-11eb-8d1e-6bc1b8e68bbb.png">

**Comment by WeidiDeng** [comment]
Configure Nginx to allow larger upload.

**Comment by o1egl** [comment]
This is your proxy server's error.
