### ISSUE TITLE
Allow a user to use multiple commands

### ISSUE THREAD

**Issue by benasse** [filebrowser/filebrowser#1250]
**Description**
I try to allow a user to run commands via filebrowser.
Below is how I configure the software: :
```
filebrowser config init
filebrowser config set --auth.method noauth
filebrowser config set --commands "ip, bash, python3"
filebrowser users add "default-user" "default-password"
```

**Expected behaviour**
I expect to be able to run the commands I have configured via the shell from the web interface.

**What is happening instead?**
In practice I can only run the first configured command.

In my example I can only launch the `ip` command.

**My questions**
Is it a bug or does it come from a bad configuration on my side?

**Comment by WeidiDeng** [comment]
Separate commands with space, not comma

**Comment by benasse** [comment]
Indeed it's also what I saw in the documentation, but it doesn't work.

I finally managed to make it work, you only have to use commas.

```
filebrowser config init
filebrowser config set --auth.method noauth
filebrowser config set --commands "ip,bash,python3"
filebrowser users add "default-user" "default-password"
```

**Comment by WeidiDeng** [comment]
Why don't set it in the ui? They'are available in ```global settings``` > ```user default```, where commands are separated by space.

**Comment by benasse** [comment]
The interface doesn't allow me to do what I want, I need to automate the filebrowser installation and specify the commands that can be executed during the installation.

**Comment by o1egl** [comment]
Updated the docs. I think we can close this issue
