### ISSUE TITLE
Enable a user to use all commands

### ISSUE THREAD

**Issue by kaaax0815** [filebrowser/filebrowser#1254]
**Is your feature request related to a problem? Please describe.**
I don't want to specify all command I want to use

**Describe the solution you'd like**
In Allowed Commands provide a feature to use '*' (For all)

**Comment by snokin** [comment]
> **Is your feature request related to a problem? Please describe.**
> I don't want to specify all command I want to use
> 
> **Describe the solution you'd like**
> In Allowed Commands provide a feature to use '*' (For all)

It didn't work. Commands not any response.

**Comment by o1egl** [comment]
Since the commands matcher uses regexp you can use `.*` to match any string
