### ISSUE TITLE
Lazy loading didn't load some situation.

### ISSUE THREAD

**Issue by snokin** [filebrowser/filebrowser#1257]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

Open folder with the list mode. And turn it in card mode. That will makes lazy loading don't work. And just shows fewer files on page.

**Expected behaviour**
What did you expect to happen?

Fix it.

**What is happening instead?**
Please, give full error messages and/or log.

No error log.

**Comment by alexisLefebvre** [comment]
Same issue than #1238?

**Comment by snokin** [comment]
> Same issue than #1238?

Yes. same.

**Comment by o1egl** [comment]
Duplicate
