### ISSUE TITLE
Command line is insane when they using it for hack

### ISSUE THREAD

**Issue by snokin** [filebrowser/filebrowser#1259]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

When l using command like `ls cp mv` just action in users current folder. But if they are using absolute path like `ls /home` it works too. Even they can move or copy any files from anywhere to their current folder. Like `cp /etc/some/thing/config.ini ./` is worked well. Is insane.

**Expected behaviour**
What did you expect to happen?

Can we just limit their action in their current folder.

**Comment by o1egl** [comment]
This is expected behavior. We can't limit commands to use some particular directory only. It is the admin's responsibility to decide which commands to allow.
