### ISSUE TITLE
Please more detailed documents in website or GitHub

### ISSUE THREAD

**Issue by snokin** [filebrowser/filebrowser#1260]
**Is your feature request related to a problem? Please describe.**
Add a clear and concise description of what the problem is. E.g. *I'm always frustrated when [...]*

The configuring way is so strange. And i do seen the helps and makes me more confused. I'm hosting file browser like `filebrowser - c /etc/filebrowser/config.json` And in the terminal using settings it will using default database file path like `~/` . And i was pointed in config.jason to another place. Some configuration is on the web. Some are like disable image preview is on config files and the user list on database. And their documentation is very poor in official website and GitHub. Lot of functions are i found in issues and discussion and some blogs. And i never realize how command lines are work and how do i customize these things. I really hope a more detailed documentation.

**Describe the solution you'd like**
Add a clear and concise description of what you want to happen.

More detailed documentation.

**Comment by o1egl** [comment]
The docs are available in this repo https://github.com/filebrowser/docs. You are welcome to make a PR to improve the docs.
