### ISSUE TITLE
Request for function own commands for command lines

### ISSUE THREAD

**Issue by snokin** [filebrowser/filebrowser#1261]
**Is your feature request related to a problem? Please describe.**
Add a clear and concise description of what the problem is. E.g. *I'm always frustrated when [...]*

On terminal I'm using a shell function on `/etc/profile.d/xx.sh` which is making a symbolic links for users, example `givepub maomao` will create a symbolic links for user maomao. And it doesn't work on command line in web. I think more useful is like let user check their usage like alias `du -h --max-depth=1` to command like `myusage`.

**Describe the solution you'd like**
Add a clear and concise description of what you want to happen.

Make own commands like these.

**Comment by o1egl** [comment]
Have you allowed this command in settings? What's the error you get?

**Comment by o1egl** [comment]
No response

**Comment by snokin** [comment]
> Have you allowed this command in settings? What's the error you get?

Yes. I'm allowed. It showed
`/bin/bash: givepub: command not found`

**Comment by o1egl** [comment]
It means that givepub is not in the PATH
