### ISSUE TITLE
Some pics show in wrong direction under full size mode in android phone's browser.

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1264]
For some pics in full size mode, the PC's web browser can show them in correct direction. But the android phone's web browser can not show them in correct direction. It's weird. Please fix it.

**Comment by alexisLefebvre** [comment]
Please create as many issues as many problems you have.

**Comment by niubility000** [comment]
> Please create as many issues as many problems you have.

Oh, thank you. I will modify it.

**Comment by niubility000** [comment]
oh, I found the reason. When I use --disable-preview-resize --cache-dir cache, the long size pics will show in wrong direction. Please fix it.

**Comment by o1egl** [comment]
This is expected behavior. The preview resizer tries to detect and fix image orientation. When you disable it, you see the source image with an unchanged orientation.

**Comment by niubility000** [comment]
> This is expected behavior. The preview resizer tries to detect and fix image orientation. When you disable it, you see the source image with an unchanged orientation.

Wow, then is there a way to fix it? My router's cpu is low, can't do the heavy jobs to resize pictures. If I don't disable it, I can't see any picture. (same thing with version 2.5.0) It's hard for a router to resize thousands of pictures. It's arm v5. 

They said "nextcloud" is very slow because it try to resize every picture.  "filerun" is much faster, because it only resize pictures larger than 10M. 
So maybe we could add a function like that, and let the user to set the exact value (10M or 5M....) based on their environment. 
My internet speed is high. I can browser the full size pictures with no problem. I don't wanna use my computer as the serve, I can't keep it on all the time.  So, just hope the full size pics can be shown in correct direction.

**Comment by o1egl** [comment]
I think in your case, the better solution would be to fix orientation in source files and disable resizing.

**Comment by niubility000** [comment]
> I think in your case, the better solution would be to fix orientation in source files and disable resizing.

Yeah, I am trying to find a software to do that in pc. 

As I know, JavaScript can read the the orientation info from Jpeg's EXIF. and use canvas to fix the direction.
Here's an example: https://github.com/legend-li/img_compress_rotate_preview_upload, just download the zip file and doubleclick ImgProcess.html. it's very fast.

**Comment by niubility000** [comment]
I almost fixed it.

**Comment by niubility000** [comment]
That's easy:
just add one sentence in styles.css
#previewer .preview img {
  max-height: 100%;
  margin: 0;
  transition: height .1s linear;
  cursor: pointer;
  **_image-orientation: from-image;_**
}

but currently not all android browsers support this, we need use android chrome, or android firefox.
https://caniuse.com/css-image-orientation

**Comment by niubility000** [comment]
Oh, we donot need to modify the styles.css file. just update the android browser. or use chrome, firefox. They will correct the direction automatically.
