### ISSUE TITLE
Double click to zoom pics in phone's browser.

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1266]
I can't double click to enlarge the pics in the android phone's web browser when I browser them. But I can do that in the PC's web browser.

**Comment by niubility000** [comment]
I got how to fix it. just add some codes in ExtendedImage.vue , I copied it from WeidiDeng. :)
[ExtendedImage.zip](https://github.com/filebrowser/filebrowser/files/5905344/ExtendedImage.zip)

Feel free to merge it to master.

**Comment by o1egl** [comment]
Please make a PR
