### ISSUE TITLE
Making the preview windows much larger.

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1268]
I just changed some codes in the file (filebrowser\frontend\src\css\styles.css) to make the preview window as large as possible. Currently it looks pretty good. All the buttons and bars are transparent and shown above the pics layer. Now the pics are much clearer in the Phone's web browser. 
I already uploaded some screenshots, just take a look. If you like it, you can  compile it. I posted the method to cross compile filebrowser using windows pc. I hope some one can improve it, especially add a function to swipe the screen to switch to the next or last pic/video in the phone's browser.

❤️ Thank you!
[styles.zip](https://github.com/filebrowser/filebrowser/files/5900148/styles.zip)

[screenshot1.zip](https://github.com/filebrowser/filebrowser/files/5900191/screenshot1.zip)

(I can't upload the pics to githubcontent.com, it's blocked here. so I just upload the zip files instead. Hope you can download them.)

**Comment by o1egl** [comment]
You can make a PR with proposed changes
