### ISSUE TITLE
Cross compile (build) the "filebrowser" under windows pc.

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1269]
Since windows can't run the "wizard.sh" in the source code folder，some people maybe don't know how to build or cross compile the "filebrowser" under windows pc. I just wrote a document about it. 

Please see the attachment. Hope it's helpful.

[Cross compile filebrowser under windows pc.docx](https://github.com/filebrowser/filebrowser/files/5905295/Cross.compile.filebrowser.under.windows.pc.docx)

**Comment by niubility000** [comment]
I know I posted this file in wrong session, feel free to move it to the right session.

**Comment by o1egl** [comment]
We don't plan to support windows shell. The recommended way is to use WSL
