### ISSUE TITLE
Right click context menu support

### ISSUE THREAD

**Issue by xiaozhuai** [filebrowser/filebrowser#1276]
Good job! I love filebrowser very much, it works pretty good on my openwrt router. 

Would you please add support for right click context menu?

**Comment by alexisLefebvre** [comment]
What is the expected behaviour of that right click context menu?

**Comment by xiaozhuai** [comment]
When right click on a file or directory, it shows a context menu contains rename, copy, cut, delete, share, etc...
It will be much convenient.

**Comment by xiaozhuai** [comment]
[https://github.com/xiaozhuai/luci-app-filebrowser](https://github.com/xiaozhuai/luci-app-filebrowser)
Here is an OpenWRT luci app what I made.

**Comment by niubility000** [comment]
You can do it in your phone's browser. just long press.  I also think we need this function for the Pc' browser.

**Comment by o1egl** [comment]
Duplicate of https://github.com/filebrowser/filebrowser/discussions/1031
