### ISSUE TITLE
(Suggestion for) proxy auth hard to implement for the docker container

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1277]
**Description**
Proxy auth doesn't work when the service is running behind a nginx proxy. Using docker container.

I've added the below to my .filebrowser.json:

        "auth.method": "proxy",
        "auth.header": "X-WEBAUTH-USER"

Set the header in nginx,  and it doesn't work.

**Comment by ghost** [comment]
Solved: the problem is that some config cannot be set with .filebrowser.json. For the docker instance, those config are stored in database.db. So we need to edit this database.db somehow.

I managed to solve this by installing filebrowser on my local machine (instead of the docker instance)

I copied database.db in the docker mapped volume to my user directory, then renamed it to filebrowser.db (the filename recognized by the local instance.)

And used the following command in terminal on the local machine:
filebrowser config set --auth.method=proxy --auth.header=MYHEADER

And then replaced the docker database with this newly modified one.

_______________

As you can see, this is not an elegant solution. My suggestions below:

- implement docker exec bash, so that we can use the filebrowser config set command within the container
- change the way .filebrowser.json works such that it can modify more configs.
- change the gui such that it can modify more configs.

I will keep this issue opened for now so that it get more attention.

**Comment by o1egl** [comment]
The configuration method will be changed in the next major release. The only way to change auth method of the existing app is CLI
