### ISSUE TITLE
Not able to upload file

### ISSUE THREAD

**Issue by patratapas** [filebrowser/filebrowser#1278]
**Description**
Not able to upload file. Its giving Forbidden issue.

**Expected behaviour**
File should upload properly.

**What is happening instead?**
File not uploading.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by alexisLefebvre** [comment]
Does it work with small files? What file sizes are accepted or throw an error?

**Comment by patratapas** [comment]
File size is 1 kb.

**Comment by o1egl** [comment]
We need more context. Which error do you get on the server/client?

**Comment by shinytreecko** [comment]
I'm getting the exact same issue. I'm not sure how to check the logs

**Comment by o1egl** [comment]
The logs are printed to the stdout.

**Comment by shinytreecko** [comment]
This might be a dumb question, but what is the stdout and how would I check the logs in it?

**Comment by shinytreecko** [comment]
Also since I'm not running filebrowser with docker and instead just as a service, do the logs still print to the same place?

**Comment by o1egl** [comment]
How you run the service?

**Comment by shinytreecko** [comment]
I run it as a standalone executable and making it start on reboot with systemctl as a service.

**Comment by o1egl** [comment]
Try this one https://unix.stackexchange.com/questions/225401/how-to-see-full-log-from-systemctl-status-service

**Comment by shinytreecko** [comment]
These are my results for doing journalctl -u to show all services that have logs, but when I check the status of filebrowser.service using systemctl status filebrowser.service it says the journal has been moved.


![Screenshot (159)](https://user-images.githubusercontent.com/23491590/108093629-e6aeb700-704b-11eb-954c-5a26a025607a.png)

**Comment by shinytreecko** [comment]
wow i fixed it... somehow the permissions of the directory my filebrowser service stores its files wasn't owned by filebrowser

**Comment by o1egl** [comment]
Shall we close this ticket?

**Comment by shinytreecko** [comment]
Since I didn't open the issue, I would say no for a couple of days just in case OP's problem requires a different solution from what my problem required. But thank you so much!

**Comment by o1egl** [comment]
No response from the author
