### ISSUE TITLE
Setting password at startup does not work

### ISSUE THREAD

**Issue by vemonet** [filebrowser/filebrowser#1286]
**Description**
I am trying to set the password at the start of the Docker container (so that it does not get reset to admin if the docker container is retarted, which is really common)

**Expected behaviour**
I should be able to login with the password I provide with `-e FB_PASSWORD`  environment variable

**What is happening instead?**
`Wrong credentials` with the provided password, and even the default `admin` password does not work anymore 

**How to reproduce?**
```bash
docker run -e FB_PASSWORD=test -p 80:80 filebrowser/filebrowser
```
Try to login to http://localhost using `admin` username / `test` password

**Additional context**
Control run: `admin` password works
```bash
docker run -p 80:80 filebrowser/filebrowser
```

According to the doc the password can be provided, even if it is not clear if it needs to be hashed before (which would not be ideal, but is mentionned):
> --password string          hashed password for the first user when using quick config (default "admin")

```bash
openssl passwd test
docker run -e FB_PASSWORD=Uhgep98fkCgKE -p 80:80 filebrowser/filebrowser
```
Neither `test` nor `admin` passwords worked

**Comment by o1egl** [comment]
You should hash your password with `docker run filebrowser/filebrowser hash mypassword` command and then use it as param `docker run -e FB_PASSWORD=Uhgep98fkCgKE -p 80:80 filebrowser/filebrowser --password hashed_password`
