### ISSUE TITLE
When type in the search box, lively show the satisfied items in the current folder. 

### ISSUE THREAD

**Issue by HaujetZhao** [filebrowser/filebrowser#1293]
**Is your feature request related to a problem? Please describe.**

In a folder which contains lots of items, I can't precisely and quickly locate to a folder by name. 

When I use the search bar, after enter, it tries to search the whole folder recursively, which consumes a lot of times if the folder structure is complex. 

On windows explorer, I can simply type the header character, then it will automatically select the first name-satisfied file. 

**Describe the solution you'd like**
When type in the search box, lively show the satisfied items in the current folder. (no need to search recursively before pressing enter key)

**Describe alternatives you've considered**
On the interface, when type in  a few character quickly, automatically select the first satisfied item, just like the behavior of Windows Explorer.

**Comment by benasse** [comment]
I agree having a field that would filter files in the current directory would greatly improve the user experience.
Especially in directories with a large number of files.

**Comment by jniggemann** [comment]
I wanted to propose exactly this feature but then I came across you feature request.

**Comment by jniggemann** [comment]
Commenting to not auto-close, as I'd like to see this implemented some day.

**Comment by jniggemann** [comment]
Commenting to not auto-close, as I'd like to see this implemented some day.

**Comment by MistarMuffin** [comment]
This is a critical need, IMO. I have a folder with thousands of sub-folders. They don't all get loaded into the browser DOM, so I can't even use the browser "find" function to jump down to what I am looking for. I have just settled on manually typing the path in the browser address bar. Using the built-in search is slow due to the recursive nature, as noted. An instant "filter" on the current folder would be very welcome. Thank you!

**Comment by jniggemann** [comment]
Commenting to not auto-close, as I'd like to see this implemented some day.

**Comment by jniggemann** [comment]
Commenting to not auto-close, as I'd like to see this implemented some day.

**Comment by jniggemann** [comment]
Commenting to not auto-close, as I'd like to see this implemented some day.

**Comment by jniggemann** [comment]
Commenting to not auto-close, as I'd like to see this implemented some day.

**Comment by jniggemann** [comment]
Project hasn't seen a lot of activity lately, I'll try to hack something together myself. I'll send a PR if it's good enough someday. Unsubscribing.
