### ISSUE TITLE
filebrowser on docker swarm with RaspberryPi doesn't work

### ISSUE THREAD

**Issue by genzzz** [filebrowser/filebrowser#1294]
Hello, i was trying to install filebrowser with docker on raspberry pi4. i pulled filebrowser/filebrowser:pi. when i run it with 'docker run' command, it gives this warning: 'WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested', but it works (i can access it).

The problem is when i want to run it on docker swarm, with 'docker stack' command. it creates the service, but with error "no suitable node (unsupported…".

**Comment by ramiresviana** [comment]
The cause of the warning may be that all docker images are listed as linux/amd64 on docker hub.

@o1egl should the images architecture be listed correctly at https://hub.docker.com/r/filebrowser/filebrowser/tags?

**Comment by genzzz** [comment]
exactly, even the tag 'pi' is listed as 'linux/amd64'. would be better if you correct them.
thnx.

**Comment by o1egl** [comment]
@genzzz fixed in v2.12.0. Now you can simply use `filebrowser/filebrowser` docker image.
