### ISSUE TITLE
service can't bring up

### ISSUE THREAD

**Issue by dikaye** [filebrowser/filebrowser#1296]
service can't bring up.

# filebrowser -c /data01/filebrowser/config.json
2021/02/20 08:35:16 Using config file: /data01/filebrowser/config.json
2021/02/20 08:35:16 the resource does not exist

#  cat /data01/filebrowser/config.json
{
    "address":"0.0.0.0",
    "database":"/data01/filebrowser/filebrowser.db",
    "log":"/var/log/filebrowser.log",
    "port":80,
    "root":"/data01/file",
    "username":"admin"
}

**Comment by ramiresviana** [comment]
Check the file permissions, is possible that Filebrowser is unable to access the required files.

**Comment by o1egl** [comment]
No response
