### ISSUE TITLE
Setting a hashed password at startup does not work

### ISSUE THREAD

**Issue by vemonet** [filebrowser/filebrowser#1299]
**Description**
I am trying to set a password at the start of the Docker container using a hashed password (so that it does not get reset to admin if the docker container is restarted, which is really common)

It is a follow up of this issue that has been closed: https://github.com/filebrowser/filebrowser/issues/1286

**Expected behaviour**

I followed the instructions @o1egl sent (thanks!) to hash the password using the docker image, to then provide it when starting the filebrowser:

```
docker run filebrowser/filebrowser hash mypassword
```

The command returns: `$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO`, so I will continue use this hash and should be able to login using `admin` as username and `mypassword` as password

> You should hash your password with `docker run filebrowser/filebrowser hash mypassword` command and then use it as param `docker run -e FB_PASSWORD=Uhgep98fkCgKE -p 80:80 filebrowser/filebrowser --password hashed_password`

It is not clear if the hash of the password should go in the `FB_PASSWORD` environment variable or the `--password` argument

According to the docs: https://filebrowser.org/cli/filebrowser#options The password arg correspond to the hashed password: "hashed password for the first user when using quick config (default "admin")"

So I tried all possible combination, but none of them work:

```bash
docker run -e FB_PASSWORD=$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO -p 80:80 filebrowser/filebrowser --password hashed_password
```

Passing the hash directly to the password arg (which is described in the docs) and to FB_PASSWORD environment variable:

```bash
docker run -e FB_PASSWORD=$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO -p 80:80 filebrowser/filebrowser --password $2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO
```

With quotes:

```bash
docker run -e FB_PASSWORD=$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO -p 80:80 filebrowser/filebrowser --password "$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO"
```

Just to the password arg:

```bash
docker run -p 80:80 filebrowser/filebrowser --password $2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO
```

Passing the hash as environment variable:
```bash
docker run -e FB_PASSWORD=$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO -p 80:80 filebrowser/filebrowser --password "$FB_PASSWORD"
```

**What is happening instead?**

Login with the username `admin` and the password `mypassword` does not work (using the password `admin` does not work neither)

**How to reproduce?**
Rerun exactly the docker command described and try to login with username `admin` and password `mypassword`

**Comment by o1egl** [comment]
As written in the docs you should use --password argument. The password has `$` and must be escaped. You can use single quotes for that `docker run -p 8080:80 filebrowser/filebrowser --password '$2a$10$Mlw4C/VVeWjQpJGLwO5huu2ttJ4bqKo9utv85QJIHRrHluDhv2EJS'`

**Comment by vemonet** [comment]
The docs also mentioned `FB_PASSWORD` environment variable and it was also part of the answer you provided in the previous issue

And in this try I properly used quotes, but it was double quotes:
 
```
docker run -e FB_PASSWORD=$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO -p 80:80 filebrowser/filebrowser --password "$2a$10$1FwZxnlCYECr93y3zOgcTOfvtuvt1F4j7Zup4858p5REo6EKYp8VO"
```

The doc should make it clearer

**Comment by o1egl** [comment]
@vemonet, you are welcome to contribute to the [docs](https://github.com/filebrowser/docs).
