### ISSUE TITLE
Support UID&GID environment variables

### ISSUE THREAD

**Issue by Alfagun74** [filebrowser/filebrowser#1300]
**Is your feature request related to a problem? Please describe.**
Currently filebrowser is always run as root user. I want it to run as a specific user on my linux. 

The only way to do otherwise is to use `--user` in the CLI or a docker-compose `user` entry. 
Sadly I can't use those options because my docker container is managed by [caprover](https://github.com/caprover/caprover).
(selfhosted Heroku-like Platform which supports Filebrowser as an One-Click-App ready to deploy.)
I don't have any docker-compose or command lines to edit. I can only pass in enviroment variables.

**Describe the solution you'd like**
Common Docker containers like those from "linuxserver.io" use PGID and PUID Environment variables so the User can select his default user.

**Describe alternatives you've considered**
Maybe an option in the settings to select which user should run the file ops.

**Comment by Alfagun74** [comment]
Dude this is NOT completed. Please reopen this ticket.

**Comment by luandro** [comment]
This should not be closed.Someone should give some tip on how to achieve this.

**Comment by luandro** [comment]
This is related to #1382 and #1390. The suggested solutions don't work.

**Comment by Alfagun74** [comment]
> This is related to #1382 and #1390. The suggested solutions don't work.

My ticket still should be reopened.

**Comment by Rene-Sackers** [comment]
Bump, agreed, we need PUID/PGID, especially for an application like this where file operations are literally the root of the entire application.

**Comment by luandro** [comment]
Question, doesn't the `filebrowser/filebrowser:s6` version provide that?

**Comment by Alfagun74** [comment]
> Question, doesn't the `filebrowser/filebrowser:s6` version provide that?

Never heard of it, but it seems like it uses a linuxserver.io alpine container as base image. Can you test it out?

**Comment by luandro** [comment]
> Never heard of it, but it seems like it uses a linuxserver.io alpine container as base image. Can you test it out?

I've tested and it seems to solve it. Would just like others in this issue to test it out to be sure. Just took me a long time to figure out this version existed, and why nobody cared to share about it on this issue.

**Comment by Rene-Sackers** [comment]
Just tried the s6 image as well, and it works perfectly fine with `PUID`/`PGID`. I love this application, but I feel like I'm either completely missing where all the documentation is, or the existing docs are very lacking. Did not know of this version of the docker image.

**Comment by Alfagun74** [comment]
nice! a great ending to the journey of this ticket.
