### ISSUE TITLE
Upload File 

### ISSUE THREAD

**Issue by augustisaque** [filebrowser/filebrowser#1301]
**Is your feature request related to a problem? Please describe.**
*I have a shared folder where I need to upload CSV files. In this folder runs also a process that retrieves the files I uploaded and moves them to another folder.

The problem is, sometimes I have a large file that takes, say, 1 minute to upload completely, so in the meantime, the other process that runs in that folder also gets the incomplete file and move it missing some important informations.*

**Describe the solution you'd like**
*It would be good if we had a function that creates a temporary file when a file is uploaded, and when all the information is inserted into that temporary file, it is renamed to the original name. We have this function in WinSCP: https://winscp.net/eng/docs/script_locking_files_while_uploading.*

Many Thanks,
Isaque
WhatsApp: +55 47 996424355
E-Mail: Isaque_august@hotmail.com

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/discussions/1182
