### ISSUE TITLE
added docker healthcheck

### ISSUE THREAD

**Issue by thost96** [filebrowser/filebrowser#1306]
**Is your feature request related to a problem? Please describe.**
It would be nice to add the possibility for a docker health check, so you know on docker swarm if the container is still running and is healthy or not. 

**Describe alternatives you've considered**
alternative would be a /health URL which can be called with curl.

**Comment by o1egl** [comment]
Added in https://github.com/filebrowser/filebrowser/commit/a721dc1f314732e60d331a1a7da97d06e0e8b613

**Comment by sarvesh-lad** [comment]
The health check fails when editing the json file with custom path and/or port

```
{
  "port": 8080,
  "baseURL": "/filebrowser",
  "address": "filebrowser",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```

**Comment by hepto** [comment]
> The health check fails when editing the json file with custom path and/or port
> 
> ```
> {
>   "port": 8080,
>   "baseURL": "/filebrowser",
>   "address": "filebrowser",
>   "log": "stdout",
>   "database": "/database.db",
>   "root": "/srv"
> }
> ```

You can override the HEALTHCHECK configured in the image via the `run` command:

https://docs.docker.com/engine/reference/run/#healthcheck

Specifically you can override the `CMD` to your needs, such as follows:

`--health-cmd "curl -f http://localhost:8080/health || exit 1"`
