### ISSUE TITLE
Automatically switch to the next song

### ISSUE THREAD

**Issue by LeXaMeN** [filebrowser/filebrowser#1314]
**Is your feature request related to a problem? Please describe.**
I wish I had a primitive audio player.
When you switch a song to the next song, the volume setting is "reset" to 100%.

**Describe the solution you'd like**
![Снимок экрана_2021-03-08_11-54-12](https://user-images.githubusercontent.com/31878437/110298755-019a9880-8006-11eb-8050-8beedcdd12b5.png)
Please do, when the song ended, the "Next" button was automatically pressed.
And to keep the volume setting.

**Describe alternatives you've considered**
A full-fledged audio player that would be displayed when the window was minimized.
You can add a "Music" tab to the bottom of "Files".
Or just when you click on a folder and there is music in it, the "Play all songs" or "Play all songs in random order" button appears.

**Comment by o1egl** [comment]
We don't plan to add a full-featured player to this project. This is out of the scope of this project

**Comment by LeXaMeN** [comment]
Then please do auto-switching and so that the volume is not reset.
