### ISSUE TITLE
How to deal with Header Proxy auth and public shared link?

### ISSUE THREAD

**Issue by Hraph** [filebrowser/filebrowser#1316]
**Is your feature request related to a problem? Please describe.**
I use the header proxy authentication method, all my requests are identified upstream by an SSO service.
It is impossible to access publicly a shared link with this method as it would be possible with JSON Auth.
There is no way to bypass proxy header, login is disabled and FB is definitely waiting for a header. Is there a solution for this problem?

**Describe the solution you'd like**
I would like to access and download the shared link file as a non logged user when proxy header is not defined. 
To permit that, custom rules should be also set on reverse proxy to allow direct access to "/share/{token}", "/static/\*" and "/api/public/\*"

**Describe alternatives you've considered**
Create a "public" username with minimum rights is not a proper safe solution

**Comment by o1egl** [comment]
Fixed in v2.14.1
