### ISSUE TITLE
Set default "viewMode" to "list" in config file

### ISSUE THREAD

**Issue by minelminel** [filebrowser/filebrowser#1317]
**Is your feature request related to a problem? Please describe.**
Many of our directories accessed via filebrowser have very verbose names, and are difficult to differentiate at a glance in "mosaic" (grid) view. Between page visits we have to constantly switch the view to listView.

**Describe the solution you'd like**
A config file value for `"defaultViewMode": "listView"` or something similar, which would have the default of `"mosaic"` to maintain current behavior while still allowing users to modify this.

**Describe alternatives you've considered**
Monitoring the network requests sent after clicking the view mode button, a PUT request is made to `/api/users/1` (this number may be different in an authenticated use case) with the request body
```json
{"what":"user","which":["viewMode"],"data":{"id":1,"viewMode":"listView"}}
```
I have examined ways in which to fire this request off on initial page load, but have not had much success in a production environment.

**Additional context**
I am running release version 2.8.0 at commit `5aaeb3b76d833381d90bec5e1500ccdaecfb2bf5`

**Edit**
I do see in [users.go](https://github.com/filebrowser/filebrowser/blob/fc5506179a64e9e2f57f7b6d6cce4b95f5ebc235/users/users.go#L15) that the view mode can be configured seemingly on a per-user basis, I guess my question is whether this can be configured *globally*.

**Comment by ramiresviana** [comment]
You can use `filebrowser config` cli to change the configuration. Take a look at https://filebrowser.org/cli/filebrowser-config-set
