### ISSUE TITLE
Can you provide some detail about how to build this plugin with caddy? 

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#132]
_From @messyidea on July 10, 2017 13:40_

Hi,

At last issue, with your help, this memory problem has fixed.
I want the newest plugin, but the offical caddy website have not update.
So I want to build it by myself, but I have met some problems now.

I followed this [tutorial](https://github.com/mholt/caddy/wiki/Extending-Caddy) and some commands at [travis-ci](https://travis-ci.org/hacdias/filemanager). Finally I got a binary about caddy.
But when I execute it, I see the error: "could not locate box "./assets/dist""
It seems that some assets are not properly compiled.
As I have little knowledge about js and babel, I can not continue to build it.

Can you provide some detail about how to build this plugin when you are free?
Thank you~

 

_Copied from original issue: hacdias/filemanager-old#101_

**Comment by hacdias** [comment]
Hello @messyidea!

I'm doing a complete rework on this plugin and the new version will be out soon and I'll leave the instructions afterwards.

But if this is a urgent thing, I can write them today.

**Comment by hacdias** [comment]
_From @messyidea on July 10, 2017 14:18_

Hi,
It's not very urgent to me now. 
Just finish your own work first :)
Thank you ~

**Comment by hacdias** [comment]
I'll leave more information afterwards, but try building 465b10a the way you did before. It should work.

**Comment by hacdias** [comment]
@messyidea, I just wrote some [instructions](https://github.com/hacdias/filemanager/blob/master/README.md#contributing) and I hope they can help you, but I'll try to improve them soon.

**Comment by messyidea** [comment]
Hi,
With your build script, I can build it by myself now. This issue can be closed. Thank you~
