### ISSUE TITLE
Breakpoint upload support 

### ISSUE THREAD

**Issue by Orefa** [filebrowser/filebrowser#1320]
Is there a plan to support breakpoint upload, such as support for [tus](https://tus.io/)

https://tus.io/protocols/resumable-upload.html

https://tus.io/

https://github.com/tus/tusd

**Comment by o1egl** [comment]
Yes, there is. I also was considering using tus protocol for that.

**Comment by o1egl** [comment]
I close this issue since we have an open discussion for this topic https://github.com/filebrowser/filebrowser/discussions/1182
