### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by wireva** [filebrowser/filebrowser#1328]
Adding OIDC support would allow to use central authentication like keycloak. I don't mean the public OIDC auth, but the confidential one that needs to be configured on consumer and provider

**Comment by alvaroaleman** [comment]
You can already do this today with an auth proxy like e.G. [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) and the [proxy auth method](https://filebrowser.org/configuration/authentication-method#proxy-header). Be aware that this currently breaks shares, xref https://github.com/filebrowser/filebrowser/issues/1316

**Comment by o1egl** [comment]
We not going to implement native oauth/openid support. As mentioned you can use a proxy for that. This feature might be a part of the next major release

**Comment by guitarzero** [comment]
> You can already do this today with an auth proxy like e.G. [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) and the [proxy auth method](https://filebrowser.org/configuration/authentication-method#proxy-header). Be aware that this currently breaks shares, xref #1316

According to this xref, and since 21 march 2021, shares are no more broken (not tested) in version v2.14.1

**Comment by melaniestnls** [comment]
> You can already do this today with an auth proxy like e.G. [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) and the [proxy auth method](https://filebrowser.org/configuration/authentication-method#proxy-header). Be aware that this currently breaks shares, xref #1316

Hello, I have a question. I am trying to implement this solution, with filebrowser running as a service in a kube cluster. I am stuck on configuring proxy authentication. Is it possible to implement this authentication method using a configuration file instead of the command line?
