### ISSUE TITLE
When "Hide dotfiles" on, all share files appear as "You don't have permissions to access this."

### ISSUE THREAD

**Issue by megabitsenmzq** [filebrowser/filebrowser#1335]
**Description**
When "Hide dotfiles" on, all share files appear as "You don't have permissions to access this."

**Expected behaviour**
Files I shared should be shown as normal.

**What is happening instead?**
The share links always show "You don't have permissions to access this." until I disabled "Hide dotfiles".
I can see this file normally if not through a share link.

**Additional context**
I'm using filebrowser on a Mac. With no Docker or Caddy, just running the executable.

**How to reproduce?**
Just turn "Hide dotfiles" on, then open any share links.

**Comment by ramiresviana** [comment]
Files with a prefix dot in the name will be hidden and its access restricted when that option is checked. Shared files requires the user who created the share to have permission to access the files, otherwise a error message is displayed when the share is accessed.

**Comment by megabitsenmzq** [comment]
But I'm not sharing a file with prefix dot. The file I try to share is not hidden.
> Files with a prefix dot in the name will be hidden and its access restricted when that option is checked. Shared files requires the user who created the share to have permission to access the files, otherwise a error message is displayed when the share is accessed.

**Comment by ramiresviana** [comment]
This happens to every file or a specific one? Does previous versions of Filebrowser have that issue? Please provide server logs and full path of the file that causes the error.

**Comment by megabitsenmzq** [comment]
> This happens to every file or a specific one? Does previous versions of Filebrowser have that issue? Please provide server logs and full path of the file that causes the error.

It happens to every file. And the previous version I have used doesn't have the "Hide dotfiles" feature (or I didn't know that) yet.

```
2021/03/19 01:01:40 No config file used
2021/03/19 01:01:40 Listening on [::]:80
2021/03/19 01:01:55 2da0w89g: 403 27.95.72.154 permission denied
```

Log just says "403 permission denied" when I'm trying to open that share link. And the file path I just tried is "/Downloads/mpc/mpc1.mkv".

And here are all my rules, all "disallow":

```
.*\.rslsc$
Icon
\/\..*$ (Hide dotfiles instead of using the option.)
/Backup
/Library
```

By the way, if you can also add this "hide dotfiles" to the global settings (or the user default settings), it will be useful.
