### ISSUE TITLE
Deleting file 

### ISSUE THREAD

**Issue by RBH4908** [filebrowser/filebrowser#1336]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

**Expected behaviour**
What did you expect to happen? remove file

**What is happening instead?** Multiple selection enabled

clear
chevron_right
404 page not found
Please, give full error messages and/or log.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by ramiresviana** [comment]
Please provide a proper description of your issue.

**Comment by RBH4908** [comment]
I did what else do you need? When I try deleting files it doesn't work. Get error 404

**Comment by ramiresviana** [comment]
What is the name and location of the file that you are trying to delete? Since when the issue started occurring? What version of Filebrowser you are using? Please provide more details about your issue including server logs, environment and configuration.
