### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by WangRex** [filebrowser/filebrowser#1337]
**Description**
when I upload a file, it returns this error "500 Internal Server Error"

**Expected behaviour**
upload success

**What is happening instead?**
exec: "bash": executable file not found in $PATH

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by ramiresviana** [comment]
Please provide more details about your issue including server logs, environment and configuration. Also is important to tell with details how to reproduce the issue.

**Comment by ramiresviana** [comment]
The error `exec: "bash": executable file not found in $PATH` means that the bash executable was not found when running the `After Upload` hook. If you are using a Filebrowser docker image you can use `ash`, the Alpine Linux shell.
