### ISSUE TITLE
Permission denied on permanent link since last update

### ISSUE THREAD

**Issue by Sim7b** [filebrowser/filebrowser#1338]
**Description**
Permission denied on permanent link since last update

**What is happening instead?**
`2021/03/17 12:58:44 qTeeMKqn/Mods/Assetto Corsa/Voitures/BTCC/90's/btcc_1996_peugeot_406.zip: 403 192.168.0.1 permission denied

2021/03/17 12:58:44 kaNun0Mf/Mods/Assetto Corsa/Voitures/BTCC/90's/btcc_1996_vauxhall_vectra.zip: 403 192.168.0.1 permission denied

2021/03/17 12:58:44 DFvOQP4l/Mods/Assetto Corsa/Voitures/BTCC/90's/btcc_1998_ford_mondeo.zip: 403 192.168.0.1 permission denied

2021/03/17 13:00:12 qTeeMKqn/Mods/Assetto Corsa/Voitures/BTCC/90's/btcc_1996_peugeot_406.zip: 403 192.168.0.1 permission denied`

**Comment by ramiresviana** [comment]
Permission denied errors will happen when the user who created the share has no permissions to access the requested file. Check the permissions and rules on the user profile.

**Comment by Sim7b** [comment]
I have an admin role, I can access to the file, I can create a new share but link don't work

**Comment by ramiresviana** [comment]
What is the operational system and Filebrowser configuration? Please provide full path of a file that causes the error.

**Comment by Sim7b** [comment]
OS Unraid
Docker
All files causes errors, I can access and download everything from web interface. Just sharing doesn't work
https://cloud.flat6-team-eracing.fr/share/-312ygZh

**Comment by ramiresviana** [comment]
The option **Hide dotfiles** is enabled on the user profile?

**Comment by Sim7b** [comment]
Yes
