### ISSUE TITLE
Files with certain characters cannot be played or edited. 

### ISSUE THREAD

**Issue by dr47** [filebrowser/filebrowser#1343]
**Description**
Files containing the characters: (),;  (parentheses, comma, semicolon ) and maybe others cannot be played (if mp3) or edited (if txt).  Clicking on a file containing malicious characters will cause an error: **This location cannot be reached.**

**Expected behaviour**
Play or edit a file. 

**What is happening instead?**
Error page with description:  This location cannot be reached. 

**How to reproduce?**
Create an audio file named:   **a(b).mp3** and a text file named: **a,b.txt** and click on them.

**Comment by alexisLefebvre** [comment]
See #1332

**Comment by o1egl** [comment]
fixed in https://github.com/filebrowser/filebrowser/pull/1339
