### ISSUE TITLE
GET api/resources/ loaded from disk cache

### ISSUE THREAD

**Issue by c42759** [filebrowser/filebrowser#1344]
**Description**
I'm trying to upload file or multiple files, but after the upload, the list remains the same. I checked the filesystem and the file is uploaded successfully.

**Expected behavior**
After the upload with success, I expected to see the uploaded file in the list of folders/files

**What is happening instead?**
There is no error whatsoever.

**Additional context**
With the developer tools of chrome, I checked the GET api/resources/ request after the 1st one, it has been loaded from the disk cache. If I tick the option "disable cache" while maintaining the developer tools open, the resource is now being loaded correctly from the server.

![Screenshot_20210318_220441](https://user-images.githubusercontent.com/11203357/111704253-be76cb80-8836-11eb-80a4-9b7eed6b2bd2.png)

**How to reproduce?**
This was just a new installation using the docker image from the dockerhub (latest), and is behind a reverse proxy nginx.

**Files**
N/A

**Comment by ramiresviana** [comment]
Filebrowser does not implement cache policy, making every request hit the server. Your issue is related to the use of nginx, which can manipulate the headers of the server response.

**Comment by c42759** [comment]
@ramiresviana after your message I've started searching by cache disabling for NGINX. I will leave the configurations here, maybe someone can have the same problem as me.

```
location / {
		# kill cache
	        add_header Last-Modified $date_gmt;
	        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
	        if_modified_since off;
	        expires off;
	        etag off;		
	}

```
