### ISSUE TITLE
Feature request: large file multi-part upload

### ISSUE THREAD

**Issue by xlight** [filebrowser/filebrowser#1345]
**Is your feature request related to a problem? Please describe.**
when I upload a very large file (10G+), there is many problem like nginx upload size limit , network not stable ,etc.

**Describe the solution you'd like**
implement a muli-part upload like S3.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html

**Comment by o1egl** [comment]
duplicate of https://github.com/filebrowser/filebrowser/discussions/1182
