### ISSUE TITLE
trying to delete a file leads to 404 error

### ISSUE THREAD

**Issue by pgrayatmac** [filebrowser/filebrowser#1346]
**Description**
I am trying to delete files from a remote seedbed using file browser.  I selected the document and it was outlined in blue then pressed the trash can icon.  SW asked if I wanted to delete, I clicked delete.  I got a 404 page not found error

**Expected behaviour**
file deleted

**What is happening instead?**
red box indicating 404 page not found with report issue and close buttons

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by luoyangchun** [comment]
#1312 I had the same problem, and rolling back to v2.11 worked fine.

**Comment by o1egl** [comment]
Try to upgrade to the latest version
