### ISSUE TITLE
[Frontend] Top header not visible in Safari

### ISSUE THREAD

**Issue by agneevX** [filebrowser/filebrowser#1349]
**Description**
The top banner is not visible when a text file, for e.g., is opened, but I can click the close button to close it.

**Expected behaviour**
Visible top banner. 

**What is happening instead?**

<img width="513" alt="image" src="https://user-images.githubusercontent.com/19761269/111949912-89ed6300-8b07-11eb-92dd-7d1abbe1474f.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/19761269/111950061-c6b95a00-8b07-11eb-939d-b24b5d61087d.png">

**Additional context**
N/A

**How to reproduce?**
Open any text file. 

**Files**
N/A

**Comment by o1egl** [comment]
Which filebrowser/web browser versions you use? Can't reproduce it on the latest versions of chrome/safari/firefox

**Comment by agneevX** [comment]
I'm using Filebrowser 2.14.1 and Safari 13.1.3 on Catalina.
