### ISSUE TITLE
Failure on (large) file upload

### ISSUE THREAD

**Issue by kn0wmad** [filebrowser/filebrowser#1351]
**Description**
Attempting to upload a video file of significant size, ~1.8GB

**Expected behaviour**
File to upload (a long wait was expected)

**What is happening instead?**
After approximately 10min, "Something really went wrong" and [object Object] is given in the red error box

**Additional context**
The file came from a mobile device (android) via USB

**How to reproduce?**
Attempt to upload a large file from mobile device via USB

**Comment by ramiresviana** [comment]
Please provide the output of console tab on web developer tools and server logs at the moment that the problem happens.

**Comment by kn0wmad** [comment]
Trying to reproduce and the upload has taken over 5hours (same file), but seems to be progressing.  I'm going to have to disconnect unfortunately (no logs or console output have been produced yet).  I guess close this and if I encounter it again I'll let you know.

**Comment by o1egl** [comment]
You probably had some network issue. At the moment, we don't support chunked/resumable uploads. But this is something we are thinking about https://github.com/filebrowser/filebrowser/discussions/1182
