### ISSUE TITLE
get.sh not found

### ISSUE THREAD

**Issue by medlaam** [filebrowser/filebrowser#1352]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?
install the app
**Expected behaviour**
What did you expect to happen?
clean install
**What is happening instead?**
Please, give full error messages and/or log.
curl: (22) The requested URL returned error: 404
**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by ramiresviana** [comment]
@o1egl installation scripts are not available at https://filebrowser.org/get.ps1 and https://filebrowser.org/get.sh

**Comment by cloudsw** [comment]
> @o1egl installation scripts are not available at https://filebrowser.org/get.ps1 and https://filebrowser.org/get.sh

I also encountered the same problem:
"curl: (22) The requested URL returned error: 404 "

**Comment by vijuchac** [comment]
get.sh and get.ps1 are in a different git repository 
https://raw.githubusercontent.com/filebrowser/get/master/get.sh

**Comment by o1egl** [comment]
This is a Cloudflare issue. The redirect rule doesn't work. I will try to fix it with the support team.

**Comment by o1egl** [comment]
Updated the docs to point to GitHub directly.

**Comment by CouldBeThis** [comment]
Hi, sorry to say I don't think it is fixed.

Code from [Install](https://filebrowser.org/installation) > Unix generates an error:

```sh
curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
Downloading File Browser for linux/armv7...
curl: (6) Could not resolve host: api.github.com
https://github.com/filebrowser/filebrowser/releases/download//linux-armv7-filebrowser.tar.gz
curl: (22) The requested URL returned error: 404
Aborted, error 22 in command: ${net_getter} "$filemanager_url" > "$PREFIX/tmp/$filemanager_file"
```

**Comment by o1egl** [comment]
`curl: (6) Could not resolve host: api.github.com`
@CouldBeThis, you have DNS issues on your machine. It is not related to the installing script.

**Comment by alexisLefebvre** [comment]
The file https://raw.githubusercontent.com/filebrowser/get/master/get.sh is accessible but not the second file in the output https://github.com/filebrowser/filebrowser/releases/download//linux-armv7-filebrowser.tar.gz, it returns a code 404.
