### ISSUE TITLE
Question: How can I change storage path?

### ISSUE THREAD

**Issue by tauchvogel** [filebrowser/filebrowser#1362]
I have a NAS with Openmediavault 5. I installed File Browser via Portainer. 

How can I change the used Disks to save the files? I have two hard drives in Raid 1 on my NAS. 

Please help.

**Comment by ramiresviana** [comment]
The concept of disks is not present in Filebrowser, its purpose is to handle paths from the OS filesystem. You can set the root path by using the `--root` parameter.

**Comment by tauchvogel** [comment]
If it supports the operating system path, why don't I see the shared folders in Filebrowser?

**Comment by o1egl** [comment]
The scope of the filebrowser is limited to the root folder set by the `--root` param.

**Comment by tauchvogel** [comment]
Where can I find more information about it?

**Comment by ramiresviana** [comment]
The documentation is available at https://filebrowser.org/

**Comment by tauchvogel** [comment]
In the Dokumentation I saw this entry:
`docker run \
    -v /path/to/root:/srv \
    -v /path/filebrowser.db:/database.db \
    -v /path/.filebrowser.json:/.filebrowser.json \
    --user $(id -u):$(id -g)
    -p 80:80 \
    filebrowser/filebrowser`

Can I change "-v /path/to/root:/srv\" to several entrys/folders, to be the storage path(s)?

**Comment by ramiresviana** [comment]
The -v param is used by docker to bind volumes. You can check its capabilities on the docker documentation.

**Comment by alexisLefebvre** [comment]
> Can I change "-v /path/to/root:/srv" to several entrys/folders, to be the storage path(s)?

You should be able mount several volumes, and you'll have to specify different folders under `/srv/` to avoid conflicts:

```
-v /path/to/root:/srv/root -v /path/to/images:/srv/images
```

**Comment by o1egl** [comment]
I think we can close this issue
