### ISSUE TITLE
Shared file QR Code url problem.

### ISSUE THREAD

**Issue by tbelbek** [filebrowser/filebrowser#1370]
**Description**
Shared file QR Code url problem.

**Expected behaviour**
The url should be maindomain.com/api/public/dl/{shortcode}

**What is happening instead?**
When I scan the qr on the share screen, the url is only /api/public/dl/{shortcode} without main domain.

**How to reproduce?**
You can share a file, then go to download file page and scan the QR Code. I can provide a sample file.

**Comment by ramiresviana** [comment]
This issue was already solved on version v2.14.0, please update your Filebrowser version.

**Comment by tbelbek** [comment]
Thank you, I updated and the qr is working good now.
