### ISSUE TITLE
It is recommended to add a file transfer list

### ISSUE THREAD

**Issue by xc1984759471** [filebrowser/filebrowser#1371]
When uploading files, most online disks can display detailed upload information (including file information being uploaded, upload speed, remaining time, etc.), while filebrowser only displays a progress bar on the top when uploading files, so that I simply  It’s impossible to know when the upload is complete, and it’s also difficult to manage the file upload. For example, when I don’t want to upload a file, I want to cancel it, or I want to suspend uploading at any time in the middle, etc., so it’s best to add a transfer list to facilitate  Better management.

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/issues/1380
