### ISSUE TITLE
permanent link gone ?

### ISSUE THREAD

**Issue by mountaser** [filebrowser/filebrowser#1375]
where did the permanent link option go? am using filebrowser on unraid and its reverce proxied with swag any idea why its not showing the permanent link option??

![image](https://user-images.githubusercontent.com/17933154/115123847-cd56b800-9f73-11eb-92a1-eb0141329dec.png)

**Comment by ramiresviana** [comment]
A permanent share is created when the share duration field is empty.

**Comment by mountaser** [comment]
> 
> 
> A permanent share is created when the share duration field is empty.

thanks! there used to be a button for that thats why am asking.. but yah now i can create perm links again so thanks
