### ISSUE TITLE
Downloading single files from shared folder

### ISSUE THREAD

**Issue by pagdot** [filebrowser/filebrowser#1378]
**Is your feature request related to a problem? Please describe.**

When sharing a folder, you are unable to download only a single file or a selection of files.
You can only download the whole folder as a zip archive.

**Describe the solution you'd like**

Allow to select one or multiple files for download. Similar to normal view

**Describe alternatives you've considered**

Just allow downloading single files, no selection for multiple files.

**Comment by ramiresviana** [comment]
This feature is already present in the current version of Filebrowser, the share view has buttons on the header that allows to select and download files. You can select files by clicking or entering selection mode with the header button. When one or multiple files are selected, the download button is displayed, allowing to download a single file or a archive containing the selected files.

**Comment by pagdot** [comment]
Thanks, sorry 🙈 Didn't update my installation. Can confirm that it works
