### ISSUE TITLE
Download / Upload Progress Bar with percentage completed

### ISSUE THREAD

**Issue by dualznz** [filebrowser/filebrowser#1380]
**Is your feature request related to a problem? Please describe.**
There is no way of knowing how far the download / upload progress is going 

**Describe the solution you'd like**
Some sort of progress bar maybe in a model that shows  on bottom right hand corner

**Comment by ramiresviana** [comment]
Filebrowser has a progress bar for uploads that is displayed on top of the screen when uploading files. Downloads are handled by the browser, you can check the download progress on the downloads section of the browser you're using.

**Comment by Frank4411** [comment]
> 
> 
> Filebrowser has a progress bar for uploads that is displayed on top of the screen when uploading files. Downloads are handled by the browser, you can check the download progress on the downloads section of the browser you're using.

@dualznz 
Here is an example of what you might see when uploading a file(see link below). I do think that it wouldn't hurt to make the bar a bit taller, maybe double the size? The first time I was uploading a file it took me a minute to figure out where the progress bar was.

[https://i.imgur.com/aQXuHel.png](https://i.imgur.com/aQXuHel.png)

**Comment by o1egl** [comment]
I think better would be to create a small window which displays current queue. Something like that
<img width="399" alt="Screenshot 2021-04-23 at 13 54 57" src="https://user-images.githubusercontent.com/966539/115867550-8832fa00-a43b-11eb-9462-19801470ceb9.png">

**Comment by dualznz** [comment]
yea something like that would make it more streamlined

**Comment by sintaxx** [comment]
How do I enable the percentage indicator? are there plans to show the transfer rate as well ?

**Comment by ramiresviana** [comment]
This feature was introduced on Filebrowser v2.21.0.

**Comment by sintaxx** [comment]
> This feature was introduced on Filebrowser v2.21.0.

oh ok i guess i'll mess around with it some more but I just deployed this in a container v2.21.1 and saw no transfer speed or percentage indicator just a progress bar

**Comment by Pendrag00n** [comment]
> This feature was introduced on Filebrowser v2.21.0.

A progress bar was introduced, but not actual transfer rate information. This would be pretty useful

**Comment by zeezhao** [comment]
Please could you confirm if transfer rate addition is in the works? Thanks
