### ISSUE TITLE
Cant get a correct file name when downloading file

### ISSUE THREAD

**Issue by SCGabriel** [filebrowser/filebrowser#1381]
[Description]
In version 2.12.0,when I generate a share link, I will get a download link like this
"https://xxx.com/api/public/dl/-PxXWQT5/download/frp_0.35.1_linux_amd64.tar.gz"
use wget curl tools can download this link and get correct file name "frp_0.35.1_linux_amd64.tar.gz"

But in version 2.15.0,when I generate a share link, I will get a download link like this
"https://xxx.com/api/public/dl/onfCabRQ"
when using wget or curl, it will download file and get a wrong name “onfCabRQ”,not the correct name "frp_0.35.1_linux_amd64.tar.gz"

I know wget and curl can manually assign file name, but it's very inconvenient

In some worse cases, when I click download link in some mobile phone apps,it will download files with wrong names,and it won't give me chance to assign file name before download.

I guess these changes is going to cover the file path and makes it more safe.
But I hope you can add file name in the end of the urls,to make these urls become direct file links.

**Comment by ramiresviana** [comment]
Have you found a solution for this issue?
