### ISSUE TITLE
User actions log information

### ISSUE THREAD

**Issue by cdx7779** [filebrowser/filebrowser#1383]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hello, can you increase the record information of the user's operation? Security, Section Traceability Boss

**Comment by mckaygerhard** [comment]
related or duplicate of #1560  .. meanwhile for now we attend the command runners ! check https://filebrowser.org/configuration/command-runner (documentation is being updating)
