### ISSUE TITLE
Config files should be placed in a /config folder and not stored at the root (docker)

### ISSUE THREAD

**Issue by sbaydush** [filebrowser/filebrowser#1390]
By storing the config files/database files at the root directory in docker, it stops people from using docker volumes forcing them to use bind mount points. Personally this is stopping me from being able to run this on a docker swarm with distributed persistent storage. If there was a way to set the mount point to something like this:  filebrowser_data:/config that would fix the problem instead of pointing directly to the config file itself.

**Comment by pcmv-dev** [comment]
I agree this should be changed asap

**Comment by o1egl** [comment]
You can set custom config and database paths by using `-c /path/to/config  -d /path/to/db`

**Comment by sbaydush** [comment]
it needs to be to the folder, not to the actual file for this idea to function. Currently that custom config path has to point directly to the file, not the location the file is in.

**Comment by o1egl** [comment]
What is the problem with setting the config path?

**Comment by sbaydush** [comment]
by using config path pointing directly to the config and database files, you can no longer use portainer volumes nor the automatic distributed storage backend I have been using. To use that, you point directly to the volume not to a specific path inside a volume.
https://storidge.com/

The current way works great for users who have one docker machine or using nfs shares but not for anyone else.

**Comment by sbaydush** [comment]
![image](https://user-images.githubusercontent.com/14132229/117655733-75bbfe80-b165-11eb-892e-3e0a4aaf984b.png)

This is how i would like to set it to function if possible.

**Comment by sbaydush** [comment]
maybe I am misunderstanding something. Is there an environment variable i can pass in that will tell it to point to /config/.filebrowser.json for its config and /config/filebrowser.db for its database? I don't see that in the documentation.

**Comment by sbaydush** [comment]
and i just realized i can just shove that into the command field and magically i can map to the /config folder and everything works. Sorry about that. I'll close this
