### ISSUE TITLE
File not editing or replacing through File Manager

### ISSUE THREAD

**Issue by ahsanshakeel** [filebrowser/filebrowser#1393]
**Description**
I am trying to replace the file with another file but I get error on replacing as well as on removing the file

**Expected behaviour**
File should be overwritten with a new one or removed if deleted.

**What is happening instead?**
I am getting 403 Error

**Files**
File Location is app/design/frontend/Mgs/gemmart/Magento_Checkout/web/template/minicart/content.html

**Comment by ramiresviana** [comment]
Please check the Filebrowser configuration and file permissions, is possible that your user dont have the required privileges to modify the file.
