### ISSUE TITLE
Rice.Go error when trying to setup local environment for development

### ISSUE THREAD

**Issue by alex3025** [filebrowser/filebrowser#1394]
Hello, I want to customize the frontend (not only css) so I followed the contributing guide in the docs
but when I run `rice embed-go` (in the `http` directory) I get this error:
```
$ rice embed-go
2021/05/06 09:42:06 no calls to rice.FindBox() found
```

**Comment by ramiresviana** [comment]
The contributing guide is outdated, currently Filebrowser does not make use of go.rice, it will automatically embed the assets using embed.FS. For development you can use the dev coinstrant by adding `-tags dev` to the build command, making the application use the frontent directory, which is useful for viewing changes made to the frontend.

**Comment by alex3025** [comment]
Ok, so I started the .exe file generated from the dev build and ran `npm run watch` but I can't access to the app in any way.

**Comment by Tk369** [comment]
I also have the same problem. May I ask if I can update the tutorial on the https://filebrowser.org/contributing

**Comment by Ap0lloTea** [comment]
> The contributing guide is outdated, currently Filebrowser does not make use of go.rice, it will automatically embed the assets using embed.FS. For development you can use the dev coinstrant by adding `-tags dev` to the build command, making the application use the frontent directory, which is useful for viewing changes made to the frontend.

I also have the same problem. Could you please update the tutorial on the https://filebrowser.org/contributing

**Comment by ramiresviana** [comment]
You can contribute to the documentation at https://github.com/filebrowser/docs

**Comment by Ap0lloTea** [comment]
I haven't build and run success too : (  . Where is the command " -tags dev " added,I tried it many times but It still didn't work out,Can you give me the build command like "go build xxx?" or something else,I am a beginner in the Go language.thinks XD

**Comment by ramiresviana** [comment]
Use `npm run watch` for the frontend and `go run -tags dev main.go` for the backend.

**Comment by Ap0lloTea** [comment]
I tried the command, but it still didn't seem to work,I'll stick with the old version go.rice,My work is a little urgent at the moment,I can use the old version to solve my problems..XD

**Comment by o1egl** [comment]
I think that issue could be closed

**Comment by TCB13** [comment]
> Use `npm run watch` for the frontend and `go run -tags dev main.go` for the backend.

PR to clarify this waiting here: https://github.com/filebrowser/docs/pull/42
