### ISSUE TITLE
you can not login through the `admin` `admin`

### ISSUE THREAD

**Issue by gomin1d** [filebrowser/filebrowser#1396]
if you initialize the `filebrowser.db` database with the `filebrowser config init` command, then you will not be able to login with the `admin` `admin` password

step to reproduce:  
```shell
curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
rm filebrowser.db
filebrowser config init
filebrowser config set --address 0.0.0.0
filebrowser
```

**Comment by ramiresviana** [comment]
The init command will not create the default user, you can use the users command to create a new one.

**Comment by gomin1d** [comment]
> The init command will not create the default user, you can use the users command to create a new one.

it was not intuitive to me

i thought this command creates default config

if this is done intentionally, then it is not a bug
