### ISSUE TITLE
Only allow TLS 1.3 between web browser and Filebrowser

### ISSUE THREAD

**Issue by OoZe1911** [filebrowser/filebrowser#1405]
Problem :
I am using Filebrowser on a server in my company. The security team has found out that Filebrowser is allowing web client to get connected using TLS1, TLS 1.1, TLS1.2 (all ciphers), TLS1.3. This is a security issue.

Solution :
Please allow only this kind of connectivity between web client and Filebrowser :
- TLS 1.2 with the following ciphers only :
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS 1.3 all ciphers
(TLS 1.3 is recommended)

Alternative :
I am considering to use Caddy as a gateway to Filebrowser (but I have to check that Caddy can force TLS 1.3 as the preferred protocol).

Thanks for your help.

**Comment by oemsysadm** [comment]
I keep going back to nginx for this kind of thing, using the "proxy_pass" configuration option:

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

You can set up an encrypted reverse proxy, and control protocols and ciphers easily:

https://nginx.org/en/docs/http/configuring_https_servers.html

Just make sure you deal properly with DNS lookups, or the webserver won't start if it can't find the backend:

**(Just a word of caution. Don't implement the DNS lookup fix if you plan to use WebDAV over this connection. I've discovered some very alarming issues where folders become recursive, and if entered, might disappear from the filesystem completely. I plan to use traefik in my setup instead, however I don't know how easily it will allow you to configure your specific TLS wishes)**

https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/

Run everything in Docker, and things are even easier for you to manage and scale out in swarm mode:

https://phoenixnap.com/kb/docker-nginx-reverse-proxy

**Comment by OoZe1911** [comment]
Thank you for your explanation, I was also thinking about using Caddy :
https://caddyserver.com
because I am used to work with it.

Maybe in Filebrowser source code it is easy to change something to enforce TLS 1.3. I had a quick look but was not able to find where ;(

**Comment by ramiresviana** [comment]
https://github.com/filebrowser/filebrowser/blob/46ee59538914dc2859f0da6b32e2d062d0a01b10/cmd/root.go#L156-L163

This block of code handles tls, it is configured to use 1.2 as min version and default cipher suites. The default suites can be seen at https://golang.org/src/crypto/tls/cipher_suites.go?s=1340:1374#L40 and should be secure. Running nmap on a Filebrowser server, using the ssl-enum-ciphers script, returns only secure tls 1.2 ciphers.


Please provide information about how you are able to validate the support of tls 1.0 on Filebrowser.

**Comment by OoZe1911** [comment]
Thanks a lot Ramires !!
So this is straightforward to fix my issue ! I do not want to support TLS 1.0, I want to enforce TLS 1.3 only.
So line 160 should be :
`MinVersion:   tls.VersionTLS13`
and that's it !!

But wait... at the moment MinVersion is set to TLS1.2 ? But it is not working as Filebrowser is allowing connections with TLS 1 and TLS 1.1 according to the security team (red team) ?

**Comment by o1egl** [comment]
@OoZe1911 You probably have the old version of the app. Try to upgrade it.

**Comment by OoZe1911** [comment]
@o1egl Right !! I am using an old version !! Thanks for pointing this out !
