### ISSUE TITLE
Changing UMASK

### ISSUE THREAD

**Issue by gafka3** [filebrowser/filebrowser#1406]
**Is your feature request related to a problem? Please describe.**
I'm using the FileBrowser docker on unraid. I've used the flag --user 99:100 but since umask is 0022 instead of unraid's default 0000, any file/folder created using FileBrowser can only be written by user "nobody" (id:99). This means that when accessing my shares via SMB I cannot edit the files or directories created in FileBrowser.

**Describe the solution you'd like**
Some images have the variable -e UMASK= to set umask for created files.

**Describe alternatives you've considered**

**Additional context**

**Comment by telsch** [comment]
Because I run into the same situation. Just use the alpine based image like v2.22.1-s6 or s6 instead of the latest tag. But then don't forget to use also the PUID and PGUID environment variables instead of --user uid:gid.

**Comment by nathanrdodson** [comment]
Reopening this issue as a nice-to-have feature. Are there any plans to add this?

**Comment by ediazrod** [comment]
Will be great have any way to solve the umask issue.. as far I see the current mask is a issue and don't work on systemd.. as far the solution that i found is use smbclient as file server..

**Comment by domme1908** [comment]
Bump
