### ISSUE TITLE
Not bug, not

### ISSUE THREAD

**Issue by MahefaAbel** [filebrowser/filebrowser#1407]
**Is your feature request related to a problem? Please describe.**
I have a difficulty to start filebrowser. 
1. Installation success with describe in [https://filebrowser.org/installation](https://filebrowser.org/installation)
2. I run `filebrowser`
3. I obtain :
  > 2021/05/18 19:14:28 No config file used
  > 2021/05/18 19:14:28 Listening on 127.0.0.1:8081

But myIpAdress:8081 does not work.
After that, I think that I need to add config, but how? The doc does not explain this, at least, it is not clear.
I saw : https://filebrowser.org/cli/filebrowser-config or https://filebrowser.org/cli/filebrowser-config-set but these does'nt help me at all. 

I want add feature about documentation.

**Describe the solution you'd like**
My solution is simple, juste add an use example in the "docs". A docs is supposed to contains use example, not only "Synopsis" that does not give valuable help.

**Comment by o1egl** [comment]
As you can see the service started on 127.0.0.1, not your public IP address. You can change it by setting `--address 0.0.0.0`. For more information run `filebrowser -h`
