### ISSUE TITLE
Base is not set

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#141]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Built from Dockerfile today (downloaded from caddyserver.com in the build)
```dockerfile
FROM alpine:3.6

LABEL caddy_version="0.10.4" architecture="amd64"

ARG plugins=http.git,http.filemanager,http.upload

RUN apk add --no-cache openssh-client git tar curl
RUN curl --silent --show-error --fail --location \
  --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
  "https://caddyserver.com/download/linux/amd64?plugins=${plugins}" \
  | tar --no-same-owner -C /usr/bin/ -xz caddy \
  && chmod 0755 /usr/bin/caddy \
  && /usr/bin/caddy -version

VOLUME /root/.caddy

COPY Caddyfile /etc/Caddyfile

EXPOSE 80 443 2015

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]
```

### 2. What is your entire Caddyfile?
```text
https://MASK_MY_DOMAIN {
  log stdout

  basicauth MASK_MY_USERNAME MASK_MY_PASSWORD {
    /download
    /saved
  }

  proxy /wobserver/ws app:4000 {
    transparent
    websocket
  }

  proxy / app:4000 {
    except /saved /manage
    transparent
  }

  root /var/www

  browse /saved

  filemanager /manage /var/www/saved
  tls MASK_MY_EMAIL
}
```

### 3. What are you trying to do?
use filemanager

### 4. What did you expect to see?
everything works under `/manage`

### 5. What did you see instead (give full error messages and/or log)?
it doesn't
the html it returns starts with, where `base` is empty
```html
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,user-scalable=no"><meta name=base content=""><title>File Manager</title>
```

**Comment by princemaple** [comment]
Update: actually, it's more serious than that... it fails to match path. When I go to `/saved` it also gets hijacked by `filemanager`.

**Comment by hacdias** [comment]
Oops! I'm really sorry for this. I'll push a fix very soon and deploy it to the build server. When the working version is ready, I'll ping you.

**Comment by princemaple** [comment]
Thanks for the quick response!

**Comment by hacdias** [comment]
No problem! The plugin was already deployed. Please try again and check if it is working 😄

**Comment by princemaple** [comment]
Hi, it's working as expected now. I found something else, I'll open an new issue.

**Comment by hacdias** [comment]
Thank you 😄
