### ISSUE TITLE
Download multiple files without archiving?

### ISSUE THREAD

**Issue by johnnybrozzz** [filebrowser/filebrowser#1412]
**Is your feature request related to a problem? Please describe.**
Currently, when we select multiple files the download button only shows option to archive them (zip, tar etc.). We can not start downloading of all the selected files in normal way.

**Describe the solution you'd like**
It would be better to have an option where to just open all the download links in browser at once so that multiple downloads can start. The reason for such is that Archives are created on fly and in my server the download speed is slow compared to if I download files individually. Secondly many ISP's place speed limit on non mp4/video files, that's why when I zip my mp4 files the download speed is throttled by ISP.

Or if the browsers do not support opening huge number of download links at once, then perhaps we can simply copy all the download links to clipboard? So we can easily transfer them to our download managers.

**Comment by ttlttc** [comment]
yeah, it should be useful

and I have a question too, how to keep session never timeout? really don't want login again and again...

**Comment by traceback1** [comment]
I would love to see option to skip the archive on multi file download! Also, as an option, limit one link  per download if issue with multiple links, and queue the rest. This would be a big time saver, especially when  you need to dl only couple of files.
