### ISSUE TITLE
Help needed: Prevent Login from outside

### ISSUE THREAD

**Issue by praul** [filebrowser/filebrowser#1413]
Hi there.
Is there any possibility to prevent logins completely when filebrowser is accessed from the internet?

I'm using caddy reverse proxy. Blacklisting "/login*" does not work, and when whitelisting "/static* /share* /api* /messagebus*" login is still possible.

I would only like the /share URLs to be publicly accessable.
Any idea? Thank you :)

**Comment by o1egl** [comment]
You need to set auth method to noauth https://filebrowser.org/configuration/authentication-method#no-authentication

**Comment by praul** [comment]
Won't this disable auth alltogether and allows access to everyone?
I want the exact opposite: Prevent anyone from logging in :)
Only /share s should be accessible

**Comment by praul** [comment]
I have a solution. Since I'm using filebrowser docker (https://hub.docker.com/r/hurlenko/filebrowser) and caddy reverse proxy (https://github.com/lucaslorentz/caddy-docker-proxy) it works by blocking /api/login
`caddy: example.duckdns.org`
`caddy.@notblacklisted.not.path: "/api/login*"`
`caddy.reverse_proxy: "@notblacklisted {{upstreams 8080 http}}"`

With a port mapping on local network you will still be able to login, but remote access/login should not be possible.

Is this sufficient, blocking /api/login ?

**Comment by o1egl** [comment]
Yes it is
