### ISSUE TITLE
Are you thinking about release the version of mips/mipsel platform?

### ISSUE THREAD

**Issue by Hermit-Nameless** [filebrowser/filebrowser#1414]
The mips/mipsel platform widely used, are you thinking about release the version of mips/mipsel platform?

**Comment by tg567** [comment]
I compiled mips version of 2.16.0 filebrowser, but it didn't run as i expect. Got Segmentation fault on my router. If you want  to try, here's the file.
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/6890022/filebrowser.zip)
