### ISSUE TITLE
Show total folders size

### ISSUE THREAD

**Issue by pinpox** [filebrowser/filebrowser#1417]
**Is your feature request related to a problem? Please describe.**

I'd like to see the size of folders to find which ones are the taking up the most size.
Related to: https://github.com/filebrowser/filebrowser/issues/633

**Describe the solution you'd like**
Show the folder size instead of just `-`

**Describe alternatives you've considered**
Logging in as root on the server and checking manually.

**Additional context**
It would be very helpful to see folder sizes. Would it be possible to add those?

**Comment by o1egl** [comment]
To calculate the size of a folder, fb needs to recursively traverse the entire subdirectory tree, which is a very expensive operation. In the current implementation, this functionality cannot be implemented.

**Comment by YevheniiSemendiak** [comment]
@o1egl , your position is clear
But, what if the FileBrowser runs this calculation on users demand?
For instance, FileBrowser has `Info` button and window, showing the detailed info on file, like this:
![image](https://user-images.githubusercontent.com/32543098/126517344-382a2309-84ea-4b0b-8788-5d6b187b90c1.png)

What about adding a button there like "calculate folder size" there?

**Comment by Alfagun74** [comment]
Any plans to merge your changes? @derekshao1225

**Comment by Alfagun74** [comment]
This is not completed wtf

**Comment by awsms** [comment]
> This is not completed wtf

^ plz reopen

> What about adding a button there like "calculate folder size" there?

this.. there is a "generate checksums" function for individual files, but not one to calculate a total size?
