### ISSUE TITLE
Error trying to compile frontend

### ISSUE THREAD

**Issue by jdieguez89** [filebrowser/filebrowser#1419]
**Description**
Compile fronted

**Expected behavior**
Compile

**What is happening instead?**
![image](https://user-images.githubusercontent.com/26327410/120159054-76443400-c1fd-11eb-9cba-0d38026986b5.png)

**Additional context**
node v14.16.1
"vue": "^2.6.10",
Windows 10

**How to reproduce?**
Fork repository
cd frontend
npm run build

** How fixed ** 
Add in the documentation that the `find `command is not from windows

**Comment by shourysharma** [comment]
Use bash. Cause commands doesn't work in powershell.
