### ISSUE TITLE
404 when trying to change username

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#142]
Is user looked up by username? If so, changing username would probably never work, unless you send both the old name and the new name.

Changing password works.

**Comment by hacdias** [comment]
Sorry! I've already had that bug but I forgot that completely. I just launched a new version yesterday and it probably has got some bugs. Yes, we should be able to change the username. I'll fix that. BRB 😄

**Comment by hacdias** [comment]
Going to deploy to the Caddy server.

**Comment by hacdias** [comment]
I'll deploy this to the web server as soon as possible 😄 But it is already fixed.
