### ISSUE TITLE
option to cancel uploading file

### ISSUE THREAD

**Issue by Nicokalak** [filebrowser/filebrowser#1421]
**Is your feature request related to a problem? Please describe.**
when upload file there is no option to cacel the upload except closing the page
when logging out while upload file the upload is continue

**Describe the solution you'd like**
view for the uploaded file and their progress with option to cancel single file
make the upload chunked with Transfer-Encoding: chunked to prevent status 413 while uploading large files

**Comment by o1egl** [comment]
You can follow this discussion https://github.com/filebrowser/filebrowser/discussions/1182
