### ISSUE TITLE
No preview of files when public sharing

### ISSUE THREAD

**Issue by gafka3** [filebrowser/filebrowser#1422]
Files such as photos cannot be previewed (not even thumbnails) when accessing via a public link. Is this expected behavior? Is there any way to change it?

**Comment by MetallicAchu** [comment]
I'm interested in knowing as well.
Thank you

**Comment by ramiresviana** [comment]
This is not implemented in the current version of Filebrowser.

**Comment by gafka3** [comment]
> This is not implemented in the current version of Filebrowser.

Is there a reason why preview is restricted in public links? Just genuinely curious, thanks a lot!

**Comment by nic-hanna** [comment]
This is a feature I would also like, a much easier user experience. The interface for the private view is great.

**Comment by niubility000** [comment]
How about this one ?
#1735
