### ISSUE TITLE
Configuration file documentation

### ISSUE THREAD

**Issue by dchandekstark** [filebrowser/filebrowser#1424]
Hi,

Thanks for the great project!

One challenge I have faced is how to create a configuration file that has everything I want in it.  The documentation seems to assume that some things will be set interactively through the GUI or CLI -- and stored in the database?

An example is the `branding` settings.

Thanks!

**Comment by ramiresviana** [comment]
The configuration file support the parameters documented at https://filebrowser.org/cli/filebrowser#options.

**Comment by mckaygerhard** [comment]
i readed the documentation asn it seems some options are outdated or non property documented.. by example there's no examples of any running command .. 

to change branding we need some prerequisites that seems are IMPORTANT but MISSING as:

1. filebrowser must stop to run, if not the database lock get corrupted ( will open a issue to change to a RDBMS)
2. documentation only list description in vage way.. and for each we must added a "-" dash to work

**Comment by mckaygerhard** [comment]
ping , this still is valid i fixed the docukmentation and open a PR but all my PR are still not merged
