### ISSUE TITLE
docker drop upload file 409 error (only happens when I created a new user and login by new user)

### ISSUE THREAD

**Issue by conphi** [filebrowser/filebrowser#1425]
> docker pull filebrowser/filebrowser

> docker run -t -d --restart=always -v /root/ftp:/srv -v /root/filebrowser.db:/database.db -p 80:80 filebrowser/filebrowser

![409](https://user-images.githubusercontent.com/9531363/121114245-f7c34400-c845-11eb-8a31-864a09e3e014.PNG)

**Comment by ramiresviana** [comment]
Please provide the output of the Filebrowser console or logs when the problem happens.

**Comment by jopny** [comment]
save issue when upload many files.
