### ISSUE TITLE
setting --locale doesn't work from cli (filebrowser config set --locale)

### ISSUE THREAD

**Issue by azlk** [filebrowser/filebrowser#1430]
**Description**

Cannot change locale with `filebrowser config --locale ru` (or ru_RU.UTF-8, doesn't matter)

**Expected behaviour**

Web interface should change to localized names

**What is happening instead?**

All names are still in English, though filebrowser.yaml shows `locale: ru`

**Additional context**

But if I change language from Profile Settings it successfully changes to Russian!

`**How` to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
Using the command `filebrowser config set --locale` will change the locale value in Global Settings, which are the default values for new users. The command `filebrowser config set` does not make changes to existing users.

**Comment by azlk** [comment]
thank you, I didn't find this subtlety in the documents
