### ISSUE TITLE
No way to set shared folder

### ISSUE THREAD

**Issue by azlk** [filebrowser/filebrowser#1431]
**Description**

There is no way to define a shared folder in web interface. There is no such parameter with `filebrowser config set `also...
**Expected behaviour**

Create a shared folder
**What is happening instead?**

No shared folder...
![no_shared_folder](https://user-images.githubusercontent.com/4054635/121654372-54bd3500-caa6-11eb-9159-2ecfd1fc1ebf.png)

**Additional context**

I found a feature request for this from 2017, which was said had been added in 2019, but nothing changed actually.
[https://github.com/filebrowser/filebrowser/issues/192](url)
**How to reproduce?**

**Files**

**Comment by azlk** [comment]
At last found a way to make a share!... But I think it should be reflected in the documentation, as this is very unintuitive way and not described anywhere.

**Comment by azlk** [comment]
After seeing what it looks like, new questions arose: why does the link with share need the **Login** button? And can it be removed? It only takes up space on the screen, which is already small - the left half is all occupied by a not very necessary picture with the inscription "download this folder", a huge folder icon and a completely unnecessary QR code. Actually the user does not need this area outlined with a red rectangle, it only takes space.
![shared folder](https://user-images.githubusercontent.com/4054635/121670601-4a0a9c00-cab6-11eb-8284-03d28e5b1fed.png)

**Comment by ramiresviana** [comment]
Sharing a file/directory is done by clicking on the share icon on the header bar, the icon is displayed when a item is selected on the file listing. This is a community project, the share view is result of contributions of many people through the years. Feel free to open discussions about new features and contribute to the code.

**Comment by azlk** [comment]
I understand everything perfectly, no requirements, God forbid! I just asked if it could be removed and hoped you would advise how to do it
