### ISSUE TITLE
Application doesn't respect setting View mode to list

### ISSUE THREAD

**Issue by azlk** [filebrowser/filebrowser#1432]
**Description**

Web interface always in **viewMode mosaic** until one change it in web interface, then it remembers mode.

**Expected behaviour**

`filebrowser config set --viewMode list` should chage mode from "mosaic" to "list"

**What is happening instead?**

always mosaic, until change it from web interface

**Additional context**

After every changing I always export config file and check it's content, so the case is somewhere else...
Didn't want to open another issue, so writing it here: **same behaviour with Single click**, and I didn't check, **maybe other options** too
Also, pretty funny that changes made from web interface don't reflect in config file, so _you can't really tell what settings filebrowser has._

**How to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
The command `filebrowser config set` does not make changes to existing users.
