### ISSUE TITLE
Download/Upload files using cli

### ISSUE THREAD

**Issue by amir-latifi** [filebrowser/filebrowser#1433]
Hi,
Is it possible to download or upload a file using cli? If no, is there anyone who is implementing this feature?

**Comment by o1egl** [comment]
It is not possible to upload files using cli and we don't plan to add it any time soon. There are many existing cli tools that can do that.

**Comment by amir-latifi** [comment]
> It is not possible to upload files using cli and we don't plan to add it any time soon. There are many existing cli tools that can do that.

You mean there are cli tools which can be integrated with filebrowser? Could you please name some of them?

**Comment by o1egl** [comment]
No, I wanted to say that there are other tools that you can use. They are not integrated with filebrowser.
