### ISSUE TITLE
allow upload in share folder

### ISSUE THREAD

**Issue by Cyrix126** [filebrowser/filebrowser#1435]
Hello,

How hard would it be to allow uploading a file on a shared folder ? Without the need to be logged in I mean.
I guess it could be an option to add at the moment of the creation of the share.

**Comment by ramiresviana** [comment]
Shares are read-only, login can be disabled by using the noauth authentication method.

**Comment by g0rbe** [comment]
+1 for this feature.
I dont see why its a problem. With an optional "Allow upload" button, this function will be very useful.

**Comment by mrpip** [comment]
I would love to get this feature, as well. Currently I need to create a cumulative user and share its credentials in my travel group to collect photos. The possibility to create directories and upload via a shared link would solve this issue and replace Nextcloud entirely.

**Comment by zagi988** [comment]
Was thinking the same and looked up if someone already requested that. Allowing upload to shared folders is a great feature.

**Comment by r3nor** [comment]
Is this on the roadmap?

**Comment by zagi988** [comment]
It's not stale, just no one is replying.

**Comment by mrpip** [comment]
I really think this would be a great addition to Filebrowser.
Just to clarify, as there seems to be a misunderstanding: the request was not to disable logins. The request was meant to introduce a functionality that allows the creation of a link that can be shared with others and the recipient can only upload files to the directory that link was created for. There should not be a possibility for the recipient to delete files, just upload and download, no write access on already existing files.

Example:
Person A-Z go on vacation together. Person A has filebrowser set up. Person A creates a directory for pictures of that holiday (lets call that directory `Pictures of trip to place`), but does not want to create 25 accounts for Persons B-Z. Thus, Person A creates an upload link for said directory and distributes the link to the Persons B-Z (via some chat app, not part of filebrowser). Persons B-Z can follow the link, create a directory with their respective name (e.g. Person B creates a directory `Pictures of trip to place/Pictures taken by Person B`) and upload their images to their personal directory. After everyone has done so, everyone can download the entire collection using the same link.

Not being familiar with the inner workings of Filebrowser: could this be done using a temporary user in the backend?

As I am not familiar with Go, I sadly cannot help with implementation, but I am happy to discuss the design of this feature in further detail if necessary.

**Comment by dsfsdbvxc** [comment]
+1 for this!

Moving over to File Browser since File Run removed it’s free tier, this (and 2FA) are the only think missing for me.
