### ISSUE TITLE
Please, provide config file example

### ISSUE THREAD

**Issue by amg-web** [filebrowser/filebrowser#1438]
Please, provide config file example

**Comment by ramiresviana** [comment]
The config file is a file in the json, toml, yaml, or yml format, the supported options are listed at https://filebrowser.org/cli/filebrowser#options. This is the default config file for the docker images:

```json
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```

**Comment by patrickelectric** [comment]
It would be cool if config command could output the configuration in a desirable format

**Comment by patrickelectric** [comment]
Oh, there is `filebrowser config export`

**Comment by gerritgriebel** [comment]
`filebrowser config export` produces a file which does not work for me with -c option. For example I had to move`{ "server": { "port": "1532"}}` to up to  `{ "port": "1532"}` to make filebrowser listen to 1532. Also I was not able to avoid having to run filebrowser with `--auth.method=proxy --auth.header=X-HMT-User` options using json configuration file. On https://filebrowser.org/cli/filebrowser a hint to a description of the required format would be great.

**Comment by mckaygerhard** [comment]
> `filebrowser config export` produces a file which does not work for me with -c option. For example I had to move`{ "server": { "port": "1532"}}` to up to `{ "port": "1532"}` to make filebrowser listen to 1532

now i cheked file browser provides good export .. but still not good auth export.. 

a advertisement @gerritgriebel   the only sectin that can be imported alone customized are the "server" part, the "settings" part and "auth" part of the config file must be fill with all the key settings allowed.. by example if the key or the shell sub-keys missing.. import will not work

**Comment by ramiresviana** [comment]
`config export` generates a file that should be used with `config import`, the file structure is not compatible with the `-c` option.

**Comment by mckaygerhard** [comment]
> `config export` generates a file that should be used with `config import`, the file structure is not compatible with the `-c` option.

umm it makes sense.. so how i can made then a config file valid for me? please @ramiresviana  any hint?

**Comment by ramiresviana** [comment]
> > `config export` generates a file that should be used with `config import`, the file structure is not compatible with the `-c` option.
> 
> umm it makes sense.. so how i can made then a config file valid for me? please @ramiresviana any hint?

https://github.com/filebrowser/filebrowser/issues/1438#issuecomment-865046092

**Comment by mckaygerhard** [comment]
> > > `config export` generates a file that should be used with `config import`, the file structure is not compatible with the `-c` option.
> > umm it makes sense.. so how i can made then a config file valid for me? please @ramiresviana any hint?
> [#1438 (comment)](https://github.com/filebrowser/filebrowser/issues/1438#issuecomment-865046092)

that are the only parameters to be able to put in config file? i tried some more but generates a non descriptive error  as "`sintax error after `" or similar always (includin the space)

**Comment by mckaygerhard** [comment]
i have PR opened at filebrowser/docs#15 but still are not merged https://github.com/filebrowser/docs/pull/41
