### ISSUE TITLE
support for .opus?

### ISSUE THREAD

**Issue by Cathgao** [filebrowser/filebrowser#1439]
cannot play .opus as youtube audio files online. Or I just need to change .opus to .ogg?

**Comment by ramiresviana** [comment]
Filebrowser uses browser built-in player for previewing media files, the file format support depends on the browser you are using.

**Comment by Cathgao** [comment]
> Filebrowser uses browser built-in player for previewing media files, the file format support depends on the browser you are using.

I'm using chrome 91 can play .opus in no doubt. But in Filebrowser, it just shown as unknown file and can download only.
![QQ截图20210618193854](https://user-images.githubusercontent.com/21031564/122555645-24106900-d06d-11eb-9b4f-0d8864a2a71c.png)

![QQ截图20210618193923](https://user-images.githubusercontent.com/21031564/122555655-25da2c80-d06d-11eb-9035-ff0d0d5a522e.png)

**Comment by ramiresviana** [comment]
Looks like Filebrowser was unable to detect that file correctly, can you provide example files and information about how that file was created?

**Comment by Cathgao** [comment]
Running environment : 
```
Windows10 1809 LTSC 
Nginx 1.19.4
File Browser 2.9.0
```
Here is the example .opus file: (please decompress. Just for testing with no other use)
`Scatman (ski-ba-bop-ba-dop-bop) Official Video HD -Scatman John`
[example.zip](https://github.com/filebrowser/filebrowser/files/6690150/example.zip)

That is created by using https://github.com/ytdl-org/youtube-dl
`youtube-dl.exe -f bestaudio --write-thumbnail --cookies ./cookies.txt --embed-thumbnail -i -x https://www.youtube.com/watch?v=Hy8kmNEo1i8`

Also, I convert a MP3 file to OPUS using Foobar2000 has the same problem. Looks like Filebrowser unable to detect all opus files.

**Comment by ramiresviana** [comment]
Unfortunately i'm unable to reproduce the issue, even with old versions of Filebrowser. Can you provide a browser har file containing the requests when you try to preview the file? Keep in mind that har files contain sensitive data, if you dont want to share that information you can create a new instance of Filebrowser only for the purpose of testing. Also is recommended to use the latest version of the software, so you can have new features and bug fixes.

**Comment by Cathgao** [comment]
[har_file.zip](https://github.com/filebrowser/filebrowser/files/6694037/har_file.zip)
Is this the har you want? 
For my private reason, I don't using my domain but local IP this time. The Nginx will proxy to the same port in reality.
I wonder if Windows support what kind of media files will affects Filebrowser? Do I need to install the K-Lite code pack to make Windows support .opus? Or I have a wrong Nginx configuration?
I can provide more information whatever you want :)

**Comment by ramiresviana** [comment]
To make the preview work correctly, the OS need to have the mime information set correctly. For audio files, the mime must start with the `audio` keyword. On Windows, that information is stored in the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\`. For the `.opus` format, the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.opus\Content Type` value should be `audio/ogg`.

**Comment by Cathgao** [comment]
> To make the preview work correctly, the OS need to have the mime information set correctly. For audio files, the mime must start with the `audio` keyword. On Windows, that information is stored in the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\`. For the `.opus` format, the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.opus\Content Type` value should be `audio/ogg`.

Well... opus files was not registed in the server OS class. I will install an code pack to try make Windows associate opus with audio files.

**Comment by Cathgao** [comment]
After I installed code pack, .opus has been registed to OS class. But it has `PerceivedType` but no `Content Type`. Everything still the same. Should I add it manually?
![image](https://user-images.githubusercontent.com/21031564/122939236-0bbe8800-d3a6-11eb-9dab-2e16f16df2e0.png)

**Comment by Cathgao** [comment]
Finally! After adding the `Content Type` now it works well. Thanks a lot @ramiresviana ,you really helped me!
