### ISSUE TITLE
PDFs are opened as text files

### ISSUE THREAD

**Issue by marcocipriani01** [filebrowser/filebrowser#1442]
**Description**
When opening a PDF from File Browser, it sometimes opens as a text file in the editor. It happens around half of the times I try to open a PDF. If I download the PDF, it opens just fine in Adobe Acrobat, Chrome and Edge.

**Expected behaviour**
I should be able to see the PDF.

**What is happening instead?**
![image](https://user-images.githubusercontent.com/20319029/122681777-55687080-d1f6-11eb-9c68-4842810b8a2a.png)
 
Tested with lots of PDFs and two File Browser versions (a 1 year-old installation and the new v2.15.0). Same behavior on Chrome for Windows, Chrome for Android and Safari on iPhone.

**Comment by ramiresviana** [comment]
I'm unable to reproduce the issue, please provide example files and information about how that file was created.

**Comment by marcocipriani01** [comment]
I made more tests and I've discovered that all the PDFs that open in the text editor come from my HP Photosmart C4400 scanner. Here's an example scan: [scan_2021-06-21 13.38.42.pdf](https://github.com/filebrowser/filebrowser/files/6686310/scan_2021-06-21.13.38.42.pdf)

**Comment by ejrv** [comment]
I **dont** have this problem

**Comment by marcocipriani01** [comment]
Is there a way in which I can debug the problem?

**Comment by ramiresviana** [comment]
The provided file is being detected as a text file because the first part of it is non-binary. Fixing that requires to change the way how pdf files are detected.

**Comment by marcocipriani01** [comment]
How does the detection work now? Doesn't it check just the file extension?

**Comment by mckaygerhard** [comment]
i have same problem, confirmed.. so how can we disable preview of pdf or wich version does not have this problem?

**Comment by mckaygerhard** [comment]
> The provided file is being detected as a text file because the first part of it is non-binary. Fixing that requires to change the way how pdf files are detected.

but is a mayor problem .. the 98% of the files used in my hosting are scanned files

**Comment by mckaygerhard** [comment]
this problem is URGENT PLEASE asn is duplication of https://github.com/filebrowser/filebrowser/issues/1201 is an urgent problem.. at least tell us a way to disable preview and forced to download files @o1egl !!!

**Comment by mckaygerhard** [comment]
any news about this issue that is currently important?

**Comment by niubility000** [comment]
If you just wanna download it directly, it's easy. Just choose the file and download it. Don't click to open it.

**Comment by mckaygerhard** [comment]
> If you just wanna download it directly, it's easy. Just choose the file and download it. Don't click to open it.

its support to provide this as sevice for people that assumed that works as spected.. not to experts that thnks as you .. 

not all the users have the same conception of the things.. and we used filebrowser as sevice toprovide files ot others.. that just xpected a easy to use click to download thing..

**Comment by mckaygerhard** [comment]
almost 4 month was passed at least any way to disable preview for all files? puff please any response!

**Comment by mckaygerhard** [comment]
i just asked @o1egl  this commit try to avoid gif previews right? 453636dfe2bbf177c74617862eb763485d4774bf so we can made the same for pdf files as a first test and later then try to decide if we must load previews of pdf shit files?

**Comment by niubility000** [comment]
I think I have fixed it in my modified version, try this: https://gitee.com/niubilitypdj/filebrowser/releases/
If it works I can make a PR later.

**Comment by mckaygerhard** [comment]
hi @niubility000  i discovered gitee .. ok likely in fact but it seems the same as github.. nice try but i guess its better to you put a fork directly here event in the gitee cos i cannot track your changes  .. 

i mean :

1) there's only 64bit builds and all the download are zipped windo crap fiiels.. inclusivelly the repo itselft
2) event i track your commits and there's none related https://gitee.com/niubilitypdj/filebrowser/commits/master?user=76441520%2Bniubility000%40users.noreply.github.com
3) **are you trying to present to us your chinesse preferences? cos the code does not present many differences..** :smile: 

in fact your fork source code is exact same as here! only the binaries are different! so .. please show to us the changes .. not binaries!

**Comment by niubility000** [comment]
> hi @niubility000 i discovered gitee .. ok likely in fact but it seems the same as github.. nice try but i guess its better to you put a fork directly here event in the gitee cos i cannot track your changes ..
> 
> i mean :
> 
> 1. there's only 64bit builds and all the download are zipped windo crap fiiels.. inclusivelly the repo itselft
> 2. event i track your commits and there's none related https://gitee.com/niubilitypdj/filebrowser/commits/master?user=76441520%2Bniubility000%40users.noreply.github.com
> 3. **are you trying to present to us your chinesse preferences? cos the code does not present many differences..** 😄
> 
> in fact your fork source code is exact same as here! only the binaries are different! so .. please show to us the changes .. not binaries!

Sorry, I haven't noticed your reply until I checked my email. 
The change is pretty simple. just add some codes in /files/file.go

...
case strings.HasPrefix(mimetype, "image"):
		i.Type = "image"
		return nil
	**case strings.HasSuffix(mimetype, "pdf"):
		i.Type = "pdf"
		return nil**
	case (strings.HasPrefix(mimetype, "text") || !isBinary(buffer)) && i.Size <= 10*1024*1024: // 10 MB
		i.Type = "text"
...

It will check if the file is a pdf file before check if it is a text file. Then all the pdf files will not be opened as text files.

I will test it again on my computer and make a PR this coming Monday.
BTW, I use gitee because it's very hard to upload large files to github from my country.

**Comment by mckaygerhard** [comment]
> It will check if the file is a pdf file before check if it is a text file. Then all the pdf files will not be opened as text files.
> 
> I will test it again on my computer and make a PR this coming Monday. BTW, I use gitee because it's very hard to upload large files to github from my country.

holy heck you r a genious..  @niubility000  **How could this not occur to me! I already assumed that the detection of text never be sabe as pdf so assumed this was being done, elsewhere, when the type of extension was reviewed!** you are a genious! resolvered a very big problem.. so then i will wait for monday and later i will cited to author to take attention to this puff, it seems there's no delegatin of responsabilities here !

**Comment by niubility000** [comment]
done!
