### ISSUE TITLE
filebrowser editor vertical ruler

### ISSUE THREAD

**Issue by ElvisTan** [filebrowser/filebrowser#1443]
FileBrowser support editor vertical ruler?

**Comment by o1egl** [comment]
I'm not sure what you are talking about. Please provide more information.

**Comment by ElvisTan** [comment]
![1](https://user-images.githubusercontent.com/3827544/122897196-59be9600-d37c-11eb-9e73-27a1cdb462b9.png)

**Comment by o1egl** [comment]
Yes it does
