### ISSUE TITLE
Generating the JWT cookie from another web app behind the same proxy

### ISSUE THREAD

**Issue by max-l** [filebrowser/filebrowser#1448]
I indend to use Filebrowser with another Web App, both of them behind a same Nginx proxy, and this other app has it's own user authentication and identity management. 

An (relatively) easy way to do this, would be to create the JWT cookie that is expected by Filebrowser.

I can live with the constraint that all of my users can share the same identity as far as Filebrowser is concerned, in other word.

In other words, FIlebrowser would have a single user, and any user logged in via my app, would have a the proper Filebrowser JWT cookie on all the requests produced by my App, while logged in. 

The filebrowser, and my own app, would of course use the same private key.

I need to know the exact format of the Filbrowser auth cookie, the algo for the crypto signature, the encoding format, etc, 

I looked in that area of the code: https://github.com/filebrowser/filebrowser/tree/master/auth 

And it doesn't seem that this is where the cookie is being created, validated and formated 

Would appreciate some pointers

**Comment by ramiresviana** [comment]
The current version of Filebrowser does not make use of cookies. Controlling the authentication can be done using the proxy header authentication method, more information at https://filebrowser.org/configuration/authentication-method#proxy-header.

**Comment by max-l** [comment]
Hmm, the problem is that it is far from pleasant to code authentication logic in Nginx (the proxy I'm using).

I've done it before using https://openresty.org/ and although it sucks less (you get to code in lua instead of C), it introduces complexity for not much gain. 

I see in the code here: https://github.com/filebrowser/filebrowser/blob/master/frontend/src/main.js

that the filebrowser app first makes a call to /api/login : 

```
export async function login(username, password, recaptcha) {
  const data = { username, password, recaptcha };

  const res = await fetch(`${baseURL}/api/login`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });

  const body = await res.text();

  if (res.status === 200) {
    parseToken(body);
  } else {
    throw new Error(body);
  }
}
```

Given that I intend to put both filebrowser and my Python app server behind the same Nginx proxy, I could route the /api/login call to my python server (insetead of filebrowser), and I would only need to validate that the user is indeed logged in (i.e. by validating my app's session cookie, which I'm already doing), and then format a properly formated JWT signed with the same private key as the one used by filebrowser.

Would that work ? 

I only need to know what is the proper format and crypto signature used for your JWT token (I assume it is signed cryptographicaly), but strangely I'm not finding where that happens in your go code, i thought it would be around here: 
https://github.com/filebrowser/filebrowser/blob/46ee59538914dc2859f0da6b32e2d062d0a01b10/auth/json.go#L29

Where should I look to learn about the format and crypto algo used for the JWT token ?

**Comment by ramiresviana** [comment]
The code used for token generation is located here: https://github.com/filebrowser/filebrowser/blob/73ccbe912fc1848957d8b2f6bbe5243804769d85/http/auth.go#L171

**Comment by max-l** [comment]
Thanks ! 

I see that you are using this library, and an Sha256: https://pkg.go.dev/github.com/dgrijalva/jwt-go#example-NewWithClaims-CustomClaimsType

It turns out I can produce the exact same signature and format with this library: https://github.com/mpdavis/python-jose

Now the only problem that remains, is to set the filebrowser signing key, so I can use the same on the Python side.

I looked in this part of the doc:  https://filebrowser.org/cli/filebrowser-config-set

And the closest thing I found related to a signing key was this command:

  `filebrowser config set --key=<the secret key> `

but it doesn't appear to be the JSW token signing key.

I suppose the key is somewhere in the database, is there a way to set it ? 

I suppose it's in the binary ./filebrowser.db file somewhere, it seems from looking at the code that it gets generated when the db is initalized. 

If it's not possible to set the key, is there any chance you could provide me with a few lines of Go code, to read the settings from the database and dump/print the key in hex or base64, or even raw byte array ? 




If not, I guess I could always

**Comment by ramiresviana** [comment]
The security key is available on the file generated by the `config export` command. Using `config import` allows you to import a config file. Filebrowser uses of BoltDB, the code is available at https://github.com/etcd-io/bbolt.

**Comment by max-l** [comment]
Thanks, it works like a charm ! 

I noticed that the jwt was set in localStorage, so it was actualy simpler, i.e. no need to configure Nginx route to intercept the login call, given that I have a JavaScript front end,  all I have to do is to fetch the token:

        fetch("/api/filebrowserToken").then(res => res.json()).then(res => {
            localStorage.setItem('jwt', res.token)
        })

And the user will be logged in.

The Python code to generate the token is trivial with this library: https://github.com/mpdavis/python-jose: 


```
    from jose import jwt

    @flask_app.route("/api/filebrowserToken", methods=['GET'])
    def filebrowser_tok():

        def now_millis():
            epoch = datetime.datetime.utcfromtimestamp(0)
            delta = datetime.datetime.utcnow() - epoch
            return int(delta.total_seconds())
      
        now = now_millis()

        token = {
            'user': {
                'id': 1, 'locale': 'en', 'viewMode': 'list', 'singleClick': False,
                'perm': {
                    'admin': False, 'execute': True, 'create': True, 'rename': True,
                    'modify': True, 'delete': True, 'share': True, 'download': True
                },
                'commands': [], 'lockPassword': False, 'hideDotfiles': True},
            'exp': now + 7200,
            'iat': now,
            'iss': 'File Browser'
        }

        token_headers = {'alg': 'HS256', 'typ': 'JWT'}

        signing_key = base64.b64decode(ibio_flask_app.config["FILEBROWSER_JWT_SIGNING_KEY"])

        signed_and_encoded_token = jwt.encode(
            token,
            signing_key,
            headers=token_headers,
            algorithm='HS256'
        )

        return jsonify({"token": signed_and_encoded_token})

```

**Comment by max-l** [comment]
Also, I noticed that you parse the signing key as if it was straight base64, but I'm pretty sure it's url_safe base64.

I'm not sure if it changes anything, since the key is random data anyways, but perhaps there's a subtle consequence that I'm not imagining.

So in my code I do the same: 

      base64.b64decode(ibio_flask_app.config["FILEBROWSER_JWT_SIGNING_KEY"])

But I we should really be calling this: 

```
def base64_url_decode(inp):
    padding_factor = (4 - len(inp) % 4) % 4
    inp += "="*padding_factor
    return base64.b64decode(inp.translate(dict(zip(map(ord, u'-_'), u'+/'))))


```

I saw a function that appears to be doing this here: https://github.com/dgrijalva/jwt-go/blob/v3.2.0/token.go#L101

**Comment by o1egl** [comment]
I think we can close this issue
