### ISSUE TITLE
[Feature Request] delete user

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#145]

**Comment by hacdias** [comment]
I've done the back-end for this, but didn't create a button on the front-end 😂 I'll try to do this today.

**Comment by princemaple** [comment]
It's exciting having created a popular project, don't burn yourself out though! :wink:

**Comment by hacdias** [comment]
Thanks for the advice! 😄

**Comment by hacdias** [comment]
@princemaple already available to download with this feature.

**Comment by princemaple** [comment]
@hacdias nice!

The feature works.
**question**: does it allow deleting the last user? I'm little afraid to test that (too lazy to reset)
**bug**: click delete, click cancel, it shows user updated dialog

![screenshot](https://user-images.githubusercontent.com/1329716/28411558-6b73b7ca-6d84-11e7-8ae5-e914b77c76e6.gif)

**Comment by hacdias** [comment]
Yes, you can delete a user even if it is the last one (you just need to reload Caddy to create the admin again).

I just pushed a new version to the server. Could you check if the bug is solved, please? 😄

**Comment by princemaple** [comment]
@hacdias it seems that it's still there...

**Comment by hacdias** [comment]
Which browser are you using? I don't have this bug

**Comment by princemaple** [comment]
Firefox. Indeed doesn't happen on Chrome. However, the bug is caused by the "delete prompt" modal being inside the user form, and the `cancel` button is lacking a `type="button"` attribute. The behavior on Firefox is correct. According to standard, buttons without a type attribute defaults to `submit`. And the cancel button being inside the form and having default `submit` effect cause the form to be submitted, hence the bug.

**Comment by hacdias** [comment]
Hello Po Chen! It does have the type='button' as you can see here:
https://github.com/hacdias/filemanager/blob/master/assets/src/components/User.vue#L62

I'd suggest you to try to clean the cache since it might be caching the old
JavaScript file.

When I get to the computer, I'll try on Firefox though.

**Comment by princemaple** [comment]
I meant this cancel button https://github.com/hacdias/filemanager/blob/master/assets/src/components/User.vue#L57

**Comment by hacdias** [comment]
Oh, sorry. Gonna change that 😅

**Comment by hacdias** [comment]
The best to do is to put the delete prompt outside of the form.

**Comment by princemaple** [comment]
Yep, that's why I left the comment instead of sending a PR. I don't know much about Vue. So you could choose to add the attribute or move the dialog.

**Comment by hacdias** [comment]
I'll release it on Caddyserver.com and I'll ping you then.

**Comment by hacdias** [comment]
Done @princemaple 😄

**Comment by princemaple** [comment]
Yeah confirm fixed
