### ISSUE TITLE
How secure is this software in HTTPS mode? Can it be used to store confidential files?

### ISSUE THREAD

**Issue by xnxnsu** [filebrowser/filebrowser#1451]

**Comment by ramiresviana** [comment]
HTTPS is an standard protocol, it will work in the same way as any application by adding a security layer to HTTP. Enabling it wont make the application invulnerable, but rather increase confidence. If you're willing to store critical data on any type of software, you must take measures to protect it, keeping in mind that all software is prone to failure.

**Comment by xnxnsu** [comment]
> HTTPS is an standard protocol, it will work in the same way as any application by adding a security layer to HTTP. Enabling it wont make the application invulnerable, but rather increase confidence. If you're willing to store critical data on any type of software, you must take measures to protect it, keeping in mind that all software is prone to failure.

Thank you for your answer
