### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by Ricoamal** [filebrowser/filebrowser#1453]
**Description**
Uploading odoo modules via FTP

**Expected behaviour**
to upload the .zip

**What is happening instead?**
am error occurs

**Additional context**

**How to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
Filebrowser does not have any implementation of the FTP protocol or odoo modules. Can you provide more information about how your issue is related to Filebrowser?
