### ISSUE TITLE
About the style of modify time

### ISSUE THREAD

**Issue by as564335sa** [filebrowser/filebrowser#1454]
Hi,
    I've just discovered this project, and it's amazing. Thank you, the author；
    There's a problem. Can the modification time of the file be changed to a specific time instead of how long it is now？
![QQ图片20210701133352](https://user-images.githubusercontent.com/35949162/124072241-18f90800-da73-11eb-949a-b451b3a4cb66.png)

**Comment by ramiresviana** [comment]
#1270
