### ISSUE TITLE
How to get in touch about a security issue?

### ISSUE THREAD

**Issue by zidingz** [filebrowser/filebrowser#1455]
Hey there,

As there isn't a `SECURITY.md` with an email on your repository, I am unsure how to contact you regarding a potential security issue.

Would you kindly add a `SECURITY.md` file with an e-mail to your repository? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this as the best way to ensure security issues are responsibly disclosed, and it would massively help security researchers get in touch next time.

Thank you so much and I look forward to hearing from you!

**Comment by o1egl** [comment]
Hi @zidingz, thanks you for suggestion. I've created a [file](https://github.com/filebrowser/filebrowser/blob/master/SECURITY.md), so you can follow the instructions to report a security issue

**Comment by zidingz** [comment]
Thanks!

**Comment by am0o0** [comment]
Dear o1egl, Can you give me some feedbacks about the reports that I created on Huntr.dev platform please?
Best regards, Amammad.
