### ISSUE TITLE
Share button blocked by uBlock Origin 

### ISSUE THREAD

**Issue by JJGO** [filebrowser/filebrowser#1457]
**Description**

The Share button is blocked by a couple of popular filter lists available in adblockers such as uBlock Origin

**Expected behaviour**

I expected the share button to show up and it took me some time to figure out what was going on

**What is happening instead?**

Share button was present in the html but not visible since the adblocker was hiding it

**Additional context**

Here's the output of the uBlock origin [logger](https://github.com/gorhill/uBlock/wiki/The-logger) with the false positive.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/3844846/124362715-b33c8580-dc04-11eb-961d-c734c9ae32d2.png">

**How to reproduce?**

Visit a non whitelisted instance of filebrowser with either Fanboy's Social or Fanboy's Annoyances lists [link](https://fanboy.co.nz/index.html)

**Comment by o1egl** [comment]
I don't think we can fix it somehow. In general, it makes no sense to fight hundreds of ad blockers. The user is responsible for adding trusted resources to the whitelist.

**Comment by JJGO** [comment]
It could potentially be solved by using a different title attribute to the button object, specially since in the current UI, the title is not visible to the user. 

I agree on the adblocker part, I thought it was worth raising the issue in case future users run into the same problem.
