### ISSUE TITLE
Features for V1.0.0

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#146]
- [x] Open search with CTRL-F ba0b15e191ff8b411263b7a276f8f650c0a64e45
- [x] Search for file extension/type a3447bf2322a846740803e059559f5c1faf58b26
- [x] Next/Prev buttons on preview 4fa584cad9e009e6f3628bfc1ba29c2f91a39d1a
- [x] Copy files (button and CTLR-C + CTRL-V) 64e70e39dcf6759e04315bc97ec6a0fed927c737
- [x] CTRL-X + CTRL-V to Move 64e70e39dcf6759e04315bc97ec6a0fed927c737

**Comment by Florian95** [comment]
Hello,

Maybe a `Copy Folder` function ? Could be very convenient.

Regards,

**Comment by hacdias** [comment]
Hey @Florian95! Thanks for the suggestion! I'll add that to the list (with Ctrl+c and Ctrl+v included)!

**Comment by codingtony** [comment]
Adding Next/Previous using arrow keys when looking at pictures would be a great addition!

**Comment by hacdias** [comment]
@codingtony, for pictures only, or for any kind of file that opens in that preview window? What would be more useful?

**Comment by codingtony** [comment]
I guess any kind of files that allow previews. That would make sense.
