### ISSUE TITLE
Filebrowser access with HTTPS

### ISSUE THREAD

**Issue by rommadun** [filebrowser/filebrowser#1460]
Hello. I'm using a Raspberry Pi with Openmediavault. I want to access my Data on the go with Filebrowser. When i want to set up filebrowser the normal way, i cant access it. I managed to set it up with "Portainer" and "Docker". But its only accessable with http, but in want to access it with https. I tried everything, but i am to dumb...
Is there a step by step, what i have to do?

**Comment by ramiresviana** [comment]
Enabling HTTPS is done by using `-key` and `-cert` parameters, you have to provide the path to the corresponding files. On Docker you can set that options by using environment variables, more information at https://filebrowser.org/cli/filebrowser

**Comment by rommadun** [comment]
@ramiresviana , i have read this, and also managed to create the cert and the key on my rpi.
But how do i say the docker container to use this? 
When i open up portainer and go to my filebrowser container. There is the possibility for the console, but when i enter something it says "filebrowser: not found"
Same when i open ob the WebUi from filebrowser and open the console there...

**Comment by ramiresviana** [comment]
You can change FileBrowser options on the Docker image by using environment variables or arguments:

Environment variables can be set by using `--env`  parameter on the `docker run` command.

```
docker run --env FB_CERT=/path/to/my.cert FB_KEY=/path/to/my.key filebrowser/filebrowser
```
Arguments are appended to the image entrypoint.
```
docker run filebrowser/filebrowser --cert /path/to/my.cert --key /path/to/my.key
```

**Comment by rommadun** [comment]
@ramiresviana ![image](https://user-images.githubusercontent.com/59207007/124794981-e1e19580-df4f-11eb-8bd2-65d9b51e5735.jpeg)
Something still have to be wrong. The container won't start anymore ...

Edit: Watched the log files and it says:
"open /home/pi/Documents/SSL_cert/selfsigned.crt: no such file or directory"... but there is one... 
Is it possible i made a wrong cert?...
I made them on the rpi with this command "sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /path/to/key -out /path/to/crt"

**Comment by ramiresviana** [comment]
The container do not have access to the host filesystem, you may want to use a bind mount to make the files acessible. Take a look at https://docs.docker.com/storage/

**Comment by rommadun** [comment]
@ramiresviana  ![image](https://user-images.githubusercontent.com/59207007/124809317-47d61900-df60-11eb-8fc0-b9fc62d68ea4.jpeg)
As you can see, both volumes are bind to the host system. And i also moved the data volume directly to the path, where the .crt is... still the same log 😔

**Comment by ramiresviana** [comment]
You are mounting the  `/home/pi/Documents/SSL_cert` host directory into the `/data` container directory, the path used to access the files is going to be `/data/selfsigned.crt` and `/data/html-key.key`. If you are not familiar with docker you can play with linux image such as Alpine or Ubuntu,.

**Comment by rommadun** [comment]
@ramiresviana 
Now it works! Thank you for your great help! As i mentioned in the first post, i am to dumb :D
It even works now when calling up my dyndns... 

I'm going to make a step by step on how to set up filebrowser on the rpi with Openmediavault and write it as a new issue. Would that be ok?

**Comment by o1egl** [comment]
It would be better to make a PR to the [docs](https://github.com/filebrowser/docs) repo
