### ISSUE TITLE
Do not reload the file list when close a file

### ISSUE THREAD

**Issue by as564335sa** [filebrowser/filebrowser#1461]
Hi,
    Can change an open file to a pop-up window? Because when close a file, the entire file list is reloaded. If there are a lot of files, it will be very time-consuming. Most importantly, reloading the file list will lose the current browsing location, which is a bad experience.

**Comment by niubility000** [comment]
support!

**Comment by snailwei** [comment]
I want this feature badly too, dose this duplicate https://github.com/filebrowser/filebrowser/issues/1833?

I am seeking a handy web file manager, I found the KodBox just works
https://github.com/kalcaddle/kodbox

File --> Network(admin) --> Select your directory

**Comment by wangxian** [comment]
+1

When there are many pictures, the experience is really not very good, and I hope to improve.

**Comment by 2pha** [comment]
+1, it drives me nuts
