### ISSUE TITLE
[BUG] Empty disk folder = Vue.js crash

### ISSUE THREAD

**Issue by LeXaMeN** [filebrowser/filebrowser#1463]
**Description**
If there are no files - the folder is empty, then vue.js crashes.

**Expected behaviour**
No crash.

**What is happening instead?**
![изображение](https://user-images.githubusercontent.com/31878437/124964984-4f61f480-e02a-11eb-8c1c-f6950f3df1d1.png)

**Additional context**
Due to an error, for example, "dragging and dropping a file to upload" does not work.

**Comment by ramiresviana** [comment]
This is already fixed and will be available on the next version release.
