### ISSUE TITLE
Any tips on setting up sync?

### ISSUE THREAD

**Issue by pinpox** [filebrowser/filebrowser#1465]
**Is your feature request related to a problem? Please describe.**
I'd like to use filebrowser as a minimal dropbox replacement.

**Describe the solution you'd like**
A simple way to sync files from the server to my PC

**Describe alternatives you've considered**
Mounting the server's folder using `sshfs`

**Additional context**
I didn't find anything regarding this in the documentation. While it might not be in the scope of the project itself, did anyone come up with a clever solution on how to mount or sync files on other machines? The WebUI provided by filebrowser itself is great, but It would be nice for some use-cases to be able to mount the served folder on other machines. I tried using sshfs, but couldn't get it to work. Also this requires a SSH key that has access to all filebrowser users. 

Does anyone have a solution/suggestion on how to mount my filebrowser's user-folder on a linux system? Would be nice to have some common uses cases like this in the docs

**Comment by o1egl** [comment]
File synchronization is out of the scope of this project. There are a few mature projects on the github that you can try. For example https://github.com/syncthing/syncthing

**Comment by pinpox** [comment]
Thanks for the link. I know about syncthing, but that won't play well with filebrowser's users and permissions. Would be nice to allow each user to mount or sync the data they can access via the webUI directly. I know it's not scope of the project, but thought anyone might have a working setup to share.

**Comment by decaby7e** [comment]
I personally have been using Syncthing + Filebrowser for at least 2 years now and it's basically been flawless. Permission issues can be resolved by running the Syncthing service as another user e.g. with a systemd user unit or with the syncthing@<username>.service template. As for the Filebrowser side I've been running separate instances of Filebrowser but I could get how that could not work. There could be ways to work around that though.

**Comment by josephine-munich** [comment]
> I personally have been using Syncthing + Filebrowser for at least 2 years now and it's basically been flawless. Permission issues can be resolved by running the Syncthing service as another user e.g. with a systemd user unit or with the syncthing@.service template. As for the Filebrowser side I've been running separate instances of Filebrowser but I could get how that could not work. There could be ways to work around that though.

@decaby7e can you explain how you set this up? I'd like to achieve this functionality but have no idea how to.

**Comment by decaby7e** [comment]
@jevans10 refer to these docs (https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-system-service) and let me know if you have questions.
