### ISSUE TITLE
open index.html: file does not exist

### ISSUE THREAD

**Issue by cnwelling** [filebrowser/filebrowser#1467]
**Description**
1.  run filebrowser
2.  open browser report error: "500 Internal Server Error"
3. tail -f /var/log/filebrowser.log  
      2021/07/11 20:54:20 /: 500 192.168.193.1 open index.html: file does not exist
      2021/07/11 20:54:20 /favicon.ico: 500 192.168.193.1 open index.html: file does not exist 
4.  filebrowser config cat
      Sign up:          false
      Create User Dir:  false
      Auth method:      json
      Shell:
      
      Branding:
        Name:
        Files override:
        Disable external links:  false
      
      Server:
        Log:           /var/log/filebrowser.log
        Port:          8088
        Base URL:
        Root:          /data
        Socket:
        Address:       0.0.0.0
        TLS Cert:
        TLS Key:
        Exec Enabled:  false
      
      Defaults:
        Scope:         .
        Locale:        zh-cn
        View mode:     list
        Single Click:  false
        Commands:
        Sorting:
          By:   name
          Asc:  false
        Permissions:
          Admin:     false
          Execute:   true
          Create:    true
          Rename:    true
          Modify:    true
          Delete:    true
          Share:     true
          Download:  true
      
      Auther configuration (raw):
      
      {
        "recaptcha": null
      }

Why and How config？

**Comment by o1egl** [comment]
Which version of the app are you using?

**Comment by cnwelling** [comment]
laster version  run on centos 7

**Comment by o1egl** [comment]
Please provide the CLI command that you use to run the app

**Comment by cnwelling** [comment]
[root@www filebrowser-master]# ls
auth          commitlint.config.js  fb.json         fileutils  http     Makefile   scripts      share
bin           diskcache             filebrowser     frontend   img      README.md  search       storage
CHANGELOG.md  Dockerfile            filebrowser.db  go.mod     LICENSE  rules      SECURITY.md  users
cmd           errors                files           go.sum     main.go  runner     settings     version
[root@www filebrowser-master]# ./filebrowser
2021/07/14 10:34:32 No config file used
^C[root@www filebrowser-master]# tail /var/log/filebrowser.log
2021/07/14 10:32:49 Caught signal interrupt: shutting down.
2021/07/14 10:32:49 accept tcp4 0.0.0.0:8088: use of closed network connection
2021/07/14 10:34:01 Listening on 0.0.0.0:8088
2021/07/14 10:34:16 /: 500 192.168.193.1 open index.html: file does not exist
2021/07/14 10:34:16 /favicon.ico: 500 192.168.193.1 open index.html: file does not exist
2021/07/14 10:34:23 Caught signal interrupt: shutting down.
2021/07/14 10:34:23 accept tcp4 0.0.0.0:8088: use of closed network connection
2021/07/14 10:34:32 Listening on 0.0.0.0:8088
2021/07/14 10:38:35 Caught signal interrupt: shutting down.
2021/07/14 10:38:35 accept tcp4 0.0.0.0:8088: use of closed network connection
[root@www filebrowser-master]#

**Comment by ramiresviana** [comment]
That error means that the frontend entrypoint 'index.html' file is not available. Building FileBrowser from source requires  you to generate the required files by building the frontend. If you are whiling to just run FileBrowser, you can download compiled builds on the releases page.

**Comment by cnwelling** [comment]
Thanks. 
How to generate an executable file based on the source code and what are the specific steps?

**Comment by ramiresviana** [comment]
The `make` command is used to build the application. Running `make build` should generate the compiled build, `nodejs` and `golang` must be installed.
