### ISSUE TITLE
Enable Sponsorship

### ISSUE THREAD

**Issue by dsikes** [filebrowser/filebrowser#1468]
I really love this project. You guys have done an amazing job with it. I would like to sponsor the project, but didn't see any way to do that. Is that something that you plan to add? If so, please let me know once you do and I'll gladly sponsor this project. Keep up the great work guys!

**Comment by thoernle** [comment]
We would also very much like to support the project

**Comment by JaegerMa** [comment]
+1

**Comment by agung2001** [comment]
yup really wanted to sponsor this project, hope they open either GitHub sponsor or Open Collective account.
