### ISSUE TITLE
Crashes when uploading large .tif files

### ISSUE THREAD

**Issue by GMV-ROA** [filebrowser/filebrowser#1470]
**Description**
I am trying to store .tiff images. These are large geotif files sometimes 100s of Mb so I am not expecting thumbnails for them. they are essentially elevation data in tiff format

**Expected behaviour**
Upload tiff files to a folder

**What is happening instead?**
Filebrowser crashes
2021/07/12 11:48:05 /thumb/ORTHO/Flight7-05-05-2021.psx.tif: 0 185.55.63.52 unexpected EOF: unsupported image format
2021/07/12 11:48:06 /thumb/ORTHO/Flight1086-17-05-2021.psx.tif: 0 185.55.63.52 unexpected EOF: unsupported image format
2021/07/12 11:48:06 /thumb/ORTHO/Flight465-14-05-2021.psx.tif: 0 185.55.63.52 unexpected EOF: unsupported image format

**Additional context**
Want to store some drone data.

**How to reproduce?**
Upload .tif file that is more than 100Mb

**Suggested solution**
Configuration option to disable thumbnails. Or even better for specific extensions

**Comment by o1egl** [comment]
Thank you for reporting this issue. As a workaround you can use `--disable-thumbnails` cli param to disable thumbnails creating
