### ISSUE TITLE
Is there a way to compile this project in Windows platform? or only in Linux platform.

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1474]
Before, I could compile the project on my Windows PC. and I wrote a doc about how to do it. It's very easy. 
[Cross compile filebrowser under windows pc.docx](https://github.com/filebrowser/filebrowser/files/6834683/Cross.compile.filebrowser.under.windows.pc.docx)

But now, the new version use makefile to compile it. As I know, it only can be run in Linux platform. Is there a way to compile the new version in windows platform? What should I install?  

Or should we update this page: https://filebrowser.org/contributing. It's out of date obviously.

**Comment by ramiresviana** [comment]
Using the `make` command is optional , you can use the same steps as before for building for windows, ignoring `rice embed-go` which is no more required.

**Comment by niubility000** [comment]
> Using the `make` command is optional , you can use the same steps as before for building for windows, ignoring `rice embed-go` which is no more required.

Thank you. I will try it.

**Comment by niubility000** [comment]
> Using the `make` command is optional , you can use the same steps as before for building for windows, ignoring `rice embed-go` which is no more required.

When I use  the command "npm run build" it always says 
> filebrowser-frontend@2.0.0 build
> find ./dist -maxdepth 1 -mindepth 1 ! -name '.gitignore' -exec rm -r {} + && vue-cli-service build --no-clean
FIND:  Parameter format not correct" 

It's weird.
I can compile it successfully in this way using the source code before 2.14.0.

**Comment by o1egl** [comment]
You can try to use WSL or docker to build the app

**Comment by niubility000** [comment]
> You can try to use WSL or docker to build the app

Thank you. Finally, I figured it out. 
The source code is not suitable to be compiled on Windows platform, or Linux arm64 platform. 

So I installed a docker in my windows pc. and run a ubuntu system in the docker. it works pretty good. 

Using this command to share the windows pc folder c:\dshare with the ubuntu:
docker run -t -i --name="fb"  -v /run/desktop/mnt/host/c/dshare:/dshare ubuntu:xenial-20210804 /bin/bash

**Comment by ilusoiluso** [comment]
modify "frontend\package.json"  
replace "find"  to "GIT-PATH\usr\bin\find.exe" or busybox
make install

**Comment by niubility000** [comment]
> modify "frontend\package.json" replace "find" to "GIT-PATH\usr\bin\find.exe" or busybox make install

Thank you!!!

**Comment by niubility000** [comment]
I figured it out finally.:)
1. We need use the nodejs v16, we can't use v17 or v18.
2. in package.json, we need change:     
    "build": "find ./dist -maxdepth 1 -mindepth 1 ! -name '.gitignore' -exec rm -r {} + && vue-cli-service build --no-clean",
    "watch": "find ./dist -maxdepth 1 -mindepth 1 ! -name '.gitignore' -exec rm -r {} + && vue-cli-service build --watch --no-clean"
to: 

"build": "c:/git/usr/bin/find.exe ./dist -maxdepth 1 -mindepth 1 ! -name '.gitignore' -exec rm -r {} + && vue-cli-service build --no-clean",

    "watch": "c:/git/usr/bin/find.exe ./dist -maxdepth 1 -mindepth 1 ! -name '.gitignore' -exec rm -r {} + && vue-cli-service build --watch --no-clean"

"c:/git/" is the directory where your git installed.

3. we need rewrite the whole content in the vue.config.js as:
module.exports = {
  runtimeCompiler: true,
  publicPath: '[{[ .StaticURL ]}]',
  parallel: 2,
  css: {
    extract: false
  }
}
