### ISSUE TITLE
Cannot download a directory with large number of files 

### ISSUE THREAD

**Issue by amir-latifi** [filebrowser/filebrowser#1475]
**Description**
I tried to Download a directory including 400k files with a total size of 100GB in both types of .zip and .tar.

**What is happening instead?**
Instead of downloading a zip file of size 100GB, download finishes successfully after downloading just 3MB.

Has anyone seen such a problem?

**Comment by o1egl** [comment]
Please share your server/client logs

**Comment by amir-latifi** [comment]
```
2021/07/20 09:44:17 http: superfluous response.WriteHeader call from github.com/filebrowser/filebrowser/v2/http.handle.func1 (data.go:67)
2021/07/20 09:44:17 /dir1/dir2/dir3/dir4/2021-07-19-18-30-00/: 500 95.217.239.71 stat /data/dir1/dir2/dir3/dir4/2021-07-19-18-30-00/data/git-data/repositories/@hashed/00/32/00328ce57bbc14b33bd6695bc8eb32cdf2fb5f3a7d89ec14a42825e15d39df60.git/hooks: no such file or directory
```
When i go to hooks directory using UI, this message appears "This location can't be reached.".

And the output of `ls -la` for hooks is: 
```lrwxrwxrwx    1 998      998             47 Jul 28  2019 hooks -> /opt/gitlab/embedded/service/gitlab-shell/hooks```


note: /data is the root i'v given to filebrowser with this command: /filebrowser -r /data

UPDATE: After testing, it seems filebrowser does not support files of type "link".

**Comment by amir-latifi** [comment]
@o1egl

**Comment by bbkgh** [comment]
Hi. We have same problem. Filebrowser download folder as zip doesn't works properly when there are symlinks in folders.
We can help in fixing this problem if you guide us and give us some clues in code. thanks

**Comment by o1egl** [comment]
Filebrowser can resolve symlinks unless it has proper rights. Can't reproduce the issue

**Comment by o1egl** [comment]
There are a few fixes done in the latest version which should fix your issue
