### ISSUE TITLE
filebrowser config set --auth.method=proxy --auth.header=X-My-Header

### ISSUE THREAD

**Issue by wdx13666** [filebrowser/filebrowser#1476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

这个具体如何使用，我想用一个vue服务，通过接口访问登陆后跳转到主页面
**Describe alternatives you've considered**

**Additional context**

**Comment by o1egl** [comment]
Describe it in English, please

**Comment by mckaygerhard** [comment]
basically @wdx13666  wants a working easy to understand example, not only a technical pure one

**Comment by mckaygerhard** [comment]
ping @github-actions this is a valid issue
