### ISSUE TITLE
Redirect login to external service

### ISSUE THREAD

**Issue by stashymane** [filebrowser/filebrowser#1484]
Currently, no matter what auth method is used, the login link redirects to filebrowser's own login, which is, at least from what I can see, no-op with proxy auth.
It would be great if proxy auth also allowed the login link to redirect to the service used for authentication.

**Comment by stashymane** [comment]
Please reconsider using stalebot, feature requests don't get implemented accidentally.

**Comment by stashymane** [comment]
Still not implemented. And stalebot is still awful.

**Comment by stashymane** [comment]
Not stale. A feature request cannot become stale.

**Comment by pseudocoder** [comment]
I think this misunderstands the point of proxy auth - if you're using a proxy for authentication, it's supposed to do everything so FB never even sees an unauthenticated user. That all works fine - if you're successfully setting the user header in the proxy and have FB configured to use it.

On the other hand that blocks using sharing links, so supporting OAUTH properly would be nice.

**Comment by stashymane** [comment]
Keeping public sharig is the whole point :)
Oauth is probably going to be a much larger undertaking than just a quick redirect though

**Comment by pseudocoder** [comment]
It can work, only a limited number of paths need to bypass the proxy check:

I use vouch-proxy in nginx to check/enforce OAUTH, and the config below works for me to allow sharing. My filebrowser runs on port 500 in a docker on the same machine as the proxy, with the path /browse/ and expects the header X-Vouch-User to include the username.

```
    location /browse/ {
        auth_request /vouch/validate;
        auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
        error_page 401 = @error401;

        proxy_pass http://127.0.0.1:500/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
        client_max_body_size 20m;
    }

    location ~* /browse/(api\/public|share|static)(.*) {
        proxy_pass http://127.0.0.1:500;
        proxy_set_header Host $http_host;
        proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
        client_max_body_size 20m;
    }
```
