### ISSUE TITLE
docker Health Check false positive on https port 443

### ISSUE THREAD

**Issue by albert-simohartono** [filebrowser/filebrowser#1487]
**Description**

When using docker on https port 443, the container will be shown as unhealthy, because the HEALTHCHECK only use http.

**Expected behaviour**

The HEALTHCHECK should try both http and https.

**Comment by o1egl** [comment]
You must define a custom health check if you make any changes to existing config

**Comment by hepto** [comment]
You can override the HEALTHCHECK configured in the image via the `run` command: 

https://docs.docker.com/engine/reference/run/#healthcheck

Specifically you can override the `CMD` to your needs, such as follows when it is running on a different port.  Presumably you can just update to HTTPS, but I have not tested.

`--health-cmd "curl -f http://localhost:8080/health || exit 1"`
