### ISSUE TITLE
2.16 no longer follows symlink

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#1488]
**Description**
Opening a symlink to a folder no longer works

**Expected behaviour**
in 2.15 it works

**What is happening instead?**
```
500 read /path/to/target/location is a directory
```

**Additional context**
N/A

**How to reproduce?**
```
ln -s some_where some_link
```

try and open `some_link`

**Files**
N/A

**Comment by princemaple** [comment]
Thanks!

**Comment by Andoramb** [comment]
Hi!
I'm on 2.16.1 (docker) symlinks are still considered a file
![image](https://user-images.githubusercontent.com/3399628/128517435-8cac429b-8e8c-4429-bfc3-d0b785cd1bfc.png)

**Comment by ramiresviana** [comment]
> Hi!
> I'm on 2.16.1 (docker) symlinks are still considered a file
> ![image](https://user-images.githubusercontent.com/3399628/128517435-8cac429b-8e8c-4429-bfc3-d0b785cd1bfc.png)

Are you able to access the link using a shell? Invalid links will be shown as a file on FileBrowser.

**Comment by Andoramb** [comment]
Hi @ramiresviana 
You're right, I also cannot open symlinks (running filebrowser in docker). However symlinks are ok on the host. Has it something to do with permissions? UID/GID?
Thanks :)

**Comment by Andoramb** [comment]
Attaching the same folders in docker-compose works without problem.
As for the symlinks:   _ls -al_ shows the original path for the folders, which is inaccessible of course from within the container.

EDIT: another strange behavior: in docker compose: by adding
`- "${MEDIA}/DATA2:/srv/media"`
to the volume, the app creates empty folders on the host at "/srv/_**media**_"

**Comment by Nepherim** [comment]
Looks like this is still an issue. Path is navigable from the OS, but the link shows as a file in FB. Happy to help with log info, etc.

**Comment by ParronS3** [comment]
Hello, sorry for the refloating.I was having the same error. 2 symlinks i had were working, but the new I was trying to make was not.
![imagen](https://github.com/filebrowser/filebrowser/assets/104781033/a8354df5-1d5d-40b5-982c-39e3c931aef7)

I had solved it. The difference was that the woking ones were pointing from a relative route, the one thas i was creating was from an absolute one
![imagen](https://github.com/filebrowser/filebrowser/assets/104781033/58ffaca4-e439-447f-9b1a-bb3487f8ddb3)

**Comment by scambier** [comment]
I'm having the same issue, but relative or absolute links don't seem to make a difference. I'm on 2.27.0.

If the symlink target is a folder that is already available from Filebrowser, it works. If the target is outside, the link is shown as incorrect. The folder's owner is the same in both cases, if that matters.

Edit: I guess it's due to Docker to having rights to "outside" folders?

Edit2: It works as expected when Filebrowser is not executed through Docker

**Comment by mattiaBox** [comment]
Same as @scambier here with version 2.31.2
I cannot add visibility to the symlink's destination because that's /srv and this would lead for sure to a conflict with the /srv used by filebrowser itself within the container.

Do you have some hint/suggestion?
