### ISSUE TITLE
How to alter admin user name and/or password during Docker install

### ISSUE THREAD

**Issue by mpkayeuk** [filebrowser/filebrowser#1489]
I want to change the default admin/admin username and password combo when bringing up file browser in Docker.  I've read some stuff that suggests this would be fixed in v. 2.0, but I can't see how to do it! 

Please can you provide some guidance on how to change the default admin/admin username and password combo when starting Filebrowser in Docker.

I am Terraforming an EKS cluster that relies on filebrowser as a component in a multi-tier application.  Filebrowser is also the only component exposed to the public internet (HTTPS/LoadBalancer Ingress). The whole EKS cluster is ephemeral, and doesn't last too long each time (maybe a couple of hours).  It's important that the username/password combo can be changed from the default so that it's more secure.

**Comment by ramiresviana** [comment]
The `username` and `password` options allows you to modify their respective properties for the first created user. Those options can be set using flags, environment variables and configuration files. The options documentation is available at https://filebrowser.org/cli/filebrowser
