### ISSUE TITLE
Cannot upload files into an Empty Directory

### ISSUE THREAD

**Issue by torch2424** [filebrowser/filebrowser#149]
Hello,

I noticed when you create a new directory, and try to upload files within it, you receive an error in the JS console. Thus, the upload popup never appears. See a screenshot below:

<img width="1280" alt="screen shot 2017-07-21 at 11 20 23 pm" src="https://user-images.githubusercontent.com/1448289/28488956-57c1a664-6e6b-11e7-996c-2d4587754bd9.png">

# Temporary Fix

Simply create a text file in your directory, upload the files, and then delete the text file 😄

**Comment by hacdias** [comment]
Hello @torch2424! Thanks for the report. I'll try to solve this ASAP.
