### ISSUE TITLE
Use win command "mklink /d[/j]  target dir source dir" to create a dir link，this dir link is judged as a file

### ISSUE THREAD

**Issue by ladixiu** [filebrowser/filebrowser#1490]
![image](https://user-images.githubusercontent.com/43605070/127731864-821c9e32-b59f-4fe9-addf-28415e4cfa09.png)

this is go io/fs problem

**Comment by ladixiu** [comment]
root path
scope  path
 not surport multi
when has multi dir in diffrent path
i use win mklink to relate diffrent path to on dir

**Comment by o1egl** [comment]
Duplicate of #1488
