### ISSUE TITLE
Video preview

### ISSUE THREAD

**Issue by Kareless** [filebrowser/filebrowser#1497]
播放不了1080p的视频 一直加载
![6BPY{6(UT%})XEYOXRIW5O7](https://user-images.githubusercontent.com/54282507/128127554-0004e98a-924f-4a55-9d36-302c3528c91d.png)

**Comment by bennyborn** [comment]
I've noticed this too since the last release.

**Comment by o1egl** [comment]
Describe the issue in English please

**Comment by Kareless** [comment]
I'm not good at English
what i mean is Video with 1080p bit rate cannot be played 
Been loading
Some of the videos I uploaded will change from mp4 format to normal file format and cannot be played.
Don't know you understand what i mean
![image](https://user-images.githubusercontent.com/54282507/128149625-e093942b-e8c2-4dac-8143-0dea3deec5ad.png)
this is mp4 file but it can t played

**Comment by o1egl** [comment]
Filebrowser uses the browser's capabilities to play a video file. Looks like your browser can't play this file

**Comment by Kareless** [comment]
I use google chrome

**Comment by niubility000** [comment]
> I use google chrome

Try qq browser. It has a enbedded video player.

**Comment by Kareless** [comment]
But not all people use QQ browsers. I hope people who use all browsers can watch videos online.

**Comment by ramiresviana** [comment]
@bennyborn can you provide more information about how the behavior of the preview was changed from version 2.15 to 2.16?

**Comment by BruceWind** [comment]
Hello!  @Kareless, Maybe your video **codec format** is not be supported by chrome. 
You can use an applicaton such as  `mediainfo` to read **codec format**  of the  video file.


In my test, result of a mp4 file:
```
$ mediainfo Big_Buck_Bunny_1080_10s_1MB.mp4 
General
Complete name                            : Big_Buck_Bunny_1080_10s_1MB.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 996 KiB
Duration                                 : 10 s 0 ms
Overall bit rate                         : 816 kb/s
Movie name                               : Big Buck Bunny, Sunflower version
Performer                                : Blender Foundation 2008, Janus Bager Kristensen 2013
Composer                                 : Sacha Goedegebure
Genre                                    : Animation
Writing application                      : Lavf57.63.100
Comment                                  : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 16 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 16 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 10 s 0 ms
Bit rate                                 : 828 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.013
Stream size                              : 992 KiB (100%)
Writing library                          : x264 core 148 r2744 b97ae06
Codec configuration box                  : avcC


```

You can look at ` AVC` in there. It is H.264 codec format.

**Comment by bennyborn** [comment]
@ramiresviana tbh I haven't paid much attention in the past but I know I was in fact able to start "streaming" multiple GB large videos right away. If I try to do so now it seems the video won't actually start until all of it has finished loading. 

If there was any change in the API regarding "streaming" since the last version I guess this would be a good starting place to look for.

**Comment by Kareless** [comment]
![image](https://user-images.githubusercontent.com/54282507/128186059-cbe3755c-ff15-4a72-ba45-d486187a9063.png)
My video format is like this

**Comment by Kareless** [comment]
<HTML><HEAD></HEAD>
<BODY>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY><TR>
<TD><I>Complete name :</I></TD>
<TD 
colSpan=3>I:\备份\锡兰youtube视频搬运\[BD影视分享bd-film.cc]黑洞频率.Frequency.2000.BD1080P.中英双字.mp4</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MPEG-4</TD></TR>
<TR>
<TD><I>Format profile :</I></TD>
<TD colSpan=3>Base Media</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>isom (isom/avc1)</TD></TR>
<TR>
<TD><I>File size :</I></TD>
<TD colSpan=3>1.79 GiB</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>1 时 58 分</TD></TR>
<TR>
<TD><I>Overall bit rate mode :</I></TD>
<TD colSpan=3>动态码率 (VBR)</TD></TR>
<TR>
<TD><I>Overall bit rate :</I></TD>
<TD colSpan=3>2 159 kb/s</TD></TR>
<TR>
<TD><I>Encoded date :</I></TD>
<TD colSpan=3>UTC 2020-11-22 02:39:49</TD></TR>
<TR>
<TD><I>Tagged date :</I></TD>
<TD colSpan=3>UTC 2020-11-22 02:39:49</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>视频</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>AVC</TD></TR>
<TR>
<TD><I>Format/Info :</I></TD>
<TD colSpan=3>Advanced Video Codec</TD></TR>
<TR>
<TD><I>Format profile :</I></TD>
<TD colSpan=3>High@L3.1</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>CABAC / 4 Ref Frames</TD></TR>
<TR>
<TD><I>Format settings, CABAC :</I></TD>
<TD colSpan=3>是</TD></TR>
<TR>
<TD><I>Format settings, Reference frames :</I></TD>
<TD colSpan=3>4 帧</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>avc1</TD></TR>
<TR>
<TD><I>Codec ID/Info :</I></TD>
<TD colSpan=3>Advanced Video Coding</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>1 时 58 分</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>2 000 kb/s</TD></TR>
<TR>
<TD><I>Maximum bit rate :</I></TD>
<TD colSpan=3>11.7 Mb/s</TD></TR>
<TR>
<TD><I>Width :</I></TD>
<TD colSpan=3>1 920 像素</TD></TR>
<TR>
<TD><I>Height :</I></TD>
<TD colSpan=3>1 080 像素</TD></TR>
<TR>
<TD><I>Display aspect ratio :</I></TD>
<TD colSpan=3>16:9</TD></TR>
<TR>
<TD><I>Frame rate mode :</I></TD>
<TD colSpan=3>恒定帧率 (CFR)</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>23.976 (24000/1001) FPS</TD></TR>
<TR>
<TD><I>Color space :</I></TD>
<TD colSpan=3>YUV</TD></TR>
<TR>
<TD><I>Chroma subsampling :</I></TD>
<TD colSpan=3>4:2:0</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>8 位</TD></TR>
<TR>
<TD><I>Scan type :</I></TD>
<TD colSpan=3>逐行扫描 (连续)</TD></TR>
<TR>
<TD><I>Bits/(Pixel*Frame) :</I></TD>
<TD colSpan=3>0.040</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>1.66 GiB (93%)</TD></TR>
<TR>
<TD><I>Writing library :</I></TD>
<TD colSpan=3>x264 core 157 r2969 d4099dd</TD></TR>
<TR>
<TD><I>Encoding settings :</I></TD>
<TD colSpan=3>cabac=1 / ref=2 / deblock=1:-2:-2 / analyse=0x3:0x113 / me=hex / 
subme=6 / psy=1 / psy_rd=1.00:0.25 / mixed_ref=1 / me_range=16 / chroma_me=1 / 
trellis=1 / 8x8dct=1 / cqm=0 / deadzone=6,6 / fast_pskip=1 / chroma_qp_offset=-4 
/ threads=34 / lookahead_threads=5 / sliced_threads=0 / nr=0 / decimate=0 / 
interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / 
b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / 
keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / 
rc=2pass / mbtree=1 / bitrate=2000 / ratetol=1.0 / qcomp=0.80 / qpmin=0 / 
qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=17500 / 
vbv_bufsize=17500 / nal_hrd=none / filler=0 / ip_ratio=1.10 / 
aq=1:0.50</TD></TR>
<TR>
<TD><I>Encoded date :</I></TD>
<TD colSpan=3>UTC 2020-11-22 02:39:49</TD></TR>
<TR>
<TD><I>Tagged date :</I></TD>
<TD colSpan=3>UTC 2020-11-22 02:40:14</TD></TR>
<TR>
<TD><I>编码配置区块 (box) :</I></TD>
<TD colSpan=3>avcC</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>音频</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>2</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>AAC LC</TD></TR>
<TR>
<TD><I>Format/Info :</I></TD>
<TD colSpan=3>Advanced Audio Codec Low Complexity</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>mp4a-40-2</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>1 时 58 分</TD></TR>
<TR>
<TD><I>Bit rate mode :</I></TD>
<TD colSpan=3>动态码率 (VBR)</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>156 kb/s</TD></TR>
<TR>
<TD><I>Maximum bit rate :</I></TD>
<TD colSpan=3>165 kb/s</TD></TR>
<TR>
<TD><I>Channel(s) :</I></TD>
<TD colSpan=3>2 声道</TD></TR>
<TR>
<TD><I>Channel layout :</I></TD>
<TD colSpan=3>L R</TD></TR>
<TR>
<TD><I>Sampling rate :</I></TD>
<TD colSpan=3>48.0 kHz</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>46.875 FPS (1024 SPF)</TD></TR>
<TR>
<TD><I>Compression mode :</I></TD>
<TD colSpan=3>有损</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>132 MiB (7%)</TD></TR>
<TR>
<TD><I>Encoded date :</I></TD>
<TD colSpan=3>UTC 2020-11-21 22:11:39</TD></TR>
<TR>
<TD><I>Tagged date :</I></TD>
<TD colSpan=3>UTC 2020-11-22 02:40:14</TD></TR></TBODY></TABLE><BR></BODY></HTML>

**Comment by o1egl** [comment]
That might be a meta information issue https://stackoverflow.com/questions/10328401/html5-how-to-stream-large-mp4-files

**Comment by Kareless** [comment]
Can this problem be solved? If the video preview problem can be solved, I think the file browser will be perfect

**Comment by BruceWind** [comment]
> Complete name :	I:\备份\锡兰youtube视频搬运\[BD影视分享bd-film.cc]黑洞频率.Frequency.2000.BD1080P.中英双字.mp4
> Format :	MPEG-4
> Format profile :	Base Media
> Codec ID :	isom (isom/avc1)
> File size :	1.79 GiB
> Duration :	1 时 58 分
> Overall bit rate mode :	动态码率 (VBR)
> Overall bit rate :	2 159 kb/s
> Encoded date :	UTC 2020-11-22 02:39:49
> Tagged date :	UTC 2020-11-22 02:39:49
> 
> ## 视频
> ID :	1
> Format :	AVC
> Format/Info :	Advanced Video Codec
> Format profile :	High@L3.1
> Format settings :	CABAC / 4 Ref Frames
> Format settings, CABAC :	是
> Format settings, Reference frames :	4 帧
> Codec ID :	avc1
> Codec ID/Info :	Advanced Video Coding
> Duration :	1 时 58 分
> Bit rate :	2 000 kb/s
> Maximum bit rate :	11.7 Mb/s
> Width :	1 920 像素
> Height :	1 080 像素
> Display aspect ratio :	16:9
> Frame rate mode :	恒定帧率 (CFR)
> Frame rate :	23.976 (24000/1001) FPS
> Color space :	YUV
> Chroma subsampling :	4:2:0
> Bit depth :	8 位
> Scan type :	逐行扫描 (连续)
> Bits/(Pixel*Frame) :	0.040
> Stream size :	1.66 GiB (93%)
> Writing library :	x264 core 157 r2969 d4099dd
> Encoding settings :	cabac=1 / ref=2 / deblock=1:-2:-2 / analyse=0x3:0x113 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.25 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=6,6 / fast_pskip=1 / chroma_qp_offset=-4 / threads=34 / lookahead_threads=5 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / rc=2pass / mbtree=1 / bitrate=2000 / ratetol=1.0 / qcomp=0.80 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=17500 / vbv_bufsize=17500 / nal_hrd=none / filler=0 / ip_ratio=1.10 / aq=1:0.50
> Encoded date :	UTC 2020-11-22 02:39:49
> Tagged date :	UTC 2020-11-22 02:40:14
> 编码配置区块 (box) :	avcC
> 
> ## 音频
> ID :	2
> Format :	AAC LC
> Format/Info :	Advanced Audio Codec Low Complexity
> Codec ID :	mp4a-40-2
> Duration :	1 时 58 分
> Bit rate mode :	动态码率 (VBR)
> Bit rate :	156 kb/s
> Maximum bit rate :	165 kb/s
> Channel(s) :	2 声道
> Channel layout :	L R
> Sampling rate :	48.0 kHz
> Frame rate :	46.875 FPS (1024 SPF)
> Compression mode :	有损
> Stream size :	132 MiB (7%)
> Encoded date :	UTC 2020-11-21 22:11:39
> Tagged date :	UTC 2020-11-22 02:40:14

You put codec  and meta information that looks like supported.

But at the first of this issue, you took a screenshot is  a **mkv** file. can that **mkv** file play? 

And, Can that mp4 files play?

**Comment by Kareless** [comment]
Yes,it can play
But this one cannot be played
![image](https://user-images.githubusercontent.com/54282507/128199549-fceaadb9-37e4-4b2e-974b-7267305cd571.png)

**Comment by Kareless** [comment]
The above mkv format 1080p video takes a long time to load
Only found this problem on 1080p video
This problem was not found in the 720p video!
![image](https://user-images.githubusercontent.com/54282507/128200085-04de8347-594d-4e1c-a7a5-d6df38290ee1.png)

**Comment by BruceWind** [comment]
May you can press **F12** to find some errors or logs that chrome print.

I hope you said everything was exactly, If it couldn't play, you should describe "it can't play. " and put video codec infomation.
Or if it could play but take long time, you should say "it can play".

**Comment by BruceWind** [comment]
I think you should forget 1080P or 720p. it shouldn't be considered in this problem.

**Comment by Kareless** [comment]
But I’m not a professional. I don’t understand. I’m in China. I don’t know if you can access my file browser.
ip:116.11.106.98:28888
user name:admin
password:admin

**Comment by Kareless** [comment]
I don’t understand the parameters given by F12. Which part do I need to give you?

**Comment by Kareless** [comment]
You are right, the resolution is not important. 1080p videos can still be played

**Comment by BruceWind** [comment]
pls delete your password, bro. It is very dangerous. 
You need consider network losing package, not the software's bugs.


--------------------
If you aren't a software engineer, we are difficult to figure out problem. I'm sorry bro.

**Comment by Kareless** [comment]
OK Now what we need to discuss is why some mp4 files cannot be played? It becomes a file format that can only be downloaded

**Comment by BruceWind** [comment]
> OK Now what we need to discuss is why some mp4 files cannot be played? It becomes a file format that can only be downloaded

This question need @o1egl  to answer. I dont know, bro. sorry.

**Comment by ramiresviana** [comment]
@bennyborn 
There is an issue that makes browsers transfer the whole video, that can cause long waiting times, and have to be fixed.

@Kareless
FileBrowser uses MIME information provided by the operational system to check files type, it wont be able to show the preview  when that information is not available. Similar to #1439, you can check the Windows registry or add `--disable-type-detection-by-header` parameter when executing FileBrowser as a workaround.

**Comment by Kareless** [comment]
If I want other users who visit my file browser to preview the file, do they have to do this too? Is it possible that the next version of file browser can solve this problem or it can only be solved from the user side

**Comment by bennyborn** [comment]
> @bennyborn
> There is an issue that makes browsers transfer the whole video, that can cause long waiting times, and have to be fixed.

@ramiresviana Just for clarification. Is this an issue of filebrowser or the web browser?

**Comment by tianyunperfect** [comment]
Has the problem been solved? I watch 1080p or continuous loading, it is estimated that after downloading to preview, other videos are very normal.

**Comment by tianyunperfect** [comment]
Another problem is that the video preview does not control the progress.
