### ISSUE TITLE
Wrong name when downloading from CLI

### ISSUE THREAD

**Issue by alexandrestein** [filebrowser/filebrowser#1498]
**Description**

When downloading from cURL or wget the downloaded file names are not good. 
Instead of the name the file are saved with the link ID. 

**Expected behaviour**

File saved with the correct name.

**What is happening instead?**

It is saved with the link ID instead.

**Additional context**

I already fixed the issue on previous version but apparently the length of the like was more important for someone.
Would it be possible to reconsider re-implementing [my fix](https://files.interlab-net.com/api/public/dl/14m4P-HD).

**How to reproduce?**

Generate a link and download the target file with _curl 7.64.0_ or _GNU Wget 1.20.1_ from an up-to-date _Debian 10_ for example.

**Comment by o1egl** [comment]
You can give a name to the downloaded file by using the `-o` param

**Comment by alexandrestein** [comment]
Thanks for your feedback.

OK, this is not a fix, but a workaround.
Actually, I have other tools which don't let me assign save names. (My TV-box, which where I download my movies from my server)

What is the problem of having the name of the file at the end of the link?

If the main reason is the length of the link ; I think this is not relevant because the _usual way_ to share with **filebrowser** is to provide not the file link but the "display" page inside the app where the real download link is clickable.

**Comment by ramiresviana** [comment]
That feature is present on the share view, but only when downloading subfolder items. This is an issue, not a design decision, and should be fixed.

**Comment by alexandrestein** [comment]
@ramiresviana, you are correct. 
Downloading from inside a shared directory, the links has the complete path and file name.
That's perfectly what I'm looking for:
![Screenshot from 2021-08-09 16-51-54](https://user-images.githubusercontent.com/5431025/128728910-f465792c-df4d-49a8-9162-4169baed0d1d.png)

Would be nice to have it even with single file share.
Thanks.
