### ISSUE TITLE
Nil dereference panic upon error creating file

### ISSUE THREAD

**Issue by moshee** [filebrowser/filebrowser#150]
If an error occurs while creating a file, fileserver panics on resource.go:165:

```go
	// Create/Open the file.
	f, err := c.User.FileSystem.OpenFile(context.TODO(), r.URL.Path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0666)
(!)	defer f.Close()

	if err != nil {
		return errorToHTTP(err, false), err
	}
```

This is because if an error occurs, then `f` will usually be `nil`. This deferred method should be placed after the error handling.

**Comment by hacdias** [comment]
Thank you! I'll solve this as soon as I can!

**Comment by hacdias** [comment]
Thank you @moshee
