### ISSUE TITLE
problem with Send email

### ISSUE THREAD

**Issue by am0o0** [filebrowser/filebrowser#1500]
hello dears.
I try to send a message to this email filebrowser@googlegroups.com with my google email and get this error after sending:
![image](https://user-images.githubusercontent.com/77095239/128594894-95e6af9f-7881-4c71-88c6-93ce53acda6d.png)

**Comment by am0o0** [comment]
hey again dear filebrowser team.
this is really important issue please give me some feedback...

**Comment by o1egl** [comment]
Fixed. Try again

**Comment by am0o0** [comment]
Hello again sir, did you get any message from huntr.dev team?

**Comment by o1egl** [comment]
Yes, I did. I think we can close this thread

**Comment by am0o0** [comment]
dear file browser team, can you just give me and huntr team some feedback please?
Best regards.

**Comment by am0o0** [comment]
Hello dear team
On Huntr platfrom you only validate one of my reports can I ask you validate two other ones please?
I losing my mitivation about finding and helping with securoty issues on your nice repository.
If you want any help in fixing those issues just tell me.

Best regards.
