### ISSUE TITLE
(Docker) panic: While parsing config: unexpected end of JSON input

### ISSUE THREAD

**Issue by Suffice** [filebrowser/filebrowser#1504]
Running LibreELEC OS on a Raspberry Pi 4

I try to create the container with this command:
`docker run -v /var/media:/srv -v $HOME/File_Browser/filebrowser.db:/database.db -v $HOME/File_Browser/filebrowser.json:/.filebrowser.json -p 80:80 filebrowser/filebrowser `

```
/storage/File_Browser$ docker run -v /var/media:/srv -v $HOME/File_Browser/filebrowser.db:/database.db -v $HOME/File_Browser/.filebrowser.json:/.filebrowser.json -p 80:80 filebrowser/filebrowser
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x3ec
github.com/spf13/cobra.(*Command).preRun(0x123b628)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x40
github.com/spf13/cobra.(*Command).execute(0x123b628, 0x180e128, 0x0, 0x0, 0x123b628, 0x180e128)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0xe0
github.com/spf13/cobra.(*Command).ExecuteC(0x123b628, 0x1, 0x56e254, 0x12437d8)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x238
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x20
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x24
```

I created two files with the blank command in the appropriate directory: .filebrowser.json and database.db

If I remove the the dot before the file name in the command and the file the container is created successfully and I get these messages:
```
Using config file /.filebrowser.json
Listening on [::]:80
```
Then I lose connection with WinSCP and have to reconnect. 

I'm guessing the .filebrowser.json is created inside the container and not mapped outside of it like intended.

My OS seems to not like hidden files?

I'm also trying to set up access from outside my home network, but not sure how to enter in commands like this:
`filebrowser -a 0.0.0.0 --port 80 r /var/www/html`

If I try to attach myself to the console through Portainer I get:

 The interactive-flag is not set. You might not be able to use the console properly.
 The TTY-flag is not set. You might not be able to use the console properly.

Do I just add it to the docker run command?

Not really sure what's going on, need some help figuring this out.

Thank you in advance!

**Update!**
I was able to connect outside of my network!

I just ran this command:
`docker run -v /var/media:/srv -v $HOME/File_Browser/filebrowser.db:/database.db -p 8085:80 filebrowser/filebrowser`

And forwarded port 8085 from my router.

Still having issue with mapping the .filebrowser.json file though.

**Comment by ramiresviana** [comment]
The provided config file must be on a valid json format, having at least an empty object.

**Comment by Suffice** [comment]
So if I add:
```
{
    "fruit": "Apple",
    "size": "Large",
    "color": "Red"
}
```
To the json file, it will work?

Edit:

Is it supposed to look like this?
```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```

**Comment by ramiresviana** [comment]
The supported config file options are listed at https://filebrowser.org/cli/filebrowser#options.

**Comment by Suffice** [comment]
Adding the information I posted above allowed it to map without fail, so problem solved!

This is the command I ended up using:

`docker run -v /:/srv -v $HOME/File_Browser/filebrowser.db:/database.db -v $HOME/File_Browser/.filebrowser.json:/.filebrowser.json -p 8085:80 filebrowser/filebrowser`

But then I thought I'd try self signing an SSL certificate so there'd be some level of encryption for the files, and I used this command:

`docker run -v /:/srv -v $HOME/File_Browser/data:/data -v $HOME/File_Browser/filebrowser.db:/database.db -v $HOME/File_Browser/.filebrowser.json:/.filebrowser.json -p 8085:80 filebrowser/filebrowser --cert /data/domain.crt --key /data/domain.key`

But the container wasn't working properly, said unhealthy, and this was the last output:
`
% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (22) The requested URL returned error: 400 -- | --
`
Tried using these for the certificates:
```
Public IP
Local IP
127.0.0.1
172.17.0.3
172.17.0.1
0.0.0.0
```
Same problem. Not really sure which one I should be using. 

Definitely over my head with this one, is there a simple solution for this?

**Comment by ramiresviana** [comment]
The default healthcheck will only work with HTTP, see #1487.

**Comment by Suffice** [comment]
I tried this command:
`docker run --health-cmd "curl -f http://localhost:8085/health || exit 1" -v /:/srv -v $HOME/File_Browser/data:/data -v $HOME/File_Browser/filebrowser.db:/database.db -v $HOME/File_Browser/.filebrowser.json:/.filebrowser.json -p 8085:80 filebrowser/filebrowser --cert /data/localhost.crt --key /data/localhost.key`

and got a new last output:
`% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (7) Failed to connect to localhost port 8085 after 24 ms: Connection refused`

Still lost on this...

**Comment by ramiresviana** [comment]
`curl: (7) Failed to connect to localhost port 8085 after 24 ms: Connection refused`
The healthcheck command is executed in the container, you have to use the port used by the application. When no configuration is provided, FileBrowser will listen on port 8080 by default.

**Comment by Suffice** [comment]
Okay, so I tried changing the port for the health check part of the command to 8080, but I still get this error:
`Failed to connect to localhost port 8080 after 0 ms: Connection refused`
So no luck

Trying to connect to the page gives an HTTP ERROR 400.

**Comment by ramiresviana** [comment]
Check the server logs for more information about errors. I recommend you to play around with non-containerized FileBrowser before using it on Docker, the downloads are available on the releases page.

**Comment by Suffice** [comment]
I might try to figure this out later, but for my purposes right now HTTP is fine. 

Since the two issues I had in the beginning are solved I'm going to go ahead and close this. 

Thanks for helping me figure this stuff out!
