### ISSUE TITLE
This location can't be reached (newbie)

### ISSUE THREAD

**Issue by ihubgit** [filebrowser/filebrowser#1507]
Hi, just gave filebrowser a spin on MacOS Mojave 10.14.1. Installed through brew and got to the web UI. Changed the name of admin and password and now I'm trying to figure out how to create a shared folder. Trying to add a folder or dock using the left pane in the web UI gives me a "This location can't be reached" error. So there's probably some other steps to be taken ? But which ? Haven't found very clear info on what to do next.
PS i tried both behind a mobile 4G router and an ADSL connection behind proxy.

**Comment by ramiresviana** [comment]
You have to check the server logs for more information about errors. Please provide the contents of the server console when the error happens.

**Comment by ihubgit** [comment]
ok how can i get those ?

**Comment by ramiresviana** [comment]
FileBrowser will use the current terminal window to show information when something wrong happens. I need that information to help you find what is happening.
