### ISSUE TITLE
File Browser 2.15.0--2.16.1，Why does the file download real connection fail?

### ISSUE THREAD

**Issue by LsnmxNB** [filebrowser/filebrowser#1508]
http://78.com:8088/api/public/dl/h48qCUNX/Base64.txt 
Became http://78.com:8088/api/public/dl/kxWS7RQi
It is too unfriendly to change to this method, and all the connections I shared before are invalid. Can you provide a choice?
The current download real connection does not display the file name.xxxx

**Comment by ramiresviana** [comment]
There's no changes on the url structure of shares from version 2.15 to 2.16. Share hashes are generated randomly, to keep the shares when upgrading versions, you need to use the same database file.

**Comment by LsnmxNB** [comment]
> There's no changes on the url structure of shares from version 2.15 to 2.16. Share hashes are generated randomly, to keep the shares when upgrading versions, you need to use the same database file.

New installation of 2.17.1 will not work, the download connection cannot display the file name

**Comment by o1egl** [comment]
What do you mean saying `the download connection cannot display the file name`

**Comment by o1egl** [comment]
Try the latest version

**Comment by LsnmxNB** [comment]
> Try the latest version

2.17.1 Nor does it work
Download connection does not display file name.xxx

![Snipaste_2021-08-27_11-56-17](https://user-images.githubusercontent.com/42826027/131069524-ea85fd57-d998-4d48-8592-29f56a20e77d.png)

**Comment by ramiresviana** [comment]
The endless loading problem on share screen is now fixed on version 1.17.2.

**Comment by LsnmxNB** [comment]
> The endless loading problem on share screen is now fixed on version 1.17.2.

2.17.2 Nor does it work
Download connection does not display file name.xxx

![Snipaste_2021-08-30_13-35-41](https://user-images.githubusercontent.com/42826027/131290194-ccee0942-13c0-4ed4-b869-c52e0ad9fe1c.png)

**Comment by ramiresviana** [comment]
The filename is not present on the download url from a share, is that you mean? There's a open issue for that, #1498 will be closed once fixed.

**Comment by LsnmxNB** [comment]
> The filename is not present on the download url from a share, is that you mean? There's a open issue for that, #1498 will be closed once fixed.

Yes, Thanks
It is inconvenient that the current download URL does not display the name of the file!
