### ISSUE TITLE
Allow us to change the value of the `theme-color` meta tag

### ISSUE THREAD

**Issue by owenfiscus** [filebrowser/filebrowser#1512]
The source code for filebrowser reveals that the following meta tag is being used to define a theme color for Android browsers, and now, for Safari 15.

`<meta name="theme-color" content="#2979ff">`

It would be great to have a way to set this color to one of our choosing, similar to how we can set a custom css file for the application to use.

**Comment by damienmauchamp** [comment]
Is there any updates?

**Comment by ramiresviana** [comment]
This is already implemented on https://github.com/filebrowser/filebrowser/pull/1542. The color can be set using the `branding.color` configuration.
