### ISSUE TITLE
 In the shared link, you can only open the folder, not the file(version-v2.17)

### ISSUE THREAD

**Issue by spysir** [filebrowser/filebrowser#1514]
In the shared link, you can only open the folder, not the file

**Comment by o1egl** [comment]
There is an `Open file` button on the share page

**Comment by Charolf** [comment]
Can confirm the issue. When a folder is being shared, the files (say, pdf) in the folder are always loading when I want to open them.

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/pull/1515
