### ISSUE TITLE
Don't bind to port 80 by default

### ISSUE THREAD

**Issue by mofirouz** [filebrowser/filebrowser#152]
I'm running this project as a way to remote access files on my local NAS, without the need to SSH or VNC into the machine.

Upon running the project, I got:
```
panic: listen tcp :80: bind: permission denied
```

Now I know how to change the port number of filemanager to not run on port 80, but I think you should change the default port number to be > 1024 at least as those are privileged ports and will require root on some machines.

**Comment by hacdias** [comment]
Hello @mofirouz! You are, indeed, right. I didn't thought much about it. What about 8080? Since it's the most well known alternative port.

**Edit:** I'll set it to 8080 by default.

**Comment by mofirouz** [comment]
Thanks for the quick turnaround - I would suggest a different / random port because the chances are there are other programs using port 8080. This time it's about the ergonomics - totally up to you.

FWIW, I'm running it on port 55532

**Comment by hacdias** [comment]
I'll check if Golang can found a non-used port by default then.
