### ISSUE TITLE
Set share link name manually so that we can remember easily.

### ISSUE THREAD

**Issue by WantToLearnJapanese** [filebrowser/filebrowser#1520]
**Is your feature request related to a problem? Please describe.**
I can not remember 6 characters mixed of sumbols n7mbers captitals.

**Describe the solution you'd like**
Feature to set  manual link name

**Comment by BreakfastSerial** [comment]
I'd second this request. For now I simply configure a redirect on my NGINX reverse proxy, but it would be a welcome option, to manually adjust the share directory.

It would make sense, to only allow administrators to do so and manage possible conflicts with other shares.
