### ISSUE TITLE
OAuth implementation

### ISSUE THREAD

**Issue by mannyci** [filebrowser/filebrowser#1521]
**Authentication with OAuth**
- OAtuh2
- Github
- Google etc

**Comment by fdefilippo** [comment]
Hi, you can use a reverse proxy configured to authenticate using the protocols you mention and then filebrowser with the auth proxy.

**Comment by o1egl** [comment]
OAuth is a feature that will be a part of V3 release. Until then the workaround is using reverse proxy.

**Comment by mannyci** [comment]
Thanks @o1egl for the info that is great to hear that it will be part of V3 release. For now I can't seem to figure out how to achieve this with proxy, any pointers on this is much appreciated. Thanks

**Comment by o1egl** [comment]
Check this section https://filebrowser.org/configuration/authentication-method#proxy-header

And you can use https://github.com/oauth2-proxy/oauth2-proxy or any other solution

**Comment by petersgiles** [comment]
Is there a docker-compose available where this proxy header works?

I can configure my docker image with the header as per the instructions but it redirects me to a login page when I test a GET with the x-header in a postman call.

Internally in the docker image log it seems to get a 403 error making a call to /api/login

**Comment by adyanth** [comment]
Here is a sample stack for traefik + traefik forward auth
https://github.com/adyanth/portable-oidc
