### ISSUE TITLE
General Question.... Installing FILEBROWSER between AWS VM or SSH Shared Hosting Provider

### ISSUE THREAD

**Issue by inglesuniversal** [filebrowser/filebrowser#1522]
I have the option of installing your script on either of the options shown above.

From your experience which option would be better for the script as far as getting the most of it and also maintaining the most secure environment after installation.

Best regards

**Comment by ramiresviana** [comment]
The installation script works by downloading the latest release and extracting the binary, it also makes FileBrowser available on the PATH. If you don't care about the install location, using the script is fine, it doesn't provide additional features between a manual installation.
