### ISSUE TITLE
Antivirus integration

### ISSUE THREAD

**Issue by Id2ndR** [filebrowser/filebrowser#1523]
**Is your feature request related to a problem? Please describe.**
*Command Runner* allows to integrate with an Antivirus software on file(s) upload.
However, if a virus is found and the corresponding file is (re)move, then FileBrowser send a 500 internal error in a tooltip at bottom right.

**Describe the solution you'd like**
It may be useful to display the output of the command in the tooltip when return code of the command is not 0.

**Describe alternatives you've considered**
*I don't have any alternative here

**Additional context**
Set command with `filebrowser cmds add after_upload 'clamdscan -m --move=quarantine $FILE'`

**Comment by r-anwar** [comment]
Hello, I need to initiate an antivirus scan upon the upload event before saving the file to the destination folder. Is there a way to intercept or listen for the upload event?
