### ISSUE TITLE
Display exact date

### ISSUE THREAD

**Issue by thoernle** [filebrowser/filebrowser#1525]
Currently, when viewing a file list, only rounded dates are displayed. Is there a way to display the exact timestamps? In many cases the rough indication is not enough.

**Comment by orazmyradov** [comment]
what about setting a class dedicated to tthe layout of the timestamps?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: thoernle ***@***.***>
Sent: Monday, August 30, 2021 4:52:32 PM
To: filebrowser/filebrowser ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [filebrowser/filebrowser] Display exact date (#1525)


Currently, when viewing a file list, only rounded dates are displayed. Is there a way to display the exact timestamps? In many cases the rough indication is not enough.
