### ISSUE TITLE
Unsupported video formats still end up with <video> tag but never load

### ISSUE THREAD

**Issue by niieani** [filebrowser/filebrowser#1530]
**Description**

Video formats that aren't supported by a given browser still end up with the `<video>` tag, just broken.

**Expected behaviour**

`<video>` component shouldn't be used for formats that aren't supported by the browser. If this is too complicated to implement, there should be a setting to disable automated `<video>` and fallback to the generic UI that shows downloading as the first option.

**What is happening instead?**

Depending on the video, there's either a loading message for an infinite amount of time, or there's a black screen and only audio plays (if audio is a supported codec, but video isn't)

**Additional context**

Screenshot:

<img width="907" alt="Screen Shot 2021-08-31 at 11 06 36 PM" src="https://user-images.githubusercontent.com/563469/131620410-fb5de26c-ee70-4c54-abf7-5812c691c4bd.png">

**How to reproduce?**

Upload attached file, try opening in File Browser on latest Chrome on Mac or from an Android phone.

**Files**

- [example.mov](https://user-images.githubusercontent.com/563469/131620081-f983333e-fbc2-4d0d-91ac-64718054fad6.mov)

**Comment by ramiresviana** [comment]
Can you provide a video sample that causes the endless loading screen? It should be possible to fix the unsupported video format issue with some tweaks on media type detection and `HTMLMediaElement.canPlayType()` on the frontend.

**Comment by niieani** [comment]
Hi @ramiresviana, I provided the sample file in the original post.

**Comment by niieani** [comment]
bot ping

**Comment by niieani** [comment]
bot ping

**Comment by niieani** [comment]
bot ping

**Comment by niieani** [comment]
bot ping
