### ISSUE TITLE
total size of the folder

### ISSUE THREAD

**Issue by Lilihx** [filebrowser/filebrowser#1535]
It taks a little time to get the size of every folder in the file list.

But, can we cal that in the file information ?

<img width="438" alt="截屏2021-09-03 下午2 35 43" src="https://user-images.githubusercontent.com/88191432/131961367-88bea74c-f3f6-4592-8cba-e9ae16a391ad.png">

**Comment by ramiresviana** [comment]
This was already requested on #1417

**Comment by o1egl** [comment]
Duplicate
