### ISSUE TITLE
Can't upload the file and no error detail shown

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1539]
**Description** i can't upload a file 

**Expected behaviour**
our excpectation was i can upload the file

**What is happening instead?**
The error shown [object Object]. that's it. 

**Files**
![image](https://user-images.githubusercontent.com/83719948/132215341-bc1661db-4b83-4656-b14d-524a3d3fc7ca.png)

**Comment by o1egl** [comment]
We need server and client logs to be able to help you

**Comment by uatec** [comment]
I have received the same error. However I have not got any logs to show. Neither the client nor the server logged anything when this error occured.

What I did find is that my load balancer was giving me an HTTP 413. This should have been made visible to the client

**Comment by o1egl** [comment]
@Michaelnotavaiableingithub you are using filebrowser integrated into a 3rd party app. We are not supporting 3rd party integrations
