### ISSUE TITLE
Need unzip option

### ISSUE THREAD

**Issue by mohitjoshi155** [filebrowser/filebrowser#1541]
can unzip option be added plz so we can unzip files on filebrowser

**Comment by menincode** [comment]
You must add 'unzip' command allow to admin account.
* First,
`Settings > User Management > Click pencil edit 'admin' account`
* Then scroll to `Commands`, add `unzip` command
* Click 'Save' and refresh
* Done

**Comment by ChilliGeologist** [comment]
I second this, support .rar as well would be amazing but at least .zip would be great
