### ISSUE TITLE
flv video

### ISSUE THREAD

**Issue by mujiebibai** [filebrowser/filebrowser#1543]
I am try play flv format video, but no play,  Can't the video in this format be played?  sorry , i'm english not good
![1631000033(1)](https://user-images.githubusercontent.com/31977599/132303794-d9da0555-d583-4aaa-badb-7e533717171d.jpg)

**Comment by o1egl** [comment]
Filebrowser uses the browser's capabilities to play a video file. Looks like your browser is not able to play this video

**Comment by mujiebibai** [comment]
I am currently using edge for chromium browser, It doesn't seem possible to play this video now, After that, do you have any plans to replace the browser player?

**Comment by niubility000** [comment]
Use "quark browser" in android phone. It can play all kinds of videos except ".swf".

**Comment by y1jiong** [comment]
> Use "quark browser" in android phone. It can play all kinds of videos except ".swf". 

Useful.

**Comment by niubility000** [comment]
> > Use "quark browser" in android phone. It can play all kinds of videos except ".swf".
> 
> Useful.

and @mujiebibai
You can use firefox browser in windows PC to play .flv, or .avi, or .rm... video online (not download completely then play. It's online playing). When you click "open file", Firefox will ask you to choose which app(installed in your PC) you wanna use to open the file.

**Comment by sxx1314** [comment]
I can use [https://chrome.google.com/webstore/detail/native-flv-playback/fjmoemhemaejfjodjgnpkelbdgejnpgd](https://chrome.google.com/webstore/detail/native-flv-playback/fjmoemhemaejfjodjgnpkelbdgejnpgd)  flv.js  to play  flv .
Url : http://xxx.com/api/raw/home/3.flv?k=123456&inline=true .
