### ISSUE TITLE
Error on File Manager when updating file [object Object]

### ISSUE THREAD

**Issue by AiltonSalguero** [filebrowser/filebrowser#1546]
**Description**
Error when updating a file in file manager

**Expected behaviour**
Successful txt file update

**What is happening instead?**
Error message

**Additional context**
Odoo application

**How to reproduce?**
Go into file manager and try to update a txt file

**Files**

![Screenshot_3](https://user-images.githubusercontent.com/40039043/132720737-7057c5aa-a090-42c6-94cc-b5c1835916f2.png)

**Comment by ramiresviana** [comment]
Looks like you're using FileBrowser through a third-party application, please contact your service provider for support.
