### ISSUE TITLE
RestAPI

### ISSUE THREAD

**Issue by MrTelly** [filebrowser/filebrowser#1548]
Hi FileBrowser,
        We're using FileBrowser as part of a larger vendor product and would like to upload files via RestAPI or any other automatable interface. 

I can see in a previous request that WebSocket API would require a change of the source and re-implementation. As we don't have control over the SAAS environment that the vendor provides that's probably going to be too hard.

I'm considering using Selenium to drive FileBrowser but wanted to check if there's any form of API or URL forms encoding that I could use as a better alternative before I start the development work.

MrTelly

**Comment by o1egl** [comment]
Filebrowser uses http queries for everything but the command terminal. Unfortunately, there are no docs for that API and the only way is to browse the code

**Comment by krysalead** [comment]
Hi,
I have almost the same need, I wanted to use the FileBrowser as a file server I can upload, list files using an API, not using the UI.  I had a look to the UI code to see how you communicate with the server and sees that there is not that much of comment :-1: and a huge bunch of code. Could be good to write some words to put everyone on track.

**Comment by nambrosch** [comment]
I'm looking for this solution as well - would like to automate uploads with a script using rest api and allow humans to access these files using the gui.  Here's what my browser is sending, If there was an easily scriptable way to authenticate then we'd be in business:
```
curl 'https://.../api/resources/...?override=false'
  -X POST
  -H 'User-Agent: ...'
  -H 'Accept: */*'
  -H 'Accept-Language: en-US,en;q=0.5'
  -H 'Accept-Encoding: gzip, deflate, br'
  -H 'X-Auth: ...'
  -H 'Content-Length: 24'
  -H 'Origin: https://...'
  -H 'Authorization: Basic ...'
  -H 'Connection: keep-alive'
  -H 'Referer: https://...'
  -H 'Cookie: ...'
  -H 'Sec-Fetch-Dest: empty'
  -H 'Sec-Fetch-Mode: cors'
  -H 'Sec-Fetch-Site: same-origin'
  -H 'Pragma: no-cache'
  -H 'Cache-Control: no-cache'
  ```

**Comment by michaelniemand** [comment]
possible duplicate of https://github.com/filebrowser/filebrowser/issues/1079 / 
also maybe this: https://github.com/filebrowser/docs/issues/1

**Comment by rizlas** [comment]
Check this https://github.com/rizlas/filebrowser-upload. I just updated and old repository that upload files via cli. Maybe you can pick some logic from there.

**Comment by gaby** [comment]
Still valid, i dont understand why the bot is so aggresive
