### ISSUE TITLE
Serving filebrowser as Apache/Nginx webserver's user on Ubuntu, runing under systemd!

### ISSUE THREAD

**Issue by mehdiMj-ir** [filebrowser/filebrowser#1549]
**Is your feature request related to a problem? Please describe.**
Hi, I have a `GNU/Linux Ubuntu` VPS witch serving several `Wordpress` sites on _/var/www/ directory_. I gave permissions  on _/var/www/_ directory to `www-data` user, `644` for files and `755` for directories.

**Describe the solution you'd like**
I wonder if **`filebrowser`** able to serve and have no problem with _/var/www/_ directory  permissions as `systemd service` .

**Describe alternatives you've considered**
I think if I cloud run `filebrouser` as `www-data` user  will be ok -> `sudo -u www-data filebrowser -r /var/www/ -p 8080 -a 0.0.0.0` and then `reverse proxy` it with my webserver so I have nice **Direct File Access** on port 443 _https://dfa.mydomain.com_.

**Additional context**
I wonder if this is OK or right approach, what is your operation?

**Comment by o1egl** [comment]
I don't see any issues using this solution

**Comment by mehdiMj-ir** [comment]
> I don't see any issues using this solution

That was a relief Thank you and I'm grateful for this magnificent software :)

**Comment by raspi-coder** [comment]
I am using such a configuration and it works without issues. Using Apache as web server / reverse proxy. 

Hope this helps in any way.
