### ISSUE TITLE
Directory Pagination

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#155]
Limit the number of files in each page.

**Comment by hacdias** [comment]
@arteta22000 do you think it should have "pages" or infinite scrolling would be better?

**Comment by arteta22000** [comment]
The easiest (or lightest) for you ?
"infinite scrolling" is probably more modern ;)

**Comment by arteta22000** [comment]
If someone could work on that :thumbsup: . it becomes unusable with a lot of files

**Comment by arteta22000** [comment]
I'll need to change tool :(  without this option, it's unusable.

**Comment by hacdias** [comment]
@arteta22000 sorry for this... let me produce a test build with infinite scrolling just to make sure it works. WHich OS and arch do you use?

**Comment by arteta22000** [comment]
Debian 8, amd64.

**Comment by hacdias** [comment]
Here's the file: https://www.dropbox.com/s/8ltfl8l4h9st9ev/filebrowser?dl=0
I tried it on a dir with more than 1500 files and it seemed fast. Initially it will only show 50 items and when you scroll down, 50 more will be added.

**Comment by hacdias** [comment]
(it has a bug when you select the file, but I'll solve it. just to make sure the pagination is good)

**Comment by arteta22000** [comment]
Ok, thanks, I'll check at lunch ;)
Can you control that the pagination is ok when we do a search?

**Comment by hacdias** [comment]
Uh, the pagination was just for files and not search results, but I can add that.

**Comment by hacdias** [comment]
Here https://www.dropbox.com/s/8ltfl8l4h9st9ev/filebrowser?dl=0
And I made search case insensitive by default.

**Comment by arteta22000** [comment]
Everything is working smoothly for now, much faster ;)
I ping you, if we report bugs. Thanks !!

You're pushing this in release ?

**Comment by hacdias** [comment]
@arteta22000 1.9.0 coming soon!

**Comment by rhjmoore** [comment]
This works wonderfully in Chrome on a desktop. On Chrome on Android, the infinite scroll doesn't work - it just comes to the end of the first set of file and goes no further.
If you go to copy a file into a folder with many folders, all of them list successfully. It's just the main pagination / infinite scrolling while browsing a large directory that doesn't work on mobile.

Do let me know if there's anything I can to help identify the issue.
