### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by DarrenPIngram** [filebrowser/filebrowser#1552]
**Description**

The log is filling with reports about broken pipes, and people trying to use the share report problems.

**Expected behaviour**

I expect it to deliver the file and not give an error. Other functions on the machine appear to be working.

**What is happening instead?**

Extract from the displayed console:
2021/09/12 08:07:39 Failed to archive /asian.provocateur.s02e01.dvdrip.x264-ghouls.mkv: asian.provocateur.s02e01.dvdrip.x264-ghouls.mkv: copying contents: write tcp 192.168.0.90:8082->**ip**:61753: write: broken pipe
2021/09/12 08:07:39 Failed to archive /asian.provocateur.s02e01.dvdrip.x264-ghouls.sub: asian.provocateur.s02e01.dvdrip.x264-ghouls.sub: making header: write tcp 192.168.0.90:8082->**ip**:61753: write: broken pipe

**Additional context**

-

**How to reproduce?**

The application was installed. No specific permission restrictions on the data drive (mounted as a standard drive under OSX. File copied over to the directory. Shared and then the error was noted on retrieval.

**Files**

-

**Comment by o1egl** [comment]
Which version of the app are you using? Also please share your browser logs

**Comment by DarrenPIngram** [comment]
Sorry for the delay. MacOS 10.5.7. File Browser 2.17.2



‌

**Comment by o1egl** [comment]
Do you have a proxy server in front of the app? And there are no browser logs attached

**Comment by DarrenPIngram** [comment]
No proxy server. Where/what are the logs you refer to? I have not had the
problem again so far, but no one has tried to access a fileshare either.

Tks

‌

**Comment by ramiresviana** [comment]
The broken pipe error happens when the connection with the server is interrupted abruptly. This issue is probably related to connectivity problems not related to FileBrowser.

**Comment by DarrenPIngram** [comment]
Thanks. Useful to know, but difficult to understand as it is running on a
beefy server and whilst the available bandwidth is lower than my other
server, the file sharing link was only given to a couple of people.

A separate SFTP process with a much larger use-case seems not be throwing
up the problems, at least according to the logging.

Maybe I must concentrate the share-browsing on the other server. There it
seems to be without problems so far. The only difference is that the
"problematical" server is MacOS whereas the other is pure Linux.




‌
