### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by sunosv** [filebrowser/filebrowser#1555]
**Description**
logs show nothing about this.But in web browser F12 you can see this.
I put filebrowser on windows running

DevTools failed to parse SourceMap: https:/xxx/static/js/chunk-vendors.fdfc012d.js.map
DevTools failed to load source map: Could not load content for webpack:///node_modules/sockjs-client/dist/sockjs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://xxxx/static/js/chunk-vendors.fdfc012d.js.map: HTTP error: status code 200, net::ERR_CONTENT_LENGTH_MISMATCH
DevTools failed to load source map: Could not load content for https://xxxxx/static/js/app.22296cc3.js.map: HTTP error: status code 200, net::ERR_CONTENT_LENGTH_MISMATCH
GET https://localhost:9000/sockjs-node/info?t=1631590550989 net::ERR_CONNECTION_REFUSED
[![4FIRAJ.png](https://z3.ax1x.com/2021/09/14/4FIRAJ.png)](https://imgtu.com/i/4FIRAJ)

**Comment by ramiresviana** [comment]
Your description does not contain information necessary to reproduce the issue.  Please provide information following the bug report template, including also server logs and a browser HAR file.
