### ISSUE TITLE
Is there a correct way to set a baseurl via the docker so that a reverse proxy can work?

### ISSUE THREAD

**Issue by Nurgus** [filebrowser/filebrowser#1557]
**Is your feature request related to a problem? Please describe.**
Filebrowser doesn't work when behind a reverse proxy

**Describe the solution you'd like**
Filebrowser under a baseurl.

**Comment by ramiresviana** [comment]
The baseurl option be set using a flag, environment variable and configuration file. The options documentation is available at https://filebrowser.org/cli/filebrowser

**Comment by Nurgus** [comment]
Setting baseurl in an environment variable would be ideal but it doesn't seem to be taking effect.

**Comment by ramiresviana** [comment]
I have no issues when running `docker run -P -e "FB_BASEURL=/filebrowser" filebrowser/filebrowser`.

**Comment by Nurgus** [comment]
That did the trick (with a leading slash) thanks! Where did you get FB_BASEURL from? I don't see any mention of that.

**Comment by ramiresviana** [comment]
All options listed at https://filebrowser.org/cli/filebrowser#options can be used with a flag, environment variable and configuration file. The documentation currently lacks information about the leading slash.
