### ISSUE TITLE
Stuck at loading when there are a lot of files in a directory?

### ISSUE THREAD

**Issue by shahidcodes** [filebrowser/filebrowser#1566]
Hello, I really like this project. I am trying to use it to browse files in a directory that has 10K+ pdf and image files. But it gets stuck for a very very long time. Eventually, it shows the files but it takes a lot of time.

Is there any way I can improve the load time of such a directory?

**Comment by shahidcodes** [comment]
it seems to be fine now. After few times it is fast. Is there any cache? If so can I configure cache ttl

**Comment by o1egl** [comment]
There is no cache for file listing

**Comment by niubility000** [comment]
Maybe try this command, for example:for windows: .\filebrowser.exe -d filebrowser.db --disable-preview-resize --cache-dir cache
The best way is to seperate the current huge folder to several small folders.  
I think Filebrowser is the fastest one compared with other projects, for example: nextcloud, filerun, kodexplorer, kodbox, photoprism, eyeblue... I've tried them all, they are very slow to load huge pics, especially for the linux arm64, linux arm v5 server . Another problem is that they need to change your harddisk's current directories completely.  
Filebrowser gets the thumbnails from the exif info of the pics. This makes it very fast to load the thumbnails.

**Comment by niubility000** [comment]
this will solve the problem: 
--disable-type-detection-by-header

**Comment by niubility000** [comment]
Use the following command to run the filebrowser:
/filebrowser/filebrowser -d /filebrowser/filebrowser.db --disable-preview-resize --disable-type-detection-by-header  --cache-dir /filebrowser/cache

It will be as fast as "ls" command in Linux, no matter how large the folder is.

**Comment by banchchuoi** [comment]
I used file browser version  2.21.1 but I had the same problem as his despite configured with --disable-type-detection-by-header option, but no effect,  here is my configuration:
- /etc/filebrowser.json
{
  "port": 8080,
  "baseURL": "",
  "address": "x.x.x.x",
  "log": "stdout",
  "database": "/etc/filebrowser.db",
  "root": "/u01/camera"
}
- /etc/systemd/system/filebrowser.service
[Unit]
Description=File Browser
After=network.target
[Service]
ExecStart=/usr/local/bin/filebrowser -c /etc/filebrowser.json --disable-preview-resize --disable-type-detection-by-header --cache-dir /u01/cache
[Install]
WantedBy=multi-user.target

Can somebody help me?

**Comment by NzmlAl01** [comment]
![image](https://github.com/user-attachments/assets/e0327594-bdf3-4ab6-8f49-00fa4c124611)
help me please
