### ISSUE TITLE
the content-type is zip when download a .apk file

### ISSUE THREAD

**Issue by xmade** [filebrowser/filebrowser#1578]
**Description**
download a .apk file from host. the response header is like below
```pt-ranges: bytes
cache-control: private
content-disposition: attachment; filename*=utf-8''xxxxx_v1.2.6.apk
content-length: 2359569
content-security-policy: default-src 'self'
content-type: application/zip
date: Thu, 23 Sep 2021 03:51:17 GMT
last-modified: Fri, 14 May 2021 01:47:32 GMT
server: nginx/1.18.0 (Ubuntu)
```
**Expected behaviour**
download .apk file  as apk content-type
`application/vnd.android.package-archive`

**What is happening instead?**
content-type: application/zip

**Comment by ramiresviana** [comment]
The `content-type` value is provided by the OS. On my Windows 10 system, the information for the `.apk` format, that should be located on the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\`, is absent. To make the `.apk` format work correctly, the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.apk\Content Type` value should be `application/vnd.android.package-archive`.

**Comment by mckaygerhard** [comment]
so in resume.. is a shitty os problem.. not a filebrowser problem :laughing:
