### ISSUE TITLE
provide hook or more flexible auth method, to be able to integrate with databases, ex: custom query

### ISSUE THREAD

**Issue by mckaygerhard** [filebrowser/filebrowser#1579]
**Is your feature request related to a problem? Please describe.**

hi your app is great.. but auth integratino is bit frustrating.. after a while found the PR https://github.com/filebrowser/filebrowser/pull/1554 and i guess can be adapted to provide auth hook agains a database

**Describe the solution you'd like**

something like the PR https://github.com/filebrowser/filebrowser/pull/1554 but adapted to property integrated to an already provided database.. a custom query will be enought with two mandatory parameters as '?' and a thirh one optional for grouping!

**Describe alternatives you've considered**

i only check most close the PR https://github.com/filebrowser/filebrowser/pull/1554 rest of issues are only proxy header that is not available for mixed intranets!

i dont have golang skills but i can collaborate with several support and tutorial and use cases

**Comment by adga137** [comment]
i want this feature, curerntly for novicers or too busy people is hard to understandt networking  issues and setup not knowing things.. i like more a SQL setup

**Comment by gaby** [comment]
This is fixed by #1554

**Comment by mckaygerhard** [comment]
> This is fixed by #1554

the branch its out of date respect master.. also that is only a help part for that is requested here.. @gaby  .. i am afraid that the only way to improve this project its by forking and made a new team.. but its a drastic movement cos we are reinventing the whell cos there's already this project... **just that @o1egl  does not want to delegate functions**

**Comment by mckaygerhard** [comment]
ping

**Comment by mckaygerhard** [comment]
ping

**Comment by mckaygerhard** [comment]
crap bot.. closing valid issues due author do not take care neither delegate the project

if anyone wants to fork the project take me as contributor too

**Comment by gaby** [comment]
@mckaygerhard doesnt #1554 fix this issue?

**Comment by mckaygerhard** [comment]
intersting someone already teal me abouyt such hook but i do not tested becouse i was on hurry in such moment.. and i guess i cannot test until july almost.. @gaby
