### ISSUE TITLE
Persistent caching of frontend files in development - better docs

### ISSUE THREAD

**Issue by bartlomieju** [filebrowser/filebrowser#158]
Really great package! I wanted to hack around on the frontend part of project as I am really keen on Vue but couldn't get past caching of  `.js` files. Could you add a sentence or two on how to develop front-end code? I used `npm run dev` as stated but I'm still getting served with old files by service workers. Thanks!

**Comment by hacdias** [comment]
Hello @bartlomieju 😄 

1. Start running `npm run dev`
2. Then, `go build`/`go install` github.com/hacdias/filemanager/cmd/filemanager

I have to update the docs to make them more clear!
Tell me if that's what you're doing and if you're still receiving the old files.

**Comment by bartlomieju** [comment]
Yes. I'm going like:
1. `yarn run dev`
2. `go install github.com/hacdias/filemanager/cmd/filemanager`
3. `go run cmd/filemanager/main.go --port 9100`
But no luck :(

**Comment by hacdias** [comment]
Strange... did you try cleaning the cache?

**Comment by bartlomieju** [comment]
I've managed to get it working - I `clone`d the repo instead of `go get` :(

Sorry for inconvenience, I'll try to make up by adding some PR concerning front-end app. Cheers!

**Comment by hacdias** [comment]
No problem! I'll look forward for your PRs 😄
