### ISSUE TITLE
minor bug: filebrowser reveals real name of root protected directory

### ISSUE THREAD

**Issue by mckaygerhard** [filebrowser/filebrowser#1580]
**Description**

installed filebrowser and deploy to a domain, using subpath or not, permit to watch the name of the directory protected of the root fs

**Expected behaviour**

in root directory there's no "file" to show, so event parse the name of the real root directory parsed only "/" or "root dir"

**What is happening instead?**

gives me the named of the root directory that is protected in the web server filesystem

**How to reproduce?**
the most easy way is runs with defaults in any directory and without selecting any file push in the info icon

**Additional context**

![imagen](https://user-images.githubusercontent.com/1571724/134588852-044234d1-3388-40c2-a9e3-d7c15d2180d8.png)

**Comment by o1egl** [comment]
I didn't get what is the issue? Filebrowser doesn't read your web server configs. You must configure it separately

**Comment by mckaygerhard** [comment]
> I didn't get what is the issue? Filebrowser doesn't read your web server configs. You must configure it separately

the issue is that due there's no clarification on the docs (as i can see) when user/admin runs with current path.. this path is revelaed the real name in the file information if you are in root and have some privilegies in filebrowser.. 

is minor issue but as i can see, documentation is the problem is not user friendly.. has not clear examples and does not are up to date (as some issues pointed)

i am currently triying to get up to date the docs.. maybe some pull may be the solution

**Comment by o1egl** [comment]
You are welcome to make a PR to the [docs](https://github.com/filebrowser/docs) repo

**Comment by mckaygerhard** [comment]
> You are welcome to make a PR to the [docs](https://github.com/filebrowser/docs) repo

yeas.. i am studing the appication to property fixed those documents
