### ISSUE TITLE
Rclone mount issue?

### ISSUE THREAD

**Issue by DarrenPIngram** [filebrowser/filebrowser#1582]
**Description**

Run filebrowser. It seems that an unmounted/failed rclone mount on the system can stop Filebrowser working, even though Filebrowser is not referencing the rclone mount. 

**Expected behaviour**

Filebrowser to run and share files.

**What is happening instead?**

When you visit Filebrowser by the web interface, in order to create a shared item, you get the "there is something wrong" error message at the "root" / home.

**Additional context**

**How to reproduce?**

Filebrowser has the path created with

`filebrowser config set -r "/home/user/torrents/qbittorrent/Rshare"`

and it is confirmed by running `filebrowser config cat`

The established directory is verified as working by the terminal too.

**Files**

After hitting a brick wall, the host's technical support fixed it by noting a mount was down (it wasn't being used).

I think it was showing as failed in the FB log too, but that was ignored as it wasn't being used.

I am wondering if there is some old setting remembering the presence of the server mount, despite it being a new installation etc.

**Comment by ramiresviana** [comment]
FileBrowser makes use of the host filesystem, it will list mount points in the same way as directories, do not knowing the diference between both.  The directory/information is gathered over demand, only settings are 'remembered'. You have an issue where the root path was not accessible, not related to FileBrowser.

**Comment by DarrenPIngram** [comment]
That is frustrating as it is difficult to track down with the terse
messages it generates, especially as the same root system (or directories
below it, the same as Filebrowser gets) is accessible by sftp and that has
(so far) no problems nor strange entries in the log. Thanks for the
feedback though.

‌

**Comment by ramiresviana** [comment]
It may be a problem with FileBrowser since other programs are able to access that directory. To check what is happening, we need information about how to reproduce the issue. If you find out what causes the issue, please tell us.

**Comment by DarrenPIngram** [comment]
Is there a way to get any more detailed logs, such a debug?

I am firing it off by:

filebrowser -a address -p 8082 -r path_to_fils



Some reports suggest that files can be downloaded, even if the log gives
material such as:


2021/09/28 09:26:13 Failed to archive
/20.To.One.S13E08.720p.HDTV.x264-CBFM.mkv:
20.To.One.S13E08.720p.HDTV.x264-CBFM.mkv: making header: write tcp
address:8082->address:60496: write: broken pipe
‌

**Comment by ramiresviana** [comment]
There's no debug option for FileBrowser, errors will be logged to the console.

**Comment by DarrenPIngram** [comment]
Ok, I’ve passed on examples of ‘errors’ that come up on the terminal. The only difference I can see is this installation is running on MacOS 10.15.7 while another installation I have runs under Debian.


—- 
Via iPad. Hopefully with not too many typos.
