### ISSUE TITLE
unexpected sharing

### ISSUE THREAD

**Issue by nilsherzig** [filebrowser/filebrowser#1584]
**Description**
Open image in new tab and sharing the link 

**Expected behavior**
since I didn't use the share function, I expect the link not be working when opened in another browser / incognito 

**What is happening instead?**
Link works even from another device

**Additional context**
The problem is, that i have no overview over files shared this way, since they don't appear in the "share manager" tab.

**Comment by ramiresviana** [comment]
When clicking on the Download or Open File buttons from the preview, a URL containing user token is generated. The user token is an information used to check if the user is authenticated. When a valid token is present on the URL, the file can be downloaded. The user token is confidential, you should avoid sharing direct download links that contains tokens.

**Comment by mckaygerhard** [comment]
> When clicking on the Download or Open File buttons from the preview, a URL containing user token is generated. The user token is an information used to check if the user is authenticated...

interesting.. **_maybe a token expiration is the right choice_**, but this will complicated the things.. so **i guess is minor issue and user responsabilitie is the key..**

**Comment by ramiresviana** [comment]
The authentication token is configured to expire 2 hours after it was issued.
