### ISSUE TITLE
Selectively disable folder downloads

### ISSUE THREAD

**Issue by Xwaler** [filebrowser/filebrowser#1586]
**Is your feature request related to a problem? Please describe.**
I would like to share a very heavy folder (2+ To), however it is absolutely possible that one of my users tries to download the whole folder, resulting in the creation of an archive possibly bigger than the available disk space. I suspect that a very high load would be experienced on the server and eventually a loss of free space after the archiving failed.

**Describe the solution you'd like**
Allow the administrator to select which folder is downloadable, and/or which are forbidden.

**Describe alternatives you've considered**
Allow to disable folder download altogether. Add an option to configure the max size allowed for a folder to be downloaded.

**Additional context**
Great work overall !

**Comment by ramiresviana** [comment]
The process of archiving, when a folder is downloaded, does not store temporary files on disk. Also, canceling a folder download will cancel the process of archiving. Even with disabling the folder download, users will still be able to download multiple files by selecting then or by opening each one.

**Comment by Xwaler** [comment]
Brilliant! That's reassuring, in my case I'm okay if a user wants to download the whole folder and operations are done without cache.
Thank you for the quick response, I'll now close the issue.
