### ISSUE TITLE
Iframe embedding auth handling

### ISSUE THREAD

**Issue by mhdaouas** [filebrowser/filebrowser#1587]
Thank you for this awesome file manager!

I wanted to know how to handle authentication when embedding it with an iframe?

**Comment by o1egl** [comment]
You can try to use header based authentication

**Comment by mhdaouas** [comment]
What is more secure: json auth or proxy header method? Also what is the best way to migrate users based on an existing Postgres DB or ldap server? Maybe I should create the user with your /api/users API?

**Comment by Tooloco** [comment]
As the documentation states I assume proxy header authentication is worse if the reverse proxy can be bypassed
