### ISSUE TITLE
Hugo plugin not using caddyfile settings

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#159]
Hi Hacdias

I'm Using Caddy 0.10.4 from caddyserver.com today (27 July)

This is my caddyfile
```text
simonchurch.preview.astondavies.co.uk {
  tls jeremy@astondavies.co.uk
  root /hugo/simonchurch/preview
  gzip
  errors {
    404 404.html
  }

  hugo /hugo/simonchurch /cms {
    database simonchurch.db
  }
}

http://www.simonchurch.co.uk {
  redir http://www.simonchurchelectrical.co.uk{uri}
}

http://www.simonchurchelectrical.co.uk {
  root /hugo/simonchurch/public
  gzip
  log /var/log/www/simonchurchelectrical.log
  errors /var/log/www/simonchurchelectrical.err.log {
    404 404.html
  }
}
```

When logging in to the Filemanager interface, the home (my files) shows the caddy root (with . in the site title) instead of the files at /hugo/simonchurch as specified in the caddyfile.

I can manually change this after logging in (as admin) by setting both the global hugo root and the users scope but it seems that it should really default to the caddyfile settings.

**Comment by hacdias** [comment]
Hello @AstonDavies!

Sorry for this. This is the exactly same mistake I did with filemanager plugin, but I haven't updated the Hugo one to fix it 😞 I'll fix this now

**Comment by AstonDavies** [comment]
Hi

No worries. I have a few other issues with publishing but this may all be related to the paths here so I will await an update and see if they go away. Unless, of course, you would like to know about them now.

**Comment by hacdias** [comment]
I'll deploy this fix to the build server and ping you when it finishes the build. If the other issues persist, you then tell me 😄

**Comment by hacdias** [comment]
Deployed! @AstonDavies
