### ISSUE TITLE
Hope to let filebrowser display the transfer rate when uploading.

### ISSUE THREAD

**Issue by daiaji** [filebrowser/filebrowser#1590]
My upload rate is not particularly fast, and not seeing the upload rate makes me a little anxious.
Show the rate when the mouse hovers over the upload progress bar, or show the speed when the mouse hovers over the upload button, which is great.

**Comment by niubility000** [comment]
I have fixed it.

**Comment by daiaji** [comment]
> I have fixed it.

Great, but what happens when uploading multiple files?

**Comment by niubility000** [comment]
> > I have fixed it.
> 
> Great, but what happens when uploading multiple files?

Can we upload multiple files? I think it will be treated as one large file, the process rate is for the whole process.

**Comment by niubility000** [comment]
> > I have fixed it.
> 
> Great, but what happens when uploading multiple files?

Can we upload multiple files? I think it will be treated as one large file, the process rate is for the whole process.

**Comment by donut** [comment]
Show a percentage isn't the transfer rate. It would be helpful to have a list of uploads and the rates at which they're uploading.

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/issues/1380
