### ISSUE TITLE
Make filebrowser conform to XDG Base Directory Specification.

### ISSUE THREAD

**Issue by daiaji** [filebrowser/filebrowser#1592]
The filebrowser does not seem to conform to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) .

**Comment by o1egl** [comment]
Filebrowser doesn't use linux user home directories. All operations are done relative to the [root path](https://filebrowser.org/cli/filebrowser)

**Comment by mckaygerhard** [comment]
filebrowser must complain with XDG base directory in unix like systems, for now the config file is searching in `/etc/ `but is not enought cos is more like LSB standard

**Comment by o1egl** [comment]
You can make a PR to the project

**Comment by daiaji** [comment]
File names like `.filebrowser.json` don’t look like they conform to any kind of specification. They seem to be ordinary hidden files randomly created in the home directory. This seems to be exactly what XDG is committed to solving.

**Comment by mckaygerhard** [comment]
hi @o1egl  i was working in some changes but unfortunatelly the first things to be fixed is the documentation.. please can you take a look to the pull request of the docs repository, and provide directions! 

also the workflow of the merge are too slow so I propose that any PR be merged as long as there are two approvals, where @ramiresviana  can be one of the candidates cos i can see he is very active !

**Comment by o1egl** [comment]
@daiaji we had no intention to conform XDG specification. As I mentioned earlier, if you have any ideas, you can make a PR for this project.
