### ISSUE TITLE
Feature request for file encryption 

### ISSUE THREAD

**Issue by Tooloco** [filebrowser/filebrowser#1593]
**Is your feature request related to a problem? Please describe.**
Nope
**Describe the solution you'd like**
A way to enable file encryption per user maybe using a hash of the user's password as a key

**Describe alternatives you've considered**

I haven't thought about it much but maybe through the command execution functionality it could be done. 
**Additional context**

**Comment by o1egl** [comment]
What is the use case of file encryption?

**Comment by PLK2** [comment]
I have an SSD drive attached to a RockPro64 running File Browser. All the files I have in File Browser are saved to that SSD drive unencrypted. Not ideal for privacy/security.

**Comment by IceWreck** [comment]
Why not use gocryptfs in combination with filebrowser ?

I do it just for sensitive files.
