### ISSUE TITLE
Some changes I 've made, please take a look. 

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1594]
I've made some changes, please take a look. If it's good, we can make it more efficient and make PRs.
Attached are the filebrowser.exe (windows X64 version) and the code files I changed and the whole source codes(already include the changes).  Feel free to test and modify it.

1. Swipe screen to switch pics and videos and audios. ( copy from WeidiDeng's PR)
2. Add animation when pics enter, switch and zoom.
3. Add rotate button for pics (copy from WeidiDeng's PR) and maximize the preview window, make the header bar transparent and auto hidden.
4. Add fullscreen button.
5. Add "thrumbnails border-radius", looks better.
6. Fix searchbox size.
7. Fix breadcrumb border.
8. Show process percentage when uploading.
9. fixed share delete confirmation (copy from EricAndrechek)
10. Fix the sidebar's function.
11. Fix the browser's "back" button functon.

[modified.zip](https://github.com/filebrowser/filebrowser/files/7272647/modified.zip)

[filebrowser source code.zip](https://github.com/filebrowser/filebrowser/files/7272676/filebrowser.source.code.zip)

1. fullscreen and rotate buttons, and transparent header bar
![1 fullscreen and rotate button](https://user-images.githubusercontent.com/76441520/135738701-cb7bc010-e11c-47b4-a2e8-dcdddea5a4d7.png)

2. hidden header bar
![2](https://user-images.githubusercontent.com/76441520/135799277-b1bfe26c-3056-475d-af22-771d6201987b.png)

3. rotated pic and hidden header bar
![3](https://user-images.githubusercontent.com/76441520/135799312-829e71ab-2b69-4a0e-841e-28757906c5aa.png)

4. rotated pic and fullscreen, hidden header bar
![4](https://user-images.githubusercontent.com/76441520/135799358-14e30f5c-d84c-4208-940c-e4f9581ad066.png)

5.the maximized video player
![5](https://user-images.githubusercontent.com/76441520/135799407-06fa5452-17cc-4aa5-9c5e-81e7d41ef9ee.png)

6. music player
![6](https://user-images.githubusercontent.com/76441520/135799442-ce1799be-e053-4d2a-9c76-559179f34262.png)

7. fullscreen music player
![7](https://user-images.githubusercontent.com/76441520/135799468-47abf35d-a9ee-44d1-9921-f6825bbd709f.png)

8. curved thumbnails border
![8](https://user-images.githubusercontent.com/76441520/135799489-c85048cb-001a-44cd-9831-0215a7899aa4.png)

9. uploading rate
![9](https://user-images.githubusercontent.com/76441520/135799505-13c78475-281c-4627-adf9-6dbcca355eb8.png)

10. uploading rate
![10](https://user-images.githubusercontent.com/76441520/135738714-16d46eef-af8e-46c1-b22d-f338a70c48e3.png)

11. searchbox border
![11 search box](https://user-images.githubusercontent.com/76441520/135738716-98229b84-4ba0-468f-98b1-d9948223c39d.png)

12. searchbox border fixed
![12](https://user-images.githubusercontent.com/76441520/135738717-8c0f65e1-7201-4dc2-beb0-5dc4476f4885.png)

13.breadcrumb: out of the border
![13 breadcrumbs](https://user-images.githubusercontent.com/76441520/135738718-6ac96ae6-ed85-4d5e-9db1-945a7ba94494.png)

14. breadcrumb fixed
![14](https://user-images.githubusercontent.com/76441520/135738719-7147f266-9030-4023-b82e-dc87514169a0.png)

**Comment by ehsundar** [comment]
why dont you open a PR?

**Comment by mckaygerhard** [comment]
@niubility000 open a pull request use the git commands and developers tools to follow the contribution procedure please.. thanks in advance

**Comment by mckaygerhard** [comment]
in particular.. those are innecesary:

* curved particular borders ..
* rate upload
* full screen videos and music player (is a file admin not a youtube place)

**Comment by niubility000** [comment]
> why dont you open a PR?

I just changed so many things, and the codes maybe are not that efficient. It's just a demo, some professional guys may make it better.

**Comment by niubility000** [comment]
> @niubility000 open a pull request use the git commands and developers tools to follow the contribution procedure please.. thanks in advance

I know how to open a PA. I just don't know if other people like these changes or not. It changes so much.

**Comment by niubility000** [comment]
> in particular.. those are innecesary:
> 
> * curved particular borders ..
I think almost all the other projects curve this thumbnail's border. it looks good.
> * rate upload
It will make the upload process much obvious , the process bar is so thin to notice.  When you see the animation, it's pretty cool. 
> * full screen videos and music player (is a file admin not a youtube place)
Yes, I may change this to "loop" button for the video and music players.

**Comment by mckaygerhard** [comment]
> > why dont you open a PR?
> I just changed so many things, and the codes maybe are not that efficient. It's just a demo, some professional guys may make it better.

i understand you @niubility000  .. how about by a pull request with "open edit"? so others can work in your code .. and then  to be organized just use couple of commits with good descriptions.. 

of course you should title with "WIP:" prefix so

**Comment by niubility000** [comment]
> WIP



> > > why dont you open a PR?
> > > I just changed so many things, and the codes maybe are not that efficient. It's just a demo, some professional guys may make it better.
> 
> i understand you @niubility000 .. how about by a pull request with "open edit"? so others can work in your code .. and then to be organized just use couple of commits with good descriptions..
> 
> of course you should title with "WIP:" prefix so

Thank you. I will try the "open edit" thing when I got time. I haven't noticed that before. and I think I need pull requests one by one. Each request only has one change.

**Comment by mckaygerhard** [comment]
i already check that you already has one for upload progress, put a comment how to deuglyfy the mergecode @niubility000 also i asked the main mantainer to check the pull merge request of the repository
