### ISSUE TITLE
config log file output not imported or misinterpreted the -l flag

### ISSUE THREAD

**Issue by mckaygerhard** [filebrowser/filebrowser#1599]
### Discussed in https://github.com/filebrowser/filebrowser/discussions/1598

<div type='discussions-op-text'>

<sup>Originally posted by **mckaygerhard** October  5, 2021</sup>
i amd seraching for log to file.. i will not cited the OUT DATED documentation.. command line does not details:
`  -l, --log string                         log output (default "stdout")`

so the log only are standar output adn standar error, i can specify a file for? or i must use unix linux redirection 2&1 ??</div>

i try with relative path and absolute one.. and this does not work...

![imagen](https://user-images.githubusercontent.com/1571724/136257954-bd554466-8491-4873-8d93-28b7edf68e16.png)

and still redirects to stdout.. but still no file generated.. after several tryes.. i must to force by absolute path, works but still redirect to stdout.. 

i try to setup in config file and import/export and it do not take the configuration

````
root@sysanydesktop0:/srv# ./filebrowser config export ./filebrowser.json -d ./filebrowser.dbroot@sysanydesktop0:/srv# grep log ./filebrowser.json
        "log": "/srv/log.log",
root@sysanydesktop0:/srv# ls
CHANGELOG.md  filebrowser  filebrowser.db  filebrowser.json  LICENSE  linux-386-filebrowser.tar.gz  lo	README.md
root@sysanydesktop0:/srv#
```

i used the i386 build of last release, not last git!

**Comment by ramiresviana** [comment]
Cant reproduce this issue, the log option is working as expected on my tests. After displaying the message `No config file used` on the console, the output is written to the log file.

**Comment by mckaygerhard** [comment]
it seems the error messages is not output when log file is not writable or cannot be updated..
