### ISSUE TITLE
Multiple scopes per user

### ISSUE THREAD

**Issue by AxelRHD** [filebrowser/filebrowser#1600]
Is it possible to narrow the scope to **multiple** directories per user?

Example:

Users = A, B, C
Dirs = X,Y,Z

User A can enter X,Y,Z
User B can enter X,Z
User C can enter X

If not that would be a nice feature.

**Comment by o1egl** [comment]
No. User can have only 1 root dir. This feature is planned for v3 release

**Comment by c-nv-s** [comment]
> No. User can have only 1 root dir. This feature is planned for v3 release

is there a ticket for tracking this for v3? considering this ticket is closed

**Comment by o1egl** [comment]
No, there are no tickets for that

**Comment by mrjiaxuan** [comment]
i need this feature /(ㄒoㄒ)/~~

**Comment by be-engineer** [comment]
Everyone needs this feature.

**Comment by lmingzhi** [comment]
We can use `Rules` to disable users to see the folders.

![image](https://user-images.githubusercontent.com/25837153/184591293-22c54aec-7844-4cec-9090-4adb0e5590eb.png)

**Comment by inuonly** [comment]
still missing this feature in 2023.

**Comment by pituluk** [comment]
yeah, really could use it.

**Comment by cr08** [comment]
Seems like there's been no progress on this? Nothing in the documentation I can find and actually using the application there doesn't appear to be the option. This would be really nice to have. May have to start looking at alternative options. The suggestion above to use the Rules function is a nice workaround but I'd rather not risk something slipping through.
