### ISSUE TITLE
table header "size" "modified" is hidden in mobile view

### ISSUE THREAD

**Issue by MrSong0607** [filebrowser/filebrowser#1604]
**Description**
in mobile view,size and modified is hidden,if i want to sort by modified, there is no way to do that,cause table header is hidden too.

**Expected behaviour**
 give some button to sort file in mobile view

**Comment by MrSong0607** [comment]
```
@media (max-width: 736px)
#listing.list .item .size {
    display: none;
}
```
this css code control the view

**Comment by niubility000** [comment]
Yes, just change to this: (in the mobile.css file)
@media (max-width: 736px) {
  body {
    padding-bottom: 5em;
  }
  #listing.list .item .size {
  width: 35%;
  }

**Comment by shalva97** [comment]
Hi. Should not this be properly fixed? it's not good having to research this and then having to copy pase random code at random place

**Comment by ghnp5** [comment]
See this - https://github.com/filebrowser/filebrowser/issues/5976
