### ISSUE TITLE
filebrowser set config

### ISSUE THREAD

**Issue by morganzero** [filebrowser/filebrowser#1605]
**Description**
This is obviously not a bug. I'm trying to run some commands  when deploying filebrowser via docker-compose.
```
    command:
      - 'filebrowser set config --username ${MYUSER}'
      - 'filebrowser set config --password ${MYPASSWORD}'
      - 'filebrowser set config --branding.name "Morgan Zero"'
      - 'filebrowser set config --branding.files "/example/path/to/img/"'
      - 'filebrowser set config --branding.disableExternal'
      - 'filebrowser set config --branding.theme "Dark"'
```
**Expected behaviour**
I expected these commands to work as I got them from --help

**What is happening instead?**
I'm getting this error from logs
```
unknown command "filebrowser set config --username exampleusername" for "filebrowser"
```

What should I run to accomplish the idea?

**Comment by mckaygerhard** [comment]
this question must be moved to discussion, cos is not a bug and neither an issue.. 

the problem is that your `${MYUSER}`  is not set, i guess you shoul check by put some `echo ${MYUSER}` before the command to see the real value

also any `set config`  must be done with the currrnt configure db

you must have a real knowledge of linux abstraction of filesystem and environment to handle that

**Comment by alexishuxley** [comment]
The command is not 'set config'. The command is 'config set'.

**Comment by barocko-works** [comment]
> The command is not 'set config'. The command is 'config set'.

Thank you so much for clarifying. However, I still get the same error msg:
```2021/11/12 10:06:49 unknown command "filebrowser config set --username morganzero" for "filebrowser"```

**Comment by alexishuxley** [comment]
> Thank you so much for clarifying. However, I still get the same error msg:
> ```2021/11/12 10:06:49 unknown command "filebrowser config set --username morganzero" for "filebrowser"```

Can you show us the command you're typing, the output and the shell prompts
before and after - please just copy and paste it.

**Comment by barocko-works** [comment]
> Thank you so much for clarifying. However, I still get the same error msg: ```2021/11/12 10:06:49 unknown command "filebrowser config set --username morganzero" for "filebrowser"```
> Can you show us the command you're typing, the output and the shell prompts before and after - please just copy and 

Absolutely!

Command:
```
filebrowser config set --username morganzero --password REDACTED --branding.name "morganzero" --branding.files "/opt/filebrowser/img" --branding.disableExternal --branding.theme "Dark"
```
Output:
```
Run 'filebrowser --help' for usage.
2021/11/12 10:20:42 unknown command "filebrowser config set --username morganzero --password REDACTED --branding.name \"morganzero\" --branding.files \"/opt/filebrowser/img\" --branding.disableExternal --branding.theme \"Dark\"" for "filebrowser"
```

**Comment by alexishuxley** [comment]
> Absolutely!

like I said, can you paste in *including* shell prompts before and after please?

**Comment by ramiresviana** [comment]
The username and password parameters are not valid, check the documentation at https://filebrowser.org/cli/filebrowser-config-set

**Comment by luandro** [comment]
Tried with existing commands and doesn't work. This would be very useful.

**Comment by amg-web** [comment]
same to me.
I run filebrowser  as service with specific user and start service:
```
[Unit]
Description=FileBrowser instance
After=network.target

[Service]
User=myuser
Group=myuser

ExecStart=/usr/local/bin/filebrowser -d /var/lib/filebrowser/filebrowser.db -r /var/record/ -b /fb

[Install]
WantedBy=multi-user.target
```

after I enable and start service, and everything works, but I have manually change default admin password, via web page.
I tryed different commands but with with no luck to alter admin password.
eg this:
`sudo -H -u myuser bash -c 'filebrowser  -d /var/lib/filebrowser/filebrowser.db users add admin my_password'`
returned: 2021/11/16 07:58:43 timeout 
without actuall password change.
Can somebody explain what is wrong here?

**Comment by mckaygerhard** [comment]
after some test confirmed that only `--user` is valid but not `--password` are set.. in any way of the command line @ramiresviana and @alexishuxley 

i run sussessfully with `-u pepe` as default first admin but not using a default first password.. the filebroser command just ignored that parameter

**Comment by amg-web** [comment]
I'll reply to myself.
The problem was due to filebrowser service was running.
Everything is OK after I stopped it.

**Comment by mckaygerhard** [comment]
hey ping @github-actions this is valid issue seems its solved since https://github.com/filebrowser/filebrowser/issues/1605#issuecomment-983831150

**Comment by danilo-silva-funttastic** [comment]
`filebrowser config set --branding.theme "dark"`

works for me
