### ISSUE TITLE
Page won't load

### ISSUE THREAD

**Issue by TinyBabyOwl** [filebrowser/filebrowser#1606]
**Description**
I used the quick script to set up Filebrowser, set up a config file, and ran filebrowser with `filebrowser -c /path/to/my/config/config.json`. Filebrowser says it's listening on `127.0.0.1:8001` (the port I set in the config), but the page doesn't reach it when I visit myserverip:8001. The port is open for TCP traffic.

**Expected behaviour**
Page should load

**What is happening instead?**
Console doesn't give me any errors and sits at `Listening on 127.0.0.1:8001`.

**Additional context**
Ubuntu 20.04

**How to reproduce?**
`curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash`
`filebrowser config export /path/to/config/location/config.json`
[Set config options]
`filebrowser -c /path/to/config/locations/config.json`

**Comment by niubility000** [comment]
Here's what I am using for ubuntu18.04. And filebrowser is in /filebrowser folder.

chmod 755 /filebrowser

cd /filebrowser

chmod 755 filebrowser

./filebrowser -d filebrowser.db config init

./filebrowser -d filebrowser.db config set --address 0.0.0.0

./filebrowser -d filebrowser.db config set --port 1000

./filebrowser -d filebrowser.db users add aaa 1234 --perm.admin

./filebrowser -d filebrowser.db config set --root /

/filebrowser/filebrowser -d /filebrowser/filebrowser.db --disable-preview-resize --disable-type-detection-by-header  --cache-dir /filebrowser/cache


then just visit 192.168.x.x:1000
or www.yourdomain.com:1000

**Comment by niubility000** [comment]
I just think 127.0.0.1 doesn't work. You need set the address to 0.0.0.0

**Comment by TinyBabyOwl** [comment]
> 
> 
> I just think 127.0.0.1 doesn't work. You need set the address to 0.0.0.0

Well I actually got it up and running in docker, but I'll give it a try that way too to see if that's a working solution in case anyone else has this problem.

**Comment by TinyBabyOwl** [comment]
> 
> 
> I just think 127.0.0.1 doesn't work. You need set the address to 0.0.0.0

Yeah that did the trick, cheers.

**Comment by niubility000** [comment]
> > I just think 127.0.0.1 doesn't work. You need set the address to 0.0.0.0
> 
> Yeah that did the trick, cheers.



> > I just think 127.0.0.1 doesn't work. You need set the address to 0.0.0.0
> 
> Well I actually got it up and running in docker, but I'll give it a try that way too to see if that's a working solution in case anyone else has this problem.

I just wonder why you guys like to run it in docker? It's written in golang. It doesn't need any environment , and can be run directly easily in any platform.  Put the file 'filebrowser' in any folder in Ubuntu, and just run it. In this way, you will not confuse the root path of the docker and the real root path in Ubuntu.
