### ISSUE TITLE
Feature Request: Upload files via remote URL

### ISSUE THREAD

**Issue by TheHamkerCat** [filebrowser/filebrowser#1612]
**Is your feature request related to a problem? Please describe.**
I want to download files to my file server using a URL (filebrowser will download the file from the provided URL).

**Describe the solution you'd like**
Add another option in **Upload**, Upload via URL, instead of opening file chooser directly.

**Describe alternatives you've considered**
Currently, I have to ssh to my file server and then use wget to download the file via that URL.

**Comment by ramiresviana** [comment]
The command shell allows users to run commands in the FileBrowser interface. Adding wget to the user commands allows it to  download files into the server.

**Comment by TheHamkerCat** [comment]
> The command shell allows users to run commands in the FileBrowser interface. Adding wget to the user commands allows it to download files into the server.

But it would be great to have it with the "Upload file" button
