### ISSUE TITLE
Not able to delete the copy of my file in Sysman

### ISSUE THREAD

**Issue by Jenny8594ag** [filebrowser/filebrowser#1616]
**Description**
I am not able to delete the copy of my file. I created a file in Sysman Filebrowser by clicking on New File and after that I copied the file.  

**Expected behaviour**
I expected the copy to be deleted

**What is happening instead?**
I get the error "404 Page not found"

**Additional context**

**How to reproduce?**
1. Create a New file in the file browser in Sysman.
2. Copy the file by clicking up in the right corner in Sysman
3. delete both files by clicking on the trash bon up in the corner at the same time

**Files**

![image](https://user-images.githubusercontent.com/92437452/137119815-f9bea2cd-2709-4816-97e4-39377b8a6d00.png)

**Comment by ramiresviana** [comment]
We need more details to reproduce the issue, please provide server environment info, configuration and logs.
