### ISSUE TITLE
Cannot download files / Permissions not working?

### ISSUE THREAD

**Issue by cetm-rj** [filebrowser/filebrowser#1619]
**Description**
If I press the download button it only opens a webpage returning "202 Accepted"

**Expected behaviour**
The file should be downloaded.

**What is happening instead?**
Not downloading anything, just printing "202 Accepted"

**Additional context**
Filebrowser is running as a docker container. Access through a reverse proxy (nginx docker). 
I think the "permissions" set in the filebrowser.json are not working (?)

**How to reproduce?**

**Files**
filebrowser.json : 
`{
  "port": 80,
  "baseURL": "files.xyz.com",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
  "perm": {
    "create": true,
    "execute": false,
    "modify": true,
    "download": true,
    "share": true,
    "delete": true,
    "rename": true,
    "admin": true
  },
  "auth": {
    "method": "none"
}`

**Comment by o1egl** [comment]
We need application logs so we can help you

**Comment by cetm-rj** [comment]
The docker container log only shows this: 

> 2021/10/14 08:39:09 Using config file: /.filebrowser.json

> 2021/10/14 08:39:09 Listening on [::]:80

Is there any other log I can provide?

**Comment by o1egl** [comment]
Try to use it directly. There might be an issue with your nginx config
