### ISSUE TITLE
Hugo plugin after save commands blocked

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#162]
I am trying to get a preview site published after any content is saved. Using the following After Save commands:
```
rm -r /hugo/simonchurch/preview/
hugo -D -E -F -d /hugo/simonchurch/preview -b https://simonchurch.preview.astondavies.co.uk --canonifyURLs --cleanDestinationDir
```
The following is logged by Caddy:
```
2017/07/27 13:09:12 [INFO] Blocking Command:"rm -r /hugo/simonchurch/preview/"
2017/07/27 13:09:12 [INFO] Blocking Command:"hugo -D -E -F -d /hugo/simonchurch/preview -b https://simonchurch.preview.astondavies.co.uk --canonifyURLs --cleanDestinationDir"
```

I have the commands setup for the user:
![image](https://user-images.githubusercontent.com/24296735/28669830-d04782c8-72cd-11e7-81fb-a12de14370a8.png)

**Comment by hacdias** [comment]
Hello! What's the problem? Blocking Command is meant to indicate that the command is running in a synced way. Or it doesn't work?

**Comment by AstonDavies** [comment]
Ah I see, the command is not blocked it is a blocking command!

It does not work though. I get:
![image](https://user-images.githubusercontent.com/24296735/28673899-b9a1306a-72db-11e7-8bc9-d745694202ac.png)
I assume that is a hugo exit code.

If I run that command on the server it works:
```
deploy@aston:/hugo/simonchurch$ hugo -D -E -F -d /hugo/simonchurch/preview -b https://simonchurch.preview.astondavies.co.uk --canonifyURLs --cleanDestinationDir
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
14 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 17 ms
```

**Comment by hacdias** [comment]
Could you try setting the path of the files on the Hugo command and see if you still get the error?

**Comment by AstonDavies** [comment]
Do you mean the contentDir (-c, --contentDir string) ?

**Comment by AstonDavies** [comment]
With -c specified as /hugo/simonchurch/content it works:
```
deploy@aston:/hugo/simonchurch$ hugo -c /hugo/simonchurch/content -D -E -F -d /hugo/simonchurch/preview -b https://simonchurch.preview.astondavies.co.uk --canonifyURLs --cleanDestinationDir
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
14 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 17 ms
```
Missing the leading slash makes it fail:
```
deploy@aston:/hugo/simonchurch$ hugo -c hugo/simonchurch/content -D -E -F -d /hugo/simonchurch/preview -b https://simonchurch.preview.astondavies.co.uk --canonifyURLs --cleanDestinationDir
Started building sites ...
Error: Error building site: No source directory found, expecting to find it at /hugo/simonchurch/hugo/simonchurch/content
```

**Comment by hacdias** [comment]
The commands from after_save, before_save and so on are executed with no specific working directory. That's why the command was failing and you needed to specify the directory.

I don't know if I should set the working directory for the default scope or the user's scope. Why? Because each user can have its own different scope so the commands which depend on a working directory would fail.

What are your thoughts on this?

**Comment by AstonDavies** [comment]
It all works if I specify the source (-s , --source) as /hugo/simonchurch, I can then use relative paths in the command:
```
hugo -s /hugo/simonchurch -D -E -F -d preview -b https://simonchurch.preview.astondavies.co.uk --canonifyURLs --cleanDestinationDir
```
I think setting a working directory as the Hugo root would be a good convention. Using command options you could then override this for specific users or even have a parameter (like the file variable) that is the current users scope which could be substituted as required.

Thanks for all your great efforts. I really like the new interface and user login features.

**Comment by hacdias** [comment]
I'll close this issue. I decided not to change the working directory of the command - so you will need to specify the source - because this would not be very correct from the File Manager's point. If someone wants to execute the command in a specific path, he just needs to do something like:

```
bash -c "cd /path/to/files && mycommand"
```

Hope there's no problem with this.
