### ISSUE TITLE
Security Issue (Vulnerability details and report are not disclosed here)

### ISSUE THREAD

**Issue by febinrev** [filebrowser/filebrowser#1621]
Hi, this is Febin, an Independent security researcher. I have found a critical vulnerability in filebrowser.

I reported the vulnerability to filebrowser@googlegroups.com from [SECURITY.md](https://github.com/filebrowser/filebrowser/blob/master/SECURITY.md).

I also reported a private report on the issue via huntr.dev.

Link to the Private Report: [https://huntr.dev/bounties/afd97e53-aa82-40e5-bb7c-8d1fe9c118eb](https://huntr.dev/bounties/afd97e53-aa82-40e5-bb7c-8d1fe9c118eb)

Thanks.

**Comment by o1egl** [comment]
Thank you for your report. It will be reviewed as soon as possible

**Comment by MrSuicideParrot** [comment]
I also sent you an email, and no one answer me... Could you also check my emails? I sent you two mails about the same vulnerability day 1 and 12  of this month. If I don't received any answer from you until first of November, my plan is to publish the write-up.

**Comment by febinrev** [comment]
Please close the issue on hunter.dev.

[https://huntr.dev/bounties/afd97e53-aa82-40e5-bb7c-8d1fe9c118eb](https://huntr.dev/bounties/afd97e53-aa82-40e5-bb7c-8d1fe9c118eb)

Thanks in advance.
