### ISSUE TITLE
login sessions

### ISSUE THREAD

**Issue by anish9991** [filebrowser/filebrowser#1624]
The login sessions are persistent for a long time.

How can I,  end the session once the browser tab/window is closed.

Can this be achieved by browser settings or is it possible to manage it in file browser config setup or any settings.

**Comment by ehsundar** [comment]
You can simply logout!

**Comment by o1egl** [comment]
There is no such config param

**Comment by anish9991** [comment]
> 
> 
> You can simply logout!

Like if someone forgets to, or may be a long copying is in progress, and the system is not private, is unattended,  accessible and authorized for others too.

**Comment by o1egl** [comment]
This is something we can add in v3. Added to my notes

**Comment by anish9991** [comment]
> 
> 
> This is something we can add in v3. Added to my notes

That would be great support
