### ISSUE TITLE
Generate warning when closing modified text file

### ISSUE THREAD

**Issue by bluesky-ca** [filebrowser/filebrowser#1625]
**Description**

When using the built-in text editor, when closing using the X button either allow the user to save the file or quit without saving.
**Expected behaviour**

Receive a prompt with an option to save or cancel.
**What is happening instead?**

The changes to the file are lost.
**Additional context**

**How to reproduce?**

**Files**

**Comment by niubility000** [comment]
That's easy to do if use default confirm.

**Comment by bluesky-ca** [comment]
I looked at the settings and ./filebrowser -h - don't see any reference to default confirm - I am running ver. 2.17.2 - can you be more specific where to set that - if it is documented please point to the docs.

**Comment by o1egl** [comment]
This feature is not available in filebrowser. I think @niubility000 wanted to say that it is easy to implement using a standard browser prompt
