### ISSUE TITLE
Updater Script

### ISSUE THREAD

**Issue by kylejfrost** [filebrowser/filebrowser#163]
I just wanted to pass along a Bash script I wrote that I'm using to update the filemanager executable (I don't use Caddy, I do manual install). I call it an updater, but it will also download it to the current directory if it isn't installed already. Just in case anyone else wanted to use it.

https://gist.github.com/kylefrost/861c83138f473240c6956044bb16e4ef#file-update-filemanager-sh

**Comment by hacdias** [comment]
That's a pretty nice script! I'll make you a challenge: if you make an installer script like [this](https://getcaddy.com/), I may get it published on `hacdias.github.io/filemanager/get.sh` or something. Accept the idea? 😄 (Don't depend on Python though)

**Comment by kylejfrost** [comment]
Check out #169 :smile:

**Comment by hacdias** [comment]
Awesome dude!
I'm working on a simple, small, website and this will absolutely be there 😄

**Comment by hacdias** [comment]
[Check This](https://henriquedias.com/filemanager/getting-started/#installation-script) 😄 
The website isn't finished yet, btw. If you have any suggestions, just ping me.
