### ISSUE TITLE
Filebrowser Documentation is not very clear

### ISSUE THREAD

**Issue by obvionaoe** [filebrowser/filebrowser#1630]
Hi, is filebrowser able to use PostgreSQL instead of a .db file?

And is there any place where all the environment variables are listed? The documentation seems to completely miss this point

Thanks

**Comment by ramiresviana** [comment]
The supported options are documented at https://filebrowser.org/cli/filebrowser#options.

**Comment by obvionaoe** [comment]
Thanks, I did miss that! I thought those options would be in the configuration section... 
The descriptions are quite vague though, what is the purpose of `baseURL` and `address`, for example?

**Comment by mckaygerhard** [comment]
this is a question not an issue please move this and covert the issue to discussion using the github tool @ramiresviana  @o1egl (if this operation is too complicated please designate a person with time to do)

**Comment by obvionaoe** [comment]
well, okay looks like I won't be using filebrowser then
