### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by jadsongmatos** [filebrowser/filebrowser#1636]
there is this project for nextcloud very cool, I think it would be interesting to have something like this.

![image](https://raw.githubusercontent.com/nextcloud/files_rightclick/master/screenshots/picture.png)

[https://apps.nextcloud.com/apps/files_rightclick](https://apps.nextcloud.com/apps/files_rightclick)

**Comment by o1egl** [comment]
duplicate of https://github.com/filebrowser/filebrowser/discussions/1031

**Comment by jadsongmatos** [comment]
thanks
