### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by isaacteoh25** [filebrowser/filebrowser#1638]
**Description**
Upload successfully the pb file to server

**Expected behaviour**
Upload successfully the pb file to server

**What is happening instead?**
500 Internal Server Error when uploading the pb file

**Additional context**

**How to reproduce?**
after uploading one pb file successfully, we move in on to upload another one and it result with error. Sometimes when uploading if you move to another folder concurrently from same server page

**Files**

**Comment by o1egl** [comment]
We need server/browser logs to be able to analyze the issue
