### ISSUE TITLE
Only the first command in the list is available

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#164]
With the commands set as:
![image](https://user-images.githubusercontent.com/24296735/28679050-e8edaef8-72e9-11e7-8982-b7cf1eb12601.png)
only the first one is available to the user:
![image](https://user-images.githubusercontent.com/24296735/28679093-09c8471e-72ea-11e7-835b-535c32c11abe.png)
![image](https://user-images.githubusercontent.com/24296735/28679108-152a287a-72ea-11e7-9cd4-2a9f9c24a11a.png)
![image](https://user-images.githubusercontent.com/24296735/28679130-2778566e-72ea-11e7-8d4e-4a3dfc2e471c.png)

**Comment by hacdias** [comment]
I mentioned this: https://github.com/hacdias/filemanager/issues/161#issuecomment-318354035 😄

**Comment by AstonDavies** [comment]
DOH! apologies

**Comment by hacdias** [comment]
NP!
