### ISSUE TITLE
feat: ability to upload files with web share target

### ISSUE THREAD

**Issue by decaby7e** [filebrowser/filebrowser#1646]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Ability to upload files using a share menu in Android and iOS.

**Describe alternatives you've considered**

Opening the app in a PWA/browser and uploading files with the upload button. This is less than ideal because sometimes sharing from the context with the information in it is more useful than exiting said app, opening Filebrowser, and uploading the file.

**Additional context**

There is some good documentation [here](https://web.dev/web-share-target/) and I would be willing to help with this feature request.

**Comment by CALPARDO** [comment]
No progress on that feature?
