### ISSUE TITLE
filebrowser config export or filebrowser config cat always timeout

### ISSUE THREAD

**Issue by helmut72** [filebrowser/filebrowser#1647]
**Description**
I want to export or cat the configuration from filebrowser running in a docker container. But it always timeout.

**Expected behaviour**
export or cat the configuration

**What is happening instead?**
just shows a timeout

**How to reproduce?**

```
docker exec -it filebrowser /filebrowser config cat -c /.filebrowser.json -d /database.db`
```

or

```
docker exec -it filebrowser /filebrowser ash
/filebrowser config cat -c /.filebrowser.json -d /database.db
```

Both files are exists, .filebrowser.json and database.db

**Comment by o1egl** [comment]
It it happening because filebrowser service locks the database file. The workaround is to copy the db file and then run cli using the `-d` flag.

**Comment by helmut72** [comment]
Works, thanks for the info!

**Comment by doing-cr7** [comment]
/ # ./filebrowser config set --auth.method=proxy --auth.header=X-My-Header -d /filebrowser.db
2022/01/11 09:39:11 timeout

**Comment by laker-93** [comment]
> It it happening because filebrowser service locks the database file. The workaround is to copy the db file and then run cli using the `-d` flag.

Can you please be a bit more specific about this work around?
Say we have a docker container running that uses the database `/config/filebrowser.db` and we run the following command:

`docker exec -it filebrowser /filebrowser users ls -d /config/filebrowser.db`

If this command timesout then what is the work around?
I've tried copying the db on the host but it still timesout.

**Comment by laker-93** [comment]
> It it happening because filebrowser service locks the database file. The workaround is to copy the db file and then run cli using the `-d` flag.

Presumably you're implying we should copy the db on the container, then run the command against the copied db and then finally overwrite the first db with the copied db?

Do you know why filebrowser would be holding an open connection to the bolt db? I see this issue occur occasionally with only a single logged out admin account when no files are being uploaded. In such a case I would expect no open connections to the bolt db and therefore for the timeout issue to not occur. I think the proper solution here would be to ensure open db connections are properly closed and to possibly increase the timeout value for an operation that writes to the db, to give it more of a chance to succeed.

**Comment by meminens** [comment]
> It it happening because filebrowser service locks the database file. The workaround is to copy the db file and then run cli using the `-d` flag.

Obviously this is from two years ago but this workaround does not work today.

**Comment by koriwi** [comment]
this workaround still works. duplicate the file, act on it with `-d` and then replace the old one

**Comment by meminens** [comment]
Can you share exact steps and commands to run please? I am stuck here.

**Comment by st0rm3rd** [comment]
I’d like to know the exact steps too. What is meant act on it with -d? I cannot get inside the container as it is not starting as it says following when trying to start up:
Using database: /database.db
2024/04/11 13:27:35 timeout

**Comment by laker-93** [comment]
The workaround I use is as follows:

```
        docker cp <filebrowser_container> /config/filebrowser.db /config/filebrowser.db.bak
        docker cp <filebrowser_container> /config/filebrowser.db.bak /config/filebrowser.db
        docker rm <filebrowser_container> /config/filebrowser.db.bak
```

This should be enough to clear the lock from the database.
You should then be able to execute your command:

```
docker exec <filebrowser_container> /filebrowser users add foo bar --database /config/filebrowser.db
```

**Comment by St0rm3rt** [comment]
Thanks for your response. However when reverting back to previous version everything was resolved. I think there's an issue with V2.28.0
