### ISSUE TITLE
Unzip & Unarchive Support

### ISSUE THREAD

**Issue by viperadnan-git** [filebrowser/filebrowser#1648]
**Is your feature request related to a problem? Please describe.**

There are many files which is compressed or archived. I want to share some file from them. I have to open terminal and unzip files manually before sharing them. It would be great if we can unzip by web interface.

**Describe the solution you'd like**

Add a Unarchive or Unzip option for most of the formats we can. 

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/discussions/1585

**Comment by gingerbeardman** [comment]
How to enable it is now at https://github.com/filebrowser/filebrowser/discussions/1585#discussioncomment-2524818
