### ISSUE TITLE
Filemanager causes a panic when built along with all the middlewares for Caddy

### ISSUE THREAD

**Issue by Flameborn** [filebrowser/filebrowser#165]
When Caddy is built with all the Middlewares, Filemanager included, upon running it, Go.Rice panics with the following:

EmbeddedBox with name `./assets/dist` exists already

My guess is that this might happen due to https://github.com/hacdias/caddy-hugo embedding the same or similar assets or asset names.

**Comment by hacdias** [comment]
Oh, I guess it would happen when building Hugo and FileManager together. I'll try to find out why.

**Comment by hacdias** [comment]
I just downloaded from Caddyserver a file with both Hugo and File Manager and I haven't got any errors. Did you build it manually?

**Comment by Flameborn** [comment]
Yes, I cloned the latest version of Caddy from the master branch, imported every middleware in 'run.go' and I get the panic after 'go build'.

**Comment by hacdias** [comment]
I'm not being able to reproduce this 😞

**Comment by hacdias** [comment]
Can you show me your imports, please?

**Comment by Flameborn** [comment]
Here are the steps I’ve done:

1. Clone Caddy from Github.

2. add all the imports from ‘plugin.go’ in ‘run.go’

3. Run go build in the Caddy directory, where build.bash is.

Here are my imports, below the comment (// This is where other plugins get plugged in (imported)):

	_ "blitznote.com/src/caddy.upload"

	_ "github.com/BTBurke/caddy-jwt"

	_ "github.com/SchumacherFM/mailout"

	_ "github.com/Xumeiquer/nobots"

	_ "github.com/abiosoft/caddy-git"

	_ "github.com/captncraig/caddy-realip"

	_ "github.com/captncraig/cors/caddy"

	_ "github.com/casbin/caddy-authz"

	_ "github.com/coopernurse/caddy-awslambda"

	_ "github.com/echocat/caddy-filter"

	_ "github.com/epicagency/caddy-expires"

	_ "github.com/freman/caddy-reauth"

	_ "github.com/hacdias/caddy-hugo"

	_ "github.com/hacdias/caddy-minify"

	_ "github.com/hacdias/caddy-webdav"

	_ "github.com/hacdias/filemanager"

	_ "github.com/jung-kurt/caddy-cgi"

	_ "github.com/mastercactapus/caddy-proxyprotocol"

	_ "github.com/miekg/caddy-prometheus"

	_ "github.com/namsral/multipass/caddy"

	_ "github.com/nicolasazrak/caddy-cache"

	_ "github.com/payintech/caddy-datadog"

	_ "github.com/pedronasser/caddy-search"

	_ "github.com/pieterlouw/caddy-grpc"

	_ "github.com/pschlump/caddy-jsonp"

	_ "github.com/pyed/ipfilter"

	_ "github.com/restic/caddy"

	_ "github.com/simia-tech/caddy-locale"

	_ "github.com/tarent/loginsrv/caddy"

	_ "github.com/xuqingfeng/caddy-rate-limit"

	_ "github.com/zikes/gopkg"

**Comment by hacdias** [comment]
Replace my section, from:

```
_ "github.com/hacdias/caddy-hugo"
_ "github.com/hacdias/caddy-minify"
_ "github.com/hacdias/caddy-webdav"
_ "github.com/hacdias/filemanager"
```

to

```
_ "github.com/hacdias/caddy-minify"
_ "github.com/hacdias/caddy-webdav"
_ "github.com/hacdias/filemanager/caddy/filemanager"
_ "github.com/hacdias/filemanager/caddy/hugo"
```

And try again. The repositories have changed. That's probably it.

**Comment by Flameborn** [comment]
This did the trick, thank you! 😌 Hopefully this will be updated in the Caddy source for the next release.
I'm sorry for the inconvenience!

**Comment by hacdias** [comment]
No problem 😄
