### ISSUE TITLE
[Feature Request] Static Paths with permanence

### ISSUE THREAD

**Issue by deathbybandaid** [filebrowser/filebrowser#1655]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Maybe a different than intended usecase for filebrowser, but the reason I installed it was to make a `/assets/` root path to store things that I use by other web applications (images, text, etc).

What I'd like is a way to create a folder that I can share permanently, and set a custom path.

**Comment by deathbybandaid** [comment]
I did discover that setting 9999999999999999 (16 9s) days is equals "in 219 years",

BUT setting 99999999999999999 (17 9s) equals "153 years ago",

BUT setting 999999999999999999 (18 9s) equals "in 222 years",

Setting 19+ 9s yields a red box that says "500".

I think for a temporary solution, I can set 222 years, and use nginx to proxy-rewrite a path

**Comment by ramiresviana** [comment]
A permanent share is created when the duration field is left blank.

**Comment by kakadais** [comment]
This issue is not cleared because the permanent duration is possible but the static path is not allowed.
Does any feature has been considered for this 'Static Custom Path' for sharing?
