### ISSUE TITLE
Search in file content 

### ISSUE THREAD

**Issue by laurentvergnaud** [filebrowser/filebrowser#1657]
We use filebrowser to edit live WordPress sites files. We often have to look for a specific function or variable in the code and we can't do that with the current search feature.

It would be great if the search would take into account the content of the files. 
Having VS Code like search results with the list of results and the extract of the lines where the search term is used would be ideal.

PS: thank you for this great tool :-)

**Comment by niubility000** [comment]
Do you mean you wanna search in all the file contents in the listing page? including the current folder and sub folders? That may be a heavy job.

**Comment by laurentvergnaud** [comment]
Yes indeed. All the files of the current folder and subfolders.
It might be heavy depending on the number of files indeed but the feature
is really needed if we want to be able to use FileBrowser as a coding tool.
It might not be the main use case though.


Le mer. 10 nov. 2021 à 02:53, niubility000 ***@***.***> a
écrit :

**Comment by Juszoe** [comment]
I think you would like to use [code server](https://github.com/cdr/code-server) in your case.

**Comment by laurentvergnaud** [comment]
The problem is that it requires lots of resources (1GB ram \ 2CPU).
We are looking for a modern (lots of unmaintained cloud IDE out there)
lightweight alternative and file browser is the best option we found.
Would you be open to this kind of features or would you recommend us to
fork the project eventually ?

**Comment by mdraevich** [comment]
Hi!

First of all, wonderful tool that I'm actually looking for. Thank you, guys!

However the search speed is quiet low.
I've some experience in building file browser with instant typing search using nginx autoindex + meilisearch + apache tika. That works very nice on 117.000 files which have been indexed. 
Why not to do the same in your project? You have wonderful UI for managing files and the last thing you have to implement -- it's a quick search!

Here's how it looks like:
![image](https://user-images.githubusercontent.com/34220689/160022930-e509d86d-1fe9-4b20-b187-0f066ab7ea99.png)

**Comment by silijon** [comment]
Having a pluggable search would be great. If you could docker compose a stack with filebrowser pointing at elasticsearch and indexing with something like this: https://github.com/dadoonet/fscrawler it'd be incredible.
