### ISSUE TITLE
Use images instead of fonts for the icons

### ISSUE THREAD

**Issue by DUOLabs333** [filebrowser/filebrowser#1668]
**Is your feature request related to a problem? Please describe.**
I force the same font for all websites for usability purposes, and that obviously makes this unusable.

**Describe the solution you'd like**
Instead of using text icons, maybe use images

**Describe alternatives you've considered**
You can use Unicode for some of them

**Additional context**

**Comment by o1egl** [comment]
We don't plan to use images. It will slow down the frontend. You can create custom CSS styles and override the default theme https://filebrowser.org/configuration/custom-branding
