### ISSUE TITLE
Optional Disable Ram Cache

### ISSUE THREAD

**Issue by nevetS-718** [filebrowser/filebrowser#1671]
**Is your feature request related to a problem? Please describe.**

I am trying to share a very large file (19 gigs) and I noticed that my Filebrowser container is using 20 gigs of RAM. I am using a very fast NVME SSD for my storage, so not caching the file wouldn't be too degrading to performance. Is there a way to disable this RAM cache or could a solution be implemented?

**Describe the solution you'd like**

A disable RAM cache flag or config option

**Describe alternatives you've considered**

Upgrading the system and adding more memory?

**Additional context**

![memusage](https://user-images.githubusercontent.com/70534545/142084771-dfaca89a-3535-4dd7-a9a2-870438484189.png)

**Comment by nevetS-718** [comment]
One thing I forgot to mention is that after 5-10 minutes, it didn't garbage collect either, so I ended up having to manually restart it.

**Comment by o1egl** [comment]
What is the file ext?

**Comment by nevetS-718** [comment]
That file was a iso, but it was also happening when trying to download a large folder as a zip file

**Comment by o1egl** [comment]
Can't reproduce it on the latest version. @nevetS-718 Can you confirm it?

**Comment by stignarnia** [comment]
I have the same problem, I have several GB large video files and no problem, but as soon as I navigate to a folder with an 800MB image it starts using more that 6GB of RAM. I really don't understand how it can fill up so much more than even the total content of the folder

**Comment by mikicvi** [comment]
I can confirm, garbage collection does not seem to work at all. Tested with multiple image and video files with different extension formats. 2 hours later, the ram is still sitting occupied {around 2GB in my case, would go higher if I was to load more files}.

Tested on Docker 23.0.5 running on Ubuntu 22.04 LTS.
