### ISSUE TITLE
backend go build issue

### ISSUE THREAD

**Issue by derekshao1225** [filebrowser/filebrowser#1672]
I followed the tutorial to build frontend successfully and then move to backend, but I get the error when go build this project:

build github.com/filebrowser/filebrowser/v2: cannot load embed: cannot find module providing package embed

I have go mod download before I run go build, how can I fix that? Thanks

**Comment by ramiresviana** [comment]
Building the Filebrowser backend requires go v1.16

**Comment by niubility000** [comment]
> I followed the tutorial to build frontend successfully and then move to backend, but I get the error when go build this project:
> 
> build github.com/filebrowser/filebrowser/v2: cannot load embed: cannot find module providing package embed
> 
> I have go mod download before I run go build, how can I fix that? Thanks

Have you figured it out? If not, I can tell you my method. I use windows PC to compile filebrowser. Just install docker, and then Ubuntu, and then setup nodejs, npm, go environments. Actually I have written a doc about it, but it's in Chinese.

**Comment by derekshao1225** [comment]
I checked it out, the go version is go1.13.4 darwin/amd64 on my M1 mac. I will try to rebuild in cloud to see if it works. Thank you for your tips bro!

**Comment by niubility000** [comment]
> I checked it out, the go version is go1.13.4 darwin/amd64 on my M1 mac. I will try to rebuild in cloud to see if it works. Thank you for your tips bro!

Here's my version: https://gitee.com/niubilitypdj/filebrowser/releases
