### ISSUE TITLE
Black background in pdf viewer on iOS

### ISSUE THREAD

**Issue by gerry-momo** [filebrowser/filebrowser#1673]
Normal on mac
![WX20211119-234108](https://user-images.githubusercontent.com/73962678/142650749-8c874278-5d80-4dfe-8ddc-8b6a78147c84.png)

![WX20211119-234123](https://user-images.githubusercontent.com/73962678/142650922-445dc1b6-7908-4c4a-b0a0-46791cb192fe.png)

but black background on ios (dark model and light model)
![IMG_4742](https://user-images.githubusercontent.com/73962678/142650836-cdc19ce7-12d8-4436-8cdb-92ec982f04cc.jpg)

![IMG_4743](https://user-images.githubusercontent.com/73962678/142650902-c4f6c602-64bb-442c-a0ec-616b6fa34e6a.PNG)

can not read the word

**Comment by o1egl** [comment]
Similar to the https://github.com/filebrowser/filebrowser/issues/1201#issuecomment-756069487

**Comment by mckaygerhard** [comment]
duplication of #1201 must be closed as duplicate, but still there's any repónse.. for
