### ISSUE TITLE
Toggle full-text search

### ISSUE THREAD

**Issue by DUOLabs333** [filebrowser/filebrowser#1678]
**Is your feature request related to a problem? Please describe.**
When I'm searching for a file, it also searches the text of the files when I don't want it to.

**Describe the solution you'd like**
There should be a way of toggling whether to search inside files or not.

**Describe alternatives you've considered**

**Additional context**

**Comment by o1egl** [comment]
Filebrowser doesn't use file content in the search

**Comment by DUOLabs333** [comment]
Oh, then it must be that filebrowser searches recursively through all child folders of a directory, rather on just the top-level. Is there a way to turn that off?

**Comment by o1egl** [comment]
No there is no way to prevent this behavior
