### ISSUE TITLE
When can I support multilingual switching?

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#168]
When can I support multilingual switching?
Or users to write their own language files.

**Comment by hacdias** [comment]
You mean the interface in other languages?

**Comment by ghost** [comment]
@hacdias Yes.

**Comment by hacdias** [comment]
I'll see what I can do, but then I will need people to do the translations.

**Comment by ghost** [comment]
@hacdias I believe that as long as you can provide a language file help documentation and examples, there will naturally be some people making language files.
Multi-language support, will make more people fall in love with filemanager! :>

**Comment by hacdias** [comment]
I'll work on this 😄

**Comment by hacdias** [comment]
I'm implementing this on [i18n branch](https://github.com/hacdias/filemanager/tree/i18n). As soon as I have a translation file ready to be translated in other languages, I'll let you know.

**Comment by ghost** [comment]
OK! Hope language translation document production process is very simple~

**Comment by hacdias** [comment]
@ToyoDAdoubi see [this file for example](https://github.com/hacdias/filemanager/blob/i18n/assets/src/i18n/en.yaml). You only will need to create another for your language with the translations.

I'll also create a Portuguese translation since... hmm... I'm Portuguese 😆

**Comment by ghost** [comment]
@hacdias 
I made a simplified Chinese language file [zh_cn.yaml].
Because I am not professional, while some options do not know the specific role, so part of the translation content may not be standard, the future will gradually improve ~
But I'm new to Github, I do not know how to add files to your project ...
(https://github.com/ToyoDAdoubi/filemanager/blob/i18n/assets/src/i18n/zh_cn.yaml)
——————
In my here, already 2:10 am, I went to the rest ~ ~

**Comment by hacdias** [comment]
Thank you 😄 I just merged it. Although, it will not be available for download right now. It will probably be out when 1.0.3 is released. There are still some corners to polish.

**Comment by hacdias** [comment]
The translation file is not complete yet. I'll add some more phrases and will tell you afterwards to  add the, okay?

**Comment by hacdias** [comment]
Just made some additions: https://github.com/hacdias/filemanager/commit/bb8f7d0958f3316226c08661ac987edc4fff33c3#diff-fe6ccd8f0bf41f00b9ff5d61b8e0e3e9

**Comment by ghost** [comment]
@hacdias https://github.com/hacdias/filemanager/pull/182
Has been updated to the latest language file~

**Comment by hacdias** [comment]
Hello @ToyoDAdoubi 😄 How's everything?
I just made some changes to the [language file](https://github.com/hacdias/filemanager/blob/master/assets/src/i18n/en.yaml). I removed and added some new things to translate. The removed ones were also removed from the Chinese file!

**Comment by ghost** [comment]
@hacdias After comparison found that only a few of the new content, there is no missing what?
```
 language: Language
 settingsUpdated: Settings updated!
languages:
  en: English
  pt: Portuguese
  zhCN: Chinese (Simplified)
```
https://github.com/hacdias/filemanager/pull/185

**Comment by hacdias** [comment]
I think those are the only ones, yes. :)

**Comment by hacdias** [comment]
So, you can already download the newest version (1.1.0) from Caddy or from the releases page and it will come with the language option 😄

**Comment by hacdias** [comment]
I really thank all of your work translating this 😃

**Comment by ghost** [comment]
@hacdias I also want filemanager better, more people like to use it! :rofl: :
