### ISSUE TITLE
Javascript TypeError on shared folder page

### ISSUE THREAD

**Issue by C0ntroller** [filebrowser/filebrowser#1683]
**Description**
When anonymously visiting a link to download or view a shared folder files from that folder will not be shown.

**Expected behaviour**
Files from folder will be shown.

**What is happening instead?**
No files are shown, console log is 
```
TypeError: Cannot read properties of null (reading 'dateFormat')
```

**Additional context**
It is maybe fixable by changing `this.user.dateFormat` to `this.user?.dateFormat` in [this line](https://github.com/filebrowser/filebrowser/blob/master/frontend/src/components/files/ListingItem.vue#L109) but I currently have no way to test this fix.

**How to reproduce?**
Create a link to share a folder and visit it in incognito mode or while logged out.

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/pull/1662
