### ISSUE TITLE
Get errow when send file

### ISSUE THREAD

**Issue by doragoma** [filebrowser/filebrowser#1684]
**Description**

When i send a file. i get error.
file -> https://xgf.nu/ewZX
Its file is .zip but when i get error file type is folder. not zip

**Expected behaviour**

i want to succes for send file

**What is happening instead?**

wss://saba2.azisaba.net/api/command/?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNywibG9jYWxlIjoiamEiLCJ2aWV3TW9kZSI6Im1vc2FpYyIsInNpbmdsZUNsaWNrIjpmYWxzZSwicGVybSI6eyJhZG1pbiI6ZmFsc2UsImV4ZWN1dGUiOnRydWUsImNyZWF0ZSI6dHJ1ZSwicmVuYW1lIjp0cnVlLCJtb2RpZnkiOnRydWUsImRlbGV0ZSI6dHJ1ZSwic2hhcmUiOmZhbHNlLCJkb3dubG9hZCI6dHJ1ZX0sImNvbW1hbmRzIjpbXSwibG9ja1Bhc3N3b3JkIjp0cnVlLCJoaWRlRG90ZmlsZXMiOmZhbHNlfSwiZXhwIjoxNjM3Nzc0MDI3LCJpYXQiOjE2Mzc3NjY4MjcsImlzcyI6IkZpbGUgQnJvd3NlciJ9.YlXs-MLtuMx1kCmr6yzqwVrQsyvQV-wxb2eNwjrQAzE のサーバーへの接続を確立できませんでした。 commands.js:12:13

**How to reproduce?**

please use this file https://xgf.nu/ewZX and send not .zip file.
download -> unfreeze -> send

**Files**
 https://xgf.nu/ewZX

**Comment by o1egl** [comment]
We need server/client error logs to be able to analyze the error
