### ISSUE TITLE
Authentification with sha512 ($6$) hashes not possible ?

### ISSUE THREAD

**Issue by rapesco** [filebrowser/filebrowser#1685]
**Description**
I'm trying to use sha512 encrypted password from /etc/shadow within filebrowser configuration, I can work with blowfish but not with sha512 $6$ prefix - auth just doesn't works with this hash

**Expected behaviour**
I was expecting to get logged in with the user already hashed password

**What is happening instead?**
2021/11/24 15:48:35 /api/login: 403 xxx.xxx.xxx.xxx <nil>
2021/11/24 15:48:39 /api/login: 403 xxx.xxx.xxx.xxx  <nil>
2021/11/24 15:48:40 /api/renew: 403 xxx.xxx.xxx.xxx  <nil>
2021/11/24 15:48:58 /api/login: 403 xxx.xxx.xxx.xxx  <nil>
2021/11/24 15:49:13 /api/renew: 403 xxx.xxx.xxx.xxx  <nil>
2021/11/24 15:49:40 /api/renew: 403 xxx.xxx.xxx.xxx  <nil>
auth refused

**Additional context**
Change a password for a linux user, use sha512 hashed password within json config of filebrowser (import)

**How to reproduce?**
1. Get the last version of filebrowser
2. ./filebrowser config import config.json
3. ./filebrowser users import users.json (manually crafted using $6$ hashed password from /etc/shadow)

**Files**
users.json
```
[
    {
        "id": 1,
        "username": "testuser",
        "password": "$6$pDFdFuW5$Zuk9LNtN1AfdnXj8cS2ivYH5OOmW741PWzehKVUE6vdb6ZEb0cDx2.c9420flYgbStdAYuPhuj1cdfdcjweRo1",
        "scope": ".",
        "locale": "en",
        "lockPassword": true,
        "perm": {
            "admin": false,
            "execute": true,
            "create": true,
            "rename": true,
            "modify": true,
            "delete": true,
            "share": true,
            "download": true
        },
        "commands": [
            "git",
            "id",
            "php"
        ],
        "hideDotfiles": false,
        "dateFormat": false
    }
]

```

it should work with user: testuser and password: cVkQez4FiZ with this hash, but it doesn't

Thank you!

**Comment by o1egl** [comment]
Filebrowser uses bcrypt to encrypt and compare passwords. It is not possible to use sha512
