### ISSUE TITLE
I wonder if the project has considered switching to more advanced editors (such as the Monaco Editor) and support for more code files!

### ISSUE THREAD

**Issue by sundaqiang** [filebrowser/filebrowser#1686]
I wonder if the project has considered switching to more advanced editors (such as the Monaco Editor) and support for more code files!

**Comment by niubility000** [comment]
Yes. I think the current Ace editor is hard to use in the phone's browser.
Personally I use mavon editor instead. It's actually a md editor
![11-26160333](https://user-images.githubusercontent.com/76441520/143547622-2fdecd1a-7533-4ad2-a154-b101d5a0e304.png)

You can test it here if you like: https://gitee.com/niubilitypdj/filebrowser/releases/

**Comment by sundaqiang** [comment]
> Yes. I think the current Ace editor is hard to use in the phone's browser. Personally I use mavon editor instead. It's actually a md editor ![11-26160333](https://user-images.githubusercontent.com/76441520/143547622-2fdecd1a-7533-4ad2-a154-b101d5a0e304.png)
> 
> You can test it here if you like: https://gitee.com/niubilitypdj/filebrowser/releases/

This is a great version, but I would like to use a more useful code editor
