### ISSUE TITLE
Error while trying to upload a file through internet, but works with localhost

### ISSUE THREAD

**Issue by ajitesh-kuppa-sivakumar** [filebrowser/filebrowser#1691]
Hi,

I've connected filebrowser to my subdomain. Whenever I try to upload mid or large file, I get error saying "[Object object]".
Kindly assist me.

![filebrowser-error](https://user-images.githubusercontent.com/40975704/143916905-c38a7e46-8405-4929-b9d4-35ca5d956388.png)

File Size was around 900MB.

**Comment by o1egl** [comment]
We need server/browser logs to be able to help you
