### ISSUE TITLE
Need to be able to share files/folders from the search results or preview views

### ISSUE THREAD

**Issue by menasamuel** [filebrowser/filebrowser#1692]
**Is your feature request related to a problem? Please describe.**

When viewing a folder containing a large number of files, it is tedious to find the file manually (have to scroll one page at a time for a long time). The search feature solves this but once the file is found via search, it is impossible to share it.

**Describe the solution you'd like**

A share button to be added to either the search results view or the preview view.

**Describe alternatives you've considered**

Considered scrolling

**Additional context**

The bug request below was the source of this feature request:
https://github.com/filebrowser/filebrowser/issues/1689

**Comment by jniggemann** [comment]
Same for me, lots of files in some folders.

A solution may be to have a row with filters at the top of the file listing. While you type a partial filename, the list below narrows down to only the matches (in the currently displayed folder).

**Comment by allixx** [comment]
Hate the bumps, but this needs to be un-staled.
