### ISSUE TITLE
a shell bug

### ISSUE THREAD

**Issue by zhengmingliang** [filebrowser/filebrowser#1694]
**Description**

when I exec `ps -ef | grep ping `  it causes an error 
```
error: garbage option

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
```
the shell can not use `|` , 
![image](https://user-images.githubusercontent.com/16442564/144191876-ade01123-fbfe-4bf7-9963-2caf04dc2fef.png)

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

![image](https://user-images.githubusercontent.com/16442564/144192173-66c35a53-1d4d-41ce-977d-1dc76020d757.png)
you can use the flow commands to Reproduce this problem
```shell
ps -ef | grep ping 
ls -l | wc -l
```

**Files**

**Comment by o1egl** [comment]
It is not a bug. By default, filebrowser doesn't support bash syntax. To enable it you need to navigate to `Settings -> Global settings -> Execute on shell` and set `bash -c` prefix there
