### ISSUE TITLE
Long Custom brandname position

### ISSUE THREAD

**Issue by amg-web** [filebrowser/filebrowser#1695]
**Description**
After I set a long brand name as single word it was not centered.

![Login - Opera 01 12 2021 18_25_55](https://user-images.githubusercontent.com/22151881/144273563-d4620d4e-579b-4873-a46f-98f23c5f39eb.png)

**Comment by niubility000** [comment]
Just add "  word-break: break-all;" in login.css
#login h1 {
  text-align: center;
  font-size: 2.5em;
  margin: .4em 0 .67em;
  word-break: break-all;
}
![1](https://user-images.githubusercontent.com/76441520/144960615-f5eaf290-9e02-45e4-9278-f678afff0e6d.png)

**Comment by amg-web** [comment]
> Just add " word-break: break-all;" in login.css

it does not look better (

**Comment by niubility000** [comment]
> > Just add " word-break: break-all;" in login.css
> 
> it does not look better (

Then, you wanna display it in one line and keep it centered? Maybe it's too long, especially for mobile browser.
Simply solution: just don't use this long word.
