### ISSUE TITLE
How can I reset the password??

### ISSUE THREAD

**Issue by YueMiyuki** [filebrowser/filebrowser#1697]
I forgot the password ;-;

**Comment by ArmJo** [comment]
I think you can set a new password via the command line interface 
https://filebrowser.org/cli/filebrowser-users-update

**Comment by YueMiyuki** [comment]
;-; it throws me a timeout error
![image](https://user-images.githubusercontent.com/76854136/144695906-f5f9c265-0db8-463c-a814-9046b662c3d0.png)

**Comment by o1egl** [comment]
It is caused because a db file is locked by the running service. You need to stop filebrowser server before using cli command.

**Comment by MichalisDBA** [comment]
> It is caused because a db file is locked by the running service. You need to stop filebrowser server before using cli command.

Hello. The thing is how to do that when you are running filebrowser via Docker? If you stop filebrowser the container stops or restarts based on the policy. You can't run cli via docker. I get the same timeout.

**Comment by YueMiyuki** [comment]
Well i gave up docker and reseted everything and I set it to startup script. I guess i wont hav to deal with this thing anymore

**Comment by o1egl** [comment]
@MichalisDBA the easiest way is to copy the database file on your host machine, run cli to bake changes in the file, and then mount it into the docker container.

**Comment by niterfjord** [comment]
Hello, I have filebrowser running in docker but when I run the command filebrowser users update admin -p "azerty" to reset the password, I only get this:
ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
1   admin             .          en      mosaic     false     true      true      true        true       true        true      true      true           false
But the password has not been updated.

**Comment by CharlesDerek** [comment]
> filebrowser users update admin -p "*******"
returns ```[timestamp] the resource does not exist```?:

**Comment by nailKhaled** [comment]
If you are running the filebrowser in a docker container you need just remove filebrowser.db file the recreate the container again

**Comment by All-001** [comment]
excuse me for rising this thread from the dead, i was looking for an answer and eventually found one:
i copied the filebrowser executable from the container and did the password reset 
docker cp filebrowser:/filebrowser .
/filebrowser users update admin --password "younewpass"
replace the filebrowser.db in you freshly recreated container

I had a need for password reset because otherwise i lost all my sharing links

**Comment by scienceandresearch** [comment]
I was able to use the following in terminal after stopping the container:

docker run --rm \
  -v /mnt/user/appdata/filebrowser/database.db:/tmp/database.db:rw \
  filebrowser/filebrowser:latest \
  users update admin --password "new_password" --database /tmp/database.db
