### ISSUE TITLE
FEATURE REQUEST: Folder and File Icon Differentiation

### ISSUE THREAD

**Issue by hernandito** [filebrowser/filebrowser#1698]
Hi.

I would love to see better visual differentiation between files and folders. Being that the folder and file icons are the same color and look very close to each other; please add option to better distinguish... a quick Photoshop below illustrates what I suggest:
**BEFORE:**
![FB-Before](https://user-images.githubusercontent.com/787317/144958145-4129c670-8a98-4038-81ee-2c70baf0d123.jpg)

**AFTER:**

![FB-After2](https://user-images.githubusercontent.com/787317/144960147-67fc7bca-9774-4a78-bf66-c2872a44e6b7.jpg)
Similar to how in any OS it's easy to distinguish between a folder and a file.  

If you strongly object to adding colors, at a bare minimum, please use "**view_headline**" instead of "_insert_drive_file_" for the font icon:

![image](https://user-images.githubusercontent.com/787317/144959070-e87e2eb6-08a8-4167-b665-300b8cc77172.png)

This should be a very easy change... I hope you will consider this.

Thank you!

**Comment by jniggemann** [comment]
Filebrowser is really great! My feeling is though, that many good feature requests go unoticed and as such, are not implemented. This is one of them, most probably an easy fix that greatly helps vision impaired people and all other users, too.

**Comment by hernandito** [comment]
> Filebrowser is really great! My feeling is though, that many good feature requests go unoticed and as such, are not implemented. This is one of them, most probably an easy fix that greatly helps vision impaired people and all other users, too.

Thank you...! It is indeed awesome.

I have tried editing the .vue files, but for the life of me, I have not been able to build the single binary executable with npm and go. At the end, the is no new "filebrowser" file to be found. I have spent 3 days trying. 

I created a new docker container (with an unRAID template as well) to make the user settings (and custom.css) persistent.

**Comment by hernandito** [comment]
After many days trying to recompile… without success, I just found this post that achieves exactly what I propose……

https://github.com/filebrowser/filebrowser/discussions/1256

Thank you to snokin!!!

**Comment by niubility000** [comment]
I have written a doc about how to compile filebrowser in windows pc. But it's in Chinese. 
https://gitee.com/niubilitypdj/filebrowser/releases/
If you need, I can translate it to English when I have time.

**Comment by niubility000** [comment]
@hernandito, You could start a new topic to mention that you can't compile the filebrowser. Everyone would notice it earlier. Then you don't need to try many days.

**Comment by o1egl** [comment]
@hernandito I think the proposed file icon would look unfamiliar for most people

**Comment by hernandito** [comment]
> 

Thank you. I understand about the change in icon, I was looking at this as a new user… it makes sense not changing because of user base… for the icon color, luckily there is a workaround with the custom css. Thank you for everything!
