### ISSUE TITLE
Unable to login to file manager using Firefox

### ISSUE THREAD

**Issue by AstonDavies** [filebrowser/filebrowser#170]
When using firefox (on Linux), the login process fails. The only error I can see is in the JS console:
![image](https://user-images.githubusercontent.com/24296735/28724925-afd7c264-73b3-11e7-8480-e4206900d5ed.png)
Same credentials work in Chrome and Safari (on Mac)

**Comment by hacdias** [comment]
I'll try to reproduce this.

**Comment by hacdias** [comment]
Which is the version of FF? I'm not getting that error here.

**Comment by AstonDavies** [comment]
It's version 54.0

Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0)
Gecko/20100101 Firefox/54.0

Jeremy Davies

+44(0)7957 743 743 | jeremy@astondavies.co.uk | www.astondavies.co.uk |
linkedin <https://uk.linkedin.com/in/jeremyricharddavies>
Aston Davies Limited
Aston Cottage, 33 High Street
Great Cheverell
Devizes
SN10 5TH
Registered in England No. 09408731

**Comment by hacdias** [comment]
I'm also using FF 54.0 but I don't receive any error at all. Could you try on another computer with FF, please? Or eventually try to clear the cache (although I don't think it would solve, but we never know).

**Comment by AstonDavies** [comment]
I have tried another computer (my laptop with FF and linux mint) and I get
the same error.

I can create a user on my server for you to test if you like? I will send
you the credentials directly to your e-mail.

Jeremy Davies

+44(0)7957 743 743 | jeremy@astondavies.co.uk | www.astondavies.co.uk |
linkedin <https://uk.linkedin.com/in/jeremyricharddavies>
Aston Davies Limited
Aston Cottage, 33 High Street
Great Cheverell
Devizes
SN10 5TH
Registered in England No. 09408731

**Comment by hacdias** [comment]
Yes, please.

**Comment by hacdias** [comment]
Strange... I get the same error on FF here. But when I download from caddyserver.com I don't get it. Have you built it manually or downloaded it?

**Comment by hacdias** [comment]
Oh, wait. I think I know what the problem might be: the characters in the password!

**Comment by AstonDavies** [comment]
I downloaded it yesterday

Jeremy Davies

+44(0)7957 743 743 | jeremy@astondavies.co.uk | www.astondavies.co.uk |
linkedin <https://uk.linkedin.com/in/jeremyricharddavies>
Aston Davies Limited
Aston Cottage, 33 High Street
Great Cheverell
Devizes
SN10 5TH
Registered in England No. 09408731

**Comment by hacdias** [comment]
@AstonDavies, could you please try disabling the GZIP and see if it works?

**Comment by hacdias** [comment]
It seems FF isn't decompressing the server's response body...

**Comment by hacdias** [comment]
Don't worry. I just fixed it 😄 I'll ping you when this is deployed to the server.

**Comment by AstonDavies** [comment]
Yes, without gzip it works. Is that a FF issue?

Jeremy Davies

+44(0)7957 743 743 | jeremy@astondavies.co.uk | www.astondavies.co.uk |
linkedin <https://uk.linkedin.com/in/jeremyricharddavies>
Aston Davies Limited
Aston Cottage, 33 High Street
Great Cheverell
Devizes
SN10 5TH
Registered in England No. 09408731

**Comment by hacdias** [comment]
I don't think so. I forgot to add the Content-Type to the header of the response. Although, the other browsers decompress it anyway. I'll push the fix and ping you when deployed. Will try to let the new version out today.

**Comment by hacdias** [comment]
Deployed to the caddyserver. Please check if the issues is fixed, please.

**Comment by AstonDavies** [comment]
Slight issue when installing:

```text
curl https://getcaddy.com | bash -s http.hugo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4812  100  4812    0     0   7517      0 --:--:-- --:--:-- --:--:--  7518
Downloading Caddy for linux/amd64...
https://caddyserver.com/download/linux/amd64?plugins=http.hugo
Extracting...
tar: caddy: time stamp 2017-07-29 17:38:15 is 53.083252226 s in the future
Backing up /usr/local/bin/caddy to /usr/local/bin/caddy_old
(Password may be required.)
Putting caddy in /usr/local/bin (may require password)
panic: could not locate box "./assets/"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0xd02f5e, 0x9, 0xc4200f14f0)
	/gopath/src/github.com/GeertJohan/go.rice/box.go:110 +0x94
github.com/hacdias/filemanager/plugins.init.1()
	src/github.com/hacdias/filemanager/plugins/hugo.go:21 +0x48
github.com/hacdias/filemanager/plugins.init()
	src/github.com/hacdias/filemanager/plugins/utils.go:20 +0xfd
github.com/hacdias/filemanager/caddy/hugo.init()
	src/github.com/hacdias/filemanager/caddy/hugo/setup.go:169 +0x70
github.com/mholt/caddy/caddy/caddymain.init()
	src/github.com/mholt/caddy/caddy/caddymain/run.go:237 +0x7a
main.init()
	src/github.com/mholt/caddy/caddy/main.go:15 +0x44
Aborted, error 2 in command: $caddy_bin --version
```

**Comment by hacdias** [comment]
Sorry 😞

**Comment by hacdias** [comment]
I just downloaded from caddyserver.com and didn't get any error :(

**Edit**: I don't get this. On Windows no error, On Linux error.

**Comment by AstonDavies** [comment]
I just downloaded it from caddyserver.com, extracted from the zip and ran it in my local home:

```text
jeremy@zoostorm ~ $ ls -la caddy 
-rwxr-xr-x 1 jeremy jeremy 27258339 Jul 29 17:38 caddy
jeremy@zoostorm ~ $ ./caddy --version
panic: could not locate box "./assets/"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0xd02f5e, 0x9, 0xc420137220)
	/gopath/src/github.com/GeertJohan/go.rice/box.go:110 +0x94
github.com/hacdias/filemanager/plugins.init.1()
	src/github.com/hacdias/filemanager/plugins/hugo.go:21 +0x48
github.com/hacdias/filemanager/plugins.init()
	src/github.com/hacdias/filemanager/plugins/utils.go:20 +0xfd
github.com/hacdias/filemanager/caddy/hugo.init()
	src/github.com/hacdias/filemanager/caddy/hugo/setup.go:169 +0x70
github.com/mholt/caddy/caddy/caddymain.init()
	src/github.com/mholt/caddy/caddy/caddymain/run.go:237 +0x7a
main.init()
	src/github.com/mholt/caddy/caddy/main.go:15 +0x44
jeremy@zoostorm ~ $ 
```

**Comment by hacdias** [comment]
Deploying... when it finishes it should be fixed. I'll ping you then.

**Comment by hacdias** [comment]
Done!

**Comment by AstonDavies** [comment]
Sorry. Caddy won't start now...

```text
caddy
Activating privacy features... done.
panic: hugo plugin is already registred

goroutine 1 [running]:
github.com/hacdias/filemanager.RegisterPlugin(0xcfe00b, 0x4, 0xd7ecde, 0x1a80, 0xc420390180, 0x2, 0x2, 0xc4203901c0, 0x1, 0x1, ...)
	src/github.com/hacdias/filemanager/filemanager.go:195 +0x1ae
github.com/hacdias/filemanager/plugins.RegisterHugo()
	src/github.com/hacdias/filemanager/plugins/hugo.go:35 +0x20e
github.com/hacdias/filemanager/caddy/hugo.setup(0xc42042ee10, 0x4, 0xcfe00b)
	src/github.com/hacdias/filemanager/caddy/hugo/setup.go:21 +0x29
github.com/mholt/caddy.executeDirectives(0xc420248c30, 0xd030bd, 0x9, 0x16c1bc0, 0x3c, 0x3c, 0xc4200e3800, 0xe, 0x10, 0x0, ...)
	src/github.com/mholt/caddy/caddy.go:583 +0x570
github.com/mholt/caddy.ValidateAndExecuteDirectives(0x1654520, 0xc42028e000, 0xc420248c30, 0x0, 0x1654520, 0xc42028e000)
	src/github.com/mholt/caddy/caddy.go:533 +0x3bf
github.com/mholt/caddy.startWithListenerFds(0x1654520, 0xc42028e000, 0xc420248c30, 0x0, 0x0, 0x0)
	src/github.com/mholt/caddy/caddy.go:437 +0x6b
github.com/mholt/caddy.Start(0x1654520, 0xc42028e000, 0x1654520, 0xc42028e000, 0x0)
	src/github.com/mholt/caddy/caddy.go:429 +0xe0
github.com/mholt/caddy/caddy/caddymain.Run()
	src/github.com/mholt/caddy/caddy/caddymain/run.go:117 +0x3b7
main.main()
	src/github.com/mholt/caddy/caddy/main.go:13 +0x27

```

**Comment by hacdias** [comment]
Not your fault. It was mine. Try again pls

**Comment by AstonDavies** [comment]
:smile: All working now. FF can login with gzip enabled. :thumbsup:

**Comment by hacdias** [comment]
Awesome!
