### ISSUE TITLE
upload file when file name contain '+' will cause error

### ISSUE THREAD

**Issue by hcl0712xyz** [filebrowser/filebrowser#1701]
if upload file when file name contain '+' will cause 404 error

filebrowser amd64 version 2.19.0 and 2.18.0
server windows 2012 x64

testing file: any file with name contain '+' char, for example  :  CE+.7z

screen shot

![Snap525](https://user-images.githubusercontent.com/95897630/145515824-c5b3a84c-7a2d-4d7e-af77-866962c48957.png)

![Snap524](https://user-images.githubusercontent.com/95897630/145515833-bdad1839-81b1-46e5-adee-1d1e35285eb3.png)

**Comment by ramiresviana** [comment]
Filebrowser has no issues with special characters on filenames when uploading. Looks like you're having issues with your proxy configuration.

**Comment by hcl0712xyz** [comment]
Thanks for the information.
