### ISSUE TITLE
Detect multiple subtitle languages

### ISSUE THREAD

**Issue by mazenbesher** [filebrowser/filebrowser#1702]
It would be nice to support subtitle files (i.e. `.vtt`) for **multiple languages** by detecting filename with language codes like `videoname.en.vtt` as shown in this [TODO](https://github.com/filebrowser/filebrowser/blob/aa52b07bb169e53bc1b656cbf88262e808c10ae3/files/file.go#L274) for the native video player.

**Comment by mazenbesher** [comment]
As a non-go programmer but a fan of this project, those are my two cents to solve this:

```go
import (
	"fmt"
	"io/ioutil"
	"regexp"
	"strings"
)

func main() {
	// directory with files: video.vtt, video.en.vtt, video.fr.vtt, video.🎈.vtt

	path := "video.mp4"
	ext := ".mp4"
	subtitles := []string{}

	base := strings.TrimSuffix(path, ext)
	r := regexp.MustCompile(base + `\.(.*\.)?vtt`)
	items, _ := ioutil.ReadDir(".")
	for _, item := range items {
		if !item.IsDir() {
			if matches := r.FindStringSubmatch(item.Name()); len(matches) == 2 {
				subtitles = append(subtitles, matches[0])
			}
		}
	}

	fmt.Printf("%v", subtitles) // [video.en.vtt video.fr.vtt video.vtt video.🎈.vtt]
}
```

If there is any hope that this is useful, I can work on a PR.

**Comment by niubility000** [comment]
It's cool.
