### ISSUE TITLE
Config environment variable appears to be ignored

### ISSUE THREAD

**Issue by geoffbon** [filebrowser/filebrowser#1703]
**Description**
I'm trying to use an environment variable for both the config and database locations, so that I can run this in a docker container (actually, in Rancher/Kubernetes).  I have shelled into the pod and moved the system-generated config file to my specified location.

**Expected behaviour**
I expected to see filebrowser start up with my specified config file.

**What is happening instead?**
Instead, it appears to be generating and using a new config file in the root.  When I start up, this is the log that I see:
```
2021/12/10 17:30:12 Using config file: /.filebrowser.json
2021/12/10 17:30:12 Listening on [::]:80
```

**Additional context**
Inside the pod:
```
/ # ls /srv -al
total 92
drwxr-xr-x    8 root     root          4096 Dec 10 17:29 .
drwxr-xr-x    1 root     root          4096 Dec 10 17:30 ..
-rw-r--r--    1 root     root           121 Dec 10 17:33 config.json
-rw-------    1 root     root         65536 Dec 10 17:30 database.db

/ # set | grep FB_
FB_CONFIG='/srv/config.json'
FB_DATABASE='/srv/database.db'

/ # cat /srv/config.json 
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/srv/database.db",
  "root": "/srv"
}
```

**How to reproduce?**

**Files**

**Comment by paolomemoli** [comment]
this is very frustrating and makes trying to use filebrowser inside kubernetes useless.

it should be able to set environment settings to point the config file to a location inside a volume, this would allow you to easily move the installation and encapsulate all settings inside kubernetes.

Heres the order the docs mention settings are read from and why each one doesn't work well in kubernetes: 

1. flags: overriding docker run commands is not scalable or portable, hard coding setting here is not an option when moving deployments around
2. environment variables: would be ideal but for some reason are simply being ignored. setting an env of FB_CONFIG = /config/.filebrowser.json still results in the process logging:  `Using config file: /.filebrowser.json`
3. configuration file: cannot bind-mount single file, could mount the folder its in, but being located at  /.filebrowser.json would mean mounting the / as a volume, which isn't just a bad idea, it's blocked
4. database values: pointless as the database by default is stored in the root so has the same issues
5. defaults: not useful.

**Comment by paolomemoli** [comment]
passing in the command: `--config=/config/.filebrowser.json` is a doable workaround until this is fixed.

**Comment by ramiresviana** [comment]
The config option is not retrieving the value from the environment variable. This should be fixed by making some changes on [root.go#L386](https://github.com/filebrowser/filebrowser/blob/a078f0b787de83b58c3e5dd5699387e90f1bf0d6/cmd/root.go#L386)

**Comment by JaneJeon** [comment]
I _think_ it's added now? https://github.com/filebrowser/filebrowser/blob/a078f0b787de83b58c3e5dd5699387e90f1bf0d6/cmd/root.go#L399

**Comment by Maximus48p** [comment]
Still not working for me
