### ISSUE TITLE
Add Git to the Docker image 

### ISSUE THREAD

**Issue by tinkerdudeno1** [filebrowser/filebrowser#1706]
**Is your feature request related to a problem? Please describe.**
One of THE reasons to use this app is that it allows users to use cli commands. IMHO three commands are absolutely basic and should be available: wget, curl, and git. The latter is not preinstalled in the Docker image.

**Describe the solution you'd like**
Add git to the Docker image

**Describe alternatives you've considered**
The alternative would be to build a new image but this requires me to create a build pipeline so that I can auto-update the app.

**Additional context**
n/a

**Comment by o1egl** [comment]
I don't think that we should add something to the base image. In my opinion, the best way to solve this would be an initialization script that installs the required software on startup. With that everyone will be able to manage their own list of software
