### ISSUE TITLE
Can we reuse the cached HD images or thumbnails for different users?

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#1709]
Currently, different users will generate different cached HD images or thumbnails in the server's cache folder. 
For example, if I log in as user A, and browse some HD images, the server will generate these HD images at the first time and save them in the server's cache folder. 
Then, I logged in as user B, and wanna browse these HD images, it will genarate them again. But they are already generated for user A. I hope it can read the cached images directly. It will much faster for low-end server, and will save the space of server.  I think we do not need to genarate these HD images and cache them again and again for different users.

**Comment by ramiresviana** [comment]
https://github.com/filebrowser/filebrowser/blob/a078f0b787de83b58c3e5dd5699387e90f1bf0d6/http/preview.go#L145

This is the code used to generate the identifier that is used to store and retrieve a cache entry, the function does not have any parameter to distinguish users. All users have access to the same cache.

**Comment by niubility000** [comment]
> https://github.com/filebrowser/filebrowser/blob/a078f0b787de83b58c3e5dd5699387e90f1bf0d6/http/preview.go#L145
> 
> This is the code used to generate the identifier that is used to store and retrieve a cache entry, the function does not have any parameter to distinguish users. All users have access to the same cache.

Thank you. I will try again.
I just personally added a filesize 240*240 to show larger and clearer thumbnails. and added three buttons in the search page to cache all the images to server in advance. It works great for the same user, but not for other users. Maybe it's the problem of my modification. 
I will try the official version to check it. 

I add a switch button to allow to show large thumbnails in Mosaic Mode.
![7](https://user-images.githubusercontent.com/76441520/145922464-78b12e7d-5f38-4b84-9f33-eb1339f3af1d.png)

![4](https://user-images.githubusercontent.com/76441520/145879029-d7850402-834f-4b82-b539-e8b9a4e7d1d7.png)
![5](https://user-images.githubusercontent.com/76441520/145881157-d4b32db0-0061-4157-aa13-1ed827a1b6ac.png)
![6](https://user-images.githubusercontent.com/76441520/145881181-865845ce-1e98-4204-8617-6cb168eba795.png)

**Comment by niubility000** [comment]
> https://github.com/filebrowser/filebrowser/blob/a078f0b787de83b58c3e5dd5699387e90f1bf0d6/http/preview.go#L145
> 
> This is the code used to generate the identifier that is used to store and retrieve a cache entry, the function does not have any parameter to distinguish users. All users have access to the same cache.

As I tested, only the users with same scope have access to the same cache. 
The users with different scopes can't read it and will generate new cached files for the same images. the cache folders in the server will become twice larger.

User A can't read the same cached files generated by user B with different scopes.


For example:
There is a folder "/mnt/d/family/photos/"  with a lot of images,  and we have four users(no matter it's an admin account or not): 
User A with scope "/"
User B with scope "/mnt/d"
User BB with scope "/mnt/d"
User C with scope "/mnt/d/family"
Before testing, just delete the cache in the browser, and the cache folder in the server. 
then, login as User B, browse the folder "/mnt/d/family/photos/", it will generate the cache files to the server's cache folder.
Then, delete the cache in the browser, login as User BB, browse the same folder "/mnt/d/family/photos/", it will show the thumbnails and HD images very fast. It can read the cached files generated by User B because they have the same scope, and the cache folder in the server will remain the same.
But, if we delete the cache in the browser and login as User A, or user C, it will show the thumbnails and HD images much slower at first time. It's generating the thumbnails and HD images by the server again.  The number of cached files in the server are twice larger. And after browse the folder thouroughly, delete the cache in the browser, and browse the folder again. The thumbnails and HD images will show up very fast. It can read the cached files this time. And all the users (A, B, BB, C) can read the cached files now. 

I think maybe it's a problem of "file.Path" in cacheKey := previewCacheKey(file.Path, file.ModTime.Unix(), previewSize). Is this a relative path? 
 
----------------------------------------
By the way, to see it clearly, we may disable "reading thumbnails from exif" temporarily. just add a line "return nil, wrappedReader, exif.ErrNoThumbnail" in the img/service.go 


func getEmbeddedThumbnail(in io.Reader) ([]byte, io.Reader, error) {
	buf := &bytes.Buffer{}
	r := io.TeeReader(in, buf)
	wrappedReader := io.MultiReader(buf, in)
  **return nil, wrappedReader, exif.ErrNoThumbnail**
	offset := 0
	offsets := []int{12, 30}
	head := make([]byte, 0xffff) //nolint:gomnd
	_, err := r.Read(head)
	if err != nil {
		return nil, wrappedReader, err
	}

and make larger thumbnails, just change some number in the  preview.go

	switch {
	case previewSize == PreviewSizeBig:
		width = 1080
		height = 1080
		options = append(options, img.WithMode(img.ResizeModeFit), img.WithQuality(img.QualityHigh))
	case previewSize == PreviewSizeThumb:
		width = 320
		height = 320
		options = append(options, img.WithMode(img.ResizeModeFill),img.WithQuality(img.QualityHigh),img.WithFormat(img.FormatJpeg))
	default:
		return nil, img.ErrUnsupportedFormat
	}

**Comment by niubility000** [comment]
I tested again. users with different scope will not reuse the cache files. It will generate new cached thumbnails and HD images for the same images. and the cache folder will become twice times larger.

**Comment by ramiresviana** [comment]
The path used to generate the cache identifier is relative to the user filesystem. Files on different filesystems have issues hiting the cache and can overwrite it incorrectly. This should be fixed by using the real file path to generate the cache key.

**Comment by niubility000** [comment]
> The path used to generate the cache identifier is relative to the user filesystem. Files on different filesystems have issues hiting the cache and can overwrite it incorrectly. This should be fixed by using the real file path to generate the cache key.

Thank you so much. 
It's true the problem is from cacheKey.
I have tried so many different ways , and finally found the simplest way to fix it.
In http/preview.go 
just simply delete the "fPath" in the return value of func previewCacheKey( ),

```
 func previewCacheKey(fPath string, fTime int64, previewSize PreviewSize) string {
	return fmt.Sprintf("%x%x%x", fTime, previewSize)
}
```
It works great as I tested. the fTime is strong enough to tell different images because it includes year, month, day, hour, minute, second. It's really rare that two different images have the same fTime.

Or, to make it more reliable, we also can use the filename to help to tell different images. 
Just add two lines in http/preview.go: 
```
import (
	"path/filepath"
)
```
....

```
func previewCacheKey(fPath string, fTime int64, previewSize PreviewSize) string {
        fPath = filepath.Base(fPath)
	return fmt.Sprintf("%x%x%x", fPath, fTime, previewSize)
}
```
========================
It works very good! All users can read the same cached files now.
It is also very good when you have a lot of copies of same images in different folders in your server, it will only generate the cache file once for all of them.

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/commit/c1987237d05adcce77c614e5247a181ae5cdfacd
