### ISSUE TITLE
caddy-hugo: consider enabling publishing outside /content

### ISSUE THREAD

**Issue by casio** [filebrowser/filebrowser#171]
Hey guys - first of all: awesome plugin! : )

When editing data for instance in `./data/menu.yaml`, these changes are only reflected once I hit 'Publish' in a `./content` file. From a UX point of view thats a bit suboptimal, imho.
Do you have plans/ideas for this scenario? Maybe a global publish button in the sidebar or similar?

On a sidenote: hugo's default server will automatically watch for changes in `{data,content,static,themes}`. That would actually solve my usecase.
In older github issues I saw a `watch` flag being mentioned, but I cant seem to find it in docs/code.

Thx for any pointer & keep up the great work!

**Comment by hacdias** [comment]
Hello @casio! Thanks 😄 The easiest way to fix this, for me, is adding the button in the other pages. Does it sound good to you?

**Comment by casio** [comment]
Hello @hacdias - thanks for getting back so quickly! : )

Yep, that sounds great already! And will help my 'editor is editing data/media/...' usecase right away - would be awesome.

Thinking some more about it: consider the case that some other os process is updating a relevant file - would still be cool, if the site would get re-generated.
Didnt get to read your code too deeply - do you run off hugo once you got a change event and/or can we start hugo in server and, thus, watch mode as well?

**Comment by hacdias** [comment]
Only when we the server gets a change event. You can also run it by adding the 'hugo' command to your user. That way you can run any hugo command anytime, anywhere 😄

**Comment by casio** [comment]
Ha, works like a charm. Cool, thanks a lot, editor usecase solved! : D

However, what do you think about the 'os process doing the change' usecase?
Is it reasonable to have hugo run in the background with a flag?
Will be some days on vacation now, but would be willing to contribute



Henrique Dias <notifications@github.com> schrieb am Fr., 28. Juli 2017 um
22:41 Uhr:

**Comment by hacdias** [comment]
Hello! I know there are some users using Hugo with watch option in the background. Although, I don't think l it's a good idea because unless you want to update the site at every change, the site is already updated when you hit the publish button.

**Comment by hacdias** [comment]
This update is already available on Caddyserver.com. I'll close this issue since its main topic is closed. We can finish the conversation about the os proccess here though.

**Comment by hacdias** [comment]
L
