### ISSUE TITLE
No option to set theme in `config init` commandline.

### ISSUE THREAD

**Issue by hgaiser** [filebrowser/filebrowser#1711]
**Description**
I'm trying to initialize a new db and set the theme on commandline.

**Expected behaviour**
I expected an argument on the commandline to set the theme.

**What is happening instead?**
There is no option to set the theme on commandline.

**Additional context**
The available options are:

```
--branding.color string              set the theme color
--branding.disableExternal           disable external links such as GitHub links
--branding.files string              path to directory with images and custom styles
--branding.name string               replace 'File Browser' by this name
```

I think a `--branding.theme` is missing.

Also I'm using v2.19.0 in a Docker container.

**How to reproduce?**
`filebrowser config init --help`

**Files**
I don't think this is necessary.

**Comment by o1egl** [comment]
Branding options are related to the custom branding and theme param doesn't make sense there since everything can be overridden by the custom.css file
