### ISSUE TITLE
[Rules] Root Folder of allowed sub-path not shown

### ISSUE THREAD

**Issue by sgohl** [filebrowser/filebrowser#1718]
**Description**

Having a path like
```
something/foo/bar
```

with Rule definitions like so:
```
[x] Regex  [ ] Allow  [ /.+ ]
[ ] Regex  [x] Allow  [ /something/foo/bar ]
```
the root path (`/something`) is not shown to the user, despite accessing the sub-path `/something/foo/bar` via URL will be accessible.

**Expected behaviour**

Root Folder `/something` should be shown in the My Files listing, following with the sub-folder `foo` being the only visible folder in there, following by `bar` being the only visible folder then.

**What is happening instead?**

Root Folder is not shown

Edit: this seems slightly related to https://github.com/filebrowser/filebrowser/issues/998
but in that case here, we're talking about multiple subfolders in different sublocations. The example here just mentions one subpath for simplicity
I see this could be achieved by stating multiple rules, but this isn't very handy the way it is, as I have to create them for every user.  

My proposal would be to provide something like Rule-Templates we could manage, and apply them to users. 
And/or additionally, if anyhow possible, put a user in multiple Scopes.

**Comment by o1egl** [comment]
1) Regex rules are applied from top to bottom
2) /something/foo/bar doesn't match /something. You need to explicitly allow /something, /something/foo, etc.
