### ISSUE TITLE
Show logged-in User

### ISSUE THREAD

**Issue by sgohl** [filebrowser/filebrowser#1719]
It would be very helpful if the user you are currently using, would be shown somewhere.
Usual positions would be top-right or somewhere around the Logout Link

We've got some users who work in multiple, lets say contexts, where one person has to switch/use different accounts.
And it's always a struggle to find out which user you currently are.

**Comment by niubility000** [comment]
How about this one? 
![sidebar](https://user-images.githubusercontent.com/76441520/146677779-6f689317-9590-43b8-806f-bebe6a701e42.png)
It's easy. Just add this in sidebar.vue:
          <span>{{ $t("sidebar.logout") }} **: {{user.username}}**</span>

And add this in http/auth.go:
type userInfo struct {
	ID           uint              `json:"id"`
	Locale       string            `json:"locale"`
	ViewMode     users.ViewMode    `json:"viewMode"`
	SingleClick  bool              `json:"singleClick"`
	Perm         users.Permissions `json:"perm"`
	Commands     []string          `json:"commands"`
	LockPassword bool              `json:"lockPassword"`
	HideDotfiles bool              `json:"hideDotfiles"`
	DateFormat   bool              `json:"dateFormat"`
	**Username     string            `json:"username"`**
}
		User: userInfo{
			ID:           user.ID,
			Locale:       user.Locale,
			ViewMode:     user.ViewMode,
			SingleClick:  user.SingleClick,
			Perm:         user.Perm,
			LockPassword: user.LockPassword,
			Commands:     user.Commands,
			HideDotfiles: user.HideDotfiles,
			DateFormat:   user.DateFormat,
			**Username:     user.Username,**
		},

**Comment by aae42** [comment]
> It would be very helpful if the user you are currently using, would be shown somewhere. Usual positions would be top-right or somewhere around the Logout Link
> 
> We've got some users who work in multiple, lets say contexts, where one person has to switch/use different accounts. And it's always a struggle to find out which user you currently are.

you say it's a struggle, but how do you do it?  having this functionality would be particularly useful when using the proxy auth feature

**Comment by aae42** [comment]
maybe it can be closed in favor of #2692
