### ISSUE TITLE
upload large files through some CDNs

### ISSUE THREAD

**Issue by tasi788** [filebrowser/filebrowser#1720]
**Is your feature request related to a problem? Please describe.**

I'm using Cloudflare CDN to protect my own filebrowser, but due to [cloudflare's docs](https://developers.cloudflare.com/cache/about/default-cache-behavior#customization-options-and-limitations) says Pro and Free user can only upload less than 100MB.

**Describe the solution you'd like**

split large file.

**Describe alternatives you've considered**

to upload file, if we announce to server says I'll chunk large file to 90MB and we would be sending 90MB file through.

**Additional context**

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/discussions/1182
