### ISSUE TITLE
No seek bar for videos on mobile browsers

### ISSUE THREAD

**Issue by ineptcharge** [filebrowser/filebrowser#1724]
There doesn't seem to be a seek bar for videos on mobile browsers. I tried Firefox for Android and Chrome for Android. On Chrome you can pause and unpause videos. On Firefox you can't. Neither had a seek bar for videos. Does anyone else have this problem?

**Comment by jason5545** [comment]
Me too

**Comment by niubility000** [comment]
I just figure it out.
When the address bar of the browser is hidden, we can see the seek bar of the video. 
![02](https://user-images.githubusercontent.com/76441520/147521681-354dbf41-f9bd-48f8-a49f-5fc0b3007ab3.png)

But when the address bar is not hidden, we can't see the seek bar. 
![01](https://user-images.githubusercontent.com/76441520/147521322-d34c7647-c52e-4f97-9d62-8dec464ee0e4.png)

I will fix it.
