### ISSUE TITLE
Docker database.db path issue in version 2.20.0

### ISSUE THREAD

**Issue by Teraskull** [filebrowser/filebrowser#1733]
**Description**
Commit 988d3e5bdd224509ddc2f08444560e3087e9c67d changes the database path.
After the docker image update my login does not work. It says "Wrong credentials".
I tried changing the database path in my docker compose as stated in the mentioned commit, but the container logs say something about incorrect permissions.

**Expected behaviour**
Use the same `database.db` path.

**What is happening instead?**
Probably creates a completely new database.

**Additional context**
If I use the previous docker image (`2.19.0`), everything works, and the correct `database.db` is used.

**How to reproduce?**
Update the filebrowser docker container from `2.19.0` to `2.20.0` and attempt to log in.

**Comment by o1egl** [comment]
Default image building pipeline is restored in `v2.20.1`
