### ISSUE TITLE
Audio preview for shared folders

### ISSUE THREAD

**Issue by bluemle** [filebrowser/filebrowser#1735]
It would be really nice to have an inline audio preview for shared folders similar to the non-shared folder view. For example by clicking on the loudspeaker icon in the file list and starting an inline player.
So far every shared audio file has to be opened seperately by clicking "OPEN FILE".

**Comment by niubility000** [comment]
How about this one?
![Uploading Screenshot_20211230-052846.png…]()

**Comment by niubility000** [comment]
How about this one ? When you single click an item, it will be selected and a preview window will show up on the top of the current page if it's an img or audio or video.
![Screenshot_20211230-052846](https://user-images.githubusercontent.com/76441520/147705033-5be094a5-1313-4dce-b1ca-78cb740974da.png)
![Screenshot_20211230-052827](https://user-images.githubusercontent.com/76441520/147705054-77e6ed97-ef51-4705-bf2d-dd9b412c77d6.png)
![Screenshot_20211230-052812](https://user-images.githubusercontent.com/76441520/147705085-e41ff249-5370-4848-89eb-fa8604d8a0d9.png)

**Comment by bluemle** [comment]
Sure, thanks that looks great! With an arrow to skip to the next or previous track it would perfect!

**Comment by niubility000** [comment]
> Sure, thanks that looks great! With an arrow to skip to the next or previous track it would perfect!

Yes, it's the simplest way and looks great. But it's still not that professional. I just don't know where to put this preview window. Maybe we can replace the big icon with this preview window.

And about the nav arrows, I have tried, but couldn't get the prev and next link. 
We can click the items to switch or turn off it directly.

**Comment by niubility000** [comment]
I have made some changes, it looks better.

![Screenshot_20220102-073848](https://user-images.githubusercontent.com/76441520/147862481-9d906e04-1e89-4394-ac44-c83db05eff5b.png)

![Screenshot_20220102-073934](https://user-images.githubusercontent.com/76441520/147862425-14589d27-dde2-4870-b18c-9e24fc2f61ec.png)
![Screenshot_20220102-073919](https://user-images.githubusercontent.com/76441520/147862426-5f97c8e4-d96d-4332-9b62-d176fe8e5d4b.png)
