### ISSUE TITLE
Possible typo in docs

### ISSUE THREAD

**Issue by methatronc** [filebrowser/filebrowser#1737]
Hello,

After the changes done yesterday I read the docs again just to be sure all is done right on my server, I believe the 4th line of the Alpine section in [this page](https://filebrowser.org/installation#docker) should be :
`-v /path/.filebrowser.json:/filebrowser.json \`
instead of :
`-v /path/.filebrowser.json:/.filebrowser.json \`

( ie not a hidden file )

I say this because when mounting it as a hidden file I cannot get it to run, but as a not-hidden file all is loaded as it should.

Thanks,

Have a good day

**Comment by o1egl** [comment]
Fixed in v2.20.1
