### ISSUE TITLE
Activity logs

### ISSUE THREAD

**Issue by Yingzzzzz** [filebrowser/filebrowser#1738]
Dear Programmers and Filebrowser makers,

I really like this filebrowser, but I need some help.
I need  to record user's activities log (copy file, delete file, download file.)with their username and password into a local txt file. I have no idea of how to manage this. As I know I should use Command runner to do that, but the instruction one doesn't work. Could you please tell me how to code to save these activities to local file. It's quiet urgent.

Thank you very much!!

**Comment by o1egl** [comment]
You can define commands using ui `Settings → Global Settings → Command runner`. All available env variables are listed [here](https://github.com/filebrowser/filebrowser/blob/master/runner/runner.go#L68-L83)

**Comment by Yingzzzzz** [comment]
> You can define commands using ui `Settings → Global Settings → Command runner`. All available env variables are listed [here](https://github.com/filebrowser/filebrowser/blob/master/runner/runner.go#L68-L83)

Dear Programmer, 

Could you give me an example of code for this command runner's code?
For example save "username" and "File" name into 123.txt

**Comment by Yingzzzzz** [comment]
> > You can define commands using ui `Settings → Global Settings → Command runner`. All available env variables are listed [here](https://github.com/filebrowser/filebrowser/blob/master/runner/runner.go#L68-L83)
> 
> Dear Programmer,
> 
> Could you give me an example of code for this command runner's code? For example save "username" and "File" name into 123.txt

Or maybe to the default log file is also good! 
I think I just need an example of code format, I will be able to figure out the rest of these codes

**Comment by o1egl** [comment]
Define a command:

<img width="570" alt="Screenshot 2021-12-22 at 16 04 18" src="https://user-images.githubusercontent.com/966539/147113046-b3ef61df-bcd8-4d82-b473-b844c92acc0c.png">

Upload a file and you will see a message in the stdout:

<img width="633" alt="Screenshot 2021-12-22 at 16 04 36" src="https://user-images.githubusercontent.com/966539/147113053-bdfa5815-6017-4868-b5a4-8870af08f51e.png">

**Comment by normalC** [comment]
![](https://user-images.githubusercontent.com/966539/147113046-b3ef61df-bcd8-4d82-b473-b844c92acc0c.png)
How to record download file activities log?

**Comment by Officepoint** [comment]
Hello to everyone!!
Please, it would be extremely helpful if someone could provide a simple procedure, an example where it can be seen who and when the file was downloaded or viewed.
Thank you very much and I hope someone can perform this operation. All the best!

**Comment by pkuwwt** [comment]
AFAIK, the command runner only works for part of the APIs currently. For example, there is no runner hooked for downloading.

To solve this problem, I implement the logging feature to allow recording every request. [pull 2893](https://github.com/filebrowser/filebrowser/pull/2893)
