### ISSUE TITLE
"cache-dir" doesn't seem to be doing anything

### ISSUE THREAD

**Issue by ManuelFte** [filebrowser/filebrowser#1746]
**Description**

`cache-dir`, `disable-preview-resize`, and `disable-type-detection-by-header` don't seem to be having any effect despite being all enabled in an attempt to help File Browser deal with directories with large number of files.

I run File Browser with this command:

`filebrowser --config ~/.filebrowser/config.json`

And these configurations:

```json
{
    "address":"0.0.0.0",
    "database":"/home/mediacenter/.filebrowser/filebrowser.db",
    "root":"/run/media/mediacenter/Seagate Expansion Drive",
    "disable-preview-resize": true,
    "disable-type-detection-by-header": true,
    "cache-dir": "/home/mediacenter/.cache/filebrowser"
}
```

However, it's not caching anything. Directories keep getting reloaded every time I do an operation, which takes very long time when there are many files (currently testing on a folder with 11k+ files and 261 subdirectories) and it's extremely tedious. The specified cache directory is always empty, with File Browser not storing anything in it.

**Expected behaviour**

It should store a cache in the specified directory, making the browsing much faster and not reloading thumbnails and the list of files every time.

**What is happening instead?**

It's not caching anything and the browsing is as slow as when not using any of the parameters.

**Additional context**

I'm using File Browser 2.20.1 on Manjaro Linux. The files are stored in an external Seagate HDD with NTFS; however, I also did an experiment by moving a folder with many files (2500+) to the local Ext4 file system, and the result was the same. It was still not caching and the browsing was as slow as with the external HDD.

**How to reproduce?**

Run File Browser with those configurations on a Linux distro and while browsing a directory with a few thousand files.

**Comment by ramiresviana** [comment]
The config file does not support the `cache-dir` option, you need to use CLI to make it work. Filebrowser uses the cache directory to store previews and images thumbnails, that does not prevent directories from being reloaded.

**Comment by ManuelFte** [comment]
@ramiresviana Oh, I see. I added `cache-dir` as a flag and now I can see the directory being populated. Is the fact that it's not supported by the config file the intended behavior, or will it be supported in the future?

And shouldn't `--disable-type-detection-by-header` make the listing of files nearly instantaneous according to [this issue](https://github.com/filebrowser/filebrowser/issues/1689#issuecomment-982022360)?

At least the cache of images already helps somewhat, thanks.

**Comment by niubility000** [comment]
> And shouldn't `--disable-type-detection-by-header` make the listing of files nearly instantaneous according to [this issue](https://github.com/filebrowser/filebrowser/issues/1689#issuecomment-982022360)?
> 
Do you mean the listing of files still shows up slowly after you use "--disable-type-detection-by-header"? 
Generally it takes 1 or 2 seconds to show up no matter how large the folder is. That 's "nearly instantaneous".

**Comment by ManuelFte** [comment]
@niubility000 Yes, it just doesn't seem to make any difference. Every time I enter the directory it takes about 15 seconds to complete the listing, with or without the flag. And since it reloads the list every time any operation is done (like renaming anything or simply opening an image), it makes it virtually unusable.

Forgot to mention that I'm running the program on a modest hardware, it's my old laptop that I connected to an external 3 TB HDD to turn it into my personal media server. It has 4 GB RAM and an Intel Pentium N3700, but I don't know if it should be _this_ slow, considering that the resource usage is always very minimum. I checked it when listing files and it was at 25% RAM and 32% CPU.

**Comment by niubility000** [comment]
If you open a small folder with one or two files, will it still need 15 seconds to list the files?  
Or try a window version of filebrowser on your main PC. 
I just think maybe your old laptop' system disk is not a SSD.

**Comment by ManuelFte** [comment]
> If you open a small folder with one or two files, will it still need 15 seconds to list the files?

It only happens on folders with thousands of files. Other folders open pretty quickly.

> Or try a window version of filebrowser on your main PC. I just think maybe your old laptop' system disk is not a SSD.

I just did a test on my current laptop, which also runs Manjaro but has a much better hardware and an SSD, by copying one of those big folders to the local disk. In here, File Browser displays the list instantaneously, therefore it's a hardware-related issue. I guess I underestimated the impact an HDD can have on the performance. :unamused: 

I've been working on organizing those thousands of scattered files into subfolders and now I've largely reduced the issue. Since I also got an answer about `cache-dir` not working, I consider this issue fixed and I'll close it.

Thank you so much for the help, and sorry for the inconveniences. :sweat_smile: 

If you don't mind please just let me know the answer to this:

> Is the fact that [`cache-dir` is] not supported by the config file the intended behavior, or will it be supported in the future?
