### ISSUE TITLE
Ability to permanent share folder to another users

### ISSUE THREAD

**Issue by Rihan9** [filebrowser/filebrowser#1747]
**Is your feature request related to a problem? Please describe.**
I would like to have a folder, let's call it "Public", accessible by all users or a subset of users.

**Describe the solution you'd like**
One solution could be:
- add a new menu item on folder context menu, like "share with another user", that opens a pop-up with the list of users
- add another menu item below "My files", called, for example, "Shared With Me", that contains a screen similar to "My Files" but relative to a different folder.
- this folder can be a system folder, with path like "/shared/$USER/" which contains symbolic links to shared folders. The new items on the first point should take care of creating these links (no absolute path, but relative)

**Describe alternatives you've considered**
Since the first solution involves a lot of work, I can give up to have new menu items and I can take care of create a new folder on user's scope and create the links, if I had at least the possibility to launch a post user creation script with the Command runner

**Comment by niubility000** [comment]
It's good idea to have a public folder for all users (or for specific users? It will be complicated ).  
But a filebrowser user can only visit files and folders within his/her scope,  how to make the public folder?

**Comment by Rihan9** [comment]
Hi,
I can present to you my personal use case.
I have 3 users: admin, user1, user2.
The admin's user scope is "." that contains 3 folder: "User1", "User2", "public".
The user1's and user2's scope is respectively the folder "./User1" and "./User2".
The first solution would allow me to click on the "./public" folder, select "share with another user", and select others user to share it. It's complicated to implement this, I know. 

The programs should:
1. on first start, create a system folder to store the symbolic link in a structure like "/shared/$USER/"
2. every time a user is created, a new folder needs to be created on the previous structure (Es: User1 should have /shared/user1)
3. when a user use the "share with another user" functionality, the program shoud create a new link on the previous folder (es: admin share the public folder whit user1 and user2, the following links shoud be created: "/shared/User1/public",  "/shared/user2/public"). I dont't think is a good idea to store the entire path, only the folder's name.
4. the voice on the left menù should read the content on the structure on point 2. They can be read on the same way is read the scope folder.

Something like that. This is the cleanest solution that I can think at the moment. 

Another solution, far more simple I think, is to add another voice on the config, like "global scope", "public scope" or similar. If present, the program should "only" duplicate the voice "My Files" and show use the path from this config instead from the user's scope. To manage a minimum of permissions, maybe is a good idea to add 3 voices on the users permission settings, like "create files and directories on the public folder",  "delete files and directories on the public folder",  "rename or move files and directories on the public folder", but I think that could be managed as "improvement which can be done later", because if you share a public folder, you expect that being public, everyone can do whatever they want with it.

**Comment by o1egl** [comment]
I think the better way would be an introduction of a multi-scope. So a user would have a primary and multiple attached scopes

**Comment by Rihan9** [comment]
> I think the better way would be an introduction of a multi-scope. So a user would have a primary and multiple attached scopes

Yes, it would be good for me to.

**Comment by uamrws** [comment]
> I think the better way would be an introduction of a multi-scope. So a user would have a primary and multiple attached scopes

Yse, I think multi-scope is a good idea

**Comment by Pikamander2** [comment]
Are there any development plans for this? We'd like to be able to use this tool to share files publicly as needed.

**Comment by cubedmeatgoeshere** [comment]
This is sorely needed! Filebrowser cannot understand symlinks so there's no workaround. If you have an assortment of subdirectories and you need a user to have access to only certain directories there is no way to accomplish this besides rearranging your entire directory structure to suit the file browser (which in many cases is not acceptable)

**Comment by Pikamander2** [comment]
@o1egl - Would it be possible to reopen this since it's still active?

**Comment by Owned67** [comment]
yes please, thanks very much!

**Comment by vikasedulab** [comment]
how i can give 2 folder location to same user in scope i can add only one folder location
