### ISSUE TITLE
Force download instead of streaming

### ISSUE THREAD

**Issue by CaseyBakey** [filebrowser/filebrowser#1748]
**Description**
I would like my server to force users to download served files instead of streaming them.

**Expected behaviour**
Click on a video file (MP4, mkv, etc.) should prompt to download the file.

**What is happening instead?**
Once clicked, the file is streamed/played within browser.

**Additional context**
Using filebrowser v2.10.0 for now

**How to reproduce?**
Click on a browser supported file.

**Files**
Any MP4/MKV/browser supported file.

I'm sorry if it's not up to filebrowser to handle this but it's not very clear for me.
For information, I'm using caddy v1.0.5 as reverse proxy for filebrowser.

I read some things about setting mime for such files (mp4/mkv), to purposedly unknow mime types (for browsers to fallback to download), or disabling web browsers to sniff the mime types, or even changing header to attachment, and so on.

Anyway, if there is such a setting in filebrowser, please let me know ;)

**Comment by niubility000** [comment]
There's no such settings in filebrowser. But it's easy to do by changing the code.
in /frontend/src/view/files/preview.vue;
just change 
  v-else-if="req.type == 'blob'" class="info">
to 
  v-else-if="req.type == 'blob'|| req.type == 'video'" class="info">

and change 
        <video
          v-else-if="req.type == 'video'"
to 
        <video
          v-else-if="req.type == '    '"
