### ISSUE TITLE
set description for shared folder

### ISSUE THREAD

**Issue by jjit** [filebrowser/filebrowser#1750]
there are multiple files in my shared folder
I want to set description like
file01 is for xxx, file02 is for xxx, file03 is for xxx
so visitors can download what they want accordingly
currently there is zip download folder function in place
can I replace that function with folder description

**Comment by niubility000** [comment]
How about just changing the file's name to 'file01_for_xxx'...?

**Comment by niubility000** [comment]
Is it simpler if you just change the file's name to 'file01_for_xxx'...?
