### ISSUE TITLE
Detailed information about upload progress

### ISSUE THREAD

**Issue by jbruned** [filebrowser/filebrowser#1756]
**Is your feature request related to a problem? Please describe.**
The current progress bar doesn't show enough information about the upload.

**Describe the solution you'd like**
The best approach in my opinion is to make a pop-up-like dialog in the bottom right corner (would be great if it could be minimized) showing the files which are currently being uploaded along their individual progress, as well as the total progress (% uploaded). There is an example below (originally posted by @o1egl in https://github.com/filebrowser/filebrowser/issues/1380#issuecomment-825607117). Google Drive has this kind of dialog, too (can be used as an example as well).

<img width="399" alt="Screenshot 2021-04-23 at 13 54 57" src="https://user-images.githubusercontent.com/966539/115867550-8832fa00-a43b-11eb-9462-19801470ceb9.png">

**Comment by o1egl** [comment]
Let's keep a discussion on the original issue
