### ISSUE TITLE
HTML file is not rendered

### ISSUE THREAD

**Issue by shrinandj** [filebrowser/filebrowser#1757]
**Description**
I have some HTML files in my director. I am trying to use filebrowser for this. It works just fine for listing the directories and the files in the directories. However, when I try to open the HTML files, I was expecting them to be fully rendered webpages. Instead, I see the HTML code for these files.

**Expected behaviour**
Fully rendered HTML files should be visible.

**What is happening instead?**
I see the HTML source of the pages.

**Additional context**
<img width="1780" alt="Screen Shot 2022-01-04 at 10 52 01 PM" src="https://user-images.githubusercontent.com/3084759/148173208-3b994681-4de8-4e9f-ab2f-11b0b7472d68.png">

**How to reproduce?**
- Create a directory with one html file.
- Run filebrowser with the `-r <path/to/above/directory>` option.
- Open the filebrowser web ui and try to open the html file above.

FWIW, I am running filebrowser docker image version `v2.20.1-s6`.

**Comment by o1egl** [comment]
It is expected behavior. All text files are opened in the text editor.

**Comment by shrinandj** [comment]
Is it possible to render the html files as webpages? If there is a way, I can see if this feature could be a contributed feature.

I see some file types being detected as image, video, etc. in files.go.

**Comment by alspadoni** [comment]
This feature would be really useful because otherwise I need to add another service to serve statically the HTML files, can we maybe have an option to return the files "raw" so that HTML ones would be rendered?

**Comment by WSL-Ben** [comment]
+1 to this feature. Would you accept a PR implementing it?

**Comment by markusschanta** [comment]
+1

**Comment by ygorelik** [comment]
+1 Need this feature too. Any references to the service implementation?

**Comment by Totoro97** [comment]
+1

**Comment by klapeyron5** [comment]
+1

**Comment by mlzxy** [comment]
+1

**Comment by ryukinix** [comment]
I would like to do something like that.

**Comment by Mj-16** [comment]
+1

**Comment by Rozan1000** [comment]
I need it too

**Comment by superswan** [comment]
+1

**Comment by niubility000** [comment]
The simplest solution is:
Just share this html file. and visit this shared file. click open file. In this way, the browser can render the html files, because it's in public folder now.

**Comment by also-good** [comment]
+1
