### ISSUE TITLE
Support Casbin as the authorization mechanism

### ISSUE THREAD

**Issue by hsluoyz** [filebrowser/filebrowser#176]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (Gorm or Xorm or any popular DBs).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current way. I saw there's a ``Allowed`` method checks the URL with the regex in rule. This kind of matches is already supported by Casbin (see [here](https://github.com/casbin/casbin/wiki/Matchers#functions-in-matchers)). So you can directly use them instead of implementing them on your own. I can provide help on porting to Casbin. Let me know if there's any question:) Thanks.

Btw: Casbin is also the authz middleware for Caddyserver (see: https://caddyserver.com/docs/http.authz). But that plugin primarily mediates the access on HTTP path (RESTful). I'm not sure if it fits for the file path in this project.

**Comment by hacdias** [comment]
Hello @hsluoyz

I thank for the suggestion, but how could it be useful in for File Manager's use case?

**Comment by hsluoyz** [comment]
Hi @hacdias ,

1. Casbin can replace the ``Rule`` and ``Regexp`` structs.  Casbin will manage and store the rules for you. You can use the built-in ``regexMatch()`` function to implement the regex match. See the RESTful example here: https://github.com/casbin/casbin#examples

2. ``AllowNew, AllowEdit, AllowCommands`` boolean values in ``User`` can also be expressed by Casbin rules as action. There are a lot of checkings like this:

```go
if !c.User.AllowNew && r.Method == http.MethodPost {
	return http.StatusForbidden, nil
}

if !c.User.AllowEdit && r.Method == http.MethodPut {
	return http.StatusForbidden, nil
}
```

With Casbin, you don't need to write this kind of checkings in every function. Just need to put Casbin into a filter that filters all requests (Casbin's middelware for web frameworks all work like this). Then pass in user, URL path and r.Method into ``casbin.Enforcer.enforce()``. Casbin will determine whether to allow the access. So you don't need to write security checks in such many places.

3. I don't know why the above regex rule and AllowXXX permission are diverged in filemanager, but in Casbin, they can be in the same form of Casbin policy rules. For example, you can use a Casbin model like this:

```ini
[request_definition]
r = user, path, action

[policy_definition]
p = user, path, action

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.user == p.user && regexMatch(r.path, p.path) && regexMatch(r.action, p.action)
```

The path is the original regex rule matching. And the action is the permission strings like ``AllowNew, AllowEdit, AllowCommands``. We also use regexMatch() here so you can use a grammar like (AllowNew|AllowEdit) to express multiple permissions. I think it's better than ``Permissions   map[string]bool``.

4. Casbin not only simplify things. It also supports a [powerful policy storage](https://github.com/casbin/casbin#policy-persistence) and provides a [full-fledged policy management API](https://github.com/casbin/casbin/wiki/Policy-management). So you will benefit from these features when using Casbin.
