### ISSUE TITLE
Disclosing sensitive information to non-admin users

### ISSUE THREAD

**Issue by devmiek** [filebrowser/filebrowser#1761]
I am sorry that I did not use the issue template.

I found that HTTP endpoint `GET /api/users/{userId}` is disclosing sensitive information to non-admin users. The user information gets through this endpoint has the full path of the user's root directory located on the file system (`scope` property of JSON payload). 

I think this could be a potential security issue. If the attacker is an authorized user, knowing the actual path to the user's root directory may be helpful for the attack.

**Comment by o1egl** [comment]
It is a relative path, so the original path on the server is not exposed

**Comment by ramiresviana** [comment]
The scope can contain a absolute path too.

**Comment by devmiek** [comment]
Thanks for your comment.

If scope is an absolute path, then this endpoint will expose the original path on the server.  I don't know how web frontend app uses scope, but it shouldn't be exposed to non-admin users. Even if scope is a virtual absolute path in the sandbox.

What do you think? Did I misunderstand something?

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/commit/0942fc7042fd949cce91855169d0bcf16eb75771
