### ISSUE TITLE
Permanent sharing of folders

### ISSUE THREAD

**Issue by nic-hanna** [filebrowser/filebrowser#1762]
**Describe the solution you'd like**
I'd like to be able to share a folder permanetly until deleted. I plan on using this as a dropbox alternative so create folders than can be sent to groups of people.

**Describe alternatives you've considered**
At the moment I use 3650 days for 10 years expiry, which works but isn't ideal.

**Comment by niubility000** [comment]
Just leave it empty for permanent share.
