### ISSUE TITLE
404 error after deleting file

### ISSUE THREAD

**Issue by linuxsme** [filebrowser/filebrowser#1763]
**Description**

After deleting the file - the browser shows red color 404  not found report issue"
File Browser 2.20.1

**Expected behaviour**

File deleted confirmation message
**What is happening instead?**

the browser shows red color 404  not found report issue"
**Additional context**

**How to reproduce?**

Upload 9 GB  file
delete the file
**Files**

![404Capture](https://user-images.githubusercontent.com/94956507/148701531-94858470-d84e-4924-8d70-86928938e997.PNG)

**Comment by o1egl** [comment]
Is the file deleted? what is printed in the server logs?

**Comment by linuxsme** [comment]
The file was deleted without any issue.

**Comment by o1egl** [comment]
We need browser/server logs to analyze it
