### ISSUE TITLE
Is it not possible to set the auth method using the settings file?

### ISSUE THREAD

**Issue by JaneJeon** [filebrowser/filebrowser#1766]
I'm looking at this https://github.com/filebrowser/filebrowser/blob/master/docker/root/defaults/settings.json and there's seemingly no option for auth, and the docs seem to suggest that the only way to do this is through the command line.

Is it not possible to set it in the settings file and have filebrowser pick up on it?

e.g.

```json
{
  "auth": {
    "method": "proxy",
    "header": "X-blahblahblah"
  }
}
```

**Comment by o1egl** [comment]
No, you should use cli
