### ISSUE TITLE
Subfolder hierarchy corruption in any chosen archive type (zip etc) when downloading a folder on MacOS

### ISSUE THREAD

**Issue by kostask** [filebrowser/filebrowser#1768]
**Description**
Downloading a folder with subfolders that contain files using any type of compression results in corrupted file hierarchy when de-compressing the downloaded .zip file. This happens in any MacOS client and does not affect Windows PCs.

Testing environment:
Tested with MacOS Mojave 10.14 up to MacOS Monterey 12.1
Tested with the latest version of Web Browsers: Chrome, Firefox and Safari
Tested with version of File Browser 2.15 (ever since we adopted the solution) up to the latest version 2.20.1

**Expected behaviour**
It should work the way it works with Windows, file hierarchy should be maintained, files within a subfolder must remain in their subfolder.

Please see the following screenshot:
![Correct_Appearance](https://user-images.githubusercontent.com/1630695/149147977-934dd345-bd1c-4ef9-89f1-e711416d6abe.png)

**What is happening instead?**
When de-compressing the downloaded archive, files within a subfolder appear outside their subfolder, to the root level/parent folder of the archive, and their filename contains the subfolder name, where originally were located and a slash, like: "subfolder\somefile.txt". This happens recursively with any amount of nested subfolders. Files always end up in the root/parent folder with the path of their original location in their filename! 

Please see the attached screenshots for reference:
![Example_01_One_Level](https://user-images.githubusercontent.com/1630695/149147639-088fc1d7-4ddc-4c3c-aabf-2e3bac82542e.png)

![Example_02_Nested_Folders](https://user-images.githubusercontent.com/1630695/149147808-f04c055f-2e1b-4271-9587-9d4f5f66cf2e.png)

**How to reproduce?**
All you have to do is to download a folder that contains a substantial hierarchy, subfolders with files, using a MacOS client and decompress it.

**Comment by o1egl** [comment]
Is your server running on windows?

**Comment by kostask** [comment]
Hi, thanks for your reply,

Yes, it is running on Windows Server 2019 Standard on VMWare ESXi 7.0

**Comment by mfalconi-perle** [comment]
@kostask  did you solve this? I am having a similar issue
