### ISSUE TITLE
Windows commands for address/port do not work properly

### ISSUE THREAD

**Issue by jenny787** [filebrowser/filebrowser#1773]
When running the command like below on Windows:
filebrowser -r o:/filebrowser -p 8282 -a xxx.yyy.com

it gives the error:
2022/01/14 10:53:41 listen tcp xxx.yyy.com:8282: bind: The requested address is not valid in its context.

Why is it adding that extra colon?  Anyway, I couldn't get anything to work with a custom address.  Without the -a flag, the site only works on 127.0.0.1 and will not resolve to anything.

**Comment by niubility000** [comment]
try this one:
--address 0.0.0.0
