### ISSUE TITLE
Can't login through ipv6

### ISSUE THREAD

**Issue by JIA-Jimmy** [filebrowser/filebrowser#1774]
try to login through ipv6 but doesn't work.

listening on 0.0.0.0 and ::/0
tcp6       0      0 :::80                   :::*                    LISTEN      158636/filebrowser 

Everytime i login with correct account&password the web return 403 Forbidden.

LOG
===========
2022/01/15 22:18:21 /api/login: 403 2409:8a1e:5171:xxxxxxxxx <nil>
2022/01/15 22:18:31 /api/login: 403 2409:8a1e:5171:xxxxxxxxx <nil>
2022/01/15 22:18:32 /api/login: 403 2409:8a1e:5171:xxxxxxxxx <nil>
2022/01/15 22:19:56 /api/login: 403 2409:8a1e:5171:xxxxxxxxx <nil>
2022/01/15 22:19:56 /api/login: 403 2409:8a1e:5171:xxxxxxxxx <nil>
===========

CONFIG.JSON
===========
{
    "address":["0.0.0.0","::/0"],                                  
    "database":"/filebrowser/fbconf/filebrowser.db",
    "log":"/var/log/filebrowser.log",
    "port":80,
    "root":"/root/data",
    "username":"admin"
}
===========

The system is Debian11

**Comment by ixkjje3** [comment]
the same to you
