### ISSUE TITLE
New user settings.

### ISSUE THREAD

**Issue by Yingzzzzz** [filebrowser/filebrowser#1775]
Dear project makers,

I have a problem want to ask, I made a docker file to set the container with command runner, but once I do "init" the database of our filebrowser, I will lose the admin account, in case, I am not able to log in. May I know the code of how to create an account with username and password in dockerfile?

My current docker file looks like this, all the rest is good, but I can't get any account to log in to my localhost filebrowser.

<img width="544" alt="微信图片_20220116221902" src="https://user-images.githubusercontent.com/96532087/149676577-17fe5734-f6cd-4555-b04b-cd34983a73d3.png">

**Comment by ramiresviana** [comment]
The init command will not create the default user, you can use the users command to create a new one: https://filebrowser.org/cli/filebrowser-users-add
