### ISSUE TITLE
Is there any way to change the file to white color?

### ISSUE THREAD

**Issue by Yingzzzzz** [filebrowser/filebrowser#1776]
I have my current custom style fiile, but it changes all the files in filebrowser to same file, I would like to make the folder as yellow color, but txt file or other files as white color, any idea of how to change it by using CSS code in custom file?

example like this 

![image](https://user-images.githubusercontent.com/96532087/149676659-9a78bc05-3c60-44b0-a440-62dcd03f568a.png)

**Comment by niubility000** [comment]
#1698
#1256
https://github.com/jniggemann/filebrowser-css/blob/main/custom.css

**Comment by Teraskull** [comment]
@Yingzzzzz I made a theme https://github.com/Teraskull/file-browser-modern-theme where most icons are changed. You can check the bottom part of `custom.css` to see how the folder and file icons were replaced.
