### ISSUE TITLE
Changing sort by?

### ISSUE THREAD

**Issue by zagi988** [filebrowser/filebrowser#1789]
Hello everyone.

**Is your feature request related to a problem? Please describe.**
It would be really useful if we would be able to have "Sort by" for files and folders.

**Describe the solution you'd like**
An option to select "sort by", date, name, etc...

Maybe I'm not understanding how it all works and that sorting would be impossible because of something?
Or maybe I can set default sorting in command line and am not aware of?

**Comment by niubility000** [comment]
Do you mean this one?
![aaa](https://user-images.githubusercontent.com/76441520/151494491-c53690d1-f7a2-4532-94db-061a42f06865.png)

**Comment by zagi988** [comment]
Huh. The thing is I never used "list" as a type of view and under "grid" there is no way to sort the files. Thanks.
Would be useful to have that option under "grid" too tho. Would take away a few click and a few tens of seconds of waiting time for larger folders.
