### ISSUE TITLE
Cannot start caddy with filemanager ( Windows 64-bit )

### ISSUE THREAD

**Issue by aaboyd** [filebrowser/filebrowser#179]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Downloaded from caddyserver.com about 2 days ago.  Windows 64-bit.

### 2. What is your entire Caddyfile?
Didn't even add in filemanager directive, but it caused a crash.
```text
https://* {
    tls self_signed
    root .
    log logs/access.log
    errors logs/error.log

    # PHP-FPM with regular udp socket
    fastcgi / 127.0.0.1:9123 php {
        index index.php
    }

    # Routing for WordPress
    rewrite / {
        to {path} {path}/ /index.php?{query}
    }

    startup C:\tools\php71\php-cgi.exe -b 127.0.0.1:9123 &
}

```

### 3. What are you trying to do?
I was planning to add the file manager for all the files in the root directory

### 4. What did you expect to see?
Caddy server start.

### 5. What did you see instead (give full error messages and/or log)?
`
panic: could not locate box "./assets/"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0xd4d33c, 0x9, 0xc0421380e0)
        /gopath/src/github.com/GeertJohan/go.rice/box.go:110 +0x9b
github.com/hacdias/filemanager/plugins.init.1()
        src/github.com/hacdias/filemanager/plugins/hugo.go:21 +0x4f
github.com/hacdias/filemanager/plugins.init()
        src/github.com/hacdias/filemanager/plugins/utils.go:20 +0x104
github.com/hacdias/filemanager/caddy/hugo.init()
        src/github.com/hacdias/filemanager/caddy/hugo/setup.go:169 +0x77
github.com/mholt/caddy/caddy/caddymain.init()
        src/github.com/mholt/caddy/caddy/caddymain/run.go:239 +0x8b
main.init()
        src/github.com/mholt/caddy/caddy/main.go:15 +0x4b
`

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Download caddy from caddyserver.com and try to run.

**Comment by hacdias** [comment]
Hey @aaboyd, could you try downloading it again, please? I had that problem some days ago and I fixed it in the meanwhile.

**Comment by aaboyd** [comment]
@hacdias all is good now.  Sorry for the false alarm, my version must have been a bit stale.  Thanks for the quick response.

**Comment by hacdias** [comment]
Yeah, I deployed a version with that bug for like 1 hour and then I changed it. Hopefully no more people downloaded it in that time! 😌
