### ISSUE TITLE
Session lost

### ISSUE THREAD

**Issue by thewh1teagle** [filebrowser/filebrowser#1791]
Hi
I don't know why, but every day I try to get into the system from the browser, I need to enter username and password again.
maybe it because of restart or something like that. 
but this app should store the session, and and not let me enter the user and password every time.

**Comment by ramiresviana** [comment]
The session expiration time is 2 hours, accessing the app will reset the timer.

**Comment by thewh1teagle** [comment]
@ramiresviana 
How can I disable this timer?

**Comment by niubility000** [comment]
> How can I disable this timer?

You can change it yourself:
in http/auth.go

const (
	TokenExpirationTime = time.Hour * 2
) 

You can change 2 to whatever you want.

**Comment by thewh1teagle** [comment]
@niubility000 
Thanks

**Comment by Brancliff** [comment]
> > How can I disable this timer?
> 
> You can change it yourself: in http/auth.go
> 
> const ( TokenExpirationTime = time.Hour * 2 )
> 
> You can change 2 to whatever you want.

Hey! Could I get some more elaboration on this? Noob question here - is this, like, a command to enter? Where should I enter it? Is it a file? Where would that be? Running version v2.22.1 on docker (just pulled an image today).

**Comment by QisFj** [comment]
> Hey! Could I get some more elaboration on this? Noob question here - is this, like, a command to enter? Where should I enter it? Is it a file? Where would that be? Running version v2.22.1 on docker (just pulled an image today).

that is Golang code, looks like we have to change the source code to change expiration time. 

i run it by Docker, too. change the source code is hard to manage.  hope can support a arg or cfg to customize it

**Comment by m4heshd** [comment]
It's mind-blowing that there's no configuration to set this.

**Comment by collatdam** [comment]
Any progress on this?

**Comment by WolfgangDpunkt** [comment]
any news here? This is so often asked :-)

**Comment by DarthJahus** [comment]
For large downloads, or for convenience, you can extend the session by increasing the JWT token expiration with the `--token-expiration-time` flag.

## Docker / s6
In your `docker-compose.yml`, add:

```yaml
command: s6-setuidgid abc filebrowser -c /config/settings.json --token-expiration-time 48h
```

This preserves s6 init, permissions, and config (check file: [docker/s6/etc/services.d/filebrowser/run](https://github.com/filebrowser/filebrowser/blob/master/docker/s6/etc/services.d/filebrowser/run))
