### ISSUE TITLE
Multi user setup ( unique uid/gid ) per user

### ISSUE THREAD

**Issue by bluesky-ca** [filebrowser/filebrowser#1793]
I am thinking of ways to integrate filebrowser into a setup where there are multiple users with home directories on a server (e.g. NFS) and credentials stored in ldap - using Nginx/Authelia (or another SSO ) as a front-end, and having a script for the before and after commands that does the chown/chgrp on the files/dirs should work ( and should avoid any double copy of files ie the file can go directly to the user's home directory ) - for all this to work filebrowser has to run as root ( maybe inside a chroot given that it is a static binary and does not need any libs, chroot would be very simple to setup )

Has anybody implemented a setup like this, if yes did it work well ?  Are there better methods to crate a multi user configuration where each user's home dir has different uid/gid as defined by /etc/{passwd,group} or taken from ldap ?

We use Nextcloud, but would be interested in finding a very fast file transfer to complement it - based on my benchmarks filebrowser matches scp performance and is a number of times faster compared to Nextcloud upload.   I understand the focus of this project is not Enterprise, so I don't want to suggest any changes - makes sense to keep it small and fast.

**Comment by ramiresviana** [comment]
Filebrowser does not manipulate permissions, it uses the privileges of the process owner to access/create files. You can use the command runner (https://filebrowser.org/configuration/command-runner) to change files permissions when they're created.  Currently no event is triggered when a user creates a directory.

There's no ldap integration, you will need to use the proxy header method (https://filebrowser.org/configuration/authentication-method#proxy-header) and use another server to handle the authentication. There's a proposal for a authentication hook (https://github.com/filebrowser/filebrowser/pull/1554) that would allow to integrate Filebrowser with other systems, but that feature is not very demanded and probably wont be available soon.
