### ISSUE TITLE
Is there a way to upload or download use multiple threads?

### ISSUE THREAD

**Issue by JerryLiew** [filebrowser/filebrowser#1795]
first of all, thanks for your work. ,because ,i like this tools very much. and have used it for a period,
but now i have a question. i have more than one broadband, and i have made  broadband multi dial,Is there a way to upload or download use multiple threads so that i can use all my broadband to accelerated the download and upload speed?
thanks a lot

**Comment by o1egl** [comment]
You can copy the download URL and pass it to some download manager. It is not possible to do a parallel upload

**Comment by JerryLiew** [comment]
thanks a lot,i've tried,it works. but This method can't achieve the goal.
