### ISSUE TITLE
upload function nor drag & drop works when uploading over public url

### ISSUE THREAD

**Issue by EytanMorg** [filebrowser/filebrowser#1796]
**Description**

trying to upload a mp4 clip to the fileserver while connecting the public url (subdomain.domain.com) gives an "empty" error popup

**Expected behaviour**

upload mp4 file to file storage

**What is happening instead?**

A red popup with [object Object] spawns
![image](https://user-images.githubusercontent.com/12435345/152378120-5555d9b2-0ae6-4978-b180-4a0d266bf60d.png)

**Additional context**

Uploading used to work without a hitch, but recently changed to hosting through Caddy
uploading over public url (subdomain.domain.com) does not work and spawns aforementioned message
uploading over local url (192.168.x.x:p) works without a problem

**How to reproduce?**

1. host filebrowser through caddy 
2. goto public url
2. log in with non-admin user account. 
3. try to upload file through upload button
4. or upload by drag & drop

**Files**

n/a

**Comment by ramiresviana** [comment]
Please provide client and server logs. Since Filebrowser is working fine alone, looks like your issue is related to Caddy.

**Comment by EytanMorg** [comment]
when uploading the file:
Fileserver log:
2022/02/03 15:45:48 /api/renew: 403 public_IP <nil>
2022/02/03 15:57:12 /api/renew: 403 192.168.1.130 <nil>

caddy logs:
2022-02-06T08:40:56.625179821Z {"level":"info","ts":1644136856.6250212,"logger":"tls","msg":"finished cleaning storage units"}
2022-02-06T08:40:56.623456190Z {"level":"info","ts":1644136856.6232328,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
2022-02-05T08:40:56.562152071Z {"level":"info","ts":1644050456.5619967,"logger":"tls","msg":"finished cleaning storage units"}
2022-02-05T08:40:56.560356309Z {"level":"info","ts":1644050456.5601523,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}


also the time in the logs seems off but when using the "time" command through the terminal the date/time is the same for both machines and my computer

n.b.: it only seems to occur with multi media files, no uploading issues with text/pictures/documents, only a problem with videos

**Comment by o1egl** [comment]
There is probably something wrong with your caddy config

**Comment by EytanMorg** [comment]
The issue was neither caddy nor fileserver. Apparently there is a limit on file sizes when using cloudflare's proxy (100mb).
The message that in the red popup does show it's content when using Chrome (error 413, file size too big | cloudflare) but not in firefox,( where it shows object,object) which I was using at the time when creating this ticket. 

I think you can close this ticket,
