### ISSUE TITLE
Dockerfile and image issue

### ISSUE THREAD

**Issue by myset** [filebrowser/filebrowser#1798]
**Description**

When I change the defult port 80 or when I configure TLS SSL on port 443 container health status wrong because
`HEALTHCHECK --start-period=2s --interval=5s --timeout=3s \
  CMD curl -f http://localhost/health || exit 1`

**Expected behaviour**

Healthy container on different ports, based on different criteria or drop healthcheck

**What is happening instead?**

Container is not healthy and try continuously unsuccessfully health check

**How to reproduce?**

Edit .filebrowser.json and change the port with other than 80

**Comment by ramiresviana** [comment]
The default healthcheck will only work with HTTP, see #1487.

**Comment by myset** [comment]
That why I propose to drop default health-check from Dockerfile.

**Comment by o1egl** [comment]
What is the use-case of changing the port within a docker container?

**Comment by alvaroaleman** [comment]
@o1egl for example not wanting to run it as root or give cap_net_admin. Could this get addressed, please?
