### ISSUE TITLE
Dockerfile change default configurations location and filbrowser binary location

### ISSUE THREAD

**Issue by myset** [filebrowser/filebrowser#1799]
**Description**

There are some constrains in Docker environment regarding custom files (Ex. .filebrowser, database.db and filebrowser) stored in root I mean /

**Expected behaviour**

Please take into consideration the following changes:
1. Change Dockerfile in order to copy .filebrowser.json into /etc/filebrowser/
2. Change Dockerfile in order to copy database.db into /etc/filebrowser/
3. Change Dockerfile in order to copy filebrowser binary into /usr/bin

**How to reproduce?**

Try to map a speciffic .filebrowser.json from your local system to /.filebrowser.json @ the container creation
-v $HOME/.filebrowser/.filebrowser.json:/.filebrowser.json
-v $HOME/.filebrowser/database.db:/database.db

**Comment by o1egl** [comment]
We already have linuxserver based [docker image](https://github.com/filebrowser/filebrowser/blob/master/Dockerfile.s6). You can find an example cli command in the [docs](https://filebrowser.org/installation#docker)
