### ISSUE TITLE
Upload files button on empty folder

### ISSUE THREAD

**Issue by zagi988** [filebrowser/filebrowser#1800]
Hi. I've made one account called "share" that only has scope of one folder and simple pass. Also, can only download and create/upload files.

Is there a possibility to have a upload files button under "It feels lonely here..."?

Point is, I use that acc to get files from someone and current UI isn't really intuitive for stuff like that.
Upload button is somewhat hidden and without label so I always have to explain how to upload. This button would make stuff so much easier and is somewhat logical to have it there. 

Can I modify something to get the button there or would developers be interested to put it there?

**Comment by ramiresviana** [comment]
No upload button is displayed when the directory is empty. Files can be uploaded by clicking on the header upload icon or dragging and dropping.

**Comment by zagi988** [comment]
Yes, I understand that there is no upload button displayed. That is exactly what I am asking for here.

There is no indication that files can be dragged and dropped to upload and upload icon is barely noticeable since it's just an icon without any text.

**Comment by zagi988** [comment]
So, is there a chance that this will be considered as a new feature?

**Comment by zagi988** [comment]
No?

**Comment by zagi988** [comment]
Shouldn't be stale because no one answered about this.
