### ISSUE TITLE
Bold Progress bar 

### ISSUE THREAD

**Issue by maniCitizen** [filebrowser/filebrowser#1801]
expecting a bold Progress Bar to be visible normally for a clear view.

**Comment by niubility000** [comment]
Just simple change   height: 3px to 9px in src/css/base.css,

```
#progress {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 9px;
  z-index: 9999999999;
}
```
![2022-02-07 140032](https://user-images.githubusercontent.com/76441520/152733314-4a29c8c0-9bb7-4eb6-90ed-cef7a1ab5fe1.png)

**Comment by maniCitizen** [comment]
Thanks a lot , man. one more request ? can we add a speed-o-meter/transfer speed in progress bar !.

**Comment by o1egl** [comment]
@maniCitizen you can follow this thread https://github.com/filebrowser/filebrowser/issues/1380

**Comment by maniCitizen** [comment]
> Just simple change height: 3px to 9px in src/css/base.css,
> 
> ```
> #progress {
>   position: fixed;
>   top: 0;
>   left: 0;
>   width: 100%;
>   height: 9px;
>   z-index: 9999999999;
> }
> ```
> 
> ![2022-02-07 140032](https://user-images.githubusercontent.com/76441520/152733314-4a29c8c0-9bb7-4eb6-90ed-cef7a1ab5fe1.png)

i not able to find the directory src/css/base.css , bcoz i started it from bin file (a single excutable file)

**Comment by maniCitizen** [comment]
> @maniCitizen you can follow this thread #1380
yah..man i got it ..thank you...i waiting for the update/feature as you suggest .
https://github.com/filebrowser/filebrowser/issues/1380#issuecomment-825607117
