### ISSUE TITLE
Privilege Escalation: `key` used to protect JWT is stored in config db

### ISSUE THREAD

**Issue by janstarke** [filebrowser/filebrowser#1805]
As soon as a limited user is able to access the config db via `filebrowser`, she can read the secret key from the configuration database and can spoof a JWT.

In a test on our side, we ware able to create a valid JWT using <https://jwt.io> and this very `key` for a privileged user. This spoofed JWT was accepted by `filebrowser`.

This finding is at least valid for v2.17.2 v2.5

I suggest that the key should only be stored in memory. Otherwise, You must make sure that the configuration database MUST NOT be read by `filebrowser` users.

**Comment by o1egl** [comment]
You must not put the db file into the directory which is served by filebrowser. The path to the database can be changed by `-d` param.

**Comment by janstarke** [comment]
Yeah, you're absolutely right. I found this issue during a penetration test on a customer system and did the same recommendation.

However, it may be possible that administrators of filebrowser do this minimal misconfiguration of letting users download the database. I think we should either
 - prohibit the download of the database in a technical way or
 - document that administrators must take care that this database must not be accessible via filebrowser

Both ways are not easy and may not be 100% effective, so I thought that storing the key in memory would be the most efficient way of solving the issue.

**Comment by o1egl** [comment]
Getting access to the db file means that anyone can simply change the admin password. There is no sense to protect jwt key in that case :)

**Comment by janstarke** [comment]
Sorry, but this is not correct. Getting _read_ access to the db file _does not_ mean that someone could change anything in it. But if getting _read_ access allows an attacker to elevate his privileges to obtain _write_ access finally, this is called a privilege escalation and is a vulnerability for its own.

Second: It makes always sense to protect a key. Especially, if the actions required for protection are cheap. You should not rely on one single security measure (e.g. storing the db file in a folder not accessible by the filebrowser user) to be effective. If you have a cheap way to introduce one additional layer of defense, you should do this.
