### ISSUE TITLE
add minio as file storage

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1809]
**Is your feature request related to a problem?**
No.

# Feature: Minio storage

A awesome feature would be to add [minio](https://min.io) as file storage. For this need there exists a [golang-client package](https://github.com/minio/minio-go). With this integration you can run filebrowser in professional way and the data is stored securely in a minio bucket.

Please let me know, what you think about this idea?

**Comment by o1egl** [comment]
Filebrowser uses https://github.com/spf13/afero as a filesystem abstraction layer. S3 support can be added after adding it to the afero package.

**Comment by Zetanova** [comment]
In afero S3 is under "Desired/possible backends" topic.

Is there a simple solution to use S3 storage like aws, minio or storj ?

**Comment by pinpox** [comment]
Seems to be supported via backend in afero: https://github.com/chonthu/aferoS3

**Comment by calvintwr** [comment]
are there any documentation for this?

**Comment by pinpox** [comment]
> are there any documentation for this?

I only know what I could figure out from the repository. Not involved in the development of the project personally.
