### ISSUE TITLE
Disabling Auth

### ISSUE THREAD

**Issue by martinbaillie** [filebrowser/filebrowser#181]
I have pulled the latest version of Caddy and the file manager plugin. Is there a way to disable the new auth features via Caddy directives? I have no desire for them (I front Caddy with an authenticating proxy already).

**Comment by hacdias** [comment]
I'll think about creating an option for that. Right now it is not possible in any way.

**Comment by hacdias** [comment]
Hello @martinbaillie! Now available on caddyserver.com. Just add the option _no_auth_ to the Caddyfile 😄

**Comment by martinbaillie** [comment]
Works perfectly @hacdias. Appreciate your quick turnaround on this and thanks for the great plugin!👍

**Comment by hacdias** [comment]
NP 😄 I'm the one who should thank you.
