### ISSUE TITLE
[FeatureRequest] please! Smarter Command Runner

### ISSUE THREAD

**Issue by CodeAnthem** [filebrowser/filebrowser#1810]
Hello, Im not sure if it was meant for things like this. But I'd like to restart a docker container, when it's config file was saved via filebrowser. As an example: 
`if [[ $FILE = /srv/docker/serviceName/* ]]; then docker restart service; fi`
unfortunately its not working. Could you maybe imlement this? 

I use filebrowser only to edit config files, which other users have no access to and many docker containers don't support dynamic config. So I have to start the SSH connection everytime to restart the service. Would be quite handy, if you could add this.

**Comment by o1egl** [comment]
By default, File Browser executes the commands by calling their binaries directly. If you want to run them on a shell instead (such as Bash or PowerShell) you need to define it in `Settings -> Global Settings -> Execute on shell`
Also, you need to put this script into a file and use that file as a hook

**Comment by CodeAnthem** [comment]
Hello, Thanks for the help.

I'have changed the execute on shell to: `/bin/bash`

Wrote a small script:
```
#!/bin/bash
if [[ -z $1 ]]; then 
    echo "No parameter passed."
    exit
fi

case  $1  in
    /srv/docker/authelia/*)     
        docker restart authelia
        echo "Authelia restarted"
    ;;
    *)  
        echo "Service not found"
esac 
```

and added this line to **After Save**:  `/srv/docker/file-browser/scripts/restartService.sh $FILE`

It still doesn't work, I get the error message:
```
2022/02/09 02:35:45 [INFO] Blocking Command: "/bin/bash /srv/docker/file-browser/scripts/restartService.sh /srv/docker/authelia/test.txt"
2022/02/09 02:35:45 /docker/authelia/test.txt: 404 10.0.0.13 fork/exec /bin/bash: no such file or directory
```

What do I wrong here? I run out of ideas.

PS: for branding I use this path: `/srv/docker/file-browser/custom` and that works just fine

**Comment by o1egl** [comment]
It should be `/bin/bash -c`

**Comment by CodeAnthem** [comment]
I can't get it to work with bash. Probably because I run filebrowser in a docker container and I'm not sure if its smart to mount the whole root to the container. But I got it working with SH. The only issue right now is, I can't access the docker command to restart services. Do you have any idea how I can solve this? Would be really handy if filebrowser can restart docker services. Thanks for your help.

**Comment by o1egl** [comment]
If you are running filebrowser as a docker container neither bash nor docker is installed by [default](https://github.com/filebrowser/filebrowser/blob/master/Dockerfile). You can build a custom image with required cli tools using filebrowser/filebrowser as a base one
