### ISSUE TITLE
SMB/CIFS share

### ISSUE THREAD

**Issue by donluca87** [filebrowser/filebrowser#1823]
Is there the possibility to a add in someway samba sharing management feature ? It could be a great option to have in FileBrowser.

**Comment by zagi988** [comment]
Why? How would that work? SMB is mostly for local sharing and if you want to share something locally there are literally tens of ways how to do that on any OS.

**Comment by donluca87** [comment]
Let's say I'd use a container on which are installed both filebrowser and
samba, it would be awesome to have the possibility to set the samba sharing
configuration on files and folders (like you do in trueNAS or OMV but
solutions like these are too much low level compared to a container one and
ofc they cannot run in containers, FileBrowser does).

**Comment by o1egl** [comment]
We don't plan to add smb/cifs support to this project in the feasible future

**Comment by TCB13** [comment]
> Let's say I'd use a container on which are installed both filebrowser and samba, it would be awesome to have the possibility to set the samba sharing configuration on files and folders (like you do in trueNAS or OMV but solutions like these are too much low level compared to a container one and ofc they cannot run in containers, FileBrowser does).

I guess that's kind out of scope of this project...
