### ISSUE TITLE
panic: While parsing config: unexpected end of JSON input

### ISSUE THREAD

**Issue by sshuangliu** [filebrowser/filebrowser#1824]
**Description**

I faced that issue when I deployed the filebrowser with docker on pi 3B+

the docker log:

panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x3ec
github.com/spf13/cobra.(*Command).preRun(0x12f4b20)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x40
github.com/spf13/cobra.(*Command).execute(0x12f4b20, {0x249e108, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x12f4b20)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x20
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x24

my environment：

Pi3 B+ ARMv7 32bit 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux
Docker version 20.10.12, build e91ed57

docker run \
	--name filebrowser \
    -v /mnt/usb_flash:/srv \
    -v /mnt/usb_flash/filebrowser/filebrowser.db:/database.db \
    -v /mnt/usb_flash/filebrowser/.filebrowser.json:/.filebrowser.json \
    -u $(id -u):$(id -g) \
    -p 802:80 \
    filebrowser/filebrowser

so what did might happen here and why ?
many thank

**Comment by iruochen** [comment]
I also encountered this problem.

**Comment by o1egl** [comment]
It says it can't read the json file. Have you tried to run it with the default config?
```
docker run
--name filebrowser
-p 802:80
filebrowser/filebrowser
```

**Comment by iruochen** [comment]
This is my run command

docker run -d \
    -v /var/www/pan:/srv \
    -v /var/www/filebrowser/database/filebrowser.db:/database/filebrowser.db \
    -v /var/www/filebrowser/config/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -p 8080:80 \
    --name=share \
    --privileged=true \
    --restart always \
    filebrowser/filebrowser:s6

Before running, I have touch filebrowser.db and settings.json
My system is centos7.6. Error report after operation panic: While parsing config: unexpected end of JSON input
I have not tried to run it with the default config. I want to map the configuration file

**Comment by ramiresviana** [comment]
> panic: While parsing config: unexpected end of JSON input

Filebrowser expects a valid JSON structure on the config file, empty files are invalid.

**Comment by sshuangliu** [comment]
> 

it works when I run with the default configuration

Details are as follows：
pi@raspberrypi:~$ docker run --name filebrowser -p 802:80 filebrowser/filebrowser
2022/02/15 12:47:57 Using config file: /.filebrowser.json
2022/02/15 12:47:57 Listening on [::]:80
2022/02/15 12:48:29 /api/login: 403 192.168.88.77 <nil>

![image](https://user-images.githubusercontent.com/38092313/154066236-f80e806d-e63a-4217-8e38-0fd6eeebcb11.png)

![image](https://user-images.githubusercontent.com/38092313/154065524-a9d1c261-56b7-443b-a69a-90223be0d1af.png)


Maybe the problem is how to mount single file beween host and container

**Comment by iruochen** [comment]
> > 恐慌：解析配置时：JSON输入意外结束
> 
> Filebrowser 需要配置文件上的有效 JSON 结构，空文件无效。

Thank you. That's true

**Comment by sshuangliu** [comment]
hi, guys 
it works after I did the follow steps:

**step1:**
set up  a filebrowser with the default config
docker run -d --name filebrowser11 -p 803:80 filebrowser/filebrowser

**step2:**
copy files that we need from the inside container to host
sudo docker cp filebrowser11:/database.db /mnt/usb_flash/filebrowser/
sudo docker cp filebrowser11:/.filebrowser.json /mnt/usb_flash/filebrowser/

**step3:**
check if there are files  on the host
ls -la /mnt/usb_flash/filebrowser/
$ ls -la /mnt/usb_flash/filebrowser/
total 76
drwxr-xr-x  2 root root  4096 Feb 15 22:37 .
drwxr-xr-x 11 pi   pi    4096 Feb 15 22:57 ..
-rw-------  1 root root 65536 Feb 15 22:56 database.db
-rw-r--r--  1 root root   117 Dec 21 22:14 .filebrowser.json



**step4:**
deploy the filebrowser container with yourself config with root id :
docker run \
	--name filebrowser \
	-v /mnt/usb_flash:/srv \
    -v /mnt/usb_flash/filebrowser/database.db:/database.db \
    -v /mnt/usb_flash/filebrowser/.filebrowser.json:/.filebrowser.json \
    -u 0:0 \
    -p 802:80 \
    filebrowser/filebrowser

finally ,it works 
but we need to notice the right of files, database.db and  .filebrowser.json, 
we can modify  it if need

**Comment by o1egl** [comment]
As @ramiresviana mentioned, your json config file, that you mounted initially was empty. I think we can close this issue

**Comment by Michael-Fletcher** [comment]
This is the content of .filebrowser.json created by the system on first run. Populate your .json with it. This step shouldn't be necessary, it's making and filling a text file.  Please fix.  

```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```
