### ISSUE TITLE
Add file count in folder info

### ISSUE THREAD

**Issue by Arryboom** [filebrowser/filebrowser#1828]
Hi Thanks for create this great tool,would you like to add file count in folder info page?so we can check how many files in a folder,sometimes upload may failed and if we can compare how many files between local and remote it will be easy,and if we has size count on folder its clearly alot benefit

**Comment by ramiresviana** [comment]
Number of files is displayed on the Information panel, you can open it by clicking on the info icon in the head bar.

**Comment by Arryboom** [comment]
> Number of files is displayed on the Information panel, you can open it by clicking on the info icon in the head bar.

oh,yea its here,didnt know this before,I was 
1.single click on the folder to make the folder as selected state
2.click the info icon and check folder info and got 
![image](https://user-images.githubusercontent.com/28295452/154799850-2ba78209-ee84-4c7a-8dca-e90359545974.png)


this,and the title in this small window is file(but it actually a directory),so I thought there has no file count info before,thanks for direction!
