### ISSUE TITLE
When editing a user, the directory scope is not displayed.

### ISSUE THREAD

**Issue by y1jiong** [filebrowser/filebrowser#1834]
**Description**

When editing a user, the directory scope is not displayed.

**Expected behaviour**

When editing a user, the directory scope is displayed.

**What is happening instead?**

Directory scope not shown.
![image](https://user-images.githubusercontent.com/59520517/155068873-74ebefca-4443-4413-bb9a-3f8e2fad5d24.png)

**Additional context**

As above.

**How to reproduce?**

Visible on latest version v2.21.0.

**Files**

without

**Comment by parsa20001999** [comment]
> **Description**
> 
> When editing a user, the directory scope is not displayed.
> 
> **Expected behaviour**
> 
> When editing a user, the directory scope is displayed.
> 
> **What is happening instead?**
> 
> Directory scope not shown.
> ![image](https://user-images.githubusercontent.com/59520517/155068873-74ebefca-4443-4413-bb9a-3f8e2fad5d24.png)
> 
> **Additional context**
> 
> As above.
> 
> **How to reproduce?**
> 
> Visible on latest version v2.21.0.
> 
> **Files**
> 
> without
>
