### ISSUE TITLE
Using Filebrowser on an RCLON Mount results in "Something really went wrong." with Folders that have numerous Files in them.

### ISSUE THREAD

**Issue by NightHammer1000** [filebrowser/filebrowser#1836]
**Description**
Trying to use Filebrowser on a folder that is on a RClone Mount results in a "Something really went wrong." message when the folder has more than ~200 Files in it.

**Expected behaviour**
Files should be listed.

**What is happening instead?**
Nothing is shown at all except "Something really went wrong."

**Additional context**
I do belive this has to do with how Filebrowser lists the Content of that Folder. It runs in some kind of Timeout because it naturally takes longer to look into every single file on an Cloud Mount.
A normal "ls" or "ll" gives me the Result instantly because of my Caching Setup.
I watched what my system is doing with "Netdata" and noticed something.
Opening the folder inside Filebrowser results in IOWait. Which is normal for a Cloud Mount, but only when opening files from the Mount.
But everything needed from the File to be listed should be retrievable from my local cache just like "ls" or "ll" does.

If Filebrowser does indeed open the files to read more Info, a Light Mode for specific Folders, which only builds the List from "ls" or "ll" would be worth to think about in the future.

**How to reproduce?**
Put a Folder with many small files on an RClone Google Drive Mount. (Like a Rom-Set or something like that)
Start Filebrowser and try to access the Folder. 
It will fail.

**Comment by o1egl** [comment]
If you have images there, filebrowser reads them to make thumbnails

**Comment by NightHammer1000** [comment]
Nope. Just ZIPs inside there. Nothing more

The one Folder i tried it with has around 600 zip files inside of it.

In comparison, NGINX with Fancyindex displays the folder in a fraction of a second.

**Comment by Fukitsu** [comment]
I had the same problem and read in another issue about enabling ``--disable-type-detection-by-header``. With it it displays the files without problem

**Comment by NightHammer1000** [comment]
Indeed it does!

Nice find. Thanks!

**Comment by alfablac** [comment]
btw, this is true for general files, one folder with 2k txt files loads instantly, a folder with 600 video files won't, even with all disable flags of filebrowser
