### ISSUE TITLE
Batch delete users

### ISSUE THREAD

**Issue by danny2jenny** [filebrowser/filebrowser#1837]
I hava about 150 students a year. And I made a filebrowser server for them to upload homeworks. Next year, I need delete their accounts one bye one. 

If you can provide a feature for fatch deleting users?

I'm very appreciated, thanks.

btw, #1700 is also very useful.

**Comment by o1egl** [comment]
You can use cli for that
1. Stop filebrowser app to unlock the database file
2. run `filebrowser users ls | tail +2 | awk  -F '[[:space:]]+' '{if ($1 != 1) {print $1}}' | xargs -I "{}" filebrowser users rm {}`

**Comment by danny2jenny** [comment]
Thanks, I'll try this.
