### ISSUE TITLE
You cannot directly drag and drop folders to upload, and you cannot upload multiple folders at the same time.

### ISSUE THREAD

**Issue by y1jiong** [filebrowser/filebrowser#1839]
**Description**

You cannot directly drag and drop folders to upload, and you cannot upload multiple folders at the same time.

**Expected behaviour**

Drag and drop folders to upload directly, upload multiple folders at the same time

**What is happening instead?**

Uploading folders is harder than before.

**Additional context**

Without.

**How to reproduce?**

Anytime on v2.21.1.

**Files**

Without.

**Comment by y1jiong** [comment]
Can someone respond?

**Comment by ramiresviana** [comment]
This issue was introduced on v2.21.0, you can use a previous version until its fixed.
