### ISSUE TITLE
i18n for Static Generators, like Hugo

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#184]
That ^

**Comment by hacdias** [comment]
@ToyoDAdoubi, I've got some new stuff for you (https://github.com/hacdias/filemanager/commit/da4fd84002f4cac1d4e04f65c96237a553203d83#diff-fe6ccd8f0bf41f00b9ff5d61b8e0e3e9) 😄 Thank you!

p.s.: the 'hugoNew' thing is related to this: http://gohugo.io/

**Comment by ghost** [comment]
@hacdias 
Also, why is there "post"?
Functional misunderstanding can cause translation barriers.

**Comment by hacdias** [comment]
Hello, Hugo New will only show up when the user activated the Hugo module (a static website generator). Hugo New is a command of Hugo CLI so I think that the best option is to leave it as it is. 

Post is not the verb, but the name (equivalent to article).

**Comment by ghost** [comment]
@hacdias complete!
Before specific function is not clear, it may be not accurate enough.
https://github.com/hacdias/filemanager/pull/196

**Comment by hacdias** [comment]
Thanks 😄
