### ISSUE TITLE
Running "Filebrowser" from service file after configuring DB doesn't work

### ISSUE THREAD

**Issue by TinyBabyOwl** [filebrowser/filebrowser#1840]
**Description**
I set up some initial configuration with `filebrowser config set etc` and then set up a systemd service file for filebrowser to simply run `filebrowser`. When running it this way filebrowser complains about no config file, and tries to start up on a port other than what I set when I ran config. 

**Expected behaviour**
Filebrowser to run the same way as when you only enter `filebrowser` into terminal after setting config.

**What is happening instead?**
`ExecStart=filebrowser` in a service file expects config flags and runs on the default port

**How to reproduce?**
1. Run `filebrowser config set` and set up whatever config options you need. Then run `filebrowser` from terminal. It will launch and use the configuration set previously. 
2. Create a systemd service file and set the `ExecStart=filebrowser`. Run the service file from systemd and it will fail expecting a config file.

**Comment by MiranDaniel** [comment]
I also have this issue
