### ISSUE TITLE
Error when trying to upload file of any size

### ISSUE THREAD

**Issue by TigerRusso** [filebrowser/filebrowser#1844]
**Description**

When trying to upload the file it does not load properly. Getting 0 bytes or corrupted.
![image](https://user-images.githubusercontent.com/68338124/156442694-c0a4775c-e617-4ba6-aeed-2ddaf8db6c4d.png)

![image](https://user-images.githubusercontent.com/68338124/156443000-c92de0dd-92e7-456d-9824-0d02dda54b0c.png)

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration and logs.
