### ISSUE TITLE
provide a way to tar or zip a folder with or without compression.

### ISSUE THREAD

**Issue by finalcreator** [filebrowser/filebrowser#1847]
In order to take advantage of cdn, folder with a lot of trivial files should be convert to one file for downloading

**Comment by ramiresviana** [comment]
The current implementation uses the default value from the `compress/flate` package for the compression level.

**Comment by finalcreator** [comment]
> The current implementation uses the default value from the `compress/flate` package for the compression level.

how to zip folder in the web GUI or any command?

**Comment by ramiresviana** [comment]
You can control which commands are allowed on the shell by adding them to the commands fields available on the user settings.

**Comment by finalcreator** [comment]
Thanks.
I create a alias in .bashrc, but can not find in shell:
exec: "t": executable file not found in $PATH

**Comment by o1egl** [comment]
Command runner doesn't use bash for running commands

**Comment by finalcreator** [comment]
> Command runner doesn't use bash for running commands

How about create a executable shell in the "path"? Where is the path exactly?

**Comment by o1egl** [comment]
Not sure I understood what you meant

**Comment by finalcreator** [comment]
> Not sure I understood what you meant

 just want to easeliy easily tar a folder into a single file , in order to take advantage of CDN in downloading

**Comment by Goldmaster** [comment]
Would nice to have this feature where you can zip or tar files with different options such as add a password

**Comment by Goldmaster** [comment]
Any eta? Of if this is a possibility? Wonder if a 7zip integration would work?

**Comment by finalcreator** [comment]
> Any eta? Of if this is a possibility? Wonder if a 7zip integration would work?

it seems no GUI button will do the work in the future. We have to run zip command ourself

**Comment by zagi988** [comment]
It would be great if there were any documentation on where the commands have to be.
For instance, I have allowed "ls pwd 7z" and only ls and pwd are working, even tho 7z is in the same folder.
How is that possible?

**Comment by finalcreator** [comment]
> It would be great if there were any documentation on where the commands have to be. For instance, I have allowed "ls pwd 7z" and only ls and pwd are working, even tho 7z is in the same folder. How is that possible?

You can use zip instead. However you must configure this in "User Management" and modify user (little pen), and then put "7z" in "Commands" text box
