### ISSUE TITLE
exec: "my command": executable file not found in $ PATH

### ISSUE THREAD

**Issue by marcuzz0** [filebrowser/filebrowser#1848]
Hi,

i have a script in bash that executes commands, how do i run it from the toggle shell?
It returns me an error like this:

exec: "my command": executable file not found in $ PATH

Actually the command is in the path

**Comment by o1egl** [comment]
How are you running the app? If you use docker, you must install your binaries manually

**Comment by marcuzz0** [comment]
Ok tks
