### ISSUE TITLE
Crash when uploading large folders

### ISSUE THREAD

**Issue by PrzemekSkw** [filebrowser/filebrowser#1853]
OS: DietpiOS (Debian 11), kernel 5.10
Docker installation from Dockstarter

**Description**
File Browser crash when uploading large folders (more that 4GB I think). Browser dashboard stops at popup window when I choose File or Folder.
**Expected behaviour**
Upload whole folder.

When I upload folder about 1,5GB everything looks OK but after uploading I see endless loop of that error, cannot close that because always new popup window appear:
![Zrzut ekranu z 2022-03-07 09-01-49](https://user-images.githubusercontent.com/25219988/156991357-0859dc15-2319-4b23-ae22-fa7d16f90b40.png)

Regards.

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration and logs.

**Comment by PrzemekSkw** [comment]
Hi @ramiresviana, thanks for answer. In Dockstarter I find that file
```
~/.docker/compose/.env

FILEBROWSER_BASEURL='/file'
FILEBROWSER_DATABASE='/config/database.db'
FILEBROWSER_ENABLED='true'
FILEBROWSER_LOG='/config/filebrowser.log'
FILEBROWSER_NETWORK_MODE=''
FILEBROWSER_PORT_80='8070'
FILEBROWSER_RESTART='unless-stopped'
FILEBROWSER_SHARE_DIR='~/.config/appdata/filebrowser/share'
```
I see in docker-compose logs only that:
```
dietpi@DietPi:~/.docker/compose$ docker-compose logs filebrowser
Attaching to filebrowser
filebrowser    | 2022/03/07 07:21:29 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:31 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:33 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:34 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:36 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:38 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:42 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:21:50 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:22:03 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:22:30 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:23:21 open /config/database.db: permission denied
filebrowser    | 2022/03/07 07:24:01 Using config file: /.filebrowser.json
filebrowser    | 2022/03/07 07:48:41 Using config file: /.filebrowser.json
dietpi@DietPi:~/.docker/compose$
```
I don't know why there's no more logs.
Regards.

**Comment by ramiresviana** [comment]
```
filebrowser    | 2022/03/07 07:21:29 open /config/database.db: permission denied
```

That error needs to be fixed, you have the check the file permissions. Also provide a HAR file containing your browser requests when the error occurs and console output.

**Comment by PrzemekSkw** [comment]
Thanks, I fix that error but I realize that File Browser don't sync folders on my devices. I will look for something else.
Regards.
