### ISSUE TITLE
Cant Upload Files to OMV NAS

### ISSUE THREAD

**Issue by sbc-mining** [filebrowser/filebrowser#1856]
Hi there,

I operate an OMV NAS which I access through the Filebrowser. For this I mount the directory of the NAS server as FTP on the FileBrowser server. All files are also displayed to me, I can watch videos, delete files, but not upload them or create some new. Then I always get the error message "Internal Error 500". Unfortunately I don't know where to find the logs from Filebrowser.

I hope someone can help me with the problem with the upload.

Thanks

**Comment by o1egl** [comment]
I assume there are some permission issues with a mounted folder. You can try to create a file under the user that runs filebrowser app

**Comment by sbc-mining** [comment]
Hi there, Thanks for the answer. 
So on the Raspberry on which file browser is running, this service is apparently executed by the "Root" user. The idea with the rights already came to me. Would it make sense to change the uid and gid to www-data when mounting? Or are there any other ideas? Because I've already added the user www-data to the group "pi" as a test, but that doesn't work either.

**Comment by sbc-mining** [comment]
Okay, i found the problem but no solution.

2022/03/10 16:15:44 /image.png: 500 192.168.0.30 open /home/pi/ftp/image.png: operation not supported


A old Topic about the problem is here:
https://github.com/filebrowser/filebrowser/issues/912

Anybody any ideas??

**Comment by o1egl** [comment]
If you can't open a file using cli that means you have an issue with your mounting.

**Comment by sbc-mining** [comment]
I can open files, remove files and more. The only thing that is not working is Uploading a file.

Thats my mount command:
curlftpfs#fileserver:password@192.168.0.18 /home/pi/ftp fuse auto,user,uid=1000,gid=1000,umask=0022,allow_other,_netdev 0 0

What i change:
Start Filebrowser as user PI and not root.
Set premission of the mounted folder and Files to PI
Set all permissions for PI in OMV

Nginx is running as user PI too:
pi@raspberrypi:~ $ sudo ps aux| grep nginx
pi           820  0.0  0.0   5912   656 pts/1    S+   18:53   0:00 grep --color=auto nginx

If i connect via FTP to the PI where Filebrowser is running, i can upload files. But not whit Filebrowser.

Thats the error from the Log:

2022/03/10 18:01:18 /ip-port.txt: 500 192.168.0.30 open /home/pi/ftp/ip-port.txt: operation not supported

**Comment by sbc-mining** [comment]
Browser Error Log:

POSThttps://cloud.jennyan.tv/api/resources/6ec68474-3551-42b2-832c-0f3ed24ad1ad-profile_im

`Exception { name: "NS_BASE_STREAM_CLOSED", message: "Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsISeekableStream.tell]", result: 2152136706, filename: "resource://devtools/shared/webconsole/network-helper.js", lineNumber: 175, columnNumber: 0, data: null, stack: "readPostTextFromRequest@resource://devtools/shared/webconsole/network-helper.js:175:30\n_onRequestBodySent@resource://devtools/server/actors/network-monitor/network-observer.js:933:34\n_dispatchActivity@resource://devtools/server/actors/network-monitor/network-observer.js:559:14\nNetworkObserver.prototype.observeActivity<@resource://devtools/server/actors/network-monitor/network-observer.js:672:12\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22\n", location: XPCWrappedNative_NoHelper }
​
columnNumber: 0
​
data: null
​
filename: "resource://devtools/shared/webconsole/network-helper.js"
​
lineNumber: 175
​
`
