### ISSUE TITLE
superfluous response.WriteHeader error when using haproxy https, but no error with http

### ISSUE THREAD

**Issue by athoune** [filebrowser/filebrowser#1857]
I'm using HAproxy 1.8, with unix socket to filebrowser.

It works well with HTTP, but got a status 400 error when using https.

The log line is :

```
2022/03/09 15:03:56 http: superfluous response.WriteHeader call from github.com/filebrowser/filebrowser/v2/http.handle.func1 (data.go:74)
```
The error is here : https://github.com/filebrowser/filebrowser/blob/master/http/data.go#L74

The code try to set the status more than one time.

**Comment by ramiresviana** [comment]
I'm unable to reproduce this issue, please check your proxy configuration.

**Comment by athoune** [comment]
The double header should never happened.

My bug only appear when using https:haproxy->unix:systemd-socket-proxyd->unix:filebrowser

http:haproxy->unix:systemd-socket-proxyd->unix:filebrowser is ok

https:haproxy->unix:filebrowser is ok

the filebrowser error is :
```
2022/03/10 15:02:49 /: 500  write unix /var/run/filebrowser/machin/private.socket->@: write: broken pipe
```
So, I think `systemd-socket-proxyd` is guilty, not filebrowser.

Thanks for your time.
