### ISSUE TITLE
Image preview in share folder

### ISSUE THREAD

**Issue by zagi988** [filebrowser/filebrowser#1864]
Hello. What a great piece of software, for starters.
Now about the issue/feature request.
When I share a folder, let's say with 100 photos in it... There is no way for anyone who opens a folder to preview photos as they're going thru the list. They would need to double-click on the photo and then select "OPEN FILE" to see the picture.
And that uses a lot of bandwidth and is very slow.

I would like to request a feature that when you open a shared folder, there are thumbnail previews as are in regular folders. Secondly, when double clicking the photo you get a bigger preview instead of just "photo" icon.

Is it doable, considerable?

**Comment by zagi988** [comment]
Anything on this?

**Comment by ClenonWolf** [comment]
I would love to see this feature aswell, because one of the things I use it for a lot is sharing images and not having previews is a pain. Adding the default previews and viewing options as in regular folders to shares would be perfect. 

#1735 Seems to also be addressing this issue but I'm not sure if it's still being worked on or what happened to it because this was close to a year ago. 

Would love to hear more about this and to see this happen.

**Comment by zagi988** [comment]
Yeah, thumbnails and previews are already integrated, they just need to be enabled for this.

**Comment by niubility000** [comment]
I did a modification last year. I am still using it personally. In mobile browser, when you swipe down, the preview window will stick on the top.(click the item to preview it, and double-click them to jump to the original second page.)

If you guys like it. Here are the files I modified (based on 2.22.4):

[modified-basedon2.22.4.zip](https://github.com/filebrowser/filebrowser/files/9641351/modified-basedon2.22.4.zip)

BTW, I am not a professional coder, so feel free to modify them and make a PR.

**Comment by aluo-x** [comment]
I would like to bump this request.

**Comment by gogito** [comment]
Bumping and following

**Comment by maxesisn** [comment]
👀looking forward for this feature

**Comment by Jaydip-Chabhadiya** [comment]
Yeah, This feature is very useful to identify and download shared images if it have thumbnail preview

**Comment by mishka81** [comment]
same, would be appreciated

**Comment by BrendanxP** [comment]
Feature very much appreciated!

**Comment by daraujo85** [comment]
Feature very much appreciated!

**Comment by Minoo122** [comment]
Would be great to have that feature
