### ISSUE TITLE
Requested address is not valid in it's context.

### ISSUE THREAD

**Issue by whitigol** [filebrowser/filebrowser#1867]
**Description**
`listen tcp x.x.x.x:8080: bind: The requested address is not valid in its context.`

**Expected behaviour**
Running FileBrowser

**What is happening instead?**
`listen tcp x.x.x.x:8080: bind: The requested address is not valid in its context.`

**How to reproduce?**
Correctly installed FileBrowser (I've installed it several times before). Tried to init the config file, create the config file and only set branding name (Worked as intended). Then inline with Powershell, tried launching via `filebrowser -r "C:\" -a x.x.x.x` and I received the listed error.

**Comment by ramiresviana** [comment]
The provided address cannot be used by Filebrowser, the address is not available or you dont have permissions to use it.
