### ISSUE TITLE
通过nps内网穿透后，上传文件失败。但是关掉cdn代理后（仅dns）有成功案例一次，vps使用的是甲骨文免费的vps,目前局域网内上传没有问题，网速慢应该是我的设备问题。

### ISSUE THREAD

**Issue by TeemAlive** [filebrowser/filebrowser#1869]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by TeemAlive** [comment]
After passing through the nps intranet, uploading files fails. However, after turning off the cdn proxy (only dns), there was a successful case. The vps used Oracle's free vps. At present, there is no problem with uploading in the local area network. The slow network speed should be the problem of my equipment.

**Comment by TeemAlive** [comment]
![1647336973(1)](https://user-images.githubusercontent.com/84560604/158349193-7f1fd29b-296f-4021-8574-34949540d29f.png)

**Comment by TeemAlive** [comment]
个人初步判断为vps问题。毕竟局域网内正常使用，或者您有什么提议请告知，非常抱歉打扰您

**Comment by TeemAlive** [comment]
Personal preliminary judgment is a vps problem. After all, it is used normally in the local area network, or if you have any suggestions, please let me know, I am very sorry to disturb you.

**Comment by TeemAlive** [comment]
个人初步判断为vps问题。毕竟局域网内正常使用，或者您有什么提议请告知，非常抱歉打扰您

**Comment by 456vv** [comment]
可能是宽带限制，造成上传时间超时。It may be due to bandwidth limitations, causing the upload time to time out.

**Comment by o1egl** [comment]
I'm not sure that I understand what is happening

**Comment by yyszak** [comment]
> 个人初步判断为vps问题。毕竟局域网内正常使用，或者您有什么提议请告知，非常抱歉打扰您

我以前碰到过这种情况，修改文件的名称就解决了。
I've been in this situation before and just change the name of the file.

**Comment by TeemAlive** [comment]
> > 非常感谢您为您的个人身份识别问题。
> 
> 以前碰巧遇到这个问题的情况，我是文件名，改文件名就解决了，不知道你是什么情况

我上传成功过一个大文件，文件是win7的ios文件，我试试你的办法

**Comment by o1egl** [comment]
Please use english, so everyone can understand

**Comment by devmiek** [comment]
@TeemAlive Can you track a POST request to upload a file via DevTools in your browser?

I suspect that one or more middleware may have closed the TCP connection because the HTTP request timed out. This middleware may be edge proxy servers for CDN service providers, or they may be NAT traversal gateway.

I suggest you check the middleware timeout configuration. If possible, please provide the running log of FileBrowser.

**Comment by liuchuhan1** [comment]
我这边用路由器搭建的 配合ipv6公网+cf cdn上传下载（客户端为ipv4/6单双栈均可）都是没有问题的，路由器用了nps本机服务端+本机客户端实现泛解析和泛域名端口转发，注意防火墙要放行相应的端口
