### ISSUE TITLE
Download button accessible directly after sharing file

### ISSUE THREAD

**Issue by PatrykKlimowicz** [filebrowser/filebrowser#1871]
**As a** user, developer, DevOps engineer,
**I can** click to *download* icon after sharing a file,
**So I** can download file directly after sharing operation is done.

Currently, the share process results in link to the downloading page which I should paste in the browser and then download a file. It would be nice to have this additional step marked as optional. The additional *download button* would be nice to be there:
![image](https://user-images.githubusercontent.com/49591875/158974541-0d05e830-68c1-40ec-b1e2-30659179c90f.png)

With this approach I could skip additional step of opening the download page and download the file directly. At the same time I will be able to obtain the downloading link directly from that new button and use it for example in the `wget` command.

**Comment by o1egl** [comment]
What is the use case? Why do you need to create a share to download a file? Why not to download it from a regular UI?
