### ISSUE TITLE
Error with the content of '500 Internal Server Error'.

### ISSUE THREAD

**Issue by dpmoehre** [filebrowser/filebrowser#1875]
Hello, developer of FileBrowser, I got an error when uploading a file. The details are as follows.
When I was saving the file to my folder, there was an Error with the content of '500 Internal Server Error'. The file I transferred was a PDF file, less than 10MB, and the disk I mounted was in EXT4 format.
Further testing found that this folder could not upload any files. My preliminary judgment is that it should be this folder. The same files can be placed in another folder.
Whether FileBrowser has folder naming conventions, creation procedures, or other special requirements. What do I need to do to upload files in this folder?
I look forward to your reply and the development of FileBrowser.

Chinese translation：
我在向我的文件夹中存放文件时出现了内容为‘500 Internal Server Error’的报错，我传输的文件是一个PDF文档，文件不到10mb，我挂载的硬盘为EXT4格式。
经过进一步测试发现这个文件夹不能上传任何文件。我初步判断应该是这个文件夹的问题。同样的文件可以放在别的文件夹里。
FileBrowser是否存在文件夹命名规范、创建步骤，或其他特殊要求。我需要做什么样的操作才可以在这个文件夹里上传文件。

**Comment by dpmoehre** [comment]
![image](https://user-images.githubusercontent.com/52621572/159131793-70bce4d5-a4f0-43a5-866a-e19eb2d9ef1f.png)

**Comment by dpmoehre** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/52621572/159131871-c249c6f7-0d14-464d-a888-9c78dd084a37.png">

**Comment by dpmoehre** [comment]
Suspect that a folder cannot be too large.Once a 260MB video is deleted from the parent directory, other small files can be uploaded.

**Comment by o1egl** [comment]
Filebrowser doesn't have any file/folder size limits. We need to inspect server side logs to be able to help you

**Comment by dpmoehre** [comment]
Okay, so what do I need to do next?

**Comment by o1egl** [comment]
Share server-side logs

**Comment by o1egl** [comment]
> Suspect that a folder cannot be too large.Once a 260MB video is deleted from the parent directory, other small files can be uploaded.

I think you are running out of space on your drive
