### ISSUE TITLE
Download files using password

### ISSUE THREAD

**Issue by PatrykKlimowicz** [filebrowser/filebrowser#1877]
**Is your feature request related to a problem? Please describe.**
None
 
**Describe the solution you'd like**
It will be nice to make it possible to download files with `wget` command with `--user` and `--password` switches. So something like:

```bash
wget --user USER --password PASSWORD <URL_TO_FILE>
````

With that I could use file manager w/o a problem in scripts as well and not only through the web browser.

**Comment by JerryLiew** [comment]
I have the same demand, Did you got a solution for this?

**Comment by PatrykKlimowicz** [comment]
> I have the same demand, Did you got a solution for this?

I used [this](https://kubernetes.github.io/ingress-nginx/examples/auth/basic/) solution.

**Comment by JerryLiew** [comment]
it's too difficult for me with my poor ability. thanks all the same.

**Comment by tonglv** [comment]
$ wget --user admin --password admin@1018 http://xx.xx.xx.xx:8018/api/raw/software/jdk-11.0.16.1_linux-x64_bin.tar.gz
--2022-11-02 09:28:31-- http://xx.xx.xx.xx:8018/api/raw/software/jdk-11.0.16.1_linux-x64_bin.tar.gz
Connecting to xx.xx.xx.xx:8018… connected.
HTTP request sent, awaiting response… 401 Unauthorized
Unknown authentication scheme.
Authorization failed.
