### ISSUE TITLE
V1.1.0 and later versions do not support the same name file upload and cover it?

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#188]
If upload the same name file will prompt "There is already a file on that path"
You can add a function, prompt the user to have the same name file already exists, and let the user manually select whether to overwrite.

**Comment by ghost** [comment]
By the way, if you later add the language file content, remember to inform me. :rofl:

**Comment by hacdias** [comment]
Hey @ToyoDAdoubi,

I'll implement this when I can. 

About the language files, I added this to the files section:

```
sortByName: Sort by name
sortBySize: Sort by size
sortByLastModified: Sort by last modified
```

**Comment by ghost** [comment]
@hacdias complete! https://github.com/hacdias/filemanager/pull/189

**Comment by hacdias** [comment]
Just added some stuff to the translations file: https://github.com/hacdias/filemanager/commit/6ee846ef0eab0f3b91ff3557877cd2eb63acb505#diff-fe6ccd8f0bf41f00b9ff5d61b8e0e3e9

I already fixed this issue and it will be available on the next release 😄

**Comment by ghost** [comment]
@hacdias complete! https://github.com/hacdias/filemanager/pull/191
