### ISSUE TITLE
cannot access /host_mnt/c/ and cannot upload files.

### ISSUE THREAD

**Issue by Death-Pact** [filebrowser/filebrowser#1880]
I have file browser up and running, but I am having serious issues with several things and I do not know where else to go for support. I am going to attach logs from portainer. No files are showing up when trying to explore my C: drive on windows and I cannot upload files at all. Any help would be greatly appreciated.

[_file-browser_logs (1).txt](https://github.com/filebrowser/filebrowser/files/8347032/_file-browser_logs.1.txt)

I am currently running file browser in docker running on windows. I see that I do not have access but i do not see a way of remedying this situation or fixing the upload issues.

**Comment by ramiresviana** [comment]
Filebrowser works by making calls to the filesystem, it does not handles file permissions or Docker volumes. If you're going to use Filebrowser on Docker, you must first ensure that your environment is working correctly. If you're not familiar with Linux and Docker, i would suggest you to use Filebrowser version for Windows.
