### ISSUE TITLE
add config for hideDotfiles to filebrowser cli

### ISSUE THREAD

**Issue by dr-bonez** [filebrowser/filebrowser#1884]
currently, there are cli options (through `filebrowser config set` or `filebrowser users update`) to set most configuration options that are available in the ui. It would be good to be able to modify the setting for `hideDotfiles` in the cli as well.

**Comment by Senui** [comment]
This is still not possible I believe? Dumping the config to update the `hideDotfiles` parameter is not working due to https://github.com/filebrowser/filebrowser/issues/2440 , so it's not possible to change this parameter other than the UI. Or is did someone come up with a way?
