### ISSUE TITLE
How to allow execution of shell commands?

### ISSUE THREAD

**Issue by sbwml** [filebrowser/filebrowser#1894]
Suppose, I want to implement the `ls` command in the filebrowser command line, how should I set it?

![1](https://user-images.githubusercontent.com/16485166/161347345-fab1d864-41e7-4d17-8316-2f67528c32a5.png)
![2](https://user-images.githubusercontent.com/16485166/161347351-7c2fb10a-3763-4673-a2b0-c7f1dafb25ee.png)

**Comment by o1egl** [comment]
You need to navigate to the user management tab and configure the list of the allowed commands for a user.

**Comment by sbwml** [comment]
> You need to navigate to the user management tab and configure the list of the allowed commands for a user.

Thanks, I did miss this option. Now I can use the shell command line normally.

**Comment by atsag** [comment]
Unfortunately, I face the same issue and I have done the following:

- Added the executable to the path;
- Added the 'ls' command, both full path and only its name in the commands list, both in the allowed commands and in the allowed commands for the current user, which is an administrator

Is there something more I can do to debug?

**Comment by xiaohao0576** [comment]
https://github.com/filebrowser/filebrowser/issues/2393#issuecomment-2184921453

This answer may help you
