### ISSUE TITLE
"Something went wrong" (browsing file list)

### ISSUE THREAD

**Issue by DarrenPIngram** [filebrowser/filebrowser#1895]
**Description**

When browsing some directories you get a "something went wrong" message. I expect it is timing out reading a large file list.

**Expected behaviour**

file list is delivered.

**What is happening instead?**
Web browser returns (from FB) "something went wrong" message in the focus window.

**Additional context**

**How to reproduce?**

I guess try a directory with a lot of files or directories (hundreds)

**Files**

None

Suggestion? Increase a timer or whatever is used. Add a "movement" icon to show things are working in the background.

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration and server and browser logs.

> Suggestion? Increase a timer or whatever is used. Add a "movement" icon to show things are working in the background.

There's no timer implementation on Filebrowser, the request may take as long as necessary to finish. Most of the views already has a loading indicator.
