### ISSUE TITLE
Show Folder/Directory size in list view

### ISSUE THREAD

**Issue by doug62** [filebrowser/filebrowser#1903]
**Is your feature request related to a problem? Please describe.**
As a user I would like the ability to view the size of folders so that I can quickly find expensive files

**Describe the solution you'd like**
Show size of all files in a folder chip/list view

**Describe alternatives you've considered**
Linux 'du'

**Additional context**
One might argue this could cause lag/extra CPU/latency - perhaps make it an option - the alternative is way more time consuming.

**Comment by dvasdekis** [comment]
Looks like a component called `filesize` is imported [here](https://github.com/filebrowser/filebrowser/blob/cb437700255e41ff559b9f5a99ab4290b2f8df87/frontend/src/components/files/ListingItem.vue#L40), but I'm having trouble figuring out where it originates.
