### ISSUE TITLE
Uploading Files Error

### ISSUE THREAD

**Issue by jschinter** [filebrowser/filebrowser#1906]
**Description**

When routinely uploading a file, I keep getting an OBJECT error - To resolve I upgraded version, and restarted twice.

**Expected behaviour**

Succesful upload of a file

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by jreoka** [comment]
Same thing happening to me

**Comment by o1egl** [comment]
Am I understanding correctly that the issue is not reproducible on the latest version?

**Comment by jschinter** [comment]
Oleg - Thanks for the follow-up…. I was able to determine that the problem is with my laptop.  I am able to successfully upload files from all other computers.

I consider this issue closed.  But again - thanks for the follow up.

Regards John
