### ISSUE TITLE
.heic photo extensions not displaying image thumbnails?

### ISSUE THREAD

**Issue by githubaccountforme** [filebrowser/filebrowser#1908]
**Description**
Hi, first off, I'm loving using Filebrowser with my Start9 Embassy device. I'm a new user (and not technical) trying my best to utilize Filebrowser to self-host all my own data. 

I've uploaded quite a few photos to my personal server and when viewing iphone photos in Filebrowser I'm unable to see any thumbnail's for images that use a .heic file extension. I'm not sure when Apple switched over, but when I view a gallery of these files, I can see thumbnail previews for the jpegs but I only see a grey icon for all the .heic photo files. 

I'm currently using Filebrowser version 2.14.1~1. 

**Expected behaviour**
I was hoping to view these photos in thumbnail view just like I can view the .jpegs in thumbnail view

**What is happening instead?**
I can only see a grey icon of a page with a folded top-right corner instead of the image itself. When I click into it to view the isolated file, I don't see the image, I only see "download" and a download icon. When I do the same for a .jpeg file I see the actual photo itself in addition to the download prompt.

**Additional context**
screenshots of the .heic files attached

**How to reproduce?**
I would assume upload an iphone .heic photo and see the same thing?

**Files**

<img width="380" alt="heic previews" src="https://user-images.githubusercontent.com/47697547/163251701-a8791157-640c-4d51-a563-c46e9e8eefb4.png">

**Comment by o1egl** [comment]
Filebrowser doesn't support heic format

**Comment by githubaccountforme** [comment]
Got it, is it possible to put in a feature request to add this functionality? There are a lot of iphone users out there using the default settings which make their images .heic file extensions, so it would be great if these could be supported at some point in the future.

**Comment by sebw** [comment]
For what it's worth Photoview has been implementing support for HEIC, see https://github.com/photoview/photoview/pull/271/files and https://github.com/strukturag/libheif

**Comment by Julemane** [comment]
Hello guys, and thanks for this greatfull app, I'm glad to use it, the only missing thing for me as an ios owner is the .heic support.
I hope this 'll be introduced in the future ;)
