### ISSUE TITLE
[object Object] Error

### ISSUE THREAD

**Issue by dillfrescott** [filebrowser/filebrowser#1909]
When trying to upload a 2 GB file, it gets to about 20 percent uploaded and always throws this error...

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, server and browser logs.

**Comment by jreoka** [comment]
The server is Ubuntu 22 Toshiba satellite laptop. The configuration is default, I can provide server and browser logs next time it happens! :)

**Comment by jreoka** [comment]
The browser console:

`Failed to load resource: net::ERR_CONNECTION_CLOSED`

The Server Console:

`2022/04/18 21:18:55 No config file used
2022/04/18 21:18:55 Listening on 127.0.0.1:8080`

**Comment by jreoka** [comment]
I seemed to have found and fixed the issue (I think).

It was Cloudflare's proxy causing it, so under the Cloudflare UI I turned off the proxy for the dns and it seems to work now.
