### ISSUE TITLE
Case-insensitive username field

### ISSUE THREAD

**Issue by jeroenev** [filebrowser/filebrowser#1910]
Currently, when logging in on a mobile device, the keyboard automatically capitalizes the first letter when filling in the Username field.
So it will automatically type 'Username' instead of 'username' if you're not careful to lowercase the first letter.

It would be nice if either:

- The Username is case-insensitive, so this causes no problems
- autocapitalize="off" is added to the username field, so mobile devices no longer capitalize it automatically

**Comment by o1egl** [comment]
Making username case-insensitive is a backward-incompatible change. So the second option looks like a solution

**Comment by jeroenev** [comment]
Awesome, thanks a lot for fixing this!
