### ISSUE TITLE
Device-specific single-click setting

### ISSUE THREAD

**Issue by jeroenev** [filebrowser/filebrowser#1911]
I like having to double-click to open folders on desktop, however on mobile I think it's a little confusing to double-tap it.
Would be nice if there would be an option to set this single/double-click setting per device type (touch or non-touch, or mobile / tablet / desktop)

**Comment by o1egl** [comment]
There is such an option in the settings, but it is global for all devices

**Comment by jeroenev** [comment]
Yes, I'm aware of the setting, the ticket was opened to see if it's possible to add a different setting per device type (single tap makes a lot of sense on touch devices, but double-click makes more sense on desktop, at least in my opinion)

**Comment by jeroenev** [comment]
Should still be relevant
