### ISSUE TITLE
You don't have permissions to access this - after some hours of uploading large file

### ISSUE THREAD

**Issue by bigbeka** [filebrowser/filebrowser#1919]
**Description**

Upload a large file to my NAS using NGINX Reverse Proxy

**Expected behaviour**

Upload any file size with any speed

**What is happening instead?**

Upload is interrupted, message: "You don't have permissions to access this."

**Additional context**

I use NGINX as reverse proxy for my NAS. NGINX has buffering turned off to pass on the file traffic to the upstream right away. No issue when I upload smaller files that takes less time to upload.

No exact amount of time is measured, but after some hours of non interaction with FileBrowser webUI (while uploading) the page shows "You don't have permissions to access this.". Same file can be uploaded with no issue if I interact with the page in some way or from additional tab.

I suspect that FileBrowser kicks out the session and it stop 'sending' the upload, although no error message is shown on the page, it still keeps showing that it is uploading. If the webUI is refreshed, "You don't have permissions to access this." message shows.

NOTE: The PC with the upload webUI does not go to sleep or the connection doesn't drop in any way.

**How to reproduce?**

Upload large file that takes many hours, and don't interact with the FileBrowser webUI in any way.
In my case, this is cause due to high latency. My VPN has about 130ms latency, which causes slow upload. But this is not relevant as FileBrowser should upload no matter the latency or the time it takes to upload any given size of a file.

**Files**

N/A

**Comment by ramiresviana** [comment]
The session token is configured to expire after 2 hours. Uploads in progress are not interrupted when the session token expires, only pending itens in queue cannot start. The `You don't have permissions to access this.` message is displayed because the token is expired, this is a unwanted behavior because causes confusion to users and should be fixed.

**Comment by bigbeka** [comment]
Thanks for your reply.

It would be helpful to have this message clearer, it did confuse me, as I set all the permission to read/write for filebrowser.

It would also be good to prolong the default 2 hours auto-session interruption. My use case requires long uploads and I do queue many large files. @ramiresviana Do you know how to change the default session interruption time?

This might be for another thread as a feature suggestions, but instead of queueing, why not have concurrent uploads? This especially will help big latency connections.
I know mickael-kerjean/filestash allows concurrent uploads of multiple files, but it doesn't allow multi-user environment.

**Comment by plashenkov** [comment]
Yeah, second this. It would be really nice to have a possibility to increase the session duration.
Plus it would be great if the session could self-prolong itself while there is an activity.

**Comment by plashenkov** [comment]
Ah, I can see: https://github.com/filebrowser/filebrowser/pull/1794 and https://github.com/filebrowser/filebrowser/issues/1791

**Comment by bigbeka** [comment]
@plashenkov Very good point.

@ramiresviana Do know if the active session is registered in Cookies or some other way?
As the filebrowser offers other methods of Auth, could those methods help solve this issue?

What about workaround with NGINX proxy?

**Comment by bigbeka** [comment]
> Ah, I can see: #1794 and #1791

Thank you, I will have a look.

**Comment by bigbeka** [comment]
@plashenkov Thank you once again, I am new in all this self hosting.
I am running this in docker and the docker CLI Bash is not running, and bin/sh isn't accepting the config command stated in the solution.

Where else can you run these commands? It there CLI within the WebUI?

**Comment by plashenkov** [comment]
I am not 100% sure about best practices, but I would create config database locally with all the needed settings and then upload it to the server by embedding it into the docker container. You have an initial config (in JSON format), but you can set up there only small amount of initial parameters, so the real config is the database. You really can create it and configure it as you want locally and then just embed it into your image.

This is my point of view. Maybe somebody can correct me.

But currently you still can't use commands from the linked PR, it is not merged yet.

**Comment by plashenkov** [comment]
I.e. you can initialize you database locally by using the real filebrowser executable.

**Comment by bigbeka** [comment]
@plashenkov thank you for the info. I will probably give a try to a custom database.

**Comment by bigbeka** [comment]
Based on this #1794 you can run commands from WebUI, the cli icon '< >' is located on the right top corner next to upload/download buttons.

But when I use the documented commands from [here](https://filebrowser.org/cli), it spits out the following errors:
![Screenshot 2022-04-30 at 17 33 15](https://user-images.githubusercontent.com/53529055/166112207-c48fdd5f-33f1-43fd-973b-3897f804f22d.png)

Any idea how to get the suggested commands to use from #1794 ?

**Comment by plashenkov** [comment]
@bigbeka
You cannot use session.timeout yet because PR which adds this option isn't merged yet. I already wrote this above.

**Comment by bigbeka** [comment]
@plashenkov Oh I see, thank you. I will keep an eye out for the coming merges and releases .
