### ISSUE TITLE
[Feature Request] Share folder to anonymous users

### ISSUE THREAD

**Issue by jivank** [filebrowser/filebrowser#192]
It would be great to be able to share a folder or subfolder that will generate a unique link that can be shared. The link generated would have readonly permissions and allow an unregistered user to download. The link can expire or be a permanent share.

**Comment by hacdias** [comment]
Thanks for the idea 😄 It's a really good one. Added to the roadmap.

**Comment by hacdias** [comment]
This will be available as soon as 1.2.0 is released (which will be soon!) 😄

**Comment by hacdias** [comment]
Hey @ToyoDAdoubi! Sorry for being always pinging you! I've got some new stuff: https://github.com/hacdias/filemanager/commit/868434360592aa0280e0d631840750d53a564cd3#diff-fe6ccd8f0bf41f00b9ff5d61b8e0e3e9 Thanks :smile:

**Comment by ghost** [comment]
@jivank complete! https://github.com/hacdias/filemanager/pull/198
Do not need to apologize, this is what i like to do.

**Comment by hacdias** [comment]
Thanks 😄

**Comment by ip75** [comment]
v1.10.0  anyway unable to share files for users with readonly permissions

**Comment by Nottt** [comment]
I can't find this anywhere on the UI on how to create a share link? I'm on File Browser 2.0.12, and googling about how to share only bring github links

**Comment by hacdias** [comment]
Hey @Nottt! You can select the folder you want, click the share button and generate a new link :) The share button is near the others on the top right of the screen!

**Comment by Nottt** [comment]
I don't have that

![image](https://user-images.githubusercontent.com/13532436/64095913-94ce8000-cd36-11e9-95ba-1103400fdb97.png)

**Comment by hacdias** [comment]
Does your user has share permissions?

**Comment by Nottt** [comment]
I am the admin the user

**Comment by benwiley4000** [comment]
I wasn't seeing this either. The reason was because I had activated single-click opening of directories. Is there a way to get the option menu for an item while single-click opening is turned on?

ETA: I have discovered a couple of ways. On is on mobile you can long-press (which is normal). On desktop the only way I've found is to start dragging the item like you want to move it, then let go. This will leave the item selected. Seems weird there isn't another way to select it though.

**Comment by siraht** [comment]
> I wasn't seeing this either. The reason was because I had activated single-click opening of directories. Is there a way to get the option menu for an item while single-click opening is turned on?
> 
> ETA: I have discovered a couple of ways. On is on mobile you can long-press (which is normal). On desktop the only way I've found is to start dragging the item like you want to move it, then let go. This will leave the item selected. Seems weird there isn't another way to select it though.

The far right button with the checkmark icon is Select Multiple, which will allow selecting.
