### ISSUE TITLE
nginx reverse proxy filebrowser,cannot load /api/renew

### ISSUE THREAD

**Issue by yesli** [filebrowser/filebrowser#1923]
Hi,
   I'm using nginx reverse proxy filebrowser.The pages looks normal,but i found "api/renew" cannot be load.
![image](https://cc.yeslicn.tk/api/public/dl/6lSSnPBV)
How can i fix it?
My nginx config:

location / {
		  proxy_redirect off;
		  proxy_set_header X-Real-IP $remote_addr;
		  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		  proxy_set_header Host $host;
		  proxy_pass http://127.0.0.1:1231;
}

**Comment by ramiresviana** [comment]
Messages are written to the console when the user token is expired, it does not affect the usability.
