### ISSUE TITLE
Speed up search function with mlocate.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1925]
**Is your feature request related to a problem? Please describe.**
Search feature is slow on huge directory and intensive for a simple HDD (close to 1min on huge directory). 

**Describe the solution you'd like**
It could be nice to implement `mlocate` for the search function (results in less than 1sec on same huge directory). I don't know if it's possible to use `locate` and the associated local database (mlocate.db﻿) without install on the OS in a Golang project... and make it OK for others OS ? 

At least, I will try to implement `locate` by myself, in this file I guess ? [search/search.go](https://github.com/filebrowser/filebrowser/blob/master/search/search.go). Maybe just trigger a bash command, retrieve the results and return in the last function. I don't really know Golang but it doesn't sound too difficult.

**Comment by august-isaque** [comment]
please, let us know if you could perform it editing this class. I'm also with this problem, the search function in my server take too long and ends up with a timeout error...

**Comment by ghost** [comment]
@august-isaque I'm not a Go guru (1 month), but I'm trying.

**Comment by o1egl** [comment]
Filebrowser doesn't use any CLI tool for searching purposes. Instead, it traverses the file tree and returns files matched by name.

**Comment by august-isaque** [comment]
> Filebrowser doesn't use any CLI tool for searching purposes. Instead, it traverses the file tree and returns files matched by name.

And does the project has plan to change this approach?

**Comment by daliang1215** [comment]
The search file name is  so slowly, can it be used to speed up the search for file name in the background of the system

**Comment by o1egl** [comment]
> > Filebrowser doesn't use any CLI tool for searching purposes. Instead, it traverses the file tree and returns files matched by name.
> 
> And does the project has plan to change this approach?

No, there are no plans to use CLI tools for search purposes. We might consider using https://github.com/blevesearch/bleve as a search engine
