### ISSUE TITLE
Allow filebrowser to set absolute URI so that it can run on http://localhost/filebrowser

### ISSUE THREAD

**Issue by hereshem** [filebrowser/filebrowser#1928]
**Is your feature request related to a problem? Please describe.**

I always want filebrowser to run as a very close plugin for any website by which we can have much control on what to show in website. so website runs on their main domain and I want to have this running on the same domain with different path uri for eg `/filebrowser`

**Describe the solution you'd like**

Currently it has direct dependent on the following endpoints
- /api
- /static
- /login
- /files
- /setting

By introducing this absolute uri all the requests can be passed via same endpoint as defined such as `/filebrowser` `/files` `/explorer` etc

**Describe alternatives you've considered**

Currently I am supposed to implement filebrowser as a file browser only for specific host. and also i am forced to create a new subdomain to host this filebrowser to run parallel with my other websites.
It would be great if we have this small feature to set absolute uri so that we can serve them on any running server with any number of instances bound simply using reverse proxy.

**Additional context**

This feature request is similar to the phpmyadmin where we can set `cfg['PmaAbsoluteUri'] = ''`.
With this implementation it has become more and more useable and popular. 
It would be great if this feature is available soon in this filebrowser as well.

**Comment by ramiresviana** [comment]
The `baseurl` param is used to add a prefix to the url path, it also must have a leading slash to work correctly. That option can be set using a flag, environment variable and configuration file. The options documentation is available at https://filebrowser.org/cli/filebrowser

**Comment by hem-shrestha** [comment]
Thanks for the response, I will check them.

**Comment by hereshem** [comment]
Thanks for the response, I will check them.
