### ISSUE TITLE
Cannot read property 'findIndex' of null

### ISSUE THREAD

**Issue by vothanhkiet** [filebrowser/filebrowser#193]
I run the latest docker image of filemanager

### What are you trying to do?
Upload new file to filemanager, any kind of file, currently I test .md .txt .jpg .pdf, have the same result.

### What did you expect to see?
I can upload any files.

### What did you see instead (give full error messages and/or log)?
Nothing happen, I check Chrome console log and see this.

```app.633cd4387611b3c6a7fd.js:7487 Uncaught TypeError: Cannot read property 'findIndex' of null
    at o.checkConflict (app.633cd4387611b3c6a7fd.js:7487)
    at o.n [as checkConflict] (vue.esm.js:181)
    at o.uploadInput (app.633cd4387611b3c6a7fd.js:7512)
    at o.n [as uploadInput] (vue.esm.js:182)
    at change (Listing.vue?6505:17)
    at HTMLInputElement.t (vue.esm.js:1814)
```
 
[https://github.com/hacdias/filemanager/blob/dc7f389fdebf6af17e90675e3220d56e02ad68dc/assets/src/components/files/Listing.vue#L277](https://github.com/hacdias/filemanager/blob/dc7f389fdebf6af17e90675e3220d56e02ad68dc/assets/src/components/files/Listing.vue#L277)

**Comment by hacdias** [comment]
Which method are you using to upload? Using drag'n'drop or the upload button?

**Comment by vothanhkiet** [comment]
I used both drag'n'drop and upload button. This issue happen when the folder is empty only, I create a empty file and it works.

**Comment by hacdias** [comment]
Oh, thanks. Gonna fix it.

**Comment by hacdias** [comment]
The Docker image will build now and the fix will be available in some minutes.
