### ISSUE TITLE
Auto-select / focus "username" login field on page load

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1931]
Hello,

I am using File Browser 2.21.1.
After opening the login page, I have to press "TAB" to focus / select the username field so I can enter my username to log in (or I can click on it with the pc mouse).

I tried Firefox and Chrome, same behavior.

Can you change this behavior so that the login field "username" is selected automatically when entering the login page?

Thank you

**Comment by o1egl** [comment]
Added in https://github.com/filebrowser/filebrowser/commit/596c73288f5b53bd7e79ab8046136dc75ff078b9

**Comment by o1egl** [comment]
Added in https://github.com/filebrowser/filebrowser/commit/596c73288f5b53bd7e79ab8046136dc75ff078b9
