### ISSUE TITLE
Follow Symlinks

### ISSUE THREAD

**Issue by RyannDaGreat** [filebrowser/filebrowser#1935]
**Is your feature request related to a problem? Please describe.**
When encountering a symlink to a folder, FileBrowser treats it as a file. **Technically** symlinks *are* files, but it's much more useful to treat them as folders (the way most OS file browsers and terminals do).

**Describe the solution you'd like**
When there's a symlink, for example `~/cyclegan/datasets/zebras --> ~/global_datasets/zebras` is encountered, `~/cyclegan/datasets/zebras` should take me to `~/global_datasets/zebras` when I double click it in FileBrowser

**Describe alternatives you've considered**
I think this functionality is pretty straightforward. Perhaps it should tell the user that it's a symlink somehow, by highlighting it's colors?

**Additional context**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17944835/166193975-b1a6f485-3c75-4e4a-915e-ca8361b5affd.png">
In this picture, you see 5 symlinks that point to dataset folders on my computer. FileBrowser treats them as an ordinary file, just like any other.
This should show 5 folders, not 5 symlink files.

**Comment by abdullasharapov** [comment]
I cannot confirm this. Symlink "Общая" used as folder in filebrowser.

lrwxrwxrwx 1    0    0   29 мая  2 12:54 Общая -> /data/Syncthing/users/Shared/

![Screenshot_2022-05-02-16-35-34-04_64efd17076aaba0cba3ac771b3d23d9e](https://user-images.githubusercontent.com/25831272/166242897-c0b55161-1b8e-4b32-aa35-445554237c81.jpg)

**Comment by o1egl** [comment]
@RyannDaGreat, I can't reproduce your issue. Filebrowser correctly displays symlinks to folders. I think your symlinks might be broken
<img width="581" alt="Screenshot 2022-05-04 at 01 26 43" src="https://user-images.githubusercontent.com/966539/166569332-6ca78f9d-fcb6-4a59-b009-a254520873b8.png">
<img width="518" alt="Screenshot 2022-05-04 at 01 27 04" src="https://user-images.githubusercontent.com/966539/166569345-5751ab8d-2e04-4b23-bec1-cae37896c4e4.png">
