### ISSUE TITLE
Cannot load api/login?

### ISSUE THREAD

**Issue by yesli** [filebrowser/filebrowser#1938]
Serveral days ago,My site works well.But today when i open my site again.I found that I cann't login.I pressed 'F12',found error below:

**POST http://xxx.xxx.xxx.xxx/api/login 403 (Forbidden)**

How can i fix it?

**Comment by ramiresviana** [comment]
The login endpoint will return a response with status code 403 when the user provides invalid credentials. Your access can be recovered by updating the password using cli, check the documentation at https://filebrowser.org/cli/filebrowser-users-update

**Comment by yesli** [comment]
> 

Thanks.

**Comment by papatistos** [comment]
> The login endpoint will return a response with status code 403 when the user provides invalid credentials.

@ramiresviana  Or when filebrowser _thinks_ that the credentials are wrong. When this happens, restarting the docker container will fix it.
