### ISSUE TITLE
Can't delete default "admin" user

### ISSUE THREAD

**Issue by dtypo** [filebrowser/filebrowser#1940]
**Description**
I've created a new custom user with admin priviledges.
I login in with the newly created user, then removed the admin permissions to the default `admin `user.
Then I try to delete the default `admin` user through the GUI, but I receive an error message: `You don't have permissions to access this`
The same happens if I stop the filebrowser container and give the following command from the shell oh my host machine:

```
docker-compose run --rm filebrowser users rm admin
Creating host_filebrowser_run ... done
2022/05/05 16:25:00 user with id 1 can't be deleted
ERROR: 1
```

**Comment by o1egl** [comment]
It is not allowed to delete default admin user

**Comment by meikeeit** [comment]
You can rename the admin's username into some random words.

**Comment by adipeterca** [comment]
I encounter the same problem, even if the user is not an admin. 
```
2025/06/07 15:30:32 Using database: /home/vm/filebrowser.db
ID  Username  Scope          Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
1   vm        /user_vm       en      list     false    false  true     true    true    true    true    true   true      false
```
the error
```
2025/06/07 15:30:13 Using database: /home/vm/filebrowser.db
2025/06/07 15:30:13 user with id 1 can't be deleted
```
Any motivation behind this limitation?
