### ISSUE TITLE
Add Filebrowser as a share target

### ISSUE THREAD

**Issue by bbergeron0** [filebrowser/filebrowser#1944]
Share targets are the options shown in the share menu on Android and iOS. Adding Filebrowser as a share target could allow users to upload content directly to their filebrowser drive from any application, instead of saving each files on their device and uploading them from the application.

I've notice the web app is a PWA, which means this could be done by adding a few line to manifest.json and writting a vue to handle the new share endpoint.

**Comment by s-h-a-r-d** [comment]
This is something all the apps that handle files should have. I would argue that this flow:
```go to gallery app > select a file > share > pick a target```
is more common than:
```go to the file manager app > select upload > go to gallery app > select a file```

Apps not having this functionality is literally the only reason why I still use nextcloud, even though I don't use over 90% of nextclouds functionality.

**Comment by dev-nicolaos** [comment]
This would be a really nice feature to have
