### ISSUE TITLE
can we open sqldb file in browser ?

### ISSUE THREAD

**Issue by keerthankumar** [filebrowser/filebrowser#1946]
In the current implementation we can view the text files, can we add a feature to view sqllite dbfiles ? if there is any way to view it please let me know

**Comment by o1egl** [comment]
No, it is not possible to view db file

**Comment by gerritgriebel** [comment]
I'd love a feature, that would allow invocation of a shell script for viewing files of a certain extension. @keerthankumar could then provide a shell script to dump content of sqlite to text. I would write a script that shows text in .gz files and all texts contained in .tar.gz2 files for a certain use case at a customers site.
