### ISSUE TITLE
Unable to access Filebrowser publicly despite local access.

### ISSUE THREAD

**Issue by KKDavion** [filebrowser/filebrowser#1947]
**Description**

I am currently attempting to run Filebrowser along with Caddy and FoundryVTT through docker on a Raspberry Pi 4B. As I need to give access to this server to a number of friends, I am also using DuckDNS for a free domain name. I had configured the proxy successfully to allow connection for FoundryVTT through my duckdns.org url before attempting to add Filebrowser to my docker-compose.yaml

**Expected behaviour**

Ability to access the designated folders through localhost:8080, PrivateIP:8080, PublicIP:8080, subdomain.duckdns.org:8080

**What is happening instead?**
I am able to access Filebrowser through localhost:8080 on the host device and on PrivateIP:8080 on other devices on the network. However, neither PublicIP:8080 nor subdomain.duckdns.org:8080 work. I am, however, still able to access Foundry through port 30000 as expected/

**Additional context**
Linked here are the relevant sections of my [docker-compose](https://i.imgur.com/zK8d2wq.png) and [Caddyfile](https://i.imgur.com/X6SBhDd.png). Ports 80, 443, 8080, and 30000 are all open for the relevant device. The fact that my proxy configuration works and continues to work for one service while it fails for the other leads me to believe the issue lies a little deeper. I'm unsure if Filebrowser isn't listening to all addresses despite being pointed at 0.0.0.0, or if I really am just fucking up a step here.

**How to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
`hurlenko/filebrowser` is not the official Docker image, to have support here you will have to use `filebrowser/filebrowser`. Since you have no issues by accessing Filebrowser directly, your issue is related to the proxy configuration. Ensure that the proxy is forwarding the requests correctly.

**Comment by KKDavion** [comment]
Thanks for the response. I don't use Github often and just realized my initial message had errors due to use of angle brackets. They've been replaced and clarified.

I replaced `hurlenko/filebrowser` with `filebrowser/filebrowser` in my [stack](https://i.gyazo.com/229d3930a9f7523ad1ef055a159e06cb.png) and added the [necessary file](https://i.gyazo.com/d2276a575f801367e326157ca5aba928.png), and the issue persists. Any variation in proxy settings does not solve this issue. Swapping used ports between FoundryVTT (which I have confirmed is working correctly through Caddy and DuckDNS) and FileBrowser causes the issue to persist, with Foundry working through port Public:8080 and Filebrowser failing on Public:30000.

Again, unsure where the issue lies at this point. Would appreciate some guidance. Thanks.

**Comment by ramiresviana** [comment]
Please provide logs from Filebrowser and Caddy. By default Filebrowser will output all errors to console and enabling Caddy [debug](https://caddyserver.com/docs/caddyfile/options#debug) option will provide a lot of information. A browser HAR file is also very helpful.

**Comment by KKDavion** [comment]
Attached below are my logs for Filebrowser and Caddy, as well as HAR files for local and domain based connections. Please let me know if anything else is necessary.

[Logs+HAR.zip](https://github.com/filebrowser/filebrowser/files/8683141/Logs%2BHAR.zip)

**Comment by ramiresviana** [comment]
The HAR files indicate that your server is not responding requests on the port 8080 when acessing it externally, this usually happens when there's an issue with firewall or no service is listening on that port. Caddy does not ignores a request when a error happens, it provides a response with the error code. This shows that requests are not reaching the Caddy server. What happens when you try hosting only Caddy and Filebrowser?

Your Caddy log is very minimal, it does not contain any errors or logged requests. Can you please use the [debug](https://caddyserver.com/docs/caddyfile/options#debug) option and provide a new log? It should log all requests and errors with that option enabled.

**Comment by KKDavion** [comment]
Hosting only Caddy and Filebrowser has no change on the issue. Again, unless there's an error on my end, the debug option is enabled and has been since the last test. Attached below are my docker-compose.yaml, Caddyfile, and Caddylog.log files of this current test, with the log having been active since my last message.
[Compose+Caddyfile.zip](https://github.com/filebrowser/filebrowser/files/8693756/Compose%2BCaddyfile.zip)

**Comment by ramiresviana** [comment]
Your Caddy server is unreachable, the docker-compose file is exposing ports 80 and 443 for Caddy, but the Caddyfile is using ports 30000 and 8080. Please review your configuration and check the documentation for Caddy (https://caddyserver.com/docs/) and Docker (https://docs.docker.com/).

**Comment by KKDavion** [comment]
Ah, so it is an issue on my end. Thanks for the guidance on the matter, I'll close this issue unless I find it to be relevant again
