### ISSUE TITLE
Upload only files of a specific format

### ISSUE THREAD

**Issue by marcuzz0** [filebrowser/filebrowser#1948]
hi is it possible to upload only files of a specific format?

**Comment by ramiresviana** [comment]
You can use rules to control access of directories and files, with regex allowing more complex rules. This example allows the user to access and upload only files and directories having an empty or pdf extension:

![image](https://user-images.githubusercontent.com/59319979/167861075-8e40d070-b6c0-4e4d-938e-149e87b97a44.png)

**Comment by marcuzz0** [comment]
I tried the rule by checking regex and allow but it continues to import files with format other than pdf, for example my user can only upload pdf files and not other formats

**Comment by ramiresviana** [comment]
The provided example does what you have requested. Here's the description of what is does:

`.*\..*` : blocks access of items that contains any extension.
`.*\.pdf` : allows acessing items that contains .pdf extension

This results in only items that contains .pdf extension being acessible.

**Comment by baur** [comment]
> .*\.pdf

not affects:

![image](https://github.com/filebrowser/filebrowser/assets/2898361/e53f0315-b96e-49ff-8097-6cc8650c2b0f)

**Comment by baur** [comment]
It depends order of Roles:
this works
```
/folder --allow 
.*\..* 
.*\.pdf --allow
```

but this is not affects
```
.*\..* 
.*\.pdf --allow
/folder --allow 
```
It would be nice if allowed extension will be as special option

Yes, regex is cool, but it must be applied in specific cases

**Comment by joel72265** [comment]
Thank you for a wonderful application.

This setting works but please make this setting more intuitive

**Comment by Owned67** [comment]
> It depends order of Roles: this works
> 
> ```
> /folder --allow 
> .*\..* 
> .*\.pdf --allow
> ```
> 
> but this is not affects
> 
> ```
> .*\..* 
> .*\.pdf --allow
> /folder --allow 
> ```
> 
> It would be nice if allowed extension will be as special option
> 
> Yes, regex is cool, but it must be applied in specific cases

Ive try but seems not work on the latest version...
