### ISSUE TITLE
new user can't create new file ( when specified scope doesn't exist )

### ISSUE THREAD

**Issue by chinglinwen** [filebrowser/filebrowser#195]
### 3. What are you trying to do?
Create user, with user's scope( say user1 ), and create a new file.

### 4. What did you expect to see?
I expect it can create user without the need to manual create the folder path on the terminal.

### 5. What did you see instead (give full error messages and/or log)?
1. user1's folder on the os has not been created
2. the user's UI homepage shows "This location can't be reached."
3. it can't create new file on the user's UI.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

start as

```
filemanager -s users -p 5000 &> f.log &
```

login as admin, and then create user user1, assign the scope users/user1

login as user1, see the homepage text (should not says can't reached), try if it can create new file.

version:
```
filemanager version 1.1.1
```

**Comment by hacdias** [comment]
It's the correct behavior. File Manager isn't supposed to create a folder for you when you set the user's scope. The user's scope should be an already existent folder.

I'll think about this. I don't whether or not implementing this is a great idea though.

**Comment by chinglinwen** [comment]
> It's the correct behavior.

We may have different scenery for the situation of creating user, I think it's inconvenient for the extra step to create the scope at the terminal.

Good to know you'll thought about this.

**Comment by hacdias** [comment]
This will be out in the next release 😄

**Comment by chinglinwen** [comment]
Good to hear that !   :+1:
