### ISSUE TITLE
r.text is not a function

### ISSUE THREAD

**Issue by ahonggea** [filebrowser/filebrowser#1951]
**Description**

version: docker:s6
Error renaming file name or error moving file

**What is happening instead?**
the operation fails and throws' r.text is not  a function' 

**Additional context**
r.text is not a function
![image](https://user-images.githubusercontent.com/53167116/168567698-3955e7e6-9ac7-4555-a5b0-420a30d55fbd.png)

**How to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
There's an issue with your network, making the browser unable to reach the server. A more friendly message for that error was added and will be available on the next Filebrowser release.
