### ISSUE TITLE
add webdav

### ISSUE THREAD

**Issue by yuyang233** [filebrowser/filebrowser#1955]
WebDAV function should be added

**Comment by mckaygerhard** [comment]
its a great idea.. **but errr in whict way?**.. its nonsense **cos webdav its just the same but without the web ui!**

**Comment by yuyang233** [comment]
Maybe we can add new options, configure users and permissions in web pages or configuration files, and then connect with WebDAV client.

**Comment by yuyang233** [comment]
> its a great idea.. **but errr in whict way?**.. its nonsense **cos webdav its just the same but without the web ui!**
Maybe we can add new options, configure users and permissions in web pages or configuration files, and then connect with WebDAV client.

**Comment by yuyang233** [comment]
Maybe you can add new options, configure users and permissions in web pages or configuration files, and then connect with WebDAV client.

**Comment by UbioZur** [comment]
> its a great idea.. **but errr in whict way?**.. its nonsense **cos webdav its just the same but without the web ui!**

It's not nonsense, but indeed defining use case for webdav would help define in which ways.
I don't know enough about webdav to says any details. But here are some use cases:

* Integrating OnlyOffice android app to connect to the filebrowser server (through webdav as it's an option for OnlyOffice) to edit the documents via the app.

* Integrating filebrowser server to the computer file browser (explorer, thunar etc) for a more seamless experience. Or doing like any online cloud storage, and allow the integration of the files from the servers as a 'drive' on the system.

**Comment by mckaygerhard** [comment]
> It's not nonsense, but indeed defining use case for webdav would help define in which ways. I don't know enough about webdav to says any details. But here are some use cases:

yes.. good way to support the issue lest see:

>     * Integrating OnlyOffice android app to connect to the filebrowser server (through webdav as it's an option for OnlyOffice) to edit the documents via the app.

This is a great idea.. but i noted that webdav demands high good configuration at the server side respect the app so that's the reason that nextcloud and similar apps implements their own webdav and notify that the webserver build in must be disables.. 

that means the best and correct way to support that idea must be by having own webdav implementation, maybe this will be too much work (and taking consideration the lack of progress around the pull request we noted) respect author and manpowers collaborators

i like it but this implies more code and manpower collaboration and coordination

> 
>     * Integrating filebrowser server to the computer file browser (explorer, thunar etc) for a more seamless experience. Or doing like any online cloud storage, and allow the integration of the files from the servers as a 'drive' on the system.

unusefully .. that sounds windoser only idea.. we already have pcman, caja, thanar etc that already provides all the required access using all the protocols that gvfs provides

**Comment by mckaygerhard** [comment]
puff was closed.. when?

**Comment by samil-kale** [comment]
Webdav is a good standard and often used as alternative to google-drive and dropbox for syncing configuration files.
At the moment I'm running a dedicated webdav server in addition to filebrowser to enable that kind of functionality. But integrating it into filebrowser itself would increase the value of the app.

**Comment by crim50n** [comment]
I fully support. Apart from the obvious advantages for webdav mounting on desktop computers, this functionality is very useful for mobile devices, where using the web version of filebrowser is not as convenient as on a computer.

**Comment by Eiziv** [comment]
pls add

**Comment by rockstorm101** [comment]
> we already have pcman, caja, thanar etc that already provides all the required access using all the protocols that gvfs provides

Can anyone expand on how to access filebrowser from Caja or Thunar? Or did I read that sentence wrong and such access is not (yet) supported?

**Comment by mckaygerhard** [comment]
> Can anyone expand on how to access filebrowser from Caja or Thunar? Or did I read that sentence wrong and such access is not (yet) supported?

there is not implementatin yet of webdav.. also github staled and close the issue.. author just lazy about the project.. in conclusion we need people that fork (cos author does not responds) and give some love to the project

is the current status

**Comment by reddec** [comment]
Implemented in fork https://github.com/gtsteffaniak/filebrowser/pull/1764
