### ISSUE TITLE
docker health check fails when user specifies port via environment

### ISSUE THREAD

**Issue by hereisderek** [filebrowser/filebrowser#1956]
**Description**
docker health check fails when user specifies port via environment

**Expected behaviour**
health check passes

**What is happening instead?**
fails

**Additional context**
docker provides environment variable to specify port running the service however health check is hard coded against port 80

**How to reproduce?**
run docker with specified port on any other than 80

**Files**

**Comment by o1egl** [comment]
What is the use-case of changing the app port within the docker container?

**Comment by tr4cks** [comment]
Typically if you use `SWAG` (reverse proxy running on the same containerized network as `filebrowser` container) the port used in the default configuration for `filebrowser` is `8080`, so you have to change all references in the configuration file. But obviously this is really minor and not a blocking problem.
