### ISSUE TITLE
Modification of share time on already shared links or sharing custom URLs

### ISSUE THREAD

**Issue by githubbiswb** [filebrowser/filebrowser#1958]
**Is your feature request related to a problem? Please describe.**
I set a share link with too short of a timeout and I would like to extend it. 

**Describe the solution you'd like**
Either of the 2 following options:
1. Modification of share times on links that haven been shared 
2. A custom URL instead of a random one - This would work because I could just delete the current link, reshare with the same url and extend the time

**Describe alternatives you've considered**
I can modify the .db file, the share link looks in readable text, so I would reshare the file with a better length and then modify the url. Backups of course would be critical

**Additional context**
Nothing I can think to add, but happy to answer questions if what I am looking for isn't clear.

**Comment by githubbiswb** [comment]
Un-stale me please, still wanting to request this as a feature

**Comment by githubbiswb** [comment]
Un-stale me please, still wanting to request this as a feature

**Comment by githubbiswb** [comment]
Un-stale me please, still wanting to request this as a feature

**Comment by githubbiswb** [comment]
Un-stale me please, still wanting to request this as a feature

**Comment by zfxkj** [comment]
@githubbiswb 我实现了这个功能[zfxkj/filebrowser](https://github.com/zfxkj/filebrowser)

**Comment by zfxkj** [comment]
> **Is your feature request related to a problem? Please describe.** I set a share link with too short of a timeout and I would like to extend it.
> 
> **Describe the solution you'd like** Either of the 2 following options:
> 
> 1. Modification of share times on links that haven been shared
> 2. A custom URL instead of a random one - This would work because I could just delete the current link, reshare with the same url and extend the time
> 
> **Describe alternatives you've considered** I can modify the .db file, the share link looks in readable text, so I would reshare the file with a better length and then modify the url. Backups of course would be critical
> 
> **Additional context** Nothing I can think to add, but happy to answer questions if what I am looking for isn't clear.

Sharing custom url is implemented by me. Please   refer to [zfxkj/filebrowser](https://github.com/zfxkj/filebrowser)
You can just change the docker image name from `filebrowser/filebrowser` to `zfxkj/filebrowser`

**Comment by armando-puche** [comment]
Sharing custom url is implemented by me. Please refer to [zfxkj/filebrowser](https://github.com/zfxkj/filebrowser)
You can just change the docker image name from filebrowser/filebrowser to zfxkj/filebrowser #

Sharing custom url has been integrated?
