### ISSUE TITLE
Directory Listing is too slow!!

### ISSUE THREAD

**Issue by banchchuoi** [filebrowser/filebrowser#1960]
I used file browser version 2.21.1 but it get stuck very long time to browse files in a directory that has 10K++ video files despite configured with --disable-type-detection-by-header option, but no effect, here is my configuration:

/etc/filebrowser.json
{
"port": 8080,
"baseURL": "",
"address": "x.x.x.x",
"log": "stdout",
"database": "/etc/filebrowser.db",
"root": "/u01/camera"
}
/etc/systemd/system/filebrowser.service
[Unit]
Description=File Browser
After=network.target
[Service]
ExecStart=/usr/local/bin/filebrowser -c /etc/filebrowser.json --disable-preview-resize --disable-type-detection-by-header --cache-dir /u01/cache
[Install]
WantedBy=multi-user.target
Can somebody help me?

**Comment by kcranky** [comment]
I've tested this on the raspberry pi 4b using both 32 and 64 bit versions or raspberry pi OS.
While 64 bit is considerably faster (around a minute as opposed to around 5 or 6), it's not anywhere near "as fast as ls" as a comment on issue https://github.com/filebrowser/filebrowser/issues/1566 would suggest.

**Comment by niubility000** [comment]
In this case, we may use "virtual list" to solve it. Or just simply seperate your large folder to several small ones.
