### ISSUE TITLE
When you add or delete files, the page title is displayed repeatedly

### ISSUE THREAD

**Issue by y1jiong** [filebrowser/filebrowser#1969]
**Description**

When you add or delete files, the page title is displayed repeatedly.

**Expected behaviour**

When adding or removing files, the page title only shows the current folder name.

**What is happening instead?**

![image](https://user-images.githubusercontent.com/59520517/172044156-6480535a-07c0-46ad-b7e8-6be662bd0ed1.png)

**Additional context**

Without.

**How to reproduce?**

Just add or delete files.

**Files**

Without.

**Comment by y1jiong** [comment]
Could someone reply me?

**Comment by o1egl** [comment]
I can't reproduce it. Which version of the filebrowser are you using?

**Comment by y1jiong** [comment]
> I can't reproduce it. Which version of the filebrowser are you using? 

The latest version. v2.22.1.

If still unable to reproduce, I can record the screen for reference.

**Comment by y1jiong** [comment]
Not only does this happen for adding and removing files, the same thing happens for editing filenames.  I'm going to try it today to see if this happens with the Chinese interface.

**Comment by y1jiong** [comment]
> Not only does this happen for adding and removing files, the same thing happens for editing filenames. I'm going to try it today to see if this happens with the Chinese interface.

I confirmed that not only in Chinese interface, but also in English interface has the same problem.

**Comment by y1jiong** [comment]
Step 1
![image](https://user-images.githubusercontent.com/59520517/173982036-e95f17da-7092-4bc9-ae71-6b8ae1af1f6c.png)

Step 2
![image](https://user-images.githubusercontent.com/59520517/173982069-3037ee8e-ee1c-40c7-a3ff-afe3fbe93354.png)

Step 3
![image](https://user-images.githubusercontent.com/59520517/173982120-1022bc63-89db-43d3-9a91-da33d758e0eb.png)
![image](https://user-images.githubusercontent.com/59520517/173982152-4d04c7d7-9ea8-4671-beb1-31520927c2fe.png)

**Comment by y1jiong** [comment]
> > I can't reproduce it. Which version of the filebrowser are you using?
> 
> The latest version. v2.22.1.
> 
> If still unable to reproduce, I can record the screen for reference.

I gave the reproduced picture flow in the last comment.

**Comment by jlucansky** [comment]
Still ongoing issue on latest version 2.22.4

**Comment by y1jiong** [comment]
still exists...

**Comment by ramiresviana** [comment]
This is indeed an issue and needs to be fixed. The current file/directory name is prefixed to the page title every time the user does an action. The following code must be enhanced:

https://github.com/filebrowser/filebrowser/blob/c1e6d5869acf32cda22fa7dd532ebb6130061b7b/frontend/src/views/Files.vue#L119

**Comment by y1jiong** [comment]
> This is indeed an issue and needs to be fixed. The current file/directory name is prefixed to the page title every time the user does an action. The following code must be enhanced:
> 
> https://github.com/filebrowser/filebrowser/blob/c1e6d5869acf32cda22fa7dd532ebb6130061b7b/frontend/src/views/Files.vue#L119

Thanks for your help to fix it. I'm very grateful.

**Comment by y1jiong** [comment]
keep alive the issue

**Comment by y1jiong** [comment]
This issue still exists in version 2.24.2.

**Comment by baur** [comment]
Same behavior #2325
