### ISSUE TITLE
How to display other disk file

### ISSUE THREAD

**Issue by aiastia** [filebrowser/filebrowser#197]
I put caddy on `C:\Users\lenovo \Desktop` inside, 
I configured

```
:8888 {
  root E:\a
  timeouts none
  gzip
  filemanager / {
    show  E:\a
    database patch
  } 
```

When I visit 8888, or show the caddy folder inside the content
I've found some on the web, but I think I need your help

__win10

**Comment by hacdias** [comment]
Hello @aiastia! I really want to help you, but I didn't quite understand what you said. 😞 Could you try to be a bit more clear, please?

**Comment by Equim-chan** [comment]
Use `E:\\a` instead of `E:\a`.

**Comment by aiastia** [comment]
![1](https://user-images.githubusercontent.com/19776350/29202554-e2a9ee54-7e9b-11e7-87c1-5b1c7535a977.PNG)
![default](https://user-images.githubusercontent.com/19776350/29202555-e30c7f88-7e9b-11e7-8aa5-74cea33f8816.PNG)
![3](https://user-images.githubusercontent.com/19776350/29202556-e3726ac8-7e9b-11e7-828e-e9457dc5ba13.PNG)
 ……

**Comment by Equim-chan** [comment]
请问你用的是什么版本的 Caddy？后续的 filemanager 版本把设置的签名改了。你这个配置的是旧式的。

建议参考一下最新的文档 https://caddyserver.com/docs/http.filemanager

**Comment by aiastia** [comment]
2017‎.‎8‎.6‎.，‏‎11:27:26 
[caddy_v0.10.6_windows_amd64_custom.zip](https://github.com/hacdias/filemanager/files/1217034/caddy_v0.10.6_windows_amd64_custom.zip)

How should i configure? Can you help me? This is the version I use

**Comment by aiastia** [comment]
:8888 {
 root E:\\bt
 timeouts none
 gzip
 filemanager /  {
 show E:\\bt
  database C:\Users\lenovo\.caddy\filemanager\7dfe9c406b4ce2c91c8b2f43828dac72.db
 }
}

**Comment by Equim-chan** [comment]
try this
```
:8888 {
    root E:\\bt
    timeouts none
    gzip
    filemanager / E:\\bt {
        database C:\\Users\\lenovo.caddy\\filemanager\\7dfe9c406b4ce2c91c8b2f43828dac72.db
    }
}
```

**Comment by aiastia** [comment]
Seems to be unable to use
Caddy can not allow, how should i provide error log, I do not know win10

**Comment by Equim-chan** [comment]
Run `caddy -validate` to check the syntax of your config file.

**Comment by aiastia** [comment]
/e/caddy
$ caddy -validate
bash: caddy: command not found

$ ls
caddy.exe*  Caddyfile  init/

**Comment by Equim-chan** [comment]
Please ensure that `caddy` is in your `$PATH`, whilest `Caddyfile` under your cwd.

Plus, this is not actually an issue of the current project. Move along to https://caddy.community/

**Comment by aiastia** [comment]
$ ./caddy.exe
Activating privacy features... done.
http://:8888

Has been able to run, but still the same as before
It is still showing the directory caddy.exe ... ... 
E:/caddy 
I just want to show E: // bt

This is the configuration file
````
:8888 {
    root E:\\bt
    timeouts none
    gzip
    filemanager / E:\\bt {
        database patch
    }
}

**Comment by hacdias** [comment]
This is weird... I don't have this problem here, but the value "E:\\bt" is only used for *new* users. The initial user was created with the initial value.

On http://localhost:8888 go to: **Settings** → **Global Settings** → **User Management** → Click the button to edit your user → Change the scope → **Save**.

Hope it helps!

**Comment by aiastia** [comment]
Yes yes, has been successful. Thank you very much, there are friends before
![image](https://user-images.githubusercontent.com/19776350/29204859-f812ec9a-7eab-11e7-904b-83987d8eff23.png)

**Comment by hacdias** [comment]
No problem! 😄

**Comment by chinkiko** [comment]
Hi, can I set scope to "root" in windows?  Access to all disks? (C:/;D:/;E:/;F:/;etc)
My solution now is creating syslink for all disks, like "mklink /D link2X X:\"
