### ISSUE TITLE
user path scope changes?

### ISSUE THREAD

**Issue by 0x0013** [filebrowser/filebrowser#1980]
**Description**
Not sure if this is a bug or just intended change of behaviour in a recent version.
In our setup, during provisioning we launch a container with commands in order:
    /filebrowser config init
    /filebrowser config import /customconfigfile.json
    /filebrowser users import /customusersfile.json
    /filebrowser

in `customconfigfile.json` we have, among other options, the root path
    "root":"/path/to/data/"
and in `customusersfile.json` we have users with scope defined as absolute path, for example
    "scope":"/path/to/data/"

This worked fine until v2.21.1, but since a recent update (I think v2.22.0), I observed no files in web ui, and 404 errors.

Looking further, I saw it complaining about missing files in `/srv` (not our data directory) and realized the "root" setting gets overwritten by the default config file, which has `/srv` as root. I attempted creating another running config file (in addition to the imported one, as the structure differs and it seems filebrowser cannot run without a config file), but the files were still not visible. I then found that the "scope" now gets treated as a path relative to the configured "root", so with our config I was looking into a new directory "/path/to/data/path/to/data/".

**Expected behaviour**
Previously working config would keep working.

**What is happening instead?**
Scope paths are changed

**Additional context**
My main question is if this is intended behaviour, and will be staying so, or if it is an unintended bug. I would not want to set the user scope to "/" to find in a later update that they are now scoped to system root. Will all user scopes now be relative to the configured "root"?

**Comment by ramiresviana** [comment]
As mitigation for the issue #1954, a new behavior for the user scope was introduced on v2.22.0:

- The user scope is now relative to the application root which is determined by the working directory or the `root` option.
- A new option was introduced allowing to define the base path for user home directories.
- Adjustments are required for existing installations using absolute path or drive letters on Windows systems.

Despite being a sudden change, this should have been the correct behavior since the beginning. The previous behavior was unpredictable and could introduce security issues.

**Comment by jyr45** [comment]
> As mitigation for the issue #1954, a new behavior for the user scope was introduced on v2.22.0:
> 
> * The user scope is now relative to the application root which is determined by the working directory or the `root` option.
> * A new option was introduced allowing to define the base path for user home directories.
> * Adjustments are required for existing installations using absolute path or drive letters on Windows systems.
> 
> Despite being a sudden change, this should have been the correct behavior since the beginning. The previous behavior was unpredictable and could introduce security issues.

Is there any way to solve the problem or to be able to change that under the responsibility of the user?

**Comment by o1egl** [comment]
You can change the app root path by providing it as `-r /`.

**Comment by jyr45** [comment]
> You can change the app root path by providing it as `-r /`.

where did you make the change? or what command do I use for that? 
In my case it is being used in thunder

**Comment by niubility000** [comment]
> where did you make the change? or what command do I use for that? In my case it is being used in thunder
something like:
./filebrowser -d filebrowser.db config set --root /

**Comment by JSouthGB** [comment]
For anyone else looking for a solution, I modified the systemd service file and updated `WorkingDirectory` to below. Filebrowser now starts at `/` instead of the user directory.

`WorkingDirectory=/`
