### ISSUE TITLE
Cannot set up.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1983]
I did the setup by looking at "https://filebrowser.org/installation".
But when I run "filebrowser -r /path/to/your/files" I get "2022/06/10 14:33:26 No config file used
2022/06/10 14:33:26 Listening on 127.0.0.1:8080"
I am getting a log message "No config file used 2022/06/10 14:33:26 Listening on 127.0.0.1:8080" and cannot setup.
The web page is still loading all the time.
What should I do?

**Comment by ramiresviana** [comment]
There's nothing wrong with the messages displayed on the server output, your server is available and can be accessed on the address 127.0.0.1:8080. Changing the listening address and port can be done using CLI options, check https://filebrowser.org/cli/filebrowser

**Comment by ghost** [comment]
Thank you for answering
I have apache as a reverse proxy, but was that wrong?

**Comment by ramiresviana** [comment]
> The web page is still loading all the time.

This shows that requests are not reaching the Apache server, ensure that your proxy is properly configured.

**Comment by ghost** [comment]
Thank you for answering
When I reviewed the apache settings, I just got the wrong port number.
