### ISSUE TITLE
the cpu rise continuously

### ISSUE THREAD

**Issue by MurphyDoe0815** [filebrowser/filebrowser#1985]
the docker container in proxmox makes the cpu rise continuously from 1-5%
 it is a constant up and down
stopping the container makes the cpu rest

**Comment by o1egl** [comment]
Are you sure that no one accesses the service at that time? It might be caused by the thumbnails/preview creation

**Comment by MurphyDoe0815** [comment]
100%! 
The service is not online at the moment and I was alone in the network. 
The only guess is that a scan is continuously taking place.
At least that's what it looks like. 
It constantly swings up and down from 1-5% of the processor load, but the previous versions had the same problem. 
(Proxmox 7.x + Intel I5)

**Comment by o1egl** [comment]
Filebrowser doesn't do any background scans

**Comment by MurphyDoe0815** [comment]
That's not what I meant to say. 
I haven't noticed anything like that either.
It could have been that the programme keeps searching for "new files"?
Filebrowser without Docker is without problems.

**Comment by Aqaao** [comment]
I've noticed this too.
in `sar -u 1 50`
this is binary runing
![CopyQ hdAypn](https://user-images.githubusercontent.com/110408568/203016308-35d847a1-d8de-42cc-a37e-363ab3902b19.png)
this is docker runing
![CopyQ APcaAU](https://user-images.githubusercontent.com/110408568/203017056-f88d195b-6bc8-4f74-b918-05476d863f9d.png)

**Comment by kazykenov** [comment]
Try disabling healthcheck for your container
```
services:
  filebrowser:
    image: filebrowser/filebrowser
    ...
    healthcheck:
      disable: true
```
