### ISSUE TITLE
Show size of folders

### ISSUE THREAD

**Issue by yurividal** [filebrowser/filebrowser#1987]
Is it possible to show the size of folders? This would be very useful

**Comment by o1egl** [comment]
Because the folder size calculation is resource intensive, we do not plan to add this information to the file list view. We might consider adding it as an on-demand feature. Same as we do for checksum calculations

**Comment by berot3** [comment]
Hi! I hope this is still on the radar, even when this issue is closed?

Wanted to give one more use-case: filebrowser as a ncdu-replacement. Instead of using console or other tools it would be great if one could sort by size! An easy way to find what is maybe too big and needs checking.

**Comment by patrickelectric** [comment]
That feature would be pretty nice to have!

**Comment by awsms** [comment]
> We might consider adding it as an on-demand feature. Same as we do for checksum calculations

Any news on this?

**Comment by lohmatij** [comment]
Calculating folder size is resource intensive, but manually checking folder sizes takes enormously more time. 

My filebrowser instance is installed in docker and the storage is connected through Rclone Docker Volume Plugin. It means files are not accessible anywhere but inside the Docker container. Currently I have to ssh to my server, than attach to Filebrowser container and then investigate with du. It takes same processing power as Filebrowser would initially spend, but is super inconvenient.

**Comment by gingerbeardman** [comment]
yes please

**Comment by antonio1475** [comment]
Hi @o1egl given that @gtsteffaniak implemented this on his fork https://github.com/gtsteffaniak/filebrowser/pull/218, could this be done in Filebrowser?

Thank you

**Comment by gtsteffaniak** [comment]
Its possible... but it would require a different approach. I implemented it using an index to store the information, which isn't available in this version. I wouldn't expect the feature to ever come without having something like an index to cache the information so it doesn't take a long time to load every page.

**Comment by therecluse26** [comment]
@gtsteffaniak is there anything preventing you from making a PR back to this repo for that indexed functionality?

**Comment by gingerbeardman** [comment]
A pretty big turn off are the 12 PRs that implement fixes and new features which are currently unmerged
