### ISSUE TITLE
Big uploads fail at Docker image disk utilization of 100%

### ISSUE THREAD

**Issue by GammelSami** [filebrowser/filebrowser#1989]
**Description**
I want to upload a 22GB file to my Unraid server using the File Browser Docker container. (behind a reverse proxy with [this config](https://github.com/filebrowser/filebrowser/issues/706#issuecomment-569264112))

**Expected behaviour**
Uploaded packages should not be stored in docker image file. Upload succeeds.

**What is happening instead?**
Looks like the uploaded packages are stored in Docker image file. My Docker image disk size is 30GB. 
When Docker image disk utilization of 100% is reached following things happen:
- the upload fails with "[internal server error 500](https://cdn.discordapp.com/attachments/333406801158471691/985678595466858567/unknown.png)"
- disk utilization goes back to normal
- no log entry

**How to reproduce?**
Upload a file that is bigger than the free space in docker image disk.

**Comment by o1egl** [comment]
You should mount your desired folder into a docker container. Check docker [docs](https://docs.docker.com/storage/bind-mounts/)

**Comment by GammelSami** [comment]
I have mounted the three volumes from the [instllation guide](https://filebrowser.org/installation#docker): /srv, filebrowser.db and settings.json. What else sould I mount to avoid the issue? Can't find any documentation on that.

**Comment by o1egl** [comment]
If you override the default root in the settings.json, then you need to mount a volume to the correct path

**Comment by GammelSami** [comment]
The json says `"root": "/srv"`. 
I can access all the 9TB of my files. Everything works just fine, even uploading. 
Only when uploads are bigger than the free space in docker image disk, they fail.

**Comment by o1egl** [comment]
If you can access your mounted directory and run out of space during upload, it means that your host volume is full

**Comment by o1egl** [comment]
You can run `df -h` to check your mounted volume capacity

**Comment by GammelSami** [comment]
Still 5TB free on host volume.
```
Filesystem       Size      Used Available Use% Mounted on
/dev/loop2      30.0G     13.1G     16.6G  44% /
shfs            13.0T      8.1T      4.9T  62% /srv
```
Are you shure partial files are stored in /srv during upload? I would have thought that they are in /tmp or something and I needed a fourth mount for that.

**Comment by GammelSami** [comment]
Oh, I just saw that I'm still on v2.15.0 because I use a [slightly modded version](https://hub.docker.com/r/seikv/filebrowser) to be able to also access the files via SMB. I followed [this](https://www.reddit.com/r/unRAID/comments/nkofdd/how_to_install_filebrowser_on_unraid_a_faster/) tutorial. Could that be the cause of the problem?

**Comment by o1egl** [comment]
I see that your /srv folder is 13T of size. Filebrowser uses that folder by default as a root folder

**Comment by GammelSami** [comment]
Yeah. 13T size, 8.1T used, 4.9T free. So I sould be able to upload a 22G file. But during upload the 30G volume get's filled up until the upload fails. 
When I upload a 16G file, the volume get's filled up to 99%, then the file gets "moved"(?) to /srv and then the volume utilization goes from 99% back to normal level.

**Comment by o1egl** [comment]
How are you running the app?

**Comment by GammelSami** [comment]
Running on Unraid. I followed [this](https://www.reddit.com/r/unRAID/comments/nkofdd/how_to_install_filebrowser_on_unraid_a_faster/) setup tutorial.

**Comment by o1egl** [comment]
We are not supporting custom docker images. You can report this issue to the author of that image
