### ISSUE TITLE
Share QR code fails to scan on dark theme

### ISSUE THREAD

**Issue by aarongaut** [filebrowser/filebrowser#1992]
**Description**
I'm unable to get my phone to register the share view's QR code when on dark theme, while light theme works fine. I suspect the issue is that the QR code image is missing a "quiet zone". There should be a white margin around the image. On light theme the page's white background can act as a quiet zone, but this isn't the case for dark theme.

**Expected behaviour**
Able to scan the QR code to access the shared file on mobile when using dark theme.

**What is happening instead?**
On light theme it works fine. On dark theme, my phone fails to register the QR code at all.

**Additional context**
Tested using firefox mobile on an Xperia 1 III

**How to reproduce?**
Try to scan a QR code on a share page while the dark theme is active.

**Files**
Current Appearance:

![Current Appearance](https://user-images.githubusercontent.com/6502657/173580709-7cfe9bd3-d038-457a-b0cc-e5299b3e9596.png)

Mockup with quiet zone:

![Mockup with quiet zone](https://user-images.githubusercontent.com/6502657/173580761-a5be4550-9165-4391-abdf-2a7482814dbb.png)

**Comment by ramiresviana** [comment]
This really affects the QR scanning and needs to be fixed.
