### ISSUE TITLE
How to improve security ?

### ISSUE THREAD

**Issue by donihalim** [filebrowser/filebrowser#1994]
Hi!
First, thank you for this awesome piece of software.
I'd like to ask how to improve the security since I'm planing on exposing the filebrowser to public so I can access my data from anywhere.

Here's the setup:
I have VPS running wireguard server, then connect my homelab which running the filebrowser using docker to the vpn server. Then I setup reverse proxy on my VPS and point the proxy-pass to my homelab running filebrowser so I can access it from the internet. The setup run successfully, I can access it from the internet, but how to improve the security? Since this is my first time exposing my stuff to public.

If you need more info, please let me know.
Thanks.

**Comment by o1egl** [comment]
As an option, you can connect to the VPN from your client machine instead of exposing filebrowser to the internet. There is no other security configuration other than setting a strong user password.
