### ISSUE TITLE
syntax error: unexpected end of file (expecting ")")

### ISSUE THREAD

**Issue by faizulpaydo** [filebrowser/filebrowser#1995]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by faizulpaydo** [comment]
Sat Jun 18 02:26:53 2022 user.info : luci: accepted login on / for root from 192.168.1.216
Sat Jun 18 02:27:45 2022 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 16286)
Sat Jun 18 02:27:53 2022 daemon.info uwsgi-luci: uWSGI worker 2 cheaped.
Sat Jun 18 02:29:34 2022 daemon.info uwsgi-luci: Respawned uWSGI worker 2 (new pid: 17025)
Sat Jun 18 02:29:47 2022 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.
Sat Jun 18 02:32:02 2022 daemon.info uwsgi-luci: sh:
Sat Jun 18 02:32:02 2022 daemon.info uwsgi-luci: syntax error: unexpected end of file (expecting ")")
Sat Jun 18 02:32:02 2022 daemon.info uwsgi-luci:
Sat Jun 18 02:36:20 2022 daemon.info uwsgi-luci: sh:
Sat Jun 18 02:36:20 2022 daemon.info uwsgi-luci: syntax error: unexpected end of file (expecting ")")
Sat Jun 18 02:36:20 2022 daemon.info uwsgi-luci:
Sat Jun 18 02:36:26 2022 daemon.info uwsgi-luci: sh:
Sat Jun 18 02:36:26 2022 daemon.info uwsgi-luci: syntax error: unexpected end of file (expecting ")")

**Comment by ramiresviana** [comment]
I'm unable to detect the cause of this, please provide provide more details.

**Comment by faizulpaydo** [comment]
Mon Jun 20 21:47:47 2022 daemon.info uwsgi-luci: spawned uWSGI master process (pid: 5994)
Mon Jun 20 21:47:47 2022 daemon.info uwsgi-luci: sh:
Mon Jun 20 21:47:47 2022 daemon.info uwsgi-luci: syntax error: unexpected end of file (expecting ")")

**Comment by faizulpaydo** [comment]
daemon.info uwsgi-luci: spawned uWSGI master process (pid: 5994)

after that log come out , syntax error will come out too

**Comment by faizulpaydo** [comment]
![1](https://user-images.githubusercontent.com/98760723/174616520-c299d3b2-288a-4cb2-a7e1-546d54fc29d7.PNG)

by the way , i am use that firmware for my r2s openwrt .. kiddin firmware

**Comment by ramiresviana** [comment]
Can you explain how this is related to FileBrowser? You're having a issue with `uwsgi-luci`, you should contact the developer of it.
