### ISSUE TITLE
why does it say 403 forbidden?

### ISSUE THREAD

**Issue by RuhanGaring** [filebrowser/filebrowser#1996]
**Description**
 i was just trying to edit the files in dolibarr by uploading and adding folders. 

**Expected behaviour**
 i expected it to work and to be able to edit the system files

**What is happening instead?**
 instead, it says 403 forbidden. 

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem. 
![Screenshot 2022-06-18 154639](https://user-images.githubusercontent.com/80693951/174428309-a57afc5e-e6c7-48df-9c2b-ec836a90a5f4.png)

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile. 
![Screenshot 2022-06-18 154639](https://user-images.githubusercontent.com/80693951/174428277-0dbce710-6115-4b99-981a-4b2175b069c0.png)

**Comment by ramiresviana** [comment]
Looks like you're using FileBrowser through a third-party application, please contact your service provider for support.
