### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#1997]
**Description**
I was trying to upload a file as I always do and it took very long. After a while it break and there was a red notify on the right bottom.

**Expected behaviour**
I expected to upload the file as I always do, but it didn't happen.

**What is happening instead?**
I only received the red notification on the right bottom, asking if I wanna report a bug.
There is only a text like [object] [Object], nothing else.

**Additional context**
I do not have any additional context.

**How to reproduce?**
Open FileBrowser, click on the up arrow and select upload file. Then select your file and wait for the upload.

**Files**
I do not have any files that are relevant to you, cause it happens with every bigger file I wanna upload.
Little files are working as normal, bigger files fail to upload.

**Comment by ramiresviana** [comment]
Please update your FileBrowser installation, you should get a proper error message instead of `[object] [Object]`.
