### ISSUE TITLE
Including 7z in Filebrowser (p7zip-full)

### ISSUE THREAD

**Issue by the-lazy-fox** [filebrowser/filebrowser#2001]
**Is your feature request related to a problem? Please describe.**
Hello,
I would like to be able to add 7z package into the image to open rar files. Is there any way to do it?

**Describe the solution you'd like**
Adding the command 7z should work to unzip unrar un7zip all kind of files :)

**Describe alternatives you've considered**
Is there a way to force a package to be added into the image, custom way?
Like `sudo apt install p7zip-full`

Thank you!

**Comment by o1egl** [comment]
You can build a custom docker image using `filebrowser/filebrowser` as a base image

**Comment by kk6mrp** [comment]
For reference, in Alpine Linux: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/31554

**Comment by the-lazy-fox** [comment]
That’s great, it would be super helpful to have this as part of filebrowser!

**Comment by BoKKeR** [comment]
Would you accept PR-s for this feature?
