### ISSUE TITLE
Cannot understand the logic behind the user rules

### ISSUE THREAD

**Issue by rabser** [filebrowser/filebrowser#2003]
**Description**
Cannot understand the logic behind the user rules

**Expected behaviour**
I would like to enable a user to manage only a single directory between a bunch of directories.
I would like to add a regex rule like "deny .*"  then "allow this-dir"  (or vice versa) but I tried to put the deny rule at the top or bottom of the rules but doesn't change the behaviour, in applying a set of rules, precedence should apply but it depends on what logic was chosen.

**What is happening instead?**
The user does not show any directory

**Additional context**
About how to write rules there's no documentation, so probably i'll go to read the source code, but if there are suggestions, are welcome.

**How to reproduce?**

**Files**
I don't know.

**Comment by ramiresviana** [comment]
The rules works by checking if the requested file path matches the pattern. Here is an example: https://github.com/filebrowser/filebrowser/issues/1948#issuecomment-1123770735

**Comment by rabser** [comment]
Thanks for your kind reply, but the rules are always all evaluated or at the first (or last) match exits, like it happens in routers acls, or apache acls?
Because if the rules are always evaluated i suppose that this limits the capability of the rules itself.

i.e.  the basedir contains three directories, “a”, “b”, “c” and if i want the the userA can manage/view only a and b directories and userB can manage/view only the c directory, i believe that this cannot be written in term of rules, or i’m wrong ?
Obviously this is a simple example, but think about a basedir with many subdirs, it’s simpler say “deny all” the  n “allow only …”

**Comment by ramiresviana** [comment]
All rules are evaluated sequentially and the last match determines the result. Keep in mind that when the user accesses an directory, the path contains a `/` suffix. All items listed on that directory, even subdirectories, does not have the suffix. When a directory child matches a deny rule, it will be omitted from the listing.

Here an implementation of your example:

![image](https://user-images.githubusercontent.com/59319979/175576122-aa27de04-9f07-4b39-b436-b9bfdc0ebaa5.png)

The description of what is does:

`^/.+` : blocks any children on the / directory, user sees empty directory when acessing /
`^/a$` : allows /a child, user can see /a on the listing but cannot access it
`^/a/` : allows /a/ and children, user can access anything on /a/

**Comment by rabser** [comment]
I’ll try this later, maybe this thread is eligible to get it’s space in the filebrowser documentation (BTW i was surprised on how was simple to setup, definitely a good piece of code)

**Comment by rabser** [comment]
I can confirm that your solution works! 
Lastly, only as a kind suggestion, a first match logic is usually better than a last match logic, as it's equivalent in expression power, but needs a minor number of checks against regexs, which is heavy by itself.
Reverting the logic obviously breaks retro-compatibility, but if in upgrading you can check the starting release, you can invert the order of the rules.
Anyway, some words more in the GUI about the effective usage of the rules, I think could help.

This (not an) issue can be closed.

**Comment by baur** [comment]
> All rules are evaluated sequentially and the last match determines the result. Keep in mind that when the user accesses an directory, the path contains a `/` suffix. All items listed on that directory, even subdirectories, does not have the suffix. When a directory child matches a deny rule, it will be omitted from the listing.
> 
> Here an implementation of your example:
> 
> ![image](https://user-images.githubusercontent.com/59319979/175576122-aa27de04-9f07-4b39-b436-b9bfdc0ebaa5.png)
> 
> The description of what is does:
> 
> `^/.+` : blocks any children on the / directory, user sees empty directory when acessing / `^/a$` : allows /a child, user can see /a on the listing but cannot access it `^/a/` : allows /a/ and children, user can access anything on /a/

not works for Cyrillic 
I'd like to set available only subfolders -папка2* and *папка5*

```
^/папка1/папка2$
^/папка1/папка2/
^/папка3/папка4/папка5$
^/папка3/папка4/папка5/
```

**Comment by baur** [comment]
may be add 
```go
regexp.MustCompile("[\\p{L}\\d_]+")
```

**Comment by baur** [comment]
to give the user access to the folder 
/folder1/folder2/folder3/folder4. 

I have to configure it like this:

/folder1 --allow
/folder1/.+
/folder1/folder2 --allow
/folder1/folder2/.+
/folder1/folder2/folder3 --allow
/folder1/folder2/folder3/.+
/folder1/folder2/folder3/folder4 --allow.

it's long and not convenient, it would be good to simplify the process

**Comment by rabser** [comment]
This is very old and closed issue, maybe it´s better that you open a new one.

**Comment by baur** [comment]
Generated JS code by ChatGPT:

```JS
function generateConfigSettings(directoryPaths, username) {
  const settings = new Set();
  const processedDirs = new Set();

  for (const path of directoryPaths) {
    const pathSegments = path.split('/').filter(segment => segment !== '');
    let dirPath = '';
    let configPath = '';

    for (const segment of pathSegments) {
      dirPath += `/${segment}`;
      configPath = `filebrowser rules add "${dirPath}" --${segment === '.+' ? 'regex' : 'allow'} --username ${username}\n`;
      if (!processedDirs.has(dirPath)) {
        settings.add(configPath);
        processedDirs.add(dirPath);
      }
      if (segment !== pathSegments[pathSegments.length - 1]) {
        configPath = `filebrowser rules add "${dirPath}/.+" --regex --username ${username}\n`;
        if (!processedDirs.has(`${dirPath}/.+"`)) {
          settings.add(configPath);
          processedDirs.add(`${dirPath}/.+"`);
        }
      }
    }
  }

  return Array.from(settings).join('');
}

const directoryPaths = [
  '/folder1/folder2/folder3/folder4',
  '/another_folder/some_subfolder',
  '/one_more_folder',
  '/folder1/folder2/folder3/folder4', // Adding a duplicate path to test
];
const username = 'user';
const configSettings = generateConfigSettings(directoryPaths, username);

console.log(configSettings);
```

```
filebrowser rules add "/folder1" --allow --username user
filebrowser rules add "/folder1/.+" --regex --username user
filebrowser rules add "/folder1/folder2" --allow --username user
filebrowser rules add "/folder1/folder2/.+" --regex --username user
filebrowser rules add "/folder1/folder2/folder3" --allow --username user
filebrowser rules add "/folder1/folder2/folder3/.+" --regex --username user
filebrowser rules add "/folder1/folder2/folder3/folder4" --allow --username user
filebrowser rules add "/another_folder" --allow --username user
filebrowser rules add "/another_folder/.+" --regex --username user
filebrowser rules add "/another_folder/some_subfolder" --allow --username user
filebrowser rules add "/one_more_folder" --allow --username user
```

but its too hard way, 
Yes, regex is cool, but it must be applied in specific cases
Folder access is very common case, I think it must be from box!

**Comment by ramiresviana** [comment]
@baur let me make it simpler:

`^/.+` : blocks any children on the / directory, user sees empty directory when acessing /
`^/folder1(/folder2(/folder3(/folder4)?)?)?$`: allows given folders with no suffix, user can see but cannot access
`^/folder1/(folder2/(folder3/(folder4/)?)?)?$`:  allows given folders with suffix, user can access
`^/folder1/folder2/folder3/folder4`: allows folder and any child, user can access the destination

**Comment by baur** [comment]
@ramiresviana 
Thank you! will check ASAP

Can you show easy way to globally restrict files by extension  (white list of allowed extensions) to any folder including subfolders
