### ISSUE TITLE
How to build filebrowser from git repository?

### ISSUE THREAD

**Issue by GiancarloAparicio** [filebrowser/filebrowser#2004]
Hi 👋👋👋, I would like to be able to clone the repo and build the binary locally with Docker. I understand that before it was 2 backend and frontend projects that were merged, but I don't know how to join them 😬😅
I have tried this
```bash
CGO_ENABLED=0 go build -a # If I don't do this docker build fails
docker built -t 'filebrowser' .
```
But when I run the image it tells me that it can't find the index.html file, so I also build 'frontend' or as I should do 😕🙏😕🙏

There used to be a guide on how to build in filebrowser/community, but it's outdated.

PS: I want to do this because I would like to be able to modify it for my personal use.

**Comment by ramiresviana** [comment]
`make` is used to issue the required commands to build the binary. FileBrowser can be built by running `make build`. You can also check the steps at https://github.com/filebrowser/filebrowser/blob/master/Makefile

**Comment by nedx86** [comment]
Please, fix some errors
Ubuntu 20.04
```bash
#!/bin/bash

docker build -t docker-filebrowser .
```
i got errors in Dockerfile, to fix them i need to prepend lines with './' symbol:
```
COPY ./docker_config.json /.filebrowser.json
COPY ./filebrowser /filebrowser
```

algo i need update .dockerignore:
```
*
!docker_config.json
!docker/*
!filebrowser
```

and run it
```
#!/bin/bash

docker run --rm \
    --name docker-filebrowser_1 \
    -v $PWD/data/root:/srv \
    -v $PWD/data/database.db:/database.db \
    -p 8080:80 \
    docker-filebrowser
```

i got error on ubuntu 20.04:
```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

to fix this error i need run:
```
#!/bin/bash

make build
CGO_ENABLED=0 go build -a
```
after its run perfect

Thank you.
