### ISSUE TITLE
[Feat] No theme auto switch.

### ISSUE THREAD

**Issue by lollipopkit** [filebrowser/filebrowser#2007]
**Is your feature request related to a problem? Please describe.**
No automatic night mode switching function.  
Themes cannot follow the system switch automatically.

**Describe the solution you'd like**
Add "Follow system" to theme options:  
"Follow system, Dark, Light"

**Describe alternatives you've considered**

**Additional context**

**Comment by xor-gate** [comment]
This is very easy with some javascript/CSS query to detect the OS dark mode preference:

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
https://usefulangle.com/post/318/javascript-check-dark-mode-activated

**Comment by idoodler** [comment]
I'd really appreciate this, currently looking into the code, tho I am new to Vue.js
