### ISSUE TITLE
Please, fix some errors

### ISSUE THREAD

**Issue by nedx86** [filebrowser/filebrowser#2009]
Please, fix some errors
Ubuntu 20.04
```bash
#!/bin/bash

docker build -t docker-filebrowser .
```
i got errors in Dockerfile, to fix them i need to prepend lines with './' symbol:
```
COPY ./docker_config.json /.filebrowser.json
COPY ./filebrowser /filebrowser
```

algo i need update .dockerignore:
```
*
!docker_config.json
!docker/*
!filebrowser
```

and run it
```
#!/bin/bash

docker run --rm \
    --name docker-filebrowser_1 \
    -v $PWD/data/root:/srv \
    -v $PWD/data/database.db:/database.db \
    -p 8080:80 \
    docker-filebrowser
```

i got error on ubuntu 20.04:
```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

to fix this error i need run:
```
#!/bin/bash

make build
CGO_ENABLED=0 go build -a
```
after its run perfect

Thank you.

_Originally posted by @nedx86 in https://github.com/filebrowser/filebrowser/issues/2004#issuecomment-1170243072_

**Comment by o1egl** [comment]
It is not an error. Filebrowser uses goreleaser to build docker images.`docker build -t docker-filebrowser .` will not compile a project

**Comment by nedx86** [comment]
ok, so fixing .dockerignore, Dockerfile

**Comment by o1egl** [comment]
There is nothing wrong with the Dockerfile. You can read about how goreleaser builds docker images [here](https://goreleaser.com/customization/docker/)
