### ISSUE TITLE
Mask field for hiding files and folders

### ISSUE THREAD

**Issue by EvgeniyDoctor** [filebrowser/filebrowser#2010]
**Describe the solution you'd like**
I'd like to hide some files and folders with a mask.

For example, I mounted some folders that I have on my Synology NAS; its OS creates system folders `@eaDir` everywhere: 
![Screenshot 2022-06-30 at 15 07 57](https://user-images.githubusercontent.com/15073200/176648528-af59d45f-0012-4b3b-a35d-6e26a59542b4.png)

or, I'd like to hide Windows system file `thumbs.db`:
![Screenshot 2022-06-30 at 15 08 11](https://user-images.githubusercontent.com/15073200/176649490-888d8942-2288-4353-ac7d-8012be5fc8e3.png)

So, I want some field where I can write `*.db` and hide all *.db files.

**Describe alternatives you've considered**
Maybe there is a way to do it right now? I have FB 2.22.1 in docker.

**Comment by ramiresviana** [comment]
Rules let you control the access to files, check #2003

**Comment by damian-w** [comment]
@EvgeniyDoctor - the regex in File Browser to remove these Synology '@' folders is `/@.+` 🙂
