### ISSUE TITLE
Wrong disk capacity

### ISSUE THREAD

**Issue by bebreshka** [filebrowser/filebrowser#2011]
**Description**

Why does the site show the wrong disk capacity?

**What is happening instead?**

It shows that the capacity is 686GB, although only 638GB, and shows 568GB is occupied, although 529GB is actually occupied ._. The same problem occurs even on a linux virtual machine format GiB

**Files**

![screenshot](https://user-images.githubusercontent.com/66716255/176695413-86cf2e04-1f69-4888-b6a8-efe5df4b754a.png)

**Comment by nedx86** [comment]
One GB is not 1000 Megabytes
It's looks like filebrowser divide 1GB by 1000

Total Bytes / 1000 * 1000 * 1000
Correct will be:
Total Bytes / 1024 * 1024 * 1024
