### ISSUE TITLE
Keep original files option missing on upload?

### ISSUE THREAD

**Issue by admitguy** [filebrowser/filebrowser#2014]
**Description**
When I try to upload a batch of files where some are already existing in the target folder, it only gives me the option to replace them and that makes importing large amounts of data virtually impossible now.
**Expected behaviour**
a prompt to ask me to keep original files or replace them
**What is happening instead?**
it only prompts me to replace the files
**Additional context**

**How to reproduce?**
upload some files. then, try to upload the same files again
**Files**

**Comment by ramiresviana** [comment]
Addition of a button on the replace dialog that allows to keep existing files untouched and upload the new one. This can be resource intensive as it requires every single file to be checked.
