### ISSUE TITLE
Filebrowser个人设置更新提示错误

### ISSUE THREAD

**Issue by cclove845** [filebrowser/filebrowser#2015]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by ghost** [comment]
<img width="1131" alt="iShot_2022-07-02_14 05 43" src="https://user-images.githubusercontent.com/24309441/176988931-2a089d89-2d06-4e23-ba23-da6dbd2b6bb4.png">

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/issues/2012
