### ISSUE TITLE
can not safe the config

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#2017]
When you click the red button, there is a prompt "no connection" in the lower right corner. Please see the figure below.
<img width="1131" alt="iShot_2022-07-02_14 05 43" src="https://user-images.githubusercontent.com/24309441/176988887-2cb3fa96-0da0-436f-8831-05eb5f825115.png">

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/issues/2012
