### ISSUE TITLE
Icons for .heic files missing (no file icon at all)

### ISSUE THREAD

**Issue by raisinbear** [filebrowser/filebrowser#2018]
Hi,
thanks once more for maintining this awesome project!

**Description**
Icons for .heic files are plainly missing. I know from #1908 image preview for .heic is not supported - although #1356 exists and I do not completely understand the state to be expected tbh. There is no generic icon, just background color.
![grafik](https://user-images.githubusercontent.com/68740188/177006854-67b120f9-2935-4093-b8d0-20de7a5f3f35.png)

**Expected behaviour**
If thumbnails for .heic are supported meanwhile, display thumbnail. Else display generic icon.

**What is happening instead?**
No icon at all.

**Additional context**
Filebrowser version 2.22.2

**How to reproduce?**
Upload .heic photo, view location in filebrowser.

**Files**
Any .heic file, e.g. https://github.com/tigranbs/test-heic-images/blob/master/image1.heic .

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, server and browser logs.

**Comment by raisinbear** [comment]
Thanks for the quick reply and sorry for not being more specific. I didn't think of attaching more since it happens on two completely different setups and all browser I tried (Edge, Firefox, Safari iOS).

I just span up a clean filebrowser server (just the linux amd64 binary) with plain defaults on my Debian notebook:
``Linux debian 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux`` and checked using ``Firefox 91.9.1esr (64-bit)``.

I exported the filebrowser (default) config and the Firefox network log:

[config.txt](https://github.com/filebrowser/filebrowser/files/9039551/config.txt)
[firefox.log](https://github.com/filebrowser/filebrowser/files/9039552/firefox.log)

Edit:
There is no output to the log, which is stdout.

Please let me know if I you need any more information.

**Comment by o1egl** [comment]
Duplicate of https://github.com/filebrowser/filebrowser/issues/1908

**Comment by raisinbear** [comment]
@o1egl Sorry I see you closed this. I just want to emphasize this is **not** a duplicate of #1908! I am aware of this issue as I wrote in my initial post. There, generic icons were reported to be displayed, which is exactly what I would expect if heif format was not supported. In the case described here, _no_ icons are displayed at all.
If I understand the firefox network logs correctly, a thumbnail is transmitted - and successfully so - but it is blank.

**Comment by ramiresviana** [comment]
I am unable to identify how the file is being detected as image, on my Windows 10 and Ubuntu 18.04 the mime information for `.heic` files is `application/octet-stream`.

**Comment by raisinbear** [comment]
@ramiresviana thanks for the feedback! I am relatively clueless about this. The Debian machine I tested on was a relatively fresh install and I have no heif support installed there.
