### ISSUE TITLE
V1.2.2, share function can not be used normally.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#202]
v1.2.2 version
Share function to create a share link, visit the link need to login account, after landing prompted "This location can not be reached."
The need to provide additional information about it?
Site non-80/443 port, Use with Caddy .

**Comment by hacdias** [comment]
Hey, I'll fix this ASAP. It only happens when not using Hugo or Jekyll. This was a very stupid mistake I made.

**Comment by hacdias** [comment]
v1.2.3 on the way.
