### ISSUE TITLE
Show EXIF data

### ISSUE THREAD

**Issue by jniggemann** [filebrowser/filebrowser#2024]
**Is your feature request related to a problem? Please describe.**
I sometimes come across digital photos and don't know when they were taken. 

**Describe the solution you'd like**
Show some information from EXIF data when present:
* Date (0x9003 or 0x0132 in IFD0)  - string in form YYYY:MM:DD HH:MM:SS
* Camera Make + Model (0x010F + 0x0110 both in IFD0) - both string
* ExifImageWidth (PixelXDimension 0xA002) and ExifImageHeight (PixelYDimension 0xA003) - both int, unsigned short

If I'm not mistaken, we already include the necessary library anyway.

**Comment by ramiresviana** [comment]
This is a good complement for the file information panel.

**Comment by jniggemann** [comment]
> This is a good complement for the file information panel.

Yes, that's what I was thinking, too. I don't have enough time and I'm not proficient in Go, but someone will eventually send a PR.

**Comment by charles-997** [comment]
To add to this:
- Show and permit modification to the IPTC star rating

The IPTC star rating is what apps like Adobe Bridge, Lightroom, KDE DigiKam use to rate photos 1-5 stars. The data is an open format called IPTC and could be accessed and displayed by any file viewer.

**Comment by jniggemann** [comment]
> * Show and permit modification to the IPTC star rating

_Showing_ is all right with me, as that's just another bit of information to display.
_Editing_ OTOH would need an editor component and would _write_ to the file.
Not sure I'd want that and if we already include the needed libraries.

**Comment by jniggemann** [comment]
Still a usefule FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
Still a useful FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
Still a useful FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
Still a useful FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
Still a useful FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
Still a useful FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
Still a useful FR IMHO, please bot, keep it open ;-)

**Comment by jniggemann** [comment]
I'm trying to figure this out and already have a working prototype that gets camera make and model and also the date the image was taken, all from EXIF. This won't result in a nice PR, as I'm too unsavvy to write a good one. It'll be a useable patch though, and perhaps someone will use that as a starting point.

**Comment by jniggemann** [comment]
@ramiresviana @o1egl My prototype correctly displays exif info in images, but only on the machine I develop on. Moving the binary to another machine, the exif fields are empty (as if the img had no exif data). I build using 'go build', go 1.20 on Debian. Anything else I need to do?

**Comment by jniggemann** [comment]
My bad, because I had used `i.Path` instead of `i.Fs.Open(i.Path)`  - now it works, see below. So far, I only get camera make and model and the date, the image was taken. 
![image](https://github.com/filebrowser/filebrowser/assets/1318059/2b670b8e-290f-4f36-9152-27e46343a4e7)
If anyone's interested, let me know.

ATM, the exif data only shows when the image is displayed directly, it's not yet working when selecting a single directory entry.

**Comment by jniggemann** [comment]
Bump

**Comment by jniggemann** [comment]
I was on vacation and couldn't reply fast enough. Can someone please tell me what to do to get this merged?
