### ISSUE TITLE
Stopped working with error "location can't be reached"

### ISSUE THREAD

**Issue by alfonder** [filebrowser/filebrowser#2028]
**Description**
I use official docker image. After one of recent updates "My Files" tab doesn't work. It shows "This location can't be reached" page and "Error 404" bubble. All other tabs are working.

**Expected behaviour**
"My Files" tab should show files and folders.

**What is happening instead?**
"This location can't be reached" page is displayed.

**Additional context**
File Browser version 2.22.3

**How to reproduce?**
```
docker run -d \
	--restart=always \
	--name filebr \
	-p 7777:80 \
	-v $DL_DIR:/srv \
	filebrowser/filebrowser
```

**Files**
<img width="900" alt="filebrowser" src="https://user-images.githubusercontent.com/9729554/177573963-31cfa0d2-7ad1-42f4-91ad-7a31d8257a7b.png">

**Comment by alfonder** [comment]
One line in log suggests a solution:
`2022/07/06 15:58:49 /: 404 62.217.xxx.xxx lstat /srv/srv: no such file or directory`

**Comment by alfonder** [comment]
Clearing "scope" value for every user solves the problem.
Some time the behavior was changed without any notice. Now scope is automatically prefixed by basepath.

**Comment by pigate-eu** [comment]
I have the same issue on opening the dot files. For example when I am trying to open the .htaccess file on a folder I have the message "This location can't be reached.". Any solution about this issue? I clear the scope of admin and on global settings (empty field) and not work. I am using docker container image (filebrowser/filebrowser). My -u is 0:0 on docker script.
