### ISSUE TITLE
How to change default permission when running as caddy plugin?

### ISSUE THREAD

**Issue by Bitti09** [filebrowser/filebrowser#203]
How can i change the default permission when  filemanager is running as a caddy plugin?

the documentation only  have the no_auth but no allowCommands,allownew & allowEdit part.

in my current usecase it would be good to set the the" allow" settings to false while  no_auth is true.

**Comment by hacdias** [comment]
I'll add this soon. 😄

**Comment by hacdias** [comment]
I'm deploying to the Caddy server right now. [Check the docs!](https://henriquedias.com/filemanager/caddy/).

**Comment by Bitti09** [comment]
Does caddy download link automatically include the update or do I have to
wait for next release version?

**Comment by hacdias** [comment]
It already includes the update!

**Comment by Bitti09** [comment]
Thanks for the update 👍👍👍
