### ISSUE TITLE
I can't access my file path

### ISSUE THREAD

**Issue by jyr45** [filebrowser/filebrowser#2030]
**Description**

In thunder it does not allow me to use my folder my file pool from my pool since the last updates, before if it could be done.
The path is /mnt/NAS/NAS_TEST but the docker sends it to the /data folder even if I configure it on the web.
and if I create a file it creates me in the path in /data/mnt/NAS/NAS_TEST
and it does not take me the path /mnt/NAS/NAS_TEST
And it is not the Nas configuration because in another program it does allow me to access the path /mnt/NAS/NAS_TEST

**Expected behavior**

Being able to view my files but not, it creates the files in the /data path and not in /mnt/NAS/NAS_TEST

**What's happening instead?**

I cannot see the files in the path /mnt/NAS/NAS_TEST, it is always located in the path /data

**Additional context**

![image](https://user-images.githubusercontent.com/91006077/177878192-09f1dec6-018b-4001-b097-c9dc32c748f2.png)
This is the route I want to see but it gives me an error
![image](https://user-images.githubusercontent.com/91006077/177878387-9aeaef8b-e0fb-4537-a954-8a4adede2d54.png)
and if I create a file, it generates the path in /data
![image](https://user-images.githubusercontent.com/91006077/177878845-1592fd26-1726-4122-8f27-11d0badad61e.png)
![image](https://user-images.githubusercontent.com/91006077/177878892-a93fb7b9-1d41-4563-9291-f6d718522557.png)
![image](https://user-images.githubusercontent.com/91006077/177878991-eb297a83-a331-4ccd-9414-32cd330a7b1f.png)

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/issues/1980

**Comment by lhuanyun** [comment]
I have same problem. help me
