### ISSUE TITLE
Support External Authentication methods by making minor changes or adding settings

### ISSUE THREAD

**Issue by wlanut** [filebrowser/filebrowser#2031]
**Is your feature request related to a problem? Please describe.**
There is a slight issue present when using some external authentication methods (tested so far with Cloudflare ZeroTrust and Authelia). When accessing FileBrowser via a shared link, one can then click the Login button on the sidebar and "bypass" external authentication to get to the FileBrowser login page. Depending on what external authentication frontend you're using, you may be able to successfully login if you know the password.

In my testing, both of the external auth methods listed above were able to be "bypassed" when clicking the Login button from the shared link. If the page is refreshed while on that login screen, the authentication kicks in successfully and displays the correct page.

**Describe the solution you'd like**
Forcing a page refresh, or whatever the page refresh does to cause the external auth page to show up, when clicking the Login button from a shared link would probably resolve this issue.

**Describe alternatives you've considered**
Alternatively, allowing an option somewhere to disable/remove the Login button from shared links would resolve this issue at least in my cases described.

Please let me know if I left out any pertinent info or if I'm doing something incorrect here.

EDIT: just found [a comment](https://github.com/filebrowser/filebrowser/issues/1878#issuecomment-1135615197) experiencing this same behavior on another issue - Issue #1878

**Comment by ramiresviana** [comment]
> Forcing a page refresh, or whatever the page refresh does to cause the external auth page to show up, when clicking the Login button from a shared link would probably resolve this issue.

File Browser is a SPA, all the routing logic is handled by the frontend. Once the first page is loaded, the server does not handle the routes anymore, except for api endpoints. Refreshing the page for every route change is not a proper solution.

> Alternatively, allowing an option somewhere to disable/remove the Login button from shared links would resolve this issue at least in my cases described.

Just hiding a button does not solves the issue, the authentication endpoint must be disabled also.
