### ISSUE TITLE
"Auto create user home dir while adding new user" function not working

### ISSUE THREAD

**Issue by guanjianhe** [filebrowser/filebrowser#2032]
User directory is not automatically created when creating a new account

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, server and browser logs.

**Comment by guanjianhe** [comment]
## logs:
```log
2022/07/15 14:56:17 Listening on [::]:8080
2022/07/15 14:56:21 Caught signal interrupt: shutting down.
2022/07/15 14:56:21 accept tcp [::]:8080: use of closed network connection
2022/07/15 14:56:55 Listening on [::]:8080
2022/07/15 14:57:06 /api/renew: 401 192.168.56.1 <nil>
2022/07/15 14:57:07 /api/renew: 401 192.168.56.1 <nil>
2022/07/15 14:57:08 /api/renew: 401 192.168.56.1 <nil>
2022/07/15 14:57:19 new user: test, home dir: [/].
2022/07/15 14:57:54 Caught signal interrupt: shutting down.
2022/07/15 14:57:54 accept tcp [::]:8080: use of closed network connection
```

## configuration:
```config
Sign up:          true
Create User Dir:  true
Auth method:      json
Shell:

Branding:
  Name:
  Files override:
  Disable external links:  false
  Color:

Server:
  Log:           /home/ubuntu/tmp/filebrowser.log
  Port:          8080
  Base URL:
  Root:          .
  Socket:
  Address:       0.0.0.0
  TLS Cert:
  TLS Key:
  Exec Enabled:  false

Defaults:
  Scope:         .
  Locale:        en
  View mode:     mosaic
  Single Click:  false
  Commands:
  Sorting:
    By:
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}

```
## server environment

Ubuntu 20.04.4 LTS

## filebrowser version
V2.22.3

**Comment by ramiresviana** [comment]
The scope field must be empty when adding a new user, otherwise the user directory is not created.

**Comment by EDIflyer** [comment]
Agree works OK for me when scope is empty or `.` 👍

**Comment by guanjianhe** [comment]
> The scope field must be empty when adding a new user, otherwise the user directory is not created.

thank you very much

**Comment by jfmadridc** [comment]
> The scope field must be empty when adding a new user, otherwise the user directory is not created.

this is totally un-intuitive it should change from . to empty if  `Auto create user home dir while adding new user` is selected otherwise users will have global `.` access

i understand is not your fault just didn't know were else to post it, hope it gets improved some day
