### ISSUE TITLE
Filebrowser is Reverse Proxied with nginx and basic auth: Please allow file shares without password

### ISSUE THREAD

**Issue by flower1024** [filebrowser/filebrowser#2034]
**Is your feature request related to a problem? Please describe.**
First of all thank you for this neat File Browser. It helps me a lot.
I often need it when i am away from my server so i use nginx as a reverse proxy with basic auth to access it from the internet.
your file-share functions works great and i would like to use it without a password. but as the share page requests assets (and the file itself) from other locations than /share i can't exclude that folder from basic_auth in nginx.

**Describe the solution you'd like**
i would like to have a way to share files to bypass my basic_auth from my nginx reverse proxy

**Comment by ramiresviana** [comment]
You can configure your proxy to protect the `/api/*` routes, this way the frontend can still be accessed but any action is protected. Allowing users to access a public share without the protection can be done by adding an exception to the `/api/public/*` route.
