### ISSUE TITLE
Prevent share password from autofilling

### ISSUE THREAD

**Issue by Lombra** [filebrowser/filebrowser#2035]
**Is your feature request related to a problem? Please describe.**
Opening the share dialog autofills the share password using my user account password.

**Describe the solution you'd like**
Do not autofill this input.

**Additional context**
Using Firefox 102.

**Comment by Lombra** [comment]
While obviously less disruptive, one might want to give the password change form the same treatment.

**Comment by UbioZur** [comment]
This is probably your password manager (directly firefox or any other third party ones you may be using) that does the autofilling not filebrowser.

Try to disable the autofill from your password manager and see if it does indeed stop filling the password field automatically.

If that works, then it's a matter of deciding either you want to keep the convenience of autofilling your passwords, but have the inconvenience under filebrowser.
Or have the inconvenience of having to manually get your password manager to fill the fields, but not have the problem under filebrowser (and possibly many other websites)

**Comment by Lombra** [comment]
I'm aware that it is my browser that's doing it, but I thought it might be possible to prevent this behaviour by way of web design. There is, for example, an attribute `autocomplete="new-password"` that seems relevant, though I can't speak to its functionality.

**Comment by Towdium** [comment]
Same here, I think adding `autocomplete="new-password"` does the work. Password manager think the input password is the one to login because it is a form input with type "password", but actually it is not. That makes the browser work in a confusing way, and fill my account password as share password.
