### ISSUE TITLE
Unable to drag/drop folders into upload

### ISSUE THREAD

**Issue by SRWM1991** [filebrowser/filebrowser#2040]
Hello. I've been attempting to upload a folder to Filebrowser's Web UI. I click upload and then drag and drop the folder from my hard drive to Filebrowser, but it returns the error message "[object Object]". This is a fairly small file (3.22 GB). 

I've also tried zipping the file, having already added the unzip command to my admin account. Using that method, I'm able to upload the file, but entering "unzip file" in the console has no effect whatsoever. 

Thank you so much for your time.

**Comment by ramiresviana** [comment]
Please update your FileBrowser installation, you should get a proper error message instead of `[object] [Object]`.
