### ISSUE TITLE
Seperate files and directories in the "Create" checkbox

### ISSUE THREAD

**Issue by ReinkeCompleo** [filebrowser/filebrowser#2041]
Hi,
I would like to remove the permission of a user to create a new directory. But the user should still be allowed to create and modify all the files he sees.
Is this already possible and I did not see it?

Thank you in advance for your help.

**Comment by ramiresviana** [comment]
The available user options and permissions are listed at: https://filebrowser.org/cli/filebrowser-users-add. File and directory creation is controlled by the same permission.
