### ISSUE TITLE
001 connection abort while uploading large files

### ISSUE THREAD

**Issue by Tusharkumar0012** [filebrowser/filebrowser#2043]
I am getting Error 001 Connection aborted  when uploading a file of greater than size around 150-250mb . 
Also for first 2-5 minuites upload speed is too slow.
Downloads are fine. Client is on a wifi connection &server is also having a stable 100mbps fiber connection.

_Originally posted by @Tusharkumar0012 in https://github.com/filebrowser/filebrowser/issues/2005#issuecomment-1188149884_

**Comment by o1egl** [comment]
Are you using any proxy server in between? Also, we need filebrowser logs to be able to analyze them

**Comment by Tusharkumar0012** [comment]
I got the problem , it's my cdn cloudflare which has the following upload caps -
100mb - free plan
200mb - pro 
500mb - enterprise.

But I need cloudflare for security. Is there any way we can bypass this limit like distribute the payload in chunks of less than 100 mb and bypass the cloudflare limit ?

Maybe something like this -
![Screenshot_20220719-061744_Chrome.png](https://user-images.githubusercontent.com/50898840/179640486-9c7816f4-4704-4e91-9b0f-0a2cfea2f8d1.png)

**Comment by o1egl** [comment]
Filebrowser doesn't support chunked upload. There is a discussion around it that you can follow https://github.com/filebrowser/filebrowser/discussions/1182

**Comment by StanislavJochman** [comment]
Is there a workaround when using cloudflare?
