### ISSUE TITLE
"Mount --bind" dirs are empty

### ISSUE THREAD

**Issue by EvgeniyDoctor** [filebrowser/filebrowser#2045]
**Description**

I have folder _Files_ in the _srv_ directory. In this folder I'd like to have links to other dirs. For example, I have folder _Files/Folder1_, where _Folder1_ is mounted:

`sudo mount --bind /path/dir Folder1`

But when I open _Folder1_ in FB - it is empty. I changed owner and rights, but no luck.
Symlinks `ln -s` are not supported on Synology NAS.

Here is my **run** command:
`docker run -d --name filebrowser -p 8200:80 -v /path/data:/data -v /path/config:/config -v /path/srv:/srv -e FB_NOAUTH=noauth filebrowser/filebrowser`

FB:  2.22.4

Is there a way to display the content of this folder?

**Expected behaviour**

Content of the mounted folder should be displayed in FB.

**What is happening instead?**

Mounted folder is empty in FB.

**Additional context**

If I add mounted volume to the **run** command, it will work, but I do not want to recreate the container every time.

**How to reproduce?**

Just create a dir and mount some another dir.

**Comment by ramiresviana** [comment]
> **Here is my run command:**
> `docker run -d --name filebrowser -p 8200:80 -v /path/data:/data -v /path/config:/config -v /path/srv:/srv -e FB_NOAUTH=noauth filebrowser/filebrowser`

That command works as expected and is the common user case from majority of Docker users.

> **Additional context**
> If I add mounted volume to the run command, it will work, but I do not want to recreate the container every time.

Docker does not provide a way to change volumes on existing containers, File Browser has not control of that behavior. If you want to persist your customization when running a new container, you must create your own image. Check https://docs.docker.com/engine/reference/builder/
