### ISSUE TITLE
Proxy auth doesn't work with filebrowser API's

### ISSUE THREAD

**Issue by yashcho** [filebrowser/filebrowser#2047]
**Description**
Recently when I tried to use latest version of filebrowser as a docker image, I am not able to work with proxy auth method it redirect to login page and after I sign_in with admin user the dashboard of username came from auth.header is shown. After that I checked some issue pages and found an article which say's to check the Network tab under developer tools and following that I saw the **/api/renew** was throwing **401 error** and in request header the **X-Auth** field was null. 

Similarly for **/api/users** and **filebrowser cmds**, If possible can you check why proxy header value is not honored for API endpoints? :-)

Current config : 
> {
>     "scope": "/tmp/sites",
>     "port": 8080,
>     "address": "",
>     "baseURL": "/filebrowser",
>     "log": "stdout",
>     "database": "/data/filebrowser.db",
>     "root": "/filebrowser",
>     "auth.method": "proxy",
>     "auth.header": "X-Forwarded-User"
> }

**Expected behaviour**

1. After passing header **X-Forwarded-User** value with username it should have shown me filebrowser dashboard.
2. After passing same header to **api/users** should have returned the user json list.
3. After running **filebrowser users ls** and **filebrowser config cat** it should have listed user and configuration.

**What is happening instead?**

1. It redirects to login page returning 401 error in Developer tool for **/api/renew**
2. It redirects to login page returning 401 error in Developer tool for **/api/users**
3. It returns timeout with 401 error on console for **/api/renew**

**Additional context**

UI login  
![image](https://user-images.githubusercontent.com/69308923/179810607-a225346b-12a6-4bdb-b95e-e1b42b95277b.png)

Console logs  
![image](https://user-images.githubusercontent.com/69308923/179808563-e565f9a6-0c42-4d44-b25b-ede9b07ece6b.png)

**How to reproduce?**

1. Use any docker based image (https://filebrowser.org/installation#docker).
2. Pass the config I sent and run the container.
3. Once up check the api using header : curl -H 'X-Forwarded-User: admin' http://0.0.0.0:8080/filebrowser/api/users
4. It returns "401 unauthorized"

**Comment by ramiresviana** [comment]
Currently is not possible to set the authentication method using a configuration file, `auth.method` is not a valid entry. You can use a database from a existing installation with your configuration.

**Comment by yashcho** [comment]
Hello @ramiresviana ,
Thanks for the info, so I have some question

1. Why It didn't logged me the error?
2. Can I use this way to set https://filebrowser.org/configuration/authentication-method#proxy-header?
3. What do you mean by "existing installation"?

**Comment by ramiresviana** [comment]
1. No errors are displayed for invalid config entries.
2. CLI can be used to manipulate settings while File Browser is not running.
3. Run File Browser on some machine and it will create a new database file. The file can be transferred to other machines.

**Comment by yashcho** [comment]
oka @ramiresviana , thanks for the info now how do you suggest me to work with proxy setup and it is the requirement :-) ?

**Comment by ramiresviana** [comment]
File Browser can be used alone and does not require the use of a http proxy.

**Comment by yashcho** [comment]
oka @ramiresviana but the documentation speaks something less anyway leave it, is there a way to use Web API to list, create, update, delete the user as I didn't find any documentation and using cli works without running filebrowser. :-(

In brief, can you suggest some good way to perform CRUD operation for users in filebrowser without using UI?

**Comment by ramiresviana** [comment]
There's no documentation for the api endpoints used by the frontend. If you want to perform operations you have to use the CLI or dive into the codebase.

**Comment by yashcho** [comment]
oka, but for CLI the filebrowser should not be running so syncing the user through LDAP would be difficult any suggestion here?

**Comment by ramiresviana** [comment]
A new feature allowing you to integrate the authentication will be available on the next File Browser version, check https://github.com/filebrowser/filebrowser/pull/1554.

**Comment by yashcho** [comment]
oka thanks for the info, let us know when the API document would be prepared :)
