### ISSUE TITLE
Folder Location for users

### ISSUE THREAD

**Issue by mistrysiddh** [filebrowser/filebrowser#2048]
I've been using file browser for a long time on my raspberry pi as a file-sharing server but I'm unable to find an option for particular location for giving users their own directory in a section
![image](https://user-images.githubusercontent.com/25217451/179926088-87b026df-3a50-4bfc-a83f-8faf173e54ba.png)
As you can see in this photo I have multiple of folder created but I'm unable to give location to created users in settings

**Comment by ramiresviana** [comment]
User directories can be created automatically by enabling the option `Global Settings > Auto create user home dir while adding new user` or manually by changing the option `User Management > Scope`. Keep in mind that we cant help you with outdated and forked versions of File Browser. The official downloads are avaliable on the Github releases page and on the Docker Hub repository at `filebrowser/filebrowser`.

**Comment by mistrysiddh** [comment]
thank you it worked

**Comment by sanha-ddana** [comment]
I’ve been using File Browser on my SFTP server, but I’m encountering some issues when trying to assign specific directories to individual users. Here are the problems:

After assigning a specific directory to a user in the user management settings, the directory doesn't appear in the SFTP server’s File Browser web interface.
After assigning a specific directory to a user in the user management settings, all directories show up, and the permissions are applied to all directories. Additionally, the page doesn't load when I enter the directory path directly in the scope.
