### ISSUE TITLE
Make User.Filesystem an interface

### ISSUE THREAD

**Issue by olihey** [filebrowser/filebrowser#205]
The `User.Filesystem` is a struct of type `fileutils.Dir`.
Any chance this can be changed to an interface instead? That would really make filemanager useful for embedded usage, something we currently evaluating.

**Comment by hacdias** [comment]
Yes, I can make it an interface instead 😄

**Comment by hacdias** [comment]
Hey @olihey! There is a problem with this though: the User.FileSystem must be able to be Marshalled and Unmarshalled as a string to JSON and I'm not seeing a way of doing this using an interface. What do you think?

**Comment by olihey** [comment]
Hehe, that would have probably been my second issue, the User should be an interface as well.
I am not sure if embedding is something you are going after at all but as the code looks today it's not really useful for our case, for example we have our own user database and the filesystem is a virtual one that merges several data sources.
I still really like the project and if your are thinking about making it easier for embedded use, let me know I might help out a bit.

**Comment by hacdias** [comment]
Hey @olihey!

Yeah, making "everything" an interface would be an hassle right now but it could be done. It just depends on _how_ to make the changes. 

Please take a look at this file I wrote before: https://github.com/bruhs/shopy/blob/master/user.go Take a look at the whole package if you want and tell me if that scheme would be of your interest!

Initially I thought about doing like that. Although, in that time, I didn't really need to.

**Comment by hacdias** [comment]
It would help in the way that you could fetch the user from your own source. And with the right changes, you could also use your own File System.

**Comment by hacdias** [comment]
Pinging @olihey

**Comment by olihey** [comment]
😄 Sorry, I think you can close the issue. I tried to change the `User.Filesystem` into an interface but there are quite a lot of place where it's expected to be a `string`. So, I gave up for now. Not highest priority in our project at the moment, unfortunately. I think you should close the issue if you don't plan to do anything about it yet.

BTW: Someone from our team suggested if we could just implement the API for the frontend. Is there some kind of documentation on this?

**Comment by hacdias** [comment]
Hmm... I don't have any docs for that but it is possible to use just the front-end. Did you see the link I sent you? I'm willing to make some changes for this to work if you think that that code design works 😄

**Comment by olihey** [comment]
😮 Sorry, I didn't get this. Yep, the example looks great. That would be bloody awesome.

**Comment by hacdias** [comment]
I'll work on that then.

**Comment by hacdias** [comment]
Done! @olihey 
Take a look at the code 😄 

https://github.com/hacdias/filemanager/blob/master/cmd/filemanager/main.go#L172

**Comment by olihey** [comment]
Awesome, will have a look as soon as I get time.
Thanks!

**Comment by olihey** [comment]
Found time to look at it and now ran into a problem 😉 

https://github.com/hacdias/filemanager/blob/9301966eb7b539ec871d19e760372224498a973c/filemanager.go#L446

The FileSystem is now an interface but OpenFile returns a *os.File struct. This should be changed into an interface as well, probabaly a merge of these interfaces:
- io.Reader
- io.ReaderAt
- io.Writer
- io.Seeker
- io.Closer
