### ISSUE TITLE
How can we preview the PDF&office files when the user account without download permission?

### ISSUE THREAD

**Issue by qrm1982** [filebrowser/filebrowser#2057]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by qrm1982** [comment]
User can not preview the PDF&office files when we create a user account without any permission,it shows "202 Accepted",user  can only preview the TXT files. How can we set it?

**Comment by o1egl** [comment]
To open a file, you need to download it on the client-side that conflicts with a download permission
