### ISSUE TITLE
Set File Permissions

### ISSUE THREAD

**Issue by ghnp5** [filebrowser/filebrowser#2059]
When selecting a specific file or folder, would it be possible to allow changing the file permissions?

The equivalent to running commands like "chmod" and "chown".

Thanks!

**Comment by ramiresviana** [comment]
File Browser does not handle filesystem permissions.

**Comment by ghnp5** [comment]
> File Browser does not handle filesystem permissions.

I understand it doesn't, hence I suggested it. Thank you.

**Comment by o1egl** [comment]
Filebrowser doesn't operate with system users. I don't think we will be adding this feature to the app
