### ISSUE TITLE
File View Mode and Selection Enhancements

### ISSUE THREAD

**Issue by berglh** [filebrowser/filebrowser#206]
This is a great project, so much potential and almost exactly what I'm after. Here are some things I found frustrating that would really improve my workflow with this application:

### File Viewer
When viewing a file, it would be great to have an options to:

1. Move the current file to a folder
2. Select the the current file in view so you can browse photos and select a bunch to do a bulk move operation. I envision a workflow like: Open image file, select with `space bar`, go to next image with `left/right arrow` (already implemented), go to another image, select it with `space bar` then move all the selected files to a new folder. To be fair, this would be addressed in some respects with thumbnails and the file manager view.

### File Manager
In the main file manager page, I noticed multiple selection using `ctrl` is working, but using `shift` to select a range of files is not. This would save "a lot" of hassle when trying to move a range of files.

**Comment by hacdias** [comment]
Hello @berglh! Thanks for the feedback! The `shift` thing was something I though of implementing before but I didn't. It will be out in the next version.

I will also add the Copy/Move buttons to the current files' view.

I'm just quite reluctant relatively to the `space bar` thing. I would prefer to have thumbnails but that's something I have to think about yet. Do you have any idea of how to implement it?

- [ ] Move/copy current file to a folder
- [x] SHIFT to select a range of files

**Comment by hacdias** [comment]
Closing this as frozen in time. If someone else is interested on it, please ping.
