### ISSUE TITLE
Base 64 encoding of shared link

### ISSUE THREAD

**Issue by DarrenPIngram** [filebrowser/filebrowser#2061]
**Is your feature request related to a problem? Please describe.**

As a convenience, when you have the share link button/results pop-up (to copy link) it would be nice to have a pre-coded base64 link as well (extra button).

**Describe the solution you'd like**

As a convenience, when you have the share link button/results pop-up (to copy link) it would be nice to have a pre-coded base64 link as well (extra button).

**Describe alternatives you've considered**

I copy the normal link, go to base64decoder and encode.

**Additional context**

I share a lot of links and there are many reasons for base64. It is a convenience feature request!

**Comment by o1egl** [comment]
What is the use-case for that?

**Comment by DarrenPIngram** [comment]
Sharing in links where you, for example, don't want the host to be at risk
of being spidered by the ever-seeing Google eye.

**Comment by DarrenPIngram** [comment]
Couldn't see how to remove the tag, so...

**Comment by o1egl** [comment]
This feature looks pretty niche. I don't think it should be added to the main codebase. You can always make a fork of the repo and add it there.

**Comment by DarrenPIngram** [comment]
OK. If I only knew how to do that, I would have done it in the first
place...

It's maybe not as niche as you think, but that's another matter :)
