### ISSUE TITLE
How to set docker to no auth

### ISSUE THREAD

**Issue by dudefoxlive** [filebrowser/filebrowser#2066]
I have tried modifying the setting.json file and running the command from the containers command line but nothing works to set it to no auth. Is there something that I am missing? I am running FileBrowser in docker.

**Comment by ramiresviana** [comment]
The `noauth` option can be used to configure the authentication method, check https://filebrowser.org/cli/filebrowser. Keep in mind that using this option only works when there's no existing database file. For existing installations, the `filebrowser config` must be used, check https://filebrowser.org/cli/filebrowser-config-set.

**Comment by UniqueName992** [comment]
Same issue here
> The `noauth` option can be used to configure the authentication method, check https://filebrowser.org/cli/filebrowser.

How can we set that for the **docker**?

> For existing installations, the filebrowser config must be used, check https://filebrowser.org/cli/filebrowser-config-set.

The command returns a timeout error when run in the docker:
```
root@e62bdc813060:/database# filebrowser config set --auth.method=json
2022/07/29 23:17:16 timeout
```
Also tried setting an env variable and modifying the settings.json (using the settings.go as reference) with varying deletions of the database - fishing in the dark with no luck

I removed it by replacing the run command in the systemd folder via a volume mapping
new run file:
```bash
#!/usr/bin/with-contenv bash

exec s6-setuidgid abc filebrowser -c /config/settings.json -d /database/filebrowser.db --noauth;
```
This solution has issues that it could break with future updates, I think we're missing a canonical method, documentation or they just aren't working for the docker.

**Comment by dudefoxlive** [comment]
I wish there was a env that i could set like auth_method=noauth.

**Comment by ramiresviana** [comment]
Environment variables can be used to set options by using the `FB_` prefix, `FB_NOAUTH` for example, as documented at https://filebrowser.org/cli/filebrowser

**Comment by oGAD31** [comment]
> Environment variables can be used to set options by using the `FB_` prefix, `FB_NOAUTH` for example, as documented at https://filebrowser.org/cli/filebrowser

saying i want to use `FB_NOAUTH`, where do i use it? the docker compose fie? the json config file? (sorry if its a basic question im pretty new to this)

**Comment by dudefoxlive** [comment]
Please correct me if i am wrong but i don’t think it is implemented.

**Comment by ramiresviana** [comment]
Environment variables are defined using the `-e` option on Docker, `docker run -e FB_NOAUTH=noauth filebrowser/filebrowser` for example, check https://docs.docker.com/engine/reference/run/#env-environment-variables.

**Comment by dudefoxlive** [comment]
Tried this just now. Made no difference.

**Comment by ramiresviana** [comment]
> Tried this just now. Made no difference.

The provided example command works as expected. I'm unable to help if you don't provide details about how to reproduce the issue.

**Comment by metov** [comment]
It seems that adding `"noauth": "noauth"` to the JSON config also works.

**Comment by ted423** [comment]
```
docker logs filebrowser
2022/12/01 09:08:10 Using config file: /.filebrowser.json
2022/12/01 09:08:10 Listening on [::]:80
```
so this is config file in docker

**Comment by ted423** [comment]
but seems `"noauth": "noauth" `
not work for me

**Comment by ted423** [comment]
I found why 
https://github.com/filebrowser/filebrowser/issues/534#issuecomment-464050176
need delete filebrowser.db and touch a new one.

**Comment by smallw00d2211** [comment]
`"noauth": true` worked perfectly!

**Comment by Kitchu0401** [comment]
> I found why [#534 (comment)](https://github.com/filebrowser/filebrowser/issues/534#issuecomment-464050176) need delete filebrowser.db and touch a new one.

Saved my day. Thanks!
