### ISSUE TITLE
Secure and document HTTP headers used by reverse proxies

### ISSUE THREAD

**Issue by gfagh** [filebrowser/filebrowser#2069]
Hello !

first, I'd like to thank you for maintaining File Browser, which is a great project !
I've sent this issue to filebrowser@googlegroups.com, but didn't get any answer after 4 months.
So here is my bug report :

**Description**
Some HTTP headers, related to reverse proxy use cases, affect the behaviour of File Browser.
  ex: `X-Real-IP` seems to change to IP address of the HTTP client in File Browser logs
  A failure to login will display either the real IP address of the TCP/HTTP client, or the value of  `X-Real-IP` if set.
  ```
   filebrowser[2021]: 2022/03/27 16:47:40 /api/login: 403 X.X.X.X <nil>
  ```
First, I had to read issues talking about reverse proxies to find the name of this header. Even after reading them, the exact meaning is not clear to me because other headers like `X-Forwarded-For` also seems to change this logging behaviour.

Second, HTTP clients should *NOT* be able to inject these headers themselves. Parsing these headers should be disabled in FileBrowser when in "standalone" mode (no reverse proxy). Unfortunately I didn't find anything in File Browser config to stop taking these headers into account. Letting HTTP clients injecting these kind of headers is a clear security issue.

The workaround could be to expose FileBrowser behind a reverse proxy (my current plan actually, for other reason initially), but as these proxy-specific headers are not exhaustively listed and documented, I don't know which ones my proxy should set or filter out...

**Expected behaviour**
- All HTTP headers reserved to reverse proxy usage should be disabled by default, for people exposing FileBrowser directly, with no reverse proxy
- A knob (boolean, or a list trusted proxies IP addresses) in the config database should exist to enable the use of these headers for people exposing FileBrowser through a reverse proxy
- All these headers should be listed and documented.
Optional: provide a minimalist *secure* reverse proxy config for apache/nginx/whatever setting and stripping these headers correctly.

Thanks !

**Comment by ramiresviana** [comment]
File Browser currently looks only for the `X-Real-IP` and `X-Forwarded-For` headers. Clients shouldn't be able to set these headers, this is a bug and should be fixed.

https://github.com/filebrowser/filebrowser/blob/aaed985699b3c63092ecb02c8bc07634123360ab/http/data.go#L67-L70

**Comment by gfagh** [comment]
Easy reproducer:
```
tar xvzf ../linux-amd64-filebrowser.tar.gz
./filebrowser
```

Then:
`wget --header 'X-Real-IP: 8.8.8.8' http://127.0.0.1:8080/api/renew`

And you get:
```
2022/08/03 08:57:37 No config file used
2022/08/03 08:57:37 Listening on 127.0.0.1:8080
2022/08/03 08:57:40 /api/renew: 401 8.8.8.8 <nil>
```

Parsing of these headers should be ignored if `auth.method = proxy` is not set in the config/db file.

**Comment by gfagh** [comment]
Regarding your link:
https://github.com/filebrowser/filebrowser/blob/aaed985699b3c63092ecb02c8bc07634123360ab/http/data.go#L67-L70

The HTTP headers parsing is from `github.com/tomasen/realip` right ? (I'm not a Go developper)
The logic in this project seems completely wrong...
And it's not active anymore (no commit for 5 years).

Why not simply extract `X-Real-IP` and drop the support of `X-Forwarded-For` (a bit more complex to parse than `X-Real-IP`) ?
Then the dependency on `github.com/tomasen/realip` could just be removed.

**Comment by gfagh** [comment]
Hi,
what are the next steps to move forward ?

**Comment by gfagh** [comment]
Very usefull bot...
Up
