### ISSUE TITLE
Fails to boot if there's two filemanager instances using the same database

### ISSUE THREAD

**Issue by francislavoie** [filebrowser/filebrowser#207]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Today, version 0.10.6 of Caddy

### 2. What is your entire Caddyfile?
```text
https://mydomain.com {
	filemanager / F:\\path {
		database hash.db
	}
	tls me@mydomain.com
}

localhost:2015 {
	filemanager / F:\\path {
		database hash.db
	}
	tls off
}
```

### 3. What are you trying to do?
Have filemanager accessible 2 ways, one via localhost, other via external IP

### 4. What did you expect to see?
Functioning site

### 5. What did you see instead (give full error messages and/or log)?
```
F:\caddy>caddy
Activating privacy features... done.
2017/08/16 19:43:04 timeout
```

If I run it with only one instance of `filemanager`, then it works fine. If I have 2 domains like `https://mydomain.com, localhost:2015`, it also fails. Seems like it probably has a mutex lock, and if there's 2 instances they're fighting for the lock?

I'm running it on my home machine, and if I use the external domain I can't access it from my home network (because the domain resolves to the external IP). I could probably run CoreDNS at home and point my router to it to make the domain resolve to the LAN IP, but meeehhhh, don't feel like it 😆 

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Running on Windows 10, just try to start up Caddy with 2 `filemanager`s pointing to the same DB

**Comment by hacdias** [comment]
You are not supposed to use two websites with only one database. The database doesn't allow multiple connections because it locks the file.

I'll try to see if I can do something about this but I can't promise anything.

**Comment by hacdias** [comment]
It will be available on the next release 😄

**Comment by francislavoie** [comment]
Thanks! I tested the new build and it works great!
