### ISSUE TITLE
auth.method=proxy partially broken in v2.22.4

### ISSUE THREAD

**Issue by telsch** [filebrowser/filebrowser#2071]
After upgrade from v2.22.3 to v2.22.4 log in with Proxy Header an then try to switch view or create new file ends with 401 and logging out.

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, server and browser logs.

**Comment by telsch** [comment]
Here is the config:
```
/usr/bin/filebrowser -d /database/filebrowser.db config init
/usr/bin/filebrowser -d /database/filebrowser.db users \
        add telsch $(head -c 16 /dev/random | base64 | head -c 16) \
        --lockPassword \
        --locale="de" \
        --perm.share="false" \
        --perm.execute="false"
        
/usr/bin/filebrowser -d /database/filebrowser.db config set \
        --auth.method="proxy" \
        --auth.header="X-App-User" \
        --branding.name "files" \
        --branding.files "/css" \
        --branding.disableExternal \
        --baseurl "/"
```

Browser logs
```
Request URL: https://files/api/users/1
Request Method: PUT     
401 Unauthorized
```

and server logs:
`/api/users/1: 401  <nil>`

**Comment by ramiresviana** [comment]
The `v2.22.4` introduced a change that prevents some actions to be performed when using only cookies as the authentication parameter. It looks like that your proxy is removing the `X-Auth` header from requests forwarded to the File Browser server, preventing actions that requires it to be performed.

**Comment by telsch** [comment]
Using `traefik` as reverse proxy. The initial auth is working properly. If i test with the `whoami` container also the `X-App-User` is returned. It looks as if only switch view and create new file is affected.

**Comment by telsch** [comment]
I found out when I explicitly use the header it works
`traefik.http.middlewares.auth.forwardauth.authResponseHeaders="X-App-User"`

but not working with regex
`traefik.http.middlewares.auth.forwardauth.authResponseHeadersRegex="^X-"`
