### ISSUE TITLE
Possibility to hide URL Path

### ISSUE THREAD

**Issue by err0r2k** [filebrowser/filebrowser#2073]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to hide the URL Path when you are browsing through your documents/data. (e.g. Nextcloud can do this for example)

**Comment by o1egl** [comment]
What is the use case for that?

**Comment by err0r2k** [comment]
Nevermind. First I used FileBrowser I don't wanted to see the full URL Path. But now it's useful. Closed.

**Comment by err0r2k** [comment]
Close
