### ISSUE TITLE
[feature] Connect filebrowsers to each other on a lan, and one of it act as the central entrance for the others.

### ISSUE THREAD

**Issue by sulisu** [filebrowser/filebrowser#2074]
**Is your feature request related to a problem? Please describe.**

I installed filebrowser on three devices in home network. I have to open three tabs to manage them. With more filebrowser instance will be installed, it is not very convenience.

**Describe the solution you'd like**

One of the filebrowser instance act as the central hub and other instances is configured to be pair with it, like syncthing.

The central hub will be the unified entrance for all other filebrowser instance

**Describe alternatives you've considered**

Without this feature, I have to config network share on the central hub and then share it in filebrowser.

**Additional context**

**Comment by OoZe1911** [comment]
+1
