### ISSUE TITLE
Create Recycle Bin and understanding Command Runner and File Browser.

### ISSUE THREAD

**Issue by err0r2k** [filebrowser/filebrowser#2075]
**Description**
I'm tyring to understand the Command Runner and File Browser. There is no recycle bin in File Browser, so I want to create a "Before delete" command. 

**Expected behaviour**
After deleting a file/folder, it should moved to a recycle folder.

**What is happening instead?**
The file is permanently deleted.

**Additional context**
Tested with a normal file and not with the $FILE variable.(This would be the next step) I'm using File Browser as Plugin from OpenMediaVault. It's not the Docker Version.

1. Settings -> Global Settings -> Execute on shell -> bash -c
2. Before Delete -> mv /media/data/testfile /media/data/recycle
3. I get a 500 Internal Server error. The file is not deleted or moved. Same error message with a testfolder.

I don't understand why it's not working, because I defined the bash shell.
Where can I find the log to check the error message?
Why can I Toggle the shell in the main page but no bash command is working? After every command I get the message "Command not allowed". 
I have all Admin Rights.

File Browser is a really great Web File Browser but I want to understand how it works. 

Thanks in advance!

**Comment by ramiresviana** [comment]
The allowed commands must be added to the user settings in the user management to allow them to be used in the shell.

File Browser will output any errors to the terminal by default. The `log` option allow you to change that behavior, check https://filebrowser.org/cli/filebrowser

Since you're using File Browser through a third-party service, we can't ensure that these features are available or work correctly.

**Comment by err0r2k** [comment]
> Since you're using File Browser through a third-party service, we can't ensure that these features are available or work correctly.

I uninstalled the OMV version and installed the normal version. They are really not the same. The commands in the normal version are working without problems. Thanks!

**Comment by err0r2k** [comment]
OMV version is not the same as the normal version.

**Comment by lukain88** [comment]
> > Since you're using File Browser through a third-party service, we can't ensure that these features are available or work correctly.
> 
> I uninstalled the OMV version and installed the normal version. They are really not the same. The commands in the normal version are working without problems. Thanks!

Hi, can you explain to me how you installed it? I have omv installed on a PC and I don't understand how to do it. I don't understand anything about docker etc
Thanks!
