### ISSUE TITLE
Favourites and pinned folders

### ISSUE THREAD

**Issue by damomato** [filebrowser/filebrowser#2076]
Loving filebrowser, thanks so much for your work. Just had a couple feature requests to improve navigating it.

**Is your feature request related to a problem? Please describe.**
Sometimes want to navigate to a folder directory quickly, or within a directory be able to select a commonly used folder

**Describe the solution you'd like**
I would like the ability to save folder directories to a favourites bar, maybe running down the left side of the screen. 
I would also like the ability to pin folders within their respective directories to be at the top of the list, so it sits above all other folders.

**Describe alternatives you've considered**
Haven't considered alternatives.

**Comment by OoZe1911** [comment]
You can bookmark with your browser the URL of Filebrowser when you are in your favorite folder. Then calling the bookmark page from your webbrowser will open Filebowser directly on your folder.
