### ISSUE TITLE
413 Request Entity Too Large (Nginx 1.15.12 docker compose)

### ISSUE THREAD

**Issue by wisegman2468** [filebrowser/filebrowser#2085]
I'm very new to this and I'm trying to upload files onto my file browser. it was working fine for a while and then all of a sudden, all my big files kept getting the 413 error. not seeing a limit on any of my config files but I could be missing it. I also tried putting client_max_body_size 0; in my docker_compose and still the same issue.

nginx proxy.conf:

# HTTP
server {
    listen 80;
    server_name hostname;
    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name hostname;
    client_max_body_size 0;

    ssl_certificate /etc/letsencrypt/live/hostname/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hostname/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /files/ {
        proxy_pass http://10.**.*.***:24682/;
        #proxy_set_header Host $host;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        #proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /guacamole/ {
        proxy_pass http://10.**.*.***:8443/;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Connection "";
    }

    location /portainer/ {
        proxy_pass https://10.**.*.***:9443/;
        #proxy_set_header X-Forwarded-Proto https;
        #proxy_set_header Connection "";
    }

    location / {
            root /var/www/data;
    }
 index index.html;

}

nginx docker-compose.yml:

version: "3"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/website:/var/www/data
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

filebrowser docker-compose.yml

version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 24682:8080
    volumes:
      - /home:/data/Linux
      - /mnt/10TB/:/data/10TB/
      - ./CONFIG_DIR:/config
      - /mnt/6TB/:/data/6TB/
    environment:
      - FB_BASEURL=/files
    restart: always

**Comment by hapylestat** [comment]
did you tried to check nginx logs first?

**Comment by wisegman2468** [comment]
log of nginx 

/14 23:55:39 [error] 9#9: *195 client intended to send too large body: 36757452 bytes, client: 10.**.*.*2, server: hostname, request: "POST /files/api/resources/10TB override=false HTTP/1.1", host: "hostname", referrer: "https://10.**.*.**3/files/files/10TB/"

**Comment by o1egl** [comment]
You need to fix your nginx config. Filebrowser doesn't have any body limit restrictions

**Comment by hapylestat** [comment]
@o1egl but in his configuration `client_max_body_size` is set to 0, which effectively supposed to turn upload size limit off.

@wisegman2468 
There's is worth to play with:
- the property, and instead of setting it to 0, try  to set it to some big value
- trace from where the 413 comes - nginx or the uplink(i.e. filebrowser)

**Comment by wisegman2468** [comment]
I changed it to client_max_body_size 10000M and it worked! tried that a while ago and it did nothing but I'm not complaining now. Thank you @hapylestat

**Comment by barshy** [comment]
this drove me crazy, the file you need to edit is /etc/nginx/sites-enabled/default its set to 40M by default

**Comment by asher-lab** [comment]
I've experienced this and to solve you need to:

`nano /etc/nginx/nginx.conf` 

and add the following lines in the http block:

```
client_max_body_size 100M;
```


then restart nginx:
`systemctl restart nginx`
