### ISSUE TITLE
Hope to achieve file permissions on the web page

### ISSUE THREAD

**Issue by yucns** [filebrowser/filebrowser#2086]
![image](https://user-images.githubusercontent.com/48143656/184672056-6fe55117-fe93-4b9f-bcb1-7ab00680ce92.png)
![image](https://user-images.githubusercontent.com/48143656/184672130-eb46f714-7342-4223-9cb1-370e25f96099.png)
![image](https://user-images.githubusercontent.com/48143656/184672171-9ed456a3-be42-490c-bcbc-752f4dbdd3c3.png)

**Comment by o1egl** [comment]
You can use Rules in the user settings to modify the file access rules

**Comment by organizedkaos** [comment]
I would like to re-ask for the logged in username to be shown.

For the user directories you can isolate their root folder using the scope parameter.  The scope instructs the users root directory location so when they log in they don't see above that root directory.

EDIT:  I am still learning this code stuff but I managed to do this for my use case.
![ss_main](https://user-images.githubusercontent.com/982736/191402699-71c4b37d-6e74-487d-a3a7-489aaaff540f.jpg)

![ss_settings](https://user-images.githubusercontent.com/982736/191402707-9953de75-0e55-4258-89cf-7860cd801824.jpg)

**Comment by WarmChocolateCake** [comment]
Just found this issue - the original one about permissions (although the comment about logged in username is also of interest)

The service is running as root (on Linux... I'm guessing it's something similar for Windows), so the application user can see all files / folders as if they were logged on as the elevated user account? (Which raises a security concern in my brain)

I'm presuming that there's some form of filesystem test that the service can use to mask files / folders that the user does not have access to?

If so, this would remove the need for the additional "Rules" configuration?
