### ISSUE TITLE
Operation not supported error when using iOS 

### ISSUE THREAD

**Issue by pstark556** [filebrowser/filebrowser#2087]
When I use “Connect to Server” in iOS I get this error. How do I connect iOS to Filebrowser? 
![57C67BF3-D045-4D4D-BC8D-EC55AB739BC9](https://user-images.githubusercontent.com/96851162/184687391-025728ab-73a8-43c7-812b-77d85e4466fa.png)

**Comment by o1egl** [comment]
Filebrowser doesn't have any official mobile app. You can ask help from the app owners
