### ISSUE TITLE
Storage quota limit per user

### ISSUE THREAD

**Issue by alvin0319** [filebrowser/filebrowser#2090]
**Is your feature request related to a problem? Please describe.**

Please add a storage quota limit per user, it is useful when renting storage to my friends.

**Describe the solution you'd like**

Add storage quota. (both per user, or per folder would be useful)

**Describe alternatives you've considered**

N/A

**Additional context**

I've searched opened/closed issues like #711 but they are closed.

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/discussions/1214

**Comment by tarokeitaro** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Please add a storage quota limit per user, it is useful when renting storage to my friends.
> 
> **Describe the solution you'd like**
> 
> Add storage quota. (both per user, or per folder would be useful)
> 
> **Describe alternatives you've considered**
> 
> N/A
> 
> **Additional context**
> 
> I've searched opened/closed issues like #711 but they are closed.

I use an alternative solution that is quite complicated. Create a virtual disk and then mount that disk for each user with a custom storage quota.

create krislam.img and tio.img with `fallocate -l 2G /path/to/virtual/disk.img` and format the virtual disk with `mkfs.xfs /path/to/virtual/disk.img`
![Screenshot from 2023-04-05 18-31-46](https://user-images.githubusercontent.com/42670754/230069650-a55041ee-aa65-427d-8fab-e66c4b5208dd.png)

add virtual disk to fstab
![Screenshot from 2023-04-05 18-35-24](https://user-images.githubusercontent.com/42670754/230070073-ee3aba78-0e06-4356-95ae-a65e02be7601.png)

create a parent directory for disk mounting
![Screenshot from 2023-04-05 18-35-38](https://user-images.githubusercontent.com/42670754/230070276-aef87104-143a-43c0-9023-8888ce14205a.png)

check the virtual disk
![Screenshot from 2023-04-05 18-35-50](https://user-images.githubusercontent.com/42670754/230070352-ab0c2aac-d1c8-4c31-9363-740b59fb94c6.png)

quota per user applied
user:krislam
![image](https://user-images.githubusercontent.com/42670754/230070703-3f3de855-4fd2-4de4-95f3-7afe81258371.png)

user:tio
![image](https://user-images.githubusercontent.com/42670754/230070887-edfb14f7-dd3a-478c-8e2d-22e61c6fbcf7.png)
