### ISSUE TITLE
unable to create folder

### ISSUE THREAD

**Issue by canneednew** [filebrowser/filebrowser#2098]
**Description**
unable to create a new folder while setting

**What is happening instead?**
it shows "This location can't be reached".

**Comment by canneednew** [comment]
![1661277784299](https://user-images.githubusercontent.com/111905770/186231831-0e0f8ca6-1954-490d-b81f-67e4b91642d8.gif)

**Comment by canneednew** [comment]
![1661278360281](https://user-images.githubusercontent.com/111905770/186233493-7fda0a86-635c-4573-9e57-8137e58e8551.gif)

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, server and browser logs.
