### ISSUE TITLE
Login with default account return 403

### ISSUE THREAD

**Issue by sgpublic** [filebrowser/filebrowser#2099]
I compile filebrowser on OpenWrt, I think the compilation is correct.

<details>
<summary>Click to view Makefile</summary>

```makefile
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2022 sgpublic

include $(TOPDIR)/rules.mk

PKG_NAME:=go-filebrowser
PKG_VERSION:=2.22.4
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/filebrowser/filebrowser/tar.gz/v$(PKG_VERSION)?
PKG_SOURCE_DATE:=2022-07-19
PKG_HASH:=511f0e200c4c2c3851f92d1090804a67ed425a8290493a70af49aea93c229d91

PKG_BUILD_DIR:=$(BUILD_DIR)/filebrowser-$(PKG_VERSION)

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILE:=LICENSE
PKG_MAINTAINER:=Mrs4s

PKG_BUILD_DEPENDS:=golang/host node/host
PKG_BUILD_PARALLEL:=1
PKG_USE_MIPS16:=0

GO_PKG:=github.com/filebrowser/filebrowser
GO_PKG_LDFLAGS_X:= \
	$(GO_PKG).build=OpenWrt \
	$(GO_PKG).version=$(PKG_VERSION)

include $(INCLUDE_DIR)/package.mk
include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk

define Package/go-filebrowser
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Cloud Manager
  TITLE:=go-filebrowser
  URL:=https://github.com/filebrowser/filebrowser
endef

define Package/go-filebrowser/description
  filebrowser provides a file managing interface within a specified directory
	and it can be used to upload, delete, preview, rename and edit your files.
	It allows the creation of multiple users and each user can have its own directory.
	It can be used as a standalone app.
endef

define Build/Compile
	( \
		pushd "$(PKG_BUILD_DIR)/frontend" ; \
		npm ci; \
		npm run lint ; \
		npm run build ; \
		popd ; \
		$(call GoPackage/Build/Compile) ; \
	)
endef

define Package/go-filebrowser/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_DIR) $(1)/etc/nginx
	$(CP) ./root/etc/nginx/* $(1)/etc/nginx
	$(INSTALL_DIR) $(1)/etc/uci-defaults
	$(INSTALL_BIN) ./files/zzz-go-filebrowser $(1)/etc/uci-defaults/99-go-filebrowser
	$(call GoPackage/Package/Install/Bin,$(PKG_INSTALL_DIR))
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/filebrowser $(1)/usr/bin/filebrowser
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./root/etc/init.d/* $(1)/etc/init.d
endef

$(eval $(call GoBinPackage,go-filebrowser))
$(eval $(call BuildPackage,go-filebrowser))
```
</details>

Next I start filebrowser with `/usr/bin/filebrowser -d /etc/filebrowser.db` command, then use nginx reverse proxy and finally access filebrowser from outside.

nginx conf:
```
upstream filebrowser {
  server 127.0.0.1:8080;
  keepalive 64;
}

location ~ / {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_pass http://filebrowser;
}
```

When I login with the default account (username `admin`/password `admin`), the api returns `403 Forbidden`, and the interface prompts that the password is incorrect.

How to fix?

---

Update: I‘ve tried changing the username and password of the default user, and downloading the executable binary directly from the release page, but the problem remains the same.

**Comment by ramiresviana** [comment]
Filebrowser will not create the admin user when a database file is provided. You must created it manually or initialize the database first.

**Comment by sgpublic** [comment]
But I did use `filebrowser config init -p 8081 -d /etc/filebrowser.db`, and `filebrowser users -d /etc/filebrowser.db` also lists default users admin, I even tried `filebrowser users update admin --password xxx` to change the password, but I still can't login.

**Comment by ramiresviana** [comment]
The value provided to the `users update -p` command must be generated using the `hash` command, check https://filebrowser.org/cli/filebrowser-hash.

**Comment by sgpublic** [comment]
I see, Thank you for your help! I'll try it later.

**Comment by c608345** [comment]
With v2.23.0 should set password with plain text.

**Comment by bonnebulle** [comment]
Hum I cant figure how to make it working -login with password- 
Am using Docker...
- I try the Hashing method ( ok ) 
- then I added the password has -e ```FB_PASSWORD=.....```

This never worked (am noob)

So, for notice, if can help some one :
I do the "noauth" methode  ```FB_NOAUTH="true"```
go on web page login...
then change password 
= quicksetup ?
