### ISSUE TITLE
Caddyfile validation timeout

### ISSUE THREAD

**Issue by sanderhahn** [filebrowser/filebrowser#210]
### 1. Downloaded File Manager from caddyserver.com

https://caddyserver.com/download/linux/arm64?plugins=http.ipfilter,http.filemanager

### 2. Caddyfile

```text
example.com {
    root /var/www/example.com
    filemanager /filemanager /var/www/example.com {
        database /var/www/example.db
    }
}
```

### 3. What are you trying to do?
Validate the config file using:
```
sudo -H -u www-data caddy -conf /etc/caddy/Caddyfile -validate
```

### 4. What did you expect to see?
`Caddyfile is valid`

### 5. What did you see instead (give full error messages and/or log)?
`2017/08/18 02:09:21 timeout`

When the filemanager entry is removed from the config the validation succeeds.

**Comment by hacdias** [comment]
I'll check this out.

**Comment by sanderhahn** [comment]
The validation logic might try to open the BoltDB database and that is where the timeout happens. `Bolt uses an exclusive write lock on the database file so it cannot be shared by multiple processes`. Maybe its possible to pass along a `&bolt.Options{ReadOnly: true}` if the validate flag is active.

**Comment by hacdias** [comment]
Thanks! I'll try to solve it ASAP. Right now I'm making an upgrade on this which will take one day or two but then I'll solve this. Sorry for the delay!

**Comment by sanderhahn** [comment]
No hurries, was just looking into it :) Thank you!

**Comment by hacdias** [comment]
This is my output:

```
PS D:\site> caddy -validate
[WARNING] A database is going to be created for your File Manager instace at C:\Users\henri\.caddy\filemanager\186f83e3c4a947cde85e22d48d5e3cee.db. It is highly recommended that you set the 'database' option to '186f83e3c4a947cde85e22d48d5e3cee.db'

Caddyfile is valid
```

**Comment by hacdias** [comment]
I just tested it now without changes (on master and didn't receive any error). I'll try the downloaded version.

**Comment by hacdias** [comment]
I don't receive any error on my computer using the latest version from caddyserver.com. I haven't made any changes there since this issue was opened.

Do you have any instance of Caddy running with that database? If so, the file is locked and then it can't be validated. I'll try to change to readonly though when the validate flag is active.

**Comment by sanderhahn** [comment]
The problem is only there when the server is already running. The validate logic is also invoked when you send caddy a `SIGUSR1` to reload the configuration. At the moment a full shutdown is required to update the configuration. Maybe it is not such a big problem, but it is unexpected :)

**Comment by hacdias** [comment]
Hmm... I'll change it then when the flag validate is active.

**Comment by sanderhahn** [comment]
The validate flag is not present on a `SIGUSR1` signal. So checking for a flag might fix the validate use case, but the reload config on a running caddy might still fail.

**Comment by hacdias** [comment]
But when the validation logic is invoked, is the server still running? I mean, is the database connection still active?

**Comment by sanderhahn** [comment]
The restart logic that Caddy uses is here: https://github.com/mholt/caddy/blob/master/caddy.go#L144 To perform a graceful restart without dropping incoming requests it will start a new instance and then shutdown the existing instance. Not sure how to solve this using BoltDB. Maybe Badger is a solution: https://godoc.org/github.com/dgraph-io/badger It doesn't seem to lock the database file, however it also doesn't provide transactions so its functionality is at a lower level.

**Comment by hijak** [comment]
hi

i am experiencing this when using caddy in a swarm scenario using global replicas. The replicas wont start due to the timeout error. I remove filemanager and they work fine

**Comment by hacdias** [comment]
Closing this as frozen in time. If someone else is interested on it, please ping.
