### ISSUE TITLE
[ISSUE] When configured w/ json config file and system service, stuck on 3 loading dots.

### ISSUE THREAD

**Issue by Bluemoon15** [filebrowser/filebrowser#2102]
When connecting from both my domain and IP, filebrowser hangs on the 3 loading dots. This is after I wrote a short configuration file for it and attatched filebrowser to a system service so it automatically runs. I've tried turning it off and on again but I don't know what's happened.

Might be something with filebrowser itself but i doubt it,

Please advise.

Edit: for future reference, removing the baseurl from the json file fixes the issue.

**Comment by ramiresviana** [comment]
The `baseurl` option must be provided with a leading slash to work correctly.
