### ISSUE TITLE
I cannot upload files with 500 error

### ISSUE THREAD

**Issue by majh0** [filebrowser/filebrowser#2104]
**Description**

I wanted to upload the video which is 10GB but failed it

**Expected behaviour**

I really wanted to upload some video and I thought it would be successful

**What is happening instead?**

while I was uploading the file, it failed giving me 500 error
and I found out the error log in the file named error.log
2022/08/26 23:04:37 [crit] 494#494: *177 pwrite() "/var/lib/nginx/tmp/client_body/0000000002" failed (28: No space left on device), client: 118.**.**.**, server: filebrowser.*, request: "POST /api/resources/ext3/Counter-strike%20%20Global%20Offensive%202020.08.06%20-%2021.50.25.01.mp4?override=false HTTP/2.0", host: "filebrowser.majh.duckdns.org", referrer: "https://filebrowser.****.duckdns.org/files/ext3/"
**Additional context**

but I attached new external HDD which is 2TB and it shouldn't be lack of space to upload that file

**How to reproduce?**

if you try to upload 10GB video file which is mp4 format, maybe this thing will happen

anyways thank you for your answer in advance

**Files**

**Comment by ramiresviana** [comment]
The provided log was generated by nginx, you're having a issue with your proxy configuration.

**Comment by abhi-maybe** [comment]
You need to change the client_max_body_size in nginx
