### ISSUE TITLE
iOS folder opening bug

### ISSUE THREAD

**Issue by Rearden21M** [filebrowser/filebrowser#2108]
**Is your feature request related to a problem? Please describe.**

This problem occurs on my iOS. When I tap once on a folder, it selects it but does not open it. If I double-tap, then without fail, it will always open the folder I tapped + whatever next folder is inside it if it is in the same area of the screen. In other words, it always instantly opens two folders, making me have to go to the previous folder which I actually wanted to go to.

**Describe the solution you'd like**

I would like this bug to be fixed.

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, application version, server and browser logs.
