### ISSUE TITLE
Proxy header auth doesn't work, jump to the log in page and got 403 error.

### ISSUE THREAD

**Issue by shikiroot** [filebrowser/filebrowser#2111]
**Description**
I am trying to use proxy header auth with nginx, vouch-proxy and openid, but it's not working.

**Expected behaviour**
When I log in to the openid, jump to the file list page of filebrowser.

**What is happening instead?**
When I log in to the openid, jump to the log in page of filebrowser. And I got a 403 error.

**Additional context**
Filebrowser config:
```
    filebrowser config set --auth.method=proxy --auth.header=X-Vouch-User
```
Nginx config:
```
    location / {
      proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
      proxy_pass http://<filebrowser_address>;
    }
```
Nginx log:
```
2022/08/28 17:10:16 [debug] 10204#10204: *1 http proxy header:
"GET /login HTTP/1.0
X-Vouch-User: <user@exp.com>
Host: <filebrowser_address>
Connection: close
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
DNT: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en
Cookie: VouchCookie=<cookie>

"
```
Filebrowser log:
```
    /api/login: 403 <client_address> <nil>
```

**Comment by o1egl** [comment]
The user must be created explicitly in filebrowser. It doesn't create users dynamically

**Comment by helmut72** [comment]
Why support header auth if Filebrowser don't  trust header auth?

**Comment by o1egl** [comment]
It uses a header for authentication, but the user with provided name must exist in the filebrowser

**Comment by shikiroot** [comment]
Yeah I got it, just saw this. Thanks for helping.
https://github.com/filebrowser/filebrowser/blob/c1e6d5869acf32cda22fa7dd532ebb6130061b7b/auth/proxy.go#L23

> It uses a header for authentication, but the user with provided name must exist in the filebrowser

**Comment by helmut72** [comment]
> It uses a header for authentication, but the user with provided name must exist in the filebrowser

This isn't helpful for centralized user management and authorization. I only know Filebrowser and unfortunaltelly Navidrome copied this behavior.

**Comment by ramiresviana** [comment]
A new feature allowing you to integrate the authentication will be available on the next File Browser version, check https://github.com/filebrowser/filebrowser/pull/1554.

**Comment by helmut72** [comment]
Thank you. It looks like this still doesn't support Single Sign On with header auth, but better than manage users in Filebrowser.
