### ISSUE TITLE
Prevent edits when the user has been logged out

### ISSUE THREAD

**Issue by dimo414** [filebrowser/filebrowser#2113]
**Is your feature request related to a problem? Please describe.**
Several times now I've made a number of edits to a file, only to hit save and be redirected to the login page because the window had been open too long. This makes it very easy to lose work and as best I can tell there's no indication on the page that you've been logged out until you try to save.

**Describe the solution you'd like**
It would be helpful if the page prevented edits and made it clear the user has been logged out. For example by proactively redirecting to the login page, changing the text box to read-only, or displaying a login overlay over the file so the user can log in again without losing their work.

**Describe alternatives you've considered**
More a separate FR than an alternative, but initially I was looking for a setting to configure the logout duration. It seems like it's quite short, a few hours or less, but I didn't find a setting to customize this duration.

**Additional context**
N/A

**Comment by dimo414** [comment]
A feature request that hasn't been responded to isn't stale....

**Comment by dimo414** [comment]
@o1egl sorry for the ping but I don't know how to prevent this FR from being auto-closed. I understand if it's not a priority but IMO FRs shouldn't be auto-closed just because of inactivity.

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
@o1egl looking at the list of [closed issues](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue+is%3Aclosed) it seems like _many_ are being closed as stale, including both feature requests and clear bugs like #2334. Is this stale closure behavior really working as intended?

**Comment by dimo414** [comment]
.

**Comment by bkobeszko** [comment]
+1

**Comment by dimo414** [comment]
😞

**Comment by dimo414** [comment]
😞

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
.

**Comment by bufubaoni** [comment]
> .
https://github.com/filebrowser/filebrowser/pull/2792 
look this fix may helps you?

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
:roll_eyes:

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
.

**Comment by dimo414** [comment]
I give up, clearly this repo is abandoned.
