### ISSUE TITLE
Remote Upload Feature

### ISSUE THREAD

**Issue by tarokeitaro** [filebrowser/filebrowser#2116]
**Is your feature request related to a problem? Please describe.**
I have a home server for family entertainment, every time I want to download media I have to run ssh to connect to the server, or with the ariaNG interface in another browser tab. I think this is a bit of a hassle, so I suggest adding a remote upload feature.

**Describe the solution you'd like**
This feature requires an app called [aria2](https://aria2.github.io/), in my opinion the lightest downloader because it's command line based. This is optional if the user wants to enable this feature must include the path where the aria2 is saved or if the aria2 service is already running just enter the service port into the File Browser. I'd really like to contribute to adding this feature, but I'm not a programmer who can understand the creation of this File Browser.

**Describe alternatives you've considered**
Instead I still use AriaNG as the aria2 application interface to upload those media files to my server. Here's a link to an example of the AriaNG project I'm referring to.
https://github.com/mayswind/AriaNg

**Additional context**
![image](https://user-images.githubusercontent.com/42670754/188425001-ffd6dc92-cc69-4010-b243-fad3b2a26a1a.png)

**Comment by ramiresviana** [comment]
What is the benefit of using a third-party application to download and upload files instead of doing that on the Filebrowser web interface?

**Comment by tarokeitaro** [comment]
Third party apps can only download files from urls or torrents. I think it would be very easy if FileBrowser provided that feature.
