### ISSUE TITLE
Folders/Files Favorites

### ISSUE THREAD

**Issue by suiyueou** [filebrowser/filebrowser#2117]
**Is your feature request related to a problem? Please describe.**

When I frequently switch between multiple hot folders, I always need to repeat the path switching operation, which greatly affects the smoothness of the operation

**Describe the solution you'd like**

I would like to have a folder/file favorite feature to easily and quickly switch between multiple folders/files

**Comment by erohtar** [comment]
I came here looking for a Favorite Folders feature too

**Comment by lhuanyun** [comment]
metoo

**Comment by chr0max** [comment]
We need this or any feature to pin folders in the left list.

**Comment by kimberlake** [comment]
any considerations for this feature?
