### ISSUE TITLE
The powershell installation script fails to detect OSArchitecture on non-English systems

### ISSUE THREAD

**Issue by zqm980904** [filebrowser/filebrowser#2124]
**Description**

On a non-English windows system, `Get-WmiObject Win32_OperatingSystem).OSArchitecture` may return a non-English string, which doesn't equal "64-bit" despite a 64-bit system architecture.

**Expected behaviour**

`$arch = "amd64"` on 64-bit systems.

**What is happening instead?**

(On Chinese systems)
```
PS D:\> (Get-WmiObject Win32_OperatingSystem).OSArchitecture
64 位
```

**Additional context**

Maybe try `[Environment]::Is64BitOperatingSystem`
The script concerned is https://raw.githubusercontent.com/filebrowser/get/master/get.ps1
```
$arch = "386"

If ((Get-WmiObject Win32_OperatingSystem).OSArchitecture -eq "64-bit") {
	$arch = "amd64"
}
```

**Comment by Nemoron** [comment]
This is still an issue!
