### ISSUE TITLE
Disable New File / Folder Buttons when irrelevant.

### ISSUE THREAD

**Issue by WarmChocolateCake** [filebrowser/filebrowser#2125]
**Description**
Login, navigate to any location.
Click on Settings, click New Folder, Enter a name, Click Create.

Observe "This location can't be reached." page with the path shown as (Root)/<NewFolderName> --- even if wasn't in the root location

Click on My Files, navigate to same location, without clicking on Settings, attempt to create the same folder and see that it works correctly.

**Expected behaviour**
Really, creating Files & Folders isn't a "Settings" activity, so the buttons should be disabled / hidden IMO.

But, if they're intended to still be active, then I would expect a File / Folder to be created in the location I was last in (ie not / )

**What is happening instead?**
Nothing but an error.

**Additional context**
Nothing that comes to mind.

**How to reproduce?**
As per the description above

**Files**
None

Personally, I think this is just a usability issue. When in Settings, there is no indication of the user's location in the filesystem hierarchy, so having active "New Folder" or "New File" buttons whilst in the settings view is the problem.

Thanks for a great application though! :)

**Comment by organizedkaos** [comment]
I have seen this by accident and I agree to having them not visible when in settings menu.

EDIT: I'm not the best coder (still learning) but I managed to fix this issue.  When I click in settings now the new file and new folder options are hidden and the my files main button still remains.  

![ss_main](https://user-images.githubusercontent.com/982736/191402389-e153e584-226e-4937-820e-8587b6175a6d.jpg)

![ss_settings](https://user-images.githubusercontent.com/982736/191402401-f028b335-bc3c-44f7-9951-8b0f304839cd.jpg)

**Comment by WarmChocolateCake** [comment]
Just to confirm that this is still an issue in 2.22.4 (not that anything said it was going to be fixed in that version... 🙂 )

**Comment by WarmChocolateCake** [comment]
Maybe this could be marked as Feature Request if it's not being seen as a bug?
Looks like @organizedkaos was able to make a change on their system, so it is "solvable" 🙂
