### ISSUE TITLE
ERR_CONNECTION_REFUSED after quick install

### ISSUE THREAD

**Issue by ianmcfall** [filebrowser/filebrowser#2126]
**Description**
Trying to run basic install on fresh server with ubuntu 20

**Expected behaviour**
Access running filebrowser ui from entering in ip address of server in web browser

**What is happening instead?**
ERR_CONNECTION_REFUSED after typing in address in web browser

**How to reproduce?**
curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
filebrowser -r /home/user/files/

I'm sure this is a newb problem, but any help would be much appreciated.

**Comment by liuchuhan1** [comment]
maybe you can try "service firewalld stop"，and then try to access the website,if it does work, you could pass by the port your filebrowser used both udp and tcp

**Comment by ianmcfall** [comment]
> maybe you can try "service firewalld stop"，and then try to access the website,if it does work, you could pass by the port your filebrowser used both udp and tcp

Thanks, but firewalld isn't running. Neither is ufw for that matter.

**Comment by ianmcfall** [comment]
Closing. 

Abandoned manual install and switched to docker install and it works fine. Thanks.
