### ISSUE TITLE
Error 500 when sharing with last release 1.2.4

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#213]
### 3. What are you trying to do?
Share file or folder with the share button when item is selected

### 4. What did you expect to see?
The share prompt

### 5. What did you see instead (give full error messages and/or log)?
_What I see :_ Something went wrong error 500
_Console log_ : 2017/08/20 20:28:16 the resource does not exist

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Just select item and click on the share button

**Comment by hacdias** [comment]
Hey! Sorry for this. I'll fix it tomorrow hopefully.

**Comment by hacdias** [comment]
It will be out with 1.2.5
