### ISSUE TITLE
Linux-RM64 cannot recognize FLAC format music

### ISSUE THREAD

**Issue by zp506399** [filebrowser/filebrowser#2131]
**Description**
In Linux-RM64-Filebrowse (2.22.4), it is found that music that cannot be recognized by FLAC format is found, but the Windows environment in the same version number can be recognized

**Expected behaviour**
Hope to repair this problem and can identify music in FLAC format

**What is happening instead?**

[![Snipaste-2022-09-18-02-26-22.png](https://i.postimg.cc/9f4RN7gH/Snipaste-2022-09-18-02-26-22.png)](https://postimg.cc/v1sZ4cd0)
[![Snipaste-2022-09-18-02-27-07.png](https://i.postimg.cc/rFPqZYBz/Snipaste-2022-09-18-02-27-07.png)](https://postimg.cc/yk0qknYz)
[![Snipaste-2022-09-18-02-33-51.png](https://i.postimg.cc/dVPx02d4/Snipaste-2022-09-18-02-33-51.png)](https://postimg.cc/LnDTCZx1)
**Additional context**

**How to reproduce?**

Run Linux-RM64-Filebrowser.gz (2.22.4) in the Linux-RM64 device, upload a FLAC format music to see if it is recognized as audio on the webpage as audio

**Files**

**Comment by ramiresviana** [comment]
This might be related to the MIME type detection, check https://github.com/filebrowser/filebrowser/issues/1439#issuecomment-865988937. Also there's no official image for Linux-RM64.
