### ISSUE TITLE
Some thumbnails are in wrong direction.

### ISSUE THREAD

**Issue by niubility000** [filebrowser/filebrowser#2137]
**Description**
Some thumbnails read from exifs are in wrong direction. (The HD or raw pictures are in right direction.)
![2022-09-21 095527](https://user-images.githubusercontent.com/76441520/191400223-cdbb7c54-14c2-413f-bcdb-67ea0ba0cbd6.png)

Here's some sample pics:

[wrong direction.zip](https://github.com/filebrowser/filebrowser/files/9612430/wrong.direction.zip)

**Comment by niubility000** [comment]
We can fix it with this one #2078  together.

**Comment by alexisLefebvre** [comment]
This is a common issue with EXIF Orientation, dear bot please don't close this issue.
