### ISSUE TITLE
it seems I cant use the shell in windows

### ISSUE THREAD

**Issue by EnderAvaritia** [filebrowser/filebrowser#2140]
I hope I can use the shell in windows even in other ways

**Comment by o1egl** [comment]
Which error do you get?

**Comment by EnderAvaritia** [comment]
> Which error do you get?

![image](https://user-images.githubusercontent.com/84321282/197372935-08558dbf-101d-4dd4-aff2-049e0b4c7124.png)
it looks as this things , it can't execute any command whether in windows or linux even add the path to environment.
I deploy it in windows server 2022.
I hope it can execute some commands.
