### ISSUE TITLE
Option to not show hidden files (pre-set / User cant change in UI)

### ISSUE THREAD

**Issue by ADz-83** [filebrowser/filebrowser#2142]
**Is your feature request related to a problem? Please describe.**
Can't hide hidden files/folders (example /.config)

[edit]  More specifically pre-configure to not show hidden and hard set so can't be changed by end user

**Describe the solution you'd like**
A file to edit to pre-configure this

**Comment by o1egl** [comment]
<img width="1002" alt="Screenshot 2022-09-22 at 18 45 56" src="https://user-images.githubusercontent.com/966539/191805293-a09a99f9-7db7-4603-b10c-9b55dab84787.png">
This option is already available on the settings page

**Comment by ADz-83** [comment]
My apologies I should have been clearer.  I was referring to a way to hard set it within a file so it can be pre-configured and not changed by end user.

**Comment by ADz-83** [comment]
> <img alt="Screenshot 2022-09-22 at 18 45 56" width="1002" src="https://user-images.githubusercontent.com/966539/191805293-a09a99f9-7db7-4603-b10c-9b55dab84787.png">
> This option is already available on the settings page

My apologies I should have been clearer. I was referring to a way to hard set it within a file so it can be pre-configured and not changed by end user.
