### ISSUE TITLE
filebrowser plugin 6.0.3.1 on omv6

### ISSUE THREAD

**Issue by jackleinad** [filebrowser/filebrowser#2144]
**Description**
After the omv update the filebrowser plugin 6.0.2.1 -->6.0.3.1 . The plugin is well started but now it is inaccessible ???

**Expected behaviour**
Let it work as before!

**What is happening instead?**
I don't get any error messages. except that the web page is inaccessible.

**Additional context**
System: OMV6.0.41-1 avec portainer duckdns et plug-in FileBrowser 6.0.3.1
all works except web access to filebrowser plugin from update. tried changing port, uninstall/reinstall plugin, apt clean + restart.

**How to reproduce?**
I guess with the same configuration

**Files**
tell me what you want and I will transfer it to you.

**Comment by o1egl** [comment]
We are not supporting omv plugin. You can ask the plugin owner for help.

**Comment by jackleinad** [comment]
Ok thanks for your answer o1egl
