### ISSUE TITLE
Multiple /srv locations (docker)

### ISSUE THREAD

**Issue by poudenes** [filebrowser/filebrowser#2149]
Hi All,

I love the tool!!! use it on my Synology. I want to know if its already there and if not if this can be implement:

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1:/srv
      - /volumeUSB1:/srv_usb
```

I have mount my /volume1 to /srv but a want also mount my /volumeUSB1 to a path. I tried this but is not working.

Can someone help me or tell me if this is not possible?

**Comment by xxlbug** [comment]
Take advantage of the docker mounting system:

- /a/path/to/a/generic/ServerFolder:/srv
- /volume1:/srv/volume1
- /volumeUSB1:/srv/volumeUSB1

The application will see:
/srv
/srv/volume1
/srv/volumeUSB1

and have no idea where the folders are coming from
