### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by walterzilla** [filebrowser/filebrowser#215]
Great work! 👍 

A few suggestions of mine, if not planned yet and if feasible:

1) Recaptcha optional feature at the login form
2) ~password-change permission (in order to allow a password protected full guest access without risk of password changes)~ [DONE]
3) directories size 
4) ~notify pop-up after share link copied~ [DONE]
5) ...to be discovered yet :-P

Thanks!

P.S.: I'd like to translate it to italian language: if I compile a proper "it.yaml" file , would you kindly include it in next build? I'll keep up with possible subsequent updates, of course :-)

**Comment by hacdias** [comment]
Hello @amenolo!

First of all, thank you for your feedback! 😄 I like your suggestions and I think that 1 and 4 can be easily implemented and they may be useful for many users. I'll think about the others and I'll keep this issue updated!

Yes, you can translate it to Italian and I'll surely include it in the next build! 💯 

Thanks!

**Comment by hacdias** [comment]
I'm not sure if I can use reCAPTCHA. It asks me the domains I'll use with it and that's something I can't really tell. I can ask for the API Key though.

**Comment by hacdias** [comment]
I'm thinking about using [Noty](https://ned.im/noty/#/) for success and error messages. What do you think?

**p.s.:** I'll be stroking the items from your post as they are implemented.

**Comment by walterzilla** [comment]
Your responsiveness is gold, pal! 👍

About Recaptcha: maybe I misunderstood your words, but, based on using other Recaptcha-enabled script, domain and API key are simply mandatory end user related parameters, I don't really see how they could give trouble in integrating the feature itself, sorry...anyway do not go crazy on it...

About Noty: I didn't know of it, seems straightful nice, thumbs up!

**Comment by hacdias** [comment]
Hello @amenolo! Thanks! But it won't be gold for the next 4/5 days since I won't be home nor with a computer 😞 

I'll see the recaptcha thing when I return. 😄

**Comment by hacdias** [comment]
Hey @amenolo!


1. Going to implement it now!
3. Go doesn't provide a function to get the size of a directory so I would have to walk through every path inside a directory and sum the sizes of each file. That's not complicated, but it's not desirable - image that a user has thousand of sub folders: we would have to walk through all of them and see the size of each file. I'll leave this to do if someone else wants it too.

**Comment by hacdias** [comment]
ReCaptcha implemented! I'll add the docs soon.

**Edit**: Docs: https://henriquedias.com/filemanager/configuration/
