### ISSUE TITLE
Command Runner: Translate exit code to http code

### ISSUE THREAD

**Issue by michaelcplusplus** [filebrowser/filebrowser#2150]
**Is your feature request related to a problem? Please describe.**
I would like to use the command runner to check if a user is allowed to delete a directory.

In principle, this works very well. In the called program I set an exit code not equal to 0. The user is then shown 500 Internal server error. This error message is not very understandable for the end user.
![image](https://user-images.githubusercontent.com/24432169/193460162-a7e44bea-845f-444b-a44e-46ea2e8ae35d.png)

**Describe the solution you'd like**
Is there a way to set an exit code to show the user the HTTP code 403 forbidden?

![image](https://user-images.githubusercontent.com/24432169/193460126-16d7ea72-d768-4c5b-89e8-fc781dfc9d7a.png)

**Comment by ramiresviana** [comment]
I recommend you to check your server logs, it provides useful information.

**Comment by michaelcplusplus** [comment]
I looked in the implementation of the function errorToStatus in [filebrowser](https://github.com/filebrowser/filebrowser)/[http](https://github.com/filebrowser/filebrowser/tree/master/http)/utils.go.
And I think that this requirement can currently not be configured.

**Comment by ramiresviana** [comment]
The Command Runner is not supposed to be used as a hook. Interrupting the script execution can introduce unexpected behavior.

**Comment by michaelcplusplus** [comment]
That is a great pity. 
Is there a possibility that the Command Runner will be made available officially as a hook in the future.
