### ISSUE TITLE
JWT Token expires after 2h - use refresh tokens?

### ISSUE THREAD

**Issue by egodigitus** [filebrowser/filebrowser#2152]
**Is your feature request related to a problem? Please describe.**
When uploading a lot of files, the upload takes longer than the current JWT validity of 2 hours. This means that upload requests fail after 2h with 401, which makes uploads over night impossible.

**Describe the solution you'd like**
Quick fix: Make the JWT exp claim configurable
Solid solution: Introduce the concept of JWT refresh tokens

**Comment by aqwserf** [comment]
Hi! I agree with @egodigitus . Not necessarily for big file upload but I usually write text file and forgot to save it, and I finally remember to do so, session expires and I loose my modifications.
