### ISSUE TITLE
"Something really went wrong" while trying to browse files.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#2153]
**Description**
Clicking on "My Files" results in a white screen with "Something really went wrong."in the middle, and a red popup in the bottom right corner saying "500 Internal Server Error".

**Expected behaviour**
When clicking on "My Files", expected behavior is to see a list of the files and subdirectories in the root FileBrowser folder.

**What is happening instead?**
Clicking on "My Files" results in a white screen with "Something really went wrong."in the middle, and a red popup in the bottom right corner saying "500 Internal Server Error".

**Additional context**

**How to reproduce?**
Click on "My Files".

**Files**

**Comment by o1egl** [comment]
We need server logs so we can help you
