### ISSUE TITLE
Browser tab title : unexpected behavior

### ISSUE THREAD

**Issue by ruihaut** [filebrowser/filebrowser#2155]
**Description**
When I do an action on a file (upload, download, delete...), I have the current root directory displayed more than once on the tab title.
![image](https://user-images.githubusercontent.com/40445860/194008485-c0902b7f-0981-4f5e-a972-c3dc090f24b4.png)

**Expected behaviour**
The root directory should only be displayed once on the tab title.

**How to reproduce?**
Use the version 2.22.4 and upload a file. The root directory should appear more than once on the tab title.

**Comment by ramiresviana** [comment]
This was already reported in https://github.com/filebrowser/filebrowser/issues/1969
