### ISSUE TITLE
unsupported audio codec?

### ISSUE THREAD

**Issue by NZsolt91** [filebrowser/filebrowser#2157]
Hi. I have a lot of video file with different video codec, most of them are playable in filebrowser, but many of them has no sound when i try to play it.
Is there any way to solve to filebrowser support more audio codec?

Thanks.
<img width="638" alt="filebr" src="https://user-images.githubusercontent.com/38790753/194218471-aa289f06-b8b9-4353-95b5-37bd1e231cb5.png">

**Comment by o1egl** [comment]
Filebrowser doesn't use any decoding. Video player rely on a browser's capabilities to play video/audio. You need to check which audio codec is supported by your browser

**Comment by alanmilinovic** [comment]
Why not using transcoding with ffmpeg, that would solve many issues. Most of my videos are not having sound or doesn't play at all. In time when video streaming is booming this is must in my opinion.

**Comment by alanmilinovic** [comment]
> Filebrowser doesn't use any decoding. Video player rely on a browser's capabilities to play video/audio. You need to check which audio codec is supported by your browser

I have videos that are playing audio in my browser but via other web applications. The exact same videos are have no audio in File browser, so it is not related to browser and which audio codec is supported.

**Comment by alanmilinovic** [comment]
Any news on this topic?

Here is an example of mkv file that has no audio:
http://1nuc.mooo.com:20530/filebrowser/share/4w1W9XrE

Hope that someone can debug and fix it.

**Comment by alanmilinovic** [comment]
Is this project still actively developed?

**Comment by glowinthedark** [comment]
To sum up: MKV files will only play _with_ audio IF the audio codec is one of `avc1.42E01E, avc1.4D401F, avc1.58A01E, vp9, theora, mp4a.40.2, vorbis, opus, mp3`; if the codec is, for example, AC3 (`a_ac3`) then you'll get NO audio, as using this codec would require browser makers to pay a license fee.

Use `mediainfo` to check which codecs are used in each stream.
