### ISSUE TITLE
Adding image preview on shared folder

### ISSUE THREAD

**Issue by ibaraki-douji** [filebrowser/filebrowser#2162]
It would be cool to have the same interface as the non-shared folders because when you are in a folder with a lot of pictures you don't know what is what.

**Comment by niubility000** [comment]
How about this one? http://pdj.tpddns.cn:16889/share/o05vDt61

**Comment by zagi988** [comment]
That one is too slow because you need to click every file instead of using "native" thumbnail support.

**Comment by ibaraki-douji** [comment]
Having this option in shared folder will be great

![image](https://user-images.githubusercontent.com/72337875/201314691-0c99f247-ba4c-44ec-a230-013b765c5f96.png)

**Comment by ibaraki-douji** [comment]
nothing right?

**Comment by noave** [comment]
I support having this feature would make filebrowser more usable for sharing foto folders with others

**Comment by zero-thermo** [comment]
I’m also looking for shared folder thumbnails to make simple photo sharing easier. 

File Browser already has other features to support this use case:
- No account or login needed
- Time-based duration/expiration for shares

@niubility000 how did you enable content previews?

**Comment by LennartHallenberger** [comment]
This feature would be really nice to have.

**Comment by ty114514** [comment]
+1
Hopefully it can be reopened
It looks like this makes a lot of sense and seems to be directly portable from `Listing.vue`
I am interested in this, but the front end is confusing for me
: (
