### ISSUE TITLE
Support Nix package manager

### ISSUE THREAD

**Issue by m50S79sM6SRNp8Jn** [filebrowser/filebrowser#2163]
https://nixos.org/
https://search.nixos.org/packages
https://nixos.org/manual/nixpkgs/stable/#language-javascript

**Comment by dmadisetti** [comment]
@m50S79sM6SRNp8Jn did you find a solution for nix? Is there a derivation out there?

**Comment by nielsegberts** [comment]
I've started a PR to add File Browser to nixpkgs, see https://github.com/NixOS/nixpkgs/issues/122339
