### ISSUE TITLE
Files not listed

### ISSUE THREAD

**Issue by thewh1teagle** [filebrowser/filebrowser#2167]
I built this app with `npm` and `go`
simply cloned the repo
```
git clone https://github.com/filebrowser/filebrowser
```
And then I ran this commands:
```shell
cd filebrowser/frontend
npm install
npm run build
cd ..
go build
./filebrowser
2022/10/16 19:18:34 No config file used
2022/10/16 19:18:34 Listening on 127.0.0.1:8080
```
When I accessed the app from the browser at port `8080`
Only folders are listed, but not files at all.
Also I got related errors in console:
```console
[Vue warn]: Error in render: "TypeError: Object(...) is not a function"

found in

---> <Item> at src/components/files/ListingItem.vue
       <Listing> at src/views/files/Listing.vue
         <Files> at src/views/Files.vue
           <Layout> at src/views/Layout.vue
             <App> at src/App.vue
               <Root>
```
It happened on Chrome and Firefox browsers.

I tried to enable `sourceMap` so I can get better details about the error, but I haven't managed to.

**Comment by o1egl** [comment]
You can build the app by running `make build` command from the root

**Comment by thewh1teagle** [comment]
> You can build the app by running `make build` command from the root

It worked.
But how can I debug it in the browser?
When I try to set a breakpoint, I get the webpacked code.

Update:
I used this command to get perfect development experience
in `frontend` folder:
```
npm run watch
```
in root folder:
```
go run -tags dev main.go
```
