### ISSUE TITLE
shell can't use

### ISSUE THREAD

**Issue by Yaser-wyx** [filebrowser/filebrowser#2170]
**Description**
When I use the command in the shell, there's nothing happens.

![image](https://user-images.githubusercontent.com/26665516/196122558-acdc3c89-3e57-4a82-9052-4c7808a83920.png)

As figured above, when I use commands such as pwd, ls, etc. there's no output in the shell.

**Comment by o1egl** [comment]
Do you get any errors on the server-side logs?

**Comment by Yaser-wyx** [comment]
Yes, I have got some errors in the log, it seems that the websocket has wrong, how can I fix it?
![image](https://user-images.githubusercontent.com/26665516/197332200-4fea9882-a894-45a7-832f-5c844ab7733f.png)

**Comment by ramiresviana** [comment]
Are you using Filebrowser with a proxy?

**Comment by Yaser-wyx** [comment]
> Are you using Filebrowser with a proxy?

Yes, I am using Nginx as a proxy server, and this is the Nginx config:
![image](https://user-images.githubusercontent.com/26665516/198916394-26a3e6dc-7db4-4013-8398-5d4e20d3aa76.png)

**Comment by ramiresviana** [comment]
Looks like that your proxy is not forwarding the websocket requests correctly.

**Comment by Yaser-wyx** [comment]
Do you mean I should also set a proxy to forward the WebSocket requests?

**Comment by ramiresviana** [comment]
The shell makes use of websockets, the feature will not work if requests of this type are not forwarded.

**Comment by Yaser-wyx** [comment]
Ok, thanks!
