### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by thewh1teagle** [filebrowser/filebrowser#2172]
what are the consideration about support for right-to-left languages in the UI? (`RTL`)
Currently, when using `RTL` language, the UI components are shown from left to right.

I don't see that we use any specific framework with Vue, but we can implement it with `dir="rtl"` attribute (see this [link](https://stackoverflow.com/questions/57391221/add-dir-rtl-attribute-to-html-tag-in-vuejs))
And then we can use custom css with specific selector `[dir="rtl"].className { }`

**Comment by o1egl** [comment]
You can create a PR to add support for this feature

**Comment by thewh1teagle** [comment]
Added https://github.com/filebrowser/filebrowser/pull/2178
