### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Sadetea** [filebrowser/filebrowser#2173]
**Description** 
Not able to create new folder or new file, when try to create it showing message 403 Forbidden

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by Tamaarine** [comment]
Try running it with privilege, i.e. `sudo fileBrowser -r <your directory>`

**Comment by o1egl** [comment]
Probably the user under which you are running filebrowser has no write access to the folder
