### ISSUE TITLE
You don't have permissions to access this.

### ISSUE THREAD

**Issue by alanmilinovic** [filebrowser/filebrowser#2191]
I am trying to access home folder that has View content permissions set to Anyone, and receive message that I don't have permissions to access it.

Problem only exist if I am connected with XRDP to my server.

`Sep 14 16:20:42 1raspberrypi filebrowser[30958]: 2019/09/14 16:20:42 /home/pi/: 403 5.147.1.133:60656 lstat /home/pi/thinclient_drives: permission denied
`

thinclient_drives is the issue and my home directory is not accessibale if XRDP connection is open.

**Comment by ramiresviana** [comment]
Filebrowser does not handle permissions, it will use the permissions of the user running the Filebrower proccess. If the user was no permission to access the resource, Filebrowser will also not.

**Comment by alanmilinovic** [comment]
> Filebrowser does not handle permissions, it will use the permissions of the user running the Filebrower proccess. If the user was no permission to access the resource, Filebrowser will also not.

I know but the problem is, I cannot access my user home folder if XRDP session is active. That is a bug.

**Comment by ramiresviana** [comment]
Are you able to access the same directory using an terminal while Filebrowser shows the error? Looks like that your system is applying an lock, preventing the access while the XRDP session is active.

**Comment by alanmilinovic** [comment]
> Are you able to access the same directory using an terminal while Filebrowser shows the error? Looks like that your system is applying an lock, preventing the access while the XRDP session is active.

Of course, I am able to access user home directory on linux with ssh, sftp without any issue.

**Comment by alanmilinovic** [comment]
Found a solution with disabling channels and deleting thinclient_drives folder.
http://catch22cats.blogspot.com/2018/05/xrdp-creates-strange-directory-called.html?m=1

Strange that File browser is not handling this as all other protocols and programs I tried had no issue.

I understand that /home/pi/thinclient_drives is not working but /home/pi showing permissions error and "nothing here" message is File browser issue.

**Comment by ramiresviana** [comment]
This looks like an edge case which Filebrowser can't handle a folder containing an invalid/inaccessible subdirectory.

**Comment by alanmilinovic** [comment]
Is this going to be fixed?

**Comment by alanmilinovic** [comment]
Why did you configured to have bot that is closing issues automatically?

**Comment by OrhanTozan** [comment]
> Why did you configured to have bot that is closing issues automatically?

Yes, doesn't make sense IMO.

**Comment by alanmilinovic** [comment]
We are fighting against ghosts on this git project.
