### ISSUE TITLE
Symlinks to mapped network drives not working on windows (invalid link error)

### ISSUE THREAD

**Issue by 123321mario** [filebrowser/filebrowser#2193]
**Description**
Using symlinks mapped to network drives on Windows

**Expected behaviour**
Same behaviour as local symlinks

**What is happening instead?**
![image](https://user-images.githubusercontent.com/33780173/197886660-c3095114-81dd-4f42-b2ab-f6dfa4e610bf.png)
it says I don't have permission when I click on that

**Additional context**
Fresh install on Windows 11 (actually just discovered the software an hour ago)

**How to reproduce?**
-map a network drive on windows (let's say it's named Z:\)
-`mklink /D C:\media Z:\`
-`filebrowser -r C:\media`
-observe

**Comment by ramiresviana** [comment]
Are you able to access those links in the Windows explorer?

**Comment by wboyo** [comment]
I noticed a similar issue myself on this front recently upgrading from 2.17.2 to the latest 2.23.0

In my setup, Filebrowser runs as service within a Ubuntu VM under Hyper-V.

Autofs on Ubuntu is configured to auto-mount a Windows share as /mnt/server/filebrowser which is D:\Shared\filebrowser on a Windows files server.

Within the filebrowser subfolder on the server, any junctions created and used as a user account scope/home folder e.g. "mklink /j "User1" "E:\Shared\Users\Users1" presents the popup error NOT FOUND on logon within 2.23.0.

The same folder lists the content within as expected at the terminal.  Quickly rolled back to 2.17.2 for now and all works as before within the web interface!

Can provide more detail if required!

Thanks!

**Comment by JACK-THINK** [comment]
> I noticed a similar issue myself on this front recently upgrading from 2.17.2 to the latest 2.23.0
> 
> In my setup, Filebrowser runs as service within a Ubuntu VM under Hyper-V.
> 
> Autofs on Ubuntu is configured to auto-mount a Windows share as /mnt/server/filebrowser which is D:\Shared\filebrowser on a Windows files server.
> 
> Within the filebrowser subfolder on the server, any junctions created and used as a user account scope/home folder e.g. "mklink /j "User1" "E:\Shared\Users\Users1" presents the popup error NOT FOUND on logon within 2.23.0.
> 
> The same folder lists the content within as expected at the terminal. Quickly rolled back to 2.17.2 for now and all works as before within the web interface!
> 
> Can provide more detail if required!
> 
> Thanks!


Same with you. To be more exact, everything works well until v2.21.1. From v2.22.0 in which something about 'user scope' is *fixed*, this problem emerges. @o1egl

**Comment by dtila** [comment]
the same issue I have on Linux as well. Does anyone fixed the issue ?

To be precise I am following the guide from here https://cloudtechtips.com/network/using-file-browser-with-multiple-paths-or-directories/448/ 

The user filebroiwser is in the group storage, and there is read permissions on all the hard drive for that group
