### ISSUE TITLE
"??" in markdown replaced with jQuery...

### ISSUE THREAD

**Issue by adzeitor** [filebrowser/filebrowser#22]
1. New md post
2. Input content with **"??"**
3. Save. Open browser network debuger. In form data you will see this: `{"content":"\r\n"}:`
4. Again click save

``` js
{"content":"jQuery2140322192081483081_1443556381439\r\n"}:
```

**Comment by hacdias** [comment]
Thanks for reporting that strange bug. I'll see.

**Comment by hacdias** [comment]
Another bug: the things are just saving at the second "Save". In the first one they're not saving. Is this happening there too?

**Edit**: fixed this, and I already saw that this is one of your problems ;)

**Comment by mholt** [comment]
^ looks like a JSONP issue. (that jQuery21403.... looks like a JSONP callback function. your handler is probably getting JSONP back but expecting it to be body text or something)

**Comment by hacdias** [comment]
@mholt Hmmm... But that's strange. Why the characters "??"?

**Comment by hacdias** [comment]
Apparently, when saving, it sends `"{"content":"??\r\n"}"` to the server, so the problem might be there! No?

**Comment by adzeitor** [comment]
@mholt :+1: 
http://bugs.jquery.com/ticket/12326

**Comment by hacdias** [comment]
Fixed, thanks @adzeitor and @mholt!!! In 24hrs it will be available on caddyserver.com
