### ISSUE TITLE
only support chrome browser?

### ISSUE THREAD

**Issue by helloobaby** [filebrowser/filebrowser#2200]
as title .  IE browser cant login filebrowser

**Comment by helloobaby** [comment]
![image](https://user-images.githubusercontent.com/84119280/199016613-f8427f18-3899-4362-9b92-ca4a52cb1a19.png)

has always been

**Comment by o1egl** [comment]
Can you confirm that it works on chrome?

**Comment by helloobaby** [comment]
sure. I also test it on edge and it works too. Only IE can't

**Comment by o1egl** [comment]
Microsoft ended support of the IE browser. I don't see a reason supporting it in the app

**Comment by helloobaby** [comment]
ok thk u
