### ISSUE TITLE
Failed - Network error

### ISSUE THREAD

**Issue by jdewb** [filebrowser/filebrowser#2203]
**Description**
Trying to download large files from the filebrowser web portal. After about 30 seconds the download fails.

**Additional context**
Not sure if it's related but I'm using Nginx Proxy Manager to forward to the service, and give it an SSL. Not sure why that would cause a problem. It happens when I try to download large .mp4 files.

**Comment by jdewb** [comment]
I tried disabling the SSL cert from Nginx Proxy Manager, which seems to have fixed the issue.
Does anyone know or have insight into why that may be the issue?

**Comment by ramiresviana** [comment]
Can you provide server logs? Looks like your proxy configuration has a request timout of 30 seconds.
