### ISSUE TITLE
"address": "0.0.0.0" in the config file is invalid

### ISSUE THREAD

**Issue by flytkgl** [filebrowser/filebrowser#2205]
**Description**

`"address": "0.0.0.0"` in the config file is invalid and must be specified at run time `./ filebrowser -a 0.0.0.0`

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by ramiresviana** [comment]
I am unable to reproduce this, can you provide server logs and a config file example?

**Comment by flytkgl** [comment]
> 

![1667784623779](https://user-images.githubusercontent.com/3757930/200208538-62edf1cf-2d61-4554-9d20-73d29061c710.png)

**Comment by judiaz** [comment]
try running: filebrowser config import "config.json"

**Comment by flytkgl** [comment]
> try running: filebrowser config import "config.json"

In this way, it will work properly
