### ISSUE TITLE
want filebrowser support https

### ISSUE THREAD

**Issue by EnderAvaritia** [filebrowser/filebrowser#2208]
**Is your feature request related to a problem? Please describe.**
some explorer forced to use https but the filebrowser seems can't support https

**Describe the solution you'd like**
does the filebrowser support https nativelly

**Comment by o1egl** [comment]
Check cert and key [cli flags](https://filebrowser.org/cli/filebrowser#options)

**Comment by EnderAvaritia** [comment]
> Check cert and key [cli flags](https://filebrowser.org/cli/filebrowser#options)

thanks for your help,I had not known it support https before
