### ISSUE TITLE
I think we should add version information to the interface.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#221]
I think we should add version information to the interface.
Otherwise it may forget the current version, and whether you need to upgrade.

**Comment by ghost** [comment]
Also, whether the site title can be customized, for example: DOUBI - Files, DOUBI - Profile Settings, DOUBI - Video.
Some interesting little details suggestion ~

**Comment by hacdias** [comment]
Thanks for the suggestions! I'll probably do them 😄
