### ISSUE TITLE
v2.23.0 timeout

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#2211]
**Description**
Starting v2.23.0 ends up with timeout

**Expected behaviour**
starts

**What is happening instead?**

```
root@files ~ # ❯❯❯ docker logs 075f2182e00a                                                                                                          
2022/11/05 22:54:14 timeout
```

**Additional context**
I start with this:
`command: -a 0.0.0.0 -p 4000 -d /db/data -r /var/www --img-processors 1`

**How to reproduce?**
Start with the above args

**Files**
N/A

**Comment by o1egl** [comment]
Have you stopped the previous instance? DB file can't be shared among instances

**Comment by princemaple** [comment]
Gotcha thanks 👍

**Comment by princemaple** [comment]
It's because I changed the deployment strategy recently
