### ISSUE TITLE
Disable ReCAPTCHA setting in GUI

### ISSUE THREAD

**Issue by neutor** [filebrowser/filebrowser#2212]
What is the best way to disable ReCAPTCHA, please? I don't like Google in general.

I'm running File Browser in Portainer as a docker container.

Cheers!

**Comment by ramiresviana** [comment]
Filebrowser will not use ReCAPTCHA by default, it must be enabled manually. Running `filebrowser config set --auth.method=json` will remove the ReCAPTCHA configuration on an existing installation.
