### ISSUE TITLE
Is there a user manager api doc or golang sdk

### ISSUE THREAD

**Issue by shuaiyy** [filebrowser/filebrowser#2216]
**Is your feature request related to a problem? Please describe.**

I deployed a lot of instance for different prod-env storage, It's hard to manage with a lot of users.

**Describe the solution you'd like**

I want to use web api to register users, but seems no docs or sdk, need a help.

**Comment by ramiresviana** [comment]
Filebrowser has no documentation for the API. The hook authentication method (https://github.com/filebrowser/filebrowser/pull/1554) can be used to add custom behavior to the user authentication.
