### ISSUE TITLE
Can't set /config/settings.json and /database/filebrowser.db

### ISSUE THREAD

**Issue by zagi988** [filebrowser/filebrowser#2217]
**Description**
I am trying to use custom locations for settings.json and filebrowser.db so I can back it up easier.

```
docker run \
    -v /media/filebrowser:/srv \
    -v /home/USER/filebrowser/filebrowser.db:/database/filebrowser.db \
    -v /home/USER/filebrowser/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -p 8080:80 \
    filebrowser/filebrowser:latest
```

**Expected behaviour**
I expect filebrowser to use my custom locations as per installation guide for docker.

**What is happening instead?**
Even tho everything is done as installation guide, filebrowser decides to place settings.json and filebrowser.db on stock location (/var/lib/docker/containerid)

**How to reproduce?**
Do as I did.

**Comment by posta246** [comment]
Hi,
If I remember well, I had the same problem, actually solved via workaround: try to create empty file (on linux: `touch /path/to/file/filebrowser.db`, for example) before starting container.

**Comment by ramiresviana** [comment]
Filebrowser will use the default location for the database and config files. The location of those files can be changed using CLI options, check https://filebrowser.org/cli/filebrowser

**Comment by zagi988** [comment]
> Hi, If I remember well, I had the same problem, actually solved via workaround: try to create empty file (on linux: `touch /path/to/file/filebrowser.db`, for example) before starting container.

Doesn't help, already tried that.

**Comment by Lanjelin** [comment]
According to [the docs](https://filebrowser.org/installation), :latest-tag seems to be using `/path/filebrowser.db:/database.db`and `/path/.filebrowser.json:/.filebrowser.json`, while the :s6-tag (linuxserver) uses `/path/to/filebrowser.db:/database/filebrowser.db`and `/path/to/settings.json:/config/settings.json` (along with a different way to set user).

linuxserver version seems broken though, as it just exits without tossing any errors.

Unless you're using custom settings, .filebrowser.json can be skipped, but database.db is needed, and as mentioned above, do `touch /path/to/file/filebrowser.db` if you're missing the file.

```
docker run \
    -v /path/to/root:/srv \
    -v /path/filebrowser.db:/database.db \
    -v /path/.filebrowser.json:/.filebrowser.json \
    -u $(id -u):$(id -g) \
    -p 8080:80 \
    filebrowser/filebrowser:latest
```

**Comment by meminens** [comment]
This issue is unresolved. Anyone knows the codebase enough to tackle this?
