### ISSUE TITLE
timeout error will running the command

### ISSUE THREAD

**Issue by Jaishankar872** [filebrowser/filebrowser#2218]
**Description**
timeout error will running the command only some of the command working

**What is happening**
jai@jetson:/$ sudo docker exec -it Filebrowser /filebrowser version
File Browser v2.22.4/ceec4dcf
jai@jetson:/$ sudo docker exec -it Filebrowser /filebrowser config set --branding.name "Testing"
2022/11/12 07:46:53 timeout
jai@jetson:/$ sudo docker exec -it Filebrowser /bin/sh
/ # ./filebrowser version
File Browser v2.22.4/ceec4dcf
/ # ./filebrowser config set --branding.name "Testing"
2022/11/12 07:47:23 timeout
/ #

I didn't understand the issue while running the command.
What is issue here??

**Comment by lpyparmentier** [comment]
similar trouble here on v2.23.0 

EDIT: temporarily solved with https://github.com/filebrowser/filebrowser/issues/2066#issuecomment-1264937559

**Comment by ramiresviana** [comment]
The `config set` command cannot be used when FileBrowser is running.

**Comment by Jaishankar872** [comment]
How to stop the FileBrowser to run the config set cmd

I am using Filebrowser in a docker container if I stop container, I can't ssh into it.

**Comment by ColCh** [comment]
Yes, you need to stop filebrowser first.

Just use temp container to edit your filebrowser container.

I prepared quick example on how to do it in docker.

1. determine your filebrowser container name or container id
```
docker ps
->
CONTAINER ID   IMAGE                                    COMMAND                  CREATED       STATUS                        PORTS                                                                                                                NAMES
fc4f147e14c9   filebrowser/filebrowser:s6               "/init"                  3 days ago    Up About a minute (healthy)   127.0.0.1:8036->80/tcp                                                                 filebrowser
```
name is `filebrowser`

2. stop it `docker stop filebrowser`
3. just in case, list your config: `docker run  --rm --name=filebrowser_cfg  -v $HOME/qbittorrent/downloads/:/srv  -v $HOME/filebrowser/config:/config -v $HOME/filebrowser/database:/database   -e PUID=1000     -e PGID=1000 --entrypoint="" filebrowser/filebrowser:s6 filebrowser config --config=/config/settings.json --database=/database/filebrowser.db cat` (**ATTENTION**: replace your filebrowser config path and database path).
4. edit your filebrowser config: `docker run  --rm --name=filebrowser_cfg  -v $HOME/qbittorrent/downloads/:/srv  -v $HOME/filebrowser/config:/config -v $HOME/filebrowser/database:/database   -e PUID=1000     -e PGID=1000 --entrypoint="" filebrowser/filebrowser:s6 filebrowser config --config=/config/settings.json --database=/database/filebrowser.db set --auth.method=proxy --auth.header=X-Fb-Auth` (I use `X-Fb-Auth` header here)
5. optionally, check your config (see "list your config point")
6. start filebrowser container: `docker start filebrowser`
