### ISSUE TITLE
error panic: While parsing config: unexpected end of JSON input

### ISSUE THREAD

**Issue by dewijones92** [filebrowser/filebrowser#2221]
Many thanks for this amazing project. However, I am stuck on the following error. Please help

**Description**
Trying to follow docker installation commands here: https://filebrowser.org/installation

**Expected behaviour**
The docker container to run without any errors

**What is happening instead?**
error panic: While parsing config: unexpected end of JSON input

**This script should work**
```
set -x
filebrowserpath_db="$(pwd)/filebrowser.db"
filebrowserpath_json="$(pwd)/.filebrowser.json"
echo "" > $filebrowserpath_db
echo "" > $filebrowserpath_json

ls -al

docker run \
        -v $(pwd):/srv \
    -v $filebrowserpath_db:/database.db \
    -v $filebrowserpath_json:/.filebrowser.json \
    -u $(id -u):$(id -g) \
    -p 8089:80 \
    filebrowser/filebrowser
```

**But it produces this error**
```
root@raspberrypi:/tmp/filebrowserTest # bash go.sh
++ pwd
+ filebrowserpath_db=/tmp/filebrowserTest/filebrowser.db
++ pwd
+ filebrowserpath_json=/tmp/filebrowserTest/.filebrowser.json
+ echo ''
+ echo ''
+ ls -al
total 20
drwxr-xr-x  2 pi   pi   4096 Nov 12 18:22 .
drwxrwxrwt 16 root root 4096 Nov 14 06:56 ..
-rw-r--r--  1 root root    1 Nov 14 06:56 filebrowser.db
-rw-r--r--  1 root root    1 Nov 14 06:56 .filebrowser.json
-rw-r--r--  1 pi   pi    364 Nov 14 06:53 go.sh
++ pwd
++ id -u
++ id -g
+ docker run -v /tmp/filebrowserTest:/srv -v /tmp/filebrowserTest/filebrowser.db:/database.db -v /tmp/filebrowserTest/.filebrowser.json:/.filebrowser.json -u 0:0 -p 8089:80 filebrowser/filebrowser
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
        /home/runner/work/filebrowser/filebrowser/cmd/root.go:410 +0x3c0
github.com/spf13/cobra.(*Command).preRun(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:886
github.com/spf13/cobra.(*Command).execute(0x13be500, {0x4000030220, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:822 +0x33c
github.com/spf13/cobra.(*Command).ExecuteC(0x13be500)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x2c
main.main()
        /home/runner/work/filebrowser/filebrowser/main.go:8 +0x20
```

**Comment by dewijones92** [comment]
I have just seen another issue that is similar to mine
https://github.com/filebrowser/filebrowser/issues/1824

As a suggestion:
Maybe on detection of an empty file it should populate it with a default config? Preventing the aforementioned error
Afterall it suggests here (https://filebrowser.org/installation) that all the user should do is create two empty files.

thoughts? 
thanks

**Comment by ramiresviana** [comment]
The default settings are used if no config file is provided.

**Comment by kokogakayui** [comment]
> The default settings are used if no config file is provided.

That is not what happens for me. If no file is provided, then a FOLDER called .filebrowser.json is created, and the container can not launch. If an empty file called .filebrowser.json is created before launching the container, then we get the above mentioned error. 

This could indeed be upgraded for easier use.
