### ISSUE TITLE
Download Contents of Folders without Zipping

### ISSUE THREAD

**Issue by giozucca** [filebrowser/filebrowser#2224]
It can be difficult when trying to download folders with large files to decide between letting the server zip all the files together, putting the server under load, and then having to unzip the file after it has been downloaded, or going through the folder and clicking download on every file.

This feature would help with downloading folders filled with a number of large files, or a folder with a lot of small files. This could be implemented as an opt-in feature, so if one wanted to give their users the option to download the contents of folders without zipping it would make it easy. 

Another solution to this issue would be to have a page that shows the download links to all the files in a folder. That way, rather than having to implement a "download all" feature instead of just having the end user download a zip, said list of download links could be given to another program such as JDownloader or IDM, letting that program deal with managing the downloads. 

The most realistic solution would probably be to generate a list of download links so that another program can handle them, but having either would make downloading large folders much easier on the server and the end user.

**Comment by a-fried-pOtaTO** [comment]
I would still like to bump this just in case abyo

**Comment by giozucca** [comment]
I would still like to bump this comment, because I think it would be a very good feature

**Comment by ados8** [comment]
> I would still like to bump this comment, because I think it would be a very good feature

Not sure why the issues are set to close so fast.
Seems I requested nearly the same features so will see if nets a response.
You could outright block the bulk downloading depending on your proxy setup.
I'm using NGINX so was a quick few lines in the config:
`if ($request_uri ~* (zip|tar|tar.gz|tar.bz2|tar.xz|tar.lz4|tar.sz) ){
    return 403;
}`
If you want to get fancy and have it authorise the user against a proxy to bulk download, just put the code in place of the 403. This is a complete workaround and my users can only download files, no folders, which is annoying but it's something.

**Comment by giozucca** [comment]
> > I would still like to bump this comment, because I think it would be a very good feature
> 
> Not sure why the issues are set to close so fast. Seems I requested nearly the same features so will see if nets a response. You could outright block the bulk downloading depending on your proxy setup. I'm using NGINX so was a quick few lines in the config: `if ($request_uri ~* (zip|tar|tar.gz|tar.bz2|tar.xz|tar.lz4|tar.sz) ){ return 403; }` If you want to get fancy and have it authorise the user against a proxy to bulk download, just put the code in place of the 403. This is a complete workaround and my users can only download files, no folders, which is annoying but it's something.

Unfortunately, I don't need to block bulk downloading, but rather I would like an option where a user can bulk download WITHOUT having to zip the contents of the folder. But thank you for the info.

**Comment by xenago** [comment]
Would be great to have this issue reopened. Blocking zip downloads and offering the option to download all files individually would both be welcome.

Edit: the previously described nginx zip download rule didn't work as I expected. Tweaked a bit, added user warning

```
error_page 406 = @ziplocation;
location / {
    if ( $query_string ~* ^((.+?)(algo=)?(zip|tar|tar\.gz|tar\.bz2|tar\.xz|tar\.lz4|tar\.sz)(&auth=.+)?.*)$ ) {
        return 406;
    }
    proxy_pass http://files_server/;
}
location @ziplocation {
    default_type text/html;
    return 403 "<!DOCTYPE html><h1>Archive downloads not permitted.</h1><h2>It looks like you have tried to download a folder or zip/archive of several files. Please download individual files instead.</h2>\n";
}
```

**Comment by liuhangbin** [comment]
I also hope that the directory can be downloaded directly without compression.

**Comment by fcps3** [comment]
It would be extremely useful

**Comment by Prestonsr** [comment]
#5371 - @hacdias answered this - https://github.com/filebrowser/filebrowser/issues/5371#issuecomment-3194353696

It's actually not compressed, the directory needs to be turned into a single file to send through web. So its zipped without compression. I suggested adding in the ZIP option (0 Compression).
https://github.com/filebrowser/filebrowser/issues/5371#issuecomment-3781871220

**Comment by liuhangbin** [comment]
Can we just download the files in the folder in parallel (maybe a new option) other than download one zipped folder (although not compressed)?
