### ISSUE TITLE
Firefox 57.0a1 slow upload

### ISSUE THREAD

**Issue by ferronrsmith** [filebrowser/filebrowser#223]
Tested this with/without add-ons and the performance was horrible locally.
Test a different container and the performance was still horrible.
Tested in a Private mode and it works fine. Tested chrome (works)

**Comment by hacdias** [comment]
I'll see if I have the problem here.

**Comment by hacdias** [comment]
Hello @ferronrsmith! The performance on my computer is similar on both Chrome and Firefox. Have you tried another computer?

**Comment by ferronrsmith** [comment]
Tested again with FF 57.0a1 (2017-09-04) (64-bit) (Ubuntu Linux) same issue. I only use FF

**Comment by ferronrsmith** [comment]
Got the same issue with FF 57.0a1 (2017-09-06) (64-bit) on my mac. I'm sure it has something to do with `XMLHttpRequest`.  If I have some time this weekend I'll submit a PR

**Comment by hacdias** [comment]
I'll check this out tomorrow to see if I can do something. What I find
strange is that I don't have that issue on my ff. But if you can help, I'll
appreciate 😁

**Comment by hacdias** [comment]
Do you still have this problem @ferronrsmith ?
