### ISSUE TITLE
Http not redirected to https when using custom port (docker)

### ISSUE THREAD

**Issue by benwiley4000** [filebrowser/filebrowser#2231]
**Description**
I am serving filebrowser on a custom port (not 80 or 443 [not 8080 either]) and I am using the key and cert options to serve over HTTPS. All this is being done with the Docker image. It works fine if I explicitly specify the https protocol in my browser, but if I don't, it attempts to connect with http and I get an error message.

**Expected behaviour**
Since I specified a non-80 port for my web server, as well as SSL configuration, it seems normal that there should be an automatic redirect implemented from HTTP to HTTPS.

**What is happening instead?**
I get an error message that I'm trying to make an HTTP request to an HTTPS server.

**Additional context**
Here is a discussion of how such a redirect can be done in Go. https://groups.google.com/g/golang-nuts/c/4oZp1csAm2o/m/nTTKDvvFJQ0J?pli=1

**How to reproduce?**
Specify a nonstandard port as well as the key and cert options, and try to connect in a browser without specifying the protocol explicitly.

**Comment by ramiresviana** [comment]
Browsers will try the default HTTPS and HTTP ports when accessing an address. Since you`re using an non-standard port for your web server, browsers will show an error. I recommend you to setup a web proxy to fulfill yours needs.

**Comment by benwiley4000** [comment]
Indeed I was able to use Caddy as a web proxy to make this work. Nginx also supports same-port http and https but I couldn't get it to work without errors.
