### ISSUE TITLE
Subtitle support for videos

### ISSUE THREAD

**Issue by benwiley4000** [filebrowser/filebrowser#2234]
**Is your feature request related to a problem? Please describe.**
I'd like to view subtitles when browsing video content served by the file browser. I often have caption files sitting in the same folder with the same filename as the video (except for the extension), but when I open up the video to stream in the browser I don't have access to these subtitles.

**Describe the solution you'd like**
If a subtitle file is available on disc and matches the name of the video file, it's automatically converted to webvtt and made available on the video playback. Another possible idea (in combination with the first?) is to have some UI for selecting a subtitle file, similar to the "move to" dialog.

**Describe alternatives you've considered**
A full-fledged media server is an option but I often use the filebrowser app to look at videos and this could really be useful for previewing media without having to download it all.

I'm not an expert in go but I am a front end web developer in case some help would be needed with this. I've done a lot of work with media players and closed captions in the past. If I did help with this I would need some pointers on where and what to change.

**Comment by ramiresviana** [comment]
Filebrowser has support for subtitles with the `.vtt` format. Adding a subtitle file with the same name as the video, will make that subtitle available on the player.

**Comment by benwiley4000** [comment]
Awesome thanks. My situation is that I have a bunch of SRT files already and I would like not to duplicate them on disk, although I understand VTT is the format supported on the web. I wonder if there's a way to convert all SRT files to VTT, only within the Docker container for filebrowser.

**Comment by ramiresviana** [comment]
There's no feature for converting SRT files. You can try searching for a tool that allows you to convert those type of files.
