### ISSUE TITLE
Search doesn't work on symlinks

### ISSUE THREAD

**Issue by dnquintela** [filebrowser/filebrowser#2247]
**Description**

Search doesn't work on symlinks. For example, if we have a symlink and try to search for anything inside it the search doesn't return any folders or files.

**Expected behaviour**

The search returns the files and folders that matches the query.

**What is happening instead?**

No errors or logs. An empty array is returned from the search query.

**How to reproduce?**

1) Create a folder and a file inside it.
2) Create a symlink using the folder created.
We now have a file structure like this:
![image](https://user-images.githubusercontent.com/6645147/205692504-6d4da20e-c3f7-48f5-8b4c-99720e2615d3.png)
3) Search for the file on the folder created on 1):
![image](https://user-images.githubusercontent.com/6645147/205692870-a409b292-8b8c-4f64-86bb-90d5225ec37a.png)
4) Search for the file on the symlink created on 2)
![image](https://user-images.githubusercontent.com/6645147/205692989-59d0e5eb-3849-4824-a138-53e501a23056.png)

Thanks!

**Comment by marceliq** [comment]
I run into same issue, temporary workaround is to `mount --bind` instead of making symlink. But it is not much safe solution.

**Comment by dnquintela** [comment]
Hello all,
is there any news on this topic?
Can we reopen the issue, please?

**Comment by MrChinR** [comment]
I have the same problem.hope it could be fixed.
