### ISSUE TITLE
The directory to be accessed is empty

### ISSUE THREAD

**Issue by lihuacai168** [filebrowser/filebrowser#225]
my configuration is 
![image](https://user-images.githubusercontent.com/11568297/29915530-b17aec1a-8e6e-11e7-8855-9a893748b0e8.png)

here is testfile directory 
![image](https://user-images.githubusercontent.com/11568297/29915615-ea8f0d10-8e6e-11e7-9d72-c3635a2c5783.png)

when I access ip:92
![image](https://user-images.githubusercontent.com/11568297/29915660-13443da2-8e6f-11e7-9784-4c1db9fe5f8c.png)

log is 
![image](https://user-images.githubusercontent.com/11568297/29915707-358fd6f0-8e6f-11e7-85ac-1796904699f1.png)

**Comment by ferronrsmith** [comment]
Are you sure the default scope was set ? https://henriquedias.com/filemanager/configuration/

**Comment by lihuacai168** [comment]
@ferronrsmith I follow this sample .https://caddyserver.com/docs/http.filemanager
![image](https://user-images.githubusercontent.com/11568297/29919474-07eaa75e-8e7c-11e7-8f0f-c49fbb74623c.png)

**Comment by hacdias** [comment]
That's the **default** for **new users**. Try going to **Settings** → **User Management** → Edit your user and change the scope please.

**Comment by lihuacai168** [comment]
@hacdias Thank for your answer,it works

**Comment by hacdias** [comment]
😄  No problem!
