### ISSUE TITLE
Symlinks are not working in Linux/Docker

### ISSUE THREAD

**Issue by jonp92** [filebrowser/filebrowser#2256]
**Description**
Creating a symlink /mnt/sshfs to /mnt/rcloud/rsync.net fails

**Expected behaviour**
To be able to browse the symlinked directory

**What is happening instead?**
Displays Invalid link and no content. However on the host I can browse to the symlink and see the files just fine

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem. 

**How to reproduce?**
ln -s /mnt/sshfs /mnt/rcloud/rsync.net and use /mnt/rcloud as your file base.

NOTE this only happens when running from Docker, not natively.

**Comment by ebartz** [comment]
I am using docker and it works for me. Keep in mind that the symlink has to pint to the directory inside of the docker container. So you have to add the folder from your system as a volume in docker and then use the path inside the container for the symlink.

**Comment by jonp92** [comment]
Yikes apparently I thought I knew docker better than I actually do. Fixed my volume mounts and now everything works as expected.
