### ISSUE TITLE
Changing the baseurl or basepath from command line or config file?

### ISSUE THREAD

**Issue by dstreet26** [filebrowser/filebrowser#226]
I'm trying to run filemanager on its own port and behind an nginx proxy. (I want to type in website.com/admin and have it go to the filemanager UI)

However, when I go to that page, only the index.html loads and every other asset is 404 (because it's looking for *website.com/app.js* instead of *website.com/admin/app.js*.

I have spent 3 hours doing all sorts of nginx sub_filter configs but nothing seems to work. 

Is there a way for me to tell filemanager that the baseurl should be *website.com/admin*?

**Comment by hacdias** [comment]
~Running using Caddy or command line?~

I've to create a new flag for this. I'll add it ASAP.

**Comment by dstreet26** [comment]
Command line:

`filemanager -p 42634 --staticgen hugo`

**Comment by dstreet26** [comment]
Just to be clear and helpful, I would want to enter something like this:

`filemanager -p 8080 --staticgen hugo --baseurl "/admin"`

Or something like that. 

Alternatively, in the config file:

```json
{
  "port": 8080,
  "noAuth": false,
  "address": "127.0.0.1",
  "baseurl": "/admin"
}
```

**Comment by hacdias** [comment]
Yes, I'll do something like that. Although I'm not going to be home for the
next 3 days so I don't know if I can publish that change until Monday.

**Comment by hacdias** [comment]
Available on 1.2.7. The flag's `--baseurl`.

**Comment by dstreet26** [comment]
Now the response that I get is 404 Not Found for the index page.

I have tried:

- "admin"
- "/admin"
- "admin/"
- "/admin/"

I have tried with both the docker version and the command-line version.

I also went back and tried to proxy the normal docker container without the "baseurl" option and got the same result as before (index page loads, but all assets are 404)

I can open up a separate issue...

**Comment by dstreet26** [comment]
I was able to get what I want with caddy.


```
https://mywebsite.com
gzip
log caddylog.log
root public
hugo
filemanager /admin

tls {
    dns digitalocean
}
```

**Comment by hacdias** [comment]
I know what the problem is. I have a BaseURL and a PrefixURL, which are different things. PrefixURL is the part of the URL which is stripped from the request **before** it comes to File Manager and this is what you want because the program is running behind a proxy. I'll add the new flag now 😄 And then you don't need to use caddy if you don't want to.

**Comment by hacdias** [comment]
Just pushed v1.2.8. It will build and the binaries will be available soon. I'll ask you to try running `filemanager --prefixurl=/admin` 😄 Sorry for the troubles.

**Comment by dstreet26** [comment]
Now I can't launch filemanager:

`filemanager -p 42634 --staticgen hugo  --baseurl "/admin"`


```
unable to redefine 'p' shorthand in "filemanager" flagset: it's already used for "port" flagpanic: unable to redefine 'p' shorthand in "filemanager" flagset: it's already used for "port" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc4200ea2d0, 0xc420196be0)
        /home/travis/gopath/src/github.com/spf13/pflag/flag.go:827 +0x45a
github.com/spf13/pflag.(*FlagSet).VarPF(0xc4200ea2d0, 0x13c9b40, 0x14053a0, 0xabb812, 0x9, 0xab5a72, 0x1, 0xabc01a, 0xa, 0xc420196b40)
        /home/travis/gopath/src/github.com/spf13/pflag/flag.go:784 +0x120
github.com/spf13/pflag.(*FlagSet).VarP(0xc4200ea2d0, 0x13c9b40, 0x14053a0, 0xabb812, 0x9, 0xab5a72, 0x1, 0xabc01a, 0xa)
        /home/travis/gopath/src/github.com/spf13/pflag/flag.go:790 +0x8e
github.com/spf13/pflag.StringVarP(0x14053a0, 0xabb812, 0x9, 0xab5a72, 0x1, 0x0, 0x0, 0xabc01a, 0xa)
        /home/travis/gopath/src/github.com/spf13/pflag/string.go:53 +0xaa
main.init.1()
        /home/travis/gopath/src/github.com/hacdias/filemanager/cmd/filemanager/main.go:56 +0x378
main.init()
        /home/travis/gopath/src/github.com/hacdias/filemanager/cmd/filemanager/main.go:244 +0x9d
```

**Comment by hacdias** [comment]
**Sorry** 😞 V1.2.9 on its way. I'm so sorry.

**Comment by dstreet26** [comment]
It works!

For other people who might have this problem, here is my nginx config and command-line settings:

```
server {
    listen 80;
    server_name mywebsite.com www.mywebsite.com;
    return 301 https://$host$request_uri;
}


server {
        listen 443 ssl;
        server_name mywebsite.com www.mywebsite.com;
        
        #<SSL Stuff
        
        root /usr/share/nginx/html;
        index index.html index.htm;
        server_name localhost;
        

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ /.well-known {
                allow all;
        }

        location /admin {
                proxy_pass http://localhost:42634;
        }
}
```

`filemanager -p 42634 --staticgen hugo  --baseurl "/admin"`

**Comment by hacdias** [comment]
😄
