### ISSUE TITLE
Is there a suitable client app?

### ISSUE THREAD

**Issue by qian-jiahong** [filebrowser/filebrowser#2261]
It's a small program, and it's great! It works very well in my router. 

I hope that the photo album in my mobile phone will be automatically backed up to the hard disk in the router, but I can't find the Android client. Is there a suitable client app?

**Comment by HannesJo0139** [comment]
I think you look for some cloud like nextcloud or so.

**Comment by qian-jiahong** [comment]
> I think you look for some cloud like nextcloud or so.

No. My router cannot run nextcloud such a huge program. But I need the client to automatically back up the photo album in the phone to the router.

**Comment by HannesJo0139** [comment]
Yeah but this is a filebrowser and not a cloud server. :/

**Comment by o1egl** [comment]
There is no such client, and we don't have plans to add it. As mentioned above, this project aims to be a simple file browser, not a fully featured cloud backup solution
