### ISSUE TITLE
Problem at first connection

### ISSUE THREAD

**Issue by 1qc1q** [filebrowser/filebrowser#2262]
Hello, I installed file browser on my Raspberry pi 4 (curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash) then I launched file browser with this command

filebrowser -r /home/pi/Public/filebrowser

and in response I have this message

No config file used
listen tcp 127.0.0.1:8080: bind: address already in use

So I browsed my files even in www but no trace of file browser except in /usr/local/bin

I guess there is a conflict because I have apache, php, mysql already installed for pi-hole
If you can help me because I am a novice and speak English badly, what should I do?

I understood that we can use personalized flags to launch the command but I'm afraid of making a mistake.

Thank you for your help and understanding

**Comment by o1egl** [comment]
As you can see in the response, it says that the port is already in use by another app. You can use `-p` flag to bind to a different port. You can find cli docs on this [page](https://filebrowser.org/cli/filebrowser)

**Comment by 1qc1q** [comment]
I just tested it works but I didn't know whether to put p 8080 or p=8080 it works the same for the local ip or that of the router 192....
It's a nice clean and clear file browser & not restricted to the www folder You can access the whole disk (system)
Thank you

**Comment by 1qc1q** [comment]
Ok sorry, I'm a newbie.
