### ISSUE TITLE
Bugs about 'User Scope'

### ISSUE THREAD

**Issue by JACK-THINK** [filebrowser/filebrowser#2264]
**Description**

User: root
Home directory: `/root` with mode: 700
OS: Linux
Directory structure of filebrowser:
 > /usr/local/filebrowser/
 > /usr/local/filebrowser/etc/
 > /usr/local/filebrowser/etc/database.db
 > /usr/local/filebrowser/usr/CHANGELOG.md
 > /usr/local/filebrowser/usr/filebrowser
 > /usr/local/filebrowser/usr/LICENSE
 > /usr/local/filebrowser/usr/README.md

**Expected behaviour**

The code below should work without any error.

```sh
"/usr/local/filebrowser/usr/filebrowser" --database "/usr/local/filebrowser/etc/database.db" config init --address "0.0.0.0" --branding.disableExternal --branding.name "PCloud" --perm.admin --port "33333" --scope "/root" --sorting.by "name" --viewMode "list" --auth.method "json"
#
"/usr/local/filebrowser/usr/filebrowser" --database "/usr/local/filebrowser/etc/database.db" users add "user01" "userpasswd"
```

**What is happening instead?**

The code above works well for **v2.21.1 and earlier**. Beginning from **v2.22.0 to v2.23.0**, it prompts

```
2022/12/23 21:59:06 failed to create user home dir: [/root]: mkdir /root: file does not exist
```

As a result, I can't log into filebrowser using "user01" and its password "userpasswd". It just prompts "Wrong credentials".

**Additional context**

If I remove the argument `--scope "/root"`, I can create user "user01" successfully. But if I set the user scope to `/root` from the web-end after I logged in, it will prompt "This location can't be reached.".

**Comment by JACK-THINK** [comment]
@o1egl 

Is there any plan to fix this bug? Thanks.

**Comment by dchandekstark** [comment]
It appears that, at some point, the behavior of scope changed -- at least if it was defined as an absolute path. If I set root to /data and scope to /data, FB now looks for /data/data.
