### ISSUE TITLE
i can't use nginx for filebrowser,how can i config?

### ISSUE THREAD

**Issue by Victor9578** [filebrowser/filebrowser#2266]
**Description**

Filebrowser 2.23
when i copy this conf,i can't visit my filebrowser website
already set BaseUrl : **/file** 
i can use my phone that run filebrowser server visit 127.0.0.1/file,is ok
but when by the computer ,visit http://MyPhoneIp/file , The website will keep loading (three dot)

> this nginx.conf
```

location /file {
         proxy_pass http://localhost:8080;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_cache_bypass $http_upgrade;
         proxy_set_header Host $http_host;
}
```
---
```
Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:

Branding:
  Name:
  Files override:
  Disable external links:  false
  Color:

Server:
  Log:           stdout
  Port:          8080
  Base URL:      /file
  Root:          /
  Socket:
  Address:       0.0.0.0
  TLS Cert:
  TLS Key:
  Exec Enabled:  false

Defaults:
  Scope:         .
  Locale:        en
  View mode:     list
  Single Click:  false
  Commands:
  Sorting:
    By:   name
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}

```

On the Computer ,chrome F12,
can see **chunk-vendors.js** , is fail load
![image](https://user-images.githubusercontent.com/45564367/209475614-d7b7c279-5e34-4202-9a82-08a46f9def01.png)

**Expected behaviour**

use Lan visit and manage file
**What is happening instead?**

**Additional context**

**How to reproduce?**

filebrowser 2.23 aarch64
nginx the same conf

**Files**

**Comment by Victor9578** [comment]
ok.i reinstall filebrowser that use the script of official website ,everything is Ok.nice!

**Comment by Victor9578** [comment]
if you have INCOMPLETE_CHUNKED_ENCODING err,
```
proxy_buffer_size 1024k;
proxy_buffers 16 1024k;
proxy_busy_buffers_size 2048k;
proxy_temp_file_write_size 2048k;
```
add in you `.conf` , it's the reason that temp is small

**Comment by ianhundere** [comment]
^ this was exactly what i needed. thank you @Victor9578
