### ISSUE TITLE
Is there any option to disable redirects (make them proper 404) if they do not reach baseurl

### ISSUE THREAD

**Issue by mamolli** [filebrowser/filebrowser#2269]
**Is your feature request related to a problem? Please describe.**
I am trying to run --noauth option but I do not want for filebrowser to be easily accessible. Thus I can generate a guid and run filebrowser on this custom basepath. Private enough for me.

**Describe the solution you'd like**
Generally any option (flag or config setting) to not have the UI popping at root path(due to redirect) just make it 404 if user has not entered correct basepath.

**Comment by mamolli** [comment]
So I went with settings this up via reverse proxy. (namely caddy)

**Comment by sncfsamy** [comment]
"baseURL" doesnt work. Many and many try but never take in account by the filebrowser server...
