### ISSUE TITLE
404 page returns status 200

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#227]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes; shortly after the 0.10.7 release.

### 2. What is your entire Caddyfile?
```text
example.com {
	filemanager	/	/home/web/example.com {
		database	id.db
	}
	header		/	-Server
	log		/home/web/example.com/caddy.log
	timeouts	none
	tls {
		dns	route53
	}
}
```

### 3. What are you trying to do?

Inspect response headers.

### 4. What did you expect to see?

A response status of 404

### 5. What did you see instead (give full error messages and/or log)?

A response status of 200

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

1. Get a permanent link for a file
2. Delete the permanent link
3. Visit the now defunct link
4. Note the log: e.g. `..."GET /share/id HTTP/2.0" 200...`
5. Note the response body: "404 Not Found"

**Comment by hacdias** [comment]
Thanks for reporting 😉
