### ISSUE TITLE
Allow admins to set global CSS

### ISSUE THREAD

**Issue by francislavoie** [filebrowser/filebrowser#228]
Original title: Login screen doesn't use custom CSS

While messing around with custom CSS (see https://github.com/hacdias/filemanager/issues/208#issuecomment-326781640), I noticed that the login screen doesn't have the CSS loaded. It only loads once logged in.

If you log out after having logged in, because of the SPA architecture, the login page is then styled afterwards 😆

I'd like it if I could style that page so I can have my dark theme all the way through and not only once logged in.

**Comment by hacdias** [comment]
Hmm... The custom style is **user scoped**, I mean, it's a setting for each user. Technically, the login page is not supposed to get customized since the user hasn't logged in yet.

> If you log out after having logged in, because of the SPA architecture, the login page is then styled afterwards 😆

I can fix this though.

---

What would you suggest since the custom CSS is per-user?

**Comment by francislavoie** [comment]
Oh - I was under the impression that was global CSS.

Well, how about allowing admins to set global CSS? 😛

**Comment by hacdias** [comment]
That's probably a good idea. I'll think of it 😄

**Comment by francislavoie** [comment]
Awesome. I'm excited to try it! :smile:

**Comment by hacdias** [comment]
I'll will be available with 1.3.2!
