### ISSUE TITLE
Play MKV video, no sound

### ISSUE THREAD

**Issue by a545254328** [filebrowser/filebrowser#2287]

**Comment by tarokeitaro** [comment]
> _No description provided._

MKV is media container, I think your browser doesn't support that sound format, so only video can be played by browser.

**Comment by a545254328** [comment]
> > _沒有提供說明。_
> 
> MKV是媒體容器，我想你的瀏覽器不支持那種聲音格式，所以瀏覽器只能播放視頻。

chrome 108.0.5359.125    MKV  X264  X265    no sound

Microsoft Edge 108.0.1462.76  MKV  X265   no sound

**Comment by langren1353** [comment]
kmv视频很多需要解码器，filebrowser主要还是作为一个文件管理的工具，做不到这么详尽的功能，未来可能还行，暂时肯定是没有这方面的计划的
如果你有这方面的需要，建议使用webdav来试试

**Comment by evrial** [comment]
A52 audio aka AC3 and DTS audio - not supported in Chrome
MPEG AAC audio (mp4a) - supported
Chrome plays first supported audio track in MKV, no switching and subtitles
List of supported containers and video/audio codecs here + HEVC/H.265 video recently
https://support.google.com/chromebook/answer/183093?hl=en&sjid=5104586974388833944-EU#zippy=%2Ccodecs
