### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Sharkkkk** [filebrowser/filebrowser#229]
Very enjoy your program.It is splendidly and easy to use. 
Now, I want to provide some suggestion to help it better.
1.May be you can add a function using the rar to compress the film. I think the function is sample but very useful.
2.I think using Axel in the web to help user download file more easy is a good idea.

**Comment by hacdias** [comment]
Hello @Sharkkkk! Thanks for the feedback and the suggestions.

1. RAR is a proprietary archive format and thus it can only be created using WinRAR or other tools from their company. That way, I can't add a RAR compression.
2. What is Axel?

😄

**Comment by Sharkkkk** [comment]
7z is ok. I only mean it can add a compress online function and a Multi-threaded download function......axel is Multi-threaded download in ubuntu....

**Comment by hacdias** [comment]
There is no Go library to compress or decompress 7zip files either. Sorry for that. But we have a lot of formats available!

Axel is [this](http://manpages.ubuntu.com/manpages/trusty/man1/axel.1.html), right? If so, it's a command line utility. I can't really use Axel on the browser.

**Comment by Sharkkkk** [comment]
I wrong to think that it can execute command line on the web。。。

**Comment by Sharkkkk** [comment]
Uh，my English is no very good. Let me give an example. Now , I have a file call 123.rar and it need a passward to decompress. So , I add a command unar and run `unar -p xxx 123.rar`  in search box to decompress 123.rar. But ,every time I want to decompress a file. I need to write again.....You know it is cumbersome to use... Could you add a function to run it more easy? So we don't need to write the command every time...some useful command like rar unar axel.....

**Comment by hacdias** [comment]
I could create custom button such as it was suggested in #127 but the interface would get a bit cluttered if you added too many custom buttons.

You can also create an alias on Linux for that command and you'd only need to run one command. Did you try it? 😄

**Comment by Sharkkkk** [comment]
Could you get an example for me? I am a beginner in Linux.  I don't quite understand what you mean...

**Comment by hacdias** [comment]
You could create a script such as `mycommand`:

```
#!/bin/bash
unar -p xxx 123.rar
```

Then run `chmod +x mycommand` and add the file to the `$PATH`. Then, you could run the command `mycommand` from anywhere you wanted.

`mycommand` would be a shortcut to `unar -p xxx 123.rar`.

**Comment by Sharkkkk** [comment]
Thank you

**Comment by hacdias** [comment]
Tell me if it worked so I can close the issue, please.

**Comment by Sharkkkk** [comment]
It is a good way to solve this problem. But, you konw different files may have different password and the terminal in the web is not very eary to run more one command....
I am recommand a program to you and I hope we can use the same function in your filemanager oneday.
https://github.com/genshen/sshWebConsole

**Comment by hacdias** [comment]
File Manager wasn't made to be a terminal on web. It's just a file manager. The addition of some commands is just a way to let users run some tools such as unrar.

I thank you for the suggestion of using sshWebConsole but I will not implement it. If you need ssh, you can use ssh with your terminal. A Web Console could be a security hole and once again, File Manager wasn't made for it.

Sorry for this, but the best is to run the command for every different file.
