### ISSUE TITLE
Symlinks do not search.

### ISSUE THREAD

**Issue by L0garithmic** [filebrowser/filebrowser#2295]
I was wanting the ability to add in multiple directories, but since FileBrowser does not have this extremely important function, I resorted to using symbolic links. However the search function does not seem to index the symlinks. Can this please be addressed?

I have tested this using SymLinks and Junctions. I am on Windows 11.

I would literally pay for either Symlinks search working, or the ability to add multiple directories. 
100% serious. DM me on Telegram @wulfs to talk

**Comment by L0garithmic** [comment]
Still checking daily on this. Still dead serious.

**Comment by L0garithmic** [comment]
Still here daily.. 🤷🏼‍♂️

**Comment by L0garithmic** [comment]
![Checking in!](https://media3.giphy.com/media/p3uZvqib1ewP6qTqch/200w.gif?cid=6c09b9527dmpmrlhrlytnuynkc1m4v6nvjd2wxn3sg1ks4iz&rid=200w.gif&ct=g)

**Comment by L0garithmic** [comment]
Can't wait to hear back about this 🤗

**Comment by L0garithmic** [comment]
It's a me! Mario! lol

**Comment by L0garithmic** [comment]
Still here waiting!

**Comment by L0garithmic** [comment]
Huzzah..

**Comment by L0garithmic** [comment]
Hey! It's me again!

**Comment by L0garithmic** [comment]
Refusing to let this die!

**Comment by MrChinR** [comment]
I have the same problem.

**Comment by L0garithmic** [comment]
Bump
