### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by marcel293** [filebrowser/filebrowser#2299]
I can not login at the frontend anymore. (admin/admin) I tried to reset/change the password or to add an additional user.

**Steps I did - change pw:**

> systemctl stop filebrowser.service
> filebrowser users update admin --password _newpassword_
> systemctl start filebrowser.service

**Steps I did - new user:**

> systemctl stop filebrowser.service
> filebrowser users add test test
> systemctl start filebrowser.service

Error Frontend: Wrong acess data (translated - ger: Falsche Zugangsdaten)

I can see the user in the terminal, but can not login.

![filebrowser](https://user-images.githubusercontent.com/45700575/212080761-edd83cd5-030d-4ab7-a908-2bde6dd21932.jpg)

![login](https://user-images.githubusercontent.com/45700575/212081378-b9be2571-90a1-4206-98a7-5319a37d845e.jpg)

Thx for support

**Comment by marcel293** [comment]
My solution: I deleted the filebrowser.db

**Comment by CharlesDerek** [comment]
> My solution: I deleted the filebrowser.db

For some reason that didn't help reset the password. and i keep getting:
```
$ filebrowser users update admin --password newpassword
```
```
 [timestamp] the resource does not exist
 ```
