### ISSUE TITLE
root directive doesn't used

### ISSUE THREAD

**Issue by adzeitor** [filebrowser/filebrowser#23]
Hi! It's again me ;)

I have this config `/home/toor/www/Caddyfile` ( `pwd` used here to show problem, original config have `command hugo`): 

``` yaml
localhost {
  root ./blog
  cms {
    content public
    command pwd
  }
}
```

I've expected to see `/home/toor/www/blog/`, but 

``` bash
$ caddy -conf=Caddyfile 
/home/toor/www
localhost:2015
```

But running caddy from `blog` directory let it works like a charm...

I think you need to set current working dir before Run:  https://golang.org/pkg/os/exec/#Command

**Comment by adzeitor** [comment]
But `root` directive sets current dir for serving content, not for running external apps... Maybe @mholt give us a hint.

**Comment by mholt** [comment]
No, that makes sense. If the site is at /home/toor/www, the hugo commands probably need to be run from that directory (or somewhere around there).

**Comment by hacdias** [comment]
Caddyfile should be placed where the Hugo files are placed. The `root` is the content served and `content` is what's probably causing the main problem. This directive is used to know which folder contains the main content, the markdown files. It will only affect the links, nothing else.

**Comment by hacdias** [comment]
It's not that clear in the docs, sorry. I'll change it as soon as I can. Let me know if this was the misunderstanding or if it's something else.

**Comment by adzeitor** [comment]
Currently there is no way to have more than one cms with one caddy file, because users from each cms can modify files of other:

``` yaml
0.0.0.0:8001 {
  root ./blog1/public
  cms {
   content blog1/public
   command hugo
   args -s blog1/
  }
}

0.0.0.0:8002 {
  root ./blog2/public
  cms {
   content blog2/public
   command hugo
   args -s blog2/
  }
}
```

**Comment by hacdias** [comment]
Oh... I see. What do you want is to have a a directive where you put the path of the "static-generator-content-things" and it runs there, isn't it? I could (or even you!) create that, it could be optional. You do you think?

**Comment by adzeitor** [comment]
> Oh... I see. What do you want is to have a a directive where you put the path of the "static-generator-content-things" and it runs there, isn't it?

maybe, but this makes things complicated: root, workdir, content (not very useful) ...

[search plugin](https://caddyserver.com/docs/search) use `search [directory] endpoint { ... }`

> directory is a path within the site (can be a regular expression) that should be indexed. Default is site root.

git plugin also use similar thing. Anyway current dir for executing could be **root** or **user defined**, but not a caddy running directory.

**Comment by hacdias** [comment]
@adzeitor it can't be root because those are the served files. What do you suggest?

**Comment by hacdias** [comment]
Oh... I figured out that `content` is always the same as `root`. So, I can remove `content` variable and add `workdir` or something like that.

**Comment by adzeitor** [comment]
It can be root with [rewrite](https://caddyserver.com/docs/rewrite) :smile: 

I think it is better root than caddy workdir (if root is defined).

> What do you suggest?

This syntax inspired by git and search plugin for consistency:

``` yaml
root /home/toor/blog1/public
cms /home/toor/blog1/ {
  command ...
}
```

**Comment by hacdias** [comment]
So:

```
root [path/to/public/folder]
cms [path/to/execute/things] {
    styles  file
    command cmd
    args    args...
}
```

I'm thinking about merging command and args too. What do you think?

**Comment by adzeitor** [comment]
I like it.

> merging command and args too

Good because it works in the same way as [startup directive](https://caddyserver.com/docs/startup).

**Comment by hacdias** [comment]
I'm making the changes and I found out that there's a mistake here. content =/= public. Content is the folder where are the content files like pages and posts. Public is the generated HTML. So the content directive should be used.

**Comment by hacdias** [comment]
I'll update the docs to make that clearer.

**Comment by hacdias** [comment]
Try executing from source to see if is good!
