### ISSUE TITLE
Streaming movie or sending raw file could use X-Accel-File or X-SendFile

### ISSUE THREAD

**Issue by murlock** [filebrowser/filebrowser#230]
I'm using Filemanager + Caddy behind nginx (for logs and authentification).

When I open a video, Caddy and Nginx use lot of CPU (it's an Atom server) to stream file.
Starting a video or seeking is slow, even for small video.
Using Nginx for static file doesn't show this kind of issue.

With Caddy and Nginx:
It took 9500 ms to serve around 6 MB for first request on movie (not playing, only for `video` initialization)
With Nginx:
It took only 3500 ms for same amount of data (video preload=medata)

Is it possible to configure filemanager to use Nginx / Apache to serve static file (https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/) ?

**Comment by hacdias** [comment]
No, it is not possible to configure File Manager to use Nginx nor Apache to serve static files. The static files are served by Go standard library with [ServeFile](https://golang.org/pkg/net/http/#ServeFile) function.

What do you mean by `video preload=medata`?
