### ISSUE TITLE
Feature Request to Search OCR'ed PDF's

### ISSUE THREAD

**Issue by cjohnson46** [filebrowser/filebrowser#2302]
I would love to be able to use the search field to find words in my already OCR'ed PDF documents!  I also saw a discussion of users asking for it below.
(feature request] Search into files #1905) 

I have seen many github projects that have this feature.  I'm assuming one of them has an implementation of it that would work with your current program.  I currently use [Paperless-NGX](https://github.com/paperless-ngx/paperless-ngx) that has this feature.  I believe it is possible in [Papermerge](https://github.com/ciur/papermerge) as well.  They also highlight the searched text inside of the document which is great, but I don't want to press my luck!

I love the program and hope you can consider our feature request.  I'm open for starting a bounty if anyone is in!!

**Comment by Androz2091** [comment]
so sad
