### ISSUE TITLE
Document the public API endpoints exposed by filebrowser (download/upload?)

### ISSUE THREAD

**Issue by aallrd** [filebrowser/filebrowser#2309]
Hello,

It seems that `filebrowser` exposes a public API, but I could not find any documentation about it.
```
http://filebrowser:8080/api/raw/file.txt?auth=XXX
```
I would be interested to read about the the API endpoints to download/upload files (if they exist).

**Comment by liam8888999** [comment]
I'm interested in this too

**Comment by monkiki** [comment]
Any update on this?

**Comment by mrbodich** [comment]
I am very interested in this feature too.

**Comment by Xuzan9396** [comment]
auth @aallrd
func Test_withUser(t *testing.T) {
	// 替换key
	//./filebrowser config export config.json

	claims := &authToken{
		User: userInfo{
			ID:          1,
			Locale:      "zh-cn",
			ViewMode:    "mosaic",
			SingleClick: false,
			Perm: users.Permissions{
				Admin:    true,
				Execute:  true,
				Create:   true,
				Rename:   true,
				Modify:   true,
				Delete:   true,
				Share:    true,
				Download: true,
			},
			LockPassword: false,
			Commands:     []string{},
			HideDotfiles: false,
			DateFormat:   false,
		},
		RegisteredClaims: jwt.RegisteredClaims{
			IssuedAt:  jwt.NewNumericDate(time.Now()),
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(time.Hour * 24 * 365 * 10)),
			Issuer:    "File Browser",
		},
	}
	str, _ := php2go.Base64Decode("edit，setting.key(./filebrowser config export config.json)")
	log.Println(str)
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString([]byte(str))
	if err != nil {
		t.Fatal(err)
	}
	t.Log(signed)
}
