### ISSUE TITLE
When I try to upload and replace a file, there is an error: 409.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#231]
When I try to upload and replace a file, there is an error: 409.
The error is only one figure: 409.
Any file will be wrong.
I have just updated the latest version.
The previous version without this error.

**Comment by hacdias** [comment]
Oh! I presume you downloaded via Caddy. I forgot to release the newest release there. It will probably be fixed in ~20 mins.

**Comment by ghost** [comment]
Ok, already can be used normally!
