### ISSUE TITLE
Page title gets longer with each change of sorting

### ISSUE THREAD

**Issue by otbutz** [filebrowser/filebrowser#2325]
**Description**

Each time the sorting of the table is changed, the servername is prepended to the existing tile.

Initial title:

![grafik](https://user-images.githubusercontent.com/22315436/216054006-1996e2ab-788b-43a2-b40d-7af0aa920f2f.png)

![grafik](https://user-images.githubusercontent.com/22315436/216054281-592cb18a-a3c6-4dda-ac40-30f0e7f98f77.png)

1x toggle:

![grafik](https://user-images.githubusercontent.com/22315436/216054103-ed115a7a-846b-485b-824f-4af04306b819.png)

2x toggle:

![grafik](https://user-images.githubusercontent.com/22315436/216054158-9a05719d-5e20-454e-8a17-fa2491c7b337.png)

**How to reproduce?**

Open the UI and click change the sorting of the table multiple times.

File Browser version: 2.23.0

**Comment by baur** [comment]
Yes I confirm 

![image](https://user-images.githubusercontent.com/2898361/216520052-1acde6df-eaed-44d5-82d9-e6fd729890fb.png)

**Comment by baur** [comment]
any suggestions?

**Comment by otbutz** [comment]
Still relevant

**Comment by baur** [comment]
any news?

**Comment by otbutz** [comment]
Ping

**Comment by baur** [comment]
any news?

**Comment by otbutz** [comment]
Ping

**Comment by otbutz** [comment]
Ping

**Comment by bt90** [comment]
Fixed by #3200
