### ISSUE TITLE
Branding: logo.svg not affects

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2329]
**Description**

custom.css affects well but logo.svg not works

![image](https://user-images.githubusercontent.com/2898361/216518146-63a18084-940f-486a-b8ea-379e5e2dfaf0.png)

**Expected behaviour**

custom logo.svg

**What is happening instead?**

custom logo.svg not affects

![image](https://user-images.githubusercontent.com/2898361/216518808-5fb3b22d-bb1f-4a8c-a5b4-a9438d5f1c09.png)

but a custom logo.svg not loaded

![image](https://user-images.githubusercontent.com/2898361/216518934-99a2245e-9286-4f72-89c8-1a691cab71cf.png)

**Additional context**

custom.css affects well

**Comment by baur** [comment]
Affected after day, logo.svg was cached
Thank you!!!

**Comment by nmincone** [comment]
Is it possible to control the size of the logo on the login page?
Currently my logo looks great after logging in on the top left, but on the login page it's very small.
