### ISSUE TITLE
Allow users to signup and Hook authentication method

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2330]
**Description**

**Expected behaviour**

With unchecked option *Allow users to signup*

![image](https://user-images.githubusercontent.com/2898361/216595174-eb8d433c-9c8c-4909-927e-c49d9bc2162e.png)

Passed users with the hook authentication method should get like this message "You are not authorized to access this application", because I'm not allowed to signup

**What is happening instead?**

All passed users with the hook authentication registered with the system

**Comment by baur** [comment]
any suggestions?

**Comment by SilverSong3** [comment]
What does your setup include? I'm not sure what the expected behavior should be, but I'm looking to get to the point where users are created and preferably synced with a more robust authentication manager. Do you use Docker or have it installed locally?
