### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by Roo7K1d** [filebrowser/filebrowser#2334]
**Description**
I am trying to install filebrowser. It all works great via the local network. But i wanted to use it (the docker image) behind a reverse proxy. I had another issue before (see issue #226) but i managed to fix that already. Now i get this error:

![image](https://user-images.githubusercontent.com/47664151/217610531-94b9fbb9-04f3-43e5-a29b-af8917a7ba73.png)

![image](https://user-images.githubusercontent.com/47664151/217610986-f35a98e0-f5f3-421b-a551-92b79e05bc20.png)

It looks like there is HTML code in the app.js which of course does not work.

And i all i permanently see is this:

![image](https://user-images.githubusercontent.com/47664151/217610633-9928feaa-b8aa-4d0b-80e1-5f78b827e307.png)

**Expected behaviour**
No errors. See the login page.

**What is happening instead?**
See screenshot above

**Comment by bonnebulle** [comment]
Hello
I just have the same error 
: server-side error / security CORS
( works now  using Nginx proxy )

...
I dont know if this can help : 
...

- Create a fresh filebrowser.db
```bash
touch /MY_CONFIG_PATH/filebrowser.db
```

- Please check settings.json
: https://github.com/filebrowser/filebrowser/blob/master/docker/root/defaults/settings.json
( find it from : https://filebrowser.org/installation ) 
( using it at it is )


- And if use Nginx configuration 
( + certbot for https )


```
server {
    if ($host = MY_DOMAIN.xyz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen              8080;
    listen              80;
    server_name MY_DOMAIN.xyz;
}

server {
        server_name MY_DOMAIN.xyz;
        listen [::]:443 ssl http2;
        listen 443 ssl http2;
        location / {
                proxy_pass http://0.0.0.0:MY_PORT;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

    ssl_certificate /etc/letsencrypt/live/MY_DOMAIN.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/MY_DOMAIN.xyz/privkey.pem; # managed by Certbot
}
```

- Docker running :
```bash
docker run \
    -v /MY_FILES_PATH/:/srv \
    -v /MY_CONFIG_PATH/filebrowser.db:/database/filebrowser.db \
    -v /MY_CONFIG_PATH/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -p MY_PORT:80 \
    filebrowser/filebrowser:s6
```

NB: I dont use 80 port (in host machine) because already in use...
