### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Siam-Islam** [filebrowser/filebrowser#2337]
when am trying to rename or upload a file 403 forbidden message is showing.I  am using filebrowser with nginx.

**Comment by StanislavJochman** [comment]
Are you using Cloudflare? If so it has upload limit 100mb. Should be fixed when [TUS](https://github.com/filebrowser/filebrowser/pull/2145) will be implemented.

**Comment by chomoe327** [comment]
我也遇到了这个问题，我上传的是一个只有1.9M的压缩文件，然后我把服务器的对应文件夹的权限更改之后就可以正常上传了
<img width="441" alt="image" src="https://user-images.githubusercontent.com/71968682/233248158-d8084e2d-64fe-4adc-8714-ed5a60df77b9.png">
