### ISSUE TITLE
Download filename with spaces

### ISSUE THREAD

**Issue by rigon** [filebrowser/filebrowser#234]
When a file (or a packed folder) name contains a space, the downloaded filename just contains the first word.

**Comment by hacdias** [comment]
Thanks 😄

**Comment by hacdias** [comment]
@rigon I'm not being able to reproduce this. The files are downloading with the full name here.

![image](https://user-images.githubusercontent.com/5447088/30155186-0b157408-93b4-11e7-8caa-be658cfe99f7.png)

**Comment by rigon** [comment]
It seems to be a a problem with Firefox (I'm using 55.0.3 (64-bit)). I tested on Chromium and works perfectly. Here is a screenshot of the problem:

![image](https://user-images.githubusercontent.com/1102280/30159430-75c80a98-93c0-11e7-8575-27cc7de9551c.png)

**Comment by hacdias** [comment]
I'll try with the FF version I've installed.

**Edit**: found an answer: https://stackoverflow.com/questions/21442903/firefox-has-problems-when-downloading-with-a-space-in-filename
