### ISSUE TITLE
[HELP] Where is the log ?

### ISSUE THREAD

**Issue by fana13** [filebrowser/filebrowser#2343]
2.23.0 version 
Debian OS

I want to find some informations (file downloaded by example) into the log file.
By default, default.json log config is "stdout"
Modify this by "/var/log/filebrowser" and restart service.
No log file created.
Could you help to find the right configuration for ?
Thanks

**Comment by Rhythm-2019** [comment]
Hi.
After testing that the log can be output to a file, I think it is likely that the configuration file was not loaded successfully when you started the program.

The name of the configuration file must end with ` .filebrowser` to be read, e,g `config.filebrowser` when running without providing any startup parameters.
You can also specify configuration files like this `./filebrowser config-file-name`

Refer to the following code (cmd/root.go)
```go
func initConfig() {
	if cfgFile == "" {
		home, err := homedir.Dir()
		checkErr(err)
		v.AddConfigPath(".")
		v.AddConfigPath(home)
		v.AddConfigPath("/etc/filebrowser/")
		v.SetConfigName(".filebrowser")
	} else {
		v.SetConfigFile(cfgFile)
	}

	v.SetEnvPrefix("FB")
	v.AutomaticEnv()
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))

	if err := v.ReadInConfig(); err != nil {
		if _, ok := err.(v.ConfigParseError); ok {
			panic(err)
		}
		cfgFile = "No config file used"
	} else {
		cfgFile = "Using config file: " + v.ConfigFileUsed()
	}
}

```



If the above answer does not help you, you can provide the log output of stdout and the content of your configuration file

**Comment by fana13** [comment]
Hi,
Thanks for your reply but I don't how fill this config file to have a full log file.
If you have any example ?
I never find the way to display the content of log file when is declared as stdout

**Comment by Rhythm-2019** [comment]
@fana13 HI, here are my steps:

* clone project
* run `go mod download`
* run `go buikd`
* create file `.filebrowser.json`,
 ```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "./filebrowser.log",
  "database": "/database.db",
  "root": "/srv"
}
```
* run `.filebrowser `
* get log file `filebrowser.log`
```
2023/02/22 00:33:10 Listening on [::]:80
2023/02/22 00:34:15 Caught signal interrupt: shutting down.
2023/02/22 00:34:16 Listening on [::]:80
2023/02/22 01:08:27 Caught signal terminated: shutting down.
2023/02/23 21:59:13 Listening on [::]:80
2023/02/23 22:01:41 /login: 500 ::1 open index.html: file does not exist
2023/02/23 22:01:41 /favicon.ico: 500 ::1 open index.html: file does not exist
2023/02/23 22:02:53 /resources: 500 ::1 open index.html: file does not exist
2023/02/23 22:02:53 /favicon.ico: 500 ::1 open index.html: file does not exist
2023/02/23 22:03:48 /resources//api/resources: 500 ::1 open index.html: file does not exist
2023/02/23 22:03:48 /favicon.ico: 500 ::1 open index.html: file does not exist
```
Hope it helps you, can you provide your configuration file, configuration file name, binary version and startup command?

**Comment by fana13** [comment]
Thanks again.
Log file is making good but  doesn't contain enough informations.
There's only that : 
`2023/02/23 17:47:30 Listening on [::]:8080
`
I want to find much more data, like folder making, files downloaded, etc...

**Comment by Rhythm-2019** [comment]
@fana13 It's a bit strange, do you have no logs when you access any API interface?

**Comment by csrado** [comment]
Hi,
same issue at Ubuntu 22.04, File Browser 2.23.0

I see in log file only 2023/09/18 18:10:28 Listening on ....

**Comment by eliemada** [comment]
Bump ! 
I am using a docker image for a server, i clearly see what is wrong in settings.json we need to change stdout to /database/filebrowser.log for example but then what ? 
Please

**Comment by O2F** [comment]
Hey @eliemada,

I'm not sure if you already solved it, if not I will leave here how you can solve it if you're using docker compose to launch the container. (or using the docker volumes "-v" using the docker run)

As @Rhythm-2019 already provided and already understood by you, you need to add the path to the log in the settings file, after that you need to expose that path to the host machine by using a docker volume.

Example:

Considering the following filebrowser settings:

```json
{
 "port": 80,
 "baseURL": "",
 "address": "",
 "log": "/log/filebrowser.log",
 "database": "/database/filebrowser.db",
 "root": "/srv"
}
```


you can expose the following volumes.

```sh
volumes:
       - /path/on/host/to/filebrowser_config/database:/database
       - /path/on/host/to/filebrowser_config/config:/config
       - /path/on/host/to/filebrowser_config/log:/log
```

After that you can see the log on your host machine in the path: `/path/on/host/to/filebrowser_config/log/filebrowser.log`

Hope it helps.

**Comment by gilly65** [comment]
I have done this and am also only getting, Listening on [::]:80
Is there not a better log system? 
I would prefer to see who is accessing this, or even trying to, as well as uploaded and downloaded files.

**Comment by ash34** [comment]
This issue needs to be reopened. I also want to log http traffic to see uploads and downloads.
