### ISSUE TITLE
FR: Compact List View

### ISSUE THREAD

**Issue by Andrew-H2O** [filebrowser/filebrowser#2346]
**Is your feature request related to a problem? Please describe.**

The current list view only shows about 12 files or folders onscreen, with a lot of spacing between them.  This is on a 1920 x 1080 desktop display.
Because of this, I need to do more scrolling in folders with a lot of files.

**Describe the solution you'd like**

A 'compact list view' option, displaying maybe twice as many rows onscreen as the current one.

**Describe alternatives you've considered**

**Additional context**

**Comment by Lettumika** [comment]
I'd like that also.

**Comment by xiaoqi951109** [comment]
I'd like that also.  +1    
simple info  is enough。

**Comment by Andrew-H2O** [comment]
I’d still like to see this implemented.

**Comment by Andrew-H2O** [comment]
I’d still like to see this implemented.

**Comment by Andrew-H2O** [comment]
.

**Comment by Maurits2014** [comment]
That would be very helpful. I have some large folders that right now take quite some time to scroll through.

**Comment by Andrew-H2O** [comment]
Looks like there's at least 4 people who'd like this - maybe it can be considered?

**Comment by gtsteffaniak** [comment]
There is a [compact view mode](https://private-user-images.githubusercontent.com/42989099/275902634-c76f4100-949b-4e17-a3e6-e410fb8ec08f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzk4NDUsIm5iZiI6MTcwNzEzOTU0NSwicGF0aCI6Ii80Mjk4OTA5OS8yNzU5MDI2MzQtYzc2ZjQxMDAtOTQ5Yi00ZTE3LWEzZTYtZTQxMGZiOGVjMDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzMjU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmYzZGRlZjY0ODdiN2E4M2ViNDc0ZmNjZjU3NWE0ZWM0Y2YxY2QyNmMxYTNlOTVkYjRjYzliNjI3ZDMwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b7siETXYkWx68iNZ0MoDwXi3sP9mDXo4__cXojd9F7s) on my fork here:
https://github.com/gtsteffaniak/filebrowser

**Comment by Andrew-H2O** [comment]
Just commenting to get ahead of the "This issue is stale" bot.  Still hoping to have this feature implemented.

**Comment by Andrew-H2O** [comment]
Comment

**Comment by Andrew-H2O** [comment]
:-(

**Comment by Andrew-H2O** [comment]
.

**Comment by Andrew-H2O** [comment]
:-(

**Comment by Andrew-H2O** [comment]
Happy almost-first birthday potentially useful feature.

**Comment by gtsteffaniak** [comment]
This is not a priority for the devs, just let this close as stale. It took me 30 minutes to implement on my fork 6 months ago. 

https://github.com/gtsteffaniak/filebrowser

**Comment by ShlomoCode** [comment]
> This is not a priority for the devs, just let this close as stale. It took me 30 minutes to implement on my fork 6 months ago.

So why not do a PR? I see that PRs of the frontend are merged regularly.
