### ISSUE TITLE
Download while packing a folder

### ISSUE THREAD

**Issue by rigon** [filebrowser/filebrowser#235]
When we download a packed folder, we have to wait while the sever creates the archive. It is possible to start downloading the archive while the server is still compressing, depending on the format. At least with ZIP is possible to do.

**Comment by hacdias** [comment]
Hey! Currently I'm using [this](https://godoc.org/github.com/mholt/archiver) library and I can't do that now with it so I'll close this for now. If more people ask for this, I'll consider it. 

Although, if you really want this, you could try to do it and make a PR 😃

**Comment by rigon** [comment]
Yeah, good! It easy to ask (as we say "mandar bitaites"), but when we have to implement is another story :P

**Comment by hacdias** [comment]
Lol 😂
