### ISSUE TITLE
New users directely gets into / folder in new version

### ISSUE THREAD

**Issue by Llesue** [filebrowser/filebrowser#2350]
**"Base path for user home directories"** doesn't work anymore.
New users directely gets into` / ` directory. 
Since the latest version.
Not creating user folders for new users.

**Comment by QForever** [comment]
Yes, I also found that this problem is very serious ah, after the open registration function, anyone can directly get all the files, hope this problem can be fixed as soon as possible.

**Comment by pazport** [comment]
i am having this problem also. could we not lock them into there user dir. but also give them access to other locations if we allow it.

**Comment by Llesue** [comment]
> i am having this problem also. could we not lock them into there user dir. but also give them access to other locations if we allow it.

I do that by making soft link in their directory... Yes. It's a pretty dumb way. I think we can do creating soft link by command runner, But i don't know how the command runner work, I tried few times and failed.

**Comment by yourjhay** [comment]
Yeah. Same here . new users get access to root folder

**Comment by yourjhay** [comment]
@QForever @pazport @Llesue 
upon going through the code, the reason for this is you have ` . ` in the **User default settings > scope** field.
which is make this false: https://github.com/filebrowser/filebrowser/blob/master/settings/dir.go (line 24)

`
         if userScope == "" && s.CreateUserDir {
		username = cleanUsername(username)
		if username == "" || username == "-" || username == "." {
			log.Printf("create user: invalid user for home dir creation: [%s]", username)
			return "", errors.New("invalid user for home dir creation")
		}
		userScope = path.Join(s.UserHomeBasePath, username)
	}
`


**Leave** the user scope **blank** then it should create the user DIR upon signup :) cheers..

**Comment by pazport** [comment]
> @QForever @pazport @Llesue upon going through the code, the reason for this is you have `.` in the **User default settings > scope** field. which is make this false: https://github.com/filebrowser/filebrowser/blob/master/settings/dir.go (line 24)
> 
> `if userScope == "" && s.CreateUserDir { username = cleanUsername(username) if username == "" || username == "-" || username == "." { log.Printf("create user: invalid user for home dir creation: [%s]", username) return "", errors.New("invalid user for home dir creation") } userScope = path.Join(s.UserHomeBasePath, username) }`
> 
> **Leave** the user scope **blank** then it should create the user DIR upon signup :) cheers..

ye sorry for that. i have only just seen your reply. when i put a locatio e.g /opt/apps they only had access to that location. is it possible to give 1 user access to different locations?
