### ISSUE TITLE
Can't edit or upload PHP-Files

### ISSUE THREAD

**Issue by Cheatha** [filebrowser/filebrowser#2355]
**Description**
I'm running nginx with PHP enabled:

```
      server {
                listen 80 default_server;
                listen [::]:80 default_server;

                listen 443 default_server ssl;
                listen [::]:433 default_server ssl;

                ssl_certificate /etc/ssl/local-server.cert;
                ssl_certificate_key /etc/ssl/local-server.key;

                root /var/www/html;

                index index.html index.php;

                server_name _;

                location / {
                        try_files $uri $uri/ =404;
        }


        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }

   location /filebrowser {
                server_name_in_redirect off;
                proxy_set_header Host $host;
                proxy_set_header    X-Real-IP           $remote_addr;
                proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
                proxy_pass          http://127.0.0.1:8082;
        }

}
```

I cant' edit or upload php-files as long as PHP is included:

```
location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.4-fpm-usr100p1.sock;
        }
```
If I remove this block everything is working fine. But, as you might guess, PHP outside of `filebrowser` isn't working anymore.

**Expected behaviour**
I want to use nginx with PHP-FPM and Filebrowser in a subfolder at the same time

**What is happening instead?**
I can use either PHP but can't edit php files in filebrowser or I can't use PHP and can edit them.

**Additional context**
PHP is running with fastcgi

**How to reproduce?**
Let nginx send PHP to the fastcgi process and proxy_pass filebrowser via /filebrowser

**Files**

**Comment by Cheatha** [comment]
Well, that problem's really a showstopper, so please don't close.

**Comment by Cheatha** [comment]
I still need help fixing this.

**Comment by Cheatha** [comment]
I still need help fixing this.

**Comment by nycki93** [comment]
I also can't edit html files, instead filebrowser tries to open them as folders. I think it's confused because of rewrite rules maybe?

edit: yep, it was rewrite rules! check your apache config and make sure that you're not rewriting any urls used by filebrowser. if you remove extensions it'll get confused.

**Comment by miaadp** [comment]
If you did not received the answer,
Change 
`location /filebrowser {`
to
`location ^~ /filebrowser {`

Its a nginx thing, Read more detail [here](https://stackoverflow.com/questions/29212655/nginx-php-scripts-not-being-called-from-reverse-proxy)

**Comment by Cheatha** [comment]
Thank you very much, @miaadp! This solved my issue!
