### ISSUE TITLE
error "413 request entity too large" when upload file

### ISSUE THREAD

**Issue by kwe3hk** [filebrowser/filebrowser#2358]
Anyone knows how to release the file update size limit?
I am using the docker image Filebrowser 
many thanks.

**Comment by Rhythm-2019** [comment]
What is the size of the file you uploaded?

**Comment by StanislavJochman** [comment]
Hi, are you using cloudflare or something similar? This should be fixed using [TUS](https://github.com/filebrowser/filebrowser/pull/2145)
