### ISSUE TITLE
File renaming, cursor position.

### ISSUE THREAD

**Issue by Outpost739** [filebrowser/filebrowser#2364]
Renaming files could be improved, just by automatically placing the cursor behind (left of it) the extension period 
when renaming a file.

If you rename only one file no problem, but if you do it 30 times in a row, you feel the sting a bit.
That small addition would be great.

I found file browser to be a amazing addition to my web interfaces. I love it. Amazing work by the way. 
Thank you anyway.

**Comment by gingerbeardman** [comment]
Agreed.

Even better would be if it:
- selected the whole filename without the extension
- positioned the cursor at the end of that, just before the period

**Comment by Outpost739** [comment]
It is a pretty common feature among file managers. 
I hope it can be added to File Browser.

**Comment by gingerbeardman** [comment]
Bump

**Comment by gingerbeardman** [comment]
Sigh.

**Comment by gingerbeardman** [comment]
Nope
