### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by SRTigers98** [filebrowser/filebrowser#2369]
As an administrator, I want to be able to see who made changes to the files and when, so that any misuse can be tracked.

**Is your feature request related to a problem? Please describe.**
As administrator of the system I can't see which files were edited by which user.
If there was a misuse, I can't see which user was responsible.

**Describe the solution you'd like**
An audit log tracks the following events:
- File created / uploaded
- File edited
- File moved / renamed
- File deleted

The audit logs are part of the standard server logs.

**Describe alternatives you've considered**
The audit log is managed in a separate file and can be accessed by an administrator via the UI.

**Comment by SRTigers98** [comment]
It would be great if the pull request #2370 , which is still open, could be reviewed.

**Comment by KhaaL** [comment]
Any updates on this feature, considering a PR exist already with the suggested implementation? Or is the project abandoned?

**Comment by p3t3rp3pp3r** [comment]
This is a very useful feature for a great product like filebrowser, is there  no way to see the audit logger implemented?
