### ISSUE TITLE
[Pagination/Loading Issue]

### ISSUE THREAD

**Issue by sirxsniper** [filebrowser/filebrowser#2375]
**Description**
I got a folder with over 3000 files, when I try to load it is just remaining stuck

**Expected behaviour**
You should add something like 50 items/page

**What is happening instead?**
Getting an error like "Page could not load"

**How to reproduce?**
Just create a lot of files into a folder and try to load it.

**Files**
Most of the files are jpg/video files.

**Comment by alphonse-terrier** [comment]
I have the exact same issue. (with 12k files)
