### ISSUE TITLE
Optionally chunk uploads to under 100 MB (on Cloudflare-proxied instances)

### ISSUE THREAD

**Issue by Emojigit** [filebrowser/filebrowser#2378]
**Is your feature request related to a problem? Please describe.**
It's known that Cloudflare has set an upload limit to 100~500 MB (depends on the plan, in which Free is 100 MB), making the upload of medium-sized files impossible.

![image](https://user-images.githubusercontent.com/55009343/226083286-ee6edb7a-525d-4044-b4cd-1457f0136276.png)

**Describe the solution you'd like**
Chunk the upload requests to multiple small ones, then combine them on the server. This bypasses the limit while still putting the server under Cloudflare protection.

**Describe alternatives you've considered**
Obviously, the most straightforward alternative is to upgrade my Cloudflare plan and contact support to further raise the limit, but many users cannot afford the price (including me). Hence, a change in the server software is needed.

**Additional context**

**Comment by Bajec** [comment]
Are you sure it's Cloudflare's 100MB limit? I researched exactly that for a long time, everywhere I came across comments that this limit no longer exists and that the traffic is unlimited.

**Comment by StanislavJochman** [comment]
Yup it is cloudflare error. Solution is proposed here: https://github.com/filebrowser/filebrowser/pull/2145

**Comment by Emojigit** [comment]
Duplicated #2145
