### ISSUE TITLE
Just sharing about simple theming ✌🏼

### ISSUE THREAD

**Issue by tarokeitaro** [filebrowser/filebrowser#2379]
I've been using Filebrowser for almost 2 years, I really like it and tried to play around with custom.css a bit. This is the .css file that I have, you can try it.

https://pastebin.com/VqSWkpCB

![image](https://user-images.githubusercontent.com/42670754/226083657-b76f4fa2-8589-49d4-91be-b076f0ff50b7.png)
![image](https://user-images.githubusercontent.com/42670754/226083698-50120778-1792-496f-983a-febad6ca4062.png)
![image](https://user-images.githubusercontent.com/42670754/226083728-673db23e-efd8-4c2d-826a-cf3f3a75f4e4.png)

Make sure you have set up a custom branding directory.

If nothing changes, try doing this little thing.
- Open developer window (f12 key)
- Go to the Network tab
- Turn on Disable cache
![image](https://user-images.githubusercontent.com/42670754/226083940-7b550324-8d52-4386-a012-34d524952a15.png)

This will be useful if you want to make other changes to "Filebrowser"

**Comment by admintahuna** [comment]
may I know how you custom in global setting and the logo.png path??
