### ISSUE TITLE
File/folder creation with a slash (/) in it is not denied

### ISSUE THREAD

**Issue by gingerchicken** [filebrowser/filebrowser#2380]
**Description**

I added a directory name with a `/` in it, which triggered a server error.

**Expected behaviour**

I thought the front-end would have warned me that the file name was invalid rather than it causing an error.

**What is happening instead?**

`500 internal server error` message was displayed. Sometimes, it creates two folders instead of one, but the URL still shows as if it is one folder.

**Additional context**

![imagen](https://user-images.githubusercontent.com/32576907/226109093-bad4052d-b198-4bca-beab-23cd4d67f572.png)
![imagen](https://user-images.githubusercontent.com/32576907/226109110-3c61830e-843c-4b2a-bd71-928cf782934f.png)

**How to reproduce?**

Create a new directory with the name `foo / bar`

**Files**

**Comment by Emojigit** [comment]
Suggested title: "File/folder creation with a slash (/) in it is not denied"

**Comment by gingerchicken** [comment]
> Suggested title: "File/folder creation with a slash (/) in it is not denied"

Thank you!
