### ISSUE TITLE
Copying a symbolic link copies the real file

### ISSUE THREAD

**Issue by BHare1985** [filebrowser/filebrowser#2383]
**Description**
I made a soft symbolic link inside my filebrowser directory to a file outside the directory. Renaming and moving the symlink worked no issues, but when I made a copy of the symlink it copied the actual file over (1GB file over <1Kb symlink)

**Expected behaviour**
I expected it to make a copy of the symbolic link

**What is happening instead?**
It made a copy of the actual data

**Additional context**
Ubuntu 20.04.6 LTS File Browser v2.23.0/02db83c7

**How to reproduce?**
```
echo "I have data" >> ~/data.txt
ln -s  ~/data.txt ~/symlink.txt
filebrowser -r ~/
```
Open up filebrowser and then make a copy of `symlink.txt` and it will be called `symlink(1).txt`. Now view the directory using your shell and notice when running `ls -l` that it did not create a symlink.

**Files**
N/A

**Comment by Llesue** [comment]
Same issue. Hope it could fixed soon.

**Comment by superzjg** [comment]
I hope the symbolic link to display differently from the actual file.

**Comment by Llesue** [comment]
> I hope the symbolic link to display differently from the actual file.

Same hope

**Comment by BHare1985** [comment]
As far as I know this issue is still active, leaving a comment to un-mark it stale

**Comment by Llesue** [comment]
> As far as I know this issue is still active, leaving a comment to un-mark it stale

So sad seems this project is abandoned. No more any update and response since last year.

**Comment by BHare1985** [comment]
As far as I know this issue is still active, leaving a comment to un-mark it stale

**Comment by Jason-Young-AI** [comment]
It will download the symbolic link as a real file. Re-open.
