### ISSUE TITLE
Compile for old hardware

### ISSUE THREAD

**Issue by rigon** [filebrowser/filebrowser#239]
This is more a comment rather than an issue of filemanager.

### The story

I have my NAS server where I've installed filemanager: it is the best thing I could get, it is so awesome!
That PC is kind of old, it is the old good Pentium III 866MHz (from beginning of 2000), 256MB of RAM. Then I bought a couple of SATA PCI cards from eBay, plugged a bunch of hard-drives with SMART complaining and assembled everything in a RAID5 hopping I can still recover the data in case of disaster. In the end, I got a throughput around 6MB/s! And now, Filemanager is running on top of that.

But, Pentium III only have MMX and SSE instructions sets. The binary that is being produced in releases should be requiring SSE2 because I got the error `Illegal instruction` when I try to run it.

### The solution

I wrote a post about this issue, it can be found in [Compile Golang for 386 (Pentium MMX or later)](http://www.rigon.tk/documentation/compile-golang-386-mmx).

I ended up running alpine inside docker, install Go and compile filemanager there.

**Comment by hacdias** [comment]
Hey @rigon! That's quite an interesting story. Gladly you managed to make it work! Hope you have been enjoying it! I'll mark this as `help` since it might be useful for more people in the future 😄

**Comment by rigon** [comment]
I created a script on Gist that performs this task automatically:
[build-filemanager.sh](https://gist.github.com/rigon/7bd9a1ef23ad454c21b1405d8d51ef10)

**Comment by hacdias** [comment]
Cool! Might be useful for some people 😄
