### ISSUE TITLE
Unable to enable exec via UI or config

### ISSUE THREAD

**Issue by funkypenguin** [filebrowser/filebrowser#2393]
**Description**

I'm trying to allow a user a subset of commands on the underlying host / docker container running filebrowser. Despite my configuration, I've not been successful at either globally allowing exec, or allowing commands.

On MacOS, I installed the latest filebrowser with `brew`, and run `filebrowser` in a fresh directory. 

`filebrowser.db` was created.

Then I `^C`'d to exit, and ran `filebrowser config export .filebrowser.json` to export the config from the DB into a .json (is this how it's supposed to work?)

I edited the `.filebrowser.json`, and changed this line:

```json
"enableExec": false
```

to:

```json
"enableExec": true
```

I added `ls` as an allowed command, by running `filebrowser config set --commands ls`, and the output showed that (a) `enableExec` is still false, and (b) `ls` is added as a default allowed command:

```
Defaults:
  Scope:         .
  Locale:        en
  View mode:     list
  Single Click:  false
  Commands:      ls
```

I restarted filebrowser, and tried to execute the `ls` command, but the response is `Command not allowed`.

Every time I run `filebrowser config cat`, I see:

```
  Exec Enabled:  false
```

**Expected behaviour**

When `enableExec` is set to true in the config file, then exec should be enabled.

**What is happening instead?**

Setting `enableExec` to true in the config file seem to have no effect.

**Additional context**

I see the same issue on MacOS and on the docker image

**How to reproduce?**

Repeat the diagnosis I described above using the CLI (non-docker) version for brevity

**Files**

I'm on `File Browser v2.23.0/02db83c7`

**Comment by xeruf** [comment]
Not Stale

**Comment by funkypenguin** [comment]
OK, I've worked my way around this, as follows.

💡 Using `filebrowser config set --commands` seems to only affect newly-created users, **not** existing users, even if that user is `admin`

So, this works:

```
         filebrowser config init --auth.method=noauth

        # allow zip, unzip, rar, unrar, ls, pwd, cd, mv
        filebrowser config set --commands zip,unzip,ls,bash
        filebrowser config set --shell 'bash -c'

        filebrowser users add 1 bogus
```

Note that if I want commands to be executed using `bash -c`, I **also** have to permit bash to be executed, which basically means than any command can then be executed in a subshell. I've not worked out a way around this yet!

**Comment by xeruf** [comment]
not stale

**Comment by xiaohao0576** [comment]
"enableExec": false  means you can use shell in the web UI, please check the source code
https://github.com/filebrowser/filebrowser/blob/master/cmd/root.go#L263

the problem is in the config option "shell"

when you set some value in the web UI :  Global Settings  -> Execute on shell, for example bash
you must also set bash in users Commands list

**there is a bug** when you clear the value in the web UI: Global Settings  -> Execute on shell
even it's empty in the WEB UI,  for the backend configration, shell = [""], the correct empty value should be []

you can use this command to fix it:  `filebrowser config set --shell=""`

**Comment by ghost** [comment]
im not sure how its closed, this is still an issue
