### ISSUE TITLE
Tabs for running multiple commands in background

### ISSUE THREAD

**Issue by jivank** [filebrowser/filebrowser#240]
My use case is that I want to use aria2 or wget to download something in background.  Perhaps if the commands that you run could be placed in its own tab (with an indicator if the command is still running or completed), that would allow for multiple commands to be run at the same time and cancelled if the user wishes to do so.

**Comment by hacdias** [comment]
Hey @jivank! Thanks for the suggestion. I think that the command's feature should be redesigned in a more deep manner. Any suggestions? Do you think it should be separated from the Search?

**Comment by jivank** [comment]
I think having tabs for commands would be a simple way to have a decent experience of adding functionality to this application. It appears you can already run multiple tasks in the background, but you can only see the progress of the last command.

The only idea I had in mind for a more advanced command system is a plugin system (for each whitelisted command like git, wget, aria2) that offers a seamless web interface for each command. Or the custom button functionality that can be tied to a command (as seen on one of the other tickets).

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
