### ISSUE TITLE
Ram Cache too large

### ISSUE THREAD

**Issue by stignarnia** [filebrowser/filebrowser#2400]
**Description**
I have several GB large video files and no problem, but as soon as I navigate to a folder with an 800MB image it starts using more than 6GB of RAM. I really don't understand how it can fill up so much more than even the total content of the folder

**Expected behaviour**
Fill up at most the sum of the content of the folder I'm in  
Also, I would like an option to disable ram cache altogether, so that I can run it in a small container and still be able to upload very large images

**What is happening instead?**
Fills up a lot more than that, even in some cases calling for oom-kill to intervene and kill the process

**Additional context**
I'm running inside an unprivileged ubuntu 22.04 LXC container in proxmox VE

**How to reproduce?**
put a very large image in a folder and navigate to it

**Comment by stignarnia** [comment]
#1671 is a similar issue I believe

**Comment by web9upper** [comment]
I am experiencing the same issue on my NAS, uploaded a large video and it seems that the file is constantly cached in the memory, taking up to 9GB of RAM

**Comment by VLEFF** [comment]
No solution? 
Uninstall Filebrowser and install something more lightweight will be my solution in a couple of day I guess...

**Comment by k33n8nc** [comment]
Same issue here.
