### ISSUE TITLE
‼️ Hide the download button if the file is not selected

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2406]
Hide the download button if the file is not selected
Otherwise, the download button can download the whole root or current folder

**Comment by baur** [comment]
any news?

**Comment by baur** [comment]
any news?

**Comment by baur** [comment]
any news?

**Comment by SirVeggie** [comment]
Seems like the intended behaviour to download the current folder if no file is selected.

**Comment by baur** [comment]
Then this is a very bad feature.
The user can download the entire root directory with several GB of space and not notice, especially the buttons are similar and close together
