### ISSUE TITLE
Auto-Start on Startup - Specifically on Windows?

### ISSUE THREAD

**Issue by dohlin** [filebrowser/filebrowser#2407]
I see several prior tickets created regarding how to get this software to auto-start on startup on other *nix platforms, etc. but unless I'm blind I do not see anything at all regarding doing the same thing on Windows.  I've currently got a batch file that runs at login and does a simple cd command followed by a 'filebrowser -r [file share path]' command and that works well initially...but this eventually dies too.  I'm not sure if the service is crashing or something but when I noticed it's no longer working and I console back into the server I find that  the cmd prompt window that was running the filebrowser process is gone.  I have to manually re-run those commands if I want it to start working for a period of time again.

Is there a more reliable/consistent method to accomplish auto-startup on Windows platforms that I'm missing?  Thanks!

**Comment by uliian** [comment]
You can try registering services as Windows services through the [WinSW](https://github.com/winsw/winsw) project.
