### ISSUE TITLE
ReCaptcha Not Working in Fresh Filebrowser Setup with Docker

### ISSUE THREAD

**Issue by hilyin** [filebrowser/filebrowser#2408]
**Description**

I am attempting to set up a fresh FileBrowser instance using Docker and am experiencing an issue with ReCaptcha not functioning as expected.

**Expected Behavior**

ReCaptcha should be functional and display correctly.

**Observed Behavior**

- ReCaptcha is not showing up as expected. 
- The browser console displays `window.FileBrowser.ReCaptcha` as `false`.
- Confirmed `/config/settings.json` inside docker container has expected settings.

**Steps to Reproduce**

1. Create a settings.json file with the following content:

```
{
    "port": 80,
    "baseURL": "",
    "address": "",
    "log": "stdout",
    "database": "/database/filebrowser.db",
    "root": "/srv",
    "recaptcha": {
        "host": "https://www.google.com",
        "key": "<key>",
        "secret": "<secret>"
    }
}
```

2. Start FileBrowser using Docker.

3. Open FileBrowser location in browser.

4. Observe that ReCaptcha is not functioning as expected on login page.

**Comment by hilyin** [comment]
Replying so bot doesn't close.

**Comment by octasoftdev** [comment]
Same  issue fresh installation with Ubuntu Nginx recaptcha not working.

**Comment by hilyin** [comment]
This repo seems dead.
