### ISSUE TITLE
Error when Switching view mode

### ISSUE THREAD

**Issue by ezr** [filebrowser/filebrowser#241]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
I downloaded Filemanager from caddyserver.com on 9-8-17 around 5PM Central time.
I downloaded the Linux 64-bit and the Linux ARMv7 builds and had this issue with both.

### 2. What is your entire Caddyfile?
This is the Caddyfile I'm using on my raspberry pi:
```text
0.0.0.0:80 {
    tls off
    browse
    filemanager / /var/www/file {
        database /etc/ssl/caddy/filemanager/38182a6b6f9e373df981ed37d1431cc
        no_auth
    }
}

0.0.0.0:8000 {
    tls off
    browse
    root /var/www/file
}
```
Here is the one that I used to test on my x86 desktop:
```text
127.0.0.1:8000 {
    tls off
    browse
    filemanager {
        no_auth
    }
}
```

### 3. What are you trying to do?
Switch the view from the list mode to the grid mode. 

### 4. What did you expect to see?
The list of files changes mode right away.

### 5. What did you see instead (give full error messages and/or log)?
When I click the "Switch view" button, a red popup appears in the lower right saying "missing struct tag id or ID field". The view mode does not change for the current folder. However if I click into a different folder, then the mode will have switched to the one I wanted. Then when I go back, by clicking on the house icon on top of the list of files, the mode will still be the way that I wanted it.
Here is what I got from the -log option:
```text
2017/09/10 19:56:49 http://127.0.0.1:8000
2017/09/10 19:57:00 missing struct tag id or ID field
2017/09/10 19:57:06 missing struct tag id or ID field
2017/09/10 19:57:16 [INFO] SIGINT: Shutting down
```

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Use the second caddyfile I posted. Browse to 127.0.0.1:8000 and hit the switch view button. Tested with Firefox and Chromium.

**Comment by hacdias** [comment]
Thanks for reporting this 😄
