### ISSUE TITLE
Simple upload/download endpoint for anonymous upload like transfer.sh

### ISSUE THREAD

**Issue by minhng99** [filebrowser/filebrowser#2411]
Hi,
First of all, thanks for the great project.
I'm wondering if there's a plan for something like 'transfer.sh'? Simply an endpoint where ones could just `curl --upload-file ./hello.txt https://filebrowser/public_upload` and the reply will be the link for the uploaded file.

The uploaded file could be owned by a specific user created manually so it will be easy for managing the files created by that user.

I'm trying a DIY solution, but it needs authenticate by JWT which complicated the steps needed for uploading the file. I also know about the authentication Header but I want to keep the user management capability.

Thank you

**Comment by JaCoB1123** [comment]
A possibility to add the "upload" permission to shares would be awesome.
