### ISSUE TITLE
Login via URL

### ISSUE THREAD

**Issue by RuralDependencies** [filebrowser/filebrowser#2428]
**Is your feature request related to a problem? Please describe.**
Would like to be able to autologin via GET parameters

**Describe the solution you'd like**
Example: add ?user=XXX&password=XXXX to autologin

Any idea how to do it quickly?

**Comment by ThijmenGThN** [comment]
I'd also like to have such feature, trying to integrate file browser in my own web portal via an iframe.

**Comment by idoodler** [comment]
This would be very not save. You could use the JWT from the Local Storage. Tho it needs some renewal now and then.

**Comment by ThijmenGThN** [comment]
> This would be very not save. You could use the JWT from the Local Storage. Tho it needs some renewal now and then.

I'm not able to manipulate the localStorage within an iframe due to my filebrowser being accessible on a subdomain.

I do understand that passing down the username and password is very insecure via the url - I'll look further for a solution.

**Comment by teodly** [comment]
I've done it using JWT similarly to this: https://github.com/filebrowser/filebrowser/issues/1448#issuecomment-870687787

I've generated long-lasting JWT token and have put it in a .html file generated using this script, with non-guessable file name:

```python3
#!/usr/bin/python3

SIGNING_KEY='...'

from jose import jwt
import datetime, json, base64  

def filebrowser_tok():

        def now_millis():
                epoch = datetime.datetime.utcfromtimestamp(0)
                delta = datetime.datetime.utcnow() - epoch
                return int(delta.total_seconds())

        now = now_millis()

        token = {
                'user': {
                        'id': 2, 'locale': 'en', 'viewMode': 'list', 'singleClick': True,
                        'perm': {
                                'admin': False, 'execute': False, 'create': False, 'rename': False,
                                'modify': False, 'delete': False, 'share': True, 'download': True
                        },
                        'commands': [], 'lockPassword': True, 'hideDotfiles': True},
                'exp': now + 2*365*86400,
                'iat': now,
                'iss': 'File Browser'
        }
        token_headers = {'alg': 'HS256', 'typ': 'JWT'}

        signing_key = base64.b64decode(SIGNING_KEY)

        signed_and_encoded_token = jwt.encode(
                token,
                signing_key,   
                headers=token_headers,
                algorithm='HS256'
        )

        return json.dumps(signed_and_encoded_token)


print('''<!doctype html>
<html>
<head>
</head>
<body>
Redirecting...
<script>
localStorage.setItem('jwt', ''');
print(filebrowser_tok())
print(''');
document.location.href = '/';  
</script>
</body>
</html>''');
```
Set `SIGNING_KEY` and user's id, change `exp` and `perm` according to your needs.

Downside: you can't revoke this token. Don't know whether removing the user will invalidate the token. If not, the only option is changing the global signing key.
