### ISSUE TITLE
Request for adding path feature and quick shortcuts in FileBrowser

### ISSUE THREAD

**Issue by kent1026** [filebrowser/filebrowser#2429]
Dear FileBrowser Team,

I am writing to request the addition of a path feature and quick shortcuts in FileBrowser. These features would greatly enhance the user experience and make it easier for us to manage files and folders.

Currently, when using FileBrowser, navigating to a deep directory requires clicking through multiple folders, which can be time-consuming, especially when switching between multiple directories. By adding a path feature, users can easily see their current location and quickly navigate to the desired directory.

Additionally, quick shortcuts would allow users to quickly access frequently used folders, which can save time and increase productivity.

I believe that adding these features would make FileBrowser a more convenient and user-friendly tool. Thank you for considering my request.

Thank you for your time.

Sincerely,

Kent

The article was translated by ChatGPT.

**Comment by bkobeszko** [comment]
+1 for quick shortcuts or list of favourite files and folders
