### ISSUE TITLE
Custom filebrowser in OpenMediaVault 6 (OMV6)

### ISSUE THREAD

**Issue by Mobin-khorushi** [filebrowser/filebrowser#2432]
hi im using this product with openmediavault I want to do some changes and make the file browser show in a web view inside the omv itself i installed this plugin via deb file as omv plugin but the problem is i can't see any containers or any codes in deb file to do changes or at least find out how to do changes and rebuild to work with omv 

do you guys have any clues how i can achieve this ? any ideas ? any experiences  ? been long working on it any small hints will help me a lot thanks

**Comment by gedw99** [comment]
You want a web view ?


https://github.com/gioui-plugins/gio-plugins/tree/main/webviewer

**Comment by gedw99** [comment]
Works great
