### ISSUE TITLE
[Feature request] View RAW Files

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#2433]
**Is your feature request related to a problem? Please describe.**
I can't view or preview RAW files. There are not thumbnails for videos either.

**Describe the solution you'd like**
To be able to view RAW files (thumbnails and original picture) and video thumbnails.

**Comment by gedw99** [comment]
There is a golang raw file viewer . 

Can’t remember off the top of my head but can find it.

maintainers want to add this though ?

**Comment by chipotledonut** [comment]
At least, filter by folder in searching would be great:

Case scenario: I'm looking for pictures in Tokyo, I have four folders name DATE Tokyo. I have to scroll trough all the contents of those folders to find the actual folders.

If we could filter by folder we would be able to only see the main folders.
