### ISSUE TITLE
trouble building from source

### ISSUE THREAD

**Issue by bpt6576** [filebrowser/filebrowser#245]
### 2. entire Caddyfile
```text
127.0.0.1:1234
prometheus
filemanager
```

### 3. What are you trying to do?
Use File Manager at all. It is not listed in `caddy -plugins` and launching Caddy prints "no action found for directive 'filemanager' with server type 'http' (missing a plugin?)"

### 4. What did you expect to see?
`caddy -plugins` to contain `http.filemanager`

### 5. What did you see instead (give full error messages and/or log)?
```text
Server types:
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.errors
  http.expvar
  http.ext
  http.fastcgi
  http.gzip
  http.header
  http.index
  http.internal
  http.limits
  http.log
  http.markdown
  http.mime
  http.pprof
  http.prometheus
  http.proxy
  http.push
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.websocket
  shutdown
  startup
  tls
  tls.storage.file
```

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
```text
go get github.com/mholt/caddy
go get github.com/caddyserver/builds
go get github.com/hacdias/filemanager
github.com/miekg/caddy-prometheus

cd "$GOPATH/src/github.com/mholt/caddy/caddy"

cat <<EOF>caddymain/plugins.go
package caddymain

import (
_ "github.com/hacdias/filemanager"
_ "github.com/miekg/caddy-prometheus"       
  )
EOF

go get -u -v -f ... || echo "Updated dependencies"
go run build.go
caddy -plugins
```

NOTE: If I remove the File Manager directive from the Caddyfile then Caddy runs fine; I am able to view Prometheus metrics using Caddy directive and a simple index.html file is hosted. Also, I previously was having trouble getting Caddy building prior to this as documented at https://caddy.community/t/cant-build-with-plugins/2749/5, but that may be completely unrelated.

**Comment by hacdias** [comment]
Replace `_ "github.com/hacdias/filemanager"` by `_ "github.com/hacdias/filemanager/caddy/filemanager"` please 😄 It should work

**Comment by bpt6576** [comment]
Success! File Manager shows up in the plugins list and the Caddyfile directive for it is working. I am able to login and use File Manager. Thank you! Please consider adding the github URL clarification to either https://henriquedias.com/filemanager/installation/#caddy or https://caddyserver.com/docs/http.filemanager

**Comment by hacdias** [comment]
I will! Thanks
