### ISSUE TITLE
Separating back-end and front-end projects

### ISSUE THREAD

**Issue by freakingeek** [filebrowser/filebrowser#2453]
I suggest that we separate the back-end and front-end code into separate repositories. This would allow for more flexibility in development and deployment, as well as easier collaboration between back-end and front-end developers.

### Benefits:

- Easier collaboration between back-end and front-end developers
- More flexibility in development and deployment
- Improved maintainability and scalability of the project
- Clearer separation of concerns between the back-end and front-end code  

### Possible approach:

One approach to separating the back-end and front-end code would be to create two new repositories: one for the back-end code and one for the front-end code. The back-end repository could contain the server-side code, database schema, and API endpoints, while the front-end repository could contain the client-side code, stylesheets, and user interface components. We could then connect the two projects using APIs.

**Comment by vensauro** [comment]
Which are the benefits of using separeted repositories, and how things can be more simple and easier with this?

all benefits that you have pointed, are from frontend and backend separation, and the project already enjoy these benefits.
the frontend are on the folder [frontend](https://github.com/filebrowser/filebrowser/tree/master/frontend)

another thing, how will be more easier to for deployment with docker or genereting the executable if the repositories are separated?
