### ISSUE TITLE
Unable to use Docker container

### ISSUE THREAD

**Issue by xeruf** [filebrowser/filebrowser#2456]
**Description**
Docker container installation is described at https://filebrowser.org/installation#docker
But the Docker setup seems to ship with a default auth config I cannot figure out, and no way to access the vital CLI - any command produces a timeout:
```sh
$ sudo docker exec -it 77a0df5e4c12 /bin/sh
/ $ ./filebrowser config cat
2023/05/05 11:55:05 timeout
/ $ ./filebrowser
2023/05/05 11:55:18 timeout
/ $ ./filebrowser --config .filebrowser.json  users ls
2023/05/05 11:51:55 timeout
```
Which means I have no idea how to actually use it now, even though it is working and running on the web ^^

**Expected behaviour**
Infos on how to configure dockerized installation or ability to use CLI

**How to reproduce?**
Run from docker as per docs and then exec into the container.

**Comment by AlencarGabriel** [comment]
I've had this problem in the past. The only solution I found was to clone the default DB and use it:

`filebrowser users ls -d /filebrowserdb_copy.db`

It seems that only one process at a time can access this file.

**Comment by arnonm** [comment]
Probably should rename this as "can't use filebrowser command line while web server is running".
Once a container is up, and the filebrower app is running, you cannot run additional filebrowser commands to administer the container.
This is how you would most likely setup a filebrowser container programatically.

**Comment by xeruf** [comment]
>  This is how you would most likely setup a filebrowser container programatically.

how?
