### ISSUE TITLE
Missing RestPI documentation

### ISSUE THREAD

**Issue by gaby** [filebrowser/filebrowser#2459]
There's several tickets that have been closed by stale bot asking for docs. There's no documentation on how to use the API.

Rel #1548 #1079 https://github.com/filebrowser/docs/issues/1

**Comment by gaby** [comment]
Still valid

**Comment by gaby** [comment]
Still valid

**Comment by icheered** [comment]
I wrote a short example on how to upload/download files using nodejs in #2551 but it took me WAY too long due to illogical API structure and absolutely zero documentation on using the REST API... So yeah I would argue this is a very important issue but it seems to be completely ignored...
