### ISSUE TITLE
RFE: allow to set commands for events in config file

### ISSUE THREAD

**Issue by haai** [filebrowser/filebrowser#246]
I would like to set the commands in the configfile that should be executed on specific events like 'before_save'? IT is not possible AFAIK, is it? What do you think?

**Comment by hacdias** [comment]
Thanks for reporting. We'll take care ASAP. Started uni some weeks ago and I'm still getting used to everything. Sorry 😞

**Comment by hacdias** [comment]
I'm not sure whether or not this is a good idea. Currently, File Manager saves it's configuration to a .db file. If we were going to do put the event commands on the config file, the configuration would be too much split around many files. What do you think? What is your use case?

**Comment by haai** [comment]
I understand your point ... well consider this situation:
you have a terraform configuration automatically setting up a complete cloud VPS with a caddy webserver and the hugo plugin. So good so far... to keep track of the users changes during the lifetime of the node you would like to save the changes via git. but to setup the commands you need to manually set it in the config. therefore it would be good to have a possibility to set those commands in the configfile.

wouldn't it be possible to parse the commands during start and save them in the db during parsetime? what do you think of it?

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
