### ISSUE TITLE
Filebrowser on Proxmox

### ISSUE THREAD

**Issue by Jens-Wymeersch** [filebrowser/filebrowser#2462]
**Description**
I'm sorry to ask, but I'm struggling with a problem with my PVE7 (https://forum.proxmox.com/threads/proxmox-restarts-randomly.116080/) 
After executing a `systemctl status`
I get a state of pve7 as being **degraded**
After checking it indicates after running `systemctl --failed` 
The failed service seems to be filebrowser
Hence, I want to remove this service. Can you help me with the right command(s).

**Expected behaviour**
no problems

**What is happening instead?**
After a while my proxmos server goes down

**Additional context**

**How to reproduce?**
Every few days, I need to manually reboot my system

2 Questions 
- how can I remove the program ?
- how can I avoid it to degrade my system ?

**Comment by jniggemann** [comment]
The linked proxmox forum thread does not show any relation to filebrowser.
Can you explain how filebrowser is related to you proxmox node rebooting?
