### ISSUE TITLE
docker build report error

### ISSUE THREAD

**Issue by DonXander** [filebrowser/filebrowser#2464]
when I execute “docker build -t filebrowser-image .”，it reported "/filebrowser" not found
![image](https://github.com/filebrowser/filebrowser/assets/25742814/eeea1758-4d8b-4d06-919e-36bf04aa3aa1)

**Comment by ljskatt** [comment]
Im experiencing the same issue
+1

**Comment by o1egl** [comment]
You need to build the app first. Run `make build`
