### ISSUE TITLE
【feature request】upload

### ISSUE THREAD

**Issue by abyterv** [filebrowser/filebrowser#2465]
I would like to implement file upload through a URL, which includes username, upload time, file name, etc. Do you have any suggestions for modifying the source code?

**Comment by o1egl** [comment]
I'm sorry, I'm having trouble understanding your message. Could you please provide an example to clarify your meaning?

**Comment by abyterv** [comment]
Thank you.What I mean is to upload files directly through a URL, similar to an interface, without using FileBrowser for operations. For example, by inputting http://IP:port/username/uploadtime/filename, the file with the name "filename" can be uploaded, with the uploader's name as "username," and it would be even better if an additional folder name could be included in the URL.

**Comment by abyterv** [comment]
I think that modifying the upload file interface and API in the source code would enable the desired functionality.

**Comment by abyterv** [comment]
> I'm sorry, I'm having trouble understanding your message. Could you please provide an example to clarify your meaning?



> I'm sorry, I'm having trouble understanding your message. Could you please provide an example to clarify your meaning?

Thank you.What I mean is to upload files directly through a URL, similar to an interface, without using FileBrowser for operations. For example, by inputting http://IP:port/username/uploadtime/filename, the file with the name "filename" can be uploaded, with the uploader's name as "username," and it would be even better if an additional folder name could be included in the URL.

**Comment by abyterv** [comment]
> I think that modifying the upload file interface and API in the source code would enable the desired functionality.

Implement platform integration
