### ISSUE TITLE
413 request entity too large

### ISSUE THREAD

**Issue by josemaviza** [filebrowser/filebrowser#2466]
Hello everyone, I love the work you have done with this program, I give you my most sincere congratulations.

I just wanted to ask you if there is a solution to the error that I have shown you in the title. I am a video editor and they transfer the files to me over the internet. I want to use your program but it gives me this error because my files are quite large video camera raw files. I wanted to know if that limitation can be removed. From what I've seen, it doesn't let you upload files larger than 2GB. When it exceeds that limit, it throws error 413. I would appreciate an answer. Thank you guys so much and keep it up. Hugs from Spain.

**Comment by o1egl** [comment]
There are no such limits set in the app. Probably you need to modify your proxy configs

**Comment by szmarczak** [comment]
@o1egl It shouldn't upload gigabytes of data in a single request, that's bad practice. I don't think Cloudflare allows you to modify this limit.
