### ISSUE TITLE
curl error and bash error

### ISSUE THREAD

**Issue by shen19970802** [filebrowser/filebrowser#2471]
Description 

Expected behaviour 

What is happening instead? 

Additional context 
root@iStoreOS:~# curl -fsSLk https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash 
curl: (22) The requested URL returned error: 404 
root@iStoreOS:~# curl -Lk https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    96    0    96    0     0  12745      0 --:--:-- --:--:-- --:--:-- 48000
bash: line 1: h1: No such file or directory
<img width="602" alt="123" src="https://github.com/filebrowser/filebrowser/assets/55844284/963f5e6f-85f8-4c8c-8be6-7efd8ca24e75">

How to reproduce? 

Files

**Comment by o1egl** [comment]
I can't reproduce it. Check your firewall and routing configs
