### ISSUE TITLE
static files are not served on baseurl with subpath

### ISSUE THREAD

**Issue by hydrargyrum** [filebrowser/filebrowser#2477]
**Description**

I have a reverse proxy in front of filebrowser, on `http://domain/subpath`.

Without filebrowser configuration, `http://domain/subpath` is served by filebrowser and the page contains references to `/static` for example `/static/js/chunk-vendors.0f8eac7b.js`. It fails to load because not under `/subpath` so the reverse proxy doesn't send the request to filebrowser.

With filebrowser's `baseURL` set to `http://domain/subpath`, the page contains references to `http://domain/subpath/static/`. However, it doesn't load either, this time because filebrowser returns a 404, probably because it searches `/subpath/static/<file>` instead of `/static/<file>` and subtracting `/subpath` which is part of the `baseURL`.

**Expected behaviour**

Filebrowser works behing a reverse proxy.

**What is happening instead?**

Filebrowser doesn't handle the requests properly.

**Comment by hydrargyrum** [comment]
Ok it was my mistake when configuring the reverse proxy:

I had
```
ProxyPass "/foo" "http://bar"
ProxyPassReverse "/foo" "http://bar"
```

but it should have been (that works)
```
ProxyPass "/foo" "http://bar/foo"
ProxyPassReverse "/foo" "http://bar/foo"
```

**Comment by matifali** [comment]
Hi @hydrargyrum, I have a quick question about setting `baseURL`.
When running behind a base proxy, What should be the `baseURL` be? Should it be set to the actual domain?
e.g., `baseURL=http://domain/filebrowser` or `baseURL=http://localhost:8080/filebrowser`

**Comment by hydrargyrum** [comment]
In filebrowser's `filebrowser.json`, i have 
```
    "baseURL": "/filebrowser",
```

And in the [reverse proxy](https://caddyserver.com/docs/caddyfile/directives/handle), i have

```
    handle /filebrowser/* {
        reverse_proxy http://localhost:1234
    }
```

This way, when the reverse proxy receives `/filebrowser/xxx`, it transmits that path verbatim to filebrowser, and all the css path will be relative to `/filebrowser/` (and filebrowser knows and keeps that prefix), which the reverse proxy will transmit IN. If the reverse proxy strips the prefix when giving to filebrowser, that will not work, because the output paths are not transformed by the reverse proxy OUT.
