### ISSUE TITLE
User profile page visible when noAuth is true

### ISSUE THREAD

**Issue by gdunstone** [filebrowser/filebrowser#248]
Version: 1.3.4
config:
```
port: 8080
noAuth: true
baseURL: /fm
allowEdit: false
allowNew: false
allowCommands: false
allowPublish: false
```

**Bug**:
User profile page is still visible when noAuth is true

**Expected**:
404 instead of user profile page

**Reproduce**:
go to <baseURL>/settings/profile or <baseURL>/settings and you should see a profile edit page

**Notes**:
Nothing can be changed globally from the user profile page.

**Comment by hacdias** [comment]
Thanks for reporting. We'll take care ASAP. Started uni some weeks ago and I'm still getting used to everything. Sorry 😞

**Comment by gdunstone** [comment]
Its cosmetic so no rush.
I would fix it myself but I'm unfamiliar with the codebase.
