### ISSUE TITLE
I can't upload a larger file

### ISSUE THREAD

**Issue by DaaGH** [filebrowser/filebrowser#2483]
It is not possible to upload a large file. Previously, a configuration was made in nginx, the limit on the size of uploaded files was removed. After that, everything worked. Recently I decided to upload a 17 GB file, it gives an error 405 

![image](https://github.com/filebrowser/filebrowser/assets/117726061/d0ce0751-9e98-4ce5-ba2e-b73e2d8baa30)

Is there a setting in file browser to restrict downloaded files? I didn't find this in the settings. Thank you.

**Comment by DaaGH** [comment]
2023/05/31 14:11:47 [error] 474920#474920: *139 upstream timed out (110: Connection timed out) while sending request to upstream

**Comment by DaaGH** [comment]
The file browser is in docker

**Comment by gpriyank1** [comment]
Please provide your infrastructure environment details. I was able to remove this limitation by updating my Kubernetes Ingress NGINX conf and HAProxy load balancer settings. I don't remember changing any Filebrowser settings for the upload file size.
