### ISSUE TITLE
Issue when behind nginx 

### ISSUE THREAD

**Issue by eastonman** [filebrowser/filebrowser#249]
I an using filemanager behind a nginx reverse proxy .
And I found that when behind nginx the command you execute in the searching bar do not give a respond .
Do I need some of the proxy_set_header settings?

**Comment by hacdias** [comment]
There is any error on the Developer Tools' Console?

**Comment by eastonman** [comment]
I am using Android phone right now  and I can only found a   mini developer console on my phone 
I found an error when requesting api at ws://()/app/command 


t=7918 [st=517] 
net_error = -320 (ERR_INVALID_RESPONSE)

**Comment by eastonman** [comment]
I will check it on my computer as soon as possible

**Comment by eastonman** [comment]
api.js:184 WebSocket connection to 'ws://（）/api/command/' failed: Error during WebSocket handshake: Unexpected response code: 400
on chrome developer console

**Comment by hacdias** [comment]
This is a weird uri for the websocket: ```ws://()/app/command```. What is the configuration you're using with `filemanger`?

**Comment by eastonman** [comment]
I am using config file listing below: config.yml

``````

port: 38765
baseURL: ''
noAuth: false
address: 127.0.0.1
reCaptchaKey: ''
reCaptchaSecret: ''
database: "/etc/filemanager/database.db"
log: "/etc/filemanager/filemanager.log"
plugin: ''
scope: "/root"
allowCommands: true
allowEdit: true
allowNew: true
commands:
  - git
  - svn
  - ls
  - wget

``````

And using a nginx reverse proxy 

``````
server {
        listen 80;
        listen [::]:80;
        server_name ~^FQDN$;


        location / {
                proxy_pass http://127.0.0.1:38765;
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Referer http:127.0.0.1;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}
``````

**Comment by hacdias** [comment]
Could you please try changing `baseURL: ''` to `baseURL: '/'`?

**Comment by eastonman** [comment]
i get stuck at the first page

**Comment by eastonman** [comment]
on my phone i get 
HTTP2_SESSION_CLOSE
                --> description = "Connection closed"
                --> net_error = -100 (ERR_CONNECTION_CLOSED)
and the socket is now available

**Comment by eastonman** [comment]
GET http://static/js/manifest.958a39dfce02a7147aaa.js net::ERR_ABORTED
GET http://static/js/vendor.44036de40396f416cb9a.js net::ERR_ABORTED
GET http://static/js/app.406156321387f703a1c2.js net::ERR_ABORTED
GET http://static/css/app.c5b9e7a3a9bd879a746e038e82cfeb60.css net::ERR_ABORTED
GET http://static/js/manifest.958a39dfce02a7147aaa.js net::ERR_ABORTED
GET http://static/js/vendor.44036de40396f416cb9a.js net::ERR_ABORTED
GET http://static/js/app.406156321387f703a1c2.js 502 (No data received from server or forwarder)
GET http://static/img/icons/favicon-32x32.png 502 (No data received from server or forwarder)
GET http://static/img/icons/favicon-16x16.png 502 (No data received from server or forwarder)
on chrome web console on my computer

**Comment by eastonman** [comment]
it should be http://FQDN/staic....

**Comment by hacdias** [comment]
Try adding this option to your config:

```
prefixUrl: 'FQDN/'
```

**Comment by eastonman** [comment]
I have tried adding it 
And when I use 
`````
prefixurl: 'fqdn/'
``````

The element still can't load and the url change to http://fqdn/fqdn///static.....
When I delete the '/' behind 
Still can't load
When I set base url to '' (blank)
No luck

**Comment by eastonman** [comment]
I guess nginx has some magic rewrite logic

**Comment by hacdias** [comment]
This is really weird. I'll try to reproduce this on my computer.

**Comment by eastonman** [comment]
Thanks

**Comment by hacdias** [comment]
@manyang901, could you please check my last reply with code on #278? I hope it helps. Sorry for being so late 😞

**Comment by eastonman** [comment]
Thanks , I'll try it.

**Comment by dream10201** [comment]
@manyang901 
看来我们碰到了同一个问题，nginx反向代理filemanager，这是我目前可用的配置
# nginx
![image](https://user-images.githubusercontent.com/20334372/34148503-70c9b1c8-e4dc-11e7-853b-22a90a764ea5.png)
# filemanager
![image](https://user-images.githubusercontent.com/20334372/34148531-91ddb81e-e4dc-11e7-8144-041029fe6995.png)

但是还是有一些问题，比如
![image](https://user-images.githubusercontent.com/20334372/34148600-e7c92c86-e4dc-11e7-80df-cc15b9558a84.png)

和登录后的地址栏
![image](https://user-images.githubusercontent.com/20334372/34148680-46b7ad44-e4dd-11e7-8097-1948e91508ad.png)

**Comment by hacdias** [comment]
The 403 Forbidden errors can be safely ignored (at least if they only appear before logging in *or* if you try to make some action to some directory/file you don't have access to).

I'll close this since https://github.com/hacdias/filemanager/issues/278#issuecomment-344525960 seems to be working.

If you have any other problems, just reopen this issue.

**Comment by BlueFang** [comment]
> The 403 Forbidden errors can be safely ignored (at least if they only appear before logging in _or_ if you try to make some action to some directory/file you don't have access to).
> 
> I'll close this since [#278 (comment)](https://github.com/filebrowser/filebrowser/issues/278#issuecomment-344525960) seems to be working.
> 
> If you have any other problems, just reopen this issue.

        ```
location / {
            proxy_pass http://192.168.1.3:8082;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header Access-Control-Allow-Origin 192.168.1.3;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
        }
```

Good good study, day day up.
