### ISSUE TITLE
CMYK images not displayed correctly

### ISSUE THREAD

**Issue by joergp** [filebrowser/filebrowser#2492]
Filebrowser ignores included color profiles, colors of thumbnails and previews e.g. of CMYK jpgs are way off.

**Comment by mj321** [comment]
we implemented a solution that uses ImageMagick as external process to create a thumbnail with correct colors. Currently it can be controlled through an environment variable. It's little code, but as this was my first contact with Go, it might need some touching up.

Would you (filebrowser team) be interested in a PR, or is this solution too "hacky" to be considered?
