### ISSUE TITLE
Search checks for every individual word

### ISSUE THREAD

**Issue by 46620** [filebrowser/filebrowser#2493]
**Description**

When searching for a file with spaces, it treats every space as another search.

**Expected behaviour**

Search: The quick brown fox 6
Results:
The quick brown fox 6.txt
The quick brown fox 6.pdf
The quick brown fox 6 (Copy).pdf
...

**What is happening instead?**

Search: The quick brown fox 6
Results:
**6**0573405727.png
A story about **the** day I did **6** things.rtf
**Brown** eyes.png
**quick**-remove.sh
**The quick** black **fox**.mov
The quick brown fox 6.txt
The quick brown fox 6.pdf
The quick brown fox 6 (Copy).pdf
...

**How to reproduce?**

1. Put multiple files in a folder with overlapping words
2. Search

**Comment by 46620** [comment]
bumping to keep open, even if that's seen as annoying, as this is an actual bug that makes searching large archives nearly impossible

**Comment by gtsteffaniak** [comment]
EDIT : this is included in latest release in this fork:
https://github.com/gtsteffaniak/filebrowser
