### ISSUE TITLE
Option to set a published server url for the share link creation.

### ISSUE THREAD

**Issue by fatSquirrel42** [filebrowser/filebrowser#2499]
**Is your feature request related to a problem? Please describe.**
Normally I access the filebrowser over the local network. Then when I copy a share link, I get something like "http://192.168.1.1:80/share/938ahdb". Ideally I would get the URL to the public share.

**Describe the solution you'd like**
The possibility to set the public URL of the server in the settings. You could specify the URL as https://filebrowser.mydomain.com. Then when I would generate a link to share via the local network, I would get "https://filebrowser.mydomain.com/share/938ahdb" and not "http://192.168.1.1:80/share/938ahdb"

**Comment by zfxkj** [comment]
You can use nginx to achieve what you need. After configuring nginx, you can directly use the domain name to access it.
