### ISSUE TITLE
Saving posts / video from testing

### ISSUE THREAD

**Issue by adprof** [filebrowser/filebrowser#25]
Hi, 
Matt encouraged me on Hugo forum to sent You some comments from my test.
I could not write .md file. Here you have my experiences:

https://www.icloud.com/sharedalbum/#B0WJtdOXm0casHF

Maybe this is connected to OS user rights?

I'll be happy to spreading also some suggestions regarding functionalities if You are interested.

Best Regards,

**Comment by hacdias** [comment]
Hi @adprof 

I can't really understand what's wrong. But there's a trick: see the developer console! It might help! Then send me the error so we can analyse it.

Yes, I'm opened to all suggestions!

Have a nice day,

**Comment by mholt** [comment]
Also considering enabling error logging and see if anything shows up there related to that 500 error. (If not, then the add-on's handler is not properly reporting errors)

**Comment by adprof** [comment]
Hi,
An hour ago I tested in Chrome browser too. I'm quite surprised because is working properly! ;)
"something-went-wrongs" shows only in Safari (9.0/ OS X 10.11). Server responds 404.

![screen shot 2015-10-12 at 21 16 03](https://cloud.githubusercontent.com/assets/9997937/10436476/e2efd3ee-7126-11e5-963e-74c1b8117f00.png)

Regards,

**Comment by adprof** [comment]
By the way. Notifications are quiet extraordinary :+1:

**Comment by hacdias** [comment]
Eheh thanks.

I've been using Chrome and IE and I haven't had those problems. 404... that's very strange because it only occurs with Safari and I can't test. I don't have any OS X machine I can use.

**Comment by mholt** [comment]
That's weird. I wonder if there's a bug in Safari.

But that 500 Internal Server Error - do you get that in Chrome too, @adprof? Can you do it again in Safari but enable error logging first?

```
errors error.log
```

or

```
errors {
    404 404.html
    log error.log
}
```

**Comment by mholt** [comment]
Also I want to see the contents of the access.log file which should hint at those 404s.

**Comment by adprof** [comment]
I suspect that 500 may be due to an error in a front-matter. I'll give a try with another hugo theme.
Here you have logs (first Safari, then after 404s - Chrome).

access.log

```
::1 - [12/Oct/2015:22:30:04 +0200] "GET / HTTP/1.1" 200 1024
::1 - [12/Oct/2015:22:30:04 +0200] "GET / HTTP/1.1" 200 1024
::1 - [12/Oct/2015:22:30:11 +0200] "GET / HTTP/1.1" 304 0
::1 - [12/Oct/2015:22:30:11 +0200] "GET /admin/browse/content/post/ HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:30:12 +0200] "GET /admin/browse/content/post/ HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:30:12 +0200] "GET /admin/browse/content/post/ HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:30:12 +0200] "GET /admin/browse/content/post/ HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:30:12 +0200] "GET /admin HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:30:13 +0200] "GET /admin HTTP/1.1" 307 67
::1 - [12/Oct/2015:22:30:13 +0200] "GET /admin/ HTTP/1.1" 307 82
::1 - [12/Oct/2015:22:30:13 +0200] "GET /content/ HTTP/1.1" 200 1091
::1 - [12/Oct/2015:22:30:13 +0200] "GET /admin/assets/js/app.min.js HTTP/1.1" 200 2919
::1 - [12/Oct/2015:22:30:13 +0200] "GET /admin/assets/css/main.min.css HTTP/1.1" 200 10620
::1 - [12/Oct/2015:22:30:13 +0200] "GET /admin/assets/js/plugins.min.js HTTP/1.1" 200 118784
::1 - [12/Oct/2015:22:30:13 +0200] "GET /admin/assets/fonts/fontawesome-webfont.woff?v=4.4.0 HTTP/1.1" 200 81284
::1 - [12/Oct/2015:22:30:15 +0200] "GET /content/post/?_pjax=%23content HTTP/1.1" 200 845
::1 - [12/Oct/2015:22:30:17 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md?_pjax=%23content HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:30:17 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:30:22 +0200] "GET /content/post/ HTTP/1.1" 200 1275
::1 - [12/Oct/2015:22:30:23 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md?_pjax=%23content HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:30:23 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:30:26 +0200] "GET /admin/edit/content/post/goisforlovers.md?_pjax=%23content HTTP/1.1" 200 4660
::1 - [12/Oct/2015:22:30:33 +0200] "POST /admin/edit/content/post/goisforlovers.md HTTP/1.1" 404 910
::1 - [12/Oct/2015:22:30:48 +0200] "POST /admin/edit/content/post/goisforlovers.md HTTP/1.1" 404 910
::1 - [12/Oct/2015:22:30:54 +0200] "POST /admin/edit/content/post/goisforlovers.md HTTP/1.1" 404 910
::1 - [12/Oct/2015:22:31:22 +0200] "GET /admin/edit/content/post/goisforlovers.md HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:31:22 +0200] "GET / HTTP/1.1" 200 1024
::1 - [12/Oct/2015:22:31:24 +0200] "GET /css/highlight.css HTTP/1.1" 200 629
::1 - [12/Oct/2015:22:31:24 +0200] "GET /css/style.css HTTP/1.1" 200 3406
::1 - [12/Oct/2015:22:31:27 +0200] "GET /images/avatar.png HTTP/1.1" 200 4977
::1 - [12/Oct/2015:22:31:27 +0200] "GET /js/main.js HTTP/1.1" 200 406
::1 - [12/Oct/2015:22:31:27 +0200] "GET /js/highlight.js HTTP/1.1" 200 23415
::1 - [12/Oct/2015:22:31:39 +0200] "GET /admin/edit/content/post/goisforlovers.md HTTP/1.1" 200 5118
::1 - [12/Oct/2015:22:31:55 +0200] "GET /admin/ HTTP/1.1" 401 41
::1 - [12/Oct/2015:22:31:55 +0200] "GET /admin/ HTTP/1.1" 307 82
::1 - [12/Oct/2015:22:31:55 +0200] "GET /content/ HTTP/1.1" 200 1091
::1 - [12/Oct/2015:22:31:55 +0200] "GET /admin/assets/js/app.min.js HTTP/1.1" 200 2919
::1 - [12/Oct/2015:22:31:55 +0200] "GET /admin/assets/css/main.min.css HTTP/1.1" 200 10620
::1 - [12/Oct/2015:22:31:55 +0200] "GET /admin/assets/js/plugins.min.js HTTP/1.1" 200 118784
::1 - [12/Oct/2015:22:31:55 +0200] "GET /admin/assets/fonts/fontawesome-webfont.woff2?v=4.4.0 HTTP/1.1" 200 64464
::1 - [12/Oct/2015:22:31:56 +0200] "GET /favicon.ico HTTP/1.1" 404 2733
::1 - [12/Oct/2015:22:31:57 +0200] "GET /content/post/?_pjax=%23content HTTP/1.1" 200 845
::1 - [12/Oct/2015:22:31:58 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md?_pjax=%23content HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:31:58 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:32:01 +0200] "GET /content/post/ HTTP/1.1" 200 1275
::1 - [12/Oct/2015:22:32:02 +0200] "GET /admin/edit/content/post/goisforlovers.md?_pjax=%23content HTTP/1.1" 200 4660
::1 - [12/Oct/2015:22:32:12 +0200] "GET /content/?_pjax=%23content HTTP/1.1" 200 668
::1 - [12/Oct/2015:22:32:15 +0200] "GET /content/post/?_pjax=%23content HTTP/1.1" 200 845
::1 - [12/Oct/2015:22:32:16 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md?_pjax=%23content HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:32:16 +0200] "GET /admin/edit/content/post/creating-a-new-theme.md HTTP/1.1" 500 50
::1 - [12/Oct/2015:22:32:20 +0200] "GET /admin/edit/content/post/new-post4.md?_pjax=%23content HTTP/1.1" 200 535
::1 - [12/Oct/2015:22:32:22 +0200] "POST /admin/edit/content/post/new-post4.md HTTP/1.1" 200 26
```

error.log

```
12/Oct/2015:22:30:17 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md?_pjax=%!c(MISSING)ontent] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:30:17 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:30:23 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md?_pjax=%!c(MISSING)ontent] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:30:23 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:31:58 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md?_pjax=%!c(MISSING)ontent] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:31:58 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:32:16 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md?_pjax=%!c(MISSING)ontent] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
12/Oct/2015:22:32:16 +0200 [PANIC /admin/edit/content/post/creating-a-new-theme.md] go/src/github.com/hacdias/caddy-cms/frontmatter/frontmatter.go:55 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
```

**Comment by mholt** [comment]
Thanks for the logs!

For the 404s, looks like Safari is turning the GETs into POSTs when you hit the back button? O.o Am I reading that right?

@hacdias I think you'll find these logs useful, especially the panic shown in the error log. (I think there might also be a bug in a Printf somewhere that's causing `%!c(MISSING)` to appear in the URL - maybe in Caddy core, maybe in this plugin; will need to look into that.)

**Comment by adprof** [comment]
No problem, 404s shows after "save" and "publish". I didn't hit back button.

**Comment by hacdias** [comment]
@mholt yup. I'll see when I've them. In the weekend probably.

I saw [this](https://github.com/hacdias/caddy-cms/blob/master/frontmatter/frontmatter.go#L55) and I think I've some improvements to do. I'm assuming that in all object-like-things there is a string-name to identify the content. Eg:

``` json
{
  "obj1": {
    "string1": something,
    "string2": something
  }
}
```

Where "string1" and "string2" are the "identifiers". May I create something like this:

``` json
{
  "obj1": {
    1: something,
    2: something
  }
}
```

or even like this:

``` json
{
  "obj1": {
    something,
    something
  }
}
```

?

**Comment by hacdias** [comment]
@mholt @adprof I think it's returning 404 [here](https://github.com/hacdias/caddy-cms/blob/master/editor/post.go#L55). And it shouldn't be 404, it should be 400 bad request. I've to change that,

**Comment by adprof** [comment]
![screen shot 2015-10-12 at 22 59 04](https://cloud.githubusercontent.com/assets/9997937/10438615/f4bb0aae-7134-11e5-9beb-c998e2801d6e.png)

**Comment by hacdias** [comment]
@adprof may you build it from source? If so and if you keep getting 404, we will know that it is [this](https://github.com/hacdias/caddy-cms/blob/master/editor/post.go#L83) 404.

**Comment by adprof** [comment]
Of course, I'll do it tommorow (GMT+2) ;)

**Comment by hacdias** [comment]
Sure, I'm going to sleep now. (GMT+1 very similar ahah)

**Comment by hacdias** [comment]
Please take all a look [here](https://github.com/hacdias/caddy-cms/issues/27).

**Comment by adprof** [comment]
Hi guys, 
I tried few times but still have some bugs. First I had problems with freshly updated OS X (homebrew issues). Then I followed docs, installed whole stuff and generated assets.go. But I cannot run caddydev with --source option. I cannot point properly source directory, because I got "Invalid source directory" or files are fetched from github and there is no assets.go. Are you sure that cli options functions are working properly?

How exactly should I run caddydev assuming that my clone directory is $HOME/Documents/Workshop/caddy-cms  ?

Maybe much easier to do some tests with this topic bug is to cross-compile caddy with an addon in your environement (darwin 64) so I could use it and do some tests?

process killed: go get took too long

COMMAND: go get -d caddyaddon

---- package github.com/hacdias/caddy-cms/assets: no buildable Go source files in /var/folders/t4/f0t0jt6s6bz6b2phjzprfslm0000gn/T/caddydev117150603/src/github.com/hacdias/caddy-cms/assets
RMac:newsite marcinrakiewicz$

Regards,

**Comment by hacdias** [comment]
@mholt

**Comment by hacdias** [comment]
@adprof Hi! It's been a while. Do you still receive those errors?

**Comment by mholt** [comment]
I suspect the `caddydev` errors are because of handling file paths in Windows... will look into it soon -- sorry, been swamped with a few other things.

**Comment by adprof** [comment]
@hacdias Hi, I still have caddydev issue, a precompiled version is only working so I cannot check patched version.

**Comment by hacdias** [comment]
@adprof the fix was deployed and it's now available for download! Try it out and let me know if you still receive the error!

**Comment by adprof** [comment]
Hi, I downloaded build from page. Build is quiet old (exec in my filesystem is from year 1979 ;)
I did quick check and:

1 . 500 errror as before, but logged

```
[ERROR 500 /admin/edit/content/post/goisforlovers.md] parsing time "2014-04-02" as "2006-01-02 15:04:05-07:00": cannot parse "" as "15"
```

2

```
27/Oct/2015:21:43:15 +0100 [PANIC /admin/edit/content/post/migrate-from-jekyll.md] go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:56 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
27/Oct/2015:21:45:24 +0100 [PANIC /admin/edit/content/post/creating-a-new-theme.md?_pjax=%!c(MISSING)ontent] go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:56 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
27/Oct/2015:21:45:24 +0100 [PANIC /admin/edit/content/post/creating-a-new-theme.md] go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:56 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
27/Oct/2015:21:45:28 +0100 [PANIC /admin/edit/content/post/creating-a-new-theme.md?_pjax=%!c(MISSING)ontent] go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:56 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
```

3 .
I tried also with source

```
caddydev --source /Users/mr/go/src/github.com/hacdias/caddy-hugo hugo
cannot place 'hugo' after '': directive '' not found
```

I have no time to test thoroughly today. I'll try in few days.

Regards,

**Comment by hacdias** [comment]
Hi @adprof 

Relatively to the first error, I have to see that. I know what the problem is. The problem is that, right now, the plugin only supports dates in "2006-01-02 15:04:05-07:00" so it can schedule posts.

Second error: please send me your json/toml/whatever-your-frontmatter-is so I can see where the problem is. If your frontmatter is valid, I have to check where I have the error.

For the third error we need to call @mholt!

I'll not be home this weekend so I'm not going to do anything in the next three days but I'll wait for your answer.

Have a nice day!

**Comment by mholt** [comment]
@adprof Can you be sure to pull the latest caddydev and its dependencies?

Then `cd` to the caddy-hugo repository folder and run `caddydev hugo` - that should be all you need to do to try it.

**Comment by hacdias** [comment]
@adprof Hi. Do you still receive any errors?
