### ISSUE TITLE
how can i use filebrowser as remote in rclone 

### ISSUE THREAD

**Issue by BeastAnimation361** [filebrowser/filebrowser#2508]
so i have deployed file browser in vps but how can use it as remote to copy files from vps? tried webdav did not work.

**Comment by agneevX** [comment]
What you're asking for isn't implemented in this project and is honestly, very out of scope.

**Comment by YTLoudYN** [comment]
You can listen to the port and hang it to the external network through the internal network penetration

Just like my web address ：http://mywebdev.shenzhuo.vip:59526/

**Comment by BeastAnimation361** [comment]
sup your web site doesn't load but thanks . sorry noob here so how can i do
that like any tool or github repo i can follow?
