### ISSUE TITLE
How to add more than 1 Drive?

### ISSUE THREAD

**Issue by Toasty777** [filebrowser/filebrowser#2514]
How to add more than 1 Drive? Like in [Google Drive Index](https://gitlab.com/GoogleDriveIndex/Google-Drive-Index).

**Comment by abendorg** [comment]
It would be nice to be able to add a second path, without resorting to mounting / to access the folder structure. In review of https://filebrowser.org/installation I don't see anything indicating multiple mount options.
Thanks!
