### ISSUE TITLE
share optional password autocomplete issue

### ISSUE THREAD

**Issue by edwardchenchen** [filebrowser/filebrowser#2518]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/filebrowser/filebrowser/assets/6397192/7a4360f8-7eb9-41b2-b520-e76ad297b154)
currently when create a share, browser will autofill the password with login password

**Describe the solution you'd like**

I think autocomplete can be disabled on this field

**Describe alternatives you've considered**

**Additional context**

**Comment by edwardchenchen** [comment]
unstale

**Comment by edwardchenchen** [comment]
unstale

**Comment by edwardchenchen** [comment]
unstale

**Comment by alphonse-terrier** [comment]
unstale

**Comment by edwardchenchen** [comment]
unstale
