### ISSUE TITLE
Search improvement ideas

### ISSUE THREAD

**Issue by francislavoie** [filebrowser/filebrowser#252]
It seems like it only searches filenames. It would be nice if it would also match against folders/paths. I use it as a dead-easy "fake plex", and a lot of TV show filenames are just random hashes, but the folder names are correct.

Also, the search acts weird based on context. Say I'm in the settings page and I try to use the search, there'll never be any file results, because the page I tried to search from isn't an actual file list. The search view should probably show the current path context it's searching in.

I think the results might look better if they were styled similarly to the files list view, with the modification time and such included.

Maybe if possible, sorting the search results? By relevance by default, but user could pick by name/time?

**Comment by eine** [comment]
We'll use this issue to track ideas, suggestions and enhancements related to the 'Search' feature:

- #336. External search commands.
- #415. Fuzzy search.

**Comment by helloray** [comment]
Please also consider to add an auto complete for search. Just like google.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
