### ISSUE TITLE
413 Request Entity Too Large openresty

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#2521]
how can it be fixed

**Comment by 6abc** [comment]
same issue

**Comment by RapidFire05** [comment]
same issue but it seems inconsistent. I was able to upload an 18.9gb file but not a 5.7gb ...

**Comment by RapidFire05** [comment]
So the difference is for me at least was the https. Once i put my filebrowser behind a reverse proxy with https via lets encrypt (nginx reverse proxy manager)...thats when i got the too large errors. Now with it off and accessing via 192.168...etc, it lets me upload the large file.

**Comment by RapidFire05** [comment]
This fixed it for me. Then it let me upload a large file.
![image](https://github.com/filebrowser/filebrowser/assets/80020016/bd054718-bfef-4dde-9347-c7460dfcef9c)

**Comment by RapidFire05** [comment]
I think this can be closed
