### ISSUE TITLE
Part of the files is not displayed if there are a large number of them in one directory.

### ISSUE THREAD

**Issue by OlegEnot** [filebrowser/filebrowser#2522]
**Expected behaviour**

Ability to see all directories and files on a browser page.

**What is happening instead?**

The number of displayed directories and files is limited, in different ways depending on the view settings in the browser, it is limited in different ways.

**Additional context**

Repeated on Linux Arch, Debian and Ubuntu of various versions.

**How to reproduce?**

Open a directory with more than 84 files and subdirectories.

**Comment by ArthurMousatov** [comment]
I second this issue. Just uploaded a bunch of photos/videos and only about 82 files are visible vs 158 files uploaded.
