### ISSUE TITLE
Error 413 when uploading a file (Windows 10)

### ISSUE THREAD

**Issue by Toasty777** [filebrowser/filebrowser#2524]
I'm getting the error 413 when uploading any file. The server currently runs on Windows 10.

![Screenshot 2023-06-30 211817](https://github.com/filebrowser/filebrowser/assets/122678358/48d76371-773b-4ad2-937b-507a0ea1a160)

Please help

**Comment by sbwml** [comment]
nginx.conf

`client_max_body_size 8192M;`
