### ISSUE TITLE
filebrowser logged in as "admin" but no "file access" to many dir's, on most volumes

### ISSUE THREAD

**Issue by nesch52** [filebrowser/filebrowser#2527]
**Description**

filebrowser logged in as "admin" but no "file access" to many dir's, on most volumes
logged in correctly as "admin" , changed e.g. to  /Volume2/own-subdir-name
but no "file access"
How & where can i change this to have full access like when I use TotalCommander(x64) from my PC?

**Expected behaviour**

Open Directory and show Subdir's & Data-Contents

**What is happening instead?**

!You don't have permission to access this.

**Additional context**

![image](https://github.com/filebrowser/filebrowser/assets/39209634/b94a9fd0-640f-44e8-bc9c-9c872a3af406)

**How to reproduce?**

Always in various subdir's
**Files**

**Comment by ghost** [comment]
I'm still a newb, but I suspect:
1. File/folder permissions in Linux. Or there is a mismatch between the user Filebrower is running as (not related to the Filebrowser user, but to the Linux user the app is running under) and the owner/group of the file/folder you are accessing.
On the Linux terminal, check this with "ls -l"

Is it running as a docker image or no?

**Comment by nesch52** [comment]
Thanks for your reply!! 
Sorry but I do not know much about Linux (Windows User as Linux-Newbie and Synology Admin 8,-))) ), and I'm afrayed of harming more than getting the desired effect.
But I thought being registeed and logged in on the "File Browser"-Desktop-BrowserApp  as an "admin" w. Pw# , no such problem should happen. Due to the fact that i am using no ssl , I cannot reach my synology1812+ on a root-user basis via Telnet. (Got too many SSL Login's from China ,Russia, Israel , eg as root and admin and others more, so i closed the related Ports using my Diskstation mainly as PC-File & Foto & Music depository. via TotalCommander10.5x from my PC in a smal Win11pro driven Ethernet  Home-LAN.  Is there any chance besides Midnight Commander(needs: Telnet?) to get to   the Synology System-Linux files? Have to change/edit some .cfg.Files for adapting them to my Sat-Receiver.

**Comment by ghost** [comment]
You reply doesn't make any sense, sorry.

I assume you used the standard Linux installation method. Go to a folder where you can access the files. Do "ls -l" to list owners and permissions. Then in Linux go to a folder where you can't access the files, do "ls -l". See if there is a difference in owners or permissions.

**Comment by nesch52** [comment]
Sorry not able to continue...I'm in hospital....thanks so long....

**Comment by coffseducation** [comment]
> You reply doesn't make any sense, sorry.
> 
> I assume you used the standard Linux installation method. Go to a folder where you can access the files. Do "ls -l" to list owners and permissions. Then in Linux go to a folder where you can't access the files, do "ls -l". See if there is a difference in owners or permissions.

Yes, but how do you go about fixing this?
Does the filebrowser config file have a setting for this?
Does something need to be chowned or chmoded?
How to make it act like Cpanel Filemanager with access to all directories?
Thanks!

nb I have this installed on Yunohost.
