### ISSUE TITLE
Add a Download Event for the Command Runner

### ISSUE THREAD

**Issue by sebcourant** [filebrowser/filebrowser#2534]
**Is your feature request related to a problem? Please describe.**
Trying to log Downloads for users. I was using the "Save" event after assuming wrongly it meant Download.

**Describe the solution you'd like**
Add a DOWNLOAD event to the list of possible triggers here : https://filebrowser.org/configuration/command-runner

**Comment by sebcourant** [comment]
Just noticed this discussion here : 
https://github.com/filebrowser/filebrowser/discussions/1366
which seems related but nobody picked it up since it was created

**Comment by sebcourant** [comment]
Noticed this discussion which is related, but that nobody picked up : 
https://github.com/filebrowser/filebrowser/discussions/1366

**Comment by sebcourant** [comment]
Anyone looking into this ?

**Comment by sebcourant** [comment]
anyone ?

**Comment by sbocquet** [comment]
+1

**Comment by kongdori** [comment]
+1
