### ISSUE TITLE
Files are created with execute permissions (755) instead of the standard 644

### ISSUE THREAD

**Issue by heisenberg2980** [filebrowser/filebrowser#2535]
**Description**
While testing this package I realised the files created/uploaded by the users are created with execute permissions (755)

**Expected behaviour**
Files should be created with the standard 644 permissions

**How to reproduce?**
Just create a file with any user and check the file permissions

**Comment by o1egl** [comment]
Nice point. Should we use 664 instead? 
owner: read/write
group: read/write
other: read

**Comment by heisenberg2980** [comment]
As they are currently created with 755, which means group don´t have write permissions, I assumed 644 would be enough

**Comment by heisenberg2980** [comment]
@o1egl has this been updated?

**Comment by jkablan** [comment]
Could this be made configurable. I'd prefer my files created with permissions 660. Is there a reason to give other read permission?

**Comment by itschasa** [comment]
> Could this be made configurable. I'd prefer my files created with permissions 660. Is there a reason to give other read permission?

please make this a feature

**Comment by domme1908** [comment]
Could you make these values configurable? We have a use case where files are managed not only by Filebrowser but also by a samba connection. With the restrictive 0664 permission we just can't.

**Comment by domme1908** [comment]
@Nerahikada @heisenberg2980

**Comment by domme1908** [comment]
@Nerahikada @heisenberg2980 @o1egl @hacdias any chance you had time to look into this issue?
