### ISSUE TITLE
Android Termux 运行 filebrowser 出错

### ISSUE THREAD

**Issue by laisc7301** [filebrowser/filebrowser#2536]
**Description**

```
~/.filebroswer/filebrowser -a 0.0.0.0 -p 8080 -r /storage/emulated/0
Segmentation fault
```
**Expected behaviour**

**What is happening instead?**

**Additional context**

* filebrowser version: 2.23.0
* Termux application version: 0.118.0 (118)
* Android OS version: 10
* Device model: KOZ-AL00

**How to reproduce?**

**Files**

**Comment by YTLoudYN** [comment]
you can try to download zerotermux 
zerotermux provides direct installation filebrowser

![QQ图片20230710115445](https://github.com/filebrowser/filebrowser/assets/131869902/dc351c28-412f-48f7-a656-9e768d400d77)
