### ISSUE TITLE
Bug : cannot play MPG file

### ISSUE THREAD

**Issue by Silloky** [filebrowser/filebrowser#2540]
**Description**
I have an .MPG video file.
Filebrowser shows it in the interface. If I click, the player buffers, stops, and the video doesn't start.

**Expected behaviour**
Once clicked and buffered, the video file should play.

**What is happening instead?**
It buffers for a few seconds, and then nothing happens.
No error message, I don't expect anything to be in the logs.

**Additional context**

**How to reproduce?**
1. Import an .mpg file.
2. Click on it to play

**Files**

**Comment by ghost** [comment]
The file might be encoded in HVEC (h265) and the server's processor might be too old to be able to play back this codec. Use VLC to check the codec of the file. If it is HVEC, re-encode using H264.
