### ISSUE TITLE
frontend support node.js 18 lts and openssl 3.x

### ISSUE THREAD

**Issue by vndroid** [filebrowser/filebrowser#2545]
**Is your feature request related to a problem? Please describe.**

It can not be building the image via node.js 18 lts (openssl 3.x inside).

**Describe the solution you'd like**

Can be built use [node:lts-alpine3.18](https://github.com/nodejs/docker-node/blob/d9c01570c0f72a40cbaece69c378d7c8187c56e9/18/alpine3.18/Dockerfile)

**Describe alternatives you've considered**

**Additional context**

**Comment by o1egl** [comment]
Currently frontend uses node 16. You can crate a PR to upgrade it to node 18

**Comment by vndroid** [comment]
node 16 based openssl 1.1.1, but node 18 based openssl v3.x, I can not build it on node 18, I don't know what I can do for you.

**Comment by FabioLolix** [comment]
Bump
