### ISSUE TITLE
I keep getting connection aborted when trying to upload training files and ckpt file

### ISSUE THREAD

**Issue by jvosborne** [filebrowser/filebrowser#2549]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by jvosborne** [comment]
I keep getting error connection aborted when uploading training files and ckpt files

**Comment by bigpoppaken7** [comment]
I'm getting the same error usually when doing multiple files. Single files will upload but multiple files (More than 2 will fail or stall every time)
