### ISSUE TITLE
Session Timeout for users

### ISSUE THREAD

**Issue by Tarsman013** [filebrowser/filebrowser#2554]
**Is your feature request related to a problem? Please describe.**
it is difficult to upload multiple, large files when after a period of not using the client, but still uploading, it logs the user out. This has caused multiple large transfers to fail

**Describe the solution you'd like**
the ability to set a session timeout for each user in minutes or hours (0 would be never)

**Describe alternatives you've considered**
none exist to my knowledge 

**Additional context**
n/a

**Comment by brianfromm** [comment]
@Tarsman013 This has been addressed in PR #5546 (see my comment on your other issue #2553 for full details).

You can now configure the session timeout globally using `tokenExpirationTime`. For existing installations:

```sh
filebrowser config set --tokenExpirationTime 6h
```

**Note:** Setting `0` for "never expire" is not supported. The maximum you can set is something like `8760h` (1 year) if you need very long sessions.

Also, this is currently a global setting, not per-user. All users share the same session timeout value.
