### ISSUE TITLE
Download speed or time left to upload

### ISSUE THREAD

**Issue by Tarsman013** [filebrowser/filebrowser#2555]
**Is your feature request related to a problem? Please describe.**
I am just curious to see upload and download speeds, since this is available outside of my LAN, it would be neat to see client speeds for upload and download as it happens 

alternatively a box that shows the time left in the upload would work (like gdrive has)

**Describe the solution you'd like**
add the ability to show speed for upload/download action(s)

**Describe alternatives you've considered**
watching drive and NIC activity on my server

**Additional context**
this is just a "I'm curious" and it would be neat

**Comment by RaheelJameel** [comment]
+1 to this feature request

**Comment by Calcifer97** [comment]
+1 to this feature request
