### ISSUE TITLE
Link that gets created when sharing a file is the Local IP and not the Hostname.

### ISSUE THREAD

**Issue by gearsovwar** [filebrowser/filebrowser#2560]
**Description**
When sharing a file the link generated is the servers local ip address instead of its hostname IE http://192.168.50.139:8080/share/xxxxxxxxxxx instead of fqdn such as example.com.

**Expected behaviour**
Generate URL based on server Hostname.

**What is happening instead?**
Generating link containing local IP.

**Additional context**
CentOS stream 9 non docker version.

**How to reproduce?**
Share any file.

**Comment by o1egl** [comment]
I can't reproduce it. If you are accessing filebrowser using ip:port, the share url will be generated using this information

**Comment by gearsovwar** [comment]
thanks for the reply i set the hostname with hostnamectl and reinstalled and it worked great thanks again.
