### ISSUE TITLE
<!-- Error 413 : Can't upload Videos (heavy files) on the plateforme, even if i Compress it (120mb). Is it possible to upload larger files on it? if yes, how? Thanks in advance>

### ISSUE THREAD

**Issue by Strandyvarius** [filebrowser/filebrowser#2565]
Hi, 

Error 413

I can't upload Videos (heavy files) on the plateforme, even if i Compress it (120mb). Is it possible to upload larger files on it? if yes, how? Thanks in advance

**Comment by o1egl** [comment]
There are no restrictions on the file size. Probably you have a proxy (cloudflare, nginx, etc...) that limits your upload

**Comment by Strandyvarius** [comment]
@o1egl Thank you

**Comment by RavingSmurfGB** [comment]
Haha, i ran into the same issue when I used NGINX proxy manager and configured the file browser as a proxy host

specifying the IP and port in the URL solved it for me to :)
