### ISSUE TITLE
User directory not being generated.

### ISSUE THREAD

**Issue by gearsovwar** [filebrowser/filebrowser#2567]
**Description**
Settings in the image below are checked. When users signup and login it gives them access to /user/local/bin/users instead of creating a folder for that user.

![image](https://github.com/filebrowser/filebrowser/assets/77856085/1aca78c3-d4dd-40cb-b041-24f0b9a6cfdc) 

**Expected behaviour**
When a user that signs up and logs in a "home" directory is created for them.

**What is happening instead?**
User is not being generated a home folder and logs into the Base path for user home directories. 
![image](https://github.com/filebrowser/filebrowser/assets/77856085/02a76be9-8a47-4ba8-a458-975533802fbc)

**Additional context**
CentOS stream 9
What Journalctl -fu is showing for the filebrowser service during account creation. 
![image](https://github.com/filebrowser/filebrowser/assets/77856085/1a3df7c5-d438-4891-bd94-d90835b1827a)

What is also crazy is even if the settings are set to no permissions by default the user can still look at all folders and open any document.
![image](https://github.com/filebrowser/filebrowser/assets/77856085/c5fc402a-36e3-45dd-b6ac-2f4b72bd2549)

**How to reproduce?**
Create an account through signup method and login. ( manually creating an account generates home folder just fine)

**Comment by goldsoft8888** [comment]
You are a low-level error, and the latest version 2.24.0 still does not solve it. When new users create an account on the login page, the corresponding folder is not created. Instead, the main folder is displayed directly. This is a serious security issue.
"2.20.0 is normal, I can only roll back."

**Comment by lgh06** [comment]
yeah, seems every of their release not be tested. I stuck at v2.24.1 first step,  `filebrowser config init`.  
I will turn to cloudreve or sth else.

**Comment by ojmaster** [comment]
can this be fixed? im on 2.27.0 and im experiencing this issue aswell

**Comment by ojmaster** [comment]
leave the scope in `User Default Settings` to blank and it will generate the new directory in the set `Base path for user home directories` @g3ars0fwar
