### ISSUE TITLE
filebrowser doesn't refresh after upload 

### ISSUE THREAD

**Issue by jsdxyz** [filebrowser/filebrowser#2573]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by jsdxyz** [comment]
Hello, after I upload or download or whatever the web dosn't refresh itself, I must click on refresh icon of the browser, but this happen with google-chrome but with firefox it works very fine, I must say the filebrowser , I installed it with docker and with nginx-proxy and letsencrypt, maybe this ones can affect or not? I hope somebody can answer this issue

**Comment by tws101** [comment]
I believe this is the same issue 
https://github.com/filebrowser/filebrowser/issues/2568

I am having the issue as well
