### ISSUE TITLE
How to remove File Browser 2.23.0 Help?

### ISSUE THREAD

**Issue by ahmadjamli** [filebrowser/filebrowser#2574]
How to remove File Browser 2.23.0 Help?

**Comment by o1egl** [comment]
I assume the opposite way to how you installed it. How did you install it?

**Comment by ahmadjamli** [comment]
1. Download Docker desktop
2. In CMD run (docker pull filebrowser/filebrowser)
3. Then run (docker run -p chose a port like **8081**:80 filebrowser/filebrowser)
4. Go to your browser and type (localhost:**YOUR CHOSEN PORT**)
> 80 is your default docker port number.

**Comment by o1egl** [comment]
Then you stop and remove it in the docker desktop UI
