### ISSUE TITLE
config init: flag accessed but not defined: branding.DisableUsedPercentage

### ISSUE THREAD

**Issue by CorySanin** [filebrowser/filebrowser#2576]
**Description**
`filebrowser config init` no longer works. Likely related to #2136

**Expected behaviour**
Initialization and an exit code of 0

**What is happening instead?**
```
flag accessed but not defined: branding.DisableUsedPercentage
```

**Additional context**
N/A

**How to reproduce?**
`sudo docker run -it --rm -p 8080:80 filebrowser/filebrowser:v2.24.0 "config" "init"`

**Files**
N/A

**Comment by hdegorce** [comment]
Same with the amd64 release (no Docker): `./filebrowser config init -a "0.0.0.0" -p "$PORT" -b "$INSTALL_URL_PATH"`

**Comment by CorySanin** [comment]
Not fixed in 2.24.1.

**Comment by lgh06** [comment]
I had the same problem. windows x64 2.24.1

**Comment by lgh06** [comment]
For now I have to use an old version (2.23.0) to setup then update filebrowser.exe binary to 2.24.1

**Comment by sorsudev** [comment]
@o1egl does the pull request opened by @CorySanin resolve this issue?

**Comment by CorySanin** [comment]
@sorsudev not sure you meant to direct that at me.

#2596 from @putty182 resolves this for me:

```
$> sudo docker run -it --rm -p 8080:80 filebrowser:putty182-patch-1 "config" "init"

Congratulations! You've set up your database to use with File Browser.
Now add your first user via 'filebrowser users add' and then you just
need to call the main command to boot up the server.
...
```
