### ISSUE TITLE
403 forbidden left and right

### ISSUE THREAD

**Issue by huntson** [filebrowser/filebrowser#2577]
I recently installed FileBrowser on my QNAP unit via Docker.  I have the following set for the environment:

        environment:
            - PUID=1001
            - PGID=100

I know that this user has read and write access to the directory that is being passed as the root to look at.  Within FileBrowser under the admin user I can see all the files and folders present yet I cannot make any write/delete operations.  Each time I am greeted with a 403 error in the GUI and in the logs that says 'permission denied.'  Not sure why however so hopefully someone can give me a direction or things to try.

**Comment by o1egl** [comment]
Which docker image are you using?

**Comment by huntson** [comment]
That would be helpful, wouldn't it?

filebrowser/filebrowser:s6

**Comment by huntson** [comment]
Anyone?
