### ISSUE TITLE
Edit files like .htaccess

### ISSUE THREAD

**Issue by MikeMichel** [filebrowser/filebrowser#258]
hi,

is double click the only option to open the editor? i did not found an "edit" button. i want to edit a .htaccess file and wonder how to do it without renaming it.

cheers,

mike

**Comment by hacdias** [comment]
You just need to double click on it like any other file 😄

**Comment by MikeMichel** [comment]
this opens the download dialog

**Comment by zxl777** [comment]
I think this is a bug in v1.3.9.
When I double click on the file "messages.xml" will open edit view ,
But double click on the other file "config.yml" will open download view.


![image](https://user-images.githubusercontent.com/816448/32313102-0c5994c0-bf6f-11e7-97ac-f49fc09b23b6.png)
 
![image](https://user-images.githubusercontent.com/816448/32313185-8e8f4aac-bf6f-11e7-91d4-a58db1043883.png)
