### ISSUE TITLE
2.24.0 When using tus, baseUrl is called twice

### ISSUE THREAD

**Issue by maeryo** [filebrowser/filebrowser#2581]
**Description**
There is a problem where ${baseURL} may be called twice when uploading through tus.

The scenario below is reproduced:

1. ./filebrowser --baseUrl baseUrl
2. During the upload, a 404 occurs when POST is called as baseUrl/url/baseUrl/url is invoked
3. However, there is no redundant call in HEAD afterwards

As the const tusEndpoint of constants.js is transferred to the fetchURL of utils.js, the predefined baseURL is added once more to fetch.

To address this, if the baseURL already exists, it is removed before calling fetchURL.

Please see the following Pull Request. (https://github.com/filebrowser/filebrowser/pull/2579)

**Comment by mbbyn** [comment]
Thank you for this, we are facing a similar issue where POST returns 404, however only the `baseUrl` is duplicated, not the rest of the URL. e.g. `https://website/baseUrl/baseUrl/api/tus/[file]`.

Would appreciate it if you know which filebrowser version introduced this issue?

**Comment by maeryo** [comment]
@mbbyn 
Use release v2.24.1
😁
