### ISSUE TITLE
overlay does not hide when modal is closed

### ISSUE THREAD

**Issue by xasmirx** [filebrowser/filebrowser#2585]
**Description**
When you click on the "Info" icon in the top right corner you will get a modal window with filebrowser version info. When clicked "Ok" window is closed but a transparent overlay in the background still remains and it blocks clicking. The same issue appears on any modal window.

**Expected behaviour**
On the modal window close we expect gray overlay to disappear too.

**What is happening instead?**
Transparent overlay background remains after the modal is closed. That kind of behavior blocks the mouse clicks and it forces the user to refresh the browser to get to a normal state.

**Additional context**
The issue is probably related to CSS class .overlay which has animation properties defined:
`    -webkit-animation: show .1s forwards;
    animation: show .1s forwards;`
These properties are fine to be used when the overlay is about to be shown, but as soon `display: none;`  is triggered on modal close nothing happens and the overlay stays visible on the page.

**How to reproduce?**
Click on the "Info" icon - in the top right corner. Modal will pop out, click "Ok" and Overlay will remain on the page blocking any clicks.

**Files**
![overlay](https://github.com/filebrowser/filebrowser/assets/4052970/f2b4bd36-4866-4e49-bc59-491709368225)

**Comment by alvin0319** [comment]
The same happens for all overlays, like sharing files, renaming files, info, etc.

**Comment by maeryo** [comment]
Issue #2568 already addresses this issue.
PR #2582 contains a fix for this problem.
It hasn't been reviewed by the reviewers yet, but building with reference to that commit should resolve the issue.

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/issues/2568
