### ISSUE TITLE
OMV podman custom branding 

### ISSUE THREAD

**Issue by slehernaf** [filebrowser/filebrowser#2599]
Hi, I have a problem with my File Browser2.24.1. It is installed as a plugin on openmediavault 6.5.4-1 (Shaitan). I have slightly adjusted the settings to add the branding folder. 
`podman container inspect xxxxxxxxxxxx --format {{.Config.CreateCommand}}`
```[/usr/bin/podman run --conmon-pidfile /run/container-filebrowser-app.pid --cidfile /run/container-filebrowser-app.ctr-id --cgroups=no-conmon --pod-id-file /run/pod-filebrowser.pod-id -d --replace --pull=never --name=filebrowser-app -u 994:100 -v /var/lib/filebrowser/database.db:/database.db -v /var/lib/filebrowser/filebrowser.json:/.filebrowser.json -v /srv/dev-disk-by-uuid-2c237cc4-bfc3-4c55-a9a4-14cd9709adad/samba/:/srv/ -v /var/lib/filebrowser/branding/:/branding/ docker.io/filebrowser/filebrowser:latest]```
To the folder `/var/lib/filebrowser/branding/` I put the data obtained from realfavicongenerator.net .
`find /var/lib/filebrowser/ -type f`
```/var/lib/filebrowser/branding/img/icons/android-chrome-192x192.png
/var/lib/filebrowser/branding/img/icons/android-chrome-512x512.png
/var/lib/filebrowser/branding/img/icons/apple-touch-icon.png
/var/lib/filebrowser/branding/img/icons/favicon.ico
/var/lib/filebrowser/branding/img/icons/favicon-32x32.png
/var/lib/filebrowser/branding/img/icons/favicon-16x16.png
/var/lib/filebrowser/branding/img/icons/mstile-150x150.png
/var/lib/filebrowser/branding/img/safari-pinned-tab.svg
/var/lib/filebrowser/filebrowser.json
/var/lib/filebrowser/database.db
```
Going into the web interface, I changed the branding settings like this
![image](https://github.com/filebrowser/filebrowser/assets/76738799/e88576b4-3fd0-4db0-b4df-020fb2592ff9)
But at the same time, the standard logo remained.
![image](https://github.com/filebrowser/filebrowser/assets/76738799/03c42d8a-3302-4c29-9da4-5f57cec9afaa)
![image](https://github.com/filebrowser/filebrowser/assets/76738799/d60b8030-25e6-46f6-a930-ab6aad019fc2)

What do I need to do?
P.S. I tried to log in from another device and clear the browser data

**Comment by 2lag** [comment]
Did you ever get this working? I made the same changes and nothing changes in the file browser.
