### ISSUE TITLE
Command Runner: trigger before_upload, after_upload not working

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2600]
**Description**
v2.24.1

Command Runner: trigger before_upload, after_upload not working

**Expected behaviour**
run next command:
```
echo "FILE $FILE, SCOPE = $SCOPE, TRIGGER = $TRIGGER, USERNAME = $USERNAME, DESTINATION = $DESTINATION " >> command.log.txt
```

**What is happening instead?**
nothing is happened

**Additional context**
run command via PowerShell

after_delete
before_delete 

woks fine!

**Comment by Nayruden** [comment]
I am seeing the same thing on v2.25.0 (Docker s6). I've tried everything I can think of, but it never seems to be called under any condition.
