### ISSUE TITLE
Move file operations to context menu

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2609]
Issue:

The current file manager system has a toolbar with a number of buttons for file operations, such as copy, paste, delete, and rename. However, this toolbar can be cluttered and difficult to use, especially for users who do not use all of the file operations frequently.

Proposal:

The proposed solution is to move all of the file operations to the file context menu. This would make the file manager system more streamlined and easier to use. 

Except Upload file button of course, this button can remain in the toolbar 

Benefits:
- A more streamlined and user-friendly 
- Easier access to file operations

**Comment by gtsteffaniak** [comment]
I have fork I have been working on that I did this exact thing this week on v0.1.3 (latest). Maybe its worth checking out.

https://github.com/gtsteffaniak/filebrowser
