### ISSUE TITLE
Unable to use the filemanager with IE11 (Windows 7 x64)

### ISSUE THREAD

**Issue by magikstm** [filebrowser/filebrowser#261]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Caddy v0.10.10 (non-commercial)
http.filemanager v1.3.6

Used on Windows 7 x64.
### 2. What is your entire Caddyfile?
```
:2015 {
	root F:/caddy-filemanager-test
	filemanager /admin ./admin {
		no_auth
	}
}
```

### 3. What are you trying to do?
Visit the filemanager with IE11.

### 4. What did you expect to see?
The filemanager.

### 5. What did you see instead (give full error messages and/or log)?
A loading screen of the filemanager that never stops loading. (I waited 30s locally)

It works perfectly in Firefox (latest) and Chrome (latest).

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Use the Caddyfile above and try to visit the filemanager with IE11 on Windows 7 x64.

![untitled2](https://user-images.githubusercontent.com/24783458/31875075-8307a5ee-b79a-11e7-85e6-b46a96179fed.png)

**Comment by drlifeng** [comment]
The same as you by use IE11 . It also Can not be displayed correctly with Chrome .It only works with Firefox.

**Comment by hacdias** [comment]
Hey! Could you please check if the developer console shows any error, please?

**Comment by magikstm** [comment]
The IE11 Developer Console mentions these:
```
HTML1300: Navigation occurred.
File: files
SCRIPT5022: [vuex] vuex requires a Promise polyfill in this browser.
File: vendor.44036de40396f416cb9a.js, Line: 1, Column: 52284
```

![261-1](https://user-images.githubusercontent.com/24783458/31919229-f5480614-b82e-11e7-81c1-0dab7ddfec9f.png)

![261-2](https://user-images.githubusercontent.com/24783458/31919236-f9339c84-b82e-11e7-8345-7b612746938b.png)

**Comment by hacdias** [comment]
File Manager is aimed to be used with the latest browsers. It works well on Chrome, Firefox, Safari (both on Mac and Mobile) and Chrome mobile.

**Comment by magikstm** [comment]
IE11 is still about 2.5% of users and it seems to affect other browsers a bit. I do have a few users still using this browser.

Could it be resolved by adding a polyfill like this?
https://maketips.net/tip/321/fix-vuex-requires-a-promise-polyfill-in-this-browser

Or this?
https://github.com/stefanpenner/es6-promise

**Comment by hacdias** [comment]
@magikstm, I don't think I should support IE on File Manager. It would increase the final binary since I would have to inject many features. It doesn't even support 'startsWith' for strings.

**Comment by HenryQW** [comment]
Strange enough that my instance of filebrowser is not fully functioning on Safari (macOS 10.13.2), namely control multi-select. I tried disabling every safari extension with no luck. It works on Chrome though.

**Comment by vvyoko** [comment]
@hacdias 
anyone use the kindle pw3?
it have the same errors like this.
i think because it is not the latest browsers.,..
the kindle browser even cant suport ftp....
so i search the http file share and find this.
what sad~
hope can suport this...

sorry for my bad english.

                                                     Best or Best Wishes

**Comment by Platway** [comment]
@hacdias , if Filebrowser is not meant to support IE (or certain version ranges of it), is it possible to pop up a msg box informing IE users that their browsers are not supported? Thank you and have a nice day!

**Comment by Equim-chan** [comment]
@Platway Good point. I think we may try something like http://outdatedbrowser.com.

**Comment by Platway** [comment]
@Equim-chan , I've just checked out Outdated Browser, and that is amazing! Thank you!
