### ISSUE TITLE
Can't create or remove files or map's

### ISSUE THREAD

**Issue by NicoWeij** [filebrowser/filebrowser#2610]
**Description**
When using Filebrowser 2.22.4 ...
If i select a file or map to delete i get the message "403 Forbidden".
For data storage i use a WD external diskdrive.
When i try  at the Raspberrypi itself it works fine.

I got admin status so i don't know what to do.

The used system is dietpi with al update and upgrades on RaspberryPi 4B (aarch 64)
In config read only is not selected for the external drive.

**Comment by o1egl** [comment]
Are you sure that the user that runs filebrowser has access to this drive? Which error is logged on the server side?

**Comment by NicoWeij** [comment]
After changing the folder i could't delete to 777 the problem was solved.
thx for your attention.
