### ISSUE TITLE
Uploading to read-only directory causes internal server error

### ISSUE THREAD

**Issue by SeanDS** [filebrowser/filebrowser#2611]
**Description**

I was trying to upload file to read-only directory.

**Expected behaviour**

I expected the software not to allow me to click the "Upload" button, or otherwise inform me an upload would not be possible.

**What is happening instead?**

The software appears to allow the upload to go ahead, but a red popup appears with "500 Internal server error" and the file is (obviously) not uploaded.

**Additional context**

I have the entire `/srv` directory in the Docker image mounted read-only, as I just need the file browser to browse files, not modify or upload new ones.

**How to reproduce?**

Try to upload a file to a directory to which the server user has no write permission.

**Files**

**Comment by SeanDS** [comment]
Bump

**Comment by andrewrabert** [comment]
Still an issue. Not completed.
