### ISSUE TITLE
cant upload

### ISSUE THREAD

**Issue by myeputrap** [filebrowser/filebrowser#2621]
**Description**

Multiple selection enabled

clear
chevron_right
Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/tus/be-service-notification/config-dev.zip?override=false, response code: 405, response text: , request id: n/a)

**Expected behaviour**

Able to upload

**What is happening instead?**

look above

**Additional context**

lokk above

**How to reproduce?**

**Files**

zip and yaml

**Comment by noahrdl** [comment]
Are you using cloudflare as cdn?

**Comment by idoodler** [comment]
Same issue here. I am using cloudflare

**Comment by Orkopaede** [comment]
I also have this issue. Did someone found a solution yet? I'm also using cloudflare.

**Comment by arsain** [comment]
Also having this issue, using Cloudflare as well

**Comment by o1egl** [comment]
Check https://github.com/filebrowser/filebrowser/issues/2593#issuecomment-1720153087
