### ISSUE TITLE
Migrate Frontend from Vue 2 to Vue 3

### ISSUE THREAD

**Issue by o1egl** [filebrowser/filebrowser#2623]
As part of our ongoing efforts to keep the Filebrowser project up-to-date and aligned with the latest technologies, we're considering a migration of our frontend codebase from Vue 2 to Vue 3.

Vue 3 brings enhanced performance, new features, and improved maintainability, which I believe will greatly benefit our project. However, this migration is not trivial and requires a good understanding of the changes between Vue 2 and Vue 3.

**What Needs to Be Done:**

- Analyzing the Current Codebase: Assess the existing Vue 2 code to identify areas that need updating or refactoring to align with Vue 3.
- Migrating Components and Libraries: Update existing components, directives, and libraries to be compatible with Vue 3.
- Testing: Ensuring that all functionality remains intact and works as expected after the migration.
- Documentation: Documenting any significant changes or decisions made during the migration.

**How You Can Help:**
If you have experience with Vue 3 or have an interest in learning and working on this migration, your contribution would be highly appreciated! You can start by:

- Reviewing the existing Vue 2 codebase
- Suggesting a migration plan
- Working on specific tasks related to the migration

If you would like to work on this issue, please comment below or reach out directly. Any help, even just advice or pointers, would be greatly appreciated.

Additional Resources:
[Vue 3 Migration Guide](https://v3-migration.vuejs.org/)
[Vue 3 Documentation](https://vuejs.org/guide/introduction.html)

Thank you for your interest in contributing to Filebrowser, and I look forward to collaborating with you on this exciting upgrade!

**Comment by kloon15** [comment]
I can kick this off with a PR of migrating the current tooling to Vite 4. Sadly i do not have any experience with Vue itself but i might be able look into it when i have more free time.

**Comment by axriosn** [comment]
I've taken a look at the code for the frontend and would love to give it a shot at updating it to Vue 3. It doesn't seem _too_ difficult but it would obviously take some time. There are a few libraries that would need alternatives but that should be pretty straightforward.

**Comment by kloon15** [comment]
> I've taken a look at the code for the frontend and would love to give it a shot at updating it to Vue 3. It doesn't seem _too_ difficult but it would obviously take some time. There are a few libraries that would need alternatives but that should be pretty straightforward.

I have been giving this a try in my limited time, maybe we could collaborate together? Im not sure how thats done, kind of a newbie on github.

**Comment by baur** [comment]
Please, add unique class or ID for every elements (buttons, navitems e.t.c.) #2604 also frontend issue #2603

**Comment by o1egl** [comment]
@baur feel free to contribute [here](https://github.com/filebrowser/filebrowser/pull/2689)

**Comment by kloon15** [comment]
The PR is ready, whenever u have time to review @o1egl

**Comment by brett-james-rocketlab** [comment]
I think you'll want to edit your PR to remove the stale tag if you are able to do so.

**Comment by kloon15** [comment]
> I think you'll want to edit your PR to remove the stale tag if you are able to do so.

Its already been merged.
