### ISSUE TITLE
Cant upload files 

### ISSUE THREAD

**Issue by noahrdl** [filebrowser/filebrowser#2624]
**Description**
Cant upload files using cloudflare 

**Expected behaviour**
Can upload because of the new implementation tus

**What is happening instead?**
Error of http request

**Additional context**
![Screenshot_2023-08-08-11-45-34-192_org mozilla firefox](https://github.com/filebrowser/filebrowser/assets/113783551/a9f24148-ab59-4853-8c64-c3e92a535d5f)

**How to reproduce?**
Using cloudflare as cdn and uploading files

**Files**
all type of files

**Comment by Orkopaede** [comment]
Hi, i have the same issue. Did you find a solution yet?

**Comment by xd003** [comment]
I am facing the very same issue while uploading certain types of files
Hopefully it will be fixed soon

**Comment by arsain** [comment]
Having the same issue with most file types

**Comment by kokowilly** [comment]
having the same issue, I using CloudFlare Zero Trust and Docker, I can upload txt file, but not other binary types. such as jpg and png.

**Comment by kokowilly** [comment]
```
API: https://***/api/tus/Math%20-%20PlusMinTime-1.pdf?override=false

Response: 201 Created
```

```
https://***/api/tus/Math%20-%20PlusMinTime-1.pdf?override=false

Status
405
Method Not Allowed
VersionHTTP/2
Transferred598 B (0 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem
```

The issue might comes from CloudFlare

**Comment by arsain** [comment]
CloudFlare seems to be the reason. Found relevant discussion from 2021, that suggests conditionally disabling their firewall: [https://community.cloudflare.com/t/impossible-to-upload-files-to-my-site/254856](url).
But interface looks different now, had not success disabling it so far.

**Comment by xd003** [comment]
https://github.com/filebrowser/filebrowser/issues/2624
https://github.com/filebrowser/filebrowser/issues/2621
https://github.com/filebrowser/filebrowser/issues/2650
https://github.com/filebrowser/filebrowser/issues/2588
https://github.com/filebrowser/filebrowser/issues/2593
https://github.com/filebrowser/filebrowser/pull/2145

All these seem related to the same issue

**Comment by arsain** [comment]
Also this workaround fixed the issue for me: [https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304](url)

**Comment by arsain** [comment]
Also this workaround fixed the issue for me: https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304

**Comment by Cretezy** [comment]
I was having the same issue using nginx (with Nginx Proxy Manager) locally, without Cloudflare.

I fixed it by disabled the "Cache Assets" option.

**Comment by aziz3000** [comment]
I also have the same problem..
Docker filebrowser+Nginx+Cloudflare can only upload *.txt.  Error code 405 when uploading files such as images and videos

**Comment by wmtbuddhika** [comment]
I have the same.
Using: Kubernetes, Istio, Cloudflare.
User: admin

And yes, this did the temp fix trick: https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304

<img width="1440" alt="image" src="https://github.com/filebrowser/filebrowser/assets/28972432/a701cc4a-5971-4230-9aee-6ddc33bbe989">

**Comment by o1egl** [comment]
Check https://github.com/filebrowser/filebrowser/issues/2593#issuecomment-1720153087

**Comment by xd003** [comment]
> Check [#2593 (comment)](https://github.com/filebrowser/filebrowser/issues/2593#issuecomment-1720153087)

Don't we no longer need to create a PageRule as this was pushed https://github.com/filebrowser/filebrowser/commit/36af01daa6e04005ce3d18985eebaeef06f7393d ?
