### ISSUE TITLE
docker: v2.24 no longer starting with custom PUID/PGID and database volume mapping

### ISSUE THREAD

**Issue by eduardocorral** [filebrowser/filebrowser#2633]
**Description**
Attempting to start
- as a container
- mapping /database volume
- custom PUID/PGID user/group id

**Expected behaviour**
I should be able to start the process with database mapped from outside the container, and custom GID/UID.

**What is happening instead?**
Fails to start with
```
2023/08/10 00:45:15 open /database/filebrowser.db: permission denied
2023/08/10 00:45:16 open /database/filebrowser.db: permission denied
```

**Additional context**
- Using filebrowser as a container
- s6 version (v2-s6)

**How to reproduce?**
Get the current user uid/gid
```
$ id
uid=1000(myuser) gid=1000(myuser) groups=1000(myuser),974(docker),...
``` 
Create folder to mount as /database
```
mkdir /tmp/fb
```
Start with
```
docker run --rm -p 8080:80 -e PUID=1000 -e PGID=1000 -v /tmp/fb:/database filebrowser/filebrowser:v2-s6
```
output shows
```
...
───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
2023/08/10 00:48:42 open /database/filebrowser.db: permission denied
2023/08/10 00:48:43 open /database/filebrowser.db: permission denied
...
```

**Files**
N/A

**Comment by edvinas31** [comment]
I can add that this is also relevant for us. Our requirement was to be able to run filebrowser with custom UID and GID and now it is not working after the last upgrade. We had to switch back to v.2.23.0-s6 https://hub.docker.com/layers/filebrowser/filebrowser/v2.23.0-s6/images/sha256-4df72e6702ba264465c2932938ba9a5e40eaa1a29ef81440511112a7ef04d899?context=explore

Is anyone looking at it?

**Comment by bipy** [comment]
After testing version v2.25.0:

The s6 image incorrectly modifies the ownership of the mapped volume during creation. 

A temporary solution is to use a non-s6 image or **manually** correct the ownership using the `chown` command.

**Comment by flammable** [comment]
I just started using File Browser, and specifically avoided the s6 image because of this bug. The docs don't really explain why I'd want to use the s6 or non-s6 image - just that both options are available. If this has been fixed, could I ask why one would prefer the s6 image?

**Comment by Morantoine** [comment]
Same issue here, following.

**Comment by ForrestFeng** [comment]
Same issue here, following.

**Comment by techsolo12** [comment]
Same issue here, following.
Can we open the issue again?

**Comment by garylavayou** [comment]
Same issue with version `v2.31.1/bb5d1920`.
