### ISSUE TITLE
Not able to upload files using non admin users. 

### ISSUE THREAD

**Issue by ShahiRohit** [filebrowser/filebrowser#2639]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by jniggemann** [comment]
We can't help you if you don't provide details.

**Comment by monkiki** [comment]
I got this error when trying to upload any file with a non-admin user:

`Upload failed: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: /api/tus/users/hibernate_search_reference.pdf?override=false, response code: 403, response text: 403 Forbidden , request id: n/a)`

- Using Docker image and Traefik
- File Browser v2.24.2

Do you need any other info?
