### ISSUE TITLE
Option to view photos in small resolution/LQ by default

### ISSUE THREAD

**Issue by eightren** [filebrowser/filebrowser#2642]
**Is your feature request related to a problem? Please describe.**
Sometimes the original image is too large and it takes a few seconds to load. I would like for a way to view images in LQ/small resolution by default

**Describe the solution you'd like**
If a "view images in HQ/LQ" toggle in the settings can be added, that would be great.

**Describe alternatives you've considered**
I tried to search for possible commands to execute when opening images but I don't know what else to do

**Comment by wheat0r** [comment]
Add an option to select resolution, or remembering last selection, both are good.
