### ISSUE TITLE
Move upload box and notifications area to different corners

### ISSUE THREAD

**Issue by RahulR100** [filebrowser/filebrowser#2644]
**Is your feature request related to a problem? Please describe.**
When an error pops up during upload, it covers the upload box until dismissed. If multiple errors appear, they can stack 5 high and obscure the upload window.

**Describe the solution you'd like**
Move notifications to bottom left corner.

**Describe alternatives you've considered**
Clicking on each notification... but this gets annoying

**Comment by jniggemann** [comment]
This bug is still open until the PR is merged or another solution is found.
