### ISSUE TITLE
Hello, may I ask if it supports online editing of office files such as Word, Excel, and PowerPoint

### ISSUE THREAD

**Issue by cfy3133** [filebrowser/filebrowser#2646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kloon15** [comment]
No, that would require the integration of a document server capable of handling those files such as ONLYOFFICE.
Maybe if more ppl request it, might be feasible to add: https://github.com/ONLYOFFICE/document-editor-vue

**Comment by jniggemann** [comment]
There's PR #1420, not sure about the status though.

**Comment by letshin** [comment]
Its pending a code review, I'm not sure if there are any other issues to it.

**Comment by cfy3133** [comment]
Thank you for your reply

**Comment by turbcool** [comment]
OnlyOffice intergration is a work-in-progress #2954
