### ISSUE TITLE
Internal Server Error when trying to copy a file without first selecting a folder

### ISSUE THREAD

**Issue by magikstm** [filebrowser/filebrowser#265]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Caddy v0.10.10 (non-commercial)
http.filemanager v1.3.6

Used on Windows 7 x64.
### 2. What is your entire Caddyfile?
```
:2015 {
	root F:/caddy-filemanager-test
	filemanager /admin ./admin {
		no_auth
	}
}
```

### 3. What are you trying to do?
Copy a file to another folder.

### 4. What did you expect to see?
The "Copy" button being greyed out or unavailable if no folder is selected or at least no error when trying to copy without first selecting a folder.

### 5. What did you see instead (give full error messages and/or log)?
An "Internal Server Error" modal window in the right corner.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Use the caddyfile above with at least one file that can be copied in the ./admin folder.

![untitled4](https://user-images.githubusercontent.com/24783458/31876658-7843c424-b7a1-11e7-8ea8-77a1e8c15aca.png)

**Comment by hacdias** [comment]
When you don't select a folder, you are telling FIle Manager to copy it to the "Currently navigating on" path. In that case, you're trying to move it to where it is right now, so it will generate an error.

**Comment by hacdias** [comment]
Copy/Move greyed out!
