### ISSUE TITLE
Allow Upload in shared folders

### ISSUE THREAD

**Issue by nomis-on** [filebrowser/filebrowser#2652]
**Is your feature request related to a problem? Please describe.**
I wanted to use filebrowser to create a folder where everyone with the link could upload their pictures and respectively download them, without having to login at all. 

**Describe the solution you'd like**
Allow Upload in shared folders, same as #1435 (but that issue was closed already).
Add an additional check box per share where the admin can decide if upload is allowed.

**Describe alternatives you've considered**
I tried the noauth method, but I dont think it is comparable since
1) Everyone has access to all settings and can change anything
2) Everyone who knows the plain filebrowser URL can access the data. By using a shared folder with its random generated URL it is ensured that only people with this specific link can access the folder.

**Additional context**
Nextcloud has exactly this feature where you can decide per shared folder if it is read only, uploadable, or uploadable and editable. But I like the simplicity of filebrowser compared to Nextcloud.

**Comment by tanrak** [comment]
This feature has been requested many times, as seen in the forum (for example #1218 or #1726 or #2107). Unfortunately, no one seems to find the interest to implement this.

Edit: Especially for non-technical users, this would be an easy way to send data to the owner. But also to quickly send a link to someone for an upload without having to create an account every time. Each of the big players (Nextcloud/OwnCloud, Seafile or OCIS) has this feature for a reason.

**Comment by helloworldbugs** [comment]
Strongly agree

**Comment by zottelchin** [comment]
Would like the feature too! Has someone started the implementation yet?

**Comment by ediazrod** [comment]
II love have this feature is a request on many of my customers..

**Comment by litmount** [comment]
Same here! This is what is keeping me from using it for a file run replacement.

**Comment by tulku** [comment]
This is probably the only I'd like Filebrowser to have. Other than this, it is a great tool!
