### ISSUE TITLE
FIX FOR CLOUDFLARE

### ISSUE THREAD

**Issue by noahrdl** [filebrowser/filebrowser#2653]
I got it working by setting the chunk uploads to 10MB, I'm using cloudflare and I'm on the latest version

![imagen](https://github.com/filebrowser/filebrowser/assets/113783551/273c1aab-fb95-4d6f-90c8-27624e62938a)

**Comment by noahrdl** [comment]
if its not working to you try also this fix

https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304

**Comment by liljohn360** [comment]
The settings shown here "10MB, 5 retries" seem to be the defaults, at least mine was already set to these. Still doesn't work for uploads > 100MB but my guess is this is a Cloudflare issue, not Filebrowser

**Comment by noahrdl** [comment]
> The settings shown here "10MB, 5 retries" seem to be the defaults, at least mine was already set to these. Still doesn't work for uploads > 100MB but my guess is this is a Cloudflare issue, not Filebrowser

did you make the second comment i made?

and of course I meant that files larger than 100mb work for me

**Comment by noahrdl** [comment]
> The settings shown here "10MB, 5 retries" seem to be the defaults, at least mine was already set to these. Still doesn't work for uploads > 100MB but my guess is this is a Cloudflare issue, not Filebrowser

did you make the second comment i made?

and of course I meant that files larger than 100mb work for me

**Comment by liljohn360** [comment]
What you referenced in the second comment appears to have fixed the issue for me, thanks

**Comment by Toasty777** [comment]
What do you use Cloudflare for?

**Comment by noahrdl** [comment]
hiding ip and for security

**Comment by o1egl** [comment]
Check https://github.com/filebrowser/filebrowser/issues/2593#issuecomment-1720153087
