### ISSUE TITLE
v2.24.2/184b7c14 ignores -c config file, fails to start after importing the exported config

### ISSUE THREAD

**Issue by working-name** [filebrowser/filebrowser#2654]
**Description**

Firs time trying to get filebrowser going, standalone.

If I pass it -c ./config.json it will ignore it and start on 8080 and other defaults.

If I export the config, modify it to my liking and then import it, it fails to start but does not say why, it just hangs. 

The executable creates the .db file in $PWD which is a tad bit ... interesting. I guess I'd have to always pass it a path to the db file? Is there a central location where it always looks first before $PWD?

**Expected behaviour**

Parse config passed via -c and apply settings found in it.

Put out some error message of why it won't start with a specific config - is there a syntax error? Is there a misspelling of an option? Invalid JSON?

**What is happening instead?**

## starting with a custom config:

```shell
deb@ny01:~$ filebrowser
2023/08/17 02:32:02 No config file used
^C
deb@ny01:~$ filebrowser -c onedrive/.settings.json
2023/08/17 02:32:17 Using config file: onedrive/.settings.json
```

No further logs.

Also where it says no config file used, that's incorrect, I'm assuming you stored pertinent settings in the .db file located in $PWD. Otherwise it makes no sense for it to behave the same as after I do an import of the modified config.

## Starting with a config passed via -c after `rm -f filebrowser.db` in $PWD:

```shell
deb@ny01:~$ filebrowser -c onedrive/.settings.json
2023/08/17 02:33:31 Using config file: onedrive/.settings.json
2023/08/17 02:33:31 Listening on 127.0.0.1:8080
```

It says it's using the config file, but ignores 100% of it.

**Additional context**

**How to reproduce?**

Install version mentioned in title on Debian 11.7, run it.

**Files**

**Comment by working-name** [comment]
You mean it's being ignored?

**Comment by CreMindES** [comment]
I can reproduce this bug, even with 2.25.0.
