### ISSUE TITLE
Ability to highlight a file/folder by pressing a letter

### ISSUE THREAD

**Issue by eightren** [filebrowser/filebrowser#2655]
**Describe the solution you'd like**
Same functionality as any other file explorer. When you press a letter, the file/folder starting with the same letter is highlighted

**Describe alternatives you've considered**

**Additional context**

**Comment by noahrdl** [comment]
what i do to highlight a folder its using the custom.css

this is an example of what i have 
![Screenshot_2023-08-20-20-13-46-852_org mozilla firefox](https://github.com/filebrowser/filebrowser/assets/113783551/7915ccca-cde9-4bea-a5b8-5a061fba2810)

in the custom css you have to put this code:
#listing .item[aria-label$="(here you put the name of the folder"] div i {
    color: #aaa;
}

**Comment by niubility000** [comment]
Just uncheck "Use single clicks to open files and directories" in setting-profile settings.
