### ISSUE TITLE
Large files often terminate download early when sharing links

### ISSUE THREAD

**Issue by pekempy** [filebrowser/filebrowser#2656]
**Description**
Have searched through both open and closed issues for this but majority appear to be upload related. I sometimes need to share large files (sometimes around 10GB) and while the download starts off okay, it seems the connection terminates early and a corrupt .zip ends up being the final file.  e.g. a 27GB MB4 ended up "Finishing" at 4.2GB

**Expected behaviour**
The connection should stay active until the full file has been downloaded. Alternatively, a way to 'resume' downloads if a file sum does not match?

**What is happening instead?**
Logs in Docker did not display anything.
File downloaded was 4.2GB instead of the 27.9GB provided by the server

**How to reproduce?**
1. Share a large (>8GB) file link
2. Attempt to download the file (tried using Firefox, Chrome, and Edge)
3. Download will be terminated early before the full file is received from the server

**Comment by gtsteffaniak** [comment]
likely a newtwork issue between the container and the browser. Do you have any reverse proxy, vpn, or domain service you use to access the filebrowser? Is the network stable?

If nginx see https://serverfault.com/questions/820597/nginx-does-not-serve-large-files

This could also be mitigated in filebrowser by increasing the keepalive in http connections. So, its still worth having an issue open, but just giving suggestions to troubleshoot while you wait for devs to pick up this issue.

**Comment by pekempy** [comment]
Hey,

I use Caddy for my reverse proxy - it's over a stable connection as I've experienced the same when connecting via the direct IP over LAN. 

The caddyfile contains this, if it's any help:
```
domain1.com, domain2.com {
	reverse_proxy http://192.168.1.2:3333 {
		header_up X-Forwarded-Host {host}:3333
		header_up -Origin
		header_up -Referer
	}
}
```

I did have a check through filebrowser config files to see if there was any sort of variable I could set to increase the keepalive time but couldn't see anything, hence the issue :) 

Thanks, Appreciate the help.
