### ISSUE TITLE
Skip Login?

### ISSUE THREAD

**Issue by didvc** [filebrowser/filebrowser#2669]
Since I have firewall to whitelist IP addresses on the network side, the Filebrowser's software side access restriction is redundant for me, so I'd like to rahter disable, skip the login screen for all users, accesses on Filebrowser. 

In this issue, I'd like to: 

- a. request the feature that enables users to disable the login screen.
- b. know how to bypass the login screen modifying the source code or changing some settings.

Thanks.

**Comment by Shourai** [comment]
Hi there,

this feature already exists: https://filebrowser.org/configuration/authentication-method#no-authentication

### No Authentication
We also provide a no authentication mechanism for users that want to use File Browser privately such in a home network. 
By setting this authentication method, the user with id 1 will be used as the default users. 
Creating more users won't have any effect.

```
filebrowser config set --auth.method=noauth
```
This can also be done by setting an environmental variable, useful for docker compose
see: https://github.com/filebrowser/filebrowser/issues/2359

**Comment by didvc** [comment]
Hello. Oh, sorry that I didn't notice that part in the document. The config solved the problem exactly. Thanks for your help.

**Comment by alexindigo** [comment]
> Hi there,
> 
> this feature already exists: https://filebrowser.org/configuration/authentication-method#no-authentication
> 
> ### No Authentication
> We also provide a no authentication mechanism for users that want to use File Browser privately such in a home network. By setting this authentication method, the user with id 1 will be used as the default users. Creating more users won't have any effect.
> 
> ```
> filebrowser config set --auth.method=noauth
> ```
> 
> This can also be done by setting an environmental variable, useful for docker compose see: [#2359](https://github.com/filebrowser/filebrowser/issues/2359)

@Shourai do you know by any chance, how to use it inside docker container? Is it supported to be set in the config file, or environment variable?

**Comment by Shourai** [comment]
@alexindigo, I saw you already found your answer in a different closed issue.
However for posterity, my docker compose file with no-auth looks as following:

```
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - <volumes>
    environment:
      - FB_NOAUTH=noauth
```

**Comment by alexindigo** [comment]
@Shourai thank you, this is useful.

**Comment by alexindigo** [comment]
Hmm, for some reason it didn't work for me. Neither `FB_NOAUTH=noauth` nor `FB_NOAUTH=true` had any effect, it still requires me to login. (I did restart the container).

**Comment by dogeyoyo** [comment]
@alexindigo despite `noauth` it still requires admin user, try adding it manually (using cli or temporary container):
```bash
filebrowser users add admin admin --perm.admin=true -d $DB_PATH
```

**Comment by alexindigo** [comment]
@dogeyoyo 

I'm thinking to just roll out my own.
