### ISSUE TITLE
Auth persists

### ISSUE THREAD

**Issue by pituluk** [filebrowser/filebrowser#2670]
I noticed that server somehow knows that I'm logged in when I use incognito mode, so I tried logging in as admin on one window but then log out and log in as normal user in another browser
I noticed I could still send requests with fetch copied from admin session even though I was logged out from admin, I guess server still sees the x-auth as valid even though admin user already ended their session and is logged out
Imo server shouldn't accept these after user is logged out.

**Comment by o1egl** [comment]
Filebrowser uses JWT token for user sessions, and that is an expected behavior.
