### ISSUE TITLE
High CPU (5-20%) consumption even when not being used

### ISSUE THREAD

**Issue by ManiMatter** [filebrowser/filebrowser#2676]
**Description**
I run the latest version of filebrowser on docker. I observe that the average CPU usage for filebrowser ranges from 5-10% CPU, even when I am not using it (I don't even have a window open with it).

**Expected behaviour**
I would have expected filebrowser to be at 0-1% CPU when not being used

**What is happening instead?**
I see 5-10% CPU load even if I am not using filebrowser.

**Additional context**
I suspect some sort of caching / indexing that is happening. 
I write downloads into a folder that filebrowser has access to, and I suspect that causes continous caching/indexing or something of that sort.

**How to reproduce?**
I do not know, since I do not know what triggers the (what I perceive) high CPU load. 
I am using a Raspberry Pi 4, with Ubuntu 22.04 and latest version of Docker on it, with filebrowser mounted into it.

**Comment by o1egl** [comment]
I am unable to confirm this behavior. I have installed Filebrowser via docker on my Raspberry Pi 4 and it shows that it consumes 0 CPU when idle. Are you sure that no one is accessing it?

**Comment by ManiMatter** [comment]
I am 100%  confident nobody else is accessing it. Here is what I see in GLANCES:
![image](https://github.com/filebrowser/filebrowser/assets/124743318/509313ed-e83a-4f09-a17d-cd09d3df6092)

As you can see on the screenshot, the CPU usage jumped to 16%.
In the next second, it's back to 0. So it jumps up and down.

How are you measuring the CPU usage? Maybe that helps us getting to the bottom of this..

Parallel to glances, I also checked htop. There I only see 1.2% when when glances shows 16%.
So not sure whether I am chasing ghosts here... 

Although I'd say that even 1.2% seems high for an app that is supposed to be idle.

Any pointers appreciated.

**Comment by melwinek** [comment]
I confirm. Exactly the same is happening to me.
![image](https://github.com/filebrowser/filebrowser/assets/10649327/e7d0a646-1cfe-4124-bcf5-9646ed1bef54)

**Comment by melwinek** [comment]
I found a solution.
Insert: 
```
healthcheck: 
  disable: true
```
in docker-compose.yml solves the problem.

**Comment by ManiMatter** [comment]
Thank you @melwinek , this solved it for me, too!
