### ISSUE TITLE
Feature Request: Add thumbnails to pdfs

### ISSUE THREAD

**Issue by oregonpillow** [filebrowser/filebrowser#2679]
I saw thumnail creation is enabled for jpg,gif,png. I was wondering if it's possible to add it for pdf as well?
pdf is such a popular format I think there could be great interest in it. I use filebrowser for hosting a ton of pdfs, the only thing missing is this.

**Comment by realgeek** [comment]
I would also love this feature!

**Comment by utrost** [comment]
This would be my number one feature wish!
