### ISSUE TITLE
May I have a WebDAV without caddy?

### ISSUE THREAD

**Issue by liangshengzero** [filebrowser/filebrowser#268]
I'm using it without caddy.
I want to have webdav this function
May I asked to add it？

**Comment by hacdias** [comment]
Hello! This plugin doesn't provide WebDAV anymore. You might be referring to [caddy-webdav](https://github.com/hacdias/caddy-webdav) plugin. That plugin is designed to give Caddy WebDav features so there is no reason why it should be used without Caddy.

If you want to use WebDAV without Caddy, you might try to search for webdav servers. There are quite a few! 

Hope it helps!
