### ISSUE TITLE
How can I add multiple directories?

### ISSUE THREAD

**Issue by nxuu** [filebrowser/filebrowser#2680]
How can I add multiple directories? There are multiple hard disks.
for example
d:\pt
e:\pt
f:\pt
G\pt
h:\pt
i:\pt
J:\pt
k:\pt

**Comment by agnotrodna** [comment]
Good question! Have you found the answer?

**Comment by agnotrodna** [comment]
> How can I add multiple directories? There are multiple hard disks. for example d:\pt e:\pt f:\pt G\pt h:\pt i:\pt J:\pt k:\pt

**I FIND ANSWER!!!**

You just need to use "_mklink_" in cmd if you are using Windows. Just in case, I'll leave a link to the website that I used as an instruction,but it's in Russian.

[https://winitpro.ru/index.php/2021/03/03/ispolzovanie-simlink-ssylok-v-windows/](url)

**Comment by nxuu** [comment]
> 

thanks  i'll try this way

**Comment by nxuu** [comment]
> > 如何添加多个目录？有多个硬盘。例如 d：\pt e：\pt f：\pt G\pt h：\pt i：\pt J：\pt k：\pt
> 
> **我找到了答案!!**
> 
> 如果您使用的是Windows，则只需要在cmd中使用“_mklink_”。以防万一，我会留下一个指向我用作说明的网站的链接，但它是俄语的。
> 
> [https://winitpro.ru/index.php/2021/03/03/ispolzovanie-simlink-ssylok-v-windows/](url)

 i'll try this way

**Comment by agnotrodna** [comment]
A few days have passed. I attach a photo about the operability of this method. It works GREAT! For the server, this folder is located on disk D://, but as soon as you open it, the MOST IMPORTANT THING immediately goes to disk E: The server shows the load of DISK E://

https://imgur.com/a/kR62dWB

**Comment by agnotrodna** [comment]
> > > 如何添加多个目录？有多个硬盘。例如 d：\pt e：\pt f：\pt G\pt h：\pt i：\pt J：\pt k：\pt
> > 
> > 
> > **我找到了答案!!**
> > 如果您使用的是Windows，则只需要在cmd中使用“_mklink_”。以防万一，我会留下一个指向我用作说明的网站的链接，但它是俄语的。
> > [https://winitpro.ru/index.php/2021/03/03/ispolzovanie-simlink-ssylok-v-windows/](url)
> 
> i'll try this way

A few days have passed. I attach a photo about the operability of this method. It works GREAT! For the server, this folder is located on disk D://, but as soon as you open it, the MOST IMPORTANT THING immediately goes to disk E: The server shows the load of DISK E://

https://imgur.com/a/kR62dWB

**Comment by nxuu** [comment]
> 
Great. I tried your method and I added all four drives to filebrowser. Thank you very much🌹🌹🌹🌹🌹

**Comment by nxuu** [comment]
> > > > 如何添加多个目录？有多个硬盘。例如 d：\pt e：\pt f：\pt G\pt h：\pt i：\pt J：\pt k：\pt
> > > 
> > > 
> > > **我找到了答案!!**
> > > 如果您使用的是Windows，则只需要在cmd中使用“_mklink_”。以防万一，我会留下一个指向我用作说明的网站的链接，但它是俄语的。
> > > [https://winitpro.ru/index.php/2021/03/03/ispolzovanie-simlink-ssylok-v-windows/](url)
> > 
> > 
> > i'll try this way
> 
> A few days have passed. I attach a photo about the operability of this method. It works GREAT! For the server, this folder is located on disk D://, but as soon as you open it, the MOST IMPORTANT THING immediately goes to disk E: The server shows the load of DISK E://
> 
> https://imgur.com/a/kR62dWB

Great. I tried your method and I added all four drives to filebrowser. Thank you very much

**Comment by soulfulkhani** [comment]
> > How can I add multiple directories? There are multiple hard disks. for example d:\pt e:\pt f:\pt G\pt h:\pt i:\pt J:\pt k:\pt
> 
> **I FIND ANSWER!!!**
> 
> You just need to use "_mklink_" in cmd if you are using Windows. Just in case, I'll leave a link to the website that I used as an instruction,but it's in Russian.
> 
> [https://winitpro.ru/index.php/2021/03/03/ispolzovanie-simlink-ssylok-v-windows/](url)

heyy i am using windows. can you help me hpw to setup filebrowser so that i can use it over network rn i can only login through my pc . i dunno coding . if you can help me please .  using windows terminal

**Comment by L0garithmic** [comment]
This let's you have multiple directories, but search does not work. Been dealing with this for almost a year. Dev is NO help... To solve this, I just run a complicated powershell script to make a symlink of all the individual files. It's cancer, but works for now. The PS1 file is so I can update them when changes are made

```
Add-Type -TypeDefinition @"
using System;
using System.IO;
using System.Runtime.InteropServices;

public class SymbolicLinkUtil
{
    [DllImport("kernel32.dll")]
    public static extern bool CreateSymbolicLink(string symlinkFileName, string targetFileName, int flags);

    public const int SYMBOLIC_LINK_FLAG_FILE = 0x0;
    public const int SYMBOLIC_LINK_FLAG_DIRECTORY = 0x1;

    public static bool CreateSymbolicLinkFile(string symlinkFileName, string targetFileName)
    {
        return CreateSymbolicLink(symlinkFileName, targetFileName, SYMBOLIC_LINK_FLAG_FILE);
    }

    public static bool CreateSymbolicLinkDirectory(string symlinkFileName, string targetFileName)
    {
        return CreateSymbolicLink(symlinkFileName, targetFileName, SYMBOLIC_LINK_FLAG_DIRECTORY);
    }
}
"@

$sourceFolders = @(
    @{
        Source = "C:\Folder1"
        Destination = "C:\filebrowser\directories\Folder1"
    },
    @{
        Source = "D:\Folder2"
        Destination = "C:\filebrowser\directories\Folder2"
    },
    @{
        Source = "E:\Folder3"
        Destination = "C:\filebrowser\directories\Folder3"
    },
    @{
        Source = "F:\Folder4"
        Destination = "C:\filebrowser\directories\Folder4"
    },
    @{
        Source = "G:\Folder5"
        Destination = "C:\filebrowser\directories\Folder5"
    }
)

foreach ($folder in $sourceFolders) {
    $destDirectory = $folder.Destination
    if (Test-Path -Path $destDirectory) {
        Get-ChildItem -Path $destDirectory -Force | Remove-Item -Recurse -Force
    }
    else {
        New-Item -ItemType Directory -Path $destDirectory -Force | Out-Null
    }
    $files = Get-ChildItem -Recurse -File $folder.Source
    foreach ($file in $files) {
        $relPath = $file.DirectoryName.Replace($folder.Source, "")
        $destPath = Join-Path -Path $folder.Destination -ChildPath "$relPath\$($file.Name)"
        
        $destDirectory = Split-Path -Path $destPath
        if (!(Test-Path -Path $destDirectory)) {
            New-Item -ItemType Directory -Path $destDirectory -Force | Out-Null
        }
        
        try {
            $linkPath = Join-Path -Path $destDirectory -ChildPath $file.Name
            if (!(Test-Path -Path $linkPath)) {
                $isDirectory = [System.IO.Directory]::Exists($file.FullName)
                if ($isDirectory) {
                    [SymbolicLinkUtil]::CreateSymbolicLinkDirectory($linkPath, $file.FullName)
                }
                else {
                    [SymbolicLinkUtil]::CreateSymbolicLinkFile($linkPath, $file.FullName)
                }
            }
        }
        catch {}
    }
}

Write-Host "Process completed."

```
