### ISSUE TITLE
Cant upload files 

### ISSUE THREAD

**Issue by nightmarebd** [filebrowser/filebrowser#2681]
Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/tus/users/dbaudio-manual-b22-sub-1.2-en.pdf?override=true, response code: 405, response text: , request id: n/a)

**Comment by contre95** [comment]
I'm getting the same error only while trying to upload files through a reverse proxy with authentication settings using Caddy. I can normally upload files if I do it without Caddy's authentication (https://authp.github.io/)

**Comment by jesp5555e** [comment]
I'm getting the same error while trying to upload files through Nginx Proxy Manager and Cloudflare Tunnel

**Comment by Jocho-Smith** [comment]
same situation using cloudflare tunnel. Even when I don't do any nginx reverse proxy. There is no such problem, when I upload directly through the local network. Fails already with images of size 409 KB. 
It's not failing if I upload txt files containing only a few characters, though.

**Comment by LegolasK** [comment]
I am experiencing the same error when I try to upload a file. I'm also using a Cloudflare tunnel to access this through the internet. 

"Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/tus/mnt/***/***/doc.pdf?override=false, response code: 405, response text: , request id: n/a)"

**Comment by maikvitesse** [comment]
Same error with cloudflare and traefik reverse proxy.
Disabled cloudflare caching, still the same problem.

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/releases/tag/v2.25.0

**Comment by evmolpos** [comment]
Any fix pending for Traefik ?
