### ISSUE TITLE
[Question] Share folders between users

### ISSUE THREAD

**Issue by elchanly** [filebrowser/filebrowser#2684]
If this is possible, I cant find where:
I have several users and want them to access just their home folders.  But there's an external folder to all users that I want all users to have access to.
I tried creating a symlink, but it doesnt work.
Is there a way to share folders from the admin user, for example, to another users so they can have access even if this folder is outside their boundaries?

Thanks!

**Comment by NettoHikari** [comment]
I do exactly this by creating a symlink. How are you trying to do it?

**Comment by elchanly** [comment]
I tried creating a symlink but that didnt work, i thought that was because of filebrowser. As you told me it worked for you, i tried again, but now as a relative symlink and it now works as expected. 
Thanks for your help!!!!

**Comment by ruixu2** [comment]
> I do exactly this by creating a symlink. How are you trying to do it?

dose it work when  visiting in browser?

**Comment by elchanly** [comment]
> > I do exactly this by creating a symlink. How are you trying to do it?
> 
> dose it work when visiting in browser?

as a relative symlink it does
