### ISSUE TITLE
Could not set scope for user which scope has Chinese words

### ISSUE THREAD

**Issue by vincywindy** [filebrowser/filebrowser#269]
### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 3. What are you trying to do?
I am trying to add an user then give it a scope.Like this:
![qq 20171031144654](https://user-images.githubusercontent.com/30209724/32210756-6234804c-be4a-11e7-9bbb-51cbd4e8a175.png)
It has Chinese Words,and then I trying to login this account,nothing happen!
![qq 20171031144825](https://user-images.githubusercontent.com/30209724/32210802-94019f2e-be4a-11e7-9731-193804725dfa.png)
The Server-side is Windows Server 2008,

### 5. What did you see instead (give full error messages and/or log)?

![qq 20171031144947](https://user-images.githubusercontent.com/30209724/32210840-c4962de4-be4a-11e7-86f8-eb860788cca1.jpg)

**Comment by hacdias** [comment]
Hey! That doesn't seem a scope path issue. It seems like you're just inserting the wrong credentials. I'll try creating a directory with Chinese characters to check the behavior.

**Comment by vincywindy** [comment]
I tried some Chinese characters, some Chinese characters will have this BUG, some will not.
Here are two Examples:
D:\财务\       is works fine.
D:\测试文件夹\    error.
So if you need example,please try "D:\测试文件夹\"

**Comment by hacdias** [comment]
~I tried with those characters and it is working here. Are you 100% sure the password is correct?~ Actually I just found the bug.

**Comment by vincywindy** [comment]
![1](https://user-images.githubusercontent.com/30209724/32255188-22ff2f16-bee1-11e7-8811-5f7527171b0f.jpg)


Here is the Chrome‘s Console,Maybe userful

’
