### ISSUE TITLE
Using the X-Forwarded-For header.

### ISSUE THREAD

**Issue by OlegEnot** [filebrowser/filebrowser#2693]
**Is your feature request related to a problem? Please describe.**

When using a reverse proxy server, the expected field with the client's real address in the log line is empty.
Example: `2023/09/03 20:23:43 /api/login: 403 <nil>`

**Describe the solution you'd like**

Using the X-Forwarded-For header when logging requests for subsequent Fail2Ban parsing, in conjunction with a reverse proxy.

**Describe alternatives you've considered**

[https://pkg.go.dev/net/http#Request.RemoteAddr](url) performs not quite the tasks that are expected when linking a FileBrowser and a reverse proxy (eq Caddy).

**Additional context**

When accessing directly, the ip address is present.
`2023/09/03 21:24:26 /api/login: 403 192.168.33.2 <nil>`

Thank you!

**Comment by xg4** [comment]
```
reverse_proxy <SERVER>:80 {
  header_up X-Real-IP {remote_host}
}
```

You can use it to get the real IP address in the log file
