### ISSUE TITLE
Multiple TCP streams

### ISSUE THREAD

**Issue by pituluk** [filebrowser/filebrowser#2696]
It seems that filebrowser uses only a single TCP stream for downloading limiting the download speed because of tcp throughput
In my case filebrowser file download is almost 4 times slower than nginx static file.

--
Edit
I tried forcing multiple streams myself, and it is a little buggy with filebrowser but works and allows nice speeds.
But still filebrowser download speeds are pretty meh normally, a simple nginx entry with root and location allows for full speed download, while filebrowser dips (with and without nginx, I did try direct exposure)

**Comment by DukyNuky** [comment]
Can you tell us how you did this ?

**Comment by pituluk** [comment]
> Can you tell us how you did this ?

I dont remember, I have since changed to better software.
