### ISSUE TITLE
Cannot upload file after updating to Home Assistant 2023.9.0

### ISSUE THREAD

**Issue by Naviato** [filebrowser/filebrowser#2697]
Issue: Attempting to upload a .png file to directories that I previously had no issue uploading. 

Error message: Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method:HEAD, url: /api/hassio_ingress/8gXi3-
B6|MvuPqHxunOU-3Jk06JUULuqBzqD53nwH9Q/api/tus/config/www override=false, response code: 405, response text:, request id: n/a

Attempts to resolve: 

- Restarting (full) HA
- Trying different .png files, including files that I have previously uploaded. I changed the name on the files I uploaded before doing this. 
- Downloading files (no issue)
-

**Comment by the-hotmann** [comment]
Duplicate?

https://github.com/filebrowser/filebrowser/issues/2593

**Comment by Naviato** [comment]
Yes.

From: Martin Hotmann ***@***.***>
Date: Monday, September 11, 2023 at 8:09 AM
To: filebrowser/filebrowser ***@***.***>
Cc: Naviato ***@***.***>, Author ***@***.***>
Subject: Re: [filebrowser/filebrowser] Cannot upload file after updating to Home Assistant 2023.9.0 (Issue #2697)

Duplicate?

#2593<https://github.com/filebrowser/filebrowser/issues/2593>
