### ISSUE TITLE
Support Hugo only?

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#27]
There's something else here that can be a problem: right now, the plugin can be used with more static website generators, but if it was directed only to Hugo it could be more optimized and have better functionalities both in the editor (because we know the default front matter fields) and in the back end because we know the default website structure. It's easier. It can be optimized, it can be easily better.

I know I thought before it was better to support many website generators, but there's nothing good which bring bad things too. Almost nothing. We have to see the pros and cons. Do you prefer having the plugin optimized for Hugo with better specific functionalities or do you prefer it to be general and support multiple static generators?

What do you think in restricting this editor to Hugo?

**Comment by adprof** [comment]
I'm all for it. But keep code modular to leave room for contributors and their forks in the future.
There are no other generators besides Hugo ;)

**Comment by mholt** [comment]
I vote to keep it focused - I'd rather have a plugin just for hugo. It'll be easier to maintain and use.

**Comment by hacdias** [comment]
So I can do that. I think it's better too. When I've time, I will change it to "caddy-hugo" again and make the changes on csddyserver.com repo and in the registry. I'll wait for your answer @mholt!

Sure it will keeo being modular as it is @adprof!

**Comment by mholt** [comment]
Sounds good to me... make the directive `hugo` again as well, instead of `cms`? Since the directive is changing, maybe wait to push it to master until a new Caddy version comes out so users aren't totally surprised. Don't forget to update the docs too. (You can push to another branch other than master in the mean time.)

**Comment by hacdias** [comment]
@mholt yes. Why waiting? =P I think it wouldn't be a great problem.

**Comment by hacdias** [comment]
**TODO**: change the directive and repository name.
