### ISSUE TITLE
Can't copy file to server

### ISSUE THREAD

**Issue by Jon811** [filebrowser/filebrowser#2701]
When i try to upload some file to server in any folder in Filebrowser addon, it creates zero-length file with needed name and there is error: 
`Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/hassio_ingress/NiZHkwEgpU6q0eiEO6EdTUor_LitHA2PCE3SWlctlIY/api/tus/config/go2rtc?override=true, response code: 405, response text: , request id: n/a)`
Even if i use curl in Advanced SSH, same situation, but no errors, nothing happens, only zero-length file.

**Comment by superzjg** [comment]
?
#2593

**Comment by o1egl** [comment]
Check https://github.com/filebrowser/filebrowser/issues/2593#issuecomment-1720153087
