### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by rf11291** [filebrowser/filebrowser#2702]
Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/tus/pt/1679659203378.mp4?override=true, response code: 405, response text: , request id: n/a)

**Comment by the-hotmann** [comment]
Duplicate?

https://github.com/filebrowser/filebrowser/issues/2593

**Comment by rf11291** [comment]
The issue was resolved due to incorrect use of an anti-generation server.

Martin Hotmann ***@***.***> 于 2023年9月11日周一 20:09写道：
