### ISSUE TITLE
Slow Download/Upload Speeds

### ISSUE THREAD

**Issue by George-RG** [filebrowser/filebrowser#2706]
Hello everyone,
I don't really consider this a bug so this is why I don't use the bug template. 

I noticed really slow speeds when I download files. At first, I thought that the problem was the small files but then I tested with a big video file and the same happened.  

I know for a fact that both the server and the client have good internet speeds (client: 300 mbits/s download and server 200 mbits/s upload )  so I don't know why this is happening. 

Thanks for any feedback in advance.

**Comment by o1egl** [comment]
https://github.com/filebrowser/filebrowser/pull/2677
