### ISSUE TITLE
--password options can't work on Mac ARM64 v2.24.2

### ISSUE THREAD

**Issue by stark-sim** [filebrowser/filebrowser#2707]
**Description**

I need to start filebrowser by cmd with --password option/flag
My filebrowser version is the current latest: v2.24.2(arm64/darwin)

**Expected behaviour**

The default password should by changed

**What is happening instead?**

The default password is still admin, as well as the --username I guess, it doesn't work neither

**Additional context**

I try the same cmd at linux with the same version, amd64/linux of course, and it's great

**How to reproduce?**

- download the [file](https://github.com/filebrowser/filebrowser/releases/download/v2.24.2/darwin-arm64-filebrowser.tar.gz)
- use it with something like this
```shell
filebrowser --username hello --password "$(./filebrowser hash world)"
```
- check if it works

**Files**

**Comment by o1egl** [comment]
This command will not affect existing filebrowser installation. You can try to remove filebrowser.db file and then start it with username and password params
