### ISSUE TITLE
The home page is loading all the time

### ISSUE THREAD

**Issue by xxzj990** [filebrowser/filebrowser#2708]
**Description**
Update to v2.25.0,Open web,sort by name,the home page is loading all the time.

**Expected behaviour**
Show file list.

**What is happening instead?**

![微信截图_20230915092810](https://github.com/filebrowser/filebrowser/assets/5134154/39e71622-dcbb-446a-a01c-a9de21be4daa)

**Additional context**
As shown above

**How to reproduce?**
Update to v2.25.0,Open web,sort by name,occur.

**Files**
None

**Comment by viratsoft** [comment]
Yes, having same issue,.
click on short then stuck on loding. and if reload page then logout..

**Comment by sarbian** [comment]
Same issue. Endless loading if I sort by date and need to login again if I refresh the page. Works fine if I revert to 2.24.2

**Comment by y1jiong** [comment]
I also encountered the same issue.

**Comment by leolee82** [comment]
Same issue after change some settings

**Comment by spasche** [comment]
When that happens, I see requests being done continuously on the endpoint `/api/renew`

**Comment by GH0STDATA** [comment]
I'd recommend reverting back to v2.24.2 until the issue is fixed. That version is not affected by the sorting bug.

**Comment by Mysterius** [comment]
Same problem here. That is quite an annoying bug in this version !
I would help if I wasn't completely incompetent :3

**Comment by daolanfler** [comment]
same here, if I click sort it starts loading until page crashes

**Comment by Mysterius** [comment]
Upping this a bit for it not to be forgotten.
In short :
- clicking on any sorting options forces the user to reload the page and log in again
- same when changing any option in the profile page

**Comment by xxzj990** [comment]
Already fixed in version 2.26.0
