### ISSUE TITLE
How to create new user by call rest API ?

### ISSUE THREAD

**Issue by zxl777** [filebrowser/filebrowser#271]
RT

**Comment by hacdias** [comment]
Please vote on #285, please. I hope I can do this until the end of the year.

**Comment by TUNER88** [comment]
@zxl777 we have created a small CLI tool for adding users, you can use it. Or just check the API calls we make, it's pretty straight forward.

https://github.com/ironsharkde/filebrowser-usermanager

**Comment by hacdias** [comment]
@TUNER88 that's a nice app you've got there! Just as a follow up: we are making some changes and moving the name from File Manager to File Browser 😄

**Comment by TUNER88** [comment]
@hacdias shouldn't be a problem to rename our package as well, as soon you have released new version 😄

**Comment by hacdias** [comment]
Done! 1.5.0 has the new name already 😄

**Comment by TUNER88** [comment]
Done [filebrowser-usermanager](https://github.com/ironsharkde/filebrowser-usermanager) [v0.0.2](https://www.npmjs.com/package/filebrowser-usermanager) released ✅
