### ISSUE TITLE
click the "Create Folder" button, the page becomes unresponsive

### ISSUE THREAD

**Issue by pluto-tu** [filebrowser/filebrowser#2711]
When you click the "Create Folder" button, the page becomes unresponsive and you cannot perform any actions. You need to refresh the page to restore functionality.

**Comment by superzjg** [comment]
In version v2.23, this was true in Edge browser, but Safari browser did not. 
Upgrading to v2.24.2 will display normally.

**Comment by pluto-tu** [comment]
@superzjg  thanks .     
Fixed by issue:  https://github.com/filebrowser/filebrowser/issues/2568
