### ISSUE TITLE
Cannot upload files in HA

### ISSUE THREAD

**Issue by MichielB2022** [filebrowser/filebrowser#2712]
**Description**
<!cannot upload files in HA

**Expected behaviour**
<!-upload file an it would be there on HA
**What is happening instead?**
File did not upload correct. File is there, but without content and 0 bytes content

additional i get: 
Files Multiple selection enabled clear chevron_right Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/hassio_ingress/AJvgLOEqokM67l6nnvmjTbgmeRHy_QFeaEFvzLENznc/api/tus/stooklijn.png?override=false, response code: 405, response text: , request id: n/a)

**Additional context**

Error code: 
!-Files Multiple selection enabled clear chevron_right Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/hassio_ingress/AJvgLOEqokM67l6nnvmjTbgmeRHy_QFeaEFvzLENznc/api/tus/stooklijn.png?override=false, response code: 405, response text: , request id: n/a)->

**How to reproduce?**
Every time i upload>

**Files**
<none

**Comment by vinnie1234** [comment]
Same problem here :(

**Comment by bcutter** [comment]
Same.

**Comment by alexbelgium** [comment]
I’m the owner of the addon you are using to install FileBrowser on HA, I’ll investigate. Thanks for reporting

edit : well it seems due to the nginx proxy from ingress https://tus.io/faq#how-can-i-deal-with-bad-http-proxies ; not sure if there is a solution without modifying the HA base ingress system

edit 2 : easiest short term solution is that I’ll revert to an older version

**Comment by alexbelgium** [comment]
I can confirm that the add-on works if accessed directly using ip:port. What doesn't work is using the ingress function embedded in HA. As I have no way to modify that, the only solution on my side will be to limit the add-on to versions of the app prior to tus introduction. According to the error message, it seems the HEAD method is used which is not supported by the ingress proxy. Only other solution would be to use another method, or have tus as optional...
