### ISSUE TITLE
500 error .. dealate file / create folder 

### ISSUE THREAD

**Issue by sk2eu** [filebrowser/filebrowser#2713]
HI

by itself filebroswer works on the proxmox 8.0.4

but I can not delete the files or create folders ...

filebroswer has been created in proxmox>docker>portainer via add template

how can i change the error 500 and the permissions?

![image](https://github.com/filebrowser/filebrowser/assets/48036204/e9c1e64c-a404-45c8-be2c-98cdc97dc896)

**Comment by o1egl** [comment]
There are probably some mounting permissions issue. You need to be sure that user that runs filebrowser has write permissions to the mounted volume

**Comment by sk2eu** [comment]
Edit: TCP and writable .. my bad

**Comment by sk2eu** [comment]
i was stupid.. set rights to write in portainer for this error
