### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by antonio1475** [filebrowser/filebrowser#2714]
**Description**
Uploading a file from Windows via Chrome results in error 

**Expected behaviour**
File is uploaded as normal

**What is happening instead?**
File is created with the name, but empty.

> Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/hassio_ingress/pI_Ipm6K_ZuHCMhvhilVO9yXOYExMe9VOmsvi8eB3Gg/api/tus/config/www/Ticket.To.Paradise.en.txt?override=false, response code: 405, response text: , request id: n/a)

**Additional context**
![image](https://github.com/filebrowser/filebrowser/assets/63130724/961ab6af-0042-4e4f-86f9-0b09d4c05b19)

**How to reproduce?**

1. Go to folder in Filebrowser
2. Click upload icon
3. Select file in Windows file browser, click Upload
4. See error (file is created).

Drag&drop from Windows results in the same error.

**Files**
[Ticket.To.Paradise.en.txt](https://github.com/filebrowser/filebrowser/files/12640723/Ticket.To.Paradise.en.txt)

**Comment by antonio1475** [comment]
Probably a duplicate of https://github.com/filebrowser/filebrowser/issues/2712
Apologies, the Report bug button took me directly to opening an issue without checking first for existing ones...

**Comment by bcutter** [comment]
Seeing this as well.

**Comment by alexbelgium** [comment]
Hi, same as https://github.com/filebrowser/filebrowser/issues/2712 : homeassistant embedded proxy is not compatible with TUS. As I can't change homeassistant I've reverted the addon version and it should work again

**Comment by alexbelgium** [comment]
I've opened a request for an optional setting to disable TUS otherwise we should just stay on the previous version (but affected by the CSS bug preventing refresh on modern browsers)

**Comment by bcutter** [comment]
A downgrade is no permanent solution, we need to keep this open until the noted request is (hopefully) implemented.

**Comment by alexbelgium** [comment]
Not stale
