### ISSUE TITLE
Unable to use upload function to restore filebrowser.db

### ISSUE THREAD

**Issue by superzjg** [filebrowser/filebrowser#2716]
**Description**
I have backed up the database file(filebrowser.db) and would like to restore it.

**What is happening instead?**
**Upload failed: Error: tus: failed to resume upload, caused by [object ProgressEvent], originated from request (method: HEAD, url: /api/tus/jffs/softcenter/bin/filebrowser.db?override=true, response code: n/a, response text: n/a, request id: n/a)**

**Additional context**
If do not replace it directly, but delete it first and then upload it, it is normal.
Testing v2.23.0 is OK, from v2.24 to v2.25.0, it will reproduce.

**How to reproduce?**
In the filebrowser.db file directory --> upload file --> select the filebrowser.db file --> replace.

**Files**
filebrowser.db

**Comment by o1egl** [comment]
You shouldn't replace database file on the fly. You should stop the service before doing it

**Comment by superzjg** [comment]
> You shouldn't replace database file on the fly. You should stop the service before doing it

Thanks.
I'll just do it this way, it works well:
1. Delete file first
2. Upload
3. Restart service (using built-in shell)
I don't need to stop the service first and use another tool to connect to the remote host.
