### ISSUE TITLE
ETA estimation issue for small file uploads

### ISSUE THREAD

**Issue by maeryo** [filebrowser/filebrowser#2718]
I recently implemented the upload speed display and ETA estimation included in the 2.25.0 release. #2677
This feature is quite useful when uploading large files.
However, when uploading many small files, the upload completes before the calculation can be made, making accurate estimation impossible.
I'm looking for good ideas to address this issue.

**Comment by leolee82** [comment]
This feature is to tell users the uploading is going on. I think you can ignore the estimation for small files which uploading time less than 5 sec.

**Comment by maeryo** [comment]
@leolee82
When a directory, which holds an extremely large quantity of small files approximately 100kb each, exceeds 10GB in size, its upload progresses without any calculation ETA for the entire 10GB. From the user's viewpoint, both the upload speed and ETA appear solely as 0. This can understandably be seen as a bug by users. (And, of course, depending on how you look at it, it truly is a bug. Haha...)

**Comment by leolee82** [comment]
> @leolee82 When a directory, which holds an extremely large quantity of small files approximately 100kb each, exceeds 10GB in size, its upload progresses without any calculation ETA for the entire 10GB. From the user's viewpoint, both the upload speed and ETA appear solely as 0. This can understandably be seen as a bug by users. (And, of course, depending on how you look at it, it truly is a bug. Haha...)

I think we can refer to baidu disk. Show a file status list in a separate window. and put an button show the count of remain files and total.
