### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by soulfulkhani** [filebrowser/filebrowser#2723]
I was trying to install file browser in winfows 11 and everytime i paste the command given on installation guide of filebrowser under window section. Terminal say cannot recognize path something like this . Can anyone help me with this i am completely new to this

**Comment by Luka-Spa** [comment]
Did you change the following line to use the right path: "filebrowser -r /path/to/your/files"?

**Comment by soulfulkhani** [comment]
> Did you change the following line to use the right path: "filebrowser -r /path/to/your/files"?

i just have to write the directory path right ? like d or c ? can you please write the path for directory D also if i have to unistall or if i want to remove the access of filebrowser from the said path what show i do is there any command for that aswell ?

**Comment by Luka-Spa** [comment]
This is the command: 
`filebrowser -r D:`

To stop filebrowser from having access to your (D:) drive, just shut it down by using CTRL + C in the terminal

Please show me your error if this doesn't work, because for me it works

**Comment by soulfulkhani** [comment]
> This is the command: `filebrowser -r D:`
> 
> To stop filebrowser from having access to your (D:) drive, just shut it down by using CTRL + C in the terminal
> 
> Please show me your error if this doesn't work, because for me it works

![Screenshot 2023-09-21 204303](https://github.com/filebrowser/filebrowser/assets/145058863/9db5683a-14e4-4c8d-88bd-12b0c5835385)
i dunno what i am doing wrong here

**Comment by Luka-Spa** [comment]
Please use these commands while running the Command Prompt in Administrator mode.
That should do the trick!

**Comment by soulfulkhani** [comment]
> Please use these commands while running the Command Prompt in Administrator mode. That should do the trick!

![Screenshot 2023-09-22 163914](https://github.com/filebrowser/filebrowser/assets/145058863/6f4b354f-2ecb-42b5-bc62-3179e2576575)
okay now it was installed but in the end i got error again 😭

**Comment by Luka-Spa** [comment]
Simply open another CMD in Administrator mode and try `filebrowser -r E:` again. 

This has to do with the System Variable not being present in the first CMD session.

**Comment by soulfulkhani** [comment]
> Simply open another CMD in Administrator mode and try `filebrowser -r E:` again.
> 
> This has to do with the System Variable not being present in the first CMD session.

okay should i do after that ? it says no config file used  then listening on ............

**Comment by Luka-Spa** [comment]
That means it is working!

**Comment by soulfulkhani** [comment]
> That means it is working!

thank you so much but what should i do after that like ? next step is to login or there is anything else . i am not familiar with coding

**Comment by Luka-Spa** [comment]
Open you browser (Edge, Chrome, Firefox) and type in the address bar: "localhost:8080" (and press Enter of course). Then you can login with 
- username: admin
- password: admin.

I don't know exactly what your goals are furthermore?

**Comment by soulfulkhani** [comment]
> Open you browser (Edge, Chrome, Firefox) and type in the address bar: "localhost" (and press Enter of course). Then you can login with
> 
> * username: admin
> * password: admin.
> 
> I don't know exactly what your goals are furthermore?

like how do i change username and password for now ? and to remove the accessi just have to open the cmd in administrative mode and do CTRL + C right ?

**Comment by Luka-Spa** [comment]
Just navigate to settings in order to change username and password.

![image](https://github.com/filebrowser/filebrowser/assets/70573238/6ec5e6e1-1461-4c50-817f-0716f2b68efb)


And yes to stop the service (remove access) CTRL + C

**Comment by soulfulkhani** [comment]
> Just navigate to settings in order to change username and password.
> 
> ![image](https://user-images.githubusercontent.com/70573238/269926798-6ec5e6e1-1461-4c50-817f-0716f2b68efb.png)
> 
> And yes to stop the service (remove access) CTRL + C

there is i guess only password change option .  okay last query how do it uninstall this is there any command for that too the way it got installed ?

**Comment by Luka-Spa** [comment]
To change username go to user management, to uninstall just manually remove the folder: "C:\Progam Files\filebrowser".

**Comment by soulfulkhani** [comment]
> To change username go to user management, to uninstall just manually remove the folder: "C:\Progam Files\filebrowser".

thank you so so much luka 🥹. it really means alot

**Comment by soulfulkhani** [comment]
> To change username go to user management, to uninstall just manually remove the folder: "C:\Progam Files\filebrowser".

hi luka, i have one more query i asked a person how i can use this from other computers or access the filebrowser over network from anywhere, they said about ask the internet provider to give you the service if white static ip etc. so does it require all these or it just need some config setup ?

**Comment by Luka-Spa** [comment]
Unfortunately it is not that simple, I would not recommend you try this yourself. But if you do anyway; look into Port forwarding.

**Comment by soulfulkhani** [comment]
> Unfortunately it is not that simple, I would not recommend you try this yourself. But if you do anyway; look into Port forwarding.

Ah got it( its something which is complex and i cant do that), btw is there any other alternatives that can be used which doesnt require all these sort of things?

**Comment by Prikith** [comment]
> Ah got it( its something which is complex and i cant do that), btw is there any other alternatives that can be used which doesnt require all these sort of things?
Look into zerotier or tailscale, it does require some setup on the computer you want to access from

**Comment by soulfulkhani** [comment]
> > Ah got it( its something which is complex and i cant do that), btw is there any other alternatives that can be used which doesnt require all these sort of things?
> > Look into zerotier or tailscale, it does require some setup on the computer you want to access from

thank you so much

**Comment by xlaxplaya** [comment]
Thanks @Luka-Spa that worked for me too. Wouldn't it be good to change the documentation here to reflect this step? https://filebrowser.org/installation

Seems like we should add a line that says something like "Close powershell or cmd, and re-open as administrator before running the next command."

Or does this only happen _sometimes_?
