### ISSUE TITLE
Sort broken on version 2.25.0

### ISSUE THREAD

**Issue by spasche** [filebrowser/filebrowser#2724]
**Description**

I updated from v2.24.2 to v2.25.0. Sorting doesn't work any more.

**Expected behaviour**

When clicking on a column header in details view, the files should be sorted.

**What is happening instead?**

The page shows "Loading...".
In the browser network console, I can see many requests being done to `/api/renew`.
Nothing shows in the filebrowser logs.

**How to reproduce?**

- Run instance:
```
docker run --rm -it -p 8080:80 filebrowser/filebrowser:v2.25.0 --noauth -r /usr
```
- Open http://HOSTNAME:8080/files/bin/
- Switch to details view
- Click on a column to sort

**Comment by superzjg** [comment]
https://github.com/filebrowser/filebrowser/issues/2708

**Comment by spasche** [comment]
> #2708

Thanks, I don't know how I missed it.

**Comment by leolee82** [comment]
shows "Loading..." after change language or update user rules
