### ISSUE TITLE
Folders won't open in DuckDuckGo mobile browser on iOS

### ISSUE THREAD

**Issue by hellopanictech** [filebrowser/filebrowser#2725]
**Description**
I have FileBrowser installed from a docker container and often access from a mobile (iOS) browser. When opening the application and attempting to open a folder within the directory structure, the folders do not open via a double tap in the DuckDuckGo browser. This functionality works as expected in all other tested browsers including Safari, Brave, & Chrome on iOS mobile. It also works in DuckDuckGo browser on Windows.

**Expected behaviour**
Folders should open to subfolders or next folder level

**What is happening instead?**
Double tapping on a folder selects and highlights, but does not open.

**Additional context**
Issue verified on following versions:
iOS 16 and iOS 17
DuckDuckGo iOS browser 7.88.1 and 7.89.0
FileBrowser docker container 2.24.2 and 2.25.0

This functionality was tested and works as expected on the following iOS mobile browsers:
Safari,
Brave,
Chrome

**How to reproduce?**
Use DuckDuckGo browser installed on iOS. Issue verified on iOS 16 and iOS 17 and with DuckDuckGo browser 7.88.1 and 7.89.0. Open  instance of FileBrowser and attempt to double tap on a folder. It highlights, but does not open. 

I'd put a ticket in with the browser application devs as well, but I'm not exactly sure what web browser call the FileBrowser application is using on mobile platforms. Perhaps with more code context, I can connect the dots between this being an application fault or browser problem.

**Comment by kloon15** [comment]
Afaik all iOS browsers are just glorified Safari reskins. Dont think theres anything we can do about it.
