### ISSUE TITLE
Endless sending of the 'renew' URL after saving configuration

### ISSUE THREAD

**Issue by moraisamilton** [filebrowser/filebrowser#2729]
After updating the user configuration, if you try to access any folder, the system goes into a loop sending requests to the URL https://demo.filebrowser.org/api/renew.

Here's the video.

https://github.com/filebrowser/filebrowser/assets/24901391/31e3ee47-587c-4295-bbd6-669ed7fffeba

**Comment by newrokor** [comment]
I can confirm this finding, using the AUR package [filebrowser-bin](https://aur.archlinux.org/packages/filebrowser-bin), which is the binary version 2.25.0 from here together with some system implementation. I observed it not only as described by @moraisamilton, but more or less erratically.

Downgrading to 2.24.2 did the trick for me right now.
