### ISSUE TITLE
Unable to add multiple scope for a user

### ISSUE THREAD

**Issue by asthanas** [filebrowser/filebrowser#2734]
**Description**
We are trying to provide access to multiple folder for a single user but filebrowser is not allowing the same.

**Expected behaviour**
Depending on the requirement, we should be able to provide access to 2 or 3 folder to a single user depending on our requirement.

**What is happening instead?**
Filebrowser is allowing scope only to a single folder at a time.

**How to reproduce?**
Try to add more then 1 path in the scope of user management

**Comment by kloon15** [comment]
Symlinks are ur best friend for now.

**Comment by pieroanesin** [comment]
I had the same problem. I solved it by managing the folders from the filebrowser configuration file. 
When you declare volumes for users, you can create one that points directly to user A's folder and then put it in the other user's scope. So, the concept is that each user has their own parent folder in the scope, and then when you declare the volumes, you make sure they're inside the scope's parent folder.

I hope I have been helpful to you

**Comment by TomT15** [comment]
we should reopen this...

**Comment by jordaneast1** [comment]
+1

would love for it to be like Scope= /foo /bar etc..
