### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by liluojunroger** [filebrowser/filebrowser#2735]
Upload failed: Error: tus: unable to resume upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/hassio_ingress/wwLbYyWPBB_It6TrQ0FA1rY0wA8YgZTwD_trG2ZQhvg/api/tus/config/www/UI_EMS/acc.jpg?override=true, response code: 405, response text: , request id: n/a)

**Comment by o1egl** [comment]
You probably have a proxy that blocks HEAD requests

**Comment by alexbelgium** [comment]
Hi, same as https://github.com/filebrowser/filebrowser/issues/2712 : homeassistant embedded proxy is not compatible with TUS. As I can't change homeassistant I've reverted the addon version and it should work again

**Comment by byte21516** [comment]
I get the same error message without a proxy, but with cloudflared ( cloudflare tunnel )
Not always, but often a reboot does fix it.
