### ISSUE TITLE
Missing /tmp folder in docker image

### ISSUE THREAD

**Issue by spawnia** [filebrowser/filebrowser#274]
### 1. Prerequesite
I used filemanager with docker. I run it with the default options, mounting a volume into /srv.

### 3. What are you trying to do?
Download a folder of the mounted files as a Zip.

### 4. What did you expect to see?
Browser starts the Download.

### 5. What did you see instead (give full error messages and/or log)?
A new window opens: `Internal server error`

Container log outputs the following:

11/6/2017 4:12:31 PM2017/11/06 15:12:31 /srv/user_upload/: 500 Internal Server Error
11/6/2017 4:12:31 PM2017/11/06 15:12:31 stat /tmp: no such file or directory

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

1. Run the container `docker run -it -p 80:80 -v $PWD:/srv hacdias/filemanager` --port 80`
2. Try to download a folder as any packaged format.

My solution was to simply create the folder /tmp in the root directory.

**Comment by hacdias** [comment]
Just pushed a fix. Could you please try again?

**Comment by spawnia** [comment]
The new version works perfectly, it even enters right into the /srv directory when logging in. Clean and nice, thank you so much!
