### ISSUE TITLE
As of v2.25.0, 1KB is calculated and displayed as 1000 bytes instead of 1024 bytes.

### ISSUE THREAD

**Issue by athene20** [filebrowser/filebrowser#2744]
**Description**
There was a change in the capacity calculation units, but it's not in the changelog, so I think it's a bug.
- v2.24.2: Calculate 1 KB as 1024 bytes.
- v2.25.0: Calculate 1 KB as 1000 bytes.

**Expected behaviour**
We typically count 1 KB as 1024 bytes, so the previous method seems to be correct.

**What is happening instead?**
Calculate 1 KB as 1000 bytes.

**Additional context**
See the screenshot below.
![image](https://github.com/filebrowser/filebrowser/assets/66622484/3238807e-739c-4ea2-96c1-5b64b5982d20)

**How to reproduce?**
I believe it was caused by a related library update and should be reproducible.

**Files**
Replace with the screenshot above.

**Comment by kloon15** [comment]
Well technically the old one was incorrect (1 KB is indeed 1000 bytes), but ur right, we should display them in KiB and such to avoid confusion.
