### ISSUE TITLE
Page stuck when switch language

### ISSUE THREAD

**Issue by forfcw** [filebrowser/filebrowser#2748]
**Description**
The page will be stuck due to an infinite loop (POST to **/api/renew**),  and even crash chrome after a few seconds

**Reproduce steps**
1. Click **Settings** button in Page /files/
2. Switch to another language (eng to zh_cn in my case)  in **Profile Settings**
3. Click **Update** button to apply
4. Click **My files** button to return homepage
5. Page stuck and Thousands of requests to **/api/renew** will be generated within seconds

**Screen shot**
![image](https://github.com/filebrowser/filebrowser/assets/26297213/35a421ce-8c46-4bb8-a167-521681dce7df)

**Comment by kloon15** [comment]
Fix is in master, u can revert to 2.24.2 in the meantime.

**Comment by forfcw** [comment]
> Fix is in master, u can revert to 2.24.2 in the meantime.

checkout in this Revision [bd3c1941ff8289a5dae877e08f7e25fa9b2a92c5](https://github.com/filebrowser/filebrowser/commit/bd3c1941ff8289a5dae877e08f7e25fa9b2a92c5) and the bug still exist.

**Comment by kloon15** [comment]
Hmm, i will have to double check then. Could u maybe test commit 56a5bdc it should be fixed in our vue3 branch.

**Comment by forfcw** [comment]
> Hmm, i will have to double check then. Could u maybe test commit [56a5bdc](https://github.com/filebrowser/filebrowser/commit/56a5bdc3acee0f5f004ec402543076d484ec6933) it should be fixed in our vue3 branch.

**This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.**
can not find the branch in this repository

**Comment by kloon15** [comment]
> > Hmm, i will have to double check then. Could u maybe test commit [56a5bdc](https://github.com/filebrowser/filebrowser/commit/56a5bdc3acee0f5f004ec402543076d484ec6933) it should be fixed in our vue3 branch.
> 
> **This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.** can not find the branch in this repository

You can click on browse files near the top right and download zip or clone my fork [here](https://github.com/kloon15/filebrowser/tree/vue3)

**Comment by forfcw** [comment]
> > > Hmm, i will have to double check then. Could u maybe test commit [56a5bdc](https://github.com/filebrowser/filebrowser/commit/56a5bdc3acee0f5f004ec402543076d484ec6933) it should be fixed in our vue3 branch.
> > 
> > 
> > **This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.** can not find the branch in this repository
> 
> You can click on browse files near the top right and download zip or clone my fork [here](https://github.com/kloon15/filebrowser/tree/vue3)

thanks for reply, the issue has been fixed in the vue3 branch, but **when will this submission be merged to the master branch?**

**Comment by kloon15** [comment]
Are you sure ur master branch is up to date? I checked and this IS fixed by the last commit.

**Comment by forfcw** [comment]
> Are you sure ur master branch is up to date? I checked and this IS fixed by the last commit.

absolutely yes, test again and reproduce every times on this commit **bd3c1941ff8289a5dae877e08f7e25fa9b2a92c5**
