### ISSUE TITLE
A bug when double click the file

### ISSUE THREAD

**Issue by zxl777** [filebrowser/filebrowser#275]
I think this is a bug in v1.3.9.
When I double click on the file "messages.xml" will open edit view ,
But double click on the other file "config.yml" will open download view.

![https://user-images.githubusercontent.com/816448/32313102-0c5994c0-bf6f-11e7-97ac-f49fc09b23b6.png]()

![https://user-images.githubusercontent.com/816448/32313185-8e8f4aac-bf6f-11e7-91d4-a58db1043883.png]()

**Comment by zxl777** [comment]
![image](https://user-images.githubusercontent.com/816448/32313102-0c5994c0-bf6f-11e7-97ac-f49fc09b23b6.png)
 
![image](https://user-images.githubusercontent.com/816448/32313185-8e8f4aac-bf6f-11e7-91d4-a58db1043883.png)

**Comment by hacdias** [comment]
It will be fixed in the next release 😄

**Comment by zxl777** [comment]
Thank you
