### ISSUE TITLE
Feature Request: Role-Based Access Control (Rules)

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2755]
**Is your feature request related to a problem? Please describe.**

In our usage of FileBrowser, we have a substantial number of users, each with individual access permissions based on a set of rules. Managing these permissions for hundreds of users without role-based access control is proving to be a challenging and time-consuming task (#2003).

**Describe the solution you'd like**

We propose the implementation of a role-based access control system within FileBrowser. This would allow administrators to create roles, define associated rules, and assign these roles to users. Simplifying the access management process, this feature would significantly enhance the usability and maintainability of FileBrowser.

**Describe alternatives you've considered**

We have considered an alternative solution, which is simplifying the folder access configuration (#2607). However, this may not provide the level of granularity and efficiency that role-based access control offers.

**Additional context**

It's essential to note that we currently have a minimum of 100 users, and this number is expected to grow. The implementation of role-based access control would greatly benefit our organization's workflow and security management.

**Comment by baur** [comment]
Ping

**Comment by microhello** [comment]
Ping
