### ISSUE TITLE
Can't connect to Filebrowser with no errors at all

### ISSUE THREAD

**Issue by predictcare** [filebrowser/filebrowser#2757]
**Description**
Installing on Debian was ok, and the executables was started with -p 8082 and sudo
We installed Filebrowser in our GCloud Debian 10 server
Version of Debian is : 4.19.0-24-cloud-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64
Obviously 8082 port is opened toward external connections and internal.

We also tried with anoter web-fileserver on the same port and it works ok.

**Expected behaviour**
We should see the login page with the url :   http://xxx.yyy.zzz.ttt:8082

**What is happening instead?**
connection error on chrome browser

Filebrowser version is File Browser v2.25.0/c1fb4004

**Comment by predictcare** [comment]
I discovered the reason why it doesn't work : 

standard ip (-a param) is 127.0.0.1. With this parameter it doesn't work, with no error.

If i substitute this with local ip of the google cloud machine (eg. 10.0.1.123) it works.

I don't know if it's normal or should be filed as a bug.

I can ping both adress, to clear the situation...

Thanks !

**Comment by o1egl** [comment]
It is not a bug. You have to either set a public IP or add a proxy in front of the filebrowser
