### ISSUE TITLE
Crash on changing view

### ISSUE THREAD

**Issue by DevMwd** [filebrowser/filebrowser#2762]
Hi, 
I use webapp version 2.25.0 and I have a problem when I change the view 

![Screenshot 2023-10-13 at 13 08 23](https://github.com/filebrowser/filebrowser/assets/92986974/fb4d7047-9c7f-4a70-94c7-6d8c7d472d87)

The system makes so many calls to the same endpoint until it crashes

![Screenshot 2023-10-13 at 16 42 52](https://github.com/filebrowser/filebrowser/assets/92986974/c0ea3182-e794-460d-bf5e-dbc8ab32b1d5)

![Screenshot 2023-10-13 at 13 10 53](https://github.com/filebrowser/filebrowser/assets/92986974/fda5c43f-48cf-428d-a315-a8a10c3c0858)

Thank you

**Comment by oregonpillow** [comment]
Similar issue for me, if i change the sort order, for example by modified date it will just freeze and log me out. When i log back in again the new sort order will show however.

**Comment by o1egl** [comment]
Fixed in the new release
