### ISSUE TITLE
New Feature: View files (Read Only, not download)

### ISSUE THREAD

**Issue by joel72265** [filebrowser/filebrowser#2763]
Thank you for a wonderful program.

New Feature: when I try to view a .PDF file it first downloads the file. Please have the option to view certain file types (.txt, .pdf) without downloading the file. I hope my explanation is clear. 

Another possible way would be to have an option, Disable opening certain file types (.cmd, bat, ps, js .....)

Thank you,
Joel

**Comment by o1egl** [comment]
Not sure what do you mean. Filebrowser already opens text and pdf files in a preview mode. Check this link https://demo.filebrowser.org/files/Lorem_ipsum.pdf

**Comment by joel72265** [comment]
You are correct, if the user has 

Permission = **Download**, the user is able to view and download the files
Permission = **Read**, this option does not exist. We would like the user to be able to view the files but not be able to download the file

Another **feature** is to **Disable** Users from opening certain **file types** (.cmd, bat, ps, js .....) or **permit** only certain **file types**. 

Thank you
