### ISSUE TITLE
Can not edit admin user

### ISSUE THREAD

**Issue by spawnia** [filebrowser/filebrowser#277]
### 1. Prerequesites
Running filemanager from docker on my local machine. I tried to access it via Chrome and Firefox. Issue was the same.

### 3. What are you trying to do?
I want to change the password of the user *admin* after the first log in.

### 4. What did you expect to see?
When i click on the edit symbol next to the admin user, i want to be able to edit the admin user. The link shows as `/settings/users/1`. I can create new users and edit them easily, but the admin user can not be changed.

It used to work in a previous version.

### 5. What did you see instead (give full error messages and/or log)?
I get redirected to `/settings/users/new`, no error output in the log.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

`docker run -p 80:80 -v $PWD:/srv hacdias/filemanager`

Go to localhost, login and try to edit the user *admin*.

**Comment by hacdias** [comment]
Hello @spawnia! You **must** set the path to the site root and to the database in your file system (outside of Docker)! Like this:

```
docker run \
    -v /path/to/sites/root:/srv \
    -v /path/to/database.db:/database.db \
    -p 80:80 \
    hacdias/filemanager
    --port 80
    --database /database.db
    --scope /srv
    --other-flag other-value
```

You can find more [info here](https://github.com/filebrowser/filebrowser/blob/master/docs/installation.md#docker).
