### ISSUE TITLE
directory listing enabled on static/img 

### ISSUE THREAD

**Issue by p3t3rp3pp3r** [filebrowser/filebrowser#2774]
**Description**
Directory listis is enabled on virtual folder static/img

**Expected behaviour**
Directory listing disabled on "static/img" folder

**What is happening instead?**
![image](https://github.com/filebrowser/filebrowser/assets/46246123/42ebf6ab-70d3-43cc-bab7-69685ab42061)

**Additional context**
This behaviour can be considered a security issue

**How to reproduce?**
browse <address:port>/static/img

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/commit/da1fe7c9d76a9c6a25bfa19ebd6cf8023eff5d62
