### ISSUE TITLE
How to use nginx proxy filemanager?

### ISSUE THREAD

**Issue by dream10201** [filebrowser/filebrowser#278]
Multiple services for one entrance，Bad English, translated ...

**Comment by hacdias** [comment]
Hey @xizirumeng! Do you want to have multiple URLs pointing to the same File Manager instance?

**Comment by dream10201** [comment]
A url，Multiple filemanager
E.g
abc.com/file1/
abc.com/file2/

**Comment by dream10201** [comment]
Multiple may not all be file managers

**Comment by hacdias** [comment]
I haven't used nginx, but something like this could work:

```
location /file1/ {
    proxy_pass 127.0.0.1:5000;
}

location /file2/ {
    proxy_pass 127.0.0.1:5001;
}
```

Where `:5000` and `:5001` are the different ports for each File Manager instance.

**Comment by dream10201** [comment]
This will be a problem, some url will be reported 404。Sorry, my English is poor, translated by translation software

**Comment by dream10201** [comment]
My RaspberryPi is out of power today and can not give you an error message

**Comment by hacdias** [comment]
If there are two different File Manager instances. One for `/file1/` and another for `/file2/`.

### For `/file1/` you could have:

config.yaml

```
port: 5000
baseURL: /file1
address: 127.0.0.1
database: "/path/to/database1.db"
scope: "/path/to/your/files"
```

### For `/file2/` you could have:

config.yaml

```
port: 5000
baseURL: /file2
address: 127.0.0.1
database: "/path/to/database1.db"
scope: "/path/to/your/files"
```

### On nginx

```
location /file1/ {
    proxy_pass 127.0.0.1:5000;
}

location /file2/ {
    proxy_pass 127.0.0.1:5001;
}
```

Hope this helps.

**Comment by dream10201** [comment]
I send an error message later, Beijing time around 7: 00-9: 00,thank you for your help

**Comment by dream10201** [comment]
Now normal,If baseURL is not set, the following configuration is not available
```
location /file/ { 
    proxy_pass http://192.168.123.15:8787/; 
}
```
`api.js:34 GET http://192.168.123.15:8787/api/resource/file/ 404 (Not Found)`

**Comment by hacdias** [comment]
Sorry, please try the following config:

```
port: 5000
prefixURL: /file1
address: 127.0.0.1
database: "/path/to/database1.db"
scope: "/path/to/your/files"
```

**Comment by dream10201** [comment]
Use prefixURL error, the page can not be displayed
```
manifest.1491131e12a62bc1f331.js:1 Uncaught SyntaxError: Unexpected token <
vendor.44036de40396f416cb9a.js:1 Uncaught SyntaxError: Unexpected token <
app.a856f9102ba06a5b90a5.js:1 Uncaught SyntaxError: Unexpected token <
```
There seems to be no problem using baseURL

**Comment by hacdias** [comment]
This configuration is working with me:

```nginx.conf```

```
http {
    server {
        location /file1/ {
            proxy_pass http://127.0.0.1:5000;
        }

        location /file2/ {
            proxy_pass http://127.0.0.1:5001;
        }
    }
}

events {}
```

File Manager 1:

```
port: 5000
baseURL: /file1
address: 127.0.0.1
database: "/database2.db"
scope: "."
```

File Manager 2:

```
port: 5001
baseURL: /file2
address: 127.0.0.1
database: "/database1.db"
scope: "."
```

You just need to update the ports and the addresses accordingly.

**Comment by dream10201** [comment]
Communication is more difficult, but the problem was solved successfully, thank you for your help again

**Comment by hacdias** [comment]
Sorry for not being helpful as needed but I'm glad you found out how to make it work 😄
