### ISSUE TITLE
add more detailed instructions in documents

### ISSUE THREAD

**Issue by lumos0** [filebrowser/filebrowser#2780]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

like when using --password , need  single quotes

filebrowser -r /home/disk/Files -a 0.0.0.0 -p 80 -b / -d /home/disk.db --username lexamen --password '$2a$10$rCMATV1YyIzkYLzgqetV6ukbYqsDouFY38xHZ3jICl/eTrXYHUBDC'

**Comment by GottZ** [comment]
bump
