### ISSUE TITLE
User cannot upload on mobile / admin can

### ISSUE THREAD

**Issue by RomainLG** [filebrowser/filebrowser#2789]
**Description**

Uploading a picture when admin works. 
When using regular user it doesn't work. 

**What is happening instead?**

Upload failed: Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request (method: PATCH, url: /api/tus/IMG_20231025_090048.jpg?override=false, response code: n/a, response text: n/a, request id: n/a)

**Additional context**
Using latest filebrowser docker 

This seems like it is related to an issue supposedly fixed : #2593

Edit: You can apparently fix this issue by adding edit permission to the user. Maybe I misunderstood that permission? Weird

**Comment by o1egl** [comment]
Looks like it can be closed
