### ISSUE TITLE
Install doesn't work on OpenBSD 7.4

### ISSUE THREAD

**Issue by TrisDel** [filebrowser/filebrowser#2791]
**Description**
Running the command "curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash" doesn't work on OpenBSD 7.4. 
The openbsd-amd64 package is not found.

Downloading File Browser for openbsd/amd64...
https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/openbsd-amd64-filebrowser.tar.gz
curl: (22) The requested URL returned error: 404
Aborted, error 22 in command: ${net_getter} "$filemanager_url" > "$PREFIX/tmp/$filemanager_file"

**Expected behaviour**
Expected it to download https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/openbsd-amd64-filebrowser.tar.gz and be able to extract it.

**What is happening instead?**
Downloading File Browser for openbsd/amd64...
https://github.com/filebrowser/filebrowser/releases/download/v2.25.0/openbsd-amd64-filebrowser.tar.gz
curl: (22) The requested URL returned error: 404
Aborted, error 22 in command: ${net_getter} "$filemanager_url" > "$PREFIX/tmp/$filemanager_file"

**Additional context**

**How to reproduce?**
On a clean openbsd instance:
pkg_add bash curl
then run the command:
curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash

**Files**

**Comment by c0dev0id** [comment]
```
pkg_add gmake node go
git clone https://github.com/filebrowser/filebrowser
cd filebrowser
gmake build
# ignore all warnings and watch it download the world
./filebrowser &
firefox http://127.0.0.1:8080
```

**Comment by TrisDel** [comment]
Ok will give it a go building it from source.
Thanks for the quick reply.
