### ISSUE TITLE
Display about ios heic photo

### ISSUE THREAD

**Issue by charlie-ch** [filebrowser/filebrowser#2795]
hi,could you display ios heic photo in filebrower? Thanks![image](https://github.com/filebrowser/filebrowser/assets/20819132/3d4dd489-2dab-4f5c-8fd5-a495ab9c8e6d)

**Comment by o1egl** [comment]
Unfortunately it requires a native dependency which breaks cross-compilation feature. You are welcome to make a PR to introduce a new build process that supports native libraries

**Comment by dannylin0711** [comment]
https://github.com/jdeng/goheif

Is this repository suitable for this usage? It seems might work in following flow.
Read HEIC -> Convert to PNG/JPG -> Read PNG/JPG
