### ISSUE TITLE
UI is grayed out

### ISSUE THREAD

**Issue by karam-ajaj** [filebrowser/filebrowser#2798]
**Description**
After copying a file the whole UI is grayed out and I can only do a browser refresh to resolve the issue 

**Expected behaviour**
I should still be able to use filebrowser

**What is happening instead?**
the whole UI is grayed out 

**Additional context**

**How to reproduce?**
I am using this docker image "filebrowser/filebrowser:latest"
https://hub.docker.com/layers/filebrowser/filebrowser/latest/images/sha256-dfbedfc74452e3685eec6d1a08d45b9072d974719c33a6349e3c11d207867848?context=explore

**Files**

**Comment by baur** [comment]
use prev release, current release is broken

**Comment by o1egl** [comment]
This is a known chrome issue.

**Comment by o1egl** [comment]
Can't reproduce it. Have you tested it on [demo.filebrowser.org](https://demo.filebrowser.org/)? Which browser are you using?

**Comment by karam-ajaj** [comment]
it is resolved when using this image "v2.25.0-s6"
