### ISSUE TITLE
Field data types in editor

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#28]
Taking in account that #27 will come true in a short time from now, it would be nice to make the data fields with costum types, like `datetime` for `date`, `textarea` for `description`, etc. See [gohugo.io/content/front-matter/](http://gohugo.io/content/front-matter/) to know more.

**Comment by adprof** [comment]
Will be nice but this is some funcionality. Maybe it's time to have some kind of roadmap?

Here are some of my thoughts about the CMS in general. Forgive me if I'm writing nonsense :)

Usually it is that the web interface is needed for people other than those who built the website. In my opinion, generally does not make sense to expand the functionalities to replace typing something in a text file by Admin. Hugo grows and it will be difficult to keep up with changes.
I mean, potential visual construction of layotuts for different content types, assignment of field types to front-matter params in the GUI etc.

Assuming that the goal is to facilitate the use of the Hugo by people who simply edit the page, I propose to implement user roles.

To leave webinterface as is - URL / admin and add another one but a little bit simpler at the URL / redactor. Redactor can only edit content of choosen type and allowed parts of front matter (configurable).
Authentication and security are issues to consider but in my opinion is not necessary to do anything with this in GUI.

I think that the main use case in every cms looks like this:
1. User is signed in 2. User chooses content type 3. User inputs some data (text, images, links) 4. Preview 5. Save, Publish

So these things should be top priority. Going forward:
- focus at first on .md files (one format of content files)
- to make in GUI some field to choosing existing content types ex. post, project, article etc. (layouts, templates, front matter already made earlier by admin). 
- to help redactors construct markdown content, by adding some typical editor features - small buttons on the top (image button, link button, header button etc.) For now they can put only placeholder into text. Next stage - some simple forms in the modals or hidden divs?
- maybe fields you have proposed above, but somewhere you have to configure it (for example keywords - should have input field or text-area field in GUI?) Some Hugo sites doesn’t have content at all, everything goes from toml/yaml values.

**Comment by hacdias** [comment]
Hi @adprof 

~~I liked your (very extensive :P) opinion and created a simple [roadmap](https://github.com/hacdias/caddy-cms/wiki/Roadmap). I don't have too much to say, just that the plugin currently has a toml/yaml/json editor. I hope this weekend I can do more things.~~

**Edit 6 feb 2016:** I think issues is a good place to have the plans for new features. I don't think we need a full featured roadmap.

**Comment by adprof** [comment]
Well, I promised to share ideas :smile:
