### ISSUE TITLE
docker安装升级后不能保留设置，建议增加设置备份恢复功能。

### ISSUE THREAD

**Issue by cclove845** [filebrowser/filebrowser#2801]
docker安装升级后不能保留设置，建议增加设置备份恢复功能。

请问是否有更好的升级方式，能保留原设置。

**Comment by superzjg** [comment]
filebrowser.db保存了设置信息，备份这个文件即可。

**Comment by cclove845** [comment]
> filebrowser.db保存了设置信息，备份该文件即可。

为什么我两个服务器用的docker安装filebrowser没有filebrowser.db这个文件？

**Comment by superzjg** [comment]
> > filebrowser.db保存了设置信息，备份该文件即可。
> 
> 为什么我两个服务器用的docker安装filebrowser没有filebrowser.db这个文件？

那我就不知道了。这里有配置参考：
https://filebrowser.org/installation#linuxserver

若不行的话，你重新用英文询问一下，作者是用英文的。
