### ISSUE TITLE
html file

### ISSUE THREAD

**Issue by heast90** [filebrowser/filebrowser#2805]
Loading html files with the filebrowser is very different from opening them with the browser

![image](https://github.com/filebrowser/filebrowser/assets/69491295/ece59184-07ee-4895-b76c-738d93302092)
![image](https://github.com/filebrowser/filebrowser/assets/69491295/d67bd4e0-534c-4b92-9db4-b2d64b705c23)
![image](https://github.com/filebrowser/filebrowser/assets/69491295/f614c6d8-beca-4db7-8dd8-e77115a281b1)
I want to be able to modify the same as the browser opened directly

**Comment by superzjg** [comment]
Directly open files such as HTML and ASP, which display the source code and can be edited directly.

![无标题](https://github.com/filebrowser/filebrowser/assets/115226261/b8d756d6-1745-4b87-b498-a759590b4141)
