### ISSUE TITLE
After opening a document through the search function and closing it, the page cannot scroll

### ISSUE THREAD

**Issue by superzjg** [filebrowser/filebrowser#2807]
**Description**
The page cannot scroll, when opening a document through the search function and then closing it.

**How to reproduce?**
1. In a directory  (version 2.26.0)
2. Search for a document in the top search bar 
3. Select a document in the result list and open it 
4. Close this document

**Files**

**Comment by jrelax** [comment]
this issue is still present in v 2.27.0
