### ISSUE TITLE
Add nl_NL to the Transifex translations.

### ISSUE THREAD

**Issue by cvyl** [filebrowser/filebrowser#2808]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Having nl_NL locales added to the project.

**Describe alternatives you've considered**
I've considered Dutch (Belgium) but they are different in a few ways.

**Additional context**
I think having the primary language of Dutch, which is nl_NL, would help make the application more accessible to those who don't speak English. Having only nl_BE is like only having en_US when en_UK doesn't exist.

**Comment by JonathanBout** [comment]
~~This is a duplicate of #2691~~ that one is closed

**Comment by cvyl** [comment]
Unstale

**Comment by cvyl** [comment]
Unstale

**Comment by cvyl** [comment]
Unstale

**Comment by cvyl** [comment]
Unstale

**Comment by cvyl** [comment]
Unstale
