### ISSUE TITLE
Upload failed: Error: tus: unable to resume

### ISSUE THREAD

**Issue by prologic** [filebrowser/filebrowser#2816]
Some of my internal users are seeing this error and I'm not sure what it means just yet.

[
<img width="716" alt="Screenshot 2023-11-08 at 21 39 35" src="https://github.com/filebrowser/filebrowser/assets/1290234/90c087f1-608e-4433-b4c5-523a470b9514">
](url)

No logs on the backend (_have not explored increasing logging level yet_)

**Comment by flo741** [comment]
I am getting the same issue by uploading through Traefik reverse proxy. By going over the local IP without the reverse proxy, it is no problem to upload. Same issue under #2794. A fix regarding TUS is very appreciated. Love to use FileBrowser! THX

**Comment by prologic** [comment]
Bump

**Comment by flo741** [comment]
Not stale
