### ISSUE TITLE
Horrible, never works

### ISSUE THREAD

**Issue by willbr10** [filebrowser/filebrowser#2828]
![Captura de tela de 2023-11-14 15-07-05](https://github.com/filebrowser/filebrowser/assets/31627145/22a03909-9763-4268-a44b-d92b11bb596d)
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by gtsteffaniak** [comment]
thats likely because filebrowser binary does not have filesystem permissions to the volume you specified.

**Comment by Aetherinox** [comment]
Yup. These are permission issues. Not related to the program itself. It's the responsibility of the user.
