### ISSUE TITLE
Settings reset after "2.23.0_reverted2" update (including authentication data)

### ISSUE THREAD

**Issue by bcutter** [filebrowser/filebrowser#2838]
**Description**
After updating from 2.23.0_reverted to 2.23.0_reverted2 everything is reset to default, like language settings or especially annoying login password for admin (as visible in addon log data: admin/admin)

**Expected behaviour**
Previous custom account data is preserved

**What is happening instead?**
Default authentication is used and all other settings are reset too

**Additional context**
Potentially because of the /config and /addon_config changes going on.

**How to reproduce?**
Use 2.23.0_reverted. Update to 2.23.0_reverted2. Try to login with your former login data.

**Files**
/

**Comment by superzjg** [comment]
You should back up the database file "filebrowser.db", which may have been lost during the upgrade process.

**Comment by bcutter** [comment]
I restored my few settings manually (language, folder view, password etc.).

While it was "fixed" for me already at the time creating this issue, this one is more to raise attention in case this is a general problem with the update. So all other users won't run into the same issue.

**Comment by bcutter** [comment]
OK, after updating `2.23.0_reverted4` to `2.23.0_reverted5` it happened again!

Not sure what causes this, but definitely every update breaks things. Either the path to or the `filebrowser.db` file itself is damaged.

Time to investigate! What do you need?

```
23-11-21 17:14:00 INFO (MainThread) [supervisor.docker.addon] Updating image ghcr.io/alexbelgium/filebrowser-aarch64:2.23.0_reverted4 to ghcr.io/alexbelgium/filebrowser-aarch64:2.23.0_reverted5
23-11-21 17:14:00 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/alexbelgium/filebrowser-aarch64 with tag 2.23.0_reverted5.
23-11-21 17:15:49 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_db21ed7f_filebrowser application
23-11-21 17:15:49 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_db21ed7f_filebrowser application
23-11-21 17:15:49 INFO (MainThread) [supervisor.addons.addon] Add-on 'db21ed7f_filebrowser' successfully updated
23-11-21 17:15:50 INFO (SyncWorker_2) [supervisor.docker.manager] Cleanup images: ['ghcr.io/alexbelgium/filebrowser-aarch64:2.23.0_reverted4']
23-11-21 17:15:51 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: db21ed7f_filebrowser
23-11-21 17:15:51 INFO (SyncWorker_1) [supervisor.addons.addon] Creating Home Assistant add-on config folder /data/addon_configs/db21ed7f_filebrowser
23-11-21 17:15:53 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/filebrowser-aarch64 with version 2.23.0_reverted5
```

**Comment by superzjg** [comment]
Perhaps the upgrade script deleted filebrowser.db, and filebrowser automatically generate the original database on next startup.
Just backup filebrowser.db and manually restore it

**Comment by bcutter** [comment]
You don't get my point here: I am very capable of fixing this by myself. I just
a) don't want to do that on every update
b) believe others might suffer from the same so someone should **actually fix this**.

**Comment by o1egl** [comment]
Looks like you are using unofficial builds. We are not providing support for it.

**Comment by bcutter** [comment]
> Looks like you are using unofficial builds. We are not providing support for it.

It actually just happened NOW that I realized this is the official/default filebrowser repository. I really thought I used the correct one. Sorry for wasting your time.
