### ISSUE TITLE
用的docker安装或升级filebrowser没有filebrowser.db这个文件,只有filebrowser.db文件夹，文件夹里内容为空

### ISSUE THREAD

**Issue by cclove845** [filebrowser/filebrowser#2839]
我的两个服务器用的docker安装或升级ffilebrowser没有filebrowser.db这个文件,只有filebrowser.db文件夹，文件夹里内容为空，
建议web设置页面增加备份或恢复设置，另外升级后能保留原设置。

![QQ截图20231122135230](https://github.com/filebrowser/filebrowser/assets/67997283/8cda5a3c-03a3-4996-ad9c-8594eae6bc6f)

![QQ截图20231122135241](https://github.com/filebrowser/filebrowser/assets/67997283/4e166c5b-d633-45c0-b1cd-affe7c8c5479)

**Comment by superzjg** [comment]
如果可以启动过filebrowser，就会产生一个filebrowser.db，若没有设置位置，就在binary的相同位置。
使用filebrowser定位到此文件，下载下来即备份；
删除此文件，上传备份文件再重启服务即恢复（不要直接替换）。

docker的环境应该也差不多，看下配置文件指定的db在哪里吧。

**Comment by cclove845** [comment]
> filebrowser.db

你看我发的图片，整个vps搜索了只有filebrowser.db这个名字的文件夹，没有找到filebrowser.db这个文件，docker或映射里面都是这样

![image](https://github.com/filebrowser/filebrowser/assets/67997283/f61314a0-d356-4715-ac77-57a7a5ba0172)

**Comment by superzjg** [comment]
> > filebrowser.db
> 
> 你看我发的图片，整个vps搜索了只有filebrowser.db这个名字的文件夹，没有找到filebrowser.db这个文件，docker或映射里面都是这样
> 
> ![image](https://private-user-images.githubusercontent.com/67997283/286189282-f61314a0-d356-4715-ac77-57a7a5ba0172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjI0MjMsIm5iZiI6MTcwMTE2MjEyMywicGF0aCI6Ii82Nzk5NzI4My8yODYxODkyODItZjYxMzE0YTAtZDM1Ni00NzE1LWFjNzctNTdhN2E1YmEwMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA5MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2N2E5NjA3NDBlYjU0NGJjMGM5Njc2ZmFiZThiNmFlMDY4OWQxODY1ZjU5NWQ2NjMwOWUwZGVkZWE0NmM3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.54sWyQGIVlAZJEQXcmqeuIpn9uSI7ARg2PI0Pl4JnFE)

我也是使用者，无法复现你的环境。
但倘若你能登录filebrowser，那么登录信息等数据就会储存在filebrowser.db里面，没有此文件就会自动生成默认的db。
不妨到filebrowser里面去搜索一下。

**Comment by luweijun1992** [comment]
> 我的两个服务器用的docker安装或升级ffilebrowser没有filebrowser.db这个文件,只有filebrowser.db文件夹，文件夹里内容为空， 建议web设置页面增加备份或恢复设置，另外升级后能保留原设置。
> 
> ![QQ截图20231122135230](https://private-user-images.githubusercontent.com/67997283/284803680-8cda5a3c-03a3-4996-ad9c-8594eae6bc6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTk5MDYsIm5iZiI6MTcwMjU1OTYwNiwicGF0aCI6Ii82Nzk5NzI4My8yODQ4MDM2ODAtOGNkYTVhM2MtMDNhMy00OTk2LWFkOWMtODU5NGVhZTZiYzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTlmYjNjMzlkZDM1MmEyOTE5ODBiZDY5Y2FhNDZkZjc4ZDIyYTcyZTUzZTk3MWFkODI1Yzg5NDhjNWVhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kclUaKsLn9MjZZozIp_VnhzY8RvMtAEJnEAjtAgq670)
> 
> ![QQ截图20231122135241](https://private-user-images.githubusercontent.com/67997283/284803753-4e166c5b-d633-45c0-b1cd-affe7c8c5479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTk5MDYsIm5iZiI6MTcwMjU1OTYwNiwicGF0aCI6Ii82Nzk5NzI4My8yODQ4MDM3NTMtNGUxNjZjNWItZDYzMy00NWMwLWIxY2QtYWZmZTdjOGM1NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2M0ZjQ0ZWYxNWViYzRmN2FlMTZmMjUwZTE5OTcxODI2ODA3ZTNhNGU1ODY1NmQ4NjQ3NDRhYjlkYWYzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JwaOrpz_Y_B3GIgGoQ32OVJxRkLO7-KbrRlmdSTo6u0)

一样遇到
1、先不挂载路径文件把镜像启动
2、把那2个文件复制到宿主机上
3、删除容器
4、可正常挂载文件启动

**Comment by elzx66** [comment]
![image](https://github.com/filebrowser/filebrowser/assets/34389340/e6278396-3b26-40cd-a0b6-afd23e067537)
docker安装包 有两个版本(alpine、linuxserver。我当时安装的时候也没注意，重新捯饬一下试试) 两个版本的需要映射的路径不一样。这个图片红线里的部分说的明白----需要先手动创建一下db文件，如果为空，filebrowser容器会自动创建一个db文件夹。所以出现一个空的文件夹，是filebrowser默认的操作，但是这会导致容器报错，官方文件里是这样说的，你可以自己翻译一下。
官网地址：https://filebrowser.org/installation

**Comment by cclove845** [comment]
> ![图像](https://private-user-images.githubusercontent.com/34389340/290966601-e6278396-3b26-40cd-a0b6-afd23e067537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTcyNjQsIm5iZiI6MTcwMzIxNjk2NCwicGF0aCI6Ii8zNDM4OTM0MC8yOTA5NjY2MDEtZTYyNzgzOTYtM2IyNi00MGNkLWEwYjYtYWZkMjNlMDY3NTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzNDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MzBiOTBlMjU5YmM4ZmY1YTU5Njc5MTllODM0ZTBhYmU5NGM1YTIwOTg2MGJlMjRjZmNjNmUzZGY2NzBhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jX-xVGMNcfNLAuLM9b2g3xNSr7jcsgvXM_wKOwkoHxk) 安装docker包有两个版本(alpine、linuxserver。我当时安装的时候也没注意，重新捯饬一下试试)两个版本的需要映射的路径不一样。这张图红线里的部分说的明白—— --需要先手动创建一下db文件，如果为空，filebrowserContainer会自动创建一个db文件夹。所以出现一个空的文件夹，是filebrowser默认的操作，但是这会导致Container报错，官方文件里是这样说的，你可以自己翻译一下。 官网地址：https://filebrowser.org/installation

非常感谢！
