### ISSUE TITLE
运行代码访问首页报错 /: 500 127.0.0.1 open public\index.html: file does not exist

### ISSUE THREAD

**Issue by xiangxiang0826** [filebrowser/filebrowser#2840]
**Description**

把代码拉到本机运行之后，访问ip:port，提示 /: 500 127.0.0.1 open public\index.html: file does not exist
**Expected behaviour**

我不确定是不是我有什么配置没有配好，但是我试图修改了下static.go的108行的默认文件配置，也还是不行
**What is happening instead?**

写入绝对路径：
/: 500 192.168.1.11 read /root/filebrowser-master/frontend/public/index.html: invalid name

写入相对路径：
2023/11/22 14:36:18 /: 500 192.168.1.11 open public/index.html: file does not exist

确认文件路径直接cat是可以输出内容，而且权限已经设置777了
**Additional context**

**How to reproduce?**

**Files**

**Comment by Tomortec** [comment]
我也遇到了同样的问题，解决方法是 [https://filebrowser.org/contributing#build](https://filebrowser.org/contributing#build)
`先构建前端，再构建后端`  

1. 先安装`node`(node 版本似乎要大于12)
2. 进入`frontend`文件夹运行`npm install`下载前端依赖
3. 在`frontend`文件夹内运行`npm run build`构建前端
4. 退回到`filebrowser`文件夹，运行`go mod download`和`go build`
5. 此时`filebrowser`中应该有了filebrowser的可执行文件，这个应该是可以用的

当然，上面的步骤也可以用`Makefile`运行，在`filebrowser`文件夹执行`make help`查看详情

对了，`static.go`里面的代码记得还原回去，它目前看起来是没有问题的，就用相对的路径

祝你好运😉

**Comment by xiangxiang0826** [comment]
> 我也遇到了同样的问题，解决方法是 https://filebrowser.org/contributing#build `先构建前端，再构建后端`
> 
> 1. 先安装`node`(node 版本似乎要大于12)
> 2. 进入`frontend`文件夹运行`npm install`下载前端依赖
> 3. 在`frontend`文件夹内运行`npm run build`构建前端
> 4. 退回到`filebrowser`文件夹，运行`go mod download`和`go build`
> 5. 此时`filebrowser`中应该有了filebrowser的可执行文件，这个应该是可以用的
> 
> 当然，上面的步骤也可以用`Makefile`运行，在`filebrowser`文件夹执行`make help`查看详情
> 
> 对了，`static.go`里面的代码记得还原回去，它目前看起来是没有问题的，就用相对的路径
> 
> 祝你好运😉

非常感谢，已经能正常跑起来了~
