### ISSUE TITLE
[BUG] Filebrowser session auto logs-out after 2 hours, even with --auth.method=noauth set.

### ISSUE THREAD

**Issue by d8ahazard** [filebrowser/filebrowser#2849]
**Description**
Disable all authentication in filebrowser, as we don't need it.

**Expected behaviour**
Filebrowser opens in my browser and stays that way indefinitely without making me log in.

**What is happening instead?**
After an extended period of time (Apparently two hours), the session in Filebrowser logs out, and the user is redirected to the login screen.

**Additional context**
filebrowser config set --auth.method=noauth

**How to reproduce?**
filebrowser config set --auth.method=noauth

**Files**
N/A

**Comment by stonfute** [comment]
Same Problem here sessions are too shorts ... Should have a checkbox for "permanent" login

**Comment by alexindigo** [comment]
Same here, setting noauth in the filebrowser.json has no effect.
