### ISSUE TITLE
Write Documentation about the API

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#285]
Some people have been asking me to write the documentation for the API of File Manager. Please vote here instead of creating a new issue 😄 I'd really like to do this, but first it is more important to improve File Manager (and fix bugs!!) and document its features.

**Comment by francislavoie** [comment]
Duplicate of https://github.com/hacdias/filemanager/issues/224 probably 😛

**Comment by hacdias** [comment]
OMG. Didn't see. Thanks @francislavoie
