### ISSUE TITLE
Docker options do not persist between versions

### ISSUE THREAD

**Issue by hodgesp** [filebrowser/filebrowser#2851]
**Description**
When updating to new versions (or using latest after updates) the settings do not persist.

**Expected behaviour**
Pull new version and current settings (DB and/or JSON) should be persisted. 
Able for existing users to login.

**What is happening instead?**
When pulling new version and deploying, I must re-create users, settings, and permissions.

**Additional context**
Need to add persistent disk for storing settings between versions. Moving settings to Docker volume allows for this as well as easier backups via CP in Linux host rather than moving files out of containers.

**How to reproduce?**
1. Deploy version N-1 via Docker
2. Login and modify setting(s) such as Global Settings > Instance name to "Test"
3. Deploy version N via Docker to replace current
4. Login and not instance name does not persist

**Comment by meminens** [comment]
I am having the same issue. There are posts from 1-2 years ago. I think it is something to do with the docker not setting permissions correctly. I have tried all the workarounds in other threads but nothing worked. Including copying the database into the bind volume. After container restart, everything goes to back to defaults. Such as credentials. I notice that database.db is not changing at all judging by the timestamps.

**Comment by skaboy71** [comment]
Re-opening as I have this same issue.  Just got an update on my unraid and the DB reset which could have allowed public access.  This is really unacceptable.  I have disabled auto-updates.

**Comment by Shurov** [comment]
Bumping to avoid becoming Stale. + calling for some action
