### ISSUE TITLE
"001 Connection aborted" when transferring files with a colon character

### ISSUE THREAD

**Issue by Pobega** [filebrowser/filebrowser#2858]
**Description**
Transferring a zip file to my Miyoo Mini, it failed about halfway through. After the failure I can no longer attempt to upload this file. Other files upload fine.

**Expected behaviour**
File would upload correctly, preferably starting at the point the connection was aborted previously.

**What is happening instead?**
The upload is failing to start with '001 Connection aborted'.

**Additional context**

**How to reproduce?**
Upload a file. Interrupt the upload halfway. Try uploading again.

**Files**
Small zip, 4mb.

**Comment by pjkeenan0** [comment]
I have a similar issue but with downloading. Starts ok but after a few seconds the speed just falls to 0. After a few seconds it starts up again (I assume chrome just retrying the connection?) and then falls to 0. It seems to have only happened in the newest release but not 100%, need to test further.

**Comment by Pobega** [comment]
The issue ended up being related to the filename, I believe it was a colon (`:`). Seems like the file transfer program fails to handle them.
