### ISSUE TITLE
Gui change files permissions

### ISSUE THREAD

**Issue by pizarrocz** [filebrowser/filebrowser#2859]
Hi, 
I installed filebrowser on a ubuntu server, but im trying to change permissions like chmod via graphical interface but i cant find this option.

I have  friend that uses filebrowser on a hosting platform and he got that feature enabled, does anybody know where i can enable this?

![permissions_filebrowser](https://github.com/filebrowser/filebrowser/assets/66091627/6e8dab68-f5bc-430c-a5ff-c7d7249fbaee)

**Comment by superzjg** [comment]
Maybe no this in generic release.
You can use the built-in shell in Filebrowser.

![截屏2023-12-05 11 49 58](https://github.com/filebrowser/filebrowser/assets/115226261/6fa0e39c-75ae-43fb-b264-1041943f37a5)
