### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by francislavoie** [filebrowser/filebrowser#286]
This would be really nice to have. Specifically, TOTP and security keys (FIDO U2F).

How I envision it working: 

- Option to _require_ users to set up 2FA when they first log in OR if not enforced, just the option to set it up from their settings page
- Generate a secret using an OTP lib, display the QR code to the user for them to scan it with their phone app, store the key for the user in the DB
- Require the user to enter an OTP code to confirm they have it
- Optionally, once they have OTP set up, they could add a security key as an alternative (e.g. shameless plug: https://bluink.ca/key, or a Yubikey)
- U2F works by storing a key handle, certificate, public key and counter once registered. Most of the hard work is probably dealt with by the lib, but some stuff needs to be done with JS to enable the client-side support. 

Libs you could use:
- https://github.com/pquerna/otp
(I recommend just using TOTP, not HOTP because TOTP is easier to use, but just as secure)
- https://github.com/ryankurte/go-u2f

I can probably answer any questions you have about it.

**Comment by hacdias** [comment]
I think this would be a very nice feature to have! Thanks for suggesting. I'll probably only be able to start this in three or four weeks when I start to have more time to give to this project. In the meanwhile, if you have time and are interested in this, you could fork the project and start implementing this 😄 I'd give my help if you needed.

**Comment by luxorJD** [comment]
I use google authenticator for 2 step verification in other web applications. 
Is it possible to implement this ??

**Comment by TCB13** [comment]
Also waiting for this feature!

**Comment by JulioRamos0** [comment]
Any update?

**Comment by ovidiucp** [comment]
A better way would be to rely on external authentication providers (Google, Facebook etc.), and configure your filebrowser installation to use the [proxy authentication mode](https://filebrowser.xyz/configuration/authentication-method). You can use [oauth2_proxy](https://github.com/pusher/oauth2_proxy) to provide the authentication for you, with nginx in front to handle the requests.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by TCB13** [comment]
Can we reopen this? Thank you!

**Comment by ertuil** [comment]
Can we open this issue again? This is really a good feature.

**Comment by dohlin** [comment]
Agreed, this would be a really great feature to have!

**Comment by TheFrenchGhosty** [comment]
Interested in this too.

(ping @o1egl )
