### ISSUE TITLE
Other accounts failed to upload files

### ISSUE THREAD

**Issue by wuxingyun** [filebrowser/filebrowser#2863]
This error occurs when uploading files, but the admin account does not have this problem, and other accounts will have this problem

![1701916152341](https://github.com/filebrowser/filebrowser/assets/37184972/b00dadbf-5be7-4bc9-8faf-d58d7a473a97)
![1701916152344](https://github.com/filebrowser/filebrowser/assets/37184972/44f9d947-9965-4c25-81ca-646285e4b2d6)

**Comment by wuxingyun** [comment]
version：File Browser 2.26.0

**Comment by AntonyCilleros** [comment]
same issue, solved by allowing my users to edit files (they are also allowed to create, share and download)
But I don't want them to edit my files so that's annoying me

**Comment by wuxingyun** [comment]
> 同样的问题，通过允许我的用户编辑文件（他们也被允许创建、共享和下载）解决了这个问题，但我不希望他们编辑我的文件，所以这让我很烦恼

In theory upload should require a separate permission, see your description other account upload failure requires editing and creation permissions
