### ISSUE TITLE
shared file download link bypasses password

### ISSUE THREAD

**Issue by JustinWebDev** [filebrowser/filebrowser#2866]
**Description**

shared file download link bypasses password

**Expected behaviour**

the password should be requested before the download starts

**What is happening instead?**

the user is not prompted for a password

**Additional context**

**How to reproduce?**

share a file > set a password for the share
copy the download link for the share, e.g.:
http://192.168.0.11:8080/api/public/dl/NAe9rn14/21.mp4?token=VW-XkFrTvZxAJ3mp5c0InBcc74JObXsN5FZrYmlE8P2X8S-B_DcD-YsfossKDtGwFAR1l2pozfH-P4nppca-718Ssr28qFyoPWEAZliF6cZLkcg4NyrEG3EF3sIDyf_P

on another machine, browse to the download link - observe the browser starts to download and does not prompt for the password

**Files**

**Comment by JustinWebDev** [comment]
Wow.

**Comment by lordpayder** [comment]
Just noticed this problem on latest version. Can we please get a fix?

**Comment by JustinWebDev** [comment]
Hey @lordpayder I'm thinking another issue might need to be created so that it will be on the 'open' list (maybe more visible, as I don't know if any devs will see comments on this one).  Thanks for commenting!

**Comment by LorisFriedel** [comment]
Hi! Same issue here, can we reopen this issue please?

**Comment by JustinWebDev** [comment]
I created another issue for it
https://github.com/filebrowser/filebrowser/issues/3470#issue-2511317264
