### ISSUE TITLE
如何禁止下载文件夹，防止压缩文件夹，导致爆内存

### ISSUE THREAD

**Issue by mini1025** [filebrowser/filebrowser#2868]
共享文件夹时，在左边有个下载字样，点击后，会直接压缩整个文件侠，导致爆内存，引起死机

**Comment by jniggemann** [comment]
Translation

Title: How to prohibit downloading folders and prevent compressed folders from causing memory explosion
Body: When sharing a folder, there is a download word on the left. After clicking it, the entire file will be compressed directly, causing the memory to explode and causing a crash.
