### ISSUE TITLE
How to complie for mips32le (my router)

### ISSUE THREAD

**Issue by ryubaisan** [filebrowser/filebrowser#287]
I use filemanger in my router (CPU MTK7621A, OS linux ARCH mips32le) and it works fine,thanks.
the version in use is complied by others and I want to get the newest version.
I have worked for a week but always failed.

Question:
can  the newest version be complied successfully in linux/mips32le? how can I do it? could you give some clues?it seems that GO 1.9.2 has no  mips32le  in GOARCH option, when i use mipsle it also show errors.

**Comment by hacdias** [comment]
Hello! Try this command: `GOOS=linux GOARCH=mipsle go build`.

**Comment by ryubaisan** [comment]
i run this command in filemanager floder,nothing error and nothing binary file out.

when i run 
GOOS=linux GOARCH=mipsle go build -v github.com/hacdias/filemanager/cmd/filemanager

it shows
github.com/boltdb/bolt
# github.com/boltdb/bolt
../../boltdb/bolt/db.go:101:13: undefined: maxMapSize

**Comment by eine** [comment]
Just tested it in a `golang-alpine` container and it works as expected:

``` bash
$ mkdir tmp-build && cd tmp-build
$ docker run --rm -itv $(pwd):/srv -w /go/src/github.com/filebrowser golang:alpine sh -c "\
  apk update && \
  apk add git && \
  git clone --recurse-submodules https://github.com/filebrowser/filebrowser/ && \
  cd filebrowser/cmd/filebrowser && \
  go get ./... && \
  GOOS=linux GOARCH=mipsle go build -v -o /srv/filebrowser"
$ file filebrowser
filebrowser: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, with debug_info, not stripped
$ cd ..
$ rm -rf tmp-build
```

``` bash

```

@ryubaisan, please let us know if it works for you now.

**Comment by carlsue** [comment]
> Just tested it in a `golang-alpine` container and it works as expected:
> 
> ```shell
> $ mkdir tmp-build && cd tmp-build
> $ docker run --rm -itv $(pwd):/srv -w /go/src/github.com/filebrowser golang:alpine sh -c "\
>   apk update && \
>   apk add git && \
>   git clone --recurse-submodules https://github.com/filebrowser/filebrowser/ && \
>   cd filebrowser/cmd/filebrowser && \
>   go get ./... && \
>   GOOS=linux GOARCH=mipsle go build -v -o /srv/filebrowser"
> $ file filebrowser
> filebrowser: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, with debug_info, not stripped
> $ cd ..
> $ rm -rf tmp-build
> ```
> 
> @ryubaisan, please let us know if it works for you now.

have no web ui,so i get into docker and follow offical doc:
  apk update && \
  apk add git npm&& \
  git clone --recurse-submodules https://github.com/filebrowser/filebrowser/ && \
  and so on .....

but get error
/go/src/github.com/filebrowser/filebrowser/http # rice embed-go
error reading package: go/build: importGo github.com/filebrowser/filebrowser/http: exit status 1
can't load package: package github.com/filebrowser/filebrowser/http: module github.com/filebrowser/filebrowser@latest found (v1.11.0), but does not contain package github.com/filebrowser/filebrowser/http

**Comment by carlsue** [comment]
here you are,mipsle version v2.11.0
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972922/filebrowser.zip)

**Comment by tosiek** [comment]
Could I kindly ask for newest version compilation for mips32?
