### ISSUE TITLE
Full file paths in URLs

### ISSUE THREAD

**Issue by perryclarke** [filebrowser/filebrowser#288]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes.  caddy_v0.10.10_linux_amd64_custom_personal.tar.gz

### 2. What is your entire Caddyfile?
```text
sitename.co {

	root /home/caddy/www/sitename/quickstart/public
	hugo /home/caddy/www/sitename/quickstart /admin {
		allow_commands      true
		allow_edit          true
		allow_new           true
		allow_publish       true
	}


	log /home/caddy/logs/access-sitename.log
	errors /home/caddy/logs/errors-sitename.log {
		404 ../keep-calm-404.html
	}
}
```

### 3. What are you trying to do?
I'm using the "Hugo New" menu item to create a new post called `NewPost.md`.  Incidentally, if you omit the file extension here File Manager issues a confusing "Bad Request" error; took me a while to figure that out.

### 4. What did you expect to see?
I expect to see a new file appear in the folder pointed to by "scope" which for the user is `/home/caddy/www/sitename/quickstart/content/posts`

### 5. What did you see instead (give full error messages and/or log)?
The file is created in `/home/caddy/www/sitename/quickstart/content/home/caddy/www/sitename/quickstart/content/posts/MyNewPost.md`
 (note the full path to the file is repeated in the folder path created by File Manager)

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
I'm sure I've misconfigured something but I can't figure out what that might be so, other than creating a new user and setting their scope to `<site-root>/content/posts`, I'm not sure 

After some investigation, it appears this is basically a bug in Hugo:
```
hugo new -k post `pwd`/posts/TestPost1.md
/home/caddy/www/sitename/quickstart/content/home/caddy/www/sitename/quickstart/posts/TestPost1.md created
```
If given a full path, Hugo should not prepend the current directory to that path (it might have to complain that the path is invalid but that's a separate issue). 

So my question is: how do I stop File Manager triggering this Hugo bug?  I tried setting the user's scope to just `content/posts` (i.e. a relative path) but File Manager gave an "Internal Server Error":
```
2017/11/25 20:33:46 /2: 500 Internal Server Error
2017/11/25 20:33:46 mkdir content/posts: permission denied
```

**Comment by hacdias** [comment]
Hello @perryclarke! Thanks for this! Could you open an issue on gohugo/hugo, please?

**Comment by tutley** [comment]
I'm experiencing the same thing. I believe this has something to do with the hugo plugin itself and the way it manages user scope. If you go in and change the user scope to "./" rather than the path to the directory with the hugo site, then using "hugo new" creates files in the content directory as you'd expect.

**Comment by hacdias** [comment]
Fixed! 😄 It will be available on the next release.
