### ISSUE TITLE
Http 403 when user only has create permission

### ISSUE THREAD

**Issue by CEbbinghaus** [filebrowser/filebrowser#2880]
**Description**
If a user only has the Create and not the Edit permission they are entirely unable to upload files. Even if setting the TUS size limit to 200Mb it will still prevent them. 

**Expected behaviour**
Users only require the Create permission to upload files.

**What is happening instead?**
User requires both the create & edit permissions to successfully upload any file. 

**Additional context**

**How to reproduce?**
1. Create user with only Create permission.
2. Try uploading a file as that user

**Files**

**Comment by CEbbinghaus** [comment]
This is likely due to the fact that the behaviors of the API is too correct. Since technically a PATCH request does modify a file the api requires the user to have edit permissions. However it will only ever be called in the context of sending another chunk of data via upload. As such it should be dependent on whether or not a user is currently uploading a file. I would hazard a guess that it would be possible to determine whether this PATCH is happening as part of an upload via a http header and allow users without Edit permissions to still upload files

**Comment by Heywaht** [comment]
Need root. Use the Start Command with sudo

**Comment by CEbbinghaus** [comment]
@Heywaht this is not true. the tus_handler explicitly returns a 403 if the user does not have the Modify permission:
https://github.com/filebrowser/filebrowser/blob/cfafefa35a81c09f1ed5a4cf81b65a655ce519fc/http/tus_handlers.go#L95-L97
Sudo has nothing to do with it

**Comment by CEbbinghaus** [comment]
You are kidding me, Reopen please.

@o1egl?
