### ISSUE TITLE
custom keyboard shortcuts to fix arrow keys issue in chrome and firefox

### ISSUE THREAD

**Issue by nwgat** [filebrowser/filebrowser#2885]
**Is your feature request related to a problem? Please describe.**
yes, when am seeking in a video, it skips to next video in the folder when using arrow keys as they are the default keys for seeking in both chrome and firefox

**Describe the solution you'd like**
a way to make custom mappings so people wont have this issue in the future
so i would like to change ⬅/➡ keys to ctrl + ⬅/➡ 

**Describe alternatives you've considered**

**Additional context**

**Comment by dariuszszyc** [comment]
My biggest issue with FileBrowser.
