### ISSUE TITLE
Add Ability to browse content in zip file without extracting it

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#2887]
**Is your feature request related to a problem? Please describe.**

 browse zip file requires uncompressing or downloading
**Describe the solution you'd like**

Add Ability to browse content in zip file without extracting it
**Describe alternatives you've considered**

**Additional context**

**Comment by asad-awadia** [comment]
can you do that in javascript?

**Comment by ghost** [comment]
I don't think so. the actual unzip should happen on serverside
