### ISSUE TITLE
add a guest user but could not upload file

### ISSUE THREAD

**Issue by daqingli616** [filebrowser/filebrowser#2894]
**Description**

I added a guest user who can only create file and directory and also can download and view the files but cannot delete and edit files
**Expected behaviour**

The user after login can create a directory as expected and then he can upload file into that directory
**What is happening instead?**

The uploading failed with a zero byte file left in the directory. The error message is reported as:
Upload failed: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: /api/tus/test/2023-10-
24.pdf?override=false, response code: 403, response text: 403 Forbidden, request id: n/a)
**Additional context**

**How to reproduce?**

**Files**

<img width="349" alt="Screenshot 2023-12-22 at 11 07 30 AM" src="https://github.com/filebrowser/filebrowser/assets/17305673/4d2fb2b1-6e41-47a4-9148-3b1eb249f295">

**Comment by Yogesh070** [comment]
@daqingli616  you need to give the user permission to edit file inorder to allow them to upload files.
