### ISSUE TITLE
No realiza la copia completa de archivos.

### ISSUE THREAD

**Issue by imerualfonzo** [filebrowser/filebrowser#2895]
![Captura desde 2023-12-24 15-20-44](https://github.com/filebrowser/filebrowser/assets/64542836/f33238aa-a056-4db4-bdc0-88d149b8e54b)
**Description**
Archivos grandes no se copian desde dispositivos conectados a la misma red.

**Comment by jniggemann** [comment]
Translation

Title: Does not make a complete copy of files

Description: Large files are not copied from devices connected to the same network.
