### ISSUE TITLE
Build error in frontend due to commit fc04578

### ISSUE THREAD

**Issue by Yogesh070** [filebrowser/filebrowser#2903]
**Description**

Commit fc04578e28e492116cac15b93d912386c6648ac3 causes build error on frontend

**Expected behaviour**

Successful build without error.

**What is happening instead?**

[vite:json] Failed to parse JSON file, invalid JSON syntax found at line 881
file: /Users/yogeshthapa/Development/filebrowser/frontend/src/i18n/zh-cn.json

**Additional context**

Missing comma on zh-cn.json causes build error. 

**How to reproduce?**

npm run build or yarn run build (in frontend dir)

**Files**

zh-cn.json

**Comment by People-11** [comment]
My bad, sry.
