### ISSUE TITLE
Unable to Install FileBrowser on OpenMediaVault 6

### ISSUE THREAD

**Issue by AT-StephenDetomasi** [filebrowser/filebrowser#2905]
**Description**
Following the installation documentation available at https://filebrowser.org/installation is insufficient for being able to achieve a functional installation of File Browser on OpenMediaVault 6, a debian-based distribution. Both the standard installation method and docker installation method. 

**Expected behaviour**
I expected the installation to run successfully and to be able to use the service.

**What is happening instead?**
When attempting the direct installation, the CLI reports that the installation is successful, however there is no web interface available on the default port (8080).

When attempting to use the docker installation method, the error message "open /database/filebrowser.db: is a directory" appears in the console and the web interface is inaccessible.

**Additional context**
Docker Install output:

![Screenshot-wl-23-12-30-21-44](https://github.com/filebrowser/filebrowser/assets/113870466/5704d043-4ccd-4bed-baeb-b89286f40d91)

**How to reproduce?**
Install OpenMediaVault 6 and attempt to follow the installation instructions available at https://filebrowser.org/installation

**Comment by dalkain** [comment]
It looks like you manually changed the port mapping from 8080 to 8035 in the command, so the web interface should be available on port 8035 for you.

**Comment by drewlsvern** [comment]
@AT-StephenDetomasi 

It's because you need to manually create an empty filebrowser.db file first before starting docker. Along with the settings.json file (if you choose to do so - this is optional as it will just use the defaults). This is because if the mapped files don't exist, docker creates a directory and not a file.

This is stated in the documentation at the bottom of the installation page [here](https://filebrowser.org/installation)

**Comment by AT-StephenDetomasi** [comment]
Apologies, the documentation is not very clear about this. How does one create an empty filebrowser.db file? I feel this should probably be added to the installation script if it's required for all new installations.

Is there a flag or run command for the docker container that can do this?

**Comment by drewlsvern** [comment]
@AT-StephenDetomasi All good no need for apologies. I agree that the docs aren't very clear, especially if someone isn't familiar with containers. This seems to be a common thing when running containers and mapping drives to the host.

To create an empty file you can run the following command (relative to where you want the file created):

**Linux** 
``` touch filebrowser.db```


**Windows (powershell)**

``` New-Item -ItemType "file" -Path filebrower.db```


As for a flag or run command I'm not sure.
