### ISSUE TITLE
ios can‘t paste when editing file

### ISSUE THREAD

**Issue by ReadyP1ayer** [filebrowser/filebrowser#2907]
When editing file content in iOS, long press operations are overwritten by the editor, making it impossible to call up iOS system copying, pasting, and other operations. The editor's built-in operations only include selection, copying, and cutting, so pasting operations cannot be implemented.

**Comment by ZOMGVTEK** [comment]
I have this same issue. Has anyone found a workaround?

**Comment by ZOMGVTEK** [comment]
Still trying to find a solution to this. Paste in safari on iOS appears to be impossible.
