### ISSUE TITLE
Add event for download started/finished

### ISSUE THREAD

**Issue by Hampo** [filebrowser/filebrowser#2912]
**Is your feature request related to a problem? Please describe.**
I want to keep track of what files are being downloaded, and by whom

**Describe the solution you'd like**
Similar to the existing events, add a new one for when a download is started. Potentially a second event if an archive download is started

**Describe alternatives you've considered**
Not sure what alternative there is

**Additional context**
I tried using the Save event, but I assume that's just for file editing rather than saving a file to the user's disk

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by Hampo** [comment]
Still a valid feature request

**Comment by nvillanueva2** [comment]
Hampoooo!

**Comment by nicovillanueva** [comment]
Hampoooo!
