### ISSUE TITLE
Add User Session Timeout to User Default Settings

### ISSUE THREAD

**Issue by k0gen** [filebrowser/filebrowser#2917]
Hey there,

I noticed that we can now configure the user session timeout (thanks to PR #2753!). That's pretty cool! But, it would be even cooler if we could set this up in the Global Settings > User Default Settings. It would make things a lot easier and more intuitive.

Looking forward to seeing this feature in the future!

**Comment by k0gen** [comment]
Ah, those bots nowadays! 😄

**Comment by usaboxer** [comment]
how do i add this configuration to, say 12h?

**Comment by k0gen** [comment]
> how do i add this configuration to, say 12h?

```
filebrowser --token-expiration-time=12h
```
