### ISSUE TITLE
Not https ?

### ISSUE THREAD

**Issue by Kidou-Software** [filebrowser/filebrowser#2928]
Hello,
how can we make it secure with https?
![image_2024-01-13_003900328](https://github.com/filebrowser/filebrowser/assets/83245233/98c02268-120b-42f6-9dcd-7dc69a42a483)

**Comment by Kidou-Software** [comment]
I have already tried with an SSL certificate, but it destroyed the entire configuration database.

**Comment by JustinWebDev** [comment]
https://filebrowser.org/cli/filebrowser

I use Caddy as a reverse proxy for TLS connections over the WAN.

**Comment by drewlsvern** [comment]
@Gabkill54 

This is another alternative to Caddy for a reverse proxy setup. This comes with a nice web UI to assist in setting up.
[Nginx Proxy Manager](https://nginxproxymanager.com/setup/)

**Comment by Kidou-Software** [comment]
I don't know how to configure these software programs

**Comment by JustinWebDev** [comment]
You could learn  :-)  Caddy is fairly simple as a RP, and there are videos/blogs that will show you how.
