### ISSUE TITLE
Upload failed for large files (> 12 GB), response code: 401

### ISSUE THREAD

**Issue by zcraber** [filebrowser/filebrowser#2931]
**Description**
Unable to upload large files (> 12 GB). Getting the following error:

![Screenshot 2024-01-13 170834](https://github.com/filebrowser/filebrowser/assets/61133303/0b52bf5b-9f24-40b0-8c7a-d35e08079cf8)

**Expected behaviour**
Files should be uploaded fine.

**What is happening instead?**
```
Upload failed: Error: tus: unable to resume
upload (new upload cannot be created without an endpoint), originated from request (method: HEAD, url: /api/tus/home/file.mp4?
override=false, response code: 401, response
text:, request id: n/a)
```
In logs, these can be found:

```
2024/01/13 12:25:34 /api/renew: 401 <nil>
2024/01/13 14:07:57 /home/file.mp4: 409  /srv/homefile.mp4 file size doesn't match the provided offset: 11366563840
```

**How to reproduce?**

1. Go to the folder.
2. Upload the file using the upload button or drag and drop.

**Comment by marshes** [comment]
also experiencing this issue with same error code.
