### ISSUE TITLE
Show the output of the executed commands

### ISSUE THREAD

**Issue by geertvanheusden** [filebrowser/filebrowser#294]
Hi,

It would be nice to see the actual output of a command executed in the search/command field. By having access to this output we could use commands like grep to search through the content of files.

Having a more advanced search, that has the ability to use wildcards and search in files would even be better. ;-)

Kind regards,

Geert

**Comment by jmcclelland** [comment]
Are you using the latest version? I see output when I run a command

![fm-output](https://user-images.githubusercontent.com/4511942/33801358-575cb47c-dd27-11e7-833d-1ddb117304e9.png)

**Comment by geertvanheusden** [comment]
Yes, I am using the latest version running within Docker. I changed the original Dockerfile to use Debian instead of starting from "scratch", so all my necessary tools should be available.

I don't mount a config file but use: `--scope /data --port 80 --baseurl /filemanager --commands grep ls unzip --allow-commands true` as the Docker cmd.

If I execute for example the zip command I get:

![image](https://user-images.githubusercontent.com/1923423/33809560-3d1583c8-ddf9-11e7-8b85-0c25e15ceefa.png)

And the same results for the other commands. Executing those commands from the CLI (using docker exec) work as expected... Am I missing something?

**Comment by geertvanheusden** [comment]
Ok, played around with the `--commands` param and I now use `--commands 'ls grep unzip'`. Result is different:

![image](https://user-images.githubusercontent.com/1923423/33809644-95508910-ddfa-11e7-9132-9534d67bf468.png)

But still no output for all my commands I execute.

**Comment by hacdias** [comment]
Please check the user settings to see if the commands are enabled and if you have 'ls' there. I can't reproduce that behaviour :(

**Comment by geertvanheusden** [comment]
They look correct:

![image](https://user-images.githubusercontent.com/1923423/33809755-1a7e594a-ddfc-11e7-9a2d-01a0a8c60162.png)

Did you try from the Docker container (but starting from an OS like e.g Debian that has `ls` available)

**Comment by geertvanheusden** [comment]
Ok, I think I found it...

![image](https://user-images.githubusercontent.com/1923423/33809814-279ea6e2-ddfd-11e7-9e16-fdeccc616dab.png)

Traffic is going via an AWS Load Balancer and an HA Proxy. Probably something misconfigured over there.

**Comment by hacdias** [comment]
Probably. File Manager doesn't even return 400 (Bad Request) in the commands handler. Does AWS Load Balancer and HA Proxy let you use web sockets?

**Comment by geertvanheusden** [comment]
@hacdias I need to verify this with our ops team tomorrow, probably related to:
https://blog.jverkamp.com/2015/07/20/configuring-websockets-behind-an-aws-elb/

**Comment by geertvanheusden** [comment]
Ok, I managed to fix the issue by changing the ELB settings.

Ticket can be closed. Thanks.
