### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by p3t3rp3pp3r** [filebrowser/filebrowser#2940]
**Is your feature request related to a problem? Please describe.**
I'm using filebrowser since 2021  because it has many feature not easily found in any other similar software
- Easy to configure and use
- Easy to install
- Requires low resources
- Runs on many platforms
- It' s simply a filebrowser

but when I need to handle many users I really miss of a feature to group users with similar needs

**Describe the solution you'd like**
It could be a great feature the possibility to create groups and to group users with same needs
I think a group could contain:
- Scope
- Collection of rules
- Permissions 
- List of users 

If a user belongs to many groups it could inherit rules and permission of the relative Scope in each group

**Additional context**
I know there is an issue in completed state https://github.com/filebrowser/filebrowser/issues/614 but the feature it has not been implemented

**Comment by nycki93** [comment]
not stale
