### ISSUE TITLE
How to fully delete filebrowser?

### ISSUE THREAD

**Issue by Serhioromano** [filebrowser/filebrowser#2941]
I have installed this app through a 3d party script, and it does not allow users to login, immediately opens access to files. I deleted /usr/local/bim/filebrowser file and reinstalled. But configuration is the same. How to delete DB and clean everything from filebrowser so I could try to install it from scratch?

**Comment by SimplisticGH** [comment]
Depending on where the command was run, it will create a filebrowser.db in that location. So you should be able to delete that and everything should reset.
