### ISSUE TITLE
JWT problem despite noauth

### ISSUE THREAD

**Issue by gokhangunduz** [filebrowser/filebrowser#2942]
Hello everyone. When I added the `"noauth": true` attribute to my config json file, I noticed that the JWT token was still used for session tracking even though the login was removed. Naturally there is a cookie used in request headers.

My expectation was to not have to deal with the token issue at all when the "noauth" setting was made.

What I need is to be able to send requests without needing cookies.

Thank you very much in advance for your interest.

**Comment by zjm0518** [comment]
I have the same expectation.Because I want to reuse some frontend components and the whole backend exe in this project,and bypass the whole jwt token in every fetch. Do you find a solution?It seems it still needs jwt anyway..
