### ISSUE TITLE
Command Execute Fails

### ISSUE THREAD

**Issue by jdinocco** [filebrowser/filebrowser#295]
Hi, question...  I add a command like "grep" on a new user and execute like a grep <word> *.sh with no return, any help?

Thanks!

**Comment by hacdias** [comment]
Could you check #294 to see if there is anything related, please?

**Comment by jdinocco** [comment]
Definitely related, I get the following record when I try to execute a command

`2017/12/12 11:22:40 websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header`

This is the scenario, I have a server in an intranet and I access remote with other users, look for related information but I can not find it. :(

**Comment by hacdias** [comment]
Could you show me if there is any error on the Developer Tools' Console?

**Comment by jdinocco** [comment]
Yest, hope help

![imagen](https://user-images.githubusercontent.com/6908410/33891596-26818e80-df35-11e7-8734-111e6d701912.png)

**Comment by hacdias** [comment]
That's strange. Are you using File Manager behind a proxy or something?

**Comment by jdinocco** [comment]
Sorry for that.... my bad!

So with no proxy I can execute a grep for any file with no errors

![imagen](https://user-images.githubusercontent.com/6908410/33891915-2871814a-df36-11e7-9e8a-e329e4641e53.png)

But I can't use a wildcard for the command

![imagen](https://user-images.githubusercontent.com/6908410/33891948-3d1f8baa-df36-11e7-977f-042319460523.png)

Thanks!

**Comment by hacdias** [comment]
So:

1. The proxy is somehow blocking the websocket connections.
2. I don't think the problem with the wildcard is related to File Manager, but I admit it is strange. Can you run it successfully on the directory via terminal?

**Comment by jdinocco** [comment]
yes, now I not using any proxy.

I start the service (no websocket message)
```
root@fs02:~# filemanager
Listening on [::]:43915
```
I copy .bashrc to test.log,  in the terminal execute the command
```

root@fs02:~# grep alias *.log
 alias ls='ls $LS_OPTIONS'
 alias ll='ls $LS_OPTIONS -l'
 alias l='ls $LS_OPTIONS -lA'
 alias apti='apt-get install -y'
 alias aptud='apt-get -y update'
 alias aptug='apt-get -y upgrade'
# Some more alias to avoid making mistakes:
 alias rm='rm -i'
 alias cp='cp -i'
 alias mv='mv -i'
```

On the FM the same command
![imagen](https://user-images.githubusercontent.com/6908410/33892702-3634734e-df38-11e7-9b10-e96f9bbe1993.png)

**Comment by hacdias** [comment]
I'll try to discover what the problem is. But I can't guarantee it to be this week 😞

**Comment by jdinocco** [comment]
No problem and thanks for the help!! ;)

**Comment by eine** [comment]
Closing this in favour of #466 and #486.

**Comment by themegabyte** [comment]
For Nginx, this will be like this:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;
```

Or in nginx proxy manager or equivalent:

![Image](https://github.com/user-attachments/assets/665f602c-f3ee-499e-aed6-fe4d509ba81a)
