### ISSUE TITLE
Improve documentation on settings

### ISSUE THREAD

**Issue by rluetzner** [filebrowser/filebrowser#2956]
**Is your feature request related to a problem? Please describe.**

I wanted to allow a friend access to a specific directory on my server. After a bit of searching the internet, I discovered this project, which seems to be exactly what I want. Simple to set up, but does everything I need it to do.

However, it took me way longer to set up than I initially expected. The main reason for that is because I changed some of the settings in the JSON config file, because I misunderstood them.

I'm running the server on a subdomain and my expectation was that I had to configure the `baseURL`. I guess that is only used when there's a suffix to the path, correct?

I then modified the `address` value, but quickly discovered that this means the _listen_ address.

**Describe the solution you'd like**

A documentation page describing the settings should be added. As a quick and possibly temporary alternative, I can imagine adding an example JSON file where the values contain hints, e.g.

```json
{
   [...]
   baseUrl = "only set this if you know what you're doing",
   address = "the address where the server will listen on, defaults to 0.0.0.0:<port>",
   [...]
}
```

. Yet another alternative would be to support a config format that allows for comments, e.g. TOML or YAML.

**Describe alternatives you've considered**

Umm. I guess I already listed all of them above. 😅 

**Additional context**

-

**Comment by rluetzner** [comment]
If anybody can give me the necessary details, I can also take care of a pull request.

I guess I could also look up everything in the code, but if there's somebody who already knows what all of this does, I can generate some documentation from a brain dump. 🙂

**Comment by tupiznak** [comment]
@rluetzner it was a bit unclear, but it turns out there is already such documentation at this [link](https://filebrowser.org/cli/filebrowser). Spent a lot of time looking for that.

**Comment by rluetzner** [comment]
@tupiznak , nice. Sorry it took a while to get back at you. This is sufficient for me. Thanks for the link. :slightly_smiling_face:
