### ISSUE TITLE
What's the intended upgrade process?

### ISSUE THREAD

**Issue by TehDomic** [filebrowser/filebrowser#2967]
I ran `$ filebrowser --help` in hopes of finding an official way to install any new updates, but neither there nor on the official website or GitHub page do I see any instructions for that. Only new installs.

**Comment by andrewhenke** [comment]
@TehDomic I just had to do an upgrade from v2.25.0 to v2.27.0 and I used the quick install automation script for my Linux machine, and I ran the install script even though I already have the Filebrowser executable on my machine, and the script automatically updated the binary executable to the latest version for my Server. 

<img width="461" alt="image" src="https://github.com/filebrowser/filebrowser/assets/24320242/4dae143c-e8d1-4bec-a98b-fa4f9115b936">


The command to run from your CLI to upgrade on UNIX machines is:
`curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash`

This command is located within the official documentation [as seen here](https://filebrowser.org/installation#:~:text=curl%20%2DfsSL%20https%3A//raw.githubusercontent.com/filebrowser/get/master/get.sh%20%7C%20bash). 

Does this help at all, and can I provide you with any further information?

**Comment by TehDomic** [comment]
> @TehDomic I just had to do an upgrade from v2.25.0 to v2.27.0 and I used the quick install automation script for my Linux machine, and I ran the install script even though I already have the Filebrowser executable on my machine, and the script automatically updated the binary executable to the latest version for my Server.
> <img alt="image" width="461" src="https://private-user-images.githubusercontent.com/24320242/301931383-4dae143c-e8d1-4bec-a98b-fa4f9115b936.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjAwMjEsIm5iZiI6MTcwOTUxOTcyMSwicGF0aCI6Ii8yNDMyMDI0Mi8zMDE5MzEzODMtNGRhZTE0M2MtZThkMS00YmVjLWE5OGItZmE0ZjkxMTViOTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAyMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YWZiMmIzNGJjOWY0ZDY1MWM4MWIyMjU0OTlmZmMwN2MwZWM2Y2M2ZWU3NTZkOWRjMzQ3OGNlNDdiZGJhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LQK68vPYwumFPKgazaLBSlB9l215vGmSl0jv1oMQKhE">
> 
> The command to run from your CLI to upgrade on UNIX machines is: `curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash`
> 
> This command is located within the official documentation [as seen here](https://filebrowser.org/installation#:~:text=curl%20%2DfsSL%20https%3A//raw.githubusercontent.com/filebrowser/get/master/get.sh%20%7C%20bash).
> 
> Does this help at all, and can I provide you with any further information?

I see, could then please update the documentation so it says how people are supposed to update the software? It just says how to install it. :)

Thank you.
