### ISSUE TITLE
how to show the specified folder as home dir?

### ISSUE THREAD

**Issue by hdstar2009** [filebrowser/filebrowser#297]
I want to see the contend of the dir "/home/transmission/Downloads", So I run like this:
filemanager -c /etc/filemanager.json -s /home/transmission/Downloads
But filemanager show me the conten of root directory.
I have no idea and have to ask any help. thanks.

**Comment by hacdias** [comment]
Hello @hdstar2009 😄 

The flag `-s` only tells File Manager which will be the default scope for *new* users. If your user was created in a previous run when you didn't use that flag, it will have the old scope.

You can update it on **Settings** -> **User Management**. 

hope it helps!

**Comment by hdstar2009** [comment]
thanks，it works.
