### ISSUE TITLE
Copy/Move status/progress

### ISSUE THREAD

**Issue by Joly0** [filebrowser/filebrowser#2970]
**Describe the solution you'd like**
Would be great to have any kind of progress or status of running copy and move actions

**Describe alternatives you've considered**
None

**Additional context**

**Comment by crocangIt** [comment]
Hi,
Agree. When I initiate the copy process and close the web portal, I can observe that the copying continues. However, upon reopening the web portal, I am unable to see that the previous task is still in progress.
App Version: 2.27.0 , Chart Version: 1.2.6 
On TrueNAS-SCALE-23.10.1.3
Thanks

**Comment by Joly0** [comment]
Still an issue

**Comment by Joly0** [comment]
Still an issue

**Comment by Joly0** [comment]
Still an issue

**Comment by moda20** [comment]
Still an issue, i will try to work on it next week, but it seems the maintainer is not accepting PRs

**Comment by Joly0** [comment]
Still an issue

**Comment by Joly0** [comment]
Still and issue

**Comment by Joly0** [comment]
Still an issue/request

**Comment by fred-c1** [comment]
I agree. This would help. In particular when the operation (copy, move, delete, ???) takes a lot of time (/minutes/hours)
Even a "simple" busy/ready status would help.
