### ISSUE TITLE
Mobile swipe to next image not working

### ISSUE THREAD

**Issue by Chaleuri** [filebrowser/filebrowser#2978]
**Description**

When opening an image on a mobile device, then swiping to change to the next picture does not work, it only moves the current image to the side.

**Expected behaviour**

I expected it to change to the next image.

**What is happening instead?**

The current image is moved to the side.

**How to reproduce?**

Open an image on a mobile website, then try to change to the next image by swiping on the screen from right to left.

**Comment by niubility000** [comment]
how about this modification? 

[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/14321238/filebrowser.zip)

https://note.youdao.com/s/dk3NtGWB
Just download the zip file and try it in windows, you also can download the modified source codes. 

You can switch imgs, close img's preview with animation by swiping(finger) or dragging(mouse).
