### ISSUE TITLE
Filebrowser ignores port setting in the filebrowser.db file and always starts with port 8080

### ISSUE THREAD

**Issue by dreyerm** [filebrowser/filebrowser#2979]
**Description**
Filebrowser consistently ignores the custom port configured via filebrowser config set -p "8082".
When setting the custom port, console returns that the port is correctly set to 8082 in the config.

However, when rebooting the container, it ignores the setting of port 8082 in the database, and simply listens on 8080.
I've noticed that upon boot, filebrowser executes a screen command, by using the glances package to check processes, I found the following:

SCREEN filebrowser filebrowser -a 0.0.0.0 -p 8080 -r /home/filebrowser

So it appears when starting the container, it automatically executes screen with filebrowser running on port 8080.

I was unable to find where this command is configured, as there's no systemd for it.

**Expected behaviour**
When executing filebrowser set config -p "8082" , it should update the boot command that uses screen, so that when the container start, it correctly listens on port 8082.

**What is happening instead?**
It starts screen with filebrowser listening on port 8080 instead, even though filebrowser config cat -d filebrowser.db shows port 8082.

**How to reproduce?**

* OS: Ubuntu 20.04 LTS
* Filebrowser was installed using brew
* Execute: `cp filebrowser.db filebrowser.db.orig`
* Execute `rm filebrowser.db`
* Execute: `cp filebrowser.db.orig filebrowser.db`
* Execute: `filebrowser config set -p "8082"
* Reboot the LXC container
* Filebrowser continues to listen on port 8080
* Runinng glances, I can see a screen session `SCREEN filebrowser filebrowser -a 0.0.0.0 -p 8080 -r /home/filebrowser` but have no idea what process is triggering it upon container startup

I am currently working around the issue by terminating the existing screen session, and initialising a new screen session that runs `filebrowser -a 0.0.0.0 -p 8082 -r /home/filebrowser` , then detaching. This works, but obviously I'd love for this to simply work automatically when the container boots.

Is this is a bug, or am I simply missing something very obvious?

Thanks so much in advance!

Kind regards

**Comment by baur** [comment]
maybe: 
```
filebrowser config set -p 8082
```

**Comment by dreyerm** [comment]
Hi Baur,

Thanks for the comment. Unfortunately i did already try that, its part of one or the steps in my comment.

Any other ideas on how i can solve this challenge?

Thanks!

Kind regards

**Comment by baur** [comment]
```
rm filebrowser.db
filebrowser config init
filebrowser config set --address server
filebrowser config set --port 8082
```

**Comment by jonalter** [comment]
> ```
> rm filebrowser.db
> filebrowser config init
> filebrowser config set --address server
> filebrowser config set --port 8082
> ```

I was having a similar issue. 
Running `filebrowser config set --auth.method=noauth` was having no affect. The value in the db was not changing and it was still prompting me to login.
The following steps finally make the config change take:
```
rm filebrowser.db
filebrowser config init
filebrowser config set --auth.method=noauth
```
Thank you @baur!

**Comment by niubility000** [comment]
> config set --auth.method=noauth

Maybe you are using the incorrect filebrowser.db. the filebrowser will use the filebrowser.db under the current cmd folder. for example:
C:\Users\www> d:\filebrowser\filebrowser.exe, it will use the C:\Users\www\filebrowser.db(not the filebrowser.db in d:\filebrowser\. )If there is no filebrowser.db in C:\Users\www, it will initial a new filebrowser.db in C:\Users\www and use it without warning.

Actually, you can tell it directly from:
PS C:\Users\www> d:\filebrowser\filebrowser.exe
2024/02/21 10:03:08 No config file used
2024/02/21 10:03:08 Listening on 127.0.0.1:8080
the port is 8080.
