### ISSUE TITLE
How should I mount network disk?

### ISSUE THREAD

**Issue by llovvoll** [filebrowser/filebrowser#298]
Hi All, 

I would like to ask, is there any way to mount network disk? In the window system to do, I tried for a long time:( 

Very thanks all

**Comment by hacdias** [comment]
Hey @llovvoll!

I'm not sure if it works. But try to set the scope to the path as you'd normally do in File Explorer.

**Comment by llovvoll** [comment]
Hi hacdias,

Very thanks your respond, it's work, Does not meet the practical application method :(

**Comment by hacdias** [comment]
Sorry, I can't understand you said 😞
