### ISSUE TITLE
Video Thumbnails Support

### ISSUE THREAD

**Issue by aeltawela** [filebrowser/filebrowser#2996]
Currently, file browser doesn't support generating thumbnails for videos. There are some golang packages that look promising for thumbnails, as example https://pkg.go.dev/github.com/bakape/thumbnailer#section-readme

**Comment by niubility000** [comment]
Its' simple. I did it before. But I forget how to do it now.
![screenshot](https://github.com/filebrowser/filebrowser/assets/76441520/e4ba219f-d3d8-4ce9-951b-79ef5a42b3a5)

**Comment by aeltawela** [comment]
@niubility000 any chance to find how?

**Comment by niubility000** [comment]
> https://pkg.go.dev/github.com/bakape/thumbnailer#section-readme

https://pkg.go.dev/github.com/bakape/thumbnailer#section-readme, Does this one still need to install ffmpeg seperately in your platform?

**Comment by luftaquila** [comment]
I’m not very familiar with the golang ecosystem, and I’m wondering how I can achieve this with a filebrowser docker instance.
