### ISSUE TITLE
caddy API changed

### ISSUE THREAD

**Issue by LrsK** [filebrowser/filebrowser#30]
caddy has changed a little and so caddy-hugo won't build properly.

in hugo.go change:
"github.com/mholt/caddy/config/setup"
to:
"github.com/mholt/caddy/caddy/setup"

**Comment by hacdias** [comment]
Is it being used already? cc @mholt

**Comment by mholt** [comment]
In the beta release, yes

**Comment by hacdias** [comment]
@mholt let me know when should the directive be changed! :)

**Comment by mholt** [comment]
You can update your repo at any time. When Caddy 0.8 lands (beta period is over), I'll update the build server and all the dependencies and plugins at that time.

**Comment by hacdias** [comment]
Thanks ;) I'll change it.
