### ISSUE TITLE
Directory "others" execute permissions 

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#300]
Hi,

first of all, great app.

But as always there is a "but". I need to create directories but the group "other" haven't the "execution" permission. Can it be modified in the configuration, or edited in the permission of a directory/file? 

Thanks
Brian

**Comment by hacdias** [comment]
Sorry, I didn't quite understand. Do you want to create directories, but the user which is running filemanager isn't allowed to?

**Comment by ghost** [comment]
The permissions of the newly created directory (test) in filemanager is 754 (drwxr-xr--). As a result, we can not run cd test user other than root in terminal (Permission denied).
We need to have permissions 755 (drwxr-xr-x) after the directory creation.

**Comment by eroak** [comment]
+1 Same problem here

**Comment by hacdias** [comment]
That's strange. I have set it to create directories with 776 ([source](https://github.com/hacdias/filemanager/blob/master/http/resource.go#L185)). Are you sure the user that runs filemanager has the correct permissions?

**Comment by ghost** [comment]
Yes, I'm sure.
I launch it in Docker.

**Comment by eroak** [comment]
Me too. Issue on docker too

**Comment by Equim-chan** [comment]
@hacdias I've done some investigation and realized that it is exactly how mkdir expects to work under *nix systems. A bare mkdir call is limited by umask. With a umask value of 0022, new directories will be created with permissions 0755 at most. New files will have permissions 0644 at most. 

There are several ways to fix it
* Call `syscall.Umask` on init, and change all mkdir's permission into 0777. The downside is that if filebrowser is running as a plugin then it may cause something bad to the host.
* Call `os.Chmod` immediately after calling `os.Mkdir`.

Plus, I think it should be an option for users to choose desired fmask and dmask value.

Ref: https://github.com/golang/go/issues/15210

**Comment by hacdias** [comment]
@Equim-chan thanks for searching about that. What about setting `umask` with 0755?

**Comment by Equim-chan** [comment]
I think the option should leave to the users, while 0755 can be a default value (for dmask). 

I myself have met a scene to customize the permission. Since the user/group running filebrowser is different from my own user/group, I add my personal user to the group, expecting files/directories created by filebrowser to be writable from the group.

Also it's better to separate fmask and dmask. The default fmask value can be 0644.

Plus, `os.Chmod` is better than `syscall.Umask` since the latter one is platform specific and is likely to cause more problems.

**Comment by hacdias** [comment]
My question about `os.Chmod` is that if you don't have access to the file due to the permissions, how can you change them?

**Comment by Equim-chan** [comment]
If I am able to touch a new file, I must at least have -wx permission on the current dir, then I can of course chmod the file. Am I wrong?

**Comment by hacdias** [comment]
Yeah, I think you're right. Go for it then. Create a new branch and open a PR with a fix 😄

**Comment by Equim-chan** [comment]
Hmm, I think the change should be made in github.com/hacdias/fileutils instead.

Also should we really prefer umask over chmod or?

**Comment by Equim-chan** [comment]
Hmm, I think the change should be made in github.com/hacdias/fileutils instead. 🤔

**Comment by hacdias** [comment]
Let's start by trying using chmod to make sure it works. If not, we can then change to umask.

**Comment by Equim-chan** [comment]
Okay I'll try, but just a bit busy at the moment.

**Comment by hanatokitsu** [comment]
It would also be nice to have a way to view and set permissions in the UI.

**Comment by ghost** [comment]
Hi @hacdias, аre there any updates on this issue?
Thank you very much for your work!

**Comment by ww7** [comment]
Same issue on Centos. 
Any workflow for this?

**Comment by adminrezo** [comment]
Same issue on Debian.

**Comment by nicedreams** [comment]
I'm on Debian and when I create files (ie: *.txt) the permissions are set to 755.  I have "other" group and rest of files set to 0700 since running filebrowser as user filebrowser, but files and folders still 755 when created through interface.  Would like files 644 or 640 for that matter instead.
