### ISSUE TITLE
Access rules allow browsing, but prevent sharing

### ISSUE THREAD

**Issue by dkaparis** [filebrowser/filebrowser#3003]
**Description**

For a non-admin user, I set a pair of rules like that:

[x] `Regex` [ ] `Allow` `/.+`

[ ] `Regex` [x] `Allow` `/some_folder`

This allows the user to browse under `some_folder`, but not other folders within the scope.
When sharing a folder under `some_folder` though, the shared link only opens an empty folder
with no files.

**Expected behaviour**

Files in shared folder should appear when opening the shared link.

**What is happening instead?**

When opening the shared link, an empty folder with no files appears.

**Additional context**

Running filebrowser release 2.27.0 under FreeBSD 13.2-RELEASE.

**Comment by dkaparis** [comment]
One more detail - when sharing single files under the above configuration, they are shared correctly. The issue only affects sharing directories.

**Comment by dkaparis** [comment]
The issue persists through release 2.28.0.

**Comment by steven-sun** [comment]
not fixed through 2.29.0
files ok, but dir content was blocked on share
