### ISSUE TITLE
希望增加安卓app版本的filebrowser

### ISSUE THREAD

**Issue by mufengyouyang** [filebrowser/filebrowser#3005]
**Is your feature request related to a problem? Please describe.**

就是那种打开就可以使用的app，这样可以更方便的远程管理手机软件，甚至可以安装在电视上，远程管理电视软件
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by niubility000** [comment]
You wanna compile this source code to a apk for android phone? It looks impossible. 
It's so weird golang and android are both from google, but they can't transform to each other.
