### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by evrial** [filebrowser/filebrowser#3006]
I hate being that offensive and rude guy, but looks like you don't even use your own software.

Look at that https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue+403

Do you know that basic file operations do not work if file/directory owner isn't exactly `filebrowser` even if he's member of correct unix group?

**Comment by tomshomelab** [comment]
so you can bypass the 403 error on file by naming the user "filebrowser" is this correct?
