### ISSUE TITLE
Project still alive

### ISSUE THREAD

**Issue by alanmilinovic** [filebrowser/filebrowser#3007]
Is this project still alive? I can see allot of unanswered issues closed by force by Mr stale robot. There are people contributing as well with PR's that are ignored.

How can we bring this project back on track? The only person with write permissions obviously has not that much time and I believe there are people here who are very active and can speed up and bring this project back on track.

**Comment by niubility000** [comment]
Sure. it's still alive.  It takes time to be updated.  Just be patient! 
Filebrowser is an old project and still updated more frequently compared with other projects.

**Comment by alanmilinovic** [comment]
But some issues are never answered.

**Comment by sevmonster** [comment]
Filebrowser doesn't [work for my purposes](https://github.com/filebrowser/filebrowser/issues/2995), and there hasn't been any traction on the issue, so I've since switched to [Filestash](https://filestash.app). I was able to get proxy auth working there using Nginx, but it was a bit wonky, so I can tell you if you're interested.

**Comment by alanmilinovic** [comment]
I agree traction on issues and PR's is very low and super slow.

**Comment by niubility000** [comment]
> I agree traction on issues and PR's is very low and super slow.

We may suggest o1egl to invite an experienced coder to be the project manager with write permissions for one or two years.  He can visit here every 2 or 3 days. It's a heavy work though.  
I think adrium, ramiresviana, kloon15 are good enough for this.

**Comment by onedr0p** [comment]
oh the irony

_not stale_

**Comment by onedr0p** [comment]
Confirmed?

**Comment by onedr0p** [comment]
This project may not be alive but this issue sure is!

**Comment by sevmonster** [comment]
The best part about stale bots is your project looks healthy cuz you have a lot of closed issues and issue comments :)

**Comment by maturbet** [comment]
What a shame!

**Comment by o1egl** [comment]
@alanmilinovic, you can help the community by taking the initiative and responding to issues.

**Comment by alanmilinovic** [comment]
> @alanmilinovic, you can help the community by taking the initiative and responding to issues.

There are people contributing with PR's but you are the only one who can approve it. Sorry, but very annoying.
