### ISSUE TITLE
Unable to access Filebrowser on the public internet

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#3008]
**Description**

**Expected behaviour**
Im running a google cloud linux server, I am trying to run filebrowser using the native linux binary, and access the filebrowser webapp from the servers static public ip

**What is happening instead?**
I get this error: https://pixeldrain.com/u/FC1Mhsps

**Additional context**
In the google cloud console, I have allowed egress and ingress traffic on port 8081 (the port the webapp is running on), tcp and udp, I have disabled ufw (linux firewall), however I still cannot access it from its public ip (e.g: x.x.x.x:8081)
However, when I access localhost:8081 on the server with, I can access the webapp, meaning the webapp is running normally
I have another webapp running on port 8080, which I can access from the public internet perfectly fine

**How to reproduce?**
 Run the native file-browser binary on a server with a public static IP, try to access filebrowser with that public ip

**Comment by niubility000** [comment]
try this: 
.\filebrowser -d filebrowser.db config set --address 0.0.0.0

--address 0.0.0.0 will make you to access to filebrowser from public internet or something like 192.168.1.101. The default value is 127.0.0.1. In some case you can's access to filebrowser from Public internet with this default value.

**Comment by ghost** [comment]
> try this: .\filebrowser -d filebrowser.db config set --address 0.0.0.0
> 
> --address 0.0.0.0 will make you to access to filebrowser from public internet or something like 192.168.1.101. The default value is 127.0.0.1. In some case you can's access to filebrowser from Public internet with this default value.

Thank you very much, this works.

**Comment by ai-mic-stack** [comment]
i am using file broswer it is opening in public ip from outside network but not bale to login giving inacivity error
