### ISSUE TITLE
Broken directory hierarchy downloading folder in any compression format 

### ISSUE THREAD

**Issue by xiey0** [filebrowser/filebrowser#3009]
**Description**
After downloading any folder from the website, the hierarchy of directories inside the folder broke. All the hierarchy are "flattened" into the same level. Details in picture. 

Should be: 
![Screenshot 2024-02-20 at 00 44 39](https://github.com/filebrowser/filebrowser/assets/141170394/bb5d6332-03b8-4d52-9b7c-6c7b9601b87f)
![Screenshot 2024-02-20 at 00 45 07](https://github.com/filebrowser/filebrowser/assets/141170394/f0a5a7ab-e203-41b4-b938-6be3833c72de)

But instead: 
![Screenshot 2024-02-20 at 00 45 00](https://github.com/filebrowser/filebrowser/assets/141170394/ffe93afe-7e4a-4b2e-9f91-dc182e3ed6cb)

**How to reproduce?**
Anytime performing a download of a folder

**Comment by niubility000** [comment]
I just can't reproduce it. Mine is correct. 
It's from a phone? or you change the background?
How do you unzip the file? in windows?

**Comment by xiey0** [comment]
> I just can't reproduce it. Mine is correct. 
> It's from a phone? or you change the background?
> How do you unzip the file? in windows? 

Both mac and windows show a broken hierarchy after extraction, using any software from the system built-in tool to something like 7-zip. In the picture its mac and extracted through system built-in tool. 

By the way, the computer hosting the software is running Windows Server 2022 in Administrative privilege if that's any helpful. No additional programs were installed. 

Also I'm Chinese so the interface would be in Chinese. And the system Unicode stuff was setted Chinese if that's any helpful.

**Comment by xiey0** [comment]
> I just can't reproduce it. Mine is correct. It's from a phone? or you change the background? How do you unzip the file? in windows?

The server hosting the software does not include an SSL certificate and the connection is through http. after some testing I found out that the problem may vary between browsers and "positions" by very random pattern. 

if i was downloading to .zip inside LAN where the host was in, the hierarchy wont broke. If by .tar the hierarchy will broke.

**Comment by niubility000** [comment]
> > I just can't reproduce it. Mine is correct. It's from a phone? or you change the background? How do you unzip the file? in windows?
> 
> The server hosting the software does not include an SSL certificate and the connection is through http. after some testing I found out that the problem may vary between browsers and "positions" by very random pattern.
> 
> if i was downloading to .zip inside LAN where the host was in, the hierarchy wont broke. If by .tar the hierarchy will broke.

我的是从内外网都没问题，就是下载大量文件,比如cache 文件夹，有时zip会broke，需要重新下载。

**Comment by niubility000** [comment]
Maybe this is the reason? #2983

**Comment by xiey0** [comment]
> Maybe this is the reason? #2983

I tried to do it but still. 
And also after experiement i found that even it's inside the LAN the zip would broke too.

**Comment by niubility000** [comment]
> > Maybe this is the reason? #2983
> 
> I tried to do it but still. And also after experiement i found that even it's inside the LAN the zip would broke too.

Try it in the demo website: https://demo.filebrowser.org/    demo:demo,
Just create a new folder "try1", and upload a pic, and create another folder try2 in try1, and upload a pic, and then create another folder try3 in try2, upload a pic. Then download try1 (zip), and unzip it. It works normally.

**Comment by xiey0** [comment]
> > > Maybe this is the reason? #2983
> > 
> > 
> > I tried to do it but still. And also after experiement i found that even it's inside the LAN the zip would broke too.
> 
> Try it in the demo website: https://demo.filebrowser.org/ demo:demo, Just create a new folder "try1", and upload a pic, and create another folder try2 in try1, and upload a pic, and then create another folder try3 in try2, upload a pic. Then download try1 (zip), and unzip it. It works normally.

yes it did work normally. How could it not work normally on mine though? 
Should it be an OS problem?

**Comment by xiey0** [comment]
> > > Maybe this is the reason? #2983
> > 
> > 
> > I tried to do it but still. And also after experiement i found that even it's inside the LAN the zip would broke too.
> 
> Try it in the demo website: https://demo.filebrowser.org/ demo:demo, Just create a new folder "try1", and upload a pic, and create another folder try2 in try1, and upload a pic, and then create another folder try3 in try2, upload a pic. Then download try1 (zip), and unzip it. It works normally.

After run filebrowser on WSL2 it runs perfectly. Still need some observation though.

**Comment by Illusionna** [comment]
> **描述** 从网站下载任何文件夹后，文件夹内的目录层次结构中断。所有层次结构都“扁平化”到同一级别。图片中的细节。
> 
> 应为： ![Screenshot 2024-02-20 at 00 44 39](https://github.com/filebrowser/filebrowser/assets/141170394/bb5d6332-03b8-4d52-9b7c-6c7b9601b87f) ![Screenshot 2024-02-20 at 00 45 07](https://github.com/filebrowser/filebrowser/assets/141170394/f0a5a7ab-e203-41b4-b938-6be3833c72de)
> 
> 但相反： ![Screenshot 2024-02-20 at 00 45 00](https://github.com/filebrowser/filebrowser/assets/141170394/ffe93afe-7e4a-4b2e-9f91-dc182e3ed6cb)
> 
> **如何复制？**任何时候执行文件夹下载

我做的项目归档压缩完美解决你文件树结构问题：https://github.com/Illusionna/LocalTransfer
