### ISSUE TITLE
Consider switching from Ace code editor to Monaco

### ISSUE THREAD

**Issue by Shayan-To** [filebrowser/filebrowser#3011]
**Is your feature request related to a problem? Please describe.**
[Monaco editor](https://github.com/microsoft/monaco-editor) is the text editor behind VSCode. A whole lot more people are familiar with it. And it provides better code editing experience.

**Describe the solution you'd like**
Replace Ace code editor with [Monaco editor](https://github.com/microsoft/monaco-editor).

**Describe alternatives you've considered**
\-\-

**Additional context**
\-\-

**Comment by niubility000** [comment]
support! Ace code editor looks too simple.
