### ISSUE TITLE
[Docker]: timeout on commands that connect to a locked database

### ISSUE THREAD

**Issue by vchernov-avenga** [filebrowser/filebrowser#3013]
**Description**
It's not possible to change `admin` user password when run `filebrowser` in the Docker container.
Exactly the same issue that was closed and never fixed https://github.com/filebrowser/filebrowser/issues/627 
**Expected behaviour**
The password is updated

**What is happening instead?**
```bash
docker run --rm -it filebrowser/filebrowser users update admin --password 123
2024/02/21 10:13:25 /database.db does not exist. Please run 'filebrowser config init' first.
```
or
```bash
docker exec -it filebrowser/filebrowser /bin/sh                        
/ # ./filebrowser version
File Browser v2.27.0/04e03a83
/ #  ./filebrowser users update admin --password 123
2024/02/21 10:36:00 timeout
```
**How to reproduce?**
```bash
docker run --rm -it filebrowser/filebrowser users update admin --password 123
```

**Comment by shadowbq** [comment]
Even doing a full mapping on the latest:s6 I get 'timeout'... Still getting timeout
```
s6-setuidgid abc filebrowser -c /config/settings.json -d /database/filebrowser.db users ls
```

**Comment by tigattack** [comment]
Not stale, still a problem.

**Comment by tigattack** [comment]
Not stale, still a problem.

**Comment by hugo-akaora** [comment]
Hello, same problem:
```
root@iglou:~/iglou# docker compose -f conf/compose-filebrowser.yaml exec filebrowser /filebrowser config set
2024/05/14 14:06:43 Using database: /database/filebrowser.db
2024/05/14 14:06:44 timeout
```

**Comment by DavisGoglin** [comment]
As a hacky workaround you can run this inside your running instance to stop the previous instance and run the set command at the same time, then s6 will restart it. 

`killall filebrowser && filebrowser -c /config/settings.json -d /database/filebrowser.db config set --auth.method=proxy --auth.header=X-My-Header`

**Comment by tigattack** [comment]
Not stale, still a problem.

**Comment by cscashby** [comment]
+1 seeing the same issue. Difficult to kill process with a managed k8s deployment, etc.

**Comment by killparty** [comment]
+1 Same issue

**Comment by ahmadalkhansa** [comment]
Same issue with me.

**Comment by jamesmoore** [comment]
One way is to temporarily add a command subsection into your docker-compose, start the container once and then remove them for subsequent runs:

```yaml
services:
  filebrowser:
    image: filebrowser/filebrowser
    # command:
    #   - config
    #   - set
    #   - --auth.method=proxy
    #   - --auth.header=Remote-User
    restart: unless-stopped
```

**Comment by tigattack** [comment]
Not stale, still a problem.

**Comment by pwaldon** [comment]
_This went very well... still happens._

**Comment by AmurgCodru** [comment]
Any news on this as i'd like to be able to add users and configure filebrowser via the CLI WHILE it is still running without having to restart it (or do any hacky stuff) - I mean if it were a simple sqlite db with wall it should have worked

**Comment by laker-93** [comment]
+1 on this

**Comment by AmurgCodru** [comment]
This is still much needed, but a temporary solution would be to add an admin user and use the API from a trusted APP...
For the API I can't really find a documentation on, so I just debug the network tab in the browser.

**Comment by laker-93** [comment]
@LordPraslea - have you managed to use the API to add users to filebrowser whilst it's running? I'm using the cli for this but it's not reliable due to this issue. I haven't found out how to do it with the API yet so would be interested to know how you've done it. Thanks.

**Comment by AmurgCodru** [comment]
@laker-93 This is how I've managed to add users via API. It;s work in progress and you might need to update it to your programming language, the example is in CURL as it's universally understood:

1. First create an admin user with a strong random password.
2. Login and get cookie of account
3. Configure the account settings, see the long string? you can add many different user settings..
4. Issue command to create new account
```bash 
cookie=`curl -Ss localhost:1777/api/login --data-raw '{"username":"adminUserName","password":"PassWordHere"}'`

curl -H "X-Auth: $cookie"  localhost:1777/api/users --data-raw '{"what":"user","which":[],"data":{"scope":"","locale":"en","viewMode":"list","singleClick":false,"sorting":{"by":"name","asc":false},"perm":{"admin":false,"execute":false,"create":true,"rename":true,"modify":true,"delete":true,"share":true,"download":true},"commands":[],"hideDotfiles":false,"dateFormat":false,"username":"USERNAME HERE","password":"PASSWORD HERE---~~~~~","rules":[{"allow":false,"path":".exe","regex":false,"regexp":{"raw":""}},{"allow":true,"path":"","regex":false,"regexp":{"raw":""}}],"lockPassword":false,"id":0}}'
```
Hope this helps. You can debug other commands via the network inspector in your filebrowser as you DO the actions. 

Good luck!
