### ISSUE TITLE
Can I enable view of picture in shared directories?

### ISSUE THREAD

**Issue by ptah-alexs** [filebrowser/filebrowser#3014]
When I dbl-click on picture in directory, it's open preview with navigation elements. Can I enable this behavior for shared directories? Version 2.27.0

**Comment by niubility000** [comment]
This is asked again and again. We may pull a request. 
try this (windows version): 
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/14367835/filebrowser.zip)
the souce cod file I changed: 
[Share.zip](https://github.com/filebrowser/filebrowser/files/14367844/Share.zip)
I wrote all the modified css in .vue tag to make it simple :)
I just add a preview window in the left bottom corner. You can see the pic, play the audio and video here, and click it to full screen. In mobile, this will fix in the top.
![2024-02-22 105002](https://github.com/filebrowser/filebrowser/assets/76441520/6bb0332e-a261-41c7-9dde-e6bd6c90abe2)

**Comment by ptah-alexs** [comment]
Thank you
