### ISSUE TITLE
Error 403 adding / editing or viewing files added to the /data folder

### ISSUE THREAD

**Issue by tomshomelab** [filebrowser/filebrowser#3020]
**Description**
As an administrator user im unable to see any folder structure within the "my files" section of the gui. i cannot create folders or files here due to an error 403. 

**Expected behaviour**
I expect to be able to see /data folder and all the subdirectories i have mounteded there and then be able to create more folders and files

**What is happening instead?**
i see "It feels lonely here..." within the my files section and get an error 403 when attempting to create new files or folders. 

**Additional context**
i am an admin user, i have tried with new admin users, new mount locations and the default user

**How to reproduce?**
setup the container as the instructions suggest using docker compose and attempt to edit view any files with the data folder

**Files**
i have nothing to add for this

**Comment by niubility000** [comment]
Does it work if you don't use docker and use the filebrowser windows or linux version directly? 
Why do you use it in docker? Filebrowser don't need any special env and can run directly in windows or linux.
