### ISSUE TITLE
bind to network interface instead of IP address 

### ISSUE THREAD

**Issue by TehDomic** [filebrowser/filebrowser#3021]
**Is your feature request related to a problem? Please describe.**

Ability to choose which NIC(s) to expose the server to, such as on Termux, Android where wlan0 constantly changes IP address, and you don't want to expose it to mobile network (ISP). 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by o1egl** [comment]
You can set the address as 0.0.0.0 to listen on all interfaces

**Comment by TehDomic** [comment]
That's the emergency solution I have done, but it exposes your files to ALL interfaces. That's especially bad for Android devices, where mobile internet sometimes might expose your ports to the internet or other users on the same ISP network.
