### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by kisharra** [filebrowser/filebrowser#3022]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by kisharra** [comment]
the error appears when I try to access a file storage under a domain name, if I access it by IP address then everything is fine, here is the NGINX configuration
`server {
     listen [::]:80;
     listen 80;
     server_name metal-country.ru;
     client_max_body_size 48M;
     location / {
         proxy_pass http://localhost:8080;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
    }
}
`

**Comment by RealFascinated** [comment]
> client_max_body_size 48M;

increase this
