### ISSUE TITLE
Large download kills Caddy

### ISSUE THREAD

**Issue by lstrz** [filebrowser/filebrowser#303]
### 1. Have you downloaded File Manager from caddyserver.com? When have you done that?
Yes. November 26 2017.

### 2. What is your entire Caddyfile?
```text
https://my.domain.com
errors /my/home/caddy.err {
        rotate_size 10
        rotate_age 365
        rotate_compress
}
gzip
header / {
        Strict-Transport-Security "max-age=31536000;"
        X-XSS-Protection "1; mode=block"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
}
log /my/home/caddy.out {
        rotate_size 10
        rotate_age 365
        rotate_compress
}
root /my/home/public
timeouts {
        read 180s
}
git https://github.com/a_repo.git /my/home/some_dir {
        then hugo --config /my/home/some_dir/config.toml
}
filemanager /path /my/scope {
        database 16b77317de4813d8e2fcdfefa1e92903.db
}
forwardproxy {
        basicauth username pass
        probe_resistance
        hide_ip
}
minify
```

### 3. What are you trying to do?
Download a 1.66 GB file which was uploaded successfully.

### 4. What did you expect to see?
Once the file is selected and the download button is pressed, I'd expected to see a "Save file" kind of a pop-up.

### 5. What did you see instead (give full error messages and/or log)?
After selecting the file and pressing the download button, another page started loading and after a few seconds it stopped loading. Caddy was no longer running on the VPS it was running on previously and had to be restarted. Nothing was logged. The VPS has 512 MB RAM only, so the file doesn't fit in it -- maybe that caused the problem?

To me, it doesn't seem like a timeout issue, as I wouldn't expect Caddy to crash after timing out.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
1. Upload a big file (potentially bigger than RAM available).
2. Try downloading the big file.

**Comment by hacdias** [comment]
Probably the problem is exactly what you're saying (the RAM). I'll try to find a way to download it in chunks. THanks for reporting 😄

**Comment by hacdias** [comment]
Hopefully this was fixed in #303. We're now streaming the file using `io.Copy` instead of using `http.ServeFile` which was, I think, putting it all in memory and then serving it to the user. I'm publishing the new version (1.3.12) and I ask you to test it and reopen this issue if the error persists (I hope it doesn't 😮)

**Comment by hacdias** [comment]
I'm being able to deploy the new version to Caddyserver. You can always download it through [releases](https://github.com/hacdias/filemanager/releases) and proxy it through Caddy. As soon as it is deployed into `caddyserver.com` I'll ping you. /cc @mholt

**Comment by hacdias** [comment]
Deployed! You can now download it with the fix 😄

**Comment by lstrz** [comment]
Thanks for the quick action!

I downloaded and (re)installed Caddy with `curl https://getcaddy.com | bash -s personal http.cache,http.filemanager,http.forwardproxy,http.git,http.minify`.

Is that correct? Can I validate running the correct version of Filemanager?

The problem persists and indeed, `htop` shows memory usage climbing to 800+ MB and staying there for a while (swapping) before Caddy is killed.

[The source code](https://golang.org/src/io/io.go?s=13259:13340#L378) of `io.Copy` (`io.copyBuffer`) first tries using `WriteTo` or `ReadFrom`, before falling back to a 32K buffer. Could it be that `WriteTo` or `ReadFrom` are unbuffered?

Take my Go knowledge with a big grain of salt.

**Comment by hacdias** [comment]
I just downloaded a 2GB file from a VM with 1GB RAM without any issue. Are you using any other plugin (like Minify) *with* File Manager?

If you're using Minify on the same URL as File Manager, try disabling it.

**Comment by lstrz** [comment]
Disabling Minify helped!

Had no idea it tried to minify downloads as well.

Thank you very much!

**Comment by hacdias** [comment]
I'll open an issue on caddy-minify (which was also created by me. That's why I knew it may be causing this problem...). Sorry!
