### ISSUE TITLE
Renaming a share gives odd behaviour

### ISSUE THREAD

**Issue by RealFascinated** [filebrowser/filebrowser#3032]
**Description**

When renaming a folder/file any shares that are pointed to it still go to the old folder/file name

**Expected behaviour**

the share to update where it points to

**What is happening instead?**

n/a

**Additional context**

n/a

**How to reproduce?**

n/a

**Files**

n/a

**Comment by niubility000** [comment]
I tried it in demo.filebrowser.org with demo:demo. After rename the shared folder, it just showed "This location can't be reached".
In old version like 2.20.1, the old share link doesn't work anymore, and there is a new share link for the renamed folder.
