### ISSUE TITLE
can not set the user root path with chinese characters 

### ISSUE THREAD

**Issue by maryjeck** [filebrowser/filebrowser#304]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Manager? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

**Comment by hacdias** [comment]
@maryjeck unfortunately I'm aware of this and I couldn't yet figure out why is this happening. 

I'll close this since it's a duplicated of #269
