### ISSUE TITLE
Image & Video FIle Thumbnails not visible

### ISSUE THREAD

**Issue by itsgauravjain22** [filebrowser/filebrowser#3041]
**Description**
Image & Video FIle Thumbnails not visible

**Expected behaviour**
Image & Video FIle Thumbnails not visible

**Additional context**
The file browser without thumbnails is not usable. Kindly check the attached screenshot.

![screenshot-dietpi local_8080-2024 03 10-13_45_51](https://github.com/filebrowser/filebrowser/assets/11793930/e5055914-8e41-41b2-b4f7-be10927b3d9b)

**Comment by niubility000** [comment]
Why? Upload it to demo.filebrowser.org with demo:demo and try it. 
For the video thumbnails, golang don't have a video library itself. So it's impossible to get the thumbnails without installing a separate ffmpeg in your platform.
