### ISSUE TITLE
Move files, move folders after copying

### ISSUE THREAD

**Issue by ytoaa** [filebrowser/filebrowser#3042]
When you move and copy the current file, the current folder is moved to the folder where you copied it, rather than remaining. I'd like you to give me the on/off option for that feature.

**Comment by gletiecq** [comment]
There is a copy feature and a move feature in filebrower.  By using the copy feature (using the icon at the top) you would get the functionality you want.  If you want to move files or a directory instead, you drag them to the new location.

**Comment by ytoaa** [comment]
> 파일 브라우저에는 복사 기능과 이동 기능이 있습니다. 복사 기능(상단 아이콘 사용)을 사용하면 원하는 기능을 얻을 수 있습니다. 대신 파일이나 디렉터리를 이동하려면 해당 항목을 새 위치로 드래그하세요.

I already know that there is a move and copy function. I mean the function of the web browser moving to the destination folder after move and copy.

**Comment by ytoaa** [comment]
> There is a copy feature and a move feature in filebrower. By using the copy feature (using the icon at the top) you would get the functionality you want. If you want to move files or a directory instead, you drag them to the new location.

I already know that there is a move and copy function. I mean the function of the web browser moving to the destination folder after move and copy.
Of course, I know that drag is possible without moving to the destination folder. However, I understand that this is only possible when dragging to the subfolders of the current folder. I don't know what to do with the top folder.

**Comment by ytoaa** [comment]
.
