### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by need4swede** [filebrowser/filebrowser#3043]
> **Is your feature request related to a problem? Please describe.**

Filebrowser requires `'unsafe-inline'` and `'unsafe-eval'` to be enabled, resulting in poor security when accessed behind a reverse proxy.

> **Describe the solution you'd like**

Adhere to contemporary CSP rules, like storing all js/css into their own respective files, etc.

> **Describe alternatives you've considered**

Not hosting Filebrowser, which would be a shame as I really like it.
Currently exploring options to see how this can be resolved.

> **Additional context**

I am not the first to bring this up. [This was already mentioned](https://github.com/filebrowser/filebrowser/issues/1207) **4 years ago**, but still has not been resolved.

**Comment by gletiecq** [comment]
I'm running filebrowser behind nginx using a reverse proxy with pretty much vanilla settings and am not having any problems with file uploads or downloads.  Is this an issue where filebrowser is failing, or that it's working but you believe something about how it is working is a problem?

**Comment by need4swede** [comment]
@gletiecq Perhaps you've misunderstood my post.

This is not a critique of Filebrowser's functionality. It works as intend.
I'm pointing out that it suffers from certain security vulnerabilities by allowing `unsafe-inline` and `unsafe-eval` scripting.
