### ISSUE TITLE
Something really went wrong

### ISSUE THREAD

**Issue by Alsan** [filebrowser/filebrowser#305]
I just download the binary package from the site and ran with a new created account, which has administrator permission, and results with the error.

![image](https://user-images.githubusercontent.com/217947/34383128-22049e90-eb4e-11e7-987f-9a323211eb07.png)

![image](https://user-images.githubusercontent.com/217947/34383169-618d71d6-eb4e-11e7-98f2-fd657ebf5fdc.png)

Testing procedure:
1. login with admin
2. create a new account with administrator permission, and assign a accessable path as scope
3. login with the new account, give me the error
4. logout and login back with admin account, give me the error
5. delete the filemanager.db, and login with admin account, the error gone
6. remove the filemanager.db, create a filemanager.yaml with specified port and baseURL, login with admin, give me the error

My system info: Linuxmint 18.3/Centos 7

**Comment by hacdias** [comment]
I'm not able to reproduce this.

Are you sure you put the right scope? Try using an absolute path.

**Comment by Alsan** [comment]
The scope is absolute path already.

**Comment by Adagior** [comment]
i have same problem
i can creat files  but it cant show anything       and it always said  Something really went wrong

**Comment by hacdias** [comment]
@Adagior @Alsan I can't reproduce this as I've said before. But I'll leave some question that might help me:

1. Are you running this directly in your machine? If not, are you running this inside some kind of container?
2. What's your configuration/the command you used to run?
3. Did you check opening Settings -> Users and check the Scope?


@Alsan: what is the `.virtualenvs`?

**Comment by Adagior** [comment]
```
{
  "port": 8000,
  "noAuth": false,
  "baseURL": "",
  "reCaptchaKey": "",
  "reCaptchaSecret": "",
  "log": "stdout",
  "plugin": "",
  "database":"/etc/filemanager/filemanager.db", 
  "scope":"/srv",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": [ ]
}
```

i cant download the get.sh from your blog now 0.0..............dont del it plz

**Comment by Alsan** [comment]
@hacdias 
1. Not running under any container, just run it directly;
2. I'm using a filemanager.yaml as my configuration file, and only have port, baseURL set inside, and I use ./filemanager in terminal to startup the app;
3. Yes, I've check thoses settings, and there's no problem when first run with admin user, it's comming up after create and login with a new user (which has scope specified).

I don't known about the error of virutalenv, I just saw it in terminal, it's about the python virtual environment I'm assume.

**Comment by Adagior** [comment]
and can i run 2 filemanager in same server?

one is 1.31   and  another is 1.44

**Comment by Alsan** [comment]
@Adagior I belive it's fine if they use different port.

**Comment by hacdias** [comment]
@Alsan did you check if the process that runs `filemanager` has write/read permissions over the scope? 

@Adagior  Does the user has really that *scope* defined on its settings? When you set `scope` in the configuration, you are only setting the default scope for **new** users. After a user is created, you'll need to log in and change it on settings.
 
The links [were changed](https://hacdias.github.io/filemanager/installation/#one-step-script).

**Comment by Adagior** [comment]
@hacdias        
  
first time i install it works fine when i change the user password or scope  it goes like that
  
and when it appear...i still can use the search to reach other files

and 0.0 how can i go uplevel  of the folder

**Comment by Adagior** [comment]
i think it need put in /usr/bin/

**Comment by hacdias** [comment]
@Adagior could you check if you have any errors on the Developers Console (F12 -> Console)?

**Comment by Adagior** [comment]
@hacdias
same with him.......
![image](https://github.com/Adagior/filemanager/raw/master/MobaXterm_Personal_10.4_2018-01-09_18-28-52.png)![image](https://github.com/Adagior/filemanager/raw/master/chrome_2018-01-09_18-29-26.png)
https://github.com/Adagior/filemanager/raw/master/chrome_2018-01-09_18-46-44.png

**Comment by Adagior** [comment]
with caddy in /usr/bin/   
 and  no_auth        but still cant open /var
and some folders can be opened and some cant   i'm sure its 777 or 755
https://github.com/Adagior/filemanager/raw/master/chrome_2018-01-09_18-52-08.png

**Comment by hacdias** [comment]
When the error occurs, could you take a screenshot of Settings -> User Management -> Click edit on your user.?

**Comment by Adagior** [comment]
@hacdias   at the my file site 0.0.............. is same as another user
https://github.com/Adagior/filemanager/raw/master/2018-01-09_20-37-29.png

**Comment by hacdias** [comment]
Do the user running `filemanager` has access to `/root`? THe strange thing about this is the error being Gone.

**Comment by Adagior** [comment]
@hacdias  .....the the /usr/bin  access to /  working fine 0.0............
and when this happened    i change scope to other folders it still show       some thing really went wrong

  and this  i can access to root
https://github.com/Adagior/filemanager/raw/master/chrome_2018-01-09_20-50-46.png

**Comment by hacdias** [comment]
Can you navigate to 

![image](https://user-images.githubusercontent.com/5447088/34721818-3323d6a8-f53c-11e7-9e62-bb877f815902.png)

And see what it says?

**Comment by Adagior** [comment]
@hacdias 
https://github.com/Adagior/filemanager/raw/master/2018-01-09_20-56-53.png

**Comment by hacdias** [comment]
Not that, open the URL directly please

**Comment by Adagior** [comment]
@hacdias 
![image](https://user-images.githubusercontent.com/10530567/34722099-683d6306-f580-11e7-8e45-f7413af5e5c1.png)
)

**Comment by Adagior** [comment]
Provisional headers are shown
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiIiwiYWRtaW4iOnRydWUsImZpbGVzeXN0ZW0iOiIvc3J2IiwicnVsZXMiOltdLCJjc3MiOiIiLCJsb2NhbGUiOiJlbiIsImxvY2tQYXNzd29yZCI6ZmFsc2UsImFsbG93TmV3Ijp0cnVlLCJhbGxvd0VkaXQiOnRydWUsImFsbG93Q29tbWFuZHMiOnRydWUsImFsbG93UHVibGlzaCI6dHJ1ZSwiY29tbWFuZHMiOlsiZ2l0Iiwic3ZuIl0sInZpZXdNb2RlIjoibW9zYWljIiwiZXhwIjoxNTE1NTg4NTg3LCJpc3MiOiJGaWxlIE1hbmFnZXIifQ.HJKNZRyOO3eksRJLV4BAyApTAv21DAB2qwn3zEEDva8
Referer:http://207.246.127.187:8000/admin/files/
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by hacdias** [comment]
It says it is from 'Disk cache'. Could you try to clean the cache?

**Comment by Adagior** [comment]
@hacdias

  where is the cache 0.0

not work with 
```
echo 3 > /proc/sys/vm/drop_caches
yum clean all
```
  
  first  time i open filemanager  it works well ...when change the scope  it goes like that

**Comment by hacdias** [comment]
Probably some error while saving to the database but I can't reproduce this error. Since I can't reproduce it, I won't be able to fix it 😞

**Comment by Adagior** [comment]
0.0

**Comment by hacdias** [comment]
Have you tried on another machine/OS? Is it happening with the standalone or with Caddy?

**Comment by Adagior** [comment]
yes    always  works on the first time enter ,the second time it goes like that
i use the vultr  vps 0.0

**Comment by hacdias** [comment]
So, not working on Vultr. On your local machine the same happens?

**Comment by Adagior** [comment]
not try yet.                 O.O

**Comment by Adagior** [comment]
I will try on bandwagon.   And Aliyun tomorrow~

**Comment by Adagior** [comment]
@hacdias same problem........i can open the /root at the first time,    when i change the scope,,,,,,,403 forbidden
and not work with reboot

is there some other file created by filemanager?  or  caddy cache
filemanager
filemanager.json
databass.db

i delete the databass.db  it still like that
 
and caddy with browser can read whole server     
can caddy browser  edit on files
  

i think caddy leave some file cache in somewhere

or...410 gone mean something wrong to connect with caddy?

**Comment by hacdias** [comment]
The error seems to be triggered [here](https://github.com/hacdias/filemanager/blob/master/http/resource.go#L113), which then directs me to [this functions](https://github.com/hacdias/filemanager/blob/master/file.go#L103). The error 410 is, in really, a Not Found error but for a file we knew that existed but doesn't exist anymore. I have never had that error.

**Comment by Alsan** [comment]
I'm happily to say that my problem is gone with the new version 1.4.4, which is just downloaded. I didn't noticed that there's a new version over there, and the problem I reported should be pinpoint to the version 1.4.3.

**Comment by hacdias** [comment]
I'll close this then. But that's **really** weird cause version 1.4.4 only has a typo fixed. Maybe some build bug?

**Comment by fivestones** [comment]
I have a similar error (I think because I had a non-existant path in my config file the first time I spun up docker), which always stuck around even when the config was working. It was always saying "Something really went wrong". It was fixed by deleting all the cookies and browser cache for filebrowser.
