### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by dansity** [filebrowser/filebrowser#3050]
**Description**
I'm probably overlooking something. I have filebrowser docker container setup that I access with cloudflare tunnel. I have followed the docs and set the captcha in the command line settings.
I created a new site in google dev and got the keys. I have set my keys in the config.
First I thought this is v3 captcha so it can be invisible but then I have checked the source code of the login page and there is nothing loaded from google.
My config:
```
/ # ./filebrowser config cat
Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:              

Branding:
  Name:                                
  Files override:                      
  Disable external links:              false
  Disable used disk percentage graph:  false
  Color:                               
  Theme:                               

Server:
  Log:           stdout
  Port:          8080
  Base URL:      my.domain.com
  Root:          .
  Socket:        
  Address:       127.0.0.1
  TLS Cert:      
  TLS Key:       
  Exec Enabled:  false

Defaults:
  Scope:         .
  Locale:        en
  View mode:     list
  Single Click:  false
  Commands:      
  Sorting:
    By:   name
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": {
    "host": "https://www.google.com",
    "key": "6LeZApopAAAAAKruK2redacted",
    "secret": "6LeZApopAAAAAredacted"
  }
}
```

**Expected behaviour**
captcha to appear at login

**What is happening instead?**
no captcha, login successful anyway

**Additional context**

**How to reproduce?**
Not sure, I have followed the docs to my best understanding.

**Files**

**Comment by Pendrag00n** [comment]
Test if reCAPTCHA v2 works for you

**Comment by dansity** [comment]
Hi, I have tried v2 both visible and invisible but no success unfortunately.

**Comment by sainiaj** [comment]
Hello any luck are you able to get captcha working with file browser 

Thank you
