### ISSUE TITLE
Share forever

### ISSUE THREAD

**Issue by Skyslycer** [filebrowser/filebrowser#3054]
**Is your feature request related to a problem? Please describe.**
I love using filebrowser to share files with my coworkers and friends. And I also love the share feature. Sometimes though, I want to upload a picture and link it in a wiki or markdown file. But, after 255 days I'd need to renew the link which would be a hassle.

**Describe the solution you'd like**
If you could just input -1 days or something and make it stay forever, it would be everything I'd need.

**Describe alternatives you've considered**
Previously I have used just a directory that's forwarded through NGINX so I could access that. Using it is tedious and not nearly as nice as filebrowser though.

**Additional context**
No additional context.

**Comment by niubility000** [comment]
Is it forever?
![f](https://github.com/filebrowser/filebrowser/assets/76441520/d6f0a5ea-6014-46fa-9c84-829e6784301d)

Just leave the Share Duration blank. 

![g](https://github.com/filebrowser/filebrowser/assets/76441520/98410c31-dbc6-4499-8fb8-83ecfda49be5)

**Comment by Skyslycer** [comment]
How did you do that?
EDIT: That works! Thank you. I think there should be a small note to leave it blank though. May PR.
