### ISSUE TITLE
reCAPTCHA v3 not working

### ISSUE THREAD

**Issue by Pendrag00n** [filebrowser/filebrowser#3056]
reCAPTCHA v2 works fine but reCAPTCHA v3 renders:
`ERROR for site owner: Invalid key type`

![image](https://github.com/filebrowser/filebrowser/assets/88731722/4e1ddfd9-5e53-4c59-b731-e5322fb4123b)

I use `filebrowser config set --auth.method=json --recaptcha.key <key> --recaptcha.secret <secret>` since filebrowser doesn't really care about reCAPTCHA changes made in the .toml config file whenever I restart the service

These are the contents of `filebrowser.toml`
```
address  = "192.168.1.2"
port = "443"
root = "/mnt/usb/"
database = "/var/lib/filebrowser/filebrowser.db"
log = "/var/log/filebrowser.log"
key = "/etc/filebrowser/ssl/privkey.pem"
cert = "/etc/filebrowser/ssl/fullchain.pem"
recaptcha.host = "https://www.google.com"
recaptcha.key = "<KEY>"
recaptcha.secret = "<SECRET>"
```

This is the final output of `$ filebrowser config cat`
```
Auther configuration (raw):

{
  "recaptcha": {
    "host": "https://www.google.com",
    "key": "<KEY>",
    "secret": "<SECRET>"
  }
}
```
Am I missing something? Does filebrowser just not support reCAPTCHA v3

**Comment by grobitec** [comment]
Hey, i have the same issue.

<img width="297" alt="recapcha_v3_error" src="https://github.com/filebrowser/filebrowser/assets/140963687/ea9edceb-11de-4a9c-a910-a43bf316d819">
 
Probably reCAPTCHA v3 is actually not supported.

So I'm using reCAPTCHA v2.
