### ISSUE TITLE
Uploading large number of files (possibly over 10000) seems to cause web UI to hang

### ISSUE THREAD

**Issue by StudioNirin** [filebrowser/filebrowser#3060]
**Description**
I created a new filebrowser setup to replace a synology drive setup, and I went to upload all the old files via the webUI (I could have done it straight through the NAS but I wanted to test it out).

I noticed that if I tried to do it all at once, the web page would just freeze (chrome would show the 'this page it not responding, wait or exit' popup). The 'uploading' popup with the transfer progress doesn't show up. 

However the files -do- still upload and transfer, and when I came back a while later to see if it progressed or broke it was actually working again, and the transfer dialogue box had appeared (with about 7000 files remaining) so I suspect that there's some kind of upper limit where the setup hangs or can't handle the numbers. I figure maybe it's 10,000 at a guess, maybe just because of it being 5-digits and something in the filebrowser code is only expecting 9999 as the max (but this is a total guess). 

**Expected behaviour**
Would be nice if it just worked with no upper limit!

**What is happening instead?**
Webpage hanging and not showing the progress report.

**Comment by gletiecq** [comment]
What are you hosting filebrowser on?  Looks like an issue where you've temporarily overwhelmed the hardware.

**Comment by wintermute-cell** [comment]
Similar issue here, hosting on a Raspberry Pi4, but the server hardware does not seem to be struggling. Here is a screenshot of some server metrics during the upload:
![image](https://github.com/filebrowser/filebrowser/assets/64093588/60f0fc50-9a24-43a8-bbd3-4592f8417e8a)
 
Although for me the upload seems to 'crash' at some point: The UI never stops hanging and uploading stops at some point, with only a percentage of the files being uploaded.

Maybe a limit on how many files the frontend hits the server with at any time could resolve this?

**Comment by gletiecq** [comment]
When I ran this on a Pi with 8GB and ran a large file test (using rsync) I saw available memory drop pretty quickly towards zero causing it to start using swap space, at which point the system slowed considerably.  Undoubtedly fb is going to respond at least as poorly when it starts getting stressed that hard.  Given that in the screenshots above there doesn't appear to be any actual memory telementry, it's possible you're looking at the same thing.  Maybe not, but this is my best guess.

Stress testing like this is a good idea, but is it consistent with use case given the hardware?  It'll tell you how it will fail if it does (useful info), but would that condition actually be encountered?  If so, probably more hardware would be a good idea.

Under these circumstances your pass/fail should be is the failure unrecoverable or not?  If recovery is possible, I'd call it a pass.

**Comment by wintermute-cell** [comment]
Ah yes, I should have been more specific about what I was trying to upload; For me this is an actual use case, with a directory of ~300MB of documents, stretched over ~<500~ (EDIT: \~20.000) files.

Large files do not pose a problem, I've been able to upload files that do not fit in the Pi's memory without issue, but a larger number of singular files at once seems to cause issues.

Regarding memory: there is a memory measurement in my screenshot, showing the memory at almost no usage. But maybe I am not measuring the correct things here? To me this currently looks like a client side issue, since in my eyes, the server seems to be doing just fine.

If there are any better measurements I could provide, please tell me :)

**Comment by gletiecq** [comment]
Stressing with a large number of open files and seeing problems, I'd look at the configured limitation on open files per process in linux with "ulimit" and the system open file descriptors limitation defined in /proc/sys/fs/file-max.  If you exceed these limitations the system is going to start slowing down waiting for available file dscriptors to become available which seems consistent with your observations.  My guess is that a Pi is going to by default be somewhat conservative in these limits.

**Comment by kloon15** [comment]
Could u test this against the current master branch? I have rewritten a function called [checkConflict](https://github.com/filebrowser/filebrowser/blob/ae0af1f996e9c855ccd1bf4af90f03787f52d301/frontend/src/utils/upload.ts#L4) that runs now in O(n), which should help with lots of files being uploaded.

**Comment by wintermute-cell** [comment]
> Stressing with a large number of open files and seeing problems, I'd look at the configured limitation on open files per process in linux with "ulimit" and the system open file descriptors limitation defined in /proc/sys/fs/file-max. If you exceed these limitations the system is going to start slowing down waiting for available file dscriptors to become available which seems consistent with your observations. My guess is that a Pi is going to by default be somewhat conservative in these limits.

I checked, and the servers file descriptors are not limited, neither on the host machine, nor inside the container.
Checking for open file descriptors also does not return anything alarming, and there are actually no open file descriptors after a couple of moments proceeding the beginning of the upload attempt.

> Could u test this against the current master branch? I have rewritten a function called [checkConflict](https://github.com/filebrowser/filebrowser/blob/ae0af1f996e9c855ccd1bf4af90f03787f52d301/frontend/src/utils/upload.ts#L4) that runs now in O(n), which should help with lots of files being uploaded.

Thanks for taking a look at this! ~This wasn't it however, checking for conflicts takes \~1sec, and the indefinite hang occurs right after that.~ Hopefully I'll get to properly testing this soon :)

**Comment by wintermute-cell** [comment]
> directory of ~300MB of documents, stretched over <500 files.

I retract this statement, a `node_packages` directory hid in there, it's closer to 300MB in 20.000 files.

**Comment by Turdari** [comment]
I should check it more, but similar issues may exist. I uploaded the directory with many files(2.5 gb), it suddenly hangs. I'm in condition where packet loss are many. I'll upload more specific situation latter.
