### ISSUE TITLE
Support external frontend build in releases

### ISSUE THREAD

**Issue by benwiley4000** [filebrowser/filebrowser#3070]
**Is your feature request related to a problem? Please describe.**
For someone who just wants to edit some JavaScript and isn't so proficient in Go-land, It's a huge pain to re-build the executable, particularly if trying to target the architecture of a NAS for example (ARMv7l in my case). I spent many hours today trying to do this and I finally gave up - first trying to install all the necessary dependencies and build on the NAS itself (ran out of memory), then trying to cross-compile from my laptop (succeeded but executable failed to run when used on my NAS).

My life would become much easier if I could just re-build the vue app and ship that rather than having to re-build the file browser executable. 

**Describe the solution you'd like**
Custom javascript files were already proposed and rejected: https://github.com/filebrowser/filebrowser/issues/1125 If you don't support custom JavaScript files (which I think you should, what harm does it do?), could you at least please start shipping additional releases that include the "dev" flag a.k.a. targets an external web directory rather than embed FS ? 

**Describe alternatives you've considered**
As mentioned, I tried rebuilding my changes with Go, but it's very impractical and I never succeeded.

**Additional context**
In my case the change I want to implement is just a configurable origin for Share links, rather than using the current origin. The use case is when I'm on a router that doesn't support NAT loopback, so I need a different host for my internal connection to my filebrowser than for external connection. I'd like share links to automatically use the external host even if I'm accessing my internal host, so I can easily copy them to friends without modifying the links.

**Comment by benwiley4000** [comment]
Again I'm not a go expert, but I think something like this would work (not sure how the flag would actually be implemented):

![Screenshot from 2024-03-25 01-30-00](https://github.com/filebrowser/filebrowser/assets/13558253/e033f05f-e9fb-413c-9535-deab9b0fe5a3)

**Comment by kloon15** [comment]
If ur cross compiling, u need to build with `CGO_ENABLED=0` flag.
