### ISSUE TITLE
Uploading an old, small gif image from 1997 breaks filebrowser.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#3073]
**Description**
Save this image here and try dragging and dropping it into filebrowser. It will stall out. 

**Expected behaviour**
That filebrowser will handle this gif like it handles modern images.

**What is happening instead?**
Upload failed: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: /api/tus/tomcat.gif?override=true, response code: 500, response text: 500 Internal Server Error , request id: n/a)

**Additional context**
Not sure what else to add. Pretty straightforward. I'll even attach tomcat.gif here for you to try it.

**How to reproduce?**

**Files**
tomcat.gif (5/18/1997)

https://abs.freemyip.com/tomcat.gif
![tomcat](https://github.com/filebrowser/filebrowser/assets/161256786/7460055f-a6b3-4030-9b8d-ab3e8269b19a)
[tomcat.zip](https://github.com/filebrowser/filebrowser/files/14776542/tomcat.zip)

**Comment by NIronwolf** [comment]
I can drag and drop or use the dialog and it uploads fine on my instance.

**Comment by ghost** [comment]
> I can drag and drop or use the dialog and it uploads fine on my instance.

I don't understand how. I just tried in Firefox, Brave, and Chrome and neither worked. 

Here are my settings using: **filebrowser config cat -d filebrowser2.db**
I am using port 84 and no https - just http. 

```root@Ubuntu-test:~# filebrowser config cat -d filebrowser2.db
Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:

Branding:
  Name:
  Files override:
  Disable external links:              false
  Disable used disk percentage graph:  false
  Color:
  Theme:

Server:
  Log:           stdout
  Port:          84
  Base URL:
  Root:          /root/files
  Socket:
  Address:       0.0.0.0
  TLS Cert:
  TLS Key:
  Exec Enabled:  false

Defaults:
  Scope:         .
  Locale:        en
  View mode:     mosaic
  Single Click:  false
  Commands:
  Sorting:
    By:
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}

root@Ubuntu-test:~#```

**Comment by kloon15** [comment]
Uploads fine for me too.
