### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by alfonsop123** [filebrowser/filebrowser#3075]
![image](https://github.com/filebrowser/filebrowser/assets/109006708/ea57630f-bc5c-49e4-80cf-5a7bf9369f8a)
for this, how do i make it so when ppl sign up they get 10 gb of storage, and also get their files hosted at ./cdn/users/userhere

**Comment by gletiecq** [comment]
filebrowser by iteself doesn't have a restriction on allowed space for a user, although there might be ways to do this on the os that filebrowser is running on, depending on what you're running.  As for getting their personal files hosted at a particular URL, you might look at the setting "Auto create user home dir while adding new user" in the admin console.  Not sure if a user home dir is shareable, but a symlink would do the trick on a linux system if filebrowser can't share a home dir and the symlink could be created automatically when the user home dir is created.

**Comment by alfonsop123** [comment]
> filebrowser by iteself doesn't have a restriction on allowed space for a user, although there might be ways to do this on the os that filebrowser is running on, depending on what you're running.  As for getting their personal files hosted at a particular URL, you might look at the setting "Auto create user home dir while adding new user" in the admin console.  Not sure if a user home dir is shareable, but a symlink would do the trick on a linux system if filebrowser can't share a home dir and the symlink could be created automatically when the user home dir is created.

Im running this on a rpi4 using raspberry pi os, and I emailed that option but then what do I put for the other scope I just put . And it gives me whole files to the users... Hopefully you csn help me with both

**Comment by alfonsop123** [comment]
Ok
