### ISSUE TITLE
downloads folder broken on UmbrelOS

### ISSUE THREAD

**Issue by JakeDarling** [filebrowser/filebrowser#3078]
**Description**

This application is listed in the Umbrel App Store here http://umbrel.local/app-store/file-browser and currently does not work as advertised when installed that way. (This may be related to the recent 1.0 release. I am also using Umbrel's hardware that they sell)

The "downloads" folder for UmbrelOS does not work. Any attempt to create subfolders or upload files results in a 403 Forbidden error.

New folders/files outside of "downloads" can be created without issue.

**Expected behaviour**
I should be able to upload media for use with Jellyfin as advertised in the store listing images

**What is happening instead?**
I receive a 403 Forbidden error

**How to reproduce?**
Install fresh on UmbrelOS through their store

**Additional context**

**Files**
<img width="1166" alt="Screenshot 2024-03-29 at 10 35 05 AM" src="https://github.com/filebrowser/filebrowser/assets/5066132/5f07aa3d-2c6d-4dbf-9ec4-13bac53964b7">

**Comment by JakeDarling** [comment]
If anyone else runs into this, it can be worked around by using ssh and running

`sudo chmod 777 /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/`

But be aware that according to Umbrel this will not persist if it updates and it will need to be done again

**Comment by Gregu1939** [comment]
I'm having the same issue. Can't get add media to the downloads folder for Jellyfin.
