### ISSUE TITLE
help with signups

### ISSUE THREAD

**Issue by alfonsop123** [filebrowser/filebrowser#3080]
![image](https://github.com/filebrowser/filebrowser/assets/109006708/eaaae42d-466e-44c3-aa79-ccb9079463fa)
for some reason it saids it has wrong credentials when im trying to create an account

**Comment by gletiecq** [comment]
What is the output of "filebrowser users ls"?

**Comment by alfonsop123** [comment]
> What is the output of "filebrowser users ls"?

Works now idk why that had happened...

**Comment by alfonsop123** [comment]
Ok
