### ISSUE TITLE
Symbolic link in File browsers

### ISSUE THREAD

**Issue by quick-tutoriel** [filebrowser/filebrowser#3084]
Hello,

can you tell me if **symbolic links** created in a user's directory are recognized by File browser?

Thanks

**Comment by kloon15** [comment]
They are supported yes.

**Comment by quick-tutoriel** [comment]
Hello,

Thank you for your reply.
Is there a particular option because I'm getting this message: "Invalid Link".

I'm using version 2.27 under Docker.
Best regards

**Comment by kloon15** [comment]
Thats just how docker volumes work sadly, u need to mount the symlink folder in docker aswell.
See [link](https://stackoverflow.com/a/40322275) for explanation.

**Comment by Guiorgy** [comment]
It would be a security nightmare if any file/directory on host could be accessed simply by creating a symlink. Just mount anything that needs to be accessed from inside the container

**Comment by quick-tutoriel** [comment]
Thank you for your answers.
