### ISSUE TITLE
Superposition of filebrowser and pdf headers

### ISSUE THREAD

**Issue by andresbono** [filebrowser/filebrowser#3086]
**Description**

https://github.com/filebrowser/filebrowser/pull/3024 (part of [v2.28.0](https://github.com/filebrowser/filebrowser/releases/tag/v2.28.0)) is not fully compatible with PDF previews. The filebrowser header and the PDF previewer header are superposed. See https://demo.filebrowser.org/files/Lorem_ipsum.pdf as an example:

![image](https://github.com/filebrowser/filebrowser/assets/1057973/93a4c68f-3666-4dd5-a9c8-b93c9cc0e5b2)

- To click the PDF previewer buttons (zoom in, zoom out...) you have to wait until the filebrowser header hides.
- Once the filebrowser header is hidden, you cannot get it back (mouse move is not toggling the header).

**Comment by andresbono** [comment]
@niubility000, @o1egl, is it possible to keep the old behavior for PDF previews or fix the bug some other way?

**Comment by baur** [comment]
before

![image](https://github.com/filebrowser/filebrowser/assets/2898361/36ddd9bf-8096-4bfa-81a8-8b9959441f73)

after

![Screenshot 2024-04-02 084205-1](https://github.com/filebrowser/filebrowser/assets/2898361/413c3f95-c809-41dc-aa6e-bdb67305a433)

**Comment by andresbono** [comment]
I think #3163 partially fixed the issue (thanks!! 🎉 ), but there are still a couple of bugs we can address to improve usability:

* The bottom of the pdf cannot be seen, exceeds the window limits.
* There is no need to hide the header now that we are again fixing the space for it.

I sent #3274 to fix those.
