### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by quick-tutoriel** [filebrowser/filebrowser#3093]
Hello,

I'm using Filebrowser version 2.27.0 under docker with the official image.

When I copy a large number of files (200 for example) I systematically get first the 403 Forbidden error, then for some files I get this error :
"Upload failed: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: /api/tus/Pcloud/A%20Trier/guillaume-test/Documents%20Administratifs/Bulletins%20de%20salaire/ASP/2022_10_BP_octobre.pdf?override=false, response code: 500, response text: 500 Internal Server Error , request id: n/a)"

Just to clarify, I'm using rclone to mount a webdav directory on Pcloud to copy files.

Here's the command line I use to mount a Pcloud disk with rclone: "rclone mount Pcloud: /mnt/pcloud --vfs-cache-mode writes --allow-other " 

If you could help me or give me some hints because right now I can't see.

Merci.

![error_filebrowser_1](https://github.com/filebrowser/filebrowser/assets/4949554/2450c19e-e263-4c29-a92f-eca2f3138f2c)
![error_filebrowser_2](https://github.com/filebrowser/filebrowser/assets/4949554/34a1f0de-84be-4c3a-9470-3d6f2fd45b26)

**Comment by JiveOff** [comment]
We have this issue...
