### ISSUE TITLE
filebrowser login problem 

### ISSUE THREAD

**Issue by soulfulkhani** [filebrowser/filebrowser#3094]
i am a windows user. so i  am using windows terminal for using filebrowser but as soon as i  close windows terminal, the login page says site cant be reached. also i have to open windows terminal and do this filebrowser -r path to file to open the drive . so i want to ask why it cant run even after my terminal is not open and why i have to command every time about the path file ? what can be done to resolve it

**Comment by kloon15** [comment]
U need to run it as a service in the background, see [link](https://stackoverflow.com/a/15719678) on how to create one.

**Comment by soulfulkhani** [comment]
> U need to run it as a service in the background, see [link](https://stackoverflow.com/a/15719678) on how to create one.

thank you so much. one more help if i want to access my hdd external drive remotely do i have to install filebrowser in my external drive only ? or i can install it on my pc and can just do  filebrowser -r path can i am good to go ?

**Comment by soulfulkhani** [comment]
> U need to run it as a service in the background, see [link](https://stackoverflow.com/a/15719678) on how to create one.

i installed the service using nssm but service status is stopped and everytime i do nssm start xyz it says service access denied

**Comment by kloon15** [comment]
> > U need to run it as a service in the background, see [link](https://stackoverflow.com/a/15719678) on how to create one.
> 
> i installed the service using nssm but service status is stopped and everytime i do nssm start xyz it says service access denied

![image](https://github.com/filebrowser/filebrowser/assets/1431170/51490404-ab5a-4a3b-a9f5-03f62a99fe4d)

Did u install the pre-release version as the page says? As for accessing external drive, i would just create a directory junction with `mklink /J <link> <target>` that filebrowser can use.

**Comment by soulfulkhani** [comment]
> > > U need to run it as a service in the background, see [link](https://stackoverflow.com/a/15719678) on how to create one.
> > 
> > 
> > i installed the service using nssm but service status is stopped and everytime i do nssm start xyz it says service access denied
> 
> ![image](https://private-user-images.githubusercontent.com/1431170/320543439-51490404-ab5a-4a3b-a9f5-03f62a99fe4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTI0MDYsIm5iZiI6MTcxMjg1MjEwNiwicGF0aCI6Ii8xNDMxMTcwLzMyMDU0MzQzOS01MTQ5MDQwNC1hYjVhLTRhM2ItYTlmNS0wM2Y2MmE5OWZlNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTYxNTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFhN2JiYTE4ZTE1YzJiZjVjNjZhNjkwMTUzNGEwZmU2OWNiMzA3Y2Y0Y2NkNmQ4YWY1MWMyODUxNmZjNTA3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.owYI7fP9dkpSGBHvtQbt9arW-3pwtbcg1_T0HUrFIMI)
> 
> Did u install the pre-release version as the page says? As for accessing external drive, i would just create a directory junction with `mklink /J <link> <target>` that filebrowser can use.

thank you so much kloon. ah so it like directly giving access as we give it to other drives on pc wont work right ?
