### ISSUE TITLE
Office File types Viewable from Online Webpage

### ISSUE THREAD

**Issue by R44VC0RP** [filebrowser/filebrowser#3095]
**Is your feature request related to a problem? Please describe.**
I would like to see support for Word/Excel/Powerpoint viewing when using the online viewer to look at the file.

**Describe the solution you'd like**
I would like it to be able to successfully use the online viewer to view docx, pptx, xlsx type files.

**Describe alternatives you've considered**
Right now to view a file you have to download them and open on the computer.

I have looked a solutions for this and I have seen that this might work:
https://pspdfkit.com/blog/2023/how-to-build-a-vuejs-word-viewer/
https://apryse.com/blog/webviewer/how-view-pptx-documents-in-vue

**Comment by kloon15** [comment]
They r both paid software, ur best bet is the [OnlyOffice PR](https://github.com/filebrowser/filebrowser/pull/2954) getting added.
