### ISSUE TITLE
Couldn't display a html file in filebrowser

### ISSUE THREAD

**Issue by mengyaommm** [filebrowser/filebrowser#3107]
**Description**
i want to view a html file through filebrower, but it just display html source code
![image](https://github.com/filebrowser/filebrowser/assets/40377342/b45b5f9f-972c-4c2a-b4d1-f07e985060e3)

**Comment by zhao-wuyan** [comment]
me too

**Comment by gletiecq** [comment]
Filebrowser is not a web server.  If you are looking for a web server, I'd suggest you look at apache or nginx.
