### ISSUE TITLE
403 - When uploading in an mounted folder

### ISSUE THREAD

**Issue by Turboman3000** [filebrowser/filebrowser#3115]
Hi, i've mounted an SMB Share on my host to /mnt/smb and when i mount this folder to the containers /srv folder and then trying to upload/creating smth. In this folder from FileBrowser i get an 403 Forbidden. The smb folder at the host is chmod -R 777 and i'm logged in with the default admin account

**Comment by gletiecq** [comment]
What user and group are the files at /mnt/smb associated with?  Are they the same as the user/group that filebrowser is running as, or are they different?  When you define the file mount in fstab are you telling the system to mount them with a specific user/group or are you letting the system mount them with whatever system defaults the mount process will be using?

I had to fight through this one and use specific user/group options in /etc/fstab so filebrowser would have the correct permissions considering what user/group filebrowser was running as.  If there's a mismatch, you get a 403 error.
