### ISSUE TITLE
SERVER 500 - resource temporarily unavailable

### ISSUE THREAD

**Issue by R44VC0RP** [filebrowser/filebrowser#3118]
**Description**
I rebooted my server (not running in docker running as a standalone service), and when I tried to login I kept getting 500 errors in the bottom right corner. When I started to browse it would show some of my mapped files then start to say this location cannot be found. When I looked into the logs this is what it showed:

```
2024/04/13 08:39:08 Using database: /home/ryan/filebrowser.db
2024/04/13 08:39:08 No config file used
2024/04/13 08:39:08 Listening on [::]:8080
2024/04/13 08:39:14 /: 500 192.168.50.18 resource temporarily unavailable
2024/04/13 08:39:15 Error calculating resolution for image /._Projct4_UML.jpg: image: unknown format
2024/04/13 08:39:15 Error calculating image resolution: image: unknown format
2024/04/13 08:39:15 Error calculating resolution for image /._Project4_GUI_Example (1).png: image: unknown format
2024/04/13 08:39:15 Error calculating image resolution: image: unknown format
2024/04/13 08:39:15 Error calculating resolution for image /._raavcorp logo.png: image: unknown format
2024/04/13 08:39:15 Error calculating image resolution: image: unknown format
2024/04/13 08:39:15 Error calculating image resolution: image: unknown format
2024/04/13 08:39:15 /thumb/._Projct4_UML.jpg: 500 192.168.50.18 image: unknown format: unsupported image format
2024/04/13 08:39:15 Error calculating image resolution: image: unknown format
2024/04/13 08:39:15 /thumb/._Projct4_UML.jpg: 500 192.168.50.18 image: unknown format: unsupported image format
2024/04/13 08:39:15 Error calculating image resolution: image: unknown format
2024/04/13 08:39:15 /thumb/._Projct4_UML.jpg: 500 192.168.50.18 image: unknown format: unsupported image format
2024/04/13 08:39:21 /: 500 192.168.50.18 resource temporarily unavailable
2024/04/13 08:39:21 /: 404 192.168.50.18 readdirent /home/ryan/nas: no such file or directory
```

Nothing changed in my direct setup other than that I switched out my router, which should not have anything to do with it.
-NOTE: I have a SAMBA share mapped to /home/ryan/nas that filebrowser will then look at for the files. It has worked fine with no issues until now.

**Expected behaviour**
To be able to access my files from the web interface.

**What is happening instead?**
View log above.

**Additional context**
![Screenshot 2024-04-13 at 9 43 36 AM](https://github.com/filebrowser/filebrowser/assets/89211796/ffb19c15-8f5e-4532-8c3a-9cb50d0cbac4)
![Screenshot 2024-04-13 at 9 42 48 AM](https://github.com/filebrowser/filebrowser/assets/89211796/9de0227a-2fbf-43ca-aeef-6d4ca7bfed06)

**How to reproduce?**
I am honestly not sure how to reproduce it, I have tried to restart the service, run `filebrowser` independently from the original database to make sure there is no database issues. I have remounted the share, rebooted the server, etc.

**Comment by gruenheit** [comment]
I have experienced the same problem. Suddenly, without changing the configuration. Restarting the Docker services or Sambashare does not change it. Occurs with v2.27.0 and v2.28.0.

**Comment by gruenheit** [comment]
I fixed my issue with downgrading to Ubuntu kernel 5.15.0-101-generic on my docker host running Ubuntu 22.04.4 LTS.
I came across [this post](https://askubuntu.com/questions/1510500/what-happened-with-cifs-samba-connections-on-kernel-5-15-0-102-generic) after having [a second different problem](https://github.com/immich-app/immich/discussions/8487#discussioncomment-9108223).

**Comment by R44VC0RP** [comment]
@gruenheit this worked!
