### ISSUE TITLE
Incorrectly parsing .filebrowser.json when `password` is provided

### ISSUE THREAD

**Issue by rgryta** [filebrowser/filebrowser#3123]
**Description**
While trying to automate homelab deployment, I've encountered a problem when trying to set up default credentials for admin user.
I'm utilizing docker config functionality to modify the `.filebrowser.json` file with properly set up credentials.

This however leads to some corruption to the overall configuration and based on a docker image that I've built myself (although just the backend part of it) it looks like dollar signs are the issue.

Link to a gist with docker-compose that I've been using to debug this issue: https://gist.github.com/rgryta/82a74ae2374da8ae1359c8c04af38581

**Expected behaviour**
Logging in as `admin` with password `admin` should work.

**What is happening instead?**
Incorrect credentials error (and when adding some print statement to the code, it seemed like it would crash somewhere here (then again, I have no idea if my local docker build was correct - issue exists with the official docker image though):
https://github.com/filebrowser/filebrowser/blob/master/cmd/root.go#L418

**Additional context**
N/A

**How to reproduce?**
`docker-compose up -d ` on the provided gist example and try to log in as `admin:admin`.
You can check the bcrypted hash here: https://bcrypt-generator.com/

**Comment by zyfdegh** [comment]
I think `password` is not supported in the json config, there's no definition in the source code `storage/bolt/importer/conf.go`, see `oldConf struct`.
