### ISSUE TITLE
I cant reach filebrowser (lxc )

### ISSUE THREAD

**Issue by 9acca9** [filebrowser/filebrowser#3134]
Hi.
Im running filebrowser in a Alpine LXC proxmox.

i just see this in the terminal:
filebrowser
```
2024/04/19 19:21:30 Using database: /root/filebrowser.db
2024/04/19 19:21:31 No config file used
2024/04/19 19:21:31 Listening on 127.0.0.1:8080
```
with no error. But trying from a local network pc... i cant reach i also make a nmap. And it seems that the port are closed. Im not running firewall.

Thanks

**Comment by gletiecq** [comment]
A service listinging on 127.0.0.1 is not reachable outside of the machine hosting the service.  You need to configure filebrowser to listen on 0.0.0.0 (or whatever port you intend to serve from) in order for the service to be externally available.

**Comment by 9acca9** [comment]
Thanks!
