### ISSUE TITLE
HTTP ERROR 404 Not Found

### ISSUE THREAD

**Issue by yarone-git** [filebrowser/filebrowser#3144]
Hello,

After installing filebrowser in getting the error below while trying to open it via a web browser:
HTTP ERROR 404 Not Found

Thia is the output in powershell:
PS C:\Program Files\filebrowser> filebrowser -r C:\FileBrowser
2024/04/22 02:00:45 Using database: C:\Program Files\filebrowser\filebrowser.db
2024/04/22 02:00:45 No config file used
2024/04/22 02:00:45 listen tcp 127.0.0.1:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
PS C:\Program Files\filebrowser>

Please advise,
Yaron

**Comment by gletiecq** [comment]
When you don't specify that filebrowser should be serving requests on either all interfaces (0.0.0.0) or whatever ip address is associated with the interface available to external hosts on your network, it defaults to serving on the loopback port of 127.0.0.1.  That will not allow any hosts other than the machine that filebrowser is running on to get requests.  You need to configure filebrowser to use the address you need it to listen on with 'filebrowser config set -a 0.0.0.0' or whatever address is appropriate for you.  Make sure you run this command wherever the filebrowser.db file is located.

**Comment by yarone-git** [comment]
Forgot to mention, its not working on the machine that filebrowser is running on.
I've found the problem, the default port was in used, fix it and now its working.
Thanks! @gletiecq

**Comment by jazzdd86** [comment]
I have a similar issue. I am using filebrowser behind Traefik proxy. It seems filebrowser is listening on IPV6 by default. Traefik detects only the IPv4 address of the container. Therefore I will get a 404 error as filebrowser does not accept connetions on the IPv4 address.
I wrote a config file for filebrowser and set the listening address to 0.0.0.0 ("address": "0.0.0.0",), but it still uses IPv6.

CMD line outputs this:
filebrowser  | 2024/04/24 10:31:42 Using database: /database.db
filebrowser  | 2024/04/24 10:31:42 Using config file: /.filebrowser.json
filebrowser  | 2024/04/24 10:31:42 Listening on [::]:80

Any idea how to fix this?

**Comment by jvenezia** [comment]
@jazzdd86 disabling the container's healthcheck worked for me: https://github.com/filebrowser/filebrowser/issues/3092
