### ISSUE TITLE
Add button/shortcut to kill a command

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#315]
Some [Inception](http://www.imdb.com/title/tt1375666/). Let's suppose that we want to use filemanager, as it is now, as an IDE to develop filemanager itself:

- Build a container with required dependencies:

```
FROM hacdias/filemanager as base
FROM golang:alpine as inception
COPY --from base /filemanager /filemanager
COPY --from base /config.json /config.json
VOLUME [/tmp]
VOLUME [/srv]
EXPOSE 80/tcp
EXPOSE 8080/tcp
ENTRYPOINT ["/filemanager"]
CMD ["--config" "/config.json"]
```

```
docker build -t filemanager/inception --target inception .
```

- Execute a container with two exposed ports: one for the instance of filemanager acting as an IDE, and a second one for the version under development.

```
docker run -d -p 2000:80 -p 2001:8080 filemanager/inception --commands "git go ls mv /srv/filemanager" --no-auth -p 80 -s //srv
```

- Browse `localhost:2000` and in the search box execute `git clone https://github.com/hacdias/filemanager/ ./`. Edit the sources and run go build.

- In order to test the changes, run `/srv/filemanager --no-auth -p 8080 -s /tmp/srv` in the search box. Then, browse `localhost:2001` to check the version under development.

- Ideally, here we would be able to `Ctrl+C` in the running development instance, in order to kill it, edit the sources and start again.

It'd be great to have a button or keyboard shortcut to kill a running command, which was previously executed through the search box. However, I don't know whether:
- filemanager keeps track of this processes in the background, so that it is possible to view/edit other files while the command is running, and then go back to the process and kill it.
- Right now that's not an option, because there is no feature to go back to the output of a command, once you change the view. Yet, it is possible to keep the command view open in a tab/window of the browser and edit files in a different one.

---

In practice, I am describing a portable and OS agnostic development environment for filemanager, which is directly applicable to any other project. Just bring the image in a USB.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
