### ISSUE TITLE
TrueNas Install - Cannot figure this out - Keep getting 'You don't have permissions to access this.'

### ISSUE THREAD

**Issue by samyun76** [filebrowser/filebrowser#3153]
**Description**
Install on VM of Truenas scale. Have installed several times, followed several tutorials. This will not install correctly. I keep getting 'You don't have permissions to access this' when logging in and trying to access the share folder that I assigned at installation.

**Expected behaviour**
Be able to control files int the share.

**What is happening instead?**
Have no access to write, read, or edit. Get a 403 Error at the bottom of the window.

**Additional context**

**How to reproduce?**
Any install of this on my machine results in this error.

**Files**

**Comment by mooglestiltzkin** [comment]
> **Description** Install on VM of Truenas scale. Have installed several times, followed several tutorials. This will not install correctly. I keep getting 'You don't have permissions to access this' when logging in and trying to access the share folder that I assigned at installation.
> 
> **Expected behaviour** Be able to control files int the share.
> 
> **What is happening instead?** Have no access to write, read, or edit. Get a 403 Error at the bottom of the window.
> 
> **Additional context**
> 
> **How to reproduce?** Any install of this on my machine results in this error.
> 
> **Files**

dont use vm.

use jailmaker for truenas if you want to setup docker containers.

https://www.youtube.com/watch?v=S0nTRvAHAP8

https://www.truenas.com/docs/scale/scaletutorials/apps/sandboxes/

https://github.com/Jip-Hop/jailmaker


during the setup process for the jail docker config, you need to specify in the config the bind mounts for your datasets located on the datasets outside the jailmaker dataset.

then in docker compose the pathing you use, is the bind location you had set for jailmaker.

example

in jailmaker u have 

```
	--bind='/mnt/tank/docker/:/mnt/docker'
	--bind='/mnt/tank/docker/compose/:/mnt/compose'
	--bind-ro='/mnt/tank2/media:/mnt/media'
	--bind-ro='/mnt/tank2/media2:/mnt/media2'
```


then in compose for filebrowser you add e.g.

```
    volumes:
      - /mnt/media:/srv/Storage:ro
      - /mnt//mnt/media2:/srv/media2:ro
      - /mnt/docker/data/filebrowser/config/settings.json:/config/settings.json
      - /mnt/docker/data/filebrowser/config/database.db:/database.db
```

jailmaker don't mess with the acls. just follow the guide to setup then don't touch.
https://www.truenas.com/docs/scale/scaletutorials/apps/sandboxes/

for the datasets outside your jailmaker dataset, make sure their acls are correct if you are getting permission issues.

**Comment by mooglestiltzkin** [comment]
there is also an ongoing healthy bug not yet fixed
https://github.com/filebrowser/filebrowser/issues/3139

waiting for them to fix that

**Comment by Chanabra** [comment]
no access
