### ISSUE TITLE
Spikey CPU usage 

### ISSUE THREAD

**Issue by opalfroot** [filebrowser/filebrowser#3156]
While running v2.28.0 within Docker on a Raspberry Pi 4b (4GB) I see CPU spikes every few seconds when the web service is not being used. Unsure whether this is an issue or not but feels like whatever background process is running shouldn't be using so much CPU. \

![image](https://github.com/filebrowser/filebrowser/assets/2210644/753f9465-9475-4c97-8eb7-1321279bfc56)

**Comment by djak250** [comment]
Can you check if your container is just restarting over and over? It could be related to this #3160, which had a fix (#3130) merged shortly before I submitted the issue. lol. While you wait for the version bump to fix it in the upstream docker container, you can do one of two things:
- disable healthchecks
```yml
healthcheck:
  disable: true
```
or
- Override the healthcheck.sh with the updated script

`docker-compoes.yml`
```yml
volumes:
  - /host/filebrowser/healthcheck.sh:/healthcheck.sh
```
`healthcheck.sh`
```shell
#!/bin/sh
PORT=${FB_PORT:-$(jq -r .port /.filebrowser.json)}
ADDRESS=${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}
ADDRESS=${ADDRESS:-localhost}
curl -f http://$ADDRESS:$PORT/health || exit 1
```

**Comment by opalfroot** [comment]
@djak250 I tailed the logs and the container is stable and not yoyoing. I disabled the health check to see what effect that'd have and the same spikey behaviour persists. 

It appears to be running every 5-6 seconds. Is there anything scheduled within the app to run periodically?

**Comment by djak250** [comment]
The health check runs on a 5 second interval, according to the Dockerfile, so that's probably what you're seeing.

**Comment by opalfroot** [comment]
@djak250 yea I recreated the container after applying the settings and that's fixed it. 

Thanks for the help!

**Comment by djak250** [comment]
Oh yeah, I suppose it wouldn't pick it up on a start/stop. I am using Portainer, which probably forces a --recreate any time the compose changes.
