### ISSUE TITLE
Batch/Bulk Rename 

### ISSUE THREAD

**Issue by moutasem1989** [filebrowser/filebrowser#3159]
**Rename multiple files in an automated manner:**
- Find a string within the filename and replace it with another, or remove it.
- Add a number sequence (001,002,003,...) to a list of files.
- Use a text file as a source for new file names.

**Comment by Morgul** [comment]
I'll also add a request for regular expression find/replace support. Allows for more advanced renames using capture groups, i.e. to rename `track - artist.mp3` to `artist - track.mp3`.

See the [rename](https://man7.org/linux/man-pages/man1/rename.1.html) man page as an example.
