### ISSUE TITLE
could you kindly compile the newest version for mipsel

### ISSUE THREAD

**Issue by ryubaisan** [filebrowser/filebrowser#316]
i like filemanager and use it in my router
could you kindly compile the newest version for mipsel?
thanks in advance.

**Comment by ryubaisan** [comment]
who can help?

**Comment by hacdias** [comment]
Is it any of this versions:

```
mips, mipsle (32-bit MIPS big- and little-endian)
	Supports Linux binaries. New in 1.8 and not as well exercised as other ports.
mips64, mips64le (64-bit MIPS big- and little-endian)
	Supports Linux binaries. New in 1.6 and not as well exercised as other ports.
```

?

**Comment by ryubaisan** [comment]
mips, mipsle (32-bit MIPS big- and little-endian)
	Supports Linux binaries. New in 1.8 and not as well exercised as other ports.

it should be this.

**Comment by hacdias** [comment]
@ryubaisan here you've got the binaries for mips and mipsle of version 1.3.12

https://we.tl/lc4coMfzmZ

**Comment by ryubaisan** [comment]
it works.many thanks to you.
it will be better if you could provide a mipsle version when you update filemanager.
i think many users will like it.  ^_^

**Comment by hacdias** [comment]
From now on it will be available: https://github.com/hacdias/filemanager/releases/tag/v1.4.0

**Comment by carlsue** [comment]
here you are,mipsle version v2.11.0
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972843/filebrowser.zip)
