### ISSUE TITLE
can't show any files

### ISSUE THREAD

**Issue by ryubaisan** [filebrowser/filebrowser#317]
i run filemanager 1.4 in my router and showed error "somthing may goes wrong" in my files.
how to slove it?

command line showed message below

[RT-N56U_B1 /media/AiCard_01/filemanager]# ./filemanager -p 888 -s /tmp
Listening on [::]:888
2017/12/31 07:58:25 /auth/renew: 403 Forbidden
2017/12/31 07:58:25 /auth/renew: 403 Forbidden

**Comment by hacdias** [comment]
The `-s` flag is for the default scope for **new** users. So, if you had already run that command without the `-s` flag, the user was already created.

Please try doing the following:

1. Settings
2. User Managements/Users
3. Edit your user
4. Change the Scope
5. Save

**Comment by ryubaisan** [comment]
sloved,thanks.

but it doesn't work when i try to hidden the hidden files.
disallow regex \\/\\..+

**Comment by hacdias** [comment]
Hello, what's the state of this? Can this issue be closed?
