### ISSUE TITLE
replace confirmation modal window on upload appears briefly and then disappears immediately

### ISSUE THREAD

**Issue by alexjyong** [filebrowser/filebrowser#3173]
**Description**

@o1egl  has observed while reviewing [3111](https://github.com/filebrowser/filebrowser/pull/3111) that when a user choose to upload a file that already exists, the "replace" modal window appears briefly and then disappears immediately. However, this behavior is not replicated when the user uses the drag-and-drop feature.  Bug was not introduced with the aforementioned PR.

Edit:
Current workaround is to delete the existing file manually then do the re-upload, but that's clunky. Hoping to look at this soon. :) 

**Expected behaviour**

When user tries to replace a file with the file selector that already exists, the confirmation modal doesn't disappear and remains for the user to engage with it.

**What is happening instead?**

the "replace" modal window appears briefly and then disappears immediately. 

**Additional context**

**How to reproduce?**

Upload a file completely.  Upload the same file again through the file selector (not the drag and drop selector!) and the confirmation modal to replace the file or cancel the upload appears briefly then immediately disappears.

**Files**

**Comment by StanislavJochman** [comment]
Same for me and does not replace file.

**Comment by MafiaInc** [comment]
I have the same issue. I wanted to actually resume upload and I can't anymore as the window disappears immediately.

**Comment by ediazrod** [comment]
I am on the same situation

**Comment by alexjyong** [comment]
Current workaround is to delete the existing file then do the re-upload, but that's clunky. Hoping to look at this soon. :)
