### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alfonsop123** [filebrowser/filebrowser#3189]
Last login: Thu May  2 23:30:16 2024 from 192.168.1.171
alfonsop123@raspberrypi:~ $ filebrowser
2024/05/02 23:33:02 Using database: /home/alfonsop123/filebrowser.db
2024/05/02 23:33:02 invalid database
alfonsop123@raspberrypi:~ 
File is 
������$�W)`����	
��j�
ůΉ�6�0;9;l<�0�1��#-
�/Images/2ffb24ccfc37cc7b12776785a.png__gTuIGxkYgTuIGxkY/Images/image_2024-04-26_182900255.png__Gnee6wCkGnee6wCk/Post Malone - Better Now (LyricsLyric Video).mp3__nJgkQ3JnJgkQz3J/Post Malone - Better Now (LyricsLyric Video).mp3__pMFPRppQpMFPRppQ/classes/MARCH. Drawing Monday March 4th, 2024.jpg__elwBhdCPelwBhdCP/classes/RED Monday March 18, 2024.jpg__020e3020WAde3/classes/SUB WORK - Blend challenge.jGnIPqw6xGnIPqw6/images.jpg__D5GNxrETD5GNxrET/skibidimeme1.eg__dLQkJbdLjvQkJb/stuff/Cat_but_
etter.mp3__GaI
38lFGaI138lFstorm__ids
�0��#�0,<`6�;�;�102de3/classes/RED Monday March 18, 2024.jpg__02Ade3D5GNxrET/imags.jpg__D5GNxrETGaI138lF/stuff/Cat_but_better.mp3__GaI138lFGnee6wCk/Images/image_2024-04-26_182900255.png__Gnee6wCkdLjvQkJb/skibidimeme1.jpeg__dLjvQelwBhdCP/classes/MARCH. Drawing Monday March 4th, 2024.jpg__hdCPgTuIGxkY/Images/2ffb2402b4f1c37cc7b12776785a.png__gTuIGxkYnJgkQz3J/Post Malone - Better Now (LyricsLyric Video).mp3__nJgkQz3JpMFPRppQ/Post Malone - Better Now (LyricsLyric Video).mp3__pMFPppQxGnIPqw6/classes/SUB WORK - Blend challenge.jpg__xGnIPqw6P����`CX�Z{"id":1,"username":"admin":"177272","scope":".","locale":"en","lockPassword":false,"viewMode":"mosaic","singleClick":false,"perm":{"admin":true,"execute":true,"create":true,"rename":true,"modify":true,"delete":true,"share":true,"download":true},"commands":["sudo","docker"],"sorting":{"by":"name","asc":false},"rules":[],"hideDotfiles":false,"dateFormat":false}
{"id":10,"username":"alf","password":"$2a$10$gGRyz3OUDX1NF6ntnjKD7po8W4rvk3XkvR33MRGoiTAqb5vi","scope":"./media/root/85e2d70-c661-4fb2-bd03-dfe6791b4208/usersalf","locale":"en","lockPassword":false,"viewMode":"list","singleClick":false,"perm":{"admin":true,"execute":true,"create":true,"rename":true,"modify":true,"delete":true,"share":true,"download":true},"commands":["git","node","sudo","reboot","neofetch"],"sorting":{"by":"name","asc":false},"rules":[],"hideDotfiles":false,"dateFormat":false}__storm_index_ID  

__storm_index_Username adminalf
__storm_metadata 	!IDcountercodecjson 9Y__storm_metadatacodecjsonversion"2.0.0"P9����__storm_metadatacodecjsonauther{"recaptcha":null}server{"root":"/","baseURL":"","socket":"","tlsKey":"","tlsCert":"","port":"8080","address":"127.0.0.1","log":"stdout","enableThumbnails":false,"resizePreview":false,"enableExec":false,"typeDetectionByHeader":false,"authHook":"","tokenExpirationTime":""}settings{"key":"s9ipTYSJRUrgf+KrVadoNQ3cTVMkfng1QVeYB8GUiVKUmJMlaUgDBSXX+ew1gsGg
GUip4xdLvfn8c/Bw==","signup":true,"createUserDir":true,"userHomeBasePath":"/media/root/85e2d70-c661-4fb2-bd03-dfe6791b4208/users/unset","defaults":{"scope":".","locale":"en","viewMode":"mosaic","singleClick":false,"sorting":{"by":"","asc":false},"perm":{"admin":false,"execute":false,"create":true,"rename":true,"modify":true,"delete":true,"share":true,"download":true},"commands":["git"],"hideDotfiles":false,"dateFormat":false},"authMethod":"json","branding":{"name":"Alf's CDN","disableExternal":false,"disableUsedPercentage":false,"files":"","theme":"dark","color":""},"tus":{"chunkSize":52428800,"retryCount":5},"commands":{"after_copy":[],"after_delete":[],"after_rename":[],"after_save":[],"after_upload":[],"before_copy":[],"before_delete":[],"before_rename":[],"before_save":[],"before_upload":[]},"shell":[],"rules":[]}version2��������

��020WAde3__020WAde3020WAde3D5GNxrET__D5GNxrETD5GNxrETGaI138lF__GaI138lFGaI138lFGnee6wCk__Gnee6wCkGnee6wCkdLjvQkJb__dLjvQkJbdLjvQkJbelwBhdCP__elwBhdCPelwBhdCPgTuIGxkY__gTuIGxkYgTuIGxkYnJgkQz3J__nJgkQz3JnJgkQz3JpMFPRppQ__pMFPRppQpMFPRppQstorm__ids
����������020WAde3020WAde3__020WAde3D5GNxrETD5GNxrET__D5GNxrETGaI138lFGaI138lF__GaI138le6wCkGnee6wCk__Gnee6wCkdLjvQkJbdLjvQkJb__dLjvQkJbelwBhdCPelwBhdCP__edCPgTuIGxkYgTuIGxkY__gTuIGxkYnJgkQz3JnJgkQz3J__nJgkQz3JpMFPRppQpMFPRppQ__pMFPRppQxGnIPqw6xGnIPqw6__xGnIPqw6xGnIPqw6__xGnIPqw6xGnIPqw6P9����__storm_metadatacodecjsonauther{"recaptcha":null}server{"root":"/","baseURL":"","socket":"","tlsKey":"","tlsCert":"","port":"8080","address":"127.0.0.1","log":"stdout","enableThumbnails":false,"resizePreview":false,"enableExec":false,"typeDetectionByHeader":false,"authHook":"","tokenExpirationTime":""}settings{"key":"s9ipTYSJRUrgf+KrVadoNQ3cTVMkfiVKudCUmJMlaUgDBSXX+ew1gsGgnP4GUip4xdLvfn8c/Bw==","signup":true,"createUserDir":true,"userHomeBasePath":"/media/root/85e2d70-c661-4fb2-bd03-dfb4208/users/unset","defaults":{"scope":".","locale":"en","viewMode":"mosaic","singleClick":false,"sorting":{"by":"","asc":false},"perm":{"admin":false,"execute":false,"create":true,"rename":true,"modify":true,"delete":true,"share":true,"download":true},"commands":["git"],"hideDotfiles":false,"dateFormat":false},"authMethod":"json","branding":{"name":"Alf's CDN","disableExternal":false,"disableUsedPercentage":false,"files":"","theme":"dark","color":""},"tus":{"chunkSize":52428800,"retryCount":5},"commands":{"after_copy":[],"after_delete":[],"after_rename":[],"after_save":[],"after_upload":[],"before_copy":[],"before_delete":[],"before_rename":[],"before_save":[],"before_upload":[]},"shell":[],"rules":[]}version2
�c+IlV�c'99rP�o!i�n�nNd020WAde3{"hash":"020WAde3","path":"/classes/RED Monday March 18, 2024.jpg","userID":10,"expire":8706877398}D5GNxrET{"hash":"D5GNxrET","path":"/images.jpg","userID":10,"expire":10352419746}GaI138lF{"hash":"GaI138lF","path":"/stufatacodecjsondLjvQkJb{"hash":"dLjvQkJb","path":"/skibidimeme1.jpeg","userID":10,"expire":10352418305}elwBhdCP{"hash":"elwBhdCP","path":"/classes/MARCH. Drawing Monday March 4th, 2024.jpg","userID":10,"expire":8706876627}gTuIGxkY{"hash":"gTuIGxkY","path":"/Images/2ffb24ccf702b4f1c37cc7b12776785a.png","userID":10,"expire":8636215786}nJgkQz3J{"hash":"nJgkQz3J","path":"/Post Malone - Better Now (LyricsLyric Video).mp3","userID":10,"expire":2576275546}pMFPRppQ{"hash":"pMFPRppQ","path":"/Post Malone - Better Now (LyricsLyric Video).mp3","userID":10,"expire":2576275534}xGnIPqw6{"hash":IPqw6","path":"/classes/SUB WORK - Blend challenge.jpg","userID":10,"expire":8706873400}	@DH
RLinkUser__storm_dbconfig

@DH
RLinkUser__storm_dbconfig	

@DH
RLinkUser__storm_dbconfig

**Comment by pam-param-pam** [comment]
@alfonsop123 Please provide a more descriptive _description_ of the bug. Tell us what you did, what should have happend, what instead happend. Tell us as much additional information as possible so we can help you
