### ISSUE TITLE
slimming things down with custom css

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#319]
Any suggestion on slimming everything down for a 15 inch display the default is okay for bigger displays but for a 15inch laptop display it looks ugly

**Comment by hacdias** [comment]
Hello @mrunc. I use a 15" laptop and I don't experience any issues with the interface. Could you send me a screenshot?

**Comment by ghost** [comment]
it's not an issue I just think that the interface would look better if everything were a little smaller
I was looking if it can be done with custom css
<img width="532" alt="screen shot 2018-01-01 at 8 52 30 pm" src="https://user-images.githubusercontent.com/6995878/34470261-8c3b6a8c-ef36-11e7-9c54-98c93e6f2923.png">

**Comment by hacdias** [comment]
You can set, for example, `body { zoom: 0.9 }`. Try it out! 😄
