### ISSUE TITLE
Stop upload indicator from jumping around 

### ISSUE THREAD

**Issue by RayBB** [filebrowser/filebrowser#3199]
**Description**

Related to #3111 
It would be nice if the upload bar didn't jump around like crazy after it gets to each MB.
I think it is fine if it just shows a `11.00 MB` instead of `11MB` for that split second.

**Expected behaviour**

**What is happening instead?**

https://github.com/filebrowser/filebrowser/assets/921217/272599a5-1081-4695-8cd1-59416afab5db

**Additional context**

cc: @alexjyong who made the very nice PR to improve this recently! :)

**How to reproduce?**

**Files**

**Comment by kloon15** [comment]
Or we could just right-align the text.

**Comment by SimplisticGH** [comment]
I think the 11.00 makes more sense from a consistency standpoint. (do both)

**Comment by gdy666** [comment]
https://github.com/filebrowser/filebrowser/assets/2849711/2572d712-9571-4ef1-ade7-8b3de244cf45

**Comment by gdy666** [comment]
https://github.com/filebrowser/filebrowser/assets/2849711/01b4388f-39f9-4ee4-b3e6-af39df6eda2a

I tried to modify it

**Comment by RayBB** [comment]
@gdy666 it still seems to jump around even after the latest fix.

https://github.com/filebrowser/filebrowser/assets/921217/bfd5160e-1257-4357-83ec-202e363a989a

**Comment by RayBB** [comment]
Still an issue

**Comment by alexjyong** [comment]
Hi @RayBB  check this out :) https://github.com/filebrowser/filebrowser/pull/3354

**Comment by alexjyong** [comment]
Currently pending release.
