### ISSUE TITLE
Add screenshots / functionality to readme

### ISSUE THREAD

**Issue by derekperkins** [filebrowser/filebrowser#32]
Right now it's a really heavy investment to see what caddy-hugo does and what it looks like. A front end is sorely needed for Hugo and I'd love to see what's happening, but it's hard to invest the 30-120 minutes that it's likely going to take for someone not familiar with the process. For someone investigating Hugo, this means installing and learning Hugo, installing and learning Caddy then figuring out this plugin.

Just a few screenshots + a list of functionality would go a long way towards getting people to take the time to install it, myself included.

I'm super excited about this project and hope to see it continue to grow!

**Comment by mholt** [comment]
Perhaps a brief tutorial or example could be added to [caddyserver/examples](https://github.com/caddyserver/examples) too.

**Comment by hacdias** [comment]
@derekperkins I will add the screenshots soon. Thanks for the suggestion. I have new ideas to add to this plugin :)

@mholt maybe.
