### ISSUE TITLE
Hope Caddy plugin version can be updated simultaneously!

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#321]
I found that Caddy plugin version is still stuck in the v1.3.12 version, there are some BUG (For example, IDM download can not get the file size, does not support resume from break-point) will affect the use, hope to be able to update to the latest version!
Thank you~

**Comment by hacdias** [comment]
I'm just trying to update some build stuff with Travis. Then I'll update Caddy 😄

**Comment by hacdias** [comment]
Updated.
