### ISSUE TITLE
Does it support extract zip or archived files?

### ISSUE THREAD

**Issue by rikhtehgaran** [filebrowser/filebrowser#3210]
**Is your feature request related to a problem? Please describe.**
All file managers should be able to extract or zip files. it's supports zip only when we want to download

**Describe the solution you'd like**
Add features to zip or extract on the disk (not only for download or upload)

**Describe alternatives you've considered**
we have to upload or download 

**Additional context**
maybe it has a plugin or something. I just ask if it has these features

**Comment by seternate** [comment]
Would like that feature as well 👍
