### ISSUE TITLE
After uploading or deleting a file, web page title shows duplicated folder name

### ISSUE THREAD

**Issue by Platway** [filebrowser/filebrowser#3212]
**Description**
Steps to reproduce the bug:

1. Enter folder "dir1". The web page title shows "dir1 - Files".
2. Upload or delete a file in the folder. The web page title shows "dir1 - dir1 - Files".

**Expected behaviour**
The web page title should remain "dir1 - Files".

**What is happening instead?**
The web page title changes to "dir1 - dir1 - Files" (the folder name is duplicated).

**Comment by gdy666** [comment]
[fixed it]()https://github.com/filebrowser/filebrowser/pull/3200
