### ISSUE TITLE
Service terminates (no info)?

### ISSUE THREAD

**Issue by jcroy** [filebrowser/filebrowser#3217]
**Description**
I'm running filebrowser as a service with systemd (on Ubuntu 22). It runs fine, but over the past few days its terminates and I have no insight due to lack of verbosity in logging. Any ideas on determining if its a issue with filebrowser or my host? With no error from filebrowser besides below its making it pretty tricky. 

Below is the only log data that indicates an issue from the filebrowser side. 

```
May 09 02:03:57 host filebrowser[329502]: 2024/05/09 02:03:57 Caught signal terminated: shutting down.
May 09 02:03:57 host filebrowser[329502]: 2024/05/09 02:03:57 accept tcp [::]:8080: use of closed network connection
May 09 02:03:57 host systemd[1]: filebrowser.service: Main process exited, code=exited, status=1/FAILURE
```
This has happen twice now since installing it. I set this up over the weekend. 

Here is my config for filebrowser. 

```
{
  "port": 8080,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/etc/filebrowser/filebrowser.db",
  "root": "/mnt/hdd/filebrowser/"
}
```

And the config for the service:

```
[Unit]
Description=File browser: %I
After=network.target

[Service]
User=www-data
Group=www-data
ExecStart=/usr/local/bin/filebrowser -c /etc/filebrowser/default.json
Restart=on-failure
RestartSec=5s
#StandardOutput=append:/var/log/filebrowser.log
#StandardError=inherit


[Install]
WantedBy=multi-user.target
```

**Comment by jcroy** [comment]
Is there an ability to increase verbosity for the logging? I've search the project and have not found any indication that its possible.

**Comment by thielj** [comment]
Couldn't find verbose logging either, but this might be an external cause, ie. something sending the process a SIGTERM.

**Comment by jcroy** [comment]
> Couldn't find verbose logging either, but this might be an external cause, ie. something sending the process a SIGTERM.

Yeah good idea. I started looking for other applications and found that a docker instance of file browser I hadn't terminated correctly was running. Stopped that container and it no termination issues with the service since.
