### ISSUE TITLE
Space used not updating untill site refreshed 

### ISSUE THREAD

**Issue by StanislavJochman** [filebrowser/filebrowser#3218]
**Description**
If you have 2 drives in filebrowser and go in between them using GUI the size of how much space is left stays the same. You need to manually refresh the site using F5 to get free space in the current drive.

**Comment by pam-param-pam** [comment]
Well yes, no changes will be detected if done in another tab. You can test it with changing file names or creating folders. It's how this project was created. To solve this "issue" websockets would need to be added. You can ask maintainers for this feature, it's not really a bug in my opinion.

**Comment by StanislavJochman** [comment]
@pam-param-pam I think you do not fully understand me. When I open filebrowser.com/files (example) it shows the size of root disk. I have 2 disks mapped ( Data and Media ). When from 
filebrowser.com/files I go to media or data it still shows size of root disk. However when I press F5 in same tab it suddenly starts displaying size of Data/Media. 
Does that make sense? Or should I send you a video?

**Comment by pam-param-pam** [comment]
@StanislavJochman im not quite sure if i understand correctly. If you could send a viceo, I'll try to dig into source code.

**Comment by Gh0stExp10it** [comment]
Same problem. If you have multiple mounted drives attached into the filebrowser container, it won't update the used space bar on the left. This worked in the past (last release) without any problems.

In this example I've refreshed the whole page and it now displays the USB-drive size. When I switch back to another drive it will be the same used space from the USB-drive and not auto update.
![screenshot_filebrowser_used_space_20240522](https://github.com/filebrowser/filebrowser/assets/7295005/eaab4327-46b2-4f31-8fe9-e7f541a46f2b)

**Comment by couryrr** [comment]
I think this is exactly what I came here trying to fix as well. 

- I am running filebrowser in an LXC on proxmox. 
  - The container has a 12gb drive.
- I then have an NFS mount to a NAS in /media/Filebrower 
  - This has a 500gb capacity. 
- I run filebrower from in the mount
  - cd /media/Filebrower
  - filebrowser -a 0.0.0.0
 
When I run the UI I can see all the data I expect in the NFS mount but the storage bar on the bottom left shows 11.7gb of the container not the NFS mount's 500gb.

**Comment by Hujgo** [comment]
Any updates on this? v2.27.0 doesn't have this issue
