### ISSUE TITLE
could u add a option to show or hide the hidden files and folders?

### ISSUE THREAD

**Issue by ryubaisan** [filebrowser/filebrowser#322]
could u add a option to show or hide the hidden files and folders?
now it show all the hidden things in default.

**Comment by hacdias** [comment]
@ryubaisan on user settings, you can find a section called 'Rules' where you can allow/disallow the access to files and folders. 😄

**Comment by ryubaisan** [comment]
thanks~~^_^

**Comment by ryubaisan** [comment]
disallow regex \\/\\..+

the example you gave in setting seems unvaild.
it didn't change anything when i setted.

**Comment by hacdias** [comment]
Oops, sorry. Try: ```disallow regex [\\\/]\..+``` to hide dotfiles.

**Comment by ryubaisan** [comment]
sloved！thank you very much! ^_^

**Comment by saghul** [comment]
Hi there! awesome work with filemanager, thanks!!! I just ran into this, but I'm not using auth, so there is no user settings section AFAIS... is there a way to hide dotfiles in this case? Thanks!

**Comment by hacdias** [comment]
Currently, you can't do that without using auth. Could you open an issue for that?

**Comment by saghul** [comment]
@hacdias Done! https://github.com/filebrowser/filebrowser/issues/349 Cheers.
