### ISSUE TITLE
Ability to Remove 'Login' button from shared links

### ISSUE THREAD

**Issue by SoreThumb1** [filebrowser/filebrowser#3225]
**Is your feature request related to a problem? Please describe.**
On shared links, there is an option to login on the left side. However, I don't necessarily want or expect those I'm sharing with to try logging in.

**Describe the solution you'd like**
An option to remove the login button from shared links and free up that padding on the left side.

**Additional context**
![login](https://github.com/filebrowser/filebrowser/assets/25835158/f4e74b72-8d9e-4339-b29f-723c8085fcbd)

**Comment by obuno** [comment]
+1, I'd really appreciate to have that possibility as well. Thanks a lot !

**Comment by obuno** [comment]
anti sudden death bump

**Comment by obuno** [comment]
Hi all -- I went for gokapi because of this issue -- thanks
