### ISSUE TITLE
Firefox don't load full folder, can't see all files present.

### ISSUE THREAD

**Issue by badrow** [filebrowser/filebrowser#3226]
When opening a folder with firefox, filebrowser displays only the number of files that can be printed in the current window size, and not all files of the folder.

When I open the same folder in chrome or other chromium-based browser, the files are loading while i'm scrolling so I can see all files out of initial position.
Tested on windows and linux, same behavior : Firefox is not loading all files.

Step to reproduce :

Create a folder and upload more than 50 files to it.
Open the folder in filebrowser with firefox : You can't see all the files inside the folder, only the first files are displayed.

Tip : when you zoom out and reload the page, more files are loaded, but it still stop to what the tab / window of firefox can display.

**Comment by knipp30** [comment]
I have this issue too. Not present when using chrome.

**Comment by JacobDB** [comment]
I'm also experiencing this issue, would really appreciate a fix.
