### ISSUE TITLE
Just wanted to say thank you for existing!

### ISSUE THREAD

**Issue by omnisophia** [filebrowser/filebrowser#3228]
I'm sorry to waste a bug report on this however, your program saved my a$$ last minute.  I am very grateful! Just wanted to express that! 

I had to make a large amount of files available to a client last minute.  So I just happen to find this piece of kit, ran it on tmux, configured a home path for it with the command, mounted a fstab cifs mount to that home path, and wham!  We have shared files. 

It even worked with a CIFS mount.  Nothing short of amazing!

**Comment by ediazrod** [comment]
Very good idea to share files and solve my issue with the umask files... mount over cifs... clever very clever

**Comment by omnisophia** [comment]
> Very good idea to share files and solve my issue with the umask files... mount over cifs... clever very clever

```
curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
mkdir $MOUNTPOINTNAME
filebrowser -p 8080 -a x.x.x.X -r /home/$USER/$MOUNTPOINTNAME
```
```
sudo nano /etc/fstab
//[NAS-IP-ADDR]/$PATH /home/$USER/$MOUNTPOINTNAME cifs vers=2.0,rw,username=[USERNAME],password=[PASSWORD],iocharset=utf8,file_mode=0777,dir_mode=0777,noperm 0 0
sudo mount -a 
```

```
$HOME ~ ls ./$MOUNTPOINTNAME
```
Renders NAS files. 

Then I just pointed a nginx reverse proxy to it and forwarded 80 to 8080, added lets encrypt on the reverse proxy. Fully hosted files. 

Not very fast. However it kept me from getting fired.

**Comment by ediazrod** [comment]
I tested and works very well on my case.. I need to clear some issues to avoid disconnect but and the ends is one of the best solutions :-D 

Thanks again for the idea.

**Comment by omnisophia** [comment]
> I tested and works very well on my case.. I need to clear some issues to avoid disconnect but and the ends is one of the best solutions :-D
> 
> Thanks again for the idea.

I would also run the command 

``filebrowser -p 8080 -a x.x.x.X -r /home/$USER/$MOUNTPOINTNAME```

Inside of fstab or create a tmux session and run it inside of that.
