### ISSUE TITLE
Can't obtain file size during file download

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#323]
v1.4.3 version (v1.3.10 support, v1.3.11 not tested, v1.3.12-v1.4.3 not supported)
When downloading a file, the file size can not be retrieved resulting in unsupported multithreaded download, and resume from break-point!
For example: Internet Download Manager

**Comment by ghost** [comment]
I am experiencing the same issue but only for zipped downloads. Single file downloads correctly show file size in the download manager.

**Comment by helloray** [comment]
I guess the zipped file is generated on-the-fly,  so the file size is unable to be known.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
