### ISSUE TITLE
Copy to Clipboard Buttons Not Working in Safari

### ISSUE THREAD

**Issue by geozeke** [filebrowser/filebrowser#3232]
**Description**
When clicking either the `Copy to clipboard` or `Copy download link to clipboard` buttons when using Safari, nothing happens. The links are not copied to the clipboard.

**Expected behaviour**
When clicking either of those buttons, the respective links should be copied to the clipboard and a green popup presents at the bottom of the screen indicating that the links were successfully copied.

**What is happening instead?**
No response; links are not copied and no green popup is presented.

**Additional context**
These buttons worked fine in Safari a few releases back, and they seem to work fine in either Chrome or FireFox now. There was just an update to MacOS (bumped to Sonoma v14.5), as well as a new release of Filebrowser in the last two weeks. I can't pinpoint which update may have been associated with the issue.

**How to reproduce?**
Using Safari, select any file in the Filebrowser window; then click on the `Share` button at the top of the screen. When you see the popup, click on either the `Copy to clipboard` button or the `Copy download link to clipboard` button. Note that no links are copied to the clipboard, and there's no popup indicating successful copy.

**Files**

**Comment by kloon15** [comment]
Could u test latest release, there was a PR fixing clipboard issues.

**Comment by geozeke** [comment]
Thanks for reaching out. I’m running FileBrowser in docker on Ubuntu 22.04. I pulled the latest image and I’m accessing the running container using Safari. The issue still seems to be there (for Safari in macOS, iOS, and iPadOS). The links in this version still copy correctly in FireFox and Chrome.

Not sure if it's helpful, but when I inspect the elements in the sharing popup, this is what shows for the html:

```html
<table>
  <tr>
    <th>#</th>
    <th>Share Duration</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td>wZ_RYWCl</td>
    <td>Permanent</td>
    <td class="small">
      <button class="action copy-clipboard" aria-label="Copy to clipboard" title="Copy to clipboard">
        <i class="material-icons">content_paste</i>
      </button>
    </td>
    <td class="small">
      <button class="action copy-clipboard" aria-label="Copy download link to clipboard" title="Copy download link to clipboard">
        <i class="material-icons">content_paste_go</i>
      </button>
    </td>
    <td class="small">
      <button class="action" aria-label="Delete" title="Delete">
        <i class="material-icons">delete</i>
      </button>
    </td>
  </tr>
</table>
```

**Comment by kloon15** [comment]
Could u check the console logs in devtools? If u dont get the toast saying link copied u should see an error in console.

**Comment by geozeke** [comment]
Interesting...nothing shows up in the logs. There's no response when the buttons are pressed, and no entries are generated in the logs.

**Comment by kloon15** [comment]
Are you accessing filebrowser thru https or http?

**Comment by geozeke** [comment]
I’m accessing it through https. I’m self-hosting File Browser in docker behind HAProxy with a ZeroSSL certificate (not self-signed). I’m also self-hosting a DNS, so I access File Browser using a FQDN, like this:

`https://fb.mynetwork.net`

**Comment by kloon15** [comment]
Does this demo work on Safari?
https://web.dev/async-clipboard/#demos

**Comment by geozeke** [comment]
It does. The content is copied or pasted as expected, and the toast also shows up as expected. It works on Safari in both macOS and iOS.

Just to make sure I'm not missing something I tested my File Browser instance with Safari, Chrome and FireFox again on several platforms. It works as expected in Chrome on macOS, and FireFox in a Ubuntu virtual machine. In doesn't seem to work in either Safari on macOS, or Chrome and Safari on iOS.

**Comment by Roboin161** [comment]
Has this been updated?

The demo posted here earlier works fine for me on Safari in iOS, but the FileBrowser copy buttons do not. On MacOS and Windows 10 it does work fortunately.

FileBrowser is running through Docker on Raspberry Pi OS 64-bit behind NGINX Reverse Proxy Manager.

**Comment by Terror-Gene** [comment]
Not working for me either (Safari on iOS).
Works fine if I connect directly to the server on the local network via http, but doesn’t work when connecting through reverse proxy via https (npm).
Edit: to be clear, copy to clipboard works fine on windows through the reverse proxy.

**Comment by Roboin161** [comment]
It also works for me on iOS when approaching it on its local ip over http. But running behind NGINX Reverse Proxy Manager over https it doesn't.

**Comment by kloon15** [comment]
What is the Safari version on iOS? We are just using plain [writeText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) which should be supported from Safari 13.1 onwards.

**Comment by Roboin161** [comment]
I'm not sure where to check the Safari version, but I'm on iOS 17.5.1 with latest Safari update.

**Comment by geozeke** [comment]
Are you using the docker image @Roboin161? I don't think that's been updated yet.

**Comment by Roboin161** [comment]
> Are you using the docker image @Roboin161? I don't think that's been updated yet.

I am. But that could be it then.

**Comment by hugmypc** [comment]
> > Are you using the docker image @Roboin161? I don't think that's been updated yet.
> 
> I am. But that could be it then.

Did changing the image work for you?

**Comment by Roboin161** [comment]
I haven't been able to check yet, but in the FileBrowser instance itself it says it's on version 2.30.0.

**Comment by kloon15** [comment]
Its not in version 2.30, will drop in the next one.

Roboin161 ***@***.***> ezt írta (időpont: 2024. júl. 29., H
17:27):

**Comment by Roboin161** [comment]
Thank you! Patiently awaiting the update for docker!

**Comment by sabeDev** [comment]
not working, I have safari 17.6; on Sonoma. Works fine if I used Edge; so looks specifically as a safari issue.

**Comment by geozeke** [comment]
Curious. It's not working for me now either. It worked when I tested a pre-release build, but it doesn't work in this update.

**Comment by Roboin161** [comment]
Not working over here either.

**Comment by julsssark** [comment]
Does not work for me using Safari on MacOS Sequoia 15.0 and Graylog 6.0.6.

**Comment by Toucanto** [comment]
copy is still not functional, on any iOS browser, it goes to clipboard when i try to copy through https on desktop, mobile still isint working.

**Comment by WenqingZong** [comment]
Got the same problem. My Raspberry Pi is running Ubuntu 24.04.1 LTS, used `curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash` to download `filebrowser` binary at version `2.31.2`, hosted it behind a `nginx` reverse proxy and the share function does not work in MacOS Safari. Actual behavior is exactly as described above. 

Also, if I access it via private ip (`192.168.1.XX`), then share function works normally.

**Comment by koalawangyang** [comment]
I have the same issue on the latest version v2.31.2, it's okay in other browsers. Only Safari has this problem.
