### ISSUE TITLE
The shell window is displayed underneath the settings icon

### ISSUE THREAD

**Issue by freddyholms** [filebrowser/filebrowser#3233]
**Description**
When I click on the Shell icon, it shows up squeezed up on the right
**Expected behaviour**
A shell window on the bottom of the page.
**What is happening instead?**
![Screenshot_16-5-2024_231312_192 168 162 210](https://github.com/filebrowser/filebrowser/assets/137962239/8138c551-88bf-414c-acb0-4361a19c6f97)

**Additional context**
I have tried both the alpine and linuxserver docker images and this error occurs in both. Also tried different browsers like firefox and edge.
**How to reproduce?**
Just launch the vanilla docker container, log in, and launch the shell.

**Comment by ShlomoCode** [comment]
for me too

**Comment by o1egl** [comment]
Fixed in the new version of the app
