### ISSUE TITLE
Unable to access hosted filebrowser on external devices within a LAN

### ISSUE THREAD

**Issue by novaTopFlex** [filebrowser/filebrowser#3234]
**Description**
I am trying to utilize my `wlp2s0` IP address to access the `filebrowser` application and the only device that I can access the application from in my Local Area Network (no port forwarding by the way, so only on my LAN) is the actual localhost computer.

**Expected behaviour**
I expected to be able to launch the `filebrowser` application by navigating to the appropriate website and port on my other devices, but that had continuously failed. I had attempted to change the IP address to listen on to my `wlp2s0` address and not to the default loopback address which is always `127.0.0.1`.

**What is happening instead?**
Sorry, but I have not attempted to use verbose mode with this application.

**Additional context**
On my other devices on my Local Area Network (LAN), each external system claims that the "server cannot be found" or an identical issue.

**How to reproduce?**
Visit `http://<address>:<port>` on a device that shares the network or includes access to the IP address within the network (WAN with port forwarding, otherwise LAN).

**Files**
There is no specific file to be pinpointed in this issue. I am not sure if this is a problem with the Go code, and even then, I do not have significant Go language experience and would be unsure which Go file to blame.

**Comment by ShlomoCode** [comment]
Try disabling "AP Isolation" (also known as "Client Isolation" or "Guest Mode") in your router settings

**Comment by novaTopFlex** [comment]
I am not sure if that would be the appropriate setting, as the only port that is unavailable on other devices within my network is whatever port is being utilized for `filebrowser`; all other ports and services connected operate without issue. I have also tried other applications and services that use HTTP/TCP/IP to connect (noVNC and Python HTTP Server) and have been successful outside the immediate localhost so long as the network remained the same. Therefore, I am not sure what the problem would be.

**Comment by novaTopFlex** [comment]
I have successfully figured out that I must listen to IP address `0.0.0.0` for success with accessing other devices within my Local Area Network (LAN).

**Comment by ShlomoCode** [comment]
> other applications and services that use HTTP/TCP/IP to connect (noVNC and Python HTTP Server) and have been successful outside the immediate localhost so long as the network remained the same

important information! 
What is the command you are running? Try like this:

```
filebrowser --address 0.0.0.0
```

**Comment by novaTopFlex** [comment]
filebrowser --address 0.0.0.0 # Listening on [::]:8080

The application simply defaults to the “loopback” IP address at `127.0.0.1`.
