### ISSUE TITLE
403 Error on upload, error message unhelpful

### ISSUE THREAD

**Issue by gletiecq** [filebrowser/filebrowser#3238]
**Description**
If a user does not have edit permissions, file uploads fail with a cryptic error and leaves a zero length file.

Upload failed: Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: /api/tus/"file-name"?override=true, response code: 403, response text: 403 Forbidden, request id: n/a)

Zero size file is created as a result.

**Expected behaviour**
If user permission problems exist provide a useful error message such as "you do not have the required permissions to upload a file.  Contact your system administrator for help."

That, or do not consider the initial upload of a file to be an edit, which shouldn't be the case anyways.

**Additional context**
Filebrowser version 2.27.0, 
uname -a:  Linux ... 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
filebrowser running on port 127.0.0.1:8081, nginx reverse proxy to 0.0.0.0:80.

nginx log excerpt: 
2024/05/19 14:52:27 [error] 725#725: *37179 readv() failed (104: Unknown error) while reading upstream, client: 10.10.76.17, server: <my machine>, request: "PATCH /api/tus/"my file"?override=false HTTP/1.1", upstream: "http://127.0.0.1:8081/api/tus/"my file"?override=false", host: "avtech", referrer: "http://avtech/files/AGA/"

**Comment by gletiecq** [comment]
UPDATE: tested on multiple file roots, including external USB mounted with "username":users uid:gid, and still getting same error.  Does not appear to be a file permissions problem as files are created with the correct permissions, but are all created (with zero length) and then not written with data.

**Comment by gletiecq** [comment]
UPDATE 2: updated filebrowser to version 2.30.0 and while the error message goes away, the zero length file writes problem remains.

**Comment by gletiecq** [comment]
To clarify: the "Edit Files" permission will create unexpected behavior if left unchecked.  If it is NOT checked, users attempting to upload a file will create a zero length file with no content, and in version 2.30 this will not result in an error.  I would recommed that the upload button be disabled as well as drag-and-drop if this is to be retained, or more logically, that the permission option be removed entirely.  To have create permissions but not upload makes no logical sense.

Perhaps re-thinking the permissions scheme is in order, having "full control", "upload/read only" or "read only" would make sense.  An "upload/read only" would be useful to have overwrites prevented by "updates" creating a new version of the file with a modified name and the old version retained which would be useful in the environment where I am using filebrowser.

**Comment by gnustavo** [comment]
I'm facing the same problem using Filebrowser 2.29.0.

As a workaround I've given "Edit Files" permission to all users that had only "Create file and directories" and "Download" permissions. They were unable to upload files.
