### ISSUE TITLE
use case with many files in folder

### ISSUE THREAD

**Issue by arteta22000** [filebrowser/filebrowser#324]
To begin, thank you for this tool, it is very nice to use !

I noticed a problem. We have a folder with 9000 files (yes I know...). When trying to access the folder, we have 2 behaviours:
- If the computer is a little old (white Macbook for example): cpu increase + not complete display.
- If more powerful computer: display with scrolling.

But in both cases, if you upload a file, it doesn't appear at the top of the list, as if the sort doesn't work.

Could we stop the Infinite scrolling after 500 or 1000 files? and after display in blocks of 500.

**Comment by hacdias** [comment]
Hey @arteta22000!

Yup, that's a good point. There is already an issue opened for that (#155) but since no one mentioned it in a while, it didn't go forward.

We should keep the conversation on that issue.
