### ISSUE TITLE
option to disable auto fill

### ISSUE THREAD

**Issue by bathtubfulloftoast** [filebrowser/filebrowser#3243]
**Is your feature request related to a problem? Please describe.**
i dislike how auto fill prevents me from doing new lines without it replacing the word ive typed.

**Describe the solution you'd like**
an option below ``Hide dotfiles`` in profile settings

**Describe alternatives you've considered**
making enter not do anything with auto fill

**Comment by o1egl** [comment]
I'm not following what is the issue. Filebrowser has no autofill. It's your input device settings

**Comment by bathtubfulloftoast** [comment]
> I'm not following what is the issue. Filebrowser has no autofill. It's your input device settings

it def does it shows up on multiple devices
im talking about the little box with word suggestions that pops up as you type

**Comment by jkingster** [comment]
> > I'm not following what is the issue. Filebrowser has no autofill. It's your input device settings
> 
> it def does it shows up on multiple devices im talking about the little box with word suggestions that pops up as you type

That's because every device..typically has word suggestions?

Filebrowser doesn't have autofill.

**Comment by bathtubfulloftoast** [comment]
> > > I'm not following what is the issue. Filebrowser has no autofill. It's your input device settings
> > 
> > it def does it shows up on multiple devices im talking about the little box with word suggestions that pops up as you type
> 
> That's because every device..typically has word suggestions?
> 
> Filebrowser doesn't have autofill.

this thing im talking about this
![Screenshot_20240522-105510.png](https://github.com/filebrowser/filebrowser/assets/50601927/875b1454-883f-4b4f-b810-bf8819cfe5c8)
