### ISSUE TITLE
Password resets to default `admin` with each update

### ISSUE THREAD

**Issue by Tiritibambix** [filebrowser/filebrowser#3244]
**Description**
Password resets to default `admin` with each update

**Expected behaviour**
Password shouldn't reset to default `admin` with each update

**What is happening instead?**
Password resets to default `admin` with each update

**Additional context**
Running Filebrowser with docker on debian.
Everytime there's an update, the secured password I set returns to the default `admin` password

**How to reproduce?**
Run an update of the container

**Comment by o1egl** [comment]
You should mount a persistent db file into the container. Follow installation [guide](https://filebrowser.org/installation#docker) on the website

**Comment by Tiritibambix** [comment]
> You should mount a persistent db file into the container. Follow installation [guide](https://filebrowser.org/installation#docker) on the website

Sorry for the very late answer, and thank you for your help. I don't know how I missed that.
