### ISSUE TITLE
Losing settings after container update

### ISSUE THREAD

**Issue by m3tc0n** [filebrowser/filebrowser#3245]
Hello, I have a problem with filebrowser and hopefully it can be solved.

I have filebrowser running as a docker container. For example, when the container is updated, I lose my settings. This concerns for example user settings.

My docker compose looks like this:

_services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/Cloud:/srv
      - /DATA/AppData/filebrowser/database/filebrowser.db:/database/filebrowser.db
      - /DATA/AppData/filebrowser/config/settings.json:/config/settings.json
    networks:     
      filebrowser:
        ipv4_address: 172.25.0.2_

_networks:
  filebrowser:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1_ 

My settings.json looks like this:

_{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}_

**Comment by o1egl** [comment]
The mounting path for settings and the db is incorrect. Follow docker installation docs on the [website](https://filebrowser.org/installation#docker)

**Comment by m3tc0n** [comment]
Thanks, I changed my docker compose and it seems to work now:

_services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/Cloud:/srv
      - /DATA/AppData/filebrowser/database/filebrowser.db:/database.db
      - /DATA/AppData/filebrowser/config/filebrowser.json:/filebrowser.json
    networks:     
      filebrowser:
        ipv4_address: 172.25.0.2_

_networks:
  filebrowser:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1_

Another question if I may: when changing the language settings to Dutch (Belgium) some settings disappear, for example:

![afbeelding](https://github.com/filebrowser/filebrowser/assets/106514117/0610437a-384f-4d32-a3f2-da4d06523b22)

Also I can't find dark mode anymore.

**Comment by m3tc0n** [comment]
Anyone?
