### ISSUE TITLE
Multiple hosters (same concept as torrent)

### ISSUE THREAD

**Issue by qwertysmosh** [filebrowser/filebrowser#3247]
Do we already have a feature that allows multiple people to host a single FileBrowser server? It'll be the same concept as torrenting but instead it is hosted by a trusted group of your own servers.

**Comment by jarble** [comment]
No, File Browser isn't a peer-to-peer application. I use [Syncthing](https://syncthing.net/) to sync folders from FileBrowser with other servers.

**Comment by qwertysmosh** [comment]
I see that isn't possible... It could've save me some bandwidth and less cost if they allowed such feature though, 2 hosts taking turns and halving download/upload speed on one server. Anyway, thank you for you answer!
