### ISSUE TITLE
Please, Hide the download button if no file is selected ⚠️

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#3249]
**Is your feature request related to a problem? Please describe.**

The current behavior of the file manager allows users to download the entire root or current folder if they click the download button without selecting any specific files. This can lead to accidental downloads of large amounts of data, which is not desirable.

**Describe the solution you'd like**

1. Modify the UI to hide the download button until at least one file or folder is selected. This will prevent users from inadvertently downloading large amounts of data.

2. Add "Select All" button to the file manager interface that allows users to easily select all files and folders within the current directory. This feature should enable users to download all contents intentionally and in a controlled manner.

**Comment by gletiecq** [comment]
+1 on this

**Comment by sevmonster** [comment]
Or, at least hide it behind a modal/configuration option.

**Comment by baur** [comment]
it's sad, so sad 😢
