### ISSUE TITLE
cant use command

### ISSUE THREAD

**Issue by P-Asta** [filebrowser/filebrowser#3252]
use run command: `filebrowser -r .`
<img width="1680" alt="image" src="https://github.com/filebrowser/filebrowser/assets/86705803/53127fff-b727-4da6-bbcb-70889a67193c">
<img width="1065" alt="image" src="https://github.com/filebrowser/filebrowser/assets/86705803/07508f4a-87df-4a74-882e-4ca4509abd07">
<img width="1679" alt="image" src="https://github.com/filebrowser/filebrowser/assets/86705803/f100906c-84cb-4d40-9c2c-3fc54ddfb864">

**Comment by Yothin4445** [comment]
https://github.com/filebrowser/filebrowser/issues/3252#issue-2313214520

**Comment by P-Asta** [comment]
> [#3252 (comment)](https://github.com/filebrowser/filebrowser/issues/3252#issue-2313214520)

..?

**Comment by maturbet** [comment]
When using prefix shell, you have to allow it to users.
![image](https://github.com/filebrowser/filebrowser/assets/28108356/704e34de-b6e4-4d0c-9182-d9cc86b6e483)
But this way means allowign all commands after `/bin/bash -c`

**Comment by uxweb** [comment]
@P-Asta I have already sorted this out. The global settings only apply only for users to be created, it will not update already existing users. Go to user management and edit the desired user, then in the commands section add the allowed commands for that user, press save and enjoy.

![image](https://github.com/user-attachments/assets/f59b0767-632a-49b8-a69e-4603ce6e1679)

As for the global settings, I left the Execute on shell field empty
![image](https://github.com/user-attachments/assets/9fdf5467-6c89-468e-954d-f74286d74153)
