### ISSUE TITLE
文件打包下载时目录结构全乱，所有文件都在一块

### ISSUE THREAD

**Issue by capacitor1** [filebrowser/filebrowser#3254]
**Description**
文件打包下载时目录结构全乱，所有文件都在一块
版本：2.29.0
运行系统：Windows10

**Expected behaviour**

下载出来应该目录结构是完整的才对

**What is happening instead?**
操作过程：选中一个文件夹，点下载，tar格式和zip格式都试了，但是下载出来的压缩包里面所有文件夹和文件全都在一起，很乱，多次尝试都这样
 尝试过文件名只有中，英或者混合的情况，看起来不像文件名编码的问题
**Additional context**
filebrowser显示的内容
![1](https://github.com/filebrowser/filebrowser/assets/96713354/4c5e09c0-f7bf-44c3-b9e8-84984658e0b7)

下载到的压缩包里的内容
![image](https://github.com/filebrowser/filebrowser/assets/96713354/6210331c-1491-427a-8c25-02fe1eb93b26)

**How to reproduce?**

**Files**

**Comment by zhangguanzhang** [comment]
我看了下行为是没问题的
例如目录dir1下有三个file 1 2 3，那下载压缩包里根目录就是 1 2 3三个文件。
如果dir1下你再增加一个目录dir2，dir下有456三个文件，那下载dir1的压缩包内就是
```
file1
file2
file3
dir2/file4
dir2/file5
dir2/file6
```

**Comment by Illusionna** [comment]
> **Description** 文件打包下载时目录结构全乱，所有文件都在一块 版本：2.29.0 运行系统：Windows10
> 
> **Expected behaviour**
> 
> 下载出来应该目录结构是完整的才对
> 
> **What is happening instead?** 操作过程：选中一个文件夹，点下载，tar格式和zip格式都试了，但是下载出来的压缩包里面所有文件夹和文件全都在一起，很乱，多次尝试都这样 尝试过文件名只有中，英或者混合的情况，看起来不像文件名编码的问题 **Additional context** filebrowser显示的内容 ![1](https://github.com/filebrowser/filebrowser/assets/96713354/4c5e09c0-f7bf-44c3-b9e8-84984658e0b7)
> 
> 下载到的压缩包里的内容 ![image](https://github.com/filebrowser/filebrowser/assets/96713354/6210331c-1491-427a-8c25-02fe1eb93b26)
> 
> **How to reproduce?**
> 
> **Files**

 兄弟可以看看我的，我设计归档压缩的时候会保留原来的目录结果，不会乱：https://github.com/Illusionna/LocalTransfer
