### ISSUE TITLE
Shared link not copied in Safari

### ISSUE THREAD

**Issue by adpavlov** [filebrowser/filebrowser#3260]
When I create a link to share both copy link buttons not working in Safari, just nothing is happening

<img width="402" alt="image" src="https://github.com/filebrowser/filebrowser/assets/51116816/4ac73678-35e1-4b14-9d92-1a493751cd8c">

**Comment by kloon15** [comment]
duplicate of #3232

**Comment by adpavlov** [comment]
Closed in favor of #3261 and #3232
