### ISSUE TITLE
Working locally but not with domain

### ISSUE THREAD

**Issue by joshk132** [filebrowser/filebrowser#327]
### 3. What are you trying to do?
I am trying to access my files remotely with filemanager using `filemanager.mydomain.com` but it will not work yet it will show the files for `192.168.0.111:80880`

### 4. What did you expect to see?
My files were to show up both locally and using a remote connection.

### 5. What did you see instead (give full error messages and/or log)?
I can see my files locally (using internal IP) but not when I use `filemanager.mydomain.com`
I see the error message `Something really went wrong.` using `filemanager.mydomain.com`

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Not sure, I have installed this before with no issues using domains but it seems something went wrong this time. I have reinstalled and changed my Nginx files with no luck

### Notes:
I can tell the two are linked since account and CSS changes affect both local and domain mapped.

**Comment by hacdias** [comment]
Hey @joshk132 can you show me your configuration? Did you set the 'baseurl'?

**Comment by joshk132** [comment]
I solved it by removing and reinstalling it a few times then rebooting nginx. Either the last install fixed it or the third reboot of nginx solved it.
