### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ehammock** [filebrowser/filebrowser#3272]
**Description**
When I copy a file from one host path location to another host path location on the same server, the web interface returns Error 403 Forbidden

**Expected behaviour**
It copies the file.

I am getting an error 403 Forbidden

**Additional context**
It gives the same error even if it is a file that was created within File Browser.

**How to reproduce?**
Copy a file from one host path to another on the same server.

**Files**
Not applicable. A simple text file will create the problem.

**Comment by ruedigerp** [comment]
Check the permissions of the destination directory
