### ISSUE TITLE
Not finding config on fresh start

### ISSUE THREAD

**Issue by nakinney** [filebrowser/filebrowser#3278]
**Description**
On the very first start of a fresh docker compose of filebrowser, filebrowser will not find the settings.json file.  Instead it will report "No config file used" and start with a default settings.json file. If you then restart  filebrowser it will start up and find the provided settings.json file.

**Expected behaviour**
I expect filebrowser to find the settings.json file on a fresh start. You shouldn't have to do a restart to get the settings to load.

**What is happening instead?**
The default settings.json file is being loaded and since the default isn't using the correct port and address the you won't be able to connect to it.

**Additional context**
Log view on first start:
![fresh_start](https://github.com/filebrowser/filebrowser/assets/42506409/0e60f396-2aa2-442e-9d1a-4ca0a6ef94df)

Log view on restart:
![restart](https://github.com/filebrowser/filebrowser/assets/42506409/24d1c424-a804-43aa-bc50-73e404a5ac2e)

The volumes (as seen in Portainer) look odd. I don't understand the ones in blue. I didn't add those.
![volumes](https://github.com/filebrowser/filebrowser/assets/42506409/3cb21ac9-d269-4a9f-8257-34763305adb6)

**How to reproduce?**
Remove container then start it. May need to prune all unused as well.

**Files**
[filebrowser_compose.zip](https://github.com/user-attachments/files/15520517/filebrowser_compose.zip)

**Comment by mcarame** [comment]
Same strange volumes situation here: 

<img width="965" alt="volumes" src="https://github.com/filebrowser/filebrowser/assets/47557866/d8852af0-6439-43fc-b20f-a96c3c03cd89">
