### ISSUE TITLE
413 error request too large

### ISSUE THREAD

**Issue by joshk132** [filebrowser/filebrowser#328]
I am trying to upload a .iso file to my file server using filemanager.mydomain.com but it gives me a red info box in the bottom right that says 413 error request too large. I have tried accessing it locally but no luck with that either. Rebooted the host system and filemanager. Cleared cache, use incog chrome, check for more error messages (none found).

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Upload file over 100MB

**Comment by hacdias** [comment]
Did you check your server settings? I'm not aware of any problems of this kind.

**Comment by joshk132** [comment]
I am not sure which ones to check.. 

I am running Ubuntu Server 16.04, nginx for web server and webmin so far. I am uploading to a raid 1 made using mdadm. Locally it works fine now (rebooted filemanager) but remote is still giving the `413` error.

**Comment by hacdias** [comment]
Did you check if your nginx server doesn't have a maximum upload size? I never return 413 in File Manager, so it probably is something else returning that.

**Comment by Equim-chan** [comment]
Is your server behind Cloudflare? Cloudflare has a maximum upload size limit.

**Comment by joshk132** [comment]
No not behind anything, it is a local file server that I wanted web based access to remotely.

**Comment by Equim-chan** [comment]
What is your nginx config?

**Comment by andyhuai** [comment]
```
http
    {
      ...
        server_names_hash_bucket_size 512;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 32k;
        client_max_body_size 10g;
     ....
}
```

I've the same problem, but I changed my nginx like this, now everything is OK
@joshk132

**Comment by edgeux** [comment]
i have this problem using the docker image. is there no way to configure the container from the json file to increase the setting?

**Comment by Phyremaster** [comment]
This issue cannot be fixed if you're using the Docker image. The config file isn't where it should be, so you can't mount it, and there's no way to get a shell into the container (which isn't a good solution anyway, as the changes you made would be erased if the image was updated).

**Comment by liutaob** [comment]
3Q  my question was worked out

**Comment by shiikoe** [comment]
`client_max_body_size **8000m**;`

Put that in your reverse proxy server'configration like Nginx. I tested it myself, Problem solved.

**Comment by ivyfae** [comment]
If you can't modify the reverse proxy, change FileBrowser's Chunked Uploads size limit to something smaller.
