### ISSUE TITLE
Copy shared link function not working on IOS 16

### ISSUE THREAD

**Issue by Giorey01** [filebrowser/filebrowser#3289]
**Description**

I'm recently using an IPhone 12 and I noticed that I can correctly make links to share my folders but the button to copy the link does nothing 
**Expected behaviour**

I expected the link to be copied 
**What is happening instead?**

The link is not copied
**Additional context**

I tried it both on safari and brave browser

**How to reproduce?**

Choose a folder and make a link to share it, the copy button will not work 
**Files**

**Comment by kloon15** [comment]
Duplicate of #3232
