### ISSUE TITLE
file browser upload failure

### ISSUE THREAD

**Issue by oliealine** [filebrowser/filebrowser#3291]
**Description**
 I'm trying to upload my files but it's failing

**Expected behaviour**
 that works so I can run my data

**What is happening instead?**
error [object Object] 

**Additional context**
 

**How to reproduce?**

**Files**

**Comment by working-name** [comment]
To where?
Using what browser?
Which version of file browser are you running?
How are you running filebrowser - docker? directly?
If the error message can't be copied ( [object Object] doesn't mean much ), maybe take screenshots?
What do the filebrowser logs tell you?
Have you tried anything to fix it so far?

Just some things you might want to tackle if you want someone to actually try and figure out what may be going wrong.

**Comment by collatdam** [comment]
Most likely its the session timeout.
