### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jungle-boogie** [filebrowser/filebrowser#33]
This crash mean much to you?

goroutine 1 [running]:
flag.init()
/usr/local/go/src/flag/flag.go:840 +0x11a
github.com/spf13/pflag.init()
/home/caddy/go/src/github.com/spf13/pflag/uint8.go:91 +0x59
github.com/spf13/viper.init()
/home/caddy/go/src/github.com/spf13/viper/viper.go:1026 +0x42
github.com/spf13/hugo/create.init()
/home/caddy/go/src/github.com/spf13/hugo/create/content.go:165 +0x42
github.com/spf13/hugo/commands.init()
/home/caddy/go/src/github.com/spf13/hugo/commands/version.go:76 +0x5e
github.com/hacdias/caddy-hugo/utils.init()
/home/caddy/go/src/github.com/hacdias/caddy-hugo/utils/utils.go:208 +0x42
github.com/hacdias/caddy-hugo.init()
/home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:135 +0x4c
github.com/mholt/caddy/config.init()
/tmp/custombuild_5197_315274122/src/github.com/mholt/caddy/config/directives.go:52 +0x4f
main.init()
/tmp/custombuild_5197_315274122/src/github.com/mholt/caddy/main.go:174 +0x47

full log:
http://termbin.com/gpms

Go to http://jungleboogie.me:2021/ and see the error. If you refresh, you'll notice that everything below main.init() changes between refreshes.

also see https://github.com/spf13/hugo/issues/1649

**Comment by moorereason** [comment]
I can't get to the termbin site.  The stack trace for goroutine 1 is the one that's causing the panic.  Everything after that will change depending on what other goroutines are active at the time of the panic.  Ignore the other stuff.

I downloaded Caddy+hugo+search from the Caddy download page and was unable to make it panic with the Caddyfile you posted on the original Hugo issue.  I added a `hugo /path/to/a/hugo/site` directive to the config, and the Hugo integration works fine.  I can see my Hugo site and get to the admin panel.

**Comment by jungle-boogie** [comment]
Hi @moorereason,

Are you using inetd for caddy? I am.

Without search and/or hugo, I get a panic on plain caddy:
http://jungleboogie.me:2022/

Here's the report for plain caddy: https://github.com/mholt/caddy/issues/374

**Comment by hacdias** [comment]
I can't reproduce the error as well and as you said, you still receive the panic without hugo and search, so the problem can't be generated in caddy-hugo, right? O.o

**Comment by mholt** [comment]
Yeah, this looks like something in Caddy or Go itself. I actually suspect a bug in the standard library.

**Comment by hacdias** [comment]
Thanks @mholt!

**Comment by jungle-boogie** [comment]
@hacdias,

Right, the error occurs without hugo or search.

hugo & search: http://jungleboogie.me:2021/
just caddy .76: http://jungleboogie.me:2022/

Thanks!

Hi @mholt,

Will you file the report upstream to go?

**Comment by mholt** [comment]
Let's continue this over in mholt/caddy#374 - I just updated my comments there.
