### ISSUE TITLE
Upload speed for multiple simultaneous files is understated

### ISSUE THREAD

**Issue by therealmelee** [filebrowser/filebrowser#3301]
**Description**
When uploading multiple files, the speed indicated seems to only represent the speed of one of the files. The total transfer speed experienced (by looking at the total amount transferred) is clearly higher - about 5x - which aligns with the 5 simultaneous transfers.

**Expected behaviour**
Transfer speed should show the total transfer speed.

**What is happening instead?**
Transfer speed is 1/5 of actual - probably only showing the speed of a single stream.
![image](https://github.com/filebrowser/filebrowser/assets/56363525/c7bf0414-af7b-41f6-a535-ae51c0e1c3cd)

**How to reproduce?**
Upload multiple files at the same time. Observe the difference between the speed shown at the top, and how the total transferred amount increases.

**Comment by therealmelee** [comment]
Bumping the bug so it is not closed.

**Comment by ccvca** [comment]
A simmilar issue applies to the total uploaded data. It only shows the amount of the currently uploaded files, not the already uploaded ones:

e.g. here around 20% of the files are already uploaded, but only the 40MB of the currently uploaded files are shown:
![grafik](https://github.com/user-attachments/assets/1c55c30b-ada6-40c2-9d75-1e98ec87cc0e)

(Same applies for the percentage)

**Comment by Expello** [comment]
the display is also completely wrong in the latest version...if you upload several files.

it would be great if this could be fixed.
