### ISSUE TITLE
GoLang version bump to v1.22 has broken Win7 / Server 2008 compatibility

### ISSUE THREAD

**Issue by Darthagnon** [filebrowser/filebrowser#3302]
**Description**
[This commit](https://github.com/filebrowser/filebrowser/commit/bbd0abbdfdbb3ddf3326247b7c6d925751dfabcb) bumps Go dependency from v1.21 to v1.22. Does this version bump add any features? It has broken compatibility with a whole generation of OS, as [Go v1.22 (more accurately, v1.21.5+) does not work on Windows 7 / Server 2008](https://github.com/golang/go/issues/64622)

Compatibility with Win7 can be maintained via:
- building with GoLang v1.20.14 (last officially supported version on Win7, [source](https://stackoverflow.com/questions/76994760/go-1-21-windows-compatibility))
- building with GoLang v1.21.4 ([last version confirmed to work on Win7](https://github.com/YouROK/TorrServer/issues/348))
- Win7 clients installing [VxKex](https://github.com/vxiiduu/VxKex/) ([source](https://github.com/golang/go/issues/52188)

**Comment by Darthagnon** [comment]
The last version that will work on Windows 7 / Server 2008 without the VxKex kernel extension is [Filebrowser v2.28](https://github.com/filebrowser/filebrowser/releases/tag/v2.28.0)

**Comment by stunndard** [comment]
try this: https://github.com/stunndard/golangwin7patch
