### ISSUE TITLE
Blackscreen when opening a PDF on Iphone

### ISSUE THREAD

**Issue by Isaac-the-Man** [filebrowser/filebrowser#3317]
**Description**

My pdf file won't load (shows a blackscreen) when I attempt to access it through filebrowser on Iphone. Running the latest version of Filebrowser and running on Safari. Pdf works perfectly fine on PC web browser.

![image](https://github.com/filebrowser/filebrowser/assets/29915393/75dae5e2-ef63-4d58-a73e-65fd6058a2d1)

**Expected behaviour**
Loads and render PDF. 

**What is happening instead?**

Black screen. File not rendering.

**Additional context**

I tried changing chrome into mobile view using the developer tool on my PC, and to my surprise the blackscreen happens too. 

**How to reproduce?**

Access filebrowser on an iphone and open any PDF.

**Files**

**Comment by jniggemann** [comment]
I also have this issue. Because downloading and viewing the pdf works, I assumed it's an ios issue.

**Comment by partialclass** [comment]
Also having the same issue. We are using it for our technicians to have access to our technical doc pdfs in the field and almost all of them have iphones. Is this being looked into?
