### ISSUE TITLE
Propose: Don't store JWT token in cookie.

### ISSUE THREAD

**Issue by Equim-chan** [filebrowser/filebrowser#332]
JWT itself already utilized the `Authorization` header, therefore it is redundant to set it again in the `Cookie` header, not to mention JWT token itself is quite long (see the figure). It's also [not secure](https://en.wikipedia.org/wiki/Cross-site_request_forgery) to use cookie in such manner.
![image](https://user-images.githubusercontent.com/17795845/34925172-9ad45688-f9e2-11e7-881c-77e0aebe0b18.png)

A better place to store the token in frontend is window.localStorage. Although local storage doesn't have the expiration feature like cookie, it can be implemented by storing an `expire` field and checking that manually on load.

**Comment by hacdias** [comment]
Hello @Equim-chan! Would you like to implement that? 😄 Just don't forget that there are some pages that really use the Cookie instead of the `Authorization` header such as download.

**Comment by Equim-chan** [comment]
Sure, but I may try that after I finish my exams, just a few days to go.

**Comment by hacdias** [comment]
Nice! Good luck for them 😄

**Comment by Equim-chan** [comment]
https://github.com/hacdias/filemanager/blob/1f946bd94e807679575812206e62425905434036/http/auth.go#L120-L133

Can we just put the `ID` field to the token and drop other fields of `u` here? Since when the token is validated we only used the `ID` to retrieve.

https://github.com/hacdias/filemanager/blob/1f946bd94e807679575812206e62425905434036/http/auth.go#L192

Now I just wonder if the frontend has used the token to retrieve user data. (I'm not familiar with the frontend code)

**Comment by hacdias** [comment]
The problem is: the front-end uses the user from the token to get all of the information about the user such as their permissions, name, commands and such.

**Comment by Equim-chan** [comment]
Well, that's a bit of an anti-pattern though, since tokens are meant to be used for authorization only.

**Comment by hacdias** [comment]
Hmm... that's not what I read:

> Information Exchange: JSON Web Tokens are a good way of securely transmitting information between parties. Because JWTs can be signed—for example, using public/private key pairs—you can be sure the senders are who they say they are. Additionally, as the signature is calculated using the header and the payload, you can also verify that the content hasn't been tampered with.

[Source](https://jwt.io/introduction/)
