### ISSUE TITLE
I need help with docker and filebrowser

### ISSUE THREAD

**Issue by Rapter001** [filebrowser/filebrowser#3320]
i am using portainer running on a ubuntu server 24.04 i deployed file browser using portainer but i want to use captcha with json auth is there a guide on how to do so or not

**Comment by noah-thor** [comment]
You should be able to append the necessary arguments to the docker command and they will get passed to filebrowser entrypoint accordingly `docker run --name <containerName> -d <imageName> <param1> <param2>`
