### ISSUE TITLE
Docker install help

### ISSUE THREAD

**Issue by monstruwaken** [filebrowser/filebrowser#3330]
I tried to install with this:

docker run \
    -v /path/to/root:/srv \
    -v /path/to/filebrowser.db:/database/filebrowser.db \
    -v /path/to/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -p 8082:80 \
    filebrowser/filebrowser:s6

(Had to change port due to conflict)

Portainer shows it as unhealthy and logs read:

2024/06/23 17:23:24 Using database: /database/filebrowser.db
2024/06/23 17:23:24 open /database/filebrowser.db: is a directory
2024/06/23 17:23:25 Using database: /database/filebrowser.db
2024/06/23 17:23:25 open /database/filebrowser.db: is a directory
2024/06/23 17:23:26 Using database: /database/filebrowser.db
2024/06/23 17:23:26 open /database/filebrowser.db: is a directory

**Comment by pentago** [comment]
make sure that `/path/to/filebrowser.db` and `/path/to/settings.json` exist _BEFORE_ you run container.
