### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by wawanUnic** [filebrowser/filebrowser#3332]
Hello!
![Screenshot 2024-06-24 203410](https://github.com/filebrowser/filebrowser/assets/92972782/8f042afa-d66a-4f15-a73b-511de19a479a)

and

![Screenshot 2024-06-24 203456](https://github.com/filebrowser/filebrowser/assets/92972782/11df3563-14cd-49e9-9f36-286ee7f41ced)

WTF?

**Comment by maturbet** [comment]
Listening on 127.0.0.1 means that only a local request can succeed.
Use folowing to listen on all adresses :
`filebrowser -a 0.0.0.0 -r /home`
