### ISSUE TITLE
Poor mobile support

### ISSUE THREAD

**Issue by gaoyuoppa** [filebrowser/filebrowser#334]
![image](https://user-images.githubusercontent.com/20106653/35141715-e501bc4e-fd36-11e7-9792-4076c39683ba.png)
![image](https://user-images.githubusercontent.com/20106653/35141725-ec490a3e-fd36-11e7-83b8-f54d7e5ea1e2.png)

Poor mobile support

**Comment by hacdias** [comment]
That's weird and it doesn't happen here. Is there a way you can debug the page to get more info? It seems your icons are not showing.

**Comment by iqyiqy** [comment]
I have the same problem.
This is my android browser
https://play.google.com/store/apps/details?id=com.UCMobile.intl

**Comment by Equim-chan** [comment]
I can't reproduce this under Chrome for Android 63.0.3239.111. Maybe it's just fine to update your browser?
