### ISSUE TITLE
[Feature Request] Directory Sizes

### ISSUE THREAD

**Issue by TrimVis** [filebrowser/filebrowser#3345]
**Is your feature request related to a problem? Please describe.**
It would be helpful to show the file sizes of directories. I just setup this project (first of all thanks for that! Great project imo) on my homeserver, and tried being able to see the directory sizes by allowing the du command, but somehow this is not working (its likely I'm doing something wrong here though)

**Describe the solution you'd like**
In the settings an option "show directory sizes" that will show the sizes of directories if enabled.
Due to performance reasons I can understand that this should be an option thats not enabled by default and maybe even add a warning that this can lead to performance issues.

**Describe alternatives you've considered**
Allowing users to use the 'du' command to show the file sizes in the shell.
As mentioned above this didn't work for me.

**Additional context**
New user, so in case something similiar to this is already possible, I would be happy with that too :)

**Comment by 1michaelbrown** [comment]
This issue might give you more insight #1987

**Comment by TrimVis** [comment]
Duplicate :)
