### ISSUE TITLE
shell Command not allowed

### ISSUE THREAD

**Issue by nuowei2543** [filebrowser/filebrowser#3349]
**Description**

When opening the shell in the Filebrowser UI, typing any command simply gives error: "Command not allowed"
**Expected behaviour**

Return the output of the command 

**What is happening instead?**

"Command not allowed" gets printed to the terminal

**Additional context**

image: filebrowser/filebrowser:v2.30.0
k8s version: v1.23.17
![image](https://github.com/filebrowser/filebrowser/assets/118803817/b8fc9e1e-58fb-49e8-a9ed-c3ac0737553e)

![7C82F7D1-2CB1-40C4-920C-6501979964C1](https://github.com/filebrowser/filebrowser/assets/118803817/600b4bdc-5d2a-40db-a02f-e46026eb7973)

![image](https://github.com/filebrowser/filebrowser/assets/118803817/2ddfa112-b4da-4b16-8e07-9f8185ee77d7)

**How to reproduce?**

Login to the UI in the browser, open the shell, and run any Unix/Linux command.
**Files**

**Comment by maturbet** [comment]
Same as #3252

**Comment by xiaohao0576** [comment]
you can use this command to fix it: `filebrowser config set --shell=""`

**Comment by nuowei2543** [comment]
Currently, entering commands does not return a result
![image](https://github.com/filebrowser/filebrowser/assets/118803817/9f466551-3f11-410f-8a12-e46acf17b07a)

checking the logs reveals errors
![image](https://github.com/filebrowser/filebrowser/assets/118803817/a0814099-55e8-4996-baba-a21c0ef15b42)
This was started using the filebrowser binary, not in the Docker container.

**Comment by superzjg** [comment]
Add the commands in user settings.

<img width="716" alt="无标题2" src="https://github.com/user-attachments/assets/d6544658-af51-40ec-818e-28877f751bd9">

**Comment by nuowei2543** [comment]
error still reported
![image](https://github.com/user-attachments/assets/d1540610-c6d7-45a6-9151-fc4fbdb94b68)
![image](https://github.com/user-attachments/assets/b9035594-1b77-4270-8dd3-ad46f80b9ed7)

![image](https://github.com/user-attachments/assets/cdd6fea7-907b-43b9-aa66-b636fafe6544)

**Comment by maturbet** [comment]
I found that options like `-c` in the **shell** section don't seem to work.

**Comment by wiebewillems** [comment]
Also having this issue, having configured the commands via the web user interface (space seperated). Returns "Command not allowed" for any command, even if whitelisted.

**Comment by maturbet** [comment]
"Command not allowed" for any command look like #3331

**Comment by superzjg** [comment]
> error still reported ![image](https://private-user-images.githubusercontent.com/118803817/349396952-d1540610-c6d7-45a6-9151-fc4fbdb94b68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTcyMDgsIm5iZiI6MTcyMTYxNjkwOCwicGF0aCI6Ii8xMTg4MDM4MTcvMzQ5Mzk2OTUyLWQxNTQwNjEwLWM2ZDctNDVhNi05MTUxLWZjNGZiZGI5NGI2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwMjU1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmI0MDdjOTkwNGI2YjA1ZDIyNzgwYjY2MzM3ODIzNGJhYTlkNGYxNjY5MzM4M2ZiMWQyMjZjMDZjZGQ0YjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u5E8WsarZ0XtAgPRQUbeSRXlnFSreoqrJUasT2mWUH4) ![image](https://private-user-images.githubusercontent.com/118803817/349398301-b9035594-1b77-4270-8dd3-ad46f80b9ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTcyMDgsIm5iZiI6MTcyMTYxNjkwOCwicGF0aCI6Ii8xMTg4MDM4MTcvMzQ5Mzk4MzAxLWI5MDM1NTk0LTFiNzctNDI3MC04ZGQzLWFkNDZmODBiOWVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwMjU1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjc4ZTRjNzc1NzZjZGFmYzMyMzI2MTQ2MWM0NmU1MGVmYTk4NGIxNzA0M2M4M2Y2YTZlZTU1ZTI4MzMxMjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d8lxmCmOMhsYDc-4szxAIDGGi4npcuTyAS2CMaIM2Jk)
> 
> ![image](https://private-user-images.githubusercontent.com/118803817/349398211-cdd6fea7-907b-43b9-aa66-b636fafe6544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTcyMDgsIm5iZiI6MTcyMTYxNjkwOCwicGF0aCI6Ii8xMTg4MDM4MTcvMzQ5Mzk4MjExLWNkZDZmZWE3LTkwN2ItNDNiOS1hYTY2LWI2MzZmYWZlNjU0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwMjU1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzVjYjllNjlmMWVlMTc4Nzg0ZGFlZjA0Mzg2OTJiNjY0YzA5ZGM5NWUxMWNkNzlkNTFkNjU3NGQxMTIyMDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o2tr3j1p93DUifdFHNoaiKltZBc3OYc4XyHcPGlqgyQ)

我又测试了一下，从v2.28升级到v2.30，不更改任何设置，命令可以执行，一旦通过设置功能更改了某项设置后，命令就不能执行了，即便使用同一个 filebrowser.db 降级到v2.28也不行，必须删除 filebrowser.db 并重建才会恢复。

**Comment by n-i-x** [comment]
I've done a bit of testing on this issue. The issue seems to crop up as soon as any of the Global Settings are modified. My guess is that saving the Global Settings is modifying something in the database preventing commands from running.

To reproduce on Linux:

- Start File Browser with an empty database
- Login as admin
- Enter settings and under User Management edit the admin user
- Add uname to the commands and save
- Go back to files and click <> to open the shell
- Enter uname... it works
- Go back into settings and click Global Settings
- Set the theme to Dark and hit update
- Go back to files and click <> to open the shell
- Enter uname... command not allowed

**Comment by n-i-x** [comment]
I diff'd the configs in the database and discovered that the Global Settings is changing the value of settings['shell'] from [] to [""]. This prevents the shell from working.

**Comment by maxlivi** [comment]
It is possible to fix with boltbrowser

Worked for me

**Comment by n-i-x** [comment]
It appears the issue is here:

https://github.com/filebrowser/filebrowser/blob/master/runner/parser.go#L29

The command[0] becomes the value of the Shell setting. By default, when saving from the UI, this will be "".

The command is then checked against a list of allowed commands in:

https://github.com/filebrowser/filebrowser/blob/master/users/users.go#L109-L121

I was able to make this work without code changes by setting the shell to `/usr/bin/bash` and then adding `/usr/bin/bash` to the list of allowed commands. This is obviously bad since it basically allows any command to be authorized.

The fix would be to set s.Shell to nil or []string{} if the value of shell in the settings is "" or edit ParseCommand to be something like:

```
if len(s.Shell) == 0 || s.Shell[0] == "" {
```

I'll see if I can compile this project and submit a PR

**Comment by ramsamba** [comment]
> you can use this command to fix it: `filebrowser config set --shell=""`

i don't get it why forum'ers don't get this advice.
i am running filebrowser as truenas app that is dockerized, and all i had to do was to NOT specify 'bash -c' and leave empty the following field in filebrowser's Settings > tab Global Settings > section Execute on shell
in other words, leave it blank, and if you are using Bash, enter string 'bash' in to the user's allowed commands

it worked for me perfectly, thanks XioaHao, although the BusyBox commands were lacking for me to do what i wanted to achieve
