### ISSUE TITLE
"New folder" button is disabled when copying or moving files

### ISSUE THREAD

**Issue by nuowei2543** [filebrowser/filebrowser#3350]
**Description**

"New folder" button is disabled when copying or moving files
**Expected behaviour**

**What is happening instead?**

**Additional context**

image: filebrowser/filebrowser:v2.30.0

https://github.com/filebrowser/filebrowser/assets/118803817/776d0e0e-90cc-4953-bbcc-ff87b6a0932e

**How to reproduce?**

**Files**

**Comment by 1michaelbrown** [comment]
I am on the stable release currently. So I haven't tested this. But have you checked log files? and tried using your browsers inspect tool?

**Comment by nuowei2543** [comment]
![image](https://github.com/user-attachments/assets/48f87235-53a4-4662-9fa9-fd4f780183ab)
there has some errors, click "New folder" button when copying files
