### ISSUE TITLE
[Feature Request] File Tags

### ISSUE THREAD

**Issue by tarumes** [filebrowser/filebrowser#3351]
**Is your feature request related to a problem? Please describe.**
better file search

**Describe the solution you'd like**
tagging for files, to search more efficiently
let me attach multiple custom search tags to a file like "cat", "animal", ....

**Describe alternatives you've considered**
filenames and folders and its limited clunky

**Comment by 1michaelbrown** [comment]
I am just going to say it be cool to have something like [zincsearch](https://github.com/zincsearch/zincsearch?tab=readme-ov-file) It is written in `go` so it might be more compatible with this project. Or even [meilisearch](https://github.com/meilisearch/meilisearch?tab=readme-ov-file)

**Comment by tarumes** [comment]
bump
