### ISSUE TITLE
custom_nodes无法上传文件夹

### ISSUE THREAD

**Issue by jonysuu** [filebrowser/filebrowser#3352]
想要给custom_nodes上传一个comfyui-manager，但是无法上传成功

**Comment by 1michaelbrown** [comment]
If this is translated right "Trying to upload a comfyui-manager for custom_nodes, but it won't upload successfully!" 

Is this the [ project](https://github.com/ltdrdata/ComfyUI-Manager) you are referring to?

Where are you trying to upload?

Are you trying to change the ui of filebrowser?
