### ISSUE TITLE
Forbidden Upload with Python 'open' command

### ISSUE THREAD

**Issue by neelz040** [filebrowser/filebrowser#3359]
**Description**
I am trying to upload a python script that contains an ```open(f"{filepath}", "w")``` command which throws me a 403 Forbidden error. Excluding this line will result in an upload.

**Expected behaviour**
File to upload/save

**What is happening instead?**
403 Forbidden error

**Additional context**

**How to reproduce?**
Upload python file (test.py) with this content
```py
file = open("test.json", "w", encoding="utf-8")
file.write("Hello Filebrowser")
file.close()
```

**Comment by neelz040** [comment]
workaround: 

```py
openn = open
file = openn("test.json", "w", encoding="utf-8")
file.write("Hello Filebrowser")
file.close()
```

**Comment by gingerbeardman** [comment]
Try downgrading filebrowser to 2.23.0
