### ISSUE TITLE
Customization shows inconsistent behaviour

### ISSUE THREAD

**Issue by berlinstold** [filebrowser/filebrowser#3365]
**Description**
I am using Filebrowser on Unraid via a Docker Container. The network is running on bridge mode and the container is open to the public via a Cloudflared Tunnel (subdomain.example.com). Everything is working fine and as expected: sharing works, permissions work, performance is great. Now I wanted to customize the experience and installed a `custom.css`, as well as icons and a `logo.svg`. This is how my file structure looks like:

![Bild_2024-07-18_140531976](https://github.com/user-attachments/assets/2f533af7-8aac-4b95-8b62-ac5fa96c1935)
![Bild_2024-07-18_140736349](https://github.com/user-attachments/assets/d593fba0-57cd-4f35-ab14-1ec155243ac6)
![Bild_2024-07-18_140826244](https://github.com/user-attachments/assets/e6de0abf-fdfb-48a8-be07-f3ad189809cd)

This is how my paths are configured:
![Bild_2024-07-18_141001495](https://github.com/user-attachments/assets/42571229-561b-4cb4-89b3-0722e6b7f530)

And this is my branding directory path:
![Bild_2024-07-18_141224388](https://github.com/user-attachments/assets/3b7cbbdc-21d2-440e-be73-0ea1fc6e68b5)

**Expected behaviour**
- the `custom.css` is working properly
- my favicon should be in the browser tab plus a bigger version when sharing on WhatsApp or Telegram.
- my logo should be visible on the start page and in the top left corner once logged in

**What is happening instead?**
- the `custom.css` works fine! 
- the favicon is inconstistent throughout different browsers & apps
`Opera` ![Bild_2024-07-18_141753015](https://github.com/user-attachments/assets/951c1ecc-cdfd-4227-8a12-aece2e674712)
`Microsoft Edge` ![Bild_2024-07-18_141955930](https://github.com/user-attachments/assets/423979b5-abb0-4e8b-ae0c-8aab6541fcdf)
`Brave` ![Bild_2024-07-18_142120419](https://github.com/user-attachments/assets/ffd9e59e-35bb-4336-9fe8-56ddbd8d6f82)
`Google Chrome (Desktop)` ![Bild_2024-07-18_142239658](https://github.com/user-attachments/assets/8134b940-663a-4b80-b502-0c2f90659f1a)
`Google Chrome (Mobile)` ![Screenshot_20240718-142656](https://github.com/user-attachments/assets/2221de1a-96a8-4944-9383-d2342e5b8bb8)
`WhatsApp` ![Screenshot_20240718-142306~2](https://github.com/user-attachments/assets/a4e4decc-74ac-4146-95cc-790ca3a37d72)

- my logo doesn't change at all. It stays the default in any browser, whatever I do.
![Bild_2024-07-18_143121943](https://github.com/user-attachments/assets/69f4d558-f791-4abe-b6ad-985b323e72a9)

**Additional context**
I've tried several different branding directory paths including:
`/db/branding` `/branding` `.\branding` & `.\db\branding`
but it doesn't seem to make any difference whatsoever, which makes me wonder if it's working at all.

**How to reproduce?**

- Whithin Unraid: set up a Docker Container of Filebrowser, set it to bridge mode & add a port (eg.: 8082). (configure the paths as shown above)
- Set up the Unraid-Cloudflared-Tunnel container as well and configure Cloudflare as shown here: https://www.youtube.com/watch?v=h5fAcE70xbQ
- within the `/appdata` folder make `/branding` , `/branding/img` & `/branding/img/icons` directories. Place the `custom.css`, `logo.svg` & various favicon files inside those as shown above
- restart the container, clear cache in your webbrowser

**Comment by kpg-anon** [comment]
I'm experiencing similar issues. My logo and custom.css are being applied but not the favicon. 
![Screenshot 2024-07-29 194606](https://github.com/user-attachments/assets/141c18c0-fd01-471c-b823-c729c4027a1b)

**Comment by ghost** [comment]
this is still an issue, custom branding does not work properly

**Comment by zohfur** [comment]
+1, I am connecting straight to my docker container without any kind of cookies or site data cached and I cannot for the life of me get any branding or custom CSS to work.

**Comment by WinnerWind** [comment]
+1. I too set the favicon.ico but it shows no response. I also cannot figure out how to do customCSS because there is no style sheet for me to refer to.

**Comment by berlinstold** [comment]
Interestingly enough, the issue resolved itself. But it took about 3 weeks until everything finally changed. I don't understand how that works, but it does now. All my customizations are consistent, too.

**Comment by WinnerWind** [comment]
Thats brilliant! I wonder why the website doesn't react to me changing the favicon. Weird stuff.
