### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ghaseminya** [filebrowser/filebrowser#3367]
**Description**
Hi,
When we run the program, the program runs correctly and the web panel is accessible
However, other commands that must be executed in the command line give a timeout error.
I test this on linux , windows from version 2.30.0(current version) til version 2.13.0
![image](https://github.com/user-attachments/assets/cf3f2410-5529-4b0a-b6bf-d84399adeba4)

**Comment by StefanBrand** [comment]
For me it was this problem: https://github.com/filebrowser/filebrowser/issues/2211#issuecomment-1304887615

Only one instance can access the database at once. I changed the deployment strategy to `Recreate`:


```diff
   strategy:
-    rollingUpdate:
-      maxUnavailable: 0
-    type: RollingUpdate
+    type: Recreate
```
