### ISSUE TITLE
Contributing - can't properly build frontend project

### ISSUE THREAD

**Issue by pam-param-pam** [filebrowser/filebrowser#3370]
Hi,
i was experimenting & having fun with this project for quite a while in development. Today i wanted to build it and run in production. I followed these instructions:
# From the root of the repo, go to frontend/
cd frontend
# Install the dependencies
npm install
# Build the frontend
npm run build

All commands worked, i then tried to locally run the built project using vite preview, again succesfull but when i went to browser nothing worked :(

![image](https://github.com/user-attachments/assets/d1cb8adb-b649-4af0-9d51-f3b37c48fc98)
website is stuck on loading forever. This is the network tab
![image](https://github.com/user-attachments/assets/43292d1f-00e1-43db-ae0b-16d7881e1338)
strangely enough main.js request is hiting 404
![image](https://github.com/user-attachments/assets/532ff444-0c6e-4dd3-b64e-2ebb99e91fab)
![image](https://github.com/user-attachments/assets/666a0596-a15b-45c5-88ce-a51b7b929ae0)
![image](https://github.com/user-attachments/assets/f2b9318b-7427-45cf-8e48-966bd7ef6d28)
and some requests have corrupted urls. I could guess its due to wrongly replacing these constants during build proccess?

I checked twice on a fresh project, which wasnt modified by me, to make sure it's not me that's causing these problems.

Im new to frontend development and it's enviroment and would really use some help. I would be extremely grateful for any help or nudge in the right direction.

edit:
those are the warnings during npm run build on a fresh project:
<script src="[{[ .ReCaptchaHost ]}]/recaptcha/api.js?render=explicit"> in "/public/index.html" can't be bundled without type="module" attribute

[{[ .StaticURL ]}]/custom.css doesn't exist at build time, it will remain unchanged to be resolved at runtime

**Comment by dormant-user** [comment]
I ran into the exact same problem and it was missing LD flags in my case
Are you using `make` commands to build?

**Comment by pam-param-pam** [comment]
@dormant-user im sorry im new to frontend. What do you mean by 'make' commands to build?
I use ```npm run build```
from 
```
"scripts": {
    .....
    "build": "vite build",
   ....
  },
  ```
  
  and what do you mean by LD flags?

**Comment by dormant-user** [comment]
@pam-param-pam LDflags are used to set version information in go lang. You need both backend and frontend built in order to make the executable work as it should. Frontend should be built first, so the backend build can reference the static files.
Refer to the [Makefile](https://github.com/filebrowser/filebrowser/blob/master/Makefile)
Instead of using `npm run build` try using `make build` command - this will build both the frontend and backend compoents.
If you want to build ONLY the frontend, try using `make build-frontend`

**Comment by pam-param-pam** [comment]
Oh, that makes sense now. It works now, thanks!
