### ISSUE TITLE
File listing items cannot be middle clicked to open in a new tab

### ISSUE THREAD

**Issue by williewillus** [filebrowser/filebrowser#3374]
**Description**

As the title.

**Expected behaviour**

Middle click an item in the file list view. Expected to pop a new tab with the file.

**What is happening instead?**

Nothing.

**Additional context**
Probably because they're represented as non-semantic `<div>` tags instead of proper links `<a>` tags.

**Comment by williewillus** [comment]
Still an issue, and stale is still [not the right way to treat your users](https://fvsch.com/stale-bots).

**Comment by williewillus** [comment]
Still an issue, and stale is still [not the right way to treat your users](https://fvsch.com/stale-bots).

**Comment by williewillus** [comment]
Still an issue, and stale is still [not the right way to treat your users](https://fvsch.com/stale-bots).

**Comment by williewillus** [comment]
Still an issue, and stale is still [not the right way to treat your users](https://fvsch.com/stale-bots).

**Comment by gtsteffaniak** [comment]
consider trying https://github.com/gtsteffaniak/filebrowser which has this feature.

**Comment by williewillus** [comment]
thanks, looks like a nice fork
