### ISSUE TITLE
(feat): File Encryption

### ISSUE THREAD

**Issue by wintkhantlin** [filebrowser/filebrowser#3377]
I am using external hard drive on my raspberry pi and I want to encryption some files because external hard drive can be stolen easily. 
 
**Describe the solution you'd like**
Encrypt file with password

**Comment by dormant-user** [comment]
> because external hard drive can be stolen easily

If a physical hard drive is at risk of theft, then you might consider encrypting your whole drive and have a boot process that can decrypt
`filebrowser` is protected by the auth mechanism you choose, so I don't think encrypting files is a solution for the problem
