### ISSUE TITLE
Can WebDAV protocol be integrated? I am currently running filebrowser on OPENWRT and would like to use the WebDAV protocol to manage files or view videos and audios.

### ISSUE THREAD

**Issue by mtjo** [filebrowser/filebrowser#3379]
Will  [WebDAV](http://www.webdav.org/) protocol be integrated in the future? I am currently running filebrowser on OPENWRT and want to use the WebDAV protocol to manage files or view videos and audios.

**Comment by xd003** [comment]
Undeniably, this would be a great option to have. Unfortunately, too many people have requested this feature in multiple issues since many years but nothing ever came out of it. Not sure why noone ever takes it up
