### ISSUE TITLE
Coinhive captcha?

### ISSUE THREAD

**Issue by Equim-chan** [filebrowser/filebrowser#338]
Hello, I plan to add an additional captcha feature based on [coinhive](https://coinhive.com/documentation/captcha). This is not meant to replace reCaptcha but provide another choice.

It should work like reCaptcha, and can be an alternative for reCaptcha. (reCaptcha is blocked in my country.)

However, since coinhive is a bit controversial so I'd like to ask for your opinion on it.

**Comment by hacdias** [comment]
Does coinhive captcha mines crypto??

**Comment by Equim-chan** [comment]
Yes, that's way it works.

**Comment by hacdias** [comment]
I personally don't think it is a good idea. Perhaps you can find another alternative to reCaptcha which does not eat the CPU/GPU of your users.

**Comment by Equim-chan** [comment]
Okay.
