### ISSUE TITLE
[Feature]:  ability to upload multiple files on android

### ISSUE THREAD

**Issue by balub** [filebrowser/filebrowser#3393]
**Is your feature request related to a problem? Please describe.**

When I open the filebrowser in any browser on android, I can only upload one file at a time and am not able to select multiple files and bulk upload them.

**Describe the solution you'd like**

Ability to select multiple files and bulk upload them.

**Describe alternatives you've considered**

Uploading multiple files individually.

**Additional context**

**Comment by rehack** [comment]
same issuse

**Comment by Gopal-001** [comment]
tried it on my android phone I was able to upload multiple images, is there something I'm missing ?
