### ISSUE TITLE
Caddy throws when using hugo

### ISSUE THREAD

**Issue by matthewp** [filebrowser/filebrowser#34]
Using 0.8.

With this config:

```
http://localhost:8888 {
  root public
  hugo {
    args "--theme=hyde"
  }
}

```

I get this error:

```
Activating privacy features... done.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2dfe21]

goroutine 1 [running]:
github.com/hacdias/caddy-hugo/utils.Run(0x208e8d2c0)
    /home/caddy/go/src/github.com/hacdias/caddy-hugo/utils/utils.go:178 +0x2b1
github.com/hacdias/caddy-hugo.Setup(0x208eea100, 0x0, 0x0, 0x0)
    /home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:26 +0x7d
github.com/mholt/caddy/caddy.loadConfigs(0x89c510, 0x9, 0x2208e4a2a0, 0x208f79050, 0x0, 0x0, 0x0, 0x0, 0x0)
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/config.go:162 +0x1a8a
github.com/mholt/caddy/caddy.Start(0x2208e4bd50, 0x208f79020, 0x0, 0x0)
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/caddy.go:138 +0x2c3
main.main()
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/main.go:99 +0x5fe

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
github.com/mholt/caddy/caddy.func·012()
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap_posix.go:19 +0x2d9
created by github.com/mholt/caddy/caddy.trapSignalsPosix
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap_posix.go:72 +0x25

goroutine 8 [chan receive]:
github.com/mholt/caddy/caddy.func·010()
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap.go:31 +0x110
created by github.com/mholt/caddy/caddy.trapSignalsCrossPlatform
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap.go:41 +0x25

goroutine 10 [select]:
github.com/mholt/caddy/caddy/letsencrypt.maintainAssets(0x208ee71e0, 0x1, 0x1, 0x0)
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/letsencrypt/maintain.go:34 +0x7cd
created by github.com/mholt/caddy/caddy/letsencrypt.Activate
    /tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/letsencrypt/letsencrypt.go:146 +0x113a

```

Same thing happens with no args.

**Comment by hacdias** [comment]
Hi @matthewp!

Thanks for reporting this. Can you run the code from source? If so, try running caddy with caddy-hugo, removing this line: https://github.com/hacdias/caddy-hugo/blob/master/utils/utils.go#L176.

**Comment by hacdias** [comment]
Hi @matthewp!

Thanks for reporting this, but this is strange. The binary available at caddyserver.com gives that error, but running from source, I get no errors. So I can't reproduce the error.

@mholt, what do you think about it?

**Comment by hacdias** [comment]
@matthewp @mholt I checked and the problem is NOT in buildsrv, neither in caddy-hugo. I builded caddy + hugo locally using caddydev and buildsrv and I get no errors with both of them. But I get those same errors when downloading from caddyserver.com.

**Comment by mholt** [comment]
K, we'll look at this today, Henrique, when both you and I are online and the download page isn't very busy. :smile:

**Comment by jdaiv** [comment]
Hi there! I ran from source using caddydev and received the same error. As a workaround I changed line 179 of `utils/utils.go` from:

```
commands.HugoCmd.Run(commands.HugoCmd, make([]string, 0))
```

to

```
commands.HugoCmd.RunE(commands.HugoCmd, make([]string, 0))
```

I'm not sure how to test this change properly, but I can edit pages and publish changes now!

**Comment by hacdias** [comment]
Hi @jdaivaliotis 

Thanks for telling us your workaround. Here, I just **can´t** reproduce the error. The difference between `Run` and `RunE` is that the last one returns an error. Can you change it to `err := commands.HugoCmd.RunE(nil, nil)` and check if there is an error?.

**Comment by hacdias** [comment]
This is getting even more strange. Now I also get the error with caddydev. -_- And using RunE I don't get any error.

I think @spf13 should take a look on this.

**Comment by jdaiv** [comment]
`commands.HugoCmd.RunE(nil, nil)` runs with no error! 

As far as I can see in the actual [hugo source](https://godoc.org/github.com/spf13/hugo/commands#pkg-variables), it doesn't look like `HugoCmd.Run` is implemented?

Edit: I found a commit that lines up with the start of this issue: https://github.com/spf13/hugo/commit/3f0f7eed68f44486c1e053bbce25c46c1d52a12f

Run was replaced with RunE at this point!

**Comment by hacdias** [comment]
@jdaivaliotis OMFG. That's the problem. But they used to have!!! So... I think the problem is solved. Thank you, a lot!

@mholt I hope you can update the repo's as soon as possible.

**Comment by jdaiv** [comment]
@hacdias no problems! It was fun to dig through and fix.

**Comment by hacdias** [comment]
Eheh
