### ISSUE TITLE
Remove Failed/Partial Uploads

### ISSUE THREAD

**Issue by fernverde001** [filebrowser/filebrowser#3400]
**Description**
Automatically remove failed/partial uploads.

**Expected behaviour**
Failed/partial uploads not to show up on system.

**What is happening instead?**
File is created with partial size. 

**Additional context**
Either all or no upload. Do not want to see partial files.

**How to reproduce?**
Upload and either loose connection or reload the page. The upload will get cancelled but there will be a file created.

**Files**
n/a

**Comment by DerFnoeh** [comment]
I have the same issue.
Please reconsider whether this is actually "stale". 

Or has this already been fixed?
