### ISSUE TITLE
Improve Consistency in Authentication

### ISSUE THREAD

**Issue by IGLOU-EU** [filebrowser/filebrowser#3401]
hi there !

**Description**
There seems to be an inconsistency in the authentication mechanisms used across different API endpoints, which can lead to problems when trying to open files in a new tab, or when working through a proxy. For example:
- `/api/raw/*` uses an `auth` variable in the URL.
- `/api/resources/*` appears to rely on the `X-Auth` header.
  
However, an `auth` cookie containing the JWT is also available. Using this cookie when present could provide a more consistent approach. Additionally, using a standardized header like `Authorization: Bearer [TOKEN]` might be a cleaner and more secure solution. What do you think?

**Expected behaviour**
Consistent and secure authentication across all API endpoints, ideally leveraging the `auth` cookie or the `Authorization` header to maintain consistency and security.

**What is happening instead?**
Inconsistent authentication methods are being used, which can cause issues when trying to open files in a new tab or when passing requests through a proxy.

**Additional context**
This inconsistency could potentially lead to security issues or unpredictable behavior in certain scenarios, especially in more complex setups.

**How to reproduce?**
1. Try accessing a file through `/api/raw/*` and `/api/resources/*` using different authentication methods.
2. Attempt to open a file in a new tab or pass the request through a proxy.
3. Observe the inconsistencies in how authentication is handled.

**Files**
N/A

**Comment by IGLOU-EU** [comment]
Bad bot ! Don't close it !
I can make a PR, but I need to know if you are interested.

**Comment by IGLOU-EU** [comment]
@o1egl any chance to talk about ?

**Comment by gtsteffaniak** [comment]
@IGLOU-EU you could try https://github.com/gtsteffaniak/filebrowser which has a jwt auth check in this order:

1. Uses bearer token if present
2. Ueses Cookie if present
3. Uses "auth" parameter if in url
