### ISSUE TITLE
curl: (22) The requested URL returned error: 403

### ISSUE THREAD

**Issue by Zero3Dash** [filebrowser/filebrowser#3404]
**Description**
Attempting to install file browser on RPI4, with Debian 12 ARM64

**Expected behaviour**
Install the software, but download fails

**What is happening instead?**
jellyfin@jellyfin:~ $ curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
Downloading File Browser for linux/arm64...
curl: (22) The requested URL returned error: 403
https://github.com/filebrowser/filebrowser/releases/download//linux-arm64-filebrowser.tar.gz
curl: (22) The requested URL returned error: 404
Aborted, error 22 in command: ${net_getter} "$filemanager_url" > "$PREFIX/tmp/$filemanager_file"

**Additional context**
New installation

jellyfin@jellyfin:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
jellyfin@jellyfin:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
jellyfin@jellyfin:~ $

**How to reproduce?**
New installation. I can repeat the issue by running the same line

**Files**
N/A

**Comment by alanmilinovic** [comment]
Same issue on my side as well.

**Comment by Zero3Dash** [comment]
This works, the curl request same broken
wget -qO- https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
