### ISSUE TITLE
Modify or customizable share address

### ISSUE THREAD

**Issue by Wallemuse** [filebrowser/filebrowser#3405]
sometime needs to same or fixed sharing address for users or customers.
When a file is unshared and then re-shared, it gets a different sharing address , modify to the old address is difficult.
If can modify or customizable sharing address then our users or customers they don't need modify the sharing address that was shared with them at the beginning.

**Comment by MotazHakim** [comment]
+1

also the ability to not use that share address and use a direct link instead !
