### ISSUE TITLE
Fail to make archive with filenames that are too long

### ISSUE THREAD

**Issue by Equim-chan** [filebrowser/filebrowser#341]
In the current version, archives are handled by GET, which makes it unable to pass multiple files that have long filenames combined together, since there's a limit for the length of URL.

https://github.com/hacdias/filemanager/blob/30efa23a8567771b089e835ee7d153ebabc577a1/http/download.go#L26

A possible fix can be done by changing the API to PUT/POST. How do you think?

**Comment by hacdias** [comment]
Yeah, for me, go for it 😄 Thanks for all the PRs you've been making!!

**Comment by Equim-chan** [comment]
You're welcome! It's exactly because this tool is so cool that I just want to make it cooler. :smile:

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
