### ISSUE TITLE
Android/iOS app 

### ISSUE THREAD

**Issue by lucad87** [filebrowser/filebrowser#3410]
**Is your feature request related to a problem? Please describe.**
I use FileBrowser to manage files in my homelab, sharing it with my friends. What is missing is a mobile app for Android and iOS. I tried to make my own app for Android using my file browser instance as a WebView Android app but the UX is not great. I managed to let it work also to share files directly with the app integrating FileBrowser APIs to upload files shared with but it is still a bit "meh"..

**Describe the solution you'd like**
I think it should be a good starting point to make the application a PWA, so when file browser website is opened, it is asked to the user to install it in its device.

**Describe alternatives you've considered**
Create a native application for Android and iOS. For Android consider the WebView as a cheap solution.

**Additional context**
It should awesome to have a full working mobile app, with the possibility to share files from the device directly to the file browser app in order to push these files without opening the app and doing it from the UI.

**Comment by alexjoeyyong** [comment]
I second this. I upload files frequently from my phone, and if the phone screen locks, if the file is in the middle of uploading, only part of it gets uploaded.  Or if I go to another browser or app on my phone, the tab will time out after awhile (memory limitation in Android I think?) and the upload if it isn't finished will be broken. 

An app could get around this.

**Comment by Shurov** [comment]
Upping the issue. Seconding (thirding? :D) the app!

**Comment by Crescendo-BLYAT** [comment]
I necro this, please build the binary for Android as well.

https://www.reddit.com/r/koreader/comments/1pur3qv/repurpose_old_phone_as_ereader/
