### ISSUE TITLE
Search does not find my files in deep directory tree

### ISSUE THREAD

**Issue by feklee** [filebrowser/filebrowser#3414]
**Description**
I want to find files, here `index.html`.

**Expected behaviour**
The search should show all matching files.

**What is happening instead?**
After showing the rotating search animation, the search simply shows: *Press enter to search...*

**Additional context**

`filebrowser` is running on a Linux x64 machine.

I wonder if there is an option to turn on verbose logging to see what's going on. In the regular output of `filebrowser`, I don't see anything relevant to the problem.

**How to reproduce?**
Please see my screen recording: [2024-08-21+08_search_issue][1]

On my system I go into the directory `Drafts`, then do a search for `index.html`. It gives me two results: `./web_site/index.html` and `./Emacs/.emacs.d/quelpa/melpa/html/index.html`. Good!

Then I go to home, i.e. one directory up. Now, if I do a search, then there is no result.

[1]: https://github.com/user-attachments/assets/30a3de77-9af4-4b87-82b5-9f7febff1846

**Comment by gtsteffaniak** [comment]
check out https://github.com/gtsteffaniak/filebrowser for an improved search experience.

**Comment by feklee** [comment]
Will check it out, thank you!
