### ISSUE TITLE
You can't upload a file with the same name for replacement

### ISSUE THREAD

**Issue by caixin1218** [filebrowser/filebrowser#3419]
**Description**

**Expected behaviour**

**What is happening instead?**

**Additional context**

**How to reproduce?**

**Files**

**Comment by caixin1218** [comment]
![IMG_2113](https://github.com/user-attachments/assets/5a865f74-af9f-4090-bc02-d439e9b4b214)

**Comment by caixin1218** [comment]
This window appears in too short a time to choose

**Comment by caixin1218** [comment]
Uploading ScreenRecording_08-25-2024 21-58-28_1.mov…

**Comment by caixin1218** [comment]
https://github.com/user-attachments/assets/63f51aed-0612-4dc7-97de-ec1ab75199d2

**Comment by LazyJoshua** [comment]
I encountered the same problem, the dialog disappear immediately.

**Comment by Cpn-Neemo** [comment]
Same issue here dialogbox shows for a split second and closes. Nothing showing in logs to help diagnose
