### ISSUE TITLE
Consider moving to its own organisation

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#342]
Let's consider moving this repository to its own organisation, where we can separate better the front-end from the back-end and, eventually, add more contributors 😄

**Comment by Equim-chan** [comment]
Wow! I was _just_ about to propose this!! Yeah just now when I opened the issue page! :smile:

I'm making more changes at the moment, but I can hold on until the organisation is possibly established.

There will be a few things to do if an organisation is to be established:
* [ ] Change import paths in Go source files
* [ ] Update documents for all `go get` cases
* [ ] Migrate the project's main page to its new home
* [ ] Re-submit Caddy plugin

**Comment by hacdias** [comment]
Hello @Equim-chan, so: you can keep doing your changes and this will be moved later. There are still things to settle such as CI flow and such because I'm thinking about splitting this main package into some smaller ones 😄 

Also, we'd have to choose a name for the organisation since `filemanager` is not available.

**Comment by Equim-chan** [comment]
Most of my changes are trivial, so I don't prefer them to be in one single PR, nor merged into one single commit. So I think I'd wait.

**Comment by hacdias** [comment]
Any suggestion for the name?

**Comment by Equim-chan** [comment]
I'm also thinking of it at the moment...

**Comment by Equim-chan** [comment]
If we adopt a good organisation name, do we need to change the project title as well?

**Comment by Equim-chan** [comment]
* **file-manager**? _simply adding a bar_
* **filemand**? _file manager daemon, sounds classic_
* **easyfile**? _clear but not somewhat off-topic_
* **efile**? _short but not clear_
* **teamfile**? _a bit random_
* **fileer**? _almost meaningless, but short_
* **filebrowser**? _this matches the original name more_
* **gophiles**? _gopher and files, I like it_
* **gophila**? _a more proper name for an organisation, go with phila (love)_
* **gofile**? _neat and clear name too_

I'm not really good at giving names though. :smile:

**Comment by hacdias** [comment]
I vote on `file-manager` or `filebrowser`. Don't vote for `gophiles` because the front-end could be easily (I think) reused to other back-ends (like IPFS, which is one of my goals).

**Comment by arteta22000** [comment]
I vote for filebrowser

**Comment by hacdias** [comment]
Vote here, please #343

**Comment by hacdias** [comment]
Ping @Equim-chan @arteta22000

**Comment by Equim-chan** [comment]
May I ask for access permissions on the repos? I should be able to assign some issues.

**Comment by hacdias** [comment]
Done @Equim-chan! I'm closing this issue
