### ISSUE TITLE
Automatically create account when using reverse proxy auth

### ISSUE THREAD

**Issue by Mubelotix** [filebrowser/filebrowser#3420]
**Is your feature request related to a problem? Please describe.**

[People are encountering a lot of troubles using the reverse proxy auth](https://github.com/filebrowser/filebrowser/issues/2100) as Filebrowser silently fails to handle usernames not matching any existing user

**Describe the solution you'd like**

Filebrowser should create a new account for these when needed

**Describe alternatives you've considered**

Listing and creating all users manually or automatically. Not good as it must be done periodically anyway

**Comment by Mubelotix** [comment]
FUCK NO

**Comment by Mubelotix** [comment]
Not stale

**Comment by ackphill** [comment]
This is definitely what I need. 👍

**Comment by ackphill** [comment]
Some related issues #3292 #2515

**Comment by Mubelotix** [comment]
Let's not let this one get closed!

**Comment by brezinajn** [comment]
In general proper integration with external auth sources is something filebrowser is currently lacking. +1

**Comment by Mubelotix** [comment]
Shut the fuck up you bot

**Comment by ahobsonsayers** [comment]
🎉
