### ISSUE TITLE
Better Storage Management 

### ISSUE THREAD

**Issue by Samu369** [filebrowser/filebrowser#3428]
**Is your feature request related to a problem? Please describe.**
1. I would like to share my storage space with other people, but I don't want everyone to be able to use as much space as they want, I want to set a limit.
2. I would also like to have a view of the storage space in use with graphs, and a list of the largest folders/files.

**Describe the solution you'd like**
1. In the edit users section, you could add a section to assign an amount of storage space to individual users, which once exceeded will no longer allow them to upload files.
2. You could also create a section in the administrator settings that shows disk usage with graphs (like KDE Filelight)

**Comment by o1egl** [comment]
This feature is out of the scope of this project. You can use other projects that support it.

**Comment by Nooby1** [comment]
Can you not just create seperate filesystems with these storage limits and then allow each user to acess only that filesystem in the user scope setting of filebrowser

**Comment by Samu369** [comment]
> Can you not just create seperate filesystems with these storage limits and then allow each user to acess only that filesystem in the user scope setting of filebrowser

yes, I could do that, but it would be nice and less complicated to be able to do everything from the Filebrowser's user management section
