### ISSUE TITLE
404 Error for all images

### ISSUE THREAD

**Issue by fret423** [filebrowser/filebrowser#3429]
**Description**
Setup Filebrowser for the first time. None of the images load, including the assets such as the Filebrowser logo

**Expected behaviour**
All images should show

**What is happening instead?**
It just shows an image as if it is a broken link

**Additional context**
Have installed Filebrowser on a VPS for the first time. I have a domain, and I want to serve it at domain/filebrowser. This is using the docker install and nginx reverse proxy. 

It is installed and reaches the login page, and I am able to login successfully too, but it is not showing the images as it gives a 404 error for all images in the Chrome Devtools.

**Files**
### /opt/filebrowser/config/settings.json:
```
{
  "port": 80,
  "baseURL": "/filebrowser",
  "address": "0.0.0.0",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```

### relevant part of the /etc/nginx/sites-availables/[domain]
    location /filebrowser/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Ensure correct handling of sub-paths
    proxy_set_header X-Script-Name /filebrowser;
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header X-Forwarded-Host $host;
    
    sub_filter 'href="/' 'href="/filebrowser/';
    sub_filter 'src="/' 'src="/filebrowser/';
    sub_filter_once off;
    }

### docker command
```
sudo docker run -d \
  --name=filebrowser \
  --restart unless-stopped \
  -p 8080:80 \
  -e TZ=Asia/Kolkata \
  -e PUID=$(id -u) \
  -e PGID=$(id -g) \
  -v /var/www/html/dam:/srv \
  -v /opt/filebrowser/database/filebrowser.db:/database/filebrowser.db \
  -v /opt/filebrowser/config/settings.json:/config/settings.json \
  filebrowser/filebrowser:s6
```

### Example error from Chrome DevTools
![image](https://github.com/user-attachments/assets/08695ed2-7a89-4b7b-95e6-2f10b4ef188a)

**Comment by fret423** [comment]
Adding some notes:
- I've tried changing the baseURL in the settings to "/" and "". Makes it work - login stops working
- I'm unsure of the 80 and 8080 port differences in the 2 files - is that correct?

**Comment by o1egl** [comment]
What is in your settings.json ?

**Comment by o1egl** [comment]
I see there is a x-debug-message where it says that it can't access the file under /var/www... Looks like an issue in your nginx configuration

**Comment by fret423** [comment]
[settings.json](https://github.com/user-attachments/files/16806274/settings.json)
Have uploaded settings.json

A lot of the nginx config is chatgpt tagging on additional lines as I tried to fix the issues. I have emailed you my nginx config - I hope you don't mind.

Thanks a lot for the help!
