### ISSUE TITLE
Uploading files are set to 0b, space issue?

### ISSUE THREAD

**Issue by kimhaugland** [filebrowser/filebrowser#3433]
Is there a space issue when reaching a certain amount of files?
I have uploaded a lot of files, but now suddenly the files i upload are automatically set to 0b, and they are not usable.
How to fix that?

**Comment by o1egl** [comment]
Do you see any errors in the browser dev console or filebrowser output log?

**Comment by kimhaugland** [comment]
I receive a 500 Internal Server error. Unfortunately i cant locate how we have launched the filebrowser on our site.
We are using filebrowser 2.18 version, and we want to update it to the recent one. 
On our filebrowser we dont have the bar showing how much space have been used/whats left aswell.

**Comment by o1egl** [comment]
I can't help without getting more information
