### ISSUE TITLE
Can videos also display content like images？

### ISSUE THREAD

**Issue by liutt1312** [filebrowser/filebrowser#3439]
![image](https://github.com/user-attachments/assets/9b8cdf60-982d-48b4-ac36-fd1443f35044)
![image](https://github.com/user-attachments/assets/6aa4facd-f39c-4c46-a983-e9eb6b6bac4b)
![image](https://github.com/user-attachments/assets/bdc7d731-32fa-4855-8a23-2a47eb6f5ad3)

**Comment by alfonsop123** [comment]
They have the little video tape icon for videos.

**Comment by liutt1312** [comment]
Display video content, like this one.
![image](https://github.com/user-attachments/assets/344fc619-b5e7-4db3-a27b-75c0a4697036)
