### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#3441]
**Description**
 I'm trying to upload and delete files

**Expected behaviour**
 I expected to manage the files on the server

**What is happening instead?**
 I'm receiving an error message: 500 Internal Server Error

**Additional context**

![image](https://github.com/user-attachments/assets/a9f5036a-4d44-453f-bac4-92f16ec54ca3)

**How to reproduce?**

**Files**

**Comment by alfonsop123** [comment]
Is your ethernet actually working? Does the console/terminal have any error logs maybe?
