### ISSUE TITLE
Edit any file as text file

### ISSUE THREAD

**Issue by coppea** [filebrowser/filebrowser#3444]
Hi,

I find it quite easy to double-click on a .txt file to enter edit mode and make changes. However, I would like to be able to do the same with other file types, such as .m3u files.

Could you please consider adding an "Edit" option for selected files? I understand that the project may not be under active development, but I believe this feature would be essential for many users, including myself.

Thank you!

Let me know if you need any further adjustments!

**Comment by xiaobaidadada** [comment]
https://github.com/xiaobaidadada/fileca can do it, it uses FileBrowser's CSS

**Comment by xiaobaidadada** [comment]
> 你好
> 
> 我发现双击 .txt 文件进入编辑模式并进行更改非常容易。但是，我希望能够对其他文件类型执行相同的操作，例如 .m3u 文件。
> 
> 您能否考虑为所选文件添加“编辑”选项？我知道该项目可能没有处于积极开发阶段，但我相信此功能对包括我在内的许多用户来说都是必不可少的。
> 
> 谢谢！
> 
> 如果您需要任何进一步的调整，请告诉我！

https://github.com/xiaobaidadada/filecat can do it, it uses FileBrowser's CSS

**Comment by coppea** [comment]
unable to build using docker

**Comment by coppea** [comment]
有人吗

**Comment by gtsteffaniak** [comment]
Consider trying my fork, which as this feature. Any file that has ascii content is editable. https://github.com/gtsteffaniak/filebrowser

**Comment by xiaobaidadada** [comment]
filecat can now use docker
