### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by xiaobingbing1** [filebrowser/filebrowser#3449]
homeassistant:
  packages:
    my_knx_config: !include_dir_merge_named packages
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

knx:
  light:
    # dimmable light
    # color mode: brightness
    - name: "灯1"
      address: "0/0/1"
      state_address: "0/1/1"
#      brightness_address: "0/2/1"
#      brightness_state_address: "0/3/1"
    - name: "灯2"
      address: "0/0/2"
      state_address: "0/1/2"
#      brightness_address: "0/2/2"
#      brightness_state_address: "0/3/2"
    - name: "灯3"
      address: "0/0/3"
      state_address: "0/1/3"
#      brightness_address: "0/2/3"
#      brightness_state_address: "0/3/3"
    - name: "灯4"
      address: "0/0/4"
      state_address: "0/1/4"
#      brightness_address: "0/2/4"
#      brightness_state_address: "0/3/4"
    - name: "灯5"
      address: "0/0/5"
      state_address: "0/1/5"
#      brightness_address: "0/2/5"
#      brightness_state_address: "0/3/5"
    - name: "灯6"
      address: "0/0/6"
      state_address: "0/1/6"
#      brightness_address: "0/2/6"
#      brightness_state_address: "0/3/6"
    - name: "灯7"
      address: "0/0/7"
      state_address: "0/1/7"
#      brightness_address: "0/2/7"
#      brightness_state_address: "0/3/7"
    - name: "灯8"
      address: "0/0/8"
      state_address: "0/1/8"
#      brightness_address: "0/2/8"
#      brightness_state_address: "0/3/8"
    - name: "灯9"
      address: "0/0/9"
      state_address: "0/1/9"
#      brightness_address: "0/2/9"
#      brightness_state_address: "0/3/9"
    - name: "灯10"
      address: "0/0/10"
      state_address: "0/1/10"
#      brightness_address: "0/2/10"
#      brightness_state_address: "0/3/10"
    - name: "灯11"
      address: "0/0/11"
      state_address: "0/1/11"
#      brightness_address: "0/2/11"
#      brightness_state_address: "0/3/11"
    - name: "灯12"
      address: "0/0/12"
      state_address: "0/1/12"
#      brightness_address: "0/2/12"
#      brightness_state_address: "0/3/12"
    - name: "灯13"
      address: "0/0/13"
      state_address: "0/1/13"
#      brightness_address: "0/2/13"
#      brightness_state_address: "0/3/13"
    - name: "灯14"
      address: "0/0/14"
      state_address: "0/1/14"
#      brightness_address: "0/2/14"
#      brightness_state_address: "0/3/14"
    - name: "灯15"
      address: "0/0/15"
      state_address: "0/1/15"
#      brightness_address: "0/2/15"
#      brightness_state_address: "0/3/15"
    - name: "灯16"
      address: "0/0/16"
      state_address: "0/1/16"
#      brightness_address: "0/2/16"
#      brightness_state_address: "0/3/16"
    - name: "灯17"
      address: "0/0/17"
      state_address: "0/1/17"
#      brightness_address: "0/2/17"
#      brightness_state_address: "0/3/17"
    - name: "灯18"
      address: "0/0/18"
      state_address: "0/1/18"
#      brightness_address: "0/2/18"
#      brightness_state_address: "0/3/18"
    - name: "灯19"
      address: "0/0/19"
      state_address: "0/1/19"
#      brightness_address: "0/2/19"
#      brightness_state_address: "0/3/19"
    - name: "灯20"
      address: "0/0/20"
      state_address: "0/1/20"
#      brightness_address: "0/2/20"
#      brightness_state_address: "0/3/20"
    - name: "灯21"
      address: "0/0/21"
      state_address: "0/1/21"
#      brightness_address: "0/2/21"
#      brightness_state_address: "0/3/21"
    - name: "灯22"
      address: "0/0/22"
      state_address: "0/1/22"
#      brightness_address: "0/2/22"
#      brightness_state_address: "0/3/22"
    - name: "灯23"
      address: "0/0/23"
      state_address: "0/1/23"
#      brightness_address: "0/2/23"
#      brightness_state_address: "0/3/23"
    - name: "灯24"
      address: "0/0/24"
      state_address: "0/1/24"
#      brightness_address: "0/2/24"
#      brightness_state_address: "0/3/24"

  button:
    - name: "DPT 1 - True button"
      address: "2/0/1"
    - name: "100% button"
      address: "2/0/2"
      payload: 0xFF
      payload_length: 1
    - name: "Temperature button"
      address: "2/0/3"
      value: 21.5
      type: temperature
      
      
      
  cover:
    - name: "窗帘1"
      move_long_address: "0/4/1"
      move_short_address: "0/4/1"
      stop_address: "0/4/2"
      position_address: "0/4/3"
      position_state_address: "0/4/4"
#      travelling_time_down: 51
#      travelling_time_up: 61

    - name: "窗帘2"
      move_long_address: "0/4/5"
      move_short_address: "0/4/5"
      stop_address: "0/4/6"
      position_address: "0/4/7"
      position_state_address: "0/4/8"
#      travelling_time_down: 51
#      travelling_time_up: 61

    - name: "窗帘3"
      move_long_address: "0/4/9"
      move_short_address: "0/4/9"
      stop_address: "0/4/10"
      position_address: "0/4/11"
      position_state_address: "0/4/12"
#      travelling_time_down: 51
#      travelling_time_up: 61

    - name: "窗帘4"
      move_long_address: "0/4/13"
      move_short_address: "0/4/13"
      stop_address: "0/4/14"
      position_address: "0/4/15"
      position_state_address: "0/4/16"

**Comment by o1egl** [comment]
I don't think it is somehow related to this project
