### ISSUE TITLE
File encryption on disk

### ISSUE THREAD

**Issue by jht5945** [filebrowser/filebrowser#3450]
**Is your feature request related to a problem? Please describe.**

File content stored on disk is plaintext, not encrypted, file stored on disk should encrypted.

**Describe the solution you'd like**

Filebrowser can use `AES/CTR` encrypt file contents, I wrote a afero file encryption library: https://git.hatter.ink/hatter/go-afero-encfs , I have tested in my custom build of filebrowser, and it works, but I am not familiar with filebrowser source code.

**Describe alternatives you've considered**
n/a

**Additional context**

The core AES/CTR implementation shows below:

```go
func generateCtrEncryptBytes(key, iv []byte, offset, len int64) ([]byte, error) {
	endOffset := offset + len
	blockOffset := offset / 16
	encryptStartOffset := blockOffset * 16
	encryptEndOffset := (endOffset / 16) * 16
	if endOffset%16 > 0 {
		encryptEndOffset += 16
	}
	blocksCount := int((encryptEndOffset - encryptStartOffset) / 16)

	cipher, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	encryptBytes := make([]byte, blocksCount*16)
	for i := 0; i < blocksCount; i++ {
		encNonce := nonceAdd(iv, uint64(i)+uint64(blockOffset))
		cipher.Encrypt(encryptBytes[i*16:(i+1)*16], encNonce)
	}
	encryptedBytes := encryptBytes[offset-encryptStartOffset : offset-encryptStartOffset+len]
	//fmt.Println("XX", hex.EncodeToString(key), hex.EncodeToString(iv), offset, len, hex.EncodeToString(encryptedBytes))
	return encryptedBytes, nil
}

func nonceAdd(nonce []byte, incrementValue uint64) []byte {
	n1 := binary.BigEndian.Uint64(nonce[:8])
	n2 := binary.BigEndian.Uint64(nonce[8:])

	leftToMax := math.MaxUint64 - n2
	if leftToMax <= incrementValue {
		incrementValue -= leftToMax + 1
		n2 = incrementValue
		n1 += 1
	} else {
		n2 += incrementValue
	}

	newNonce := make([]byte, 16)
	binary.BigEndian.PutUint64(newNonce, n1)
	binary.BigEndian.PutUint64(newNonce[8:], n2)
	return newNonce
}
```

**Comment by Guiorgy** [comment]
Why not just use filesystem level encryption instead?

**Comment by jht5945** [comment]
> Why not just use filesystem level encryption instead?

Different protect level, filesystem level encryption cannot protect SSRF like attack, or any one can get the plaintext if he/she can access the server via SSH/RDP. Application level encrypt can integrate with other KMS/HSM system, therefore all decryption events can be audited.
