### ISSUE TITLE
My browser went chinese for no reason

### ISSUE THREAD

**Issue by AngryBandera** [filebrowser/filebrowser#3459]
One day i logged in Filebrowser and noticed that everything is in chinese... It even hadn't been restarted, hust changed the language. How can i change it back?

**Comment by superzjg** [comment]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/c5625a6f-0005-4ec0-88c5-070585cfdfa8">

**Comment by phunanon** [comment]
I just had the same issue - not sure what caused it though.
