### ISSUE TITLE
Images from Current Folder Not Displaying in MD Preview Mode

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#3461]
Hi,

First off, great work on the project!

However, I'm having an issue where images from the current folder don't seem to display in preview mode. I've tried both Markdown and HTML syntax, but neither works:

```md
![img](images.jpg)
<img title="a title" alt="img" src="images.jpg">
```
Could you look into this? Thanks!

Expected:

![image](https://github.com/user-attachments/assets/02a71126-32ff-494d-953e-90715ff81b72)

Result:

![image](https://github.com/user-attachments/assets/b9f699dc-1cb2-4786-80cb-98c711b0c2f8)

Also, is it possible to set the preview mode as the default?

**Comment by ultwcz** [comment]
I took a look and think it is a problem with the file path, not with `marked`. There is no problem with using the URL. I will try to solve it. Please wait patiently. Thank you.

Test URL: https://via.placeholder.com/200.png

![image](https://via.placeholder.com/200.png)

**Comment by baur** [comment]
Thank you for reply 

Also, is it possible to set the preview mode as the default for only view access users?

**Comment by ultwcz** [comment]
> Also, is it possible to set the preview mode as the default for only view access users?

Hi @baur 

Of course, I think setting the preview mode as the default is up to the individual and needs to be decided by @o1egl, this feature is also very simple, just refer to the following diff to modify it,

```
diff --git a/frontend/src/views/files/Editor.vue b/frontend/src/views/files/Editor.vue
index 7e4d7a9b..142d4400 100644
--- a/frontend/src/views/files/Editor.vue
+++ b/frontend/src/views/files/Editor.vue
@@ -67,7 +67,7 @@ const router = useRouter();
 
 const editor = ref<Ace.Editor | null>(null);
 
-const isPreview = ref(false);
+const isPreview = ref(true);
 const previewContent = ref("");
 const isMarkdownFile =
   fileStore.req?.name.endsWith(".md") ||
```

**Comment by ultwcz** [comment]
> Thank you for reply
> 
> Also, is it possible to set the preview mode as the default for only view access users?

Hi @baur 

Great idea, thank you very much for your suggestion, it makes filebrowser better, I will submit a PR to fix it as soon as possible

**Comment by baur** [comment]
I see extra space in bottom

![image](https://github.com/user-attachments/assets/a956ed32-8469-43f3-b519-5dbc8d93cdd7)

**Comment by baur** [comment]
ping
