### ISSUE TITLE
share duration 999999 days error

### ISSUE THREAD

**Issue by Zhoros** [filebrowser/filebrowser#3462]
Share any folder for 999999 days, it will cause memory overflow and no sharing will be created (nothing on share management setting). maybe apply check for it to prevent overflow.

Might seem silly but sometimes people will want to share a folder indefinitely and just put really big numbers in it.

**Comment by mikelgmh** [comment]
Fun fact: You can just leave everything empty as it is (Share and leave it as 0 hours) and the link will be permanent. Not the best UX, but hey, you can create permanent links.
