### ISSUE TITLE
Filebrowser in docker not reachable locally or externally. 

### ISSUE THREAD

**Issue by HexagonIsTheBestagon** [filebrowser/filebrowser#3467]
**Description**
I am trying to set Filebrowser up via the following docker-compose.yml

services:
    filebrowser:
        container_name: filebrowser
        volumes:
            - /home/media/files:/srv
            - /home/omikron/docker/filebrowser/filebrowser.db:/database/filebrowser.db
            - /home/omikron/docker/filebrowser/settings.json:/config/settings.json
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 8810:80
        image: filebrowser/filebrowser:s6

**Expected behaviour**
I should be able to reach the service under <Server IP>:<Port>

**What is happening instead?**
I can't reach the service at all, not even locally from the server at 127.0.0.1:8810

**Additional context**
It runs on a Debian VM configured via Proxmox. 

Docker logs: 

[migrations] started
[migrations] no migrations found
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2024/09/06 12:04:52 Using database: /database/filebrowser.db
2024/09/06 12:04:52 No config file used
2024/09/06 12:04:52 Listening on 127.0.0.1:8080

**Comment by lordpayder** [comment]
Hi,
it looks like you have overwritten the default configuration with your settings.json. This means that the application uses port 8080 unless otherwise defined (look at the ```Listening on 127.0.0.1:8080``` in your logs)

You have three options:
- Remove the line ```/home/omikron/docker/filebrowser/settings.json:/config/settings.json``` from your docker-compose.yml to use the image defaults
- Copy the [default values](https://github.com/filebrowser/filebrowser/blob/master/docker/root/defaults/settings.json) into your ```settings.json```
- Change your port mapping from ```8810:80``` to ```8810:8080```

**Comment by HexagonIsTheBestagon** [comment]
Hey,
I tried removing the line and changing my port mapping, but neither worked. 
Even when I use 8810:8080, I can't reach it at all. 
When I tried giving it a config file to use with the standard options, it refused to use the one I specify and instead would always create a new directory. 

The log output didn't change, either. 
Is there something I'm missing?

**Comment by lordpayder** [comment]
Did you recreate the container with ```docker composer up -d``` after your changes to the file?

I don't see any other issue.
________________________________

**Comment by lordpayder** [comment]
I spun up another test instance and basically used your docker-compose from above, with small modifications.
Make sure the filebrowser.db is a file and not a folder.

```
services:
  filebrowser:
    container_name: filebrowser
    volumes:
    - ./files:/srv
    - ./filebrowser.db:/database/filebrowser.db
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 8810:80
    image: filebrowser/filebrowser:s6
```

After that you should get the following log output
```
filebrowser  | [migrations] started
filebrowser  | [migrations] no migrations found
filebrowser  | ───────────────────────────────────────
filebrowser  |   _____ __ __ _____ _____ _____ _____ 
filebrowser  |  |     |  |  |   __|_   _|     |     |
filebrowser  |  |   --|  |  |__   | | | |  |  | | | |
filebrowser  |  |_____|_____|_____| |_| |_____|_|_|_|
filebrowser  |        _____ __ __ _ __    ____  
filebrowser  |       | __  |  |  | |  |  |    \ 
filebrowser  |       | __ -|  |  | |  |__|  |  |
filebrowser  |       |_____|_____|_|_____|____/ 
filebrowser  | 
filebrowser  |   Based on images from linuxserver.io
filebrowser  | ───────────────────────────────────────
filebrowser  | 
filebrowser  | To support LSIO projects visit:
filebrowser  | https://www.linuxserver.io/donate/
filebrowser  | 
filebrowser  | ───────────────────────────────────────
filebrowser  | GID/UID
filebrowser  | ───────────────────────────────────────
filebrowser  | 
filebrowser  | User UID:    1000
filebrowser  | User GID:    1000
filebrowser  | ───────────────────────────────────────
filebrowser  | [custom-init] No custom files found, skipping...
filebrowser  | [ls.io-init] done.
filebrowser  | 2024/09/08 16:53:06 Warning: filebrowser.db can't be found. Initialing in /database/
filebrowser  | 2024/09/08 16:53:06 Using database: /database/filebrowser.db
filebrowser  | 2024/09/08 16:53:06 Using config file: /config/settings.json
filebrowser  | 2024/09/08 16:53:06 Listening on [::]:80
```

and should be able to access it from the machine running the container
![image](https://github.com/user-attachments/assets/3987bb7a-695c-4d18-b509-0f14cfaf76df)

If that's still not working.. check your environment.

**Comment by HexagonIsTheBestagon** [comment]
Yes, thank you very much! Now it works. I am quite unsure what my trouble was, since your approach doesn't seem to be terribly different. Oh well...
