### ISSUE TITLE
How to Disable image preview-rendering, or enable preview caching server side?

### ISSUE THREAD

**Issue by Atomic-Laboratory** [filebrowser/filebrowser#3471]
When scrolling a folder with hundreds of images for the first time in a browser, the server will consume 100% CPU rendering the image previews. 

I would like to know if there is a method to either:
1) Disable this feature
2) Make the server cache the image preview
3) Limit CPU Usage

**Comment by alfonsop123** [comment]
I'm not sure if it would cache using cloudflare tunnels

**Comment by alfonsop123** [comment]
Cloudflare free plan could work

**Comment by Atomic-Laboratory** [comment]
https://github.com/filebrowser/filebrowser/issues/1689#issuecomment-982022360
just add the cahce dir parameter when launching filebrowser
