### ISSUE TITLE
Folder Size Display in "Info" Menu

### ISSUE THREAD

**Issue by OriginalSimon** [filebrowser/filebrowser#3475]
**Is your feature request related to a problem? Please describe.**  
Sometimes it's difficult to understand how much space a folder occupies on the disk, as the current "Folder Information" menu does not display its size.

**Describe the solution you'd like**  
I would like the "Folder Information" menu in FileBrowser to display the exact size of the folder, including all files and subfolders. This would allow for a quick assessment of how much disk space the folder is using without the need for additional actions.

**Describe alternatives you've considered**  
Manually checking folder size via the command line.

**Comment by KoenM9264** [comment]
I would also like this fixed/added
