### ISSUE TITLE
nginx配置路径后登录报错

### ISSUE THREAD

**Issue by yaxAltman9** [filebrowser/filebrowser#3481]
我在使用nginx反向代理，在域名后配置路径，登录在鉴权时报错，我应该如何解决

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by xclidongbo** [comment]
反向代理成功了吗？配置能否看下。。。

**Comment by yaxAltman9** [comment]
nginx反代配置成功了，然后现在所有的http都重定向https

    ssl_certificate ./cert.crt;   # 替换为你的证书文件路径
    ssl_certificate_./private.key;   # 替换为你的证书私钥文件路径
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /Drive/ {
        proxy_pass http://localhost:7865;  # 确保正确转发请求
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 10G;
        rewrite ^/Drive/(.*)$ /$1 break;

    }

**Comment by yaxAltman9** [comment]
去掉路径后一切正常，加上后，nginx也过滤掉了Drive，但是登录还是报错，不太理解；抓包看服务端请求也是没有Drive，但是还是报错404和上面的报错

**Comment by yaxAltman9** [comment]
我想在服务端添加路径，可以通过配置文件添加吗？
