### ISSUE TITLE
cannot upload file

### ISSUE THREAD

**Issue by Maatify** [filebrowser/filebrowser#3482]
**Description**
while uploading file failed in last step after progress completed

**Expected behaviour**
the progress colore changed to red

**What is happening instead?**
default.ALERT: Fatal Error (E_ERROR): Uncaught Error: Call to a member function isValid() on array in /file_browser/filebrowser/backend/Controllers/UploadController.php:71 Stack trace: #0 [internal function]: Filebrowser\Controllers\UploadController->upload() #1 /public/file_browser/filebrowser/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array() #2
![Screenshot 2024-09-12 at 11-31-40 FileBrowser](https://github.com/user-attachments/assets/b05c8068-fff4-4a5c-a35b-361f4c64e7d2)

**Comment by alfonsop123** [comment]
What are you running filebrowser on?

**Comment by Maatify** [comment]
apache, php8, windows server
