### ISSUE TITLE
500 Internal Server Error when trying to delete file

### ISSUE THREAD

**Issue by halpz** [filebrowser/filebrowser#3483]
**Description**
500 Internal Server Error when trying to delete file

**Expected behaviour**
file is deleted

**What is happening instead?**
500 Internal Server Error when trying to delete file

**Additional context**
File can be deleted using ssh with the same user permissions

**How to reproduce?**
Try to delete a file

**Files**
all files / folders

How can I view the logs of FileBrowser to get more info ? I am using it as a built-in plugin for OMV. It doesn't seem to be running in a docker container, so I'm not sure how to attach to the file browser process?

**Comment by alfonsop123** [comment]
There might be a error on the terminal your running it on, but not 100% sure. Are you running file browser with the necessary permissions?

**Comment by halpz** [comment]
I gave my OMV server a kick (reboot) and the server errors are now gone
