### ISSUE TITLE
Run filebrowser in a subdirectory

### ISSUE THREAD

**Issue by BerengarWLehr** [filebrowser/filebrowser#3484]
I'd like to run filebrowser behind a reverse proxy in a subdirectory. Currently this does not work because I can not replace all places e.g. via proxy_html Apache.

Is there any way one can configure that? Are there any variables in the source code I could manually adjust before compiling the binary?

**Comment by TCB13** [comment]
I did it for a while and it worked fine. What's missing?

Check "base url" and "root": https://filebrowser.org/cli/filebrowser-config-set.

You can set something like this in the config file:

```
{
  "port": 8080,
  "noAuth": false,
  "address": "127.0.0.1",
  "baseurl": "/admin"
}
```

**Comment by BerengarWLehr** [comment]
For some strange reason that I couldn't figure out it always redirected to $domain/ (without the subdirectory). But I deleted the db file, reimported the config file and suddenly  it workes. Thank you for encouragement.

**Comment by gtsteffaniak** [comment]
@BerengarWLehr Try https://github.com/gtsteffaniak/filebrowser which recently added this feature.
