### ISSUE TITLE
REstful API

### ISSUE THREAD

**Issue by freedbygrace** [filebrowser/filebrowser#3486]
Are there any plans to have a rest API so that one could list, download, upload, search for files and folders via external applications?

That would be huge!

**Comment by alfonsop123** [comment]
I've seen docs made by users here but it's not really a proper way to do it :(

**Comment by kilboss** [comment]
I'm interesting with this feature also. +1

**Comment by SquareDonut1** [comment]
+1

**Comment by mrctrifork** [comment]
This would be an incredibly handy feature and I'd like to contribute
