### ISSUE TITLE
When using Cloudflare Turnstile, Filebrowser requests content from the wrong link, causing it to become unavailable.

### ISSUE THREAD

**Issue by Sentsuki** [filebrowser/filebrowser#3488]
**Description**

When using Google reCAPTCHA, the host is set to `www.google.com`, and it correctly requests `https://www.google.com/recaptcha/api.js?render=explicit`. However, when using Cloudflare, it attempts to request `https://challenges.cloudflare.com/recaptcha/api.js?render=explicit`, resulting in a 404 error. It seems that the path `/recaptcha/api.js?render=explicit` is automatically appended to the host, but the correct path for Cloudflare should be `https://challenges.cloudflare.com/turnstile/v0/api.js`.

**Files**

![Screenshot 2024-09-16 031029](https://github.com/user-attachments/assets/eae0dbbe-a5cd-4f08-926b-5627be9620fc)

**Comment by yushisora** [comment]
I also want to use cloudflare turnstile as the reCAPTCHA host. Have you find a way to solve this issue?

Thanks.
