### ISSUE TITLE
mount the following blank NTFS folder using When opening the generated path, it prompts Incorrect function

### ISSUE THREAD

**Issue by lhn1324** [filebrowser/filebrowser#3495]
After upgrading to v2.31.1, mount the following blank NTFS folder using
An error is prompted when opening the generated path, and Incorrect function appears in the log.

**Comment by gtsteffaniak** [comment]
Consider trying my fork which I recently improved windows compatibility for. https://github.com/gtsteffaniak/filebrowser

Any issues you run into I can address pretty quickly for issues on that repo.
