### ISSUE TITLE
Edit Text report

### ISSUE THREAD

**Issue by Outside-Excuse** [filebrowser/filebrowser#3498]
**Description**

Al querer editar el nombre de un texto o texto tira error
**Expected behaviour**
se espera que cambie el texto

**What is happening instead?**
tira error y no guarda cambios

**Additional context**

**How to reproduce?**
editar algún nombre de un archivo

**Files**
Settings

**Comment by alfonsop123** [comment]
Hola, predestination reproducir El error y mandarar photo del error?
