### ISSUE TITLE
RAID folder capacity incorrect

### ISSUE THREAD

**Issue by wafflewizard1** [filebrowser/filebrowser#3499]
![image](https://github.com/user-attachments/assets/6820f6a8-b0bf-4a69-b575-ad4f76d24e0b)
This is the preview for space in the browser
![image](https://github.com/user-attachments/assets/fb5cd83c-bea3-44be-b0ad-46302e2287a9)
This is my actual capacity

**Comment by alfonsop123** [comment]
Yeah, I also get that issue
