### ISSUE TITLE
Can't edit config file

### ISSUE THREAD

**Issue by jdaiv** [filebrowser/filebrowser#35]
Building from source. 

Whenever I try to edit the config.toml file I get a 500 error.

I enabled the error log and found a bunch of these lines:

```
13/Dec/2015:16:26:24 +1100 [PANIC /admin/edit/config.toml] C:/dev/go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:46 - interface conversion: interface is []map[string]interface {}, not []interface {}
```

Changing that line to the suggested types fixed the issue, but I'm not sure if this may cause other errors.

**Comment by hacdias** [comment]
Hmmm... What's the content of your config.toml? That's the easier way to see what's wrong and I think I know what it is.

**Comment by jdaiv** [comment]
Here's the config.toml:

```
baseurl = "//rooffixingsupplies.com.au"
languageCode = "en-us"
title = "Roof Fixing Supplies"

[[menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"
```

I assume it's valid since hugo itself never complained about it! And with workaround it parses fine too.

**Comment by hacdias** [comment]
Try replacing `[[menu.main]]` with `[menu.main]`. That's why it is throwing an error. Later I'll check if I can make it work with that syntax.

**Comment by jdaiv** [comment]
Yeah, that fixed it. Only using that syntax since it's pretty much a straight rip from the Hugo docs.

**Comment by hacdias** [comment]
I'll close the issue, but I think I should have a look at it.
