### ISSUE TITLE
Display current username in UI

### ISSUE THREAD

**Issue by apple15pie** [filebrowser/filebrowser#3503]
**Is your feature request related to a problem? Please describe.**
It is difficult to tell which user you are while browsing the UI. It would be helpful to know what user you are currently logged in as in the UI for troubleshooting.

**Describe the solution you'd like**
Somewhere in the base UI display the current username, possibly even include other user options (settings, switch user etc)

**Describe alternatives you've considered**
The alternative is to log out and log in again as the user you think you are/ wish to be. But often I am already logged in as that user so its a lot of wasted effort

**Comment by gtsteffaniak** [comment]
Consider trying my fork which has this feature https://github.com/gtsteffaniak/filebrowser
