### ISSUE TITLE
Not working, appears to be related to filebrowser.db

### ISSUE THREAD

**Issue by VOGUK** [filebrowser/filebrowser#3509]
Hi, I am running FileBrowser on YunoHost platform and have not received a reply on their Guthub, so posting here hoping someone may be able to help.

I have been using FileBrowser for over a year and love it. However, I just upgraded my system and tried to install it again. 

When I do so, everything seems to go well, but when I go to use the app it doesnt work and shows error code 502, Bad Gateway.

When I look under Services, the app is stopped and shows the following error in the log which appears to be causing the issue:
Filebrowser[40465]: 2024/09/27 00:31:20 Warning: filebrowser.db can't be found. Initialing in /var/www/filebrowser/database.db

Any ideas how this can be rectified?

**Comment by o1egl** [comment]
This is not an error. It just says that the existing DB is not found and a new one is created

**Comment by MadMan247** [comment]
You waited only 14.5 hrs for a response. A commit was pushed that may resolve your issue on the yunohost github 5 days ago. it looks like it was a permissions error. You may want to restore the pre-upgrade backup that yunohost automatically makes before upgrading to their next release (bringing your install to a state that works) then upgrade to the current version. Please close this issue if this resolves your problem.

**Comment by ysy95109** [comment]
Looks like the user running file browser doesn't have permission to create the db file.
