### ISSUE TITLE
Keyboard shortcuts in the vue frontend

### ISSUE THREAD

**Issue by pbberlin** [filebrowser/filebrowser#3513]
There are some very nice shortcuts, such as "DEL" and "Enter" to confirm.

But "dir up" via backspace - or almost everything else is not possible.

1.) Is there keyboard support, that  I did not find (I searched the entire frontend HTML for "accesskey"?

2.) Any qualms about a pull request adding a few "accesskey" shortcuts to the vue templates?
   Or should it be configurable from the start, for all the localized browser users

Regards
  Peter

**Comment by gtsteffaniak** [comment]
Consider tying my fork which has much better keyboard support:

https://github.com/gtsteffaniak/filebrowser

Open an issue for any additional keyboard shortcuts you would like!
