### ISSUE TITLE
New Registered Users gain full access to base path created users dont

### ISSUE THREAD

**Issue by tarumes** [filebrowser/filebrowser#3515]
this is the current version of filebrowser
fresh install
enabled Allow users to signup
enabled Auto create user home dir while adding new user
![grafik](https://github.com/user-attachments/assets/dc264f73-de54-4a80-8136-1e92a8cf7060)
then created an account
then logged out and registered an account
![grafik](https://github.com/user-attachments/assets/abac771b-e49d-467d-bdfd-c2ca2415cdae)
the new registered account has by default full access to the base path of filebrowser
![grafik](https://github.com/user-attachments/assets/a4ced85d-9ee4-4f66-8ddd-7487b117be5f)

**Comment by SilverSong3** [comment]
You're on the right path, and it can be done. If you view the options to the right of the global settings you have pictured there, you should see the "User Default Settings" options. You should be able to change the / to /users and any new users will be automatically assigned that scope when they are created. That is where you can also set the permissions for new users as well.

Hope that helps!

**Comment by tarumes** [comment]
that doesnt fix that they dont get a folder created in /users

**Comment by SilverSong3** [comment]
You are quite right. My apologies. I believe https://github.com/filebrowser/filebrowser/issues/2787#issuecomment-1781406851 and https://github.com/filebrowser/filebrowser/issues/657#issuecomment-1781390444 helped find a solution.

If you paste the following command in the Execute on Shell field, it will create a folder with the value the user used to sign up.

`docker exec -it filebrowser /filebrowser users add emc emc --database /config/filebrowser.db`

Then as long as the user default settings for the Scope is left blank (and the auto create dir for new users option is checked) the folder should be generated automatically.

It seems like adding this detail would be greatly helpful in the documentation. This should work for both sign-ups and created users.

Hopefully that helps quite a bit more.
