### ISSUE TITLE
FILE env variable not set "After Upload"

### ISSUE THREAD

**Issue by gmemstr** [filebrowser/filebrowser#352]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes, I did it about a week ago.

### 2. What is your entire Caddyfile?
```text
<redacted>.ca
gzip
minify
fastcgi / /run/php/php7.1-fpm.sock php
filemanager /manage ./pdfs {
    allow_commands true   
    commands gs mv rm
}
```

### 3. What are you trying to do?

I am trying to run  a PDF compression script when a new PDF is uploaded to the directory, in the "After upload section".

### 4. What did you expect to see?

The PDF compressed correctly.

### 5. What did you see instead (give full error messages and/or log)?

The $FILE variable doesn't seem to be set, so the command fails completely and `echo` is empty.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Add to "After upload" in settings:

`echo $FILE`

**Comment by eine** [comment]
@gmemstr, please see #483.
