### ISSUE TITLE
Save PDF Highlights

### ISSUE THREAD

**Issue by bryce-hoehn** [filebrowser/filebrowser#3522]
**Is your feature request related to a problem? Please describe.**

I am a grad student, and one of my main use cases for file browser is to read course materials that I have saved during downtime at my job. File browser has been the best self-hosted method I could come up with so far that does not require downloading or syncing files to the computer. In Firefox at least, the native PDF viewer works great for reading and highlighting text in-browser, but it does not save pdf highlights and annotations unless I download it locally and reupload it.

**Describe the solution you'd like**

Some sort of save button in the pdf viewer that can save to the server w/o having to download locally. I'm not sure if this is possible in the built-in pdf viewer or if this would require a custom implementation.

**Describe alternatives you've considered**

Zotero has a great web interface for pdf annotating, but that requires using their cloud storage which is limited to 300mb on the free plan.

**Comment by bryce-hoehn** [comment]
Doing some more digging, the "native PDF view" I mentioned is specifically the PDF.js library built into Firefox.

Nextcloud uses a modified implementation [here](https://github.com/nextcloud/files_pdfviewer) that allows saving annotations serverside, but is a bit behind upstream pdf.js. Seeing as this would require a custom implementation I understand that this is probably outside the scope of the project.

**Comment by maxlin08** [comment]
If the PDF already contains the highlights/annotations, there’s another
option for the extraction side of this workflow:

https://pdfannotations.com/

It can extract highlights, comments, underlines and other PDF annotations
from local PDFs and export them to Markdown, Obsidian, Notion, CSV, JSON,
TXT, or Excel.

It runs locally in the browser, so the PDF doesn't need to be uploaded.

It won't solve the server-side saving part of this issue, but it may be
useful for the “I already have a heavily annotated PDF and want to get
those annotations out” side of the workflow.
