### ISSUE TITLE
i cant find the password for the db file 

### ISSUE THREAD

**Issue by ExtraBytez** [filebrowser/filebrowser#3526]
![image](https://github.com/user-attachments/assets/547e1c94-d123-4e35-b2dc-af0d80dbc8dd)
i want to edit the database manually but i dont know the password

**Comment by AudunVN** [comment]
FileBrowser uses BoltDB, not SQLite: https://github.com/filebrowser/filebrowser/blob/master/storage/bolt/bolt.go

Unless you already know that what you want to edit in the database isn't covered by the commands

- `filebrowser config import`, see https://filebrowser.org/cli/filebrowser-config-import
- `filebrowser config export`, see https://filebrowser.org/cli/filebrowser-config-export
- `filebrowser users import`, see https://filebrowser.org/cli/filebrowser-users-import
- `filebrowser users export`, see https://filebrowser.org/cli/filebrowser-users-export

those are probably the easiest way to go - not too familiar with browsers/editors for BoltDB myself, at least.

EDIT: This seems like one of the most used and recently updated BoltDB browsers on GitHub, at least: https://github.com/br0xen/boltbrowser

**Comment by ExtraBytez** [comment]
thanks!
