### ISSUE TITLE
[SOLVED] [Installation] Docker fails

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#3527]
Whenever I try to install from any of the docker way see it [here](https://filebrowser.org/installation#docker), it fails. I cannot install Alpine's neither Linuxserver's. Tried into a linux box and a VM with same exact results but different permissions: mounting the volume into `/mnt` for the linux box, and into the home directory for the VM, but the same exact error appears.

Alpine's:

```
$ docker run     -v ~/docker/fb:/srv     -v ~/docker/fb/filebrowser.db:/database.db     -v ~/docker/fb/.filebrowser.json:/.filebrowser.json     -u $(id -u):$(id -g)     -p 8080:80     filebrowser/filebrowser
Unable to find image 'filebrowser/filebrowser:latest' locally
latest: Pulling from filebrowser/filebrowser
43c4264eed91: Pull complete 
8bf97b3782bc: Pull complete 
7b9ef589a6a5: Pull complete 
cbce7afa4da2: Pull complete 
6548c5532ce7: Pull complete 
cf4bef12b891: Pull complete 
Digest: sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
Status: Downloaded newer image for filebrowser/filebrowser:latest
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/user/docker/fb/.filebrowser.json" to rootfs at "/.filebrowser.json": create mount destination for /.filebrowser.json mount: cannot mkdir in /var/lib/docker/overlay2/fe6b749ebce62bbc03fabb135318aefaebefb981f4ca3b76c0c34d391e5b5f60/merged/.filebrowser.json: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

Linuxserver's:

```
docker run \
    -v ~/docker/fb:/srv \
    -v ~/docker/fb/filebrowser.db:/database/filebrowser.db \
    -v ~/docker/fb/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -p 8080:80 \
    filebrowser/filebrowser:s6
Unable to find image 'filebrowser/filebrowser:s6' locally
s6: Pulling from filebrowser/filebrowser
68c4ea3779b6: Pull complete 
df25a931801a: Pull complete 
ab0ddebe54a6: Pull complete 
19f39f464468: Pull complete 
7560e3e46aa2: Pull complete 
339ecd878087: Pull complete 
eca832828ed1: Pull complete 
cc01b3dc062a: Pull complete 
0e623de493ae: Pull complete 
Digest: sha256:62da3fc76a53db9d5a2797cbde39bbaed915822f7d88141473afe18a5e57c2a2
Status: Downloaded newer image for filebrowser/filebrowser:s6
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] Files found, executing
[custom-init] 20-config: executing...
[custom-init] 20-config: exited 0
[ls.io-init] done.
2024/10/07 15:17:38 Using database: /database/filebrowser.db
2024/10/07 15:17:38 open /database/filebrowser.db: is a directory
2024/10/07 15:17:39 Using database: /database/filebrowser.db
2024/10/07 15:17:39 open /database/filebrowser.db: is a directory
2024/10/07 15:17:40 Using database: /database/filebrowser.db
2024/10/07 15:17:40 open /database/filebrowser.db: is a directory
2024/10/07 15:17:41 Using database: /database/filebrowser.db
2024/10/07 15:17:41 open /database/filebrowser.db: is a directory
2024/10/07 15:17:42 Using database: /database/filebrowser.db
2024/10/07 15:17:42 open /database/filebrowser.db: is a directory
```

**Comment by AudunVN** [comment]
https://filebrowser.org/installation#docker

> If you don't already have a database file, make sure to create a new empty file under the path you specified. Otherwise, Docker will create an empty folder instead of an empty file, resulting in an error when mounting the database into the container.

---

As mentioned on the documentation page you linked to (see above), the file `filebrowser.db` needs to be created *before* starting the container - if a file doesn't exist at the host path you specify, Docker will create a directory there and try to mount that instead. That seems to be what's happened here, considering the

`/.filebrowser.json: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

and

`open /database/filebrowser.db: is a directory`

messages in the log output.

The same applies for mounting the settings file `.filebrowser.json` - you need to create a file you can mount before you can, well, mount it. I'm not sure if it will populate itself with the default options if you start with an empty file; last time I set up FileBrowser in Docker I started with the default settings file, which can be found [here](https://github.com/filebrowser/filebrowser/blob/master/docker/root/defaults/settings.json).

EDIT: See https://github.com/filebrowser/filebrowser/issues/3467#issuecomment-2335183225 - you'll need to fill in the settings file before mounting it.

---

PS: Also worth noting that this isn't unique to FileBrowser - if Docker can't find an existing file or directory at a bind mount path, it assumes you want a new folder and not a new file.

**Comment by ghost** [comment]
You're right! I'm sorry, I didn't read that long :'( my bad.
It's working right now.

> PS: Also worth noting that this isn't unique to FileBrowser - if Docker can't find an existing file or directory at a bind mount path, it assumes you want a new folder and not a new file.

Nice point! Little bit of a begginer with docker here. Thanks a lot.
