### ISSUE TITLE
(minor) Inconsistent behaviour when downloading folders

### ISSUE THREAD

**Issue by tristanic** [filebrowser/filebrowser#3528]
**Description**
If I have have a directory structure that looks like:
```
foo/bar.txt
bar/foo.txt
```

... then if I select both folders for download the result is a .zip file containing, as expected, `foo/bar.txt` and `bar/foo.txt`. If I select only `foo` to download, then I get a flat .zip file containing only `bar.txt`. This inconsistent behaviour can lead to messes when decompressing.

**Expected behaviour**
Downloading a single folder should give a compressed file with the folder in its directory structure, giving consistent behaviour with a multi-folder download.

**What is happening instead?**

**Additional context**
N/A

**How to reproduce?**
See the description.

**Files**
N/A

**Comment by Illusionna** [comment]
> **Description** If I have have a directory structure that looks like:
> 
> ```
> foo/bar.txt
> bar/foo.txt
> ```
> 
> ... then if I select both folders for download the result is a .zip file containing, as expected, `foo/bar.txt` and `bar/foo.txt`. If I select only `foo` to download, then I get a flat .zip file containing only `bar.txt`. This inconsistent behaviour can lead to messes when decompressing.
> 
> **Expected behaviour** Downloading a single folder should give a compressed file with the folder in its directory structure, giving consistent behaviour with a multi-folder download.
> 
> **What is happening instead?**
> 
> **Additional context** N/A
> 
> **How to reproduce?** See the description.
> 
> **Files** N/A

You can use my project: https://github.com/Illusionna/LocalTransfer.  It is consistent.
