### ISSUE TITLE
[Object Object]

### ISSUE THREAD

**Issue by joshk132** [filebrowser/filebrowser#353]
### 3. What are you trying to do?
Upload a file

### 4. What did you expect to see?
File uploaded

### 5. What did you see instead (give full error messages and/or log)?
red notification with [Object object] in it nothing else

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Upload a file.

 I access the filemanager through Chrome and Firefox (same issue) and it only happens when I try to upload any file. I can't even upload a blank txt file. I am running the site on filemanager.mydomain.com not sure if that makes a difference. It shouldn't. I am also running it behind a Nginx reverse proxy, again this should not cause issues.

**Comment by Equim-chan** [comment]
Open devtools, switch to network and find any failed ones?

**Comment by eine** [comment]
@joshk132 could please provide some more info so that we can reproduce the behaviour?

**Comment by Platway** [comment]
I have this issue too. Procedures to reproduce:

1. Upload a big file;
2. Cut the internet (e.g. turning WiFi off) before uploading completes;
3. Wait a moment and a red notification with "[Object object]" in it will show on the bottom right.

**Comment by luoyangchun** [comment]
> I have this issue too. Procedures to reproduce:
> 
> 1. Upload a big file;
> 2. Cut the internet (e.g. turning WiFi off) before uploading completes;
> 3. Wait a moment and a red notification with "[Object object]" in it will show on the bottom right.

I have the same problem on iPhone Safari.
But everything works fine on Android Chrome.
