### ISSUE TITLE
Closing the filebrowser web page will not log you out of the account

### ISSUE THREAD

**Issue by rehack** [filebrowser/filebrowser#3533]
It is recommended to close the page or browser and log out of the account automatically. This will help protect the privacy and security of the file.

**Comment by pam-param-pam** [comment]
Its not a bug, its intended behaviour. If u want to be loged out u can log out manually. I dont see a point in making an option in settings just for this

**Comment by rehack** [comment]
@pam-param-pam Sometimes we forget to click to exit and directly close the web page or browser when leaving the computer, which creates certain risks. Maybe it's time to change this bad habit.
