### ISSUE TITLE
Shell Command Not Allowed

### ISSUE THREAD

**Issue by BarrenWardo** [filebrowser/filebrowser#3535]
**Description**
Unable to run shell commands. 

<img width="1659" alt="image" src="https://github.com/user-attachments/assets/40c894ca-cb65-41ed-b64a-9bf353723e01">

**What is happening instead?**
Shows - `Command Not Allowed`

**Additional context**
Tried adding `/bin/bash -c` & `/bin/bash` in shell config. 
Tried giving admin rights.
Tried adding commands in config.

**Version**
v2.31.2

**Comment by mgite** [comment]
There is no bash in default image. They put placeholder in settings input but never say that it won't work :(

use sh instead.
