### ISSUE TITLE
Incomplete, partial files after failed upload

### ISSUE THREAD

**Issue by DerFnoeh** [filebrowser/filebrowser#3538]
Description
Automatically clean up partial files after a failed upload.
Currently, cleanup is only performed when an upload is aborted, but not when it fails.

If the user misses the error, they must carefully compare the expected and actual file sizes to determine whether the upload was successful. This is might happen and is particularly inconvenient if a user uploads a large file overnight.

Expected behaviour
Multiple Options:
A: After a failed/partial upload, no corrupted (partial) files should remain on the system.
B: The file is clearly marked as a partial file. This would also prepare Filebrowser for a follow-up feature, allowing the user to resume a failed upload. WinSCP offers a similar feature.

What is happening instead?
File is created with partial size and left on the device.

Additional context
Look at WinSCP for comparison.
Partially Copied from https://github.com/filebrowser/filebrowser/issues/3400

How to reproduce?
AttemptUpload
Either loose connection or reload the page.
The upload will get cancelled but there will be a file created.

Files
n/a

**Comment by papwickjoeyda** [comment]
This problem also troubles me. Many times, the uploading process is interrupted due to network problems. However, incomplete files are still stored on the server. They should be marked or automatically deleted by the program.

**Comment by DerFnoeh** [comment]
Comment to remove Stale label
