### ISSUE TITLE
HEAD requests return 404

### ISSUE THREAD

**Issue by FHomps** [filebrowser/filebrowser#3539]
**Description**
HEAD requests return 404:
```
$ curl --head https://REDACTED/files
HTTP/1.1 404 Not Found
Server: nginx/1.22.1
Date: Wed, 16 Oct 2024 17:09:51 GMT
```

GET requests to the same URL are fine. This is not an issue with the reverse proxy, I get 404s even when `curl`ing the backend directly from the server's shell.

This breaks compatibility with uptime checkers such as UptimeRobot.

**Comment by dockerdavid** [comment]
Do you get this solved?

**Comment by o1egl** [comment]
It doesn't look like an issue of the filebrowser, but rather a misconfiguration of your uptime checker.

**Comment by FHomps** [comment]
It is a filebrowser issue. HEAD requests are a standard part of http, and looking at the code filebrowser rejects them in bulk.
filebrowser is the first server utility I've found to not support these requests.

**Comment by o1egl** [comment]
Head is indeed a standard, but it doesn't mean that any url in the world should support get/head/post/put/whatever queries. There  are specific use cases for every type of request.

**Comment by FHomps** [comment]
Sure thing. Then if it's not a bug it's a feature request 😉

**Comment by RubenMeneses** [comment]
Hi, I came across the same issue. For me it broke Chromecast via Homey automation: the cast sends a HEAD to the video file first, gets a 404, and never issues the GET. Same URL returns 200 on GET.

Looks like it comes from `http/static.go`, in `getStaticHandlers()` — two spots with the same method guard, one in the index handler and one in the static handler:

https://github.com/filebrowser/filebrowser/blob/833d908884d5c801f30f5c098d7977177eb3a36b/http/static.go#L108-L110

https://github.com/filebrowser/filebrowser/blob/833d908884d5c801f30f5c098d7977177eb3a36b/http/static.go#L118-L120

Go's net/http already drops the body on HEAD, so letting it through the existing GET path might be all that's needed:

```diff
-		if r.Method != http.MethodGet {
+		if r.Method != http.MethodGet && r.Method != http.MethodHead {
```

In both spots. `http.FileServer` and `http.ServeFile` in the static branch seem to handle HEAD already.

FWIW RFC 9110 §9.1 lists GET and HEAD as the two methods a general-purpose server is expected to support, and §9.3.2 describes HEAD as GET without the content.

**Comment by RubenMeneses** [comment]
Hi, I think I've come across the same issue. For me it seemed to break Chromecast via Homey automation: the cast appears to send a HEAD to the video file first, gets a 404, and never issues the GET. Same URL returns 200 on GET.

From what I can tell it looks like it comes from `http/static.go`, in `getStaticHandlers()`. There appear to be two spots with the same method guard, one in the index handler and one in the static handler:

https://github.com/filebrowser/filebrowser/blob/833d908884d5c801f30f5c098d7977177eb3a36b/http/static.go#L108-L110

https://github.com/filebrowser/filebrowser/blob/833d908884d5c801f30f5c098d7977177eb3a36b/http/static.go#L118-L120

The 404 may also be affecting how clients respond here. RFC 9110 Section 15.5.5 defines 404 as no representation found, which a client is likely to treat as terminal. Section 15.5.6 defines 405 for a method the server knows but the resource doesn't accept, and requires an `Allow` header listing what it does take, which gives the client something to act on.

If I'm reading it right, Go's net/http already drops the body on HEAD, so letting it through the existing GET path might be all that's needed:

```diff
-		if r.Method != http.MethodGet {
+		if r.Method != http.MethodGet && r.Method != http.MethodHead {
```

In both spots, I think. `http.FileServer` and `http.ServeFile` in the static branch seem to handle HEAD already.

FWIW RFC 9110 Section 9.1 lists GET and HEAD as the two methods a general-purpose server is expected to support, and Section 9.3.2 describes HEAD as GET without the content.

Happy to be corrected if I've misread any of this, and I may be missing context on why it's written this way.
