### ISSUE TITLE
Symbolik link issue 

### ISSUE THREAD

**Issue by Embraser01** [filebrowser/filebrowser#354]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes, today (12/02/18)

### 2. What is your entire Caddyfile?
```text
files.example.com {	
	filemanager / ./static/files {
		database config.db
	}
}

## LOGS from systemd

Feb 12 18:41:46 xxxxxxxxxxx caddy[29603]: 2018/02/12 18:41:46 /: 410 Gone
Feb 12 18:41:46 xxxxxxxxxxx caddy[29603]: 2018/02/12 18:41:46 stat downloads: no such file or directory
```

### 3. What are you trying to do?

I'm trying to add a symlink to a folder somewhere else

### 4. What did you expect to see?

A list with all files and directories including symlink directories.

### 5. What did you see instead (give full error messages and/or log)?

HTTP Error 410 for `GET https://files.finch4.xyz/api/resource/`, with the text `Gone` in body.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

- Create a new filebrowser site
- Set filebrowser root to a folder
- In this folder, create a symlink to another folder with `ln -s /path/to/other/folder externalFolder`
- Refresh your file manager page

You should have the same error.

I should mention that I use caddy with systemd as service manager. But tis shouldn't be a problem (I already check every security features).

Also, the problem seems to be here since my last update of filebrowser which was in January,
before that, everything worked!

It seems that #281 added the bug (don't know for sure or why).

I would be happy to help, even if I don't know Go yet :smile:

**Comment by hacdias** [comment]
Ref.: #356

Thanks for reporting this. V1.5.3 is on the way and it will fix this 😄

**Comment by hacdias** [comment]
[v1.5.3 released](https://github.com/filebrowser/filebrowser/releases/tag/v1.5.3) 🎉!
