### ISSUE TITLE
500 Internal server error while browsing a folder with 168,666 subfolders 

### ISSUE THREAD

**Issue by dannycadavid87** [filebrowser/filebrowser#3540]
**Description**
500 Internal server error while browsing a folder with 168,666 subfolders 

**Expected behaviour**
The screen should have displayed the subfolders.

**What is happening instead?**
![image](https://github.com/user-attachments/assets/61bb1959-7eb1-4a68-8d0b-3e2f372538ee)

Log is just showing a 500 code
![image](https://github.com/user-attachments/assets/7f2a8d87-a454-425b-b975-7de51f38470f)

**Additional context**
Folder has 168,666 subfolders
![image](https://github.com/user-attachments/assets/5581801d-61a2-49c6-b9a5-c544790723ad)

The main folder was mounted on a k8s pod from a S3 bucket.

**How to reproduce?**
Create a S3 bucket
Create a folder with 168K+ subfolders
Create a EKS cluster
Create a pod with a volume that has mounted the main folder of the S3 bucket.

**Comment by gh74521** [comment]
我也是同样的问题,你解决了吗?
我在使用alist时,可以在设置里,找到"预览数量"的选项,设定自己需要的显示数量,不至于崩溃;
但是对于file browser 我不知道配置文件在哪儿.
如果你解决了同样的问题,记得@我一下
