### ISSUE TITLE
Add a guide for make share link work with authentication Method "proxy auth"

### ISSUE THREAD

**Issue by carrotgeball** [filebrowser/filebrowser#3545]
### Is your feature request related to a problem? Please describe.

- This where I come from and which proxy method I'm using: https://github.com/filebrowser/filebrowser/issues/1328#issuecomment-798984515

- I see that share behind proxy is ready to use: #1316

- And the path need to bypass in: https://github.com/filebrowser/filebrowser/issues/1827#issuecomment-1047777732

But till I add `/api/public/share` it finally work, path I passthorugh for not use auth:
```
/api/public/dl
/api/public/share # <-- ADD THIS
/share
/static
```

### Describe the solution you'd like  

Add a guide to official doc somewhere like [here](https://filebrowser.org/configuration/authentication-method#proxy-header)
- Announce you will break anonymous share until do something. 
- Post the path that need to bypass through the auth.

my example nginx config for allow share link with `nginx` and [`oauth2-proxy`](https://github.com/oauth2-proxy/oauth2-proxy)(works fine):

- notice that my filebrowser is running in path `https://<host>/file` so I need to use `rewrite` in nginx
```
    location ~ ^/file/(api/public/dl|api/public/share|share|static)/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/file/(.*)$ /$1 break;
        proxy_pass http://<server ip>;
    }
    location ~ ^/file/ {
        auth_request /oauth2/auth;  # other location where oauth2-proxy works
        error_page 401 = /oauth2/sign_in;

        auth_request_set $user   $upstream_http_x_auth_request_preferred_username;
        proxy_set_header X-User  $user;


        auth_request_set $auth_cookie $upstream_http_set_cookie;
        add_header Set-Cookie $auth_cookie;

        auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;

        if ($auth_cookie ~* "(; .*)") {
            set $auth_cookie_name_0 $auth_cookie;
            set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
        }

        if ($auth_cookie_name_upstream_1) {
            add_header Set-Cookie $auth_cookie_name_0;
            add_header Set-Cookie $auth_cookie_name_1;
        }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/file/(.*)$ /$1 break;
        proxy_pass http://<server ip>;
    }
```

### Additional context

The path I bypass the auth:
```
/api/public/dl
/api/public/share
/share
/static
```
Is It minimize or safe enough to just allow share link to be anonymous? maybe just use `/api/public/` is ok? I just not familiar with the code in project.

**Comment by AustinSaintAubin** [comment]
Note for use with [oauth2 proxy](https://github.com/oauth2-proxy/oauth2-proxy), add to the following to allow for authenticated sharing (use of share links).
```
skip_auth_routes = [
    "GET=^/share",
    "GET=^/api/public/share",
    "GET=^/api/public/dl",
    "GET=^/static/assets"
]
```
