### ISSUE TITLE
403 forbidden error when copying files only

### ISSUE THREAD

**Issue by dockerisedDan** [filebrowser/filebrowser#3548]
**Description**
When using FileBrowser to copy files on my server, I get a 403 forbidden error even though the user running the container has full permissions.

**Expected behaviour**
No 403 error.

**What is happening instead?**
The copy is successful but the error pops up and the copy UI does not close. I am unsure if the permissions are correct after the copy.

**Additional context**
This does not happen when creating files, moving (cutting) or deleting files. Only when copying.

**How to reproduce?**
Running FileBrowser in docker compose on TrueNAS Scale under user 3000 (created, has read/write/execute permissions on FS)
Copy file from one location to another and notice error
Cut file and notice no error
Delete file and notice no error

**Comment by HunterAhlquist** [comment]
I'm having this issue too, but when moving instead of copying.
