### ISSUE TITLE
Uploading large files fail, result in 0 byte file in the directory

### ISSUE THREAD

**Issue by danworsley** [filebrowser/filebrowser#3549]
**Description**
Trying to upload a file larger than 10mb

**Expected behaviour**
Upload the file into the directory

**What is happening instead?**
Upload finishes prematurely and a zero byte file is left in the directory, no errors logged.

**Additional context**
Uploads work fine with files less than 10mb. File upload size limit is set to 10GB in settings

**How to reproduce?**
I'm using the docker image of filebrowser, version 2.31.2 on Debian with 8GB RAM and 4 Intel Cores
Same issue occurs if I run the same docker image in a virtual machine on a different computer.

**Comment by danworsley** [comment]
Update on the issue and a temporary fix for others experiencing the same problem:

I had a brain fart moment last night and misunderstood the setting for 'max size of a request.' Now I know it actually controls the max chunk size, not the total file size limit!

Anyway, after reverting to the default setting of 10MB, I still encountered the same behaviour. I gradually reduced the limit by 1MB increments and found that I could upload a full file at a setting of 1MB. The downside is that my upload speed is now only 0.80MB/s, which isn't great, but I can cope with that for now.

If anyone else tries this, make sure to close your filebrowser tab and clear your browser's cache after changing the 'max size of a request' setting. Changes don't seem to take effect until you do this.

Developer, I would appreciate it if you could still look into this issue.
Thank you for all your support!

**Comment by danworsley** [comment]
A couple of videos showing the difference between chunk uploads set at the default 10mb and 1mb

The setting I refer to:
![Screenshot from 2024-10-20 08-54-30](https://github.com/user-attachments/assets/c8d3e5b2-996f-4630-8050-8d585191132a)

Upload with chunk size at the default 10mb:
[Screencast from 2024-10-20 08-53-19.webm](https://github.com/user-attachments/assets/8f3d4e43-59ea-48e9-aa46-da9b998f62cf)

Upload with chunk size at 1mb (works but results in slow upload speed):
[Screencast from 2024-10-20 08-52-00.webm](https://github.com/user-attachments/assets/a33fc060-ae02-47bd-8935-21be1e230a23)

**Comment by wwwutz** [comment]
Had the same problem. Maybe check if permissions for 'edit files' is unchecked, or `user.json` has `"perm": { ... "modify":  ` set to false.

At least setting it to true/allowing "edit files" fixed it for me.

In 2.27.0 an error message pops up with  "403 blabla" and 2.31.2 fails silently with 0 bytes.

**Comment by danworsley** [comment]
Thanks, I know what exactly what your talking about, I've come across that before but this is a different issue. My issue seems to be related to the chunked uploads process.

**Comment by parera10** [comment]
Do you have any web server in front of filebrowser? May be max body size parameter in your web server is blocking 10MB chunks. Usually it's set to 1MB by default.

**Comment by danworsley** [comment]
Thanks Guillem, I have Nginx configured to serve filebrowser under a reverse proxy, this is so I can run my website under www.mydomain and filebrowser under files.mydomain, I wouldn't have thought this would be throttling the connection, but I'll check nginx just to be sure and report back.

**Comment by danworsley** [comment]
Guillem, you was correct! I didn't realise nginx could be causing the issue. I've added the line '   client_max_body_size 100M' in the nginx configuration file for filebrowser, restarted everything and retested it, I've currently got Chunked Uploads set to 20MB and I'm now getting a consistent 14.0MB/s upload speed without any interruptions. Thank you very much for your help!! I will mark this thread as solved.

**Comment by boztasky** [comment]
Thank you very much, I was able to fix it with your method.
