### ISSUE TITLE
add an option to hide hidden files

### ISSUE THREAD

**Issue by lovelyjuice** [filebrowser/filebrowser#355]

**Comment by hacdias** [comment]
Why would we hide the hidden files? Aren't they hidden yet?

**Comment by eine** [comment]
No, they are not hidden yet. Example on play-with-docker:

![filebrowser_hidden](https://user-images.githubusercontent.com/6628437/36358248-7a23e658-150b-11e8-9642-eb6f45028c61.gif)

However, this might be a duplicate of #349.

**Comment by hacdias** [comment]
I'll close this then since it seems to be a duplicate of #349.
