### ISSUE TITLE
--disable-thumbnails and --disable-preview-resize not working as expected

### ISSUE THREAD

**Issue by parera10** [filebrowser/filebrowser#3553]
**Description**
I would like to disable all image resizing and thumbnails in order to boost listing folders with huge number of files (specially images). Similar as a 'ls -l' command. I'm using configuration parameters for this purpose:
```
  filebrowser config set --disable-preview-resize=true
  filebrowser config set --disable-thumbnails=true
  filebrowser config set --disable-type-detection-by-header=true
```

**Expected behaviour**
I expect a raw list of files, maybe with a default image icon, only with filename, size and last modified date.

**What is happening instead?**
All images are shown with their thumbnails and when you double-click on a image, you get a resized preview (you can see full size clicking on 'HD' icon.

**Additional context**
Exported config section:
```
    "server": {
        "root": "/data",
        "baseURL": "",
        "socket": "",
        "tlsKey": "",
        "tlsCert": "",
        "port": "8080",
        "address": "0.0.0.0",
        "log": "stdout",
        "enableThumbnails": false,
        "resizePreview": false,
        "enableExec": false,
        "typeDetectionByHeader": false,
        "authHook": "",
        "tokenExpirationTime": ""
    }
```

**How to reproduce?**
Quick boot filebrowser or init a database and apply 'filebrowser config set' actions:
```
  filebrowser config set --disable-preview-resize=true
  filebrowser config set --disable-thumbnails=true
  filebrowser config set --disable-type-detection-by-header=true
```
Now login and visit a folder with images. You will see the thumbnails.

**Comment by o1egl** [comment]
Those are cli params that should be provided when you run the app. `filebrowser --disable-thumbnails --disable-preview-resize`

**Comment by parera10** [comment]
Ok. Passing them as flags I get the expected behaviour.
Thanks for your help.
