### ISSUE TITLE
Regarding the inability to copy the sharing link under https connection on mobile devices

### ISSUE THREAD

**Issue by ShowUNow** [filebrowser/filebrowser#3556]
**Describe the solution you'd like**

If the shared link is really difficult to automatically copy to the clipboard under https connection, please display the shared link directly and let users copy it manually.

**Additional context**

Although we can now copy and share links on mobile devices via http connections, http is not secure. Unfortunately, I don't have enough expertise to contribute to this project. Maybe it's really difficult to copy a shared link via https on a mobile device. Because I found that this problem has been raised a long time ago. And it seems that it has not been solved so far. So I think it may be easier to solve this problem by directly displaying the shared link and letting the users copy it manually.

**Comment by Toucanto** [comment]
awesome idea. the only way ive been able to create new share links on mobile is by making any share link on desktop, send it to my phone, and replace the field in the middle of the template link for the share #; i can get from mobile. as i cannot get the link directly on mobile. 

honestly, i dont think this is an https issue either, i access my filebrowser with an https link on my desktop and it copies just fine.

**Comment by dr1pvfx** [comment]
I have the same problem, and havent gound a workaround using IOS and multiple browsers
