### ISSUE TITLE
Some files uploaded as 0B

### ISSUE THREAD

**Issue by CHooverShrimp** [filebrowser/filebrowser#3559]
**Description**
When I try to upload some files, for example a self-contained executable, or a TGA image, it will upload and display the file as 0B. Downloading the file will show the file as 0 byte. Opening with a text editor will show as blank.

**Expected behaviour**
I expected the files to upload and download normally.

**What is happening instead?**
Written above on the description flag

**Additional context**
![image](https://github.com/user-attachments/assets/90c5c2ca-0888-4638-bedb-85f48b878b5d)

I am not using the docker. I did curl and built it on ubuntu.
Some files work, such as mp4 and html.

**How to reproduce?**
Simply by uploading the file to the server via dragging/dialog

**Files**
Below is a sample I uploaded to the server that returned 0B
[P37 Low_FABRIC 1_FRONT_2070.003_Normal.zip](https://github.com/user-attachments/files/17533122/P37.Low_FABRIC.1_FRONT_2070.003_Normal.zip)

**Comment by o1egl** [comment]
Have you tried to reproduce an issue on https://demo.filebrowser.org/ ?

**Comment by CHooverShrimp** [comment]
Uploading the files to the demo website works.

**Comment by o1egl** [comment]
I assume you have some issues with your filesystem permissions or proxy configuration if you have one

**Comment by Mubelotix** [comment]
You miss this line in your nginx config

```
    client_max_body_size 50M;
```

Filebrowser should detect this and at least present an error to users

**Comment by GuyNoIRQ** [comment]
I just hit the same. Once I added the "Edit Files" permission to the affected user uploads began working as expected.

For context I'm running it under docker with a NFS mount servicing the /data/ and /srv/ dirs.

https://hub.docker.com/r/filebrowser/filebrowser
filebrowser/filebrowser:latest

`
me@docker:~$ docker exec -it FileBrowser ./filebrowser version

File Browser v2.31.2/129a4fd3
`

**Comment by CHooverShrimp** [comment]
> You miss this line in your nginx config
> 
> ```
>     client_max_body_size 50M;
> ```
> 
> Filebrowser should detect this and at least present an error to users

That might be it. I added the line to nginx and it starts working
