### ISSUE TITLE
Unable to use "/" as scope on linux

### ISSUE THREAD

**Issue by chanyk-joseph** [filebrowser/filebrowser#356]
3. What are you trying to do?
use "/" as scope, but the http response code is 410. No files/folders under path / is shown
but the folder can be browsed using direct URL, eg: http://xxxx:xxx/files/home/ to browse the /home

### 4. What did you expect to see?
http://xxxx:xxx/files/ should list files and folders under "/" if the scope is set to "/"

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Under linux, use "/" as scope

**Comment by hacdias** [comment]
Sometimes it can happen if filebrowser doesn't have permission to access a folder within `/`. Does it work with other paths?

**Comment by chanyk-joseph** [comment]
1. sudo is used to executed the filebrowser
2. filebrowser is working fine with other directory, eg: /home

Console log:


```[joseph@localhost Desktop]$ ls -ll /
total 24
lrwxrwxrwx.   1 root root    7 Sep 17 00:42 bin -> usr/bin
dr-xr-xr-x.   5 root root 4096 Sep 17 23:18 boot
drwxr-xr-x.  20 root root 3240 Feb 16 12:23 dev
drwxr-xr-x. 138 root root 8192 Feb 16 12:24 etc
drwxr-xr-x.   3 root root   20 Sep 17 00:49 home
lrwxrwxrwx.   1 root root    7 Sep 17 00:42 lib -> usr/lib
lrwxrwxrwx.   1 root root    9 Sep 17 00:42 lib64 -> usr/lib64
drwxr-xr-x.   3 root root   30 Sep 17 16:06 media
drwxr-xr-x.   2 root root    6 Nov  5  2016 mnt
drwxr-xr-x.   4 root root   49 Sep 17 23:24 opt
dr-xr-xr-x. 219 root root    0 Feb 16 12:23 proc
dr-xr-x---.   7 root root  229 Sep 18 14:34 root
drwxr-xr-x.  41 root root 1260 Feb 16 12:25 run
lrwxrwxrwx.   1 root root    8 Sep 17 00:42 sbin -> usr/sbin
drwxr-xr-x.   2 root root    6 Nov  5  2016 srv
dr-xr-xr-x.  13 root root    0 Feb 16 12:23 sys
drwxrwxrwt.  14 root root 4096 Feb 16 12:25 tmp
drwxr-xr-x.  13 root root  155 Sep 17 00:42 usr
drwxr-xr-x.  21 root root 4096 Sep 17 00:51 var
[joseph@localhost Desktop]$ sudo ./filebrowser --allow-edit --allow-new --no-auth --port 80 --scope="/"
Listening on [::]:80
2018/02/16 12:26:43 /: 410 Gone
2018/02/16 12:26:43 stat bin: no such file or directory
```

Browser Log:
![image](https://user-images.githubusercontent.com/28205157/36293459-f7fb08d4-1314-11e8-9e39-faa154b301b5.png)

When using direct URL of subdirectory, it is working fine:
![image](https://user-images.githubusercontent.com/28205157/36293481-21604c34-1315-11e8-8502-c9b22bdc81b5.png)

**Comment by hacdias** [comment]
I'll dig more into it. I think that there is some action File Browser is doing on root directory that it can't.

**Comment by hacdias** [comment]
A follow up: the same happens here.

**Comment by hacdias** [comment]
This problem is happening when trying to follow certain Symbolic Links on the Root Path.

https://github.com/filebrowser/filebrowser/blob/22327703fdf8c52287a42b5b2262193615230aef/file.go#L136-L144

To fix this, the code was updated to:

https://github.com/filebrowser/filebrowser/blob/df453ca6349166af3bc3c3a65e9d176e30605319/file.go#L136-L143

This way, instead of just failing, we stick with the link information instead of the target information.

**Comment by hacdias** [comment]
[v1.5.3 released](https://github.com/filebrowser/filebrowser/releases/tag/v1.5.3) 🎉!
