### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by juanqp07** [filebrowser/filebrowser#3561]
**Description**
When I restart the Docker container or turn it on after shutting down the server, I have to reconfigure everything; the settings aren't saved properly.

**Expected behaviour**
I want everything to be saved correctly without losing anything.

**What is happening instead?**
I don't have proof like logs (or I don't know if I could get them), but what happens is that when I restart or turn on the Docker container, the configuration is erased, and I don't know what to do.

**Additional context**
I have nothing else to say.

**How to reproduce?**
Try restarting the container and see if it happens to you.

**Files**
I don't have files (or don't know which ones would be correct for this).

**Comment by o1egl** [comment]
Docker container's filesystem is ephemeral. If you want to keep the state, you have to mount filebrowser db file from your host system. Check the docker command from the examples https://filebrowser.org/installation#docker

**Comment by juanqp07** [comment]
Yeah, but what happens is that if I change something in the container, like a port for example, everything resets to default and the configuration is lost, and I just realized this while testing. I have a directory where I store the files on my server.
