### ISSUE TITLE
File search is slow.

### ISSUE THREAD

**Issue by poc9999** [filebrowser/filebrowser#3563]
**Description**

File search is slow
<img width="944" alt="image" src="https://github.com/user-attachments/assets/5c981815-ae6f-4fd9-bdd0-73e578ab1009">

**Expected behavior**

My files are searched quickly among 1 million files.
<img width="617" alt="image" src="https://github.com/user-attachments/assets/ef1eea22-dd71-4732-8b0e-561ad5886b50">
Expected to have folder and file name indexes

**What is actually happening？**

Actually search is slow

**Additional context**

None

**How ​​to reproduce？**

100,000 files are nested, each containing 1,000 files. Search is very slow

**Files**

None

**Comment by poc9999** [comment]
Has this project been abandoned, no one is answering the questions

**Comment by gtsteffaniak** [comment]
@poc9999 try this out https://github.com/gtsteffaniak/filebrowser
