### ISSUE TITLE
got "Illegal instruction" when run on armel linux

### ISSUE THREAD

**Issue by higeon** [filebrowser/filebrowser#357]
I downloaded the arm version binary package from
https://github.com/filebrowser/filebrowser/releases/download/v1.5.2/linux-arm-filebrowser.tar.gz
But couldn't run it, I got the "Illegal instruction"

$ ./filebrowser --port 23333 --scope /data/share
Illegal instruction

What should I do for my arm base linux?
Below is my OS infomation

uname -a
Linux debian 4.9.0-5-marvell #1 Debian 4.9.65-3+deb9u2 (2018-01-04) armv5tel GNU/Linux
---

**Comment by Equim-chan** [comment]
Sorry, but you might have to build it on your own. `linux-arm-filebrowser.tar.gz` is targeted to armv6.

**Comment by higeon** [comment]
How to build it on my armv5 debian NAS which has only poor 64MB ram?

**Comment by Equim-chan** [comment]
Golang supports cross compile, so you don't have to compile it on the target machine.

1. Download and install [Go](https://golang.org/dl/).
1. `$ go get -d github.com/filebrowser/filebrowser/cmd/filebrowser`
1. `$ cd $GOPATH/src/github.com/filebrowser/filebrowser/cmd/filebrowser`
1. `$ env GOOS=linux GOARCH=arm GOARM=5 go build`

**Comment by helloray** [comment]
@Equim-chan Please consider adding armv5 to your official release. There are plenty of pogoplug devices using armv5 SOC. 
@higeon I have compiled an armv5 version for my pogoplug v4(armv5+128M ram). It runs smoothly.

**Comment by ikwyl6** [comment]
I had same problem with Illegal Instruction and using @Equim-chan directions above https://github.com/filebrowser/filebrowser/issues/357#issuecomment-366625310 solved my issue with using pogoplug ARM. Runs very fast!
