### ISSUE TITLE
custom.css appears to be cached somehow by FileBrowser

### ISSUE THREAD

**Issue by stecydube** [filebrowser/filebrowser#3600]
**Description**
Branding the server, I successfully set the logo and custom.css by following the documentation.
However, changing custom.css always returns the previous content no matter how I get it.
If even tried with CURL to bypass any caching.

**Expected behaviour**
Changing custom.css should give that css back when downloaded.

**What is happening instead?**
Same old custom.css always returned.

**Additional context**
Renaming custom.css to custom.xxx brings back the default css and then renaming back to custom.css does change the css of the server however, it's not the real content of custom.css on disk but some old content.

Inside a container.

**How to reproduce?**
Follow the doc, create custom.css in branding folder, set the branding folder in the web server UI

**Files**

**Comment by stecydube** [comment]
Arrrrrrggggghhhhhh

Cached by Cloudflare!

**Comment by ghost** [comment]
still having same issue
