### ISSUE TITLE
Bad request 

### ISSUE THREAD

**Issue by blackdev1l** [filebrowser/filebrowser#361]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes, 2 days ago

### 2. What is your entire Caddyfile?
```text
dev1l.tech

filemanager / 

```

### 3. What are you trying to do?

Any kind of operations is not allowed other than open files/folders.
For example changing my password gives me the alert "bad request"

### 4. What did you expect to see?

Succesfull modal

### 5. What did you see instead (give full error messages and/or log)?

Error modal

with -log "stderr" i have this: 
```
2018/02/22 06:34:15 /1: 400 Bad Request
2018/02/22 06:34:15 json: cannot set embedded pointer to unexported struct: http.modifyRequest
```

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

1. get the caddy server binary from the website with filemanager plugin included, 
2. use the caddy file above
3. try to change password 
4. ????
5. profit.

**Comment by cbf305** [comment]
I get the same thing trying to switch views, and the logs show the same error.

I also downloaded the Caddy binary from the website with the filemanager plugin included, about 10 minutes ago.  No other plugins were selected.

I am just running it directly from the CLI to play around with.  `./caddy filemanager`

**Comment by svenio** [comment]
I'm currently attempting to set this up as my primary cloud UI and encountered this yesterday. To test, I [just now] re-downloaded Caddy with the plugin and can confirm on all accounts. Any of the following actions result in a "Bad Request" modal:

- Change password
- Change view
- Enter custom CSS
- Create new user
- Change user scope
- Change user commands
- etc.

**Caddy version:** 0.10.11
**File Browser version:** 1.5.3

**My Caddyfile:**

```
localhost:8080  

filemanager / /tmp/caddy {  
    database            /tmp/caddy/data.db
    no_auth		false
    locale              en
    allow_commands      true
    allow_edit          true
    allow_new           true
    allow_publish       true
}
```

**Executed with:**

```
./caddy -conf=/tmp/caddy/Caddyfile -log=stderr
```

**Error msg:**
```
2018/02/22 13:43:02 /1: 400 Bad Request
2018/02/22 13:43:02 json: cannot set embedded pointer to unexported struct: http.modifyRequest
```

**Comment by Equim-chan** [comment]
This should have been fixed in 1.5.4, duplicate with https://github.com/filebrowser/filebrowser/issues/359. Please check out the latest version.

**Comment by svenio** [comment]
Thanks. Any idea when 1.5.4 will be available for Caddy?

![capture](https://user-images.githubusercontent.com/14263044/36578768-fb08dd3e-1824-11e8-9c66-b3c097f50702.png)

**Comment by hacdias** [comment]
Will update it now. Sorry guys 😞
