### ISSUE TITLE
Add tokenExpirationTime to settings.json for docker container

### ISSUE THREAD

**Issue by TheKing349** [filebrowser/filebrowser#3614]
**Is your feature request related to a problem? Please describe.**
I would like a way to customize the token expiration time within the settings.json. I use filebrowser as a docker container, and mount a settings.json, to customize my port and baseUrl, etc. However, I can't seem to find a way to customize the token expiration time when using a docker container. I need to upload lots of large files and cannot upload everything in 2 hours, and would like to not have to monitor and wait for the session to expire. I know there is the ```filebrowser --token-expiration-time "8h"``` if using filebrowser as a cli, but there is no way of implementing this using the official docker container and settings.json.

**Describe the solution you'd like**
I would like to see an optional addition to the settings.json where I can add this ```"tokenExpirationTimeout": "8h"``` to the settings.json file in addition to the rest of the configuration. 

**Describe alternatives you've considered**
I've considered to implement my own Dockerfile to manually set the ```token-expiration-time``` flag, but would want to make sure I have the latest features that the official filebrowser docker container offers.

**Comment by kloon15** [comment]
You can change the entrypoint when using docker compose:
```
filebrowser:
  entrypoint: /filebrowser --token-expiration-time "8h"
```

**Comment by TheKing349** [comment]
> You can change the entrypoint when using docker compose:
> 
> ```
> 
> filebrowser:
> 
>   entrypoint: /filebrowser --token-expiration-time "8h"
> 
> ```

Ohhh okay sweet! Thank you! I think still would be better if it was in settings.json but glad to see there is a way to do it! Thank you!

**Comment by TheKing349** [comment]
> You can change the entrypoint when using docker compose:
> 
> ```
> 
> filebrowser:
> 
>   entrypoint: /filebrowser --token-expiration-time "8h"
> 
> ```

Quick question though: would I need to then pass in the config and database with -c config.json and -d database.db, or because I mount those in the docker compose they would automatically use them?

**Comment by kloon15** [comment]
It gets used automatically like before, no other changes needed.

**Comment by TheKing349** [comment]
> It gets used automatically like before, no other changes needed.

Okay awesome! Thank you for your help!
