### ISSUE TITLE
How to select the last item on the mobile page

### ISSUE THREAD

**Issue by Pearlulu** [filebrowser/filebrowser#363]
![20180224143922](https://user-images.githubusercontent.com/5378519/36626612-bacd8fce-1970-11e8-927c-98aa901f2ba0.png)

The pop-up menu will block the last item. So you can not double-click the last file. I need to double-click to play the last video.
You can reproduce this on chrome. Thanks for the project!

**Comment by hacdias** [comment]
Fixed with v1.5.5 😄
