### ISSUE TITLE
Showing files fail when there are symbolic links

### ISSUE THREAD

**Issue by wjphero** [filebrowser/filebrowser#365]
my command is below:
/u02/test-agent/agent/filebrowser --no-auth --port 32032 --database /u02/test-agent/agent/filebrowser.db --scope / --commands "ls cd"
As result, I can see the root content / ,but can`t see anything in /var, but report "Something really went wrong.", and the background say:
  2018/02/25 20:29:48 /var/: 410 Gone 
  2018/02/25 20:29:48 stat lock: no such file or directory"

**Comment by Equim-chan** [comment]
Do you have proper permission on /var?

**Comment by wjphero** [comment]
I log into the linux with root and  run filebrowser, so I think filebrowser has the root permission. And I run the command: ls -al
drwxr-xr-x.  21 root root  4096 Feb 25 20:18 var

**Comment by Equim-chan** [comment]
I guess it's because of some special files in `/var`.

**Comment by wjphero** [comment]
yes, I got a result: 
if there are symbolic links(ln -s) in the directory and enter into the directory, then the filebrowser will show "Something really went wrong."

**Comment by wjphero** [comment]
hi  Equim-chan , is there a document to show how to compile the filebrowser. I had compiled the filebrowser but run to got some error below:
./example: line 1: syntax error near unexpected token `newline'
./example: line 1: `!<arch>'

**Comment by Equim-chan** [comment]
The simplest way is `go get github.com/filebrowser/filebrowser/cmd/filebrowser` (it may take a long time), and then you will have the binary under `$GOPATH/bin`.

**Comment by wjphero** [comment]
Thank you very much for the suggestion，and I have another question that why the binary I compiled is much bigger than the binary from yours, I have used  "go build" with the parameter -ldflags "-s -w"?
