### ISSUE TITLE
Show file copy progress

### ISSUE THREAD

**Issue by jivank** [filebrowser/filebrowser#367]
A useful feature would be being able to see a progress bar for file copy and possibly a speed indicator.
This is helpful when using a slow disk or FUSE mount.

**Comment by Equim-chan** [comment]
In addition, if progress visualization is implemented, I think pause-able upload can also be implemented passingly.

/cc @hacdias

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
