### ISSUE TITLE
symbolic links(ln -s) in the directory lead to the "Something really went wrong."

### ISSUE THREAD

**Issue by wjphero** [filebrowser/filebrowser#370]
I found that if there are symbolic links(ln -s) in the directory and enter into the directory, then the filebrowser will show "Something really went wrong."

my command is below:
/u02/test-agent/agent/filebrowser --no-auth --port 32032 --database /u02/test-agent/agent/filebrowser.db --scope / --commands "ls cd"
As result, I can see the root content / ,but can`t see anything in /var, but report "Something really went wrong.", and the background say:
2018/02/25 20:29:48 /var/: 410 Gone
2018/02/25 20:29:48 stat lock: no such file or directory"

how to handle it?

**Comment by Equim-chan** [comment]
Let's discuss it in https://github.com/filebrowser/filebrowser/issues/365.
