### ISSUE TITLE
能不能针对一些常用的文件配型配置几个默认的图标呢？

### ISSUE THREAD

**Issue by yanggis** [filebrowser/filebrowser#376]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Manager? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 4. What did you expect to see?

就是一些建议：
能不能针对一些常用的文件配型配置几个默认的图标呢？比如说pdf, word, ppt, jpeg图片等等，这样用起来更容易区分文件类型，管理起来更方便。

**Comment by Equim-chan** [comment]
这个设计已经存在于代码中了，然而好像后端没有准确地识别好文件类型，我检查一下原因，感谢反馈。（下次请写英文这样更多的人能看懂）

**Comment by Equim-chan** [comment]
已查明原因，不是我们这的问题，而是运行它的系统缺少一个比较全的 MIME 表(见[mime.TypeByExtension](https://golang.org/pkg/mime/#TypeByExtension))，安装 mailcap 应该能解决问题。

**Comment by yanggis** [comment]
Hi, thx for the fast response, but when I tried to install mailcap on ubuntu via the command "apt install mailcap", I got an error with info "Package 'mailcap' has no installation candidate", any idea to fix it?

**Comment by Equim-chan** [comment]
For Ubuntu install `mime-support` instead.
