### ISSUE TITLE
Better login, multi-user and user roles

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#38]
Create a new login system.

**Comment by captncraig** [comment]
Perhaps best to let caddy-native facilities handle logins. Basicauth is availible now. If you make something better I would like to see it availible for any app running under caddy.

**Comment by mholt** [comment]
^ True. Auth should be generalized so that it's just another Caddy middleware (there is an issue for it already). But since there is demand for a better auth system, feel free :smile:

**Comment by hacdias** [comment]
I would like something that allowed me to have more than one user.

**Comment by mholt** [comment]
Cool. I think https://github.com/mholt/caddy/issues/246 and https://github.com/mholt/caddy/issues/109 would be of interest. If that gets implemented, then your add-on wouldn't have to roll its own login.

I don't want you to stretch yourself too thin but if you feel like implementing a login system anyway, maybe you could consider writing a general-purpose middleware for it so any Caddy users could take advantage of it. Just an idea.

**Comment by hacdias** [comment]
That's great. Do you know if those issues are being worked?

**Comment by mholt** [comment]
I doubt it; I haven't heard anything in months.

**Comment by jnflint** [comment]
I'd like to see a simple authorisation middleware. A full blown login system would be rather more complicated especially if it needed to cater for a variety of use cases.
A authorisation system could be built around validating JWT and integrating to an external system that does the authentication and identity management. 
Something along the lines of https://github.com/auth0/nginx-jwt which provides authorisation for nginx acting as a reverse proxy. With JWT the middleware would be sessionless. Start basic and then extend it to handle validating additional claims and processing refresh tokens as well.

**Comment by hacdias** [comment]
I'll close this for now due its inactivity.
