### ISSUE TITLE
Error while executing command (behind NGINX)

### ISSUE THREAD

**Issue by Degot** [filebrowser/filebrowser#380]
I'm using docker images. It's behind NGINX Reverse proxy, which has next config:

```
location /files/ {
       proxy_pass http://10.0.3.75:58080/files/;
       proxy_buffering off;
       proxy_http_version 1.1;
       proxy_redirect off;

       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $http_connection;
       proxy_read_timeout 86400s;
       proxy_send_timeout 86400s;
       access_log off;
    }

```
baseUrl is set to /files

When I access filemanager with https://test.com/files/ and execute the command, it gives next error: `websocket: 'Origin' header value not allowed`

Everything is fine, when I access filemanager directly with http://10.0.3.75:58080.

**Comment by Equim-chan** [comment]
Try adding `proxy_set_header Host $host;`?

**Comment by Degot** [comment]
Thanks. It helped.
