### ISSUE TITLE
Unregister service workers on config change

### ISSUE THREAD

**Issue by rebolyte** [filebrowser/filebrowser#383]
Some feedback slightly related to #158: I just spent a few hours trying to figure out why my config changes weren't being reflected, and then why completely blowing away my Caddyfile to remove Filemanager was still showing me the admin interface (with browser devtools open, cache disabled). Eventually I realized that things are being served/cached in a *service worker*, so I had to manually go purge that. Then my new config worked. It would great if this were mentioned somewhere in the docs, or if there was a killswitch for the SW to re-register itself.

This package is amazing! Keep up the great work.

**Comment by hacdias** [comment]
We're not using SW anymore on v2. It will be released soon
