### ISSUE TITLE
Possible issue in filebrowser/http/download.go involving Archiver

### ISSUE THREAD

**Issue by unquietwiki** [filebrowser/filebrowser#384]
Hello all. Per https://github.com/mholt/caddy/issues/2069#issuecomment-373503116 , I was directed to report this here. It seems that with Archiver 2.0 as part of a recent Caddy build process, the following error prevents continuing with the build.

_vendor/github.com/filebrowser/filebrowser/http/download.go:75:11: ar.Write undefined (type archiver.Archiver has no field or method Write)_

**Comment by Equim-chan** [comment]
This shouldn't happen, since we already specified a special constraint in `Gopkg.toml`.

https://github.com/filebrowser/filebrowser/blob/281339337d007dc884c49e4f877e2f53e09dffd7/Gopkg.toml#L29-L34

What's your final `Gopkg.toml` for Caddy?

**Comment by unquietwiki** [comment]
@Equim-chan sorry for not replying sooner on this!


[Gopkg.toml.txt](https://github.com/filebrowser/filebrowser/files/1820471/Gopkg.toml.txt)

**Comment by Equim-chan** [comment]
Try changing
```
[[constraint]]
  name = "github.com/mholt/archiver"
  version = "2.0.0"
```

into the revision one I've shown above?

**Comment by unquietwiki** [comment]
@Equim-chan That seems to have worked; had to clear out some extra imports. Thank you so much for your help on this. 👍 

[Gopkg.toml.txt](https://github.com/filebrowser/filebrowser/files/1826984/Gopkg.toml.txt)
[modules.txt](https://github.com/filebrowser/filebrowser/files/1826985/modules.txt)
