### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by 122342256** [filebrowser/filebrowser#386]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Manager? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

**Comment by hacdias** [comment]
Could you just fill the form above, please?
