### ISSUE TITLE
args:3 - Error during parsing: Unknown directive 

### ISSUE THREAD

**Issue by TheChiefMeat** [filebrowser/filebrowser#389]
### 3. What are you trying to do?
Trying to run the commands listed here: https://filebrowser.github.io/configuration/

Specifically to set the database location:

`caddy filemanager -d /root/6666cd76f96956469e7be39d750cc7d9.db`

### 4. What did you expect to see?
Filemanager loading the database

### 5. What did you see instead (give full error messages and/or log)?
` args:3 - Error during parsing: Unknown directive '-d'`

**Comment by Equim-chan** [comment]
`-d` is for CLI. You need to specify that path in Caddyfile.

**Comment by TheChiefMeat** [comment]
Even when I do:

`caddy filemanager --database /root/6666cd76f96956469e7be39d750cc7d9.db`

like the https://filebrowser.github.io/configuration/ suggests, I still get the same error though.

**Comment by Equim-chan** [comment]
> You need to specify that path in Caddyfile.

You should read https://filebrowser.github.io/caddy/ instead.

**Comment by hacdias** [comment]
Take a look at the page @Equim-chan mentioned above. 😄 I'll close this
