### ISSUE TITLE
Permit read-only users to create sharing urls

### ISSUE THREAD

**Issue by danielloader** [filebrowser/filebrowser#390]
Right now it looks like only administrators can create sharing urls, is this true?
If so would it be possible to allow users to also, potentially as something you can enable/disable on the user management config?

Thanks

**Comment by Equim-chan** [comment]
Everyone can make share links. However it's not possible to limit who cannot make share links at the moment.

**Comment by danielloader** [comment]
I just created a new user and only gave it "Edit, rename and delete files or directories" permissions, and the share function is enabled when I log in as that user. Disabled it on the administrators account for that user and logged back in as that user and the share function is missing.

Is it reliant on being able to edit/delete the files? Was hoping to be able to share files from a read only user.

**Comment by ip75** [comment]
Yes. You are right. Unable to share files when user has read only access. It is very uncomfortable. Please explain where i can change code in sources to enable it.

**Comment by hacdias** [comment]
On 2.0 perms are more extensive and this can be customized. Will close this!
