### ISSUE TITLE
Optional compression types for share links

### ISSUE THREAD

**Issue by danielloader** [filebrowser/filebrowser#391]
Right now the download multiple files/directory feature allows a choice of compressors, would be nice to offer this for share links instead of only using zip. 

Rationale being I can't pipe a url of a zip into a decompressor since the end of the file is needed to decompress it.

**Comment by vitaliy-kuzmich** [comment]
@danielloader  https://github.com/browsefile/backend share links works like usual, you can view it, and download if needed, only restriction for zip format without compression, if needed I will enhance file formats.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
