### ISSUE TITLE
.avi cannot be played

### ISSUE THREAD

**Issue by zhentianxincun** [filebrowser/filebrowser#393]
1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Caddy 0.10.12+http.filemanager 1.7

2. What is your entire Caddyfile?
3. What are you trying to do?
.avi cannot be played. The server can be installed media player and mpc-be, can play itself.

4. What did you expect to see?
Play avi file on web page.

5. What did you see instead (give full error messages and/or log)?
6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Comment by Equim-chan** [comment]
It's mainly about your client (browser). filebrowser just embed the video in a `<video>` HTML tag, and does nothing with video decode.

**Comment by hacdias** [comment]
Or your operating system MIME Types don't set 'avi' to be a video file.

**Comment by zhentianxincun** [comment]
Many old videos are divx or xvid for avi containers. What are the simple solutions?

**Comment by hacdias** [comment]
This is only related to your browser not supporting the codec. I'm closing this due to the lack of activity.
