### ISSUE TITLE
I can't download .exe files

### ISSUE THREAD

**Issue by JarmoHu** [filebrowser/filebrowser#395]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
yes
### 2. What is your entire Caddyfile?
```text
http://67.216.207.188:80 {
	root /usr/local/caddy/www
	timeouts none
	gzip
	filemanager /Download /usr/local/caddy/www/aria2 {
		database /usr/local/caddy/filemanager.db
	}
}

http://67.216.207.188:81 {
	root /usr/local/caddy/www/aria2
	timeouts none
	gzip
}

http://67.216.207.188:82 {
	root /usr/local/caddy/www/aria2/Download
        timeouts none
        gzip
	browse
}

```

### 3. What are you trying to do?
I'm trying to download a file of ".exe"

### 4. What did you expect to see?
download it 

### 5. What did you see instead (give full error messages and/or log)?
![snipaste_2018-04-13_21-50-28](https://user-images.githubusercontent.com/34189831/38738435-be7eaa94-3f64-11e8-91c8-655cf51d22c1.png)
![snipaste_2018-04-13_21-50-11](https://user-images.githubusercontent.com/34189831/38738437-bf63de66-3f64-11e8-94b5-d36d2215ef5a.png)

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
You can change a file like ".txt" to ".exe" and download it.

**Comment by hacdias** [comment]
@hustarbor I can't reproduce this bug in any way. It's downloading fine here. Probably you have got some issues with your file permissions.

**Comment by JarmoHu** [comment]
It's usually error, but sometimes downloading fine. I don't know why.

**Comment by JarmoHu** [comment]
I think this is a question about "IP+HTTP". I tried "domain + HTTPS" and everything went fine.
