### ISSUE TITLE
More elegant and efficient way of user management

### ISSUE THREAD

**Issue by lewisxy** [filebrowser/filebrowser#401]
Filebrowser can only add user each at a time, which is not very elegant not efficient if I want to manage users on a large scale. So I purpose the following suggestions.
1. Add user group features to set some permissions (maybe not all permissions) to users within a certain group globally.
2. Create command line tools (or admin settings) that create users in batches. If user information is stored in `filebrowser.db`, then maybe some command line tool is more convenient.
3. Display customized banner/info for specific user (group)

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
