### ISSUE TITLE
Caddy only or arbitrary WebDAV servers?

### ISSUE THREAD

**Issue by paul-hammant** [filebrowser/filebrowser#403]
The README doesn't say what the relationship with Caddy is.

Page https://filebrowser.github.io/quick-start/ desn't say whether other WebDAV servers are supported.

**Comment by hacdias** [comment]
I'm a little bit confused. File Browser **is not** a WebDAV server.

**Comment by paul-hammant** [comment]
FileBrowser (given its command line nature) is a server on localhost?   The screenshot shows a domain name of `https://filemanager.web`. That is something in your `/etc/hosts` file routing to `127.0.0.1` ?

Much is unclear, despite the effort you've gone to in the documentation.

**Comment by hacdias** [comment]
@paul-hammant, yes, it is a server on localhost. You can choose in which port to listen to and which addresses ([check the config](https://filebrowser.github.io/configuration/)).

**Comment by paul-hammant** [comment]
OK, so couldn't install on an Apache somewhere? Nor a Nginx.  I could imagine wanting to do so, and host other apps on other directories within the same server.

**Comment by hacdias** [comment]
You can, you then need to proxy Nginx or Apache to File Browser.

**Comment by paul-hammant** [comment]
Fine, documentation could be better if it were extended to say "File Browser is not a WebDAV server, it is a standalone server-side web application that allows management of the files in a directory on the server. You can proxy from Apache/Nginx to it, but it maintains it's own user/password system"
