### ISSUE TITLE
Style errors on Safari

### ISSUE THREAD

**Issue by tufu9441** [filebrowser/filebrowser#404]
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?

Yes, about 2 days ago.

### 2. What is your entire Caddyfile?
```text
https://example.domain {
  root /usr/local/caddy/files
  log /usr/local/caddy/logs/filemanager.log {
    rotate_size 1
    rotate_age  14
    rotate_keep 5
    rotate_compress
  }
  timeouts none
  gzip

  filemanager / /usr/local/caddy/files {
    database /usr/local/caddy/files/filemanager.db
  }

  header / {
    Strict-Transport-Security "max-age=31536000;"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "DENY"
    Referrer-Policy "no-referrer-when-downgrade"
  }
}
```

### 3. What are you trying to do?

Login and use the File Browser via Safari 11.1 on OS X 10.11.6

### 4. What did you expect to see?

A normally rendered page.

### 5. What did you see instead (give full error messages and/or log)?

A page which has something wrong with the CSS?

![wx20180423-193523](https://user-images.githubusercontent.com/6790361/39124300-86d860d2-472d-11e8-9d18-69b17a5996b6.png)

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

I am not sure whether other users with Safari 11.1 on Mac can reproduce this behavior or not, but it works well when using Chrome on my Macbook, as well as Safari on iOS.

**Comment by itsthejb** [comment]
Seeing this also. It appears to be a common problem with the material icons:

* https://github.com/bramstein/fontfaceobserver/issues/52
* https://github.com/google/material-design-lite/issues/4382

**Comment by fdegraeve** [comment]
same problem with Safari :/

**Comment by Cotch22** [comment]
me too,Quark browser on mobile phone

**Comment by tufu9441** [comment]
And I encountered the same problem on IE11, Windows 10.

**Comment by itsthejb** [comment]
Great! I'll see if I can verify if this change fixes the issue as soon as possible

**Comment by itsthejb** [comment]
Confirmed fixed from my side

**Comment by itsthejb** [comment]
Confirmed from my end that icons are now working. Thanks a lot! Just one remaining style error I can see from the search box:

![screen shot 2018-05-23 at 22 45 46](https://user-images.githubusercontent.com/557391/40450228-4aa85110-5edb-11e8-8f51-d8a30dad4f38.png)
