### ISSUE TITLE
got "Illegal instruction" when run on armv71 linux

### ISSUE THREAD

**Issue by chenlm03** [filebrowser/filebrowser#409]
I downloaded the arm version binary package from
https://github.com/filebrowser/filebrowser/releases/download/v1.7.0/linux-arm-filebrowser.tar.gz
But couldn't run it, I got the "Illegal instruction"

./filebrowser --port 23333 --scope /mnt/ESD-USB
Illegal instruction

What should I do for my arm base linux?
Below is my OS infomation

uname -a
Linux RT-AC3100-3FC7 2.6.36.4brcmarm #44 SMP PREEMPT Fri Mar 23 10:00:10 CST 2018 armv7l Merlin-Koolshare

**Comment by eine** [comment]
@chenlm03 in the latest releases GOARM is used to produce multiple binaries for different ARM versions. Could you please try https://github.com/filebrowser/filebrowser/releases/download/v1.9.0/linux-armv7-filebrowser.tar.gz and let us know if it works for you?

**Comment by kevin335200** [comment]
It doesn't work for me with v1.10
v1.9.0 tested, same problem
It seems like all versions > 1.0.1 don't work
Linux R7000 2.6.36.4brcmarm #1 SMP PREEMPT Tue May 8 02:01:58 CST 2018 armv7l Merlin-Koolshare

**Comment by eine** [comment]
@1kevin335200 did you try the armv5 version as suggested in golang/go#18483?

**Comment by kevin335200** [comment]
Now yes and it seems to work. Thanks!

**Comment by eine** [comment]
Great! I'm closing this, as it seems to be an issue with that specific model.
