### ISSUE TITLE
don't upload folder

### ISSUE THREAD

**Issue by wmjan** [filebrowser/filebrowser#410]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

**Comment by eine** [comment]
@wmjan did you want to request something as #244? If so, could you please close this issue?

**Comment by hacdias** [comment]
@wmjan I'll close this in favour of #244
