### ISSUE TITLE
Submission: a systemd service file.

### ISSUE THREAD

**Issue by xcvista** [filebrowser/filebrowser#411]
This file might be useful for running filebrowser under Ubuntu and systemd:

```ini
[Unit]
Description=File browser: %I
After=network.target

[Service]
User=www-data
Group=www-data
ExecStart=/usr/local/sbin/filebrowser -c /etc/filebrowser/%I

[Install]
WantedBy=multi-user.target
```

Put configuration files under `/etc/filebrowser` directory, for example `default.yaml`, and execute:

```bash
sudo systemctl enable filebrowser@default.yaml.service
```

to start filebrowser on boot as a service.

**Comment by eine** [comment]
Closed in favour of filebrowser/filebrowser.github.io#5.

**Comment by Sgouws** [comment]
@xcvista Any advise for permissions on the database file?

I'm using the following systemd service file:

```
[Unit]
Description=File browser
After=network.target

[Service]
User=exampleUser
ExecStart=/usr/local/bin/filebrowser --database /ftp/filebrowser.db -p 80 -r /ftp/files -a [::]

[Install]
WantedBy=multi-user.target
```
When I try and start the service I get a `open /ftp/filebrowser.db: permission denied` error.

I've even set chmod 777 on the filebrowser.service file.

**Comment by beac0n** [comment]
@Sgouws exampleUser also must have the rights to access /ftp
