### ISSUE TITLE
Maybe change the default ICON of folder and file is more beatiful??!

### ISSUE THREAD

**Issue by andyhuai** [filebrowser/filebrowser#412]
This is very nice project, love it.

But the default theme is a little heavy, not very nice!
if change the icon like MAC Serria , I think is very nice.

Any idea to support theme in future ?

**Comment by andyhuai** [comment]
Or U can tell me how to change it myself,

**Comment by Equim-chan** [comment]
You can try setting the custom CSS.

**Comment by andyhuai** [comment]
@Equim-chan 
OK, I'll try it, is there any templates?

**Comment by hacdias** [comment]
@andyhuai there aren't any templates. The custom CSS you write is added to the default CSS. That way you can override or just add some rules you want.

**Comment by andyhuai** [comment]
@hacdias 
To overwrite default CSS? Now, where is default CSS, then I may know how to mod it

**Comment by hacdias** [comment]
@andyhuai [here](https://github.com/filebrowser/frontend/tree/master/src/css). It's split into many files.

**Comment by eine** [comment]
Closing in favour of filebrowser/frontend#24.
