### ISSUE TITLE
Failed to install in LXC Ubuntu 16 Container with Script

### ISSUE THREAD

**Issue by michacassola** [filebrowser/filebrowser#413]
### 3. What are you trying to do?
Install Filebrowser in a LXC Ubuntu 16 LTS with the autoscript.

### 4. What did you expect to see?
A finished installation.

### 5. What did you see instead (give full error messages and/or log)?
```
Extracting...
Putting filemanager in /usr/local/bin (may require password)
Failed to set capabilities on file `/usr/local/bin/filebrowser' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
Aborted, error 1 in command: $sudo_cmd $setcap_cmd cap_net_bind_service=+ep "$install_path/$filemanager_bin"
```

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Run a LXC Ubuntu 16 Container. Try the WGET script (tried with sudo and as root itself (sudo su before running)).

**Comment by hacdias** [comment]
Can't reproduce it.

![image](https://user-images.githubusercontent.com/5447088/40278634-b951b478-5c2c-11e8-940e-28f1ea9d13bb.png)

Could you try again? Might have been a temporary error

**Comment by michacassola** [comment]
I just tried on a fresh container (this time the underlaying system runs Ubuntu 18 with anewer kernel though) and it works with the curl method.

Maybe it was something else I had installed? I think I might have had easyengine running in the container...

**Comment by hacdias** [comment]
Glad it worked 😄
