### ISSUE TITLE
目录范围为中文时设置失败

### ISSUE THREAD

**Issue by ZXQ-Kyle** [filebrowser/filebrowser#414]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

**Comment by ZXQ-Kyle** [comment]
还有手机夸克浏览器登录时页面错乱

**Comment by the-eric-kwok** [comment]
请使用英语来报告bug
标题描述得不清不楚的，配置文件也没贴上，还用中文，你让开发者怎么回答你的问题？
