### ISSUE TITLE
Symbolic links shown as files

### ISSUE THREAD

**Issue by aswjh** [filebrowser/filebrowser#416]
### 1. 
yes.  
File Browser v1.7.0
### 2. 
```
filemanager /fm /mnt/sdb7/tmp/ {
    database            /mnt/sdb7/tmp/caddy/fm1.db
    #no_auth
    recaptcha_key       ""
    recaptcha_secret    ""
    alternative_recaptcha
    locale              zh-cn
    allow_commands      false
    allow_edit          false
    allow_new           true
    #allow_publish       true
    #commands            cmd1 cmd2...
    css                 /mnt/sdb7/tmp/caddy/d.css
}
```

**Comment by osatien** [comment]
if i am inside a directory link i cant copy up from that directory

**Comment by hacdias** [comment]
From @Idesousa (on https://github.com/filebrowser/filebrowser/issues/521):

> **Description**
> Filebrowser shows symbolic links to folders as files.
> 
> **Expected behaviour**
> Symbolic links to folders showing as folders.
> 
> **What is happening instead?**
> Symbolic links shown as files
> 
> **Additional context**
> Is this a glitch? Or is it made on purpose?
> 
> **How to reproduce?**
> Create a symbolic link in the scope.

**Comment by hacdias** [comment]
Tested and fixed on 2.0. Will be available as soon as it's released

**Comment by amitsax** [comment]
Is #521 this still an issue?
from official docker image of File Browser 2.9.0 on Ubuntu 20.04.1 host
Folder soft linked (ln -s) are showing as file and can't be browsed.

**Comment by daigonstar** [comment]
I am currently having the issue of soft symlinks showing as files and not folders.

Ubuntu 20.04 File Browser 2.11.0

**Comment by mkubicek** [comment]
Same here, directory symlink (ln -s) shown as file in File Browser.

filebrowser/filebrowser docker image 2.16.1

Suggesting to re-open this issue @hacdias

**Comment by sunkup** [comment]
Same. Symlinks (ln -s) are also for me shown as file in File Browser.
on docker filebrowser version 2.17.2

First time trying out filebrowser. Seems very cool and sturdy all in all otherwise. 
Anybody knows an older version that does not have this problem to use until it's fixed?

**Comment by TheCherry** [comment]
Have the same problem. I need a solution to give a User multiple directories (scope) from the root directory. In the UI I can give a user only one scope and that is a bit pointless in my scenario. So I tried it with sym links, but the above bug appears.

Please open this Issue again.

**Comment by aswjh** [comment]
On linux  2.20.1 works well.

**Comment by narenkulk** [comment]
I have the same issue. symbolick links are shown as files and don't open in filebrowser.

**Comment by dafufer** [comment]
Just for info. For me the symbolic link works if I use a relative path. If I use the full path it shows up as a file

**Comment by EspiFreelancer** [comment]
As dafufer says, a symbolic link with a relative path works in Docker:
`ln -rs $HOME/my_dir/PDFs Public` inside the shared folder of FileBrowser.

Where `PDFs` is the folder that I want to share, and `Public` the name of the symbolic link.

Then, we can see:

`ls -l`
`lrwxrwxrwx 1 name gname    6 apr 25 11:26 Public -> ../PDFs`
