### ISSUE TITLE
[Suggestion] New Logo Icon For filebrowser

### ISSUE THREAD

**Issue by timonss** [filebrowser/filebrowser#417]
Hi, I want to contribute to his project, I want to design a logo, do you want it?

**Comment by Equim-chan** [comment]
Yes, it's welcome!

**Comment by timonss** [comment]
I created a logo icon for your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then let me know and I'll change it.

![logo](https://user-images.githubusercontent.com/39112161/39964189-ef2591e8-56a8-11e8-8760-db53960ed7a0.jpg)

**Comment by timonss** [comment]
I've created a logo, with different colors, what do you think? which one do you like?

**Comment by hacdias** [comment]
Thanks @timonss. I really like the one from the left, but I'm a bit unsure about the colors. What do you think @Equim-chan?

**Comment by Equim-chan** [comment]
I prefer the right one, but I think the blue can be a bit brighter maybe? (not really good at visual design)

**Comment by timonss** [comment]
Do you really choose that from the left (light blue). And which part do you think I need to change? The color it?

**Comment by timonss** [comment]
How about this?. If you like it, I will send you the original file.

![filebrowser2](https://user-images.githubusercontent.com/39112161/40092289-ba5ef1bc-58e6-11e8-9e27-118e564be251.png)

**Comment by hacdias** [comment]
I really love this one!

**Comment by timonss** [comment]
Okay, I've uploaded that logo to the drive, you can download it on this link :
https://drive.google.com/drive/folders/1GR2WDhgNPZ4ANg00ggo9vf_PGXhfKCeb

**Comment by hacdias** [comment]
@timonss I'd like to suggest something though and I want your feedback of course: use the light blue on the circle for the diskette and change the inner circle color to white. Could you try that?

**Comment by timonss** [comment]
What do you mean: The outside circle I change to a light blue color and the inner circle I change to white color, is that so?

**Comment by hacdias** [comment]
![image](https://user-images.githubusercontent.com/5447088/40202596-5fa9baba-5a1a-11e8-9732-0f62bde99e5c.png)

Sorry:

1. White
2. The blue from 1

**Comment by timonss** [comment]
Is this what you mean ??

![icon](https://user-images.githubusercontent.com/39112161/40266023-f9f6884c-5b6d-11e8-8175-0933fb008922.jpg)


![master](https://user-images.githubusercontent.com/39112161/40266029-1093b82c-5b6e-11e8-8525-1b68fb51d5e7.jpg)

**Comment by hacdias** [comment]
Yeah, what do you think?

**Comment by timonss** [comment]
It looks more cool and beautiful to look at. 
What if I now uploaded the original file to the driver and there you can download it.

**Comment by hacdias** [comment]
Yeah, sure @timonss! Thanks 😃

**Comment by hacdias** [comment]
Is it possible to get it in SVG?

**Comment by timonss** [comment]
Sure, Here you can get it:
https://drive.google.com/drive/folders/1gjsUgQeRCR6d1OeSVoePJYR4fvcsqMeN

I feel happy if you use this logo on your project.

**Comment by eine** [comment]
@timonss the new logo is added to the master branch now. See https://github.com/filebrowser/filebrowser , https://github.com/filebrowser/filebrowser/tree/master/logo and #444.

Thanks for your contribution!

**Comment by DeAlexPesh** [comment]
sorry, but the old icon was better..

**Comment by eine** [comment]
@DeAlexPesh since we are using git as a version control system, you can easily keep the old version. Just make a fork, and remove the commits you don't like. You can also add your own if you prefer (related to #420).

**Comment by hacdias** [comment]
One thing that I forgot to ask @timonss that is very important: under which license is the Logo?

**Comment by DeAlexPesh** [comment]
@1138-4EB thanks, already saved the old version of [icon.svg](https://github.com/DeAlexPesh/filebrowser-frontend-ru/blob/master/logo.svg)
The new logo has too many small details, in the future it will turn into a headache..

**Comment by eine** [comment]
@DeAlexPesh I both agree with you and prefer the new design at the same time. The previous one was too simple for me and I considered it to be more of a placeholder than an actual logo that identifies the project uniquely. I think that the one we have now is an attractive logo for pads, smartphones, etc. (see filebrowser/frontend#9), even though it can be tricky as a favicon/icon.

Anyway, as I said, I believe that #420 is the way to go, so that the base app can be tailored to different contexts. Indeed, I just saw that @hacdias created [filebrowser/logo](https://github.com/filebrowser/logo), which I believe is meant to push in that direction.

**Comment by hacdias** [comment]
Yes, I have to take care of #420!

@1138-4EB yup, I created that repo to centralize our logo assets there instead of leaving them in this repo and with time we can create the versions for each purpose.

**Comment by timonss** [comment]
@1138-4EB .Very happy to contribute with you. 😁😁

**Comment by wavemop** [comment]
> Sure, Here you can get it: https://drive.google.com/drive/folders/1gjsUgQeRCR6d1OeSVoePJYR4fvcsqMeN
> 
> I feel happy if you use this logo on your project.

I like! - you still got a vector-image of this one.
Would love to have it for a crisp "Homer" logo instead of all the bad images I googled so far!? ( I think you gdrive link is deprecated ) 
**Thx!**
