### ISSUE TITLE
Filebroswer Stop working after closing terminal

### ISSUE THREAD

**Issue by Yusadolat** [filebrowser/filebrowser#418]
How can I keep file browser working after closing my Laptop terminal?

**Comment by Equim-chan** [comment]
nohup(1)

**Comment by Yusadolat** [comment]
You say?

**Comment by helloray** [comment]
Try to google "nohup" or "screen".

**Comment by eine** [comment]
- https://en.wikipedia.org/wiki/Terminal_multiplexer
- https://en.wikipedia.org/wiki/GNU_Screen

**Comment by the-eric-kwok** [comment]
Add a symbol `&` to the end of the command line
like
`caddy -conf Caddyfile -root /tmp &`
or try `screen`

**Comment by Korbeil** [comment]
You can also use something like [supervisord](http://supervisord.org/) which will restart the process if needed.

**Comment by eine** [comment]
I'm closing this because multiple alternatives have already been given. Feel free to continue the discussion.
