### ISSUE TITLE
Custom branding, logo/favicon, turn off github link.

### ISSUE THREAD

**Issue by cashflys** [filebrowser/filebrowser#420]
Greetings, 

This is an excellent project and I would like to ask if it would be possible to allow some custom branding in either the command line or config files?  It would be great if it was possible to point the application to a custom favicon file and logo file when integrating this software into a client solution.  The other item that would be nice to have would be the option to turn off hyperlinks.  Having FileBrowser there is fine, but the hyperlink causes issues with external web calls.  It would be great if the "Help" under that was a slightly larger font.  I am not trying to be picky as I have no ability right now to contribute to the code other than cups of coffee.  However, as suggested by Henrique, I am posting these feature requests here.

Thank you for keeping the package fairly light weight as I am currently testing this as a solution for a problem on some embedded devices that I need to remotely manage a couple of files in a very "user friendly" fashion.

Best wishes all!

C

**Comment by cashflys** [comment]
I have accomplished some of the above through customs CSS in the various profiles.  This is adequate for my needs but not eloquent.  Since not all browsers treat overlay css the same (MS Edge...) it doesn't behave the same all the time.  I would still love to see some options in the code itself to support the above versus relying on css.  Best wishes, C

**Comment by hacdias** [comment]
Status update: after checking out the code and seeing what we need to change, this will actually be more complicated than I thought it would be initially and will require some changes here and on the frontend repository.

**Comment by hacdias** [comment]
Starting this on https://github.com/filebrowser/filebrowser/pull/456.

**Comment by hacdias** [comment]
This is not as easy as it seems since we would need to be passing files from the server-side and dump them into `index.html`. It would be easier to have instructions telling people how to build a custom build with custom Branding but that would also require the user to maintain it's own build system (we could create a script to simplify).

What do you think @1138-4EB @cashflys?

**Comment by eine** [comment]
@hacdias, according to the README of go.rice, we can take advantage of the [order of precedence](https://github.com/GeertJohan/go.rice#order-of-precedence) to implement this. The default build embeds the logo and favicons as go source (`rice-box.go`). However, should these be left out and should we distribute them either as an appended ZIP or as a sibling dir, it should find them as well.

As a first step, we can move the logo and favicons from filebrowser/frontend to filebrowser/logo, and have them copied before building the frontend. This would allow any user to clone filebrowser/logo and modify the images. Then, the build process in #399 should work.

Furthermore, we can split `rice-box.go` to `rice-box.go` and `rice-logo.box`, and provide two builds: one with `rice-box.go`only and a second one with both of them. The latter would be equal to the current release.

However, we still need to come up with a scheme that lets us merge #399 without breaking the integration with the caddy build server.

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
