### ISSUE TITLE
Add Guest Mode

### ISSUE THREAD

**Issue by the-eric-kwok** [filebrowser/filebrowser#425]
My English is bad, i'll try to explain what I want.
I wanna set up a file publish site with caddy and filemamager plugin, so I want to visit the files without login (in guest mode, can't edit, new, only download permission is given). And I also wanna login with a login button, and manage all my files with user Admin. 
**So above all, I want the visitor can see the public files in default user Guest, and I can also login to Admin and manage all my files.**

Thank you!

**Comment by fn-ix** [comment]
Came here to request the exact same feature! I've been using [Encode Explorer](http://encode-explorer.siineiolekala.net/) to the same ends, but the design is a bit dated.

**Comment by YasserDRIF** [comment]
a workaround to get this working is to make two instance of the filebrowser.exe with different config files running on different ports... one with AUTH and edit enabled (your admin dashboard) and the other disabled (guest mode)

**Comment by vitaliy-kuzmich** [comment]
@the-eric-kwok @hfel https://github.com/browsefile/backend has external link share, basically you just send the link, the server will detect share by link key, and display it like for usual user.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by rpatel3001** [comment]
please reopen this, I would like to use filebrowser but need this feature. I want to be able to login via the proxy method but allow share links to be accessible by unauthenticated users.

edit: I was able to work around this in my proxy by whitelisting the whole domain for no authentication except the following paths
* /login
* /api/login
