### ISSUE TITLE
Add successful and failed logins (and IPs) to log File (fail2ban)

### ISSUE THREAD

**Issue by nicedreams** [filebrowser/filebrowser#426]
Like the software a lot and thank you for offering it and supporting open source.  I like how easy it is to use as a file manager between friends and sending files to others with temp link that expires when needed.

Running it on DigitalOcean VPS and have created a systemd service file for running it all the time.

*Was hoping you could add a log file for successful and failed logins and log the IP address?

Want it for fail2ban so I can create a filter and have it scan the log file and ban the IP of who ever is trying to brute force the login page.  If you know fail2ban and can create a filter that'd be cool too.

www.fail2ban.org

**Comment by nicedreams** [comment]
Don't know if I can bump this post, but be a nice feature to have for security.  I'm afraid to open the port for long period of time on my cloud host since can't tell how many bots trying to access the login page.  I just see a bunch of "403 Forbidden" in the log, but no clue who or what is trying to login.  Unless there's another way to get this info I don't know about then can get fail2ban to start blocking these bots.

**Comment by hacdias** [comment]
We added the IPs on the newer version. Will be available when 2.0 is out

**Comment by nicedreams** [comment]
This is great.  Thank you!
