### ISSUE TITLE
[bug]can`t visit second-level directory web site when use filebrowser

### ISSUE THREAD

**Issue by ixjx** [filebrowser/filebrowser#429]
My Caddyfile like this:
```
filemanager / {
        show /srv/file
        allow_new true
        allow_edit true
        allow_commands false
}
```
And my web site is in another directory like /srv/xxx.

When I try to visit my second-level directory web site when use filebrowser, I get "This location can't be reached"

**Comment by hacdias** [comment]
Could you activate logging so we can take a look at the error that might be happening? Probably you just need to activate Caddy logging (for stdout for example), and you can see what's happening.

**Comment by ixjx** [comment]
THX,and this problem have been solved :)
I just modified the baseURL from / to /file
