### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by ncresswell** [filebrowser/filebrowser#430]
I note that links shared with other people can have ?dl=1 appended to them, to allow direct download without having to click on the file first. Do you also support ?raw=1 so that the file renders in the browser window, rather than downloads?

**Comment by Equim-chan** [comment]
This is a good idea, though not all types of files are renderable.

**Comment by hacdias** [comment]
Yeah, but we can easily support `raw` and let the browser decide what to do with the file. If it's previewable, it is rendered, otherwise, it is downloaded.

**Comment by hacdias** [comment]
@ncresswell actually, this is feature is kind of implemented: instead of `raw`, try the following: `?dl=1&inline=true`. If it solves the issue, could you close it please?

**Comment by ncresswell** [comment]
Is there a list of supported search operators?

Rgds,

Neil Cresswell

On 2/06/2018, at 7:44 PM, Henrique Dias <notifications@github.com<mailto:notifications@github.com>> wrote:


@ncresswell<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ncresswell&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=0fx0h4vB56iTLpw2McH1ZD6TqG_QGpbggVOB-PfMJpM&m=8_FVYz0i37uxn8teGIZNvSmTOBQp-9l8i1sOtYTimQ0&s=i5LNuMTjZoZphkxTWr8IntPOKVyBY7Sr6VV_SPCnFuw&e=> actually, this is feature is kind of implemented: instead of raw, try the following: ?dl=1&inline=true

**Comment by hacdias** [comment]
There isn't, but here's what you can do on **sharing** pages:

- `dl`:
	- 0 or not present - displays the button to download.
	- 1 - automatically downloads.

The other options come from download API:

- `inline` - if true, let's the browser decide what to do with the file instead of directly downloading it.
- `format` - can be zip, tar, targz, tarbz2 or tarxz. Only works for directories.

**Comment by yumere** [comment]
@hacdias 
filebrowser is a awesome tool for me. I, however, want to share pdf and then also want the user given link can see pdf directly in browser. I just wonder your plan when you'll make inline option?

**Comment by hacdias** [comment]
You can append `?dl=1&inline=true` to the URL so the PDF is directly previewed on the browser.

**Comment by bonny1992** [comment]
Sorry for bringing up this old issue.

What about multiple "Share" links? Like, you select multiple files, then by the share button you can get a compressed single link, or a list of links.
Also, is there any way to make it compatible with download managers like Jdownloader?

**Comment by eine** [comment]
Hi @bonny1992, can you please open new separate issues for your requests?

**Comment by bonny1992** [comment]
Sure, @1138-4EB ! Sorry for the hassle!
