### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hechuan4** [filebrowser/filebrowser#432]
> ###

 Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

**Comment by hacdias** [comment]
Hello @FJHC, I need more details to know what might be wrong in order to solve this problem.

**Comment by kzw200015** [comment]
I face the same problem when I try to manager users.When I click "save",it showed the error message.Here is caddyfile
```
 pan.***.top {
    root /var/www/pan
    gzip
    timeouts none
    tls ***@gmail.com
    filemanager / /root/download {
        database /var/www/pan/filemanager.db
    }
}
```

**Comment by hacdias** [comment]
Could you activate the log option so we can check out which errors might be happening?

**Comment by kzw200015** [comment]
Problem solved.It is my fault.I set `Protect Home`to `true` in the systemd unit.It causes that caddy can't read or write.
