### ISSUE TITLE
Moving file to hard drive error

### ISSUE THREAD

**Issue by Benoit-Julien** [filebrowser/filebrowser#434]
### 1. Have you downloaded File Browser from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Browser's repository?
I updated my server today.

### 2. What is your entire Caddyfile?
```text
0.0.0.0:8080 {
  filemanager / /home/julien {
    no_auth
    commands chmod
  }
}
```

### 3. What are you trying to do?
I try to move a file to a hard drive.

### 4. What did you expect to see?
I expected that the file move to the hard drive.

### 5. What did you see instead (give full error messages and/or log)?
Error : Internal Server Error

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Connect a hard drive to the server and try to move a file to it.

**Comment by eine** [comment]
@Benoit-Julien could please provide some more info so that we can reproduce the error? What messages do you get either in the browser console or in the terminal where filebrowser/caddy are being executed? Is the hard drive mounted in a dir inside the scope (i.e. `/home/julien`)?
