### ISSUE TITLE
UC Mobile Browser Issue

### ISSUE THREAD

**Issue by helloray** [filebrowser/filebrowser#437]
UC Mobile is one of the most popular mobile browsers in China. However, filebrowser does not work correctly on it.  I searched the vue issue list and found this issue https://github.com/vuejs/vuex/issues/519. It said adding babel-polyfill could solve this issue. Could you please help to add it and resolve this issue? Thanks a lot.

You can download UC mobile from https://play.google.com/store/apps/details?id=com.UCMobile.intl

**Comment by Equim-chan** [comment]
Duplicate with #261
