### ISSUE TITLE
Add user register page or API for adding users 

### ISSUE THREAD

**Issue by F-TD5X** [filebrowser/filebrowser#439]
Though there is a multi user managment, it is hard to add many users.
So I hope you can add a register page or some api for adding user.

And maybe it is necessary that filemanager should create a folder for a user and change it's scope after which is added.

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
