### ISSUE TITLE
Add Bootstrap Website instead of blank website

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#44]

**Comment by klingtnet** [comment]
I would argument against this. Users should explicitly state the `style` they want to use. Boostrap is also fairly large, if so we should use something minimal like [skeleton](http://getskeleton.com/).

**Comment by justrjlewis** [comment]
If anything...some basic sample content with a simple theme [Cocoa](http://themes.gohugo.io/cocoa/), or maybe [Type](http://themes.gohugo.io/type/), or [Pure Hugo](https://github.com/dplesca/purehugo).

**Comment by faddat** [comment]
The basic sample content is a really great idea, it provides users with a framework when they get started.  Making that obvious helps tremendously in usability.  That way, the user can tinker and see the results of changes progressively.  

I'm really digging this theme:  
https://github.com/SenjinDarashiva/hugo-uno/

Maybe that's a decent default?  :)

**Comment by hacdias** [comment]
Maybe. We've to choose a very simple one. There is a [website](http://themes.gohugo.io/) with some Hugo themes.

**Comment by jlsjonas** [comment]
I would've also preferred a bootstrap/skeleton as default; also (or as a start) an (empty) 'theme' options in the config would help hinting where the theme should go (and indicate that a theme is required) for newer users; especially since theme's tend to suggest the `hugo -t` command-line parameter

**Comment by hacdias** [comment]
Hey @jlsjonas,

Thanks for your suggestion. It seems to be a very good choice indeed. That what I'll probably do. Now I'm   a little busy with school exams but later this month I'll do that. 

---

I've also another idea: create a "section" in the interface where you can download themes and install them into your website. Do you like it?

**Comment by faddat** [comment]
@hacdias, I very much like the theming concept.

**Comment by hacdias** [comment]
Moved to #77.
