### ISSUE TITLE
Add multi-arch Docker images (for ARM architectures)

### ISSUE THREAD

**Issue by airtonix** [filebrowser/filebrowser#440]
```
HypriotOS/armv7: pirate@black-pearl in ~ 
$ docker run --rm -i \
  -v /mnt/storage/store:/store \
  -v /mnt/storage/filemanager/config.json:/config.json \
  -v /mnt/storage/filemanager/database.db:/database.db \
  -e USER_ID=1000 \
  -e GROUP_ID=1000 \
  -p 3000:80 \
  hacdias/filebrowser
```

Some seconds pass by...

```
standard_init_linux.go:190: exec user process caused "exec format error"

HypriotOS/armv7: pirate@black-pearl in ~
$
```

```
HypriotOS/armv7: pirate@black-pearl in ~
$ uname -a
Linux black-pearl 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux
HypriotOS/armv7: pirate@black-pearl in ~
$ docker -v
Docker version 18.04.0-ce, build 3d479c0
HypriotOS/armv7: pirate@black-pearl in ~
$ docker-compose -v
docker-compose version 1.21.1, build 5a3f1a3
```

**Comment by pltanton** [comment]
Why can't you just slightly change [one line](https://github.com/filebrowser/filebrowser/blob/e3162e7170f329f37a13f7a64c2b760086e7692d/Dockerfile#L7) in Dockerfile by yourself?

**Comment by airtonix** [comment]
@pltanton Yes, I guess I could. But then the official Docker image for `FileManager` would still not be [multi arch](https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/).

also this: https://stackoverflow.com/questions/39432668/travis-multi-architecture-buiilds

**Comment by eine** [comment]
@airtonix, do you have any working example of building an ARM image in travis or any other ci platform? If so, I'd be glad to accept a PR on top of #399.

https://goreleaser.com/customization/#Docker, goreleaser/goreleaser#707 and goreleaser/goreleaser#530.

**Comment by Pandry** [comment]
I build my own Dockerfile for my Pi3, if you want it I can share it :)

**Comment by rhyst** [comment]
> Why can't you just slightly change [one line](https://github.com/filebrowser/filebrowser/blob/e3162e7170f329f37a13f7a64c2b760086e7692d/Dockerfile#L7) in Dockerfile by yourself?

I would like to do this so I do not need to wait for this issue to be resolved, but I can't see a go dep build for arm? What did you have in mind?

**Comment by eine** [comment]
@rhyst, `go dep` is not used anymore. No vendoring solution is being used ATM. See https://github.com/filebrowser/filebrowser/pull/496#issuecomment-414877673. See also (#450):

>  Extend goreleaser to build multiarch images. See goreleaser/goreleaser#707 and goreleaser/goreleaser#530.

**Comment by rhyst** [comment]
Thanks @1138-4EB . I made an alpine docker image that uses the install script mentioned in the docs and that seems to work.

```
FROM arm32v6/alpine:3.7
RUN apk add curl bash git
RUN curl -fsSL https://filebrowser.github.io/get.sh | bash
RUN mkdir /config
COPY config.json filebrowser.json
RUN mkdir /db
VOLUME ["/db"]
EXPOSE 80

ENTRYPOINT ["filebrowser"]
```

**Comment by TheRogueZeta** [comment]
@rhyst 

Do you know if your instructions still work? I just tried doing the following and got an error:
```
$ docker build -t local/filebrowserarm .
Sending build context to Docker daemon  2.048kB
Step 1/9 : FROM arm32v6/alpine:latest
 ---> 5a1d65b7d26b
Step 2/9 : RUN apk add curl bash git
 ---> Using cache
 ---> e7ad77cf5af7
Step 3/9 : RUN curl -fsSL https://filebrowser.xyz/get.sh | bash
 ---> Running in 291ce35188f2
Downloading File Browser for linux/armv7...
https://github.com/filebrowser/filebrowser/releases/download/v2.0.9/linux-armv7-filebrowser.tar.gz
Extracting...
Putting filemanager in /usr/local/bin (may require password)
Successfully installed
Removing intermediate container 291ce35188f2
 ---> 281ed1233a7b
Step 4/9 : RUN mkdir /config
 ---> Running in 59ad1b2397e4
Removing intermediate container 59ad1b2397e4
 ---> 7607698013b9
Step 5/9 : COPY config.json filebrowser.json
COPY failed: stat /var/lib/docker/tmp/docker-builder282131657/config.json: no such file or directory
``` 

And this is the dockerfile
```
$ cat dockerfile 
FROM arm32v6/alpine:latest
RUN apk add curl bash git
RUN curl -fsSL https://filebrowser.xyz/get.sh | bash
RUN mkdir /config
COPY config.json filebrowser.json
RUN mkdir /db
VOLUME ["/db"]
EXPOSE 80

ENTRYPOINT ["filebrowser"]
```

**Comment by rhyst** [comment]
@ZetaPhoenix Seems to still work!

Have you got a `config.json` file in the same directory as the Dockerfile? Thats what the error looks to be about. Mine looks like:

```
{
  "port": 80,
  "noAuth": false,
  "baseURL": "/files",
  "address": "",
  "alternativeReCaptcha": false,
  "reCaptchaKey": "",
  "reCaptchaSecret": "",
  "database": "/db/database.db",
  "log": "stdout",
  "plugin": "",
  "scope": "/srv/",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": [
    "git",
    "svn"
  ]
}
```

**Comment by TheRogueZeta** [comment]
I did not. Would it not make sense to pass the config in as a volume instead of building it in?

**Comment by rhyst** [comment]
If you need to change it then that makes sense but so far I haven't had to edit it. I think just remove the copy command if you want to do that.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by CoolSpot** [comment]
> I'm closing this since this repository will be archived. Please read the information on the README for more information.
@hacdias , could you please clarify what you meant?

The main Readme file does't have anything about multi-arh or this repository being archived.
Official website lists this GitHub repository as the main contribution point.

For others like me looking for multi-arch docker image, this one - [hurlenko/filebrowser](https://hub.docker.com/r/hurlenko/filebrowser) seems to be most popular and up to date.

**Comment by hacdias** [comment]
@CoolSpot please note that I said that in January 2020. Ref issue #532. Fortunately, @o1egl managed to revive the project after I took the decision to close the repository.
