### ISSUE TITLE
Simple installation + Russian language + editable frontend

### ISSUE THREAD

**Issue by DeAlexPesh** [filebrowser/filebrowser#445]
# Description here:
https://github.com/DeAlexPesh/filebrowser-frontend-ru

**Comment by hacdias** [comment]
Hey @DeAlexPesh! That's very nice. Could you make a PR with the Russian translation on [frontend](https://github.com/filebrowser/frontend)?

**Comment by DeAlexPesh** [comment]
@hacdias, [PR](https://github.com/filebrowser/frontend/pull/14)
