### ISSUE TITLE
Feature requests - single click mode on MobilePhone

### ISSUE THREAD

**Issue by ixjx** [filebrowser/filebrowser#449]
When I used filebrowser on my mobliephone, I found it's hard to enter a folder or open a txt file or play a mp4 , because you need to double-click the folder/file **very very very** quickly. 

There is a issue #419 @ikwyl6 asked for the same feature.

Thanks for the great project and I hope it`s easy to use on the moblie device :)

**Comment by eine** [comment]
Also suggested in https://github.com/filebrowser/filebrowser/issues/314#issue-284780299.

**Comment by eine** [comment]
Closing in favour of #419.
