### ISSUE TITLE
new file | auto date and title

### ISSUE THREAD

**Issue by k1ngf15h3r** [filebrowser/filebrowser#45]
when creating a new md file at the backend using post.md:archetype there are no auto created date field and title field created from filename is missing

**Comment by hacdias** [comment]
**Note**: https://github.com/spf13/hugo/blob/master/create/content.go#L35

**Comment by k1ngf15h3r** [comment]
okay I understand just a little bit of it ... mostly I programm in windows c# and powershell ;)

**Comment by hacdias** [comment]
Ahah... I just commented that so I can remember what to see later. It's a note for myself. Don't worry :)

**Comment by k1ngf15h3r** [comment]
okay ;) then I will wait what you will be building =)
