### ISSUE TITLE
static/js/codemirror/mode/markdown/markdown.js 404

### ISSUE THREAD

**Issue by rc452860** [filebrowser/filebrowser#452]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 3. What are you trying to do?
![image](https://user-images.githubusercontent.com/3949222/42210391-8a26d82a-7ee3-11e8-99a6-d4145e9bb4ba.png)

**Comment by eine** [comment]
Not added by default. You need to add them to the frontend and build filebrowser yourself. See https://github.com/1138-4EB/filebrowser-frontend/commit/52b25589b2299e337279641cb02029a6900996ed

**Comment by rc452860** [comment]
@1138-4EB thanks
