### ISSUE TITLE
Run in Start

### ISSUE THREAD

**Issue by karim2001** [filebrowser/filebrowser#453]
Hi,

Please, we are using Filemanager for a small community needs.

We installed Filemanager in Ubuntu, but we need to launch it every time we want to use it; How can it be launched everytime?

Thank's

**Comment by eine** [comment]
Hi @karim2001! Please, have a look at #411 and #418.

Also, if you use the docker image and launch a container with `--restart always`, every time the docker daemon is started the container will be started too. To have the docker daemon started on startup, you can enable it with `sudo systemctl enable docker`. For further info: https://docs.docker.com/config/daemon/systemd/

**Comment by yurividal** [comment]
I created a systemd service for filebrowser. Works perfectly. Check Method 4 in https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/

**Comment by eine** [comment]
Closed in favour of filebrowser/filebrowser.github.io#5.

**Comment by waynemillskidals** [comment]
@karim2001 probably too late on this but we simply kept this running by running this script in cron every minute

put the below in a file filebrowseractive.sh
then add to cron every minute

```
# Run Filebrowser if not running

LOG="/root/filebrowser.log.`date +%d%m%Y`"

echo "Delete log files older than 9 days" >>$LOG
                /usr/bin/find /root/filebrowser.log.* -type f -mtime +9 -exec rm -v {} \; 

echo "`date`" >>$LOG


FILEBROWSER=`ps -s |grep  'filebrowser --port 80' | wc -l`
echo "$FILEBROWSER"

 if [ $FILEBROWSER -gt 1 ]
        then
               echo "running"


        else
                echo "not running"
                /usr/local/bin/filebrowser --port 80 -a x.x.x.x -r /root/recordings/
 fi
echo "Finish `date`" >>$LOG
```



x.x.x.x = IP address of box running

Probably not the prettiest, but it works :)

**Comment by RatherLogical** [comment]
Here's the way I did it with a systemd service.

**_nano /etc/systemd/system/filebrowser.service_**

```
[Unit]
Description=Filebrowser
After=network-online.target

[Service]
User=root
Group=root

ExecStart=/usr/local/bin/filebrowser -r /

[Install]
WantedBy=multi-user.target
```

**_systemctl start filebrowser
systemctl enable filebrowser_**

P.S. this would be a dangerous setup if your filebrowser is accessible via the public internet. In my case it is only listening on the private network.

**Comment by pavitrashah** [comment]
> @karim2001 probably too late on this but we simply kept this running by running this script in cron every minute
> 
> put the below in a file filebrowseractive.sh
> then add to cron every minute
> 
> ```
> # Run Filebrowser if not running
> 
> LOG="/root/filebrowser.log.`date +%d%m%Y`"
> 
> echo "Delete log files older than 9 days" >>$LOG
>                 /usr/bin/find /root/filebrowser.log.* -type f -mtime +9 -exec rm -v {} \; 
> 
> echo "`date`" >>$LOG
> 
> 
> FILEBROWSER=`ps -s |grep  'filebrowser --port 80' | wc -l`
> echo "$FILEBROWSER"
> 
>  if [ $FILEBROWSER -gt 1 ]
>         then
>                echo "running"
> 
> 
>         else
>                 echo "not running"
>                 /usr/local/bin/filebrowser --port 80 -a x.x.x.x -r /root/recordings/
>  fi
> echo "Finish `date`" >>$LOG
> ```
> 
> x.x.x.x = IP address of box running
> 
> Probably not the prettiest, but it works :)

Thanks a lot. This worked for me.

**Comment by juliangaal** [comment]
> Here's the way I did it with a systemd service.
> 
> **_nano /etc/systemd/system/filebrowser.service_**
> 
> ```
> [Unit]
> Description=Filebrowser
> After=network-online.target
> 
> [Service]
> User=root
> Group=root
> 
> ExecStart=/usr/local/bin/filebrowser -r /
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> **_systemctl start filebrowser systemctl enable filebrowser_**
> 
> P.S. this would be a dangerous setup if your filebrowser is accessible via the public internet. In my case it is only listening on the private network.

What exactly would you change for the public internet? Are you talking about firewalling/webserver methods or about filebrowser directly?

**Comment by RatherLogical** [comment]
> > Here's the way I did it with a systemd service.
> > **_nano /etc/systemd/system/filebrowser.service_**
> > ```
> > [Unit]
> > Description=Filebrowser
> > After=network-online.target
> > 
> > [Service]
> > User=root
> > Group=root
> > 
> > ExecStart=/usr/local/bin/filebrowser -r /
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **_systemctl start filebrowser systemctl enable filebrowser_**
> > P.S. this would be a dangerous setup if your filebrowser is accessible via the public internet. In my case it is only listening on the private network.
> 
> What exactly would you change for the public internet? Are you talking about firewalling/webserver methods or about filebrowser directly?

It's been a while since I've used filebrowser. Running as root is the dangerous part. Maybe other things should be changed as well.

**Comment by juliangaal** [comment]
The root part is easily avoided with a systemd user service file in `~/.config/systemd/user`

**Comment by fffx** [comment]
My setup, start as a normal user
```
mkdir -p ~/.config/systemd/user
```

```
# ~/.config/systemd/user/filebrowser.service

[Unit]
Description=Filebrowser
After=network-online.target

[Service]
ExecStart=/usr/local/bin/filebrowser -r /some/where

[Install]
# Here must be `default.target`, the service otherwise won't start on boot
WantedBy=default.target
```
Enable it to start on boot
```
systemctl --user daemon-reload
systemctl --user start filebrowser.service
systemctl --user enable filebrowser.service
```

**Comment by juliangaal** [comment]
Are you running into the [this issue](https://github.com/filebrowser/filebrowser/issues/1633#issuecomment-971786721) @fffx? Which version are you using?

**Comment by fffx** [comment]
> Are you running into the [this issue](https://github.com/filebrowser/filebrowser/issues/1633#issuecomment-971786721) @fffx? Which version are you using?

I just installed the latest version(v2.18.0/7f2d2210),  I didn't encounter your issue. Also my service file is much simpler than yours, as you can see above.

```
 $ systemctl --user status  filebrowser

● filebrowser.service - Filebrowser
     Loaded: loaded (/home/ubuntu/.config/systemd/user/filebrowser.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-11-19 15:34:53 UTC; 2 days ago
   Main PID: 28734 (filebrowser)
     CGroup: /user.slice/user-1000.slice/user@1000.service/filebrowser.service
             └─28734 /usr/local/bin/filebrowser -a 0.0.0.0 -r /mnt/sda1

```

**Comment by juliangaal** [comment]
thanks, I'll try yours as well

**Comment by linesquarecube** [comment]
Thank you very much for providing the service file @fffx! Unfortunately this only works for me as long as I am logged in via SSH on my Raspberry Pi. When I'm not logged in and right after I close the SSH connection, filebrowser is not reachable.  I tried to shift the service file to `/usr/lib/systemd/system` and used the `deamon-reload`, `start` and `enable` command without `--user` with no success. Would be great if you or someone could hint me a solution.

**Comment by fffx** [comment]
> Thank you very much for providing the service file @fffx! Unfortunately this only works for me as long as I am logged in via SSH on my Raspberry Pi. When I'm not logged in and right after I close the SSH connection, filebrowser is not reachable. I tried to shift the service file to `/usr/lib/systemd/system` and used the `deamon-reload`, `start` and `enable` command without `--user` with no success. Would be great if you or someone could hint me a solution.

I also use it on a Rasberry PI,  my service works even after reboot. You can try this  https://unix.stackexchange.com/questions/522545/systemd-shutting-down-when-terminal-is-closed ?

**Comment by linesquarecube** [comment]
> I also using it on a Rasberry PI, my service works even after reboot. You can try this https://unix.stackexchange.com/questions/522545/systemd-shutting-down-when-terminal-is-closed ?

Thank you very much for this hint, the linked solution solved the problem for me!

**Comment by cm-ms** [comment]
Ok, thank you very much for your contribution. For those using OrangePi, do the configuration beforehand (init db) and inform execStart where the file is located.

```
[Unit]
Description=Filebrowser
After=network-online.target

[Service]
User=root
Group=root
ExecStart=/usr/local/bin/filebrowser --database /home/files/filebrowser.db

[Install]
# Here must be `default.target`, the service otherwise won't start on boot
WantedBy=default.target


```

**Comment by GogoFC** [comment]
> @karim2001 probably too late on this but we simply kept this running by running this script in cron every minute
> 
> put the below in a file filebrowseractive.sh then add to cron every minute
> 
> ```
> # Run Filebrowser if not running
> 
> LOG="/root/filebrowser.log.`date +%d%m%Y`"
> 
> echo "Delete log files older than 9 days" >>$LOG
>                 /usr/bin/find /root/filebrowser.log.* -type f -mtime +9 -exec rm -v {} \; 
> 
> echo "`date`" >>$LOG
> 
> 
> FILEBROWSER=`ps -s |grep  'filebrowser --port 80' | wc -l`
> echo "$FILEBROWSER"
> 
>  if [ $FILEBROWSER -gt 1 ]
>         then
>                echo "running"
> 
> 
>         else
>                 echo "not running"
>                 /usr/local/bin/filebrowser --port 80 -a x.x.x.x -r /root/recordings/
>  fi
> echo "Finish `date`" >>$LOG
> ```
> 
> x.x.x.x = IP address of box running
> 
> Probably not the prettiest, but it works :)

This is always 1.
