### ISSUE TITLE
Upload file failed

### ISSUE THREAD

**Issue by GRiverone** [filebrowser/filebrowser#454]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 1. Have you downloaded File Browser from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Browser's repository?
yes
### 2. What is your entire Caddyfile?
```
127.0.0.1:8080 {
 root /usr/local/caddy/www/file
 timeouts none
 gzip
 filemanager / /usr/local/caddy/www/file {
  database /usr/local/caddy/filemanager.db
 }
}
```

### 3. What are you trying to do?

When I upload a '.htaccess' file to my server, the result fails
### 4. What did you expect to see?

Successful upload
### 5. What did you see instead (give full error messages and/or log)?
Forbidden

**Comment by eine** [comment]
Please, provide as much info as you can:

- If yes, when have you done that?
- What did you see instead (give full error messages and/or log)? Hint: either show the browser console or a screenshot.
- How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Comment by hacdias** [comment]
@GRiverone when using Caddy, we add this rules by default to the default user (Settings -> User Management -> Edit your user):

```
disallow regex \/\..+
```

So the dotfiles are blocked by default, inaccessible and you can't create or upload them. 

I don't really remember why I had this decision before, but I'm removing this default option because it doesn't make much sense. If the user wants to block them, they just need to add that rule (which is one of the examples so the user doesn't even need to think about how to do it).

**Comment by hacdias** [comment]
See #455.

**Comment by eine** [comment]
@GRiverone can you reproduce this issue with the latest release?

**Comment by amalic** [comment]
@1138-4EB I can reproduce the issue on Openshift. But not if i just run the image via Docker (did not mount anything just tested if fileupload works).

Running in a a project which allows starting conainers as root user. 

I think the problem might be related having proxies doing stuff between the browser and the container.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
