### ISSUE TITLE
Upload large files

### ISSUE THREAD

**Issue by GRiverone** [filebrowser/filebrowser#457]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 1. Have you downloaded File Browser from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Browser's repository?
I have downloaded File Browser
### 2. What is your entire Caddyfile?
```
127.0.0.1:8080 {
 root /usr/local/caddy/www/file
 timeouts none
 gzip
 filemanager / /usr/local/caddy/www/file {
  database /usr/local/caddy/filemanager.db
 }
}
```

```
server {
  listen 80;
  server_name www.filemanager.com;
  rewrite ^ https://$server_name$request_uri? permanent;
}
server {
  listen 443 ssl http2;
  server_name www.filemanager.com;
  ssl on;
  ssl_certificate /usr/local/nginx/conf/vhost/ssl/filemanager/1_www.filemanager.com_bundle.crt;
  ssl_certificate_key /usr/local/nginx/conf/vhost/ssl/filemanager/2_www.filemanager.com.key;
  client_max_body_size 256M;
  location / {
      proxy_pass http://127.0.0.1:8080;
  }
}
```

### 3. What are you trying to do?

I am now using the nginx proxy filebrowser. But when I uploaded a 200M file to my server, the result failed.My guess is that the file failed because the file was too large, so I modified the nginx configuration file, but uploading the large file still failed.Also, I won't encounter this problem when I don't use nginx.
### 4. What did you expect to see?
I want to be able to upload large files

### 5. What did you see instead (give full error messages and/or log)?
This is an error report. https://s1.ax1x.com/2018/07/08/PmZfE9.png

**Comment by eine** [comment]
Hello @GRiverone! This seems to be a configuration problem with nginx, not directly related to File Browser. It might be related to https://stackoverflow.com/questions/2056124/nginx-client-max-body-size-has-no-effect
