### ISSUE TITLE
how to use wget in filebrowser ?

### ISSUE THREAD

**Issue by jsjcjsjc** [filebrowser/filebrowser#458]
Dear all
here is my filebrowser.json
{
  "port": 60000,
  "noAuth": false,
  "address": "0.0.0.0",
  "reCaptchaKey": "",
  "reCaptchaSecret": "",
  "database": "/opt/filebrowser/filebrowser.db",
  "log": "stdout",
  "plugin": "",
  "scope": "/var/www/",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": [
    "git",
    "wget"
  ]
}

 and I run it in debian: screen -d -m /usr/local/bin/filebrowser -c /opt/filebrowser/filebrowser.json

but there is nothing happend after run wget http://share.getpocket.in/25MB.test in  seach bar

is there something wrong ?

**Comment by eine** [comment]
Try `$wget http://share.getpocket.in/25MB.test`. See filebrowser/frontend#7.

**Comment by jsjcjsjc** [comment]
thank you so much for your kind help ;-)
I have tested many times and find the problem. my port is 60000. if you use ip:60000 to log in ,everything  is perfect, but i use the  cong files below in nginx., then it will failed .
it looks i have to use 80 port for filebrowser


```
upstream filebrowser{
    server 127.0.0.1:60000;
}

server {
    listen       80;
    server_name  cloud.getpocket.net;
    
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://filebrowser;
    }
}
```

**Comment by eine** [comment]
It seems that the issue is solved, so I'm closing this. Feel free to open a new one to ask about how to configure nginx with filebrowser.
