### ISSUE TITLE
请问大神 用frp 穿透后 提示 502错误。。。。如何解决啊？

### ISSUE THREAD

**Issue by wistarine** [filebrowser/filebrowser#459]
### Instructions (remove before submitting):

1. Are you asking for help with using Caddy or File Browser? Please use our forum instead: https://forum.caddyserver.com.
2. If you are filing a bug report, please answer the following questions.
3. If your issue is not a bug report, you do not need to use this template.
4. If not using with Caddy, ignore questions 1 and 2.

### 2. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

**Comment by eine** [comment]
@wistarine, please, provide some more information about your setup and the issue you are facing.

**Comment by wistarine** [comment]
thx a lot ....fixed my problems, coz frp sock configuration...
