### ISSUE TITLE
Support subtitles for videos

### ISSUE THREAD

**Issue by VLEFF** [filebrowser/filebrowser#460]
Hi,
It would be a nice feature to be able to automatically link subtitles to videos (I'm currently using Substital Chrome extension, but it would be better if it was native)

I see here that it is a standard HTML5 feature : https://www.w3schools.com/tags/tag_track.asp

**Comment by eine** [comment]
@VLEFF Can we close this issue now that filebrowser/filebrowser#468 and filebrowser/frontend#18 are merged?

**Comment by VLEFF** [comment]
Of course!
