### ISSUE TITLE
A non-standard txt file crashed the program

### ISSUE THREAD

**Issue by OpaqueArc** [filebrowser/filebrowser#463]
#####Found the cause of the bug######
Predicted cause pasted at the bottom
> ### 1. Have you downloaded File Browser from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Browser's repository?

No, I used the official script provided at https://filebrowser.github.io/installation/#one-step-script

> ### 2. What is your entire Caddyfile?
Err, what exactly is Caddy file?

> ### 3. What are you trying to do?
Environment: Ubuntu 16.04 on OpenVZ(VPS server)
To perform a speed test, i executed dd command to create a 50MB .**txt** file and tried to display it with Filebrowser (installation done under root user)

> ### 4. What did you expect to see?
Filebrowser display the file as usual

> ### 5. What did you see instead (give full error messages and/or log)?

it crashed the whole program
"killed"
said the terminal

> ### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Install Ubuntu 16.04 (my version was provided by VPS host)
`dd if=/dev/zero of=/root/50Mtest.txt bs=50M count=1`
and try to show the file using Filebrowser

> Cause of the bug

Filebrowser seemed having issue dealing with non-standard txt file(which contains all 0 bits)
Trying to show such a file 100% (as far as mine does) crashes the program

**Comment by hacdias** [comment]
On 2.0 (which is yet to be released) this will be fixed. Only readable text files will be opened and the threshold will be 10MB.
