### ISSUE TITLE
Trying to use filebrowser behind traefik.

### ISSUE THREAD

**Issue by lordSeaworth** [filebrowser/filebrowser#467]
### 3. What are you trying to do?

Trying to run filebrowser behind traefik using a docker container.

### 4. What did you expect to see?

Being able to access the script (filebrowser docker image) trought my traefik setup like the rest.
When i use it trought host ports it works to browse the files. (server:8080)

### 5. What did you see instead (give full error messages and/or log)?
When visted trought traefik it lets me login but just gives the message. Something went wrong when trying to browse the files.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Start a traefik setup and add filebrowser as a container to it trought docker.

So i have no idea how else to explain.

Maybe it has something to do with the webserver from caddy itself and their setup?
I love this filebrowser and i would love to get it working toghether with traefik

EDIT: "2018/07/24 08:47:44 /auth/renew: 403 Forbidden"
This seems to be the error given in the logs when i login with my account in filebrowser.

Maybe its the redirection or the script itself uses some reverse proxy. Any help on how i could get it to work toghether would be nice.

**Comment by eine** [comment]
> So i have no idea how else to explain.

Could you, please, provide the exact commands you are using to run both traefik and filebrowser. It'd be great if you could reproduce it in [play-with-docker](https://labs.play-with-docker.com/).

> Maybe it has something to do with the webserver from caddy itself and their setup?

It seems that you are not using filebrowser on its own, but rather using it with caddy, is it?

**Comment by lordSeaworth** [comment]
Hmm i was using hacdias/filemanager:latest it seems. I changed it to hacdias/filebrowser:latest and it seems to work now.

This can be closed.

**Comment by eine** [comment]
Reopening this and assigning it to me, just to remember adding a note to let users know which docker image to use.

**Comment by robflate** [comment]
@lordSeaworth Sorry to post in a Closed thread but do you mind posting your compose file for filebrowser? I'm trying to get it to work through Traefik too. Also, has hacdias/filebrowser:latest become filebrowser/filebrowser:latest? Thanks

**Comment by hostar** [comment]
Can't help you about Traefik, but I was not able to make this work with nginx as well.
Devs will not like me for this, but in the end I used this project instead:
https://github.com/prasathmani/tinyfilemanager
