### ISSUE TITLE
Watching changes

### ISSUE THREAD

**Issue by k1ngf15h3r** [filebrowser/filebrowser#47]
When editing content on the shell or with sublime text 3 the changes are not recognized and not renderd. would be nice to be able to get the caddy-hugo watching the content folder

**Comment by mholt** [comment]
Perhaps optionally. I wouldn't want these extra resources consuming my production environment, for example.

**Comment by hacdias** [comment]
Of course! =D

**Comment by k1ngf15h3r** [comment]
But isn't it already a feature in Hugo to add watch to true to recognize changes and render them live?

**Comment by hacdias** [comment]
Yes, but due to the Hugo architecture the watch option won't work on multi site installations (there's no way to create an Hugo instance).

**Comment by k1ngf15h3r** [comment]
damn :-/ that is a little bit anoying so I have to restart caddy-hugo each time I update or add content?!

**Comment by hacdias** [comment]
No, you can simply go to the admin interface, open something like config or
a post and click "Publish". I'll add a Build button to the interface.

**Comment by faddat** [comment]
I'd love to trade the CPU usage for the watching.  Just my $.02.
