### ISSUE TITLE
Hide dot (.*) files and folders

### ISSUE THREAD

**Issue by yurividal** [filebrowser/filebrowser#472]
Hey guys. It would be great to have an option to hide or show hidden files. (files that start with .).

Maybe a user-based policy for such.

**Comment by hacdias** [comment]
Hello @yurividal - that option already exists. Altough you need to set it for each individual user. If you go to a user's settings, there will be an "allow/disallow/rules" section. There's an example in there showing how to hide . files.

**Comment by yurividal** [comment]
Thank you! Can't believe I missed that.

Here is my block list now:

disallow regex [\\\/]\..+
disallow regex \$RECYCLE\.BIN
disallow regex System\sVolume\sInformation

**Comment by eine** [comment]
@hacdias would it be possible to bind some keyboard shortcut (which is unused in browsers) to this specific feature? E.g. `Ctrl+Alt+H` as in [winscp](https://winscp.net/eng/docs/ui_commander_key).

On the one hand, settings are not accessible when `notAuth` is set to `true`. On the other hand, I think that it is desirable to be able to change this fast. For example, when browsing a repo, it is handy to hide/show config files easily. On the whole, I think that hidding/showing dot files/folders should be a complement to (dis)allowing them.

**Comment by yurividal** [comment]
Great idea. Ctrl Alt H or Ctrl shift H would really be awesome.

**Comment by eine** [comment]
> [@yurividal]
> Great idea. Ctrl Alt H or Ctrl shift H would really be awesome.

In Firefox `Ctrl+Shift+H` opens the History in a new window. Does `Ctrl+Alt+H` trigger anything in your browser?

**Comment by yurividal** [comment]
@1138-4EB not it Chrome

**Comment by eine** [comment]
Related #355.

**Comment by itsthejb** [comment]
Fantastic! Didn't know this already exists. Not easy to find, though - seems like something that would be good to add to the docs?

Here's the rule I used disallow `\/\..*$`

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
