### ISSUE TITLE
SSL/X509-Error on using ReCaptcha in Docker Container

### ISSUE THREAD

**Issue by pklink** [filebrowser/filebrowser#476]
If I using ReCaptcha with Docker it is not possible to verify the captcha on login. I got the following error in the logs:

```
Post https://www.google.com/recaptcha/api/siteverify: x509: failed to load system roots and no roots provided
```

I found a very similar problem here: https://github.com/zenazn/goji/issues/126
As suggested linking the certificate CRT from host system into container solves my problem:

```
docker run -v '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt' ...
```

But I think it's more clean to install the root certificates in the docker image.

**Comment by eine** [comment]
We can install the ca-certificates from the latest alpine image by using [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/):

```
FROM alpine:latest as certs
RUN apk --no-cache --update upgrade && apk --no-cache add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
```
