### ISSUE TITLE
Improve release changelog

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#482]
Currently, the changelog for each release (created by [goreleaser](https://github.com/goreleaser/goreleaser)) does not include the commits/PRs that belong to the frontend. Only those in this repo are included. It'd be desirable to have all of them included.

See goreleaser/goreleaser#915.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
