### ISSUE TITLE
Searched filename in UPPER CASE is found but result is lower case, thus file not found :(

### ISSUE THREAD

**Issue by gestioko** [filebrowser/filebrowser#484]
**Description**
I searched this File3.txt and is able to find but presented file is file3.txt

**Expected behaviour**
Should be able to find (yes this is achieved) however the presented file (in URL) is in lowercase. Upon clicking I get this "This location can't be reached".

**Comment by eine** [comment]
This seems to be due to a somehow buggy implementation of the case sensitiveness. While searching for `File3` produces the result you describe, if you write `File3 case:sensitive` in the search box it will provide a valid result.

**Comment by hugomassing** [comment]
I did a quick fix for this in #515.

let me know if this is OK for you!

**Comment by eine** [comment]
The fix by @hugomassing is merged in master now. It will be available in the next release. Meanwhile, you can try the latest docker image (`filebrowser/filebrowser:latest`).

**Comment by PejmanNik** [comment]
In the last release 'v1.10.0' this bug still exists
