### ISSUE TITLE
Rules: disallow all directories except

### ISSUE THREAD

**Issue by HesselTjeerdsma** [filebrowser/filebrowser#493]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to allow certain directories for a users.  I have a directory with many sub-directories, a certain user only needs access to some of them. Maybe it is doable with regex but I cannot get this to work.

**Describe the solution you'd like**
It would like there to be a function to allow all except: 
disallow all except /dir1 and /dir2 for example.

**Describe alternatives you've considered**
Another solution would be to only allow the directories that are indicated by allow, and block the other by default.

**Comment by zhentianxincun** [comment]
I sincerely hope to see such permission settings.
![snipaste_2018-08-20_19-27-05](https://user-images.githubusercontent.com/35227732/44338067-62494080-a4af-11e8-9cc8-10d7dd617c44.png)

**Comment by nambrosch** [comment]
did anyone figure out a way to do this with filebrowser as-is or is it impossible?  i'd also like to disallow access to ^/.* globally and allow specific directories per-user.

**Comment by nambrosch** [comment]
@HesselTjeerdsma did you ever figure out an elegant solution to your problem?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
