### ISSUE TITLE
Feature: Activity streams so users can not just share links but discuss content like you can in google drive.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#499]
**Is your feature request related to a problem? Please describe.**
Its additional. Activity Streams is a way for people to discuss things over a content store ( normally).
Its going through W3C and there are golang with vuejs code base so it fits with File Browser really well.

**Describe the solution you'd like**
The ability to have discussions over the content. FileBrowser already has the Share functionality, but this take it up step to a federated system for users to share but also discuss and be notified of changes to the discussion.

**Describe alternatives you've considered**
None. This feature seems to fit like a glove.

**Additional context**
Here is all that is needed and it works really well.

- Spec: : https://www.w3.org/TR/activitypub/
- Docs and Tutorial: https://go-fed.org/
  - Conforms to the official Activity W3C spec !
- Core Code: https://github.com/go-fed/activity
- Client and Server code using the core: https://gitlab.com/tuxether/anancus
  - uses Golang, VueJS, CockroachDB

**Comment by vitaliy-kuzmich** [comment]
@ghost do you think features like in jitsi or skype will works ? Like video/audio screen share ?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
