### ISSUE TITLE
Would you mind doing a brief screencast on how to setup and use caddy-hugo?

### ISSUE THREAD

**Issue by bzerangue** [filebrowser/filebrowser#50]
Would you mind doing a brief screencast on how to setup and use caddy-hugo? It would be extremely helpful to see how you install and setup and use Hugo for Caddy.

**Comment by faddat** [comment]
Sure thing.  I'll try and have one up by wednesday.  Here's what I consider the most important things: 

1) Get caddy with hugo extension from [caddy's](https://caddy.org) web site.  Move the "caddy" binary to /usr/bion

```
tar xvf caddy.tar.gz
mv caddy /usr/bin
```

2) Make a Caddyfile in the folder you want to serve content from and edit content with caddy-hugo.  This was tough for me.  Here's mine:  

```
cat Caddyfile
sharebitstalk.io www.sharebitstalk.io technologistguild.com www.technologistguild.com {
gzip                                                            # tells caddy to compress traffic
proxy /         192.168.191.206:80                              # / tells caddy that it should proxy to the folder / and 192.168.191.206:80 Tells Caddy what URL to proxy at /
tls             email=jake@klouds.org                           # Tells let's encrypt your e-mail address
}

chat.sharebitstalk.io {
gzip
proxy /         192.168.191.206:8065
tls             email=jake@klouds.org
}

klouds.org www.klouds.org {
gzip
tls             email=jake@klouds.org
root            /root/hugo-semantic-homepage-starter/dist       # Tells CADDY which folder to serve as the root
basicauth       /admin faddat *******                         # protect the admin area using HTTP basic auth
hugo            /root/hugo-semantic-homepage-starter            # Tells HUGO which folder to execute in
}
```

3)   Save your Caddyfile and run caddy with the command, executed in the same folder as the Caddyfile.  

```
caddy
```

**Comment by hacdias** [comment]
Hello @bzerangue! Like to hear that someone is using (or trying to use) caddy-hugo! Hope you enjoy and hope @faddat can help! Thanks for helping @faddat :)

**Comment by faddat** [comment]
Sure thing!  Thinks for the awesome tool, @hacdias!

**Comment by hacdias** [comment]
You're welcome :D

**Comment by ludovicc** [comment]
With Docker, it's easy. Go to the folder containing the Hugo project, then

  docker run -d -v $(pwd):/srv -p 2015:2015 ludovicc/caddy-hugo

**Comment by faddat** [comment]
Screencast coming some time this hour :).

**Comment by bzerangue** [comment]
Awesome!

On Wed, Feb 24, 2016 at 8:02 PM, Jacob Gadikian notifications@github.com
wrote:
Screencast coming some time this hour :).

—
Reply to this email directly or view it on GitHub
[https://github.com/hacdias/caddy-hugo/issues/50#issuecomment-188560293] .[https://github.com/notifications/beacon/AABqG8-OdBfjgAO2CsPvrwebhPwKF2Jcks5pnlg7gaJpZM4HfPgT.gif]

**Comment by faddat** [comment]
@ozzadar has been making awesome videos on windows lately-- anyone know a great video editor for Linux?  Goal:  "out-class Corel Video"

**Comment by faddat** [comment]
Maybe one hour from now.... _work_.....

**Comment by faddat** [comment]
Does anyone have a good guide for doing screencasts?  I've made this one twice now but it takes an hour to show what shouldn't be longer than 15 minutes....

**Comment by hacdias** [comment]
I've never done that so I can't help you with that :(

**Comment by hacdias** [comment]
I'll close this issue right now because of the lack of the activity on it. If you want to reopen it, just tell me. :+1:

**Comment by liz-miller** [comment]
I know this is 8 mos old, but I'd like to see this screencast. I've been reading through the issues and documentations, etc and I am still having some trouble getting caddy + hugo  hosted on github to work properly :(

**Comment by hacdias** [comment]
Hello @liz-miller, if you really need it, I could do it in the weekend probably, but tell me: what have you already done and where is it failing? 🙂

**Comment by liz-miller** [comment]
I've completed the following:
- installed Hugo 
- created a Hugo site & content
- created a GitHub repo to host using gitpages 
- configured my domain to point to the GitHub pages URL
- made my site live (www.queenflex.com)

Now what I want to do is add caddy-Hugo for the ability to blog anywhere. 

I've done the following for caddy:
- downloaded caddy with Hugo extension
- added caddy to the path
- attempted at a caddy file, but it's failed --> I'm suck here

I'm not at my computer now, but I will send you the caddyfile and output errors later on. 

It's probably something simple I'm missing...

**Comment by hacdias** [comment]
To use caddy-hugo you'll need to have it set up on your own server but it seems you're using Github Pages. Anyway, if you can send me the Caddyfile I can check if it has got any error related to hugo 😄

**Comment by liz-miller** [comment]
I see. Well that could be the reason for my problems. I didn't realize I couldn't host using github -_-

**Comment by hacdias** [comment]
You can host a Hugo website using Github Pages but you can't use Caddy + this plugin with github pages.

**Comment by liz-miller** [comment]
will Caddy + Caddy-Hugo work with hosting on AWS?

**Comment by hacdias** [comment]
I'm not sure how does AWS work (never used it). But if it's like a VPS it will work for sure.
