### ISSUE TITLE
More flexible rights/permission scheme

### ISSUE THREAD

**Issue by Darkham42** [filebrowser/filebrowser#502]
**More flexibilty to assign rights**

It could be great to explode the right "rename/edit and delete a file".
In fact we can wish to give rights to rename a file but not to delete it.

I don't think it's really hard and if nobody do it until I take a look at go I'll do a PR ;)

In the same order, but more difficult, would be to give rights by folders (more flexibility again but more difficult).

What do you think about that ? :)

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
