### ISSUE TITLE
Disable user submitted stylesheets

### ISSUE THREAD

**Issue by Marneus68** [filebrowser/filebrowser#507]
I'm using filebrowser in a configuration where I have some administrative accounts who submit content and multiple shared user account with different permission levels who access said content. I would like to be able to disable user submitted stylesheets as I would like all shared accounts to have the same user experience and prevent some users to disrupt the experience of other users they share the account with.

A good way to handle that would be to allow or disallow stylesheet submission per user.

Alternatively, it would be good to disable custom stylesheets for the whole filebrowser instance, if that is easier to do in the meantime.

If I have missed that feature in the current version, I apologise for the wrong request. I looked into the documentation and that feature seemed missing to me.

Thanks for your consideration and the work you did on filebrowser.

**Comment by hacdias** [comment]
Somewhat related to #502 - one more option to add: allowStyling.

**Comment by yurividal** [comment]
[offtopic] Speaking of stylesheets, could we have some examples of nice stylesheet mods, maybe posted to the readme?

**Comment by eine** [comment]
@yurividal, see e.g. #208. Also, please consider opening a new issue to discuss either documenting style mods (probably in [filebrowser/community](https://github.com/filebrowser/community)) (also suggested in #407) or enhancing filebrowser to support multiple 'default' CSS and a dropdown select for each user.

**Comment by hacdias** [comment]
We should wait for #506 before doing this because of the commands compatibility.

**Comment by eine** [comment]
#506 is merged now :smile:.

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!
