### ISSUE TITLE
How can I get my admin password back if I forget it?

### ISSUE THREAD

**Issue by chenfeichen** [filebrowser/filebrowser#510]
How can I get my admin password back if I forget it? I try to delete the database but seems to make no effect?

**Comment by DeyV** [comment]
Users and they password are saved in DB. 
Password is saved as hash, so it's not possible to retrieve it. 

But if You delete this DB and restart filebrowser, app will start with default admin account and password

**Comment by eine** [comment]
Hi @chenfeichen. As @DeyV explained, removing the DB should restart filebrowser. However, your browser cache might be trying to use the old credentials. Can you try either cleaning the cache or opening a tab in incognito mode?

If it does still not work, please let us know about your context: whether you are using the docker image or caddy, which version of filebrowser is it, the plaform, etc.

For completeness, overwriting the password either through the config file or with a CLI option is in the roadmap, but no ETA yet. See #489.

**Comment by chenfeichen** [comment]
thank you @1138-4EB @DeyV
