### ISSUE TITLE
Implement Right Click Menu

### ISSUE THREAD

**Issue by yurividal** [filebrowser/filebrowser#512]
**Is your feature request related to a problem? Please describe.**
Right click menu would make UI more intuitive.

**Describe the solution you'd like**
Right click a file, should bring up a menu with common actions, such as rename, copy, move, delete, or share.
Right Click a Folder could also be implemented. 
Long-click on mobile version could be an alternative. Could be inspired in Google Drive site. 

**Additional context**
Example of Google Drive Right-click on a file:

![right_click](https://user-images.githubusercontent.com/8555749/44092145-f9975530-9fa5-11e8-8774-db908dff4e42.png)

**Comment by eine** [comment]
Closing as duplicate of #442. Please, write any additional suggestion there.
