### ISSUE TITLE
Installer Script does not Work in Raspberry Pi

### ISSUE THREAD

**Issue by yurividal** [filebrowser/filebrowser#516]
**Description**
Installer Script does not Work in Raspberry Pi because it looks for file linux-arm-filebrowser.tar.gz instead of file linux-armv7-filebrowser.tar.gz

**Expected behaviour**
Should download the right version. linux-arm-filebrowser.tar.gz does not exist.
 
**What is happening instead?**
404

**Files**
get.sh

**Comment by eine** [comment]
Thanks for reporting @yurividal! According to https://github.com/filebrowser/filebrowser.github.io/blob/master/get.sh#L53-L65, `uname -m` is used to detect the arch. Can you please execute it in the RPi and tell us which is the output?

**Comment by yurividal** [comment]
pi@raspberrypi:~ $ uname -m
armv7l
pi@raspberrypi:~ $

**Comment by eine** [comment]
@yurividal can you please try https://raw.githubusercontent.com/filebrowser/filebrowser.github.io/e921a287e71f54fffd87a9db60201602d7380c4d/get.sh ?

**Comment by yurividal** [comment]
@1138-4EB it works thanks.

**Comment by yurividal** [comment]
i added
```
$sudo_cmd service filebrowser stop
$sudo_cmd systemctl daemon-reload
$sudo_cmd service filebrowser start 
```
Because i use filebrowser as a service. Im not 100% sure if this is necessary, but just wanted to make sure. Dont know if this could be added to the script, maybe doing a check,

**Comment by eine** [comment]
@yurividal, there is a ongoing discussion about it in filebrowser/filebrowser.github.io#5.
