### ISSUE TITLE
폴더 삭제시 504 gateway time out 발생함

### ISSUE THREAD

**Issue by minhohihi** [filebrowser/filebrowser#526]
정확한 원인인지는 모르지만 문제가 발생한 시퀀스를 적어보면 아래 두 단계입니다.

1. dfc cp 명령어로 파일 copy 중 ctrl+c로 중단함
2. http://files.deepflow.devel.kakao.com/maverick.park/ 에서 copy하던 데이터 폴더를 선택 후 삭제 실행

터미널에서 dfc rm으로는 정상적으로 삭제가 되었습니다.

**Comment by hacdias** [comment]
@minhohihi I can't open that website. It gives connection timeout.

**Comment by minhohihi** [comment]
@hacdias I'm sorry. That page is for internal and I thought this issue report site also internal page when I reported the issue. You can ignore this issue.
