### ISSUE TITLE
.mkv file can't play in Safari, but can in Chrome

### ISSUE THREAD

**Issue by livc** [filebrowser/filebrowser#527]

**Comment by yurividal** [comment]
also, some MP4 play in chrome, but with no sound.

**Comment by jazware** [comment]
MKV files are not supported natively on MacOS, you either have to download the file and open it in something like VLC player, or use a modern browser like Chrome that has codecs to decode the MKV containers. The MP4 issues are similar in that browsers don't have every audio/video codec required for consistent playback, please download the files and open them in VLC or some other video player.

If you want to be streaming video content from a server to your web browser, look at a project like [Plex](https://www.plex.tv/) which performs live transcoding of your media to ensure it can properly playback in your browser.

**Comment by jazware** [comment]
I just realize this is also related to #465 so I'll tag it here.
