### ISSUE TITLE
Sessions per user limited to one

### ISSUE THREAD

**Issue by ldesousa** [filebrowser/filebrowser#529]
**Description**
Once a session is started with a certain user, no more sessions can be created with that user. In such cases the message "Wrong credentials" is shown, that is very confusing to users.

**Expected behaviour**
One of two behaviours would be expected:
1. Let more that one session be created by each user
or
2. Issue an error message like: "You are already logged on from a different instance."

**What is happening instead?**
Users can not create more than one session simultaneously. In such cases the user is shown a misleading message: "Wrong credentials".

**Additional context**
This was found out on Windows, when a user logged on first with IE; as it can not display Filebrowser properly, the user tried to log on with a different browser and got the "Wrong credentials" message.

It would be rather useful to have multiple persons logging on with the same credentials, for instance to give access to the same resources to a large group of people.

**How to reproduce?**
Log on with one browser and they try from another one with the same user.

**Files**
-

**Comment by dream10201** [comment]
Create multiple users

**Comment by ldesousa** [comment]
@dream10201 Which part of "to give access to the same resources to a large group of people" did you miss?

**Comment by dream10201** [comment]
Unable to reproduce，everything is normal
version：1.10.0

**Comment by jazware** [comment]
This should probably be a feature request for user groups that can share permissions or for a multi-access user option.

**Comment by hacdias** [comment]
You can open how many session you want. File Browser doesn't set any limit and it works with the same user on many browsers at the same time. Please make sure you used the right instance of File Browser and that the credentials were correct.

Internet Explorer is not officially supported. The errors might be due to the old age of the browser and its incompatibilities with newer technologies.
