### ISSUE TITLE
Automatically set the baseURL for Hugo

### ISSUE THREAD

**Issue by ludovicc** [filebrowser/filebrowser#53]
Hello,

I'm running Caddy-hugo in a Docker container (https://github.com/ludovicc/caddy-hugo). My project contains custom css and javascript files, but those are not served as the url for them starts with http://localhost:1313 instead of http://localhost:2015.

I tried to change the configuration in the Caddyfile, but it doesn't change anything.

hugo /srv {
  cmd "--buildDrafts --watch --baseURL=http://localhost:2015/ --bind 0.0.0.0 --port 2015"
}

You can try this by running the Docker container on the Balsamiq site, a Hugo project (https://github.com/balsamiq/docs.balsamiq.com)

**Comment by hacdias** [comment]
Hello @ludovicc 

As I understood, you are running caddy-hugo from source, so there are some differences from the documentation. I've implemented a new idea that's already on `master` but not detailed in the docs.

Instead of:

```
hugo /srv {
   cmd "--buildDrafts --watch --baseURL=http://localhost:2015/ --bind 0.0.0.0 --port 2015"
}
```

Try:

```
hugo /srv {
   buildDrafts
   watch 
   baseURL http://localhost:2015/ 
   bind 0.0.0.0 
   port 2015
}
```

Hope it helps!

**Comment by ludovicc** [comment]
Hello,

I tried, but it doesn't seem to work, the Caddy server runs but does not
even listen on port 2015.

Ludovic

2016-02-23 19:25 GMT+01:00 Henrique Dias notifications@github.com:

**Comment by hacdias** [comment]
Hey,

That's everything you have on your caddyfile?

It should be something like this:

```
0.0.0.0:2015

root /srv/public
hugo /srv {
   buildDrafts
   watch 
   baseURL http://localhost:2015/ 
}
```

Try that pls :D

**Comment by hacdias** [comment]
@ludovicc any news?

**Comment by ludovicc** [comment]
Hello,

caddydev fails with this error, do you have any idea?

```
Watcher enabled, watching for file changes.
Building...
2016/02/27 21:50:18 exit status 2
---- COMMAND: go build -o /tmp/caddydev888063144
---- 
---- # github.com/mholt/caddy/caddy/https
---- caddy/https/setup.go:271: undefined: tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
---- caddy/https/setup.go:272: undefined: tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
---- caddy/https/setup.go:292: undefined: tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
---- caddy/https/setup.go:293: undefined: tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
---- caddy/https/setup.go:308: undefined: tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
---- caddy/https/setup.go:309: undefined: tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

**Comment by hacdias** [comment]
Hmm... Nope. Try to update the repository and if that doesn't work, let's see what @mholt knows.

**Comment by mholt** [comment]
You need Go 1.6 installed.

**Comment by ludovicc** [comment]
@mholt thanks, I've made progress.

@hacdias I'm getting something that's almost working, at least Caddy is starting and listens on the right port, but most requests fail with 404.

Try this:

docker pull ludovicc/caddy-hugo
docker run -d --name caddy-hugo -v $(pwd):/srv -p 7011:7011 -e PORT=7011 ludovicc/caddy-hugo

Strangely, http://localhost:7011/srv/public/ serves some content, everything else returns 404. Any idea?

**Comment by hacdias** [comment]
Even /admin?

**Comment by ludovicc** [comment]
Yes, /admin included

2016-03-03 20:09 GMT+01:00 Henrique Dias notifications@github.com:

**Comment by hacdias** [comment]
Strange... So that's not a problem of caddy-hugo I think. What's your configuration? And your Caddyfile?

**Comment by ludovicc** [comment]
Caddy was launched with this command:

/home/go/bin/caddydev --source /home/go/src/github.com/hacdias/caddy-hugo
hugo -port 7011

/etc/Caddyfile contains the configuration, /srv the Hugo project to serve.

This is my Caddyfile:

# disable HTTPS to run the server on localhost

tls off

# the folder where Hugo generates the website

root      /srv/public

# enable the admin panel

hugo /srv {
   buildDrafts
   watch
   baseURL http://localhost:7011/
}

2016-03-03 20:18 GMT+01:00 Henrique Dias notifications@github.com:

**Comment by hacdias** [comment]
Try this Caddyfile:

```
0.0.0.0:7011

tls off
root      /srv/public
hugo /srv {
   buildDrafts
   watch
   baseURL http://localhost:7011/
}
```

Run `/home/go/bin/caddydev --source /home/go/src/github.com/hacdias/caddy-hugo` and go to `http://localhost:7011/` and `http://localhost:7011/admin` to try it out, please. 

Hope it helps!

**Comment by ludovicc** [comment]
Hello,

I tried to run this with your Caddyfile in the current directory:

```
sudo docker run -d -v $(pwd):/srv -p 7011:7011 -e PORT=7011 ludovicc/caddy-hugo
cd /
/home/go/bin/caddydev --source /home/go/src/github.com/hacdias/caddy-hugo hugo -port 7011
```

it says:

```
Watcher enabled, watching for file changes.
Building...
Starting Caddy...
Activating privacy features... done.
:7011
```

But I still get the 404 errors. Note that I need to force the use of port 7011 on the command line of caddydev, otherwise it uses port 2015. Actually, it looks like the Caddyfile is never used, but I do not know why.

If I do this:

```
docker run -v $(pwd):/srv -p 7011:7011 -e PORT=7011 --entrypoint /bin/sh -i -t --rm ludovicc/caddy-hugo
cd /srv
/home/go/bin/caddydev --source /home/go/src/github.com/hacdias/caddy-hugo hugo
```

then it says:

```
Watcher enabled, watching for file changes.
Building...
Starting Caddy...
Activating privacy features... done.
Unable to find Hugo on your computer.
Downloading Hugo from GitHub releases... downloaded.
Checking SHA256...checked!
Unziping... open /tmp/caddy-hugo526225374: is a directory
```

and the server doesn't run.

You can check how the Docker image was built here: https://hub.docker.com/r/ludovicc/caddy-hugo/~/dockerfile/

**Comment by hacdias** [comment]
I've made some changes in the way caddy-hugo uses Hugo and now it installs Hugo in a different folder. I'll see if I can fix that bug and then you test it.

It's strange that your OS is not using Caddyfile. Are you running caddy in the same folder as caddyfile? That's really strange. 

Anyway, the second way you run is doing what's expected. There's just a bug I need to fix. What's your OS?

**Comment by hacdias** [comment]
One more thing: I started using Bintray with Travis so the people who don't want to download the source code and compile it from source can still use and test the latest versions of caddy-hugo. If you're only using this plugin, you can download the build from here: https://dl.bintray.com/hacdias/generic/caddy-hugo/ . Always open the last folder, which is the one that has a bigger number. And download the version for your OS.

I'm really sorry for this situation :(

**Comment by hacdias** [comment]
Try using the latest version on Bintray, please.

**Comment by ludovicc** [comment]
Hello, sorry for the long delay. I'm trying with the version on Bintray, but it doesn't seem to support disabling tls and Letsencrypt certificate generation.

/usr/local/bin/caddy -port 2015 -log /var/log/caddy.log
Activating privacy features...2016/04/05 23:44:10 [tls] failed to get certificate: acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: DNS name does not have enough labels

Caddyfile:

```
# disable HTTPS to run the server on localhost
tls off

# the folder where Hugo generates the website
root /srv/public

# enable the admin panel
hugo /srv {
   buildDrafts
   watch
   baseURL http://localhost:/
}

```

**Comment by hacdias** [comment]
Hello!

Try with the version of caddyserver.com please. It's the latest version of
caddy-hugo like on Bintray, but it has the other plugins and stuff more
updated.

If that error persists, you should contact @mholt.

Thanks :)

**Comment by ludovicc** [comment]
@hacdias thanks, the build of caddy with the hugo plugin included works like a charm!

**Comment by hacdias** [comment]
You're welcome! :) I hope you enjoy the plugin. If you have some suggestions to make it better, don't forget to tell me!
