### ISSUE TITLE
🆘 Need Maintainers

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#532]
This project is not under active development, i.e., new features won't be created and deep bugs might be hard to be fixed. A small set of developers is taking care of keeping it building and fixing small issues.

If you're interested in becoming a maintainer of this project, please let us know through this issue and start contributing. It would be awesome for the more than 3000 people that starred this project!

**Comment by yurividal** [comment]
@hacdias that is SO SAD... =(

I wish i had any knowledge in this programing field, to help... 

Anyways, thank you for all the hard-work

**Comment by hacdias** [comment]
@yurividal 😞

**Comment by rhjmoore** [comment]
Do you need help maintaining the Go side or the web client side more?

**Comment by hacdias** [comment]
@rhjmoore both. All help is welcome 😄

**Comment by jazware** [comment]
Hey, I'll see if I can carve up some time to help out. I had a few commits way back when this was starting out but haven't touched the source in a while.

**Comment by jazware** [comment]
If you want to make me a maintainer I can dig through the issues and get rid of the noise of people who don't understand how web or golang or whatever works...

**Comment by hacdias** [comment]
@ericvolp12 awesome that you want to contribute! You can start by looking at the issues and creating PRs. We'll only give push access to someone who has a history on this repository. You can start building one right now! 😃

**Comment by jazware** [comment]
Hey @hacdias it'd be nice if I had the permissions required to close or label issues as I dig through the backlog. I do have a history of commits to the project for the record.

**Comment by eine** [comment]
> it'd be nice if I had the permissions required to close or label issues as I dig through the backlog

You can comment on those you are interested to fix, and we will close or relabel them correspondingly. Indeed, we rarely take actions without double approval. That is, even if an issue is to be closed, we comment there to ensure that it is solved. Then, if no reply is received in around a week, it is closed. However, if the issue is old, and no maintainer replied to it previously, we wait longer as the OP might have forgotten about it and some more time might be needed to come back.

Nonetheless, ATM we can read and respond to issues/questions, but *new features won't be created and deep bugs might be hard to be fixed*. So, it'd be great if you contributed to these topics.

**Comment by dtwilliams10** [comment]
I would like to help, I haven't developed with Go or Vue but I do have full stack experience that I can try to help with. After looking through the issue log is there any priority or order that you would want things worked on?

**Comment by hacdias** [comment]
@dtwilliams10 hello! Thanks 😄 hope you contribute. There's no special order. Just bugs >>>> features.

**Comment by hugomassing** [comment]
I can help as well for the frontend part! I have some commit with minor fixes! So sad because the tool is so good!

**Comment by eine** [comment]
@dtwilliams10, as @hacdias suggested, [bugs](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) have the highest priority. However, since you are not familiar with neither the languages nor the code, triaging can help you. With triaging I mean trying to reproduce issues reported by users. Doing so will let you gain insight into the build procedure and into the wide use space. Of course, it is also useful for us, in order to better label the issues. If you do so, please reply in the corresponding issue telling if you could reproduce it or, in case you couldn't, asking for additional info.

Also, please read https://github.com/filebrowser/community.

@hugomassing looking forward for those fixes ;)

**Comment by wuzhefang** [comment]
fine. Begin to learning Go.

**Comment by IanDuncanT** [comment]
I would like to help develop this. I haven't learned go yet, but I will look at some issues and try to fix some.

**Comment by hacdias** [comment]
@IanDuncanT cool! Thank you 😄

**Comment by hacdias** [comment]
The current master is stable. Probably new features won't be added by myself. Only fixes if I have time. I'd like to welcome everyone to contribute to this project.

**Comment by gugadev** [comment]
@hacdias I want to help to develop & maintain this project. I have some free time. 👍

**Comment by hacdias** [comment]
@takeabug that's awesome! You could start by submitting some PRs 😄 With time, you could be made a contributor of the organization.

**Comment by girishramnani** [comment]
@hacdias I would also like to help develop and maintain his project.

**Comment by hacdias** [comment]
@girishramnani that's awesome! Thank you 😄 The best way to start is by looking at the issues and make PRs to solve some of them. Let me know if you need anything.

**Comment by jtnotes** [comment]
@hacdias I love this program and I have experience of backend development (go/python/node etc), glad to help!

**Comment by hacdias** [comment]
Hey @jtnote! That'd be awesome! You can look at the [issues](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and see if there's something you'd like to work on. Bug fixes must be prioritized at the moment. Unfortunately, I have no time to work on this at the moment :(

**Comment by Liberxue** [comment]
I have used filebrowser for a while and found that the support on the mobile side is not optimized. At present, I personally try to develop [filebrowser ios and Android client ](https://github.com/Liberxue/filebrowser-Flutter )with flutter. Is there any plan to develop it?

**Comment by hacdias** [comment]
@Liberxue unfortunately there are no plans to develop further features for File Browser due to the everything that's described on this issue. However, if you'd like to contribute, it'd be awesome if you did! :D

**Comment by Liberxue** [comment]
> @Liberxue unfortunately there are no plans to develop further features for File Browser due to the everything that's described on this issue. However, if you'd like to contribute, it'd be awesome if you did! :D

Ok, I am trying to finish [filebrowser-Flutter](https://github.com/Liberxue/filebrowser-Flutter)😄 
Now I am going to submit design documents development, if necessary can be included in the official repository, or participate in UI design and development

**Comment by hacdias** [comment]
It's been over a year without active maintenance on this repository and the issue and PR list is always getting bigger and bigger. I decided to, unfortunately, close the issues and the PRs and archive the repo and mark it as unmaintained.

Sadly, I don't have the bandwidth to keep this project alive. And no one has decided to do so either. Unfortunately I've seen this happening on other open source projects, but if anyone in the future wants to maintain this project, I will handover the organization to that person.

I don't want to keep this repository looking as if it was going to be maintained soon and give false expectation to users. That's another reason. 

I will do this during tomorrow.

**Comment by nambrosch** [comment]
@hacdias Thank you for all of your work, it is a great product!

**Comment by hacdias** [comment]
I will make sure I push a release with the last merged PRs before closing everything else.

**Comment by hacdias** [comment]
Just released 2.1.0 with the last changes I merged. I'm now going to archive this repository. ~If, in the future, anyone wants to take over this project, just ping me.~ It's time to say goodbye to the project I started 5 years ago! Thanks everyone for their contributions and I hope you all understand.

**Edit.:** feel free to fork the project!
