### ISSUE TITLE
Файлы                Мультивыбор включен  clear [object Object]

### ISSUE THREAD

**Issue by ndkiatm** [filebrowser/filebrowser#535]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

**Expected behaviour**
What did you expect to happen?

**What is happening instead?**
Please, give full error messages and/or log.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by jazware** [comment]
This contains no information we can action upon at all, this should be closed.
