### ISSUE TITLE
How about filename modification

### ISSUE THREAD

**Issue by seagochen** [filebrowser/filebrowser#537]
Thanks for all of kind people like you guys first. I've deployed filebrowser on my raspberry, because of your contribution, now I have a cheap and powerful NAS!

But, I think if enable filename modification will much better.

I noticed that I can move a file from an old place to a new place, delete a file, search file. However, I can't rename my file. So I've delete the old file first, and then re-upload a renamed one.

So, if there any possible to add a "rename" to filebrowser?

And, thank you again!

**Comment by helloray** [comment]
This simple feature was already supported. Select a file and click the pen icon.

**Comment by seagochen** [comment]
I got it! Very thanks!
