### ISSUE TITLE
always 404 Not Found

### ISSUE THREAD

**Issue by tonka3000** [filebrowser/filebrowser#54]
Hey,

i've try to get caddy-hugo to run, but i always get an **404 Not Found**. I could open the admin panel, but i get no content from the site itself.

I've use the [2minutes hugo-site](https://gohugo.io/overview/quickstart/)

My Caddyfile is simple:

```
localhost:2020
gzip
log ./access.log
errors ./errors.log

root ./

hugo {

}
```

Caddy version is 0.8.1

what is my issues?

Greetings
Tonka

**Comment by hacdias** [comment]
Hello! Is your caddyfile in the same folder as your hugo website?

**Comment by tonka3000** [comment]
Yes, it's in the same directory.

**Comment by hacdias** [comment]
Try this Caddyfile:

```
localhost:2020
gzip
log ./access.log
errors ./errors.log

root ./public
hugo 
```

And what's your OS?

**Comment by hacdias** [comment]
One thing: I never tried Hugo with gzip. If the error persists, remove the gzip directive to see if it works.

**Comment by tonka3000** [comment]
I'm using it on windows 7 x64 SP1.
I moved my hugo site to a different location on my harddisk and give it all rights, and now it works - with gzip => so it seems to be a access problem, but i don't know why i got 404 instead of 403.
The only thing which does not work at the moment are the css-stuff.

My final Caddyfile is

```
localhost:2020
gzip
root ./public

hugo {

}

```

Thanks for your help.

**Comment by hacdias** [comment]
Hey!

Those are good news. And thanks for reporting that it was an access error.
I'll fix that when I can.

Br

**Comment by tonka3000** [comment]
:+1:
