### ISSUE TITLE
Filebrowser cannot show one particular folder

### ISSUE THREAD

**Issue by rhjmoore** [filebrowser/filebrowser#540]
**Description**
I have deployed filebrowser via docker. It is successfully deployed, serving my folders. I can happily move files around my file system and access my files remotely.
I have one folder, that does not have an unusual name, that just hangs when I double click on it. It never errors, and it never returns a listing of the directory, and nothing is logged to the log.
Permissions of this folder appear to be identical to other folders around it that are successfully served. SELinux is disabled on the system.

**Expected behaviour**
I expected the folder to be served successfully, or for an explanatory log entry to be logged explaining the problem.

**How to reproduce?**
Not easily reproduceable yet since it seems to be specific to this folder on my system, and we don't yet understand why. I'd like to be able to turn up the logging in some manner to get an understanding of what it is failing on.

**Comment by helloray** [comment]
Why not paste your folder name here? You said a lot but without your folder name, nobody can solve your problem.

**Comment by rhjmoore** [comment]
The folder name is /media/Media/Resilio. I should add that, as the name suggests, this folder is synced via the Resilio software to other machines; but so are other folders that I can successfully view. So it's possible it's related to the Resilio software is some way, but unlikely given that all other work.

**Comment by eine** [comment]
@rhjmoore, unfortunately, this seems to be a tricky issue to triage. On the one hand, you can try to reproduce the problem in a virtual/portable machine, such as a session in play-with-docker. That will allow other people to further analyze it. On the other hand, in order to get additional and specific log messages, you will need to add `log.Println()` instructions to the codebase and build filebrowser yourself.

Just in case, did you already check the console log in the browser?

**Comment by rhjmoore** [comment]
Understood that it is difficult to triage. I'm running the docker build; I'll have to have a go at building the code myself to then try adding the print statements you suggest. And yes, I've checked the log, just a note that the server is listening to the port. Thanks anyway.
I'll open a new issue if I get it built, logged and have something more specific to report.
