### ISSUE TITLE
list a lot of files direcotry : out of memory

### ISSUE THREAD

**Issue by glinuz** [filebrowser/filebrowser#541]
fatal error: runtime: out of memory

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 20 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/filebrowser/filebrowser/vendor/github.com/robfig/cron.(*Cron).Start
	/go/src/github.com/filebrowser/filebrowser/vendor/github.com/robfig/cron/cron.go:127 +0x43

**Comment by eine** [comment]
@glinuz, please answer the questions suggested in the template/form, in order to allow other users understand and reproduce your issue.

**Comment by glinuz** [comment]
W**Description**
When open a directory,with a lot of files,more than 400(my host),web show internal error. The console log : out of memory.

**Expected behaviour**
open directory ,with a lot of files.

**What is happening instead?**
fatal error: runtime: out of memory

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 20 [running]:
goroutine running on other thread; stack unavailable
created by github.com/filebrowser/filebrowser/vendor/github.com/robfig/cron.(*Cron).Start
/go/src/github.com/filebrowser/filebrowser/vendor/github.com/robfig/cron/cron.go:127 +0x43


My environment : Centos 7.4  64ibt v1.10.0 xfs,with more than 400 files
