### ISSUE TITLE
Suggest paging with a lot of files directory, bugout of memory

### ISSUE THREAD

**Issue by glinuz** [filebrowser/filebrowser#544]
**Is your feature request related to a problem? Please describe.**
With a lot of files directory ,GetList() listingHandler() funtion ,well out of memory

**Describe the solution you'd like**
Add paging or limit number web list size,with Ajax load more listing item

my problem ,with centos 7 v1.10.0, one directory with more than 400 files.
when web load , crash down. with "out of memory " error.

**Comment by helloray** [comment]
I use filebrowser(arm/x86 version) with over 10000 files in a single directory. No crash happened.

**Comment by hacdias** [comment]
Fix on newer version since we don't load the files data. Although I find it strange anyway to have that error.
