### ISSUE TITLE
Failed to get file browser compiled due to obsolete directory structure.

### ISSUE THREAD

**Issue by hufh** [filebrowser/filebrowser#545]
**Description**
Current directory structure is not for higher version GO. New go version requires that all the source code directories are put under "src" directory. I used GO 1.8 to compile, the compiler failed to find source files.

**Expected behaviour**
For higher version of GO, currently directory should be adjusted. "cli", "lib" should be moved into "src" directory, and build scripts under "build" need to be modified. And documents should be updated as well.

**Comment by eine** [comment]
Hi @hufh. This project is actually being built with the latest go version:

``` bash
docker run --rm -it filebrowser/dev go version
go version go1.11 linux/amd64
```

At the same time, all the builds pass successfully in the CI environment: https://travis-ci.com/filebrowser

Can you, please, let us know which problem/error did you find? At the same time, could you provide any reference related to the requirement of having sources in subdir `src`?

**Comment by hufh** [comment]
@1138-4EB Thanks for reply. I finally found this link https://github.com/filebrowser/community/blob/master/builds.md, followed the instruction and successfully compiled it. The document is not so easy to find, I'd suggest to move the document to filebrowser repo from community repo.

But i still have problem to get it running. I got following errors:

[root@linux cli]# ./filebrowser
2018/10/05 10:56:37 Listening on [::]:46229
panic: could not locate box "../frontend/dist"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0xda7824, 0x10, 0x744f05)
	/usr/lib/golang/src/github.com/GeertJohan/go.rice/box.go:110 +0x97
github.com/filebrowser/filebrowser/lib.(*FileBrowser).Setup(0xc42012e1e0, 0x1, 0xd6cd06)
	/usr/lib/golang/src/github.com/filebrowser/filebrowser/lib/filebrowser.go:138 +0x48
github.com/filebrowser/filebrowser/cli/cmd.handler(0xc420199b80, 0x2)
	/usr/lib/golang/src/github.com/filebrowser/filebrowser/cli/cmd/server.go:119 +0x9b9
github.com/filebrowser/filebrowser/cli/cmd.Serve()
	/usr/lib/golang/src/github.com/filebrowser/filebrowser/cli/cmd/server.go:72 +0x4c4
github.com/filebrowser/filebrowser/cli/cmd.glob..func2(0x13c8de0, 0x13fa670, 0x0, 0x0)
	/usr/lib/golang/src/github.com/filebrowser/filebrowser/cli/cmd/serve.go:17 +0x20
github.com/spf13/cobra.(*Command).execute(0x13c8de0, 0x13fa670, 0x0, 0x0, 0x13c8de0, 0x13fa670)
	/usr/lib/golang/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x13c8920, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/github.com/spf13/cobra/command.go:852 +0x334
github.com/spf13/cobra.(*Command).Execute(0x13c8920, 0xc420000260, 0x0)
	/usr/lib/golang/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/filebrowser/filebrowser/cli/cmd.Execute()
	/usr/lib/golang/src/github.com/filebrowser/filebrowser/cli/cmd/root.go:36 +0x32
main.main()
	/root/filebrowser/cli/main.go:6 +0x20

My OS is CentOS 7.2, 1511, and go version is 1.9.4. I also tried it with go 1.10 on another machine, but both failed.  I used native mode to compile rather than docker mode.

Could you give me a hand?  Thanks.

**Comment by hufh** [comment]
@1138-4EB If you run "go help gopath", you can get following info:


---------------------------------------------------------
"See https://golang.org/wiki/SettingGOPATH to set a custom GOPATH.

Each directory listed in GOPATH must have a prescribed structure:

The src directory holds source code. The path below src
determines the import path or executable name.
......
Here's an example directory layout:

    GOPATH=/home/user/go

    /home/user/go/
        src/
            foo/
                bar/               (go code in package bar)
                    x.go
                quux/              (go code in package main)
                    y.go
        bin/
            quux                   (installed command)
        pkg/
            linux_amd64/
                foo/
                    bar.a          (installed package object)
---------------------------------------------------------

It suggests that all the source code should be put under "src" folder. I am not sure if we should do so.

**Comment by eine** [comment]
The GOPATH is not the same as the root of the repository. The repositories are located in `$GOPATH/src/filebrowser/*`, indeed.

About the error you are getting, did you build the frontend and execute rice prior to building the backend?

**Comment by hufh** [comment]
> The GOPATH is not the same as the root of the repository. The repositories are located in `$GOPATH/src/filebrowser/*`, indeed.
> 
> About the error you are getting, did you build the frontend and execute rice prior to building the backend?

Yes, i did. My GOPATH is as follows. Is that correct?

[root@linux filebrowser]# ls
build  cli  Dockerfile  Docker.json  frontend  lib  LICENSE  README.md  src
[root@linux filebrowser]# echo $GOPATH
/root/filebrowser/
[root@linux filebrowser]# pwd
/root/filebrowser

**Comment by eine** [comment]
Please, have a look at:

- https://golang.org/doc/code.html
- https://github.com/golang/go/wiki/GOPATH

**Comment by hufh** [comment]
> Please, have a look at:
> 
> * https://golang.org/doc/code.html
> * https://github.com/golang/go/wiki/GOPATH

Thanks for reply. I double-checked the  procedure and got it recompiled sucessfully, but i still got following error:

[root@bogon cli]# ./filebrowser
2018/10/06 09:45:31 Listening on [::]:44910
panic: could not locate box "../frontend/dist"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0xd01ab7, 0x10, 0xc4201d15c0)
	/root/github/filebrowser/src/github.com/GeertJohan/go.rice/box.go:110 +0x97
github.com/filebrowser/filebrowser/lib.(*FileBrowser).Setup(0xc4201661e0, 0x0, 0x0)
	/root/github/filebrowser/src/github.com/filebrowser/filebrowser/lib/filebrowser.go:138 +0x48
github.com/filebrowser/filebrowser/cli/cmd.handler(0xc42014db88, 0x2)
	/root/github/filebrowser/src/github.com/filebrowser/filebrowser/cli/cmd/server.go:119 +0x755
github.com/filebrowser/filebrowser/cli/cmd.Serve()
	/root/github/filebrowser/src/github.com/filebrowser/filebrowser/cli/cmd/server.go:72 +0x480
github.com/filebrowser/filebrowser/cli/cmd.glob..func2(0x128b620, 0x12bc1e0, 0x0, 0x0)
	/root/github/filebrowser/src/github.com/filebrowser/filebrowser/cli/cmd/serve.go:17 +0x20
github.com/spf13/cobra.(*Command).execute(0x128b620, 0x12bc1e0, 0x0, 0x0, 0x128b620, 0x12bc1e0)
	/root/github/filebrowser/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x128b160, 0x0, 0x0, 0x0)
	/root/github/filebrowser/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x128b160, 0x0, 0xb5629b)
	/root/github/filebrowser/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/filebrowser/filebrowser/cli/cmd.Execute()
	/root/github/filebrowser/src/github.com/filebrowser/filebrowser/cli/cmd/root.go:36 +0x32
main.main()
	/root/github/filebrowser/src/github.com/filebrowser/cli/main.go:6 +0x20

I understand that the original issue should be closed, should i open a new issue for this runtime error? Thanks for your patience.
