### ISSUE TITLE
mkdir file: permission denied

### ISSUE THREAD

**Issue by opser-gavin** [filebrowser/filebrowser#548]
10月 20 15:01:24 localhost.localdomain caddy[27586]: 2018/10/20 15:01:24 /aaa/: 403 Forbidden
10月 20 15:01:24 localhost.localdomain caddy[27586]: 2018/10/20 15:01:24 mkdir file: permission denied
10月 20 15:01:43 localhost.localdomain kernel: hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
10月 20 15:02:01 localhost.localdomain systemd[1]: Created slice User Slice of root.
10月 20 15:02:01 localhost.localdomain systemd[1]: Starting User Slice of root.
10月 20 15:02:01 localhost.localdomain systemd[1]: Started Session 13002 of user root.
10月 20 15:02:01 localhost.localdomain systemd[1]: Starting Session 13002 of user root.
10月 20 15:02:01 localhost.localdomain CROND[27607]: (root) CMD (/usr/sbin/ntpdate pool.ntp.org > /dev/null 2>&1)

**Comment by hacdias** [comment]
You still have this issue?
