### ISSUE TITLE
Can not create a folder

### ISSUE THREAD

**Issue by tboerger** [filebrowser/filebrowser#55]
I have tried to create a folder but that is currently not possible.

<img width="1440" alt="bildschirmfoto 2016-02-25 um 18 37 19" src="https://cloud.githubusercontent.com/assets/156964/13328546/8081ce86-dbef-11e5-83e0-6207e8893d3c.png">

**Comment by tboerger** [comment]
Do you know how long it takes to get it integrated into the caddy builds from the website?

**Comment by hacdias** [comment]
When this PR is merges (https://github.com/caddyserver/caddyserver.com/pull/32) it will be updated too!
