### ISSUE TITLE
load txt failed

### ISSUE THREAD

**Issue by Ya-RZ** [filebrowser/filebrowser#551]
**Description**

filebrowser cannot show the txt file list . 

I have some txt、mobi which size is 440M. But when i browser those files on mobile chrome , the browers always crashed  after several seconds. In the several seconds ,it downloaded somethind with full speed. I guess the space cannot hold ,so the chrome crashes. 
The desktop chrome has the similar problem, which loads  very very slow.

**What is happening instead?**

192.168.2.187 - - [21/Oct/2018:15:34:56 +0800] "GET /novel/ HTTP/1.1" 200 3444
192.168.2.187 - - [21/Oct/2018:15:34:56 +0800] "GET /novel/api/auth/renew HTTP/1.1" 200 476
192.168.2.187 - - [21/Oct/2018:15:34:59 +0800] "GET /novel/api/resource/ HTTP/1.1" 200 457304062

**Comment by helloray** [comment]
440M is too large for a browser. The local program such as notepad may be hard to open it too.

**Comment by Ya-RZ** [comment]
@helloray It's not a file but almost 10 files . It always downloads txt file , which confuses me.

**Comment by hacdias** [comment]
I think that what you're saying is that when you go to a directory, it downloads all the text files. Yes, it isn't supposed to happen and this fix (28b326ab1df32f41234c0d48f3555f1a18e2ffeb) will be available when 2.0 is out.
