### ISSUE TITLE
Download manager/folder link

### ISSUE THREAD

**Issue by bonny1992** [filebrowser/filebrowser#552]
Hello everyone!
Is it possible to obtain in some way a sort of direct link for a single file or a folder (maybe through the "share" button?) to make it work with download managers like JDownloader?

I know that I can share the file/folder then add the ?dl=1 querystring, but it can be heavy if the server has to compress a lot of files and more than 1 user at a time.
Also, JDownloader for example, isn't able to obtain size data from the url.

**Comment by hacdias** [comment]
JDownloader can't obtain the size data due to #323. I'm closing this as the latest version provides better direct links.

The file will only be compressed if it is a folder. A file is downloaded directly.
