### ISSUE TITLE
is possible to "open" the html file , not edit ?

### ISSUE THREAD

**Issue by changchichung** [filebrowser/filebrowser#553]
let`s I have a folder with many html files , and I want give users a web ui to view those html files , like the way you do in browsers(file --> open --> select the html file)

with this plugin , almost solve my problem , I dont need to generate a folder tree , export to html , and use nginx or apache to serve. and it`s much more pretty than the ui I wrote .. XD

but when users double click the html file , the plugin open the file to "edit" , is there any way to change that ?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
