### ISSUE TITLE
Build failed after hugo updated: undefined: parser.ReadFrom

### ISSUE THREAD

**Issue by helloray** [filebrowser/filebrowser#554]
How to resolve it?

**Comment by helloray** [comment]
I use local vendor directory solve this issue.  
cd $GOPATH/src/github.com/filebrowser/filebrowser
mkdir -p vendor/github.com/gohugoio
cd vendor/github.com/gohugoio
git clone https://github.com/gohugoio/hugo -b release-0.49.2
After that, everything is OK. Maybe the better way is to use dep for  dependency management.

**Comment by eine** [comment]
Related to #496.

**Comment by vitaliy-kuzmich** [comment]
> I use local vendor directory solve this issue.
> cd $GOPATH/src/github.com/filebrowser/filebrowser
> mkdir -p vendor/github.com/gohugoio
> cd vendor/github.com/gohugoio
> git clone https://github.com/gohugoio/hugo -b release-0.49.2
> After that, everything is OK. Maybe the better way is to use dep for dependency management.

/lib/http/download.go:54:17: type archiver.Zip is not an expression
../lib/http/download.go:56:17: type archiver.Tar is not an expression
../lib/http/download.go:58:17: type archiver.TarGz is not an expression
../lib/http/download.go:60:17: type archiver.TarBz2 is not an expression
../lib/http/download.go:62:30: undefined: archiver.TarXZ
../lib/http/download.go:75:11: ar.Write undefined (type archiver.Archiver has no field or method Write)

**Comment by hacdias** [comment]
Hello! I actually suggest blurring the line between front-matter and content and leave it in the same editor. That way we can stop depending on Hugo.

The archiver thing I'll open a PR soon, but we also need to define if we're removing Hugo as a dependency or not.

**Comment by pandarong** [comment]
git clone https://github.com/gohugoio/hugo -b release-0.49.2
git clone https://github.com/mholt/archiver
cd archiver
git tag -l
git checkout v2.1.0
replace the archiver ,hugo folder in gopatch,it will build successful.

i will fix the filebrowser with Latest dependency options

**Comment by benfff85** [comment]
Just a friendly inquiry, is this impacting the publication of an updated docker image? I tried this out locally and love it but #522 is preventing it from being used behind a reverse proxy.

**Comment by Syavne** [comment]
Docker build is indeed affected, the following command ends up with the error message:
`docker build --build-arg plugins=filemanager github.com/abiosoft/caddy-docker.git`

I'm looking for a successful deploy pointing to a specific base URL, either with the Caddy plugin or a reverse proxy.

**Comment by hacdias** [comment]
I'm working on a rewrite/revamp/cleanup for File Browser #574. It won't be available until the end of the month certainly. I don't like to give precise values but I believe that in the middle of January it will be ready.

Please use an older build (tagged) for now. Sorry
