### ISSUE TITLE
Hugo: Restrict user scope (access) to subfolder of content. Unexpected "Hugo New" behaviour.

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#555]
# Is your feature request related to a problem? Please describe.

## Our setup:
We have a small community homepage where kind of a lot of people are allowed to make blog posts. Not edit the rest of our Hugo-Site. 

## Our temporarily solution
So I give them a filebrowser account with scope to ./content/blog/username . I do that because I don't want them to be able to edit each others blog posts. When they intuitively press "Hugo New" they can't just enter the title they have to type /blog/username/title in the title field, otherwise they still are able to create the basic file anywhere in the ./content directory, no matter how scope is defined, but they won't be able to delete or edit this later, so I have to do the cleanup. I can teach them to do that right, but then they see:

home --> ... --> blog --> username --> title.markdown
"This location can't be reached." 

Nevertheless they can select home now and edit their content.

#  Describe the solution you'd like
I would like the limeted-content-scope-users to be able to skip the /content/blog/ part in the title-field  aka set a custom title prefix. Which would be enough to serve this according to the hugo syntax.

Afterwards they should get redirected to their content without the error message, which is no real error.

# Describe alternatives you've considered
Please tell me.

**Comment by ghost** [comment]
I see, related to  #523.

**Comment by hacdias** [comment]
As we'll remove staticgen feature on 2.0, I'm closing this.
