### ISSUE TITLE
not working with mobile browser

### ISSUE THREAD

**Issue by mphz** [filebrowser/filebrowser#559]
**Description**
I have run the filebrowser in host, and via chrome and firefox in PC it works pretty well, but when I try in my iPhone not matter safari, chrome and firefox, it stucks in the loading page with animation.

**Comment by helloray** [comment]
I can confirm mobile browser is working perfectly with filebrowser. I use android and tested with chrome/firefox.

**Comment by mphz** [comment]
@helloray yeah, I can also confirm that, really weird, today it works. I think can close the issue.. thx
