### ISSUE TITLE
madvise: function not implemented

### ISSUE THREAD

**Issue by ousui** [filebrowser/filebrowser#566]
I want to run filebrowser for my Router which is NetGear R6300v2.
The cpu is BCM4708 A9.
```
root@ROUTER-R6300v2:/opt/tmp# uname -a
Linux ROUTER-R6300v2 4.4.134 #568 SMP Thu May 31 11:02:32 CEST 2018 armv7l GNU/Linux
```

When I download linux-armv5-filebrowser.tar.gz which version is 1.10.0, and run it:
```
root@ROUTER-R6300v2:/opt/tmp# filebrowser
Listening on 0.0.0.0:43667
2018/11/10 09:49:39 madvise: function not implemented
```

But when I run caddy with filemanager, it can be run well good.

**Comment by eine** [comment]
> But when I run caddy with filemanager, it can be run well good.

This is interesting. How did you get the binaries? Were both of them (filebrowser and caddy) built in the same context?

**Comment by ousui** [comment]
@1138-4EB No, I found them on the official website or github.com.
caddy: https://caddyserver.com/download/linux/arm5?plugins=http.filemanager&license=personal&telemetry=off (https://caddyserver.com/download)
filebrowser: https://github.com/filebrowser/filebrowser/releases/download/v1.10.0/linux-armv5-filebrowser.tar.gz (https://github.com/filebrowser/filebrowser/releases)

**Comment by eine** [comment]
The tarball for filebrowser is generated with [goreleaser](https://github.com/goreleaser/goreleaser) (see https://github.com/filebrowser/filebrowser/blob/master/.goreleaser.yml).

However, the binary you get with goreleaser is slightly different from the one you get when building it yourself: https://github.com/filebrowser/filebrowser/blob/master/build/build.sh#L15

Last, caddy is built with it's own procedure.

Therefore, it can be tricky to find which is the difference that triggers this error.

**Comment by ousui** [comment]
> The tarball for filebrowser is generated with [goreleaser](https://github.com/goreleaser/goreleaser) (see https://github.com/filebrowser/filebrowser/blob/master/.goreleaser.yml).
> 
> However, the binary you get with goreleaser is slightly different from the one you get when building it yourself: https://github.com/filebrowser/filebrowser/blob/master/build/build.sh#L15
> 
> Last, caddy is built with it's own procedure.
> 
> Therefore, it can be tricky to find which is the difference that triggers this error.

Thank you~
