### ISSUE TITLE
Add an automatic option to the locale directive as the default for Caddy Plugins

### ISSUE THREAD

**Issue by daiaji** [filebrowser/filebrowser#570]
**Is your feature request related to a problem? Please describe.**
In fact, I found that the filebrowser login page will automatically select locale for me, but after I log in with the admin user, filebrowser will use the English page.
Even if my browser requests the correct Accept-Language.

**Describe the solution you'd like**
Add an automatic option to the locale directive as the default for Caddy Plugins

**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
