### ISSUE TITLE
Symlinks should not always treated as files

### ISSUE THREAD

**Issue by mmahmoudian** [filebrowser/filebrowser#572]
**Description**
In the file lists, a symlink is always represented as a file regardless of it being pointing at a file or folder.

**Expected behaviour**
If the symlink is pointing at a folder, it shows it as among the folders with folder icon and possibly with an icon to show this is a symlink (something link a shortcut sign on a folder"

**What is happening instead?**
Showing the symlinks that are pointing at a folder among files

**Comment by rudymartinb** [comment]
as a hint

cd /picadora/filebrowser/ 
ln -s /picadora/entrada/aH264 entradas

target directory has write access but I want to prevent files being created on /picadora/filebrowser/ 

chmod -w .

when uploading a file "farmacias.txt" to one of those dirs I got this on the console:

2018/11/29 12:06:01 open /picadora/filebrowser/entradafarmacias.txt: permission denied

**Comment by mmahmoudian** [comment]
@rudymartinb I think what you commented here has little to do with what I intended to imply. It is indeed symlink related, but what you are addressing is about write permission (back-end) and what I'm pointing at is the sorting and icon in the file view part (front-end).

**Comment by eine** [comment]
@mmahmoudian is ok. @rudymartinb, please open a new issue.
