### ISSUE TITLE
在前端增加类似YAAW的插件实现像百度云一样的离线下载功能

### ISSUE THREAD

**Issue by idcm** [filebrowser/filebrowser#573]
能不能把aria2的web管理界面https://github.com/binux/yaaw
集成到filebrowser前端里，然后在filebrowser添加是否开启这一插件的选项。在同时安装filebrowser和aria2的电脑上就能实现离线下载和文件管理了。

**Comment by pandarong** [comment]
这个项目现在缺少人维护。现在计划
1.增加对新版本go 1.11 modules 新功能支持，版本管控
2.依赖库mholt/archiver 3.0以上，hugo 5.0以上版本适配
3.codemirror 改为 monaco-editor

**Comment by hacdias** [comment]
Unfortunately, aria2 is out of the scope of this project so I'm closing this.
