### ISSUE TITLE
logfile is too simple to be parsed by fail2ban etc

### ISSUE THREAD

**Issue by laoshaw** [filebrowser/filebrowser#576]
I'm trying to use fail2ban to protect filebrowser brutal-force login attack.

however the log file only output:

2018/11/30 22:19:17 /auth/get: 403 Forbidden

which does not contain the remote-IP, thus fail2ban has no way to know which IP to block.

can we make the logfile more useful?

**Comment by hacdias** [comment]
Yes, we can add that

**Comment by eine** [comment]
@laoshaw is it ok to add just the IP to the standard log? Or should it have a specific format to make it easier to read/parse? Moreover, is it reasonable to add a separate log file for this purporse?

**Comment by laoshaw** [comment]
@1138-4EB  it will be great if the log can contain remote-IP, username, and a timestamp when login occurred. If this is too complicated to add, at least have remote-IP in the log file will help. As an example, below is a log line from gitea project(another golang project):

2018/11/30 23:01:13 [I] Failed authentication attempt for gitea_user from 21.65.123.14

Thanks!

**Comment by UnAfraid** [comment]
```diff
diff --git a/lib/http/http.go b/lib/http/http.go
index cadc893..61e2940 100644
--- a/lib/http/http.go
+++ b/lib/http/http.go
@@ -26,7 +26,7 @@ func Handler(m *fb.FileBrowser) http.Handler {
                        w.WriteHeader(code)

                        txt := http.StatusText(code)
-                       log.Printf("%v: %v %v\n", r.URL.Path, code, txt)
+                       log.Printf("%v: %v %s %v\n", r.URL.Path, code, r.RemoteAddr, txt)
                        w.Write([]byte(txt + "\n"))
                }
```
This should provide ip address in the logs for > 400 status code.
Should i open up pull request also which branch should i target because i notice there is some revamp/rework in progress.

**Comment by laoshaw** [comment]
> ```diff
> diff --git a/lib/http/http.go b/lib/http/http.go
> index cadc893..61e2940 100644
> --- a/lib/http/http.go
> +++ b/lib/http/http.go
> @@ -26,7 +26,7 @@ func Handler(m *fb.FileBrowser) http.Handler {
>                         w.WriteHeader(code)
> 
>                         txt := http.StatusText(code)
> -                       log.Printf("%v: %v %v\n", r.URL.Path, code, txt)
> +                       log.Printf("%v: %v %s %v\n", r.URL.Path, code, r.RemoteAddr, txt)
>                         w.Write([]byte(txt + "\n"))
>                 }
> ```
> 
> This should provide ip address in the logs for > 400 status code.
> Should i open up pull request also which branch should i target because i notice there is some revamp/rework in progress.

this change seems non-intrusive, please make sure PR will be merged in next release

**Comment by UnAfraid** [comment]
I need to know which branch to target with my PR

**Comment by hacdias** [comment]
Hello! Will be available on v2.0! I'm closing this to remove the clutter in the meanwhile. For more info, check #574 and #575!

**Comment by vbaros** [comment]
Anyone managed to setup fail2ban from docker to work with filebrowser also on docker?
Can you please share the steps?

**Comment by Quantumatum** [comment]
> Anyone managed to setup fail2ban from docker to work with filebrowser also on docker? Can you please share the steps?

Did you ever figure this out? I too would like to do this
