### ISSUE TITLE
disallow file folder can be searched

### ISSUE THREAD

**Issue by ericma15** [filebrowser/filebrowser#578]
**Description**
when i try to disallow a user to see a folder, i use this,
`disallow /Python-3.7.1`
in fact,the file folder disappear
![image](https://user-images.githubusercontent.com/27952575/49489254-14e9b700-f885-11e8-8b62-c4990888a135.png)
but unexpected, I still can search the folder.
![image](https://user-images.githubusercontent.com/27952575/49489286-364aa300-f885-11e8-9712-4f5d4bb27a5d.png)
So how can I solve this problem?
Thx :)

**Comment by hacdias** [comment]
This is fixed and will be available on 2.0!
