### ISSUE TITLE
Dependency management is in urgent need

### ISSUE THREAD

**Issue by silentred** [filebrowser/filebrowser#579]
It took me more than half hour to solve the dependency problem.  It needs more work than just doing `go get`. Some packages changed to a total different API in master branch, so I have to check the git log and try to choose some history commit  by luck. 

For examle, `github.com/mholt/archiver` changed to new API after 5105dc13ef4742e45ae9fcc7e98fa413cb7ca876. The new API cannot be used in the project.

**Suggestion**: use vendor dir to include all dependencies to this repo.

**Comment by hacdias** [comment]
Hello! We're working on a new version that will all of that in account. Sorry for the trouble.

@1138-4EB or @Equim-chan would you like to take a stab at this and add dep management on master already?

**Comment by eine** [comment]
@hacdias, I could succesfully add `go mod` support. But `gometalinter` fails. Please, have a look at #586.
