### ISSUE TITLE
X-Content-Type header not defined

### ISSUE THREAD

**Issue by bronzehedwick** [filebrowser/filebrowser#58]
Whenever I try to do any action through the admin interface that would require a `POST` request, I get a `Something went wrong` error in the GUI. When I looked in the error log, it showed `X-Content-Type header not defined`. Is there some configuration that I missed? I am using caddy/hugo out of the box.

Error log:

```
28/Feb/2016:10:24:29 -0500 [ERROR 400 /admin/edit/content/index.md] X-Content-Type header not defined
28/Feb/2016:10:25:00 -0500 [ERROR 400 /admin/edit/config.toml] X-Content-Type header not defined
28/Feb/2016:10:25:05 -0500 [ERROR 400 /admin/edit/config.toml] X-Content-Type header not defined
28/Feb/2016:10:25:09 -0500 [ERROR 400 /admin/edit/config.toml] X-Content-Type header not defined
28/Feb/2016:10:27:14 -0500 [ERROR 400 /admin/edit/content/index.html] X-Content-Type header not defined
28/Feb/2016:10:27:20 -0500 [ERROR 400 /admin/edit/content/index.html] X-Content-Type header not defined
28/Feb/2016:10:28:37 -0500 [ERROR 400 /admin/edit/content/index.html] X-Content-Type header not defined
28/Feb/2016:10:30:59 -0500 [ERROR 406 /admin/edit/content/home] File format not supported.
28/Feb/2016:10:30:59 -0500 [ERROR 406 /admin/edit/content/home] File format not supported.
28/Feb/2016:10:31:21 -0500 [ERROR 400 /admin/edit/content/home.md] X-Content-Type header not defined
28/Feb/2016:11:03:57 -0500 [ERROR 400 /admin/edit/content/home.md] X-Content-Type header not defined
28/Feb/2016:11:04:27 -0500 [ERROR 400 /admin/edit/config.toml] X-Content-Type header not defined
28/Feb/2016:11:05:01 -0500 [ERROR 400 /admin/edit/config.toml] X-Content-Type header not defined
28/Feb/2016:11:05:17 -0500 [ERROR 400 /admin/edit/config.toml] X-Content-Type header not defined
28/Feb/2016:11:14:51 -0500 [ERROR 400 /admin/edit/content/home.md] X-Content-Type header not defined
28/Feb/2016:11:14:55 -0500 [ERROR 400 /admin/edit/content/home.md] X-Content-Type header not defined
```

**Comment by hacdias** [comment]
When you say out of the box you mean you downloaded it from http://caddyserver.com, right?

**Comment by bronzehedwick** [comment]
Yes, the Mac version.

**Comment by hacdias** [comment]
Strange. No one had that problem until now. Are you sure your js is enabled? If so, please check the console on developer tools (normally F12) on the browser and check if there are any errors. If so, paste them here pls.

**Comment by hacdias** [comment]
Also, please check the source of those pages and check if the buttons have the data-type attribute defined somehow like they are in this file: https://github.com/hacdias/caddy-hugo/blob/master/templates/editor.tmpl#L49 .

**Comment by bronzehedwick** [comment]
Javascript is enabled. When i try to save I get a `400 Bad Request` error:

```
HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Server: Caddy
Vary: Accept-Encoding
x-content-type-options: nosniff
Date: Sun, 28 Feb 2016 17:00:45 GMT
Content-Length: 40
```

**Comment by bronzehedwick** [comment]
Source of my test `home.md` page is super simple:

``` md
# Home
yep
```

**Comment by hacdias** [comment]
No, the source of /admin/edit/content/home.md PLS.

**Comment by bronzehedwick** [comment]
Maybe this is where I'm doing something wrong; I'm not sure where that path is.

My directory structure looks like this:

```
.
├── Caddyfile
├── LICENSE
├── README.md
├── access.log
├── archetypes
├── config.toml
├── content
│   ├── home.md
│   └── post
│       └── first.md
├── data
├── error.log
├── layouts
├── public
│   ├── 404.html
│   ├── apple-touch-icon-144-precomposed.png
│   ├── css
│   │   ├── hyde.css
│   │   ├── poole.css
│   │   └── syntax.css
│   ├── favicon.png
│   ├── home
│   │   └── index.html
│   ├── index.html
│   ├── index.xml
│   ├── post
│   │   ├── first
│   │   │   └── index.html
│   │   ├── index.html
│   │   └── index.xml
│   ├── robots.txt
│   └── sitemap.xml
├── static
└── themes
    ├── LICENSE
    ├── README.md
    ├── hyde
    │   ├── LICENSE.md
    │   ├── README.md
    │   ├── archetypes
    │   │   └── default.md
    │   ├── images
    │   │   ├── screenshot.png
    │   │   └── tn.png
    │   ├── layouts
    │   │   ├── 404.html
    │   │   ├── _default
    │   │   │   ├── list.html
    │   │   │   └── single.html
    │   │   ├── index.html
    │   │   └── partials
    │   │       ├── disqus.html
    │   │       ├── head.html
    │   │       └── sidebar.html
    │   ├── static
    │   │   ├── apple-touch-icon-144-precomposed.png
    │   │   ├── css
    │   │   │   ├── hyde.css
    │   │   │   ├── poole.css
    │   │   │   └── syntax.css
    │   │   └── favicon.png
    │   └── theme.toml
```

In case this is useful, my Caddyfile is:

```
localhost:2020
gzip
log ./access.log
browse
root public
hugo
errors ./error.log
```

**Comment by hacdias** [comment]
Why are you using browse directive? Try removing it please.

**Comment by bronzehedwick** [comment]
Removed browse, same error.

**Comment by bronzehedwick** [comment]
`config.toml` is:

```
baseurl = "http://localhost:2020"
languageCode = "en-us"
title = "Test Hugo"
theme = "hyde"
```

**Comment by hacdias** [comment]
Please give me the source-code of `http://localhost:2020/admin/edit/content/home.md` so I can check if Go vars are being evaluated, pls.

And please check the **console** of developer tools of your browser to see if there is any error there or some valuable information.

![screenshot 103](https://cloud.githubusercontent.com/assets/5447088/13381492/a482c91c-de55-11e5-8178-537c0a8ec062.png)

**Comment by bronzehedwick** [comment]
The source of `http://localhost:2020/admin/edit/content/home.md` is the source I already posted:

``` md
# Home
yep
```

I actually narrowed down the issue: it only works in Chrome. I was using Firefox initially, and tested in Safari, and both have the same issue. Is the admin Chrome only?

**Comment by hacdias** [comment]
Hmm... I've only tested it on Chrome and Edge. Later today I'll test it on other browsers.

I didn't want the source code of "home.md"! I want the source of the page when editing the file. Open the URL, right click on the page, and there should be a button which says " View Source". But if it works on Chrome, the problem is not in there. It might be in JavaScript. 

So, can you please check the console of developer tools on Firefox. The console, not the headers of the response.

![Ff dev tools](https://mdn.mozillademos.org/files/5599/web-console-messages-highlighted.png)

**Comment by hacdias** [comment]
_Just for reference: it works on Firefox for Android._

**Comment by bronzehedwick** [comment]
Ah sorry, got confused. Here's a screenshot of the Firefox console, directly after clicking save.

<img width="1440" alt="screen shot 2016-02-29 at 6 38 05 am" src="https://cloud.githubusercontent.com/assets/637174/13393374/1498380a-deaf-11e5-9bb0-25fe15f593f6.png">

**Comment by hacdias** [comment]
Hey @bronzehedwick! I just tested with Firefox and it works here. But do the following, please:
1. Open the page in firefox
2. Open the developer console tools and go to Network tab
3. Save the file.
4. Click in the latest POST request it shows.
5. In the right side, click in Headers.
6. Copy the **Request** headers and paste them here.

They should be something like this:

```
Host: henriquedias.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json; charset=utf-8
X-Regenerate: false
X-Content-Type: content-only
X-Requested-With: XMLHttpRequest
Referer: https://henriquedias.com/admin/edit/content/teste.markdown
Content-Length: 17
Cookie: __cfduid=------------------------------------------
Authorization: ------------------------------------------
Connection: keep-alive
```

**Comment by hacdias** [comment]
_P.S.: I know caddy-hugo is adding a new line in the beginning of the file. It will be fixed in the next version._

**Comment by bronzehedwick** [comment]
Hey @hacdias, thanks for taking the time to look into this.

Here are the request headers from that page.

```
Host: localhost:2020
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:2020/admin/edit/content/home.md
Content-Type: application/json; charset=utf-8
X-Requested-With: XMLHttpRequest
Content-Length: 31
Cookie: stickynoties=true; stickynoties=true; sort=name; order=asc
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by hacdias** [comment]
Hello!

The problem is with X-Content-Type header indeed. If you're only using Hugo plugin, please download the newest version from [here](https://bintray.com/hacdias/generic/caddy-hugo). Those executables use the version from this repository.

If the error persists, open `http://localhost:2020/admin/edit/content/home.md`, right click on the page, and then click `View Source` (or something like that). Then, copy and paste what you see here, pls.

**Comment by hacdias** [comment]
@bronzehedwick any news?

**Comment by bronzehedwick** [comment]
@hacdias sorry I haven't had a chance to test but will soon

**Comment by hacdias** [comment]
Sure

**Comment by bronzehedwick** [comment]
Hm, I must be doing something else wrong.  Using the `caddy_darwin_amd64.zip` archive from this page: `https://bintray.com/hacdias/generic/caddy-hugo/view#files/caddy-hugo/1457035347`, I get the following error:

```
Activating privacy features... done.
user: Current not implemented on darwin/amd64
```

The command I'm using is `/path/to/caddy -conf="./Caddyfile"` from my caddy root directory.

**Comment by hacdias** [comment]
Try out a newer one please: https://bintray.com/hacdias/generic/caddy-hugo/1457192002/view

**Comment by justrjlewis** [comment]
I am also getting this [error](http://cl.ly/3s3p0e3y1A1U).
Here's the output from the console: [http://cl.ly/432g3O1G3V3y](http://cl.ly/432g3O1G3V3y)
This was Safari Version 9.0.3 (11601.4.4)

I did load the latest version.

Also, I'm not sure if it's related, but I cannot load the settings tab.  I get a 500 error that resolves to this in the log: 

```
07/Mar/2016:18:58:58 -0600 [PANIC /admin/edit/config.toml] go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:59 - interface conversion: interface is []map[string]interface {}, not map[string]interface {}
```

**Comment by hacdias** [comment]
Hey @justrjlewis!

For the configuration can you please open an issue and paste there your  config file?

You are using the latest version from caddyserver.com or from Bintray?

Can you please check the log? Or execute caddy with `-log stderr` flag to see what the error is, please?

Thanks

**Comment by justrjlewis** [comment]
Hi Henrique(@hacdias)!
I don't have an admin/edit/config.toml file.  Should I have created one?

Also I started with the one from caddyserver.com and then loaded the one from Bintray after I read this thread.

**Comment by hacdias** [comment]
You should have a config.toml in the folder you have your Hugo website.

Have you run Caddy with the flag I mentioned before?

**Comment by hacdias** [comment]
@justrjlewis open a new issue, please.

**Comment by bronzehedwick** [comment]
@hacdias sadly same error in the GUI. Got this in the error log:

```
10/Mar/2016:21:51:05 -0500 [PANIC /admin/edit/content/home.md] /home/travis/.gimme/versions/go/src/log/log.go:320 - X-Content-Type header not defined
10/Mar/2016:21:51:07 -0500 [PANIC /admin/edit/content/home.md] /home/travis/.gimme/versions/go/src/log/log.go:320 - X-Content-Type header not defined
```

**Comment by hacdias** [comment]
I'll try to solve this this weekend!

**Comment by bronzehedwick** [comment]
@hacdias thanks so much! Please let me know if I can help in any way.

**Comment by hacdias** [comment]
Hello @bronzehedwick 

Please try out [this](https://bintray.com/hacdias/generic/caddy-hugo/1457778991/view#files/caddy-hugo/1457778991) build and check if it works now!

**Comment by bronzehedwick** [comment]
@hacdias yes, that works, in both Firefox and Safari for me. Minor point, but the success message is blank in those browsers (it still displays fine in Chrome).

<img width="1145" alt="screen shot 2016-03-12 at 5 45 44 pm" src="https://cloud.githubusercontent.com/assets/637174/13725803/7e564154-e87a-11e5-8cf8-5a5d49b76773.png">

**Comment by hacdias** [comment]
~~What the....?? Just one more thing: the Publish button regenerates the website?~~

The error persists, but in a different way! But now I think I know what to do! **OMG I did so many changes and the error was always on JavaScript.**

**Comment by hacdias** [comment]
Hey @bronzehedwick 

Try [this build](https://bintray.com/hacdias/generic/caddy-hugo/1457861772/view#files/caddy-hugo/1457861772) please! I think it will work! :D

**Comment by bronzehedwick** [comment]
Yes, that works! Thanks so much.

**Comment by hacdias** [comment]
Awesome! Thank you too :D
