### ISSUE TITLE
Add "unix file socket" port option

### ISSUE THREAD

**Issue by tux456** [filebrowser/filebrowser#584]
Would be cool to have the option to listen on unix file socket instead of TCP port.  For example:
filebrowser --port=/home/user/my.sock

This can be useful on a shared server where we have only user access.   
- No need deal with random TCP port.
- The socket file can be visible for the user only, more secure than the TCP port.
- Easy to export with a SSH tunnel.

**Comment by tux456** [comment]
I just saw a little information link on "Unix Domain Socket with Go" with benchmark discussion.
https://eli.thegreenplace.net/2019/unix-domain-sockets-in-go/

**Comment by tux456** [comment]
It work perfectly!  I just compile and try:
`./filebrowser --socket=/home/john/test.sock`

"config set --socket=..." also work as expected. 

We can now export the socket easily with a ssh tunnel.  For example, I can now start the app on "remote.org" computer and listen on my desktop http://localhost:8080 with:
`ssh -fNL 8080:/home/john/test.sock john@remote.org`

We wanted to run filebrowser on a many users shared HPC cluster and authenticate it on a external proxy.  The "--socket" are the magic feature to give us the possibility to do it securely!  So useful for us!

Many thanks!!!

**Comment by hacdias** [comment]
Nice! v2.0.9 just [released!](https://github.com/filebrowser/filebrowser/releases/tag/v2.0.9)
