### ISSUE TITLE
Stuck on "Loading ..."

### ISSUE THREAD

**Issue by dbeniamine** [filebrowser/filebrowser#587]
**Description**

I use Filebrowser with a VNC and a nginx frontend on docker and it works quite smoothly, but when I try to open one of my directory which contains more than 400 csv files it is stuck showing "Loading ...".

I seems to work well when a directory contains many directories, so I guess it is trying to load thumbnails or something like that. If so, is their a parameter to disable thumbnails ?

**Expected behaviour**

My files should appear in a few seconds, maybe one minute

**What is happening instead?**

When I try to access the concerned directory, I get :

```
files_1_c564b18e2779 | 2018/12/27 14:54:04 http: multiple response.WriteHeader calls
files_1_c564b18e2779 | 2018/12/27 14:54:04 /dev/dir/: 500 Internal Server Error
files_1_c564b18e2779 | 2018/12/27 14:54:04 write tcp 192.168.80.2:80->192.168.80.3:49622: write: connection reset by peer
 ```

`192.168.0.2` is the filebrowser container and `192.168.80.3` is the nginx frontend

**Additional context**

I use version 1.10 because of #534

![screenshot](https://user-images.githubusercontent.com/2989133/50482033-f50d6500-09e4-11e9-9dfe-5f5737f6f796.png)

**Comment by dbeniamine** [comment]
Right after openning this issue I saw that the issue because of which I was stuck on `1.10` is solved, so I updated my image. Sadly this issue is still their with the last docker image `File Browser v(4945635b)`

**Comment by hacdias** [comment]
Images updated

**Comment by dbeniamine** [comment]
Sadly I cannot test as the last image does not accept the `--auth.method='none'` argument anymore:

```
Use "filebrowser [command] --help" for more information about a command.

2019/01/07 11:20:22 unknown flag: --auth.method
``

**Comment by hacdias** [comment]
We do not recommend the use of "latest" on production environments since it is bond to master branch, which, atm, contains the code for the next major release which contains many breaking changes. Please try out the image v1.11.0. Once we release V2, we'll have docs explaining how to transition 😄 sorry for any troubles

**Comment by dbeniamine** [comment]
I spoke too quickly: with `v1.11.0` I can use the `--auth.method=none` flags and I can open a directory with many files but it is quite slow:

|number of csv| time to open|
|------------------|-----------------|
| 45                  | 15s              |
| 180                | 36s              |
| 315                |  **killed after 5m** |

**Comment by hacdias** [comment]
Yeah. That's a bug we have fixed for 2.0. For some stupid reason we were sending the content of the files on directories (well... I don't know why). It will be available soon. 

Ah oh, when you said image I thought about docker. That's why I said "images updated". Sorry for the misunderstanding

**Comment by dbeniamine** [comment]
Yes I am using docker.

I'll wait for the 2.0 then, thanks for your help.

**Comment by dbeniamine** [comment]
Now that I can use 2.0.x, I confirm that it fixed the issue for me. 

Directories now open instantaneously, thanks for all the great work !
