### ISSUE TITLE
Setup Login with Caddy?

### ISSUE THREAD

**Issue by Merith-TK** [filebrowser/filebrowser#589]
**When did you download File Browser from caddyserver.com?**
12-31-18
**What is your entire Caddyfile?**

```text
files.merith.tk {
        filemanager / /opt/www/files {
                no_auth

                allow_edit              false
                allow_new               false
                allow_publish           false
                allow_commands          false


        }
}
```

**Description**
Essentially, I don't see anywhere in the caddy documentation to set up password authentication, so a user can log in and see files.

**Comment by eine** [comment]
@DovaMerith see https://github.com/filebrowser/filebrowser.github.io/pull/9#issuecomment-411735997.

> - ```--auth.method``` it the method of authentication between 'none', 'default' and 'proxy' authentication. Defaults to "default".
