### ISSUE TITLE
Change from gometalinter to golangci-lint

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#590]
As commented in [#586](https://github.com/filebrowser/filebrowser/pull/586#issuecomment-449879621), after v2 (or as part of it) we might consider changing to golangci/golangci-lint. See [golangci/golangci-lint#comparison](https://github.com/golangci/golangci-lint#comparison).

**Comment by hacdias** [comment]
I think we can try it now on #575. We could add golangci to our docker-dev image and keep the gometalinter until #575 is merged.
