### ISSUE TITLE
Copy text via shortcut don't work

### ISSUE THREAD

**Issue by belimo** [filebrowser/filebrowser#594]
Hi

I cannot copy text with shortcut ctrl+c inside of the filebrowser app. it only works if I copy the text via context menu. Issue is not dependent on any OS, I could reproduce the issue on MacOS Chrome, Linux Chromium, Windows Chrome and Mac Firefox.

STEPS TO REPRODUCE
Login to Filebrowser app:
host:port/filebrowser/files/
Mark the small text "File Browser v1.8.0" with mouse
Press ctrl+c
Press ctrl+v somewhere

ACTUAL BEHAVIOR
Some other text you copied before is pasted, not the "File Browser v1.8.0"

EXPECTED BEHAVIOR
"File Browser v1.8.0" should have been pasted

Interestingly, I can copy paste the text on the login screen of the filebrowser app. Issue only happen, if you are logged in. I usually would need this function while renaming files via GUI.

**Comment by belimo** [comment]
Hosting Support told me, issue is also reproducible with the newest version of filebrowser.

**Comment by belimo** [comment]
@hacdias and @dtwilliams10, can you help reproducing this issue, and maybe mark is as a bug?
@hugomassing I learned that you are frontent-developer and contributing to this project. Maybe you can look at it?

**Comment by hacdias** [comment]
@belimo can reproduce! Will be fixed on the next version

**Comment by belimo** [comment]
Thanks!

**Comment by hacdias** [comment]
Closing this. This fix will be available when 2.0 is released 😄
