### ISSUE TITLE
New Dockerfile

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#600]
Continuation of https://github.com/filebrowser/filebrowser/pull/575#issuecomment-451699904

@1138-4EB I added the entry point so the user wouldn't need to set the `--port 80` flag if they wan't to add more flags to the command. I saw that in postgres Docker image.

We could remove it, but then the user would put the `--port 80` if they add anything else to the command.

```Dockerfile
FROM scratch

COPY --from=filebrowser/dev /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

VOLUME /tmp
VOLUME /srv
EXPOSE 80

COPY filebrowser /filebrowser

ENTRYPOINT [ "/filebrowser" ]
CMD [ "--port=80" ]
```

If you don't add anything after the image name, it will run `filebrowser --port 80`. If you add `x`, it will run `filebrowser x` and remove the `--port 80`. This is because we can't have the flag always there. Some commands would fail.

But yes, we can remove the entrypoint. There is a quick setup when the DB doesn't exist and the user doesn't call `filebrowser init`.

**Comment by eine** [comment]
I think that we can handle this situation as we did in `v1`: if no `--port` flag, `FB_PORT` envvar or configuration option is provided, the port defaults to `80`. So the user only needs to set it if he/she wants a different port.

I am more concerned about the location of the database. In `docker-entrypoint.sh` it deaults to `/database.db`, which I find to be *ugly* outside a container. It should probably default to `./database.db`.

**Comment by hacdias** [comment]
But that value is **inside** the container (/database.db). THat's the path you need to mount something to.

Also, as part of the refactoring the ENV vars were removed. We're trying to leave the configuration as simple as possible. But I'm interested in hearing use cases.

**Comment by eine** [comment]
Despite the configuration being simplified, we should not constrain the deployment too much. For example, begin able to set runtime parameters such as the port, the address, the location of the DB, etc. should be easy. I.e., the default location of the database can be `/database.db`, but the user should be able to set it in any arbitrary path (either inside or outside of the container).

**Comment by hacdias** [comment]
Yes and they can do all of that via flags. In which situations wouldn't flags be possible but env vars would? That's just what I don't understand

**Comment by XavierBouvard** [comment]
Hi,

If I may, I am also more concerned about the database file than the port.

I agree with @1138-4EB: it is a good idea to naturally fallback to 80 if none specified in any kind of configuration.

> but the user should be able to set it in any arbitrary path (either inside or outside of the container).

This is especially true when the application is not running in a container.

Within a container I would recommend to use a dedicated folder for all data so the configuration stays simple or remains open to more.
Would it be possible to have a dedicated folder for datas ?

@hacdias : envs variables refers to the environment in which the program is hosted while flags are more for the program's internal behaviour. That being said, it is often hard to balance between config file, flags and environment variables.

Hope this helps,
Xavier

**Comment by hacdias** [comment]
@XavierBouvard 

> it is a good idea to naturally fallback to 80 if none specified in any kind of configuration.

Maybe that's the best: set the port default as 8080. Not 80 because of #152 

> This is especially true when the application is not running in a container.

They can already. It was always an option. The Dockerfile only refers to the container. The user can always set it with the flag.

> Would it be possible to have a dedicated folder for datas ?

Didn't understand.

> That being said, it is often hard to balance between config file, flags and environment variables.

Yes, that's the issue.

**Comment by hacdias** [comment]
Maybe remove the values from the flags from the root command (which starts the HTTP server) from the database.

Address, Cert, Key, Log, Port and Root Scope depend on the environment. This ones should be able to be set through flags, env variables and a config file and not persisted to the database. All the rest in the DB. Maybe that's the best.

```
  -a, --address string    address to listen on (default comes from database)
  -c, --cert string       tls certificate (default comes from database)
  -d, --database string   path to the database (default "./filebrowser.db")
  -h, --help              help for filebrowser
  -k, --key string        tls key (default comes from database)
  -l, --log string        log output (default comes from database)
  -p, --port int          port to listen on (default comes from database)
  -s, --scope string      scope for users
```

To:

```
  -a, --address string    address to listen on (default all)
  -c, --cert string       tls certificate
  -d, --database string   path to the database (default "./filebrowser.db")
  -h, --help              help for filebrowser
  -k, --key string        tls key
  -l, --log string        log output
  -p, --port int          port to listen on (default 80)
  -s, --scope string      scope for users (default ".")
```

This would solve some issues such as the DB precedence on this kind of configuration and viper.IsSet on #603

**Comment by XavierBouvard** [comment]
> Would it be possible to have a dedicated folder for datas ?

Sorry if it wasn't clear. When setting up containers I prefer use directory for volumes instead of file.
Here's an example: 
In the current version, if I want to run the container, I run:
`docker run -v /mnt/some-directory/filebrowser.db:/filebrowser.db [...]`

When i'd rather run:
`docker run -v /mnt/filebrowser-data:/data [...]`

In this case the data folder will contain the filebrowser.db (and maybe some other files in next versions).
Hoping this is clearer.

The new version looks much better to me :)
But shouldn't the default current scope be something else than "." since the db is in there by default ?
I found '/srv' good enough though.

**Comment by hacdias** [comment]
@XavierBouvard gotcha, but I don't know if that would benefit only you or more people. Let's see what @1138-4EB says.

About the default scope: right now it is "." and that's what it should be. It allows fast deployment.

There will be two scopes on this version: take a look at #604 to understand better. I'll update the docs soon too.

**Comment by eine** [comment]
@XavierBouvard, see #604. In the next release there will be a root path, and all the relative locations will refer to it. Therefore, if you DB lies in that path, you will be able to share a single directory.

**Comment by XavierBouvard** [comment]
OK.

This makes me feel like I misunderstood the purposes of the two volumes declared in your Dockerfile.
I though that /srv would old the directory I want to administrate (I think you call that default scope) and I was wandering about the /tmp

Anyway, thanks for your answers, I'll take a look at #604 even if I have not worked in go yet, it'll be interesting to watch some :)

**Comment by eine** [comment]
@XavierBouvard certainly, I am not sure about the purpose of declaring `/tmp` as a volume. @hacdias is it used internally?

**Comment by PixiBixi** [comment]
Hi,

I've no idea what i should edit to my docker-compose.yml to re-use filebrowser, can someone help me?

```
  guillaume_filebrowser:
    image: filebrowser/filebrowser
    container_name: guillaume_filebrowser
    volumes:
      - /home/guillaume/incoming:/srv
      - /root/.apps/guillaume/filebrowser/database.db:/database.db
      - /root/.apps/guillaume/filebrowser/tmp:/tmp
    environment:
      - LETSENCRYPT_HOST=fm.guillaume.x
      - LETSENCRYPT_EMAIL=contact@x
      - VIRTUAL_HOST=fm.guillaume.x
      - VIRTUAL_PORT=80
```

**Comment by eine** [comment]
@PixiBixi, see https://github.com/filebrowser/filebrowser/issues/587#issuecomment-451907670

**Comment by hacdias** [comment]
@1138-4EB could you try out the Dockerfile on master and make any changes if needed?

**Comment by eine** [comment]
@hacdias, as commented above, what is the purpose of declaring `/tmp` as a volume?

**Comment by hacdias** [comment]
I don't know. [It was added by you](https://github.com/filebrowser/filebrowser/blame/master/Dockerfile) 😛

**Comment by hacdias** [comment]
I just left it there because... well... I didn't want to break anything.

**Comment by hacdias** [comment]
But I think we should remove it. It doesn't make sense to me.

**Comment by eine** [comment]
I have pulled the latest image and it looks good with the default user and password. It is so smooth, and the editor looks great.

However, I found the following problem when trying to just start it with `noauth`:

- `filebrowser` creates the database in `/database.db`, as set in `.filebrowser.json`. It is created with `quickSetup`, so the auth is set to `JSONAuth`.
- I cannot `docker exec` into the container, because there is no shell in it.
- I cannot change the setting from the GUI. Although this might be a possible solution.

So, I am kind of forced to make the database persistent, either by binding it to the host, or using a docker volume. That is because I need to call filebrowser multiple times (two, at least).

**Comment by hacdias** [comment]
> filebrowser creates the database in /database.db, as set in .filebrowser.json. It is created with quickSetup, so the auth is set to JSONAuth.

There's no way of starting it automatically with no-auth. Please use `config init` for that or change using `config set`.

> I cannot docker exec into the container, because there is no shell in it.

I didn't change the existence or non-existence of shells on the Dockerfile. But please change that so there is 😄 

> I cannot change the setting from the GUI. Although this might be a possible solution.

Only non-server and non-auth related settings are available from the UI.

**Comment by hacdias** [comment]
`quickSetup` is actually what the name says: a quick setup.

**Comment by eine** [comment]
> I don't know. [It was added by you](https://github.com/filebrowser/filebrowser/blame/master/Dockerfile) 😛

Not really 😋 . I was the last one modifying those lines, but the content was there far before:

- https://github.com/filebrowser/filebrowser/commit/00da35b91d759378015105a020e09a1591f5a92c#diff-3254677a7917c6c01f55212f86c57fbf
- https://github.com/filebrowser/filebrowser/commit/6f394641304b9c51cc2928539eddc29d2382ce82#diff-3254677a7917c6c01f55212f86c57fbf

> I just left it there because... well... I didn't want to break anything.
>
> But I think we should remove it. It doesn't make sense to me.

It seems to be because of #274. Are you sure that filebrowser does not need it anymore? If so, we can safely remove it.

---

> There's no way of starting it automatically with no-auth. Please use config init for that or change using config set.

I think this is a very valuable feature. Certainly, most of the time I use filebrowser I start it in noauth mode.

> I didn't change the existence or non-existence of shells on the Dockerfile. But please change that so there is 😄

I don't think we need to do so. As I have commented in previous issues, I think that it would be interesting to distribute two images (`filebrowser/filebrowser` and `filebrowser/filebrowser:alpine`. But I would keep the one based on SCRATCH as the reference. I think it is very valuable to ensure what filberowser can do on it's own, as a static binary.

> Only non-server and non-auth related settings are available from the UI.

That's ok. I was just considering alternative solutions.

---

Can we consider auth related parameters to be server params and treat them equally?

**Comment by hacdias** [comment]
> It seems to be because of #274. Are sure that filebrowser does not need it anymore? If so, we can safely remove it.

😱 it was me! I believe it doesn't. It was related to the previous version of archiver. I don't think we need it anymore. Can you try removing it and then download a file?

> I think this is a very valuable feature. Certainly, most of the time I use filebrowser I start it in noauth mode.

We could add a flag for noauth that would only be used if in quick setup mode just as username and password. Not sure if we should add all auth params though. They all require a lot of configuration for their own so I think it's better to keep it in config commands.

We could add `noauth` just as a shortcut and let it be an exception. But just for quick setup mode. What do you think?-

**Comment by eine** [comment]
> Can you try removing it and then download a file?

See #620.

> We could add a flag for noauth that would only be used if in quick setup mode just as username and password. Not sure if we should add all auth params though. They all require a lot of configuration for their own so I think it's better to keep it in config commands.
> 
> We could add noauth just as a shortcut and let it be an exception. But just for quick setup mode. What do you think?-

I might be missing some knowledge about the internals here. What configuration is required for auth settings? I was thinking about adding `auth.method` and `auth.header` to root:

- For `noauth`, the later is not required.
- With proxy, is anything more required?
- With JSONAuth (default), "username" and "password" are used, "admin" being the default.

We can limit the available auth options in quick setup to those that are straighforward.

**Comment by hacdias** [comment]
And then, you had to add all recaptcha settings which are tied to JSON auth. Not obligatory but they are JSON auth options. And (like a snowball), someone creates a new Auther and then we get new options :P

We're already omitting the possibility to add Recaptcha through quick setup. If we add sth, IMO, it should only be `--noauth` or something similar.

**Comment by eine** [comment]
I thought that recaptcha settings were independent from JSON. Therefore, I agree with you. We can only allow auth methods that need no additional parameters. For now, it is only `noauth`.

**Comment by hacdias** [comment]
I will add that flag then!

**Comment by hacdias** [comment]
Will close this as the new Dockerfile is merged
