### ISSUE TITLE
Starting new dockerfile

### ISSUE THREAD

**Issue by docgonzo2015** [filebrowser/filebrowser#602]
Hi!

After update of the new dockerfile i get 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown.

**Comment by hacdias** [comment]
@docgonzo2015 we recommend you to use the tag of the latest stable version available, which is 1.11.0. Latest tag is the same as master here which may contain breaking changes. We're working on a new major version, so until we release it, just use v1.11.0. 

You can always use latest and help us find bugs 😁

See #600
