### ISSUE TITLE
Code Climate

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#619]
We already have a set of linters and code quality checkers enabled in our CI pipeline; and there are plenty more that we can add (see #595).

However, there are some other factors related to code complexity and maintainability that we are not actively checking. [Codeclimate](https://codeclimate.com) is a service that allows to do so. It analyses the code to find complexity, duplication and style issues. If find it interesting because it tracks the evolution of code quality. It also allows to mark issues as invalid/wontfix, so that it is easier to manage new ones. Furthermore, the integration with GitHub allows to report issues in PRs before merging them.

I tried to enable it for filebrowser/filebrowser and filebrowser/frontend, but I couldn't. So I set it for my forks:

- https://codeclimate.com/github/1138-4EB/filebrowser
- https://codeclimate.com/github/1138-4EB/filebrowser-frontend

As you see, the quality of v2 is quite good. Certainly, it has improved signifficantly compared to v1:

- https://codeclimate.com/github/1138-4EB/filebrowser/trends/technical_debt
- https://codeclimate.com/github/1138-4EB/filebrowser-frontend/trends/technical_debt

Indeed, I used codeclimate to spot the code duplication fixed in #618.

---

Of course, I would be ok with using any other similar service. The advantages I see with codelimate are:

- It is free for open source projects.
- It provides docker images to run the engines locally or in your own CI service. See https://hub.docker.com/r/codeclimate/codeclimate/.

---

However, I would not replace golangci-lint with codeclimate. I think it is good to keep the Travis setup as it is right now, and add codeclimate as a second point of view.

**Comment by hacdias** [comment]
Sure! We can add it! Let me take a look!

**Comment by hacdias** [comment]
Just added it! On the next PR we'll check if it's working.

**Comment by eine** [comment]
Cool! However, I think I cannot edit the content. I mean, mark issues as wontfix/invalid.

**Comment by hacdias** [comment]
Please go to you OAuth Settings here on GitHub and make sure that Code Climate has access to File Browser. If not, request access please

**Comment by eine** [comment]
I can see Code Climate in Settings > Applications > Authorized OAuth Apps. But, there is nothing to configure there.

I cannot access File Browser Organization Settings in GitHub, because I am not an owner. But I can see other organizations there (which I own). Coherently, I can add repos from those organizations to Code Climate.

Therefore, I think that it might be limited to organization owners. Unless there is some option in Code Climate to explicitly add some user.

**Comment by hacdias** [comment]
It's not limited to owners. According to their docs, I should be able to add you. I'm trying to figure out how

**Comment by hacdias** [comment]
@1138-4EB could you try now?

**Comment by eine** [comment]
For some reason my account was blocked. I'm trying to fix it.

**Comment by hacdias** [comment]
Blocked? How so?

**Comment by eine** [comment]
At some point I tried to revoke access from GitHub and enable it again. But it didn't logout properly, so it created a user tied to my email account, with an unknown password. Now, if I try to login with GitHub it says that the email is already used.

**Comment by eine** [comment]
It works now! I reset the account, linked it to GitHub, I can acces settings now.
