### ISSUE TITLE
Can't use external authentication method

### ISSUE THREAD

**Issue by dbeniamine** [filebrowser/filebrowser#634]
**Description**

I am trying to switch from V1.11.0 to 2.0.0 and I get "Something really went wrong." when accessing my files

**Expected behaviour**

Access to my files

**What is happening instead?**

![image](https://user-images.githubusercontent.com/2989133/51195426-542c0e80-18ed-11e9-90dd-91a0cdec5418.png)

**Additional context**
I use filebrowser in docker-compose behind an nginx proxy.

on V1.11.0 I gave the command: `--auth.method=None --baseurl=/files`

On 2.0.0 I switched to `filebrowser.json` config file, my config file is:

```json
{
  "port": 80,
  "address": "",
  "noAuth": true,
  "baseURL": "/files",
  "log": "stdout",
  "plugin": "",
  "scope":"/srv/",
  "allowCommands": false,
  "allowEdit": true,
  "allowNew": true,
  "commands": [ ]
}
```
My docker-compose config:

```docker-compose
files:
        hostname: files
        image: filebrowser/filebrowser:v2.0.0
        restart: unless-stopped
        command: --config /.filebrowser.json
        volumes:
            - home:/srv/
            - ./filebrowser.json:/.filebrowser.json
        networks:
            - default
```

My nginx proxy:

```nginx
location /files/{
    proxy_pass http://files/files;
}
```

**Comment by hacdias** [comment]
Hello @dbeniamine!

First of all, did you follow the instructions to [upgrade your DB](https://docs.filebrowser.xyz/upgrade-from-1.x)? It may be useful if you have more than one user and want to migrate everything.

Most of the options on that config file are deprecated and were from the previous version. Please replace it by:

```json
{
  "port": 80,
  "baseURL": "/files",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```

You also need to mount the [database path](https://docs.filebrowser.xyz/installation#docker) as in the previous version.

let me know if this helped 😄

**Comment by efrecon** [comment]
I **think** that this is due to the `noAuth` key in the configuration (if that still is supported?). I have had similar issues when running with `--noauth` (which is supported as of the command-line help, I believe) and trying to protect through basic authentication in the reverse proxy instead. The log of my reverse proxy reports an error when accessing `/api/resources` as it does not carry the same username (probably meaning one of headers has been mangled). I am running behind caddy though, so this might be a different issue.

**Comment by dbeniamine** [comment]
Hello @hacdias,

I never mounted the db as I do not use filebrowser users, so I am running a brand new db.

With the provided configuration file I still have the same issue and `noauth` is not activated.

Mounting the db does not change anything ...

**Comment by dbeniamine** [comment]
I can see these lines on my reverse proxy:

```nginx
172.26.0.1 - <user> [16/Jan/2019:10:31:59 +0000] "GET /files/files/ HTTP/1.1" 200 1142 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:31:59 +0000] "GET /files/static/css/chunk-vendors.43006785.css HTTP/1.1" 200 7710 "http://localhost:6080/files/files/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:31:59 +0000] "GET /files/static/css/app.02f31e4b.css HTTP/1.1" 200 29917 "http://localhost:6080/files/files/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:31:59 +0000] "GET /files/static/js/chunk-vendors.dc744398.js HTTP/1.1" 200 948821 "http://localhost:6080/files/files/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:31:59 +0000] "GET /files/static/js/app.10bf4a2d.js HTTP/1.1" 200 251936 "http://localhost:6080/files/files/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - - [16/Jan/2019:10:32:00 +0000] "POST /files/api/renew HTTP/1.1" 401 204 "http://localhost:6080/files/files/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:32:00 +0000] "GET /files/static/img/logo.svg HTTP/1.1" 200 5507 "http://localhost:6080/files/login?redirect=%2Ffiles%2F" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:32:00 +0000] "GET /files/static/img/icons/apple-touch-icon-152x152.png HTTP/1.1" 404 19 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
172.26.0.1 - <user> [16/Jan/2019:10:32:00 +0000] "GET /files/static/img/icons/favicon-16x16.png HTTP/1.1" 200 843 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
```

As you can see the POST goes 401 and there is a 404 on `apple-touch-icon`

**Comment by dbeniamine** [comment]
@efrecon  when I only provide the command line `--noauth --baseurl=/files/` I indeed have the same error as you : 401 on `/api/ressources`

So I  added a port mapping to my docker-compose to access directly filebrowser and it works like a charm when I go directly on filebrowser port. But I still need to access it via my proxy, how can I make the proxy work ?

**Comment by hacdias** [comment]
@efrecon the `--noauth` flag is supported for quick setup mode only. If you have an existing database, that flag will be ignored.

@dbeniamine is there any possibility your proxy is removing the headers from the response request? Could you please open the Dev Tools (F12 usually), go over to Network tab and refresh the tab, then take a screenshot at the details of the 401 request please

**Comment by efrecon** [comment]
@hacdias Thanks. I was having this on a new non-existing database (technically in a newly created docker volume).

**Comment by dbeniamine** [comment]
@hacdias there is a screenshot with visible headers:

![image](https://user-images.githubusercontent.com/2989133/51323261-f5d76b00-1a67-11e9-8def-da47a41d0067.png)

**Comment by karlicoss** [comment]
Same as on @dbeniamine 's screenshot happens for me, even with `noauth`, the Authorisation header gets overridden by filebrowser... surely it should be left intact?

**Comment by karlicoss** [comment]
Yep, looks like it's added here unconditionally https://github.com/filebrowser/frontend/blob/b394540f535b5e9720d7948017bdefe05ef1c7dd/src/api/utils.js#L13

**Comment by hacdias** [comment]
@karlicoss and they should be always added. `noauth` is just a shortcut for automatic login with the user with ID 1.

Are you using any different authorization that is not part of File Browser?

**Comment by karlicoss** [comment]
@hacdias thanks for a quick response!
Yep, I'm relying on basic http auth set in my nginx config. 
Thing is, if I turn it off temporarily (and still use `noauth` in filebrowser), it just lets me through to see my file. So I guess I don't really understand what's this token for...

**Comment by hacdias** [comment]
@karlicoss the token contains some info about the current user. Even though you don't need to log in, there's still a user that is logged in. That token keeps the information and makes sure the info is still valid.

**Comment by hacdias** [comment]
Let's also not deviate from this issue. @dbeniamine @efrecon are you also using another auth method? Like basic auth?

**Comment by liranbg** [comment]
I use nginx http as a reverse proxy to all webapps I have on my server. nginx is configured with basic auth and it seems I have the same issue that I cannot login.
I saw in the configuration page, I can reverse proxy with different auth headers. but that doesn't work properly as well.

I was wondering, if it is feasible to be implemented, so that instead of using 'Authorization' header I can provide a flag that overrides the name of the header so that filebrowser app can work properly behind nginx (reversed proxy) with basic auth enabled.

What do you think?

**Comment by hacdias** [comment]
@liranbg the issue of not using the default authentication header is that proxies and browsers might not know how to treat it. By using Authentication, we can ensure that external proxies know how to deal with this more sensitive header.

Implementing what you said or just use a custom header is an option.

Another option is to implement basic auth.

**Comment by dbeniamine** [comment]
@hacdias : I am using a nginx proxy with basic auth (pam_auth), I can add an auth header but I do not know which one to use and what value to pass, can you give me a configuration example ?

**Comment by efrecon** [comment]
Yes. Basic auth behind caddy was what I was trying

**Comment by hacdias** [comment]
@dbeniamine basic auth won't work until this is fixed.

---

So, right now we have two options:

1. Implement Basic Auth.
2. Just change the Header name to something else and add a note to the documentation to keep that header when proxying (some proxies might try to remove the header)

I'm implementing the second since is the fastest and easiest and might not cause warm.

/cc @1138-4EB

**Comment by eine** [comment]
I'm quite lost. I always use File Browser locally, i.e., with `no-auth` and without any proxy. If I did understand correctly, this issue is about handling authentication with a *frontend* (be it *caddy* or *nginx*). Then, maybe @maweck can help us here (see #485).

**Comment by hacdias** [comment]
@1138-4EB the issue was that basic auth was rewriting our HTTP header so File Browser didn't work.

**Comment by dbeniamine** [comment]
I just tested it with 2.0.2 and I confirm that it is fixed, thanks for your help :)
