### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by Ajef** [filebrowser/filebrowser#635]
**Description**
I receive an error message 

> Something really went wrong.

on the entry page after login.

When trying to create a new folder I receive the following error Message:
Authorization Required

```
This server could not verify that you are authorized to access the document requested. 
Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
Apache/2.2.15 (CentOS) Server at [...] Port 80

```

Strangely the download Button in the top right corner works and downloads the directory as a zip-file.
Is a setup such as I describe it in additional context not possible or am I missing something with the permissions?

**Additional context**

I'm trying to run filebrowser in a shared hosting environment.
The executable is located in /home/[user]/bin and run with normal user priviliges.
The port 62734 which is running filebrowser is routed through apache to port 80 via a htaccess-rewrite Rule. The filebrowser port is not accessible through the firewall externally.

**Comment by hacdias** [comment]
@Ajef it looks like the same issue as #634, right? Both of you are using another web server and a proxy. I wonder if that's the cause. What's the base url?

**Comment by Ajef** [comment]
@hacdias: base url was empty.
I removed the .htaccess- authorization requirement and now it works. I suspect the authorization is handed down to filebrowser somehow... strange that the download button in the top right still worked.

Anyway this issue can be closed.

**Comment by hacdias** [comment]
@Ajef yes, authentication is handled by File Browser itself. The download button goes for a direct link so your browser could use basic auth (or whatever you had set up with Apache). The other APIs are called via `fetch` and we're injecting the authorization header. That may override whatever authentication you set up with Apache, breaking it.
