### ISSUE TITLE
'token expired' on different time zones

### ISSUE THREAD

**Issue by wcone** [filebrowser/filebrowser#638]
Hi i'm quite new to this and docker.

i setup a v2.0.0 with docker on machine A in the local network and everything works like a charm.
i tried to access the filebrowser from machine B in the same local network but somehow i'm getting "invalid credential" error message. I've checked the token return on jwt, seems valid and with proper expiry date.

i proceed with a "noAuth" config and this time round on machine B i'm getting "Uncaught (in promise) Error: token expired" from the console.
<img width="1308" alt="screenshot 2019-01-22 at 2 49 42 pm" src="https://user-images.githubusercontent.com/46917021/51517186-f8193b00-1e54-11e9-9d3d-eb2bacfc3f52.png">

this is how i ran the docker:
`docker run -d
--privileged
--name=filebrowser
-v <root path>:/srv
-v <path to json>:/.filebrowser.json
-p 80:80
filebrowser/filebrowser:v2.0.0`

and this is the json config:
`{
  "port": 80,
  "noAuth": true,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}`

I've tried v1.11.0 and is working as expected.
i'm not sure if i missed out anything for v2.0.0 but any help is appreciated.
Thank you!

**Comment by hacdias** [comment]
@wcone could you try cleaning up the cache and cookies please?

**Comment by wcone** [comment]
@hacdias i figured out why... my machine A was running on a different time zone. After correcting the time it works seamlessly thank you.

**Comment by hacdias** [comment]
@wcone oh, it shouldn't happen though. I'll reopen this.

**Comment by laleveille** [comment]
Same problem, but my machines are running on same time zone.
Cache and cookies cleared, everything is fine.

**Comment by ttys3** [comment]
@hacdias  I also noticed this problem. (and I've wrote an article http://nanodm.net/post/why-filebrowser-raise-wrong-credentials-error-even-with-right-credentials/ )

it is a frontend code problem.
I think  the js code should not determine the expiration status:

frontend/src/utils/auth.js
```javascript
  if (Math.round(new Date().getTime() / 1000) > data.exp) {
    throw new Error('token expired')
  }
```

**Comment by hacdias** [comment]
@ttys3, what would you recommend? Just remove that code and let the backend determine it? If so, could you open a PR for that ? 😃

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
