### ISSUE TITLE
DB insertion starts from ID 1 after migration

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#639]
**Description**
After I migrated to v2, I tried creating a new user. This created a new user with id 1, which overwrote my admin user. 😢 

**Expected behaviour**
ID continues from where it was up to.

**What is happening instead?**
ID starts from 1

**Additional context**
I used to use \*cough\* filemanager \*cough\* within Caddy. After migration I now use filebrowser as a standalone docker container and proxy requests to it via caddy.

**How to reproduce?**
Should be clear with the above

**Files**
N/A

**Comment by princemaple** [comment]
UPDATE:

I thought if I exported the users, created a new db and imported the users, the ID would be correct.
NO - still wrong. It still starts from 1, still overwrites my existing users.
Funny thing is, if I import the users again, they are rejected because of existing id.

**Comment by princemaple** [comment]
Worked it around by modifying all the ids in the exported json to some large number.
The downside is that the users newly created now are displayed at the top instead of at the bottom of the user list.

**Comment by princemaple** [comment]
@hacdias @1138-4EB ^ Please take a look

**Comment by princemaple** [comment]
"Fixed" it by changing all the ids to 0 in the json file. Recreated db and imported again. Now the new users are created with the correct ids.

**Comment by hacdias** [comment]
@princemaple hey! This seems more like an issue on Bolt DB than with File Browser itself. It seems that the internal next-value-id from Storm isn't updated when saving with a ID that didn't exist but was set. It seems to only update when leaving the ID empty, hence creating this issue. I'll dig a bit more into this.

**Comment by princemaple** [comment]
Yes I realized that this is more Bolt than FB, but this could be quite significant for FB users.

I think one easy "fix" is, when migrating, sort users by ID but don't copy the IDs over. This would keep the order of display and not run into the bug. Also when exporting users, sort and leave out the ID, too.

**Comment by hacdias** [comment]
@princemaple could you take a look at #645?

**Comment by princemaple** [comment]
Verified with latest docker image, exporting and importing now has the correct auto increment id.
