### ISSUE TITLE
Add a mipsle build to releases

### ISSUE THREAD

**Issue by leoleoasd** [filebrowser/filebrowser#640]
I need to run it on my router. i've compiled it manually using the commands in https://github.com/filebrowser/filebrowser/issues/287, but it shows this:

```
2019/01/22 10:03:00 No config file used
panic: could not locate box "../frontend/dist"
```

@1138-4EB  said in https://github.com/filebrowser/filebrowser/issues/520 
 > In #399, rice-box.go was removed from filebrowser. The frontend is now built in the CI environment, and it is used directly. When a tagged commit is pushed (a release), the rice-box.go is automatically pushed to caddy/assets (note that the first line is rewritten from package filebrowser to package assets). See (long) discussion about this starting from #399-issuecomment-401897721.

so i cant compile it manually.

**Comment by eine** [comment]
You need to build the frontend first, then generate the `rice-box.go` and last compile the backend. See https://docs.filebrowser.xyz/contributing#build

**Comment by leoleoasd** [comment]
I solved it by manually change GOOS and GOARCH in wizzard.sh and run it.

**Comment by carlsue** [comment]
> I solved it by manually change GOOS and GOARCH in wizzard.sh and run it.

user@user-VirtualBox:/tmp/filebrowser/http$ rice embed-go
user@user-VirtualBox:/tmp/filebrowser/http$ GOOS=linux GOARCH=mipsle go build -v
github.com/filebrowser/filebrowser/v2/http
go build github.com/filebrowser/filebrowser/v2/http: /usr/lib/go-1.12/pkg/tool/linux_amd64/compile: signal: killed

what's wrong with this

**Comment by carlsue** [comment]
user@user-VirtualBox:/tmp/filebrowser$ **sudo** GOOS=linux GOARCH=mipsle go build 
add sudo will be ok

**Comment by carlsue** [comment]
here you are,mipsle version v2.11.0
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972835/filebrowser.zip)
