### ISSUE TITLE
cant build from dockerfile

### ISSUE THREAD

**Issue by Auto-ZGQ** [filebrowser/filebrowser#643]
**Description**
I use the Dockerfile to build my own images.

**Expected behaviour**
exchange the base images from scratch to busybox

**What is happening instead?**
Step 6/8 : COPY filebrowser /filebrowser
COPY failed: stat /var/lib/docker/tmp/docker-builder120239541/filebrowser: no such file or directory

thank you

**Comment by zgqing** [comment]
thank you

**Comment by Auto-ZGQ** [comment]
i don't download the filebrowser binary file
