### ISSUE TITLE
The links of search results cannot be opened.

### ISSUE THREAD

**Issue by blingblingyoyo** [filebrowser/filebrowser#647]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

_The links of search results cannot be opened._

**Expected behaviour**
What did you expect to happen?

_The specific file or directory should be opened when I click on the link of search result._

**What is happening instead?**
Please, give full error messages and/or log.

_The screen refreshes and shows the root directory._

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

_I am running Filebrowser  on Win10 x64 with Edge and Chrome  being the browsers._

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

_Search something, and click on the result links._

**Comment by hacdias** [comment]
@blingblingyoyo can't reproduce on the latest version on Windows 10 Chrome. Are you using 2.0.1?

**Comment by blingblingyoyo** [comment]
@hacdias 
Yes, it happens to v2.01, I have tested it with Edge, Firefox or Chrome, they all show the same problem. 
After clicking on search result link, the file or directory is not opened, it refreshes and shows the root directory. To get the file or directory opened I have to click on "refresh icon" or "F5 Key"after that. 
I have also tested v1.11 (x64 or self-compiled mipsle ), it works well without such problem.

**Comment by eine** [comment]
@blingblingyoyo, you can use some tool (such as [screentogif](https://www.screentogif.com/)) to record a screencast, in case that helps you describe the issue.

**Comment by blingblingyoyo** [comment]
@1138-4EB 
![123](https://user-images.githubusercontent.com/47079219/51927106-c17f8980-242d-11e9-9049-057ba6614a26.gif)

**Comment by hacdias** [comment]
Could you also show the Dev Tools console please (F12)?

**Comment by blingblingyoyo** [comment]
@hacdias 
![789](https://user-images.githubusercontent.com/47079219/51928490-0822b300-2431-11e9-9730-9f72b9a15799.gif)
![456](https://user-images.githubusercontent.com/47079219/51928491-08bb4980-2431-11e9-90a5-12df4493417d.gif)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
