### ISSUE TITLE
can not login behind nginx

### ISSUE THREAD

**Issue by laoshaw** [filebrowser/filebrowser#648]
I could not get 2.x working behind nginx, the homepage came up but I can never login. I can run it locally and login just fine though, also I run 1.x behind nginx all the time.

In general 1.x is much easier to get set up,  it has default admin/admin to login and you then change settings via web interface, in 2.x I have to read quite a bit to get familiar with the command line before I can do anything. These days it's better to have a quick install, everything work out of the box, and you then configure everything via web(e.g. gittea, most php web applications,etc). Command line should only be left for power users and as a last resort.

**Comment by hacdias** [comment]
@laoshaw,

> In general 1.x is much easier to get set up

`filebrowser` does a quick setup.

> it has default admin/admin to login and you then change settings via web interface

Didn't change.

> in 2.x I have to read quite a bit to get familiar with the command line before I can do anything.

The quick config docs didn't change much: https://docs.filebrowser.xyz/installation#quick-setup

> These days it's better to have a quick install, everything work out of the box, and you then configure everything via web(e.g. gittea, most php web applications,etc). Command line should only be left for power users and as a last resort.

Yes! https://docs.filebrowser.xyz/installation#quick-setup

---

Are you using any other type of auth like basic auth?

**Comment by hacdias** [comment]
Closing due to lack of response.
