### ISSUE TITLE
500 Internal Error on Settings Tab

### ISSUE THREAD

**Issue by justrjlewis** [filebrowser/filebrowser#65]
moved from: https://github.com/hacdias/caddy-hugo/issues/58#issuecomment-193529583

@hacdias As it happens, I don't have a config file in place so I'll fix that and see if that helps.  I did run caddy with `-log stderr`.

Here's what's in the safari console: http://cl.ly/473T0d3Z0r0J

pasted: 

```
Object
abort: function(a)
always: function()
complete: function()
done: function()
error: function()
fail: function()
getAllResponseHeaders: function()
getResponseHeader: function(a)
overrideMimeType: function(a)
pipe: function()
progress: function()
promise: function(a)
readyState: 4
responseText: "400 Bad Request↵"
setRequestHeader: function(a,b)
state: function()
status: 400
statusCode: function(a)
statusText: "Bad Request"
success: function()
then: function()
Object Prototype
```

I'm not getting the error in Chrome - just Safari

**Comment by hacdias** [comment]
Hello @justrjlewis 
- Are you using caddy-hugo with an existent website or creating a new one?
- If you already have an existent website, please show me your Caddyfile.
- Paste here the result of `ls` command on the root of your Hugo website.

The error you're getting is very strange. What's the URL of the page you are trying to access?

**Comment by hacdias** [comment]
Anything new?

**Comment by hacdias** [comment]
This issue will be closed due to its inactivity. If the error persists, just comment.
