### ISSUE TITLE
The new setup procedure and `--noauth`

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#651]
I came to this context while trying to start filebrowser in a docker container with `noauth` and a predefined list of enabled commands. If filebrowser is started with:

``` bash
# ./filebrowser -a 0.0.0.0 --noauth
2019/01/31 01:50:57 No config file used
2019/01/31 01:50:57 Listening on [::]:8080
```

The quick setup procedure is executed and the defaults are applied. I.e., `&settings.Settings{...}` is created, where `Scope`, `Locale` and `Perm` are initialized, but `Commands` is left empty (uninitialized). Moreover, no CLI flag is provided, and it is not read from the config file.

As a result, the user needs to browse the Settings. However, adding commands in `Global Settings` does not have any effect, because `noauth` defaults to user `admin`, which was created with an empty list of commands. It must be changed in `User Management`, by editing the options for user `admin`.

Since I need to do it without user intervention, I checked the subcommands:

- `filebrowser config set --commands 'git,ghdl,pyhton'`. The change is properly applied, but it changes the `Global Settings`, not the ones of `admin`.
- `./filebrowser users update admin --commands 'ghdl,python,gtkwave,echo'`. This works. However, note that despite the usage prototype being `filebrowser users add <username> <password> [flags]`, I did not write any password.

So, the procedure requires to:

- Start filebrowser once with quick setup: ./filebrowser --noauth -a 0.0.0.0.
- Wait until filebrowser is started and listening, and close/kill it.
- Run `users update ...`. 
- Start filebrowser again. This time, no arguments are required.

---

Since waiting for the server to start in order to kill is not a clean procedure, I tried to find a work around with `config init`.

> NOTE: I need to copy the parameters from the configuration file to flags manually. Although flag `-c` is shown as inherited in https://docs.filebrowser.xyz/cli/filebrowser-config-init, the content of the configuration file is ignored. However, when filebrowser is started without arguments after `config init`, the configuration file applies. This might be hard to understand. See #653.

``` bash
 ./filebrowser config init --noauth -a 0.0.0.0 --commands 'ghdl,python,gtkwave,echo,bash,sh'
```

However, `--noauth` is not accepted. I can execute the same command without it. Then, even if I start `filebrowser --noauth` credentials are required. Moreover, no valid credentials exist, because the user list is empty. So, I need to add a user:

``` bash
./filebrowser users add admin --commands "sh,ghdl" --perm.admin
```

The command above fails, because `password` must be set. So I need to add a password. I can then start filebrowser and use it, but I am forced to use a user and password. I cannot remove the password. And I cannot use `noauth`.

> NOTE: This password is not a hash, so it is not consistent with the flag `--password` of the quick setup.

---

I think we should:

- Add some reference in the docs about `--noauth` and the configuration options that are supported by quicksetup. I did not find any reference to any of them.
  - Probably add a note explaining that `--noauth` might be limited, as it is not guaranteed that all the config options can be configured through CLI. It is mostly meant for a quick feel of the project.

Furthermore, we can optionally/alternatively:

- Add the quick setup as a subcommand, and allow some more params (those of `config`), which would be used for both the global settings and the user admin.
  - For users executing `filebrowser`, the behaviour and flags would be the same as now.
  - For users executing `filebrowser quick`, the behaviour would be similar to `config init` + `config users add --perm.admin`.

**Comment by hacdias** [comment]
I don't think it makes sense to create another command. There's `config init` for those who want to play more with the configuration. We removed basically nothing from the previous version.

The docs are here: https://docs.filebrowser.xyz/cli/filebrowser

**Comment by eine** [comment]
Now there is no mechanism to use `config init` to set a `noauth` instance with other custom options. At the same time, quick setup cannot be executed without starting the server inmediately (with some non-customized options).

In the previous version, you could run a quick setup (the default and single option), which would read a config file, and where you could provide all the parameters for noauth mode. The server would start with the parameters set by the user.

**Comment by hacdias** [comment]
@1138-4EB there are no custom parameters for no auth mode. It's the only Auth Method that has no other option. Please give me an example. The quick setup isn't supposed to do everything for you, and that's why there's an interface to change the settings and more commands.

**Comment by eine** [comment]
This is the config file that I was using with v1: https://github.com/1138-4EB/hwd-ide/blob/c0fcf1ef260f78546dcf2cd4b2d65ef21943d2a7/filebrowser/filebrowser.config.yml

This is the one for v2: https://github.com/1138-4EB/hwd-ide/blob/develop/filebrowser/filebrowser.config.yml. Note the list of allowed commands: [filebrowser.config.yml#L22-L29](https://github.com/1138-4EB/hwd-ide/blob/develop/filebrowser/filebrowser.config.yml#L22-L29)

With *custom parameters* I mean e.g. the list of commands, which is supported in `config`, but not in quick setup. Conversely, in `config` commands can be provided, but `--noauth` does not work.

**EDIT**

Well, I found it now. With `config` the flag is not `--noauth`. The correct syntax is `--auth.method=noauth`: https://docs.filebrowser.xyz/configuration/authentication-method#no-authentication

**Comment by Inlustra** [comment]
@1138-4EB Has this changed recently? I added watchtower last night causing docker to update quite a few of my images and now neither `--noauth` or `--auth.method=noauth` is working anymore...

``` 
Use "filebrowser [command] --help" for more information about a command.
2019/03/18 14:33:21 unknown flag: --auth.method
```

This is my docker-compose

```
  download:
    container_name: download
    image: filebrowser/filebrowser
    command: "--auth.method=noauth --defaults.allowEdit=false --defaults.allowNew=false --defaults.allowCommands=false"
    volumes:
      - ${CONFIG_DIR}/download/config.json:/etc/config.json
      - ${CONFIG_DIR}/download/database.db:/etc/database.db
    restart: unless-stopped
```

**Comment by eine** [comment]
Hi @Inlustra! Argument/option `--auth.method=noauth` corresponds to `filebrowser config`. It is not possible to do it in a single step anymore. Your `command` needs to be composed of multiple subcommands:

- Initialize a DB with `filebrowser` (quick setup) or `filebrowser config init`.
- Configure all the desired options in the DB with `filebrowser config set`.
- Start Filebrowser.

**Comment by Inlustra** [comment]
Thanks for getting back to me! 
I think for now I'll revert as I don't have too much time to setup new docker files to manage that!

Thanks again for all the work put in!
