### ISSUE TITLE
关于 2.x 版本配置文件的疑问

### ISSUE THREAD

**Issue by osdu** [filebrowser/filebrowser#652]
1.x 可以设置很多默认参数，2.x 好像只有少数几个参数可以写到配置文件，剩余大部分不生效。
使用姿势不对？

`filebrowser config export` 导出的配置文件也不能通过  `--config`  启动，那配置文件导出的意义是啥？

---
1.x 版本配置文件
```
{
	"allowCommands": true,
	"allowEdit": true,
	"allowNew": true,
	"noAuth": false,
	"commands": ["git"],
	"scope": "/readonly"
}
```

2.x 版本配置文件
```
{
	"root": ".",
	"baseurl": "",

	"log": "stdout",

	"cert": "",
	"key": "",

	"address": "0.0.0.0",
	"port": "7021",

	"locale": "zh-cn",

	"perm.admin": false,
	"perm.create": false,
	"perm.delete": false,
	"perm.download": true,
	"perm.execute": false,
	"perm.modify": false,
	"perm.rename": false,
	"perm.share": false,

	"viewMode": true,

	"signup": true,
	"sorting.asc": true,
	"sorting.by": "name",

	"username": "admin",
	"password": "$2a$10$URKX8Zeyro9fOoTwlAlB7ug2S0AU5aIUj3oLsbpxgCfOhOcfEU4Mu"
}
```

**Comment by luchuanbaker** [comment]
确实比较不清晰，我的理解是配置文件是可以快速填写配置信息，然后import到database中。也便于保存配置快速搭建第二套环境。
服务器运行好像就是使用的自己的database中的配置。
./filebrower -c config.json这些写的意义不知道是什么，因为本身它可以从自己的db中读取已经导入的配置。

**Comment by hacdias** [comment]
I will reply in English.

The configuration file `.filebrowser.json` should only be used in automatic deployments. We recommend you to use only the database file. The configuration file is more like the flags: used to override some database setting (see https://docs.filebrowser.xyz/cli/filebrowser).

`filebrowser config init` should do the trick. 

Then you can `filebrowser config set ...` anything else you want.

**Comment by omaidb** [comment]
我想修改为0.0.0.0访问，怎么搞啊，谁能写个教程

**Comment by luchuanbaker** [comment]
> 我想修改为0.0.0.0访问，怎么搞啊，谁能写个教程

导出配置
./filebrowser config export config.json

修改config.json：server属性的address改为“0.0.0.0”

导入配置
./filebrowser config import config.json 

启动
./filebrowser -c config.json

**Comment by omaidb** [comment]
2019/05/16 10:39:51 No config file used
2019/05/16 10:39:51 listen tcp 0.0.0.0:80: bind: permission denied
我把监听端口配置为80，以user启动提示权限被拒绝。但是以sudo 启动80端口正常。
我想知道这是Ubuntu的问题还是filebrowser的问题

**Comment by omaidb** [comment]
> > 我想修改为0.0.0.0访问，怎么搞啊，谁能写个教程
> 
> 导出配置
> ./filebrowser config export config.json
> 
> 修改config.json：server属性的address改为“0.0.0.0”
> 
> 导入配置
> ./filebrowser config import config.json
> 
> 启动
> ./filebrowser -c config.json

 ./filebrowser -c config.json 没卵用，我改了0.0.0.0:80但还是127.0.0.1:8080

**Comment by xavierskip** [comment]
> wser -c config.json 没卵用，我改了0.0.0.0:80但还是127.0.0.1:

以database中的配置为准。修改了config.json文件后需要import保存到database中去，运行的时候和config.json这个文件没有任何关系了。参见上面 https://github.com/filebrowser/filebrowser/issues/652#issuecomment-491580127 的回复

**Comment by bclswl0827** [comment]
> 2019/05/16 10:39:51 No config file used
> 2019/05/16 10:39:51 listen tcp 0.0.0.0:80: bind: permission denied
> 我把监听端口配置为80，以user启动提示权限被拒绝。但是以sudo 启动80端口正常。
> 我想知道这是Ubuntu的问题还是filebrowser的问题

权限问题，Linux 非 root 用户只能监听 1024 以上的高位端口

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
