### ISSUE TITLE
Configurations files and config init

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#653]
Coming from #651.

> NOTE: I need to copy the parameters from the configuration file to flags manually. Although flag -c is shown as inherited in https://docs.filebrowser.xyz/cli/filebrowser-config-init, some content of the configuration file is ignored. However, when filebrowser is started without arguments after `config init`, the configuration file applies. This might be hard to understand.

Steps to reproduce:

Configuration file located at `/etc/filebrowser/.filebrowser.yml`:

``` yaml
database: /var/lib/filebrowser/filebrowser.db
address: ""
log: stdout
port: 9090
root: /fb_root
```

`/var/lib/filebrowser/` does not exist. So, because of #650, `config init` fails:

``` bash
# filebrowser config init
2019/01/31 03:18:20 open /var/lib/filebrowser/filebrowser.db: no such file or directory
```

This means that, although it is not shown in the logs, the config file is read and the database path is used. After creating `/var/lib/filebrowser/`:

``` bash
# filebrowser config init

Congratulations! You've set up your database to use with File Browser.
Now add your first user via 'filebrowser users new' and then you just
need to call the main command to boot up the server.
Sign up:      false
Auth method:  json
Shell:

Branding:
  Name:
  Files override:
  Disable external links:  false

Server:
  Log:       stdout
  Port:      8080
  Base URL:
  Root:      .
  Address:   127.0.0.1
  TLS Cert:
  TLS Key:

Defaults:
  Scope:      .
  Locale:     en
  View mode:  list
  Commands:
  Sorting:
    By:   name
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}
```

- Fields `address` and `log` in the config file match the defaults.
- Fields `port` and `root` file are ignored.

If filebrowser is started now:

``` bash
# filebrowser
2019/01/31 03:24:26 Using config file: /etc/filebrowser/.filebrowser.yml
2019/01/31 03:24:26 Listening on [::]:9090
```

The config file is read and `port` and `root` are used.

Still, if the user executes `config cat` in order to check which configuration is being used, the config file is ignored.

We might need to explain that in `config` (and subcommands) the config file might only be used to set the path to the database. All other fields are ignored.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
