### ISSUE TITLE
Adding `*` as `--command` produces a panic

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#654]
Adding `*` as a command produces a panic. I think it should return a error to the user that tried to use the shell/terminal. If multiple users are connected to filebrowser, it should not fail for all of them.

``` bash
...
2019/01/31 03:37:34 http: panic serving 172.17.0.1:55402: regexp: Compile(`*`): error parsing regexp: missing argument to repetition o
perator: `*`
goroutine 24 [running]:
net/http.(*conn).serve.func1(0xc000236460)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0xa21ae0, 0xc000298db0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
...
```

BTW, the correct syntax to allow any command is `.*`.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
