### ISSUE TITLE
Can not access through public

### ISSUE THREAD

**Issue by wasamisam0119** [filebrowser/filebrowser#656]
**Description**
You can see it is listening on port 4000 but why it is with IPv6 address?
[centos@ip-172-31-16-109 ~]$ sudo netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name           
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      496/rpcbind         
tcp        0      0 0.0.0.0:6800            0.0.0.0:*               LISTEN      1202/aria2c         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1141/sshd           
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      1267/python         
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1106/master         
tcp6       0      0 :::4000                 :::*                    LISTEN      2478/filebrowser    
tcp6       0      0 :::111                  :::*                    LISTEN      496/rpcbind         
tcp6       0      0 :::80                   :::*                    LISTEN      2464/caddy          
tcp6       0      0 :::6800                 :::*                    LISTEN      1202/aria2c         
tcp6       0      0 :::22                   :::*                    LISTEN      1141/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      1106/master     

This is my config file:
{
  "port": 4000,
  "address":"0.0.0.0",
  "noAuth": false,
  "log": "stdout",
  "plugin": "",
  "database":"/home/centos/filebrowser.db",
  "scope":"/home",
  "allowCommands": true,
  "allowEdit": false,
  "allowNew": true,
  "commands": [
    "git",
    "svn"
  ]
}

I telnet my ip address 4000 but connection refused...
Suffered for the whole night, need help!

**Comment by eine** [comment]
Please, fill the [bug report template](https://github.com/filebrowser/filebrowser/issues/new?template=bug_report.md) and provide as much info as you can. Are you using docker? Is it a remote server? Can you `curl localhost:4000` in the same machine? Which version of filebrowser are you using? The configuration file seems to correspond to branch v1. If you are using filebrowser v2.0.0 or above, you need to update it.

**Comment by wasamisam0119** [comment]
@1138-4EB 
Thank you for your reply.
1. I am not using docker, it is on a remote server on Centos7
2. I can get response from curl localhost:4000 in the same machine.
3. I am using v2.0.2
4. Could you please tell me how to update the config file and what it the right format?

Cheers

**Comment by eine** [comment]
You can have a look at: https://docs.filebrowser.xyz/upgrade-from-1.x

**Comment by wasamisam0119** [comment]
@1138-4EB 
Thanks, but the problem is the page still can not accessed by public network, why it is binding on IPv6? I just can't figure out why...

Many many thanks
Sam

**Comment by eine** [comment]
It can be because `net.ipv6.bindv6only=1` in your CentOS. Can you check it and, if so, change if to `0`? References:

- https://github.com/moby/moby/issues/2174
- https://github.com/golang/go/issues/679

**Comment by wasamisam0119** [comment]
@1138-4EB  doesn't really work....

**Comment by hacdias** [comment]
@wasamisam0119 did you manage to make it work? It doesn't seem to be a problem of File Browser itself though.

**Comment by leowood2000** [comment]
same here, 
[root@li173-514 ~]# netstat -anupt|grep filebrowser
tcp6       0      0 :::881                   :::*                    LISTEN      9297/filebrowser

**Comment by popsc30** [comment]
same problem here!
just set port on "8080", started the server can only work through localhost but not on public...
while I shut down the filebrowser and started a nodejs server on port "8080", worked both localhost and public....

**Comment by Androkiller** [comment]
I have got the same issue but on Windows. Only accessible from from the host.

![image](https://user-images.githubusercontent.com/25016806/60357098-985a2980-99ca-11e9-8a8a-ef1a8a834196.png)

**Comment by nambrosch** [comment]
@Androkiller you're listening on address 127.0.0.1 which means it's only accessible from the host it's running on - to make it accessible from other machines change the listening address to 0.0.0.0

**Comment by ManuelFte** [comment]
I know this is a very old issue, but since it was never solved and I found it on Google while facing the same problem, I thought it could be useful to note that I solved it by configuring a reverse proxy with Nginx. It doesn't matter if it's only binding to IPv6, it works just right. Hope it helps someone.

**Comment by Dare-Devill** [comment]
@ManuelFte did you get any solution for it ?
Got same issue i can't access it from another pc in same network but the droopy still works 🥲
Currently on latest version of filebrowser and I'm on arch (already done a command "sudo ufw allow 8080")

**Comment by DarkZoneSD** [comment]
> @ManuelFte did you get any solution for it ? Got same issue i can't access it from another pc in same network but the droopy still works 🥲 Currently on latest version of filebrowser and I'm on arch (already done a command "sudo ufw allow 8080")

filebrowser config set --address "0.0.0.0" should do the trick. It changes the listening address from localhost to 0.0.0.0 which makes it accessible from other devices
