### ISSUE TITLE
Per-user auto directory creation

### ISSUE THREAD

**Issue by Casxt** [filebrowser/filebrowser#657]
**Is your feature request related to a problem? Please describe.**
Auto create folder for new user are convenient for a small team.

**Describe the solution you'd like**
for example I can setting user default scope like `./User/{$USERNAME}`,  and I notice filebrowser will create folder if user scope are not exists, so when a new user 'A' sign up, his own floder will be create automaticlly.

**Describe alternatives you've considered**
support a few environment variable are enough make scope system more powerful.
add a Command Runner of user sign up event is also a good solution.

**Comment by ttys3** [comment]
@Casxt  maybe this is what you need: http://files.80x86.io/router/rom/opt/fb/
I've added an "Auto create user home dir"  option in global settings.

**Comment by hacdias** [comment]
@442hz it would be nice if you could create a PR into this repository with that feature 😄

**Comment by ttys3** [comment]
@hacdias  OK,I've made some PR to this feature:
https://github.com/filebrowser/filebrowser/pull/676
https://github.com/filebrowser/frontend/pull/102

**Comment by hacdias** [comment]
Both PRs were merged! Closing this issue and releasing a new version (2.0.4). Sorry for taking this long and really thanks @ttys3

**Comment by laker-93** [comment]
how can this feature be used to create private folders when new users sign up?
If I have this feature enabled then user data is not private to each user.

**Comment by laker-93** [comment]
I've figured out how to do this. In the admin panel, must have the following option enabled

Auto create user home dir while adding new user 

Then in the "User default settings" section must leave the 'scope' as empty.
