### ISSUE TITLE
Option to disable Admin interface

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#66]
@mholt idea

**Comment by mholt** [comment]
... but not without a way to be useful without an interface :wink: This is not something you need to consider in the short-term, I think, unless there is demand for it from others...

**Comment by hacdias** [comment]
Sure!

**Comment by faddat** [comment]
@hacdias 
So, I finally have my implementation up and running.  I'd love to get your thoughts on my thoughts:  some of my posts are directly about caddy-hugo.  It's pretty likely that I will make caddy-hugo my testing place for learning how to write API stuff in golang.  

Thank you so much for your hard work on this plugin.  It ROCKS!

jacobgadikian.com

Ps:  I just realized I have no idea why I put this in this issue-thread.  Oh, well-- I'm not sure how it would fit into any of the others, either ;).

**Comment by hacdias** [comment]
Hey @faddat!

This is not the right place to say that (ahah), but congratulations and thanks at the same time. If you want to say something else, send me an email or open a new issue, ok?

Have a nice day!

**Comment by hacdias** [comment]
I am closing this issue for now because of its inactivity and the fact that this plugin would be useless without the admin interface. We can discuss how it couldn't be in the future.
