### ISSUE TITLE
A more detailed documentation

### ISSUE THREAD

**Issue by truc0** [filebrowser/filebrowser#660]
**Is your feature request related to a problem? Please describe.**
Unable to change a user's permission by following command:
 ```shell
filebrowser users update guest --perm.delete
```
And I'm sure that the program can find `filebrowser.db` in current folder and the username is exactly guest (not a spelling error).
Btw, I cannot set up almost anything through your docs (maybe it's my fault), please give a more clear and detailed documentation, thank you

**Additional context**
When I use docker to set up a filebrowser server, I need to create `/path/to/root/.filebrowser.json` first, or docker would create a directory that has the same name, then an error occurred.

**Comment by eine** [comment]
Hi @wozuishuai13768! There are three different issues here. Can you please split them?

1. *Unable to change a user's permission by following command*. Open new issue. Try to reply the following questions there: What output do you get, if you get any at all? Are you sure that there is no other database file which can be being used? Is there any configuration file? Is the configuration file being used? How did you initialize the configuration? All these questions are related to #653.
2. *Btw, I cannot set up almost anything through your docs (maybe it's my fault), please give a more clear and detailed documentation, thank you*. This is the issue that corresponds to the title. Please, elaborate. What do you find unclear? What were you searching for and you couldn't find? What do you know already and what do you want to learn?
3. *docker would create a directory that has the same name, then an error occurred*. Open new issue. Provide the command your are using to run the container.

For issues 1 and 3, please provide the version of filebrowser and the host OS.

**Comment by truc0** [comment]
The issues are split to: #665 #666 #667, thanks for your answer and patient.

**Comment by hacdias** [comment]
Closing as they were slip.

**Comment by eine** [comment]
@hacdias, although three issues were split, the topic of this one is not solved yet:

> @1138-4EB wrote:
> This is the issue that corresponds to the title. Please, elaborate. What do you find unclear? What were you searching for and you couldn't find? What do you know already and what do you want to learn?

So, @wozuishuai13768, if you want to follow-up, don't hesitate to reply here.

**Comment by truc0** [comment]
Thank you.
I think it would be better to add something like `filebrowser users update <username> --perm.create=false` because users may try `filebrowser users update <username> --perm.create=false` and get an error.
That's all of it. Thank you for your patients.
