### ISSUE TITLE
Incorrect file sorting (case dependency and wrong order)

### ISSUE THREAD

**Issue by sibprogrammer** [filebrowser/filebrowser#661]
**Description**
Open the directory with the following content: Applications, Downloads, bin

**Expected behaviour**
Files/directories are shown in a following order:
* Applications
* bin
* Downloads

**What is happening instead?**
Files/directories are shown in a following order:
* bin
* Downloads
* Applications 

**Additional context**
There are two problems:
* case insensitive search seems like has been broken unintentionally in 4b980100937daaf37a2cfb271fbf7b949ce8b302
* sort direction is wrong (up arrow means "A" on the first, "Z" on the last place)

**How to reproduce?**
* create file structure described above
* open filebrowser

**Comment by ttys3** [comment]
sort direction is wrong on the frontend vue files. not golang
