### ISSUE TITLE
Unable to change permission of user by using command

### ISSUE THREAD

**Issue by truc0** [filebrowser/filebrowser#665]
**Description**
I'm trying to update an user's permission in command line.
__Basic info__:     
I installed filebrowser by following command:
```shell
curl -fsSL https://filebrowser.xyz/get.sh | bash
```
And my system info:
- Ubuntu 18.04.1 LTS (bionic)

Here's the screenshot:
![](http://pan.truco.moe/archive/info.png)
Here's my config file:
```json
{
    "log": "debug",
    "root": "/share",
    "database": "/srv/filebrowser/filebrowser.db",
    
    "address": "127.0.0.1",
    "port": 29920,

    "perm.admin": true,
    "perm.download": true,
    "perm.execute": false,
    "perm.modify": true,
    "perm.share": true
    
}
```
And I tried the following one, still not working:
```json
{
    "log": "debug",
    "root": "/share",
    "database": "/srv/filebrowser/filebrowser.db",
    
    "address": "127.0.0.1",
    "port": 29920
}
```

**Expected behaviour**
I expect the permission of creating files will change to `false`

**What is happening instead?**
It seems that nothing changed...

**Additional context**
I doubt that if I used incorrect command.

**How to reproduce?**
Just install it and try. (maybe it is my misunderstanding of docs)

**Files**
No files..

**Comment by hacdias** [comment]
@wozuishuai13768 a flag is not a toggler. When you don't set it's value, it's default is true unless otherwise specified. You should run `--perm.create=false` if you want to set it to false.
