### ISSUE TITLE
Example config missing

### ISSUE THREAD

**Issue by truc0** [filebrowser/filebrowser#666]
**The example cannot be found**
In the [installation part of docs](https://docs.filebrowser.xyz/installation), it says that there is a [example file](https://github.com/filebrowser/filebrowser/blob/master/.filebrowser.docker.json), but i got this:
![404](https://user-images.githubusercontent.com/22969604/52172939-fb52d780-272e-11e9-8bba-3402d242d655.png)

**Comment by eine** [comment]
Thanks for reporting it. It should be fixed now. The correct URL is https://github.com/filebrowser/filebrowser/blob/master/.docker.json
