### ISSUE TITLE
Base URL requires a trailing slash to work

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#669]
**Description**
My setup is like:
docker
caddy `proxy /files` to filebrowser service
filebrowser started with `-p 4000 -b /files -d /db/data -r /var/www`
both /db and /var/www are mounted into the container via docker

**Expected behaviour**
when I hit `/files` it goes to filebrowser, and filebrowser should work (i.e. handle static files etc correctly)

**What is happening instead?**
when I hit `/files` I get 301 back to `/`

**How to reproduce?**
see description

**Comment by princemaple** [comment]
OK turns out baseurl requires a trailing `/` to work. so I had to go to `/files/`. Feel free to close, or "fix" it.

FYI I just do `redir /fs /fs/` in Caddy as a workaround. Changed from `files` to `fs` because I noticed filebrowser frontend uses `/files` route as well, just avoiding weird duplication in paths.

**Comment by hacdias** [comment]
This is actually a known-bug. Just a note for myself: see `StrictSlash`.

**Comment by LoaderFabi** [comment]
I have the same Issue, but without Proxy and using Filebrowser as Caddy Plugin.

The redir "/files /files/" neither "/files /files/files" seems to work, even tho Typing domain.tld/files/files manually into Adressbar works fine.
