### ISSUE TITLE
Can't build caddy hugo with latest caddy src

### ISSUE THREAD

**Issue by Bitti09** [filebrowser/filebrowser#67]
I'm gettig  the folowing errors with latest caddy source:

src/github.com/hacdias/caddy-hugo/hugo.go:18:2: no buildable Go source files in /root/caddy-src/src/github.com/hacdias/caddy-hugo/routes/assets

after `go generate .`  in  caddy-hugo:

```
# github.com/hacdias/caddy-hugo/tools/frontmatter
src/github.com/hacdias/caddy-hugo/tools/frontmatter/frontmatter.go:20: undefined: parser.DetectFrontMatter
# github.com/hacdias/caddy-hugo/routes/browse
src/github.com/hacdias/caddy-hugo/routes/browse/get.go:32: unknown browse.Browse field 'Root' in struct literal
src/github.com/hacdias/caddy-hugo/routes/browse/get.go:43: not enough arguments to return
```

is there any plan to update this  plugin to be buildable with latest caddy version?

**Comment by hacdias** [comment]
I hate the first error. It means that that function was unexported bu the Hugo team. I've opened an [issue](https://github.com/spf13/hugo/issues/2105). 

@mholt how should I fix the second part? With the removal of "Root" what should I do to set the path where the Browse middleware must act?

**Comment by mholt** [comment]
@hacdias It moved to here: https://github.com/mholt/caddy/blob/6f5cff539367acfb58d6d9edf5dede10b63fa753/middleware/browse/browse.go#L33

**Comment by hacdias** [comment]
Thanks @mholt. Now we've to wait for Hugo team.

**Comment by mholt** [comment]
Users cannot download Caddy with the hugo add-on right now:

```
---- # github.com/hacdias/caddy-hugo/browse
---- /home/caddy/go/src/github.com/hacdias/caddy-hugo/browse/get.go:32: unknown browse.Browse field 'Root' in struct literal
---- /home/caddy/go/src/github.com/hacdias/caddy-hugo/browse/get.go:43: not enough arguments to return
---- 
```

It's currently on:

```
commit f530e901c81cb30dcd55cd0eec67fa58e9d1a8f4
Date:   Mon Apr 25 08:56:40 2016 +0100
    fix a part of #67
```

**Comment by hacdias** [comment]
Have you updated caddy-hugo? I already changed the field root to config "section". o.O

**Comment by mholt** [comment]
Yes, notice that it's at commit f530e901c81cb30dcd55cd0eec67fa58e9d1a8f4 which right now is the current HEAD.

**Comment by mholt** [comment]
Sorry, now we've got:

```
---- # github.com/hacdias/caddy-hugo/routes/browse
---- /home/caddy/go/src/github.com/hacdias/caddy-hugo/routes/browse/get.go:35: cannot use conf.Path (type string) as type http.FileSystem in field value:
----    string does not implement http.FileSystem (missing Open method)
---- /home/caddy/go/src/github.com/hacdias/caddy-hugo/routes/browse/get.go:43: not enough arguments to return
```

Not sure why the error was "outdated" from last time. But this looks like an issue. You need to use http.Dir, not a string.

Please double-check by compiling the code before pushing, and I'll be happy to update it. ;)

**Comment by hacdias** [comment]
What should I do @mholt? Do I have to create an http.FileSystem for the root path? Before I just had to set the root path in browse! :P

**Comment by mholt** [comment]
Yeah, we fixed that, you now have to use http.Dir().

**Comment by hacdias** [comment]
Check it now please ;)

**p.s.:** don't update Hugo repository because its latest version unexported a function I need.

**Comment by mholt** [comment]
Aye, that did it. Thanks!

**Comment by hacdias** [comment]
You're welcome. Now we just have to wait for Hugo guys to unexport the function. I think I'm going to make a PR.

**Comment by Bitti09** [comment]
:+1:

**Comment by hacdias** [comment]
Hey @Bitti09 

They already exported the needed function. Please update the repositories and try again ;)

Let me know if it works!

**Comment by Bitti09** [comment]
Tested it  now:
without doing a  `go generate .` in 
`src/github.com/hacdias/caddy-hugo`
the  error
`src/github.com/hacdias/caddy-hugo/hugo.go:18:2: no buildable Go source files in /root/caddy-src/src/github.com/hacdias/caddy-hugo/routes/assets`
still exists

after doing that no error  is shown and  the expected
`new caddy build: /root/caddy-src/build2/customCaddy` message
is displayed :smile:

**Comment by hacdias** [comment]
Don't worry about that error. You must run that command after cloning/updating the repository. It's in the readme.

I'll close the issue then ;) I hope you like the web interface for Hugo! If you have some suggestions, tell me!
