### ISSUE TITLE
Latest docker image can't install

### ISSUE THREAD

**Issue by SpringLych** [filebrowser/filebrowser#671]
**Description**
The latest of docker image can't install, but v2.02 can.
I install by docker image latest, it failed, and then I just change the tag to v2.02, it installed success.

**What is happening instead?**
Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/data/filemanage/.filebrowser.json\\\" to rootfs \\\"/var/lib/docker/overlay2/2c1a8beb0fafef7ec1c5d482b2620aecd6b67b7e629b9b8912c3d1878bcaba4d/merged\\\" at \\\"/var/lib/docker/overlay2/2c1a8beb0fafef7ec1c5d482b2620aecd6b67b7e629b9b8912c3d1878bcaba4d/merged/.filebrowser.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
root@ubuntu:~/myfile/filemanage# docker run -v /usr/data:/srv -v /usr/data/filemanage/filebrowser.db:/database.db -v /usr/data/filemanage/.filebrowser.json:/.filebrowser.json -p 6500:80 filebrowser/filebrowser
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/data/filemanage/.filebrowser.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b00a2106c729d6f3fdc6ac46154162ce5aa0e0e826fa1c6431646050a2360436/merged\\\" at \\\"/var/lib/docker/overlay2/b00a2106c729d6f3fdc6ac46154162ce5aa0e0e826fa1c6431646050a2360436/merged/.filebrowser.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by Mosney** [comment]
I have this issue too

**Comment by eine** [comment]
I can't reproduce:

``` bash
# docker pull filebrowser/filebrowser
# docker run --rm -it filebrowser/filebrowser
2019/04/30 22:03:25 Using config file: /.filebrowser.json
2019/04/30 22:03:25 Listening on [::]:80
^C
```

**Comment by williamt31** [comment]
Getting same/similar errors by following the instructions [here](https://docs.filebrowser.xyz/installation)
If I add this line
>     -v /path/filebrowser.db:/database.db \
It doesn't error, tries to start but never shows up in docker stats.  but is somehow running as I have to stop it before i can rm it.
If I add this line
>     -v /path/.filebrowser.json:/.filebrowser.json \
I get the error every time.
If I remove both lines the container starts fine.  Is there any config that needs to be stored persistent or are these lines not needed?
I tried to docker exec -it into it but it appears there is no 'sh' nor 'bash' shell installed so I cannot look inside to see where those config files are located.

**Comment by eine** [comment]
@williamt31, please see #667 and https://github.com/filebrowser/filebrowser/blob/master/Dockerfile.

**Comment by williamt31** [comment]
maybe I'm just dense but I tried following those guides, if I create the filebrowser.json the container is unreachable.
Then I tried binding the parent dir "/etc/filebrowser" or "/srv/test/filebrowser" but nothing shows up in my host dir so when I change the admin creds it's not persistent.

**Comment by eine** [comment]
> if I create the filebrowser.json the container is unreachable.

What do you mean with 'create the filebrowser.json'? Do you 'touch' it or do you write some content in it? What do you mean with 'unreachable'? What error do you get when starting the container and/or when trying to browse?

> Then I tried binding the parent dir "/etc/filebrowser" or "/srv/test/filebrowser" but nothing shows up in my host dir so when I change the admin creds it's not persistent.

By default, `/.filebrowser.json` is used, as shown in https://github.com/filebrowser/filebrowser/blob/master/Dockerfile. You need to either replace it with a valid config file or provide a custom location with CLI arg `-c`.
