### ISSUE TITLE
cannot find package "github.com/filebrowser/filebrowser/v2/cmd"

### ISSUE THREAD

**Issue by ikwyl6** [filebrowser/filebrowser#672]
**Description**

```
$ uname -a
Linux alarm 4.4.169-1-ARCH #1 PREEMPT Fri Dec 28 09:00:53 UTC 2018 armv5tel GNU/Linux
```
I'm pretty experienced linux guy but not that familiar with github or go so please be patient. I had compiled this in the past for my little pogoplug with armv5 but it's been a while. Now I'd like an updated binary. I'm compiling because the pre-compiled executable won't work on this architecture. I did a 'git clone' to get the latest master and when I tried to compile for arm5v within that master branch from 'git clone' and when I run `go build` within that directory I get:

```
$ go build
main.go:6:2: cannot find package "github.com/filebrowser/filebrowser/v2/cmd" in any of:
 /usr/lib/go/src/github.com/filebrowser/filebrowser/v2/cmd (from $GOROOT)
 /home/alarm/go/src/github.com/filebrowser/filebrowser/v2/cmd (from $GOPATH)
```
```
$ env|grep GO
GOPATH=/home/alarm/go/
```
checking the `/home/alarm/go/src/github.com/filebrowser/filebrowser` which I had previously downloaded before when I was compiling the binary, the 'v2/cmd' command does not exist. Perhaps if someone can tell me how to update the `/home/alarm/go/src/github.com/filebrowser/filebrowser` this would probably be a non-issue...

**Comment by blingblingyoyo** [comment]
I think you should use "go get", not "go build".

**Comment by hacdias** [comment]
@ikwyl6 as @blingblingyoyo said, you must run `go get` first. Also, please ensure you're using the latest Go version. If you're using the latest Go version, please clone it outside of GOPATH.

**Comment by ikwyl6** [comment]
Ok will try later tonight. Using the most current version from arch. Thanks for info. I think these build instructions used to be on the README at some point. If they weren't before, any chance we could get them added in the Install on the FB.xyz site so they are there for future?

**Comment by eine** [comment]
> I think these build instructions used to be on the README at some point. If they weren't before, any chance we could get them added in the Install on the FB.xyz site so they are there for future?

Please, have a look at https://docs.filebrowser.xyz/contributing

**Comment by ikwyl6** [comment]
So in the contributing link it says at the end to do a `go build`. TBH I didn't even look in that page as I wasn't contributing to the code. If I create a pull request for the 'install' xyz page to add some of the points for manual install, will you add it to the page?

**Comment by eine** [comment]
> So in the contributing link it says at the end to do a `go build`.

Not exactly. `go build` is the last step in a page with six of them. So, you are expected to read and execute it from the beginning. Jumping directly to `go build` without understanding the structure of the project is likely to fail.

> TBH I didn't even look in that page as I wasn't contributing to the code.

'Contributing' is used as a synonym for 'Development'. Precisely, guessing how to build filebrowser for your platform (where it is failing now) is a contribution to the project, even if you don't expect to push it back to master.

> If I create a pull request for the 'install' xyz page to add some of the points for manual install, will you add it to the page? 

Sure, we are open to any enhancement to the docs. See https://github.com/filebrowser/docs. However, note that this issue is about 'building' filebrowser in order to obtain a binary. With 'install', we understand that the user does already have it.
