### ISSUE TITLE
Can't figure out `-s` option: filebrowser -s /path/to/your/files

### ISSUE THREAD

**Issue by akyo8** [filebrowser/filebrowser#673]
Hello FileBrowser team.
I'm trying to setup local environment to have a look. But I got stuck just after `curl`.
It says: "unknown shorthand flag: 's' in -s"

I have checked help and no `-s` flag exists.
Could you help me please?

FYI: Also, I need to setup nginx or any other webserver on my local machine and then set proxy to the filebrowser web server?

Thanks.

**Comment by hacdias** [comment]
@evgeny127 sorry, it's `-r`. Will update the docs!
