### ISSUE TITLE
Proxy authentication not bypassing login screen

### ISSUE THREAD

**Issue by nambrosch** [filebrowser/filebrowser#674]
**Description**
I'm trying to configure apache as a reverse proxy + basic auth, everything works except for filebrowser auto-login but I'm not sure if that is a feature or not.  Here is the relevant portion of my httpd config with "johndoe" as a hard-coded username, just for a demonstration:
```
RequestHeader set X-Filebrowser-Auth johndoe
ProxyPass http://127.0.0.1:8080/
ProxyPassReverse /
```
And here is the relevant portion of my filebrowser config:
```
Auth method:  proxy

Auther configuration (raw):
{
  "header": "X-Filebrowser-Auth"
}
```

**Expected behaviour**
I expect that after basic auth succeeds then the X-Filebrowser-Auth header is passed to filebrowser with the authenticated username of "johndoe" which will then log me in automatically.

**What is happening instead?**
Apache basic auth succeeds however I am brought to a login page.  I can enter any combination of username/password into the login page, including an empty password, but I will always be logged in as user "johndoe"

**Additional context**
I'm not sure what the behavior is supposed to be here... once external authentication is complete, is filebrowser supposed to bypass it's login screen?

**Comment by hacdias** [comment]
@nambrosch I didn't try it, but what you describe makes sense for me taking in account the code we have.

**Comment by hacdias** [comment]
Just released v2.0.3. Could you try it out to make sure it works?

**Comment by nambrosch** [comment]
@hacdias perfect, thank you!  when i finish my setup i'll post the full apache config for others to use since there wasn't really any reference material for apache/httpd.

**Comment by hacdias** [comment]
Sure, thanks. When you have a config template, can you open an issue on https://github.com/filebrowser/docs please?

**Comment by trivial-zero** [comment]
> @hacdias perfect, thank you! when i finish my setup i'll post the full apache config for others to use since there wasn't really any reference material for apache/httpd.

Still waiting...

**Comment by nambrosch** [comment]
@BIKA-C here is my apache config, just add your own auth method into the location section.
```
  <Location "/filebrowser/">
    (insert your auth config here)
    RequestHeader set X-Filebrowser-Auth %{REMOTE_USER}s
    ProxyPass http://127.0.0.1:8080/filebrowser/
    ProxyPassReverse http://127.0.0.1:8080/filebrowser/
  </Location>

  ProxyPreserveHost On
  RewriteEngine On

  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule (.*) ws://127.0.0.1:8080/$1 [P,L]

  RewriteRule ^/filebrowser$ /filebrowser/ [L,R=301]
  ```

**Comment by resmh** [comment]
User accounts are not automatically created. If signup is enabled, users can add themselves using dummy passwords. To initially reach the admin account on default settings, you need to fix the header to "admin".
