### ISSUE TITLE
'Undefined: bolt' when trying to 'go get'

### ISSUE THREAD

**Issue by ikwyl6** [filebrowser/filebrowser#677]
Hi  - your friendly annoying user again who wants to compile....! I've gotten all pkgs to compile filebrowser from source and when I run `go get` in the filebrowser/ directory (outside of GOPATH), I get:

```
$ go get
# github.com/filebrowser/filebrowser/v2/storage/bolt/importer
storage/bolt/importer/users.go:11:2: imported and not used: "go.etcd.io/bbolt"
storage/bolt/importer/users.go:33:31: undefined: bolt
```

any ideas? I run `go get "go.etcd.io/bbolt"` and it returns nothing after the command, thinking that all is fine. I check the directory:

```
$ ls ~/go/pkg/mod/go.etcd.io/bbolt\@v1.3.2/
LICENSE           bolt_386.go    bolt_linux.go    bolt_ppc.go      bolt_unix.go          bucket.go       cursor_test.go  errors.go         node.go       quick_test.go                        tx_test.go
Makefile          bolt_amd64.go  bolt_mips64x.go  bolt_ppc64.go    bolt_unix_solaris.go  bucket_test.go  db.go           freelist.go       node_test.go  simulation_no_freelist_sync_test.go
README.md         bolt_arm.go    bolt_mipsx.go    bolt_ppc64le.go  bolt_windows.go       cmd             db_test.go      freelist_hmap.go  page.go       simulation_test.go
allocate_test.go  bolt_arm64.go  bolt_openbsd.go  bolt_s390x.go    boltsync_unix.go      cursor.go       doc.go          freelist_test.go  page_test.go  tx.go
```

I saw this comment about 'Cannot build from scratch' about something different that was 'undefined' https://github.com/filebrowser/filebrowser/issues/663#issuecomment-459953282 and tried the `go build -mod vendor` within the bbolt directory but that gives:

```
$ go build -mod vendor
build flag -mod=vendor only valid when using modules
```

**Comment by hacdias** [comment]
Which Go version are you using? It seems it is not linking `go.etcd.io/bbolt` to `bolt`.

**Comment by ikwyl6** [comment]
```
$ go version
go version go1.11.5 linux/arm
```

**Comment by hacdias** [comment]
Try pulling now

**Comment by ikwyl6** [comment]
I did another `git clone` from github and then ran `go get` in filebrowser dir and same error.

**Comment by hacdias** [comment]
Please check if the file has `bolt "go.etcd.io/bbolt"` on the imports. I can't reproduce the error, nor the CI.

**Comment by ikwyl6** [comment]
These are the first 12 lines of storage/bolt/importer/users.go:
```
package importer

import (
   "encoding/json"
   "fmt"

   "github.com/asdine/storm"
   "github.com/filebrowser/filebrowser/v2/rules"
   "github.com/filebrowser/filebrowser/v2/storage"
   "github.com/filebrowser/filebrowser/v2/users"
   "go.etcd.io/bbolt"
)
```

**Comment by hacdias** [comment]
So you don't have the latest version from master. Git pull please.

**Comment by ikwyl6** [comment]
Doing a `go clone` again wasn't enough. I did a `go pull` which pulled all changes from the clone.
