### ISSUE TITLE
how can i upload file with my client (flex client or html client) use filebrowser api

### ISSUE THREAD

**Issue by hljlgj** [filebrowser/filebrowser#678]
**Is your feature request related to a problem? Please describe.**
how can i upload file with my client (flex client or html client) use filebrowser api?

**Comment by hacdias** [comment]
The HTTP API exists to be used with the File Browser instance via GUI. We don't support officially other use cases. Although, I can tell you the endpoint is POST at `/api/resources/${PATH}`.

**Comment by magicianlib** [comment]
@hacdias 
The filebrowser Just a file browser? Can't I upload files via Java or HTML client?

I want to implement a function, which is to use File Browser as the File storage server. In addition, there is a client, such as Java, which can call the response API to upload files to the File storage server.

My browser documentation says this, but it doesn't say anything about it.  Will this feature be implemented later? I particularly wanted to be able to provide a responsive API for file uploads
