### ISSUE TITLE
Starting filebrowser gives 'the resource does not exist'

### ISSUE THREAD

**Issue by ikwyl6** [filebrowser/filebrowser#679]
**Description**
Compiling filebrowser from source on arm using 'go get' and running filebrowser with an existing filebrowser.db in the same directory throws a 'no config file used' and 'the resource does not exist' errors. May need better error handling on what this error means.

**Expected behaviour**
What did you expect to happen? Filebrowser to start.

**What is happening instead?**
```
$ filebrowser 
2019/02/18 14:58:21 No config file used
2019/02/18 14:58:21 the resource does not exist
```

**Additional context**
I thought that where there is no filebrowser.yml file (no config file used) that I did a `touch filebrowser.yml` but that still throws the same error.

**Comment by ttys3** [comment]
this could be a key in filebrowser.db doest not exits. maybe the db is broken 
or you need to migratie from 1.x db to 2.x
simplest solution is remove the db.

**Comment by ikwyl6** [comment]
Removing the `filebrowser.db` file now gives when I run `$ filebrowser`

```
$ filebrowser 
2019/02/20 00:01:30 No config file used
panic: could not locate box "../frontend/dist"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0x5f2285, 0x10, 0x1)
        /home/alarm/go/pkg/mod/github.com/!geert!johan/go.rice@v0.0.0-20170420135705-c02ca9a983da/box.go:110 +0x7c
github.com/filebrowser/filebrowser/v2/http.getStaticHandlers(0xc0cd20, 0xe05b00, 0xe38980, 0xe22908, 0x0, 0x0)
        /home/alarm/src/filebrowser/http/static.go:87 +0x24
github.com/filebrowser/filebrowser/v2/http.NewHandler(0xc0cd20, 0xe05b00, 0xe426f0, 0xe, 0x6b2c48, 0xe22908)
        /home/alarm/src/filebrowser/http/http.go:20 +0xd8
github.com/filebrowser/filebrowser/v2/cmd.glob..func12(0xa852f8, 0xa9ca3c, 0x0, 0x0, 0x0, 0xc0cd20)
        /home/alarm/src/filebrowser/cmd/root.go:122 +0x1cc
github.com/filebrowser/filebrowser/v2/cmd.python.func1(0xa852f8, 0xa9ca3c, 0x0, 0x0)
        /home/alarm/src/filebrowser/cmd/utils.go:102 +0x16c
github.com/spf13/cobra.(*Command).execute(0xa852f8, 0xc0e100, 0x0, 0x0, 0xa852f8, 0xc0e100)
        /home/alarm/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x20c
github.com/spf13/cobra.(*Command).ExecuteC(0xa852f8, 0x1, 0x17a1c, 0xa8c608)
        /home/alarm/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x210
github.com/spf13/cobra.(*Command).Execute(0xa852f8, 0x4f2840, 0xa8c608)
        /home/alarm/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x1c
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/alarm/src/filebrowser/cmd/cmd.go:9 +0x20
main.main()
        /home/alarm/src/filebrowser/main.go:11 +0x24
```
My `filebrowser` executable is in `~/go/bin` where $GOPATH=~/go/ but my filebrowser source is `~/src/filebrowser/`. 
There is no `/frontend/dist/` in my `~/src/filebrowser/`...just `~/src/filebrowser/frontend` (No /dist directory).

**Comment by eine** [comment]
> Compiling filebrowser from source on arm using 'go get'

This is not correct. You did download and build the backend only, not the frontend. That's why it is complaining. You need to first build it, so that html, js and css are available in `frontend/dist`. Then, you can either distribute that folder with your binary, or you can build the backend again with these sources embedded into it. Please have a look at https://docs.filebrowser.xyz/contributing#project-structure.

I'm closing this issue. But feel free to continue the discussion if you have any further question.

**EDIT**

With `USE_DOCKER="true" ./wizard.sh -b`, everything will be properly built in a docker container and you will get a working binary.

**Comment by ikwyl6** [comment]
I don't use docker. That is why there should be a section in the installation page (not contributing) for building from source. Once this is all done I'll try to put together a set of steps for the install page.

**Comment by eine** [comment]
> I don't use docker.

Then, ensure that you have all the dependencies (see [filebrowser/docker-dev:Dockerfile#L5](https://github.com/filebrowser/docker-dev/blob/master/Dockerfile#L5) and [get_deps.sh](https://github.com/filebrowser/docker-dev/blob/master/get_deps.sh)) and run `./wizard.sh -b` (without the envvar).

> That is why there should be a section in the installation page (not contributing) for building from source. Once this is all done I'll try to put together a set of steps for the install page.

That's `wizard -b`. See:

- https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L209-L210
- https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L79-L93
- https://github.com/filebrowser/filebrowser/blob/master/wizard.sh#L103-L110

**Comment by batara666** [comment]
i follow [official](https://filebrowser.org/installation) installation method, but it's give me error

```sh
oreo@DESKTOP\:~$ filebrowser -r /mnt/c/Users/Dean
2020/07/07 08:52:22 Using config file: /home/oreo/.filebrowser.json
2020/07/07 08:52:22 the resource does not exist
```

ON WSL Ubuntu 20.04

```sh
oreo@DESKTOP\:~$ filebrowser -r /home/oreo
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc0002545b4, 0x0, 0x1)
...
```
