### ISSUE TITLE
离线状态在如何部署filebrower

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#685]
你好，由于现实问题，需要在离线的状态下来部署filebrower，因此手动的在官网下载了`linux-amd64-filebrowser.tar.gz`安装包，并将其上传至服务器（操作系统：Centos7），将其解压后有三个文件：
```
LICENSE
README.md
filebrowser
```
其中filebrowser为可执行文件，因此执行该文件，执行之后结果为：
```
$ ./filebrowser 
2019/02/22 01:34:45 No config file used
2019/02/22 01:34:45 listen tcp 127.0.0.1:8080: bind: address already in use
```
即8080端口已经被占用。所以我的疑问是：（1）这样的离线安装流程是否正确？（2）如何修改配置文件，将监听的`IP:端口`修改为自定义的配置？

**Comment by eine** [comment]
You can set a different port with `-p`. For example, `./filebrowser -p 9090`. Plase, have a look at https://docs.filebrowser.xyz/cli.
