### ISSUE TITLE
Filebrowser v202, v203 does not work without internet access.

### ISSUE THREAD

**Issue by minos197** [filebrowser/filebrowser#687]
**Description**
I have been trying to run file-browser as a way to expose the filesystem in an standalone network created by the device(raspberry pi). The device is running up to date debian stretch with hostapd for the access point, dnsmasq and dhcpd configured to only use the WLAN0 interface.  There is no connectivity provided with the external world, or ther access points. 

There are two possible scenarios:
* Use Filebrowser auth methods.
* Set auth method to None and rely on reverse proxy authentication.

**Expected behavior**
The user should be able to log in the main application interface

**What is happening instead?**

1. With authentication, login in fails with Wrong Credentials error
2. Without authentication the whole application fails to load

**Disabling authentication**

Disabling authentication gets the application stuck to the three dot loading page

Testing is performed with a new database and firewall, with reverse proxy disabled.

~~~~~
./filebrowser config init
./filebrowser config set --auth.method=noauth
./filebrowser

....
root@unicornpi:/opt/filebrowser# ./filebrowser
2019/02/21 13:32:31 No config file used
2019/02/21 13:32:31 Listening on [::]:80
2019/02/21 13:32:56 /api/login: 500 11.1.1.11:58494 the resource does not exist
~~~~~

In the browser console the following debug info is provided
~~~~~
Unhandled promise rejection Error: "500 Internal Server Error
"
	e auth.js:34
	w runtime.js:62
	T runtime.js:288
	t runtime.js:114
	s asyncToGenerator.js:5
	a asyncToGenerator.js:27
	o es6.promise.js:75
	j es6.promise.js:92
	l _microtask.js:18
 es6.promise.js:110
	t es6.promise.js:110
	exports _perform.js:3
	O es6.promise.js:104
	exports _invoke.js:5
	<anonymous> _task.js:35
	y _task.js:21
	b _task.js:25
~~~~~

**With User authentication set to json**

~~~~~~
./filebrowser config init
./filebrowser user add test_user pass
./filebrowser
~~~~~~

Using this setup fails without any messages, just the web-application refuses to accept the credentials.

Interestingly enough, if you connect the Ethernet cable to the device, connecting it to the internet, the same setup will just work, and the user is able to log-in the main interface.

**Comment by hacdias** [comment]
@minos197 it does work without access to an Internet connection. Perhaps it is some of your networking configuration that is causing some kind of conflict. The only networking thing we do is to open a port and listen on it. Nothing else and it isn't influenced by Internet connection.

The error 'the resource does not exist' seems more related to a non-existing user in a database. Although it doesn't make sense because it shouldn't be tied with a 500 error. I can't reproduce this.

Any ideas @1138-4EB?

**Comment by eine** [comment]
@hacdias, when I saw the issue I checked the IP that is shown in the logs: https://www.speedguide.net/ip/11.1.1.11 Which is quite strange to me. However, I don't know if it is because the configuration of the user (firewall, some VPN), if it is some configuration he is not aware about (using it in a company), or if it has nothing to do with the issue.

**Comment by hacdias** [comment]
Perhaps. I can't reproduce this. It just works without Internet connection. It doesn't actually make sense to have a non-internal IP when you don't have an internet connection.

**Comment by minos197** [comment]
I have been investigating this issue since I reported it and it appears to be quite hard to pinpoint the cause.

So far I have three theories.
* I have somehow messed up with the filebrowser database(each time I remove and recreate a user it's unique key increases,
* The fault is on the client side. Something is cached and there is a token miss-match.
* There is some horrible DNS loop going on.

The device is  set as as an access point on WLAN0 which is why the address was set to 11.1.1.1. Normally it should not be connected to any network but for debugging purposes I connect the ethernet cable.

During investigations:
* The filebrowser had a single user account
* Credentials were cached in browser so I do not manual type the password
* Testing happened in safe mode with cleaning the cache/cookies per retry
* Tried the log-in in both android device as well as a laptop and two browsers on each device.
* Tried different network back-ends, from home router (set for windows) , pfsense machine on a LInux network, as well as ddwrt in my home lab.
* Dig was used to verify the dns are resolved properly

dnsmasq.conf contained

~~~~~
interface=wlan0      # Use the require wireless interface - usually wlan0
  address=/#/11.1.1.1
  dhcp-range=11.1.1.1,11.1.1.11,255.255.255.0,1h
~~~~~

It is specifically instructed only to work on the WiFI interface so ETH0 is on default behavior.

Then since I realized that the issue was more common when using Windows laptops, I added those windows specific configurations to dnsmasq.conf

~~~~~
 dhcp-option=19,0           # option ip-forwarding off
  dhcp-option=44,0.0.0.0     # set netbios-over-TCP/IP nameserver(s) aka WINS server(s)
  dhcp-option=45,0.0.0.0     # netbios datagram distribution server
  dhcp-option=46,8             # netbios node type
~~~~~

Which appeared to fix the log-in issue for a couple of days before it returned today.

What database type is the filebrowser.db file? I would like to take a peek at the schema and see if there is something out of the ordinary.

Also in the case that there is a dns resolution race condition, what would happen if when the form loads the dns resolves to an ip iAA.AA.AA.AA and while the use fills in the username/password the domain is updated to  BB.BB.BB.BB.  When the submit button is pressed, does the code act like a normal html form and re-resolve the domain? Or the application domain-> ip picked up on startup and used throughout the application lifecycle?

At any rate, it is a unique use case, and you should not waste resources for it especially since its hard to reproduce. You may close the ticket. I will continue to investigate out of curiosity.

**Comment by hacdias** [comment]
@minos197 thanks! It's a [BoltDB](https://github.com/etcd-io/bbolt) database. There is a [good cli](https://github.com/br0xen/boltbrowser) to navigate its contents.
