### ISSUE TITLE
Stuck on blank page for some Firefox user

### ISSUE THREAD

**Issue by dbeniamine** [filebrowser/filebrowser#690]
**Description**

Some user are stuck on a white page trying to access filebrowser 2.0.x.

**Expected behaviour**

The user should be redirected from `https://<FQDN>/files` to  `https://<FQDN>/files/files/` and see filebrowser interface.

**What is happening instead?**

The user is stuck on a white page on `https://<FQDN>/files/`

In the error logs, we can see:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[En savoir plus] app.c9e23184bf5593511600.js:11:33628
Erreur dans les liens source : request failed with status 404
URL de la ressource : https://<FQDN>/files/static/js/app.c9e23184bf5593511600.js
URL du lien source : app.c9e23184bf5593511600.js.map[En savoir plus]
Impossible d’enregistrer/de mettre à jour un ServiceWorker pour la portée « https://<FQDN>/files/ » : type de contenu incorrect « text/html » reçu pour le script « https://<FQDN>/files/sw.js ». Il doit s’agir d’un type MIME JavaScript.
```

Roughly translated from french, the last sentence means: 

```
Impossible to register / update a ServiceWorker for scope « https://<FQDN>/files/ » :  incorrect content type « text/html » received for the script « https://<FQDN>/files/sw.js ». It may be a MIME type JavaScript
```

So I guess that the browser received some javascript and refused to run it as it is declared to be a `text/html`.

**Additional context**

We use filebrowser behind a reverse nginx proxy on url `/files/` (see #634),  for one user, if hes goes on `/files` he is not redirected to `/files/files/` and stuck on a white page.

Filebrowser works for this user if he goes to `/files/files` directory or uses the private navigation mode in Firefox.

He uses Firefox Version 65.0.2  (64 bits).

**Comment by shyal** [comment]
I'm also having issues with 2.0.x. I'm so grateful for this project... but at the same time, it seems there's a bit of common sense lacking. There's a command line interface, flags, a json config file, a database.. settings that can be modified via a UI.

Why not just have 1, and 1 only way of configuring filebrowser and be done with it?

Also the flags keep on changing with each update. I've spent so much time trying to configure filebrowser, and ended up pulling my hair out.. it's such a shame, because filebrowser is simply unique, and so valuable to its users.

**Comment by maxlaverse** [comment]
Hi @dbeniamine !
I had the same issue and tried several things. Sadly, it works now and I'm not sure which of my changes fixed it. 

Some additional information to your issue  maybe. I noticed that Firefox 65 was trying to set a cookie named `auth` with html content inside it which sounded weird. 

```
Cookie: auth=<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,user-scalable=no"><title>File Browser</title><link rel=icon type=image/png sizes=32x32 href="/static/img/icons/favicon-32x32.png"><link rel=icon type=image/png sizes=16x16 href="/static/img/icons/favicon-16x16.png"><link rel=manifest href="/static/manifest.json"><meta name=theme-color content=#2979ff><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black><meta name=apple-mobile-web-app-title content=assets><link rel=apple-touch-icon href="/static/img/icons/apple-touch-icon-152x152.png"><meta name=msapplication-TileImage content="/static/img/icons/msapplication-icon-144x144.png"><meta name=msapplication-TileColor content=#2979ff><script>window.FileBrowser = JSON.parse(`{
```

Also, I could see in the access logs that this `sw.js` url was being called and answered with a `200`. The frontend was working fine on Safari and there it wasn't trying to get this `sw.js` file.

I compiled the project from the master branch, changed my reverse-proxy to set the Host header properly and finally removed all my cookies. I strongly suspect that clearing the cookies is what actually solved the problem. Might be worth giving it a try.

**Comment by dbeniamine** [comment]
@maxlaverse : thanks you so much, I confirm it was only a cookie issue => I'm closing this one
