### ISSUE TITLE
filebrowser no longer working after update

### ISSUE THREAD

**Issue by shyal** [filebrowser/filebrowser#691]
I hate to be that guy. I admire this project but i feel it's become too hard to use and configure. Issues:

- config flags that change across versions
- a json file to configure, too
- a database
- a command line interface (not sure how it can be used with docker)

despite the documentation, it's still horribly hard getting filebrowser up & running, and working which is actually pretty bonkers.

I'm wasting too much time on such a small component of a much greater project, and for this reason i'm dropping filebrowser. I think it's a shame, because this project seems to have so many good bits to it, but the interface its users have to interact with to get it up & running is just so god-awfully painful.

**Comment by maxlaverse** [comment]
Hi @shyal !
I have to disagree and I hope you won't mind me telling you this, but I don't find your issue very helpful. It sounds as if you just wanted to let the world know about your frustration.

I have only been using filebrowser for a year or two. My opinion is completely different from yours. In comparison to other software, I find this project quite easy to set up (as most of the Go-based ones): download the binary, write a config file, a systemd unit and you're basically done.

If you want to contribute to this project and give it a chance to reach your expectations, I highly recommend you to write proper issues for each of the points you mentioned, with your point of view of the current situation, the problems you are facing and eventually suggestions on how to improve it. I'm sure you're also very welcomed by the maintainer of the project to open pull-requests and propose changes.

Edit: And your title sounds very dramatic too. I'm sure you came across that issue before opening yours: https://github.com/filebrowser/filebrowser/issues/532

**Comment by hacdias** [comment]
Hello @shyal! I'm sorry from knowing that you feel that way.

> config flags that change across versions

That's why we released a major version. Anything can change on those. Please see https://semver.org/.

> a json file to configure, too (...) a command line interface (not sure how it can be used with docker)

We mainly kept/created those for automatic setups.

> a database

It's where we store the configurations. You don't need to touch it. It always existed.

> despite the documentation, it's still horribly hard getting filebrowser up & running, and working which is actually pretty bonkers.

Just run `filebrowser -r .`.

---

Also, as @maxlaverse (thanks!) said, if you want to contribute, you're free to do so. Please also read #532.

I'm also reopening #532.
