### ISSUE TITLE
为什么没有退出按钮（logout）

### ISSUE THREAD

**Issue by WHBLeer** [filebrowser/filebrowser#692]
2.0.3版本没有了退出按钮是什么情况，也没有登录页，分配账号有什么意义呢

**Comment by christronyxyocum** [comment]
There is no exit (logout) button in the version, and there is no login page. What is the meaning of assigning an account?

I am seeing the same issue. No login page, no logout button, just automatically browsing files.

**Comment by luchuanbaker** [comment]
你的设置不对吧

**Comment by hacdias** [comment]
You are using `noauth` method for some reason. Please see https://docs.filebrowser.xyz/configuration/authentication-method.
