### ISSUE TITLE
斐讯路由器k3不能使用！

### ISSUE THREAD

**Issue by shenzt68** [filebrowser/filebrowser#693]
bcm53xx: Add initial support for PHICOMM K3

Specification:

System-On-Chip: Broadcom BCM4709C0
CPU/Speed: 1400 MHz
Flash-Chip: MXIC MX30LF1G18AC or SAMSUNG K9F1G08U0D
Flash size: 128 MiB
RAM: 512 MiB
3xLAN speed: 10/100/1000Mpbs , 1xWAN speed: 10/100/1000Mbps
Wireless No1 (2T2R): BCM4366 4x4 MIMO 1000Mbps -- Skyworks SE2623L 2.4GHz Power Amplifier (x4)
Wireless No2 (2T2R): BCM4366 4x4 MIMO 2167Mbps -- RFMD RFPA5542 5GHz Power Amplifier Module (x4)
USB: 1x USB 3.0 port
1x LED, 1x reset button, 1x power switch

这个路由器不能运行filebrowser!

**Comment by eine** [comment]
Please, use one of the forms we provide: https://github.com/filebrowser/filebrowser/issues/new/choose

**Comment by niubility000** [comment]
Use  linux  arm v5 . To run it perfect, you need limit the number of image resize processors.
