### ISSUE TITLE
Syntax for removing rules doesn't make sense

### ISSUE THREAD

**Issue by nambrosch** [filebrowser/filebrowser#695]
**Problem**: Command line syntax for removing a rule seems redundant and/or not documented well:

Adding a rule is fine...
```
$ filebrowser rules add "(\.stfolder)$" --regex
Global Rules:

(0) Disallow Regex: 	(\.stfolder)$
```
Based on the help you'd think this would be correct:
```
$ filebrowser rules rm 0
Error: required flag(s) "index" not set
```
Maybe this:
```
$ filebrowser rules rm --index 0
Error: accepts between 1 and 2 arg(s), received 0
```
Okay, maybe add an equal sign?
```
$ filebrowser rules rm --index=0
Error: accepts between 1 and 2 arg(s), received 0
```
Specify index in two different ways?  Bingo!
```
$ filebrowser rules rm 0 --index 0
Global Rules:
```

**Proposed Solution**:  Assuming you're only removing one rule, don't require both <index> and --index or just get rid of --index entirely.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
