### ISSUE TITLE
Misleading documentation compared with the actual UI

### ISSUE THREAD

**Issue by davidpelayo** [filebrowser/filebrowser#696]
**Description**
The Frontend (and app) allows users to save commands before and after "save" actions. However, it's just used on "upload" (which works on saving file changes too).

**Expected behaviour**
- Either to remove the before and after save hooks.
- Or to explicitly separate save hooks from upload ones.

**What is happening instead?**
- When setting a command in after/before save, nothing happens (but works if you put it on the upload hooks collection).

**How to reproduce?**
1. Set a custom command within the after or before save hook.
2. Update any file content.
3. See that the command doesn't actually get executed.
4. Now move the command to the before/after upload hook.
5. See how it works successfully.

![before_save](https://user-images.githubusercontent.com/84540/54607473-b8cf2b00-4a4e-11e9-99ab-d89a41899cd9.gif)

**Comment by eine** [comment]
It seems that there are two possible bugs here:

- 'before save' and 'after save' hooks are not being properly triggered.
- 'before upload' and 'after upload' are being incorrectly triggered when a file is saved.

@davidpelayo, can you please check the browser log, and provide it along with the backend log? It would be useful to have them in text format or in static images.

**Comment by ghost** [comment]
I can confirm both bugs @1138-4EB mentioned.

`before upload` & `after upload` are triggered when I upload and when I save.
`before save` & `after save` are not triggered at all.

**Edit:** This is really confusing. The `before upload` & `after upload` events are triggered when uploading and when saving. According [to the documentation](https://filebrowser.xyz/configuration/command-runner) there is no `before save` and `after save`. But in the frontend the two events are listed. cc: @hacdias

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
