### ISSUE TITLE
Files direct link access

### ISSUE THREAD

**Issue by Tim608** [filebrowser/filebrowser#699]
Is it possible to get the direct file link for exemple http://exemple:8080/files/video.mp4
when sharing?

I got it working with

http://exemple:8080/api/raw/file.mp4/?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJsb2NhbGUiOiJlbiIsInZpZXdNb2RlIjoibGlzdCIsInBlcm0iOnsiYWRtaW4iOnRydWUsImV4ZWN1dGUiOnRydWUsImNyZWF0ZSI6dHJ1ZSwicmVuYW1lIjp0cnVlLCJtb2RpZnkiOnRydWUsImRlbGV0ZSI6dHJ1ZSwic2hhcmUiOnRydWUsImRvd25sb2FkIjp0cnVlfSwiY29tbWFuZHMiUDtdcCJsb2NrUGFzc3dvcmQiOmZhbHNlfSwiZXhwIjoxNTUzMjExMDI5LCJpYXQiOjE1NTMyMDM4MjksImlzcyI6IkZpbGUgQnJvd3NlciJ9.4a7BlzN7SLG8VqYVKn8NhKKQfzh_dCf3N7p85W7dW8Y&inline=true

But after some time the auth expire is it possible to disable the auth so the file is always available.

Thank You.

**Comment by ttys3** [comment]
your link will not work.
because JWT token has an expire field. 

but I think your idea is very good.

the default `Permanent Link` share will provide your a link, but not the `inline` one.

**Comment by hacdias** [comment]
Did you try getting a Permalink Link with `?inline=true` in the end? I thought it worked before.

Anyways, what you want is a direct link: you can get it, as @ttys3 said, through the sharing links feature.
