### ISSUE TITLE
Directory Pagination on Mobile

### ISSUE THREAD

**Issue by rhjmoore** [filebrowser/filebrowser#701]
**Description**
This is tightly linked to Directory Pagination issue #155.

This works wonderfully in Chrome on a desktop. On Chrome on Android, the infinite scroll doesn't work - it just comes to the end of the first set of file and goes no further.
If you go to copy a file into a folder with many folders, all of them list successfully. It's just the main pagination / infinite scrolling while browsing a large directory that doesn't work on mobile.

Do let me know if there's anything I can to help identify the issue.

**Expected behaviour**
The directory should do infinite scrolling on large directories like it does on desktop, but this doesn't work on mobile.

**What is happening instead?**
It just gets to the end of the first "page" and goes no further.

**How to reproduce?**
Visit a large directory on mobile, android, using Chrome.

**Comment by yeguixiong** [comment]
我也同样遇到这个问题，求解决办法

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
