### ISSUE TITLE
Unable to use recaptcha

### ISSUE THREAD

**Issue by RatherLogical** [filebrowser/filebrowser#702]
I have used the provided commands to set up recaptcha but when I run the command the config file is not updated. Any other commands I run seem to be working fine.

I ran `filebrowser config set --recaptcha.key xxx --recaptcha.secret xxx`

And when it displayed the new config it said 

![image](https://user-images.githubusercontent.com/39105734/54874586-bf4e0180-4dc4-11e9-9a08-18f6d55f2e46.png)

I am also not sure how to modify a specific config file from the CLI. For example if I have a config file in /home/filebrowser/config.json how can I edit values for that specific cfg from the CLI?

**Comment by Jesfreric** [comment]
I have the same issue. Probably the path to a config.json file (with Recaptcha properties) has to be set, nevertheless I cannot estimate which values have to be set inside the config json.

**Comment by hacdias** [comment]
Sorry for taking so long. Please see https://github.com/filebrowser/filebrowser/issues/715. I added the known bug to the docs too!
