### ISSUE TITLE
Empty page after upgrade from 1.7.0

### ISSUE THREAD

**Issue by Platway** [filebrowser/filebrowser#703]
**Description**
I updated caddy, and accordingly FileBrowser upgraded from version 1.7.0 to the latest version shipped with Caddy 0.11.5. Then, when visiting the FileBrowser from a web browser, I got an empty home page (no matter how I refreshed it) until I cleared site data in the web browser. The same thing happened to Chrome for Windows/Android and Safari for iOS.

Yes, clearing the site data in the browser resolves the issue. But I can't expect every user to do so. They would think the site was no longer accessible.

**Expected behaviour**
Users can continue accessing FileBrowser normally after the upgrade.

**What is happening instead?**
Users got an empty home page.

**Additional context**
It is obvious that the home page was cached in the browser. And the cache can't be get rid of unless the user clears the browser's site data.

**How to reproduce?**
Just upgrade from version 1.7.0 and it would reproduce.

**Files**
Attached are the source files of the problematic home page, which were cached in the browser.
[src.zip](https://github.com/filebrowser/filebrowser/files/3011945/src.zip)

**Comment by Platway** [comment]
I finally figured out a workaround, adding the following line in Caddy's config block:

status 403 /api/auth/renew

**Comment by hacdias** [comment]
Unfortunately, we don't support Caddy anymore. Please see #723.
