### ISSUE TITLE
Option to run in docker as an user (file permissions)

### ISSUE THREAD

**Issue by zuidwijk** [filebrowser/filebrowser#704]
**Is your feature request related to a problem? Please describe.**
File and folder creations are with root as owner. I'd like to see that all files and folder creations are under a specific user. I run filebrowser as docker with the option:
```
    environment:
      - PUID=1000
      - PGID=1000
```

**Describe the solution you'd like**
I'm the only user on my system and everything I do is under my username. I'd like to see that every folder-/file creation is happening under my username.

**Describe alternatives you've considered**
Don't know any other alternative, except using midnight commander under CLI

**Additional context**
none

**Comment by maschhoff** [comment]
push, we need this too for unraid

**Comment by eine** [comment]
What is the limitation with the current implementation? What result do you get when you set `PUID`, `PGID`, or `user`? What would you expect instead?

**Comment by zuidwijk** [comment]
When I use the PUID and GUID both 1000 (my user and group ID) then nothing happens, it still makes folders as root.root (owner).

I'd like to see that everything is done with my username as owner.

**Comment by hacdias** [comment]
Well... as far as I know (correct me if I'm wrong), we can't set UIDs and GUIDs that don't exist inside the Docker container. You might be setting them, but since the user doesn't exist on that Docker image, they won't take any effect.


But, I just tried out on my mac the following command:

```
docker run --rm -v $(pwd):/srv -v $(pwd)/filebrowser.db:/database.db -p 8080:80 filebrowser/filebrowser
```

And the files created were under my host machine user so I'm a bit confused on what's going on. Which OS are you using? I, myself, am not a big user of Docker, so I'm not aware of all of these things.

**Comment by hdorio** [comment]
@hacdias 
> Well... as far as I know (correct me if I'm wrong), we can't set UIDs and GUIDs that don't exist inside the Docker container.

You can specify any UID/GUID (existing or not).
`docker run --user '1000:1000'`

But you can't specify a username that was not created inside the container beforehand.

> And the files created were under my host machine user so I'm a bit confused on what's going on.

It could be that you have installed the docker daemon with 'user namespace remapping' enabled.

**Comment by hdorio** [comment]
@zuidwijk 
What prevents you from using the `user` configuration option?
```
version: '3'
services:
  files:
    image: filebrowser/filebrowser:v2.0.12
    user: '1000:1000'
    expose:
      - 8080
```

**Comment by vitaliy-kuzmich** [comment]
@zuidwijk @maschhoff   https://github.com/browsefile/backend when I used  smb with filebrowser, I've added this feature, but now it seems it is not needed, when I've implemented webdav support. It works much more faster then SMB.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by HalianElf** [comment]
Can we reopen this now that it's not archived any more? I tried using the `user` field and it just kept restarting because it couldn't bind to port 80.

**Comment by Alek-Zywot** [comment]
> Can we reopen this now that it's not archived any more? I tried using the `user` field and it just kept restarting because it couldn't bind to port 80.

On Linux, non-root users are not able to bind to ports below 1024. In docker simply run on a different port. Im using 8080 and running as a non-root without issue. You can change the port in the config file or simply use the command `-p 8080` when starting your docker container.
