### ISSUE TITLE
Multiple Root Directories

### ISSUE THREAD

**Issue by clemone210** [filebrowser/filebrowser#705]
I would like to add a second root directory. Is it possible?

**Comment by zlm324** [comment]
you can create a new folder, assume to name A.
ln -s /first_root /A/first
ln -s /second_root /A/second
filebrowser -d /path/to/filebrowser.db -r /A

**Comment by hacdias** [comment]
Exactly as @zlm324 said. You can't have multiple root directories. That could be a feature request though. PRs are welcome!

**Comment by yeguixiong** [comment]
一楼所说的行不通，既然我想要第二个目录，那么我就想要第二个目录是跟第一个目录不同权限的。比如我想要用户a能访问和编辑文件夹1，用户b能访问和编辑文件夹2，用户a和用户b都能访问但不能编辑文件夹3。

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by XTeam-Wing** [comment]
Windows : C: D: E:
