### ISSUE TITLE
Upload Large Files on Docker Image

### ISSUE THREAD

**Issue by Annihil8ted** [filebrowser/filebrowser#706]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

I am trying to upload large files (20mb) to the docker image of filebrowser. This is being run from rancher 2.2.

**Expected behaviour**
What did you expect to happen?
File to be uploaded.

**What is happening instead?**
Please, give full error messages and/or log.

I see a pop up that says 413 Request Entity Too Large nginx/1.15.6.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

It occurs to me that this might due to rancher's proxy but wanted to check to make sure FileBrowser can handle large files.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Run Rancher 2.2 and load filebrowser. Than load big file.

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by Annihil8ted** [comment]
It was the Rancher proxy causing the issue. This is resolved now.

**Comment by hacdias** [comment]
Glad you solved it!

**Comment by pcrockett** [comment]
For anyone else with this problem, the nginx parameter that needs changing is [client_max_body_size][1]. Set it to zero to disable any limits on upload file size. Like so:

```
location / {
    client_max_body_size 0;
    proxy_pass http://backendserver:8080/;
}
```

[1]: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by portlandhodl** [comment]
Just to note this issue is caused with any Nginx based reverse proxy that is using a location with proxypass.

Adding this line  in the location of the proxypass that leads to your filebrowser docker container will resolve this issue.
`client_max_body_size 0;`
