### ISSUE TITLE
Unable to use the web page if no "-a [::]" in the command

### ISSUE THREAD

**Issue by KurohaneReko** [filebrowser/filebrowser#707]
**Description**
When I try to start the filebrowser (systemd), everything seems to be ok, but I can access the web ui(502 error), until I specify the address by using "-a [::]". In fact, my device has no IPv6 address.

**Expected behaviour**
Visit the ui successfully.

**What is happening instead?**
[root@VM_0_7_centos ~]# systemctl status filebrowser.service
● filebrowser.service - filebrowser
   Loaded: loaded (/usr/lib/systemd/system/filebrowser.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-04-05 02:43:02 CST; 9min ago
 Main PID: 16127 (filebrowser)
   CGroup: /system.slice/filebrowser.service
           └─16127 /usr/local/bin/filebrowser -r /root -p 915

Apr 05 02:43:02 VM_0_7_centos systemd[1]: Started filebrowser.
Apr 05 02:43:02 VM_0_7_centos systemd[1]: Starting filebrowser...
Apr 05 02:43:02 VM_0_7_centos filebrowser[16127]: 2019/04/05 02:43:02 No config file used
Apr 05 02:43:02 VM_0_7_centos filebrowser[16127]: 2019/04/05 02:43:02 Listening on 127.0.0.1:915

Then, a 502 error occured when I tried to visit http://ip:915

Everything ok when I use "filebrowser -r /root -a [::] -p 915"

**How to reproduce?**
This issue can be reproduced on centOS 7.2 & 7.5.

**Comment by nambrosch** [comment]
not sure if it will help, but here's what i'm using for a filebrowser.service on centos.  firewalld and selinux are not enabled on this host either.
```
[Unit]
Description="Filebrowser"
After=network.target httpd.service

[Service]
User=apache
Group=apache
ExecStartPre=/usr/local/bin/filebrowser-config.sh
ExecStart=/usr/local/bin/filebrowser --database /data/filebrowser/filebrowser.db
ProtectHome=true
ProtectSystem=full
WorkingDirectory=/data/filebrowser

[Install]
WantedBy=multi-user.target
```

**Comment by KurohaneReko** [comment]
> not sure if it will help, but here's what i'm using for a filebrowser.service on centos. firewalld and selinux are not enabled on this host either.
> 
> ```
> [Unit]
> Description="Filebrowser"
> After=network.target httpd.service
> 
> [Service]
> User=apache
> Group=apache
> ExecStartPre=/usr/local/bin/filebrowser-config.sh
> ExecStart=/usr/local/bin/filebrowser --database /data/filebrowser/filebrowser.db
> ProtectHome=true
> ProtectSystem=full
> WorkingDirectory=/data/filebrowser
> 
> [Install]
> WantedBy=multi-user.target
> ```

oh, I mean everything is OK if I replace the command in the filebrowser.service (using "-a [::]")
In fact, I can't use filebrowser using "filebrowser -r /root -p 915" and I'm sure Port 915 is available.

**Comment by nambrosch** [comment]
what outputs to console when you run filebrowser by hand (not via systemd)?

you're also binding to a privileged port... have you thought about running this as a non-root user on a port above 1024?

**Comment by KurohaneReko** [comment]
> what outputs to console when you run filebrowser by hand (not via systemd)?
> 
> you're also binding to a privileged port... have you thought about running this as a non-root user on a port above 1024?

Oh, ports above 1024(60128, etc.) also lead to 502
and the outputs
> [root@VM_0_7_centos ~]# filebrowser -r /root -a [::] -p 60128
> 2019/04/06 04:41:26 No config file used
> 2019/04/06 04:41:26 Listening on [::]:60128
> ^C
> [root@VM_0_7_centos ~]# filebrowser -r /root -a [::] -p 6128
> 2019/04/06 04:42:53 No config file used
> 2019/04/06 04:42:53 Listening on [::]:6128
> ^C
> [root@VM_0_7_centos ~]# filebrowser -r /root -p 6128
> 2019/04/06 04:44:30 No config file used
> 2019/04/06 04:44:30 Listening on 127.0.0.1:6128
> ^C

**Comment by hacdias** [comment]
502 is a bad gateway error. It doesn't seem to be caused by File Browser but from some proxy. Aren't you using any Firewall/web server/proxy in front of File Browser or your server?
