### ISSUE TITLE
how to uninstall filebrowser?

### ISSUE THREAD

**Issue by kiwiw** [filebrowser/filebrowser#709]
I installed filebrowser on centos by using "curl...", but i dont know how to remove it,
when i use "yum remove filebrowser", it shows "No Match for argument: filebrowser".

**Comment by givaha** [comment]
Filebrowser is installed in de directory **/usr/local/bin**. Just delete the filebrowser folder.

**Comment by hacdias** [comment]
Exactly as @GianniVanHavermaet!

**Comment by lsalazarm99** [comment]
Is this outdated? /usr/local/bin/filebrowser is not a directory. Where is the config file and database stored? I would like to delete them too.

**Comment by ramiresviana** [comment]
> Is this outdated? /usr/local/bin/filebrowser is not a directory. Where is the config file and database stored? I would like to delete them too.

FileBrowser installation script does not create directories, it just moves the `filebrowser` binary into `/usr/local/bin/` folder. CLI params control the database and config location, by default FileBrowser comes with no config file and will create the database file on the current working directory.
