### ISSUE TITLE
Command blocked when executing command with a Shell

### ISSUE THREAD

**Issue by hugomassing** [filebrowser/filebrowser#710]
**Description**
When I try to execute a command with a shell ("zsh -c") in my case, i have a message error `[INFO] Blocking Command: "zsh -c mycommand"`

**Expected behaviour**
Execute the command

**What is happening instead?**
i have a message error `[INFO] Blocking Command: "zsh -c mycommand"`

**Additional context**
I added zsh and my command to the list of commands but it's still not working. Also adding a command like `zsh` could bring some security issues? Because any user could execute a command on my server?

**Comment by hacdias** [comment]
That's an informational message, not an error. Isn't it working though? Yes, adding `zsh` as a valid command could be a security concern.

**Comment by vjp23** [comment]
Hi all, I'm also having issues with this. I get a 500 error, and my docker logs show:

```
2024/10/12 06:29:16 [INFO] Blocking Command: " /bin/sh -c 'if [[ "/srv/not_trash_test.txt" != "/srv/Trash/"* ]]; then mv /srv/not_trash_test.txt /srv/Trash; fi'"
2024/10/12 06:29:16 /not_trash_test.txt: 500 [my WAN IP] exec: no command
```

Do I need to, like, enable commands somewhere in the settings? I don't see anything in the docs about this but other issues suggest that maybe I do?

Thanks!
