### ISSUE TITLE
Add additional path to the $PATH environment variable for executing commands

### ISSUE THREAD

**Issue by mikelei8291** [filebrowser/filebrowser#712]
**Is your feature request related to a problem? Please describe.**
When executing some executables placed in the user space, for example: `/home/<username>/usr/bin/<executable>`, those executables won't be found by filebrowser, resulting errors like this:
`exec: "<executable>": executable file not found in $PATH`
Obviously, I can run the executable by using its full path, but it would be more convenient to add the path to the environment variable.

**Describe the solution you'd like**
Add an option to add additional path to the $PATH environment variable. For example:
```go
additionalPath := "/home/<username>/usr/bin"
os.Setenv("PATH", additionalPath + ":" + os.Getenv("PATH"))
```

**Comment by hacdias** [comment]
@mikelei8291 thanks for the feature request. I see you already have an idea for implementation and it actually looks good. PRs are welcome and really appreciated!! 😃

/cc @1138-4EB

**Comment by mikelei8291** [comment]
@hacdias Thanks for the reply, but in fact I haven't used Go before. The implementation that I came up with was totally based on some searching on the documentation of Go. I'm willing to help but I think it would be better to have someone more familiar with Go to contribute quality code to this repo.

**Comment by eine** [comment]
I am not sure about this. It is already possible to add additional paths to the PATH before starting filebrowser:

```
PATH=$PATH:my/custom/path filebrowser
```

What's the difference between this and the requested feature?

**Comment by mikelei8291** [comment]
@1138-4EB I'm talking about executing commands with the filebrowser, not executing the filebrowser itself.
As shown by this image in the ["feature"](https://docs.filebrowser.xyz/features) section of the documentation:

![Execute custom commands](https://raw.githubusercontent.com/filebrowser/docs/master/.gitbook/assets/5.PNG)

**Comment by eine** [comment]
Commands used inside filebrowser should use the same PATH as filebrowser itself. So, the solution I commented above should work for your use case.

**Comment by mikelei8291** [comment]
It works, thanks.
The problem is I didn't specify the $PATH in my systemd config file, so it was using the default value.
