### ISSUE TITLE
Not support Chinese file name online play?

### ISSUE THREAD

**Issue by LisonFan** [filebrowser/filebrowser#713]
I open an mp4 file with a Chinese file name.
Prompt to download on the page

![image](https://user-images.githubusercontent.com/9424775/56121359-86a7df00-5fa2-11e9-9bff-cfec6c6634cf.png)

**Comment by ifengchao** [comment]
可能是文件太大了。我试过不同的mp4文件，有的可以播放，有的不行。不知道为什么。

**Comment by hacdias** [comment]
Is the extension correct?

**Comment by LisonFan** [comment]
> 可能是文件太大了。我试过不同的mp4文件，有的可以播放，有的不行。不知道为什么。

有个两分钟几十兆的视频都不播不了

**Comment by LisonFan** [comment]
> Is the extension correct?

Yes, this extension is correct.
Do you need me to provide this video file?
But I need to inform in advance that this video file may have copyright issues.

**Comment by hacdias** [comment]
Could you just type here the complete name of the file? So I can try out renaming a different file to see if it works.

**Comment by LisonFan** [comment]
> Could you just type here the complete name of the file? So I can try out renaming a different file to see if it works.

"切尔诺贝利.剧情元素.Elements.of.Chernobyl.S01E01.中英字幕.WEBrip.720P-人人影视.mp4"
This is the file name of my video file.

**Comment by hacdias** [comment]
@LisonFan weird... it works here. We're using the first _n_ characters of a file to detect its file type and that perhaps could be some issue with the file instead. Could you try out any other MP4 files you have to see if they work? Is that the only one?

**Comment by LisonFan** [comment]
> @LisonFan weird... it works here. We're using the first _n_ characters of a file to detect its file type and that perhaps could be some issue with the file instead. Could you try out any other MP4 files you have to see if they work? Is that the only one?

It is not the only video file that cannot be played.
Is it possible that the problem is caused by transcoding?

**Comment by hacdias** [comment]
Hmm... it seems [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) does not detect it as a video file so we don't show it.

**Comment by LisonFan** [comment]
> @LisonFan weird... it works here. We're using the first _n_ characters of a file to detect its file type and that perhaps could be some issue with the file instead. Could you try out any other MP4 files you have to see if they work? Is that the only one?

I just tested it.
Convert this MP4 file to a new MP4/MKV file via transcoding software, it can be played online

**Comment by hacdias** [comment]
So, the conclusion is that there was some issue with the file. Shall we close this?

**Comment by LisonFan** [comment]
> So, the conclusion is that there was some issue with the file. Shall we close this?

Ok, this question may be a problem with the Go language?
Close this issue first.

**Comment by hacdias** [comment]
Most likely there was something _wrong_ with the file. Although I'm not the best person to tell it. You could try investigating a bit more: like creating a really small go program that outputs http.DetectContentType for that file and see what it shows.

**Comment by LisonFan** [comment]
> Most likely there was something _wrong_ with the file. Although I'm not the best person to tell it. You could try investigating a bit more: like creating a really small go program that outputs http.DetectContentType for that file and see what it shows.

Ok, I will try

**Comment by LisonFan** [comment]
> Most likely there was something _wrong_ with the file. Although I'm not the best person to tell it. You could try investigating a bit more: like creating a really small go program that outputs http.DetectContentType for that file and see what it shows.

![image](https://user-images.githubusercontent.com/9424775/57591603-d6a7a080-7564-11e9-9732-08dc903d6639.png)
I compared these two video files.
There is no type in the video file header in the image below.
So Go is recognized as application/octet-stream

**Comment by hacdias** [comment]
yeah, that must be the issue
