### ISSUE TITLE
Move function don't work to move a file to a Hard Drive

### ISSUE THREAD

**Issue by Benoit-Julien** [filebrowser/filebrowser#714]
I made this short video to show you my bug : https://youtu.be/T8d1Mgshx_4

Some specs :
- Ubuntu 18.04.2 LTS Server
- Caddy 0.11.4
- Hard drive partition type is NTFS

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
