### ISSUE TITLE
Need to set --auth.method to update auth settings

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#715]
**Description**

Trying to change the authentication settings.

**Expected behaviour**

I'd run:

```
filebrowser config set --recaptcha.key=key --recaptcha.secret=secret
```

And the configurations (if using the JSON Auth Method) would update correctly.

**What is happening instead?**

The configurations aren't changing.

**Additional context**

We need to set `--auth.method` every time we want to change the authentication settings. This applies to all types of authentication and not only `json`. Also, by setting this flag, we override the current auth configurations which might not be useful in some cases.

This will take some rework on the `config set` code to make this work. I'll update the documentation in the meanwhile so people know. If someone wants to take a stab at this bug, we'll all be greateful ❤️ 

**How to reproduce?**

Run the command above.

**Files**

N/A

**Comment by chummumm** [comment]
can I set recaptcha in config.json?

**Comment by hacdias** [comment]
@chummumm not right now

**Comment by Soneji** [comment]
@hacdias is there any update on whether we can set recaptcha in the config.json?
Thanks
