### ISSUE TITLE
Can't login in mobile phone.

### ISSUE THREAD

**Issue by Snowix** [filebrowser/filebrowser#717]
**Description**
It works well on my laptop, but it note wrong credentials when I'm about to login in in my mobile phone, and I'm sure I have entered the correct password.

**Comment by Snowix** [comment]
I changed phones and browsers, some of them can enter, some can not, yet I don't know the reason.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
