### ISSUE TITLE
Can't install via powershell on windows 10?

### ISSUE THREAD

**Issue by goldenpipes** [filebrowser/filebrowser#718]
**Description**
Trying to install 2.0.4 on windows 10 host via Powershell

**Expected behaviour**
filebrowser to install with no errors

**What is happening instead?**
```powershell
PS C:\fb> iwr -useb https://filebrowser.xyz/get.ps1 | iex
>> filebrowser -s c:\fb\
Downloading https://github.com/filebrowser/filebrowser/releases/download/v2.0.4/windows-amd64-filebrowser.zip
Extracting C:\Users\lewis\AppData\Local\Temp\tmp20DC.tmp.zip
Installing filebrowser on C:\Program Files\filebrowser
Removing the old version
Cleaning temporary files
Adding filemanager to the PATH
iex : A positional parameter cannot be found that accepts argument 'C:\Windows\system32;C:\Windows;C:\Windows\System32\
Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\filebrowser'.
At line:1 char:45
+ iwr -useb https://filebrowser.xyz/get.ps1 | iex
+                                             ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

filebrowser : The term 'filebrowser' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ filebrowser -s c:\fb\
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (filebrowser:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\fb>
```

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
run the install command:

```
iwr -useb https://filebrowser.xyz/get.ps1 | iex
filebrowser -s c:\fb
```

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by donaldr** [comment]
Weirdly, just retyping one of the lines in get.ps1 fixes this. I think there might be some strange non-printing characters involved. 

To fix:

Download get.ps1 like so:

`iwr https://filebrowser.xyz/get.ps1 -OutFile get.ps1`

Then modify get.ps1. Find the line:

`Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value "$path"`

Manually retype it and delete the old line. 

Run .\get.ps1

Voila.

**Comment by goldenpipes** [comment]
that did it! thanks!

**Comment by Zachar2** [comment]
The problem cause might be that the original script is missing quotation marks for "$path" in mentioned line.

**Comment by lzacharski** [comment]
The problem might be the original script missing a quotation marks for "$path" in the mentioned line.
