### ISSUE TITLE
loading loop when using reverse proxy [nginx]

### ISSUE THREAD

**Issue by pcs3rd** [filebrowser/filebrowser#719]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?
--------------------------
Host the filemanager application stand alone and using nginx to reverse proxy

**Expected behaviour**
---------------------------
Filemanager application should load

**What is happening instead?**
Please, give full error messages and/or log.
------------------------------------------

No error messages, the three loading dots are stuck in a loop. No errors made.

**Additional context**

Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
-----------------------------
Website [here](https://scrubbiest-burmese-3610.dataplicity.io/files/)
no errors are produced

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
---------------------
Setup nginx to foward host:port/filemanager
Setup filemanager to serve to localhost:sameport/filemanager
Try to access through apache2
wait forever.  

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.
---------
Nginx configuration, using same configuration as mentioned in another issue that says how to do what I want, but that is not working entirely

**Comment by hacdias** [comment]
Probably related to #669. Could you try again with the latest version?

**Comment by pcs3rd** [comment]
Currently, I am unable to access a device to do this with without rsking messing up my configuration.

**Comment by pcs3rd** [comment]
@hacdias 
Tested using automated install script and the following nginx (base) config:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        location / {
                proxy_pass http://localhost:8080/;
                proxy_set_header Host $http_host;
        }
}
```  
Now works as expected (use under nginx)

**Comment by pcs3rd** [comment]
@hacdias Turns out not working as expected.

**Comment by hacdias** [comment]
Did you try cleaning up the cache? If there were 301 Redirects they will persist unless you clean up the cache.

**Comment by pcs3rd** [comment]
Yea, I tried on a new incognito window

**Comment by hacdias** [comment]
Could you give me examples of redirections? CODE FROM TO?

**Comment by pcs3rd** [comment]
What do you mean? do you want my configuration? On my chromebook it works over localhost, but not on my raspi.

**Comment by Androkiller** [comment]
@pcs3rd I had the same issue with this when trying to setup subdomain reverse proxy. I gave FileBrowser a baseurl like this "/blahblah" not just "/". Then the proxy_pass wouldn't work with "/blahblah" but then it did with just "/"

This is the config I use and it works.

server{
        listen 80;
        listen [::]:80;
        server_name example.domain.com;
        return 301 https://$server_name$request_uri;
}

server{
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name example.domain.com;
        ssl on;
        ssl_certificate /etc/letsencrypt/live/example.domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.domain.com/privkey.pem;

        location /{
        client_max_body_size                    2048m;
        proxy_read_timeout                      86400s;
        proxy_send_timeout                      86400s;
        proxy_set_header                        X-Forwarded-Host $host;
        proxy_set_header                        X-Forwarded-Server $host;
        proxy_set_header                        X-Real-IP $remote_addr;
        proxy_set_header                        Host $host;
        proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version                      1.1;
        proxy_redirect                          off;
        proxy_set_header                        Upgrade $http_upgrade;
        proxy_set_header                        Connection "upgrade";
        proxy_pass                              http://10.10.10.10:8080/;
        }
}

you can ignore the ssl stuff and just listen on port 80
note the proxy pass is "/" but the base for FileBrowser is infact "/blahblah"

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
