### ISSUE TITLE
Compilation problem 

### ISSUE THREAD

**Issue by niceran** [filebrowser/filebrowser#720]
This program is very good, when to restore mips compilation?  A large number of mtk chip routing popularization urgently need to solve the compilation problem.

**Comment by carlsue** [comment]
clean ubuntu 18/19  with ram/vram 30G+
follow offical docs with GOOS  GOARCH
that's all

[filebrowser_v2.0.16_mipsle.zip](https://github.com/filebrowser/filebrowser/files/4004775/filebrowser_v2.0.16_mipsle.zip)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by carlsue** [comment]
here you are,mipsle version v2.11.0
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972830/filebrowser.zip)

**Comment by tg567** [comment]
> here you are,mipsle version v2.11.0
> [filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972830/filebrowser.zip)

how to cross compile mipsle version, teach me the env configure and the command pls.

**Comment by carlsue** [comment]
> > here you are,mipsle version v2.11.0
> > [filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972830/filebrowser.zip)
> 
> how to cross compile mipsle version, teach me the env configure and the command pls.

docker img
