### ISSUE TITLE
Goodbye Caddy (for now) 👋

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#723]
Hello everyone!

As most of you know, File Browser - well... File Manager at the time - was born as a single extension for [Caddy web server](https://caddyserver.com/). Although, it's time to tell goodbye to this lovely extension. There's a lot of backlog and thoughts about deprecating this extension for a long time already (#574).

There are some reasons why I'm taking this decision:

1. File Browser building process is complicated and supporting Caddy would involve a lot of extra necessary steps due to the nature of File Browser: we need static assets (HTML, JS, CSS, etc.) to work.
2. If you install them both separately, you can update only one of the binaries. It might seem a disadvantage for some, but I assure you that it can be helpful in some cases.
3. File Browser can be easily used with Caddy via the built-in [`proxy`](https://caddyserver.com/docs/proxy) directive.
4. I don't a lot of time to focus on this project to make it better and better, so supporting Caddy would be one more time sink for me (see #532).

I know not everyone will support this decision, but it's been on my head for a long time and this will simplify a lot of things in File Browser development side.

It's a goodbye to Caddy, for now. 👋

---

See https://docs.filebrowser.xyz/installation/caddy

**Comment by xor-gate** [comment]
@hacdias this is a very nice explanation, to bad its a little difficult to keep up. I was looking for an alternative for h5ai and filebrowser seems to fit. Thanks for all the effort you put in!
