### ISSUE TITLE
noauth错误代码403

### ISSUE THREAD

**Issue by lihao2019** [filebrowser/filebrowser#728]
hello
Now I am trying to use filebrowser as an intermediate plug-in to integrate into my program. The problem is that I need to skip the login page and directly enter. Now code 403 appears in the listening port
thank you

**Comment by hacdias** [comment]
Hey! Did you enable `noauth`?

```
filebrowser config set --auth.method=noauth
```

**Comment by lihao2019** [comment]
OK thanks

**Comment by hacdias** [comment]
Did it work?

**Comment by lihao2019** [comment]
The problem is now solved. thanks
