### ISSUE TITLE
Why are some packages in the code prefixed with v2, but the file path I cloned has no v2?

### ISSUE THREAD

**Issue by Rain722** [filebrowser/filebrowser#730]
**Description**
Why are some packages in the code prefixed with v2, but the file path I cloned has no v2?

**Comment by hacdias** [comment]
Hey @Rain722! That's related to Go Modules: by convention, when the version is above 1, we should add a `/v$number` to the name of package.

Id you want to know more, here's a good link https://github.com/golang/go/wiki/Modules.
