### ISSUE TITLE
The latest docker image can't be run.

### ISSUE THREAD

**Issue by ZvonimirSun** [filebrowser/filebrowser#733]
**Description**
I just ran `docker pull filebrowser/filebrowser` command to update the filebrowser image, and this image can not be run. The log says `standard_init_linux.go:207: exec user process caused "no such file or directory"`.

**Expected behaviour**

The filebrowser should be started without error.

**What is happening instead?**

It shows  `standard_init_linux.go:207: exec user process caused "no such file or directory"` and exited immediately.

**Additional context**

![image](https://user-images.githubusercontent.com/22871764/58045016-dcf4d880-7b73-11e9-8ef4-54b847281539.png)

![image](https://user-images.githubusercontent.com/22871764/58045192-542a6c80-7b74-11e9-91ce-5bdbdca388c7.png)

**How to reproduce?**

Just run the simplest command to run it. My environment is ubuntu 18.04.

**Comment by hacdias** [comment]
Fixed! Sorry!
