### ISSUE TITLE
Does it make sense to keep frontend repo separated?

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#735]
Some time ago we decided to separate the frontend code from the main repository where the backend resides. Although it also makes the build process slightly more complicated: not much! We just need to tag multiple repositories and make sure the submodules are in sync.

At the time, we thought it would be nice to decouple them because it would open door to create new front-ends. But... does that make sense? File Browser is a product on its own and should evolve instead of getting split.

Re-merging both repositories doesn't cost much, simplifies a bit the build process and the docs. What do you think?

Prior work: https://github.com/filebrowser/filebrowser/issues/342

/cc @1138-4EB

**Comment by eine** [comment]
I think that it is still ok to keep it separated. But, as you wish.
