### ISSUE TITLE
New version is crashingv2.0.11

### ISSUE THREAD

**Issue by dream10201** [filebrowser/filebrowser#738]
**Expected behaviour**
What did you expect to happen?

**What is happening instead?**
2019/05/21 17:40:24 No config file used
panic: could not locate box "../frontend/dist"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(...)
        /go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:110
github.com/filebrowser/filebrowser/v2/http.getStaticHandlers(0x1074af0, 0x1170f80, 0x1060101, 0x53a30, 0xb5d144, 0x0)
        /home/circleci/project/http/static.go:87 +0x220
github.com/filebrowser/filebrowser/v2/http.NewHandler(0x1074af0, 0x1170f80, 0x73d1a8, 0x11881b0, 0x1171000, 0x107f1e0)
        /home/circleci/project/http/http.go:20 +0xe0
github.com/filebrowser/filebrowser/v2/cmd.glob..func12(0xb45280, 0x10748e0, 0x0, 0x2, 0x1, 0x1074af0)
        /home/circleci/project/cmd/root.go:133 +0x324
github.com/filebrowser/filebrowser/v2/cmd.python.func1(0xb45280, 0x10748e0, 0x0, 0x2)
        /home/circleci/project/cmd/utils.go:102 +0x1e0
github.com/spf13/cobra.(*Command).execute(0xb45280, 0x106c0e8, 0x2, 0x3, 0xb45280, 0x106c0e8)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x204
github.com/spf13/cobra.(*Command).ExecuteC(0xb45280, 0x1, 0x544628, 0xb4c710)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x22c
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/circleci/project/cmd/cmd.go:9 +0x24
main.main()
        /home/circleci/project/main.go:11 +0x28

**How to reproduce?**
Raspberry Pi 3b run

**Comment by dream10201** [comment]
Testing v2.0.10 is normal

**Comment by hacdias** [comment]
Sorry for this past troublesome days. V2.0.12 is out and fixed 😄
