### ISSUE TITLE
Filebrowser won't load when run on Raspberry Pi.

### ISSUE THREAD

**Issue by JohnJocoo** [filebrowser/filebrowser#743]
Hi, thanks for great software, I am using filebrowser on raspberry pi in standalone mode (no internet connection). As raspberry pi doesn't have independent clock device when turned off for a while and started again without an internet connection, it's inner clock will be late. This leads to quite interesting bug when filebrowser will never load in the web browser because of the following error:

```
Uncaught (in promise) Error: token expired
    at ne (app.3dc6a2a8.js:1)
    at app.3dc6a2a8.js:1
    at w (chunk-vendors.8da789cf.js:36)
    at Generator._invoke (chunk-vendors.8da789cf.js:36)
    at Generator.e.(:8080/anonymous function) [as next] (http://127.0.0.1:8080/static/js/chunk-vendors.8da789cf.js:36:47656)
    at s (chunk-vendors.8da789cf.js:7)
    at a (chunk-vendors.8da789cf.js:7)
```

As far as I understand filebrowser backend on login return token with expire timestamp with backend dateTime (that is late in case). Error happens in frontend/src/utils/auth.js:15. Issue is reproduced at least with starting out the box filebrowser with --noauth on machine with time late for a day (you should open web page from device with correct time).

I see such ways to fix issue: 
1) Transmit expire as duration instead of fixed timestamp (ex. 3600 sec from now) (preferable)
2) Do not perform authorization in --noauth mode at all

**Comment by hacdias** [comment]
Does it still happen?

**Comment by JohnJocoo** [comment]
I am on vacation now and sadly cannot update FB, let me check within a week.

**Comment by hacdias** [comment]
Ping @JohnJocoo

**Comment by JohnJocoo** [comment]
Sorry, I forgot for a while about this. I promise to check on latest today
evening.

ср, 7 авг. 2019 г., 10:39 Henrique Dias <notifications@github.com>:

**Comment by JohnJocoo** [comment]
So I can confirm it is still reproduced on latest filebrowser installed with https://filebrowser.xyz/get.sh.

    raspberrypi:~ $ filebrowser version
    File Browser v2.0.12/64d6d9e

    raspberrypi:~ $ timedatectl status
    Local time: Tue 2019-08-06 00:00:04 BST
    Universal time: Mon 2019-08-05 23:00:04 UTC

    laptop:~ $ date 
    7 aug 2019 22:50:38 (WEST)

Error in browser (file browser will never load):

    [Error] Unhandled Promise Rejection: Error: token expired
	dispatchException (chunk-vendors.37c31b02.js:36:48355)
	(анонимная функция) (chunk-vendors.37c31b02.js:36:45556)
	s (chunk-vendors.37c31b02.js:7:23882)
	c (chunk-vendors.37c31b02.js:7:24113)
	promiseReactionJob

**Comment by JohnJocoo** [comment]
How is it going @hacdias

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
