### ISSUE TITLE
Quick access list to commands

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#744]
This issue is split from #302.

I think it'd be useful to let admins and/or users add a list of common or quick commands. Pretty simple from the UX:

- Just a dropdown/dialog with a text box, and add button, and a list. It can be opened with a button or a keyboard shortcut (e.g. `Alt+Return`).
- Double clicking an item or writing the name of some identifier and pressing return executes it.
- A button allows to edit each of them. Another one deletes them.

This is partially done with predefined 'hook' commands, but it is quite limited. It is also similar to filebrowser/filebrowser#127. However, I feel that a button for each command is not as clear as having a quick-to-show dialog containing a short id, the full command and (optional) a description.

Ideally commands in the list would be shown in a tree view, to allow grouping them for certain projects/tasks. But I think that this would unnecessarily make the first implementation more complex.

>[hacdias](https://github.com/hacdias/filemanager/issues/302#issuecomment-354128743)
> It would be interesting. Wouldn't you like to develop it?

Yes. I'd like to. No ETA, tho, as I have never used Vue.js.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
