### ISSUE TITLE
Direct download link

### ISSUE THREAD

**Issue by freedomlang** [filebrowser/filebrowser#745]
Is there a wat to get the direct download link of selected file?

**Comment by kmickeletto** [comment]
Does not seem to work for me.

Creating a share link gives me this...
https://filebrowser.mickeletto.com/share/V8kmDiIz

However, changing it to
https://filebrowser.mickeletto.com/dl/V8kmDiIz
simply gives an error stating This location can't be reached.

**Comment by vitaliy-kuzmich** [comment]
@freedomlang if you want to stream video, or something, I have possibility to download m3u as a playlist, or make external share, then you can send that link with external share, and it will be viewed like usual page, and authorized as guest, so only user with link would see that files. https://github.com/browsefile/backend

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
