### ISSUE TITLE
drag & drop does not work in firefox

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#746]
drag a file into a folder works on Chrome, but not Firefox (Nightly, not sure about stable Firefox)

**Comment by hacdias** [comment]
Can reproduce on Firefox Developer Edition too. Just a note: its only drag & drop from the interface. Drag & drop from the OS to upload works well.

**Comment by vitaliy-kuzmich** [comment]
can't upload from chromium, but it worked before, it seems browser issue, because POST request missed filename.

**Comment by princemaple** [comment]
it actually works on Firefox now. I'm going to close this one. If it continues to have problem on Chromium, you might want to open a new issue.

**Comment by n2j3** [comment]
doesn't work w/ FF 70.0.1 in windows 8 64bit. 
![image](https://user-images.githubusercontent.com/93463/69712893-3c780600-110c-11ea-87d1-0eb6fd98bc34.png)

**Comment by princemaple** [comment]
Windows 8? probably time to upgrade.

Drag and drop files into the filebrowser has always worked for me.
The d&d I mentioned that didn't work was regarding dragging files into a folder, i.e. reorganizing files. Now it works for me, in addition to d&d from explorer into FF. Win10 FF nightly.
