### ISSUE TITLE
Support one-click mode

### ISSUE THREAD

**Issue by zhentianxincun** [filebrowser/filebrowser#748]
Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Caddy 0.10.12+http.filemanager 1.7

What did you expect to see?
Can you provide one-click mode? 
That is more consistent with the way you browse web.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
