### ISSUE TITLE
Workaround for videos that can't stream in browser

### ISSUE THREAD

**Issue by francislavoie** [filebrowser/filebrowser#749]
Some videos (mostly .mkv) don't stream correctly in browsers because of missing audio codecs. Often in Chrome, the video will play, but no audio.

Normally, I'd just download the video, but that isn't the best option if the video file is huge and you just want to watch it _right now_ 😄 

My thought would be to have an option in the UI somewhere to make a URL for streaming in VLC (maybe in the File information modal?). VLC supports network streaming, so it should be a fix for the codec issue.

First problem is that if auth is enabled, VLC gets 403s when trying to load the video, obviously.

To get around auth, maybe a session token for the video can be generated and appended to the URL that would skip auth for that request?

**Comment by eine** [comment]
@francislavoie, it seems that xfrr/goffmpeg is just a wrapper, so ffmpeg must be installed in the host. Since docker images are based on `scratch`, we would need either a statically compiled version of ffmpeg or change the base image. Zipping is a different issue, because it is done without any external dependency: https://github.com/mholt/archiver.

I think that using a proper media player, such as VLC, is preferred to adding any heavy dependency (because of either the size or the workload). So, it'd be interesting to have that supported with authentication.

**Comment by zoidy** [comment]
I would also like this functionality. I don't know how to modify the source code so I made a simple userscript to stream the file using VLC. 

The script adds a button to the UI and downloads an M3U playlist which, when opened in VLC, will stream the file. It works with and without authentication enabled in Filebrowser. I've been using it for a while and decided to clean it up a bit and release it.  https://github.com/zoidy/filebrowser-streamlink/

**Comment by francislavoie** [comment]
That's awesome! Thanks for setting that up! @hacdias since that's pure JS, any chance this could be added quickly?

**Comment by vitaliy-kuzmich** [comment]
@francislavoie @zoidy  hey, if your pc runs linux, you can use this : https://github.com/browsefile/backend, and download media files like m3u playlist.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by shalva97** [comment]
> I'm closing this since this repository will be archived.

Is it still going to be archived? there is no such information in README

Anyway, I was interested if there are any updates to the issue?

**Comment by francislavoie** [comment]
The repo was archived then later revived.

**Comment by shalva97** [comment]
> The repo was archived then later revived.

Can this issue be reopened? I could also create another issue if it can't be reopened. I will be happy if it gets implemented.
