### ISSUE TITLE
Add custom context menu (rename, delete, etc.)

### ISSUE THREAD

**Issue by zxysilent** [filebrowser/filebrowser#752]
Add right mouse button eg Rename、Delete etc

**Comment by vitaliy-kuzmich** [comment]
@zxysilent https://github.com/browsefile/backend has it

**Comment by zxysilent** [comment]
> @zxysilenthttps://github.com/browsefile/backend拥有它

thinks

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
