### ISSUE TITLE
Autoplay musics and videos

### ISSUE THREAD

**Issue by rigon** [filebrowser/filebrowser#754]
It would be very nice if Filemanager autoplays musics and videos when they are opened.
I also suggest to jump to the next file when a music (possibly, also videos) ends.

---

- [x] Autoplay
- [ ] Jump to the next file.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by tenorok** [comment]
Hey! Is this feature realised?
I can't understand how to setup autoplay for next video file in the list.
