### ISSUE TITLE
reCAPTCHA not working

### ISSUE THREAD

**Issue by Soys** [filebrowser/filebrowser#758]
When I login filebrowser with recaptcha,filebrowser alert me Username or password incorrect.I make sure my username and password is right.
![pic](https://user-images.githubusercontent.com/8133994/58091055-3e13bf00-7bfb-11e9-8db7-390500fbe9b5.png)
When I remove reCaptcha,filebrowser is login successfully.Is reCaptcha problem?

And,is filebrowser unsupport custom css now?

**Comment by Jesfreric** [comment]
The same with me!

**Comment by Jesfreric** [comment]
Any news about the implementation? :-)

**Comment by Sgouws** [comment]
Has anyone figured out a workaround here?

**Comment by chihangc** [comment]
same

**Comment by Jesfreric** [comment]
Hi guys. Any news about implementation?
