### ISSUE TITLE
Search for hash

### ISSUE THREAD

**Issue by frankie-mceyes** [filebrowser/filebrowser#760]
I work in a scenario when files have to be traced and recognized even with different filenames. The only way to check this is with hashes.
I know that in the "info" of the file there's a hashes section, but i am not able to **search** for hash.

Would it be possible to implement a hash search query?

May i suggest something like:
_md5:d41d8cd98f00b204e9800998ecf8427e_
_sha1:da39a3ee5e6b4b0d3255bfef95601890afd80709_
and so on...

**Comment by hacdias** [comment]
I wonder how costly that would be. To search for ab hash, we'd need to hash every file while looking for it... Unless we perhaps stored the hashes somehow and detected when a file changed... hmm

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
