### ISSUE TITLE
No Able to Play Video Online

### ISSUE THREAD

**Issue by novicewu** [filebrowser/filebrowser#762]
Isn't filebrowser able to play vedio/audio any more?
I installed filebrowser v2.0.12, and uploaded some mp4, but I found there's no way to play it online. When I clicked the file, it will download it automatically. Could anybody help me on that?

<img width="1262" alt="Screen Shot 2019-05-25 at 19 55 12" src="https://user-images.githubusercontent.com/8786994/58369005-47689880-7f27-11e9-918e-3250c3de2a41.png">

**Comment by hacdias** [comment]
Does it only happen with that video file or all video files?

**Comment by novicewu** [comment]
@hacdias, thanks for reminding. I double checked and found it only happens to this file. Some other .mp4 file can be played. Maybe it's due to decoding issue.

Another question I have is how to play the video with .srt subtitle? I put the srt same name with mp4 in the same folder, but it's not working.

**Comment by hacdias** [comment]
@novicewu browsers don't support `.srt` subtitles format natively. You should use `.vtt`.

**Comment by novicewu** [comment]
@hacdias got it. Then how do I play the video with vtt? I placed it in the folder same as mp4, it still not working.

**Comment by hacdias** [comment]
@novicewu weird... which browser are you using? It should show a subtitles menu on the video player..

**Comment by novicewu** [comment]
@hacdias I'm using Google Chrome v74 on MacBook. There's "download" and "picture in picture" in the menu, but no subtitles, as the attached.

<img width="1065" alt="Screen Shot 2019-05-28 at 20 13 46" src="https://user-images.githubusercontent.com/8786994/58477099-5187d280-8185-11e9-8193-ab26580e090c.png">

<img width="1040" alt="Screen Shot 2019-05-28 at 20 16 39" src="https://user-images.githubusercontent.com/8786994/58477208-97449b00-8185-11e9-9bcc-942c0fdb080e.png">

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
