### ISSUE TITLE
Some .mp4 files can't be read

### ISSUE THREAD

**Issue by Creling** [filebrowser/filebrowser#763]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

- when I open a .mp4 file, the filebrowser shows `This location can't be reached.`, and if I just change the suffix  to .mkv, the video works well

**What is happening instead?**
Please, give full error messages and/or log.

- no error logs was add to the log file

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

![mp4](https://user-images.githubusercontent.com/43109504/58378422-286d1380-7fc6-11e9-8968-4ce6e7ffa688.png)

![图片](https://user-images.githubusercontent.com/43109504/58378436-6833fb00-7fc6-11e9-9e6c-b8050b7e8a5c.png)

**Comment by hacdias** [comment]
@Creling there have been issues with some `.mp4` files recently (see #564, #565 and #713). As we can see on https://github.com/filebrowser/filebrowser/issues/713#issuecomment-491651321, the issues seems to lie on the file itself because they don't seem to contain the correct file type on their magic bytes. I'll mark this as bug, because it's been an error that's happening more and more so we can see what we can do.

**Comment by hacdias** [comment]
Note to self: https://github.com/h2non/filetype

**Comment by Creling** [comment]
To tell the truth, Maybe there is no need to recongnize files via magic bytes, I think the suffix is enough.

We all know the files we are uploading and we are able to name the suffix correctly. No one will deliberately use a no-suffix file or an error suffix file.

**Comment by Creling** [comment]
Add:
I found some other problems with  MP4 files, not sure if it was caused by the same cause.
1. Cannot rename:
- ![image](https://i.rwx.rw/images/7221c808c6c9c656809da7f98c552e95.gif)
2. Cannot download:
- ![](https://i.rwx.rw/images/25e4fef5901273cabd742e42a3c51a0b.gif)
3. Cannot move:

the permission is the same as the mkv file:
![](https://i.rwx.rw/images/044e808a3c8613f1cbec5d6cd094989f.png)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
