### ISSUE TITLE
rice embed-go error

### ISSUE THREAD

**Issue by lanux** [filebrowser/filebrowser#769]
$ ./wizard.sh  -c
error reading package: go/build: importGo filebrowser/http: exit status 1
can't load package: package filebrowser/http: unknown import path "filebrowser/http": cannot find module providing package filebrowser/http

**Comment by lanux** [comment]
edit script file "wizard.sh"
eg.
rice embed-go -i "github.com/filebrowser/filebrowser/v2/http"

**Comment by richguo0615** [comment]
eg.
cd http
rice embed-go -i .
