### ISSUE TITLE
Hugo Plugin - Next Moves

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#77]
This issue contemplates the next moves on caddy-hugo plugin. The list bellow shows what am I going to do next, and after that, there is a bigger explanation for each item.

- [ ] Theme picker
- [x] Website preview
- [x] Image, audio and video preview.
- [x] Add support for multiple hugo sites within the same site.

### Image, audio and video preview

~~This one is very obvious. The same way we can click on a file on Browse to edit it, we could do the same to preview images/audio and video.~~

**Edit:** this is part of the integration with File Manager plugin.
### Page/post preview mode

~~This page preview mode would replace the current "preview" button that exists on the Edit screen. After clicking on "Preview", the plugin would generate the site in a temporary path. That temporary path would be served at, for example, `/admin/preview/`, and you would be able to preview your page with your theme, styles, css and so on. Then, after closing the tab/window, the plugin would delete the temporary folder.~~

**Comment by brasilikum** [comment]
Thoughts on the Preview:
I think generally iframes are an an ugly thing, but maybe an iframe would provide a "real time preview" next to the editor, where the content would be regenerated on 2 seconds of not-typing. What do you think?

**Comment by hacdias** [comment]
Hey @brasilikum 

I agree with you on one thing: I think generally iframes are an ugly thing. Even in this case. The most similar thing I think that would work would be the `temp` directory regenerating himself after those 2 seconds of not-typing and showing up a kind of a popup asking to go to `temp` dir. 

I don't really know what is the best approach here. Do you have any other idea besides the iframe?

**Comment by brasilikum** [comment]
Maybe just tell users to open temp in a separate window and put it on the right from the editor. 

Auto recompile should still be a thing in my opinion. 

Am 22. Juni 2016 23:01:51 MESZ, schrieb Henrique Dias notifications@github.com:

> Hey @brasilikum 
> 
> I agree with you on one thing: I think generally iframes are an ugly
> thing. Even in this case. The most similar thing I think that would
> work would be the `temp` directory regenerating himself after those
> 2 seconds of not-typing and showing up a kind of a popup asking to go
> to `temp` dir. 
> 
> I don't really know what is the best approach here. Do you have any
> other idea besides the iframe?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/hacdias/caddy-hugo/issues/77#issuecomment-227875380

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by hacdias** [comment]
Yup, I agree with you in the auto recompile thing. I just don't like the
iframe. But we'll find a way! :D

**Comment by fghhfg** [comment]
add a drop-n-drag feature on image

**Comment by F0rth** [comment]
A wysiwyg button to switch between raw mardown or wysiwyg editor like Pen http://sofish.github.io/pen/ .

**Comment by F0rth** [comment]
A theme chooser / picker to download / apply / update new themes.

**Comment by fedelibre** [comment]
I read:

> This page preview mode would replace the current "preview" button that exists on the Edit screen.

I cannot find any *"preview" button* on the Edit screen.
The edit screen is the page where I can edit a markdown file?

I'm using Caddy 0.10.6

**Comment by hacdias** [comment]
Hey @fedelibre! Sorry, but the functionality is unavailable for now. This issue was referring an older version. I'll update this. Although, I'll create a preview mode soon for the whole website.

**Comment by jmcclelland** [comment]
Thanks for the amazing project! I'm interested in using the software to help users edit their hugo sites after I build them. Toward that goal, I'm mostly interested in features targeting non-technical users. 

In particular - having buttons along the top of the editor page on markdown pages for bold, italics, links, image, etc. would be particularly useful for people who don't remember markdown syntax. No need for WYSIWYG - just buttons that will insert the right markdown characters.

Is that consistent with your vision of the project?

**Comment by YLaido** [comment]
Thanks for the great project :) But I am a little bit confused: the preview of a .mkv file appears to be soundless. Is that normal? BTW is it possible for me to customize the html5 player?
