### ISSUE TITLE
Cannot Create From docker-compose.yml

### ISSUE THREAD

**Issue by gzye** [filebrowser/filebrowser#770]
**Description**
Hi there, I think I'm doing something that is obviously wrong, but I can't see it and I've been cracking on with it for a couple of hours to no avail.

**Expected behaviour**
I am trying to build an image, using the Dockerfile located in the repo, along with a slightly modified configuration file (added the reCaptcha) and then run it using a docker-compose.yml file.

**What is happening instead?**
The image appears to build correctly with no issue, apart from the usual when building on a Windows machine:

`SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.`

But when I attempt to run the docker-compose.yml, I get the following:

`ERROR: for filebrowser  Cannot start service filebrowser: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/filebrowser\": permission denied": unknown`

**Additional context**
I'm not sure if it is due to building on a Windows machine, or whether it is something else wrong that I am doing.

**How to reproduce?**
The docker-compose file that I am using is the following:

` version: "3"
services:
  filebrowser:
    image: filebrowser:local
    networks:
      - filebrowser_net
    ports:
      - "80:80"
    volumes:
      - filebrowser_root:/srv
      - filebrowser_db:/database.db

volumes:
  filebrowser_root:
    external: true
  filebrowser_db:
    external: true
networks:
  filebrowser_net:
`

**Comment by barigorokarl** [comment]
Hi,

do you have the linux or the windows binary installed? You'll have to use the linux one.

I assume you're using the original Dockerfile to create the image. Going on from there I would change the mounts to:

```
volumes:
  - filebrowser.db:/filebrowser.db
  - .filebrowser.json:/.filebrowser.json
```

Important are the names. The Docker example in the documentation says something about a database.db. I missed that and worked for hours only to discover that that was the wrong name.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
