### ISSUE TITLE
user creation in /login not making user_dir and setting scope

### ISSUE THREAD

**Issue by braddevans** [filebrowser/filebrowser#772]
**Description**
create user in /login does not create user dir and set the scope to that dir

**Expected behaviour**
i expected it to create the user dir and set the scope like in `/settings/users` new

**What is happening instead?**
it set the user scope to `./` showing the root filesystem

**Additional context**
https://youtu.be/Y2hQs1RpmPc

**How to reproduce?**
https://youtu.be/Y2hQs1RpmPc
unlisted youtube video of issue 

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by ttys3** [comment]
hi, I've made this PR: https://github.com/filebrowser/filebrowser/pull/788
hope it will be helpul
