### ISSUE TITLE
Python Linting and Syntax Highlighting

### ISSUE THREAD

**Issue by PythonLinks** [filebrowser/filebrowser#774]
First thank you for an excellent package.  I just fired up a docker container.  It does what I need. 

But I want more.  Since the maintainers are not actively developing it, this is more a statement of what I hope to add to it eventually.  Is anyone else interested in this?

**Describe the solution you'd like**
I would like syntax highlighting and checking in the browser.  

The Ace editor does syntax highlighting. 

 There are some Python tools that do linting.   Now there is Pyodide, which is cPython compiled to WebAssembly and running in the browser.   So I can go ahead and add Pyodide and pylint, and with every keystroke get feedback on the linting of the python file.

**Comment by PythonLinks** [comment]
Here is the link to the ace editor. 
https://ace.c9.io/build/kitchen-sink.html

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
