### ISSUE TITLE
config.json设置失效

### ISSUE THREAD

**Issue by chummumm** [filebrowser/filebrowser#778]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?
能不能给一份config.json的示例呢？我在设置了"auth.method": "noauth"之后还是需要登录密码
**Expected behaviour**
What did you expect to happen?

**What is happening instead?**
Please, give full error messages and/or log.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by 467815891a** [comment]
我的理解是这样的，导出的配置文件并不会在启动时被应用，启动时还是从数据库读取配置的，总之不要太依赖配置文件。
方法一：
先导入配置
./filebrowser config import config.json
然后启动
方法二：
启动时加flag --noauth

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
