### ISSUE TITLE
support multi-way to open file

### ISSUE THREAD

**Issue by tskdsb** [filebrowser/filebrowser#781]
**Is your feature request related to a problem? Please describe.**
https://github.com/filebrowser/filebrowser/issues/553

**Describe the solution you'd like**
when you select a file by left-click, you have 4 buttons:
- edit(same as double-click)
- open in browser(depend on browser, such as .mp4, .html)
- open raw(view raw text,like`raw.githubusercontent.com`, or bytes content)
- download(supported)

**Comment by tskdsb** [comment]
I prefer the `double-click` will do `open in browser` instead of `edit`

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
