### ISSUE TITLE
files cut

### ISSUE THREAD

**Issue by chummumm** [filebrowser/filebrowser#783]
**Is your feature request related to a problem? Please describe.**
Add a clear and concise description of what the problem is. E.g. *I'm always frustrated when [...]*
I use cloudflare's cdn but it can upload less than 100m
**Describe the solution you'd like**
Add a clear and concise description of what you want to happen.
I want filebrowser can cut files automaticly.

**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
