### ISSUE TITLE
我用nginx代理后无法正常执行命令

### ISSUE THREAD

**Issue by LIU-LIU-LIU** [filebrowser/filebrowser#790]
这里是我的nginx配置
![nginx代理fileweb](https://user-images.githubusercontent.com/34854930/59910066-b3b1bb80-9443-11e9-969b-d79c89afa63d.png)

当我使用代理访问filebrowser 无法执行shell命令
![无法执行命令报错](https://user-images.githubusercontent.com/34854930/59910121-d9d75b80-9443-11e9-84ed-bef71d2e2ae2.png)
![filesweb无法执行6](https://user-images.githubusercontent.com/34854930/59910131-de037900-9443-11e9-84d5-c0b0d9cdf1ba.png)

用户可执行配置里也设置了
".*"

**Comment by RedLicorice** [comment]
You have to add 
`		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";`
to your NGINX proxy configuration (right below proxy_pass). That's what worked for me!

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
