### ISSUE TITLE
choosing a folder with zip format to download, and I got its parent folder

### ISSUE THREAD

**Issue by starP-W** [filebrowser/filebrowser#793]
**Description**
>A clear and concise description of what the issue is about. What are you trying to do?

A folder in another folder, I want to download the folder with zip format.

**Expected behaviour**
>What did you expect to happen?

when the zipfile is downloaded, I can decompress it and get the folder which  I chose to download

**What is happening instead?**
>Please, give full error messages and/or log.

I decompress the downloaded zipfile, then I got the parent folder of the target folder, the target folder is in the parent folder.

**Additional context**
>Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

for example, i have a folder named A, and another folder named B is in the A ( path: [home]/A/B ). I chosed B with zip format to download. after download finished, I got B.zip, however, after I decompressed the B.zip, I got folder A, and the folder B is in the folder A ( path: [download_folder]/A/B ).

**How to reproduce?**
>Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

create a folder in the home folder, open the new folder and create another new folder in it, then download the folder.

**Files**
>A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by ttys3** [comment]
I've found this problem too.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
