### ISSUE TITLE
Unable to login with default credentials using Docker

### ISSUE THREAD

**Issue by kevle1** [filebrowser/filebrowser#795]
**Description**
I launch the container, I am able to get to the web interface login. However when i enter `admin` and `admin` for the username and password, it keeps saying "Wrong credentials". I have verified I have entered it correctly, but I cannot login. 

**Expected behaviour**
Login.

**What is happening instead?**
Does not accept default credentials. 

**Additional context**
![image](https://user-images.githubusercontent.com/36955177/60175507-5c965700-9846-11e9-89b2-dd66ccb32837.png)

I believe it relates to my configuration. I am using Docker for OpenMediaVault (Debian). 

I have mounted `database.db` and `.filebrowser.json` but it simply does not work. 

```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```

**How to reproduce?**
Unsure.

**Comment by Androkiller** [comment]
create yourself an admin user account through the cli and then login

**Comment by 7polo** [comment]
I also has the same trouble!
I solved it by updating my centos system datetime
[a blog， you can try it](https://blog.csdn.net/qq_20989105/article/details/86253380)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
