### ISSUE TITLE
Uneeded extra fields added to Front Matter

### ISSUE THREAD

**Issue by chesedo** [filebrowser/filebrowser#80]
There seems to be a bug were extra fields are added to the Front Matter of content by itself (and causing issues with some content)
## Steps to reproduce
1. Create a new content item... say `test.md`.
2. Save this item (reloading the page shows that its Front Matter is correct).
3. Create another content item... `test2.md`.
4. Add a Front Matter field to this item and save it.
5. Go to the first item (note Front Matter is still correct).
6. Without editing anything, just save it.
7. Reload the page to find the Front Matter from `test2.md` was added automatically.
8. Go to site settings and again just save it.
9. Go to one of the test contents and save it again.
10. Reload to find the fields from settings in the Front Matter.
## Issues it creates

Lets say a content item has a `type` for it to use a specific type or a `menu` field. Then going to an item that should not have the `type` or `menu` and editing it results it those fields being added to it (with no way of removing it unless if caddy is restarted)

So I guess some form of the previous data is kept in memory and then gets merged with future data.

**Comment by hacdias** [comment]
Hey @chesedo!

Thanks for reporting this. I had already noticed this problem and it will be fixed ASAP. I'm working in a major update for caddy-hugo and this will be fixed then ;)

I hope when the version 0.9 of Caddy is officially released, the new version of this plugin will also be released.

Thanks again. I'll leave this issue open until I have the confirmation that it is fixed!

**Comment by chesedo** [comment]
@hacdias great :smiley: .

I will be using caddy-hugo quite a bit in the next few days so will also create some others bugs (that you will probably know about)

**Comment by hacdias** [comment]
Sure, I'll be waiting for them ;)

**Comment by hacdias** [comment]
I've checked and it's fixed. ;)

**Comment by chesedo** [comment]
Awesome, I take it that the fix is in the upcoming new release (for Caddy v0.9)?

**Comment by hacdias** [comment]
Yup.
