### ISSUE TITLE
In Windows7 and Server2008, Unable to be access “by local area network” , but 127.0.0.1 is working well

### ISSUE THREAD

**Issue by PointPointChen** [filebrowser/filebrowser#804]
**Description**
filebrowser is used to share files among diffierernt computers in local area network.
if my computer's address is 192.168.1.10. linstening port is 8088

**Expected behaviour**
(1)when linstening address is configure to 0.0.0.0, then 127.0.0.1:8088 and 192.168.1.10:8088 should be work well.
(2)when linstening address is configure to 192.168.1.10, then 192.168.1.10:8088 should be work well.

**What is happening instead?**
but Only 127.0.0.1:8088 is working well. 
192.168.1.10:8088 cann't working , the page is remain "three dack Pioint', but the cann't popup the "login page" 

**Additional context**
none.

**How to reproduce?**
Please help me, Thanks.

**Files**
none.

**Comment by ttys3** [comment]
please read the doc and command line message **more carefully**
if you ever do `./filebrowser -h` and see below help message,
```
 -a, --address string    address to listen on (default "127.0.0.1")
```
I think this issue should not happened here.

if you'd like to listen on all interfaces, you should specific a paramater like this:
`-a 0.0.0.0`

**Comment by PointPointChen** [comment]
ttyS3, thank you for your reply, But I still have question.
I think you use filebrowser in Linux, it do work in linux.
But when using in windows OS, what ever "filebrowser -a 0.0.0.0" and "filebrowser -a 192.168.1.10", http://192.168.1.10:8088 can't work.
And I find when "http://127.0.0.1:8088" is working well, filebrowser's output log is " /api/renew: 403 127.0.0.1:5758<nil>".   But under the non-working situation, filebrowser has no log.
Please continue to reply, thanks.

**Comment by PointPointChen** [comment]
Thanks very much.
I have fnd question. It's Web browser compatibility. 
filebrowser can be accessed by firefox and chrome, but can't be access by IE of Microsoft.
