### ISSUE TITLE
File changes aren't immediately reflected

### ISSUE THREAD

**Issue by itsthejb** [filebrowser/filebrowser#808]
First of all, thanks for the great work on this! On issue:

**Description**
When making file system changes (delete, rename, etc.), these changes are immediately reflected in the opened folder. I need to go up the file tree and down again, reloading that folder, in order to see the changes that I made.

**Expected behaviour**
Upon making some changes to an open folder (delete, rename), these changes are immediately visible in the opened directory.

**What is happening instead?**
It's necessary to exit that directory and re-open it. Then the changes previously made will be visible

**Additional context**
File Browser 2.0.12, CentOS 7.5, running in Docker CE. Also using MergerFS on the file system

**How to reproduce?**
1. Make some changes to a directory (delete, rename files)
2. You are returned to the current directory
3. Changes just made are not yet visible
4. Go up to a parent directory
5. Re-enter the previous directory
6. Previously made changes are now shown

**Files**
Seen on all file types

May be hard to recreate. Please let me know if I can help more

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
