### ISSUE TITLE
Respect `metaDataFormat`

### ISSUE THREAD

**Issue by chesedo** [filebrowser/filebrowser#81]
In Hugo's config it is possible to set the `metaDataFormat` to any of the three supported Front Matter formats which is the format that the Front Matter will be in when Hugo creates a new content item.

But caddy-hugo creates all Front Matter in JSON. Is it possible for it to use the format set in the config file of Hugo?

**Comment by hacdias** [comment]
Hello! Thanks for that. Can you move this issue to [caddy-filemanager](https://github.com/hacdias/caddy-filemanager/issues)? Hugo will be built on top of File Manager and file manager will be on charge of editing files.

**Comment by chesedo** [comment]
@hacdias I created an issue there - https://github.com/hacdias/caddy-filemanager/issues/4
