### ISSUE TITLE
Ability to download a single file in zip/gz format

### ISSUE THREAD

**Issue by tsundara** [filebrowser/filebrowser#820]
**Is your feature request related to a problem? Please describe.**
On the filebrowser UI, I love that a directory can be downloaded as zip/gz/tar and other formats. But I can't download a single file in compressed format. I expose some log and csv file directories via filebrowser and these files are several hundred MBs and sometimes GBs. Most of the time, my team needs to download a single large file. Sometimes we are on slow networks and this causes huge delays. 

**Describe the solution you'd like**
Provide option to download a SINGLE file in zip/gz/tar and other compressed formats.

**Describe alternatives you've considered**
I know we can select multiple files to download them as zip files. This hack works if there is another small file in the same directory, so we can combine and download as zip. But this is not an elegant solution.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
