### ISSUE TITLE
display a text file content in window

### ISSUE THREAD

**Issue by idontlikeit** [filebrowser/filebrowser#822]
open a text file. If I want to return, it will be a waste of time.  I suggest displaying text file content in window.

**Comment by hacdias** [comment]
Sorry, I don't understand what you meant. Where do you want to display the content? On the file listing? If so, why?

**Comment by idontlikeit** [comment]
Just like this, Because Convenient and easy to use

![window](https://user-images.githubusercontent.com/32320000/62882685-06816280-bd65-11e9-9768-4a382ddf7df6.png)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
