### ISSUE TITLE
How do I open a file?

### ISSUE THREAD

**Issue by lucasctd** [filebrowser/filebrowser#823]
I can't figure out to do it.
When I select a file it only shows me the option to rename the file.
When I created a new file, it showed me a text editor where I added some content to the file, then I saved it and couldn't also edit the file I just had created.
The shell feature always show "Command not allowed".
What am I missing?

The print screen below shows the pencil which only lemme rename the file and the shell feature which always the message I typed above.

![image](https://user-images.githubusercontent.com/5876679/62013926-91ad0680-b170-11e9-8707-958896ce2a31.png)

**Comment by lucasctd** [comment]
I am using it through a Docker container and my user has admin rights.

**Comment by hacdias** [comment]
Hey @lucasctd! Try double-clicking the file to edit it.

About the commands: are you sure you added them to the allowed commands? See on Settings please.

**Comment by lucasctd** [comment]
It worked, thx.
