### ISSUE TITLE
panic with auth.method=proxy & auth.header=X-Auth-Apache

### ISSUE THREAD

**Issue by fdefilippo** [filebrowser/filebrowser#824]
**Description**
filebrowser config set --auth.method=proxy --auth.header=X-Auth-Apache  

**Expected behaviour**

filebrowser authenticating trought apache reverse proxy

**What is happening instead?**

panic: While parsing config: yaml: line 42: could not find expected ':'
 
goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
        /home/circleci/project/cmd/root.go:345 +0x456
github.com/spf13/cobra.(*Command).preRun(0x22f39e0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:792 +0x49
github.com/spf13/cobra.(*Command).execute(0x22f39e0, 0xc00001e1c0, 0x0, 0x0, 0x22f39e0, 0xc00001e1c0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:728 +0x146
github.com/spf13/cobra.(*Command).ExecuteC(0x22f39e0, 0xc0001a5f68, 0x4069dd, 0x23020b0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/circleci/project/cmd/cmd.go:9 +0x2e
main.main()
        /home/circleci/project/main.go:11 +0x33

**Additional context**

the yaml file

Sign up:          false
Create User Dir:  false
Auth method:      proxy
Shell:

Branding:
  Name:
  Files override:
  Disable external links:  false

Server:
  Log:       stdout
  Port:      8080
  Base URL:
  Root:      .
  Socket:
  Address:   127.0.0.1
  TLS Cert:
  TLS Key:

Defaults:
  Scope:      .
  Locale:     en
  View mode:  mosaic
  Commands:
  Sorting:
    By:
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "header": "X-Auth-Apache"
}

**How to reproduce?**

**Files**

**Comment by hacdias** [comment]
Is that your `config.yaml` file? If so, it's not a valid yaml file. It should not have spaces on the keys, nor JSON mixed.

**Comment by fdefilippo** [comment]
thnx

> Is that your `config.yaml` file? If so, it's not a valid yaml file. It should not have spaces on the keys, nor JSON mixed.

Thnx a lot.
