### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by ip75** [filebrowser/filebrowser#825]
Please file a new issue at golang.org/issue/new using this template:

Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

i try to build latest sources

[ root /usr/local/gohome/src/github.com/filebrowser/filebrowser ] # go clean
[ root /usr/local/gohome/src/github.com/filebrowser/filebrowser ] # go build

./wizard.sh -b
./wizard.sh -a
the same result

#### What did you expect to see?

built filebrowser binary

#### What did you see instead?

# github.com/filebrowser/filebrowser/storage/bolt/importer
storage/bolt/importer/users.go:33:22: cannot use func literal (type func(*bbolt.Tx) error) as type func(*"github.com/coreos/bbolt".Tx) error in argument to db.Bolt.View
# github.com/filebrowser/filebrowser/http
http/raw.go:37:52: undefined: archiver.Writer
http/raw.go:40:18: undefined: archiver.NewZip
http/raw.go:42:18: undefined: archiver.NewTar
http/raw.go:44:21: undefined: archiver.NewTarGz
http/raw.go:46:22: undefined: archiver.NewTarBz2
http/raw.go:48:21: undefined: archiver.NewTarXz
http/raw.go:50:22: undefined: archiver.NewTarLz4
http/raw.go:52:21: undefined: archiver.NewTarSz
http/raw.go:81:17: undefined: archiver.Writer
http/raw.go:99:17: undefined: archiver.File
http/raw.go:99:17: too many errors

[ root@ /usr/local/gohome/src/github.com/filebrowser/filebrowser ] #

#### System details

```
go version go1.12.7 freebsd/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/usr/local/gohome"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12.7 freebsd/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.7
uname -v: FreeBSD 12.0-RELEASE-p2 c3ec797e4c1(releng/12.0) BVGM
lldb --version: lldb version 6.0.1
  clang revision 335540
gdb --version: GNU gdb 6.1.1 [FreeBSD]
```

**Comment by hacdias** [comment]
We're using go modules. Please **don't** clone it inside a `$GOPATH`. Clone it outside, run `go get` and `go build`.

I can't reproduce your issue, and CI just run and everything went well.

**Comment by ip75** [comment]
build is successful when i set `GO111MODULE=on`

```
export GO111MODULE=on
go get
go build
```
