### ISSUE TITLE
New way to install Hugo

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#83]
Right now, as you probably now, caddy-hugo is downloading Hugo binaries from GitHub releases and then it checks its hash. That means that Hugo hashes need to be hard-coded and, sometimes, Hugo release file names change and I've to change the installer code as well.

**The idea:**

Before building the Caddy executable with hugo plugin, a script would be run. That script would use GitHub api to check the latest tag of Hugo (which is the latest stable version). Replace installer.go placeholder with the latest version.

Then, it would go to `$GOPATH/github.com/spf13/hugo` and check if it already has the latest tag. If it has, it would proceed. If it doesn't, `go get -u` must be run.

After that, `go build` would be executed and the produced file gzipped. That file would be embedded in the final executable using go-bindata. In the end, it would be easier to install the latest version.

What do you think?

**Comment by hacdias** [comment]
@mholt and @abiosoft: what do you think?

**Comment by mholt** [comment]
That's a lot of logic. If you do implement it, I hope it works well. :)

**Comment by hacdias** [comment]
I need to ask you one thing: is `go generate` executed before _each_ build, or after the server starts?

**Comment by hacdias** [comment]
And is it executed after setting GOOS and GOARCH or before? @mholt

**Comment by mholt** [comment]
On the build server? [go generate is run on each build](https://github.com/caddyserver/caddydev/blob/cb87cf35a419542c2c2e0a7da73b0b70421074d5/caddybuild/build.go#L122-L123) - it does not set GOOS or GOARCH variables when running that command.

**Comment by hacdias** [comment]
I would like you to take a look at [this](https://github.com/hacdias/caddy-hugo/blob/master/build/main.go) and [this](https://github.com/hacdias/caddy-hugo/blob/master/installer.go) files when you have some time. :D

**Comment by hacdias** [comment]
Done! Done! And done! :D Let's see what's going to happen. I ask you @mholt to check if everything on build/main.go can be executed on the build server (I think it can).

**Comment by hacdias** [comment]
Gonna close this because from now on, the user **must** install hugo for themselves.
