### ISSUE TITLE
Getting Proxy to work with Filebrowser using Apache

### ISSUE THREAD

**Issue by ChrisFowl2** [filebrowser/filebrowser#839]
When I access my instance via apache2 with mod_proxy, I get an 2 Syntax Errors; SyntaxError: expected expression, got '<' in chunk-vendors.37c31b02.js:1 and SyntaxError: expected expression, got '<' in app.2e1de15d.js:1. This is at the loading page and it won't go to the login page.

**Comment by nambrosch** [comment]
can you post your apache config?

**Comment by ChrisFowl2** [comment]
Of course! I believe you're looking for the VirtualHost, if not let me know.
```
<VirtualHost *:443>
  ServerAdmin admin@example.tld
  ServerName example.tld

  DocumentRoot /var/www/example.tld
  DirectoryIndex index.html

  <Directory /var/www/example.tld>
    AllowOverride All
    Require all granted
  </Directory>

  SSLCertificateFile /var/www/certificates/example.tld-cert.pem
  SSLCertificateKeyFile /var/www/certificates/example.tld-key.pem

  ProxyPass /filebrowser http://localhost:8080/
  ProxyPassReverse /filebrowser http://localhost:8080/
<VirtualHost>
```

**Comment by nambrosch** [comment]
try adding this below `ProxyPassReverse`:

```
  ProxyPreserveHost On
  RewriteEngine On
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule (.*) ws://127.0.0.1:8080/$1 [P,L]
```

**Comment by ChrisFowl2** [comment]
Hmmm... didn't seem to work. It still won't get past the loading screen. Thank you for your help, though! Furthermore, I discovered where the syntax error came from. For the proxy, I had set the filebrowser baseurl option to filebrowser, so browsers can find pages, scripts and other assets. When I set it back to normal, the syntax error disappeared, but now it can't find the assets. So maybe this syntax error is a bug when using the baseurl option? And also, would I be able to get filebrowser working with a proxy?

**Comment by ChrisFowl2** [comment]
Probably related to #719, but this one is for apache2. Thus, this is also related to #669 & #30.

**Comment by nambrosch** [comment]
if you've updated the baseurl then you need to update apache's config to reflect that, so something like this -
```
  <Location "/filebrowser/">
    ProxyPass http://127.0.0.1:8080/filebrowser/
    ProxyPassReverse http://127.0.0.1:8080/filebrowser/
  </Location>

  ProxyPreserveHost On
  RewriteEngine On

  # upgrade websocket requests
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule (.*) ws://127.0.0.1:8080/$1 [P,L]
```
not required, but helpful:
```
  # add trailing slash to /filebrowser/
  RewriteRule ^/filebrowser$ /filebrowser/ [L,R=301]
```

**Comment by ChrisFowl2** [comment]
Almost there! Now I get to the login page, but when I try to login, the browser goes to the following address: https://example.tld/filebrowser/filebrowser/api/login, which, of course, gives an 404 not found. How can I prevent the double filebrowser in the link?

**Comment by nambrosch** [comment]
`--baseurl=/filebrowser/` should do the trick, no?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by erambour** [comment]
> if you've updated the baseurl then you need to update apache's config to reflect that, so something like this -
> 
> ```
>   <Location "/filebrowser/">
>     ProxyPass http://127.0.0.1:8080/filebrowser/
>     ProxyPassReverse http://127.0.0.1:8080/filebrowser/
>   </Location>
> 
>   ProxyPreserveHost On
>   RewriteEngine On
> 
>   # upgrade websocket requests
>   RewriteCond %{HTTP:Connection} Upgrade [NC]
>   RewriteCond %{HTTP:Upgrade} websocket [NC]
>   RewriteRule (.*) ws://127.0.0.1:8080/$1 [P,L]
> ```
> 
> not required, but helpful:
> 
> ```
>   # add trailing slash to /filebrowser/
>   RewriteRule ^/filebrowser$ /filebrowser/ [L,R=301]
> ```

Hello, sorry to resurrect a such old issue ...

I've used with success those instructions, but I'm still facing a problem with the shell commands:

`http://my_server_url/filebrowser` works (on port 80) 

but if I send a shell command  ( with '< >" ), I have no output except in the browser console :
```WebSocket connection to 'ws://my_server_url/filebrowser/api/command/?auth= .../...  ' failed: There was a bad response from the server.```

if I use instead `http://my_server_url:8080/filebrowser` everything works : testing a simple `ls` displays the directory content as expected.

Of course it's probably more a apache2 issue (I have a very basic apache knowledge), but I'm looking for a clean solution ;-)
Apache version 2.4.52, proxy_http & proxy_wstunnel active, setups in 000-default.conf ( this is a local server/browser config )
