### ISSUE TITLE
Advice on supporting HTTP Basic auth

### ISSUE THREAD

**Issue by osdu** [filebrowser/filebrowser#840]
Advice on supporting HTTP Basic auth

Install filebrowser on the route as a private cloud storage service, using HTTP Basic auth to help block unauthorized access and weak password cracking for filebrowser。

For privacy purposes, you don't want some users on the LAN to use port scans to detect application types on open ports.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
