### ISSUE TITLE
A more detailed log?

### ISSUE THREAD

**Issue by luftaquila** [filebrowser/filebrowser#844]
I'm saving log as 
    "server": {
        "root": "/home/pi/ExtHDD",
         ...
        "log": "log.txt"
    },
in setting. 

By the way, I think the log only prints 400~500 http errors. Is there any way to do some more detailed logging? ex) http log, login log, directory browsing log, file download log,... or so.

I tried to fork it and made it on my own. But I'm not familiar with Go, I failed : (
Thank you.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
