### ISSUE TITLE
User registration cannot automatically create directories

### ISSUE THREAD

**Issue by zjacai** [filebrowser/filebrowser#845]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?

**Expected behaviour**
What did you expect to happen?
User registration can automatically create directories

**What is happening instead?**
Please, give full error messages and/or log.
User registration cannot automatically create directories
but，the administrator add user can automatically create directories

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
Tell us how to reproduce this issue. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

**Files**
A list of relevant files for this issue. Large files can be uploaded one-by-one or in a tarball/zipfile.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
