### ISSUE TITLE
Create user while filebrowser running

### ISSUE THREAD

**Issue by ggarpanchal** [filebrowser/filebrowser#846]
Dear Team,

When filebrowser (File Browser v2.0.12/64d6d9e ) is in running stage, new user can not be created by below command.
```
filebrowser users add <username> <password>
```
It shown "timeout" as shown in below snap.
 
![Screenshot from 2019-08-25 16-45-12](https://user-images.githubusercontent.com/12757494/63649152-c902d900-c757-11e9-87c4-42ca57fad045.png)

Alternatively, is there any other ways to create new user via terminal ( **not from web-GUI** ) ?

Thank you.

**Comment by hacdias** [comment]
When filebrowser is running the database is locked so no other process can execute commands on it. You need to use the Web UI. We haven't yet had time to look if we can somehow circumvent this situation.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
