### ISSUE TITLE
get wrong in home page

### ISSUE THREAD

**Issue by ZhaoBaymax** [filebrowser/filebrowser#850]
version: v2.0.12 
env:  docker

Sometimes when i enter the page or refresh the page, i will get this wrong(probabilistic events)

![image](https://user-images.githubusercontent.com/28599497/63755882-fda69a00-c8e9-11e9-954b-9b43eac1f2ca.png)

log:

```
2019/08/27 08:27:09 /api/renew: 403 10.4.143.186:10632 <nil>
```

config:
```
  .filebrowser.json: |-
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/srv/database.db",
      "root": "/srv"
    }
```

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
