### ISSUE TITLE
Edit any file as text file

### ISSUE THREAD

**Issue by alanmilinovic** [filebrowser/filebrowser#851]
Hi, if I have .txt as an extension it is quite easy to double click and enter edit mode of the file. Where one can do changes and save the file.

Problem is that I cannot do it with other files, for example I would like to edit .m3u file. Can someone add an option "edit" once the file is selected? I know project is not under active development, but this should be like mandatory feature (at least for me). 😁

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by alanmilinovic** [comment]
Plese open this topic again as repository is no longer archived.
