### ISSUE TITLE
Logs on user activities 

### ISSUE THREAD

**Issue by premum** [filebrowser/filebrowser#855]
I have been using this filebrowser locally within our team for a quiet long time now for common sharing.
But i always get confused on finding who uploaded a doc and who edited a particular document.
It is a necessary feature to log which user did what in a specific session.
If this feature is already available  and if I am missing it unnoticed., then it would be great if someone enlightens me on the same.

**Comment by DanielVladu** [comment]
I did not tested this but I think you can use the command runner for this, for example:

filebrowser cmds add -e="after_copy" -c="echo '$(date) User $USERNAME copied $FILE to $DESTINATION' >> /var/log/filebrowser_access_logs.log"

You can do this for copy/rename/upload/delete. The download/edit events are missing.
https://filebrowser.xyz/configuration/command-runner

Also if I get the time I will try to fix this issue native in the app.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
