### ISSUE TITLE
Doesn't work on jailbroken iOS device (cross compiled for arm64 darwin), keeps loading

### ISSUE THREAD

**Issue by qianbinbin** [filebrowser/filebrowser#856]
**Description**
I cross compiled filebrowser on macOS for a jailbroken iOS device (iPhone 5S) by:
```sh
CC=$GOPATH/misc/ios/clangwrap.sh CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build
```
And everything looks good:
```sh
root@iPhone:/var/mobile# ./filebrowser 
runtime/cgo: no Info.plist URL
2019/09/04 17:41:21 No config file used
2019/09/04 17:41:21 Listening on 192.168.0.100:8080
```

**Expected behaviour**
It should work

**What is happening instead?**
After I open the link with Chrome or Safari both keeps loading:
![image](https://user-images.githubusercontent.com/7856168/64279388-8627d900-cf81-11e9-91cb-65d7f4d79904.png)
(for 127.0.0.1 using iOS Safari doesn't work either)
the log shows no error.

**Additional context**
the time seems weird, like with a wrong timezone? filebrowser shows UTC+0 but I'm in UTC+8:
```sh
root@iPhone:/var/mobile# date
四  9  5 01:42:27 CST 2019
```
Another error is reported by Chrome:
![image](https://user-images.githubusercontent.com/7856168/64280671-339bec00-cf84-11e9-9ac8-8c555903165b.png)
But I'm poor at frontend and can't figure it out.
Anyone help? Thanks in advance.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
