### ISSUE TITLE
RPi - You don't have permissions to access this.

### ISSUE THREAD

**Issue by alanmilinovic** [filebrowser/filebrowser#859]
I am trying to access folder that has View content permissions set to Anyone, and receive message that I don't have permissions to access it. User running the service is set to root (I also tried with pi user).

This is my service file

> [Unit]
> Description=Filebrowser
> After=network-online.target
> 
> [Service]
> Restart=on-failure
> RestartSec=30
> User=root
> Group=root
> Type=simple
> ExecStart=/etc/filebrowser/filebrowser
> ExecStop=killall /etc/filebrowser/filebrowser
> 
> [Install]
> WantedBy=multi-user.target

**Comment by alanmilinovic** [comment]
I just realized what is the problem, from the log file. Problem only exist if I am connected with XRDP to my RPi.

`Sep 14 16:20:42 1raspberrypi filebrowser[30958]: 2019/09/14 16:20:42 /home/pi/: 403 5.147.1.133:60656 lstat /home/pi/thinclient_drives: permission denied
`

**Comment by mouzzampk2014-zz** [comment]
> I just realized what is the problem, from the log file. Problem only exist if I am connected with XRDP to my RPi.
> Sep 14 16:20:42 1raspberrypi filebrowser[30958]: 2019/09/14 16:20:42 /home/pi/: 403 5.147.1.133:60656 lstat /home/pi/thinclient_drives: permission denied

Hi, you are running docker version? If yes, you what tag you are using for docker? I am planning too run on `rpi 3b+`. Thank you

**Comment by alanmilinovic** [comment]
I am not using docker at all. Also I am running it on a RPi 4 as well as on RPi 3b +.

Can someone please have a look on this bug? I see that file called "thinclient_drives" that is created when I make an xrdp connection is preventing Filebrowser to read home folder of my "pi" user.

**Comment by alanmilinovic** [comment]
Any update on this issue?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by alanmilinovic** [comment]
Please open this topic as repository is active again.
