### ISSUE TITLE
File Manager/Access Question

### ISSUE THREAD

**Issue by justrjlewis** [filebrowser/filebrowser#86]
Is there a way to add access restrictions?  For example, only allowing someone access to the content folder?

**Comment by hacdias** [comment]
I'm not sure if this would work, but try `basicauth /admin/content user pass`. I think it will conflict with the the "super admin" but try anyway.

**Comment by justrjlewis** [comment]
It didn't work. It does conflict with the primary admin. Shucks.

**Comment by hacdias** [comment]
So, I don't know any way to do this right now. How is the auth plugin @mholt? I've read that there was someone doing it.

**Comment by mholt** [comment]
That was @captncraig but he's been pretty busy lately.

**Comment by hacdias** [comment]
I'm making huge updates to File Manager to support a bit of Access Permissions. Check out the closed recent closed issues. I'll update this plugin in some time to work with those permissions.

**Comment by justrjlewis** [comment]
@hacdias I saw that! 😈

**Comment by hacdias** [comment]
Check out #87. It seems to be working fine :P
