### ISSUE TITLE
Can't Get to Command Line in Docker Container

### ISSUE THREAD

**Issue by pageb018** [filebrowser/filebrowser#861]
**Description**
Trying to get a console when using filebrowser in a docker container fails.

**Expected behaviour**
To get a command prompt

**What is happening instead?**
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown

**Additional context**
Tried both /sh and /bash

**How to reproduce?**
Run filebrowser in docker container, try to bring up a console.

**Files**
NA

**Comment by barigorokarl** [comment]
Hi,

this is because the Dockerfile creates a base image without any further software - even a shell.

Edit the `Dockerfile` in the project root and comment the FROM scratch and COPY lines such:

```
FROM alpine:latest as certs
RUN apk --update add ca-certificates

#FROM scratch
#COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

VOLUME /srv
EXPOSE 80

COPY .docker.json /.filebrowser.json
COPY filebrowser /filebrowser

ENTRYPOINT [ "/filebrowser" ]
```

`docker build .`  and you will be able to sh into that container.

**Comment by danielloader** [comment]
Might be out of scope here but it would be nice to have official docker images built with different tags for this sort of reason, `filebrowser/filebrowser:alpine-latest` etc

**Comment by dennorske** [comment]
Just a follow up question on the same issue - the step before the ENTRYPOINT is failing. The filebrowser dir is nowhere to be found.. What am I doing wrong?

**Comment by barigorokarl** [comment]
Not really the same issue, but anyways: 

COPY filebrowser /filebrowser does not copy a directory but the filebrowser binary. You need to have that in the same directory as the Dockerfile.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
