### ISSUE TITLE
Error with custom commands on Docker image

### ISSUE THREAD

**Issue by kmickeletto** [filebrowser/filebrowser#864]
**Description**
Error with custom commands on Docker image.  Trying to use custom command for after uploading files.  Example, `chmod -x "$FILE"`

**Expected behaviour**
In this instance, it should execute the command chmod against the file

**What is happening instead?**
I receive a server error, most likely because chmod is not installed on the container or isn't in the path??

**Comment by barigorokarl** [comment]
Hi,

yes, chmod is not installed. Follow this solution: https://github.com/filebrowser/filebrowser/issues/861#issuecomment-540481463

Cheers

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
