### ISSUE TITLE
More Symlink Errors

### ISSUE THREAD

**Issue by kmickeletto** [filebrowser/filebrowser#865]
**Description**
Creating symlink to a different partition works at OS level, not inside filebrowser.

`\# ln -sr /docker/kameron scripts`

`\# ls -lah`
`total 0`
`drwxr-xr-x. 2 root root 35 Sep 19 17:37 .`
`drwxr-xr-x. 8 root root 89 Sep 19 12:54 ..`
`lrwxrwxrwx. 1 root root  9 Sep 19 12:55 Public -> ../Public`
`lrwxrwxrwx. 1 ken  ken  23 Sep 19 17:37 scripts -> ../../../docker/kameron`

**Expected behaviour**
Directory to be browsable inside of filemanager

**What is happening instead?**
![image](https://user-images.githubusercontent.com/22467125/65286554-973a2380-db05-11e9-907a-f4f990b0ec8b.png)

Symlink directory appears as a file and I get the error message 
![image](https://user-images.githubusercontent.com/22467125/65286591-b5a01f00-db05-11e9-8cbd-0fc56fb0447b.png)

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
Interestingly enough, I have another symlinked directory that is on the same partition called Public and it works flawlessly...

**Comment by CrazyMouse** [comment]
I have the same issue ,the soft link on linux can not be work right !

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by wschlotter** [comment]
Can we reopen this issue since the project has not been archived. I am getting the same issue.
