### ISSUE TITLE
Custom info/error messages

### ISSUE THREAD

**Issue by mkielak** [filebrowser/filebrowser#866]
I often use filebrowser with my python projects, where I use watchdog for incoming new files and use filebrowser like GUI for users. Everything works perfect, I can process files, output them in output directory what is very easy for users.
The main problem is that users doesn't know if anything is in progress or not. I don't know if this feature is already implemented but it would be great to have some api and socket file, where every event will posted, your program listening this socket can handle it and return some message which will be logged on user screen.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
