### ISSUE TITLE
[Question] Equivalent maintained app?

### ISSUE THREAD

**Issue by lonix1** [filebrowser/filebrowser#869]
I see that this app is no longer maintained.

Does anyone know of an equivalent (dockerized) app that is maintained?

**Comment by rah-0** [comment]
This shouldn't be the attitude of anyone in GIT. Instead of asking for a "better" app, which can be an offense for the devs that spent their time MAINTAINING this, see how you can contribute to keep this one alive, and hopefully after a while it will pick up more devs.

**Comment by lonix1** [comment]
From readme:

> WARN: This project is not under active development ATM. A small group of developers keeps the project alive, but due to lack of time, we can't continue adding new features or doing deep changes.

BTW I didn't ask about "better"... in fact I'll settle for something worse, as long as it's active.

Presumably many users have found a replacement. So this is THE place to ask such a question.

No offense was given, and I'm sure very little taken. I think this is a good case of "mind your own business" - the developers, if they are indeed offended (and shouldn't be because I didn't insult them), can protect themselves.

**Comment by hacdias** [comment]
I'm not offended, but I personally would like to see more people contributing. Even if it was not for new features, bug fixes and improvements would be great to have.

About "equivalent" maintained apps, I just know about heavier options such as OwnCloud and NextCloud. I'm not really aware of many apps in this scope.

**Comment by nambrosch** [comment]
when i was looking for something originally, a cloud storage replacement system was too complex for what i was looking to do.  filebrowser is perfect for my needs.  i've seen many people saying they are ready to contribute but few of them do much.  i can't thank you enough for what has been done with filebrowser, @hacdias and i also hope it does not end up abandoned.

**Comment by lonix1** [comment]
Agreed, I cannot find anything equivalent, which is why I asked. Everything I've found is too "heavy", like @hacdias said.
