### ISSUE TITLE
Feature request: remove logout on proxy auth

### ISSUE THREAD

**Issue by fdefilippo** [filebrowser/filebrowser#870]
When filebrowser is configured to authenticate users via environment variable (reverse proxy) the logout link should be removed or hidden or other action. 

thank you.

**Comment by ovidiucp** [comment]
I'd actually like to have the logout button redirect to a custom URL, that could be user specified.

I'm using oauth2_proxy with nginx. The former uses the /oauth2/sign_in path to log out the current user. I'd like to setup the Logout button in filebrowser to point to that URL.

**Comment by ovidiucp** [comment]
It turns out logging out of oauth2_proxy cannot be done in filebrowser, since the cookie is an HttpOnly cookie. The Logout button was confusing some of my users, so I took a stab at this.
