### ISSUE TITLE
Centos 8 下File Browser无法开机启动

### ISSUE THREAD

**Issue by LsnmxNB** [filebrowser/filebrowser#873]
File Browser 2.0.12 ，curl https://cdn.mivm.cn/www.mivm.cn/archives/filebrowser/filebrowser.service -o /lib/systemd/system/filebrowser.service

[root@server ~]# systemctl is-enabled filebrowser.service
enabled
[root@server ~]# systemctl status filebrowser.service
● filebrowser.service - File Browser
   Loaded: loaded (/usr/lib/systemd/system/filebrowser.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

无奈每次重启只能手动执行 systemctl start filebrowser.service

**Comment by xupefei** [comment]
You can use `journalctl` to see what's wrong.

**Comment by freedomlang** [comment]
@LsnmxNB Can you show us the filebrowser.service?

**Comment by LsnmxNB** [comment]
> You can use `journalctl` to see what's wrong.

@xupefei 

> @LsnmxNB Can you show us the filebrowser.service?

@freedomlang 
Hello there! File Browser 2.0.16 still fails to start automatically under Centos 8

[root@server ~]# journalctl -u filebrowser.service
-- Logs begin at Mon 2019-12-09 16:43:21 CST, end at Mon 2019-12-09 16:43:43 CST. --
Dec 09 16:43:24 server systemd[1]: Started File Browser.
Dec 09 16:43:24 server filebrowser[714]: 2019/12/09 16:43:24 No config file used
Dec 09 16:43:24 server systemd[1]: filebrowser.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 16:43:24 server filebrowser[714]: 2019/12/09 16:43:24 listen tcp 5.*.*.*:8088: bind: cannot assign requested address
Dec 09 16:43:24 server systemd[1]: filebrowser.service: Failed with result 'exit-code'.

[root@server ~]# journalctl -u filebrowser.service
-- Logs begin at Fri 2019-12-06 15:51:49 CST, end at Mon 2019-12-09 16:29:53 CST. --
Dec 06 15:51:56 server systemd[1]: Started File Browser.
Dec 06 15:51:59 server filebrowser[839]: 2019/12/06 15:51:59 No config file used
Dec 06 15:51:59 server filebrowser[839]: 2019/12/06 15:51:59 listen tcp 91.*.*.*:8088: bind: cannot assign requested address
Dec 06 15:51:59 server systemd[1]: filebrowser.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 15:51:59 server systemd[1]: filebrowser.service: Failed with result 'exit-code'.

**Comment by freedomlang** [comment]
@LsnmxNB Did you check your filebrowser.service? Maybe missing config for After?

**Comment by LsnmxNB** [comment]
> filebrowser.service
@freedomlang 

filebrowser.service It is configured, and can be booted normally under Centos 7, Centos 8 will not work

[root@vps022 ~]# systemctl is-enabled filebrowser.service
enabled

**Comment by xupefei** [comment]
> No config file used
> listen tcp 91...*:8088: bind: cannot assign requested address

Two problems:
1) No config file is provided when starting the service.
2) The port 8088 is unavailable. Either your permission is insufficient or the port is already occupied by another process.

**Comment by LsnmxNB** [comment]
> > No config file used
> > listen tcp 91...*:8088: bind: cannot assign requested address
> 
> Two problems:
> 
> 1. No config file is provided when starting the service.
> 2. The port 8088 is unavailable. Either your permission is insufficient or the port is already occupied by another process.

@xupefei 

Under Centos 8 will not boot and start, I manually executed systemctl start filebrowser.service is no problem, the same deployment can start normally under Centos 7 ~~~

**Comment by LsnmxNB** [comment]
> > No config file used
> > listen tcp 91...*:8088: bind: cannot assign requested address
> 
> Two problems:
> 
> 1. No config file is provided when starting the service.
> 2. The port 8088 is unavailable. Either your permission is insufficient or the port is already occupied by another process.
@xupefei 
I suggest you try Centos 8 on your local VMware

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by LsnmxNB** [comment]
@o1egl Under Centos 8 will not boot and start, I manually executed systemctl start filebrowser.service is no problem, the same deployment can start normally under Centos 7 ~~~

**Comment by o1egl** [comment]
If you are be able te execute filebrowser manually it means you have some issues in your service config. It might be that you start it before networking service is up

**Comment by LsnmxNB** [comment]
> If you are be able te execute filebrowser manually it means you have some issues in your service config. It might be that you start it before networking service is up

The filebrowser v2.2.0 on several of my 10 Centos 8 can't boot and start automatically, the same configuration under Centos 7 is completely fine, otherwise I will provide a VPS Centos 8 for you to test, please provide me with the mailbox I send VPS Centos 8 ROOT password is for you, thank you!

**Comment by LsnmxNB** [comment]
@o1egl   @xupefei 

filebrowser.service

[Unit]
Description=File Browser
After=network.target

[Service]
User=root
ExecStart=/usr/local/bin/filebrowser -d /etc/filebrowser.db

[Install]
WantedBy=multi-user.target

**Comment by imChaLi** [comment]
Having the same problem. Pretty sure the service file and config file are correct. Also using CentOS 8. 

`/usr/local/bin/filebrowser -c /root/fb/config.json` works fine. 

But showing `Process: 23652 ExecStart=/usr/local/bin/filebrowser -c /root/fb/config.json (code=exited, status=203/EXEC)
 Main PID: 23652 (code=exited, status=203/EXEC)
`

`#!/bin/bash
[Unit]
Description=fb service
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/filebrowser -c /root/fb/config.json

[Install]
WantedBy=multi-user.target`
