### ISSUE TITLE
Maintain login status

### ISSUE THREAD

**Issue by 92000** [filebrowser/filebrowser#874]
After each successful login, you need to login again in a very short time.
I want to be able to keep this up for days or even weeks without having to log in again.

**Comment by AndreGeddert** [comment]
I think this is http/auth.go line 64
`expired := !tk.VerifyExpiresAt(time.Now().Add(time.Hour).Unix(), true)`

Just do 
`Add(time.Hour*24*x)` 
and you will stay logged in for x days.

**Comment by AndreGeddert** [comment]
Maybe this could be made configurable with something like
`Add(d.settings.LoginTimeout)` ?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
