### ISSUE TITLE
API for generating shared URLs in bulk

### ISSUE THREAD

**Issue by sbamin** [filebrowser/filebrowser#893]
Shared URLs is a nice feature but not handy if I need to create URLs for 100s of files all at once.

I wonder if there is an API to create bulk shared URLs for >1 files or an option to create URLs for each of file separately when I select multiple files?

Thanks

**Comment by zoidy** [comment]
There is (sort of). You can use the internal commands filebrowser itself uses to create links. I used it for my script to be able to generate links for streaming files in VLC. It should be easy to modify it to create many links at once.

https://github.com/zoidy/filebrowser-streamlink

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
