### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by brasilikum** [filebrowser/filebrowser#90]
Just wanted to leave a "Thank You" here for working on this awesome project. It makes it really simple to integrate into my existing hugo/caddy setup and provides the possibility to include non-technical people for providing content

**Comment by hacdias** [comment]
Hi @brasilikum! Thanks! I'm really happy to hear that from you. It's always enjoyable to know that someone is using what we've done and that it is really helping somehow. I hope you use it for long! Do you have any suggestions? :smile:

**Comment by brasilikum** [comment]
I do, see the other issues 😉
