### ISSUE TITLE
CentOS 8: filebrowser -d /database path, error: No config file used.

### ISSUE THREAD

**Issue by MisterWenLai** [filebrowser/filebrowser#902]
[root@V ~]# filebrowser -d /etc/filebrowser/filebrowser.db config set --locale zh-cn
Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:              

Branding:
  Name:                    
  Files override:          
  Disable external links:  false

Server:
  Log:       /etc/filebrowser/filebrowser.log
  Port:      80
  Base URL:  
  Root:      /
  Socket:    
  Address:   0.0.0.0
  TLS Cert:  
  TLS Key:   

Defaults:
  Scope:      /home
  Locale:     zh-cn
  View mode:  list
  Commands:   
  Sorting:
    By:   name
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}

[root@V ~]# filebrowser -d /etc/filebrowser/filebrowser.db
**2019/10/26 18:04:01 No config file used**
^C[root@V ~]# systemctl status filebrowser.service
● filebrowser.service - File Browser
   Loaded: loaded (/etc/systemd/system/filebrowser.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2019-10-26 17:35:09 CST; 29min ago
  Process: 1453 ExecStart=/usr/local/bin/filebrowser -d /etc/filebrowser/filebrowser.db (code=exited, status=203/EXEC)
 Main PID: 1453 (code=exited, status=203/EXEC)

Oct 26 17:35:09 V systemd[1]: Started File Browser.
Oct 26 17:35:09 V systemd[1]: filebrowser.service: Main process exited, code=exited, status=203/EXEC
Oct 26 17:35:09 V systemd[1]: filebrowser.service: Failed with result 'exit-code'.
[root@V ~]#

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
