### ISSUE TITLE
File with accent cannot be preview or edit

### ISSUE THREAD

**Issue by pinonpierre** [filebrowser/filebrowser#903]
Hi,
Great app!

But of course, I have a little issue.
I'm french and if I wrote an accent (é, è, à, ...) in a text file, the file cannot be preview or edit anymore.

I used the last Docker Image

Thanks!

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
