### ISSUE TITLE
How to use "custom brand"?

### ISSUE THREAD

**Issue by 437153** [filebrowser/filebrowser#907]
I followed the prompts to set up, I filled in "/img/logo.png" in "Branding directory path". The absolute path to this file is "D:\Program Files\Filebrowser\img". but did not replace the logo image, How should I set it to take effect?
Thank you！

**Comment by ghost** [comment]
* `logo.svg`, not `logo.png`, according to: https://github.com/filebrowser/frontend/tree/master/public/img
* Specify the directory and not the file.
* Clear the cache after a change.

**Comment by sabatale** [comment]
Here is an actual working example (natedalliard is right):

C:/Users/{username}/Documents/vue-bpmn-browser/frontend/src/assets/custom-branding

**Do not add a " / " at the end of the path.**

Folder custom-branding contains:

_1. file custom.css
2. folder img
       3. file logo.svg_

![image](https://user-images.githubusercontent.com/50220345/68163662-08ecf600-ff29-11e9-9ce5-d17f317ef930.png)

![image](https://user-images.githubusercontent.com/50220345/68163703-21f5a700-ff29-11e9-881f-26f22085fb72.png)

**Comment by Rony-n94** [comment]
Can someone provide a custom.css example and what is the idea of it. And does it need to exist for the image to work ?

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by EDIflyer** [comment]
> I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

Unfortunately the README doesn't provide an example `custom.css`?
