### ISSUE TITLE
Allow buttons that execute custom commands

### ISSUE THREAD

**Issue by brasilikum** [filebrowser/filebrowser#91]
Imagine the following usecase:
A static hugo website is persisted in a git repository. 
The productive version is at the master branch and automatically updated to be served at domain.com.
The staging version is at branch 'staging' and served at staging.domain.com with basic auth.
Both environments would be completely separate.
It would be awsome if the administrator could define a button, in this case 'send to production'.
If an author finished changes at the staging environment, he/she would press the button, which would trigger a script like 'git add . && git commit -m "" && git push'
The administrator would then review the branch and merge it into 'master', which would lead to the production environment updating automatically.

The functionality needed from caddy-hugo would be custom buttons that could be created from an administrator. What do you think, is this in scope?

**Comment by hacdias** [comment]
Good idea, but I ask you to move this question to [File Manager issues](https://github.com/hacdias/caddy-filemanager/issues) :)
