### ISSUE TITLE
Copy File to FTP

### ISSUE THREAD

**Issue by Proteus86** [filebrowser/filebrowser#912]
File Browser 2.0.15
Помощь
![image](https://user-images.githubusercontent.com/17897470/68530709-6e275980-0324-11ea-887f-147c39fbb04f.png)
**Description**
mount FTP
curlftpfs#ftp://*****:*****@*.*.*.*/ /media/***/1dc79642-f68f-4acd-828c-af3f372e6f191/shara/FTP_SUPPORT_ fuse allow_other,uid=1000,gid=1000,umask=0022 0 0

try upload file

2019/11/09 19:05:37 /FTP_SUPPORT_/SUPPORT/0.6/731212.odt: 500 ******:50736 open /media/***/1dc79642-f68f-4acd-828c-af3f372e6f191/shara/FTP_SUPPORT_/SUPPORT/0.6/731212.odt: operation not supported

**In mc file upload successful**

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
