### ISSUE TITLE
"filebrowser -d /etc/filebrowser/filebrowser.db config set --commands wget" failed ?

### ISSUE THREAD

**Issue by jsjcjsjc** [filebrowser/filebrowser#917]
I try to use wget in filebrowser
but it looks "filebrowser -d /etc/filebrowser/filebrowser.db config set --commands wget" failed ?
or I made a mistake ?

here is my full shell
```
filebrowser -d /etc/filebrowser/filebrowser.db config init
filebrowser -d /etc/filebrowser/filebrowser.db config set --address 0.0.0.0
filebrowser -d /etc/filebrowser/filebrowser.db config set --port 8080
filebrowser -d /etc/filebrowser/filebrowser.db config set --locale zh-cn
filebrowser -d /etc/filebrowser/filebrowser.db config set --log /var/log/filebrowser.log
filebrowser -d /etc/filebrowser/filebrowser.db config set --scope /var/www/html/
filebrowser -d /etc/filebrowser/filebrowser.db config set --commands wget
filebrowser -d /etc/filebrowser/filebrowser.db users add admin admin123  --perm.admin
```

Thanks a lot

**Comment by freedomlang** [comment]
@jsjcjsjc 
The command above should work. Dis you check it on webui(global settings)?

**Comment by jsjcjsjc** [comment]
> @jsjcjsjc
> The command above should work. Dis you check it on webui(global settings)?

sure,I tested it in three servers, the same problem.
I can find "wget" is in setting, But it doesn't work.

**Comment by hacdias** [comment]
https://github.com/filebrowser/filebrowser/issues/532
