### ISSUE TITLE
Bug: command 'git add .'

### ISSUE THREAD

**Issue by brasilikum** [filebrowser/filebrowser#92]
When I entered 'git add .' in the command field, there was neither a change in the local repo nor did I ever get feedback. The laoding-circle kept loading forever.
'git add content' resulted in the change being made in the local repo, but the output never reached me neither. It kept loading.

**Comment by hacdias** [comment]
Strange... Have you received any error in the Developer Console?

**Comment by brasilikum** [comment]
No. Do I have to run caddy other than just 'caddy'?

**Comment by hacdias** [comment]
Hey @brasilikum! On browser, right click in the page and select "Inspect". It will open the Dev Tools. Then open the Console and check if there are any errors there, please :) Like this:

![Like this](https://developer.chrome.com/devtools/docs/console-files/error-server-not-resp.png)

**Comment by brasilikum** [comment]
ok, so this is not so easy to track. It works some times, however as there is no output, I simply thought it had not worked. I will suggest a visual feedback on success in another issue. However the second time I got 403, but also no visual feedback. Why would that be?

**Comment by hacdias** [comment]
Hey Georg! I think that I only return 403 when the error is related to the
permissions. Do caddy has permissions over the files?

Anyway, I will check that out later when I have my laptop. :)

**Comment by brasilikum** [comment]
ok, the permissions might be the problem.

**Comment by hacdias** [comment]
Okay, check it out and let me know :)

**Comment by hacdias** [comment]
I'm going to close this due to its inactivity. If there are any updates, tell me!
