### ISSUE TITLE
Unknown option watch

### ISSUE THREAD

**Issue by brasilikum** [filebrowser/filebrowser#93]
hey,

if I try to make caddy watch on changes in the directory with 

```
hugo {
    watch
}
```

caddy tells me

`Unknown option watch`

I am aware that changes via the gui trigger a rebuild but what about local changes during development?
I would like to use this as a replacement for `hugo serve` with all the caddy-awsomeness.
Am I doing something wrong or is caddy-hugo simply not meant to be used for this?

**Comment by hacdias** [comment]
Sorry!!!! I've updated the syntax in the last version but the docs weren't updated. Try `flag watch`.

_Pinging_ @mholt

**Comment by brasilikum** [comment]
Ok, that worked. Hot reloading seems to be a whole different topic so I might still have to rely on 'hugo serve' for some time.

**Comment by hacdias** [comment]
Yup. Glad it worked :smiley:

**Comment by mholt** [comment]
Sorry, docs will be updated before too long. :sweat:
