### ISSUE TITLE
Please add 2 new languages in transifex - Bulgarian and Ukranian

### ISSUE THREAD

**Issue by ANTERRA-ADM** [filebrowser/filebrowser#930]
**Please add 2 new languages in transifex - Bulgarian and Ukranian**
Please add 2 new languages in transifex (https://www.transifex.com/file-browser/file-browser/) - Bulgarian and Ukranian.
Hello!
For a long time (even for version 2.0.8) we have prepared 2 new translation languages - Bulgarian and Ukrainian, but forgot about them =)
They are attached as files, please add them.
Thanks!
[BASE_BG.xlsx](https://github.com/filebrowser/filebrowser/files/3907574/BASE_BG.xlsx)
[BASE_UK.xlsx](https://github.com/filebrowser/filebrowser/files/3907575/BASE_UK.xlsx)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
