### ISSUE TITLE
Infinite Scroll does not work on large monitors

### ISSUE THREAD

**Issue by Airyzz** [filebrowser/filebrowser#931]
**Description**
When trying to browse large directories, infinite scroll does not kick in if the 50 displayed files fit on the screen without needing to scroll

**Expected behaviour**
Ideally, the page should not be limited to 50 files, but instead be populated until the screen is filled

**What is happening instead?**
Only the 50 initial files are being displayed, and since they all fit on screen, scrolling is impossible unless you make the window smaller

**How to reproduce?**
Open a large directory on a high resolution monitor (I am using 2560x1440 at 100% scale)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by alexisLefebvre** [comment]
I have the same issue, could you please reopen this issue? This repository isn't archived.

**Comment by alexisLefebvre** [comment]
Workaround to avoid resizing the browser: Switch view, then scroll to bottom, and Switch view again.
