### ISSUE TITLE
用什么命令取消用户权限?

### ISSUE THREAD

**Issue by mimishy2000** [filebrowser/filebrowser#941]
我要取消用户一些权限，比如删除，该怎么操作？
`[root@test]# filebrowser config set --perm.delete`这条命令是允许用户删除，默认设置也是TRUE，怎么设置用户的某些权限为FALSE
也不是执行`[root@test]# filebrowser config set --perm.delete false`

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
