### ISSUE TITLE
filebrowser 有计划做Android和IOS的APP吗？

### ISSUE THREAD

**Issue by 17558760** [filebrowser/filebrowser#943]
filebrowser 有计划做Android和IOS的APP吗？能用APP查看文件，图片和视频能显示缩略图，还有能自动备份手机上图片和视频。

Does filebrowser have plans for Android and IOS apps? Can use app to view files, pictures and videos can display thumbnails, and can automatically back up pictures and videos on mobile phones.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by rwlin** [comment]
I think that maybe enhancing the handling on mobile browser should be enough. For example, clicking to download and view the pdf file with installed pdf viewer app instead of showing unsupported pdf-preview.

**Comment by ppdragon16** [comment]
I want a mobile app so that I can cache multiple folders/files on my mobile device.

And it'd be nicer to sync the file changes from mobile to server.

Using mobile browser isn't enough for that.
