### ISSUE TITLE
Can't run with Podman 1.6.5 on Fedora 31

### ISSUE THREAD

**Issue by therevoman** [filebrowser/filebrowser#948]
**Description**
While trying to start he filebrowser docker container hosted on docker.io the container fails with the following error.  

`2019/12/25 05:32:58 exec: "getent": executable file not found in $PATH`

**Expected behaviour**
I expect the container to start and run

**What is happening instead?**
container tries to start and fails

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**How to reproduce?**
I'm using the zfs storage driver with podman on Fedora 31.
/usr/bin/podman run --log-level=debug -it --rm --name filebrowser filebrowser/filebrowser:v2

**Files**
uploading the verbose logs as an attachment.

[podman-filebrowser-getent.zip](https://github.com/filebrowser/filebrowser/files/3999686/podman-filebrowser-getent.zip)

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by gandazgul** [comment]
@hacdias I'm having this issue, Filebrowser seems alive and well, do you know how to fix this?

**Comment by gandazgul** [comment]
@therevoman did you ever find a fix? I'm having this issue.
