### ISSUE TITLE
how to setup caddy-hugo on a shared hoster?

### ISSUE THREAD

**Issue by tristan-k** [filebrowser/filebrowser#95]
I'm trying to run caddy-hugo on the shared hoster [uberspace](https://uberspace.de/). In order to use specific ports I will have to proxy the content with a htaccess [RewriteRule](https://wiki.uberspace.de/webserver:htaccess#rewriterule_mit_proxy). Here are the steps I did:
- Selected the hugo feature when downloading the caddy 64 bit Linux binary
- Created a Caddyfile with this content: 

```
localhost:61000

root      public           # the folder where Hugo generates the website
basicauth /admin user pass # protect the admin area using HTTP basic auth
hugo                       # enable the admin panel
```
- Created a ReWriteRule with a`.htaccess` for caddy.tristank.de:

```
RewriteEngine On
RewriteBase /
RewriteRule (.*) http://127.0.0.1:61000/$1 [QSA,P]
```
- Started Caddy with `./caddy -conf="Caddyfile"`

```
Activating privacy features... done.
http://localhost:61000
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
1 pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 168 ms
```

Finally I tried to access [caddy.tristank.de](http://caddy.tristank.de) but it just gives an error saying `No such site at :61000`.

Any advice?

**Comment by tristan-k** [comment]
Never mind! I had to use `localhost` in the `.htaccess` ReWriteRule not `127.0.0.1`.

**Comment by hacdias** [comment]
Glad to know that you figured that out 😄
