### ISSUE TITLE
Support build-in daemon

### ISSUE THREAD

**Issue by axetroy** [filebrowser/filebrowser#958]
**Is your feature request related to a problem? Please describe.**

The built-in daemon is important

Sometimes I don't need to use Docker to keep it running (because Docker's resource consumption in Windows / MacOS is not small)

If support built-in daemon, then it can be very clean and implementable

**Describe the solution you'd like**

add a flags to support daemon

```shell
$ filebrowser --address 0.0.0.0 --port 8888 --root ./share/ --daemon
```

**Describe alternatives you've considered**

Docker is a solution, but not the best

**Additional context**

The built-in support daemon is not difficult and is easy to implement

**Comment by nambrosch** [comment]
Most operating systems have something built-in to do this already, for example systemd on linux, service manager on windows, launchd on macos.

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by mckaygerhard** [comment]
due is now unarchived i reference this here: i finished solved in my way .. puff .. please! filebrowser/docs#41
