### ISSUE TITLE
Feature request: S3 Backend

### ISSUE THREAD

**Issue by fdefilippo** [filebrowser/filebrowser#963]
Hello, It would be very convenient to have the ability to use the credentials accesskey & secretkey of an s3 storage and then connect to the storage itself as backend.

**Comment by nambrosch** [comment]
i was thinking about doing something like this using aws cli, particularly the sync command.  Maybe trigger a run after any action that changes a file on disk?  Not as elegant as a proper integration would be but it might work as long as your local copy can always be considered the source of truth.

https://aws.amazon.com/cli/

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!
