### ISSUE TITLE
PDF preview on Android Chrome

### ISSUE THREAD

**Issue by studioai** [filebrowser/filebrowser#964]
**Description**
In Chrome Android version, PDF preview isn't shown up.

**Expected behaviour**
Same behavior as PC chrome

**What is happening instead?**
I get 'This plug-in is not supported' error message.

**Additional context**
I heard that Chrome Android don't have PDF plug-in support.
I found a way to preview a PDF file by entering the URL below. 

> http://docs.google.com/gview?embedded=true&url=filebrowser_generated_share_link_url

If it's hard to implement an original Android Chrome plug-in support, It's considerable to just show the Google doc preview in the preview.

[more detail](https://stackoverflow.com/questions/7437602/how-to-display-a-pdf-via-android-web-browser-without-downloading-first)

and this will be a solution to #880 

**How to reproduce?**
Double-tap on a PDF file on Android Chrome

**Comment by hacdias** [comment]
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Comment by lukesoftware** [comment]
I think that the best and simple solution is pass the full link of the PDF to the browser, as fallback, when the plugin Is not supported. Are two lines of code, buy very very useful! A filebrowser that not permit tò view the must used type of file in the world, on the must used device...is not possible! Thanks in advance for a solution.
