### ISSUE TITLE
Filebrowser won't start in Podman 

### ISSUE THREAD

**Issue by Ke1i** [filebrowser/filebrowser#966]
**Description**
I get a "exec: 'getent': executable file not found in $PATH" error when trying to start filebrowser container in Podman 1.9.2 on Fedora 32.

**Expected behaviour**
Container to start successfully and web interface to be available at http://hostip:port

**What is happening instead?**
Container fails to start and I get a "exec: 'getent': executable file not found in $PATH" error in the log file.

**Additional context**
None

**How to reproduce?**
1. Pull the docker container from the official repo. i.e 
```
sudo podman pull docker.io/filebrowser/filebrowser
``` 
2. Run the container using default configuration as instructed i.e
```
sudo podman run -dt --name=filebrowser -v /public:/srv:z -v ~/Containers/filebrowser/filebrowser.db:/database.db:z -v ~/Containers/filebrowser/.filebrowser.json:/.filebrowser.json:z -p 3080:80  docker.io/filebrowser/filebrowser
```
**Files**
None

**Edit**
Made some corrections to the problem description.

**Comment by o1egl** [comment]
@Ke1i Have you tries to set executable file path explicitly? I think it should look like that
```
sudo podman run -dt --name=filebrowser -v /public:/srv:z -v ~/Containers/filebrowser/filebrowser.db:/database.db:z -v ~/Containers/filebrowser/.filebrowser.json:/.filebrowser.json:z -p 3080:80  docker.io/filebrowser/filebrowser /filebrowser
```

**Comment by Ke1i** [comment]
No I haven't. Let me try and see how it goes. Thanks for the suggestion.

**Comment by Ke1i** [comment]
> @Ke1i Have you tries to set executable file path explicitly? I think it should look like that
> ```
> sudo podman run -dt --name=filebrowser -v /public:/srv:z -v ~/Containers/filebrowser/filebrowser.db:/database.db:z -v ~/Containers/filebrowser/.filebrowser.json:/.filebrowser.json:z -p 3080:80  docker.io/filebrowser/filebrowser /filebrowser
> ```

It didn't work. Just checked the command and it was already set to '/filebrowser.' 
Adding '/filebrowser' at the end makes it '/filebrowser /filebrowser'. But I know filebrowser isn't the issue because '/filebrowser --help' shows command options and usage.

**Comment by o1egl** [comment]
@Ke1i I've added alpine and debian based docker images. Can you please check if any of them work?

**Comment by Ke1i** [comment]
Funny how filebrowser turned out to be the thing that pushed me back to docker.
So unfortunately I can't test this right now :(
I moved everything from podman to docker. Thanks for the good work you're doing with the project.

**Comment by pinembour** [comment]
I still run into this issue with the base images, but I can confirm that both the alpine and the debian based images work as expected.
