### ISSUE TITLE
Feature Request: Downloader ( File Downloader and Torrent Downloader)

### ISSUE THREAD

**Issue by ghost** [filebrowser/filebrowser#968]
**Is your feature request related to a problem?**
No. I want to add Downloader to Filemanager so than i can download files from URLs and download torrent files from magnet links/torrent files.

**Describe the solution you'd like**
1. [Golang Grab Package](https://github.com/cavaliercoder/grab) provides the ability to download from direct links.
2. [anacrolix/torrent package](https://github.com/anacrolix/torrent) provides the ability to download torrent files.

And all these settings (of each user/globally) must be manageable by administrator account.

**Describe alternatives you've considered**
1. Cloud Torrent
2. Aria2 webui
3. Transmission remote

**Additional context**
Add settings to maintain no. of concurrent downloads, maximum download bandwidth,torrent settings, in administration panel.

**Comment by 726a67** [comment]
This feature seems to fall a bit outside the intended scope of filebrowser, which is ostensibly designed to manage existing file content, not to retrieve new file content.

I'm also concerned that the addition of these features would introduce a bit of heft to the project's currently light footprint.

I'm curious what others think.

**Comment by nambrosch** [comment]
I agree with @726a67 - it probably doesn't belong in filebrowser right now.  A tool like transmission is a fantastic torrent client with a web ui (I've used it for years).

**Comment by ghost** [comment]
It's not the absolute necessity for file manager but it's useful addon.

Suppose, if a person deploys this in production. A client/user will not be given ssh access(consider they are given just filebrowser access).

Now, there are many cases where a person needs to download files from internet. Currently he need to download locally and then upload it to filebrowser.

So, i do think that adding download manager to file manager will be useful.

Using external tools can't be linearly managed in settings.

**Comment by nambrosch** [comment]
@varbhat All-in-one software is always attractive, but as a solution today you could run transmission for torrent management, with a root directory of /opt/files/torrents then run filebrowser with a root directory of /opt/files - this way users have access to the completed downloads.  Hopefully this suggestion helps.

**Comment by 726a67** [comment]
> 
> 
> @varbhat All-in-one software is always attractive, but as a solution today you could run transmission for torrent management, with a root directory of /opt/files/torrents then run filebrowser with a root directory of /opt/files - this way users have access to the completed downloads. Hopefully this suggestion helps.

Exactly -- there are many ways to integrate existing (but separate) applications to produce a solution to the proposed use-case. I do something very similar with transmission and filebrowser myself.

I believe the goal of this project should be to make the core functionality (i.e. web-based file management) as robust and stable as possible. Let other projects tackle file content acquisition.

**Comment by o1egl** [comment]
@varbhat I completely agree with the above commentators that adding a torrent client is beyond the scope of this project.
