### ISSUE TITLE
Unable to publish content

### ISSUE THREAD

**Issue by mdaguete** [filebrowser/filebrowser#97]
Hi,

I'm testing caddy with hugo plugin, when I try to publish changes the following error is thrown

    application.js:120 Uncaught ReferenceError: token is not defined(…)document.getElementById.addEventListener.event @ application.js:120

If I try to create new content:

    application.js:43 Uncaught ReferenceError: token is not defined(…)document.getElementById.addEventListener.event @ application.js:43

The Caddyfile

    0.0.0.0:2020
    gzip
    root      sites/hugosite/public           # the folder where Hugo generates the website
    basicauth /admin user pass # protect the admin area using HTTP basic auth
    hugo sites/hugosite /admin                      # enable the admin panel

Regards.

**Comment by hacdias** [comment]
Hello @mdaguete!

Thanks for coming up with this! I forgot some things here when making some changes on File Manager. I just committed a possible fix. Can you build it from source and try it please?

**Comment by mdaguete** [comment]
Hi @hacdias,

Now it crash on https://github.com/hacdias/caddy-hugo/blob/2e111eab9fef3d4b342a2077b527bf402aa70dd2/assets/public/js/application.js#L118

Regards.

**Comment by hacdias** [comment]
Hey @mdaguete! Sorry about that. Check it out now 😄

**Comment by mdaguete** [comment]
No problem @hacdias, now it works like a charm!!!
Thanks. Regards.

**Comment by hacdias** [comment]
You're welcome! It's my duty 😄

**Comment by valentinvieriu** [comment]
@mdaguete I've just downloaded latest cody now with plugin enabled, and still getting this error. 
Can you tell us when will this fix be a part of the build?

**Comment by hacdias** [comment]
@valentinvieriu hey! Sorry, but this fix is not yet available on caddyserver.com. You have to build Caddy from source with the plugin.

Pinging @mholt

**Comment by valentinvieriu** [comment]
Bummer! This is a little bit bad, because right now the admin interface is quite pointless. You need to restart caddy to see the changes.
I've tried with the watch option from HUGO, but that didn't worked out. The files are not picked up by hugo.

**Comment by hacdias** [comment]
I can built it from you if you want. Just tell me the plugins, the OS and the architecture and I'll send you the binary file. @valentinvieriu

**Comment by valentinvieriu** [comment]
@hacdias I have found an older build, that didn't had this bug in.
Can you please give an estimation when you think this will be added to the build?

**Comment by hacdias** [comment]
@valentinvieriu Unfortunately I can't. Only @mholt knows. Let's wait for his answer.

**Comment by valentinvieriu** [comment]
@hacdias there was a new release and the fix it's not in. ( or at least the bug it's still happening )

**Comment by hacdias** [comment]
There was a new release of Caddy. The plugins weren't updated I think. Sorry for that. I think @mholt will make some changes in the build server soon related to the plugins and then I can deploy the fixed immediately.

If you want, you can tell me your OS and Architecture and the plugins you want and I'll build the binary for you with the newest things.

**Comment by valentinvieriu** [comment]
@hacdias no problem. I'm still playing with the setup of the system. The ability to save and rebuild the website it's not crucial right now, but will be in 1 month. I'll wait for the official release I just wanted to report the situation. Would be great to have quicker updates when comes to plugins.
Thank you
