### ISSUE TITLE
Download noneed auth

### ISSUE THREAD

**Issue by qrqhuang** [filebrowser/filebrowser#971]
**Describe the solution you'd like**
I'd like to index files for download for all anonymous users.  
But only logged user for `CUD`

**Describe alternatives you've considered**
no longer to login if download anonymous mode available.
But if you want to upload or rename file, login required.

**Additional context**
In this mode, can generate wget link.

**Comment by o1egl** [comment]
@qrqhuang please follow https://github.com/filebrowser/filebrowser/issues/973 discussion
