### ISSUE TITLE
edit model how to set

### ISSUE THREAD

**Issue by migouKang** [filebrowser/filebrowser#974]
File preview failed
The interface can get the content, but the page cannot be displayed

**Comment by o1egl** [comment]
@migouKang can you give more context on what exactly is happening and how to reproduce it?

**Comment by migouKang** [comment]
When I open my file, the contents of the file cannot be previewed,but,about the screenshot on the official website, the content can be previewed.

**Comment by stubbornrock** [comment]
I have the same issue，When I double click a file，Page does not display file content。but the http api return the file content（See the figure below）.I have set the file modification permission .  The official document website https://filebrowser.xyz/features has a display where users can Open and Edit my files。
![image](https://user-images.githubusercontent.com/7532609/83590247-e5a22c00-a587-11ea-8a63-2278e7b27d19.png)
![image](https://user-images.githubusercontent.com/7532609/83590331-184c2480-a588-11ea-90ec-06df3862268b.png)

Enviroment:
I deployed with docker, image tag is filebrowser/filebrowser:v2.1.0

**Comment by o1egl** [comment]
@stubbornrock I can't reproduce it. Do you see any errors in console tab? Try to use the latest release

**Comment by stubbornrock** [comment]
@o1egl When I updated docker image from v2.1.0 to latest ，resolved my issue, I can Open and Edit files now，thanks。
