### ISSUE TITLE
Feature request: Group Scope Management

### ISSUE THREAD

**Issue by fdefilippo** [filebrowser/filebrowser#975]
I wish there was an option to assign a scope to a group and then assign users to the group so that multiple users can see different scopes.

**Comment by sabatale** [comment]
That makes me think about this feature. How exactly does it work?

Initially I thought this is to allow administrators to set a scope of folders, but I couldn't find any documentation related to this:

![image](https://user-images.githubusercontent.com/50220345/84932150-d5b73b80-b0a1-11ea-99a5-d3cce5b67944.png)
