### ISSUE TITLE
Blinking previewer

### ISSUE THREAD

**Issue by minostauros** [filebrowser/filebrowser#976]
**Description**

When we click next button on the previewer, the next() function is called as
https://github.com/filebrowser/filebrowser/blob/34bdb8fcfcc947bedda0ec35eaf5b479ea6ad614/frontend/src/components/files/Preview.vue#L123-L125

**What is happening?**

The previewer window is reloaded every time we _keep move fastly to previous or next link_.
It causes blinking effect.
https://github.com/filebrowser/filebrowser/blob/6e54dff40dd458601669078a50c8b6f65b2481ac/frontend/src/css/styles.css#L109-L118

![blinking mov](https://user-images.githubusercontent.com/6764739/83622891-8cf48280-a5cb-11ea-8970-4b446f2aa6f1.gif)

**Expected behaviour**

The #previewer div must be loaded faster.

**Comment by o1egl** [comment]
Fixed in https://github.com/filebrowser/filebrowser/pull/993
