### ISSUE TITLE
Upload button doesn't work 

### ISSUE THREAD

**Issue by amsparko** [filebrowser/filebrowser#977]
**Description**
Tried to upload a file to a new folder I created using the filebrowser UI

**Expected behaviour**
File to be uploaded

**What is happening instead?**
Internal Server Error 500

**Additional context**
![Screen Shot 2020-06-04 at 10 31 22 AM](https://user-images.githubusercontent.com/33906880/83770100-a985ce80-a64e-11ea-93b9-dcfa70b82a4a.png)

**How to reproduce?**
Click the access URL on a project
Choose file browser
Make a new folder
Try to upload something to that folder using the upload button

**Comment by o1egl** [comment]
Do you see any errors in backend log?

**Comment by amsparko** [comment]
So sorry I thought I was submitting this bug to my local organization! I'm sure they just have a bug in how they implemented your code.
