### ISSUE TITLE
Can't access the server from outside the network

### ISSUE THREAD

**Issue by tkchouaki** [filebrowser/filebrowser#983]
Hello,
I'm trying to setup filebrowser to be able to access my files from outside my local network.
I first tried with the following command :

```bash
filebrowser -a 0.0.0.0 --port 80
```
The server starts successfully and i'm able to access it using both localhost & the local ip address (192.168....) on a different PC inside the same network.
But when trying with my public IP, it doesn't work. 

So then i tried to listen directly on my public IP

```bash
filebrowser -a <public_ip> --port 80
``` 
And i obtain the following message
2020/06/15 01:06:08 listen tcp <public_ip>:80: bind: cannot assign requested address

Of course i had configured my router to forward the port 80 to the host PC. I have no problem running other servers using it.

**Comment by o1egl** [comment]
@tkchouaki  looks like you you need to:
1. Verify that port 80 is free on the host machine
2. Allowed to use port 80 in your firewall

**Comment by tkchouaki** [comment]
Yes, my port 80 is free on the host PC and in the firewall.
I tested the same port 80 for another webserver and it works just fine using my external IP. Of course i stop that webserver before testing filebrowser.

**Comment by o1egl** [comment]
Can you try to use different port? 8080 for example?

**Comment by tkchouaki** [comment]
Same for another port (which i ensured was free and the port forwarding configured in my router)

**Comment by o1egl** [comment]
I'm not sure what exactly you are doing. It looks like you are trying to start filebrowser using an IP that is not available on this host. You can solve this problem by running filebrowser on the internal network and redirecting your public_ip:port to host_ip:port in your router config.

**Comment by nambrosch** [comment]
@tkchouaki Can you try another application, for example apache or ngnix to make sure your port forwarding is working properly?  Your issue probably isn't specific to filebrowser.

Could you try checking to see how the software is bound?  In linux you can run this:

```
netstat -plnt
```

**Comment by tkchouaki** [comment]
Thank you for all your anwsers, 
I already had tried another server (tomcat) in the same port and i noticed i had to open the port from my firewall. Then tomcat worked just fine.
But then i was trying filebrowser with this command: 

```bash
filebrowser -p 80
```
Because i thought it would serve on all adresses. But it didn't work until i did it like this

```bash
filebrowser -a 0.0.0.0 -p 80
```

**Comment by nambrosch** [comment]
I'm glad you got it worked out :)
