### ISSUE TITLE
Shell is not available

### ISSUE THREAD

**Issue by JIA-Jimmy** [filebrowser/filebrowser#986]
**Description**
use filebrowser 2.1.2 

Enter the command in the shell and nothing happened

`
>docker ps
>
`

**Expected behaviour**
What did you expect to happen?

Return container ID

**What is happening instead?**

***in shell***
Nothing happend in filebrowser shell

***in filebrowser log***
```
2020/06/17 01:35:16 /: 500 ip:port fork/exec : no such file or directory
2020/06/17 01:35:16 websocket: bad write message type
```

**Comment by o1egl** [comment]
How do you run filebrowser?

**Comment by JIA-Jimmy** [comment]
> How do you run filebrowser?
systemd

**Comment by o1egl** [comment]
Are you sure that you have `docker` command in the PATH? Can you try to run `ls` or `pwd`?

**Comment by JIA-Jimmy** [comment]
> Are you sure that you have `docker` command in the PATH? Can you try to run `ls` or `pwd`?

I'm sure i have docker command in the PATH and not only docker ,all command will not get return in the filebrowser shell.
Just something in log like this
```
2020/06/18 08:08:10 /: 500 IP:12135 fork/exec : no such file or directory
2020/06/18 08:08:10 websocket: bad write message type
```
But i found when you change the
Global Settings
User default settings Scope
and save,the shell will Back to normal
I don't know why this happens
And i find in filebrowser shell,linux tab autocomplete doesn't work
