### ISSUE TITLE
Support running a configurable command when an item is saved

### ISSUE THREAD

**Issue by ndarilek** [filebrowser/filebrowser#99]
I'm working on a Hugo app for [Sandstorm](https://sandstorm.io) that enables one-click deployment of Hugo sites. Currently the app exposes a Git repository and expects the user to push content, at which point the site is automatically rebuilt and published.

What I'd like to do is expose a web-based admin interface like this one. In order for this to work, I'd need to configure a command that gets run whenever content is edited. In the case of the Sandstorm app, this command would create a Git commit, which in turn would trigger a rebuild of the site. It isn't quite a Publish button, but it's close.

Thanks.

**Comment by hacdias** [comment]
Hey @ndarilek! That's a really good idea, to create some hooks before and after some actions. What if:

```
before_save
after_save
before_publish
after_publish
```

What do you think?

**Comment by ndarilek** [comment]
Thanks, sounds great! The only point I'd make is that there likely won't 
be a Publish option for Sandstorm since the site is published on save, 
so as long as I can disable the Publish button/functionality then we're 
good.

**Comment by hacdias** [comment]
Yes, the options I mentioned are meant to be general, not only for Sandstorm. But, are you using `caddy-hugo` publish button? If not, you could just use `filemanager` instead.

**Comment by ndarilek** [comment]
Oh, I guess I could do that, I wasn't sure if this plugin offered any 
functionality in addition to that. Perhaps I should file this issue 
against the filemanager?

**Comment by hacdias** [comment]
The only differences between `hugo` and `filemanager` is that the first can run the hugo commands, create files based on the archetypes, schedule and publish. `filemanager` doesn't have those options.

Anyway, I'll probably create this options on `filemanager`:

```
before_save
after_save
```

And these will be specific to `hugo` plugin:

```
before_publish
after_publish
```

After each of those directives/options you'll be able to put a command. And I'm thinking about creating a variable (probably `$file`) that we'll be replaced with the file path. It can be useful for some cases.

What do you think?

**Comment by ndarilek** [comment]
Sounds good. Thanks!

**Comment by hacdias** [comment]
You're welcome! I'll mark this as a todo. I'll do it when I can 😄

**Comment by hacdias** [comment]
@ndarilek hello! Do you think that the execution of the command should be non-blocking?

**Comment by hacdias** [comment]
I just made a few changes. Can you build it from source and try, please? 😄

**Comment by hacdias** [comment]
Closing since it's already done.

**Comment by ndarilek** [comment]
Thanks, my apologies, finally getting a look at this after the holidays.

Should this appear in the filemanager plugin as downloaded from the Caddy customizable download page? If so, then I'll try to integrate it into my Sandstorm package.

**Comment by hacdias** [comment]
It isn't available yet on caddyserver.com but I'll ping you as soon as it is. 

*Pinging @mholt*

**Comment by hacdias** [comment]
Updated @ndarilek on the server!
