### ISSUE TITLE
Text files with a lot of lines take really long to display

### ISSUE THREAD

**Issue by jpxd** [filebrowser/filebrowser#992]
**Description**
I uploaded a 1MB text-file which contains about 30000 short lines. When opening in the browser, the page freezes and it takes about 24 seconds until the file is displayed. I used the newest Google Chrome on a decent laptop.

**Expected behaviour**
The file should be opened and displayed in less time and the page should not freeze. Alternatively, there could just be a message, that large text files cannot be previewed in the browser and have to be downloaded.

**What is happening instead?**
The file takes about 24 seconds to display. Meanwhile the whole page freezes and is unresponsive. Chrome even killed the page once (err code: RESULT_CODE_HUNG)

**Additional context**
The long waiting delay does seem to correlate with the amount of lines and not with the file size. For comparison, a 1MB file with just 1000 lines just takes about 3 seconds. I did a chrome profiling session:  
<img width="1383" alt="Screenshot 2020-06-18 11 44 16" src="https://user-images.githubusercontent.com/10384363/85006865-fb544b80-b15a-11ea-87ce-7b8cd0eda5df.png">

Here is the chrome profile: [Profile-20200618T114046.json.zip](https://github.com/filebrowser/filebrowser/files/4797784/Profile-20200618T114046.json.zip)

**How to reproduce?**
Upload the test.txt file (see below). Open the file. It takes a long time.

**Files**
Test.txt: [test.txt.zip](https://github.com/filebrowser/filebrowser/files/4797812/test.txt.zip)

**Comment by o1egl** [comment]
@jpxd thank you for reporting. The problem is in the `ace` editor. It is constantly resizing. As a workaround I set `maxLines: 80`. This is not an ideal solution. I would prefer to set the dynamic size of the editor depending on the page size.
