### ISSUE TITLE
Delete your own files/folders permission

### ISSUE THREAD

**Issue by sabatale** [filebrowser/filebrowser#994]
**Feature**

**Is your feature request related to a problem? Please describe.**
Administrators have no option to allow users to delete only their own files/folders (the ones they have created).

**Describe the solution you'd like**
Additional users permission "Delete only user's own files and folders".

**Comment by o1egl** [comment]
You can change the scope of the user to give him/her access only to a specific folder.

**Comment by sabatale** [comment]
The idea is actually to allow users to delete their own files/folders but not the ones that are available to them "by default".

**Comment by o1egl** [comment]
The idea is to keep the app as simple as possible. Adding folder/file level permissions model will be too complicated and is out of the scope of this project
